JUCE: Atomic< Type > Class Template Reference
Atomic< Type > Class Template Reference final
memory
Simple class to hold a primitive value and perform atomic operations on it.
Public Types
typedef AtomicBase< Type >
::DiffType DiffType
Resulting type when subtracting the underlying Type.
Public Types inherited from AtomicBase< Type >
typedef
AtomicHelpers::DiffTypeHelper
< Type >::Type DiffType
Public Member Functions
Atomic () noexcept
Creates a new value, initialised to zero.
Atomic (const Type initialValue) noexcept
Creates a new value, with a given initial value.
Atomic (const Atomic &other) noexcept
Copies another value (atomically).
~Atomic () noexcept
Destructor.
Type get () const noexcept
Atomically reads and returns the current value.
Atomic & operator= (const Atomic &other) noexcept
Copies another value into this one (atomically).
Atomic & operator= (const Type newValue) noexcept
Copies another value into this one (atomically).
void set (Type newValue) noexcept
Atomically sets the current value.
Type exchange (Type v) noexcept
Atomically sets the current value, returning the value that was replaced.
Type operator+= (DiffType amountToAdd) noexcept
Atomically adds a number to this value, returning the new value.
Type operator-= (DiffType amountToSubtract) noexcept
Atomically subtracts a number from this value, returning the new value.
Type operator++ () noexcept
Atomically increments this value, returning the new value.
Type operator-- () noexcept
Atomically decrements this value, returning the new value.
bool compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
Type compareAndSetValue (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
Public Member Functions inherited from AtomicBase< Type >
AtomicBase () noexcept
AtomicBase (const Type v) noexcept
AtomicBase (const AtomicBase &other) noexcept
Type get () const noexcept
AtomicBase & operator= (const AtomicBase< Type > &other) noexcept
AtomicBase & operator= (const Type newValue) noexcept
void set (Type newValue) noexcept
Type exchange (Type) noexcept
bool compareAndSetBool (Type, Type) noexcept
Type compareAndSetValue (Type, Type) noexcept
Static Public Member Functions
static void memoryBarrier () noexcept
Implements a memory read/write barrier.
Static Public Member Functions inherited from AtomicBase< Type >
static void memoryBarrier () noexcept
Additional Inherited Members
Public Attributes inherited from AtomicBase< Type >
volatile Type value
The raw value that this class operates on.
Protected Member Functions inherited from AtomicBase< Type >
Type operator++ (int)
Type operator-- (int)
template<typename ValueType >
ValueType negateValue (ValueType n) noexcept
This templated negate function will negate pointers as well as integers.
template<typename PointerType >
PointerType * negateValue (PointerType *n) noexcept
This templated negate function will negate pointers as well as integers.
Static Protected Member Functions inherited from AtomicBase< Type >
template<typename Dest , typename Source >
static Dest castTo (Source value) noexcept
static Type castFrom32Bit (int32 value) noexcept
static Type castFrom64Bit (int64 value) noexcept
static int32 castTo32Bit (Type value) noexcept
static int64 castTo64Bit (Type value) noexcept
Detailed Description
template<typename Type>
class Atomic< Type >
Simple class to hold a primitive value and perform atomic operations on it.
The type used must be a 32 or 64 bit primitive, like an int, pointer, etc. There are methods to perform most of the basic atomic operations.
Member Typedef Documentation
template<typename Type> typedef AtomicBase<Type>::DiffType Atomic< Type >::DiffType
Resulting type when subtracting the underlying Type.
Constructor & Destructor Documentation
template<typename Type> Atomic< Type >::Atomic () noexcept
Creates a new value, initialised to zero.
template<typename Type> Atomic< Type >::Atomic (const Type initialValue) explicit noexcept
Creates a new value, with a given initial value.
template<typename Type> Atomic< Type >::Atomic (const Atomic< Type > & other) noexcept
Copies another value (atomically).
template<typename Type> Atomic< Type >::~Atomic () noexcept
Destructor.
Member Function Documentation
template<typename Type> Type Atomic< Type >::get () const noexcept
Atomically reads and returns the current value.
Referenced by ThreadLocalValue< Type >::get(), ThreadLocalValue< Type >::releaseCurrentThreadStorage(), and ThreadLocalValue< Type >::~ThreadLocalValue().
template<typename Type> Atomic& Atomic< Type >::operator= (const Atomic< Type > & other) noexcept
Copies another value into this one (atomically).
template<typename Type> Atomic& Atomic< Type >::operator= (const Type newValue) noexcept
Copies another value into this one (atomically).
template<typename Type> void Atomic< Type >::set (Type newValue) noexcept
Atomically sets the current value.
template<typename Type> Type Atomic< Type >::exchange (Type v) noexcept
Atomically sets the current value, returning the value that was replaced.
Referenced by Atomic< Thread::ThreadID >::set(), and Atomic< void * >::set().
template<typename Type> bool Atomic< Type >::compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
bool compareAndSetBool (Type newValue, Type valueToCompare)
{
    if (get() == valueToCompare)
    {
        set (newValue);
        return true;
    }
    return false;
}
Returns
true if the comparison was true and the value was replaced; false if the comparison failed and the value was left unchanged.
See Also
compareAndSetValue
Referenced by ThreadLocalValue< Type >::get().
template<typename Type> Type Atomic< Type >::compareAndSetValue (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
Type compareAndSetValue (Type newValue, Type valueToCompare)
{
    Type oldValue = get();
    if (oldValue == valueToCompare)
        set (newValue);
    return oldValue;
}
Returns
the old value before it was changed.
See Also
compareAndSetBool
template<typename Type> static void Atomic< Type >::memoryBarrier () static noexcept
Implements a memory read/write barrier.
The documentation for this class was generated from the following file:
juce_Atomic.h