JUCE: juce::BorderSize< ValueType > Class Template Reference
juce::BorderSize< ValueType > Class Template Reference
geometry
Specifies a set of gaps to be left around the sides of a rectangle.
Public Member Functions
BorderSize () noexcept
Creates a null border.
BorderSize (const BorderSize &other) noexcept
Creates a copy of another border.
BorderSize (ValueType topGap, ValueType leftGap, ValueType bottomGap, ValueType rightGap) noexcept
Creates a border with the given gaps.
BorderSize (ValueType allGaps) noexcept
Creates a border with the given gap on all sides.
ValueType getTop () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getLeft () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getBottom () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getRight () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getTopAndBottom () const noexcept
Returns the sum of the top and bottom gaps.
ValueType getLeftAndRight () const noexcept
Returns the sum of the left and right gaps.
bool isEmpty () const noexcept
Returns true if this border has no thickness along any edge.
void setTop (ValueType newTopGap) noexcept
Changes the top gap.
void setLeft (ValueType newLeftGap) noexcept
Changes the left gap.
void setBottom (ValueType newBottomGap) noexcept
Changes the bottom gap.
void setRight (ValueType newRightGap) noexcept
Changes the right gap.
Rectangle< ValueType > subtractedFrom (const Rectangle< ValueType > &original) const noexcept
Returns a rectangle with these borders removed from it.
void subtractFrom (Rectangle< ValueType > &rectangle) const noexcept
Removes this border from a given rectangle.
Rectangle< ValueType > addedTo (const Rectangle< ValueType > &original) const noexcept
Returns a rectangle with these borders added around it.
void addTo (Rectangle< ValueType > &rectangle) const noexcept
Adds this border around a given rectangle.
bool operator== (const BorderSize &other) const noexcept
bool operator!= (const BorderSize &other) const noexcept
Detailed Description
template<typename ValueType>
class juce::BorderSize< ValueType >
Specifies a set of gaps to be left around the sides of a rectangle.
This is basically the size of the spaces at the top, bottom, left and right of a rectangle. It's used by various component classes to specify borders.
See Also
Rectangle
Constructor & Destructor Documentation
template<typename ValueType> juce::BorderSize< ValueType >::BorderSize () noexcept
Creates a null border.
All sizes are left as 0.
template<typename ValueType> juce::BorderSize< ValueType >::BorderSize (const BorderSize< ValueType > & other) noexcept
Creates a copy of another border.
template<typename ValueType> juce::BorderSize< ValueType >::BorderSize (ValueType topGap, ValueType leftGap, ValueType bottomGap, ValueType rightGap) noexcept
Creates a border with the given gaps.
template<typename ValueType> juce::BorderSize< ValueType >::BorderSize (ValueType allGaps) explicit noexcept
Creates a border with the given gap on all sides.
Member Function Documentation
template<typename ValueType> ValueType juce::BorderSize< ValueType >::getTop () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType juce::BorderSize< ValueType >::getLeft () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType juce::BorderSize< ValueType >::getBottom () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType juce::BorderSize< ValueType >::getRight () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType juce::BorderSize< ValueType >::getTopAndBottom () const noexcept
Returns the sum of the top and bottom gaps.
template<typename ValueType> ValueType juce::BorderSize< ValueType >::getLeftAndRight () const noexcept
Returns the sum of the left and right gaps.
template<typename ValueType> bool juce::BorderSize< ValueType >::isEmpty () const noexcept
Returns true if this border has no thickness along any edge.
template<typename ValueType> void juce::BorderSize< ValueType >::setTop (ValueType newTopGap) noexcept
Changes the top gap.
template<typename ValueType> void juce::BorderSize< ValueType >::setLeft (ValueType newLeftGap) noexcept
Changes the left gap.
template<typename ValueType> void juce::BorderSize< ValueType >::setBottom (ValueType newBottomGap) noexcept
Changes the bottom gap.
template<typename ValueType> void juce::BorderSize< ValueType >::setRight (ValueType newRightGap) noexcept
Changes the right gap.
template<typename ValueType> Rectangle<ValueType> juce::BorderSize< ValueType >::subtractedFrom (const Rectangle< ValueType > & original) const noexcept
Returns a rectangle with these borders removed from it.
Referenced by juce::BorderSize< int >::subtractFrom().
template<typename ValueType> void juce::BorderSize< ValueType >::subtractFrom (Rectangle< ValueType > & rectangle) const noexcept
Removes this border from a given rectangle.
template<typename ValueType> Rectangle<ValueType> juce::BorderSize< ValueType >::addedTo (const Rectangle< ValueType > & original) const noexcept
Returns a rectangle with these borders added around it.
Referenced by juce::BorderSize< int >::addTo().
template<typename ValueType> void juce::BorderSize< ValueType >::addTo (Rectangle< ValueType > & rectangle) const noexcept
Adds this border around a given rectangle.
template<typename ValueType> bool juce::BorderSize< ValueType >::operator== (const BorderSize< ValueType > & other) const noexcept
Referenced by juce::BorderSize< int >::operator!=().
template<typename ValueType> bool juce::BorderSize< ValueType >::operator!= (const BorderSize< ValueType > & other) const noexcept
The documentation for this class was generated from the following file:
juce_BorderSize.h