JUCE: FakeMouseMoveGenerator Class Reference
FakeMouseMoveGenerator Class Reference
utility
Public Member Functions
FakeMouseMoveGenerator ()
void timerCallback () override
The user-defined callback routine that actually gets called periodically.
Constructor & Destructor Documentation
FakeMouseMoveGenerator::FakeMouseMoveGenerator ()
References Timer::startTimer().
Member Function Documentation
void FakeMouseMoveGenerator::timerCallback () override virtual
The user-defined callback routine that actually gets called periodically.
It's perfectly ok to call startTimer() or stopTimer() from within this callback to change the subsequent intervals.
Implements Timer.
References Time::currentTimeMillis(), Desktop::findComponentAt(), ModifierKeys::getCurrentModifiers(), Desktop::getInstance(), Desktop::getMainMouseSource(), Component::getPeer(), MouseInputSource::getScreenPosition(), MouseInputSource::invalidOrientation, and MouseInputSource::invalidPressure.
The documentation for this class was generated from the following file:
juce_FakeMouseMoveGenerator.h