JUCE: Atomic< void * > Class Template Reference
Atomic< void * > Class Template Reference
memory
Public Member Functions
Atomic () noexcept
Atomic (void *const initialValue) noexcept
Atomic (const Atomic< void * > &other) noexcept
void * get () const noexcept
Atomic & operator= (const Atomic &other) noexcept
Atomic & operator= (void *const newValue) noexcept
void set (void *newValue) noexcept
void * exchange (void *v) noexcept
bool compareAndSetBool (void *newValue, void *valueToCompare) noexcept
void * compareAndSetValue (void *newValue, void *valueToCompare) noexcept
Public Member Functions inherited from AtomicBase< void * >
AtomicBase () noexcept
AtomicBase (const void *v) noexcept
AtomicBase (const AtomicBase &other) noexcept
void * get () const noexcept
AtomicBase & operator= (const AtomicBase< void * > &other) noexcept
AtomicBase & operator= (const void *newValue) noexcept
void set (void *newValue) noexcept
void * exchange (void *) noexcept
bool compareAndSetBool (void *, void *) noexcept
void * compareAndSetValue (void *, void *) noexcept
Static Public Member Functions
static void memoryBarrier () noexcept
Static Public Member Functions inherited from AtomicBase< void * >
static void memoryBarrier () noexcept
Additional Inherited Members
Public Types inherited from AtomicBase< void * >
typedef
AtomicHelpers::DiffTypeHelper
< void * >::void * DiffType
Public Attributes inherited from AtomicBase< void * >
volatile void * value
The raw value that this class operates on.
Protected Member Functions inherited from AtomicBase< void * >
void * operator++ (int)
void * operator-- (int)
ValueType negateValue (ValueType n) noexcept
This templated negate function will negate pointers as well as integers.
PointerType * negateValue (PointerType *n) noexcept
This templated negate function will negate pointers as well as integers.
Static Protected Member Functions inherited from AtomicBase< void * >
static Dest castTo (Source value) noexcept
static void * castFrom32Bit (int32 value) noexcept
static void * castFrom64Bit (int64 value) noexcept
static int32 castTo32Bit (void *value) noexcept
static int64 castTo64Bit (void *value) noexcept
Constructor & Destructor Documentation
Atomic< void * >::Atomic () noexcept
Atomic< void * >::Atomic (void *const initialValue) explicit noexcept
Atomic< void * >::Atomic (const Atomic< void * > & other) noexcept
Member Function Documentation
void* Atomic< void * >::get () const noexcept
References AtomicBase< Type >::get().
Atomic& Atomic< void * >::operator= (const Atomic< void * > & other) noexcept
References AtomicBase< Type >::operator=().
Atomic& Atomic< void * >::operator= (void *const newValue) noexcept
References AtomicBase< Type >::operator=().
void Atomic< void * >::set (void * newValue) noexcept
References Atomic< Type >::exchange().
void* Atomic< void * >::exchange (void * v) noexcept
References AtomicBase< Type >::exchange().
bool Atomic< void * >::compareAndSetBool (void * newValue, void * valueToCompare) noexcept
References AtomicBase< Type >::compareAndSetBool().
void* Atomic< void * >::compareAndSetValue (void * newValue, void * valueToCompare) noexcept
References AtomicBase< Type >::compareAndSetValue().
static void Atomic< void * >::memoryBarrier () static noexcept
References AtomicBase< Type >::memoryBarrier().
The documentation for this class was generated from the following file:
juce_Atomic.h