JUCE: juce::Reverb Class Reference
juce::Reverb Class Reference
effects
Performs a simple reverb effect on a stream of audio data.
Classes
struct Parameters
Holds the parameters being used by a Reverb object.
Public Member Functions
Reverb ()
const Parameters & getParameters () const noexcept
Returns the reverb's current parameters.
void setParameters (const Parameters &newParams)
Applies a new set of parameters to the reverb.
void setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
void reset ()
Clears the reverb's buffers.
void processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
void processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
Detailed Description
Performs a simple reverb effect on a stream of audio data.
This is a simple stereo reverb, based on the technique and tunings used in FreeVerb. Use setSampleRate() to prepare it, and then call processStereo() or processMono() to apply the reverb to your audio data.
See Also
ReverbAudioSource
Constructor & Destructor Documentation
juce::Reverb::Reverb ()
References setParameters(), and setSampleRate().
Member Function Documentation
const Parameters& juce::Reverb::getParameters () const noexcept
Returns the reverb's current parameters.
void juce::Reverb::setParameters (const Parameters & newParams)
Applies a new set of parameters to the reverb.
Note that this doesn't attempt to lock the reverb, so if you call this in parallel with the process method, you may get artifacts.
References juce::Reverb::Parameters::dryLevel, juce::Reverb::Parameters::freezeMode, juce::LinearSmoothedValue< FloatType >::setValue(), juce::Reverb::Parameters::wetLevel, and juce::Reverb::Parameters::width.
Referenced by Reverb().
void juce::Reverb::setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
You must call this before the process methods, in order to tell it the correct sample rate.
References jassert, and juce::LinearSmoothedValue< FloatType >::reset().
Referenced by Reverb().
void juce::Reverb::reset ()
Clears the reverb's buffers.
void juce::Reverb::processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
References juce::LinearSmoothedValue< FloatType >::getNextValue(), and jassert.
void juce::Reverb::processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
References juce::LinearSmoothedValue< FloatType >::getNextValue(), and jassert.
The documentation for this class was generated from the following file:
juce_Reverb.h