JUCE: juce::FloatVectorOperations Class Reference
juce::FloatVectorOperations Class Reference
buffers
A collection of simple vector operations on arrays of floats, accelerated with SIMD instructions where possible.
Static Public Member Functions
static void JUCE_CALLTYPE clear (float *dest, int numValues) noexcept
Clears a vector of floats.
static void JUCE_CALLTYPE clear (double *dest, int numValues) noexcept
Clears a vector of doubles.
static void JUCE_CALLTYPE fill (float *dest, float valueToFill, int numValues) noexcept
Copies a repeated value into a vector of floats.
static void JUCE_CALLTYPE fill (double *dest, double valueToFill, int numValues) noexcept
Copies a repeated value into a vector of doubles.
static void JUCE_CALLTYPE copy (float *dest, const float *src, int numValues) noexcept
Copies a vector of floats.
static void JUCE_CALLTYPE copy (double *dest, const double *src, int numValues) noexcept
Copies a vector of doubles.
static void JUCE_CALLTYPE copyWithMultiply (float *dest, const float *src, float multiplier, int numValues) noexcept
Copies a vector of floats, multiplying each value by a given multiplier.
static void JUCE_CALLTYPE copyWithMultiply (double *dest, const double *src, double multiplier, int numValues) noexcept
Copies a vector of doubles, multiplying each value by a given multiplier.
static void JUCE_CALLTYPE add (float *dest, float amountToAdd, int numValues) noexcept
Adds a fixed value to the destination values.
static void JUCE_CALLTYPE add (double *dest, double amountToAdd, int numValues) noexcept
Adds a fixed value to the destination values.
static void JUCE_CALLTYPE add (float *dest, const float *src, float amount, int numValues) noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE add (double *dest, const double *src, double amount, int numValues) noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE add (float *dest, const float *src, int numValues) noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE add (double *dest, const double *src, int numValues) noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE add (float *dest, const float *src1, const float *src2, int num) noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE add (double *dest, const double *src1, const double *src2, int num) noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE subtract (float *dest, const float *src, int numValues) noexcept
Subtracts the source values from the destination values.
static void JUCE_CALLTYPE subtract (double *dest, const double *src, int numValues) noexcept
Subtracts the source values from the destination values.
static void JUCE_CALLTYPE subtract (float *dest, const float *src1, const float *src2, int num) noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE subtract (double *dest, const double *src1, const double *src2, int num) noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE addWithMultiply (float *dest, const float *src, float multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
static void JUCE_CALLTYPE addWithMultiply (double *dest, const double *src, double multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
static void JUCE_CALLTYPE addWithMultiply (float *dest, const float *src1, const float *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE addWithMultiply (double *dest, const double *src1, const double *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (float *dest, const float *src, float multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (double *dest, const double *src, double multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (float *dest, const float *src1, const float *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (double *dest, const double *src1, const double *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE multiply (float *dest, const float *src, int numValues) noexcept
Multiplies the destination values by the source values.
static void JUCE_CALLTYPE multiply (double *dest, const double *src, int numValues) noexcept
Multiplies the destination values by the source values.
static void JUCE_CALLTYPE multiply (float *dest, const float *src1, const float *src2, int numValues) noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE multiply (double *dest, const double *src1, const double *src2, int numValues) noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE multiply (float *dest, float multiplier, int numValues) noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE multiply (double *dest, double multiplier, int numValues) noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE multiply (float *dest, const float *src, float multiplier, int num) noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE multiply (double *dest, const double *src, double multiplier, int num) noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE negate (float *dest, const float *src, int numValues) noexcept
Copies a source vector to a destination, negating each value.
static void JUCE_CALLTYPE negate (double *dest, const double *src, int numValues) noexcept
Copies a source vector to a destination, negating each value.
static void JUCE_CALLTYPE abs (float *dest, const float *src, int numValues) noexcept
Copies a source vector to a destination, taking the absolute of each value.
static void JUCE_CALLTYPE abs (double *dest, const double *src, int numValues) noexcept
Copies a source vector to a destination, taking the absolute of each value.
static void JUCE_CALLTYPE convertFixedToFloat (float *dest, const int *src, float multiplier, int numValues) noexcept
Converts a stream of integers to floats, multiplying each one by the given multiplier.
static void JUCE_CALLTYPE min (float *dest, const float *src, float comp, int num) noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE min (double *dest, const double *src, double comp, int num) noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE min (float *dest, const float *src1, const float *src2, int num) noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE min (double *dest, const double *src1, const double *src2, int num) noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE max (float *dest, const float *src, float comp, int num) noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE max (double *dest, const double *src, double comp, int num) noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE max (float *dest, const float *src1, const float *src2, int num) noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE max (double *dest, const double *src1, const double *src2, int num) noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE clip (float *dest, const float *src, float low, float high, int num) noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static void JUCE_CALLTYPE clip (double *dest, const double *src, double low, double high, int num) noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static Range< float > JUCE_CALLTYPE findMinAndMax (const float *src, int numValues) noexcept
Finds the miniumum and maximum values in the given array.
static Range< double >
JUCE_CALLTYPE findMinAndMax (const double *src, int numValues) noexcept
Finds the miniumum and maximum values in the given array.
static float JUCE_CALLTYPE findMinimum (const float *src, int numValues) noexcept
Finds the miniumum value in the given array.
static double JUCE_CALLTYPE findMinimum (const double *src, int numValues) noexcept
Finds the miniumum value in the given array.
static float JUCE_CALLTYPE findMaximum (const float *src, int numValues) noexcept
Finds the maximum value in the given array.
static double JUCE_CALLTYPE findMaximum (const double *src, int numValues) noexcept
Finds the maximum value in the given array.
static void JUCE_CALLTYPE enableFlushToZeroMode (bool shouldEnable) noexcept
On Intel CPUs, this method enables or disables the SSE flush-to-zero mode.
static void JUCE_CALLTYPE disableDenormalisedNumberSupport () noexcept
On Intel CPUs, this method enables the SSE flush-to-zero and denormalised-are-zero modes.
Detailed Description
A collection of simple vector operations on arrays of floats, accelerated with SIMD instructions where possible.
Member Function Documentation
static void JUCE_CALLTYPE juce::FloatVectorOperations::clear (float * dest, int numValues) static noexcept
Clears a vector of floats.
Referenced by juce::AudioBuffer< float >::applyGain(), juce::dsp::AudioBlock< float >::clear(), juce::AudioBuffer< float >::clear(), and juce::AudioBuffer< float >::copyFrom().
static void JUCE_CALLTYPE juce::FloatVectorOperations::clear (double * dest, int numValues) static noexcept
Clears a vector of doubles.
static void JUCE_CALLTYPE juce::FloatVectorOperations::fill (float * dest, float valueToFill, int numValues) static noexcept
Copies a repeated value into a vector of floats.
Referenced by juce::dsp::AudioBlock< float >::fill().
static void JUCE_CALLTYPE juce::FloatVectorOperations::fill (double * dest, double valueToFill, int numValues) static noexcept
Copies a repeated value into a vector of doubles.
static void JUCE_CALLTYPE juce::FloatVectorOperations::copy (float * dest, const float * src, int numValues) static noexcept
Copies a vector of floats.
Referenced by juce::AudioBuffer< float >::addFrom(), juce::AudioBuffer< float >::AudioBuffer(), juce::dsp::AudioBlock< float >::copy(), juce::AudioBuffer< float >::copyFrom(), juce::AudioBuffer< float >::operator=(), and juce::AudioBuffer< float >::setSize().
static void JUCE_CALLTYPE juce::FloatVectorOperations::copy (double * dest, const double * src, int numValues) static noexcept
Copies a vector of doubles.
static void JUCE_CALLTYPE juce::FloatVectorOperations::copyWithMultiply (float * dest, const float * src, float multiplier, int numValues) static noexcept
Copies a vector of floats, multiplying each value by a given multiplier.
Referenced by juce::AudioBuffer< float >::addFrom(), and juce::AudioBuffer< float >::copyFrom().
static void JUCE_CALLTYPE juce::FloatVectorOperations::copyWithMultiply (double * dest, const double * src, double multiplier, int numValues) static noexcept
Copies a vector of doubles, multiplying each value by a given multiplier.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (float * dest, float amountToAdd, int numValues) static noexcept
Adds a fixed value to the destination values.
Referenced by juce::dsp::AudioBlock< float >::add(), juce::AudioBuffer< float >::addFrom(), and juce::dsp::Bias< FloatType >::process().
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (double * dest, double amountToAdd, int numValues) static noexcept
Adds a fixed value to the destination values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (float * dest, const float * src, float amount, int numValues) static noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (double * dest, const double * src, double amount, int numValues) static noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (float * dest, const float * src, int numValues) static noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (double * dest, const double * src, int numValues) static noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (float * dest, const float * src1, const float * src2, int num) static noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::add (double * dest, const double * src1, const double * src2, int num) static noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtract (float * dest, const float * src, int numValues) static noexcept
Subtracts the source values from the destination values.
Referenced by juce::dsp::AudioBlock< float >::subtract().
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtract (double * dest, const double * src, int numValues) static noexcept
Subtracts the source values from the destination values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtract (float * dest, const float * src1, const float * src2, int num) static noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtract (double * dest, const double * src1, const double * src2, int num) static noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::addWithMultiply (float * dest, const float * src, float multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
Referenced by juce::AudioBuffer< float >::addFrom(), and juce::dsp::AudioBlock< float >::addWithMultiply().
static void JUCE_CALLTYPE juce::FloatVectorOperations::addWithMultiply (double * dest, const double * src, double multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::addWithMultiply (float * dest, const float * src1, const float * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::addWithMultiply (double * dest, const double * src1, const double * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtractWithMultiply (float * dest, const float * src, float multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtractWithMultiply (double * dest, const double * src, double multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtractWithMultiply (float * dest, const float * src1, const float * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::subtractWithMultiply (double * dest, const double * src1, const double * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (float * dest, const float * src, int numValues) static noexcept
Multiplies the destination values by the source values.
Referenced by juce::LinearSmoothedValue< NumericType >::applyGain(), juce::AudioBuffer< float >::applyGain(), juce::dsp::AudioBlock< float >::multiply(), and juce::dsp::Gain< FloatType >::process().
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (double * dest, const double * src, int numValues) static noexcept
Multiplies the destination values by the source values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (float * dest, const float * src1, const float * src2, int numValues) static noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (double * dest, const double * src1, const double * src2, int numValues) static noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (float * dest, float multiplier, int numValues) static noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (double * dest, double multiplier, int numValues) static noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (float * dest, const float * src, float multiplier, int num) static noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::multiply (double * dest, const double * src, double multiplier, int num) static noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::negate (float * dest, const float * src, int numValues) static noexcept
Copies a source vector to a destination, negating each value.
Referenced by juce::dsp::AudioBlock< float >::replaceWithNegativeOf().
static void JUCE_CALLTYPE juce::FloatVectorOperations::negate (double * dest, const double * src, int numValues) static noexcept
Copies a source vector to a destination, negating each value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::abs (float * dest, const float * src, int numValues) static noexcept
Copies a source vector to a destination, taking the absolute of each value.
Referenced by juce::dsp::AudioBlock< float >::replaceWithAbsoluteValueOf().
static void JUCE_CALLTYPE juce::FloatVectorOperations::abs (double * dest, const double * src, int numValues) static noexcept
Copies a source vector to a destination, taking the absolute of each value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::convertFixedToFloat (float * dest, const int * src, float multiplier, int numValues) static noexcept
Converts a stream of integers to floats, multiplying each one by the given multiplier.
static void JUCE_CALLTYPE juce::FloatVectorOperations::min (float * dest, const float * src, float comp, int num) static noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
Referenced by juce::dsp::AudioBlock< float >::min().
static void JUCE_CALLTYPE juce::FloatVectorOperations::min (double * dest, const double * src, double comp, int num) static noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::min (float * dest, const float * src1, const float * src2, int num) static noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::min (double * dest, const double * src1, const double * src2, int num) static noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::max (float * dest, const float * src, float comp, int num) static noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
Referenced by juce::dsp::AudioBlock< float >::max().
static void JUCE_CALLTYPE juce::FloatVectorOperations::max (double * dest, const double * src, double comp, int num) static noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE juce::FloatVectorOperations::max (float * dest, const float * src1, const float * src2, int num) static noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::max (double * dest, const double * src1, const double * src2, int num) static noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE juce::FloatVectorOperations::clip (float * dest, const float * src, float low, float high, int num) static noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static void JUCE_CALLTYPE juce::FloatVectorOperations::clip (double * dest, const double * src, double low, double high, int num) static noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static Range<float> JUCE_CALLTYPE juce::FloatVectorOperations::findMinAndMax (const float * src, int numValues) static noexcept
Finds the miniumum and maximum values in the given array.
Referenced by juce::dsp::AudioBlock< float >::findMinAndMax(), and juce::AudioBuffer< float >::findMinMax().
static Range<double> JUCE_CALLTYPE juce::FloatVectorOperations::findMinAndMax (const double * src, int numValues) static noexcept
Finds the miniumum and maximum values in the given array.
static float JUCE_CALLTYPE juce::FloatVectorOperations::findMinimum (const float * src, int numValues) static noexcept
Finds the miniumum value in the given array.
static double JUCE_CALLTYPE juce::FloatVectorOperations::findMinimum (const double * src, int numValues) static noexcept
Finds the miniumum value in the given array.
static float JUCE_CALLTYPE juce::FloatVectorOperations::findMaximum (const float * src, int numValues) static noexcept
Finds the maximum value in the given array.
static double JUCE_CALLTYPE juce::FloatVectorOperations::findMaximum (const double * src, int numValues) static noexcept
Finds the maximum value in the given array.
static void JUCE_CALLTYPE juce::FloatVectorOperations::enableFlushToZeroMode (bool shouldEnable) static noexcept
On Intel CPUs, this method enables or disables the SSE flush-to-zero mode.
Effectively, this is a wrapper around a call to _MM_SET_FLUSH_ZERO_MODE
static void JUCE_CALLTYPE juce::FloatVectorOperations::disableDenormalisedNumberSupport () static noexcept
On Intel CPUs, this method enables the SSE flush-to-zero and denormalised-are-zero modes.
This effectively sets the DAZ and FZ bits of the MXCSR register. It's a convenient thing to call before audio processing code where you really want to avoid denormalisation performance hits.
The documentation for this class was generated from the following file:
juce_FloatVectorOperations.h