JUCE: juce::Colour Class Reference
juce::Colour Class Reference
colour
Represents a colour, also including a transparency value.
Public Member Functions
Colour () noexcept
Creates a transparent black colour.
Colour (const Colour &other) noexcept
Creates a copy of another Colour object.
Colour (uint32 argb) noexcept
Creates a colour from a 32-bit ARGB value.
Colour (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
Colour (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
Colour (uint8 red, uint8 green, uint8 blue, float alpha) noexcept
Creates a colour from 8-bit red, green, and blue values, and a floating-point alpha.
Colour (float hue, float saturation, float brightness, uint8 alpha) noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
Colour (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using floating point hue, saturation, brightness and alpha values.
Colour (PixelARGB argb) noexcept
Creates a colour using a PixelARGB object.
Colour (PixelRGB rgb) noexcept
Creates a colour using a PixelRGB object.
Colour (PixelAlpha alpha) noexcept
Creates a colour using a PixelAlpha object.
~Colour () noexcept
Destructor.
Colour & operator= (const Colour &other) noexcept
Copies another Colour object.
bool operator== (const Colour &other) const noexcept
Compares two colours.
bool operator!= (const Colour &other) const noexcept
Compares two colours.
uint8 getRed () const noexcept
Returns the red component of this colour.
uint8 getGreen () const noexcept
Returns the green component of this colour.
uint8 getBlue () const noexcept
Returns the blue component of this colour.
float getFloatRed () const noexcept
Returns the red component of this colour as a floating point value.
float getFloatGreen () const noexcept
Returns the green component of this colour as a floating point value.
float getFloatBlue () const noexcept
Returns the blue component of this colour as a floating point value.
const PixelARGB getPixelARGB () const noexcept
Returns a premultiplied ARGB pixel object that represents this colour.
uint32 getARGB () const noexcept
Returns a 32-bit integer that represents this colour.
uint8 getAlpha () const noexcept
Returns the colour's alpha (opacity).
float getFloatAlpha () const noexcept
Returns the colour's alpha (opacity) as a floating point value.
bool isOpaque () const noexcept
Returns true if this colour is completely opaque.
bool isTransparent () const noexcept
Returns true if this colour is completely transparent.
Colour withAlpha (uint8 newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour withAlpha (float newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour withMultipliedAlpha (float alphaMultiplier) const noexcept
Returns a colour that's the same colour as this one, but with a modified alpha value.
Colour overlaidWith (Colour foregroundColour) const noexcept
Returns a colour that is the result of alpha-compositing a new colour over this one.
Colour interpolatedWith (Colour other, float proportionOfOther) const noexcept
Returns a colour that lies somewhere between this one and another.
float getHue () const noexcept
Returns the colour's hue component.
float getSaturation () const noexcept
Returns the colour's saturation component.
float getBrightness () const noexcept
Returns the colour's brightness component.
float getPerceivedBrightness () const noexcept
Returns a skewed brightness value, adjusted to better reflect the way the human eye responds to different colour channels.
void getHSB (float &hue, float &saturation, float &brightness) const noexcept
Returns the colour's hue, saturation and brightness components all at once.
Colour withHue (float newHue) const noexcept
Returns a copy of this colour with a different hue.
Colour withSaturation (float newSaturation) const noexcept
Returns a copy of this colour with a different saturation.
Colour withBrightness (float newBrightness) const noexcept
Returns a copy of this colour with a different brightness.
Colour withRotatedHue (float amountToRotate) const noexcept
Returns a copy of this colour with it hue rotated.
Colour withMultipliedSaturation (float multiplier) const noexcept
Returns a copy of this colour with its saturation multiplied by the given value.
Colour withMultipliedBrightness (float amount) const noexcept
Returns a copy of this colour with its brightness multiplied by the given value.
Colour brighter (float amountBrighter=0.4f) const noexcept
Returns a brighter version of this colour.
Colour darker (float amountDarker=0.4f) const noexcept
Returns a darker version of this colour.
Colour contrasting (float amount=1.0f) const noexcept
Returns a colour that will be clearly visible against this colour.
Colour contrasting (Colour targetColour, float minLuminosityDiff) const noexcept
Returns a colour that is as close as possible to a target colour whilst still being in contrast to this one.
String toString () const
Returns a stringified version of this colour.
String toDisplayString (bool includeAlphaValue) const
Returns the colour as a hex string in the form RRGGBB or AARRGGBB.
Static Public Member Functions
static Colour fromRGB (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
static Colour fromRGBA (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
static Colour fromFloatRGBA (float red, float green, float blue, float alpha) noexcept
Creates a colour using floating point red, green, blue and alpha values.
static Colour fromHSV (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
static Colour contrasting (Colour colour1, Colour colour2) noexcept
Returns a colour that contrasts against two colours.
static Colour greyLevel (float brightness) noexcept
Returns an opaque shade of grey.
static Colour fromString (StringRef encodedColourString)
Reads the colour from a string that was created with toString().
Detailed Description
Represents a colour, also including a transparency value.
The colour is stored internally as unsigned 8-bit red, green, blue and alpha values.
Constructor & Destructor Documentation
juce::Colour::Colour () noexcept
Creates a transparent black colour.
juce::Colour::Colour (const Colour & other) noexcept
Creates a copy of another Colour object.
juce::Colour::Colour (uint32 argb) explicit noexcept
Creates a colour from a 32-bit ARGB value.
The format of this number is: ((alpha << 24) | (red << 16) | (green << 8) | blue).
All components in the range 0x00 to 0xff. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque.
See Also
getPixelARGB
juce::Colour::Colour (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
juce::Colour::Colour (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
juce::Colour::Colour (uint8 red, uint8 green, uint8 blue, float alpha) noexcept
Creates a colour from 8-bit red, green, and blue values, and a floating-point alpha.
Alpha of 0.0 is transparent, alpha of 1.0f is opaque. Values outside the valid range will be clipped.
juce::Colour::Colour (float hue, float saturation, float brightness, uint8 alpha) noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
The floating point values must be between 0.0 and 1.0. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque. Values outside the valid range will be clipped.
juce::Colour::Colour (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using floating point hue, saturation, brightness and alpha values.
All values must be between 0.0 and 1.0. Numbers outside the valid range will be clipped.
juce::Colour::Colour (PixelARGB argb) noexcept
Creates a colour using a PixelARGB object.
This function assumes that the argb pixel is not premultiplied.
juce::Colour::Colour (PixelRGB rgb) noexcept
Creates a colour using a PixelRGB object.
juce::Colour::Colour (PixelAlpha alpha) noexcept
Creates a colour using a PixelAlpha object.
juce::Colour::~Colour () noexcept
Destructor.
Member Function Documentation
static Colour juce::Colour::fromRGB (uint8 red, uint8 green, uint8 blue) static noexcept
Creates an opaque colour using 8-bit red, green and blue values.
static Colour juce::Colour::fromRGBA (uint8 red, uint8 green, uint8 blue, uint8 alpha) static noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
static Colour juce::Colour::fromFloatRGBA (float red, float green, float blue, float alpha) static noexcept
Creates a colour using floating point red, green, blue and alpha values.
Numbers outside the range 0..1 will be clipped.
static Colour juce::Colour::fromHSV (float hue, float saturation, float brightness, float alpha) static noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
The floating point values must be between 0.0 and 1.0. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque. Values outside the valid range will be clipped.
Colour& juce::Colour::operator= (const Colour & other) noexcept
Copies another Colour object.
bool juce::Colour::operator== (const Colour & other) const noexcept
Compares two colours.
bool juce::Colour::operator!= (const Colour & other) const noexcept
Compares two colours.
uint8 juce::Colour::getRed () const noexcept
Returns the red component of this colour.
Returns
a value between 0x00 and 0xff.
References juce::PixelARGB::getRed().
uint8 juce::Colour::getGreen () const noexcept
Returns the green component of this colour.
Returns
a value between 0x00 and 0xff.
References juce::PixelARGB::getGreen().
uint8 juce::Colour::getBlue () const noexcept
Returns the blue component of this colour.
Returns
a value between 0x00 and 0xff.
References juce::PixelARGB::getBlue().
float juce::Colour::getFloatRed () const noexcept
Returns the red component of this colour as a floating point value.
Returns
a value between 0.0 and 1.0
float juce::Colour::getFloatGreen () const noexcept
Returns the green component of this colour as a floating point value.
Returns
a value between 0.0 and 1.0
float juce::Colour::getFloatBlue () const noexcept
Returns the blue component of this colour as a floating point value.
Returns
a value between 0.0 and 1.0
const PixelARGB juce::Colour::getPixelARGB () const noexcept
Returns a premultiplied ARGB pixel object that represents this colour.
uint32 juce::Colour::getARGB () const noexcept
Returns a 32-bit integer that represents this colour.
The format of this number is: ((alpha << 24) | (red << 16) | (green << 16) | blue).
uint8 juce::Colour::getAlpha () const noexcept
Returns the colour's alpha (opacity).
Alpha of 0x00 is completely transparent, 0xff is completely opaque.
References juce::PixelARGB::getAlpha().
float juce::Colour::getFloatAlpha () const noexcept
Returns the colour's alpha (opacity) as a floating point value.
Alpha of 0.0 is completely transparent, 1.0 is completely opaque.
Referenced by juce::FillType::getOpacity().
bool juce::Colour::isOpaque () const noexcept
Returns true if this colour is completely opaque.
Equivalent to (getAlpha() == 0xff).
bool juce::Colour::isTransparent () const noexcept
Returns true if this colour is completely transparent.
Equivalent to (getAlpha() == 0x00).
Colour juce::Colour::withAlpha (uint8 newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour juce::Colour::withAlpha (float newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour juce::Colour::withMultipliedAlpha (float alphaMultiplier) const noexcept
Returns a colour that's the same colour as this one, but with a modified alpha value.
The new colour's alpha will be this object's alpha multiplied by the value passed-in.
Colour juce::Colour::overlaidWith (Colour foregroundColour) const noexcept
Returns a colour that is the result of alpha-compositing a new colour over this one.
If the foreground colour is semi-transparent, it is blended onto this colour accordingly.
Colour juce::Colour::interpolatedWith (Colour other, float proportionOfOther) const noexcept
Returns a colour that lies somewhere between this one and another.
If amountOfOther is zero, the result is 100% this colour, if amountOfOther is 1.0, the result is 100% of the other colour.
float juce::Colour::getHue () const noexcept
Returns the colour's hue component.
The value returned is in the range 0.0 to 1.0
float juce::Colour::getSaturation () const noexcept
Returns the colour's saturation component.
The value returned is in the range 0.0 to 1.0
float juce::Colour::getBrightness () const noexcept
Returns the colour's brightness component.
The value returned is in the range 0.0 to 1.0
float juce::Colour::getPerceivedBrightness () const noexcept
Returns a skewed brightness value, adjusted to better reflect the way the human eye responds to different colour channels.
This makes it better than getBrightness() for comparing differences in brightness.
void juce::Colour::getHSB (float & hue, float & saturation, float & brightness) const noexcept
Returns the colour's hue, saturation and brightness components all at once.
The values returned are in the range 0.0 to 1.0
Colour juce::Colour::withHue (float newHue) const noexcept
Returns a copy of this colour with a different hue.
Colour juce::Colour::withSaturation (float newSaturation) const noexcept
Returns a copy of this colour with a different saturation.
Colour juce::Colour::withBrightness (float newBrightness) const noexcept
Returns a copy of this colour with a different brightness.
See Also
brighter, darker, withMultipliedBrightness
Colour juce::Colour::withRotatedHue (float amountToRotate) const noexcept
Returns a copy of this colour with it hue rotated.
The new colour's hue is ((this->getHue() + amountToRotate) % 1.0)
See Also
brighter, darker, withMultipliedBrightness
Colour juce::Colour::withMultipliedSaturation (float multiplier) const noexcept
Returns a copy of this colour with its saturation multiplied by the given value.
The new colour's saturation is (this->getSaturation() * multiplier) (the result is clipped to legal limits).
Colour juce::Colour::withMultipliedBrightness (float amount) const noexcept
Returns a copy of this colour with its brightness multiplied by the given value.
The new colour's brightness is (this->getBrightness() * multiplier) (the result is clipped to legal limits).
Colour juce::Colour::brighter (float amountBrighter = 0.4f) const noexcept
Returns a brighter version of this colour.
Parameters
amountBrighter how much brighter to make it - a value from 0 to 1.0 where 0 is unchanged, and higher values make it brighter
See Also
withMultipliedBrightness
Colour juce::Colour::darker (float amountDarker = 0.4f) const noexcept
Returns a darker version of this colour.
Parameters
amountDarker how much darker to make it - a value from 0 to 1.0 where 0 is unchanged, and higher values make it darker
See Also
withMultipliedBrightness
Colour juce::Colour::contrasting (float amount = 1.0f) const noexcept
Returns a colour that will be clearly visible against this colour.
The amount parameter indicates how contrasting the new colour should be, so e.g. Colours::black.contrasting (0.1f) will return a colour that's just a little bit lighter; Colours::black.contrasting (1.0f) will return white; Colours::white.contrasting (1.0f) will return black, etc.
Colour juce::Colour::contrasting (Colour targetColour, float minLuminosityDiff) const noexcept
Returns a colour that is as close as possible to a target colour whilst still being in contrast to this one.
The colour that is returned will be the targetColour, but with its luminosity nudged up or down so that it differs from the luminosity of this colour by at least the amount specified by minLuminosityDiff.
static Colour juce::Colour::contrasting (Colour colour1, Colour colour2) static noexcept
Returns a colour that contrasts against two colours.
Looks for a colour that contrasts with both of the colours passed-in. Handy for things like choosing a highlight colour in text editors, etc.
static Colour juce::Colour::greyLevel (float brightness) static noexcept
Returns an opaque shade of grey.
Parameters
brightness the level of grey to return - 0 is black, 1.0 is white
String juce::Colour::toString () const
Returns a stringified version of this colour.
The string can be turned back into a colour using the fromString() method.
static Colour juce::Colour::fromString (StringRef encodedColourString) static
Reads the colour from a string that was created with toString().
String juce::Colour::toDisplayString (bool includeAlphaValue) const
Returns the colour as a hex string in the form RRGGBB or AARRGGBB.
The documentation for this class was generated from the following file:
juce_Colour.h