JUCE: juce::PluginHostType Class Reference
juce::PluginHostType Class Reference
utility
Public Types
enum HostType {
UnknownHost, AbletonLive6, AbletonLive7, AbletonLive8,
AbletonLiveGeneric, AdobeAudition, AdobePremierePro, AppleLogic,
Ardour, BitwigStudio, CakewalkSonar8, CakewalkSonarGeneric,
DaVinciResolve, DigidesignProTools, DigitalPerformer, FinalCut,
FruityLoops, MagixSamplitude, MergingPyramix, MuseReceptorGeneric,
Reaper, Renoise, SADiE, SteinbergCubase4,
SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7,
SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, SteinbergCubaseGeneric,
SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, SteinbergNuendoGeneric,
SteinbergWavelab5, SteinbergWavelab6, SteinbergWavelab7, SteinbergWavelab8,
SteinbergWavelabGeneric, SteinbergTestHost, StudioOne, Tracktion3,
TracktionGeneric, TracktionWaveform, VBVSTScanner, WaveBurner
}
Public Member Functions
PluginHostType ()
PluginHostType (const PluginHostType &other) noexcept
PluginHostType & operator= (const PluginHostType &other) noexcept
bool isAbletonLive () const noexcept
bool isAdobeAudition () const noexcept
bool isArdour () const noexcept
bool isBitwigStudio () const noexcept
bool isCubase () const noexcept
bool isCubase7orLater () const noexcept
bool isCubaseBridged () const noexcept
bool isDaVinciResolve () const noexcept
bool isDigitalPerformer () const noexcept
bool isFinalCut () const noexcept
bool isFruityLoops () const noexcept
bool isLogic () const noexcept
bool isNuendo () const noexcept
bool isPremiere () const noexcept
bool isProTools () const noexcept
bool isPyramix () const noexcept
bool isReceptor () const noexcept
bool isReaper () const noexcept
bool isRenoise () const noexcept
bool isSADiE () const noexcept
bool isSamplitude () const noexcept
bool isSonar () const noexcept
bool isSteinbergTestHost () const noexcept
bool isSteinberg () const noexcept
bool isStudioOne () const noexcept
bool isTracktion () const noexcept
bool isTracktionWaveform () const noexcept
bool isVBVSTScanner () const noexcept
bool isWaveBurner () const noexcept
bool isWavelab () const noexcept
bool isWavelabLegacy () const noexcept
const char * getHostDescription () const noexcept
bool isInterAppAudioConnected () const
void switchToHostApplication () const
Static Public Member Functions
static String getHostPath ()
static AudioProcessor::WrapperType getPluginLoadedAs () noexcept
Returns the plug-in format via which the plug-in file was loaded.
Public Attributes
HostType type
Member Enumeration Documentation
enum juce::PluginHostType::HostType
Enumerator
UnknownHost
AbletonLive6
AbletonLive7
AbletonLive8
AbletonLiveGeneric
AdobeAudition
AdobePremierePro
AppleLogic
Ardour
BitwigStudio
CakewalkSonar8
CakewalkSonarGeneric
DaVinciResolve
DigidesignProTools
DigitalPerformer
FinalCut
FruityLoops
MagixSamplitude
MergingPyramix
MuseReceptorGeneric
Reaper
Renoise
SADiE
SteinbergCubase4
SteinbergCubase5
SteinbergCubase5Bridged
SteinbergCubase6
SteinbergCubase7
SteinbergCubase8
SteinbergCubase8_5
SteinbergCubase9
SteinbergCubaseGeneric
SteinbergNuendo3
SteinbergNuendo4
SteinbergNuendo5
SteinbergNuendoGeneric
SteinbergWavelab5
SteinbergWavelab6
SteinbergWavelab7
SteinbergWavelab8
SteinbergWavelabGeneric
SteinbergTestHost
StudioOne
Tracktion3
TracktionGeneric
TracktionWaveform
VBVSTScanner
WaveBurner
Constructor & Destructor Documentation
juce::PluginHostType::PluginHostType ()
juce::PluginHostType::PluginHostType (const PluginHostType & other) noexcept
Member Function Documentation
PluginHostType& juce::PluginHostType::operator= (const PluginHostType & other) noexcept
References type.
bool juce::PluginHostType::isAbletonLive () const noexcept
References AbletonLive6, AbletonLive7, AbletonLive8, AbletonLiveGeneric, and type.
bool juce::PluginHostType::isAdobeAudition () const noexcept
References AdobeAudition, and type.
bool juce::PluginHostType::isArdour () const noexcept
References Ardour, and type.
bool juce::PluginHostType::isBitwigStudio () const noexcept
References BitwigStudio, and type.
bool juce::PluginHostType::isCubase () const noexcept
References SteinbergCubase4, SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7, SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, SteinbergCubaseGeneric, and type.
Referenced by isCubase7orLater(), and isSteinberg().
bool juce::PluginHostType::isCubase7orLater () const noexcept
References isCubase(), SteinbergCubase4, SteinbergCubase5, SteinbergCubase6, and type.
bool juce::PluginHostType::isCubaseBridged () const noexcept
References SteinbergCubase5Bridged, and type.
bool juce::PluginHostType::isDaVinciResolve () const noexcept
References DaVinciResolve, and type.
bool juce::PluginHostType::isDigitalPerformer () const noexcept
References DigitalPerformer, and type.
bool juce::PluginHostType::isFinalCut () const noexcept
References FinalCut, and type.
bool juce::PluginHostType::isFruityLoops () const noexcept
References FruityLoops, and type.
bool juce::PluginHostType::isLogic () const noexcept
References AppleLogic, and type.
bool juce::PluginHostType::isNuendo () const noexcept
References SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, SteinbergNuendoGeneric, and type.
Referenced by isSteinberg().
bool juce::PluginHostType::isPremiere () const noexcept
References AdobePremierePro, and type.
bool juce::PluginHostType::isProTools () const noexcept
References DigidesignProTools, and type.
bool juce::PluginHostType::isPyramix () const noexcept
References MergingPyramix, and type.
bool juce::PluginHostType::isReceptor () const noexcept
References MuseReceptorGeneric, and type.
bool juce::PluginHostType::isReaper () const noexcept
References Reaper, and type.
bool juce::PluginHostType::isRenoise () const noexcept
References Renoise, and type.
bool juce::PluginHostType::isSADiE () const noexcept
References SADiE, and type.
bool juce::PluginHostType::isSamplitude () const noexcept
References MagixSamplitude, and type.
bool juce::PluginHostType::isSonar () const noexcept
References CakewalkSonar8, CakewalkSonarGeneric, and type.
bool juce::PluginHostType::isSteinbergTestHost () const noexcept
References SteinbergTestHost, and type.
Referenced by isSteinberg().
bool juce::PluginHostType::isSteinberg () const noexcept
References isCubase(), isNuendo(), isSteinbergTestHost(), and isWavelab().
bool juce::PluginHostType::isStudioOne () const noexcept
References StudioOne, and type.
bool juce::PluginHostType::isTracktion () const noexcept
References isTracktionWaveform(), Tracktion3, TracktionGeneric, and type.
bool juce::PluginHostType::isTracktionWaveform () const noexcept
References TracktionWaveform, and type.
Referenced by isTracktion().
bool juce::PluginHostType::isVBVSTScanner () const noexcept
References type, and VBVSTScanner.
bool juce::PluginHostType::isWaveBurner () const noexcept
References type, and WaveBurner.
bool juce::PluginHostType::isWavelab () const noexcept
References isWavelabLegacy(), SteinbergWavelab7, SteinbergWavelab8, SteinbergWavelabGeneric, and type.
Referenced by isSteinberg().
bool juce::PluginHostType::isWavelabLegacy () const noexcept
References SteinbergWavelab5, SteinbergWavelab6, and type.
Referenced by isWavelab().
const char* juce::PluginHostType::getHostDescription () const noexcept
References AbletonLive6, AbletonLive7, AbletonLive8, AbletonLiveGeneric, AdobeAudition, AdobePremierePro, AppleLogic, BitwigStudio, CakewalkSonar8, CakewalkSonarGeneric, DaVinciResolve, DigidesignProTools, DigitalPerformer, FinalCut, FruityLoops, MagixSamplitude, MergingPyramix, MuseReceptorGeneric, Reaper, Renoise, SADiE, SteinbergCubase4, SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7, SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, SteinbergCubaseGeneric, SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, SteinbergNuendoGeneric, SteinbergTestHost, SteinbergWavelab5, SteinbergWavelab6, SteinbergWavelab7, SteinbergWavelab8, SteinbergWavelabGeneric, StudioOne, Tracktion3, TracktionGeneric, type, VBVSTScanner, and WaveBurner.
bool juce::PluginHostType::isInterAppAudioConnected () const
void juce::PluginHostType::switchToHostApplication () const
static String juce::PluginHostType::getHostPath () static
References juce::File::getFullPathName(), juce::File::getSpecialLocation(), and juce::File::hostApplicationPath.
static AudioProcessor::WrapperType juce::PluginHostType::getPluginLoadedAs () static noexcept
Returns the plug-in format via which the plug-in file was loaded.
This value is identical to AudioProcessor::wrapperType of the main audio processor of this plug-in. This function is useful for code that does not have access to the plug-in's main audio processor.
See Also
AudioProcessor::wrapperType
Referenced by juce::StandalonePluginHolder::getInstance().
Member Data Documentation
HostType juce::PluginHostType::type
Referenced by getHostDescription(), isAbletonLive(), isAdobeAudition(), isArdour(), isBitwigStudio(), isCubase(), isCubase7orLater(), isCubaseBridged(), isDaVinciResolve(), isDigitalPerformer(), isFinalCut(), isFruityLoops(), isLogic(), isNuendo(), isPremiere(), isProTools(), isPyramix(), isReaper(), isReceptor(), isRenoise(), isSADiE(), isSamplitude(), isSonar(), isSteinbergTestHost(), isStudioOne(), isTracktion(), isTracktionWaveform(), isVBVSTScanner(), isWaveBurner(), isWavelab(), isWavelabLegacy(), and operator=().
The documentation for this class was generated from the following file:
juce_PluginHostType.h