JUCE: juce::CharacterFunctions Class Reference
juce::CharacterFunctions Class Reference
text
A collection of functions for manipulating characters and character strings.
Classes
struct HexParser
Static Public Member Functions
static juce_wchar toUpperCase (juce_wchar character) noexcept
Converts a character to upper-case.
static juce_wchar toLowerCase (juce_wchar character) noexcept
Converts a character to lower-case.
static bool isUpperCase (juce_wchar character) noexcept
Checks whether a unicode character is upper-case.
static bool isLowerCase (juce_wchar character) noexcept
Checks whether a unicode character is lower-case.
static bool isWhitespace (char character) noexcept
Checks whether a character is whitespace.
static bool isWhitespace (juce_wchar character) noexcept
Checks whether a character is whitespace.
static bool isDigit (char character) noexcept
Checks whether a character is a digit.
static bool isDigit (juce_wchar character) noexcept
Checks whether a character is a digit.
static bool isLetter (char character) noexcept
Checks whether a character is alphabetic.
static bool isLetter (juce_wchar character) noexcept
Checks whether a character is alphabetic.
static bool isLetterOrDigit (char character) noexcept
Checks whether a character is alphabetic or numeric.
static bool isLetterOrDigit (juce_wchar character) noexcept
Checks whether a character is alphabetic or numeric.
static bool isPrintable (char character) noexcept
Checks whether a character is a printable character, i.e.
static bool isPrintable (juce_wchar character) noexcept
Checks whether a character is a printable character, i.e.
static int getHexDigitValue (juce_wchar digit) noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
static juce_wchar getUnicodeCharFromWindows1252Codepage (uint8 windows1252Char) noexcept
Converts a byte of Windows 1252 codepage to unicode.
template<typename CharPointerType >
static double readDoubleValue (CharPointerType &text) noexcept
Parses a character string to read a floating-point number.
template<typename CharPointerType >
static double getDoubleValue (CharPointerType text) noexcept
Parses a character string, to read a floating-point value.
template<typename IntType , typename CharPointerType >
static IntType getIntValue (const CharPointerType text) noexcept
Parses a character string, to read an integer value.
template<typename CharPointerType >
static size_t lengthUpTo (CharPointerType text, const size_t maxCharsToCount) noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
template<typename CharPointerType >
static size_t lengthUpTo (CharPointerType start, const CharPointerType end) noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
template<typename DestCharPointerType , typename SrcCharPointerType >
static void copyAll (DestCharPointerType &dest, SrcCharPointerType src) noexcept
Copies null-terminated characters from one string to another.
template<typename DestCharPointerType , typename SrcCharPointerType >
static size_t copyWithDestByteLimit (DestCharPointerType &dest, SrcCharPointerType src, size_t maxBytesToWrite) noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
template<typename DestCharPointerType , typename SrcCharPointerType >
static void copyWithCharLimit (DestCharPointerType &dest, SrcCharPointerType src, int maxChars) noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
static int compare (juce_wchar char1, juce_wchar char2) noexcept
Compares two characters.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compare (CharPointerType1 s1, CharPointerType2 s2) noexcept
Compares two null-terminated character strings.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
Compares two null-terminated character strings, up to a given number of characters.
static int compareIgnoreCase (juce_wchar char1, juce_wchar char2) noexcept
Compares two characters, using a case-independant match.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) noexcept
Compares two null-terminated character strings, using a case-independant match.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
Compares two null-terminated character strings, using a case-independent match.
template<typename CharPointerType1 , typename CharPointerType2 >
static int indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
Finds the character index of a given substring in another string.
template<typename CharPointerType1 , typename CharPointerType2 >
static CharPointerType1 find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
Returns a pointer to the first occurrence of a substring in a string.
template<typename CharPointerType >
static CharPointerType find (CharPointerType textToSearch, const juce_wchar charToLookFor) noexcept
Returns a pointer to the first occurrence of a substring in a string.
template<typename CharPointerType1 , typename CharPointerType2 >
static int indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) noexcept
Finds the character index of a given substring in another string, using a case-independent match.
template<typename Type >
static int indexOfChar (Type text, const juce_wchar charToFind) noexcept
Finds the character index of a given character in another string.
template<typename Type >
static int indexOfCharIgnoreCase (Type text, juce_wchar charToFind) noexcept
Finds the character index of a given character in another string, using a case-independent match.
template<typename Type >
static Type findEndOfWhitespace (Type text) noexcept
Returns a pointer to the first non-whitespace character in a string.
template<typename Type , typename BreakType >
static Type findEndOfToken (Type text, BreakType breakCharacters, Type quoteCharacters)
Returns a pointer to the first character in the string which is found in the breakCharacters string.
Detailed Description
A collection of functions for manipulating characters and character strings.
Most of these methods are designed for internal use by the String and CharPointer classes, but some of them may be useful to call directly.
See Also
String, CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Member Function Documentation
static juce_wchar juce::CharacterFunctions::toUpperCase (juce_wchar character) static noexcept
Converts a character to upper-case.
Referenced by juce::CharPointer_ASCII::toUpperCase(), juce::CharPointer_UTF32::toUpperCase(), juce::CharPointer_UTF16::toUpperCase(), and juce::CharPointer_UTF8::toUpperCase().
static juce_wchar juce::CharacterFunctions::toLowerCase (juce_wchar character) static noexcept
Converts a character to lower-case.
Referenced by indexOfCharIgnoreCase(), juce::CharPointer_ASCII::toLowerCase(), juce::CharPointer_UTF32::toLowerCase(), juce::CharPointer_UTF16::toLowerCase(), and juce::CharPointer_UTF8::toLowerCase().
static bool juce::CharacterFunctions::isUpperCase (juce_wchar character) static noexcept
Checks whether a unicode character is upper-case.
Referenced by juce::CharPointer_ASCII::isUpperCase(), juce::CharPointer_UTF32::isUpperCase(), juce::CharPointer_UTF16::isUpperCase(), and juce::CharPointer_UTF8::isUpperCase().
static bool juce::CharacterFunctions::isLowerCase (juce_wchar character) static noexcept
Checks whether a unicode character is lower-case.
Referenced by juce::CharPointer_ASCII::isLowerCase(), juce::CharPointer_UTF32::isLowerCase(), juce::CharPointer_UTF16::isLowerCase(), and juce::CharPointer_UTF8::isLowerCase().
static bool juce::CharacterFunctions::isWhitespace (char character) static noexcept
Checks whether a character is whitespace.
Referenced by juce::CharPointer_ASCII::isWhitespace(), juce::CharPointer_UTF32::isWhitespace(), and juce::CharPointer_UTF16::isWhitespace().
static bool juce::CharacterFunctions::isWhitespace (juce_wchar character) static noexcept
Checks whether a character is whitespace.
static bool juce::CharacterFunctions::isDigit (char character) static noexcept
Checks whether a character is a digit.
Referenced by juce::CharPointer_ASCII::isDigit(), juce::CharPointer_UTF32::isDigit(), and juce::CharPointer_UTF16::isDigit().
static bool juce::CharacterFunctions::isDigit (juce_wchar character) static noexcept
Checks whether a character is a digit.
static bool juce::CharacterFunctions::isLetter (char character) static noexcept
Checks whether a character is alphabetic.
Referenced by juce::CppTokeniserFunctions::isIdentifierStart(), juce::CharPointer_ASCII::isLetter(), juce::CharPointer_UTF32::isLetter(), juce::CharPointer_UTF16::isLetter(), and juce::CharPointer_UTF8::isLetter().
static bool juce::CharacterFunctions::isLetter (juce_wchar character) static noexcept
Checks whether a character is alphabetic.
static bool juce::CharacterFunctions::isLetterOrDigit (char character) static noexcept
Checks whether a character is alphabetic or numeric.
Referenced by juce::CppTokeniserFunctions::isIdentifierBody(), juce::CharPointer_ASCII::isLetterOrDigit(), juce::CharPointer_UTF32::isLetterOrDigit(), juce::CharPointer_UTF16::isLetterOrDigit(), juce::CharPointer_UTF8::isLetterOrDigit(), and juce::CppTokeniserFunctions::skipNumberSuffix().
static bool juce::CharacterFunctions::isLetterOrDigit (juce_wchar character) static noexcept
Checks whether a character is alphabetic or numeric.
static bool juce::CharacterFunctions::isPrintable (char character) static noexcept
Checks whether a character is a printable character, i.e.
alphabetic, numeric, a punctuation character or a space.
static bool juce::CharacterFunctions::isPrintable (juce_wchar character) static noexcept
Checks whether a character is a printable character, i.e.
alphabetic, numeric, a punctuation character or a space.
static int juce::CharacterFunctions::getHexDigitValue (juce_wchar digit) static noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
Referenced by juce::CharacterFunctions::HexParser< ResultType >::parse(), and juce::CppTokeniserFunctions::writeEscapeChars().
static juce_wchar juce::CharacterFunctions::getUnicodeCharFromWindows1252Codepage (uint8 windows1252Char) static noexcept
Converts a byte of Windows 1252 codepage to unicode.
template<typename CharPointerType > static double juce::CharacterFunctions::readDoubleValue (CharPointerType & text) static noexcept
Parses a character string to read a floating-point number.
Note that this will advance the pointer that is passed in, leaving it at the end of the number.
References JUCE_CONSTEXPR, and max().
template<typename CharPointerType > static double juce::CharacterFunctions::getDoubleValue (CharPointerType text) static noexcept
Parses a character string, to read a floating-point value.
Referenced by juce::CharPointer_UTF32::getDoubleValue(), juce::CharPointer_ASCII::getDoubleValue(), juce::CharPointer_UTF16::getDoubleValue(), and juce::CharPointer_UTF8::getDoubleValue().
template<typename IntType , typename CharPointerType > static IntType juce::CharacterFunctions::getIntValue (const CharPointerType text) static noexcept
Parses a character string, to read an integer value.
template<typename CharPointerType > static size_t juce::CharacterFunctions::lengthUpTo (CharPointerType text, const size_t maxCharsToCount) static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
Referenced by juce::CharPointer_ASCII::lengthUpTo(), juce::CharPointer_UTF32::lengthUpTo(), juce::CharPointer_UTF16::lengthUpTo(), and juce::CharPointer_UTF8::lengthUpTo().
template<typename CharPointerType > static size_t juce::CharacterFunctions::lengthUpTo (CharPointerType start, const CharPointerType end) static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
template<typename DestCharPointerType , typename SrcCharPointerType > static void juce::CharacterFunctions::copyAll (DestCharPointerType & dest, SrcCharPointerType src) static noexcept
Copies null-terminated characters from one string to another.
Referenced by juce::CharPointer_ASCII::writeAll(), juce::CharPointer_UTF32::writeAll(), juce::CharPointer_UTF16::writeAll(), and juce::CharPointer_UTF8::writeAll().
template<typename DestCharPointerType , typename SrcCharPointerType > static size_t juce::CharacterFunctions::copyWithDestByteLimit (DestCharPointerType & dest, SrcCharPointerType src, size_t maxBytesToWrite) static noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
References juce::getAddressDifference().
Referenced by juce::CharPointer_ASCII::writeWithDestByteLimit(), juce::CharPointer_UTF32::writeWithDestByteLimit(), juce::CharPointer_UTF16::writeWithDestByteLimit(), and juce::CharPointer_UTF8::writeWithDestByteLimit().
template<typename DestCharPointerType , typename SrcCharPointerType > static void juce::CharacterFunctions::copyWithCharLimit (DestCharPointerType & dest, SrcCharPointerType src, int maxChars) static noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
Referenced by juce::CharPointer_ASCII::writeWithCharLimit(), juce::CharPointer_UTF32::writeWithCharLimit(), juce::CharPointer_UTF16::writeWithCharLimit(), and juce::CharPointer_UTF8::writeWithCharLimit().
static int juce::CharacterFunctions::compare (juce_wchar char1, juce_wchar char2) static noexcept
Compares two characters.
Referenced by juce::CharPointer_ASCII::compare(), juce::CharPointer_UTF32::compare(), juce::CharPointer_UTF16::compare(), and juce::CharPointer_UTF8::compare().
template<typename CharPointerType1 , typename CharPointerType2 > static int juce::CharacterFunctions::compare (CharPointerType1 s1, CharPointerType2 s2) static noexcept
Compares two null-terminated character strings.
template<typename CharPointerType1 , typename CharPointerType2 > static int juce::CharacterFunctions::compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) static noexcept
Compares two null-terminated character strings, up to a given number of characters.
Referenced by juce::CharPointer_ASCII::compareUpTo(), juce::CharPointer_UTF32::compareUpTo(), juce::CharPointer_UTF16::compareUpTo(), and juce::CharPointer_UTF8::compareUpTo().
static int juce::CharacterFunctions::compareIgnoreCase (juce_wchar char1, juce_wchar char2) static noexcept
Compares two characters, using a case-independant match.
Referenced by juce::CharPointer_ASCII::compareIgnoreCase(), juce::CharPointer_UTF32::compareIgnoreCase(), juce::CharPointer_UTF16::compareIgnoreCase(), and juce::CharPointer_UTF8::compareIgnoreCase().
template<typename CharPointerType1 , typename CharPointerType2 > static int juce::CharacterFunctions::compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) static noexcept
Compares two null-terminated character strings, using a case-independant match.
template<typename CharPointerType1 , typename CharPointerType2 > static int juce::CharacterFunctions::compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) static noexcept
Compares two null-terminated character strings, using a case-independent match.
Referenced by juce::CharPointer_ASCII::compareIgnoreCaseUpTo(), juce::CharPointer_UTF32::compareIgnoreCaseUpTo(), juce::CharPointer_UTF16::compareIgnoreCaseUpTo(), and juce::CharPointer_UTF8::compareIgnoreCaseUpTo().
template<typename CharPointerType1 , typename CharPointerType2 > static int juce::CharacterFunctions::indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) static noexcept
Finds the character index of a given substring in another string.
Returns -1 if the substring is not found.
Referenced by juce::CharPointer_ASCII::indexOf(), juce::CharPointer_UTF32::indexOf(), juce::CharPointer_UTF16::indexOf(), and juce::CharPointer_UTF8::indexOf().
template<typename CharPointerType1 , typename CharPointerType2 > static CharPointerType1 juce::CharacterFunctions::find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) static noexcept
Returns a pointer to the first occurrence of a substring in a string.
If the substring is not found, this will return a pointer to the string's null terminator.
template<typename CharPointerType > static CharPointerType juce::CharacterFunctions::find (CharPointerType textToSearch, const juce_wchar charToLookFor) static noexcept
Returns a pointer to the first occurrence of a substring in a string.
If the substring is not found, this will return a pointer to the string's null terminator.
template<typename CharPointerType1 , typename CharPointerType2 > static int juce::CharacterFunctions::indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) static noexcept
Finds the character index of a given substring in another string, using a case-independent match.
Returns -1 if the substring is not found.
template<typename Type > static int juce::CharacterFunctions::indexOfChar (Type text, const juce_wchar charToFind) static noexcept
Finds the character index of a given character in another string.
Returns -1 if the character is not found.
Referenced by juce::CharPointer_ASCII::indexOf(), juce::CharPointer_UTF32::indexOf(), juce::CharPointer_UTF16::indexOf(), and juce::CharPointer_UTF8::indexOf().
template<typename Type > static int juce::CharacterFunctions::indexOfCharIgnoreCase (Type text, juce_wchar charToFind) static noexcept
Finds the character index of a given character in another string, using a case-independent match.
Returns -1 if the character is not found.
References toLowerCase().
Referenced by juce::CharPointer_ASCII::indexOf(), juce::CharPointer_UTF32::indexOf(), juce::CharPointer_UTF16::indexOf(), and juce::CharPointer_UTF8::indexOf().
template<typename Type > static Type juce::CharacterFunctions::findEndOfWhitespace (Type text) static noexcept
Returns a pointer to the first non-whitespace character in a string.
If the string contains only whitespace, this will return a pointer to its null terminator.
Referenced by juce::CharPointer_UTF32::findEndOfWhitespace(), juce::CharPointer_ASCII::findEndOfWhitespace(), juce::CharPointer_UTF16::findEndOfWhitespace(), and juce::CharPointer_UTF8::findEndOfWhitespace().
template<typename Type , typename BreakType > static Type juce::CharacterFunctions::findEndOfToken (Type text, BreakType breakCharacters, Type quoteCharacters) static
Returns a pointer to the first character in the string which is found in the breakCharacters string.
The documentation for this class was generated from the following file:
juce_CharacterFunctions.h