JUCE: juce::OptionalScopedPointer< ObjectType > Class Template Reference
juce::OptionalScopedPointer< ObjectType > Class Template Reference
memory
Holds a pointer to an object which can optionally be deleted when this pointer goes out of scope.
Public Member Functions
OptionalScopedPointer ()
Creates an empty OptionalScopedPointer.
OptionalScopedPointer (ObjectType *objectToHold, bool takeOwnership)
Creates an OptionalScopedPointer to point to a given object, and specifying whether the OptionalScopedPointer will delete it.
OptionalScopedPointer (OptionalScopedPointer &objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
OptionalScopedPointer & operator= (OptionalScopedPointer &objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
~OptionalScopedPointer ()
The destructor may or may not delete the object that is being held, depending on the takeOwnership flag that was specified when the object was first passed into an OptionalScopedPointer constructor.
operator ObjectType * () const noexcept
Returns the object that this pointer is managing.
ObjectType * get () const noexcept
Returns the object that this pointer is managing.
ObjectType & operator* () const noexcept
Returns the object that this pointer is managing.
ObjectType * operator-> () const noexcept
Lets you access methods and properties of the object that this pointer is holding.
ObjectType * release () noexcept
Removes the current object from this OptionalScopedPointer without deleting it.
void clear ()
Resets this pointer to null, possibly deleting the object that it holds, if it has ownership of it.
void set (ObjectType *newObject, bool takeOwnership)
Makes this OptionalScopedPointer point at a new object, specifying whether the OptionalScopedPointer will take ownership of the object.
void setOwned (ObjectType *newObject)
Makes this OptionalScopedPointer point at a new object, and take ownership of that object.
void setNonOwned (ObjectType *newObject)
Makes this OptionalScopedPointer point at a new object, but will not take ownership of that object.
bool willDeleteObject () const noexcept
Returns true if the target object will be deleted when this pointer object is deleted.
void swapWith (OptionalScopedPointer< ObjectType > &other) noexcept
Swaps this object with another OptionalScopedPointer.
Detailed Description
template<class ObjectType>
class juce::OptionalScopedPointer< ObjectType >
Holds a pointer to an object which can optionally be deleted when this pointer goes out of scope.
This acts in many ways like a ScopedPointer, but allows you to specify whether or not the object is deleted.
See Also
ScopedPointer
Constructor & Destructor Documentation
template<class ObjectType> juce::OptionalScopedPointer< ObjectType >::OptionalScopedPointer ()
Creates an empty OptionalScopedPointer.
template<class ObjectType> juce::OptionalScopedPointer< ObjectType >::OptionalScopedPointer (ObjectType * objectToHold, bool takeOwnership)
Creates an OptionalScopedPointer to point to a given object, and specifying whether the OptionalScopedPointer will delete it.
If takeOwnership is true, then the OptionalScopedPointer will act like a ScopedPointer, deleting the object when it is itself deleted. If this parameter is false, then the OptionalScopedPointer just holds a normal pointer to the object, and won't delete it.
template<class ObjectType> juce::OptionalScopedPointer< ObjectType >::OptionalScopedPointer (OptionalScopedPointer< ObjectType > & objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
Like a normal ScopedPointer, the objectToTransferFrom object will become null, as ownership of the managed object is transferred to this object.
The flag to indicate whether or not to delete the managed object is also copied from the source object.
template<class ObjectType> juce::OptionalScopedPointer< ObjectType >::~OptionalScopedPointer ()
The destructor may or may not delete the object that is being held, depending on the takeOwnership flag that was specified when the object was first passed into an OptionalScopedPointer constructor.
Member Function Documentation
template<class ObjectType> OptionalScopedPointer& juce::OptionalScopedPointer< ObjectType >::operator= (OptionalScopedPointer< ObjectType > & objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
Like a normal ScopedPointer, the objectToTransferFrom object will become null, as ownership of the managed object is transferred to this object.
The ownership flag that says whether or not to delete the managed object is also copied from the source object.
template<class ObjectType> juce::OptionalScopedPointer< ObjectType >::operator ObjectType * () const noexcept
Returns the object that this pointer is managing.
template<class ObjectType> ObjectType* juce::OptionalScopedPointer< ObjectType >::get () const noexcept
Returns the object that this pointer is managing.
template<class ObjectType> ObjectType& juce::OptionalScopedPointer< ObjectType >::operator* () const noexcept
Returns the object that this pointer is managing.
template<class ObjectType> ObjectType* juce::OptionalScopedPointer< ObjectType >::operator-> () const noexcept
Lets you access methods and properties of the object that this pointer is holding.
template<class ObjectType> ObjectType* juce::OptionalScopedPointer< ObjectType >::release () noexcept
Removes the current object from this OptionalScopedPointer without deleting it.
This will return the current object, and set this OptionalScopedPointer to a null pointer.
template<class ObjectType> void juce::OptionalScopedPointer< ObjectType >::clear ()
Resets this pointer to null, possibly deleting the object that it holds, if it has ownership of it.
Referenced by juce::OptionalScopedPointer< juce::Component >::operator=(), juce::OptionalScopedPointer< juce::Component >::set(), and juce::OptionalScopedPointer< juce::Component >::~OptionalScopedPointer().
template<class ObjectType> void juce::OptionalScopedPointer< ObjectType >::set (ObjectType * newObject, bool takeOwnership)
Makes this OptionalScopedPointer point at a new object, specifying whether the OptionalScopedPointer will take ownership of the object.
If takeOwnership is true, then the OptionalScopedPointer will act like a ScopedPointer, deleting the object when it is itself deleted. If this parameter is false, then the OptionalScopedPointer just holds a normal pointer to the object, and won't delete it.
Referenced by juce::OptionalScopedPointer< juce::Component >::setNonOwned(), and juce::OptionalScopedPointer< juce::Component >::setOwned().
template<class ObjectType> void juce::OptionalScopedPointer< ObjectType >::setOwned (ObjectType * newObject)
Makes this OptionalScopedPointer point at a new object, and take ownership of that object.
template<class ObjectType> void juce::OptionalScopedPointer< ObjectType >::setNonOwned (ObjectType * newObject)
Makes this OptionalScopedPointer point at a new object, but will not take ownership of that object.
template<class ObjectType> bool juce::OptionalScopedPointer< ObjectType >::willDeleteObject () const noexcept
Returns true if the target object will be deleted when this pointer object is deleted.
template<class ObjectType> void juce::OptionalScopedPointer< ObjectType >::swapWith (OptionalScopedPointer< ObjectType > & other) noexcept
Swaps this object with another OptionalScopedPointer.
The two objects simply exchange their states.
The documentation for this class was generated from the following file:
juce_OptionalScopedPointer.h