JUCE: juce::SpeakerMappings::VstSpeakerConfigurationHolder Class Reference
juce::SpeakerMappings::VstSpeakerConfigurationHolder Class Reference
Public Member Functions
VstSpeakerConfigurationHolder ()
VstSpeakerConfigurationHolder (const VstSpeakerConfiguration &vstConfig)
VstSpeakerConfigurationHolder (const VstSpeakerConfigurationHolder &other)
VstSpeakerConfigurationHolder (VstSpeakerConfigurationHolder &&other)
VstSpeakerConfigurationHolder (const AudioChannelSet &channels)
VstSpeakerConfigurationHolder & operator= (const VstSpeakerConfigurationHolder &vstConfig)
VstSpeakerConfigurationHolder & operator= (const VstSpeakerConfiguration &vstConfig)
VstSpeakerConfigurationHolder & operator= (VstSpeakerConfigurationHolder &&vstConfig)
const VstSpeakerConfiguration & get () const
Constructor & Destructor Documentation
juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder ()
juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (const VstSpeakerConfiguration & vstConfig)
References operator=().
juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (const VstSpeakerConfigurationHolder & other)
References get(), and operator=().
juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (VstSpeakerConfigurationHolder && other)
juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder (const AudioChannelSet & channels)
References juce::SpeakerMappings::channelSetToVstArrangementType(), juce::SpeakerMappings::getSpeakerType(), juce::AudioChannelSet::getTypeOfChannel(), VstSpeakerConfiguration::numberOfChannels, juce::AudioChannelSet::size(), VstSpeakerConfiguration::speakers, VstIndividualSpeakerInfo::type, VstSpeakerConfiguration::type, and juce::zeromem().
Member Function Documentation
VstSpeakerConfigurationHolder& juce::SpeakerMappings::VstSpeakerConfigurationHolder::operator= (const VstSpeakerConfigurationHolder & vstConfig)
References get(), and operator=().
Referenced by operator=(), and VstSpeakerConfigurationHolder().
VstSpeakerConfigurationHolder& juce::SpeakerMappings::VstSpeakerConfigurationHolder::operator= (const VstSpeakerConfiguration & vstConfig)
References VstSpeakerConfiguration::numberOfChannels, VstSpeakerConfiguration::speakers, and VstSpeakerConfiguration::type.
VstSpeakerConfigurationHolder& juce::SpeakerMappings::VstSpeakerConfigurationHolder::operator= (VstSpeakerConfigurationHolder && vstConfig)
References juce::HeapBlock< ElementType, throwOnFailure >::clear().
const VstSpeakerConfiguration& juce::SpeakerMappings::VstSpeakerConfigurationHolder::get () const
References juce::HeapBlock< ElementType, throwOnFailure >::get().
Referenced by operator=(), and VstSpeakerConfigurationHolder().
The documentation for this class was generated from the following file:
juce_VSTCommon.h