JUCE: juce::MidiEventList Class Reference
juce::MidiEventList Class Reference
format_types
Inherits IEventList.
Public Member Functions
MidiEventList ()
virtual ~MidiEventList ()
JUCE_DECLARE_VST3_COM_REF_METHODS
JUCE_DECLARE_VST3_COM_QUERY_METHODS
void clear ()
Steinberg::int32 PLUGIN_API getEventCount () override
Steinberg::tresult PLUGIN_API getEvent (Steinberg::int32 index, Steinberg::Vst::Event &e) override
Steinberg::tresult PLUGIN_API addEvent (Steinberg::Vst::Event &e) override
Static Public Member Functions
static void toMidiBuffer (MidiBuffer &result, Steinberg::Vst::IEventList &eventList)
static void toEventList (Steinberg::Vst::IEventList &result, MidiBuffer &midiBuffer)
Constructor & Destructor Documentation
juce::MidiEventList::MidiEventList ()
virtual juce::MidiEventList::~MidiEventList () virtual
Member Function Documentation
JUCE_DECLARE_VST3_COM_REF_METHODS JUCE_DECLARE_VST3_COM_QUERY_METHODS void juce::MidiEventList::clear ()
Steinberg::int32 PLUGIN_API juce::MidiEventList::getEventCount () override
Steinberg::tresult PLUGIN_API juce::MidiEventList::getEvent (Steinberg::int32 index, Steinberg::Vst::Event & e) override
References juce::isPositiveAndBelow().
Steinberg::tresult PLUGIN_API juce::MidiEventList::addEvent (Steinberg::Vst::Event & e) override
static void juce::MidiEventList::toMidiBuffer (MidiBuffer & result, Steinberg::Vst::IEventList & eventList) static
References juce::MidiBuffer::addEvent(), juce::MidiMessage::aftertouchChange(), juce::MidiMessage::createSysExMessage(), juce::MidiMessage::noteOff(), and juce::MidiMessage::noteOn().
static void juce::MidiEventList::toEventList (Steinberg::Vst::IEventList & result, MidiBuffer & midiBuffer) static
References juce::MidiMessage::getAfterTouchValue(), juce::MidiMessage::getChannel(), juce::MidiBuffer::Iterator::getNextEvent(), juce::MidiMessage::getNoteNumber(), juce::MidiMessage::getSysExData(), juce::MidiMessage::getSysExDataSize(), juce::MidiMessage::getVelocity(), juce::MidiMessage::isAftertouch(), juce::MidiMessage::isNoteOff(), juce::MidiMessage::isNoteOn(), juce::MidiMessage::isSysEx(), and juce::MidiMessage::noteOn().
The documentation for this class was generated from the following file:
juce_VST3Common.h