JUCE: juce::FillType Class Reference
juce::FillType Class Reference
colour
Represents a colour or fill pattern to use for rendering paths.
Public Member Functions
FillType () noexcept
Creates a default fill type, of solid black.
FillType (Colour colour) noexcept
Creates a fill type of a solid colour.
FillType (const ColourGradient &gradient)
Creates a gradient fill type.
FillType (const Image &image, const AffineTransform &transform) noexcept
Creates a tiled image fill type.
FillType (const FillType &)
Creates a copy of another FillType.
FillType & operator= (const FillType &)
Makes a copy of another FillType.
FillType (FillType &&) noexcept
Move constructor.
FillType & operator= (FillType &&) noexcept
Move assignment operator.
~FillType () noexcept
Destructor.
bool isColour () const noexcept
Returns true if this is a solid colour fill, and not a gradient or image.
bool isGradient () const noexcept
Returns true if this is a gradient fill.
bool isTiledImage () const noexcept
Returns true if this is a tiled image pattern fill.
void setColour (Colour newColour) noexcept
Turns this object into a solid colour fill.
void setGradient (const ColourGradient &newGradient)
Turns this object into a gradient fill.
void setTiledImage (const Image &image, const AffineTransform &transform) noexcept
Turns this object into a tiled image fill type.
void setOpacity (float newOpacity) noexcept
Changes the opacity that should be used.
float getOpacity () const noexcept
Returns the current opacity to be applied to the colour, gradient, or image.
bool isInvisible () const noexcept
Returns true if this fill type is completely transparent.
FillType transformed (const AffineTransform &transform) const
Returns a copy of this fill, adding the specified transform applied to the existing transform.
bool operator== (const FillType &) const
bool operator!= (const FillType &) const
Public Attributes
Colour colour
The solid colour being used.
ScopedPointer< ColourGradient > gradient
Returns the gradient that should be used for filling.
Image image
The image that should be used for tiling.
AffineTransform transform
The transform that should be applied to the image or gradient that's being drawn.
Detailed Description
Represents a colour or fill pattern to use for rendering paths.
This is used by the Graphics and DrawablePath classes as a way to encapsulate a brush type. It can either be a solid colour, a gradient, or a tiled image.
See Also
Graphics::setFillType, DrawablePath::setFill
Constructor & Destructor Documentation
juce::FillType::FillType () noexcept
Creates a default fill type, of solid black.
juce::FillType::FillType (Colour colour) noexcept
Creates a fill type of a solid colour.
See Also
setColour
juce::FillType::FillType (const ColourGradient & gradient)
Creates a gradient fill type.
See Also
setGradient
juce::FillType::FillType (const Image & image, const AffineTransform & transform) noexcept
Creates a tiled image fill type.
The transform allows you to set the scaling, offset and rotation of the pattern.
See Also
setTiledImage
juce::FillType::FillType (const FillType &)
Creates a copy of another FillType.
juce::FillType::FillType (FillType &&) noexcept
Move constructor.
juce::FillType::~FillType () noexcept
Destructor.
Member Function Documentation
FillType& juce::FillType::operator= (const FillType &)
Makes a copy of another FillType.
FillType& juce::FillType::operator= (FillType &&) noexcept
Move assignment operator.
bool juce::FillType::isColour () const noexcept
Returns true if this is a solid colour fill, and not a gradient or image.
References juce::Image::isNull().
bool juce::FillType::isGradient () const noexcept
Returns true if this is a gradient fill.
bool juce::FillType::isTiledImage () const noexcept
Returns true if this is a tiled image pattern fill.
References juce::Image::isValid().
void juce::FillType::setColour (Colour newColour) noexcept
Turns this object into a solid colour fill.
If the object was an image or gradient, those fields will no longer be valid.
void juce::FillType::setGradient (const ColourGradient & newGradient)
Turns this object into a gradient fill.
void juce::FillType::setTiledImage (const Image & image, const AffineTransform & transform) noexcept
Turns this object into a tiled image fill type.
The transform allows you to set the scaling, offset and rotation of the pattern.
void juce::FillType::setOpacity (float newOpacity) noexcept
Changes the opacity that should be used.
If the fill is a solid colour, this just changes the opacity of that colour. For gradients and image tiles, it changes the opacity that will be used for them.
float juce::FillType::getOpacity () const noexcept
Returns the current opacity to be applied to the colour, gradient, or image.
See Also
setOpacity
References juce::Colour::getFloatAlpha().
bool juce::FillType::isInvisible () const noexcept
Returns true if this fill type is completely transparent.
FillType juce::FillType::transformed (const AffineTransform & transform) const
Returns a copy of this fill, adding the specified transform applied to the existing transform.
bool juce::FillType::operator== (const FillType &) const
bool juce::FillType::operator!= (const FillType &) const
Member Data Documentation
Colour juce::FillType::colour
The solid colour being used.
If the fill type is not a solid colour, the alpha channel of this colour indicates the opacity that should be used for the fill, and the RGB channels are ignored.
ScopedPointer<ColourGradient> juce::FillType::gradient
Returns the gradient that should be used for filling.
This will be zero if the object is some other type of fill. If a gradient is active, the overall opacity with which it should be applied is indicated by the alpha channel of the colour variable.
Image juce::FillType::image
The image that should be used for tiling.
If an image fill is active, the overall opacity with which it should be applied is indicated by the alpha channel of the colour variable.
AffineTransform juce::FillType::transform
The transform that should be applied to the image or gradient that's being drawn.
The documentation for this class was generated from the following file:
juce_FillType.h