JUCE: juce::Identifier Class Reference
juce::Identifier Class Reference
text
Represents a string identifier, designed for accessing properties by name.
Public Member Functions
Identifier () noexcept
Creates a null identifier.
Identifier (const char *name)
Creates an identifier with a specified name.
Identifier (const String &name)
Creates an identifier with a specified name.
Identifier (String::CharPointerType nameStart, String::CharPointerType nameEnd)
Creates an identifier with a specified name.
Identifier (const Identifier &other) noexcept
Creates a copy of another identifier.
Identifier & operator= (const Identifier &other) noexcept
Creates a copy of another identifier.
Identifier (Identifier &&other) noexcept
Creates a copy of another identifier.
Identifier & operator= (Identifier &&other) noexcept
Creates a copy of another identifier.
~Identifier () noexcept
Destructor.
bool operator== (const Identifier &other) const noexcept
Compares two identifiers.
bool operator!= (const Identifier &other) const noexcept
Compares two identifiers.
bool operator== (StringRef other) const noexcept
Compares the identifier with a string.
bool operator!= (StringRef other) const noexcept
Compares the identifier with a string.
bool operator< (StringRef other) const noexcept
Compares the identifier with a string.
bool operator<= (StringRef other) const noexcept
Compares the identifier with a string.
bool operator> (StringRef other) const noexcept
Compares the identifier with a string.
bool operator>= (StringRef other) const noexcept
Compares the identifier with a string.
const String & toString () const noexcept
Returns this identifier as a string.
operator String::CharPointerType () const noexcept
Returns this identifier's raw string pointer.
String::CharPointerType getCharPointer () const noexcept
Returns this identifier's raw string pointer.
operator StringRef () const noexcept
Returns this identifier as a StringRef.
bool isValid () const noexcept
Returns true if this Identifier is not null.
bool isNull () const noexcept
Returns true if this Identifier is null.
Static Public Member Functions
static bool isValidIdentifier (const String &possibleIdentifier) noexcept
Checks a given string for characters that might not be valid in an Identifier.
Static Public Attributes
static Identifier null
A null identifier.
Detailed Description
Represents a string identifier, designed for accessing properties by name.
Comparing two Identifier objects is very fast (an O(1) operation), but creating them can be slower than just using a String directly, so the optimal way to use them is to keep some static Identifier objects for the things you use often.
See Also
NamedValueSet, ValueTree
Constructor & Destructor Documentation
juce::Identifier::Identifier () noexcept
Creates a null identifier.
juce::Identifier::Identifier (const char * name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
juce::Identifier::Identifier (const String & name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
juce::Identifier::Identifier (String::CharPointerType nameStart, String::CharPointerType nameEnd)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
juce::Identifier::Identifier (const Identifier & other) noexcept
Creates a copy of another identifier.
juce::Identifier::Identifier (Identifier && other) noexcept
Creates a copy of another identifier.
juce::Identifier::~Identifier () noexcept
Destructor.
Member Function Documentation
Identifier& juce::Identifier::operator= (const Identifier & other) noexcept
Creates a copy of another identifier.
Identifier& juce::Identifier::operator= (Identifier && other) noexcept
Creates a copy of another identifier.
bool juce::Identifier::operator== (const Identifier & other) const noexcept
Compares two identifiers.
This is a very fast operation.
References juce::String::getCharPointer().
bool juce::Identifier::operator!= (const Identifier & other) const noexcept
Compares two identifiers.
This is a very fast operation.
References juce::String::getCharPointer().
bool juce::Identifier::operator== (StringRef other) const noexcept
Compares the identifier with a string.
bool juce::Identifier::operator!= (StringRef other) const noexcept
Compares the identifier with a string.
bool juce::Identifier::operator< (StringRef other) const noexcept
Compares the identifier with a string.
bool juce::Identifier::operator<= (StringRef other) const noexcept
Compares the identifier with a string.
bool juce::Identifier::operator> (StringRef other) const noexcept
Compares the identifier with a string.
bool juce::Identifier::operator>= (StringRef other) const noexcept
Compares the identifier with a string.
const String& juce::Identifier::toString () const noexcept
Returns this identifier as a string.
juce::Identifier::operator String::CharPointerType () const noexcept
Returns this identifier's raw string pointer.
References juce::String::getCharPointer().
String::CharPointerType juce::Identifier::getCharPointer () const noexcept
Returns this identifier's raw string pointer.
References juce::String::getCharPointer().
juce::Identifier::operator StringRef () const noexcept
Returns this identifier as a StringRef.
bool juce::Identifier::isValid () const noexcept
Returns true if this Identifier is not null.
References juce::String::isNotEmpty().
bool juce::Identifier::isNull () const noexcept
Returns true if this Identifier is null.
References juce::String::isEmpty().
static bool juce::Identifier::isValidIdentifier (const String & possibleIdentifier) static noexcept
Checks a given string for characters that might not be valid in an Identifier.
Since Identifiers are used as a script variables and XML attributes, they should only contain alphanumeric characters, underscores, or the '-' and ':' characters.
Member Data Documentation
Identifier juce::Identifier::null static
A null identifier.
The documentation for this class was generated from the following file:
juce_Identifier.h