JUCE: juce::StatisticsAccumulator< FloatType > Class Template Reference
juce::StatisticsAccumulator< FloatType > Class Template Reference
maths
A class that measures various statistics about a series of floating point values that it is given.
Public Member Functions
StatisticsAccumulator () noexcept
Constructs a new StatisticsAccumulator.
void addValue (FloatType v) noexcept
Add a new value to the accumulator.
void reset () noexcept
Reset the accumulator.
FloatType getAverage () const noexcept
Returns the average (arithmetic mean) of all previously added values.
FloatType getVariance () const noexcept
Returns the variance of all previously added values.
FloatType getStandardDeviation () const noexcept
Returns the standard deviation of all previously added values.
FloatType getMinValue () const noexcept
Returns the smallest of all previously added values.
FloatType getMaxValue () const noexcept
Returns the largest of all previously added values.
size_t getCount () const noexcept
Returns how many values have been added to this accumulator.
Detailed Description
template<typename FloatType>
class juce::StatisticsAccumulator< FloatType >
A class that measures various statistics about a series of floating point values that it is given.
Constructor & Destructor Documentation
template<typename FloatType > juce::StatisticsAccumulator< FloatType >::StatisticsAccumulator () noexcept
Constructs a new StatisticsAccumulator.
Member Function Documentation
template<typename FloatType > void juce::StatisticsAccumulator< FloatType >::addValue (FloatType v) noexcept
Add a new value to the accumulator.
This will update all running statistics accordingly.
References jassert, and juce::juce_isfinite().
template<typename FloatType > void juce::StatisticsAccumulator< FloatType >::reset () noexcept
Reset the accumulator.
This will reset all currently saved statistcs.
template<typename FloatType > FloatType juce::StatisticsAccumulator< FloatType >::getAverage () const noexcept
Returns the average (arithmetic mean) of all previously added values.
If no values have been added yet, this will return zero.
template<typename FloatType > FloatType juce::StatisticsAccumulator< FloatType >::getVariance () const noexcept
Returns the variance of all previously added values.
If no values have been added yet, this will return zero.
Referenced by juce::StatisticsAccumulator< FloatType >::getStandardDeviation().
template<typename FloatType > FloatType juce::StatisticsAccumulator< FloatType >::getStandardDeviation () const noexcept
Returns the standard deviation of all previously added values.
If no values have been added yet, this will return zero.
References juce::StatisticsAccumulator< FloatType >::getVariance().
template<typename FloatType > FloatType juce::StatisticsAccumulator< FloatType >::getMinValue () const noexcept
Returns the smallest of all previously added values.
If no values have been added yet, this will return positive infinity.
template<typename FloatType > FloatType juce::StatisticsAccumulator< FloatType >::getMaxValue () const noexcept
Returns the largest of all previously added values.
If no values have been added yet, this will return negative infinity.
template<typename FloatType > size_t juce::StatisticsAccumulator< FloatType >::getCount () const noexcept
Returns how many values have been added to this accumulator.
The documentation for this class was generated from the following file:
juce_StatisticsAccumulator.h