JUCE: juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse > Class Template Reference
juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse > Class Template Reference
containers
An array designed for holding objects.
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
OwnedArray () noexcept
Creates an empty array.
~OwnedArray ()
Deletes the array and also deletes any objects inside it.
OwnedArray (OwnedArray &&other) noexcept
Move constructor.
OwnedArray & operator= (OwnedArray &&other) noexcept
Move assignment operator.
void clear (bool deleteObjects=true)
Clears the array, optionally deleting the objects inside it first.
void clearQuick (bool deleteObjects)
Clears the array, optionally deleting the objects inside it first.
int size () const noexcept
Returns the number of items currently in the array.
bool isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
ObjectClass * operator[] (const int index) const noexcept
Returns a pointer to the object at this index in the array.
ObjectClass * getUnchecked (const int index) const noexcept
Returns a pointer to the object at this index in the array, without checking whether the index is in-range.
ObjectClass * getFirst () const noexcept
Returns a pointer to the first object in the array.
ObjectClass * getLast () const noexcept
Returns a pointer to the last object in the array.
ObjectClass ** getRawDataPointer () noexcept
Returns a pointer to the actual array data.
ObjectClass ** begin () const noexcept
Returns a pointer to the first element in the array.
ObjectClass ** end () const noexcept
Returns a pointer to the element which follows the last element in the array.
int indexOf (const ObjectClass *objectToLookFor) const noexcept
Finds the index of an object which might be in the array.
bool contains (const ObjectClass *objectToLookFor) const noexcept
Returns true if the array contains a specified object.
ObjectClass * add (ObjectClass *newObject) noexcept
Appends a new object to the end of the array.
ObjectClass * insert (int indexToInsertAt, ObjectClass *newObject) noexcept
Inserts a new object into the array at the given index.
void insertArray (int indexToInsertAt, ObjectClass *const *newObjects, int numberOfElements)
Inserts an array of values into this array at a given position.
bool addIfNotAlreadyThere (ObjectClass *newObject) noexcept
Appends a new object at the end of the array as long as the array doesn't already contain it.
ObjectClass * set (int indexToChange, ObjectClass *newObject, bool deleteOldElement=true)
Replaces an object in the array with a different one.
template<class OtherArrayType >
void addArray (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
Adds elements from another array to the end of this array.
template<class OtherArrayType >
void addCopiesOf (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
Adds copies of the elements in another array to the end of this array.
template<class ElementComparator >
int addSorted (ElementComparator &comparator, ObjectClass *const newObject) noexcept
Inserts a new object into the array assuming that the array is sorted.
template<typename ElementComparator >
int indexOfSorted (ElementComparator &comparator, const ObjectClass *const objectToLookFor) const noexcept
Finds the index of an object in the array, assuming that the array is sorted.
void remove (int indexToRemove, bool deleteObject=true)
Removes an object from the array.
ObjectClass * removeAndReturn (int indexToRemove)
Removes and returns an object from the array without deleting it.
void removeObject (const ObjectClass *objectToRemove, bool deleteObject=true)
Removes a specified object from the array.
void removeRange (int startIndex, int numberToRemove, bool deleteObjects=true)
Removes a range of objects from the array.
void removeLast (int howManyToRemove=1, bool deleteObjects=true)
Removes the last n objects from the array.
void swap (int index1, int index2) noexcept
Swaps a pair of objects in the array.
void move (int currentIndex, int newIndex) noexcept
Moves one of the objects to a different position.
template<class OtherArrayType >
void swapWith (OtherArrayType &otherArray) noexcept
This swaps the contents of this array with those of another array.
void minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the array.
void ensureStorageAllocated (const int minNumElements) noexcept
Increases the array's internal storage to hold a minimum number of elements.
template<class ElementComparator >
void sort (ElementComparator &comparator, bool retainOrderOfEquivalentItems=false) const noexcept
Sorts the elements in the array.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this array.
Detailed Description
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection>
class juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >
An array designed for holding objects.
This holds a list of pointers to objects, and will automatically delete the objects when they are removed from the array, or when the array is itself deleted.
Declare it in the form: OwnedArray<MyObjectClass>
..and then add new objects, e.g. myOwnedArray.add (new MyObjectClass());
After adding objects, they are 'owned' by the array and will be deleted when removed or replaced.
To make all the array's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See Also
Array, ReferenceCountedArray, StringArray, CriticalSection
Member Typedef Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> typedef TypeOfCriticalSectionToUse::ScopedLockType juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::OwnedArray () noexcept
Creates an empty array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::~OwnedArray ()
Deletes the array and also deletes any objects inside it.
To get rid of the array without deleting its objects, use its clear (false) method before deleting it.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::OwnedArray (OwnedArray< ObjectClass, TypeOfCriticalSectionToUse > && other) noexcept
Move constructor.
Member Function Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> OwnedArray& juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator= (OwnedArray< ObjectClass, TypeOfCriticalSectionToUse > && other) noexcept
Move assignment operator.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::clear (bool deleteObjects = true)
Clears the array, optionally deleting the objects inside it first.
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::removeLast().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::clearQuick (bool deleteObjects)
Clears the array, optionally deleting the objects inside it first.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> int juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::size () const noexcept
Returns the number of items currently in the array.
See Also
operator[]
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::isEmpty(), juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::prepare(), juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::process(), and juce::OwnedArray< juce::AudioProcessorParameter >::sort().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator[] (const int index) const noexcept
Returns a pointer to the object at this index in the array.
If the index is out-of-range, this will return a null pointer, (and it could be null anyway, because it's ok for the array to hold null pointers as well as objects).
See Also
getUnchecked
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getUnchecked (const int index) const noexcept
Returns a pointer to the object at this index in the array, without checking whether the index is in-range.
This is a faster and less safe version of operator[] which doesn't check the index passed in, so it can be used when you're sure the index is always going to be legal.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getFirst () const noexcept
Returns a pointer to the first object in the array.
This will return a null pointer if the array's empty.
See Also
getLast
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getLast () const noexcept
Returns a pointer to the last object in the array.
This will return a null pointer if the array's empty.
See Also
getFirst
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getRawDataPointer () noexcept
Returns a pointer to the actual array data.
This pointer will only be valid until the next time a non-const method is called on the array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::begin () const noexcept
Returns a pointer to the first element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::end () const noexcept
Returns a pointer to the element which follows the last element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> int juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::indexOf (const ObjectClass * objectToLookFor) const noexcept
Finds the index of an object which might be in the array.
Parameters
objectToLookFor the object to look for
Returns
the index at which the object was found, or -1 if it's not found
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::contains (const ObjectClass * objectToLookFor) const noexcept
Returns true if the array contains a specified object.
Parameters
objectToLookFor the object to look for
Returns
true if the object is in the array
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::addIfNotAlreadyThere().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::add (ObjectClass * newObject) noexcept
Appends a new object to the end of the array.
Note that the this object will be deleted by the OwnedArray when it is removed, so be careful not to delete it somewhere else.
Also be careful not to add the same object to the array more than once, as this will obviously cause deletion of dangling pointers.
Parameters
newObject the new object to add to the array
Returns
the new object that was added
See Also
set, insert, addIfNotAlreadyThere, addSorted
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::addIfNotAlreadyThere(), juce::OwnedArray< juce::AudioProcessorParameter >::insert(), and juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::prepare().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::insert (int indexToInsertAt, ObjectClass * newObject) noexcept
Inserts a new object into the array at the given index.
Note that the this object will be deleted by the OwnedArray when it is removed, so be careful not to delete it somewhere else.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Be careful not to add the same object to the array more than once, as this will obviously cause deletion of dangling pointers.
Parameters
indexToInsertAt the index at which the new element should be inserted
newObject the new object to add to the array
Returns
the new object that was added
See Also
add, addSorted, addIfNotAlreadyThere, set
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::addSorted().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::insertArray (int indexToInsertAt, ObjectClass *const * newObjects, int numberOfElements)
Inserts an array of values into this array at a given position.
If the index is less than 0 or greater than the size of the array, the new elements will be added to the end of the array. Otherwise, they will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the first new element should be inserted
newObjects the new values to add to the array
numberOfElements how many items are in the array
See Also
insert, add, addSorted, set
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addIfNotAlreadyThere (ObjectClass * newObject) noexcept
Appends a new object at the end of the array as long as the array doesn't already contain it.
If the array already contains a matching object, nothing will be done.
Parameters
newObject the new object to add to the array
Returns
true if the new object was added, false otherwise
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::set (int indexToChange, ObjectClass * newObject, bool deleteOldElement = true)
Replaces an object in the array with a different one.
If the index is less than zero, this method does nothing. If the index is beyond the end of the array, the new object is added to the end of the array.
Be careful not to add the same object to the array more than once, as this will obviously cause deletion of dangling pointers.
Parameters
indexToChange the index whose value you want to change
newObject the new value to set for this index.
deleteOldElement whether to delete the object that's being replaced with the new one
See Also
add, insert, remove
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addArray (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
Adds elements from another array to the end of this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addCopiesOf (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
Adds copies of the elements in another array to the end of this array.
The other array must be either an OwnedArray of a compatible type of object, or an Array containing pointers to the same kind of object. The objects involved must provide a copy constructor, and this will be used to create new copies of each element, and add them to this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > int juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addSorted (ElementComparator & comparator, ObjectClass *const newObject) noexcept
Inserts a new object into the array assuming that the array is sorted.
This will use a comparator to find the position at which the new object should go. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort method for details about this object's structure
newObject the new object to insert to the array
Returns
the index at which the new object was added
See Also
add, sort, indexOfSorted
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<typename ElementComparator > int juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::indexOfSorted (ElementComparator & comparator, const ObjectClass *const objectToLookFor) const noexcept
Finds the index of an object in the array, assuming that the array is sorted.
This will use a comparator to do a binary-chop to find the index of the given element, if it exists. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
objectToLookFor the object to search for
Returns
the index of the element, or -1 if it's not found
See Also
addSorted, sort
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::remove (int indexToRemove, bool deleteObject = true)
Removes an object from the array.
This will remove the object at a given index (optionally also deleting it) and move back all the subsequent objects to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
deleteObject whether to delete the object that is removed
See Also
removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeAndReturn (int indexToRemove)
Removes and returns an object from the array without deleting it.
This will remove the object at a given index and return it, moving back all the subsequent objects to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
See Also
remove, removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeObject (const ObjectClass * objectToRemove, bool deleteObject = true)
Removes a specified object from the array.
If the item isn't found, no action is taken.
Parameters
objectToRemove the object to try to remove
deleteObject whether to delete the object (if it's found)
See Also
remove, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeRange (int startIndex, int numberToRemove, bool deleteObjects = true)
Removes a range of objects from the array.
This will remove a set of objects, starting from the given index, and move any subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters
startIndex the index of the first object to remove
numberToRemove how many objects should be removed
deleteObjects whether to delete the objects that get removed
See Also
remove, removeObject
Referenced by juce::dsp::ProcessorDuplicator< MonoProcessorType, StateType >::prepare(), and juce::OwnedArray< juce::AudioProcessorParameter >::removeLast().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeLast (int howManyToRemove = 1, bool deleteObjects = true)
Removes the last n objects from the array.
Parameters
howManyToRemove how many objects to remove from the end of the array
deleteObjects whether to also delete the objects that are removed
See Also
remove, removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::swap (int index1, int index2) noexcept
Swaps a pair of objects in the array.
If either of the indexes passed in is out-of-range, nothing will happen, otherwise the two objects at these positions will be exchanged.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::move (int currentIndex, int newIndex) noexcept
Moves one of the objects to a different position.
This will move the object to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the object to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this object to end up. If this is less than zero, it will be moved to the end of the array
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::swapWith (OtherArrayType & otherArray) noexcept
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::remove(), juce::OwnedArray< juce::AudioProcessorParameter >::removeAndReturn(), and juce::OwnedArray< juce::AudioProcessorParameter >::removeRange().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::ensureStorageAllocated (const int minNumElements) noexcept
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > void juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::sort (ElementComparator & comparator, bool retainOrderOfEquivalentItems = false) const noexcept
Sorts the elements in the array.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
int compareElements (ElementType* first, ElementType* second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
See Also
sortArray, indexOfSorted
Referenced by juce::ValueTree::sort().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> const TypeOfCriticalSectionToUse& juce::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getLock () const noexcept
Returns the CriticalSection that locks this array.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by juce::OwnedArray< juce::AudioProcessorParameter >::add(), juce::OwnedArray< juce::AudioProcessorParameter >::addArray(), juce::OwnedArray< juce::AudioProcessorParameter >::addCopiesOf(), juce::OwnedArray< juce::AudioProcessorParameter >::addIfNotAlreadyThere(), juce::OwnedArray< juce::AudioProcessorParameter >::addSorted(), juce::OwnedArray< juce::AudioProcessorParameter >::clear(), juce::OwnedArray< juce::AudioProcessorParameter >::clearQuick(), juce::OwnedArray< juce::AudioProcessorParameter >::contains(), juce::OwnedArray< juce::AudioProcessorParameter >::ensureStorageAllocated(), juce::OwnedArray< juce::AudioProcessorParameter >::getFirst(), juce::OwnedArray< juce::AudioProcessorParameter >::getLast(), juce::OwnedArray< juce::AudioProcessorParameter >::getUnchecked(), juce::OwnedArray< juce::AudioProcessorParameter >::indexOf(), juce::OwnedArray< juce::AudioProcessorParameter >::indexOfSorted(), juce::OwnedArray< juce::AudioProcessorParameter >::insert(), juce::OwnedArray< juce::AudioProcessorParameter >::insertArray(), juce::OwnedArray< juce::AudioProcessorParameter >::minimiseStorageOverheads(), juce::OwnedArray< juce::AudioProcessorParameter >::move(), juce::OwnedArray< juce::AudioProcessorParameter >::operator=(), juce::OwnedArray< juce::AudioProcessorParameter >::operator[](), juce::OwnedArray< juce::AudioProcessorParameter >::remove(), juce::OwnedArray< juce::AudioProcessorParameter >::removeAndReturn(), juce::OwnedArray< juce::AudioProcessorParameter >::removeLast(), juce::OwnedArray< juce::AudioProcessorParameter >::removeObject(), juce::OwnedArray< juce::AudioProcessorParameter >::removeRange(), juce::OwnedArray< juce::AudioProcessorParameter >::set(), juce::OwnedArray< juce::AudioProcessorParameter >::sort(), juce::OwnedArray< juce::AudioProcessorParameter >::swap(), and juce::OwnedArray< juce::AudioProcessorParameter >::swapWith().
The documentation for this class was generated from the following file:
juce_OwnedArray.h