JUCE: juce::CharPointer_UTF16 Class Reference
juce::CharPointer_UTF16 Class Reference
text
Wraps a pointer to a null-terminated UTF-16 character string, and provides various methods to operate on the data.
Public Types
enum { byteOrderMarkBE1 = 0xfe, byteOrderMarkBE2 = 0xff, byteOrderMarkLE1 = 0xff, byteOrderMarkLE2 = 0xfe }
These values are the byte-order-mark (BOM) values for a UTF-16 stream.
typedef int16 CharType
Public Member Functions
CharPointer_UTF16 (const CharType *rawPointer) noexcept
CharPointer_UTF16 (const CharPointer_UTF16 &other) noexcept
CharPointer_UTF16 operator= (CharPointer_UTF16 other) noexcept
CharPointer_UTF16 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF16 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_UTF16 other) const noexcept
bool operator<= (CharPointer_UTF16 other) const noexcept
bool operator< (CharPointer_UTF16 other) const noexcept
bool operator>= (CharPointer_UTF16 other) const noexcept
bool operator> (CharPointer_UTF16 other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF16 operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF16 operator-- () noexcept
Moves this pointer back to the previous character in the string.
juce_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF16 operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
juce_wchar operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF16 operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF16 operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void write (juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (CharPointer_UTF16 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_UTF16 findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
template<typename CharPointer >
void writeAll (CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
void writeAll (CharPointer_UTF16 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
size_t writeWithDestByteLimit (CharPointer src, size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
void writeWithCharLimit (CharPointer src, int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
int compare (CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int compareIgnoreCase (CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareIgnoreCaseUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int indexOf (CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (juce_wchar charToFind, bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
bool isDigit () const noexcept
Returns true if the first character of this string is a digit.
bool isLetter () const noexcept
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
bool isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
juce_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
juce_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_UTF16 findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
CharPointer_UTF16 atomicSwap (CharPointer_UTF16 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
Static Public Member Functions
static size_t getBytesRequiredFor (juce_wchar charToWrite) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer >
static size_t getBytesRequiredFor (CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (juce_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
static bool isByteOrderMarkBigEndian (const void *possibleByteOrder) noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (big endian).
static bool isByteOrderMarkLittleEndian (const void *possibleByteOrder) noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (little endian).
Detailed Description
Wraps a pointer to a null-terminated UTF-16 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF8, CharPointer_UTF32
Member Typedef Documentation
typedef int16 juce::CharPointer_UTF16::CharType
Member Enumeration Documentation
anonymous enum
These values are the byte-order-mark (BOM) values for a UTF-16 stream.
Enumerator
byteOrderMarkBE1
byteOrderMarkBE2
byteOrderMarkLE1
byteOrderMarkLE2
Constructor & Destructor Documentation
juce::CharPointer_UTF16::CharPointer_UTF16 (const CharType * rawPointer) explicit noexcept
Referenced by atomicSwap(), and findTerminatingNull().
juce::CharPointer_UTF16::CharPointer_UTF16 (const CharPointer_UTF16 & other) noexcept
Member Function Documentation
CharPointer_UTF16 juce::CharPointer_UTF16::operator= (CharPointer_UTF16 other) noexcept
CharPointer_UTF16 juce::CharPointer_UTF16::operator= (const CharType * text) noexcept
bool juce::CharPointer_UTF16::operator== (CharPointer_UTF16 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool juce::CharPointer_UTF16::operator!= (CharPointer_UTF16 other) const noexcept
bool juce::CharPointer_UTF16::operator<= (CharPointer_UTF16 other) const noexcept
bool juce::CharPointer_UTF16::operator< (CharPointer_UTF16 other) const noexcept
bool juce::CharPointer_UTF16::operator>= (CharPointer_UTF16 other) const noexcept
bool juce::CharPointer_UTF16::operator> (CharPointer_UTF16 other) const noexcept
CharType* juce::CharPointer_UTF16::getAddress () const noexcept
Returns the address that this pointer is pointing to.
juce::CharPointer_UTF16::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool juce::CharPointer_UTF16::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool juce::CharPointer_UTF16::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar juce::CharPointer_UTF16::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF16 juce::CharPointer_UTF16::operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF16 juce::CharPointer_UTF16::operator-- () noexcept
Moves this pointer back to the previous character in the string.
juce_wchar juce::CharPointer_UTF16::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF16 juce::CharPointer_UTF16::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void juce::CharPointer_UTF16::operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
Referenced by operator-=().
void juce::CharPointer_UTF16::operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
References operator+=().
juce_wchar juce::CharPointer_UTF16::operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF16 juce::CharPointer_UTF16::operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF16 juce::CharPointer_UTF16::operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void juce::CharPointer_UTF16::write (juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void juce::CharPointer_UTF16::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t juce::CharPointer_UTF16::length () const noexcept
Returns the number of characters in this string.
size_t juce::CharPointer_UTF16::lengthUpTo (size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References juce::CharacterFunctions::lengthUpTo().
size_t juce::CharPointer_UTF16::lengthUpTo (CharPointer_UTF16 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References juce::CharacterFunctions::lengthUpTo().
size_t juce::CharPointer_UTF16::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
static size_t juce::CharPointer_UTF16::getBytesRequiredFor (juce_wchar charToWrite) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Referenced by getBytesRequiredFor().
template<class CharPointer > static size_t juce::CharPointer_UTF16::getBytesRequiredFor (CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
References getBytesRequiredFor().
CharPointer_UTF16 juce::CharPointer_UTF16::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_UTF16().
template<typename CharPointer > void juce::CharPointer_UTF16::writeAll (CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References juce::CharacterFunctions::copyAll().
void juce::CharPointer_UTF16::writeAll (CharPointer_UTF16 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer > size_t juce::CharPointer_UTF16::writeWithDestByteLimit (CharPointer src, size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References juce::CharacterFunctions::copyWithDestByteLimit().
template<typename CharPointer > void juce::CharPointer_UTF16::writeWithCharLimit (CharPointer src, int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References juce::CharacterFunctions::copyWithCharLimit().
template<typename CharPointer > int juce::CharPointer_UTF16::compare (CharPointer other) const noexcept
Compares this string with another one.
References juce::CharacterFunctions::compare().
template<typename CharPointer > int juce::CharPointer_UTF16::compareUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References juce::CharacterFunctions::compareUpTo().
template<typename CharPointer > int juce::CharPointer_UTF16::compareIgnoreCase (CharPointer other) const noexcept
Compares this string with another one.
References juce::CharacterFunctions::compareIgnoreCase().
template<typename CharPointer > int juce::CharPointer_UTF16::compareIgnoreCaseUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References juce::CharacterFunctions::compareIgnoreCaseUpTo().
template<typename CharPointer > int juce::CharPointer_UTF16::indexOf (CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References juce::CharacterFunctions::indexOf().
int juce::CharPointer_UTF16::indexOf (juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References juce::CharacterFunctions::indexOfChar().
int juce::CharPointer_UTF16::indexOf (juce_wchar charToFind, bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References juce::CharacterFunctions::indexOfChar(), and juce::CharacterFunctions::indexOfCharIgnoreCase().
bool juce::CharPointer_UTF16::isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
References juce::CharacterFunctions::isWhitespace().
bool juce::CharPointer_UTF16::isDigit () const noexcept
Returns true if the first character of this string is a digit.
References juce::CharacterFunctions::isDigit().
bool juce::CharPointer_UTF16::isLetter () const noexcept
Returns true if the first character of this string is a letter.
References juce::CharacterFunctions::isLetter().
bool juce::CharPointer_UTF16::isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
References juce::CharacterFunctions::isLetterOrDigit().
bool juce::CharPointer_UTF16::isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
References juce::CharacterFunctions::isUpperCase().
bool juce::CharPointer_UTF16::isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
References juce::CharacterFunctions::isLowerCase().
juce_wchar juce::CharPointer_UTF16::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References juce::CharacterFunctions::toUpperCase().
juce_wchar juce::CharPointer_UTF16::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References juce::CharacterFunctions::toLowerCase().
int juce::CharPointer_UTF16::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 juce::CharPointer_UTF16::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double juce::CharPointer_UTF16::getDoubleValue () const noexcept
Parses this string as a floating point double.
References juce::CharacterFunctions::getDoubleValue().
CharPointer_UTF16 juce::CharPointer_UTF16::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References juce::CharacterFunctions::findEndOfWhitespace().
static bool juce::CharPointer_UTF16::canRepresent (juce_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool juce::CharPointer_UTF16::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
CharPointer_UTF16 juce::CharPointer_UTF16::atomicSwap (CharPointer_UTF16 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
References CharPointer_UTF16().
static bool juce::CharPointer_UTF16::isByteOrderMarkBigEndian (const void * possibleByteOrder) static noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (big endian).
The pointer must not be null, and must contain at least two valid bytes.
References byteOrderMarkBE1, byteOrderMarkBE2, and jassert.
static bool juce::CharPointer_UTF16::isByteOrderMarkLittleEndian (const void * possibleByteOrder) static noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (little endian).
The pointer must not be null, and must contain at least two valid bytes.
References byteOrderMarkLE1, byteOrderMarkLE2, and jassert.
The documentation for this class was generated from the following file:
juce_CharPointer_UTF16.h