JUCE: juce::RectangleList< ValueType > Class Template Reference
juce::RectangleList< ValueType > Class Template Reference
geometry
Maintains a set of rectangles as a complex region.
Public Types
typedef Rectangle< ValueType > RectangleType
Public Member Functions
RectangleList () noexcept
Creates an empty RectangleList.
RectangleList (const RectangleList &other)
Creates a copy of another list.
RectangleList (const RectangleType &rect)
Creates a list containing just one rectangle.
RectangleList & operator= (const RectangleList &other)
Copies this list from another one.
RectangleList (RectangleList &&other) noexcept
Move constructor.
RectangleList & operator= (RectangleList &&other) noexcept
Move assignment operator.
bool isEmpty () const noexcept
Returns true if the region is empty.
int getNumRectangles () const noexcept
Returns the number of rectangles in the list.
RectangleType getRectangle (int index) const noexcept
Returns one of the rectangles at a particular index.
void clear ()
Removes all rectangles to leave an empty region.
void add (const RectangleType &rect)
Merges a new rectangle into the list.
void add (ValueType x, ValueType y, ValueType width, ValueType height)
Merges a new rectangle into the list.
void addWithoutMerging (const RectangleType &rect)
Dumbly adds a rectangle to the list without checking for overlaps.
void add (const RectangleList &other)
Merges another rectangle list into this one.
void subtract (const RectangleType &rect)
Removes a rectangular region from the list.
bool subtract (const RectangleList &otherList)
Removes all areas in another RectangleList from this one.
bool clipTo (const RectangleType &rect)
Removes any areas of the region that lie outside a given rectangle.
template<typename OtherValueType >
bool clipTo (const RectangleList< OtherValueType > &other)
Removes any areas of the region that lie outside a given rectangle list.
bool getIntersectionWith (const RectangleType &rect, RectangleList &destRegion) const
Creates a region which is the result of clipping this one to a given rectangle.
void swapWith (RectangleList &otherList) noexcept
Swaps the contents of this and another list.
bool containsPoint (Point< ValueType > point) const noexcept
Checks whether the region contains a given point.
bool containsPoint (ValueType x, ValueType y) const noexcept
Checks whether the region contains a given point.
bool containsRectangle (const RectangleType &rectangleToCheck) const
Checks whether the region contains the whole of a given rectangle.
bool intersectsRectangle (const RectangleType &rectangleToCheck) const noexcept
Checks whether the region contains any part of a given rectangle.
bool intersects (const RectangleList &other) const noexcept
Checks whether this region intersects any part of another one.
RectangleType getBounds () const noexcept
Returns the smallest rectangle that can enclose the whole of this region.
void consolidate ()
Optimises the list into a minimum number of constituent rectangles.
void offsetAll (Point< ValueType > offset) noexcept
Adds an x and y value to all the coordinates.
void offsetAll (ValueType dx, ValueType dy) noexcept
Adds an x and y value to all the coordinates.
template<typename ScaleType >
void scaleAll (ScaleType scaleFactor) noexcept
Scales all the coordinates.
void transformAll (const AffineTransform &transform) noexcept
Applies a transform to all the rectangles.
Path toPath () const
Creates a Path object to represent this region.
const RectangleType * begin () const noexcept
Standard method for iterating the rectangles in the list.
const RectangleType * end () const noexcept
Standard method for iterating the rectangles in the list.
void ensureStorageAllocated (int minNumRectangles)
Increases the internal storage to hold a minimum number of rectangles.
Detailed Description
template<typename ValueType>
class juce::RectangleList< ValueType >
Maintains a set of rectangles as a complex region.
This class allows a set of rectangles to be treated as a solid shape, and can add and remove rectangular sections of it, and simplify overlapping or adjacent rectangles.
See Also
Rectangle
Member Typedef Documentation
template<typename ValueType> typedef Rectangle<ValueType> juce::RectangleList< ValueType >::RectangleType
Constructor & Destructor Documentation
template<typename ValueType> juce::RectangleList< ValueType >::RectangleList () noexcept
Creates an empty RectangleList.
template<typename ValueType> juce::RectangleList< ValueType >::RectangleList (const RectangleList< ValueType > & other)
Creates a copy of another list.
template<typename ValueType> juce::RectangleList< ValueType >::RectangleList (const RectangleType & rect)
Creates a list containing just one rectangle.
template<typename ValueType> juce::RectangleList< ValueType >::RectangleList (RectangleList< ValueType > && other) noexcept
Move constructor.
Member Function Documentation
template<typename ValueType> RectangleList& juce::RectangleList< ValueType >::operator= (const RectangleList< ValueType > & other)
Copies this list from another one.
template<typename ValueType> RectangleList& juce::RectangleList< ValueType >::operator= (RectangleList< ValueType > && other) noexcept
Move assignment operator.
template<typename ValueType> bool juce::RectangleList< ValueType >::isEmpty () const noexcept
Returns true if the region is empty.
Referenced by juce::RectangleList< int >::add(), juce::RectangleList< int >::clipTo(), juce::RectangleList< int >::containsRectangle(), juce::RectangleList< int >::getBounds(), juce::RectangleList< int >::getIntersectionWith(), and juce::RectangleList< int >::subtract().
template<typename ValueType> int juce::RectangleList< ValueType >::getNumRectangles () const noexcept
Returns the number of rectangles in the list.
template<typename ValueType> RectangleType juce::RectangleList< ValueType >::getRectangle (int index) const noexcept
Returns one of the rectangles at a particular index.
Returns
the rectangle at the index, or an empty rectangle if the index is out-of-range.
template<typename ValueType> void juce::RectangleList< ValueType >::clear ()
Removes all rectangles to leave an empty region.
Referenced by juce::RectangleList< int >::clipTo(), and juce::RectangleList< int >::getIntersectionWith().
template<typename ValueType> void juce::RectangleList< ValueType >::add (const RectangleType & rect)
Merges a new rectangle into the list.
The rectangle being added will first be clipped to remove any parts of it that overlap existing rectangles in the list, and adjacent rectangles will be merged into it.
The rectangle can have any size and may be empty, but if it's floating point then it's expected to not contain any INF values.
Referenced by juce::RectangleList< int >::add().
template<typename ValueType> void juce::RectangleList< ValueType >::add (ValueType x, ValueType y, ValueType width, ValueType height)
Merges a new rectangle into the list.
The rectangle being added will first be clipped to remove any parts of it that overlap existing rectangles in the list.
template<typename ValueType> void juce::RectangleList< ValueType >::addWithoutMerging (const RectangleType & rect)
Dumbly adds a rectangle to the list without checking for overlaps.
This simply adds the rectangle to the end, it doesn't merge it or remove any overlapping bits.
The rectangle can have any size and may be empty, but if it's floating point then it's expected to not contain any INF values.
Referenced by juce::RectangleList< int >::RectangleList().
template<typename ValueType> void juce::RectangleList< ValueType >::add (const RectangleList< ValueType > & other)
Merges another rectangle list into this one.
Any overlaps between the two lists will be clipped, so that the result is the union of both lists.
template<typename ValueType> void juce::RectangleList< ValueType >::subtract (const RectangleType & rect)
Removes a rectangular region from the list.
Any rectangles in the list which overlap this will be clipped and subdivided if necessary.
Referenced by juce::RectangleList< int >::add(), juce::RectangleList< int >::containsRectangle(), and juce::RectangleList< int >::subtract().
template<typename ValueType> bool juce::RectangleList< ValueType >::subtract (const RectangleList< ValueType > & otherList)
Removes all areas in another RectangleList from this one.
Any rectangles in the list which overlap this will be clipped and subdivided if necessary.
Returns
true if the resulting list is non-empty.
template<typename ValueType> bool juce::RectangleList< ValueType >::clipTo (const RectangleType & rect)
Removes any areas of the region that lie outside a given rectangle.
Any rectangles in the list which overlap this will be clipped and subdivided if necessary.
Returns true if the resulting region is not empty, false if it is empty.
See Also
getIntersectionWith
template<typename ValueType> template<typename OtherValueType > bool juce::RectangleList< ValueType >::clipTo (const RectangleList< OtherValueType > & other)
Removes any areas of the region that lie outside a given rectangle list.
Any rectangles in this object which overlap the specified list will be clipped and subdivided if necessary.
Returns true if the resulting region is not empty, false if it is empty.
See Also
getIntersectionWith
template<typename ValueType> bool juce::RectangleList< ValueType >::getIntersectionWith (const RectangleType & rect, RectangleList< ValueType > & destRegion) const
Creates a region which is the result of clipping this one to a given rectangle.
Unlike the other clipTo method, this one doesn't affect this object - it puts the resulting region into the list whose reference is passed-in.
Returns true if the resulting region is not empty, false if it is empty.
See Also
clipTo
template<typename ValueType> void juce::RectangleList< ValueType >::swapWith (RectangleList< ValueType > & otherList) noexcept
Swaps the contents of this and another list.
This swaps their internal pointers, so is hugely faster than using copy-by-value to swap them.
Referenced by juce::RectangleList< int >::clipTo().
template<typename ValueType> bool juce::RectangleList< ValueType >::containsPoint (Point< ValueType > point) const noexcept
Checks whether the region contains a given point.
Returns
true if the point lies within one of the rectangles in the list
Referenced by juce::RectangleList< int >::containsPoint().
template<typename ValueType> bool juce::RectangleList< ValueType >::containsPoint (ValueType x, ValueType y) const noexcept
Checks whether the region contains a given point.
Returns
true if the point lies within one of the rectangles in the list
template<typename ValueType> bool juce::RectangleList< ValueType >::containsRectangle (const RectangleType & rectangleToCheck) const
Checks whether the region contains the whole of a given rectangle.
Returns
true all parts of the rectangle passed in lie within the region defined by this object
See Also
intersectsRectangle, containsPoint
template<typename ValueType> bool juce::RectangleList< ValueType >::intersectsRectangle (const RectangleType & rectangleToCheck) const noexcept
Checks whether the region contains any part of a given rectangle.
Returns
true if any part of the rectangle passed in lies within the region defined by this object
See Also
containsRectangle
template<typename ValueType> bool juce::RectangleList< ValueType >::intersects (const RectangleList< ValueType > & other) const noexcept
Checks whether this region intersects any part of another one.
See Also
intersectsRectangle
template<typename ValueType> RectangleType juce::RectangleList< ValueType >::getBounds () const noexcept
Returns the smallest rectangle that can enclose the whole of this region.
template<typename ValueType> void juce::RectangleList< ValueType >::consolidate ()
Optimises the list into a minimum number of constituent rectangles.
This will try to combine any adjacent rectangles into larger ones where possible, to simplify lists that might have been fragmented by repeated add/subtract calls.
template<typename ValueType> void juce::RectangleList< ValueType >::offsetAll (Point< ValueType > offset) noexcept
Adds an x and y value to all the coordinates.
Referenced by juce::RectangleList< int >::offsetAll().
template<typename ValueType> void juce::RectangleList< ValueType >::offsetAll (ValueType dx, ValueType dy) noexcept
Adds an x and y value to all the coordinates.
template<typename ValueType> template<typename ScaleType > void juce::RectangleList< ValueType >::scaleAll (ScaleType scaleFactor) noexcept
Scales all the coordinates.
template<typename ValueType> void juce::RectangleList< ValueType >::transformAll (const AffineTransform & transform) noexcept
Applies a transform to all the rectangles.
Obviously this will create a mess if the transform involves any rotation or skewing.
template<typename ValueType> Path juce::RectangleList< ValueType >::toPath () const
Creates a Path object to represent this region.
template<typename ValueType> const RectangleType* juce::RectangleList< ValueType >::begin () const noexcept
Standard method for iterating the rectangles in the list.
template<typename ValueType> const RectangleType* juce::RectangleList< ValueType >::end () const noexcept
Standard method for iterating the rectangles in the list.
template<typename ValueType> void juce::RectangleList< ValueType >::ensureStorageAllocated (int minNumRectangles)
Increases the internal storage to hold a minimum number of rectangles.
Calling this before adding a large number of rectangles means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
See Also
Array::ensureStorageAllocated
The documentation for this class was generated from the following file:
juce_RectangleList.h