JUCE: juce::SelectedItemSet< SelectableItemType > Class Template Reference
juce::SelectedItemSet< SelectableItemType > Class Template Reference
mouse
Manages a list of selectable items.
Public Types
typedef SelectableItemType ItemType
typedef Array< SelectableItemType > ItemArray
typedef
TypeHelpers::ParameterType
< SelectableItemType >::type ParameterType
Public Member Functions
SelectedItemSet ()
Creates an empty set.
SelectedItemSet (const ItemArray &items)
Creates a set based on an array of items.
SelectedItemSet (const SelectedItemSet &other)
Creates a copy of another set.
SelectedItemSet & operator= (const SelectedItemSet &other)
Creates a copy of another set.
void selectOnly (ParameterType item)
Clears any other currently selected items, and selects this item.
void addToSelection (ParameterType item)
Selects an item.
void addToSelectionBasedOnModifiers (ParameterType item, ModifierKeys modifiers)
Selects or deselects an item.
bool addToSelectionOnMouseDown (ParameterType item, ModifierKeys modifiers)
Selects or deselects items that can also be dragged, based on a mouse-down event.
void addToSelectionOnMouseUp (ParameterType item, ModifierKeys modifiers, const bool wasItemDragged, const bool resultOfMouseDownSelectMethod)
Selects or deselects items that can also be dragged, based on a mouse-up event.
void deselect (ParameterType item)
Deselects an item.
void deselectAll ()
Deselects all items.
int getNumSelected () const noexcept
Returns the number of currently selected items.
SelectableItemType getSelectedItem (const int index) const
Returns one of the currently selected items.
bool isSelected (ParameterType item) const noexcept
True if this item is currently selected.
const ItemArray & getItemArray () const noexcept
Provides access to the array of items.
SelectableItemType * begin () const noexcept
Provides iterator access to the array of items.
SelectableItemType * end () const noexcept
Provides iterator access to the array of items.
virtual void itemSelected (SelectableItemType)
Can be overridden to do special handling when an item is selected.
virtual void itemDeselected (SelectableItemType)
Can be overridden to do special handling when an item is deselected.
void changed ()
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
void changed (const bool synchronous)
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
Public Member Functions inherited from juce::ChangeBroadcaster
ChangeBroadcaster () noexcept
Creates an ChangeBroadcaster.
virtual ~ChangeBroadcaster ()
Destructor.
void addChangeListener (ChangeListener *listener)
Registers a listener to receive change callbacks from this broadcaster.
void removeChangeListener (ChangeListener *listener)
Unregisters a listener from the list.
void removeAllChangeListeners ()
Removes all listeners from the list.
void sendChangeMessage ()
Causes an asynchronous change message to be sent to all the registered listeners.
void sendSynchronousChangeMessage ()
Sends a synchronous change message to all the registered listeners.
void dispatchPendingMessages ()
If a change message has been sent but not yet dispatched, this will call sendSynchronousChangeMessage() to make the callback immediately.
Detailed Description
template<class SelectableItemType>
class juce::SelectedItemSet< SelectableItemType >
Manages a list of selectable items.
Use one of these to keep a track of things that the user has highlighted, like icons or things in a list.
The class is templated so that you can use it to hold either a set of pointers to objects, or a set of ID numbers or handles, for cases where each item may not always have a corresponding object.
To be informed when items are selected/deselected, register a ChangeListener with this object.
Member Typedef Documentation
template<class SelectableItemType > typedef SelectableItemType juce::SelectedItemSet< SelectableItemType >::ItemType
template<class SelectableItemType > typedef Array<SelectableItemType> juce::SelectedItemSet< SelectableItemType >::ItemArray
template<class SelectableItemType > typedef TypeHelpers::ParameterType<SelectableItemType>::type juce::SelectedItemSet< SelectableItemType >::ParameterType
Constructor & Destructor Documentation
template<class SelectableItemType > juce::SelectedItemSet< SelectableItemType >::SelectedItemSet ()
Creates an empty set.
template<class SelectableItemType > juce::SelectedItemSet< SelectableItemType >::SelectedItemSet (const ItemArray & items) explicit
Creates a set based on an array of items.
template<class SelectableItemType > juce::SelectedItemSet< SelectableItemType >::SelectedItemSet (const SelectedItemSet< SelectableItemType > & other)
Creates a copy of another set.
Member Function Documentation
template<class SelectableItemType > SelectedItemSet& juce::SelectedItemSet< SelectableItemType >::operator= (const SelectedItemSet< SelectableItemType > & other)
Creates a copy of another set.
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin(), juce::SelectedItemSet< SelectableItemType >::changed(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), juce::SelectedItemSet< SelectableItemType >::isSelected(), juce::SelectedItemSet< SelectableItemType >::itemDeselected(), juce::SelectedItemSet< SelectableItemType >::itemSelected(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn(), and juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::selectOnly (ParameterType item)
Clears any other currently selected items, and selects this item.
If this item is already the only thing selected, no change notification will be sent out.
See Also
addToSelection, addToSelectionBasedOnModifiers
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), juce::SelectedItemSet< SelectableItemType >::changed(), juce::SelectedItemSet< SelectableItemType >::deselect(), juce::SelectedItemSet< SelectableItemType >::deselectAll(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), juce::SelectedItemSet< SelectableItemType >::isSelected(), juce::SelectedItemSet< SelectableItemType >::itemSelected(), juce::jmin(), and juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::addToSelection (ParameterType item)
Selects an item.
If the item is already selected, no change notification will be sent out.
See Also
selectOnly, addToSelectionBasedOnModifiers
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), juce::SelectedItemSet< SelectableItemType >::changed(), juce::SelectedItemSet< SelectableItemType >::isSelected(), and juce::SelectedItemSet< SelectableItemType >::itemSelected().
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers (ParameterType item, ModifierKeys modifiers)
Selects or deselects an item.
This will use the modifier keys to decide whether to deselect other items first.
So if the shift key is held down, the item will be added without deselecting anything (same as calling addToSelection())
If no modifiers are down, the current selection will be cleared first (same as calling selectOnly())
If the ctrl (or command on the Mac) key is held down, the item will be toggled - so it'll be added to the set unless it's already there, in which case it'll be deselected.
If the items that you're selecting can also be dragged, you may need to use the addToSelectionOnMouseDown() and addToSelectionOnMouseUp() calls to handle the subtleties of this kind of usage.
See Also
selectOnly, addToSelection, addToSelectionOnMouseDown, addToSelectionOnMouseUp
References juce::SelectedItemSet< SelectableItemType >::addToSelection(), juce::SelectedItemSet< SelectableItemType >::deselect(), juce::ModifierKeys::isCommandDown(), juce::SelectedItemSet< SelectableItemType >::isSelected(), juce::ModifierKeys::isShiftDown(), and juce::SelectedItemSet< SelectableItemType >::selectOnly().
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown(), and juce::SelectedItemSet< SelectableItemType >::addToSelectionOnMouseUp().
template<class SelectableItemType > bool juce::SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown (ParameterType item, ModifierKeys modifiers)
Selects or deselects items that can also be dragged, based on a mouse-down event.
If you call addToSelectionOnMouseDown() at the start of your mouseDown event, and then call addToSelectionOnMouseUp() at the end of your mouseUp event, this makes it easy to handle multiple-selection of sets of objects that can also be dragged.
For example, if you have several items already selected, and you click on one of them (without dragging), then you'd expect this to deselect the other, and just select the item you clicked on. But if you had clicked on this item and dragged it, you'd have expected them all to stay selected.
When you call this method, you'll need to store the boolean result, because the addToSelectionOnMouseUp() method will need to be know this value.
See Also
addToSelectionOnMouseUp, addToSelectionBasedOnModifiers
References juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), juce::ModifierKeys::isPopupMenu(), and juce::SelectedItemSet< SelectableItemType >::isSelected().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::addToSelectionOnMouseUp (ParameterType item, ModifierKeys modifiers, const bool wasItemDragged, const bool resultOfMouseDownSelectMethod)
Selects or deselects items that can also be dragged, based on a mouse-up event.
Call this during a mouseUp callback, when you have previously called the addToSelectionOnMouseDown() method during your mouseDown event.
See addToSelectionOnMouseDown() for more info
Parameters
item the item to select (or deselect)
modifiers the modifiers from the mouse-up event
wasItemDragged true if your item was dragged during the mouse click
resultOfMouseDownSelectMethod this is the boolean return value that came back from the addToSelectionOnMouseDown() call that you should have made during the matching mouseDown event
References juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::deselect (ParameterType item)
Deselects an item.
References juce::SelectedItemSet< SelectableItemType >::changed(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOf(), juce::SelectedItemSet< SelectableItemType >::itemDeselected(), and juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn().
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), and juce::SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::deselectAll ()
Deselects all items.
References juce::SelectedItemSet< SelectableItemType >::changed(), juce::SelectedItemSet< SelectableItemType >::itemDeselected(), juce::jmin(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn(), and juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by juce::SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > int juce::SelectedItemSet< SelectableItemType >::getNumSelected () const noexcept
Returns the number of currently selected items.
See Also
getSelectedItem
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<class SelectableItemType > SelectableItemType juce::SelectedItemSet< SelectableItemType >::getSelectedItem (const int index) const
Returns one of the currently selected items.
If the index is out-of-range, this returns a default-constructed SelectableItemType.
See Also
getNumSelected
template<class SelectableItemType > bool juce::SelectedItemSet< SelectableItemType >::isSelected (ParameterType item) const noexcept
True if this item is currently selected.
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::contains().
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelection(), juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), juce::SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown(), juce::SelectedItemSet< SelectableItemType >::operator=(), and juce::SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > const ItemArray& juce::SelectedItemSet< SelectableItemType >::getItemArray () const noexcept
Provides access to the array of items.
template<class SelectableItemType > SelectableItemType* juce::SelectedItemSet< SelectableItemType >::begin () const noexcept
Provides iterator access to the array of items.
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin().
template<class SelectableItemType > SelectableItemType* juce::SelectedItemSet< SelectableItemType >::end () const noexcept
Provides iterator access to the array of items.
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end().
template<class SelectableItemType > virtual void juce::SelectedItemSet< SelectableItemType >::itemSelected (SelectableItemType) virtual
Can be overridden to do special handling when an item is selected.
For example, if the item is an object, you might want to call it and tell it that it's being selected.
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelection(), juce::SelectedItemSet< SelectableItemType >::operator=(), and juce::SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > virtual void juce::SelectedItemSet< SelectableItemType >::itemDeselected (SelectableItemType) virtual
Can be overridden to do special handling when an item is deselected.
For example, if the item is an object, you might want to call it and tell it that it's being deselected.
Referenced by juce::SelectedItemSet< SelectableItemType >::deselect(), juce::SelectedItemSet< SelectableItemType >::deselectAll(), and juce::SelectedItemSet< SelectableItemType >::operator=().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::changed ()
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
References juce::ChangeBroadcaster::sendChangeMessage().
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelection(), juce::SelectedItemSet< SelectableItemType >::deselect(), juce::SelectedItemSet< SelectableItemType >::deselectAll(), juce::SelectedItemSet< SelectableItemType >::operator=(), and juce::SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > void juce::SelectedItemSet< SelectableItemType >::changed (const bool synchronous)
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
References juce::ChangeBroadcaster::sendChangeMessage(), and juce::ChangeBroadcaster::sendSynchronousChangeMessage().
The documentation for this class was generated from the following file:
juce_SelectedItemSet.h