JUCE: juce::SparseSet< Type > Class Template Reference
juce::SparseSet< Type > Class Template Reference
containers
Holds a set of primitive values, storing them as a set of ranges.
Public Member Functions
SparseSet ()
Creates a new empty set.
SparseSet (const SparseSet< Type > &other)
Creates a copy of another SparseSet.
void clear ()
Clears the set.
bool isEmpty () const noexcept
Checks whether the set is empty.
Type size () const
Returns the number of values in the set.
Type operator[] (Type index) const
Returns one of the values in the set.
bool contains (const Type valueToLookFor) const
Checks whether a particular value is in the set.
int getNumRanges () const noexcept
Returns the number of contiguous blocks of values.
const Range< Type > getRange (const int rangeIndex) const
Returns one of the contiguous ranges of values stored.
Range< Type > getTotalRange () const
Returns the range between the lowest and highest values in the set.
void addRange (const Range< Type > range)
Adds a range of contiguous values to the set.
void removeRange (const Range< Type > rangeToRemove)
Removes a range of values from the set.
void invertRange (const Range< Type > range)
Does an XOR of the values in a given range.
bool overlapsRange (const Range< Type > range)
Checks whether any part of a given range overlaps any part of this set.
bool containsRange (const Range< Type > range)
Checks whether the whole of a given range is contained within this one.
bool operator== (const SparseSet< Type > &other) noexcept
bool operator!= (const SparseSet< Type > &other) noexcept
Detailed Description
template<class Type>
class juce::SparseSet< Type >
Holds a set of primitive values, storing them as a set of ranges.
This container acts like an array, but can efficiently hold large contiguous ranges of values. It's quite a specialised class, mostly useful for things like keeping the set of selected rows in a listbox.
The type used as a template parameter must be an integer type, such as int, short, int64, etc.
Constructor & Destructor Documentation
template<class Type> juce::SparseSet< Type >::SparseSet ()
Creates a new empty set.
template<class Type> juce::SparseSet< Type >::SparseSet (const SparseSet< Type > & other)
Creates a copy of another SparseSet.
Member Function Documentation
template<class Type> void juce::SparseSet< Type >::clear ()
Clears the set.
template<class Type> bool juce::SparseSet< Type >::isEmpty () const noexcept
Checks whether the set is empty.
This is much quicker than using (size() == 0).
template<class Type> Type juce::SparseSet< Type >::size () const
Returns the number of values in the set.
Because of the way the data is stored, this method can take longer if there are a lot of items in the set. Use isEmpty() for a quick test of whether there are any items.
template<class Type> Type juce::SparseSet< Type >::operator[] (Type index) const
Returns one of the values in the set.
Parameters
index the index of the value to retrieve, in the range 0 to (size() - 1).
Returns
the value at this index, or 0 if it's out-of-range
template<class Type> bool juce::SparseSet< Type >::contains (const Type valueToLookFor) const
Checks whether a particular value is in the set.
Referenced by juce::SparseSet< int >::removeRange().
template<class Type> int juce::SparseSet< Type >::getNumRanges () const noexcept
Returns the number of contiguous blocks of values.
See Also
getRange
Referenced by juce::SparseSet< int >::containsRange(), juce::SparseSet< int >::getRange(), juce::SparseSet< int >::invertRange(), and juce::SparseSet< int >::overlapsRange().
template<class Type> const Range<Type> juce::SparseSet< Type >::getRange (const int rangeIndex) const
Returns one of the contiguous ranges of values stored.
Parameters
rangeIndex the index of the range to look up, between 0 and (getNumRanges() - 1)
See Also
getTotalRange
Referenced by juce::SparseSet< int >::invertRange().
template<class Type> Range<Type> juce::SparseSet< Type >::getTotalRange () const
Returns the range between the lowest and highest values in the set.
See Also
getRange
template<class Type> void juce::SparseSet< Type >::addRange (const Range< Type > range)
Adds a range of contiguous values to the set.
e.g. addRange (Range <int> (10, 14)) will add (10, 11, 12, 13) to the set.
Referenced by juce::SparseSet< int >::invertRange().
template<class Type> void juce::SparseSet< Type >::removeRange (const Range< Type > rangeToRemove)
Removes a range of values from the set.
e.g. removeRange (Range<int> (10, 14)) will remove (10, 11, 12, 13) from the set.
Referenced by juce::SparseSet< int >::addRange(), and juce::SparseSet< int >::invertRange().
template<class Type> void juce::SparseSet< Type >::invertRange (const Range< Type > range)
Does an XOR of the values in a given range.
template<class Type> bool juce::SparseSet< Type >::overlapsRange (const Range< Type > range)
Checks whether any part of a given range overlaps any part of this set.
template<class Type> bool juce::SparseSet< Type >::containsRange (const Range< Type > range)
Checks whether the whole of a given range is contained within this one.
template<class Type> bool juce::SparseSet< Type >::operator== (const SparseSet< Type > & other) noexcept
template<class Type> bool juce::SparseSet< Type >::operator!= (const SparseSet< Type > & other) noexcept
The documentation for this class was generated from the following file:
juce_SparseSet.h