JUCE: juce::AudioUnitHelpers::CoreAudioBufferList Class Reference
juce::AudioUnitHelpers::CoreAudioBufferList Class Reference
Public Member Functions
CoreAudioBufferList ()
void prepare (int inChannels, int outChannels, int maxFrames)
void release ()
void reset () noexcept
float * setBuffer (const int idx, float *ptr=nullptr) noexcept
float * push () noexcept
void push (AudioBufferList &bufferList, const int *channelMap) noexcept
float * pop () noexcept
void pop (AudioBufferList &buffer, const int *channelMap) noexcept
AudioSampleBuffer & getBuffer (UInt32 frames) noexcept
Constructor & Destructor Documentation
juce::AudioUnitHelpers::CoreAudioBufferList::CoreAudioBufferList ()
References reset().
Member Function Documentation
void juce::AudioUnitHelpers::CoreAudioBufferList::prepare (int inChannels, int outChannels, int maxFrames)
References juce::HeapBlock< ElementType, throwOnFailure >::calloc(), juce::jmax(), reset(), and juce::AudioBuffer< Type >::setSize().
void juce::AudioUnitHelpers::CoreAudioBufferList::release ()
References juce::HeapBlock< ElementType, throwOnFailure >::free(), and juce::AudioBuffer< Type >::setSize().
void juce::AudioUnitHelpers::CoreAudioBufferList::reset () noexcept
References juce::HeapBlock< ElementType, throwOnFailure >::get(), juce::AudioBuffer< Type >::getNumChannels(), and juce::zeromem().
Referenced by CoreAudioBufferList(), and prepare().
float* juce::AudioUnitHelpers::CoreAudioBufferList::setBuffer (const int idx, float * ptr = nullptr) noexcept
References juce::AudioBuffer< Type >::getNumChannels(), and jassert.
float* juce::AudioUnitHelpers::CoreAudioBufferList::push () noexcept
References juce::AudioBuffer< Type >::getNumChannels(), and jassert.
Referenced by push().
void juce::AudioUnitHelpers::CoreAudioBufferList::push (AudioBufferList & bufferList, const int * channelMap) noexcept
References juce::AudioUnitHelpers::copyAudioBuffer(), juce::AudioBuffer< Type >::getNumChannels(), juce::AudioUnitHelpers::isAudioBufferInterleaved(), jassert, and push().
float* juce::AudioUnitHelpers::CoreAudioBufferList::pop () noexcept
References juce::AudioBuffer< Type >::getNumChannels(), and jassert.
Referenced by pop().
void juce::AudioUnitHelpers::CoreAudioBufferList::pop (AudioBufferList & buffer, const int * channelMap) noexcept
References juce::AudioUnitHelpers::copyAudioBuffer(), juce::AudioUnitHelpers::isAudioBufferInterleaved(), and pop().
AudioSampleBuffer& juce::AudioUnitHelpers::CoreAudioBufferList::getBuffer (UInt32 frames) noexcept
References juce::AudioBuffer< Type >::getNumChannels(), jassert, and juce::AudioBuffer< Type >::setDataToReferTo().
The documentation for this class was generated from the following file:
juce_AU_Shared.h