JUCE: juce::Quaternion< Type > Class Template Reference
juce::Quaternion< Type > Class Template Reference
geometry
Holds a quaternion (a 3D vector and a scalar value).
Public Member Functions
Quaternion () noexcept
Quaternion (const Quaternion &other) noexcept
Quaternion (Vector3D< Type > vectorPart, Type scalarPart) noexcept
Quaternion (Type x, Type y, Type z, Type w) noexcept
Quaternion & operator= (Quaternion other) noexcept
Quaternion & operator*= (Quaternion other) noexcept
Type length () const noexcept
Type normal () const noexcept
Quaternion normalised () const noexcept
Matrix3D< Type > getRotationMatrix () const noexcept
Returns the matrix that will perform the rotation specified by this quaternion.
Static Public Member Functions
static Quaternion fromAngle (Type angle, Vector3D< Type > axis) noexcept
Creates a quaternion from an angle and an axis.
Public Attributes
Vector3D< Type > vector
The vector part of the quaternion.
Type scalar
The scalar part of the quaternion.
Detailed Description
template<typename Type>
class juce::Quaternion< Type >
Holds a quaternion (a 3D vector and a scalar value).
Constructor & Destructor Documentation
template<typename Type> juce::Quaternion< Type >::Quaternion () noexcept
Referenced by juce::Quaternion< float >::fromAngle(), and juce::Quaternion< float >::normalised().
template<typename Type> juce::Quaternion< Type >::Quaternion (const Quaternion< Type > & other) noexcept
template<typename Type> juce::Quaternion< Type >::Quaternion (Vector3D< Type > vectorPart, Type scalarPart) noexcept
template<typename Type> juce::Quaternion< Type >::Quaternion (Type x, Type y, Type z, Type w) noexcept
Member Function Documentation
template<typename Type> static Quaternion juce::Quaternion< Type >::fromAngle (Type angle, Vector3D< Type > axis) static noexcept
Creates a quaternion from an angle and an axis.
template<typename Type> Quaternion& juce::Quaternion< Type >::operator= (Quaternion< Type > other) noexcept
template<typename Type> Quaternion& juce::Quaternion< Type >::operator*= (Quaternion< Type > other) noexcept
template<typename Type> Type juce::Quaternion< Type >::length () const noexcept
Referenced by juce::Quaternion< float >::normalised().
template<typename Type> Type juce::Quaternion< Type >::normal () const noexcept
Referenced by juce::Quaternion< float >::getRotationMatrix(), and juce::Quaternion< float >::length().
template<typename Type> Quaternion juce::Quaternion< Type >::normalised () const noexcept
template<typename Type> Matrix3D<Type> juce::Quaternion< Type >::getRotationMatrix () const noexcept
Returns the matrix that will perform the rotation specified by this quaternion.
Referenced by juce::Draggable3DOrientation::getRotationMatrix().
Member Data Documentation
template<typename Type> Vector3D<Type> juce::Quaternion< Type >::vector
The vector part of the quaternion.
Referenced by juce::Quaternion< float >::getRotationMatrix(), juce::Quaternion< float >::normal(), juce::Quaternion< float >::normalised(), juce::Quaternion< float >::operator*=(), and juce::Quaternion< float >::operator=().
template<typename Type> Type juce::Quaternion< Type >::scalar
The scalar part of the quaternion.
Referenced by juce::Quaternion< float >::getRotationMatrix(), juce::Quaternion< float >::normal(), juce::Quaternion< float >::normalised(), juce::Quaternion< float >::operator*=(), and juce::Quaternion< float >::operator=().
The documentation for this class was generated from the following file:
juce_Quaternion.h