JUCE: juce::Matrix3D< Type > Class Template Reference
juce::Matrix3D< Type > Class Template Reference
geometry
A 4x4 3D transformation matrix.
Public Member Functions
Matrix3D () noexcept
Creates an identity matrix.
Matrix3D (const Matrix3D &other) noexcept
Creates a copy of another matrix.
Matrix3D & operator= (const Matrix3D &other) noexcept
Copies another matrix.
Matrix3D (const Type &m00, const Type &m10, const Type &m20, const Type &m30, const Type &m01, const Type &m11, const Type &m21, const Type &m31, const Type &m02, const Type &m12, const Type &m22, const Type &m32, const Type &m03, const Type &m13, const Type &m23, const Type &m33) noexcept
Creates a matrix from its raw 4x4 values.
Matrix3D (const Type *values) noexcept
Creates a matrix from an array of 16 raw values.
Matrix3D (const AffineTransform &transform) noexcept
Creates a matrix from a 2D affine transform.
Matrix3D (Vector3D< Type > vector) noexcept
Creates a matrix from a 3D vector translation.
Matrix3D & operator*= (const Matrix3D &other) noexcept
Multiplies this matrix by another.
Matrix3D operator* (const Matrix3D &other) const noexcept
Multiplies this matrix by another, and returns the result.
Matrix3D rotated (Vector3D< Type > eulerAngleRadians) const noexcept
Returns a copy of this matrix after rotation through the Y, X and then Z angles specified by the vector.
Static Public Member Functions
static Matrix3D fromFrustum (Type left, Type right, Type bottom, Type top, Type nearDistance, Type farDistance) noexcept
Returns a new matrix from the given frustrum values.
Public Attributes
Type mat [16]
The 4x4 matrix values.
Detailed Description
template<typename Type>
class juce::Matrix3D< Type >
A 4x4 3D transformation matrix.
See Also
Vector3D, Quaternion, AffineTransform
Constructor & Destructor Documentation
template<typename Type > juce::Matrix3D< Type >::Matrix3D () noexcept
Creates an identity matrix.
References juce::Matrix3D< Type >::mat.
Referenced by juce::Matrix3D< Type >::fromFrustum(), juce::Matrix3D< Type >::operator*(), and juce::Matrix3D< Type >::rotated().
template<typename Type > juce::Matrix3D< Type >::Matrix3D (const Matrix3D< Type > & other) noexcept
Creates a copy of another matrix.
References juce::Matrix3D< Type >::mat.
template<typename Type > juce::Matrix3D< Type >::Matrix3D (const Type & m00, const Type & m10, const Type & m20, const Type & m30, const Type & m01, const Type & m11, const Type & m21, const Type & m31, const Type & m02, const Type & m12, const Type & m22, const Type & m32, const Type & m03, const Type & m13, const Type & m23, const Type & m33) noexcept
Creates a matrix from its raw 4x4 values.
References juce::Matrix3D< Type >::mat.
template<typename Type > juce::Matrix3D< Type >::Matrix3D (const Type * values) noexcept
Creates a matrix from an array of 16 raw values.
References juce::Matrix3D< Type >::mat.
template<typename Type > juce::Matrix3D< Type >::Matrix3D (const AffineTransform & transform) noexcept
Creates a matrix from a 2D affine transform.
References juce::Matrix3D< Type >::mat.
template<typename Type > juce::Matrix3D< Type >::Matrix3D (Vector3D< Type > vector) noexcept
Creates a matrix from a 3D vector translation.
References juce::Matrix3D< Type >::mat.
Member Function Documentation
template<typename Type > Matrix3D& juce::Matrix3D< Type >::operator= (const Matrix3D< Type > & other) noexcept
Copies another matrix.
References juce::Matrix3D< Type >::mat.
template<typename Type > static Matrix3D juce::Matrix3D< Type >::fromFrustum (Type left, Type right, Type bottom, Type top, Type nearDistance, Type farDistance) static noexcept
Returns a new matrix from the given frustrum values.
References juce::Matrix3D< Type >::Matrix3D().
template<typename Type > Matrix3D& juce::Matrix3D< Type >::operator*= (const Matrix3D< Type > & other) noexcept
Multiplies this matrix by another.
template<typename Type > Matrix3D juce::Matrix3D< Type >::operator* (const Matrix3D< Type > & other) const noexcept
Multiplies this matrix by another, and returns the result.
References juce::Matrix3D< Type >::mat, and juce::Matrix3D< Type >::Matrix3D().
template<typename Type > Matrix3D juce::Matrix3D< Type >::rotated (Vector3D< Type > eulerAngleRadians) const noexcept
Returns a copy of this matrix after rotation through the Y, X and then Z angles specified by the vector.
References juce::Matrix3D< Type >::Matrix3D().
Member Data Documentation
template<typename Type > Type juce::Matrix3D< Type >::mat[16]
The 4x4 matrix values.
These are stored in the standard OpenGL order.
Referenced by juce::Matrix3D< Type >::Matrix3D(), juce::Matrix3D< Type >::operator*(), and juce::Matrix3D< Type >::operator=().
The documentation for this class was generated from the following file:
juce_Matrix3D.h