JUCE: SmoothedValue< FloatType, SmoothingType > Class Template Reference
SmoothedValue< FloatType, SmoothingType > Class Template Reference
utilities
A utility class for values that need smoothing to avoid audio glitches.
Public Types
template<typename T >
using MultiplicativeVoid = (void setValue(FloatType newValue, bool force=false) noexcept,{if(force){this->setCurrentAndTargetValue(newValue);return;}setTargetValue(newValue);}) private typename std::enable_if< std::is_same< T, ValueSmoothingTypes::Multiplicative >::value, void >::type
THIS FUNCTION IS DEPRECATED.
Public Types inherited from SmoothedValueBase< SmoothedValue< FloatType, SmoothingType > >
using FloatType = typename FloatTypeHelper< SmoothedValue< FloatType, SmoothingType > >::Type
Public Member Functions
SmoothedValue () noexcept
Constructor.
SmoothedValue (FloatType initialValue) noexcept
Constructor.
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
void reset (int numSteps) noexcept
Set a new ramp length directly in samples.
void setTargetValue (FloatType newValue) noexcept
Set the next value to ramp towards.
FloatType getNextValue () noexcept
Compute the next value.
FloatType skip (int numSamples) noexcept
Skip the next numSamples samples.
template<typename T = SmoothingType>
LinearVoid< T > setStepSize () noexcept
template<typename T = SmoothingType>
MultiplicativeVoid< T > setStepSize ()
template<typename T = SmoothingType>
LinearVoid< T > setNextValue () noexcept
template<typename T = SmoothingType>
MultiplicativeVoid< T > setNextValue () noexcept
template<typename T = SmoothingType>
LinearVoid< T > skipCurrentValue (int numSamples) noexcept
template<typename T = SmoothingType>
MultiplicativeVoid< T > skipCurrentValue (int numSamples)
Public Member Functions inherited from SmoothedValueBase< SmoothedValue< FloatType, SmoothingType > >
SmoothedValueBase ()=default
Constructor.
virtual ~SmoothedValueBase ()
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
FloatType getCurrentValue () const noexcept
Returns the current value of the ramp.
FloatType getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
void setCurrentAndTargetValue (FloatType newValue)
Sets the current value and the target value.
void applyGain (FloatType *samples, int numSamples) noexcept
Applies a smoothed gain to a stream of samples S[i] *= gain.
void applyGain (FloatType *samplesOut, const FloatType *samplesIn, int numSamples) noexcept
Computes output as a smoothed gain applied to a stream of samples.
void applyGain (AudioBuffer< FloatType > &buffer, int numSamples) noexcept
Applies a smoothed gain to a buffer.
Public Attributes
FloatType step = FloatType()
int stepsToTarget = 0
Additional Inherited Members
Protected Attributes inherited from SmoothedValueBase< SmoothedValue< FloatType, SmoothingType > >
FloatType currentValue
FloatType target
int countdown
Detailed Description
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear>
class SmoothedValue< FloatType, SmoothingType >
A utility class for values that need smoothing to avoid audio glitches.
A ValueSmoothingTypes::Linear template parameter selects linear smoothing, which increments the SmoothedValue linearly towards its target value.
SmoothedValue<float, ValueSmoothingTypes::Linear> yourSmoothedValue;
A ValueSmoothingTypes::Multiplicative template parameter selects multiplicative smoothing increments towards the target value.
SmoothedValue<float, ValueSmoothingTypes::Multiplicative> yourSmoothedValue;
Multiplicative smoothing is useful when you are dealing with exponential/logarithmic values like volume in dB or frequency in Hz. For example a 12 step ramp from 440.0 Hz (A4) to 880.0 Hz (A5) will increase the frequency with an equal temperament tuning across the octave. A 10 step smoothing from 1.0 (0 dB) to 3.16228 (10 dB) will increase the value in increments of 1 dB.
Note that when you are using multiplicative smoothing you cannot ever reach a target value of zero!
Member Typedef Documentation
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T > using SmoothedValue< FloatType, SmoothingType >::MultiplicativeVoid = (void setValue (FloatType newValue, bool force = false) noexcept, { if (force) { this->setCurrentAndTargetValue (newValue); return; } setTargetValue (newValue); }) private typename std::enable_if <std::is_same <T, ValueSmoothingTypes::Multiplicative>::value, void>::type
THIS FUNCTION IS DEPRECATED.
Use setTargetValue (float) and setCurrentAndTargetValue() instead:
lsv.setValue (x, false); -> lsv.setTargetValue (x); lsv.setValue (x, true); -> lsv.setCurrentAndTargetValue (x);
Parameters
newValue The new target value
force If true, the value will be set immediately, bypassing the ramp
Constructor & Destructor Documentation
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> SmoothedValue< FloatType, SmoothingType >::SmoothedValue () noexcept
Constructor.
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> SmoothedValue< FloatType, SmoothingType >::SmoothedValue (FloatType initialValue) noexcept
Constructor.
Member Function Documentation
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> void SmoothedValue< FloatType, SmoothingType >::reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
Parameters
sampleRate The sample rate
rampLengthInSeconds The duration of the ramp in seconds
Referenced by dsp::Gain< FloatType >::reset(), dsp::Bias< FloatType >::reset(), dsp::Oscillator< SampleType >::reset(), SmoothedValue< Type >::reset(), and Reverb::setSampleRate().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> void SmoothedValue< FloatType, SmoothingType >::reset (int numSteps) noexcept
Set a new ramp length directly in samples.
Parameters
numSteps The number of samples over which the ramp should be active
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> void SmoothedValue< FloatType, SmoothingType >::setTargetValue (FloatType newValue) noexcept
Set the next value to ramp towards.
Parameters
newValue The new target value
Referenced by dsp::Bias< FloatType >::setBias(), dsp::Oscillator< SampleType >::setFrequency(), dsp::Gain< FloatType >::setGainLinear(), and Reverb::setParameters().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> FloatType SmoothedValue< FloatType, SmoothingType >::getNextValue () noexcept
Compute the next value.
Returns
Smoothed value
Referenced by dsp::Gain< FloatType >::process(), dsp::Bias< FloatType >::process(), dsp::Oscillator< SampleType >::process(), Reverb::processMono(), dsp::Gain< FloatType >::processSample(), dsp::Bias< FloatType >::processSample(), dsp::Oscillator< SampleType >::processSample(), and Reverb::processStereo().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> FloatType SmoothedValue< FloatType, SmoothingType >::skip (int numSamples) noexcept
Skip the next numSamples samples.
This is identical to calling getNextValue numSamples times. It returns the new current value.
See Also
getNextValue
Referenced by dsp::Gain< FloatType >::process(), dsp::Bias< FloatType >::process(), and dsp::Oscillator< SampleType >::process().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T = SmoothingType> LinearVoid<T> SmoothedValue< FloatType, SmoothingType >::setStepSize () noexcept
Referenced by SmoothedValue< Type >::setTargetValue().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T = SmoothingType> MultiplicativeVoid<T> SmoothedValue< FloatType, SmoothingType >::setStepSize ()
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T = SmoothingType> LinearVoid<T> SmoothedValue< FloatType, SmoothingType >::setNextValue () noexcept
Referenced by SmoothedValue< Type >::getNextValue().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T = SmoothingType> MultiplicativeVoid<T> SmoothedValue< FloatType, SmoothingType >::setNextValue () noexcept
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T = SmoothingType> LinearVoid<T> SmoothedValue< FloatType, SmoothingType >::skipCurrentValue (int numSamples) noexcept
Referenced by SmoothedValue< Type >::skip().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> template<typename T = SmoothingType> MultiplicativeVoid<T> SmoothedValue< FloatType, SmoothingType >::skipCurrentValue (int numSamples)
Member Data Documentation
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> FloatType SmoothedValue< FloatType, SmoothingType >::step = FloatType()
Referenced by SmoothedValue< Type >::setNextValue(), SmoothedValue< Type >::setStepSize(), and SmoothedValue< Type >::skipCurrentValue().
template<typename FloatType, typename SmoothingType = ValueSmoothingTypes::Linear> int SmoothedValue< FloatType, SmoothingType >::stepsToTarget = 0
Referenced by SmoothedValue< Type >::reset(), and SmoothedValue< Type >::setTargetValue().
The documentation for this class was generated from the following file:
juce_SmoothedValue.h