JUCE: juce::PositionableAudioSource Class Reference
juce::PositionableAudioSource Class Reference abstract
sources
A type of AudioSource which can be repositioned.
Public Member Functions
~PositionableAudioSource ()
Destructor.
virtual void setNextReadPosition (int64 newPosition)=0
Tells the stream to move to a new position.
virtual int64 getNextReadPosition () const =0
Returns the position from which the next block will be returned.
virtual int64 getTotalLength () const =0
Returns the total length of the stream (in samples).
virtual bool isLooping () const =0
Returns true if this source is actually playing in a loop.
virtual void setLooping (bool shouldLoop)
Tells the source whether you'd like it to play in a loop.
Public Member Functions inherited from juce::AudioSource
virtual ~AudioSource ()
Destructor.
virtual void prepareToPlay (int samplesPerBlockExpected, double sampleRate)=0
Tells the source to prepare for playing.
virtual void releaseResources ()=0
Allows the source to release anything it no longer needs after playback has stopped.
virtual void getNextAudioBlock (const AudioSourceChannelInfo &bufferToFill)=0
Called repeatedly to fetch subsequent blocks of audio data.
Protected Member Functions
PositionableAudioSource () noexcept
Creates the PositionableAudioSource.
Protected Member Functions inherited from juce::AudioSource
AudioSource () noexcept
Creates an AudioSource.
Detailed Description
A type of AudioSource which can be repositioned.
The basic AudioSource just streams continuously with no idea of a current time or length, so the PositionableAudioSource is used for a finite stream that has a current read position.
See Also
AudioSource, AudioTransportSource
Constructor & Destructor Documentation
juce::PositionableAudioSource::PositionableAudioSource () protected noexcept
Creates the PositionableAudioSource.
juce::PositionableAudioSource::~PositionableAudioSource ()
Destructor.
Member Function Documentation
virtual void juce::PositionableAudioSource::setNextReadPosition (int64 newPosition) pure virtual
Tells the stream to move to a new position.
Calling this indicates that the next call to AudioSource::getNextAudioBlock() should return samples from this position.
Note that this may be called on a different thread to getNextAudioBlock(), so the subclass should make sure it's synchronised.
Implemented in juce::AudioTransportSource, juce::AudioFormatReaderSource, and juce::BufferingAudioSource.
virtual int64 juce::PositionableAudioSource::getNextReadPosition () const pure virtual
Returns the position from which the next block will be returned.
See Also
setNextReadPosition
Implemented in juce::AudioTransportSource, juce::AudioFormatReaderSource, and juce::BufferingAudioSource.
virtual int64 juce::PositionableAudioSource::getTotalLength () const pure virtual
Returns the total length of the stream (in samples).
Implemented in juce::AudioTransportSource, juce::AudioFormatReaderSource, and juce::BufferingAudioSource.
Referenced by juce::BufferingAudioSource::getTotalLength().
virtual bool juce::PositionableAudioSource::isLooping () const pure virtual
Returns true if this source is actually playing in a loop.
Implemented in juce::AudioTransportSource, juce::BufferingAudioSource, and juce::AudioFormatReaderSource.
Referenced by juce::BufferingAudioSource::isLooping().
virtual void juce::PositionableAudioSource::setLooping (bool shouldLoop) virtual
Tells the source whether you'd like it to play in a loop.
Reimplemented in juce::AudioFormatReaderSource.
References juce::ignoreUnused().
The documentation for this class was generated from the following file:
juce_PositionableAudioSource.h