JUCE: juce::Line< ValueType > Class Template Reference
juce::Line< ValueType > Class Template Reference
geometry
Represents a line.
Public Member Functions
Line () noexcept
Creates a line, using (0, 0) as its start and end points.
Line (const Line &other) noexcept
Creates a copy of another line.
Line (ValueType startX, ValueType startY, ValueType endX, ValueType endY) noexcept
Creates a line based on the coordinates of its start and end points.
Line (Point< ValueType > startPoint, Point< ValueType > endPoint) noexcept
Creates a line from its start and end points.
Line & operator= (const Line &other) noexcept
Copies a line from another one.
~Line () noexcept
Destructor.
ValueType getStartX () const noexcept
Returns the x coordinate of the line's start point.
ValueType getStartY () const noexcept
Returns the y coordinate of the line's start point.
ValueType getEndX () const noexcept
Returns the x coordinate of the line's end point.
ValueType getEndY () const noexcept
Returns the y coordinate of the line's end point.
Point< ValueType > getStart () const noexcept
Returns the line's start point.
Point< ValueType > getEnd () const noexcept
Returns the line's end point.
void setStart (ValueType newStartX, ValueType newStartY) noexcept
Changes this line's start point.
void setEnd (ValueType newEndX, ValueType newEndY) noexcept
Changes this line's end point.
void setStart (const Point< ValueType > newStart) noexcept
Changes this line's start point.
void setEnd (const Point< ValueType > newEnd) noexcept
Changes this line's end point.
Line reversed () const noexcept
Returns a line that is the same as this one, but with the start and end reversed,.
void applyTransform (const AffineTransform &transform) noexcept
Applies an affine transform to the line's start and end points.
ValueType getLength () const noexcept
Returns the length of the line.
ValueType getLengthSquared () const noexcept
Returns the length of the line.
bool isVertical () const noexcept
Returns true if the line's start and end x coordinates are the same.
bool isHorizontal () const noexcept
Returns true if the line's start and end y coordinates are the same.
Point< ValueType >::FloatType getAngle () const noexcept
Returns the line's angle.
Line< float > toFloat () const noexcept
Casts this line to float coordinates.
Line< double > toDouble () const noexcept
Casts this line to double coordinates.
bool operator== (Line other) const noexcept
Compares two lines.
bool operator!= (Line other) const noexcept
Compares two lines.
Point< ValueType > getIntersection (Line line) const noexcept
Finds the intersection between two lines.
bool intersects (Line line, Point< ValueType > &intersection) const noexcept
Finds the intersection between two lines.
bool intersects (Line other) const noexcept
Returns true if this line intersects another.
Point< ValueType > getPointAlongLine (ValueType distanceFromStart) const noexcept
Returns the location of the point which is a given distance along this line.
Point< ValueType > getPointAlongLine (ValueType distanceFromStart, ValueType perpendicularDistance) const noexcept
Returns a point which is a certain distance along and to the side of this line.
Point< ValueType > getPointAlongLineProportionally (typename Point< ValueType >::FloatType proportionOfLength) const noexcept
Returns the location of the point which is a given distance along this line proportional to the line's length.
ValueType getDistanceFromPoint (Point< ValueType > targetPoint, Point< ValueType > &pointOnLine) const noexcept
Returns the smallest distance between this line segment and a given point.
ValueType findNearestProportionalPositionTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point, and returns its position as a proportional position along the line.
Point< ValueType > findNearestPointTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point.
bool isPointAbove (Point< ValueType > point) const noexcept
Returns true if the given point lies above this line.
Line withShortenedStart (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
Line withShortenedEnd (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
Static Public Member Functions
static Line fromStartAndAngle (Point< ValueType > startPoint, ValueType length, ValueType angle) noexcept
Creates a line from a start point, length and angle.
Detailed Description
template<typename ValueType>
class juce::Line< ValueType >
Represents a line.
This class contains a bunch of useful methods for various geometric tasks.
The ValueType template parameter should be a primitive type - float or double are what it's designed for. Integer types will work in a basic way, but some methods that perform mathematical operations may not compile, or they may not produce sensible results.
See Also
Point, Rectangle, Path, Graphics::drawLine
Constructor & Destructor Documentation
template<typename ValueType> juce::Line< ValueType >::Line () noexcept
Creates a line, using (0, 0) as its start and end points.
template<typename ValueType> juce::Line< ValueType >::Line (const Line< ValueType > & other) noexcept
Creates a copy of another line.
template<typename ValueType> juce::Line< ValueType >::Line (ValueType startX, ValueType startY, ValueType endX, ValueType endY) noexcept
Creates a line based on the coordinates of its start and end points.
template<typename ValueType> juce::Line< ValueType >::Line (Point< ValueType > startPoint, Point< ValueType > endPoint) noexcept
Creates a line from its start and end points.
template<typename ValueType> juce::Line< ValueType >::~Line () noexcept
Destructor.
Member Function Documentation
template<typename ValueType> Line& juce::Line< ValueType >::operator= (const Line< ValueType > & other) noexcept
Copies a line from another one.
template<typename ValueType> ValueType juce::Line< ValueType >::getStartX () const noexcept
Returns the x coordinate of the line's start point.
template<typename ValueType> ValueType juce::Line< ValueType >::getStartY () const noexcept
Returns the y coordinate of the line's start point.
template<typename ValueType> ValueType juce::Line< ValueType >::getEndX () const noexcept
Returns the x coordinate of the line's end point.
template<typename ValueType> ValueType juce::Line< ValueType >::getEndY () const noexcept
Returns the y coordinate of the line's end point.
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::getStart () const noexcept
Returns the line's start point.
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::getEnd () const noexcept
Returns the line's end point.
template<typename ValueType> void juce::Line< ValueType >::setStart (ValueType newStartX, ValueType newStartY) noexcept
Changes this line's start point.
template<typename ValueType> void juce::Line< ValueType >::setEnd (ValueType newEndX, ValueType newEndY) noexcept
Changes this line's end point.
template<typename ValueType> void juce::Line< ValueType >::setStart (const Point< ValueType > newStart) noexcept
Changes this line's start point.
template<typename ValueType> void juce::Line< ValueType >::setEnd (const Point< ValueType > newEnd) noexcept
Changes this line's end point.
template<typename ValueType> Line juce::Line< ValueType >::reversed () const noexcept
Returns a line that is the same as this one, but with the start and end reversed,.
template<typename ValueType> void juce::Line< ValueType >::applyTransform (const AffineTransform & transform) noexcept
Applies an affine transform to the line's start and end points.
template<typename ValueType> ValueType juce::Line< ValueType >::getLength () const noexcept
Returns the length of the line.
Referenced by juce::Line< ValueType >::getPointAlongLine(), juce::Line< ValueType >::withShortenedEnd(), and juce::Line< ValueType >::withShortenedStart().
template<typename ValueType> ValueType juce::Line< ValueType >::getLengthSquared () const noexcept
Returns the length of the line.
template<typename ValueType> bool juce::Line< ValueType >::isVertical () const noexcept
Returns true if the line's start and end x coordinates are the same.
template<typename ValueType> bool juce::Line< ValueType >::isHorizontal () const noexcept
Returns true if the line's start and end y coordinates are the same.
template<typename ValueType> Point<ValueType>::FloatType juce::Line< ValueType >::getAngle () const noexcept
Returns the line's angle.
This value is the number of radians clockwise from the 12 o'clock direction, where the line's start point is considered to be at the centre.
template<typename ValueType> static Line juce::Line< ValueType >::fromStartAndAngle (Point< ValueType > startPoint, ValueType length, ValueType angle) static noexcept
Creates a line from a start point, length and angle.
This angle is the number of radians clockwise from the 12 o'clock direction, where the line's start point is considered to be at the centre.
template<typename ValueType> Line<float> juce::Line< ValueType >::toFloat () const noexcept
Casts this line to float coordinates.
template<typename ValueType> Line<double> juce::Line< ValueType >::toDouble () const noexcept
Casts this line to double coordinates.
template<typename ValueType> bool juce::Line< ValueType >::operator== (Line< ValueType > other) const noexcept
Compares two lines.
template<typename ValueType> bool juce::Line< ValueType >::operator!= (Line< ValueType > other) const noexcept
Compares two lines.
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::getIntersection (Line< ValueType > line) const noexcept
Finds the intersection between two lines.
Parameters
line the line to intersect with
Returns
the point at which the lines intersect, even if this lies beyond the end of the lines
template<typename ValueType> bool juce::Line< ValueType >::intersects (Line< ValueType > line, Point< ValueType > & intersection) const noexcept
Finds the intersection between two lines.
Parameters
line the other line
intersection the position of the point where the lines meet (or where they would meet if they were infinitely long) the intersection (if the lines intersect). If the lines are parallel, this will just be set to the position of one of the line's endpoints.
Returns
true if the line segments intersect; false if they dont. Even if they don't intersect, the intersection coordinates returned will still be valid
template<typename ValueType> bool juce::Line< ValueType >::intersects (Line< ValueType > other) const noexcept
Returns true if this line intersects another.
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::getPointAlongLine (ValueType distanceFromStart) const noexcept
Returns the location of the point which is a given distance along this line.
Parameters
distanceFromStart the distance to move along the line from its start point. This value can be negative or longer than the line itself
See Also
getPointAlongLineProportionally
References juce::Line< ValueType >::getLength().
Referenced by juce::Line< ValueType >::withShortenedEnd(), and juce::Line< ValueType >::withShortenedStart().
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::getPointAlongLine (ValueType distanceFromStart, ValueType perpendicularDistance) const noexcept
Returns a point which is a certain distance along and to the side of this line.
This effectively moves a given distance along the line, then another distance perpendicularly to this, and returns the resulting position.
Parameters
distanceFromStart the distance to move along the line from its start point. This value can be negative or longer than the line itself
perpendicularDistance how far to move sideways from the line. If you're looking along the line from its start towards its end, then a positive value here will move to the right, negative value move to the left.
References juce::juce_hypot().
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::getPointAlongLineProportionally (typename Point< ValueType >::FloatType proportionOfLength) const noexcept
Returns the location of the point which is a given distance along this line proportional to the line's length.
Parameters
proportionOfLength the distance to move along the line from its start point, in multiples of the line's length. So a value of 0.0 will return the line's start point and a value of 1.0 will return its end point. (This value can be negative or greater than 1.0).
See Also
getPointAlongLine
Referenced by juce::Line< ValueType >::findNearestPointTo().
template<typename ValueType> ValueType juce::Line< ValueType >::getDistanceFromPoint (Point< ValueType > targetPoint, Point< ValueType > & pointOnLine) const noexcept
Returns the smallest distance between this line segment and a given point.
So if the point is close to the line, this will return the perpendicular distance from the line; if the point is a long way beyond one of the line's end-point's, it'll return the straight-line distance to the nearest end-point.
pointOnLine receives the position of the point that is found.
Returns
the point's distance from the line
See Also
getPositionAlongLineOfNearestPoint
template<typename ValueType> ValueType juce::Line< ValueType >::findNearestProportionalPositionTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point, and returns its position as a proportional position along the line.
Returns
a value 0 to 1.0 which is the distance along this line from the line's start to the point which is nearest to the point passed-in. To turn this number into a position, use getPointAlongLineProportionally().
See Also
getDistanceFromPoint, getPointAlongLineProportionally
References juce::jlimit().
Referenced by juce::Line< ValueType >::findNearestPointTo().
template<typename ValueType> Point<ValueType> juce::Line< ValueType >::findNearestPointTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point.
See Also
getDistanceFromPoint, findNearestProportionalPositionTo
References juce::Line< ValueType >::findNearestProportionalPositionTo(), and juce::Line< ValueType >::getPointAlongLineProportionally().
template<typename ValueType> bool juce::Line< ValueType >::isPointAbove (Point< ValueType > point) const noexcept
Returns true if the given point lies above this line.
The return value is true if the point's y coordinate is less than the y coordinate of this line at the given x (assuming the line extends infinitely in both directions).
template<typename ValueType> Line juce::Line< ValueType >::withShortenedStart (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
This will chop off part of the start of this line by a certain amount, (leaving the end-point the same), and return the new line.
References juce::Line< ValueType >::getLength(), juce::Line< ValueType >::getPointAlongLine(), and juce::jmin().
template<typename ValueType> Line juce::Line< ValueType >::withShortenedEnd (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
This will chop off part of the end of this line by a certain amount, (leaving the start-point the same), and return the new line.
References juce::Line< ValueType >::getLength(), juce::Line< ValueType >::getPointAlongLine(), and juce::jmin().
The documentation for this class was generated from the following file:
juce_Line.h