JUCE: LinearSmoothedValue< FloatType > Class Template Reference
LinearSmoothedValue< FloatType > Class Template Reference
utilities
Utility class for linearly smoothed values like volume etc.
Public Member Functions
LinearSmoothedValue ()=default
Constructor.
LinearSmoothedValue (FloatType initialValue) noexcept
Constructor.
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
void reset (int numSteps) noexcept
Set a new ramp length directly in samples.
void setTargetValue (FloatType newValue) noexcept
Set the next value to ramp towards.
FloatType getNextValue () noexcept
Compute the next value.
FloatType skip (int numSamples) noexcept
Skip the next numSamples samples.
Public Member Functions inherited from SmoothedValueBase< LinearSmoothedValue, FloatType >
SmoothedValueBase ()=default
Constructor.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
FloatType getCurrentValue () const noexcept
Returns the current value of the ramp.
FloatType getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
void setCurrentAndTargetValue (FloatType newValue)
Sets the current value and the target value.
void applyGain (FloatType *samples, int numSamples) noexcept
Applies a smoothed gain to a stream of samples S[i] *= gain.
void applyGain (FloatType *samplesOut, const FloatType *samplesIn, int numSamples) noexcept
Computes output as a smoothed gain applied to a stream of samples.
void applyGain (AudioBuffer< FloatType > &buffer, int numSamples) noexcept
Applies a smoothed gain to a buffer.
Public Attributes
JUCE_DEPRECATED_WITH_BODY(void
setValue(FloatType newValue,
bool force=false) noexcept,{if(force){this->
setCurrentAndTargetValue(newValue);return;}setTargetValue(newValue);})
private int stepsToTarget = 0
THIS FUNCTION IS DEPRECATED.
Additional Inherited Members
Protected Member Functions inherited from SmoothedValueBase< LinearSmoothedValue, FloatType >
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Protected Attributes inherited from SmoothedValueBase< LinearSmoothedValue, FloatType >
FloatType currentValue
FloatType target
int countdown
Detailed Description
template<typename FloatType>
class LinearSmoothedValue< FloatType >
Utility class for linearly smoothed values like volume etc.
that should not change abruptly but as a linear ramp to avoid audio glitches.
Constructor & Destructor Documentation
template<typename FloatType> LinearSmoothedValue< FloatType >::LinearSmoothedValue () default
Constructor.
template<typename FloatType> LinearSmoothedValue< FloatType >::LinearSmoothedValue (FloatType initialValue) noexcept
Constructor.
Member Function Documentation
template<typename FloatType> void LinearSmoothedValue< FloatType >::reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
Parameters
sampleRate The sample rate
rampLengthInSeconds The duration of the ramp in seconds
Referenced by dsp::Oscillator< SampleType >::reset(), LinearSmoothedValue< Type >::reset(), and Reverb::setSampleRate().
template<typename FloatType> void LinearSmoothedValue< FloatType >::reset (int numSteps) noexcept
Set a new ramp length directly in samples.
Parameters
numSteps The number of samples over which the ramp should be active
template<typename FloatType> void LinearSmoothedValue< FloatType >::setTargetValue (FloatType newValue) noexcept
Set the next value to ramp towards.
Parameters
newValue The new target value
Referenced by dsp::Oscillator< SampleType >::setFrequency(), and Reverb::setParameters().
template<typename FloatType> FloatType LinearSmoothedValue< FloatType >::getNextValue () noexcept
Compute the next value.
Returns
Smoothed value
Referenced by dsp::Oscillator< SampleType >::process(), Reverb::processMono(), dsp::Oscillator< SampleType >::processSample(), and Reverb::processStereo().
template<typename FloatType> FloatType LinearSmoothedValue< FloatType >::skip (int numSamples) noexcept
Skip the next numSamples samples.
This is identical to calling getNextValue numSamples times. It returns the new current value.
See Also
getNextValue
Referenced by dsp::Oscillator< SampleType >::process().
Member Data Documentation
template<typename FloatType> JUCE_DEPRECATED_WITH_BODY (void setValue (FloatType newValue, bool force = false) noexcept, { if (force) { this->setCurrentAndTargetValue (newValue); return; } setTargetValue (newValue); }) private int LinearSmoothedValue< FloatType >::stepsToTarget = 0
THIS FUNCTION IS DEPRECATED.
Use setTargetValue (float) and setCurrentAndTargetValue() instead:
lsv.setValue (x, false); -> lsv.setTargetValue (x); lsv.setValue (x, true); -> lsv.setCurrentAndTargetValue (x);
Parameters
newValue The new target value
force If true, the value will be set immediately, bypassing the ramp
Referenced by LinearSmoothedValue< Type >::reset(), and LinearSmoothedValue< Type >::setTargetValue().
The documentation for this class was generated from the following file:
juce_SmoothedValues.h