JUCE: ADSR Class Reference
ADSR Class Reference
utilities
A very simple ADSR envelope class.
Classes
struct Parameters
Holds the parameters being used by an ADSR object.
Public Member Functions
ADSR ()
void setParameters (const Parameters &newParameters)
Sets the parameters that will be used by an ADSR object.
const Parameters & getParameters () const
Returns the parameters currently being used by an ADSR object.
bool isActive () const noexcept
Returns true if the envelope is in its attack, decay, sustain or release stage.
void setSampleRate (double sampleRate)
Sets the sample rate that will be used for the envelope.
void reset ()
Resets the envelope to an idle state.
void noteOn ()
Starts the attack phase of the envelope.
void noteOff ()
Starts the release phase of the envelope.
float getNextSample ()
Returns the next sample value for an ADSR object.
template<typename FloatType >
void applyEnvelopeToBuffer (AudioBuffer< FloatType > &buffer, int startSample, int numSamples)
This method will conveniently apply the next numSamples number of envelope values to an AudioBuffer.
Detailed Description
A very simple ADSR envelope class.
To use it, call setSampleRate() with the current sample rate and give it some parameters with setParameters() then call getNextSample() to get the envelope value to be applied to each audio sample or applyEnvelopeToBuffer() to apply the envelope to a whole buffer.
Constructor & Destructor Documentation
ADSR::ADSR ()
References setParameters(), and setSampleRate().
Member Function Documentation
void ADSR::setParameters (const Parameters & newParameters)
Sets the parameters that will be used by an ADSR object.
You must have called setSampleRate() with the correct sample rate before this otherwise the values may be incorrect!
See Also
getParameters
References ADSR::Parameters::sustain.
Referenced by ADSR().
const Parameters& ADSR::getParameters () const
Returns the parameters currently being used by an ADSR object.
See Also
setParameters
bool ADSR::isActive () const noexcept
Returns true if the envelope is in its attack, decay, sustain or release stage.
References idle.
void ADSR::setSampleRate (double sampleRate)
Sets the sample rate that will be used for the envelope.
This must be called before the getNextSample() or setParameters() methods.
References jassert.
Referenced by ADSR().
void ADSR::reset ()
Resets the envelope to an idle state.
References idle.
Referenced by getNextSample(), and noteOff().
void ADSR::noteOn ()
Starts the attack phase of the envelope.
References attack, decay, and sustain.
void ADSR::noteOff ()
Starts the release phase of the envelope.
References idle, release, and reset().
float ADSR::getNextSample ()
Returns the next sample value for an ADSR object.
See Also
applyEnvelopeToBuffer
References attack, decay, idle, release, reset(), and sustain.
Referenced by applyEnvelopeToBuffer().
template<typename FloatType > void ADSR::applyEnvelopeToBuffer (AudioBuffer< FloatType > & buffer, int startSample, int numSamples)
This method will conveniently apply the next numSamples number of envelope values to an AudioBuffer.
See Also
getNextSample
References getNextSample(), AudioBuffer< Type >::getNumChannels(), AudioBuffer< Type >::getNumSamples(), AudioBuffer< Type >::getWritePointer(), and jassert.
The documentation for this class was generated from the following file:
juce_ADSR.h