JUCE: juce::LinearSmoothedValue< FloatType > Class Template Reference
juce::LinearSmoothedValue< FloatType > Class Template Reference
effects
Utility class for linearly smoothed values like volume etc.
Public Member Functions
LinearSmoothedValue () noexcept
Constructor.
LinearSmoothedValue (FloatType initialValue) noexcept
Constructor.
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
void setValue (FloatType newValue) noexcept
Set a new target value.
FloatType getNextValue () noexcept
Compute the next value.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
FloatType getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
void applyGain (FloatType *samples, int numSamples) noexcept
Applies a linear smoothed gain to a stream of samples S[i] *= gain.
void applyGain (FloatType *samplesOut, const FloatType *samplesIn, int numSamples) noexcept
Computes output as linear smoothed gain applied to a stream of samples.
void applyGain (AudioBuffer< FloatType > &buffer, int numSamples) noexcept
Applies a linear smoothed gain to a buffer.
Detailed Description
template<typename FloatType>
class juce::LinearSmoothedValue< FloatType >
Utility class for linearly smoothed values like volume etc.
that should not change abruptly but as a linear ramp, to avoid audio glitches.
Constructor & Destructor Documentation
template<typename FloatType> juce::LinearSmoothedValue< FloatType >::LinearSmoothedValue () noexcept
Constructor.
template<typename FloatType> juce::LinearSmoothedValue< FloatType >::LinearSmoothedValue (FloatType initialValue) noexcept
Constructor.
Member Function Documentation
template<typename FloatType> void juce::LinearSmoothedValue< FloatType >::reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
Parameters
sampleRate The sampling rate
rampLengthInSeconds The duration of the ramp in seconds
Referenced by juce::dsp::Oscillator< SampleType >::reset(), and juce::Reverb::setSampleRate().
template<typename FloatType> void juce::LinearSmoothedValue< FloatType >::setValue (FloatType newValue) noexcept
Set a new target value.
Parameters
newValue New target value
Referenced by juce::dsp::Oscillator< SampleType >::setFrequency(), and juce::Reverb::setParameters().
template<typename FloatType> FloatType juce::LinearSmoothedValue< FloatType >::getNextValue () noexcept
Compute the next value.
Returns
Smoothed value
Referenced by juce::LinearSmoothedValue< NumericType >::applyGain(), juce::dsp::Oscillator< SampleType >::process(), juce::Reverb::processMono(), juce::dsp::Oscillator< SampleType >::processSample(), and juce::Reverb::processStereo().
template<typename FloatType> bool juce::LinearSmoothedValue< FloatType >::isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
Referenced by juce::LinearSmoothedValue< NumericType >::applyGain(), and juce::dsp::Oscillator< SampleType >::process().
template<typename FloatType> FloatType juce::LinearSmoothedValue< FloatType >::getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
Referenced by juce::dsp::Oscillator< SampleType >::getFrequency().
template<typename FloatType> void juce::LinearSmoothedValue< FloatType >::applyGain (FloatType * samples, int numSamples) noexcept
Applies a linear smoothed gain to a stream of samples S[i] *= gain.
Parameters
samples Pointer to a raw array of samples
numSamples Length of array of samples
template<typename FloatType> void juce::LinearSmoothedValue< FloatType >::applyGain (FloatType * samplesOut, const FloatType * samplesIn, int numSamples) noexcept
Computes output as linear smoothed gain applied to a stream of samples.
Sout[i] = Sin[i] * gain
Parameters
samplesOut A pointer to a raw array of output samples
samplesIn A pointer to a raw array of input samples
numSamples The length of the array of samples
template<typename FloatType> void juce::LinearSmoothedValue< FloatType >::applyGain (AudioBuffer< FloatType > & buffer, int numSamples) noexcept
Applies a linear smoothed gain to a buffer.
The documentation for this class was generated from the following file:
juce_LinearSmoothedValue.h