JUCE: juce::PositionedGlyph Class Reference
juce::PositionedGlyph Class Reference
fonts
A glyph from a particular font, with a particular size, style, typeface and position.
Public Member Functions
PositionedGlyph () noexcept
PositionedGlyph (const Font &font, juce_wchar character, int glyphNumber, float anchorX, float baselineY, float width, bool isWhitespace)
PositionedGlyph (const PositionedGlyph &)
PositionedGlyph & operator= (const PositionedGlyph &)
PositionedGlyph (PositionedGlyph &&) noexcept
Move constructor.
PositionedGlyph & operator= (PositionedGlyph &&) noexcept
Move assignment operator.
~PositionedGlyph ()
juce_wchar getCharacter () const noexcept
Returns the character the glyph represents.
bool isWhitespace () const noexcept
Checks whether the glyph is actually empty.
float getLeft () const noexcept
Returns the position of the glyph's left-hand edge.
float getRight () const noexcept
Returns the position of the glyph's right-hand edge.
float getBaselineY () const noexcept
Returns the y position of the glyph's baseline.
float getTop () const
Returns the y position of the top of the glyph.
float getBottom () const
Returns the y position of the bottom of the glyph.
Rectangle< float > getBounds () const
Returns the bounds of the glyph.
void moveBy (float deltaX, float deltaY)
Shifts the glyph's position by a relative amount.
void draw (Graphics &g) const
Draws the glyph into a graphics context.
void draw (Graphics &g, const AffineTransform &transform) const
Draws the glyph into a graphics context, with an extra transform applied to it.
void createPath (Path &path) const
Returns the path for this glyph.
bool hitTest (float x, float y) const
Checks to see if a point lies within this glyph.
Detailed Description
A glyph from a particular font, with a particular size, style, typeface and position.
You should rarely need to use this class directly - for most purposes, the GlyphArrangement class will do what you need for text layout.
See Also
GlyphArrangement, Font
Constructor & Destructor Documentation
juce::PositionedGlyph::PositionedGlyph () noexcept
juce::PositionedGlyph::PositionedGlyph (const Font & font, juce_wchar character, int glyphNumber, float anchorX, float baselineY, float width, bool isWhitespace)
juce::PositionedGlyph::PositionedGlyph (const PositionedGlyph &)
juce::PositionedGlyph::PositionedGlyph (PositionedGlyph &&) noexcept
Move constructor.
juce::PositionedGlyph::~PositionedGlyph ()
Member Function Documentation
PositionedGlyph& juce::PositionedGlyph::operator= (const PositionedGlyph &)
PositionedGlyph& juce::PositionedGlyph::operator= (PositionedGlyph &&) noexcept
Move assignment operator.
juce_wchar juce::PositionedGlyph::getCharacter () const noexcept
Returns the character the glyph represents.
bool juce::PositionedGlyph::isWhitespace () const noexcept
Checks whether the glyph is actually empty.
float juce::PositionedGlyph::getLeft () const noexcept
Returns the position of the glyph's left-hand edge.
float juce::PositionedGlyph::getRight () const noexcept
Returns the position of the glyph's right-hand edge.
float juce::PositionedGlyph::getBaselineY () const noexcept
Returns the y position of the glyph's baseline.
float juce::PositionedGlyph::getTop () const
Returns the y position of the top of the glyph.
References juce::Font::getAscent().
float juce::PositionedGlyph::getBottom () const
Returns the y position of the bottom of the glyph.
References juce::Font::getDescent().
Rectangle<float> juce::PositionedGlyph::getBounds () const
Returns the bounds of the glyph.
References juce::Font::getHeight().
void juce::PositionedGlyph::moveBy (float deltaX, float deltaY)
Shifts the glyph's position by a relative amount.
void juce::PositionedGlyph::draw (Graphics & g) const
Draws the glyph into a graphics context.
(Note that this may change the context's currently selected font).
void juce::PositionedGlyph::draw (Graphics & g, const AffineTransform & transform) const
Draws the glyph into a graphics context, with an extra transform applied to it.
(Note that this may change the context's currently selected font).
void juce::PositionedGlyph::createPath (Path & path) const
Returns the path for this glyph.
Parameters
path the glyph's outline will be appended to this path
bool juce::PositionedGlyph::hitTest (float x, float y) const
Checks to see if a point lies within this glyph.
The documentation for this class was generated from the following file:
juce_GlyphArrangement.h