JUCE: juce::ModifierKeys Class Reference
juce::ModifierKeys Class Reference
keyboard
Represents the state of the mouse buttons and modifier keys.
Public Types
enum Flags {
noModifiers = 0, shiftModifier = 1, ctrlModifier = 2, altModifier = 4,
leftButtonModifier = 16, rightButtonModifier = 32, middleButtonModifier = 64, commandModifier = 8,
popupMenuClickModifier = rightButtonModifier | ctrlModifier, allKeyboardModifiers = shiftModifier | ctrlModifier | altModifier | commandModifier, allMouseButtonModifiers = leftButtonModifier | rightButtonModifier | middleButtonModifier, ctrlAltCommandModifiers = ctrlModifier | altModifier | commandModifier
}
Flags that represent the different keys.
Public Member Functions
ModifierKeys () noexcept
Creates a ModifierKeys object with no flags set.
ModifierKeys (int flags) noexcept
Creates a ModifierKeys object from a raw set of flags.
ModifierKeys (const ModifierKeys &other) noexcept
Creates a copy of another object.
ModifierKeys & operator= (const ModifierKeys other) noexcept
Copies this object from another one.
bool isCommandDown () const noexcept
Checks whether the 'command' key flag is set (or 'ctrl' on Windows/Linux).
bool isPopupMenu () const noexcept
Checks whether the user is trying to launch a pop-up menu.
bool isLeftButtonDown () const noexcept
Checks whether the flag is set for the left mouse-button.
bool isRightButtonDown () const noexcept
Checks whether the flag is set for the right mouse-button.
bool isMiddleButtonDown () const noexcept
bool isAnyMouseButtonDown () const noexcept
Tests for any of the mouse-button flags.
bool isAnyModifierKeyDown () const noexcept
Tests for any of the modifier key flags.
bool isShiftDown () const noexcept
Checks whether the shift key's flag is set.
bool isCtrlDown () const noexcept
Checks whether the CTRL key's flag is set.
bool isAltDown () const noexcept
Checks whether the ALT key's flag is set.
ModifierKeys withOnlyMouseButtons () const noexcept
Returns a copy of only the mouse-button flags.
ModifierKeys withoutMouseButtons () const noexcept
Returns a copy of only the non-mouse flags.
bool operator== (const ModifierKeys other) const noexcept
bool operator!= (const ModifierKeys other) const noexcept
int getRawFlags () const noexcept
Returns the raw flags for direct testing.
ModifierKeys withoutFlags (int rawFlagsToClear) const noexcept
ModifierKeys withFlags (int rawFlagsToSet) const noexcept
bool testFlags (int flagsToTest) const noexcept
Tests a combination of flags and returns true if any of them are set.
int getNumMouseButtonsDown () const noexcept
Returns the total number of mouse buttons that are down.
Static Public Member Functions
static ModifierKeys getCurrentModifiers () noexcept
Creates a ModifierKeys object to represent the last-known state of the keyboard and mouse buttons.
static ModifierKeys getCurrentModifiersRealtime () noexcept
Creates a ModifierKeys object to represent the current state of the keyboard and mouse buttons.
Detailed Description
Represents the state of the mouse buttons and modifier keys.
This is used both by mouse events and by KeyPress objects to describe the state of keys such as shift, control, alt, etc.
See Also
KeyPress, MouseEvent::mods
Member Enumeration Documentation
enum juce::ModifierKeys::Flags
Flags that represent the different keys.
Enumerator
noModifiers
Indicates no modifier keys.
shiftModifier
Shift key flag.
ctrlModifier
CTRL key flag.
altModifier
ALT key flag.
leftButtonModifier
Left mouse button flag.
rightButtonModifier
Right mouse button flag.
middleButtonModifier
Middle mouse button flag.
commandModifier
Command key flag - on windows this is the same as the CTRL key flag.
popupMenuClickModifier
Popup menu flag - on windows this is the same as rightButtonModifier, on the Mac it's the same as (rightButtonModifier | ctrlModifier).
allKeyboardModifiers
Represents a combination of all the shift, alt, ctrl and command key modifiers.
allMouseButtonModifiers
Represents a combination of all the mouse buttons at once.
ctrlAltCommandModifiers
Represents a combination of all the alt, ctrl and command key modifiers.
Constructor & Destructor Documentation
juce::ModifierKeys::ModifierKeys () noexcept
Creates a ModifierKeys object with no flags set.
juce::ModifierKeys::ModifierKeys (int flags) noexcept
Creates a ModifierKeys object from a raw set of flags.
Parameters
flags to represent the keys that are down
See Also
shiftModifier, ctrlModifier, altModifier, leftButtonModifier, rightButtonModifier, commandModifier, popupMenuClickModifier
juce::ModifierKeys::ModifierKeys (const ModifierKeys & other) noexcept
Creates a copy of another object.
Member Function Documentation
ModifierKeys& juce::ModifierKeys::operator= (const ModifierKeys other) noexcept
Copies this object from another one.
bool juce::ModifierKeys::isCommandDown () const noexcept
Checks whether the 'command' key flag is set (or 'ctrl' on Windows/Linux).
This is a platform-agnostic way of checking for the operating system's preferred command-key modifier - so on the Mac it tests for the Apple key, on Windows/Linux, it's actually checking for the CTRL key.
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), juce::LassoComponent< SelectableItemType >::dragLasso(), and juce::TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
bool juce::ModifierKeys::isPopupMenu () const noexcept
Checks whether the user is trying to launch a pop-up menu.
This checks for platform-specific modifiers that might indicate that the user is following the operating system's normal method of showing a pop-up menu.
So on Windows/Linux, this method is really testing for a right-click. On the Mac, it tests for either the CTRL key being down, or a right-click.
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown().
bool juce::ModifierKeys::isLeftButtonDown () const noexcept
Checks whether the flag is set for the left mouse-button.
bool juce::ModifierKeys::isRightButtonDown () const noexcept
Checks whether the flag is set for the right mouse-button.
Note that for detecting popup-menu clicks, you should be using isPopupMenu() instead, as this is platform-independent (and makes your code more explanatory too).
bool juce::ModifierKeys::isMiddleButtonDown () const noexcept
bool juce::ModifierKeys::isAnyMouseButtonDown () const noexcept
Tests for any of the mouse-button flags.
bool juce::ModifierKeys::isAnyModifierKeyDown () const noexcept
Tests for any of the modifier key flags.
bool juce::ModifierKeys::isShiftDown () const noexcept
Checks whether the shift key's flag is set.
Referenced by juce::SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), juce::LassoComponent< SelectableItemType >::dragLasso(), and juce::TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
bool juce::ModifierKeys::isCtrlDown () const noexcept
Checks whether the CTRL key's flag is set.
Remember that it's better to use the platform-agnostic routines to test for command-key and popup-menu modifiers.
See Also
isCommandDown, isPopupMenu
Referenced by juce::TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
bool juce::ModifierKeys::isAltDown () const noexcept
Checks whether the ALT key's flag is set.
Referenced by juce::LassoComponent< SelectableItemType >::dragLasso(), and juce::TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
ModifierKeys juce::ModifierKeys::withOnlyMouseButtons () const noexcept
Returns a copy of only the mouse-button flags.
ModifierKeys juce::ModifierKeys::withoutMouseButtons () const noexcept
Returns a copy of only the non-mouse flags.
bool juce::ModifierKeys::operator== (const ModifierKeys other) const noexcept
bool juce::ModifierKeys::operator!= (const ModifierKeys other) const noexcept
int juce::ModifierKeys::getRawFlags () const noexcept
Returns the raw flags for direct testing.
ModifierKeys juce::ModifierKeys::withoutFlags (int rawFlagsToClear) const noexcept
ModifierKeys juce::ModifierKeys::withFlags (int rawFlagsToSet) const noexcept
bool juce::ModifierKeys::testFlags (int flagsToTest) const noexcept
Tests a combination of flags and returns true if any of them are set.
int juce::ModifierKeys::getNumMouseButtonsDown () const noexcept
Returns the total number of mouse buttons that are down.
static ModifierKeys juce::ModifierKeys::getCurrentModifiers () static noexcept
Creates a ModifierKeys object to represent the last-known state of the keyboard and mouse buttons.
See Also
getCurrentModifiersRealtime
Referenced by juce::FakeMouseMoveGenerator::timerCallback().
static ModifierKeys juce::ModifierKeys::getCurrentModifiersRealtime () static noexcept
Creates a ModifierKeys object to represent the current state of the keyboard and mouse buttons.
This isn't often needed and isn't recommended, but will actively check all the mouse and key states rather than just returning their last-known state like getCurrentModifiers() does.
This is only needed in special circumstances for up-to-date modifier information at times when the app's event loop isn't running normally.
Another reason to avoid this method is that it's not stateless, and calling it may update the value returned by getCurrentModifiers(), which could cause subtle changes in the behaviour of some components.
The documentation for this class was generated from the following file:
juce_ModifierKeys.h