JUCE: juce::PixelRGB Class Reference
juce::PixelRGB Class Reference
colour
Represents a 24-bit RGB pixel, and can perform compositing operations on it.
Public Types
enum { indexR = 0, indexG = 1, indexB = 2 }
The indexes of the different components in the byte layout of this type of colour.
Public Member Functions
PixelRGB () noexcept
Creates a pixel without defining its colour.
~PixelRGB () noexcept
forcedinline uint32 getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format which is compatible with the native format of a PixelARGB.
forcedinline uint32 getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
forcedinline uint32 getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
forcedinline uint32 getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
forcedinline uint8 getAlpha () const noexcept
forcedinline uint8 getRed () const noexcept
forcedinline uint8 getGreen () const noexcept
forcedinline uint8 getBlue () const noexcept
forcedinline uint8 & getRed () noexcept
forcedinline uint8 & getGreen () noexcept
forcedinline uint8 & getBlue () noexcept
template<class Pixel >
forcedinline void set (const Pixel &src) noexcept
Copies another pixel colour over this one.
void setARGB (const uint8, const uint8 red, const uint8 green, const uint8 blue) noexcept
Sets the pixel's colour from individual components.
template<class Pixel >
forcedinline void blend (const Pixel &src) noexcept
Blends another pixel onto this one.
forcedinline void blend (const PixelRGB src) noexcept
template<class Pixel >
forcedinline void blend (const Pixel &src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
template<class Pixel >
forcedinline void tween (const Pixel &src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void setAlpha (const uint8) noexcept
This method is included for compatibility with the PixelARGB class.
forcedinline void multiplyAlpha (int) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void multiplyAlpha (float) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void desaturate () noexcept
Detailed Description
Represents a 24-bit RGB pixel, and can perform compositing operations on it.
This is used internally by the imaging classes.
See Also
PixelARGB
Member Enumeration Documentation
anonymous enum
The indexes of the different components in the byte layout of this type of colour.
Enumerator
indexR
indexG
indexB
Constructor & Destructor Documentation
juce::PixelRGB::PixelRGB () noexcept
Creates a pixel without defining its colour.
juce::PixelRGB::~PixelRGB () noexcept
Member Function Documentation
forcedinline uint32 juce::PixelRGB::getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format which is compatible with the native format of a PixelARGB.
See Also
PixelARGB::getNativeARGB
forcedinline uint32 juce::PixelRGB::getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 juce::PixelRGB::getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
In other words, if the return-value is read as a uint8 array then the elements will be in the order of a, r, g, b
forcedinline uint32 juce::PixelRGB::getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent but compatible with the return value of getEvenBytes of the PixelARGB class.
See Also
PixelARGB::getEvenBytes
forcedinline uint32 juce::PixelRGB::getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent but compatible with the return value of getOddBytes of the PixelARGB class.
See Also
PixelARGB::getOddBytes
forcedinline uint8 juce::PixelRGB::getAlpha () const noexcept
forcedinline uint8 juce::PixelRGB::getRed () const noexcept
forcedinline uint8 juce::PixelRGB::getGreen () const noexcept
forcedinline uint8 juce::PixelRGB::getBlue () const noexcept
forcedinline uint8& juce::PixelRGB::getRed () noexcept
forcedinline uint8& juce::PixelRGB::getGreen () noexcept
forcedinline uint8& juce::PixelRGB::getBlue () noexcept
template<class Pixel > forcedinline void juce::PixelRGB::set (const Pixel & src) noexcept
Copies another pixel colour over this one.
This doesn't blend it - this colour is simply replaced by the other one. Because PixelRGB has no alpha channel, any alpha value in the source pixel is thrown away.
void juce::PixelRGB::setARGB (const uint8 , const uint8 red, const uint8 green, const uint8 blue) noexcept
Sets the pixel's colour from individual components.
template<class Pixel > forcedinline void juce::PixelRGB::blend (const Pixel & src) noexcept
Blends another pixel onto this one.
This takes into account the opacity of the pixel being overlaid, and blends it accordingly.
References juce::clampPixelComponents(), and juce::maskPixelComponents().
forcedinline void juce::PixelRGB::blend (const PixelRGB src) noexcept
template<class Pixel > forcedinline void juce::PixelRGB::blend (const Pixel & src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
The opacity of the pixel being overlaid is scaled by the extraAlpha factor before being used, so this can blend semi-transparently from a PixelRGB argument.
References juce::clampPixelComponents(), and juce::maskPixelComponents().
template<class Pixel > forcedinline void juce::PixelRGB::tween (const Pixel & src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void juce::PixelRGB::setAlpha (const uint8) noexcept
This method is included for compatibility with the PixelARGB class.
forcedinline void juce::PixelRGB::multiplyAlpha (int) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void juce::PixelRGB::multiplyAlpha (float) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void juce::PixelRGB::premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void juce::PixelRGB::unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void juce::PixelRGB::desaturate () noexcept
The documentation for this class was generated from the following file:
juce_PixelFormats.h