JUCE: juce::PixelARGB Class Reference
juce::PixelARGB Class Reference
colour
Represents a 32-bit INTERNAL pixel with premultiplied alpha, and can perform compositing operations with it.
Public Types
enum { indexA = 3, indexR = 0, indexG = 1, indexB = 2 }
The indexes of the different components in the byte layout of this type of colour.
Public Member Functions
PixelARGB () noexcept
Creates a pixel without defining its colour.
~PixelARGB () noexcept
PixelARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
forcedinline uint32 getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format.
forcedinline uint32 getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
forcedinline uint32 getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
forcedinline uint32 getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
forcedinline uint8 getAlpha () const noexcept
forcedinline uint8 getRed () const noexcept
forcedinline uint8 getGreen () const noexcept
forcedinline uint8 getBlue () const noexcept
forcedinline uint8 & getAlpha () noexcept
forcedinline uint8 & getRed () noexcept
forcedinline uint8 & getGreen () noexcept
forcedinline uint8 & getBlue () noexcept
template<class Pixel >
forcedinline void set (const Pixel &src) noexcept
Copies another pixel colour over this one.
void setARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
Sets the pixel's colour from individual components.
template<class Pixel >
forcedinline void blend (const Pixel &src) noexcept
Blends another pixel onto this one.
forcedinline void blend (const PixelRGB src) noexcept
Blends another pixel onto this one.
template<class Pixel >
forcedinline void blend (const Pixel &src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
template<class Pixel >
forcedinline void tween (const Pixel &src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void setAlpha (const uint8 newAlpha) noexcept
Replaces the colour's alpha value with another one.
forcedinline void multiplyAlpha (int multiplier) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void multiplyAlpha (const float multiplier) noexcept
PixelARGB getUnpremultiplied () const noexcept
forcedinline void premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void desaturate () noexcept
Detailed Description
Represents a 32-bit INTERNAL pixel with premultiplied alpha, and can perform compositing operations with it.
This is used internally by the imaging classes.
See Also
PixelRGB
Member Enumeration Documentation
anonymous enum
The indexes of the different components in the byte layout of this type of colour.
Enumerator
indexA
indexR
indexG
indexB
Constructor & Destructor Documentation
juce::PixelARGB::PixelARGB () noexcept
Creates a pixel without defining its colour.
juce::PixelARGB::~PixelARGB () noexcept
juce::PixelARGB::PixelARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
Member Function Documentation
forcedinline uint32 juce::PixelARGB::getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format.
forcedinline uint32 juce::PixelARGB::getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 juce::PixelARGB::getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
In other words, if the return-value is read as a uint8 array then the elements will be in the order of a, r, g, b
forcedinline uint32 juce::PixelARGB::getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent.
forcedinline uint32 juce::PixelARGB::getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent.
forcedinline uint8 juce::PixelARGB::getAlpha () const noexcept
Referenced by juce::Colour::getAlpha().
forcedinline uint8 juce::PixelARGB::getRed () const noexcept
Referenced by juce::Colour::getRed().
forcedinline uint8 juce::PixelARGB::getGreen () const noexcept
Referenced by juce::Colour::getGreen().
forcedinline uint8 juce::PixelARGB::getBlue () const noexcept
Referenced by juce::Colour::getBlue().
forcedinline uint8& juce::PixelARGB::getAlpha () noexcept
forcedinline uint8& juce::PixelARGB::getRed () noexcept
forcedinline uint8& juce::PixelARGB::getGreen () noexcept
forcedinline uint8& juce::PixelARGB::getBlue () noexcept
template<class Pixel > forcedinline void juce::PixelARGB::set (const Pixel & src) noexcept
Copies another pixel colour over this one.
This doesn't blend it - this colour is simply replaced by the other one.
void juce::PixelARGB::setARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
Sets the pixel's colour from individual components.
template<class Pixel > forcedinline void juce::PixelARGB::blend (const Pixel & src) noexcept
Blends another pixel onto this one.
This takes into account the opacity of the pixel being overlaid, and blends it accordingly.
References juce::clampPixelComponents(), and juce::maskPixelComponents().
template<class Pixel > forcedinline void juce::PixelARGB::blend (const Pixel & src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
The opacity of the pixel being overlaid is scaled by the extraAlpha factor before being used, so this can blend semi-transparently from a PixelRGB argument.
References juce::clampPixelComponents(), and juce::maskPixelComponents().
template<class Pixel > forcedinline void juce::PixelARGB::tween (const Pixel & src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void juce::PixelARGB::setAlpha (const uint8 newAlpha) noexcept
Replaces the colour's alpha value with another one.
forcedinline void juce::PixelARGB::multiplyAlpha (int multiplier) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void juce::PixelARGB::multiplyAlpha (const float multiplier) noexcept
PixelARGB juce::PixelARGB::getUnpremultiplied () const noexcept
References unpremultiply().
forcedinline void juce::PixelARGB::premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void juce::PixelARGB::unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
References juce::jmin().
Referenced by getUnpremultiplied().
forcedinline void juce::PixelARGB::desaturate () noexcept
Member Data Documentation
uint32 juce::PixelARGB::internal
Components juce::PixelARGB::components
The documentation for this class was generated from the following file:
juce_PixelFormats.h