JUCE: juce::LinkedListPointer< ObjectType > Class Template Reference
juce::LinkedListPointer< ObjectType > Class Template Reference
containers
Helps to manipulate singly-linked lists of objects.
Classes
class Appender
Allows efficient repeated insertions into a list.
Public Member Functions
LinkedListPointer () noexcept
Creates a null pointer to an empty list.
LinkedListPointer (ObjectType *const headItem) noexcept
Creates a pointer to a list whose head is the item provided.
LinkedListPointer & operator= (ObjectType *const newItem) noexcept
Sets this pointer to point to a new list.
LinkedListPointer (LinkedListPointer &&other) noexcept
LinkedListPointer & operator= (LinkedListPointer &&other) noexcept
operator ObjectType * () const noexcept
Returns the item which this pointer points to.
ObjectType * get () const noexcept
Returns the item which this pointer points to.
LinkedListPointer & getLast () noexcept
Returns the last item in the list which this pointer points to.
int size () const noexcept
Returns the number of items in the list.
LinkedListPointer & operator[] (int index) noexcept
Returns the item at a given index in the list.
const LinkedListPointer & operator[] (int index) const noexcept
Returns the item at a given index in the list.
bool contains (const ObjectType *const itemToLookFor) const noexcept
Returns true if the list contains the given item.
void insertNext (ObjectType *const newItem)
Inserts an item into the list, placing it before the item that this pointer currently points to.
void insertAtIndex (int index, ObjectType *newItem)
Inserts an item at a numeric index in the list.
ObjectType * replaceNext (ObjectType *const newItem) noexcept
Replaces the object that this pointer points to, appending the rest of the list to the new object, and returning the old one.
void append (ObjectType *const newItem)
Adds an item to the end of the list.
void addCopyOfList (const LinkedListPointer &other)
Creates copies of all the items in another list and adds them to this one.
ObjectType * removeNext () noexcept
Removes the head item from the list.
void remove (ObjectType *const itemToRemove)
Removes a specific item from the list.
void deleteAll ()
Iterates the list, calling the delete operator on all of its elements and leaving this pointer empty.
LinkedListPointer * findPointerTo (ObjectType *const itemToLookFor) noexcept
Finds a pointer to a given item.
void copyToArray (ObjectType **destArray) const noexcept
Copies the items in the list to an array.
void swapWith (LinkedListPointer &other) noexcept
Swaps this pointer with another one.
Detailed Description
template<class ObjectType>
class juce::LinkedListPointer< ObjectType >
Helps to manipulate singly-linked lists of objects.
For objects that are designed to contain a pointer to the subsequent item in the list, this class contains methods to deal with the list. To use it, the ObjectType class that it points to must contain a LinkedListPointer called nextListItem, e.g.
struct MyObject
{
    int x, y, z;
    // A linkable object must contain a member with this name and type, which must be
    // accessible by the LinkedListPointer class. (This doesn't mean it has to be public -
    // you could make your class a friend of a LinkedListPointer<MyObject> instead).
    LinkedListPointer<MyObject> nextListItem;
};
LinkedListPointer<MyObject> myList;
myList.append (new MyObject());
myList.append (new MyObject());
int numItems = myList.size(); // returns 2
MyObject* lastInList = myList.getLast();
Constructor & Destructor Documentation
template<class ObjectType> juce::LinkedListPointer< ObjectType >::LinkedListPointer () noexcept
Creates a null pointer to an empty list.
template<class ObjectType> juce::LinkedListPointer< ObjectType >::LinkedListPointer (ObjectType *const headItem) explicit noexcept
Creates a pointer to a list whose head is the item provided.
template<class ObjectType> juce::LinkedListPointer< ObjectType >::LinkedListPointer (LinkedListPointer< ObjectType > && other) noexcept
Member Function Documentation
template<class ObjectType> LinkedListPointer& juce::LinkedListPointer< ObjectType >::operator= (ObjectType *const newItem) noexcept
Sets this pointer to point to a new list.
template<class ObjectType> LinkedListPointer& juce::LinkedListPointer< ObjectType >::operator= (LinkedListPointer< ObjectType > && other) noexcept
template<class ObjectType> juce::LinkedListPointer< ObjectType >::operator ObjectType * () const noexcept
Returns the item which this pointer points to.
template<class ObjectType> ObjectType* juce::LinkedListPointer< ObjectType >::get () const noexcept
Returns the item which this pointer points to.
template<class ObjectType> LinkedListPointer& juce::LinkedListPointer< ObjectType >::getLast () noexcept
Returns the last item in the list which this pointer points to.
This will iterate the list and return the last item found. Obviously the speed of this operation will be proportional to the size of the list. If the list is empty the return value will be this object. If you're planning on appending a number of items to your list, it's much more efficient to use the Appender class than to repeatedly call getLast() to find the end.
Referenced by juce::LinkedListPointer< juce::XmlElement >::append().
template<class ObjectType> int juce::LinkedListPointer< ObjectType >::size () const noexcept
Returns the number of items in the list.
Obviously with a simple linked list, getting the size involves iterating the list, so this can be a lengthy operation - be careful when using this method in your code.
template<class ObjectType> LinkedListPointer& juce::LinkedListPointer< ObjectType >::operator[] (int index) noexcept
Returns the item at a given index in the list.
Since the only way to find an item is to iterate the list, this operation can obviously be slow, depending on its size, so you should be careful when using this in algorithms.
template<class ObjectType> const LinkedListPointer& juce::LinkedListPointer< ObjectType >::operator[] (int index) const noexcept
Returns the item at a given index in the list.
Since the only way to find an item is to iterate the list, this operation can obviously be slow, depending on its size, so you should be careful when using this in algorithms.
template<class ObjectType> bool juce::LinkedListPointer< ObjectType >::contains (const ObjectType *const itemToLookFor) const noexcept
Returns true if the list contains the given item.
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::insertNext (ObjectType *const newItem)
Inserts an item into the list, placing it before the item that this pointer currently points to.
Referenced by juce::LinkedListPointer< juce::XmlElement >::addCopyOfList(), and juce::LinkedListPointer< juce::XmlElement >::insertAtIndex().
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::insertAtIndex (int index, ObjectType * newItem)
Inserts an item at a numeric index in the list.
Obviously this will involve iterating the list to find the item at the given index, so be careful about the impact this may have on execution time.
template<class ObjectType> ObjectType* juce::LinkedListPointer< ObjectType >::replaceNext (ObjectType *const newItem) noexcept
Replaces the object that this pointer points to, appending the rest of the list to the new object, and returning the old one.
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::append (ObjectType *const newItem)
Adds an item to the end of the list.
This operation involves iterating the whole list, so can be slow - if you need to append a number of items to your list, it's much more efficient to use the Appender class than to repeatedly call append().
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::addCopyOfList (const LinkedListPointer< ObjectType > & other)
Creates copies of all the items in another list and adds them to this one.
This will use the ObjectType's copy constructor to try to create copies of each item in the other list, and appends them to this list.
template<class ObjectType> ObjectType* juce::LinkedListPointer< ObjectType >::removeNext () noexcept
Removes the head item from the list.
This won't delete the object that is removed, but returns it, so the caller can delete it if necessary.
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::remove (ObjectType *const itemToRemove)
Removes a specific item from the list.
Note that this will not delete the item, it simply unlinks it from the list.
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::deleteAll ()
Iterates the list, calling the delete operator on all of its elements and leaving this pointer empty.
template<class ObjectType> LinkedListPointer* juce::LinkedListPointer< ObjectType >::findPointerTo (ObjectType *const itemToLookFor) noexcept
Finds a pointer to a given item.
If the item is found in the list, this returns the pointer that points to it. If the item isn't found, this returns null.
Referenced by juce::LinkedListPointer< juce::XmlElement >::remove().
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::copyToArray (ObjectType ** destArray) const noexcept
Copies the items in the list to an array.
The destArray must contain enough elements to hold the entire list - no checks are made for this!
template<class ObjectType> void juce::LinkedListPointer< ObjectType >::swapWith (LinkedListPointer< ObjectType > & other) noexcept
Swaps this pointer with another one.
The documentation for this class was generated from the following file:
juce_LinkedListPointer.h