JUCE: juce::AudioBuffer< Type > Class Template Reference
juce::AudioBuffer< Type > Class Template Reference
buffers
A multi-channel buffer of floating point audio samples.
Public Member Functions
AudioBuffer () noexcept
Creates an empty buffer with 0 channels and 0 length.
AudioBuffer (int numChannelsToAllocate, int numSamplesToAllocate)
Creates a buffer with a specified number of channels and samples.
AudioBuffer (Type *const *dataToReferTo, int numChannelsToUse, int numSamples)
Creates a buffer using a pre-allocated block of memory.
AudioBuffer (Type *const *dataToReferTo, int numChannelsToUse, int startSample, int numSamples)
Creates a buffer using a pre-allocated block of memory.
AudioBuffer (const AudioBuffer &other)
Copies another buffer.
AudioBuffer & operator= (const AudioBuffer &other)
Copies another buffer onto this one.
~AudioBuffer () noexcept
Destructor.
AudioBuffer (AudioBuffer &&other) noexcept
Move constructor.
AudioBuffer & operator= (AudioBuffer &&other) noexcept
Move assignment.
int getNumChannels () const noexcept
Returns the number of channels of audio data that this buffer contains.
int getNumSamples () const noexcept
Returns the number of samples allocated in each of the buffer's channels.
const Type * getReadPointer (int channelNumber) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
const Type * getReadPointer (int channelNumber, int sampleIndex) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
Type * getWritePointer (int channelNumber) noexcept
Returns a writeable pointer to one of the buffer's channels.
Type * getWritePointer (int channelNumber, int sampleIndex) noexcept
Returns a writeable pointer to one of the buffer's channels.
const Type ** getArrayOfReadPointers () const noexcept
Returns an array of pointers to the channels in the buffer.
Type ** getArrayOfWritePointers () noexcept
Returns an array of pointers to the channels in the buffer.
void setSize (int newNumChannels, int newNumSamples, bool keepExistingContent=false, bool clearExtraSpace=false, bool avoidReallocating=false)
Changes the buffer's size or number of channels.
void setDataToReferTo (Type **dataToReferTo, int newNumChannels, int newStartSample, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
void setDataToReferTo (Type **dataToReferTo, int newNumChannels, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
template<typename OtherType >
void makeCopyOf (const AudioBuffer< OtherType > &other, bool avoidReallocating=false)
Resizes this buffer to match the given one, and copies all of its content across.
void clear () noexcept
Clears all the samples in all channels.
void clear (int startSample, int numSamples) noexcept
Clears a specified region of all the channels.
void clear (int channel, int startSample, int numSamples) noexcept
Clears a specified region of just one channel.
bool hasBeenCleared () const noexcept
Returns true if the buffer has been entirely cleared.
Type getSample (int channel, int sampleIndex) const noexcept
Returns a sample from the buffer.
void setSample (int destChannel, int destSample, Type newValue) noexcept
Sets a sample in the buffer.
void addSample (int destChannel, int destSample, Type valueToAdd) noexcept
Adds a value to a sample in the buffer.
void applyGain (int channel, int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of one channel.
void applyGain (int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of all the channels.
void applyGain (Type gain) noexcept
Applies a gain multiple to all the audio data.
void applyGainRamp (int channel, int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of a channel.
void applyGainRamp (int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of all channels.
void addFrom (int destChannel, int destStartSample, const AudioBuffer &source, int sourceChannel, int sourceStartSample, int numSamples, Type gainToApplyToSource=(Type) 1) noexcept
Adds samples from another buffer to this one.
void addFrom (int destChannel, int destStartSample, const Type *source, int numSamples, Type gainToApplyToSource=(Type) 1) noexcept
Adds samples from an array of floats to one of the channels.
void addFromWithRamp (int destChannel, int destStartSample, const Type *source, int numSamples, Type startGain, Type endGain) noexcept
Adds samples from an array of floats, applying a gain ramp to them.
void copyFrom (int destChannel, int destStartSample, const AudioBuffer &source, int sourceChannel, int sourceStartSample, int numSamples) noexcept
Copies samples from another buffer to this one.
void copyFrom (int destChannel, int destStartSample, const Type *source, int numSamples) noexcept
Copies samples from an array of floats into one of the channels.
void copyFrom (int destChannel, int destStartSample, const Type *source, int numSamples, Type gain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain to it.
void copyFromWithRamp (int destChannel, int destStartSample, const Type *source, int numSamples, Type startGain, Type endGain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain ramp.
Range< Type > findMinMax (int channel, int startSample, int numSamples) const noexcept
Returns a Range indicating the lowest and highest sample values in a given section.
Type getMagnitude (int channel, int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region of a channel.
Type getMagnitude (int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region on all channels.
Type getRMSLevel (int channel, int startSample, int numSamples) const noexcept
Returns the root mean squared level for a region of a channel.
void reverse (int channel, int startSample, int numSamples) const noexcept
Reverses a part of a channel.
void reverse (int startSample, int numSamples) const noexcept
Reverses a part of the buffer.
Detailed Description
template<typename Type>
class juce::AudioBuffer< Type >
A multi-channel buffer of floating point audio samples.
See Also
AudioSampleBuffer
Constructor & Destructor Documentation
template<typename Type> juce::AudioBuffer< Type >::AudioBuffer () noexcept
Creates an empty buffer with 0 channels and 0 length.
template<typename Type> juce::AudioBuffer< Type >::AudioBuffer (int numChannelsToAllocate, int numSamplesToAllocate)
Creates a buffer with a specified number of channels and samples.
The contents of the buffer will initially be undefined, so use clear() to set all the samples to zero.
The buffer will allocate its memory internally, and this will be released when the buffer is deleted. If the memory can't be allocated, this will throw a std::bad_alloc exception.
template<typename Type> juce::AudioBuffer< Type >::AudioBuffer (Type *const * dataToReferTo, int numChannelsToUse, int numSamples)
Creates a buffer using a pre-allocated block of memory.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
numChannelsToUse the number of channels to use - this must correspond to the number of elements in the array passed in
numSamples the number of samples to use - this must correspond to the size of the arrays passed in
template<typename Type> juce::AudioBuffer< Type >::AudioBuffer (Type *const * dataToReferTo, int numChannelsToUse, int startSample, int numSamples)
Creates a buffer using a pre-allocated block of memory.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
numChannelsToUse the number of channels to use - this must correspond to the number of elements in the array passed in
startSample the offset within the arrays at which the data begins
numSamples the number of samples to use - this must correspond to the size of the arrays passed in
template<typename Type> juce::AudioBuffer< Type >::AudioBuffer (const AudioBuffer< Type > & other)
Copies another buffer.
This buffer will make its own copy of the other's data, unless the buffer was created using an external data buffer, in which case boths buffers will just point to the same shared block of data.
template<typename Type> juce::AudioBuffer< Type >::~AudioBuffer () noexcept
Destructor.
This will free any memory allocated by the buffer.
template<typename Type> juce::AudioBuffer< Type >::AudioBuffer (AudioBuffer< Type > && other) noexcept
Move constructor.
Member Function Documentation
template<typename Type> AudioBuffer& juce::AudioBuffer< Type >::operator= (const AudioBuffer< Type > & other)
Copies another buffer onto this one.
This buffer's size will be changed to that of the other buffer.
template<typename Type> AudioBuffer& juce::AudioBuffer< Type >::operator= (AudioBuffer< Type > && other) noexcept
Move assignment.
template<typename Type> int juce::AudioBuffer< Type >::getNumChannels () const noexcept
Returns the number of channels of audio data that this buffer contains.
See Also
getNumSamples, getReadPointer, getWritePointer
Referenced by juce::VST3BufferExchange< float >::associateBufferTo(), juce::AudioUnitHelpers::CoreAudioBufferList::getBuffer(), juce::AudioBuffer< float >::makeCopyOf(), juce::AudioBuffer< float >::operator=(), juce::AudioUnitHelpers::CoreAudioBufferList::pop(), juce::AudioUnitHelpers::CoreAudioBufferList::push(), juce::AudioUnitHelpers::CoreAudioBufferList::reset(), and juce::AudioUnitHelpers::CoreAudioBufferList::setBuffer().
template<typename Type> int juce::AudioBuffer< Type >::getNumSamples () const noexcept
Returns the number of samples allocated in each of the buffer's channels.
See Also
getNumChannels, getReadPointer, getWritePointer
Referenced by juce::AudioProcessor::getBusBuffer(), juce::AudioBuffer< float >::makeCopyOf(), and juce::AudioBuffer< float >::operator=().
template<typename Type> const Type* juce::AudioBuffer< Type >::getReadPointer (int channelNumber) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
For speed, this doesn't check whether the channel number is out of range, so be careful when using it! If you need to write to the data, do NOT call this method and const_cast the result! Instead, you must call getWritePointer so that the buffer knows you're planning on modifying the data.
Referenced by juce::AudioBuffer< float >::makeCopyOf().
template<typename Type> const Type* juce::AudioBuffer< Type >::getReadPointer (int channelNumber, int sampleIndex) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
For speed, this doesn't check whether the channel number or index are out of range, so be careful when using it! If you need to write to the data, do NOT call this method and const_cast the result! Instead, you must call getWritePointer so that the buffer knows you're planning on modifying the data.
template<typename Type> Type* juce::AudioBuffer< Type >::getWritePointer (int channelNumber) noexcept
Returns a writeable pointer to one of the buffer's channels.
For speed, this doesn't check whether the channel number is out of range, so be careful when using it! Note that if you're not planning on writing to the data, you should always use getReadPointer instead.
Referenced by juce::VST3BufferExchange< float >::associateBufferTo().
template<typename Type> Type* juce::AudioBuffer< Type >::getWritePointer (int channelNumber, int sampleIndex) noexcept
Returns a writeable pointer to one of the buffer's channels.
For speed, this doesn't check whether the channel number or index are out of range, so be careful when using it! Note that if you're not planning on writing to the data, you should use getReadPointer instead.
template<typename Type> const Type** juce::AudioBuffer< Type >::getArrayOfReadPointers () const noexcept
Returns an array of pointers to the channels in the buffer.
Don't modify any of the pointers that are returned, and bear in mind that these will become invalid if the buffer is resized.
template<typename Type> Type** juce::AudioBuffer< Type >::getArrayOfWritePointers () noexcept
Returns an array of pointers to the channels in the buffer.
Don't modify any of the pointers that are returned, and bear in mind that these will become invalid if the buffer is resized.
Referenced by juce::AudioProcessor::getBusBuffer().
template<typename Type> void juce::AudioBuffer< Type >::setSize (int newNumChannels, int newNumSamples, bool keepExistingContent = false, bool clearExtraSpace = false, bool avoidReallocating = false)
Changes the buffer's size or number of channels.
This can expand or contract the buffer's length, and add or remove channels.
If keepExistingContent is true, it will try to preserve as much of the old data as it can in the new buffer.
If clearExtraSpace is true, then any extra channels or space that is allocated will be also be cleared. If false, then this space is left uninitialised.
If avoidReallocating is true, then changing the buffer's size won't reduce the amount of memory that is currently allocated (but it will still increase it if the new size is bigger than the amount it currently has). If this is false, then a new allocation will be done so that the buffer uses takes up the minimum amount of memory that it needs.
If the required memory can't be allocated, this will throw a std::bad_alloc exception.
Referenced by juce::AudioBuffer< float >::makeCopyOf(), juce::AudioBuffer< float >::operator=(), juce::AudioUnitHelpers::CoreAudioBufferList::prepare(), and juce::AudioUnitHelpers::CoreAudioBufferList::release().
template<typename Type> void juce::AudioBuffer< Type >::setDataToReferTo (Type ** dataToReferTo, int newNumChannels, int newStartSample, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
There's also a constructor that lets you specify arrays like this, but this lets you change the channels dynamically.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
newNumChannels the number of channels to use - this must correspond to the number of elements in the array passed in
newStartSample the offset within the arrays at which the data begins
newNumSamples the number of samples to use - this must correspond to the size of the arrays passed in
Referenced by juce::AudioUnitHelpers::CoreAudioBufferList::getBuffer(), and juce::AudioBuffer< float >::setDataToReferTo().
template<typename Type> void juce::AudioBuffer< Type >::setDataToReferTo (Type ** dataToReferTo, int newNumChannels, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
There's also a constructor that lets you specify arrays like this, but this lets you change the channels dynamically.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
newNumChannels the number of channels to use - this must correspond to the number of elements in the array passed in
newNumSamples the number of samples to use - this must correspond to the size of the arrays passed in
template<typename Type> template<typename OtherType > void juce::AudioBuffer< Type >::makeCopyOf (const AudioBuffer< OtherType > & other, bool avoidReallocating = false)
Resizes this buffer to match the given one, and copies all of its content across.
The source buffer can contain a different floating point type, so this can be used to convert between 32 and 64 bit float buffer types.
template<typename Type> void juce::AudioBuffer< Type >::clear () noexcept
Clears all the samples in all channels.
Referenced by juce::AudioBuffer< float >::AudioBuffer(), juce::AudioBuffer< float >::makeCopyOf(), and juce::AudioBuffer< float >::operator=().
template<typename Type> void juce::AudioBuffer< Type >::clear (int startSample, int numSamples) noexcept
Clears a specified region of all the channels.
For speed, this doesn't check whether the channel and sample number are in-range, so be careful!
template<typename Type> void juce::AudioBuffer< Type >::clear (int channel, int startSample, int numSamples) noexcept
Clears a specified region of just one channel.
For speed, this doesn't check whether the channel and sample number are in-range, so be careful!
template<typename Type> bool juce::AudioBuffer< Type >::hasBeenCleared () const noexcept
Returns true if the buffer has been entirely cleared.
Note that this does not actually measure the contents of the buffer - it simply returns a flag that is set when the buffer is cleared, and which is reset whenever functions like getWritePointer() are invoked. That means the method does not take any time, but it may return false negatives when in fact the buffer is still empty.
Referenced by juce::AudioBuffer< float >::makeCopyOf().
template<typename Type> Type juce::AudioBuffer< Type >::getSample (int channel, int sampleIndex) const noexcept
Returns a sample from the buffer.
The channel and index are not checked - they are expected to be in-range. If not, an assertion will be thrown, but in a release build, you're into 'undefined behaviour' territory.
template<typename Type> void juce::AudioBuffer< Type >::setSample (int destChannel, int destSample, Type newValue) noexcept
Sets a sample in the buffer.
The channel and index are not checked - they are expected to be in-range. If not, an assertion will be thrown, but in a release build, you're into 'undefined behaviour' territory.
template<typename Type> void juce::AudioBuffer< Type >::addSample (int destChannel, int destSample, Type valueToAdd) noexcept
Adds a value to a sample in the buffer.
The channel and index are not checked - they are expected to be in-range. If not, an assertion will be thrown, but in a release build, you're into 'undefined behaviour' territory.
template<typename Type> void juce::AudioBuffer< Type >::applyGain (int channel, int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of one channel.
For speed, this doesn't check whether the channel and sample number are in-range, so be careful!
Referenced by juce::AudioBuffer< float >::applyGain(), and juce::AudioBuffer< float >::applyGainRamp().
template<typename Type> void juce::AudioBuffer< Type >::applyGain (int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of all the channels.
For speed, this doesn't check whether the sample numbers are in-range, so be careful!
template<typename Type> void juce::AudioBuffer< Type >::applyGain (Type gain) noexcept
Applies a gain multiple to all the audio data.
template<typename Type> void juce::AudioBuffer< Type >::applyGainRamp (int channel, int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of a channel.
The gain that is applied to each sample will vary from startGain on the first sample to endGain on the last Sample, so it can be used to do basic fades.
For speed, this doesn't check whether the sample numbers are in-range, so be careful!
Referenced by juce::AudioBuffer< float >::applyGainRamp().
template<typename Type> void juce::AudioBuffer< Type >::applyGainRamp (int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of all channels.
The gain that is applied to each sample will vary from startGain on the first sample to endGain on the last Sample, so it can be used to do basic fades.
For speed, this doesn't check whether the sample numbers are in-range, so be careful!
template<typename Type> void juce::AudioBuffer< Type >::addFrom (int destChannel, int destStartSample, const AudioBuffer< Type > & source, int sourceChannel, int sourceStartSample, int numSamples, Type gainToApplyToSource = (Type) 1) noexcept
Adds samples from another buffer to this one.
Parameters
destChannel the channel within this buffer to add the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to add from
sourceChannel the channel within the source buffer to read from
sourceStartSample the offset within the source buffer's channel to start reading samples from
numSamples the number of samples to process
gainToApplyToSource an optional gain to apply to the source samples before they are added to this buffer's samples
See Also
copyFrom
Referenced by juce::AudioBuffer< float >::addFromWithRamp().
template<typename Type> void juce::AudioBuffer< Type >::addFrom (int destChannel, int destStartSample, const Type * source, int numSamples, Type gainToApplyToSource = (Type) 1) noexcept
Adds samples from an array of floats to one of the channels.
Parameters
destChannel the channel within this buffer to add the samples to
destStartSample the start sample within this buffer's channel
source the source data to use
numSamples the number of samples to process
gainToApplyToSource an optional gain to apply to the source samples before they are added to this buffer's samples
See Also
copyFrom
template<typename Type> void juce::AudioBuffer< Type >::addFromWithRamp (int destChannel, int destStartSample, const Type * source, int numSamples, Type startGain, Type endGain) noexcept
Adds samples from an array of floats, applying a gain ramp to them.
Parameters
destChannel the channel within this buffer to add the samples to
destStartSample the start sample within this buffer's channel
source the source data to use
numSamples the number of samples to process
startGain the gain to apply to the first sample (this is multiplied with the source samples before they are added to this buffer)
endGain the gain to apply to the final sample. The gain is linearly interpolated between the first and last samples.
template<typename Type> void juce::AudioBuffer< Type >::copyFrom (int destChannel, int destStartSample, const AudioBuffer< Type > & source, int sourceChannel, int sourceStartSample, int numSamples) noexcept
Copies samples from another buffer to this one.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
sourceChannel the channel within the source buffer to read from
sourceStartSample the offset within the source buffer's channel to start reading samples from
numSamples the number of samples to process
See Also
addFrom
Referenced by juce::AudioBuffer< float >::copyFromWithRamp().
template<typename Type> void juce::AudioBuffer< Type >::copyFrom (int destChannel, int destStartSample, const Type * source, int numSamples) noexcept
Copies samples from an array of floats into one of the channels.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
numSamples the number of samples to process
See Also
addFrom
template<typename Type> void juce::AudioBuffer< Type >::copyFrom (int destChannel, int destStartSample, const Type * source, int numSamples, Type gain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain to it.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
numSamples the number of samples to process
gain the gain to apply
See Also
addFrom
template<typename Type> void juce::AudioBuffer< Type >::copyFromWithRamp (int destChannel, int destStartSample, const Type * source, int numSamples, Type startGain, Type endGain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain ramp.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
numSamples the number of samples to process
startGain the gain to apply to the first sample (this is multiplied with the source samples before they are copied to this buffer)
endGain the gain to apply to the final sample. The gain is linearly interpolated between the first and last samples.
See Also
addFrom
template<typename Type> Range<Type> juce::AudioBuffer< Type >::findMinMax (int channel, int startSample, int numSamples) const noexcept
Returns a Range indicating the lowest and highest sample values in a given section.
Parameters
channel the channel to read from
startSample the start sample within the channel
numSamples the number of samples to check
Referenced by juce::AudioBuffer< float >::getMagnitude().
template<typename Type> Type juce::AudioBuffer< Type >::getMagnitude (int channel, int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region of a channel.
Referenced by juce::AudioBuffer< float >::getMagnitude().
template<typename Type> Type juce::AudioBuffer< Type >::getMagnitude (int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region on all channels.
template<typename Type> Type juce::AudioBuffer< Type >::getRMSLevel (int channel, int startSample, int numSamples) const noexcept
Returns the root mean squared level for a region of a channel.
template<typename Type> void juce::AudioBuffer< Type >::reverse (int channel, int startSample, int numSamples) const noexcept
Reverses a part of a channel.
Referenced by juce::AudioBuffer< float >::reverse().
template<typename Type> void juce::AudioBuffer< Type >::reverse (int startSample, int numSamples) const noexcept
Reverses a part of the buffer.
The documentation for this class was generated from the following file:
juce_AudioSampleBuffer.h