JUCE: SmoothedValueBase< SmoothedValueClass, FloatType > Class Template Reference
SmoothedValueBase< SmoothedValueClass, FloatType > Class Template Reference
utilities
A base class for the smoothed value classes.
Public Member Functions
SmoothedValueBase ()=default
Constructor.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
FloatType getCurrentValue () const noexcept
Returns the current value of the ramp.
FloatType getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
void setCurrentAndTargetValue (FloatType newValue)
Sets the current value and the target value.
void applyGain (FloatType *samples, int numSamples) noexcept
Applies a smoothed gain to a stream of samples S[i] *= gain.
void applyGain (FloatType *samplesOut, const FloatType *samplesIn, int numSamples) noexcept
Computes output as a smoothed gain applied to a stream of samples.
void applyGain (AudioBuffer< FloatType > &buffer, int numSamples) noexcept
Applies a smoothed gain to a buffer.
Protected Member Functions
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Protected Attributes
FloatType currentValue = 0
FloatType target = 0
int countdown = 0
Detailed Description
template<template< typename > class SmoothedValueClass, typename FloatType>
class SmoothedValueBase< SmoothedValueClass, FloatType >
A base class for the smoothed value classes.
Constructor & Destructor Documentation
template<template< typename > class SmoothedValueClass, typename FloatType> SmoothedValueBase< SmoothedValueClass, FloatType >::SmoothedValueBase () default
Constructor.
Member Function Documentation
template<template< typename > class SmoothedValueClass, typename FloatType> bool SmoothedValueBase< SmoothedValueClass, FloatType >::isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
Referenced by SmoothedValueBase< LinearSmoothedValue, FloatType >::applyGain(), and dsp::Oscillator< SampleType >::process().
template<template< typename > class SmoothedValueClass, typename FloatType> FloatType SmoothedValueBase< SmoothedValueClass, FloatType >::getCurrentValue () const noexcept
Returns the current value of the ramp.
template<template< typename > class SmoothedValueClass, typename FloatType> FloatType SmoothedValueBase< SmoothedValueClass, FloatType >::getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
Referenced by dsp::Oscillator< SampleType >::getFrequency().
template<template< typename > class SmoothedValueClass, typename FloatType> void SmoothedValueBase< SmoothedValueClass, FloatType >::setCurrentAndTargetValue (FloatType newValue)
Sets the current value and the target value.
Parameters
newValue the new value to take
Referenced by dsp::Oscillator< SampleType >::setFrequency().
template<template< typename > class SmoothedValueClass, typename FloatType> void SmoothedValueBase< SmoothedValueClass, FloatType >::applyGain (FloatType * samples, int numSamples) noexcept
Applies a smoothed gain to a stream of samples S[i] *= gain.
Parameters
samples Pointer to a raw array of samples
numSamples Length of array of samples
template<template< typename > class SmoothedValueClass, typename FloatType> void SmoothedValueBase< SmoothedValueClass, FloatType >::applyGain (FloatType * samplesOut, const FloatType * samplesIn, int numSamples) noexcept
Computes output as a smoothed gain applied to a stream of samples.
Sout[i] = Sin[i] * gain
Parameters
samplesOut A pointer to a raw array of output samples
samplesIn A pointer to a raw array of input samples
numSamples The length of the array of samples
template<template< typename > class SmoothedValueClass, typename FloatType> void SmoothedValueBase< SmoothedValueClass, FloatType >::applyGain (AudioBuffer< FloatType > & buffer, int numSamples) noexcept
Applies a smoothed gain to a buffer.
template<template< typename > class SmoothedValueClass, typename FloatType> void SmoothedValueBase< SmoothedValueClass, FloatType >::reset (double sampleRate, double rampLengthInSeconds) protected noexcept
Member Data Documentation
template<template< typename > class SmoothedValueClass, typename FloatType> FloatType SmoothedValueBase< SmoothedValueClass, FloatType >::currentValue = 0 protected
Referenced by SmoothedValueBase< LinearSmoothedValue, FloatType >::getCurrentValue(), and SmoothedValueBase< LinearSmoothedValue, FloatType >::setCurrentAndTargetValue().
template<template< typename > class SmoothedValueClass, typename FloatType> FloatType SmoothedValueBase< SmoothedValueClass, FloatType >::target = 0 protected
Referenced by SmoothedValueBase< LinearSmoothedValue, FloatType >::applyGain(), SmoothedValueBase< LinearSmoothedValue, FloatType >::getTargetValue(), and SmoothedValueBase< LinearSmoothedValue, FloatType >::setCurrentAndTargetValue().
template<template< typename > class SmoothedValueClass, typename FloatType> int SmoothedValueBase< SmoothedValueClass, FloatType >::countdown = 0 protected
Referenced by SmoothedValueBase< LinearSmoothedValue, FloatType >::isSmoothing(), and SmoothedValueBase< LinearSmoothedValue, FloatType >::setCurrentAndTargetValue().
The documentation for this class was generated from the following file:
juce_SmoothedValues.h