JUCE: juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass > Class Template Reference
juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass > Class Template Reference
A smart-pointer class which points to a reference-counted object.
Public Types
typedef ReferenceCountedObjectClass ReferencedType
The class being referenced by this pointer.
Public Member Functions
ReferenceCountedObjectPtr () noexcept
Creates a pointer to a null object.
ReferenceCountedObjectPtr (decltype(nullptr)) noexcept
Creates a pointer to a null object.
ReferenceCountedObjectPtr (ReferencedType *refCountedObject) noexcept
Creates a pointer to an object.
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr &other) noexcept
Copies another pointer.
template<typename Convertible >
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > &other) noexcept
Copies another pointer.
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr &other)
Changes this pointer to point at a different object.
template<typename Convertible >
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr< Convertible > &other)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr & operator= (ReferencedType *const newObject)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr (ReferenceCountedObjectPtr &&other) noexcept
Takes-over the object from another pointer.
ReferenceCountedObjectPtr & operator= (ReferenceCountedObjectPtr &&other)
Takes-over the object from another pointer.
~ReferenceCountedObjectPtr ()
Destructor.
operator ReferencedType * () const noexcept
Returns the object that this pointer references.
ReferencedType * get () const noexcept
Returns the object that this pointer references.
ReferencedType * getObject () const noexcept
Returns the object that this pointer references.
ReferencedType * operator-> () const noexcept
Detailed Description
template<class ReferenceCountedObjectClass>
class juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >
A smart-pointer class which points to a reference-counted object.
The template parameter specifies the class of the object you want to point to - the easiest way to make a class reference-countable is to simply make it inherit from ReferenceCountedObject or SingleThreadedReferenceCountedObject, but if you need to, you can roll your own reference-countable class by implementing a set of methods called incReferenceCount(), decReferenceCount(), and decReferenceCountWithoutDeleting(). See ReferenceCountedObject for examples of how these methods should behave.
When using this class, you'll probably want to create a typedef to abbreviate the full templated name - e.g.
struct MyClass  : public ReferenceCountedObject
{
    typedef ReferenceCountedObjectPtr<MyClass> Ptr;
    ...
See Also
ReferenceCountedObject, ReferenceCountedObjectArray
Member Typedef Documentation
template<class ReferenceCountedObjectClass> typedef ReferenceCountedObjectClass juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferencedType
The class being referenced by this pointer.
Constructor & Destructor Documentation
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr () noexcept
Creates a pointer to a null object.
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (decltype(nullptr)) noexcept
Creates a pointer to a null object.
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (ReferencedType * refCountedObject) noexcept
Creates a pointer to an object.
This will increment the object's reference-count.
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & other) noexcept
Copies another pointer.
This will increment the object's reference-count.
template<class ReferenceCountedObjectClass> template<typename Convertible > juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > & other) noexcept
Copies another pointer.
This will increment the object's reference-count (if it is non-null).
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (ReferenceCountedObjectPtr< ReferenceCountedObjectClass > && other) noexcept
Takes-over the object from another pointer.
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::~ReferenceCountedObjectPtr ()
Destructor.
This will decrement the object's reference-count, which will cause the object to be deleted when the ref-count hits zero.
Member Function Documentation
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr& juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & other)
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Referenced by juce::ReferenceCountedObjectPtr< juce::ReferenceCountedObject >::operator=().
template<class ReferenceCountedObjectClass> template<typename Convertible > ReferenceCountedObjectPtr& juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (const ReferenceCountedObjectPtr< Convertible > & other)
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr& juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (ReferencedType *const newObject)
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr& juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (ReferenceCountedObjectPtr< ReferenceCountedObjectClass > && other)
Takes-over the object from another pointer.
template<class ReferenceCountedObjectClass> juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator ReferencedType * () const noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
template<class ReferenceCountedObjectClass> ReferencedType* juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::get () const noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
Referenced by juce::WeakReference< juce::Component >::get(), juce::WeakReference< ObjectType, ReferenceCountingType >::Master::getSharedPointer(), juce::ReferenceCountedObjectPtr< juce::ReferenceCountedObject >::operator=(), juce::WeakReference< juce::Component >::wasObjectDeleted(), and juce::WeakReference< ObjectType, ReferenceCountingType >::Master::~Master().
template<class ReferenceCountedObjectClass> ReferencedType* juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::getObject () const noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
template<class ReferenceCountedObjectClass> ReferencedType* juce::ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator-> () const noexcept
The documentation for this class was generated from the following file:
juce_ReferenceCountedObject.h