JUCE: juce::FakeMouseMoveGenerator Class Reference
juce::FakeMouseMoveGenerator Class Reference
utility
Public Member Functions
FakeMouseMoveGenerator ()
void timerCallback () override
The user-defined callback routine that actually gets called periodically.
Constructor & Destructor Documentation
juce::FakeMouseMoveGenerator::FakeMouseMoveGenerator ()
References juce::Timer::startTimer().
Member Function Documentation
void juce::FakeMouseMoveGenerator::timerCallback () override virtual
The user-defined callback routine that actually gets called periodically.
It's perfectly ok to call startTimer() or stopTimer() from within this callback to change the subsequent intervals.
Implements juce::Timer.
References juce::Time::currentTimeMillis(), juce::Desktop::findComponentAt(), juce::ModifierKeys::getCurrentModifiers(), juce::Desktop::getInstance(), juce::Desktop::getMainMouseSource(), juce::MouseInputSource::getScreenPosition(), juce::MouseInputSource::invalidOrientation, and juce::MouseInputSource::invalidPressure.
The documentation for this class was generated from the following file:
juce_FakeMouseMoveGenerator.h