JUCE: dsp::Gain< FloatType > Class Template Reference
dsp::Gain< FloatType > Class Template Reference
Applies a gain to audio samples as single samples or AudioBlocks.
Public Member Functions
Gain () noexcept=default
void setGainLinear (FloatType newGain) noexcept
Applies a new gain as a linear value.
void setGainDecibels (FloatType newGainDecibels) noexcept
Applies a new gain as a decibel value.
FloatType getGainLinear () const noexcept
Returns the current gain as a linear value.
FloatType getGainDecibels () const noexcept
Returns the current gain in decibels.
void setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
double getRampDurationSeconds () const noexcept
Returns the ramp duration in seconds.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
void prepare (const ProcessSpec &spec) noexcept
Called before processing starts.
void reset () noexcept
Resets the internal state of the gain.
template<typename SampleType >
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType s) noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes the input and output buffers supplied in the processing context.
Detailed Description
template<typename FloatType>
class dsp::Gain< FloatType >
Applies a gain to audio samples as single samples or AudioBlocks.
Constructor & Destructor Documentation
template<typename FloatType > dsp::Gain< FloatType >::Gain () default noexcept
Member Function Documentation
template<typename FloatType > void dsp::Gain< FloatType >::setGainLinear (FloatType newGain) noexcept
Applies a new gain as a linear value.
References SmoothedValue< FloatType, SmoothingType >::setTargetValue().
Referenced by dsp::Gain< FloatType >::setGainDecibels().
template<typename FloatType > void dsp::Gain< FloatType >::setGainDecibels (FloatType newGainDecibels) noexcept
Applies a new gain as a decibel value.
References dsp::Gain< FloatType >::setGainLinear().
template<typename FloatType > FloatType dsp::Gain< FloatType >::getGainLinear () const noexcept
Returns the current gain as a linear value.
References SmoothedValueBase< SmoothedValueType >::getTargetValue().
Referenced by dsp::Gain< FloatType >::getGainDecibels().
template<typename FloatType > FloatType dsp::Gain< FloatType >::getGainDecibels () const noexcept
Returns the current gain in decibels.
References dsp::Gain< FloatType >::getGainLinear().
template<typename FloatType > void dsp::Gain< FloatType >::setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
References dsp::Gain< FloatType >::reset().
template<typename FloatType > double dsp::Gain< FloatType >::getRampDurationSeconds () const noexcept
Returns the ramp duration in seconds.
template<typename FloatType > bool dsp::Gain< FloatType >::isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
References SmoothedValueBase< SmoothedValueType >::isSmoothing().
template<typename FloatType > void dsp::Gain< FloatType >::prepare (const ProcessSpec & spec) noexcept
Called before processing starts.
References dsp::Gain< FloatType >::reset().
template<typename FloatType > void dsp::Gain< FloatType >::reset () noexcept
Resets the internal state of the gain.
References SmoothedValue< FloatType, SmoothingType >::reset().
Referenced by dsp::Gain< FloatType >::prepare(), and dsp::Gain< FloatType >::setRampDurationSeconds().
template<typename FloatType > template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE dsp::Gain< FloatType >::processSample (SampleType s) noexcept
Returns the result of processing a single sample.
References SmoothedValue< FloatType, SmoothingType >::getNextValue().
template<typename FloatType > template<typename ProcessContext > void dsp::Gain< FloatType >::process (const ProcessContext & context) noexcept
Processes the input and output buffers supplied in the processing context.
References SmoothedValue< FloatType, SmoothingType >::getNextValue(), jassert, FloatVectorOperations::multiply(), and SmoothedValue< FloatType, SmoothingType >::skip().
The documentation for this class was generated from the following file:
juce_Gain.h