JUCE: juce::Font Class Reference
juce::Font Class Reference
fonts
Represents a particular font, including its size, style, etc.
Public Types
enum FontStyleFlags { plain = 0, bold = 1, italic = 2, underlined = 4 }
A combination of these values is used by the constructor to specify the style of font to use.
Public Member Functions
Font (float fontHeight, int styleFlags=plain)
Creates a sans-serif font in a given size.
Font (const String &typefaceName, float fontHeight, int styleFlags)
Creates a font with a given typeface and parameters.
Font (const String &typefaceName, const String &typefaceStyle, float fontHeight)
Creates a font with a given typeface and parameters.
Font (const Font &other) noexcept
Creates a copy of another Font object.
Font (const Typeface::Ptr &typeface)
Creates a font for a typeface.
Font ()
Creates a basic sans-serif font at a default height.
Font (Font &&other) noexcept
Move constructor.
Font & operator= (Font &&other) noexcept
Move assignment operator.
Font & operator= (const Font &other) noexcept
Copies this font from another one.
bool operator== (const Font &other) const noexcept
bool operator!= (const Font &other) const noexcept
~Font () noexcept
Destructor.
void setTypefaceName (const String &faceName)
Changes the font family of the typeface.
const String & getTypefaceName () const noexcept
Returns the font family of the typeface that this font uses.
const String & getTypefaceStyle () const noexcept
Returns the font style of the typeface that this font uses.
void setTypefaceStyle (const String &newStyle)
Changes the font style of the typeface.
Font withTypefaceStyle (const String &newStyle) const
Returns a copy of this font with a new typeface style.
StringArray getAvailableStyles () const
Returns a list of the styles that this font can use.
Font withHeight (float height) const
Returns a copy of this font with a new height.
Font withPointHeight (float heightInPoints) const
Returns a copy of this font with a new height, specified in points.
void setHeight (float newHeight)
Changes the font's height.
void setHeightWithoutChangingWidth (float newHeight)
Changes the font's height without changing its width.
float getHeight () const noexcept
Returns the total height of this font, in pixels.
float getHeightInPoints () const
Returns the total height of this font, in points.
float getAscent () const
Returns the height of the font above its baseline, in pixels.
float getAscentInPoints () const
Returns the height of the font above its baseline, in points.
float getDescent () const
Returns the amount that the font descends below its baseline, in pixels.
float getDescentInPoints () const
Returns the amount that the font descends below its baseline, in points.
int getStyleFlags () const noexcept
Returns the font's style flags.
Font withStyle (int styleFlags) const
Returns a copy of this font with the given set of style flags.
void setStyleFlags (int newFlags)
Changes the font's style.
void setBold (bool shouldBeBold)
Makes the font bold or non-bold.
Font boldened () const
Returns a copy of this font with the bold attribute set.
bool isBold () const noexcept
Returns true if the font is bold.
void setItalic (bool shouldBeItalic)
Makes the font italic or non-italic.
Font italicised () const
Returns a copy of this font with the italic attribute set.
bool isItalic () const noexcept
Returns true if the font is italic.
void setUnderline (bool shouldBeUnderlined)
Makes the font underlined or non-underlined.
bool isUnderlined () const noexcept
Returns true if the font is underlined.
float getHorizontalScale () const noexcept
Returns the font's horizontal scale.
Font withHorizontalScale (float scaleFactor) const
Returns a copy of this font with a new horizontal scale.
void setHorizontalScale (float scaleFactor)
Changes the font's horizontal scale factor.
float getExtraKerningFactor () const noexcept
Returns the font's kerning.
Font withExtraKerningFactor (float extraKerning) const
Returns a copy of this font with a new kerning factor.
void setExtraKerningFactor (float extraKerning)
Changes the font's kerning.
void setSizeAndStyle (float newHeight, int newStyleFlags, float newHorizontalScale, float newKerningAmount)
Changes all the font's characteristics with one call.
void setSizeAndStyle (float newHeight, const String &newStyle, float newHorizontalScale, float newKerningAmount)
Changes all the font's characteristics with one call.
int getStringWidth (const String &text) const
Returns the total width of a string as it would be drawn using this font.
float getStringWidthFloat (const String &text) const
Returns the total width of a string as it would be drawn using this font.
void getGlyphPositions (const String &text, Array< int > &glyphs, Array< float > &xOffsets) const
Returns the series of glyph numbers and their x offsets needed to represent a string.
Typeface * getTypeface () const
Returns the typeface used by this font.
String toString () const
Creates a string to describe this font.
Static Public Member Functions
static const String & getDefaultSansSerifFontName ()
Returns a typeface font family that represents the default sans-serif font.
static const String & getDefaultSerifFontName ()
Returns a typeface font family that represents the default serif font.
static const String & getDefaultMonospacedFontName ()
Returns a typeface font family that represents the default monospaced font.
static const String & getDefaultStyle ()
Returns a font style name that represents the default style.
static Typeface::Ptr getDefaultTypefaceForFont (const Font &font)
Returns the default system typeface for the given font.
static float getDefaultMinimumHorizontalScaleFactor () noexcept
Returns the minimum horizontal scale to which fonts may be squashed when trying to create a layout.
static void setDefaultMinimumHorizontalScaleFactor (float newMinimumScaleFactor) noexcept
Sets the minimum horizontal scale to which fonts may be squashed when trying to create a text layout.
static void findFonts (Array< Font > &results)
Creates an array of Font objects to represent all the fonts on the system.
static StringArray findAllTypefaceNames ()
Returns a list of all the available typeface font families.
static StringArray findAllTypefaceStyles (const String &family)
Returns a list of all the available typeface font styles.
static const String & getFallbackFontName ()
Returns the font family of the typeface to be used for rendering glyphs that aren't found in the requested typeface.
static void setFallbackFontName (const String &name)
Sets the (platform-specific) font family of the typeface to use to find glyphs that aren't available in whatever font you're trying to use.
static const String & getFallbackFontStyle ()
Returns the font style of the typeface to be used for rendering glyphs that aren't found in the requested typeface.
static void setFallbackFontStyle (const String &style)
Sets the (platform-specific) font style of the typeface to use to find glyphs that aren't available in whatever font you're trying to use.
static Font fromString (const String &fontDescription)
Recreates a font from its stringified encoding.
Detailed Description
Represents a particular font, including its size, style, etc.
Apart from the typeface to be used, a Font object also dictates whether the font is bold, italic, underlined, how big it is, and its kerning and horizontal scale factor.
See Also
Typeface
Member Enumeration Documentation
enum juce::Font::FontStyleFlags
A combination of these values is used by the constructor to specify the style of font to use.
Enumerator
plain
indicates a plain, non-bold, non-italic version of the font.
See Also
setStyleFlags
bold
boldens the font.
See Also
setStyleFlags
italic
finds an italic version of the font.
See Also
setStyleFlags
underlined
underlines the font.
See Also
setStyleFlags
Constructor & Destructor Documentation
juce::Font::Font (float fontHeight, int styleFlags = plain)
Creates a sans-serif font in a given size.
Parameters
fontHeight the height in pixels (can be fractional)
styleFlags the style to use - this can be a combination of the Font::bold, Font::italic and Font::underlined, or just Font::plain for the normal style.
See Also
FontStyleFlags, getDefaultSansSerifFontName
juce::Font::Font (const String & typefaceName, float fontHeight, int styleFlags)
Creates a font with a given typeface and parameters.
Parameters
typefaceName the font family of the typeface to use
fontHeight the height in pixels (can be fractional)
styleFlags the style to use - this can be a combination of the Font::bold, Font::italic and Font::underlined, or just Font::plain for the normal style.
See Also
FontStyleFlags, getDefaultSansSerifFontName
juce::Font::Font (const String & typefaceName, const String & typefaceStyle, float fontHeight)
Creates a font with a given typeface and parameters.
Parameters
typefaceName the font family of the typeface to use
typefaceStyle the font style of the typeface to use
fontHeight the height in pixels (can be fractional)
juce::Font::Font (const Font & other) noexcept
Creates a copy of another Font object.
juce::Font::Font (const Typeface::Ptr & typeface)
Creates a font for a typeface.
juce::Font::Font ()
Creates a basic sans-serif font at a default height.
You should use one of the other constructors for creating a font that you're planning on drawing with - this constructor is here to help initialise objects before changing the font's settings later.
juce::Font::Font (Font && other) noexcept
Move constructor.
juce::Font::~Font () noexcept
Destructor.
Member Function Documentation
Font& juce::Font::operator= (Font && other) noexcept
Move assignment operator.
Font& juce::Font::operator= (const Font & other) noexcept
Copies this font from another one.
bool juce::Font::operator== (const Font & other) const noexcept
bool juce::Font::operator!= (const Font & other) const noexcept
void juce::Font::setTypefaceName (const String & faceName)
Changes the font family of the typeface.
e.g. "Arial", "Courier", etc.
This may also be set to Font::getDefaultSansSerifFontName(), Font::getDefaultSerifFontName(), or Font::getDefaultMonospacedFontName(), which are not actual platform-specific font family names, but are generic font family names that are used to represent the various default fonts. If you need to know the exact typeface font family being used, you can call Font::getTypeface()->getName(), which will give you the platform-specific font family.
If a suitable font isn't found on the machine, it'll just use a default instead.
const String& juce::Font::getTypefaceName () const noexcept
Returns the font family of the typeface that this font uses.
e.g. "Arial", "Courier", etc.
This may also be set to Font::getDefaultSansSerifFontName(), Font::getDefaultSerifFontName(), or Font::getDefaultMonospacedFontName(), which are not actual platform-specific font family names, but are generic font familiy names that are used to represent the various default fonts.
If you need to know the exact typeface font family being used, you can call Font::getTypeface()->getName(), which will give you the platform-specific font family.
const String& juce::Font::getTypefaceStyle () const noexcept
Returns the font style of the typeface that this font uses.
See Also
withTypefaceStyle, getAvailableStyles()
void juce::Font::setTypefaceStyle (const String & newStyle)
Changes the font style of the typeface.
See Also
getAvailableStyles()
Font juce::Font::withTypefaceStyle (const String & newStyle) const
Returns a copy of this font with a new typeface style.
See Also
getAvailableStyles()
StringArray juce::Font::getAvailableStyles () const
Returns a list of the styles that this font can use.
static const String& juce::Font::getDefaultSansSerifFontName () static
Returns a typeface font family that represents the default sans-serif font.
This is also the typeface that will be used when a font is created without specifying any typeface details.
Note that this method just returns a generic placeholder string that means "the default sans-serif font" - it's not the actual font family of this font.
See Also
setTypefaceName, getDefaultSerifFontName, getDefaultMonospacedFontName
static const String& juce::Font::getDefaultSerifFontName () static
Returns a typeface font family that represents the default serif font.
Note that this method just returns a generic placeholder string that means "the default serif font" - it's not the actual font family of this font.
See Also
setTypefaceName, getDefaultSansSerifFontName, getDefaultMonospacedFontName
static const String& juce::Font::getDefaultMonospacedFontName () static
Returns a typeface font family that represents the default monospaced font.
Note that this method just returns a generic placeholder string that means "the default monospaced font" - it's not the actual font family of this font.
See Also
setTypefaceName, getDefaultSansSerifFontName, getDefaultSerifFontName
static const String& juce::Font::getDefaultStyle () static
Returns a font style name that represents the default style.
Note that this method just returns a generic placeholder string that means "the default font style" - it's not the actual name of the font style of any particular font.
See Also
setTypefaceStyle
static Typeface::Ptr juce::Font::getDefaultTypefaceForFont (const Font & font) static
Returns the default system typeface for the given font.
Font juce::Font::withHeight (float height) const
Returns a copy of this font with a new height.
Font juce::Font::withPointHeight (float heightInPoints) const
Returns a copy of this font with a new height, specified in points.
void juce::Font::setHeight (float newHeight)
Changes the font's height.
See Also
getHeight, withHeight, setHeightWithoutChangingWidth
void juce::Font::setHeightWithoutChangingWidth (float newHeight)
Changes the font's height without changing its width.
This alters the horizontal scale to compensate for the change in height.
float juce::Font::getHeight () const noexcept
Returns the total height of this font, in pixels.
This is the maximum height, from the top of the ascent to the bottom of the descenders.
See Also
withHeight, setHeightWithoutChangingWidth, getAscent
Referenced by juce::PositionedGlyph::getBounds().
float juce::Font::getHeightInPoints () const
Returns the total height of this font, in points.
This is the maximum height, from the top of the ascent to the bottom of the descenders.
See Also
withPointHeight, getHeight
float juce::Font::getAscent () const
Returns the height of the font above its baseline, in pixels.
This is the maximum height from the baseline to the top.
See Also
getHeight, getDescent
Referenced by juce::PositionedGlyph::getTop().
float juce::Font::getAscentInPoints () const
Returns the height of the font above its baseline, in points.
This is the maximum height from the baseline to the top.
See Also
getHeight, getDescent
float juce::Font::getDescent () const
Returns the amount that the font descends below its baseline, in pixels.
This is calculated as (getHeight() - getAscent()).
See Also
getAscent, getHeight
Referenced by juce::PositionedGlyph::getBottom().
float juce::Font::getDescentInPoints () const
Returns the amount that the font descends below its baseline, in points.
This is calculated as (getHeight() - getAscent()).
See Also
getAscent, getHeight
int juce::Font::getStyleFlags () const noexcept
Returns the font's style flags.
This will return a bitwise-or'ed combination of values from the FontStyleFlags enum, to describe whether the font is bold, italic, etc.
See Also
FontStyleFlags, withStyle
Font juce::Font::withStyle (int styleFlags) const
Returns a copy of this font with the given set of style flags.
Parameters
styleFlags a bitwise-or'ed combination of values from the FontStyleFlags enum.
See Also
FontStyleFlags, getStyleFlags
void juce::Font::setStyleFlags (int newFlags)
Changes the font's style.
Parameters
newFlags a bitwise-or'ed combination of values from the FontStyleFlags enum.
See Also
FontStyleFlags, withStyle
void juce::Font::setBold (bool shouldBeBold)
Makes the font bold or non-bold.
Font juce::Font::boldened () const
Returns a copy of this font with the bold attribute set.
If the font does not have a bold version, this will return the default font.
bool juce::Font::isBold () const noexcept
Returns true if the font is bold.
void juce::Font::setItalic (bool shouldBeItalic)
Makes the font italic or non-italic.
Font juce::Font::italicised () const
Returns a copy of this font with the italic attribute set.
bool juce::Font::isItalic () const noexcept
Returns true if the font is italic.
void juce::Font::setUnderline (bool shouldBeUnderlined)
Makes the font underlined or non-underlined.
bool juce::Font::isUnderlined () const noexcept
Returns true if the font is underlined.
float juce::Font::getHorizontalScale () const noexcept
Returns the font's horizontal scale.
A value of 1.0 is the normal scale, less than this will be narrower, greater than 1.0 will be stretched out.
See Also
withHorizontalScale
Font juce::Font::withHorizontalScale (float scaleFactor) const
Returns a copy of this font with a new horizontal scale.
Parameters
scaleFactor a value of 1.0 is the normal scale, less than this will be narrower, greater than 1.0 will be stretched out.
See Also
getHorizontalScale
void juce::Font::setHorizontalScale (float scaleFactor)
Changes the font's horizontal scale factor.
Parameters
scaleFactor a value of 1.0 is the normal scale, less than this will be narrower, greater than 1.0 will be stretched out.
static float juce::Font::getDefaultMinimumHorizontalScaleFactor () static noexcept
Returns the minimum horizontal scale to which fonts may be squashed when trying to create a layout.
See Also
setDefaultMinimumHorizontalScaleFactor
static void juce::Font::setDefaultMinimumHorizontalScaleFactor (float newMinimumScaleFactor) static noexcept
Sets the minimum horizontal scale to which fonts may be squashed when trying to create a text layout.
See Also
getDefaultMinimumHorizontalScaleFactor
float juce::Font::getExtraKerningFactor () const noexcept
Returns the font's kerning.
This is the extra space added between adjacent characters, as a proportion of the font's height.
A value of zero is normal spacing, positive values will spread the letters out more, and negative values make them closer together.
Font juce::Font::withExtraKerningFactor (float extraKerning) const
Returns a copy of this font with a new kerning factor.
Parameters
extraKerning a multiple of the font's height that will be added to space between the characters. So a value of zero is normal spacing, positive values spread the letters out, negative values make them closer together.
void juce::Font::setExtraKerningFactor (float extraKerning)
Changes the font's kerning.
Parameters
extraKerning a multiple of the font's height that will be added to space between the characters. So a value of zero is normal spacing, positive values spread the letters out, negative values make them closer together.
void juce::Font::setSizeAndStyle (float newHeight, int newStyleFlags, float newHorizontalScale, float newKerningAmount)
Changes all the font's characteristics with one call.
void juce::Font::setSizeAndStyle (float newHeight, const String & newStyle, float newHorizontalScale, float newKerningAmount)
Changes all the font's characteristics with one call.
int juce::Font::getStringWidth (const String & text) const
Returns the total width of a string as it would be drawn using this font.
For a more accurate floating-point result, use getStringWidthFloat().
float juce::Font::getStringWidthFloat (const String & text) const
Returns the total width of a string as it would be drawn using this font.
See Also
getStringWidth
void juce::Font::getGlyphPositions (const String & text, Array< int > & glyphs, Array< float > & xOffsets) const
Returns the series of glyph numbers and their x offsets needed to represent a string.
An extra x offset is added at the end of the run, to indicate where the right hand edge of the last character is.
Typeface* juce::Font::getTypeface () const
Returns the typeface used by this font.
Note that the object returned may go out of scope if this font is deleted or has its style changed.
static void juce::Font::findFonts (Array< Font > & results) static
Creates an array of Font objects to represent all the fonts on the system.
If you just need the font family names of the typefaces, you can also use findAllTypefaceNames() instead.
Parameters
results the array to which new Font objects will be added.
static StringArray juce::Font::findAllTypefaceNames () static
Returns a list of all the available typeface font families.
The names returned can be passed into setTypefaceName().
You can use this instead of findFonts() if you only need their font family names, and not font objects.
static StringArray juce::Font::findAllTypefaceStyles (const String & family) static
Returns a list of all the available typeface font styles.
The names returned can be passed into setTypefaceStyle().
You can use this instead of findFonts() if you only need their styles, and not font objects.
static const String& juce::Font::getFallbackFontName () static
Returns the font family of the typeface to be used for rendering glyphs that aren't found in the requested typeface.
static void juce::Font::setFallbackFontName (const String & name) static
Sets the (platform-specific) font family of the typeface to use to find glyphs that aren't available in whatever font you're trying to use.
static const String& juce::Font::getFallbackFontStyle () static
Returns the font style of the typeface to be used for rendering glyphs that aren't found in the requested typeface.
static void juce::Font::setFallbackFontStyle (const String & style) static
Sets the (platform-specific) font style of the typeface to use to find glyphs that aren't available in whatever font you're trying to use.
String juce::Font::toString () const
Creates a string to describe this font.
The string will contain information to describe the font's typeface, size, and style. To recreate the font from this string, use fromString().
static Font juce::Font::fromString (const String & fontDescription) static
Recreates a font from its stringified encoding.
This method takes a string that was created by toString(), and recreates the original font.
The documentation for this class was generated from the following file:
juce_Font.h