JUCE: juce::Rectangle< ValueType > Class Template Reference
juce::Rectangle< ValueType > Class Template Reference
geometry
Manages a rectangle and allows geometric operations to be performed on it.
Public Member Functions
Rectangle () noexcept
Creates a rectangle of zero size.
Rectangle (const Rectangle &other) noexcept
Creates a copy of another rectangle.
Rectangle (ValueType initialX, ValueType initialY, ValueType width, ValueType height) noexcept
Creates a rectangle with a given position and size.
Rectangle (ValueType width, ValueType height) noexcept
Creates a rectangle with a given size, and a position of (0, 0).
Rectangle (Point< ValueType > corner1, Point< ValueType > corner2) noexcept
Creates a Rectangle from the positions of two opposite corners.
Rectangle & operator= (const Rectangle &other) noexcept
~Rectangle () noexcept
Destructor.
bool isEmpty () const noexcept
Returns true if the rectangle's width or height are zero or less.
bool isFinite () const noexcept
Returns true if the rectangle's values are all finite numbers, i.e.
ValueType getX () const noexcept
Returns the x coordinate of the rectangle's left-hand-side.
ValueType getY () const noexcept
Returns the y coordinate of the rectangle's top edge.
ValueType getWidth () const noexcept
Returns the width of the rectangle.
ValueType getHeight () const noexcept
Returns the height of the rectangle.
ValueType getRight () const noexcept
Returns the x coordinate of the rectangle's right-hand-side.
ValueType getBottom () const noexcept
Returns the y coordinate of the rectangle's bottom edge.
ValueType getCentreX () const noexcept
Returns the x coordinate of the rectangle's centre.
ValueType getCentreY () const noexcept
Returns the y coordinate of the rectangle's centre.
Point< ValueType > getCentre () const noexcept
Returns the centre point of the rectangle.
ValueType getAspectRatio (bool widthOverHeight=true) const noexcept
Returns the aspect ratio of the rectangle's width / height.
Point< ValueType > getPosition () const noexcept
Returns the rectangle's top-left position as a Point.
void setPosition (Point< ValueType > newPos) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
void setPosition (ValueType newX, ValueType newY) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
Point< ValueType > getTopLeft () const noexcept
Returns the rectangle's top-left position as a Point.
Point< ValueType > getTopRight () const noexcept
Returns the rectangle's top-right position as a Point.
Point< ValueType > getBottomLeft () const noexcept
Returns the rectangle's bottom-left position as a Point.
Point< ValueType > getBottomRight () const noexcept
Returns the rectangle's bottom-right position as a Point.
Range< ValueType > getHorizontalRange () const noexcept
Returns the rectangle's left and right positions as a Range.
Range< ValueType > getVerticalRange () const noexcept
Returns the rectangle's top and bottom positions as a Range.
void setSize (ValueType newWidth, ValueType newHeight) noexcept
Changes the rectangle's size, leaving the position of its top-left corner unchanged.
void setBounds (ValueType newX, ValueType newY, ValueType newWidth, ValueType newHeight) noexcept
Changes all the rectangle's coordinates.
void setX (ValueType newX) noexcept
Changes the rectangle's X coordinate.
void setY (ValueType newY) noexcept
Changes the rectangle's Y coordinate.
void setWidth (ValueType newWidth) noexcept
Changes the rectangle's width.
void setHeight (ValueType newHeight) noexcept
Changes the rectangle's height.
void setCentre (ValueType newCentreX, ValueType newCentreY) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
void setCentre (Point< ValueType > newCentre) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
void setHorizontalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's left and right edges.
void setVerticalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's top and bottom edges.
Rectangle withX (ValueType newX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but with a different x-position.
Rectangle withY (ValueType newY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but with a different y-position.
Rectangle withRightX (ValueType newRightX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but whose right-hand edge has the given position.
Rectangle withBottomY (ValueType newBottomY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but whose bottom edge has the given position.
Rectangle withPosition (ValueType newX, ValueType newY) const noexcept
Returns a rectangle with the same size as this one, but a new position.
Rectangle withPosition (Point< ValueType > newPos) const noexcept
Returns a rectangle with the same size as this one, but a new position.
Rectangle withZeroOrigin () const noexcept
Returns a rectangle whose size is the same as this one, but whose top-left position is (0, 0).
Rectangle withCentre (Point< ValueType > newCentre) const noexcept
Returns a rectangle with the same size as this one, but a new centre position.
Rectangle withWidth (ValueType newWidth) const noexcept
Returns a rectangle which has the same position and height as this one, but with a different width.
Rectangle withHeight (ValueType newHeight) const noexcept
Returns a rectangle which has the same position and width as this one, but with a different height.
Rectangle withSize (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same top-left position as this one, but a new size.
Rectangle withSizeKeepingCentre (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same centre position as this one, but a new size.
void setLeft (ValueType newLeft) noexcept
Moves the x position, adjusting the width so that the right-hand edge remains in the same place.
Rectangle withLeft (ValueType newLeft) const noexcept
Returns a new rectangle with a different x position, but the same right-hand edge as this one.
void setTop (ValueType newTop) noexcept
Moves the y position, adjusting the height so that the bottom edge remains in the same place.
Rectangle withTop (ValueType newTop) const noexcept
Returns a new rectangle with a different y position, but the same bottom edge as this one.
void setRight (ValueType newRight) noexcept
Adjusts the width so that the right-hand edge of the rectangle has this new value.
Rectangle withRight (ValueType newRight) const noexcept
Returns a new rectangle with a different right-hand edge position, but the same left-hand edge as this one.
void setBottom (ValueType newBottom) noexcept
Adjusts the height so that the bottom edge of the rectangle has this new value.
Rectangle withBottom (ValueType newBottom) const noexcept
Returns a new rectangle with a different bottom edge position, but the same top edge as this one.
Rectangle withTrimmedLeft (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its left-hand edge.
Rectangle withTrimmedRight (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its right-hand edge.
Rectangle withTrimmedTop (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its top edge.
Rectangle withTrimmedBottom (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its bottom edge.
void translate (ValueType deltaX, ValueType deltaY) noexcept
Moves the rectangle's position by adding amount to its x and y coordinates.
Rectangle translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
Rectangle operator+ (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
Rectangle & operator+= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
Rectangle operator- (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
Rectangle & operator-= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
template<typename FloatType >
Rectangle operator* (FloatType scaleFactor) const noexcept
Returns a rectangle that has been scaled by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator*= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator*= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
template<typename FloatType >
Rectangle operator/ (FloatType scaleFactor) const noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator/= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator/= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
void expand (ValueType deltaX, ValueType deltaY) noexcept
Expands the rectangle by a given amount.
Rectangle expanded (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is larger than this one by a given amount.
Rectangle expanded (ValueType delta) const noexcept
Returns a rectangle that is larger than this one by a given amount.
void reduce (ValueType deltaX, ValueType deltaY) noexcept
Shrinks the rectangle by a given amount.
Rectangle reduced (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Rectangle reduced (ValueType delta) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Rectangle removeFromTop (ValueType amountToRemove) noexcept
Removes a strip from the top of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Rectangle removeFromLeft (ValueType amountToRemove) noexcept
Removes a strip from the left-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Rectangle removeFromRight (ValueType amountToRemove) noexcept
Removes a strip from the right-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Rectangle removeFromBottom (ValueType amountToRemove) noexcept
Removes a strip from the bottom of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Point< ValueType > getConstrainedPoint (Point< ValueType > point) const noexcept
Returns the nearest point to the specified point that lies within this rectangle.
template<typename FloatType >
Point< ValueType > getRelativePoint (FloatType relativeX, FloatType relativeY) const noexcept
Returns a point within this rectangle, specified as proportional coordinates.
template<typename FloatType >
ValueType proportionOfWidth (FloatType proportion) const noexcept
Returns a proportion of the width of this rectangle.
template<typename FloatType >
ValueType proportionOfHeight (FloatType proportion) const noexcept
Returns a proportion of the height of this rectangle.
template<typename FloatType >
Rectangle getProportion (Rectangle< FloatType > proportionalRect) const noexcept
Returns a rectangle based on some proportional coordinates relative to this one.
bool operator== (const Rectangle &other) const noexcept
Returns true if the two rectangles are identical.
bool operator!= (const Rectangle &other) const noexcept
Returns true if the two rectangles are not identical.
bool contains (ValueType xCoord, ValueType yCoord) const noexcept
Returns true if this coordinate is inside the rectangle.
bool contains (Point< ValueType > point) const noexcept
Returns true if this coordinate is inside the rectangle.
bool contains (Rectangle other) const noexcept
Returns true if this other rectangle is completely inside this one.
bool intersects (Rectangle other) const noexcept
Returns true if any part of another rectangle overlaps this one.
bool intersects (const Line< ValueType > &line) const noexcept
Returns true if any part of the given line lies inside this rectangle.
Rectangle getIntersection (Rectangle other) const noexcept
Returns the region that is the overlap between this and another rectangle.
bool intersectRectangle (ValueType &otherX, ValueType &otherY, ValueType &otherW, ValueType &otherH) const noexcept
Clips a set of rectangle coordinates so that they lie only within this one.
bool intersectRectangle (Rectangle< ValueType > &rectangleToClip) const noexcept
Clips a rectangle so that it lies only within this one.
Rectangle getUnion (Rectangle other) const noexcept
Returns the smallest rectangle that contains both this one and the one passed-in.
bool enlargeIfAdjacent (Rectangle other) noexcept
If this rectangle merged with another one results in a simple rectangle, this will set this rectangle to the result, and return true.
bool reduceIfPartlyContainedIn (Rectangle other) noexcept
If after removing another rectangle from this one the result is a simple rectangle, this will set this object's bounds to be the result, and return true.
Rectangle constrainedWithin (Rectangle areaToFitWithin) const noexcept
Tries to fit this rectangle within a target area, returning the result.
Rectangle transformedBy (const AffineTransform &transform) const noexcept
Returns the smallest rectangle that can contain the shape created by applying a transform to this rectangle.
Rectangle< int > getSmallestIntegerContainer () const noexcept
Returns the smallest integer-aligned rectangle that completely contains this one.
Rectangle< int > toNearestInt () const noexcept
Casts this rectangle to a Rectangle<int>.
Rectangle< float > toFloat () const noexcept
Casts this rectangle to a Rectangle<float>.
Rectangle< double > toDouble () const noexcept
Casts this rectangle to a Rectangle<double>.
template<typename TargetType >
Rectangle< TargetType > toType () const noexcept
Casts this rectangle to a Rectangle with the given type.
String toString () const
Creates a string describing this rectangle.
Static Public Member Functions
static Rectangle leftTopRightBottom (ValueType left, ValueType top, ValueType right, ValueType bottom) noexcept
Creates a Rectangle from a set of left, right, top, bottom coordinates.
static Rectangle findAreaContainingPoints (const Point< ValueType > *points, int numPoints) noexcept
Returns the smallest Rectangle that can contain a set of points.
static bool intersectRectangles (ValueType &x1, ValueType &y1, ValueType &w1, ValueType &h1, ValueType x2, ValueType y2, ValueType w2, ValueType h2) noexcept
Static utility to intersect two sets of rectangular coordinates.
static Rectangle fromString (StringRef stringVersion)
Parses a string containing a rectangle's details.
Detailed Description
template<typename ValueType>
class juce::Rectangle< ValueType >
Manages a rectangle and allows geometric operations to be performed on it.
See Also
RectangleList, Path, Line, Point
Constructor & Destructor Documentation
template<typename ValueType> juce::Rectangle< ValueType >::Rectangle () noexcept
Creates a rectangle of zero size.
The default coordinates will be (0, 0, 0, 0).
template<typename ValueType> juce::Rectangle< ValueType >::Rectangle (const Rectangle< ValueType > & other) noexcept
Creates a copy of another rectangle.
template<typename ValueType> juce::Rectangle< ValueType >::Rectangle (ValueType initialX, ValueType initialY, ValueType width, ValueType height) noexcept
Creates a rectangle with a given position and size.
template<typename ValueType> juce::Rectangle< ValueType >::Rectangle (ValueType width, ValueType height) noexcept
Creates a rectangle with a given size, and a position of (0, 0).
template<typename ValueType> juce::Rectangle< ValueType >::Rectangle (Point< ValueType > corner1, Point< ValueType > corner2) noexcept
Creates a Rectangle from the positions of two opposite corners.
template<typename ValueType> juce::Rectangle< ValueType >::~Rectangle () noexcept
Destructor.
Member Function Documentation
template<typename ValueType> static Rectangle juce::Rectangle< ValueType >::leftTopRightBottom (ValueType left, ValueType top, ValueType right, ValueType bottom) static noexcept
Creates a Rectangle from a set of left, right, top, bottom coordinates.
The right and bottom values must be larger than the left and top ones, or the resulting rectangle will have a negative size.
Referenced by juce::Rectangle< int >::getSmallestIntegerContainer().
template<typename ValueType> Rectangle& juce::Rectangle< ValueType >::operator= (const Rectangle< ValueType > & other) noexcept
template<typename ValueType> bool juce::Rectangle< ValueType >::isEmpty () const noexcept
Returns true if the rectangle's width or height are zero or less.
Referenced by juce::RectangleList< int >::add(), juce::RectangleList< int >::addWithoutMerging(), juce::RectangleList< int >::clipTo(), juce::RectangleList< int >::getIntersectionWith(), and juce::Rectangle< int >::getUnion().
template<typename ValueType> bool juce::Rectangle< ValueType >::isFinite () const noexcept
Returns true if the rectangle's values are all finite numbers, i.e.
not NaN or infinity.
Referenced by juce::RectangleList< int >::add(), juce::RectangleList< int >::addWithoutMerging(), juce::RectangleList< int >::clipTo(), and juce::RectangleList< int >::getIntersectionWith().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getX () const noexcept
Returns the x coordinate of the rectangle's left-hand-side.
Referenced by juce::Path::addRoundedRectangle(), and juce::RectangleList< int >::subtract().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getY () const noexcept
Returns the y coordinate of the rectangle's top edge.
Referenced by juce::Path::addRoundedRectangle(), and juce::RectangleList< int >::subtract().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getWidth () const noexcept
Returns the width of the rectangle.
Referenced by juce::Path::addRoundedRectangle(), and juce::RectangleList< int >::subtract().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getHeight () const noexcept
Returns the height of the rectangle.
Referenced by juce::Path::addRoundedRectangle(), and juce::RectangleList< int >::subtract().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getRight () const noexcept
Returns the x coordinate of the rectangle's right-hand-side.
Referenced by juce::Rectangle< int >::enlargeIfAdjacent().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getBottom () const noexcept
Returns the y coordinate of the rectangle's bottom edge.
Referenced by juce::Rectangle< int >::enlargeIfAdjacent().
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getCentreX () const noexcept
Returns the x coordinate of the rectangle's centre.
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getCentreY () const noexcept
Returns the y coordinate of the rectangle's centre.
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getCentre () const noexcept
Returns the centre point of the rectangle.
template<typename ValueType> ValueType juce::Rectangle< ValueType >::getAspectRatio (bool widthOverHeight = true) const noexcept
Returns the aspect ratio of the rectangle's width / height.
If widthOverHeight is true, it returns width / height; if widthOverHeight is false, it returns height / width.
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getPosition () const noexcept
Returns the rectangle's top-left position as a Point.
template<typename ValueType> void juce::Rectangle< ValueType >::setPosition (Point< ValueType > newPos) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
template<typename ValueType> void juce::Rectangle< ValueType >::setPosition (ValueType newX, ValueType newY) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getTopLeft () const noexcept
Returns the rectangle's top-left position as a Point.
Referenced by juce::Rectangle< int >::intersects().
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getTopRight () const noexcept
Returns the rectangle's top-right position as a Point.
Referenced by juce::Rectangle< int >::intersects().
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getBottomLeft () const noexcept
Returns the rectangle's bottom-left position as a Point.
Referenced by juce::Rectangle< int >::intersects().
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getBottomRight () const noexcept
Returns the rectangle's bottom-right position as a Point.
Referenced by juce::Rectangle< int >::intersects().
template<typename ValueType> Range<ValueType> juce::Rectangle< ValueType >::getHorizontalRange () const noexcept
Returns the rectangle's left and right positions as a Range.
template<typename ValueType> Range<ValueType> juce::Rectangle< ValueType >::getVerticalRange () const noexcept
Returns the rectangle's top and bottom positions as a Range.
template<typename ValueType> void juce::Rectangle< ValueType >::setSize (ValueType newWidth, ValueType newHeight) noexcept
Changes the rectangle's size, leaving the position of its top-left corner unchanged.
template<typename ValueType> void juce::Rectangle< ValueType >::setBounds (ValueType newX, ValueType newY, ValueType newWidth, ValueType newHeight) noexcept
Changes all the rectangle's coordinates.
Referenced by juce::Rectangle< int >::expand().
template<typename ValueType> void juce::Rectangle< ValueType >::setX (ValueType newX) noexcept
Changes the rectangle's X coordinate.
template<typename ValueType> void juce::Rectangle< ValueType >::setY (ValueType newY) noexcept
Changes the rectangle's Y coordinate.
template<typename ValueType> void juce::Rectangle< ValueType >::setWidth (ValueType newWidth) noexcept
Changes the rectangle's width.
template<typename ValueType> void juce::Rectangle< ValueType >::setHeight (ValueType newHeight) noexcept
Changes the rectangle's height.
template<typename ValueType> void juce::Rectangle< ValueType >::setCentre (ValueType newCentreX, ValueType newCentreY) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
template<typename ValueType> void juce::Rectangle< ValueType >::setCentre (Point< ValueType > newCentre) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
Referenced by juce::Rectangle< int >::setCentre().
template<typename ValueType> void juce::Rectangle< ValueType >::setHorizontalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's left and right edges.
template<typename ValueType> void juce::Rectangle< ValueType >::setVerticalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's top and bottom edges.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withX (ValueType newX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but with a different x-position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withY (ValueType newY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but with a different y-position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withRightX (ValueType newRightX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but whose right-hand edge has the given position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withBottomY (ValueType newBottomY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but whose bottom edge has the given position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withPosition (ValueType newX, ValueType newY) const noexcept
Returns a rectangle with the same size as this one, but a new position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withPosition (Point< ValueType > newPos) const noexcept
Returns a rectangle with the same size as this one, but a new position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withZeroOrigin () const noexcept
Returns a rectangle whose size is the same as this one, but whose top-left position is (0, 0).
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withCentre (Point< ValueType > newCentre) const noexcept
Returns a rectangle with the same size as this one, but a new centre position.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withWidth (ValueType newWidth) const noexcept
Returns a rectangle which has the same position and height as this one, but with a different width.
Referenced by juce::Rectangle< int >::withTrimmedRight().
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withHeight (ValueType newHeight) const noexcept
Returns a rectangle which has the same position and width as this one, but with a different height.
Referenced by juce::Rectangle< int >::withTrimmedBottom().
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withSize (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same top-left position as this one, but a new size.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withSizeKeepingCentre (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same centre position as this one, but a new size.
template<typename ValueType> void juce::Rectangle< ValueType >::setLeft (ValueType newLeft) noexcept
Moves the x position, adjusting the width so that the right-hand edge remains in the same place.
If the x is moved to be on the right of the current right-hand edge, the width will be set to zero.
See Also
withLeft
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withLeft (ValueType newLeft) const noexcept
Returns a new rectangle with a different x position, but the same right-hand edge as this one.
If the new x is beyond the right of the current right-hand edge, the width will be set to zero.
See Also
setLeft
Referenced by juce::Rectangle< int >::withTrimmedLeft().
template<typename ValueType> void juce::Rectangle< ValueType >::setTop (ValueType newTop) noexcept
Moves the y position, adjusting the height so that the bottom edge remains in the same place.
If the y is moved to be below the current bottom edge, the height will be set to zero.
See Also
withTop
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withTop (ValueType newTop) const noexcept
Returns a new rectangle with a different y position, but the same bottom edge as this one.
If the new y is beyond the bottom of the current rectangle, the height will be set to zero.
See Also
setTop
Referenced by juce::Rectangle< int >::withTrimmedTop().
template<typename ValueType> void juce::Rectangle< ValueType >::setRight (ValueType newRight) noexcept
Adjusts the width so that the right-hand edge of the rectangle has this new value.
If the new right is below the current X value, the X will be pushed down to match it.
See Also
getRight, withRight
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withRight (ValueType newRight) const noexcept
Returns a new rectangle with a different right-hand edge position, but the same left-hand edge as this one.
If the new right edge is below the current left-hand edge, the width will be set to zero.
See Also
setRight
template<typename ValueType> void juce::Rectangle< ValueType >::setBottom (ValueType newBottom) noexcept
Adjusts the height so that the bottom edge of the rectangle has this new value.
If the new bottom is lower than the current Y value, the Y will be pushed down to match it.
See Also
getBottom, withBottom
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withBottom (ValueType newBottom) const noexcept
Returns a new rectangle with a different bottom edge position, but the same top edge as this one.
If the new y is beyond the bottom of the current rectangle, the height will be set to zero.
See Also
setBottom
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withTrimmedLeft (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its left-hand edge.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withTrimmedRight (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its right-hand edge.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withTrimmedTop (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its top edge.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::withTrimmedBottom (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its bottom edge.
template<typename ValueType> void juce::Rectangle< ValueType >::translate (ValueType deltaX, ValueType deltaY) noexcept
Moves the rectangle's position by adding amount to its x and y coordinates.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::operator+ (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
template<typename ValueType> Rectangle& juce::Rectangle< ValueType >::operator+= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::operator- (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
template<typename ValueType> Rectangle& juce::Rectangle< ValueType >::operator-= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::operator* (FloatType scaleFactor) const noexcept
Returns a rectangle that has been scaled by the given amount, centred around the origin.
Note that if the rectangle has int coordinates and it's scaled by a floating-point amount, then the result will be converted back to integer coordinates using getSmallestIntegerContainer().
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::operator*= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
Note that if the rectangle has int coordinates and it's scaled by a floating-point amount, then the result will be converted back to integer coordinates using getSmallestIntegerContainer().
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::operator*= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
Note that if the rectangle has int coordinates and it's scaled by a floating-point amount, then the result will be converted back to integer coordinates using getSmallestIntegerContainer().
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::operator/ (FloatType scaleFactor) const noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::operator/= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::operator/= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
template<typename ValueType> void juce::Rectangle< ValueType >::expand (ValueType deltaX, ValueType deltaY) noexcept
Expands the rectangle by a given amount.
Effectively, its new size is (x - deltaX, y - deltaY, w + deltaX * 2, h + deltaY * 2).
See Also
expanded, reduce, reduced
Referenced by juce::Rectangle< int >::reduce().
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::expanded (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is larger than this one by a given amount.
Effectively, the rectangle returned is (x - deltaX, y - deltaY, w + deltaX * 2, h + deltaY * 2).
See Also
expand, reduce, reduced
Referenced by juce::Rectangle< int >::expanded(), and juce::Rectangle< int >::reduced().
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::expanded (ValueType delta) const noexcept
Returns a rectangle that is larger than this one by a given amount.
Effectively, the rectangle returned is (x - delta, y - delta, w + delta * 2, h + delta * 2).
See Also
expand, reduce, reduced
template<typename ValueType> void juce::Rectangle< ValueType >::reduce (ValueType deltaX, ValueType deltaY) noexcept
Shrinks the rectangle by a given amount.
Effectively, its new size is (x + deltaX, y + deltaY, w - deltaX * 2, h - deltaY * 2).
See Also
reduced, expand, expanded
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::reduced (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Effectively, the rectangle returned is (x + deltaX, y + deltaY, w - deltaX * 2, h - deltaY * 2).
See Also
reduce, expand, expanded
Referenced by juce::Rectangle< int >::reduced().
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::reduced (ValueType delta) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Effectively, the rectangle returned is (x + delta, y + delta, w - delta * 2, h - delta * 2).
See Also
reduce, expand, expanded
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::removeFromTop (ValueType amountToRemove) noexcept
Removes a strip from the top of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (100, 100, 300, 50) and leave this rectangle as (100, 150, 300, 250).
If amountToRemove is greater than the height of this rectangle, it'll be clipped to that value.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::removeFromLeft (ValueType amountToRemove) noexcept
Removes a strip from the left-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (100, 100, 50, 300) and leave this rectangle as (150, 100, 250, 300).
If amountToRemove is greater than the width of this rectangle, it'll be clipped to that value.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::removeFromRight (ValueType amountToRemove) noexcept
Removes a strip from the right-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (250, 100, 50, 300) and leave this rectangle as (100, 100, 250, 300).
If amountToRemove is greater than the width of this rectangle, it'll be clipped to that value.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::removeFromBottom (ValueType amountToRemove) noexcept
Removes a strip from the bottom of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (100, 250, 300, 50) and leave this rectangle as (100, 100, 300, 250).
If amountToRemove is greater than the height of this rectangle, it'll be clipped to that value.
template<typename ValueType> Point<ValueType> juce::Rectangle< ValueType >::getConstrainedPoint (Point< ValueType > point) const noexcept
Returns the nearest point to the specified point that lies within this rectangle.
template<typename ValueType> template<typename FloatType > Point<ValueType> juce::Rectangle< ValueType >::getRelativePoint (FloatType relativeX, FloatType relativeY) const noexcept
Returns a point within this rectangle, specified as proportional coordinates.
The relative X and Y values should be between 0 and 1, where 0 is the left or top of this rectangle, and 1 is the right or bottom. (Out-of-bounds values will return a point outside the rectangle).
template<typename ValueType> template<typename FloatType > ValueType juce::Rectangle< ValueType >::proportionOfWidth (FloatType proportion) const noexcept
Returns a proportion of the width of this rectangle.
Referenced by juce::Rectangle< int >::getProportion().
template<typename ValueType> template<typename FloatType > ValueType juce::Rectangle< ValueType >::proportionOfHeight (FloatType proportion) const noexcept
Returns a proportion of the height of this rectangle.
Referenced by juce::Rectangle< int >::getProportion().
template<typename ValueType> template<typename FloatType > Rectangle juce::Rectangle< ValueType >::getProportion (Rectangle< FloatType > proportionalRect) const noexcept
Returns a rectangle based on some proportional coordinates relative to this one.
So for example getProportion ({ 0.25f, 0.25f, 0.5f, 0.5f }) would return a rectangle of half the original size, with the same centre.
template<typename ValueType> bool juce::Rectangle< ValueType >::operator== (const Rectangle< ValueType > & other) const noexcept
Returns true if the two rectangles are identical.
template<typename ValueType> bool juce::Rectangle< ValueType >::operator!= (const Rectangle< ValueType > & other) const noexcept
Returns true if the two rectangles are not identical.
template<typename ValueType> bool juce::Rectangle< ValueType >::contains (ValueType xCoord, ValueType yCoord) const noexcept
Returns true if this coordinate is inside the rectangle.
Referenced by juce::RectangleList< int >::add(), and juce::Rectangle< int >::intersects().
template<typename ValueType> bool juce::Rectangle< ValueType >::contains (Point< ValueType > point) const noexcept
Returns true if this coordinate is inside the rectangle.
template<typename ValueType> bool juce::Rectangle< ValueType >::contains (Rectangle< ValueType > other) const noexcept
Returns true if this other rectangle is completely inside this one.
template<typename ValueType> bool juce::Rectangle< ValueType >::intersects (Rectangle< ValueType > other) const noexcept
Returns true if any part of another rectangle overlaps this one.
Referenced by juce::RectangleList< int >::add().
template<typename ValueType> bool juce::Rectangle< ValueType >::intersects (const Line< ValueType > & line) const noexcept
Returns true if any part of the given line lies inside this rectangle.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::getIntersection (Rectangle< ValueType > other) const noexcept
Returns the region that is the overlap between this and another rectangle.
If the two rectangles don't overlap, the rectangle returned will be empty.
template<typename ValueType> bool juce::Rectangle< ValueType >::intersectRectangle (ValueType & otherX, ValueType & otherY, ValueType & otherW, ValueType & otherH) const noexcept
Clips a set of rectangle coordinates so that they lie only within this one.
This is a non-static version of intersectRectangles(). Returns false if the two rectangles didn't overlap.
Referenced by juce::RectangleList< int >::clipTo(), juce::RectangleList< int >::getIntersectionWith(), and juce::Rectangle< int >::intersectRectangle().
template<typename ValueType> bool juce::Rectangle< ValueType >::intersectRectangle (Rectangle< ValueType > & rectangleToClip) const noexcept
Clips a rectangle so that it lies only within this one.
Returns false if the two rectangles didn't overlap.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::getUnion (Rectangle< ValueType > other) const noexcept
Returns the smallest rectangle that contains both this one and the one passed-in.
If either this or the other rectangle are empty, they will not be counted as part of the resulting region.
template<typename ValueType> bool juce::Rectangle< ValueType >::enlargeIfAdjacent (Rectangle< ValueType > other) noexcept
If this rectangle merged with another one results in a simple rectangle, this will set this rectangle to the result, and return true.
Returns false and does nothing to this rectangle if the two rectangles don't overlap, or if they form a complex region.
template<typename ValueType> bool juce::Rectangle< ValueType >::reduceIfPartlyContainedIn (Rectangle< ValueType > other) noexcept
If after removing another rectangle from this one the result is a simple rectangle, this will set this object's bounds to be the result, and return true.
Returns false and does nothing to this rectangle if the two rectangles don't overlap, or if removing the other one would form a complex region.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::constrainedWithin (Rectangle< ValueType > areaToFitWithin) const noexcept
Tries to fit this rectangle within a target area, returning the result.
If this rectangle is not completely inside the target area, then it'll be shifted (without changing its size) so that it lies within the target. If it is larger than the target rectangle in either dimension, then that dimension will be reduced to fit within the target.
template<typename ValueType> Rectangle juce::Rectangle< ValueType >::transformedBy (const AffineTransform & transform) const noexcept
Returns the smallest rectangle that can contain the shape created by applying a transform to this rectangle.
This should only be used on floating point rectangles.
template<typename ValueType> Rectangle<int> juce::Rectangle< ValueType >::getSmallestIntegerContainer () const noexcept
Returns the smallest integer-aligned rectangle that completely contains this one.
This is only relevant for floating-point rectangles, of course.
See Also
toFloat(), toNearestInt()
template<typename ValueType> Rectangle<int> juce::Rectangle< ValueType >::toNearestInt () const noexcept
Casts this rectangle to a Rectangle<int>.
This uses roundToInt to snap x, y, width and height to the nearest integer (losing precision). If the rectangle already uses integers, this will simply return a copy.
See Also
getSmallestIntegerContainer()
template<typename ValueType> Rectangle<float> juce::Rectangle< ValueType >::toFloat () const noexcept
Casts this rectangle to a Rectangle<float>.
See Also
getSmallestIntegerContainer
template<typename ValueType> Rectangle<double> juce::Rectangle< ValueType >::toDouble () const noexcept
Casts this rectangle to a Rectangle<double>.
See Also
getSmallestIntegerContainer
template<typename ValueType> template<typename TargetType > Rectangle<TargetType> juce::Rectangle< ValueType >::toType () const noexcept
Casts this rectangle to a Rectangle with the given type.
If the target type is a conversion from float to int, then the conversion will be done using getSmallestIntegerContainer().
template<typename ValueType> static Rectangle juce::Rectangle< ValueType >::findAreaContainingPoints (const Point< ValueType > * points, int numPoints) static noexcept
Returns the smallest Rectangle that can contain a set of points.
template<typename ValueType> static bool juce::Rectangle< ValueType >::intersectRectangles (ValueType & x1, ValueType & y1, ValueType & w1, ValueType & h1, ValueType x2, ValueType y2, ValueType w2, ValueType h2) static noexcept
Static utility to intersect two sets of rectangular coordinates.
Returns false if the two regions didn't overlap.
See Also
intersectRectangle
template<typename ValueType> String juce::Rectangle< ValueType >::toString () const
Creates a string describing this rectangle.
The string will be of the form "x y width height", e.g. "100 100 400 200".
Coupled with the fromString() method, this is very handy for things like storing rectangles (particularly component positions) in XML attributes.
See Also
fromString
template<typename ValueType> static Rectangle juce::Rectangle< ValueType >::fromString (StringRef stringVersion) static
Parses a string containing a rectangle's details.
The string should contain 4 integer tokens, in the form "x y width height". They can be comma or whitespace separated.
This method is intended to go with the toString() method, to form an easy way of saving/loading rectangles as strings.
See Also
toString
The documentation for this class was generated from the following file:
juce_Rectangle.h