JUCE: littlefoot
littlefoot
juce_blocks_basics
Namespaces
littlefoot
Classes
struct littlefoot::Compiler
This class compiles littlefoot source code into a littlefoot::Program object which can be executed by a littlefoot::Runner.
struct littlefoot::LittleFootRemoteHeap< ImplementationClass >
This class manages the synchronisation of a remote block of heap memory used by a littlefoot program running on a block.
struct littlefoot::NativeFunction
Defines a native function that the program can call.
struct littlefoot::Program
A reference to a block of memory which contains a complete program.
struct littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >
Loads a program, and lets the user execute its functions.
Macros
#define LITTLEFOOT_DEBUG_TRACE 0
#define LITTLEFOOT_DUMP_PROGRAM 0
#define LITTLEFOOT_OPCODES(OP, OP_INT8, OP_INT16, OP_INT32)
Typedefs
using littlefoot::int8 = signed char
using littlefoot::uint8 = unsigned char
using littlefoot::int16 = signed short
using littlefoot::uint16 = unsigned short
using littlefoot::int32 = signed int
using littlefoot::uint32 = unsigned int
using littlefoot::FunctionID = int16
Enumerations
enum littlefoot::OpCode : uint8 { littlefoot::OpCode::LITTLEFOOT_OP, littlefoot::OpCode::endOfOpcodes }
enum littlefoot::Type : uint8 { littlefoot::Type::void_ = 'v', littlefoot::Type::int_ = 'i', littlefoot::Type::bool_ = 'b', littlefoot::Type::float_ = 'f' }
Available value types.
Detailed Description
Class Documentation
struct littlefoot::Compiler
This class compiles littlefoot source code into a littlefoot::Program object which can be executed by a littlefoot::Runner.
Public Member Functions
Compiler ()=default
void addNativeFunctions (const char *const *functionPrototypes)
Gives the compiler a zero-terminated list of native function prototypes to use when parsing function calls.
template<typename RunnerType >
void addNativeFunctions (const RunnerType &runner)
Tells the compiler to use the list of native function prototypes from this littlefoot::Runner object.
Result compile (const String &sourceCode, uint32 defaultHeapSize)
Compiles a littlefoot program.
Program getCompiledProgram () const noexcept
After a successful compilation, this returns the finished Program.
Public Attributes
Array< uint8 > compiledObjectCode
After a successful call to compile(), this contains the bytecode generated.
Constructor & Destructor Documentation
littlefoot::Compiler::Compiler () default
Member Function Documentation
void littlefoot::Compiler::addNativeFunctions (const char *const * functionPrototypes)
Gives the compiler a zero-terminated list of native function prototypes to use when parsing function calls.
template<typename RunnerType > void littlefoot::Compiler::addNativeFunctions (const RunnerType & runner)
Tells the compiler to use the list of native function prototypes from this littlefoot::Runner object.
Result littlefoot::Compiler::compile (const String & sourceCode, uint32 defaultHeapSize)
Compiles a littlefoot program.
If there's an error, this returns it, otherwise the compiled bytecode is placed in the compiledObjectCode member.
References Result::fail(), and Result::ok().
Program littlefoot::Compiler::getCompiledProgram () const noexcept
After a successful compilation, this returns the finished Program.
Member Data Documentation
Array<uint8> littlefoot::Compiler::compiledObjectCode
After a successful call to compile(), this contains the bytecode generated.
A littlefoot::Program object can be created directly from this array.
struct littlefoot::LittleFootRemoteHeap
template<typename ImplementationClass>
struct littlefoot::LittleFootRemoteHeap< ImplementationClass >
This class manages the synchronisation of a remote block of heap memory used by a littlefoot program running on a block.
Data in the block can be changed by calling setByte, setBytes, setBits etc, and these changes will be flushed to the device when sendChanges is called.
Public Member Functions
LittleFootRemoteHeap (uint32 blockSizeToUse) noexcept
void clear () noexcept
void resetDeviceStateToUnknown ()
void resetDataRangeToUnknown (size_t offset, size_t size) noexcept
void setByte (size_t offset, uint8 value) noexcept
void setBytes (size_t offset, const uint8 *data, size_t num) noexcept
void setBits (uint32 startBit, uint32 numBits, uint32 value) noexcept
uint8 getByte (size_t offset) noexcept
void invalidateData () noexcept
bool isFullySynced () const noexcept
void sendChanges (ImplementationClass &bi, bool forceSend)
void handleACKFromDevice (ImplementationClass &bi, uint32 packetIndex) noexcept
bool isProgramLoaded () noexcept
Static Public Member Functions
static bool isAllZero (const uint8 *data, size_t size) noexcept
Public Attributes
const size_t blockSize
Static Public Attributes
static constexpr uint16 unknownByte = 0x100
Constructor & Destructor Documentation
template<typename ImplementationClass > littlefoot::LittleFootRemoteHeap< ImplementationClass >::LittleFootRemoteHeap (uint32 blockSizeToUse) noexcept
Member Function Documentation
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::clear () noexcept
References zeromem().
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::resetDeviceStateToUnknown ()
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::resetDataRangeToUnknown (size_t offset, size_t size) noexcept
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::setByte (size_t offset, uint8 value) noexcept
References jassertfalse.
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::setBytes (size_t offset, const uint8 * data, size_t num) noexcept
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::setBits (uint32 startBit, uint32 numBits, uint32 value) noexcept
References jassertfalse, readLittleEndianBitsInBuffer(), and writeLittleEndianBitsInBuffer().
template<typename ImplementationClass > uint8 littlefoot::LittleFootRemoteHeap< ImplementationClass >::getByte (size_t offset) noexcept
References jassertfalse.
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::invalidateData () noexcept
template<typename ImplementationClass > bool littlefoot::LittleFootRemoteHeap< ImplementationClass >::isFullySynced () const noexcept
template<typename ImplementationClass > static bool littlefoot::LittleFootRemoteHeap< ImplementationClass >::isAllZero (const uint8 * data, size_t size) static noexcept
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::sendChanges (ImplementationClass & bi, bool forceSend)
References Time::getCurrentTime(), and RelativeTime::milliseconds().
template<typename ImplementationClass > void littlefoot::LittleFootRemoteHeap< ImplementationClass >::handleACKFromDevice (ImplementationClass & bi, uint32 packetIndex) noexcept
template<typename ImplementationClass > bool littlefoot::LittleFootRemoteHeap< ImplementationClass >::isProgramLoaded () noexcept
References littlefoot::Program::checksumMatches(), and littlefoot::Program::getProgramSize().
Member Data Documentation
template<typename ImplementationClass > const size_t littlefoot::LittleFootRemoteHeap< ImplementationClass >::blockSize
template<typename ImplementationClass > constexpr uint16 littlefoot::LittleFootRemoteHeap< ImplementationClass >::unknownByte = 0x100 static
struct littlefoot::NativeFunction
Defines a native function that the program can call.
Public Types
using ImplementationFunction = int32(*)(void *, const int32 *)
Public Member Functions
NativeFunction (const char *nameAndArgumentTypes, ImplementationFunction fn) noexcept
Creates a NativeFunction from its signature and an implementation function.
Static Public Member Functions
static FunctionID createID (const char *nameAndArgTypes) noexcept
Converts a function signature to its hashed ID.
Public Attributes
const char * nameAndArguments
This signature must have the form "name/[return type][arg1][arg2..]".
ImplementationFunction function
A static function that will be called.
FunctionID functionID
The ID is a hash of the name + arguments, but not the return type.
Type returnType
The function's return type.
uint8 numArgs
The number of arguments that the function takes.
Member Typedef Documentation
using littlefoot::NativeFunction::ImplementationFunction = int32 (*) (void*, const int32*)
Constructor & Destructor Documentation
littlefoot::NativeFunction::NativeFunction (const char * nameAndArgumentTypes, ImplementationFunction fn) noexcept
Creates a NativeFunction from its signature and an implementation function.
The format of nameAndArgumentTypes is "name/[return type][arg1][arg2..]" So for example "int foobar (float, bool)" would be "foobar/ifb"
References numArgs, and returnType.
Member Function Documentation
static FunctionID littlefoot::NativeFunction::createID (const char * nameAndArgTypes) static noexcept
Converts a function signature to its hashed ID.
References jassert.
Member Data Documentation
const char* littlefoot::NativeFunction::nameAndArguments
This signature must have the form "name/[return type][arg1][arg2..]".
ImplementationFunction littlefoot::NativeFunction::function
A static function that will be called.
FunctionID littlefoot::NativeFunction::functionID
The ID is a hash of the name + arguments, but not the return type.
Type littlefoot::NativeFunction::returnType
The function's return type.
Referenced by NativeFunction().
uint8 littlefoot::NativeFunction::numArgs
The number of arguments that the function takes.
Referenced by NativeFunction().
struct littlefoot::Program
A reference to a block of memory which contains a complete program.
Data format: 2 bytes - program checksum 2 bytes - program size 2 bytes - num functions 2 bytes - num globals 2 bytes - amount of heap space needed (bytes) 2 bytes - ID of function 1 2 bytes - byte offset of function 1 code 2 bytes - ID of function 2 2 bytes - byte offset of function 2 code etc.. ...function code...
Public Member Functions
Program (const void *data, uint32 totalMemorySize) noexcept
uint16 getStoredChecksum () const noexcept
uint16 calculateChecksum () const noexcept
bool checksumMatches () const noexcept
uint32 getNumFunctions () const noexcept
FunctionID getFunctionID (uint32 functionIndex) const noexcept
const uint8 * getFunctionStartAddress (uint32 functionIndex) const noexcept
const uint8 * getFunctionEndAddress (uint32 functionIndex) const noexcept
uint32 getProgramSize () const noexcept
uint16 getHeapSizeBytes () const noexcept
Returns the number of bytes of heap space the program needs.
uint16 getNumGlobals () const noexcept
Returns the number of global variables the program uses.
uint32 getTotalSpaceNeeded () const noexcept
Static Public Member Functions
static uint8 getNumExtraBytesForOpcode (OpCode op) noexcept
For a given op code, this returns the number of program bytes that follow it.
static float intToFloat (int32 value) noexcept
static int32 floatToInt (float value) noexcept
static int16 readInt16 (const uint8 *d) noexcept
static int32 readInt32 (const uint8 *d) noexcept
static void writeInt16 (uint8 *d, int16 v) noexcept
static void writeInt32 (uint8 *d, int32 v) noexcept
Public Attributes
const uint8 * programStart = 0
const uint32 maxProgramSize
Static Public Attributes
static constexpr uint32 programHeaderSize = 10
Constructor & Destructor Documentation
littlefoot::Program::Program (const void * data, uint32 totalMemorySize) noexcept
References jassert.
Member Function Documentation
uint16 littlefoot::Program::getStoredChecksum () const noexcept
References programStart, and readInt16().
Referenced by checksumMatches().
uint16 littlefoot::Program::calculateChecksum () const noexcept
References getProgramSize(), and programStart.
Referenced by checksumMatches().
bool littlefoot::Program::checksumMatches () const noexcept
References calculateChecksum(), and getStoredChecksum().
Referenced by littlefoot::LittleFootRemoteHeap< ImplementationClass >::isProgramLoaded().
uint32 littlefoot::Program::getNumFunctions () const noexcept
References programStart, and readInt16().
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::FunctionExecutionContext::FunctionExecutionContext(), and getFunctionEndAddress().
FunctionID littlefoot::Program::getFunctionID (uint32 functionIndex) const noexcept
References readInt16().
const uint8* littlefoot::Program::getFunctionStartAddress (uint32 functionIndex) const noexcept
References getProgramSize(), programStart, and readInt16().
Referenced by getFunctionEndAddress().
const uint8* littlefoot::Program::getFunctionEndAddress (uint32 functionIndex) const noexcept
References getFunctionStartAddress(), getNumFunctions(), getProgramSize(), and programStart.
uint32 littlefoot::Program::getProgramSize () const noexcept
References maxProgramSize, programHeaderSize, programStart, and readInt16().
Referenced by calculateChecksum(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::clearHeapAndGlobals(), getFunctionEndAddress(), getFunctionStartAddress(), getTotalSpaceNeeded(), littlefoot::LittleFootRemoteHeap< ImplementationClass >::isProgramLoaded(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setDataByte().
uint16 littlefoot::Program::getHeapSizeBytes () const noexcept
Returns the number of bytes of heap space the program needs.
References programStart, and readInt16().
Referenced by getTotalSpaceNeeded().
uint16 littlefoot::Program::getNumGlobals () const noexcept
Returns the number of global variables the program uses.
References programStart, and readInt16().
uint32 littlefoot::Program::getTotalSpaceNeeded () const noexcept
References getHeapSizeBytes(), and getProgramSize().
static uint8 littlefoot::Program::getNumExtraBytesForOpcode (OpCode op) static noexcept
For a given op code, this returns the number of program bytes that follow it.
References jassertfalse, littlefoot::LITTLEFOOT_OP, LITTLEFOOT_OP_INT16, LITTLEFOOT_OP_INT32, LITTLEFOOT_OP_INT8, and LITTLEFOOT_OPCODES.
static float littlefoot::Program::intToFloat (int32 value) static noexcept
static int32 littlefoot::Program::floatToInt (float value) static noexcept
static int16 littlefoot::Program::readInt16 (const uint8 * d) static noexcept
Referenced by getFunctionID(), getFunctionStartAddress(), getHeapSizeBytes(), getNumFunctions(), getNumGlobals(), getProgramSize(), and getStoredChecksum().
static int32 littlefoot::Program::readInt32 (const uint8 * d) static noexcept
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapInt().
static void littlefoot::Program::writeInt16 (uint8 * d, int16 v) static noexcept
static void littlefoot::Program::writeInt32 (uint8 * d, int32 v) static noexcept
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapInt().
Member Data Documentation
constexpr uint32 littlefoot::Program::programHeaderSize = 10 static
Referenced by getProgramSize().
const uint8* littlefoot::Program::programStart = 0
Referenced by calculateChecksum(), getFunctionEndAddress(), getFunctionStartAddress(), getHeapSizeBytes(), getNumFunctions(), getNumGlobals(), getProgramSize(), and getStoredChecksum().
const uint32 littlefoot::Program::maxProgramSize
Referenced by getProgramSize().
struct littlefoot::Runner
template<int programAndHeapSpace, int stackAndGlobalsSpace>
struct littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >
Loads a program, and lets the user execute its functions.
The programAndHeapSpace is the number of bytes allocated for program + heap. stackAndGlobalsSpace is the size of the globals + stack area.
Memory layout:
Program code goes at address 0, followed by any shared data the program needs globals are at the top end of the buffer stack space stretches downwards from the start of the globals
Public Types
enum ErrorCode : uint8 {
ErrorCode::ok = 0, ErrorCode::executionTimedOut, ErrorCode::unknownInstruction, ErrorCode::stackOverflow,
ErrorCode::stackUnderflow, ErrorCode::illegalAddress, ErrorCode::divisionByZero, ErrorCode::unknownFunction
}
Return codes from a function call.
Public Member Functions
Runner () noexcept
void setNativeFunctions (const NativeFunction *functions, int numFunctions, void *userDataForCallback) noexcept
Installs an array of native functions that the code can use.
int getNumNativeFunctions () const noexcept
Returns the number of native functions available.
const NativeFunction & getNativeFunction (int index) const noexcept
Returns one of the native functions available.
void reset () noexcept
Clears the memory state.
void clearHeapAndGlobals () noexcept
Clears all the non-program data.
ErrorCode callFunction (const char *functionSignature) noexcept
Calls one of the functions in the program, by its textual signature.
ErrorCode callFunction (FunctionID function) noexcept
Calls one of the functions in the program, by its function ID.
uint8 * getProgramAndDataStart () const noexcept
uint8 * getProgramAndDataEnd () const noexcept
uint32 getProgramAndDataSize () const noexcept
uint8 * getProgramHeapStart () const noexcept
uint8 * getProgramHeapEnd () const noexcept
uint16 getProgramHeapSize () const noexcept
bool isProgramValid () const noexcept
void setDataByte (uint32 index, uint8 value) noexcept
Sets a byte of data.
void setHeapByte (uint32 index, uint8 value) noexcept
uint8 getHeapByte (uint32 index) const noexcept
uint32 getHeapBits (uint32 startBit, uint32 numBits) const noexcept
int32 setHeapInt (uint32 byteOffset, uint32 value) noexcept
int32 getHeapInt (uint32 byteOffset) const noexcept
Static Public Member Functions
static const char * getErrorDescription (ErrorCode e) noexcept
Returns a text description for an error code.
static uint32 getMaximumProgramSize () noexcept
Public Attributes
uint8 allMemory [((programAndHeapSpace+stackAndGlobalsSpace)+3)&~3]
Program program
Static Public Attributes
static constexpr uint32 totalProgramAndHeapSpace = programAndHeapSpace
static constexpr uint32 totalStackAndGlobalsSpace = stackAndGlobalsSpace
Member Enumeration Documentation
template<int programAndHeapSpace, int stackAndGlobalsSpace> enum littlefoot::Runner::ErrorCode : uint8 strong
Return codes from a function call.
Enumerator
ok
executionTimedOut
unknownInstruction
stackOverflow
stackUnderflow
illegalAddress
divisionByZero
unknownFunction
Constructor & Destructor Documentation
template<int programAndHeapSpace, int stackAndGlobalsSpace> littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::Runner () noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::reset().
Member Function Documentation
template<int programAndHeapSpace, int stackAndGlobalsSpace> void littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setNativeFunctions (const NativeFunction * functions, int numFunctions, void * userDataForCallback) noexcept
Installs an array of native functions that the code can use.
Note that this doesn't take ownership of any memory involved, so the caller mustn't pass any dangling pointers
template<int programAndHeapSpace, int stackAndGlobalsSpace> int littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getNumNativeFunctions () const noexcept
Returns the number of native functions available.
template<int programAndHeapSpace, int stackAndGlobalsSpace> const NativeFunction& littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getNativeFunction (int index) const noexcept
Returns one of the native functions available.
The index must not be out of range.
References jassert.
template<int programAndHeapSpace, int stackAndGlobalsSpace> void littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::reset () noexcept
Clears the memory state.
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::allMemory.
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::Runner().
template<int programAndHeapSpace, int stackAndGlobalsSpace> void littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::clearHeapAndGlobals () noexcept
Clears all the non-program data.
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::allMemory, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataStart(), littlefoot::Program::getProgramSize(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::program.
template<int programAndHeapSpace, int stackAndGlobalsSpace> static const char* littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getErrorDescription (ErrorCode e) static noexcept
Returns a text description for an error code.
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::divisionByZero, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::executionTimedOut, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::illegalAddress, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::ok, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::stackOverflow, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::stackUnderflow, littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::unknownFunction, and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::unknownInstruction.
template<int programAndHeapSpace, int stackAndGlobalsSpace> ErrorCode littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::callFunction (const char * functionSignature) noexcept
Calls one of the functions in the program, by its textual signature.
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::FunctionExecutionContext::run().
template<int programAndHeapSpace, int stackAndGlobalsSpace> ErrorCode littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::callFunction (FunctionID function) noexcept
Calls one of the functions in the program, by its function ID.
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::FunctionExecutionContext::run().
template<int programAndHeapSpace, int stackAndGlobalsSpace> static uint32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getMaximumProgramSize () static noexcept
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint8* littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataStart () const noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::allMemory.
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::clearHeapAndGlobals(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataSize(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setDataByte().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint8* littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataEnd () const noexcept
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataSize(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapEnd().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataSize () const noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataEnd(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataStart().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint8* littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapStart () const noexcept
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::FunctionExecutionContext::FunctionExecutionContext(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapBits(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapByte(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapInt(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapByte(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapInt().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint8* littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapEnd () const noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataEnd().
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapByte(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapByte().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint16 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapSize () const noexcept
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapBits(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapInt(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapInt().
template<int programAndHeapSpace, int stackAndGlobalsSpace> bool littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::isProgramValid () const noexcept
template<int programAndHeapSpace, int stackAndGlobalsSpace> void littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setDataByte (uint32 index, uint8 value) noexcept
Sets a byte of data.
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataStart(), littlefoot::Program::getProgramSize(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::program.
template<int programAndHeapSpace, int stackAndGlobalsSpace> void littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapByte (uint32 index, uint8 value) noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapEnd(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapStart().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint8 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapByte (uint32 index) const noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapEnd(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapStart().
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapBits (uint32 startBit, uint32 numBits) const noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapSize(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapStart(), jassertfalse, and readLittleEndianBitsInBuffer().
template<int programAndHeapSpace, int stackAndGlobalsSpace> int32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setHeapInt (uint32 byteOffset, uint32 value) noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapSize(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapStart(), and littlefoot::Program::writeInt32().
template<int programAndHeapSpace, int stackAndGlobalsSpace> int32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapInt (uint32 byteOffset) const noexcept
References littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapSize(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramHeapStart(), and littlefoot::Program::readInt32().
Member Data Documentation
template<int programAndHeapSpace, int stackAndGlobalsSpace> constexpr uint32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::totalProgramAndHeapSpace = programAndHeapSpace static
template<int programAndHeapSpace, int stackAndGlobalsSpace> constexpr uint32 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::totalStackAndGlobalsSpace = stackAndGlobalsSpace static
template<int programAndHeapSpace, int stackAndGlobalsSpace> uint8 littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::allMemory[((programAndHeapSpace+stackAndGlobalsSpace)+3)&~3]
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::clearHeapAndGlobals(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getProgramAndDataStart(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::reset().
template<int programAndHeapSpace, int stackAndGlobalsSpace> Program littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::program
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::clearHeapAndGlobals(), littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::FunctionExecutionContext::FunctionExecutionContext(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::setDataByte().
Macro Definition Documentation
#define LITTLEFOOT_DEBUG_TRACE 0
#define LITTLEFOOT_DUMP_PROGRAM 0
#define LITTLEFOOT_OPCODES (OP, OP_INT8, OP_INT16, OP_INT32)
Referenced by littlefoot::Program::getNumExtraBytesForOpcode(), and littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::FunctionExecutionContext::run().
Typedef Documentation
using littlefoot::int8 = typedef signed char
using littlefoot::uint8 = typedef unsigned char
using littlefoot::int16 = typedef signed short
using littlefoot::uint16 = typedef unsigned short
using littlefoot::int32 = typedef signed int
using littlefoot::uint32 = typedef unsigned int
using littlefoot::FunctionID = typedef int16
Enumeration Type Documentation
enum littlefoot::OpCode : uint8 strong
Enumerator
LITTLEFOOT_OP
endOfOpcodes
enum littlefoot::Type : uint8 strong
Available value types.
Enumerator
void_
int_
bool_
float_