JUCE: containers
containers
juce_core
Classes
class AbstractFifo
Encapsulates the logic required to implement a lock-free FIFO.
class Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >
Holds a resizable array of primitive or copy-by-value objects.
class ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >
Implements some basic array storage allocation functions.
class DynamicObject
Represents a dynamically implemented object.
class DefaultElementComparator< ElementType >
A simple ElementComparator class that can be used to sort an array of objects that support the '<' operator.
struct DefaultHashFunctions
A simple class to generate hash functions for some primitive types, intended for use with the HashMap class.
class HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >
Holds a set of mappings between some key/value pairs.
class LinkedListPointer< ObjectType >
Helps to manipulate singly-linked lists of objects.
class ListenerList< ListenerClass, ArrayType >
Holds a set of objects and can invoke a member function callback on each object in the set with a single call.
class NamedValueSet
Holds a set of named var objects.
class OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >
An array designed for holding objects.
class PropertySet
A set of named property values, which can be strings, integers, floating point, etc.
class ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >
Holds a list of objects derived from ReferenceCountedObject, or which implement basic reference-count handling methods.
class ScopedValueSetter< ValueType >
Helper class providing an RAII-based mechanism for temporarily setting and then re-setting a value.
class SortedSet< ElementType, TypeOfCriticalSectionToUse >
Holds a set of unique primitive objects, such as ints or doubles.
class SparseSet< Type >
Holds a set of primitive values, storing them as a set of ranges.
class var
A variant class, that can be used to hold a range of primitive values.
struct VariantConverter< Type >
This template-overloaded class can be used to convert between var and custom types.
struct VariantConverter< String >
This template-overloaded class can be used to convert between var and custom types.
Functions
JUCE_API bool operator== (const var &, const var &) noexcept
Compares the values of two var objects, using the var::equals() comparison.
JUCE_API bool operator!= (const var &, const var &) noexcept
Compares the values of two var objects, using the var::equals() comparison.
JUCE_API bool operator== (const var &, const String &)
JUCE_API bool operator!= (const var &, const String &)
JUCE_API bool operator== (const var &, const char *)
JUCE_API bool operator!= (const var &, const char *)
Detailed Description
Class Documentation
class AbstractFifo
Encapsulates the logic required to implement a lock-free FIFO.
This class handles the logic needed when building a single-reader, single-writer FIFO.
It doesn't actually hold any data itself, but your FIFO class can use one of these to manage its position and status when reading or writing to it.
To use it, you can call prepareToWrite() to determine the position within your own buffer that an incoming block of data should be stored, and prepareToRead() to find out when the next outgoing block should be read from.
e.g.
class MyFifo
{
public:
    MyFifo()  : abstractFifo (1024)
    {
    }
    void addToFifo (const int* someData, int numItems)
    {
        int start1, size1, start2, size2;
        abstractFifo.prepareToWrite (numItems, start1, size1, start2, size2);
        if (size1 > 0)
            copySomeData (myBuffer + start1, someData, size1);
        if (size2 > 0)
            copySomeData (myBuffer + start2, someData + size1, size2);
        abstractFifo.finishedWrite (size1 + size2);
    }
    void readFromFifo (int* someData, int numItems)
    {
        int start1, size1, start2, size2;
        abstractFifo.prepareToRead (numItems, start1, size1, start2, size2);
        if (size1 > 0)
            copySomeData (someData, myBuffer + start1, size1);
        if (size2 > 0)
            copySomeData (someData + size1, myBuffer + start2, size2);
        abstractFifo.finishedRead (size1 + size2);
    }
private:
    AbstractFifo abstractFifo;
    int myBuffer [1024];
};
Public Member Functions
AbstractFifo (int capacity) noexcept
Creates a FIFO to manage a buffer with the specified capacity.
~AbstractFifo ()
Destructor.
int getTotalSize () const noexcept
Returns the total size of the buffer being managed.
int getFreeSpace () const noexcept
Returns the number of items that can currently be added to the buffer without it overflowing.
int getNumReady () const noexcept
Returns the number of items that can currently be read from the buffer.
void reset () noexcept
Clears the buffer positions, so that it appears empty.
void setTotalSize (int newSize) noexcept
Changes the buffer's total size.
void prepareToWrite (int numToWrite, int &startIndex1, int &blockSize1, int &startIndex2, int &blockSize2) const noexcept
Returns the location within the buffer at which an incoming block of data should be written.
void finishedWrite (int numWritten) noexcept
Called after writing from the FIFO, to indicate that this many items have been added.
void prepareToRead (int numWanted, int &startIndex1, int &blockSize1, int &startIndex2, int &blockSize2) const noexcept
Returns the location within the buffer from which the next block of data should be read.
void finishedRead (int numRead) noexcept
Called after reading from the FIFO, to indicate that this many items have now been consumed.
Constructor & Destructor Documentation
AbstractFifo::AbstractFifo (int capacity) noexcept
Creates a FIFO to manage a buffer with the specified capacity.
AbstractFifo::~AbstractFifo ()
Destructor.
Member Function Documentation
int AbstractFifo::getTotalSize () const noexcept
Returns the total size of the buffer being managed.
int AbstractFifo::getFreeSpace () const noexcept
Returns the number of items that can currently be added to the buffer without it overflowing.
int AbstractFifo::getNumReady () const noexcept
Returns the number of items that can currently be read from the buffer.
void AbstractFifo::reset () noexcept
Clears the buffer positions, so that it appears empty.
void AbstractFifo::setTotalSize (int newSize) noexcept
Changes the buffer's total size.
Note that this isn't thread-safe, so don't call it if there's any danger that it might overlap with a call to any other method in this class!
void AbstractFifo::prepareToWrite (int numToWrite, int & startIndex1, int & blockSize1, int & startIndex2, int & blockSize2) const noexcept
Returns the location within the buffer at which an incoming block of data should be written.
Because the section of data that you want to add to the buffer may overlap the end and wrap around to the start, two blocks within your buffer are returned, and you should copy your data into the first one, with any remaining data spilling over into the second.
If the number of items you ask for is too large to fit within the buffer's free space, then blockSize1 + blockSize2 may add up to a lower value than numToWrite. If this happens, you may decide to keep waiting and re-trying the method until there's enough space available.
After calling this method, if you choose to write your data into the blocks returned, you must call finishedWrite() to tell the FIFO how much data you actually added.
e.g.
void addToFifo (const int* someData, int numItems)
{
    int start1, size1, start2, size2;
    prepareToWrite (numItems, start1, size1, start2, size2);
    if (size1 > 0)
        copySomeData (myBuffer + start1, someData, size1);
    if (size2 > 0)
        copySomeData (myBuffer + start2, someData + size1, size2);
    finishedWrite (size1 + size2);
}
Parameters
numToWrite indicates how many items you'd like to add to the buffer
startIndex1 on exit, this will contain the start index in your buffer at which your data should be written
blockSize1 on exit, this indicates how many items can be written to the block starting at startIndex1
startIndex2 on exit, this will contain the start index in your buffer at which any data that didn't fit into the first block should be written
blockSize2 on exit, this indicates how many items can be written to the block starting at startIndex2
See Also
finishedWrite
void AbstractFifo::finishedWrite (int numWritten) noexcept
Called after writing from the FIFO, to indicate that this many items have been added.
See Also
prepareToWrite
void AbstractFifo::prepareToRead (int numWanted, int & startIndex1, int & blockSize1, int & startIndex2, int & blockSize2) const noexcept
Returns the location within the buffer from which the next block of data should be read.
Because the section of data that you want to read from the buffer may overlap the end and wrap around to the start, two blocks within your buffer are returned, and you should read from both of them.
If the number of items you ask for is greater than the amount of data available, then blockSize1 + blockSize2 may add up to a lower value than numWanted. If this happens, you may decide to keep waiting and re-trying the method until there's enough data available.
After calling this method, if you choose to read the data, you must call finishedRead() to tell the FIFO how much data you have consumed.
e.g.
void readFromFifo (int* someData, int numItems)
{
    int start1, size1, start2, size2;
    prepareToRead (numSamples, start1, size1, start2, size2);
    if (size1 > 0)
        copySomeData (someData, myBuffer + start1, size1);
    if (size2 > 0)
        copySomeData (someData + size1, myBuffer + start2, size2);
    finishedRead (size1 + size2);
}
Parameters
numWanted indicates how many items you'd like to add to the buffer
startIndex1 on exit, this will contain the start index in your buffer at which your data should be written
blockSize1 on exit, this indicates how many items can be written to the block starting at startIndex1
startIndex2 on exit, this will contain the start index in your buffer at which any data that didn't fit into the first block should be written
blockSize2 on exit, this indicates how many items can be written to the block starting at startIndex2
See Also
finishedRead
void AbstractFifo::finishedRead (int numRead) noexcept
Called after reading from the FIFO, to indicate that this many items have now been consumed.
See Also
prepareToRead
class Array
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0>
class Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >
Holds a resizable array of primitive or copy-by-value objects.
Examples of arrays are: Array<int>, Array<Rectangle> or Array<MyClass*>
The Array class can be used to hold simple, non-polymorphic objects as well as primitive types - to do so, the class must fulfil these requirements:
it must have a copy constructor and assignment operator
it must be able to be relocated in memory by a memcpy without this causing any problems - so objects whose functionality relies on external pointers or references to themselves can not be used.
You can of course have an array of pointers to any kind of object, e.g. Array<MyClass*>, but if you do this, the array doesn't take any ownership of the objects - see the OwnedArray class or the ReferenceCountedArray class for more powerful ways of holding lists of objects.
For holding lists of strings, you can use Array<String>, but it's usually better to use the specialised class StringArray, which provides more useful functions.
To make all the array's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See Also
OwnedArray, ReferenceCountedArray, StringArray, CriticalSection
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
Array () noexcept
Creates an empty array.
Array (const Array< ElementType, TypeOfCriticalSectionToUse > &other)
Creates a copy of another array.
Array (Array< ElementType, TypeOfCriticalSectionToUse > &&other) noexcept
template<typename TypeToCreateFrom >
Array (const TypeToCreateFrom *values)
Initalises from a null-terminated C array of values.
template<typename TypeToCreateFrom >
Array (const TypeToCreateFrom *values, int numValues)
Initalises from a C array of values.
template<typename TypeToCreateFrom >
Array (const std::initializer_list< TypeToCreateFrom > &items)
~Array ()
Destructor.
Array & operator= (const Array &other)
Copies another array.
Array & operator= (Array &&other) noexcept
template<class OtherArrayType >
bool operator== (const OtherArrayType &other) const
Compares this array to another one.
template<class OtherArrayType >
bool operator!= (const OtherArrayType &other) const
Compares this array to another one.
void clear ()
Removes all elements from the array.
void clearQuick ()
Removes all elements from the array without freeing the array's allocated storage.
void fill (const ParameterType &newValue) noexcept
Fills the Array with the provided value.
int size () const noexcept
Returns the current number of elements in the array.
bool isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
ElementType operator[] (const int index) const
Returns one of the elements in the array.
ElementType getUnchecked (const int index) const
Returns one of the elements in the array, without checking the index passed in.
ElementType & getReference (const int index) const noexcept
Returns a direct reference to one of the elements in the array, without checking the index passed in.
ElementType getFirst () const
Returns the first element in the array, or a default value if the array is empty.
ElementType getLast () const
Returns the last element in the array, or a default value if the array is empty.
ElementType * getRawDataPointer () noexcept
Returns a pointer to the actual array data.
ElementType * begin () const noexcept
Returns a pointer to the first element in the array.
ElementType * end () const noexcept
Returns a pointer to the element which follows the last element in the array.
int indexOf (ParameterType elementToLookFor) const
Finds the index of the first element which matches the value passed in.
bool contains (ParameterType elementToLookFor) const
Returns true if the array contains at least one occurrence of an object.
void add (const ElementType &newElement)
Appends a new element at the end of the array.
void add (ElementType &&newElement)
Appends a new element at the end of the array.
template<typename... OtherElements>
void add (const ElementType &firstNewElement, OtherElements...otherElements)
Appends multiple new elements at the end of the array.
template<typename... OtherElements>
void add (ElementType &&firstNewElement, OtherElements...otherElements)
Appends multiple new elements at the end of the array.
void insert (int indexToInsertAt, ParameterType newElement)
Inserts a new element into the array at a given position.
void insertMultiple (int indexToInsertAt, ParameterType newElement, int numberOfTimesToInsertIt)
Inserts multiple copies of an element into the array at a given position.
void insertArray (int indexToInsertAt, const ElementType *newElements, int numberOfElements)
Inserts an array of values into this array at a given position.
bool addIfNotAlreadyThere (ParameterType newElement)
Appends a new element at the end of the array as long as the array doesn't already contain it.
void set (const int indexToChange, ParameterType newValue)
Replaces an element with a new value.
void setUnchecked (const int indexToChange, ParameterType newValue)
Replaces an element with a new value without doing any bounds-checking.
template<typename Type >
void addArray (const Type *elementsToAdd, int numElementsToAdd)
Adds elements from an array to the end of this array.
template<typename TypeToCreateFrom >
void addArray (const std::initializer_list< TypeToCreateFrom > &items)
template<typename Type >
void addNullTerminatedArray (const Type *const *elementsToAdd)
Adds elements from a null-terminated array of pointers to the end of this array.
template<class OtherArrayType >
void swapWith (OtherArrayType &otherArray) noexcept
This swaps the contents of this array with those of another array.
template<class OtherArrayType >
void addArray (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
Adds elements from another array to the end of this array.
void resize (const int targetNumItems)
This will enlarge or shrink the array to the given number of elements, by adding or removing items from its end.
template<class ElementComparator >
int addSorted (ElementComparator &comparator, ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
void addUsingDefaultSort (ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
template<typename ElementComparator , typename TargetValueType >
int indexOfSorted (ElementComparator &comparator, TargetValueType elementToLookFor) const
Finds the index of an element in the array, assuming that the array is sorted.
void remove (int indexToRemove)
Removes an element from the array.
ElementType removeAndReturn (const int indexToRemove)
Removes an element from the array.
void remove (const ElementType *elementToRemove)
Removes an element from the array.
void removeFirstMatchingValue (ParameterType valueToRemove)
Removes an item from the array.
int removeAllInstancesOf (ParameterType valueToRemove)
Removes items from the array.
template<typename PredicateType >
int removeIf (PredicateType predicate)
Removes items from the array.
void removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
void removeLast (int howManyToRemove=1)
Removes the last n elements from the array.
template<class OtherArrayType >
void removeValuesIn (const OtherArrayType &otherArray)
Removes any elements which are also in another array.
template<class OtherArrayType >
void removeValuesNotIn (const OtherArrayType &otherArray)
Removes any elements which are not found in another array.
void swap (const int index1, const int index2)
Swaps over two elements in the array.
void move (const int currentIndex, int newIndex) noexcept
Moves one of the values to a different position.
void minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
void ensureStorageAllocated (const int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
void sort ()
Sorts the array using a default comparison operation.
template<class ElementComparator >
void sort (ElementComparator &comparator, const bool retainOrderOfEquivalentItems=false)
Sorts the elements in the array.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this array.
Member Typedef Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> typedef TypeOfCriticalSectionToUse::ScopedLockType Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array () noexcept
Creates an empty array.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const Array< ElementType, TypeOfCriticalSectionToUse > & other)
Creates a copy of another array.
Parameters
other the array to copy
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (Array< ElementType, TypeOfCriticalSectionToUse > && other) noexcept
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename TypeToCreateFrom > Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const TypeToCreateFrom * values) explicit
Initalises from a null-terminated C array of values.
Parameters
values the array to copy from
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename TypeToCreateFrom > Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const TypeToCreateFrom * values, int numValues)
Initalises from a C array of values.
Parameters
values the array to copy from
numValues the number of values in the array
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename TypeToCreateFrom > Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const std::initializer_list< TypeToCreateFrom > & items)
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::~Array ()
Destructor.
Member Function Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array& Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator= (const Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize > & other)
Copies another array.
Parameters
other the array to copy
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array& Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator= (Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize > && other) noexcept
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > bool Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator== (const OtherArrayType & other) const
Compares this array to another one.
Two arrays are considered equal if they both contain the same set of elements, in the same order.
Parameters
other the other array to compare with
Referenced by Array< Button::Listener * >::operator!=().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > bool Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator!= (const OtherArrayType & other) const
Compares this array to another one.
Two arrays are considered equal if they both contain the same set of elements, in the same order.
Parameters
other the other array to compare with
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clear ()
Removes all elements from the array.
This will remove all the elements, and free any storage that the array is using. To clear the array without freeing the storage, use the clearQuick() method instead.
See Also
clearQuick
Referenced by SparseSet< int >::clear(), SortedSet< ColourSetting >::clear(), LassoComponent< SelectableItemType >::endLasso(), Array< Button::Listener * >::removeValuesIn(), and Array< Button::Listener * >::removeValuesNotIn().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick ()
Removes all elements from the array without freeing the array's allocated storage.
See Also
clear
Referenced by VST3BufferExchange< float >::associateBufferTo(), MidiEventList::clear(), SortedSet< ColourSetting >::clearQuick(), and Polynomial< FloatingType >::getProductWith().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::fill (const ParameterType & newValue) noexcept
Fills the Array with the provided value.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size () const noexcept
Returns the current number of elements in the array.
Referenced by SortedSet< ColourSetting >::add(), Matrix< ElementType >::clear(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::clear(), SparseSet< int >::contains(), SelectedItemSet< SelectableItemType >::deselectAll(), Matrix< ElementType >::end(), AudioUnitHelpers::getAUChannelInfo(), CoreAudioLayouts::getCoreAudioLayoutChannels(), MidiEventList::getEvent(), MidiEventList::getEventCount(), FIR::Coefficients< NumericType >::getFilterOrder(), AudioProcessor::BusesLayout::getNumChannels(), StretchableObjectResizer::getNumItems(), LookupTable< NumericType >::getNumPoints(), SparseSet< int >::getNumRanges(), SelectedItemSet< SelectableItemType >::getNumSelected(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots(), Polynomial< FloatingType >::getOrder(), Polynomial< FloatingType >::getProductWith(), Polynomial< FloatingType >::getSumWith(), SparseSet< int >::getTotalRange(), SortedSet< ColourSetting >::indexOf(), SparseSet< int >::isEmpty(), Array< Button::Listener * >::isEmpty(), LookupTable< NumericType >::isInitialised(), VST3BufferExchange< float >::mapArrangementToBuses(), VST3BufferExchange< float >::mapBufferToBuses(), Polynomial< FloatingType >::operator()(), SelectedItemSet< SelectableItemType >::operator=(), SparseSet< int >::operator[](), Oscillator< SampleType >::process(), SparseSet< int >::removeRange(), SortedSet< ColourSetting >::removeValuesIn(), SortedSet< ColourSetting >::removeValuesNotIn(), SelectedItemSet< SelectableItemType >::selectOnly(), SparseSet< int >::size(), SortedSet< ColourSetting >::size(), and Array< Button::Listener * >::sort().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> bool Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
Referenced by Polynomial< FloatingType >::Polynomial().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator[] (const int index) const
Returns one of the elements in the array.
If the index passed in is beyond the range of valid elements, this will return a default value.
If you're certain that the index will always be a valid element, you can call getUnchecked() instead, which is faster.
Parameters
index the index of the element being requested (0 is the first element in the array)
See Also
getUnchecked, getFirst, getLast
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked (const int index) const
Returns one of the elements in the array, without checking the index passed in.
Unlike the operator[] method, this will try to return an element without checking that the index is within the bounds of the array, so should only be used when you're confident that it will always be a valid index.
Parameters
index the index of the element being requested (0 is the first element in the array)
See Also
operator[], getFirst, getLast
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::clear(), SparseSet< int >::contains(), SparseSet< int >::containsRange(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::containsValue(), SparseSet< int >::getRange(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference(), SparseSet< int >::getTotalRange(), LookupTable< NumericType >::getUnchecked(), SortedSet< ColourSetting >::getUnchecked(), VST3BufferExchange< float >::mapBufferToBuses(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::Iterator::next(), Polynomial< FloatingType >::operator()(), Polynomial< FloatingType >::operator[](), SparseSet< int >::operator[](), SparseSet< int >::overlapsRange(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remove(), SparseSet< int >::removeRange(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::removeValue(), SelectedItemSet< SelectableItemType >::selectOnly(), and SparseSet< int >::size().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType& Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference (const int index) const noexcept
Returns a direct reference to one of the elements in the array, without checking the index passed in.
This is like getUnchecked, but returns a direct reference to the element, so that you can alter it directly. Obviously this can be dangerous, so only use it when absolutely necessary.
Parameters
index the index of the element being requested (0 is the first element in the array)
See Also
operator[], getFirst, getLast
Referenced by SortedSet< ColourSetting >::add(), Matrix< ElementType >::begin(), AudioUnitHelpers::getAUChannelInfo(), MidiEventList::getEvent(), AudioProcessor::BusesLayout::getNumChannels(), SortedSet< ColourSetting >::getReference(), SortedSet< ColourSetting >::indexOf(), VST3BufferExchange< float >::mapArrangementToBuses(), Matrix< ElementType >::operator()(), SelectedItemSet< SelectableItemType >::operator=(), Polynomial< FloatingType >::operator[](), SortedSet< ColourSetting >::removeValuesIn(), and SortedSet< ColourSetting >::removeValuesNotIn().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getFirst () const
Returns the first element in the array, or a default value if the array is empty.
See Also
operator[], getUnchecked, getLast
Referenced by SortedSet< ColourSetting >::getFirst().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getLast () const
Returns the last element in the array, or a default value if the array is empty.
See Also
operator[], getUnchecked, getFirst
Referenced by SortedSet< ColourSetting >::getLast(), and SparseSet< int >::removeRange().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType* Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer () noexcept
Returns a pointer to the actual array data.
This pointer will only be valid until the next time a non-const method is called on the array.
Referenced by VST3BufferExchange< float >::associateBufferTo(), FIR::Coefficients< NumericType >::getRawCoefficients(), Matrix< ElementType >::getRawDataPointer(), Matrix< ElementType >::Matrix(), and Oscillator< SampleType >::process().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType* Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin () const noexcept
Returns a pointer to the first element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
Referenced by SortedSet< ColourSetting >::begin(), Matrix< ElementType >::begin(), SelectedItemSet< SelectableItemType >::begin(), Matrix< ElementType >::clear(), FIR::Coefficients< NumericType >::getRawCoefficients(), Matrix< ElementType >::getRawDataPointer(), and SelectedItemSet< SelectableItemType >::operator=().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType* Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end () const noexcept
Returns a pointer to the element which follows the last element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
Referenced by SortedSet< ColourSetting >::end(), Matrix< ElementType >::end(), SelectedItemSet< SelectableItemType >::end(), and SelectedItemSet< SelectableItemType >::operator=().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOf (ParameterType elementToLookFor) const
Finds the index of the first element which matches the value passed in.
This will search the array for the given object, and return the index of its first occurrence. If the object isn't found, the method will return -1.
Parameters
elementToLookFor the value or object to look for
Returns
the index of the object, or -1 if it's not found
Referenced by SelectedItemSet< SelectableItemType >::deselect().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> bool Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::contains (ParameterType elementToLookFor) const
Returns true if the array contains at least one occurrence of an object.
Parameters
elementToLookFor the value or object to look for
Returns
true if the item is found
Referenced by Array< Button::Listener * >::addIfNotAlreadyThere(), and SelectedItemSet< SelectableItemType >::isSelected().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add (const ElementType & newElement)
Appends a new element at the end of the array.
Parameters
newElement the new object to add to the array
See Also
set, insert, addIfNotAlreadyThere, addSorted, addUsingDefaultSort, addArray
Referenced by Array< Button::Listener * >::addArray(), MidiEventList::addEvent(), Array< Button::Listener * >::addIfNotAlreadyThere(), SelectedItemSet< SelectableItemType >::addToSelection(), Array< Button::Listener * >::Array(), VST3BufferExchange< float >::associateBufferTo(), AudioUnitHelpers::getAUChannelInfo(), Polynomial< FloatingType >::getProductWith(), CoreAudioLayouts::getSpeakerLayoutForCoreAudioTag(), VST3BufferExchange< float >::mapArrangementToBuses(), SelectedItemSet< SelectableItemType >::operator=(), Polynomial< FloatingType >::Polynomial(), SelectedItemSet< SelectableItemType >::selectOnly(), and AudioUnitHelpers::setBusesLayout().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add (ElementType && newElement)
Appends a new element at the end of the array.
Parameters
newElement the new object to add to the array
See Also
set, insert, addIfNotAlreadyThere, addSorted, addUsingDefaultSort, addArray
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename... OtherElements> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add (const ElementType & firstNewElement, OtherElements... otherElements)
Appends multiple new elements at the end of the array.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename... OtherElements> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add (ElementType && firstNewElement, OtherElements... otherElements)
Appends multiple new elements at the end of the array.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insert (int indexToInsertAt, ParameterType newElement)
Inserts a new element into the array at a given position.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the new element should be inserted (pass in -1 to add it to the end)
newElement the new object to add to the array
See Also
add, addSorted, addUsingDefaultSort, set
Referenced by SortedSet< ColourSetting >::add(), and Array< Button::Listener * >::addSorted().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insertMultiple (int indexToInsertAt, ParameterType newElement, int numberOfTimesToInsertIt)
Inserts multiple copies of an element into the array at a given position.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the new element should be inserted
newElement the new object to add to the array
numberOfTimesToInsertIt how many copies of the value to insert
See Also
insert, add, addSorted, set
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::HashMap(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), and Array< Button::Listener * >::resize().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insertArray (int indexToInsertAt, const ElementType * newElements, int numberOfElements)
Inserts an array of values into this array at a given position.
If the index is less than 0 or greater than the size of the array, the new elements will be added to the end of the array. Otherwise, they will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the first new element should be inserted
newElements the new values to add to the array
numberOfElements how many items are in the array
See Also
insert, add, addSorted, set
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> bool Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addIfNotAlreadyThere (ParameterType newElement)
Appends a new element at the end of the array as long as the array doesn't already contain it.
If the array already contains an element that matches the one passed in, nothing will be done.
Parameters
newElement the new object to add to the array
Returns
true if the element was added to the array; false otherwise.
Referenced by CoreAudioLayouts::getCoreAudioLayoutChannels().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set (const int indexToChange, ParameterType newValue)
Replaces an element with a new value.
If the index is less than zero, this method does nothing. If the index is beyond the end of the array, the item is added to the end of the array.
Parameters
indexToChange the index whose value you want to change
newValue the new value to set for this index.
See Also
add, insert
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::clear(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remove(), and HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::removeValue().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::setUnchecked (const int indexToChange, ParameterType newValue)
Replaces an element with a new value without doing any bounds-checking.
This just sets a value directly in the array's internal storage, so you'd better make sure it's in range!
Parameters
indexToChange the index whose value you want to change
newValue the new value to set for this index.
See Also
set, getUnchecked
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename Type > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addArray (const Type * elementsToAdd, int numElementsToAdd)
Adds elements from an array to the end of this array.
Parameters
elementsToAdd an array of some kind of object from which elements can be constructed.
numElementsToAdd how many elements are in this other array
See Also
add
Referenced by Array< Button::Listener * >::addNullTerminatedArray(), Array< Button::Listener * >::Array(), and LassoComponent< SelectableItemType >::dragLasso().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename TypeToCreateFrom > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addArray (const std::initializer_list< TypeToCreateFrom > & items)
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename Type > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addNullTerminatedArray (const Type *const * elementsToAdd)
Adds elements from a null-terminated array of pointers to the end of this array.
Parameters
elementsToAdd an array of pointers to some kind of object from which elements can be constructed. This array must be terminated by a nullptr
See Also
addArray
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::swapWith (OtherArrayType & otherArray) noexcept
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
Referenced by Array< Button::Listener * >::operator=(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::swapWith(), and SortedSet< ColourSetting >::swapWith().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addArray (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
Adds elements from another array to the end of this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::resize (const int targetNumItems)
This will enlarge or shrink the array to the given number of elements, by adding or removing items from its end.
If the array is smaller than the given target size, empty elements will be appended until its size is as specified. If its size is larger than the target, items will be removed from its end to shorten it.
Referenced by Oscillator< SampleType >::prepare().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class ElementComparator > int Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addSorted (ElementComparator & comparator, ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
This will use a comparator to find the position at which the new element should go. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
newElement the new element to insert to the array
Returns
the index at which the new item was added
See Also
addUsingDefaultSort, add, sort
Referenced by Array< Button::Listener * >::addUsingDefaultSort().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addUsingDefaultSort (ParameterType newElement)
Inserts a new element into the array, assuming that the array is sorted.
This will use the DefaultElementComparator class for sorting, so your ElementType must be suitable for use with that class. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
newElement the new element to insert to the array
See Also
addSorted, sort
Referenced by SparseSet< int >::addRange(), and SparseSet< int >::removeRange().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename ElementComparator , typename TargetValueType > int Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOfSorted (ElementComparator & comparator, TargetValueType elementToLookFor) const
Finds the index of an element in the array, assuming that the array is sorted.
This will use a comparator to do a binary-chop to find the index of the given element, if it exists. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
elementToLookFor the element to search for
Returns
the index of the element, or -1 if it's not found
See Also
addSorted, sort
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::remove (int indexToRemove)
Removes an element from the array.
This will remove the element at a given index, and move back all the subsequent elements to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
See Also
removeAndReturn, removeFirstMatchingValue, removeAllInstancesOf, removeRange
Referenced by SparseSet< int >::removeRange(), and SortedSet< ColourSetting >::removeValue().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn (const int indexToRemove)
Removes an element from the array.
This will remove the element at a given index, and move back all the subsequent elements to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
Returns
the element that has been removed
See Also
removeFirstMatchingValue, removeAllInstancesOf, removeRange
Referenced by SelectedItemSet< SelectableItemType >::deselect(), SelectedItemSet< SelectableItemType >::deselectAll(), SelectedItemSet< SelectableItemType >::operator=(), and SortedSet< ColourSetting >::remove().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::remove (const ElementType * elementToRemove)
Removes an element from the array.
This will remove the element pointed to by the given iterator, and move back all the subsequent elements to close the gap. If the iterator passed in does not point to an element within the array, behaviour is undefined.
Parameters
elementToRemove a pointer to the element to remove
See Also
removeFirstMatchingValue, removeAllInstancesOf, removeRange, removeIf
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeFirstMatchingValue (ParameterType valueToRemove)
Removes an item from the array.
This will remove the first occurrence of the given element from the array. If the item isn't found, no action is taken.
Parameters
valueToRemove the object to try to remove
See Also
remove, removeRange, removeIf
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAllInstancesOf (ParameterType valueToRemove)
Removes items from the array.
This will remove all occurrences of the given element from the array. If no such items are found, no action is taken.
Parameters
valueToRemove the object to try to remove
Returns
how many objects were removed.
See Also
remove, removeRange, removeIf
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename PredicateType > int Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeIf (PredicateType predicate)
Removes items from the array.
This will remove all objects from the array that match a condition. If no such items are found, no action is taken.
Parameters
predicate the condition when to remove an item. Must be a callable type that takes an ElementType and returns a bool
Returns
how many objects were removed.
See Also
remove, removeRange, removeAllInstancesOf
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
This will remove a set of elements, starting from the given index, and move subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters
startIndex the index of the first element to remove
numberToRemove how many elements should be removed
See Also
remove, removeFirstMatchingValue, removeAllInstancesOf, removeIf
Referenced by Array< Button::Listener * >::resize().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeLast (int howManyToRemove = 1)
Removes the last n elements from the array.
Parameters
howManyToRemove how many elements to remove from the end of the array
See Also
remove, removeFirstMatchingValue, removeAllInstancesOf, removeRange
Referenced by AudioUnitHelpers::getBusesLayout().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeValuesIn (const OtherArrayType & otherArray)
Removes any elements which are also in another array.
Parameters
otherArray the other array in which to look for elements to remove
See Also
removeValuesNotIn, remove, removeFirstMatchingValue, removeAllInstancesOf, removeRange
Referenced by LassoComponent< SelectableItemType >::dragLasso().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeValuesNotIn (const OtherArrayType & otherArray)
Removes any elements which are not found in another array.
Only elements which occur in this other array will be retained.
Parameters
otherArray the array in which to look for elements NOT to remove
See Also
removeValuesIn, remove, removeFirstMatchingValue, removeAllInstancesOf, removeRange
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::swap (const int index1, const int index2)
Swaps over two elements in the array.
This swaps over the elements found at the two indexes passed in. If either index is out-of-range, this method will do nothing.
Parameters
index1 index of one of the elements to swap
index2 index of the other element to swap
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::move (const int currentIndex, int newIndex) noexcept
Moves one of the values to a different position.
This will move the value to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the value to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this value to end up. If this is less than zero, the value will be moved to the end of the array
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Referenced by SortedSet< ColourSetting >::minimiseStorageOverheads().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::ensureStorageAllocated (const int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
Referenced by SortedSet< ColourSetting >::ensureStorageAllocated().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::sort ()
Sorts the array using a default comparison operation.
If the type of your elements isn't supported by the DefaultElementComparator class then you may need to use the other version of sort, which takes a custom comparator.
Referenced by Array< Button::Listener * >::sort().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class ElementComparator > void Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::sort (ElementComparator & comparator, const bool retainOrderOfEquivalentItems = false)
Sorts the elements in the array.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
int compareElements (ElementType first, ElementType second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
See Also
addSorted, indexOfSorted, sortArray
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> const TypeOfCriticalSectionToUse& Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getLock () const noexcept
Returns the CriticalSection that locks this array.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by Array< Button::Listener * >::add(), Array< Button::Listener * >::addArray(), Array< Button::Listener * >::addIfNotAlreadyThere(), Array< Button::Listener * >::addSorted(), Array< Button::Listener * >::Array(), Array< Button::Listener * >::clear(), Array< Button::Listener * >::clearQuick(), Array< Button::Listener * >::contains(), Array< Button::Listener * >::ensureStorageAllocated(), Array< Button::Listener * >::fill(), Array< Button::Listener * >::getFirst(), Array< Button::Listener * >::getLast(), SortedSet< ColourSetting >::getLock(), Array< Button::Listener * >::getReference(), Array< Button::Listener * >::getUnchecked(), SortedSet< ColourSetting >::indexOf(), Array< Button::Listener * >::indexOf(), Array< Button::Listener * >::indexOfSorted(), Array< Button::Listener * >::insert(), Array< Button::Listener * >::insertArray(), Array< Button::Listener * >::insertMultiple(), Array< Button::Listener * >::minimiseStorageOverheads(), Array< Button::Listener * >::move(), Array< Button::Listener * >::operator=(), Array< Button::Listener * >::operator==(), Array< Button::Listener * >::operator[](), Array< Button::Listener * >::remove(), Array< Button::Listener * >::removeAllInstancesOf(), Array< Button::Listener * >::removeAndReturn(), Array< Button::Listener * >::removeFirstMatchingValue(), Array< Button::Listener * >::removeIf(), Array< Button::Listener * >::removeLast(), Array< Button::Listener * >::removeRange(), Array< Button::Listener * >::removeValuesIn(), Array< Button::Listener * >::removeValuesNotIn(), Array< Button::Listener * >::set(), Array< Button::Listener * >::setUnchecked(), Array< Button::Listener * >::sort(), Array< Button::Listener * >::swap(), and Array< Button::Listener * >::swapWith().
class ArrayAllocationBase
template<class ElementType, class TypeOfCriticalSectionToUse>
class ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >
Implements some basic array storage allocation functions.
This class isn't really for public use - it's used by the other array classes, but might come in handy for some purposes.
It inherits from a critical section class to allow the arrays to use the "empty base class optimisation" pattern to reduce their footprint.
See Also
Array, OwnedArray, ReferenceCountedArray
Inherits TypeOfCriticalSectionToUse.
Public Member Functions
ArrayAllocationBase () noexcept
Creates an empty array.
~ArrayAllocationBase () noexcept
Destructor.
ArrayAllocationBase (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > &&other) noexcept
ArrayAllocationBase & operator= (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > &&other) noexcept
void setAllocatedSize (const int numElements)
Changes the amount of storage allocated.
void ensureAllocatedSize (const int minNumElements)
Increases the amount of storage allocated if it is less than a given amount.
void shrinkToNoMoreThan (const int maxNumElements)
Minimises the amount of storage allocated so that it's no more than the given number of elements.
void swapWith (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > &other) noexcept
Swap the contents of two objects.
Public Attributes
HeapBlock< ElementType > elements
int numAllocated
Constructor & Destructor Documentation
template<class ElementType, class TypeOfCriticalSectionToUse> ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::ArrayAllocationBase () noexcept
Creates an empty array.
template<class ElementType, class TypeOfCriticalSectionToUse> ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::~ArrayAllocationBase () noexcept
Destructor.
template<class ElementType, class TypeOfCriticalSectionToUse> ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::ArrayAllocationBase (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > && other) noexcept
Member Function Documentation
template<class ElementType, class TypeOfCriticalSectionToUse> ArrayAllocationBase& ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::operator= (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > && other) noexcept
template<class ElementType, class TypeOfCriticalSectionToUse> void ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::setAllocatedSize (const int numElements)
Changes the amount of storage allocated.
This will retain any data currently held in the array, and either add or remove extra space at the end.
Parameters
numElements the number of elements that are needed
Referenced by OwnedArray< MidiBuffer >::clear(), ReferenceCountedArray< AudioProcessorGraph::Node >::clear(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::ensureAllocatedSize(), ReferenceCountedArray< AudioProcessorGraph::Node >::ReferenceCountedArray(), and ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::shrinkToNoMoreThan().
template<class ElementType, class TypeOfCriticalSectionToUse> void ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::ensureAllocatedSize (const int minNumElements)
Increases the amount of storage allocated if it is less than a given amount.
This will retain any data currently held in the array, but will add extra space at the end to make sure there it's at least as big as the size passed in. If it's already bigger, no action is taken.
Parameters
minNumElements the minimum number of elements that are needed
Referenced by OwnedArray< MidiBuffer >::add(), ReferenceCountedArray< AudioProcessorGraph::Node >::add(), ReferenceCountedArray< AudioProcessorGraph::Node >::addArray(), OwnedArray< MidiBuffer >::addArray(), OwnedArray< MidiBuffer >::addCopiesOf(), OwnedArray< MidiBuffer >::ensureStorageAllocated(), ReferenceCountedArray< AudioProcessorGraph::Node >::ensureStorageAllocated(), OwnedArray< MidiBuffer >::insert(), ReferenceCountedArray< AudioProcessorGraph::Node >::insert(), OwnedArray< MidiBuffer >::insertArray(), OwnedArray< MidiBuffer >::set(), and ReferenceCountedArray< AudioProcessorGraph::Node >::set().
template<class ElementType, class TypeOfCriticalSectionToUse> void ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::shrinkToNoMoreThan (const int maxNumElements)
Minimises the amount of storage allocated so that it's no more than the given number of elements.
Referenced by OwnedArray< MidiBuffer >::minimiseStorageOverheads(), and ReferenceCountedArray< AudioProcessorGraph::Node >::minimiseStorageOverheads().
template<class ElementType, class TypeOfCriticalSectionToUse> void ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::swapWith (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > & other) noexcept
Swap the contents of two objects.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::swapWith(), and OwnedArray< MidiBuffer >::swapWith().
Member Data Documentation
template<class ElementType, class TypeOfCriticalSectionToUse> HeapBlock<ElementType> ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::elements
Referenced by OwnedArray< MidiBuffer >::add(), ReferenceCountedArray< AudioProcessorGraph::Node >::add(), OwnedArray< MidiBuffer >::addArray(), OwnedArray< MidiBuffer >::addCopiesOf(), ReferenceCountedArray< AudioProcessorGraph::Node >::addOrReplaceSorted(), ReferenceCountedArray< AudioProcessorGraph::Node >::addSorted(), OwnedArray< MidiBuffer >::addSorted(), OwnedArray< MidiBuffer >::begin(), ReferenceCountedArray< AudioProcessorGraph::Node >::begin(), OwnedArray< MidiBuffer >::contains(), ReferenceCountedArray< AudioProcessorGraph::Node >::contains(), OwnedArray< MidiBuffer >::end(), ReferenceCountedArray< AudioProcessorGraph::Node >::end(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::ensureAllocatedSize(), OwnedArray< MidiBuffer >::getFirst(), ReferenceCountedArray< AudioProcessorGraph::Node >::getFirst(), OwnedArray< MidiBuffer >::getLast(), ReferenceCountedArray< AudioProcessorGraph::Node >::getLast(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointer(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointerUnchecked(), OwnedArray< MidiBuffer >::getRawDataPointer(), ReferenceCountedArray< AudioProcessorGraph::Node >::getRawDataPointer(), OwnedArray< MidiBuffer >::getUnchecked(), OwnedArray< MidiBuffer >::indexOf(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOf(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOfSorted(), OwnedArray< MidiBuffer >::indexOfSorted(), OwnedArray< MidiBuffer >::insert(), ReferenceCountedArray< AudioProcessorGraph::Node >::insert(), OwnedArray< MidiBuffer >::insertArray(), ReferenceCountedArray< AudioProcessorGraph::Node >::move(), OwnedArray< MidiBuffer >::move(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::operator=(), ReferenceCountedArray< AudioProcessorGraph::Node >::operator==(), OwnedArray< MidiBuffer >::operator[](), ReferenceCountedArray< AudioProcessorGraph::Node >::ReferenceCountedArray(), ReferenceCountedArray< AudioProcessorGraph::Node >::remove(), OwnedArray< MidiBuffer >::remove(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeAndReturn(), OwnedArray< MidiBuffer >::removeAndReturn(), OwnedArray< MidiBuffer >::removeObject(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeRange(), OwnedArray< MidiBuffer >::removeRange(), OwnedArray< MidiBuffer >::set(), ReferenceCountedArray< AudioProcessorGraph::Node >::set(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::setAllocatedSize(), ReferenceCountedArray< AudioProcessorGraph::Node >::sort(), OwnedArray< MidiBuffer >::sort(), ReferenceCountedArray< AudioProcessorGraph::Node >::swap(), OwnedArray< MidiBuffer >::swap(), and ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::swapWith().
template<class ElementType, class TypeOfCriticalSectionToUse> int ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::numAllocated
Referenced by ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::ensureAllocatedSize(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::operator=(), ReferenceCountedArray< AudioProcessorGraph::Node >::remove(), OwnedArray< MidiBuffer >::remove(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeAndReturn(), OwnedArray< MidiBuffer >::removeAndReturn(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeRange(), OwnedArray< MidiBuffer >::removeRange(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::setAllocatedSize(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::shrinkToNoMoreThan(), and ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::swapWith().
class DynamicObject
Represents a dynamically implemented object.
This class is primarily intended for wrapping scripting language objects, but could be used for other purposes.
An instance of a DynamicObject can be used to store named properties, and by subclassing hasMethod() and invokeMethod(), you can give your object methods.
Public Types
typedef
ReferenceCountedObjectPtr
< DynamicObject > Ptr
Public Member Functions
DynamicObject ()
DynamicObject (const DynamicObject &)
~DynamicObject ()
virtual bool hasProperty (const Identifier &propertyName) const
Returns true if the object has a property with this name.
virtual const var & getProperty (const Identifier &propertyName) const
Returns a named property.
virtual void setProperty (const Identifier &propertyName, const var &newValue)
Sets a named property.
virtual void removeProperty (const Identifier &propertyName)
Removes a named property.
virtual bool hasMethod (const Identifier &methodName) const
Checks whether this object has the specified method.
virtual var invokeMethod (Identifier methodName, const var::NativeFunctionArgs &args)
Invokes a named method on this object.
void setMethod (Identifier methodName, var::NativeFunction function)
Adds a method to the class.
void clear ()
Removes all properties and methods from the object.
NamedValueSet & getProperties () noexcept
Returns the NamedValueSet that holds the object's properties.
void cloneAllProperties ()
Calls var::clone() on all the properties that this object contains.
virtual Ptr clone ()
Returns a clone of this object.
virtual void writeAsJSON (OutputStream &, int indentLevel, bool allOnOneLine, int maximumDecimalPlaces)
Writes this object to a text stream in JSON format.
Public Member Functions inherited from ReferenceCountedObject
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Additional Inherited Members
Protected Member Functions inherited from ReferenceCountedObject
ReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () noexcept
Resets the reference count to zero without deleting the object.
Member Typedef Documentation
typedef ReferenceCountedObjectPtr<DynamicObject> DynamicObject::Ptr
Constructor & Destructor Documentation
DynamicObject::DynamicObject ()
DynamicObject::DynamicObject (const DynamicObject &)
DynamicObject::~DynamicObject ()
Member Function Documentation
virtual bool DynamicObject::hasProperty (const Identifier & propertyName) const virtual
Returns true if the object has a property with this name.
Note that if the property is actually a method, this will return false.
virtual const var& DynamicObject::getProperty (const Identifier & propertyName) const virtual
Returns a named property.
This returns var() if no such property exists.
virtual void DynamicObject::setProperty (const Identifier & propertyName, const var & newValue) virtual
Sets a named property.
virtual void DynamicObject::removeProperty (const Identifier & propertyName) virtual
Removes a named property.
virtual bool DynamicObject::hasMethod (const Identifier & methodName) const virtual
Checks whether this object has the specified method.
The default implementation of this just checks whether there's a property with this name that's actually a method, but this can be overridden for building objects with dynamic invocation.
virtual var DynamicObject::invokeMethod (Identifier methodName, const var::NativeFunctionArgs & args) virtual
Invokes a named method on this object.
The default implementation looks up the named property, and if it's a method call, then it invokes it.
This method is virtual to allow more dynamic invocation to used for objects where the methods may not already be set as properies.
void DynamicObject::setMethod (Identifier methodName, var::NativeFunction function)
Adds a method to the class.
This is basically the same as calling setProperty (methodName, (var::NativeFunction) myFunction), but helps to avoid accidentally invoking the wrong type of var constructor. It also makes the code easier to read,
void DynamicObject::clear ()
Removes all properties and methods from the object.
NamedValueSet& DynamicObject::getProperties () noexcept
Returns the NamedValueSet that holds the object's properties.
void DynamicObject::cloneAllProperties ()
Calls var::clone() on all the properties that this object contains.
virtual Ptr DynamicObject::clone () virtual
Returns a clone of this object.
The default implementation of this method just returns a new DynamicObject with a (deep) copy of all of its properties. Subclasses can override this to implement their own custom copy routines.
virtual void DynamicObject::writeAsJSON (OutputStream & , int indentLevel, bool allOnOneLine, int maximumDecimalPlaces) virtual
Writes this object to a text stream in JSON format.
This method is used by JSON::toString and JSON::writeToStream, and you should never need to call it directly, but it's virtual so that custom object types can stringify themselves appropriately.
class DefaultElementComparator
template<class ElementType>
class DefaultElementComparator< ElementType >
A simple ElementComparator class that can be used to sort an array of objects that support the '<' operator.
This will work for primitive types and objects that implement operator<().
Example:
Array <int> myArray;
DefaultElementComparator<int> sorter;
myArray.sort (sorter);
See Also
ElementComparator
Static Public Member Functions
static int compareElements (ParameterType first, ParameterType second)
Member Function Documentation
template<class ElementType> static int DefaultElementComparator< ElementType >::compareElements (ParameterType first, ParameterType second) static
struct DefaultHashFunctions
A simple class to generate hash functions for some primitive types, intended for use with the HashMap class.
See Also
HashMap
Public Member Functions
int generateHash (const int key, const int upperLimit) const noexcept
Generates a simple hash from an integer.
int generateHash (const int64 key, const int upperLimit) const noexcept
Generates a simple hash from an int64.
int generateHash (const String &key, const int upperLimit) const noexcept
Generates a simple hash from a string.
int generateHash (const var &key, const int upperLimit) const noexcept
Generates a simple hash from a variant.
int generateHash (const void *key, const int upperLimit) const noexcept
Generates a simple hash from a void ptr.
Member Function Documentation
int DefaultHashFunctions::generateHash (const int key, const int upperLimit) const noexcept
Generates a simple hash from an integer.
References abs().
int DefaultHashFunctions::generateHash (const int64 key, const int upperLimit) const noexcept
Generates a simple hash from an int64.
References abs().
int DefaultHashFunctions::generateHash (const String & key, const int upperLimit) const noexcept
Generates a simple hash from a string.
int DefaultHashFunctions::generateHash (const var & key, const int upperLimit) const noexcept
Generates a simple hash from a variant.
References generateHash().
Referenced by generateHash().
int DefaultHashFunctions::generateHash (const void * key, const int upperLimit) const noexcept
Generates a simple hash from a void ptr.
class HashMap
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection>
class HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >
Holds a set of mappings between some key/value pairs.
The types of the key and value objects are set as template parameters. You can also specify a class to supply a hash function that converts a key value into an hashed integer. This class must have the form:
struct MyHashGenerator
{
    int generateHash (MyKeyType key, int upperLimit) const
    {
        // The function must return a value 0 <= x < upperLimit
        return someFunctionOfMyKeyType (key) % upperLimit;
    }
};
Like the Array class, the key and value types are expected to be copy-by-value types, so if you define them to be pointer types, this class won't delete the objects that they point to.
If you don't supply a class for the HashFunctionType template parameter, the default one provides some simple mappings for strings and ints.
HashMap<int, String> hash;
hash.set (1, "item1");
hash.set (2, "item2");
DBG (hash [1]); // prints "item1"
DBG (hash [2]); // prints "item2"
// This iterates the map, printing all of its key -> value pairs..
for (HashMap<int, String>::Iterator i (hash); i.next();)
    DBG (i.getKey() << " -> " << i.getValue());
Template Parameters
HashFunctionType The class of hash function, which must be copy-constructible.
See Also
CriticalSection, DefaultHashFunctions, NamedValueSet, SortedSet
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
HashMap (int numberOfSlots=defaultHashTableSize, HashFunctionType hashFunction=HashFunctionType())
Creates an empty hash-map.
~HashMap ()
Destructor.
void clear ()
Removes all values from the map.
int size () const noexcept
Returns the current number of items in the map.
ValueType operator[] (KeyTypeParameter keyToLookFor) const
Returns the value corresponding to a given key.
ValueType & getReference (KeyTypeParameter keyToLookFor)
Returns a reference to the value corresponding to a given key.
bool contains (KeyTypeParameter keyToLookFor) const
Returns true if the map contains an item with the specied key.
bool containsValue (ValueTypeParameter valueToLookFor) const
Returns true if the hash contains at least one occurrence of a given value.
void set (KeyTypeParameter newKey, ValueTypeParameter newValue)
Adds or replaces an element in the hash-map.
void remove (KeyTypeParameter keyToRemove)
Removes an item with the given key.
void removeValue (ValueTypeParameter valueToRemove)
Removes all items with the given value.
void remapTable (int newNumberOfSlots)
Remaps the hash-map to use a different number of slots for its hash function.
int getNumSlots () const noexcept
Returns the number of slots which are available for hashing.
template<class OtherHashMapType >
void swapWith (OtherHashMapType &otherHashMap) noexcept
Efficiently swaps the contents of two hash-maps.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this structure.
Iterator begin () const noexcept
Returns a start iterator for the values in this tree.
Iterator end () const noexcept
Returns an end iterator for the values in this tree.
Member Typedef Documentation
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> typedef TypeOfCriticalSectionToUse::ScopedLockType HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::HashMap (int numberOfSlots = defaultHashTableSize, HashFunctionType hashFunction = HashFunctionType()) explicit
Creates an empty hash-map.
Parameters
numberOfSlots Specifies the number of hash entries the map will use. This will be the "upperLimit" parameter that is passed to your generateHash() function. The number of hash slots will grow automatically if necessary, or it can be remapped manually using remapTable().
hashFunction An instance of HashFunctionType, which will be copied and stored to use with the HashMap. This parameter can be omitted if HashFunctionType has a default constructor.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insertMultiple().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::~HashMap ()
Destructor.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::clear().
Member Function Documentation
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> void HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::clear ()
Removes all values from the map.
Note that this will clear the content, but won't affect the number of slots (see remapTable and getNumSlots).
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::~HashMap().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> int HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::size () const noexcept
Returns the current number of items in the map.
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> ValueType HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::operator[] (KeyTypeParameter keyToLookFor) const
Returns the value corresponding to a given key.
If the map doesn't contain the key, a default instance of the value type is returned.
Parameters
keyToLookFor the key of the item being requested
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> ValueType& HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference (KeyTypeParameter keyToLookFor)
Returns a reference to the value corresponding to a given key.
If the map doesn't contain the key, a default instance of the value type is added to the map and a reference to this is returned.
Parameters
keyToLookFor the key of the item being requested
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set().
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::set().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::contains (KeyTypeParameter keyToLookFor) const
Returns true if the map contains an item with the specied key.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::containsValue (ValueTypeParameter valueToLookFor) const
Returns true if the hash contains at least one occurrence of a given value.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> void HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::set (KeyTypeParameter newKey, ValueTypeParameter newValue)
Adds or replaces an element in the hash-map.
If there's already an item with the given key, this will replace its value. Otherwise, a new item will be added to the map.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> void HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remove (KeyTypeParameter keyToRemove)
Removes an item with the given key.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> void HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::removeValue (ValueTypeParameter valueToRemove)
Removes all items with the given value.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> void HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable (int newNumberOfSlots)
Remaps the hash-map to use a different number of slots for its hash function.
Each slot corresponds to a single hash-code, and each one can contain multiple items.
See Also
getNumSlots()
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insertMultiple(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::swapWith().
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> int HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getNumSlots () const noexcept
Returns the number of slots which are available for hashing.
Each slot corresponds to a single hash-code, and each one can contain multiple items.
See Also
getNumSlots()
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::containsValue(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::Iterator::next(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remove(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::removeValue(), and HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::Iterator::resetToEnd().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherHashMapType > void HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::swapWith (OtherHashMapType & otherHashMap) noexcept
Efficiently swaps the contents of two hash-maps.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::swapWith().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> const TypeOfCriticalSectionToUse& HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getLock () const noexcept
Returns the CriticalSection that locks this structure.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::clear(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::contains(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::containsValue(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::getReference(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::operator[](), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remapTable(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::remove(), HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::removeValue(), and HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::swapWith().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> Iterator HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::begin () const noexcept
Returns a start iterator for the values in this tree.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::Iterator::next().
template<typename KeyType, typename ValueType, class HashFunctionType = DefaultHashFunctions, class TypeOfCriticalSectionToUse = DummyCriticalSection> Iterator HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::end () const noexcept
Returns an end iterator for the values in this tree.
References HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::Iterator::resetToEnd().
class LinkedListPointer
template<class ObjectType>
class LinkedListPointer< ObjectType >
Helps to manipulate singly-linked lists of objects.
For objects that are designed to contain a pointer to the subsequent item in the list, this class contains methods to deal with the list. To use it, the ObjectType class that it points to must contain a LinkedListPointer called nextListItem, e.g.
struct MyObject
{
    int x, y, z;
    // A linkable object must contain a member with this name and type, which must be
    // accessible by the LinkedListPointer class. (This doesn't mean it has to be public -
    // you could make your class a friend of a LinkedListPointer<MyObject> instead).
    LinkedListPointer<MyObject> nextListItem;
};
LinkedListPointer<MyObject> myList;
myList.append (new MyObject());
myList.append (new MyObject());
int numItems = myList.size(); // returns 2
MyObject* lastInList = myList.getLast();
Public Member Functions
LinkedListPointer () noexcept
Creates a null pointer to an empty list.
LinkedListPointer (ObjectType *const headItem) noexcept
Creates a pointer to a list whose head is the item provided.
LinkedListPointer & operator= (ObjectType *const newItem) noexcept
Sets this pointer to point to a new list.
LinkedListPointer (LinkedListPointer &&other) noexcept
LinkedListPointer & operator= (LinkedListPointer &&other) noexcept
operator ObjectType * () const noexcept
Returns the item which this pointer points to.
ObjectType * get () const noexcept
Returns the item which this pointer points to.
LinkedListPointer & getLast () noexcept
Returns the last item in the list which this pointer points to.
int size () const noexcept
Returns the number of items in the list.
LinkedListPointer & operator[] (int index) noexcept
Returns the item at a given index in the list.
const LinkedListPointer & operator[] (int index) const noexcept
Returns the item at a given index in the list.
bool contains (const ObjectType *const itemToLookFor) const noexcept
Returns true if the list contains the given item.
void insertNext (ObjectType *const newItem)
Inserts an item into the list, placing it before the item that this pointer currently points to.
void insertAtIndex (int index, ObjectType *newItem)
Inserts an item at a numeric index in the list.
ObjectType * replaceNext (ObjectType *const newItem) noexcept
Replaces the object that this pointer points to, appending the rest of the list to the new object, and returning the old one.
void append (ObjectType *const newItem)
Adds an item to the end of the list.
void addCopyOfList (const LinkedListPointer &other)
Creates copies of all the items in another list and adds them to this one.
ObjectType * removeNext () noexcept
Removes the head item from the list.
void remove (ObjectType *const itemToRemove)
Removes a specific item from the list.
void deleteAll ()
Iterates the list, calling the delete operator on all of its elements and leaving this pointer empty.
LinkedListPointer * findPointerTo (ObjectType *const itemToLookFor) noexcept
Finds a pointer to a given item.
void copyToArray (ObjectType **destArray) const noexcept
Copies the items in the list to an array.
void swapWith (LinkedListPointer &other) noexcept
Swaps this pointer with another one.
Constructor & Destructor Documentation
template<class ObjectType> LinkedListPointer< ObjectType >::LinkedListPointer () noexcept
Creates a null pointer to an empty list.
template<class ObjectType> LinkedListPointer< ObjectType >::LinkedListPointer (ObjectType *const headItem) explicit noexcept
Creates a pointer to a list whose head is the item provided.
template<class ObjectType> LinkedListPointer< ObjectType >::LinkedListPointer (LinkedListPointer< ObjectType > && other) noexcept
Member Function Documentation
template<class ObjectType> LinkedListPointer& LinkedListPointer< ObjectType >::operator= (ObjectType *const newItem) noexcept
Sets this pointer to point to a new list.
template<class ObjectType> LinkedListPointer& LinkedListPointer< ObjectType >::operator= (LinkedListPointer< ObjectType > && other) noexcept
template<class ObjectType> LinkedListPointer< ObjectType >::operator ObjectType * () const noexcept
Returns the item which this pointer points to.
template<class ObjectType> ObjectType* LinkedListPointer< ObjectType >::get () const noexcept
Returns the item which this pointer points to.
template<class ObjectType> LinkedListPointer& LinkedListPointer< ObjectType >::getLast () noexcept
Returns the last item in the list which this pointer points to.
This will iterate the list and return the last item found. Obviously the speed of this operation will be proportional to the size of the list. If the list is empty the return value will be this object. If you're planning on appending a number of items to your list, it's much more efficient to use the Appender class than to repeatedly call getLast() to find the end.
Referenced by LinkedListPointer< XmlElement >::append().
template<class ObjectType> int LinkedListPointer< ObjectType >::size () const noexcept
Returns the number of items in the list.
Obviously with a simple linked list, getting the size involves iterating the list, so this can be a lengthy operation - be careful when using this method in your code.
template<class ObjectType> LinkedListPointer& LinkedListPointer< ObjectType >::operator[] (int index) noexcept
Returns the item at a given index in the list.
Since the only way to find an item is to iterate the list, this operation can obviously be slow, depending on its size, so you should be careful when using this in algorithms.
template<class ObjectType> const LinkedListPointer& LinkedListPointer< ObjectType >::operator[] (int index) const noexcept
Returns the item at a given index in the list.
Since the only way to find an item is to iterate the list, this operation can obviously be slow, depending on its size, so you should be careful when using this in algorithms.
template<class ObjectType> bool LinkedListPointer< ObjectType >::contains (const ObjectType *const itemToLookFor) const noexcept
Returns true if the list contains the given item.
template<class ObjectType> void LinkedListPointer< ObjectType >::insertNext (ObjectType *const newItem)
Inserts an item into the list, placing it before the item that this pointer currently points to.
Referenced by LinkedListPointer< XmlElement >::addCopyOfList(), and LinkedListPointer< XmlElement >::insertAtIndex().
template<class ObjectType> void LinkedListPointer< ObjectType >::insertAtIndex (int index, ObjectType * newItem)
Inserts an item at a numeric index in the list.
Obviously this will involve iterating the list to find the item at the given index, so be careful about the impact this may have on execution time.
template<class ObjectType> ObjectType* LinkedListPointer< ObjectType >::replaceNext (ObjectType *const newItem) noexcept
Replaces the object that this pointer points to, appending the rest of the list to the new object, and returning the old one.
template<class ObjectType> void LinkedListPointer< ObjectType >::append (ObjectType *const newItem)
Adds an item to the end of the list.
This operation involves iterating the whole list, so can be slow - if you need to append a number of items to your list, it's much more efficient to use the Appender class than to repeatedly call append().
template<class ObjectType> void LinkedListPointer< ObjectType >::addCopyOfList (const LinkedListPointer< ObjectType > & other)
Creates copies of all the items in another list and adds them to this one.
This will use the ObjectType's copy constructor to try to create copies of each item in the other list, and appends them to this list.
template<class ObjectType> ObjectType* LinkedListPointer< ObjectType >::removeNext () noexcept
Removes the head item from the list.
This won't delete the object that is removed, but returns it, so the caller can delete it if necessary.
template<class ObjectType> void LinkedListPointer< ObjectType >::remove (ObjectType *const itemToRemove)
Removes a specific item from the list.
Note that this will not delete the item, it simply unlinks it from the list.
template<class ObjectType> void LinkedListPointer< ObjectType >::deleteAll ()
Iterates the list, calling the delete operator on all of its elements and leaving this pointer empty.
template<class ObjectType> LinkedListPointer* LinkedListPointer< ObjectType >::findPointerTo (ObjectType *const itemToLookFor) noexcept
Finds a pointer to a given item.
If the item is found in the list, this returns the pointer that points to it. If the item isn't found, this returns null.
Referenced by LinkedListPointer< XmlElement >::remove().
template<class ObjectType> void LinkedListPointer< ObjectType >::copyToArray (ObjectType ** destArray) const noexcept
Copies the items in the list to an array.
The destArray must contain enough elements to hold the entire list - no checks are made for this!
template<class ObjectType> void LinkedListPointer< ObjectType >::swapWith (LinkedListPointer< ObjectType > & other) noexcept
Swaps this pointer with another one.
class ListenerList
template<class ListenerClass, class ArrayType = Array<ListenerClass*>>
class ListenerList< ListenerClass, ArrayType >
Holds a set of objects and can invoke a member function callback on each object in the set with a single call.
Use a ListenerList to manage a set of objects which need a callback, and you can invoke a member function by simply calling call() or callChecked().
E.g.
class MyListenerType
{
public:
    void myCallbackMethod (int foo, bool bar);
};
ListenerList <MyListenerType> listeners;
listeners.add (someCallbackObjects...);
// This will invoke myCallbackMethod (1234, true) on each of the objects
// in the list...
listeners.call (&MyListenerType::myCallbackMethod, 1234, true);
If you add or remove listeners from the list during one of the callbacks - i.e. while it's in the middle of iterating the listeners, then it's guaranteed that no listeners will be mistakenly called after they've been removed, but it may mean that some of the listeners could be called more than once, or not at all, depending on the list's order.
Sometimes, there's a chance that invoking one of the callbacks might result in the list itself being deleted while it's still iterating - to survive this situation, you can use callChecked() instead of call(), passing it a local object to act as a "BailOutChecker". The BailOutChecker must implement a method of the form "bool shouldBailOut()", and the list will check this after each callback to determine whether it should abort the operation. For an example of a bail-out checker, see the Component::BailOutChecker class, which can be used to check when a Component has been deleted. See also ListenerList::DummyBailOutChecker, which is a dummy checker that always returns false.
Public Types
typedef ListenerList
< ListenerClass, ArrayType > ThisType
typedef ListenerClass ListenerType
Public Member Functions
ListenerList ()
Creates an empty list.
~ListenerList ()
Destructor.
void add (ListenerClass *const listenerToAdd)
Adds a listener to the list.
void remove (ListenerClass *const listenerToRemove)
Removes a listener from the list.
int size () const noexcept
Returns the number of registered listeners.
bool isEmpty () const noexcept
Returns true if any listeners are registered.
void clear ()
Clears the list.
bool contains (ListenerClass *const listener) const noexcept
Returns true if the specified listener has been added to the list.
void call (void(ListenerClass::*callbackFunction)())
Calls a member function on each listener in the list, with no parameters.
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)())
Calls a member function, with no parameters, on all but the specified listener in the list.
template<class BailOutCheckerType >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)())
Calls a member function on each listener in the list, with no parameters and a bail-out-checker.
template<class BailOutCheckerType >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)())
Calls a member function on all but the specified listener in the list with a bail-out-checker.
template<LL_TEMPLATE(1) >
void call (void(ListenerClass::*callbackFunction)(P1), LL_PARAM(1))
Calls a member function on each listener in the list, with 1 parameter.
template<LL_TEMPLATE(1) >
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)(P1), LL_PARAM(1))
Calls a member function, with 1 parameter, on all but the specified listener in the list.
template<class BailOutCheckerType , LL_TEMPLATE(1) >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1), LL_PARAM(1))
Calls a member function on each listener in the list, with 1 parameter and a bail-out-checker.
template<class BailOutCheckerType , LL_TEMPLATE(1) >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1), LL_PARAM(1))
Calls a member function, with 1 parameter, on all but the specified listener in the list with a bail-out-checker.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) >
void call (void(ListenerClass::*callbackFunction)(P1, P2), LL_PARAM(1), LL_PARAM(2))
Calls a member function on each listener in the list, with 2 parameters.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) >
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)(P1, P2), LL_PARAM(1), LL_PARAM(2))
Calls a member function, with 2 parameters, on all but the specified listener in the list.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2), LL_PARAM(1), LL_PARAM(2))
Calls a member function on each listener in the list, with 2 parameters and a bail-out-checker.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2), LL_PARAM(1), LL_PARAM(2))
Calls a member function, with 2 parameters, on all but the specified listener in the list with a bail-out-checker.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) >
void call (void(ListenerClass::*callbackFunction)(P1, P2, P3), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3))
Calls a member function on each listener in the list, with 3 parameters.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) >
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)(P1, P2, P3), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3))
Calls a member function, with 3 parameters, on all but the specified listener in the list.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3))
Calls a member function on each listener in the list, with 3 parameters and a bail-out-checker.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3))
Calls a member function, with 3 parameters, on all but the specified listener in the list with a bail-out-checker.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) >
void call (void(ListenerClass::*callbackFunction)(P1, P2, P3, P4), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4))
Calls a member function on each listener in the list, with 4 parameters.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) >
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4))
Calls a member function, with 4 parameters, on all but the specified listener in the list.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4))
Calls a member function on each listener in the list, with 4 parameters and a bail-out-checker.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4))
Calls a member function, with 4 parameters, on all but the specified listener in the list with a bail-out-checker.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) >
void call (void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5))
Calls a member function on each listener in the list, with 5 parameters.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) >
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5))
Calls a member function, with 5 parameters, on all but the specified listener in the list.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5))
Calls a member function on each listener in the list, with 5 parameters and a bail-out-checker.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5))
Calls a member function, with 5 parameters, on all but the specified listener in the list with a bail-out-checker.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) >
void call (void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5, P6), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5), LL_PARAM(6))
Calls a member function on each listener in the list, with 6 parameters.
template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) >
void callExcluding (ListenerClass *listenerToExclude, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5, P6), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5), LL_PARAM(6))
Calls a member function, with 6 parameters, on all but the specified listener in the list.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) >
void callChecked (const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5, P6), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5), LL_PARAM(6))
Calls a member function on each listener in the list, with 6 parameters and a bail-out-checker.
template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) >
void callCheckedExcluding (ListenerClass *listenerToExclude, const BailOutCheckerType &bailOutChecker, void(ListenerClass::*callbackFunction)(P1, P2, P3, P4, P5, P6), LL_PARAM(1), LL_PARAM(2), LL_PARAM(3), LL_PARAM(4), LL_PARAM(5), LL_PARAM(6))
Calls a member function, with 5 parameters, on all but the specified listener in the list with a bail-out-checker.
const ArrayType & getListeners () const noexcept
Member Typedef Documentation
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> typedef ListenerList<ListenerClass, ArrayType> ListenerList< ListenerClass, ArrayType >::ThisType
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> typedef ListenerClass ListenerList< ListenerClass, ArrayType >::ListenerType
Constructor & Destructor Documentation
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> ListenerList< ListenerClass, ArrayType >::ListenerList ()
Creates an empty list.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> ListenerList< ListenerClass, ArrayType >::~ListenerList ()
Destructor.
Member Function Documentation
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> void ListenerList< ListenerClass, ArrayType >::add (ListenerClass *const listenerToAdd)
Adds a listener to the list.
A listener can only be added once, so if the listener is already in the list, this method has no effect.
See Also
remove
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> void ListenerList< ListenerClass, ArrayType >::remove (ListenerClass *const listenerToRemove)
Removes a listener from the list.
If the listener wasn't in the list, this has no effect.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> int ListenerList< ListenerClass, ArrayType >::size () const noexcept
Returns the number of registered listeners.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> bool ListenerList< ListenerClass, ArrayType >::isEmpty () const noexcept
Returns true if any listeners are registered.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> void ListenerList< ListenerClass, ArrayType >::clear ()
Clears the list.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> bool ListenerList< ListenerClass, ArrayType >::contains (ListenerClass *const listener) const noexcept
Returns true if the specified listener has been added to the list.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)() callbackFunction)
Calls a member function on each listener in the list, with no parameters.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)() callbackFunction)
Calls a member function, with no parameters, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)() callbackFunction)
Calls a member function on each listener in the list, with no parameters and a bail-out-checker.
See the class description for info about writing a bail-out checker.
Referenced by ListenerList< MenuBarModel::Listener >::call().
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)() callbackFunction)
Calls a member function on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
Referenced by ListenerList< MenuBarModel::Listener >::callExcluding().
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) > void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)(P1) callbackFunction, LL_PARAM(1))
Calls a member function on each listener in the list, with 1 parameter.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) > void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)(P1) callbackFunction, LL_PARAM(1))
Calls a member function, with 1 parameter, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1) callbackFunction, LL_PARAM(1))
Calls a member function on each listener in the list, with 1 parameter and a bail-out-checker.
See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1) callbackFunction, LL_PARAM(1))
Calls a member function, with 1 parameter, on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) > void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)(P1, P2) callbackFunction, LL_PARAM(1) , LL_PARAM(2))
Calls a member function on each listener in the list, with 2 parameters.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) > void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)(P1, P2) callbackFunction, LL_PARAM(1) , LL_PARAM(2))
Calls a member function, with 2 parameters, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2) callbackFunction, LL_PARAM(1) , LL_PARAM(2))
Calls a member function on each listener in the list, with 2 parameters and a bail-out-checker.
See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2) callbackFunction, LL_PARAM(1) , LL_PARAM(2))
Calls a member function, with 2 parameters, on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) > void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)(P1, P2, P3) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3))
Calls a member function on each listener in the list, with 3 parameters.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) > void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)(P1, P2, P3) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3))
Calls a member function, with 3 parameters, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3))
Calls a member function on each listener in the list, with 3 parameters and a bail-out-checker.
See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3))
Calls a member function, with 3 parameters, on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) > void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)(P1, P2, P3, P4) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4))
Calls a member function on each listener in the list, with 4 parameters.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) > void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)(P1, P2, P3, P4) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4))
Calls a member function, with 4 parameters, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3, P4) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4))
Calls a member function on each listener in the list, with 4 parameters and a bail-out-checker.
See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3, P4) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4))
Calls a member function, with 4 parameters, on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) > void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)(P1, P2, P3, P4, P5) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5))
Calls a member function on each listener in the list, with 5 parameters.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) > void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)(P1, P2, P3, P4, P5) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5))
Calls a member function, with 5 parameters, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3, P4, P5) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5))
Calls a member function on each listener in the list, with 5 parameters and a bail-out-checker.
See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3, P4, P5) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5))
Calls a member function, with 5 parameters, on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) > void ListenerList< ListenerClass, ArrayType >::call (void(ListenerClass::*)(P1, P2, P3, P4, P5, P6) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5) , LL_PARAM(6))
Calls a member function on each listener in the list, with 6 parameters.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) > void ListenerList< ListenerClass, ArrayType >::callExcluding (ListenerClass * listenerToExclude, void(ListenerClass::*)(P1, P2, P3, P4, P5, P6) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5) , LL_PARAM(6))
Calls a member function, with 6 parameters, on all but the specified listener in the list.
This can be useful if the caller is also a listener and needs to exclude itself.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) > void ListenerList< ListenerClass, ArrayType >::callChecked (const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3, P4, P5, P6) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5) , LL_PARAM(6))
Calls a member function on each listener in the list, with 6 parameters and a bail-out-checker.
See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> template<class BailOutCheckerType , LL_TEMPLATE(1) , LL_TEMPLATE(2) , LL_TEMPLATE(3) , LL_TEMPLATE(4) , LL_TEMPLATE(5) , LL_TEMPLATE(6) > void ListenerList< ListenerClass, ArrayType >::callCheckedExcluding (ListenerClass * listenerToExclude, const BailOutCheckerType & bailOutChecker, void(ListenerClass::*)(P1, P2, P3, P4, P5, P6) callbackFunction, LL_PARAM(1) , LL_PARAM(2) , LL_PARAM(3) , LL_PARAM(4) , LL_PARAM(5) , LL_PARAM(6))
Calls a member function, with 5 parameters, on all but the specified listener in the list with a bail-out-checker.
This can be useful if the caller is also a listener and needs to exclude itself. See the class description for info about writing a bail-out checker.
template<class ListenerClass, class ArrayType = Array<ListenerClass*>> const ArrayType& ListenerList< ListenerClass, ArrayType >::getListeners () const noexcept
class NamedValueSet
Holds a set of named var objects.
This can be used as a basic structure to hold a set of var object, which can be retrieved by using their identifier.
Public Member Functions
NamedValueSet () noexcept
Creates an empty set.
NamedValueSet (const NamedValueSet &)
Creates a copy of another set.
NamedValueSet & operator= (const NamedValueSet &)
Replaces this set with a copy of another set.
NamedValueSet (NamedValueSet &&) noexcept
Move constructor.
NamedValueSet & operator= (NamedValueSet &&) noexcept
Move assignment operator.
~NamedValueSet () noexcept
Destructor.
bool operator== (const NamedValueSet &) const
bool operator!= (const NamedValueSet &) const
NamedValueSet::NamedValue * begin ()
NamedValueSet::NamedValue * end ()
int size () const noexcept
Returns the total number of values that the set contains.
bool isEmpty () const noexcept
Returns true if the set is empty.
const var & operator[] (const Identifier &name) const noexcept
Returns the value of a named item.
var getWithDefault (const Identifier &name, const var &defaultReturnValue) const
Tries to return the named value, but if no such value is found, this will instead return the supplied default value.
bool set (const Identifier &name, const var &newValue)
Changes or adds a named value.
bool set (const Identifier &name, var &&newValue)
Changes or adds a named value.
bool contains (const Identifier &name) const noexcept
Returns true if the set contains an item with the specified name.
bool remove (const Identifier &name)
Removes a value from the set.
Identifier getName (int index) const noexcept
Returns the name of the value at a given index.
var * getVarPointer (const Identifier &name) const noexcept
Returns a pointer to the var that holds a named value, or null if there is no value with this name.
const var & getValueAt (int index) const noexcept
Returns the value of the item at a given index.
var * getVarPointerAt (int index) const noexcept
Returns the value of the item at a given index.
int indexOf (const Identifier &name) const noexcept
Returns the index of the given name, or -1 if it's not found.
void clear ()
Removes all values.
void setFromXmlAttributes (const XmlElement &xml)
Sets properties to the values of all of an XML element's attributes.
void copyToXmlAttributes (XmlElement &xml) const
Sets attributes in an XML element corresponding to each of this object's properties.
Constructor & Destructor Documentation
NamedValueSet::NamedValueSet () noexcept
Creates an empty set.
NamedValueSet::NamedValueSet (const NamedValueSet &)
Creates a copy of another set.
NamedValueSet::NamedValueSet (NamedValueSet &&) noexcept
Move constructor.
NamedValueSet::~NamedValueSet () noexcept
Destructor.
Member Function Documentation
NamedValueSet& NamedValueSet::operator= (const NamedValueSet &)
Replaces this set with a copy of another set.
NamedValueSet& NamedValueSet::operator= (NamedValueSet &&) noexcept
Move assignment operator.
bool NamedValueSet::operator== (const NamedValueSet &) const
bool NamedValueSet::operator!= (const NamedValueSet &) const
NamedValueSet::NamedValue* NamedValueSet::begin ()
NamedValueSet::NamedValue* NamedValueSet::end ()
int NamedValueSet::size () const noexcept
Returns the total number of values that the set contains.
bool NamedValueSet::isEmpty () const noexcept
Returns true if the set is empty.
const var& NamedValueSet::operator[] (const Identifier & name) const noexcept
Returns the value of a named item.
If the name isn't found, this will return a void variant.
See Also
getProperty
var NamedValueSet::getWithDefault (const Identifier & name, const var & defaultReturnValue) const
Tries to return the named value, but if no such value is found, this will instead return the supplied default value.
bool NamedValueSet::set (const Identifier & name, const var & newValue)
Changes or adds a named value.
Returns
true if a value was changed or added; false if the value was already set the value passed-in.
bool NamedValueSet::set (const Identifier & name, var && newValue)
Changes or adds a named value.
Returns
true if a value was changed or added; false if the value was already set the value passed-in.
bool NamedValueSet::contains (const Identifier & name) const noexcept
Returns true if the set contains an item with the specified name.
bool NamedValueSet::remove (const Identifier & name)
Removes a value from the set.
Returns
true if a value was removed; false if there was no value with the name that was given.
Identifier NamedValueSet::getName (int index) const noexcept
Returns the name of the value at a given index.
The index must be between 0 and size() - 1.
var* NamedValueSet::getVarPointer (const Identifier & name) const noexcept
Returns a pointer to the var that holds a named value, or null if there is no value with this name.
Do not use this method unless you really need access to the internal var object for some reason - for normal reading and writing always prefer operator[]() and set().
const var& NamedValueSet::getValueAt (int index) const noexcept
Returns the value of the item at a given index.
The index must be between 0 and size() - 1.
var* NamedValueSet::getVarPointerAt (int index) const noexcept
Returns the value of the item at a given index.
The index must be between 0 and size() - 1, or this will return a nullptr
int NamedValueSet::indexOf (const Identifier & name) const noexcept
Returns the index of the given name, or -1 if it's not found.
void NamedValueSet::clear ()
Removes all values.
void NamedValueSet::setFromXmlAttributes (const XmlElement & xml)
Sets properties to the values of all of an XML element's attributes.
void NamedValueSet::copyToXmlAttributes (XmlElement & xml) const
Sets attributes in an XML element corresponding to each of this object's properties.
class OwnedArray
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection>
class OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >
An array designed for holding objects.
This holds a list of pointers to objects, and will automatically delete the objects when they are removed from the array, or when the array is itself deleted.
Declare it in the form: OwnedArray<MyObjectClass>
..and then add new objects, e.g. myOwnedArray.add (new MyObjectClass());
After adding objects, they are 'owned' by the array and will be deleted when removed or replaced.
To make all the array's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See Also
Array, ReferenceCountedArray, StringArray, CriticalSection
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
OwnedArray () noexcept
Creates an empty array.
~OwnedArray ()
Deletes the array and also deletes any objects inside it.
OwnedArray (OwnedArray &&other) noexcept
Move constructor.
OwnedArray & operator= (OwnedArray &&other) noexcept
Move assignment operator.
void clear (bool deleteObjects=true)
Clears the array, optionally deleting the objects inside it first.
void clearQuick (bool deleteObjects)
Clears the array, optionally deleting the objects inside it first.
int size () const noexcept
Returns the number of items currently in the array.
bool isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
ObjectClass * operator[] (const int index) const noexcept
Returns a pointer to the object at this index in the array.
ObjectClass * getUnchecked (const int index) const noexcept
Returns a pointer to the object at this index in the array, without checking whether the index is in-range.
ObjectClass * getFirst () const noexcept
Returns a pointer to the first object in the array.
ObjectClass * getLast () const noexcept
Returns a pointer to the last object in the array.
ObjectClass ** getRawDataPointer () noexcept
Returns a pointer to the actual array data.
ObjectClass ** begin () const noexcept
Returns a pointer to the first element in the array.
ObjectClass ** end () const noexcept
Returns a pointer to the element which follows the last element in the array.
int indexOf (const ObjectClass *objectToLookFor) const noexcept
Finds the index of an object which might be in the array.
bool contains (const ObjectClass *objectToLookFor) const noexcept
Returns true if the array contains a specified object.
ObjectClass * add (ObjectClass *newObject) noexcept
Appends a new object to the end of the array.
ObjectClass * insert (int indexToInsertAt, ObjectClass *newObject) noexcept
Inserts a new object into the array at the given index.
void insertArray (int indexToInsertAt, ObjectClass *const *newObjects, int numberOfElements)
Inserts an array of values into this array at a given position.
bool addIfNotAlreadyThere (ObjectClass *newObject) noexcept
Appends a new object at the end of the array as long as the array doesn't already contain it.
ObjectClass * set (int indexToChange, ObjectClass *newObject, bool deleteOldElement=true)
Replaces an object in the array with a different one.
template<class OtherArrayType >
void addArray (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
Adds elements from another array to the end of this array.
template<class OtherArrayType >
void addCopiesOf (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
Adds copies of the elements in another array to the end of this array.
template<class ElementComparator >
int addSorted (ElementComparator &comparator, ObjectClass *const newObject) noexcept
Inserts a new object into the array assuming that the array is sorted.
template<typename ElementComparator >
int indexOfSorted (ElementComparator &comparator, const ObjectClass *const objectToLookFor) const noexcept
Finds the index of an object in the array, assuming that the array is sorted.
void remove (int indexToRemove, bool deleteObject=true)
Removes an object from the array.
ObjectClass * removeAndReturn (int indexToRemove)
Removes and returns an object from the array without deleting it.
void removeObject (const ObjectClass *objectToRemove, bool deleteObject=true)
Removes a specified object from the array.
void removeRange (int startIndex, int numberToRemove, bool deleteObjects=true)
Removes a range of objects from the array.
void removeLast (int howManyToRemove=1, bool deleteObjects=true)
Removes the last n objects from the array.
void swap (int index1, int index2) noexcept
Swaps a pair of objects in the array.
void move (int currentIndex, int newIndex) noexcept
Moves one of the objects to a different position.
template<class OtherArrayType >
void swapWith (OtherArrayType &otherArray) noexcept
This swaps the contents of this array with those of another array.
void minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the array.
void ensureStorageAllocated (const int minNumElements) noexcept
Increases the array's internal storage to hold a minimum number of elements.
template<class ElementComparator >
void sort (ElementComparator &comparator, bool retainOrderOfEquivalentItems=false) const noexcept
Sorts the elements in the array.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this array.
Member Typedef Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> typedef TypeOfCriticalSectionToUse::ScopedLockType OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::OwnedArray () noexcept
Creates an empty array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::~OwnedArray ()
Deletes the array and also deletes any objects inside it.
To get rid of the array without deleting its objects, use its clear (false) method before deleting it.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::OwnedArray (OwnedArray< ObjectClass, TypeOfCriticalSectionToUse > && other) noexcept
Move constructor.
Member Function Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> OwnedArray& OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator= (OwnedArray< ObjectClass, TypeOfCriticalSectionToUse > && other) noexcept
Move assignment operator.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::clear (bool deleteObjects = true)
Clears the array, optionally deleting the objects inside it first.
Referenced by OwnedArray< MidiBuffer >::removeLast().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::clearQuick (bool deleteObjects)
Clears the array, optionally deleting the objects inside it first.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> int OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::size () const noexcept
Returns the number of items currently in the array.
See Also
operator[]
Referenced by OwnedArray< MidiBuffer >::isEmpty(), and OwnedArray< MidiBuffer >::sort().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator[] (const int index) const noexcept
Returns a pointer to the object at this index in the array.
If the index is out-of-range, this will return a null pointer, (and it could be null anyway, because it's ok for the array to hold null pointers as well as objects).
See Also
getUnchecked
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getUnchecked (const int index) const noexcept
Returns a pointer to the object at this index in the array, without checking whether the index is in-range.
This is a faster and less safe version of operator[] which doesn't check the index passed in, so it can be used when you're sure the index is always going to be legal.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getFirst () const noexcept
Returns a pointer to the first object in the array.
This will return a null pointer if the array's empty.
See Also
getLast
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getLast () const noexcept
Returns a pointer to the last object in the array.
This will return a null pointer if the array's empty.
See Also
getFirst
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getRawDataPointer () noexcept
Returns a pointer to the actual array data.
This pointer will only be valid until the next time a non-const method is called on the array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::begin () const noexcept
Returns a pointer to the first element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::end () const noexcept
Returns a pointer to the element which follows the last element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> int OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::indexOf (const ObjectClass * objectToLookFor) const noexcept
Finds the index of an object which might be in the array.
Parameters
objectToLookFor the object to look for
Returns
the index at which the object was found, or -1 if it's not found
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::contains (const ObjectClass * objectToLookFor) const noexcept
Returns true if the array contains a specified object.
Parameters
objectToLookFor the object to look for
Returns
true if the object is in the array
Referenced by OwnedArray< MidiBuffer >::addIfNotAlreadyThere().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::add (ObjectClass * newObject) noexcept
Appends a new object to the end of the array.
Note that the this object will be deleted by the OwnedArray when it is removed, so be careful not to delete it somewhere else.
Also be careful not to add the same object to the array more than once, as this will obviously cause deletion of dangling pointers.
Parameters
newObject the new object to add to the array
Returns
the new object that was added
See Also
set, insert, addIfNotAlreadyThere, addSorted
Referenced by OwnedArray< MidiBuffer >::addIfNotAlreadyThere(), and OwnedArray< MidiBuffer >::insert().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::insert (int indexToInsertAt, ObjectClass * newObject) noexcept
Inserts a new object into the array at the given index.
Note that the this object will be deleted by the OwnedArray when it is removed, so be careful not to delete it somewhere else.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Be careful not to add the same object to the array more than once, as this will obviously cause deletion of dangling pointers.
Parameters
indexToInsertAt the index at which the new element should be inserted
newObject the new object to add to the array
Returns
the new object that was added
See Also
add, addSorted, addIfNotAlreadyThere, set
Referenced by OwnedArray< MidiBuffer >::addSorted().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::insertArray (int indexToInsertAt, ObjectClass *const * newObjects, int numberOfElements)
Inserts an array of values into this array at a given position.
If the index is less than 0 or greater than the size of the array, the new elements will be added to the end of the array. Otherwise, they will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the first new element should be inserted
newObjects the new values to add to the array
numberOfElements how many items are in the array
See Also
insert, add, addSorted, set
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addIfNotAlreadyThere (ObjectClass * newObject) noexcept
Appends a new object at the end of the array as long as the array doesn't already contain it.
If the array already contains a matching object, nothing will be done.
Parameters
newObject the new object to add to the array
Returns
true if the new object was added, false otherwise
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::set (int indexToChange, ObjectClass * newObject, bool deleteOldElement = true)
Replaces an object in the array with a different one.
If the index is less than zero, this method does nothing. If the index is beyond the end of the array, the new object is added to the end of the array.
Be careful not to add the same object to the array more than once, as this will obviously cause deletion of dangling pointers.
Parameters
indexToChange the index whose value you want to change
newObject the new value to set for this index.
deleteOldElement whether to delete the object that's being replaced with the new one
See Also
add, insert, remove
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addArray (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
Adds elements from another array to the end of this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addCopiesOf (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1)
Adds copies of the elements in another array to the end of this array.
The other array must be either an OwnedArray of a compatible type of object, or an Array containing pointers to the same kind of object. The objects involved must provide a copy constructor, and this will be used to create new copies of each element, and add them to this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > int OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addSorted (ElementComparator & comparator, ObjectClass *const newObject) noexcept
Inserts a new object into the array assuming that the array is sorted.
This will use a comparator to find the position at which the new object should go. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort method for details about this object's structure
newObject the new object to insert to the array
Returns
the index at which the new object was added
See Also
add, sort, indexOfSorted
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<typename ElementComparator > int OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::indexOfSorted (ElementComparator & comparator, const ObjectClass *const objectToLookFor) const noexcept
Finds the index of an object in the array, assuming that the array is sorted.
This will use a comparator to do a binary-chop to find the index of the given element, if it exists. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
objectToLookFor the object to search for
Returns
the index of the element, or -1 if it's not found
See Also
addSorted, sort
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::remove (int indexToRemove, bool deleteObject = true)
Removes an object from the array.
This will remove the object at a given index (optionally also deleting it) and move back all the subsequent objects to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
deleteObject whether to delete the object that is removed
See Also
removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeAndReturn (int indexToRemove)
Removes and returns an object from the array without deleting it.
This will remove the object at a given index and return it, moving back all the subsequent objects to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
See Also
remove, removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeObject (const ObjectClass * objectToRemove, bool deleteObject = true)
Removes a specified object from the array.
If the item isn't found, no action is taken.
Parameters
objectToRemove the object to try to remove
deleteObject whether to delete the object (if it's found)
See Also
remove, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeRange (int startIndex, int numberToRemove, bool deleteObjects = true)
Removes a range of objects from the array.
This will remove a set of objects, starting from the given index, and move any subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters
startIndex the index of the first object to remove
numberToRemove how many objects should be removed
deleteObjects whether to delete the objects that get removed
See Also
remove, removeObject
Referenced by OwnedArray< MidiBuffer >::removeLast().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeLast (int howManyToRemove = 1, bool deleteObjects = true)
Removes the last n objects from the array.
Parameters
howManyToRemove how many objects to remove from the end of the array
deleteObjects whether to also delete the objects that are removed
See Also
remove, removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::swap (int index1, int index2) noexcept
Swaps a pair of objects in the array.
If either of the indexes passed in is out-of-range, nothing will happen, otherwise the two objects at these positions will be exchanged.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::move (int currentIndex, int newIndex) noexcept
Moves one of the objects to a different position.
This will move the object to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the object to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this object to end up. If this is less than zero, it will be moved to the end of the array
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::swapWith (OtherArrayType & otherArray) noexcept
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Referenced by OwnedArray< MidiBuffer >::remove(), OwnedArray< MidiBuffer >::removeAndReturn(), and OwnedArray< MidiBuffer >::removeRange().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::ensureStorageAllocated (const int minNumElements) noexcept
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > void OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::sort (ElementComparator & comparator, bool retainOrderOfEquivalentItems = false) const noexcept
Sorts the elements in the array.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
int compareElements (ElementType* first, ElementType* second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
See Also
sortArray, indexOfSorted
Referenced by ValueTree::sort().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> const TypeOfCriticalSectionToUse& OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getLock () const noexcept
Returns the CriticalSection that locks this array.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by OwnedArray< MidiBuffer >::add(), OwnedArray< MidiBuffer >::addArray(), OwnedArray< MidiBuffer >::addCopiesOf(), OwnedArray< MidiBuffer >::addIfNotAlreadyThere(), OwnedArray< MidiBuffer >::addSorted(), OwnedArray< MidiBuffer >::clear(), OwnedArray< MidiBuffer >::clearQuick(), OwnedArray< MidiBuffer >::contains(), OwnedArray< MidiBuffer >::ensureStorageAllocated(), OwnedArray< MidiBuffer >::getFirst(), OwnedArray< MidiBuffer >::getLast(), OwnedArray< MidiBuffer >::getUnchecked(), OwnedArray< MidiBuffer >::indexOf(), OwnedArray< MidiBuffer >::indexOfSorted(), OwnedArray< MidiBuffer >::insert(), OwnedArray< MidiBuffer >::insertArray(), OwnedArray< MidiBuffer >::minimiseStorageOverheads(), OwnedArray< MidiBuffer >::move(), OwnedArray< MidiBuffer >::operator=(), OwnedArray< MidiBuffer >::operator[](), OwnedArray< MidiBuffer >::remove(), OwnedArray< MidiBuffer >::removeAndReturn(), OwnedArray< MidiBuffer >::removeLast(), OwnedArray< MidiBuffer >::removeObject(), OwnedArray< MidiBuffer >::removeRange(), OwnedArray< MidiBuffer >::set(), OwnedArray< MidiBuffer >::sort(), OwnedArray< MidiBuffer >::swap(), and OwnedArray< MidiBuffer >::swapWith().
class PropertySet
A set of named property values, which can be strings, integers, floating point, etc.
Effectively, this just wraps a StringPairArray in an interface that makes it easier to load and save types other than strings.
See the PropertiesFile class for a subclass of this, which automatically broadcasts change messages and saves/loads the list from a file.
Public Member Functions
PropertySet (bool ignoreCaseOfKeyNames=false)
Creates an empty PropertySet.
PropertySet (const PropertySet &other)
Creates a copy of another PropertySet.
PropertySet & operator= (const PropertySet &other)
Copies another PropertySet over this one.
virtual ~PropertySet ()
Destructor.
String getValue (StringRef keyName, const String &defaultReturnValue=String()) const noexcept
Returns one of the properties as a string.
int getIntValue (StringRef keyName, int defaultReturnValue=0) const noexcept
Returns one of the properties as an integer.
double getDoubleValue (StringRef keyName, double defaultReturnValue=0.0) const noexcept
Returns one of the properties as an double.
bool getBoolValue (StringRef keyName, bool defaultReturnValue=false) const noexcept
Returns one of the properties as an boolean.
XmlElement * getXmlValue (StringRef keyName) const
Returns one of the properties as an XML element.
void setValue (const String &keyName, const var &value)
Sets a named property.
void setValue (const String &keyName, const XmlElement *xml)
Sets a named property to an XML element.
void addAllPropertiesFrom (const PropertySet &source)
This copies all the values from a source PropertySet to this one.
void removeValue (StringRef keyName)
Deletes a property.
bool containsKey (StringRef keyName) const noexcept
Returns true if the properies include the given key.
void clear ()
Removes all values.
StringPairArray & getAllProperties () noexcept
Returns the keys/value pair array containing all the properties.
const CriticalSection & getLock () const noexcept
Returns the lock used when reading or writing to this set.
XmlElement * createXml (const String &nodeName) const
Returns an XML element which encapsulates all the items in this property set.
void restoreFromXml (const XmlElement &xml)
Reloads a set of properties that were previously stored as XML.
void setFallbackPropertySet (PropertySet *fallbackProperties) noexcept
Sets up a second PopertySet that will be used to look up any values that aren't set in this one.
PropertySet * getFallbackPropertySet () const noexcept
Returns the fallback property set.
Protected Member Functions
virtual void propertyChanged ()
Subclasses can override this to be told when one of the properies has been changed.
Constructor & Destructor Documentation
PropertySet::PropertySet (bool ignoreCaseOfKeyNames = false)
Creates an empty PropertySet.
Parameters
ignoreCaseOfKeyNames if true, the names of properties are compared in a case-insensitive way
PropertySet::PropertySet (const PropertySet & other)
Creates a copy of another PropertySet.
virtual PropertySet::~PropertySet () virtual
Destructor.
Member Function Documentation
PropertySet& PropertySet::operator= (const PropertySet & other)
Copies another PropertySet over this one.
String PropertySet::getValue (StringRef keyName, const String & defaultReturnValue = String()) const noexcept
Returns one of the properties as a string.
If the value isn't found in this set, then this will look for it in a fallback property set (if you've specified one with the setFallbackPropertySet() method), and if it can't find one there, it'll return the default value passed-in.
Parameters
keyName the name of the property to retrieve
defaultReturnValue a value to return if the named property doesn't actually exist
Referenced by StandalonePluginHolder::getLastFile(), and StandalonePluginHolder::reloadPluginState().
int PropertySet::getIntValue (StringRef keyName, int defaultReturnValue = 0) const noexcept
Returns one of the properties as an integer.
If the value isn't found in this set, then this will look for it in a fallback property set (if you've specified one with the setFallbackPropertySet() method), and if it can't find one there, it'll return the default value passed-in.
Parameters
keyName the name of the property to retrieve
defaultReturnValue a value to return if the named property doesn't actually exist
double PropertySet::getDoubleValue (StringRef keyName, double defaultReturnValue = 0.0) const noexcept
Returns one of the properties as an double.
If the value isn't found in this set, then this will look for it in a fallback property set (if you've specified one with the setFallbackPropertySet() method), and if it can't find one there, it'll return the default value passed-in.
Parameters
keyName the name of the property to retrieve
defaultReturnValue a value to return if the named property doesn't actually exist
bool PropertySet::getBoolValue (StringRef keyName, bool defaultReturnValue = false) const noexcept
Returns one of the properties as an boolean.
The result will be true if the string found for this key name can be parsed as a non-zero integer.
If the value isn't found in this set, then this will look for it in a fallback property set (if you've specified one with the setFallbackPropertySet() method), and if it can't find one there, it'll return the default value passed-in.
Parameters
keyName the name of the property to retrieve
defaultReturnValue a value to return if the named property doesn't actually exist
Referenced by StandalonePluginHolder::reloadAudioDeviceState().
XmlElement* PropertySet::getXmlValue (StringRef keyName) const
Returns one of the properties as an XML element.
The result will a new XMLElement object that the caller must delete. If may return nullptr if the key isn't found, or if the entry contains an string that isn't valid XML.
If the value isn't found in this set, then this will look for it in a fallback property set (if you've specified one with the setFallbackPropertySet() method), and if it can't find one there, it'll return the default value passed-in.
Parameters
keyName the name of the property to retrieve
Referenced by StandalonePluginHolder::reloadAudioDeviceState().
void PropertySet::setValue (const String & keyName, const var & value)
Sets a named property.
Parameters
keyName the name of the property to set. (This mustn't be an empty string)
value the new value to set it to
Referenced by StandalonePluginHolder::saveAudioDeviceState(), StandalonePluginHolder::savePluginState(), and StandalonePluginHolder::setLastFile().
void PropertySet::setValue (const String & keyName, const XmlElement * xml)
Sets a named property to an XML element.
Parameters
keyName the name of the property to set. (This mustn't be an empty string)
xml the new element to set it to. If this is a nullptr, the value will be set to an empty string
See Also
getXmlValue
void PropertySet::addAllPropertiesFrom (const PropertySet & source)
This copies all the values from a source PropertySet to this one.
This won't remove any existing settings, it just adds any that it finds in the source set.
void PropertySet::removeValue (StringRef keyName)
Deletes a property.
Parameters
keyName the name of the property to delete. (This mustn't be an empty string)
bool PropertySet::containsKey (StringRef keyName) const noexcept
Returns true if the properies include the given key.
void PropertySet::clear ()
Removes all values.
StringPairArray& PropertySet::getAllProperties () noexcept
Returns the keys/value pair array containing all the properties.
const CriticalSection& PropertySet::getLock () const noexcept
Returns the lock used when reading or writing to this set.
XmlElement* PropertySet::createXml (const String & nodeName) const
Returns an XML element which encapsulates all the items in this property set.
The string parameter is the tag name that should be used for the node.
See Also
restoreFromXml
void PropertySet::restoreFromXml (const XmlElement & xml)
Reloads a set of properties that were previously stored as XML.
The node passed in must have been created by the createXml() method.
See Also
createXml
void PropertySet::setFallbackPropertySet (PropertySet * fallbackProperties) noexcept
Sets up a second PopertySet that will be used to look up any values that aren't set in this one.
If you set this up to be a pointer to a second property set, then whenever one of the getValue() methods fails to find an entry in this set, it will look up that value in the fallback set, and if it finds it, it will return that.
Make sure that you don't delete the fallback set while it's still being used by another set! To remove the fallback set, just call this method with a null pointer.
See Also
getFallbackPropertySet
PropertySet* PropertySet::getFallbackPropertySet () const noexcept
Returns the fallback property set.
See Also
setFallbackPropertySet
virtual void PropertySet::propertyChanged () protected virtual
Subclasses can override this to be told when one of the properies has been changed.
Reimplemented in PropertiesFile.
class ReferenceCountedArray
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection>
class ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >
Holds a list of objects derived from ReferenceCountedObject, or which implement basic reference-count handling methods.
The template parameter specifies the class of the object you want to point to - the easiest way to make a class reference-countable is to simply make it inherit from ReferenceCountedObject or SingleThreadedReferenceCountedObject, but if you need to, you can roll your own reference-countable class by implementing a set of methods called incReferenceCount(), decReferenceCount(), and decReferenceCountWithoutDeleting(). See ReferenceCountedObject for examples of how these methods should behave.
A ReferenceCountedArray holds objects derived from ReferenceCountedObject, and takes care of incrementing and decrementing their ref counts when they are added and removed from the array.
To make all the array's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See Also
Array, OwnedArray, StringArray
Public Types
typedef
ReferenceCountedObjectPtr
< ObjectClass > ObjectClassPtr
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
ReferenceCountedArray () noexcept
Creates an empty array.
ReferenceCountedArray (const ReferenceCountedArray &other) noexcept
Creates a copy of another array.
template<class OtherObjectClass , class OtherCriticalSection >
ReferenceCountedArray (const ReferenceCountedArray< OtherObjectClass, OtherCriticalSection > &other) noexcept
Creates a copy of another array.
ReferenceCountedArray & operator= (const ReferenceCountedArray &other) noexcept
Copies another array into this one.
template<class OtherObjectClass >
ReferenceCountedArray
< ObjectClass,
TypeOfCriticalSectionToUse > & operator= (const ReferenceCountedArray< OtherObjectClass, TypeOfCriticalSectionToUse > &other) noexcept
Copies another array into this one.
~ReferenceCountedArray ()
Destructor.
void clear ()
Removes all objects from the array.
void clearQuick ()
Removes all objects from the array without freeing the array's allocated storage.
int size () const noexcept
Returns the current number of objects in the array.
bool isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
ObjectClassPtr operator[] (const int index) const noexcept
Returns a pointer to the object at this index in the array.
ObjectClassPtr getUnchecked (const int index) const noexcept
Returns a pointer to the object at this index in the array, without checking whether the index is in-range.
ObjectClass * getObjectPointer (const int index) const noexcept
Returns a raw pointer to the object at this index in the array.
ObjectClass * getObjectPointerUnchecked (const int index) const noexcept
Returns a raw pointer to the object at this index in the array, without checking whether the index is in-range.
ObjectClassPtr getFirst () const noexcept
Returns a pointer to the first object in the array.
ObjectClassPtr getLast () const noexcept
Returns a pointer to the last object in the array.
ObjectClass ** getRawDataPointer () const noexcept
Returns a pointer to the actual array data.
ObjectClass ** begin () const noexcept
Returns a pointer to the first element in the array.
ObjectClass ** end () const noexcept
Returns a pointer to the element which follows the last element in the array.
int indexOf (const ObjectClass *const objectToLookFor) const noexcept
Finds the index of the first occurrence of an object in the array.
bool contains (const ObjectClass *const objectToLookFor) const noexcept
Returns true if the array contains a specified object.
ObjectClass * add (ObjectClass *const newObject) noexcept
Appends a new object to the end of the array.
ObjectClass * insert (int indexToInsertAt, ObjectClass *const newObject) noexcept
Inserts a new object into the array at the given index.
bool addIfNotAlreadyThere (ObjectClass *const newObject) noexcept
Appends a new object at the end of the array as long as the array doesn't already contain it.
void set (const int indexToChange, ObjectClass *const newObject)
Replaces an object in the array with a different one.
void addArray (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1) noexcept
Adds elements from another array to the end of this array.
template<class ElementComparator >
int addSorted (ElementComparator &comparator, ObjectClass *newObject) noexcept
Inserts a new object into the array assuming that the array is sorted.
template<class ElementComparator >
void addOrReplaceSorted (ElementComparator &comparator, ObjectClass *newObject) noexcept
Inserts or replaces an object in the array, assuming it is sorted.
template<class ElementComparator >
int indexOfSorted (ElementComparator &comparator, const ObjectClass *const objectToLookFor) const noexcept
Finds the index of an object in the array, assuming that the array is sorted.
void remove (const int indexToRemove)
Removes an object from the array.
ObjectClassPtr removeAndReturn (const int indexToRemove)
Removes and returns an object from the array.
void removeObject (ObjectClass *const objectToRemove)
Removes the first occurrence of a specified object from the array.
void removeRange (const int startIndex, const int numberToRemove)
Removes a range of objects from the array.
void removeLast (int howManyToRemove=1)
Removes the last n objects from the array.
void swap (const int index1, const int index2) noexcept
Swaps a pair of objects in the array.
void move (const int currentIndex, int newIndex) noexcept
Moves one of the objects to a different position.
template<class OtherArrayType >
void swapWith (OtherArrayType &otherArray) noexcept
This swaps the contents of this array with those of another array.
bool operator== (const ReferenceCountedArray &other) const noexcept
Compares this array to another one.
bool operator!= (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > &other) const noexcept
Compares this array to another one.
template<class ElementComparator >
void sort (ElementComparator &comparator, const bool retainOrderOfEquivalentItems=false) const noexcept
Sorts the elements in the array.
void minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the array.
void ensureStorageAllocated (const int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this array.
Member Typedef Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> typedef ReferenceCountedObjectPtr<ObjectClass> ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::ObjectClassPtr
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> typedef TypeOfCriticalSectionToUse::ScopedLockType ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::ReferenceCountedArray () noexcept
Creates an empty array.
See Also
ReferenceCountedObject, Array, OwnedArray
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::ReferenceCountedArray (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > & other) noexcept
Creates a copy of another array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherObjectClass , class OtherCriticalSection > ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::ReferenceCountedArray (const ReferenceCountedArray< OtherObjectClass, OtherCriticalSection > & other) noexcept
Creates a copy of another array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::~ReferenceCountedArray ()
Destructor.
Any objects in the array will be released, and may be deleted if not referenced from elsewhere.
Member Function Documentation
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ReferenceCountedArray& ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator= (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > & other) noexcept
Copies another array into this one.
Any existing objects in this array will first be released.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherObjectClass > ReferenceCountedArray<ObjectClass, TypeOfCriticalSectionToUse>& ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator= (const ReferenceCountedArray< OtherObjectClass, TypeOfCriticalSectionToUse > & other) noexcept
Copies another array into this one.
Any existing objects in this array will first be released.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::clear ()
Removes all objects from the array.
Any objects in the array that whose reference counts drop to zero will be deleted.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::clearQuick ()
Removes all objects from the array without freeing the array's allocated storage.
Any objects in the array that whose reference counts drop to zero will be deleted.
See Also
clear
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> int ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::size () const noexcept
Returns the current number of objects in the array.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addArray(), ReferenceCountedArray< AudioProcessorGraph::Node >::isEmpty(), and ReferenceCountedArray< AudioProcessorGraph::Node >::sort().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClassPtr ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator[] (const int index) const noexcept
Returns a pointer to the object at this index in the array.
If the index is out-of-range, this will return a null pointer, (and it could be null anyway, because it's ok for the array to hold null pointers as well as objects).
See Also
getUnchecked
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClassPtr ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getUnchecked (const int index) const noexcept
Returns a pointer to the object at this index in the array, without checking whether the index is in-range.
This is a faster and less safe version of operator[] which doesn't check the index passed in, so it can be used when you're sure the index is always going to be legal.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addArray().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getObjectPointer (const int index) const noexcept
Returns a raw pointer to the object at this index in the array.
If the index is out-of-range, this will return a null pointer, (and it could be null anyway, because it's ok for the array to hold null pointers as well as objects).
See Also
getUnchecked
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::operator[]().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getObjectPointerUnchecked (const int index) const noexcept
Returns a raw pointer to the object at this index in the array, without checking whether the index is in-range.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::getUnchecked().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClassPtr ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getFirst () const noexcept
Returns a pointer to the first object in the array.
This will return a null pointer if the array's empty.
See Also
getLast
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClassPtr ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getLast () const noexcept
Returns a pointer to the last object in the array.
This will return a null pointer if the array's empty.
See Also
getFirst
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getRawDataPointer () const noexcept
Returns a pointer to the actual array data.
This pointer will only be valid until the next time a non-const method is called on the array.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::begin () const noexcept
Returns a pointer to the first element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass** ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::end () const noexcept
Returns a pointer to the element which follows the last element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> int ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::indexOf (const ObjectClass *const objectToLookFor) const noexcept
Finds the index of the first occurrence of an object in the array.
Parameters
objectToLookFor the object to look for
Returns
the index at which the object was found, or -1 if it's not found
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::removeObject().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::contains (const ObjectClass *const objectToLookFor) const noexcept
Returns true if the array contains a specified object.
Parameters
objectToLookFor the object to look for
Returns
true if the object is in the array
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addIfNotAlreadyThere().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::add (ObjectClass *const newObject) noexcept
Appends a new object to the end of the array.
This will increase the new object's reference count.
Parameters
newObject the new object to add to the array
See Also
set, insert, addIfNotAlreadyThere, addSorted, addArray
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addArray(), ReferenceCountedArray< AudioProcessorGraph::Node >::addIfNotAlreadyThere(), and ReferenceCountedArray< AudioProcessorGraph::Node >::insert().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClass* ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::insert (int indexToInsertAt, ObjectClass *const newObject) noexcept
Inserts a new object into the array at the given index.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
This will increase the new object's reference count.
Parameters
indexToInsertAt the index at which the new element should be inserted
newObject the new object to add to the array
See Also
add, addSorted, addIfNotAlreadyThere, set
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addOrReplaceSorted(), and ReferenceCountedArray< AudioProcessorGraph::Node >::addSorted().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::addIfNotAlreadyThere (ObjectClass *const newObject) noexcept
Appends a new object at the end of the array as long as the array doesn't already contain it.
If the array already contains a matching object, nothing will be done.
Parameters
newObject the new object to add to the array
Returns
true if the object has been added, false otherwise
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::set (const int indexToChange, ObjectClass *const newObject)
Replaces an object in the array with a different one.
If the index is less than zero, this method does nothing. If the index is beyond the end of the array, the new object is added to the end of the array.
The object being added has its reference count increased, and if it's replacing another object, then that one has its reference count decreased, and may be deleted.
Parameters
indexToChange the index whose value you want to change
newObject the new value to set for this index.
See Also
add, insert, remove
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addOrReplaceSorted().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::addArray (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1) noexcept
Adds elements from another array to the end of this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > int ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::addSorted (ElementComparator & comparator, ObjectClass * newObject) noexcept
Inserts a new object into the array assuming that the array is sorted.
This will use a comparator to find the position at which the new object should go. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator object to use to compare the elements - see the sort() method for details about this object's form
newObject the new object to insert to the array
Returns
the index at which the new object was added
See Also
add, sort
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::addOrReplaceSorted (ElementComparator & comparator, ObjectClass * newObject) noexcept
Inserts or replaces an object in the array, assuming it is sorted.
This is similar to addSorted, but if a matching element already exists, then it will be replaced by the new one, rather than the new one being added as well.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > int ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::indexOfSorted (ElementComparator & comparator, const ObjectClass *const objectToLookFor) const noexcept
Finds the index of an object in the array, assuming that the array is sorted.
This will use a comparator to do a binary-chop to find the index of the given element, if it exists. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
objectToLookFor the object to search for
Returns
the index of the element, or -1 if it's not found
See Also
addSorted, sort
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::remove (const int indexToRemove)
Removes an object from the array.
This will remove the object at a given index and move back all the subsequent objects to close the gap.
If the index passed in is out-of-range, nothing will happen.
The object that is removed will have its reference count decreased, and may be deleted if not referenced from elsewhere.
Parameters
indexToRemove the index of the element to remove
See Also
removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> ObjectClassPtr ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeAndReturn (const int indexToRemove)
Removes and returns an object from the array.
This will remove the object at a given index and return it, moving back all the subsequent objects to close the gap. If the index passed in is out-of-range, nothing will happen and a null pointer will be returned.
Parameters
indexToRemove the index of the element to remove
See Also
remove, removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeObject (ObjectClass *const objectToRemove)
Removes the first occurrence of a specified object from the array.
If the item isn't found, no action is taken. If it is found, it is removed and has its reference count decreased.
Parameters
objectToRemove the object to try to remove
See Also
remove, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeRange (const int startIndex, const int numberToRemove)
Removes a range of objects from the array.
This will remove a set of objects, starting from the given index, and move any subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
The objects that are removed will have their reference counts decreased, and may be deleted if not referenced from elsewhere.
Parameters
startIndex the index of the first object to remove
numberToRemove how many objects should be removed
See Also
remove, removeObject
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeLast (int howManyToRemove = 1)
Removes the last n objects from the array.
The objects that are removed will have their reference counts decreased, and may be deleted if not referenced from elsewhere.
Parameters
howManyToRemove how many objects to remove from the end of the array
See Also
remove, removeObject, removeRange
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::swap (const int index1, const int index2) noexcept
Swaps a pair of objects in the array.
If either of the indexes passed in is out-of-range, nothing will happen, otherwise the two objects at these positions will be exchanged.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::move (const int currentIndex, int newIndex) noexcept
Moves one of the objects to a different position.
This will move the object to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the object to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this object to end up. If this is less than zero, it will be moved to the end of the array
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherArrayType > void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::swapWith (OtherArrayType & otherArray) noexcept
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::operator=().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator== (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > & other) const noexcept
Compares this array to another one.
Returns
true only if the other array contains the same objects in the same order
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::operator!=().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::operator!= (const ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse > & other) const noexcept
Compares this array to another one.
See Also
operator==
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class ElementComparator > void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::sort (ElementComparator & comparator, const bool retainOrderOfEquivalentItems = false) const noexcept
Sorts the elements in the array.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
int compareElements (ElementType first, ElementType second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
See Also
sortArray
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::remove(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeAndReturn(), and ReferenceCountedArray< AudioProcessorGraph::Node >::removeRange().
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> void ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::ensureStorageAllocated (const int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
template<class ObjectClass, class TypeOfCriticalSectionToUse = DummyCriticalSection> const TypeOfCriticalSectionToUse& ReferenceCountedArray< ObjectClass, TypeOfCriticalSectionToUse >::getLock () const noexcept
Returns the CriticalSection that locks this array.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::add(), ReferenceCountedArray< AudioProcessorGraph::Node >::addArray(), ReferenceCountedArray< AudioProcessorGraph::Node >::addIfNotAlreadyThere(), ReferenceCountedArray< AudioProcessorGraph::Node >::addOrReplaceSorted(), ReferenceCountedArray< AudioProcessorGraph::Node >::addSorted(), ReferenceCountedArray< AudioProcessorGraph::Node >::clear(), ReferenceCountedArray< AudioProcessorGraph::Node >::clearQuick(), ReferenceCountedArray< AudioProcessorGraph::Node >::contains(), ReferenceCountedArray< AudioProcessorGraph::Node >::ensureStorageAllocated(), ReferenceCountedArray< AudioProcessorGraph::Node >::getFirst(), ReferenceCountedArray< AudioProcessorGraph::Node >::getLast(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointer(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointerUnchecked(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOf(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOfSorted(), ReferenceCountedArray< AudioProcessorGraph::Node >::insert(), ReferenceCountedArray< AudioProcessorGraph::Node >::minimiseStorageOverheads(), ReferenceCountedArray< AudioProcessorGraph::Node >::move(), ReferenceCountedArray< AudioProcessorGraph::Node >::operator==(), ReferenceCountedArray< AudioProcessorGraph::Node >::remove(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeAndReturn(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeLast(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeObject(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeRange(), ReferenceCountedArray< AudioProcessorGraph::Node >::set(), ReferenceCountedArray< AudioProcessorGraph::Node >::sort(), ReferenceCountedArray< AudioProcessorGraph::Node >::swap(), and ReferenceCountedArray< AudioProcessorGraph::Node >::swapWith().
class ScopedValueSetter
template<typename ValueType>
class ScopedValueSetter< ValueType >
Helper class providing an RAII-based mechanism for temporarily setting and then re-setting a value.
E.g.
int x = 1;
{
    ScopedValueSetter setter (x, 2);
    // x is now 2
}
// x is now 1 again
{
    ScopedValueSetter setter (x, 3, 4);
    // x is now 3
}
// x is now 4
Public Member Functions
ScopedValueSetter (ValueType &valueToSet, ValueType newValue)
Creates a ScopedValueSetter that will immediately change the specified value to the given new value, and will then reset it to its original value when this object is deleted.
ScopedValueSetter (ValueType &valueToSet, ValueType newValue, ValueType valueWhenDeleted)
Creates a ScopedValueSetter that will immediately change the specified value to the given new value, and will then reset it to be valueWhenDeleted when this object is deleted.
~ScopedValueSetter ()
Constructor & Destructor Documentation
template<typename ValueType > ScopedValueSetter< ValueType >::ScopedValueSetter (ValueType & valueToSet, ValueType newValue)
Creates a ScopedValueSetter that will immediately change the specified value to the given new value, and will then reset it to its original value when this object is deleted.
template<typename ValueType > ScopedValueSetter< ValueType >::ScopedValueSetter (ValueType & valueToSet, ValueType newValue, ValueType valueWhenDeleted)
Creates a ScopedValueSetter that will immediately change the specified value to the given new value, and will then reset it to be valueWhenDeleted when this object is deleted.
template<typename ValueType > ScopedValueSetter< ValueType >::~ScopedValueSetter ()
class SortedSet
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection>
class SortedSet< ElementType, TypeOfCriticalSectionToUse >
Holds a set of unique primitive objects, such as ints or doubles.
A set can only hold one item with a given value, so if for example it's a set of integers, attempting to add the same integer twice will do nothing the second time.
Internally, the list of items is kept sorted (which means that whatever kind of primitive type is used must support the ==, <, >, <= and >= operators to determine the order), and searching the set for known values is very fast because it uses a binary-chop method.
Note that if you're using a class or struct as the element type, it must be capable of being copied or moved with a straightforward memcpy, rather than needing construction and destruction code.
To make all the set's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See Also
Array, OwnedArray, ReferenceCountedArray, StringArray, CriticalSection
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Returns the type of scoped lock to use for locking this array.
Public Member Functions
SortedSet () noexcept=default
Creates an empty set.
SortedSet (const SortedSet &)=default
Creates a copy of another set.
SortedSet (SortedSet &&) noexcept=default
Creates a copy of another set.
SortedSet & operator= (const SortedSet &)=default
Makes a copy of another set.
SortedSet & operator= (SortedSet &&) noexcept=default
Makes a copy of another set.
~SortedSet () noexcept
Destructor.
bool operator== (const SortedSet< ElementType > &other) const noexcept
Compares this set to another one.
bool operator!= (const SortedSet< ElementType > &other) const noexcept
Compares this set to another one.
void clear () noexcept
Removes all elements from the set.
void clearQuick () noexcept
Removes all elements from the set without freeing the array's allocated storage.
int size () const noexcept
Returns the current number of elements in the set.
bool isEmpty () const noexcept
Returns true if the set is empty, false otherwise.
ElementType operator[] (const int index) const noexcept
Returns one of the elements in the set.
ElementType getUnchecked (const int index) const noexcept
Returns one of the elements in the set, without checking the index passed in.
ElementType & getReference (const int index) const noexcept
Returns a direct reference to one of the elements in the set, without checking the index passed in.
ElementType getFirst () const noexcept
Returns the first element in the set, or 0 if the set is empty.
ElementType getLast () const noexcept
Returns the last element in the set, or 0 if the set is empty.
ElementType * begin () const noexcept
Returns a pointer to the first element in the set.
ElementType * end () const noexcept
Returns a pointer to the element which follows the last element in the set.
int indexOf (const ElementType &elementToLookFor) const noexcept
Finds the index of the first element which matches the value passed in.
bool contains (const ElementType &elementToLookFor) const noexcept
Returns true if the set contains at least one occurrence of an object.
bool add (const ElementType &newElement) noexcept
Adds a new element to the set, (as long as it's not already in there).
void addArray (const ElementType *elementsToAdd, int numElementsToAdd) noexcept
Adds elements from an array to this set.
template<class OtherSetType >
void addSet (const OtherSetType &setToAddFrom, int startIndex=0, int numElementsToAdd=-1) noexcept
Adds elements from another set to this one.
ElementType remove (const int indexToRemove) noexcept
Removes an element from the set.
void removeValue (const ElementType valueToRemove) noexcept
Removes an item from the set.
template<class OtherSetType >
void removeValuesIn (const OtherSetType &otherSet) noexcept
Removes any elements which are also in another set.
template<class OtherSetType >
void removeValuesNotIn (const OtherSetType &otherSet) noexcept
Removes any elements which are not found in another set.
template<class OtherSetType >
void swapWith (OtherSetType &otherSet) noexcept
This swaps the contents of this array with those of another array.
void minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the set.
void ensureStorageAllocated (const int minNumElements)
Increases the set's internal storage to hold a minimum number of elements.
const TypeOfCriticalSectionToUse & getLock () const noexcept
Returns the CriticalSection that locks this array.
Member Typedef Documentation
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> typedef TypeOfCriticalSectionToUse::ScopedLockType SortedSet< ElementType, TypeOfCriticalSectionToUse >::ScopedLockType
Returns the type of scoped lock to use for locking this array.
Constructor & Destructor Documentation
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> SortedSet< ElementType, TypeOfCriticalSectionToUse >::SortedSet () default noexcept
Creates an empty set.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> SortedSet< ElementType, TypeOfCriticalSectionToUse >::SortedSet (const SortedSet< ElementType, TypeOfCriticalSectionToUse > &) default
Creates a copy of another set.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> SortedSet< ElementType, TypeOfCriticalSectionToUse >::SortedSet (SortedSet< ElementType, TypeOfCriticalSectionToUse > &&) default noexcept
Creates a copy of another set.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> SortedSet< ElementType, TypeOfCriticalSectionToUse >::~SortedSet () noexcept
Destructor.
Member Function Documentation
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> SortedSet& SortedSet< ElementType, TypeOfCriticalSectionToUse >::operator= (const SortedSet< ElementType, TypeOfCriticalSectionToUse > &) default
Makes a copy of another set.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> SortedSet& SortedSet< ElementType, TypeOfCriticalSectionToUse >::operator= (SortedSet< ElementType, TypeOfCriticalSectionToUse > &&) default noexcept
Makes a copy of another set.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool SortedSet< ElementType, TypeOfCriticalSectionToUse >::operator== (const SortedSet< ElementType > & other) const noexcept
Compares this set to another one.
Two sets are considered equal if they both contain the same set of elements.
Parameters
other the other set to compare with
Referenced by SortedSet< ColourSetting >::operator!=().
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool SortedSet< ElementType, TypeOfCriticalSectionToUse >::operator!= (const SortedSet< ElementType > & other) const noexcept
Compares this set to another one.
Two sets are considered equal if they both contain the same set of elements.
Parameters
other the other set to compare with
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> void SortedSet< ElementType, TypeOfCriticalSectionToUse >::clear () noexcept
Removes all elements from the set.
This will remove all the elements, and free any storage that the set is using. To clear it without freeing the storage, use the clearQuick() method instead.
See Also
clearQuick
Referenced by SortedSet< ColourSetting >::removeValuesIn(), and SortedSet< ColourSetting >::removeValuesNotIn().
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> void SortedSet< ElementType, TypeOfCriticalSectionToUse >::clearQuick () noexcept
Removes all elements from the set without freeing the array's allocated storage.
See Also
clear
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> int SortedSet< ElementType, TypeOfCriticalSectionToUse >::size () const noexcept
Returns the current number of elements in the set.
Referenced by SortedSet< ColourSetting >::isEmpty().
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool SortedSet< ElementType, TypeOfCriticalSectionToUse >::isEmpty () const noexcept
Returns true if the set is empty, false otherwise.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType SortedSet< ElementType, TypeOfCriticalSectionToUse >::operator[] (const int index) const noexcept
Returns one of the elements in the set.
If the index passed in is beyond the range of valid elements, this will return zero.
If you're certain that the index will always be a valid element, you can call getUnchecked() instead, which is faster.
Parameters
index the index of the element being requested (0 is the first element in the set)
See Also
getUnchecked, getFirst, getLast
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType SortedSet< ElementType, TypeOfCriticalSectionToUse >::getUnchecked (const int index) const noexcept
Returns one of the elements in the set, without checking the index passed in.
Unlike the operator[] method, this will try to return an element without checking that the index is within the bounds of the set, so should only be used when you're confident that it will always be a valid index.
Parameters
index the index of the element being requested (0 is the first element in the set)
See Also
operator[], getFirst, getLast
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType& SortedSet< ElementType, TypeOfCriticalSectionToUse >::getReference (const int index) const noexcept
Returns a direct reference to one of the elements in the set, without checking the index passed in.
This is like getUnchecked, but returns a direct reference to the element, so that you can alter it directly. Obviously this can be dangerous, so only use it when absolutely necessary.
Parameters
index the index of the element being requested (0 is the first element in the array)
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType SortedSet< ElementType, TypeOfCriticalSectionToUse >::getFirst () const noexcept
Returns the first element in the set, or 0 if the set is empty.
See Also
operator[], getUnchecked, getLast
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType SortedSet< ElementType, TypeOfCriticalSectionToUse >::getLast () const noexcept
Returns the last element in the set, or 0 if the set is empty.
See Also
operator[], getUnchecked, getFirst
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType* SortedSet< ElementType, TypeOfCriticalSectionToUse >::begin () const noexcept
Returns a pointer to the first element in the set.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType* SortedSet< ElementType, TypeOfCriticalSectionToUse >::end () const noexcept
Returns a pointer to the element which follows the last element in the set.
This method is provided for compatibility with standard C++ iteration mechanisms.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> int SortedSet< ElementType, TypeOfCriticalSectionToUse >::indexOf (const ElementType & elementToLookFor) const noexcept
Finds the index of the first element which matches the value passed in.
This will search the set for the given object, and return the index of its first occurrence. If the object isn't found, the method will return -1.
Parameters
elementToLookFor the value or object to look for
Returns
the index of the object, or -1 if it's not found
Referenced by SortedSet< ColourSetting >::contains(), and SortedSet< ColourSetting >::removeValue().
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool SortedSet< ElementType, TypeOfCriticalSectionToUse >::contains (const ElementType & elementToLookFor) const noexcept
Returns true if the set contains at least one occurrence of an object.
Parameters
elementToLookFor the value or object to look for
Returns
true if the item is found
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> bool SortedSet< ElementType, TypeOfCriticalSectionToUse >::add (const ElementType & newElement) noexcept
Adds a new element to the set, (as long as it's not already in there).
Note that if a matching element already exists, the new value will be assigned to the existing one using operator=, so that if there are any differences between the objects which were not recognised by the object's operator==, then the set will always contain a copy of the most recently added one.
Parameters
newElement the new object to add to the set
Returns
true if the value was added, or false if it already existed
See Also
set, insert, addIfNotAlreadyThere, addSorted, addSet, addArray
Referenced by SortedSet< ColourSetting >::addArray(), and AudioUnitHelpers::getAUChannelInfo().
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> void SortedSet< ElementType, TypeOfCriticalSectionToUse >::addArray (const ElementType * elementsToAdd, int numElementsToAdd) noexcept
Adds elements from an array to this set.
Parameters
elementsToAdd the array of elements to add
numElementsToAdd how many elements are in this other array
See Also
add
Referenced by SortedSet< ColourSetting >::addSet().
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherSetType > void SortedSet< ElementType, TypeOfCriticalSectionToUse >::addSet (const OtherSetType & setToAddFrom, int startIndex = 0, int numElementsToAdd = -1) noexcept
Adds elements from another set to this one.
Parameters
setToAddFrom the set from which to copy the elements
startIndex the first element of the other set to start copying from
numElementsToAdd how many elements to add from the other set. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> ElementType SortedSet< ElementType, TypeOfCriticalSectionToUse >::remove (const int indexToRemove) noexcept
Removes an element from the set.
This will remove the element at a given index. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
Returns
the element that has been removed
See Also
removeValue, removeRange
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> void SortedSet< ElementType, TypeOfCriticalSectionToUse >::removeValue (const ElementType valueToRemove) noexcept
Removes an item from the set.
This will remove the given element from the set, if it's there.
Parameters
valueToRemove the object to try to remove
See Also
remove, removeRange
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherSetType > void SortedSet< ElementType, TypeOfCriticalSectionToUse >::removeValuesIn (const OtherSetType & otherSet) noexcept
Removes any elements which are also in another set.
Parameters
otherSet the other set in which to look for elements to remove
See Also
removeValuesNotIn, remove, removeValue, removeRange
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherSetType > void SortedSet< ElementType, TypeOfCriticalSectionToUse >::removeValuesNotIn (const OtherSetType & otherSet) noexcept
Removes any elements which are not found in another set.
Only elements which occur in this other set will be retained.
Parameters
otherSet the set in which to look for elements NOT to remove
See Also
removeValuesIn, remove, removeValue, removeRange
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> template<class OtherSetType > void SortedSet< ElementType, TypeOfCriticalSectionToUse >::swapWith (OtherSetType & otherSet) noexcept
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> void SortedSet< ElementType, TypeOfCriticalSectionToUse >::minimiseStorageOverheads () noexcept
Reduces the amount of storage being used by the set.
Sets typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> void SortedSet< ElementType, TypeOfCriticalSectionToUse >::ensureStorageAllocated (const int minNumElements)
Increases the set's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the set won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
template<class ElementType, class TypeOfCriticalSectionToUse = DummyCriticalSection> const TypeOfCriticalSectionToUse& SortedSet< ElementType, TypeOfCriticalSectionToUse >::getLock () const noexcept
Returns the CriticalSection that locks this array.
To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Referenced by SortedSet< ColourSetting >::add(), SortedSet< ColourSetting >::addArray(), SortedSet< ColourSetting >::addSet(), SortedSet< ColourSetting >::removeValue(), SortedSet< ColourSetting >::removeValuesIn(), and SortedSet< ColourSetting >::removeValuesNotIn().
class SparseSet
template<class Type>
class SparseSet< Type >
Holds a set of primitive values, storing them as a set of ranges.
This container acts like an array, but can efficiently hold large contiguous ranges of values. It's quite a specialised class, mostly useful for things like keeping the set of selected rows in a listbox.
The type used as a template parameter must be an integer type, such as int, short, int64, etc.
Public Member Functions
SparseSet ()
Creates a new empty set.
SparseSet (const SparseSet< Type > &other)
Creates a copy of another SparseSet.
void clear ()
Clears the set.
bool isEmpty () const noexcept
Checks whether the set is empty.
Type size () const
Returns the number of values in the set.
Type operator[] (Type index) const
Returns one of the values in the set.
bool contains (const Type valueToLookFor) const
Checks whether a particular value is in the set.
int getNumRanges () const noexcept
Returns the number of contiguous blocks of values.
const Range< Type > getRange (const int rangeIndex) const
Returns one of the contiguous ranges of values stored.
Range< Type > getTotalRange () const
Returns the range between the lowest and highest values in the set.
void addRange (const Range< Type > range)
Adds a range of contiguous values to the set.
void removeRange (const Range< Type > rangeToRemove)
Removes a range of values from the set.
void invertRange (const Range< Type > range)
Does an XOR of the values in a given range.
bool overlapsRange (const Range< Type > range)
Checks whether any part of a given range overlaps any part of this set.
bool containsRange (const Range< Type > range)
Checks whether the whole of a given range is contained within this one.
bool operator== (const SparseSet< Type > &other) noexcept
bool operator!= (const SparseSet< Type > &other) noexcept
Constructor & Destructor Documentation
template<class Type> SparseSet< Type >::SparseSet ()
Creates a new empty set.
template<class Type> SparseSet< Type >::SparseSet (const SparseSet< Type > & other)
Creates a copy of another SparseSet.
Member Function Documentation
template<class Type> void SparseSet< Type >::clear ()
Clears the set.
template<class Type> bool SparseSet< Type >::isEmpty () const noexcept
Checks whether the set is empty.
This is much quicker than using (size() == 0).
template<class Type> Type SparseSet< Type >::size () const
Returns the number of values in the set.
Because of the way the data is stored, this method can take longer if there are a lot of items in the set. Use isEmpty() for a quick test of whether there are any items.
template<class Type> Type SparseSet< Type >::operator[] (Type index) const
Returns one of the values in the set.
Parameters
index the index of the value to retrieve, in the range 0 to (size() - 1).
Returns
the value at this index, or 0 if it's out-of-range
template<class Type> bool SparseSet< Type >::contains (const Type valueToLookFor) const
Checks whether a particular value is in the set.
Referenced by SparseSet< int >::removeRange().
template<class Type> int SparseSet< Type >::getNumRanges () const noexcept
Returns the number of contiguous blocks of values.
See Also
getRange
Referenced by SparseSet< int >::containsRange(), SparseSet< int >::getRange(), SparseSet< int >::invertRange(), and SparseSet< int >::overlapsRange().
template<class Type> const Range<Type> SparseSet< Type >::getRange (const int rangeIndex) const
Returns one of the contiguous ranges of values stored.
Parameters
rangeIndex the index of the range to look up, between 0 and (getNumRanges() - 1)
See Also
getTotalRange
Referenced by SparseSet< int >::invertRange().
template<class Type> Range<Type> SparseSet< Type >::getTotalRange () const
Returns the range between the lowest and highest values in the set.
See Also
getRange
template<class Type> void SparseSet< Type >::addRange (const Range< Type > range)
Adds a range of contiguous values to the set.
e.g. addRange (Range <int> (10, 14)) will add (10, 11, 12, 13) to the set.
Referenced by SparseSet< int >::invertRange().
template<class Type> void SparseSet< Type >::removeRange (const Range< Type > rangeToRemove)
Removes a range of values from the set.
e.g. removeRange (Range<int> (10, 14)) will remove (10, 11, 12, 13) from the set.
Referenced by SparseSet< int >::addRange(), and SparseSet< int >::invertRange().
template<class Type> void SparseSet< Type >::invertRange (const Range< Type > range)
Does an XOR of the values in a given range.
template<class Type> bool SparseSet< Type >::overlapsRange (const Range< Type > range)
Checks whether any part of a given range overlaps any part of this set.
template<class Type> bool SparseSet< Type >::containsRange (const Range< Type > range)
Checks whether the whole of a given range is contained within this one.
template<class Type> bool SparseSet< Type >::operator== (const SparseSet< Type > & other) noexcept
template<class Type> bool SparseSet< Type >::operator!= (const SparseSet< Type > & other) noexcept
class var
A variant class, that can be used to hold a range of primitive values.
A var object can hold a range of simple primitive values, strings, or any kind of ReferenceCountedObject. The var class is intended to act like the kind of values used in dynamic scripting languages.
You can save/load var objects either in a small, proprietary binary format using writeToStream()/readFromStream(), or as JSON by using the JSON class.
See Also
JSON, DynamicObject
Public Types
using NativeFunction = std::function< var(const NativeFunctionArgs &)>
Public Member Functions
var () noexcept
Creates a void variant.
~var () noexcept
Destructor.
var (const var &valueToCopy)
var (int value) noexcept
var (int64 value) noexcept
var (bool value) noexcept
var (double value) noexcept
var (const char *value)
var (const wchar_t *value)
var (const String &value)
var (const Array< var > &value)
var (const StringArray &value)
var (ReferenceCountedObject *object)
var (NativeFunction method) noexcept
var (const void *binaryData, size_t dataSize)
var (const MemoryBlock &binaryData)
var & operator= (const var &valueToCopy)
var & operator= (int value)
var & operator= (int64 value)
var & operator= (bool value)
var & operator= (double value)
var & operator= (const char *value)
var & operator= (const wchar_t *value)
var & operator= (const String &value)
var & operator= (const MemoryBlock &value)
var & operator= (const Array< var > &value)
var & operator= (ReferenceCountedObject *object)
var & operator= (NativeFunction method)
var (var &&) noexcept
var (String &&)
var (MemoryBlock &&)
var (Array< var > &&)
var & operator= (var &&) noexcept
var & operator= (String &&)
void swapWith (var &other) noexcept
operator int () const noexcept
operator int64 () const noexcept
operator bool () const noexcept
operator float () const noexcept
operator double () const noexcept
operator String () const
String toString () const
Array< var > * getArray () const noexcept
If this variant holds an array, this provides access to it.
MemoryBlock * getBinaryData () const noexcept
If this variant holds a memory block, this provides access to it.
ReferenceCountedObject * getObject () const noexcept
DynamicObject * getDynamicObject () const noexcept
bool isVoid () const noexcept
bool isUndefined () const noexcept
bool isInt () const noexcept
bool isInt64 () const noexcept
bool isBool () const noexcept
bool isDouble () const noexcept
bool isString () const noexcept
bool isObject () const noexcept
bool isArray () const noexcept
bool isBinaryData () const noexcept
bool isMethod () const noexcept
bool equals (const var &other) const noexcept
Returns true if this var has the same value as the one supplied.
bool equalsWithSameType (const var &other) const noexcept
Returns true if this var has the same value and type as the one supplied.
bool hasSameTypeAs (const var &other) const noexcept
Returns true if this var has the same type as the one supplied.
var clone () const noexcept
Returns a deep copy of this object.
int size () const
If the var is an array, this returns the number of elements.
const var & operator[] (int arrayIndex) const
If the var is an array, this can be used to return one of its elements.
var & operator[] (int arrayIndex)
If the var is an array, this can be used to return one of its elements.
void append (const var &valueToAppend)
Appends an element to the var, converting it to an array if it isn't already one.
void insert (int index, const var &value)
Inserts an element to the var, converting it to an array if it isn't already one.
void remove (int index)
If the var is an array, this removes one of its elements.
void resize (int numArrayElementsWanted)
Treating the var as an array, this resizes it to contain the specified number of elements.
int indexOf (const var &value) const
If the var is an array, this searches it for the first occurrence of the specified value, and returns its index.
const var & operator[] (const Identifier &propertyName) const
If this variant is an object, this returns one of its properties.
const var & operator[] (const char *propertyName) const
If this variant is an object, this returns one of its properties.
var getProperty (const Identifier &propertyName, const var &defaultReturnValue) const
If this variant is an object, this returns one of its properties, or a default fallback value if the property is not set.
var call (const Identifier &method) const
Invokes a named method call with no arguments.
var call (const Identifier &method, const var &arg1) const
Invokes a named method call with one argument.
var call (const Identifier &method, const var &arg1, const var &arg2) const
Invokes a named method call with 2 arguments.
var call (const Identifier &method, const var &arg1, const var &arg2, const var &arg3)
Invokes a named method call with 3 arguments.
var call (const Identifier &method, const var &arg1, const var &arg2, const var &arg3, const var &arg4) const
Invokes a named method call with 4 arguments.
var call (const Identifier &method, const var &arg1, const var &arg2, const var &arg3, const var &arg4, const var &arg5) const
Invokes a named method call with 5 arguments.
var invoke (const Identifier &method, const var *arguments, int numArguments) const
Invokes a named method call with a list of arguments.
NativeFunction getNativeFunction () const
If this object is a method, this returns the function pointer.
void writeToStream (OutputStream &output) const
Writes a binary representation of this value to a stream.
Static Public Member Functions
static var undefined () noexcept
Returns a var object that can be used where you need the javascript "undefined" value.
static var readFromStream (InputStream &input)
Reads back a stored binary representation of a value.
Member Typedef Documentation
using var::NativeFunction = std::function<var (const NativeFunctionArgs&)>
Constructor & Destructor Documentation
var::var () noexcept
Creates a void variant.
var::~var () noexcept
Destructor.
var::var (const var & valueToCopy)
var::var (int value) noexcept
var::var (int64 value) noexcept
var::var (bool value) noexcept
var::var (double value) noexcept
var::var (const char * value)
var::var (const wchar_t * value)
var::var (const String & value)
var::var (const Array< var > & value)
var::var (const StringArray & value)
var::var (ReferenceCountedObject * object)
var::var (NativeFunction method) noexcept
var::var (const void * binaryData, size_t dataSize)
var::var (const MemoryBlock & binaryData)
var::var (var &&) noexcept
var::var (String &&)
var::var (MemoryBlock &&)
var::var (Array< var > &&)
Member Function Documentation
var& var::operator= (const var & valueToCopy)
var& var::operator= (int value)
var& var::operator= (int64 value)
var& var::operator= (bool value)
var& var::operator= (double value)
var& var::operator= (const char * value)
var& var::operator= (const wchar_t * value)
var& var::operator= (const String & value)
var& var::operator= (const MemoryBlock & value)
var& var::operator= (const Array< var > & value)
var& var::operator= (ReferenceCountedObject * object)
var& var::operator= (NativeFunction method)
var& var::operator= (var &&) noexcept
var& var::operator= (String &&)
void var::swapWith (var & other) noexcept
static var var::undefined () static noexcept
Returns a var object that can be used where you need the javascript "undefined" value.
var::operator int () const noexcept
var::operator int64 () const noexcept
var::operator bool () const noexcept
var::operator float () const noexcept
var::operator double () const noexcept
var::operator String () const
String var::toString () const
Referenced by VariantConverter< String >::fromVar().
Array<var>* var::getArray () const noexcept
If this variant holds an array, this provides access to it.
NOTE: Beware when you use this - the array pointer is only valid for the lifetime of the variant that returned it, so be very careful not to call this method on temporary var objects that are the return-value of a function, and which may go out of scope before you use the array!
MemoryBlock* var::getBinaryData () const noexcept
If this variant holds a memory block, this provides access to it.
NOTE: Beware when you use this - the MemoryBlock pointer is only valid for the lifetime of the variant that returned it, so be very careful not to call this method on temporary var objects that are the return-value of a function, and which may go out of scope before you use the MemoryBlock!
ReferenceCountedObject* var::getObject () const noexcept
DynamicObject* var::getDynamicObject () const noexcept
bool var::isVoid () const noexcept
bool var::isUndefined () const noexcept
bool var::isInt () const noexcept
bool var::isInt64 () const noexcept
bool var::isBool () const noexcept
bool var::isDouble () const noexcept
bool var::isString () const noexcept
bool var::isObject () const noexcept
bool var::isArray () const noexcept
bool var::isBinaryData () const noexcept
bool var::isMethod () const noexcept
bool var::equals (const var & other) const noexcept
Returns true if this var has the same value as the one supplied.
Note that this ignores the type, so a string var "123" and an integer var with the value 123 are considered to be equal.
See Also
equalsWithSameType
bool var::equalsWithSameType (const var & other) const noexcept
Returns true if this var has the same value and type as the one supplied.
This differs from equals() because e.g. "123" and 123 will be considered different.
See Also
equals
bool var::hasSameTypeAs (const var & other) const noexcept
Returns true if this var has the same type as the one supplied.
var var::clone () const noexcept
Returns a deep copy of this object.
For simple types this just returns a copy, but if the object contains any arrays or DynamicObjects, they will be cloned (recursively).
int var::size () const
If the var is an array, this returns the number of elements.
If the var isn't actually an array, this will return 0.
const var& var::operator[] (int arrayIndex) const
If the var is an array, this can be used to return one of its elements.
To call this method, you must make sure that the var is actually an array, and that the index is a valid number. If these conditions aren't met, behaviour is undefined. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
var& var::operator[] (int arrayIndex)
If the var is an array, this can be used to return one of its elements.
To call this method, you must make sure that the var is actually an array, and that the index is a valid number. If these conditions aren't met, behaviour is undefined. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
void var::append (const var & valueToAppend)
Appends an element to the var, converting it to an array if it isn't already one.
If the var isn't an array, it will be converted to one, and if its value was non-void, this value will be kept as the first element of the new array. The parameter value will then be appended to it. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
void var::insert (int index, const var & value)
Inserts an element to the var, converting it to an array if it isn't already one.
If the var isn't an array, it will be converted to one, and if its value was non-void, this value will be kept as the first element of the new array. The parameter value will then be inserted into it. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
void var::remove (int index)
If the var is an array, this removes one of its elements.
If the index is out-of-range or the var isn't an array, nothing will be done. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
void var::resize (int numArrayElementsWanted)
Treating the var as an array, this resizes it to contain the specified number of elements.
If the var isn't an array, it will be converted to one, and if its value was non-void, this value will be kept as the first element of the new array before resizing. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
int var::indexOf (const var & value) const
If the var is an array, this searches it for the first occurrence of the specified value, and returns its index.
If the var isn't an array, or if the value isn't found, this returns -1.
const var& var::operator[] (const Identifier & propertyName) const
If this variant is an object, this returns one of its properties.
const var& var::operator[] (const char * propertyName) const
If this variant is an object, this returns one of its properties.
var var::getProperty (const Identifier & propertyName, const var & defaultReturnValue) const
If this variant is an object, this returns one of its properties, or a default fallback value if the property is not set.
var var::call (const Identifier & method) const
Invokes a named method call with no arguments.
var var::call (const Identifier & method, const var & arg1) const
Invokes a named method call with one argument.
var var::call (const Identifier & method, const var & arg1, const var & arg2) const
Invokes a named method call with 2 arguments.
var var::call (const Identifier & method, const var & arg1, const var & arg2, const var & arg3)
Invokes a named method call with 3 arguments.
var var::call (const Identifier & method, const var & arg1, const var & arg2, const var & arg3, const var & arg4) const
Invokes a named method call with 4 arguments.
var var::call (const Identifier & method, const var & arg1, const var & arg2, const var & arg3, const var & arg4, const var & arg5) const
Invokes a named method call with 5 arguments.
var var::invoke (const Identifier & method, const var * arguments, int numArguments) const
Invokes a named method call with a list of arguments.
NativeFunction var::getNativeFunction () const
If this object is a method, this returns the function pointer.
void var::writeToStream (OutputStream & output) const
Writes a binary representation of this value to a stream.
The data can be read back later using readFromStream().
See Also
JSON
static var var::readFromStream (InputStream & input) static
Reads back a stored binary representation of a value.
The data in the stream must have been written using writeToStream(), or this will have unpredictable results.
See Also
JSON
struct VariantConverter
template<typename Type>
struct VariantConverter< Type >
This template-overloaded class can be used to convert between var and custom types.
Static Public Member Functions
static Type fromVar (const var &v)
static var toVar (const Type &t)
Member Function Documentation
template<typename Type > static Type VariantConverter< Type >::fromVar (const var & v) static
template<typename Type > static var VariantConverter< Type >::toVar (const Type & t) static
struct VariantConverter< String >
template<>
struct VariantConverter< String >
This template-overloaded class can be used to convert between var and custom types.
Static Public Member Functions
static String fromVar (const var &v)
static var toVar (const String &s)
Member Function Documentation
static String VariantConverter< String >::fromVar (const var & v) static
References var::toString().
static var VariantConverter< String >::toVar (const String & s) static
Function Documentation
JUCE_API bool operator== (const var & , const var &) noexcept
Compares the values of two var objects, using the var::equals() comparison.
Referenced by NamedValueSet::NamedValue::operator!=().
JUCE_API bool operator!= (const var & , const var &) noexcept
Compares the values of two var objects, using the var::equals() comparison.
JUCE_API bool operator== (const var & , const String &)
JUCE_API bool operator!= (const var & , const String &)
JUCE_API bool operator== (const var & , const char *)
JUCE_API bool operator!= (const var & , const char *)