JUCE: misc
misc
juce_core
Classes
class Result
Represents the 'success' or 'failure' of an operation, and holds an associated error message to describe the error when there's a failure.
class RuntimePermissions
Class to handle app runtime permissions for certain functionality on some platforms.
class std::function< typename >
This class provides an alternative to std::function that is compatible with OS X 10.6 and earlier.
class std::function< Result(Arguments...)>
class Uuid
A universally unique 128-bit identifier.
class WindowsRegistry
Contains some static helper functions for manipulating the MS Windows registry (Only available on Windows, of course!)
Detailed Description
Class Documentation
class Result
Represents the 'success' or 'failure' of an operation, and holds an associated error message to describe the error when there's a failure.
E.g.
Result myOperation()
{
    if (doSomeKindOfFoobar())
        return Result::ok();
    else
        return Result::fail ("foobar didn't work!");
}
const Result result (myOperation());
if (result.wasOk())
{
    ...it's all good...
}
else
{
    warnUserAboutFailure ("The foobar operation failed! Error message was: "
                            + result.getErrorMessage());
}
Public Member Functions
bool wasOk () const noexcept
Returns true if this result indicates a success.
bool failed () const noexcept
Returns true if this result indicates a failure.
operator bool () const noexcept
Returns true if this result indicates a success.
bool operator! () const noexcept
Returns true if this result indicates a failure.
const String & getErrorMessage () const noexcept
Returns the error message that was set when this result was created.
Result (const Result &)
Result & operator= (const Result &)
Result (Result &&) noexcept
Result & operator= (Result &&) noexcept
bool operator== (const Result &other) const noexcept
bool operator!= (const Result &other) const noexcept
Static Public Member Functions
static Result ok () noexcept
Creates and returns a 'successful' result.
static Result fail (const String &errorMessage) noexcept
Creates a 'failure' result.
Constructor & Destructor Documentation
Result::Result (const Result &)
Result::Result (Result &&) noexcept
Member Function Documentation
static Result Result::ok () static noexcept
Creates and returns a 'successful' result.
Referenced by littlefoot::Compiler::compile().
static Result Result::fail (const String & errorMessage) static noexcept
Creates a 'failure' result.
If you pass a blank error message in here, a default "Unknown Error" message will be used instead.
Referenced by littlefoot::Compiler::compile().
bool Result::wasOk () const noexcept
Returns true if this result indicates a success.
bool Result::failed () const noexcept
Returns true if this result indicates a failure.
You can use getErrorMessage() to retrieve the error message associated with the failure.
Result::operator bool () const noexcept
Returns true if this result indicates a success.
This is equivalent to calling wasOk().
bool Result::operator! () const noexcept
Returns true if this result indicates a failure.
This is equivalent to calling failed().
const String& Result::getErrorMessage () const noexcept
Returns the error message that was set when this result was created.
For a successful result, this will be an empty string;
Result& Result::operator= (const Result &)
Result& Result::operator= (Result &&) noexcept
bool Result::operator== (const Result & other) const noexcept
bool Result::operator!= (const Result & other) const noexcept
class RuntimePermissions
Class to handle app runtime permissions for certain functionality on some platforms.
The use of this class is currently only required if the app should run on Android API level 23 and higher.
On lower API levels, the permissions are specified in the app manifest. On iOS, runtime permission requests are handled automatically by the Apple APIs and not manually in the app code. On Windows, OS X, and Linux, runtime permissions are not used at all. In all these cases, request() will simply call through to the callback with no overhead and pass true (making it safe to use on all platforms).
For example, to enable audio recording on Android in your cross-platform app, you could modify your code as follows:
Old code:
audioDeviceManager.initialise (2, 2, nullptr, true, String(), nullptr);
New code:
RuntimePermissions::request (
    RuntimePermissions::audioRecording,
    [this] (bool wasGranted)
    {
         if (! wasGranted)
         {
e.g. display an error or initialise with 0 input channels return; }
audioDeviceManager.initialise (2, 2, nullptr, true, String(), nullptr); });
Public Types
enum PermissionID { recordAudio = 1, bluetoothMidi = 2, readExternalStorage = 3, writeExternalStorage = 4 }
typedef std::function< void(bool)> Callback
Function type of runtime permission request callbacks.
Static Public Member Functions
static void request (PermissionID permission, Callback callback)
Call this method to request a runtime permission.
static bool isRequired (PermissionID permission)
Returns whether a runtime request is required to obtain the permission on the current platform.
static bool isGranted (PermissionID permission)
Returns true if the app has been already granted this permission, either via a previous runtime request or otherwise, or no permission is necessary.
Member Typedef Documentation
typedef std::function<void (bool)> RuntimePermissions::Callback
Function type of runtime permission request callbacks.
Member Enumeration Documentation
enum RuntimePermissions::PermissionID
Enumerator
recordAudio
Permission to access the microphone (required on Android).
You need to request this, for example, to initialise an AudioDeviceManager with a non-zero number of input channels, and to open the default audio input device.
bluetoothMidi
Permission to scan for and pair to Bluetooth MIDI devices (required on Android).
You need to request this before calling BluetoothMidiDevicePairingDialogue::open(), otherwise no devices will be found.
readExternalStorage
Permission to read from external storage such as SD cards.
writeExternalStorage
Permission to write to external storage such as SD cards.
Member Function Documentation
static void RuntimePermissions::request (PermissionID permission, Callback callback) static
Call this method to request a runtime permission.
Parameters
permission The PermissionID of the permission you want to request.
callback The callback to be called after the request has been granted or denied; the argument passed will be true if the permission has been granted and false otherwise.
If no runtime request is required or possible to obtain the permission, the callback will be called immediately. The argument passed in will be true if the permission is granted or no permission is required on this platform, and false otherwise.
If a runtime request is required to obtain the permission, the callback will be called asynchronously after the OS has granted or denied the requested permission (typically by displaying a dialog box to the user and waiting until the user has responded).
Referenced by StandalonePluginHolder::StandalonePluginHolder().
static bool RuntimePermissions::isRequired (PermissionID permission) static
Returns whether a runtime request is required to obtain the permission on the current platform.
Referenced by StandalonePluginHolder::StandalonePluginHolder().
static bool RuntimePermissions::isGranted (PermissionID permission) static
Returns true if the app has been already granted this permission, either via a previous runtime request or otherwise, or no permission is necessary.
Note that this can be false even if isRequired returns false. In this case, the permission can not be obtained at all at runtime.
Referenced by StandalonePluginHolder::StandalonePluginHolder().
class std::function
template<typename>
class std::function< typename >
This class provides an alternative to std::function that is compatible with OS X 10.6 and earlier.
This will only be used in OS X versions 10.6 and earlier and the Projucer live build.
class std::function< Result(Arguments...)>
template<typename Result, typename... Arguments>
class std::function< Result(Arguments...)>
Public Member Functions
function () noexcept
Creates an empty function.
function (decltype(nullptr)) noexcept
Creates an empty function.
template<typename Functor >
function (Functor f)
Creates a function targetting the provided Functor.
function (function const &other)
Copy constructor.
function (function &&other)
Move constructor.
~function ()
Destructor.
function & operator= (function const &other)
Replaces the contents of this function with the contents of another.
function & operator= (function &&other)
Moves the contents of another function into this one.
operator bool () const noexcept
Allows conditional expressions to test if this function is empty.
void swap (function &other)
Swaps the contents of this function with another.
Result operator() (Arguments...args) const
Invokes the target of this function.
bool operator== (decltype(nullptr)) const noexcept
bool operator!= (decltype(nullptr)) const noexcept
Constructor & Destructor Documentation
template<typename Result , typename... Arguments> std::function< Result(Arguments...)>::function () noexcept
Creates an empty function.
template<typename Result , typename... Arguments> std::function< Result(Arguments...)>::function (decltype(nullptr)) noexcept
Creates an empty function.
template<typename Result , typename... Arguments> template<typename Functor > std::function< Result(Arguments...)>::function (Functor f)
Creates a function targetting the provided Functor.
template<typename Result , typename... Arguments> std::function< Result(Arguments...)>::function (function< Result(Arguments...)> const & other)
Copy constructor.
References StandardApplicationCommandIDs::copy.
template<typename Result , typename... Arguments> std::function< Result(Arguments...)>::function (function< Result(Arguments...)> && other)
Move constructor.
template<typename Result , typename... Arguments> std::function< Result(Arguments...)>::~function ()
Destructor.
Member Function Documentation
template<typename Result , typename... Arguments> function& std::function< Result(Arguments...)>::operator= (function< Result(Arguments...)> const & other)
Replaces the contents of this function with the contents of another.
References StandardApplicationCommandIDs::copy.
template<typename Result , typename... Arguments> function& std::function< Result(Arguments...)>::operator= (function< Result(Arguments...)> && other)
Moves the contents of another function into this one.
template<typename Result , typename... Arguments> std::function< Result(Arguments...)>::operator bool () const explicit noexcept
Allows conditional expressions to test if this function is empty.
template<typename Result , typename... Arguments> void std::function< Result(Arguments...)>::swap (function< Result(Arguments...)> & other)
Swaps the contents of this function with another.
After this operation the two functions will be pointing at each other's targets.
template<typename Result , typename... Arguments> Result std::function< Result(Arguments...)>::operator() (Arguments... args) const
Invokes the target of this function.
template<typename Result , typename... Arguments> bool std::function< Result(Arguments...)>::operator== (decltype(nullptr)) const noexcept
template<typename Result , typename... Arguments> bool std::function< Result(Arguments...)>::operator!= (decltype(nullptr)) const noexcept
class Uuid
A universally unique 128-bit identifier.
This class generates very random unique numbers. It's vanishingly unlikely that two identical UUIDs would ever be created by chance. The values are formatted to meet the RFC 4122 version 4 standard.
The class includes methods for saving the ID as a string or as raw binary data.
Public Member Functions
Uuid ()
Creates a new unique ID, compliant with RFC 4122 version 4.
~Uuid () noexcept
Destructor.
Uuid (const Uuid &) noexcept
Creates a copy of another UUID.
Uuid & operator= (const Uuid &) noexcept
Copies another UUID.
bool isNull () const noexcept
Returns true if the ID is zero.
bool operator== (const Uuid &) const noexcept
bool operator!= (const Uuid &) const noexcept
bool operator< (const Uuid &) const noexcept
bool operator> (const Uuid &) const noexcept
bool operator<= (const Uuid &) const noexcept
bool operator>= (const Uuid &) const noexcept
String toString () const
Returns a stringified version of this UUID.
String toDashedString () const
Returns a stringified version of this UUID, separating it into sections with dashes.
Uuid (const String &uuidString)
Creates an ID from an encoded string version.
Uuid & operator= (const String &uuidString)
Copies from a stringified UUID.
uint32 getTimeLow () const noexcept
Returns the time-low section of the UUID.
uint16 getTimeMid () const noexcept
Returns the time-mid section of the UUID.
uint16 getTimeHighAndVersion () const noexcept
Returns the time-high-and-version section of the UUID.
uint8 getClockSeqAndReserved () const noexcept
Returns the clock-seq-and-reserved section of the UUID.
uint8 getClockSeqLow () const noexcept
Returns the clock-seq-low section of the UUID.
uint64 getNode () const noexcept
Returns the node section of the UUID.
const uint8 * getRawData () const noexcept
Returns a pointer to the internal binary representation of the ID.
Uuid (const uint8 *rawData) noexcept
Creates a UUID from a 16-byte array.
Uuid & operator= (const uint8 *rawData) noexcept
Sets this UUID from 16-bytes of raw data.
Static Public Member Functions
static Uuid null () noexcept
Returns a null Uuid object.
Constructor & Destructor Documentation
Uuid::Uuid ()
Creates a new unique ID, compliant with RFC 4122 version 4.
Uuid::~Uuid () noexcept
Destructor.
Uuid::Uuid (const Uuid &) noexcept
Creates a copy of another UUID.
Uuid::Uuid (const String & uuidString)
Creates an ID from an encoded string version.
See Also
toString
Uuid::Uuid (const uint8 * rawData) noexcept
Creates a UUID from a 16-byte array.
See Also
getRawData
Member Function Documentation
Uuid& Uuid::operator= (const Uuid &) noexcept
Copies another UUID.
bool Uuid::isNull () const noexcept
Returns true if the ID is zero.
static Uuid Uuid::null () static noexcept
Returns a null Uuid object.
bool Uuid::operator== (const Uuid &) const noexcept
bool Uuid::operator!= (const Uuid &) const noexcept
bool Uuid::operator< (const Uuid &) const noexcept
bool Uuid::operator> (const Uuid &) const noexcept
bool Uuid::operator<= (const Uuid &) const noexcept
bool Uuid::operator>= (const Uuid &) const noexcept
String Uuid::toString () const
Returns a stringified version of this UUID.
A Uuid object can later be reconstructed from this string using operator= or the constructor that takes a string parameter.
Returns
a 32 character hex string.
String Uuid::toDashedString () const
Returns a stringified version of this UUID, separating it into sections with dashes.
Returns
a string in the format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Uuid& Uuid::operator= (const String & uuidString)
Copies from a stringified UUID.
The string passed in should be one that was created with the toString() method.
uint32 Uuid::getTimeLow () const noexcept
Returns the time-low section of the UUID.
uint16 Uuid::getTimeMid () const noexcept
Returns the time-mid section of the UUID.
uint16 Uuid::getTimeHighAndVersion () const noexcept
Returns the time-high-and-version section of the UUID.
uint8 Uuid::getClockSeqAndReserved () const noexcept
Returns the clock-seq-and-reserved section of the UUID.
uint8 Uuid::getClockSeqLow () const noexcept
Returns the clock-seq-low section of the UUID.
uint64 Uuid::getNode () const noexcept
Returns the node section of the UUID.
const uint8* Uuid::getRawData () const noexcept
Returns a pointer to the internal binary representation of the ID.
This is an array of 16 bytes. To reconstruct a Uuid from its data, use the constructor or operator= method that takes an array of uint8s.
Uuid& Uuid::operator= (const uint8 * rawData) noexcept
Sets this UUID from 16-bytes of raw data.
class WindowsRegistry
Contains some static helper functions for manipulating the MS Windows registry (Only available on Windows, of course!)
Public Types
enum WoW64Mode { WoW64_Default = 0, WoW64_64bit = 0x100, WoW64_32bit = 0x200 }
These values can be used to specify whether the 32- or 64-bit registry should be used.
Public Member Functions
JUCE_DEPRECATED (static String getValueWow64(const String &, const String &defaultValue=String()))
JUCE_DEPRECATED (static bool valueExistsWow64(const String &))
JUCE_DEPRECATED (static bool keyExistsWow64(const String &))
Static Public Member Functions
static String JUCE_CALLTYPE getValue (const String &regValuePath, const String &defaultValue=String(), WoW64Mode mode=WoW64_Default)
Returns a string from the registry.
static uint32 JUCE_CALLTYPE getBinaryValue (const String &regValuePath, MemoryBlock &resultData, WoW64Mode mode=WoW64_Default)
Reads a binary block from the registry.
static bool JUCE_CALLTYPE setValue (const String &regValuePath, const String &value, WoW64Mode mode=WoW64_Default)
Sets a registry value as a string.
static bool JUCE_CALLTYPE setValue (const String &regValuePath, uint32 value, WoW64Mode mode=WoW64_Default)
Sets a registry value as a DWORD.
static bool JUCE_CALLTYPE setValue (const String &regValuePath, uint64 value, WoW64Mode mode=WoW64_Default)
Sets a registry value as a QWORD.
static bool JUCE_CALLTYPE setValue (const String &regValuePath, const MemoryBlock &value, WoW64Mode mode=WoW64_Default)
Sets a registry value as a binary block.
static bool JUCE_CALLTYPE valueExists (const String &regValuePath, WoW64Mode mode=WoW64_Default)
Returns true if the given value exists in the registry.
static bool JUCE_CALLTYPE keyExists (const String &regValuePath, WoW64Mode mode=WoW64_Default)
Returns true if the given key exists in the registry.
static bool JUCE_CALLTYPE deleteValue (const String &regValuePath, WoW64Mode mode=WoW64_Default)
Deletes a registry value.
static bool JUCE_CALLTYPE deleteKey (const String &regKeyPath, WoW64Mode mode=WoW64_Default)
Deletes a registry key (which is registry-talk for 'folder').
static bool JUCE_CALLTYPE registerFileAssociation (const String &fileExtension, const String &symbolicDescription, const String &fullDescription, const File &targetExecutable, int iconResourceNumber, bool registerForCurrentUserOnly, WoW64Mode mode=WoW64_Default)
Creates a file association in the registry.
Member Enumeration Documentation
enum WindowsRegistry::WoW64Mode
These values can be used to specify whether the 32- or 64-bit registry should be used.
When running on a 32-bit OS, there is no 64-bit registry, so the mode will be ignored.
Enumerator
WoW64_Default
Default handling: 32-bit apps will use the 32-bit registry, and 64-bit apps will use the 64-bit registry.
WoW64_64bit
Always use the 64-bit registry store.
(KEY_WOW64_64KEY).
WoW64_32bit
Always use the 32-bit registry store.
(KEY_WOW64_32KEY).
Member Function Documentation
static String JUCE_CALLTYPE WindowsRegistry::getValue (const String & regValuePath, const String & defaultValue = String(), WoW64Mode mode = WoW64_Default) static
Returns a string from the registry.
The path is a string for the entire path of a value in the registry, e.g. "HKEY_CURRENT_USER\Software\foo\bar"
static uint32 JUCE_CALLTYPE WindowsRegistry::getBinaryValue (const String & regValuePath, MemoryBlock & resultData, WoW64Mode mode = WoW64_Default) static
Reads a binary block from the registry.
The path is a string for the entire path of a value in the registry, e.g. "HKEY_CURRENT_USER\Software\foo\bar"
Returns
a DWORD indicating the type of the key.
static bool JUCE_CALLTYPE WindowsRegistry::setValue (const String & regValuePath, const String & value, WoW64Mode mode = WoW64_Default) static
Sets a registry value as a string.
This will take care of creating any groups needed to get to the given registry value.
static bool JUCE_CALLTYPE WindowsRegistry::setValue (const String & regValuePath, uint32 value, WoW64Mode mode = WoW64_Default) static
Sets a registry value as a DWORD.
This will take care of creating any groups needed to get to the given registry value.
static bool JUCE_CALLTYPE WindowsRegistry::setValue (const String & regValuePath, uint64 value, WoW64Mode mode = WoW64_Default) static
Sets a registry value as a QWORD.
This will take care of creating any groups needed to get to the given registry value.
static bool JUCE_CALLTYPE WindowsRegistry::setValue (const String & regValuePath, const MemoryBlock & value, WoW64Mode mode = WoW64_Default) static
Sets a registry value as a binary block.
This will take care of creating any groups needed to get to the given registry value.
static bool JUCE_CALLTYPE WindowsRegistry::valueExists (const String & regValuePath, WoW64Mode mode = WoW64_Default) static
Returns true if the given value exists in the registry.
static bool JUCE_CALLTYPE WindowsRegistry::keyExists (const String & regValuePath, WoW64Mode mode = WoW64_Default) static
Returns true if the given key exists in the registry.
static bool JUCE_CALLTYPE WindowsRegistry::deleteValue (const String & regValuePath, WoW64Mode mode = WoW64_Default) static
Deletes a registry value.
static bool JUCE_CALLTYPE WindowsRegistry::deleteKey (const String & regKeyPath, WoW64Mode mode = WoW64_Default) static
Deletes a registry key (which is registry-talk for 'folder').
static bool JUCE_CALLTYPE WindowsRegistry::registerFileAssociation (const String & fileExtension, const String & symbolicDescription, const String & fullDescription, const File & targetExecutable, int iconResourceNumber, bool registerForCurrentUserOnly, WoW64Mode mode = WoW64_Default) static
Creates a file association in the registry.
This lets you set the executable that should be launched by a given file extension.
Parameters
fileExtension the file extension to associate, including the initial dot, e.g. ".txt"
symbolicDescription a space-free short token to identify the file type
fullDescription a human-readable description of the file type
targetExecutable the executable that should be launched
iconResourceNumber the icon that gets displayed for the file type will be found by looking up this resource number in the executable. Pass 0 here to not use an icon
registerForCurrentUserOnly if false, this will try to register the association for all users (you might not have permission to do this unless running in an installer). If true, it will register the association in HKEY_CURRENT_USER.
mode the WoW64 mode to use for choosing the database
WindowsRegistry::JUCE_DEPRECATED (static String getValueWow64const String &, const String &defaultValue=String())
WindowsRegistry::JUCE_DEPRECATED (static bool valueExistsWow64const String &)
WindowsRegistry::JUCE_DEPRECATED (static bool keyExistsWow64const String &)