JUCE: code_editor
code_editor
juce_gui_extra
Classes
class CodeDocument
A class for storing and manipulating a source code file.
class CodeEditorComponent
A text editor component designed specifically for source code.
class CodeTokeniser
A base class for tokenising code so that the syntax can be displayed in a code editor.
class CPlusPlusCodeTokeniser
A simple lexical analyser for syntax colouring of C++ code.
struct CppTokeniserFunctions
Class containing some basic functions for simple tokenising of C++ code.
class LuaTokeniser
class XmlTokeniser
Detailed Description
Class Documentation
class CodeDocument
A class for storing and manipulating a source code file.
When using a CodeEditorComponent, it takes one of these as its source object.
The CodeDocument stores its content as an array of lines, which makes it quick to insert and delete.
See Also
CodeEditorComponent
Public Member Functions
CodeDocument ()
Creates a new, empty document.
~CodeDocument ()
Destructor.
String getAllContent () const
Returns the full text of the document.
String getTextBetween (const Position &start, const Position &end) const
Returns a section of the document's text.
String getLine (int lineIndex) const noexcept
Returns a line from the document.
int getNumCharacters () const noexcept
Returns the number of characters in the document.
int getNumLines () const noexcept
Returns the number of lines in the document.
int getMaximumLineLength () noexcept
Returns the number of characters in the longest line of the document.
void deleteSection (const Position &startPosition, const Position &endPosition)
Deletes a section of the text.
void deleteSection (int startIndex, int endIndex)
Deletes a section of the text.
void insertText (const Position &position, const String &text)
Inserts some text into the document at a given position.
void insertText (int insertIndex, const String &text)
Inserts some text into the document at a given position.
void replaceSection (int startIndex, int endIndex, const String &newText)
Replaces a section of the text with a new string.
void replaceAllContent (const String &newContent)
Clears the document and replaces it with some new text.
void applyChanges (const String &newContent)
Analyses the changes between the current content and some new text, and applies those changes.
bool loadFromStream (InputStream &stream)
Replaces the editor's contents with the contents of a stream.
bool writeToStream (OutputStream &stream)
Writes the editor's current contents to a stream.
String getNewLineCharacters () const noexcept
Returns the preferred new-line characters for the document.
void setNewLineCharacters (const String &newLineCharacters) noexcept
Sets the new-line characters that the document should use.
void newTransaction ()
Begins a new undo transaction.
void undo ()
Undo the last operation.
void redo ()
Redo the last operation.
void clearUndoHistory ()
Clears the undo history.
UndoManager & getUndoManager () noexcept
Returns the document's UndoManager.
void setSavePoint () noexcept
Makes a note that the document's current state matches the one that is saved.
bool hasChangedSinceSavePoint () const noexcept
Returns true if the state of the document differs from the state it was in when setSavePoint() was last called.
Position findWordBreakAfter (const Position &position) const noexcept
Searches for a word-break.
Position findWordBreakBefore (const Position &position) const noexcept
Searches for a word-break.
void findTokenContaining (const Position &pos, Position &start, Position &end) const noexcept
Finds the token that contains the given position.
void findLineContaining (const Position &pos, Position &start, Position &end) const noexcept
Finds the line that contains the given position.
void addListener (Listener *listener) noexcept
Registers a listener object to receive callbacks when the document changes.
void removeListener (Listener *listener) noexcept
Deregisters a listener.
Constructor & Destructor Documentation
CodeDocument::CodeDocument ()
Creates a new, empty document.
CodeDocument::~CodeDocument ()
Destructor.
Member Function Documentation
String CodeDocument::getAllContent () const
Returns the full text of the document.
String CodeDocument::getTextBetween (const Position & start, const Position & end) const
Returns a section of the document's text.
String CodeDocument::getLine (int lineIndex) const noexcept
Returns a line from the document.
int CodeDocument::getNumCharacters () const noexcept
Returns the number of characters in the document.
int CodeDocument::getNumLines () const noexcept
Returns the number of lines in the document.
int CodeDocument::getMaximumLineLength () noexcept
Returns the number of characters in the longest line of the document.
void CodeDocument::deleteSection (const Position & startPosition, const Position & endPosition)
Deletes a section of the text.
This operation is undoable.
void CodeDocument::deleteSection (int startIndex, int endIndex)
Deletes a section of the text.
This operation is undoable.
void CodeDocument::insertText (const Position & position, const String & text)
Inserts some text into the document at a given position.
This operation is undoable.
void CodeDocument::insertText (int insertIndex, const String & text)
Inserts some text into the document at a given position.
This operation is undoable.
void CodeDocument::replaceSection (int startIndex, int endIndex, const String & newText)
Replaces a section of the text with a new string.
This operation is undoable.
void CodeDocument::replaceAllContent (const String & newContent)
Clears the document and replaces it with some new text.
This operation is undoable - if you're trying to completely reset the document, you might want to also call clearUndoHistory() and setSavePoint() after using this method.
void CodeDocument::applyChanges (const String & newContent)
Analyses the changes between the current content and some new text, and applies those changes.
bool CodeDocument::loadFromStream (InputStream & stream)
Replaces the editor's contents with the contents of a stream.
This will also reset the undo history and save point marker.
bool CodeDocument::writeToStream (OutputStream & stream)
Writes the editor's current contents to a stream.
String CodeDocument::getNewLineCharacters () const noexcept
Returns the preferred new-line characters for the document.
This will be either "\n", "\r\n", or (rarely) "\r".
See Also
setNewLineCharacters
void CodeDocument::setNewLineCharacters (const String & newLineCharacters) noexcept
Sets the new-line characters that the document should use.
The string must be either "\n", "\r\n", or (rarely) "\r".
See Also
getNewLineCharacters
void CodeDocument::newTransaction ()
Begins a new undo transaction.
The document itself will not call this internally, so relies on whatever is using the document to periodically call this to break up the undo sequence into sensible chunks.
See Also
UndoManager::beginNewTransaction
void CodeDocument::undo ()
Undo the last operation.
See Also
UndoManager::undo
void CodeDocument::redo ()
Redo the last operation.
See Also
UndoManager::redo
void CodeDocument::clearUndoHistory ()
Clears the undo history.
See Also
UndoManager::clearUndoHistory
UndoManager& CodeDocument::getUndoManager () noexcept
Returns the document's UndoManager.
void CodeDocument::setSavePoint () noexcept
Makes a note that the document's current state matches the one that is saved.
After this has been called, hasChangedSinceSavePoint() will return false until the document has been altered, and then it'll start returning true. If the document is altered, but then undone until it gets back to this state, hasChangedSinceSavePoint() will again return false.
See Also
hasChangedSinceSavePoint
bool CodeDocument::hasChangedSinceSavePoint () const noexcept
Returns true if the state of the document differs from the state it was in when setSavePoint() was last called.
See Also
setSavePoint
Position CodeDocument::findWordBreakAfter (const Position & position) const noexcept
Searches for a word-break.
Position CodeDocument::findWordBreakBefore (const Position & position) const noexcept
Searches for a word-break.
void CodeDocument::findTokenContaining (const Position & pos, Position & start, Position & end) const noexcept
Finds the token that contains the given position.
void CodeDocument::findLineContaining (const Position & pos, Position & start, Position & end) const noexcept
Finds the line that contains the given position.
void CodeDocument::addListener (Listener * listener) noexcept
Registers a listener object to receive callbacks when the document changes.
If the listener is already registered, this method has no effect.
See Also
removeListener
void CodeDocument::removeListener (Listener * listener) noexcept
Deregisters a listener.
See Also
addListener
class CodeEditorComponent
A text editor component designed specifically for source code.
This is designed to handle syntax highlighting and fast editing of very large files.
Public Types
enum ColourIds {
backgroundColourId = 0x1004500, highlightColourId = 0x1004502, defaultTextColourId = 0x1004503, lineNumberBackgroundId = 0x1004504,
lineNumberTextId = 0x1004505
}
A set of colour IDs to use to change the colour of various aspects of the editor.
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusChanged() and focusLost() methods.
Public Types inherited from TextInputTarget
enum VirtualKeyboardType {
textKeyboard = 0, numericKeyboard, decimalKeyboard, urlKeyboard,
emailAddressKeyboard, phoneNumberKeyboard
}
A set of possible on-screen keyboard types, for use in the getKeyboardType() method.
Public Member Functions
CodeEditorComponent (CodeDocument &document, CodeTokeniser *codeTokeniser)
Creates an editor for a document.
~CodeEditorComponent ()
Destructor.
CodeDocument & getDocument () const noexcept
Returns the code document that this component is editing.
void loadContent (const String &newContent)
Loads the given content into the document.
float getCharWidth () const noexcept
Returns the standard character width.
int getLineHeight () const noexcept
Returns the height of a line of text, in pixels.
int getNumLinesOnScreen () const noexcept
Returns the number of whole lines visible on the screen, This doesn't include a cut-off line that might be visible at the bottom if the component's height isn't an exact multiple of the line-height.
int getFirstLineOnScreen () const noexcept
Returns the index of the first line that's visible at the top of the editor.
int getNumColumnsOnScreen () const noexcept
Returns the number of whole columns visible on the screen.
CodeDocument::Position getCaretPos () const
Returns the current caret position.
Rectangle< int > getCaretRectangle () override
Returns the position of the caret, relative to the editor's origin.
void moveCaretTo (const CodeDocument::Position &newPos, bool selecting)
Moves the caret.
Rectangle< int > getCharacterBounds (const CodeDocument::Position &pos) const
Returns the on-screen position of a character in the document.
CodeDocument::Position getPositionAt (int x, int y)
Finds the character at a given on-screen position.
CodeDocument::Position getSelectionStart () const
Returns the start of the selection as a position.
CodeDocument::Position getSelectionEnd () const
Returns the end of the selection as a position.
void setLineNumbersShown (bool shouldBeShown)
Enables or disables the line-number display in the gutter.
bool moveCaretLeft (bool moveInWholeWordSteps, bool selecting)
bool moveCaretRight (bool moveInWholeWordSteps, bool selecting)
bool moveCaretUp (bool selecting)
bool moveCaretDown (bool selecting)
bool scrollDown ()
bool scrollUp ()
bool pageUp (bool selecting)
bool pageDown (bool selecting)
bool moveCaretToTop (bool selecting)
bool moveCaretToStartOfLine (bool selecting)
bool moveCaretToEnd (bool selecting)
bool moveCaretToEndOfLine (bool selecting)
bool deleteBackwards (bool moveInWholeWordSteps)
bool deleteForwards (bool moveInWholeWordSteps)
bool deleteWhitespaceBackwardsToTabStop ()
virtual bool copyToClipboard ()
virtual bool cutToClipboard ()
virtual bool pasteFromClipboard ()
bool undo ()
bool redo ()
void selectRegion (const CodeDocument::Position &start, const CodeDocument::Position &end)
bool selectAll ()
void deselectAll ()
void scrollToLine (int newFirstLineOnScreen)
void scrollBy (int deltaLines)
void scrollToColumn (int newFirstColumnOnScreen)
void scrollToKeepCaretOnScreen ()
void scrollToKeepLinesOnScreen (Range< int > linesToShow)
void insertTextAtCaret (const String &textToInsert) override
Inserts some text, overwriting the selected text region, if there is one.
void insertTabAtCaret ()
void indentSelection ()
void unindentSelection ()
Range< int > getHighlightedRegion () const override
Returns the extents of the selected text region, or an empty range if nothing is selected,.
bool isHighlightActive () const noexcept
void setHighlightedRegion (const Range< int > &newRange) override
Sets the currently-selected text region.
String getTextInRange (const Range< int > &range) const override
Returns a specified sub-section of the text.
void setTabSize (int numSpacesPerTab, bool insertSpacesInsteadOfTabCharacters)
Changes the current tab settings.
int getTabSize () const noexcept
Returns the current number of spaces per tab.
bool areSpacesInsertedForTabs () const
Returns true if the tab key will insert spaces instead of actual tab characters.
String getTabString (int numSpaces) const
Returns a string containing spaces or tab characters to generate the given number of spaces.
void setFont (const Font &newFont)
Changes the font.
const Font & getFont () const noexcept
Returns the font that the editor is using.
void setReadOnly (bool shouldBeReadOnly) noexcept
Makes the editor read-only.
bool isReadOnly () const noexcept
Returns true if the editor is set to be read-only.
void setColourScheme (const ColourScheme &scheme)
Changes the syntax highlighting scheme.
const ColourScheme & getColourScheme () const noexcept
Returns the current syntax highlighting colour scheme.
Colour getColourForTokenType (int tokenType) const
Returns one the syntax highlighting colour for the given token.
void setScrollbarThickness (int thickness)
Changes the size of the scrollbars.
int getScrollbarThickness () const noexcept
Returns the thickness of the scrollbars.
virtual void handleReturnKey ()
Called when the return key is pressed - this can be overridden for custom behaviour.
virtual void handleTabKey ()
Called when the tab key is pressed - this can be overridden for custom behaviour.
virtual void handleEscapeKey ()
Called when the escape key is pressed - this can be overridden for custom behaviour.
virtual void editorViewportPositionChanged ()
Called when the view position is scrolled horizontally or vertically.
virtual void addPopupMenuItems (PopupMenu &menuToAddTo, const MouseEvent *mouseClickEvent)
This adds the items to the popup menu.
virtual void performPopupMenuAction (int menuItemID)
This is called to perform one of the items that was shown on the popup menu.
void setCommandManager (ApplicationCommandManager *newManager) noexcept
Specifies a commmand-manager which the editor will notify whenever the state of any of its commands changes.
void paint (Graphics &) override
void resized () override
bool keyPressed (const KeyPress &) override
void mouseDown (const MouseEvent &) override
void mouseDrag (const MouseEvent &) override
void mouseUp (const MouseEvent &) override
void mouseDoubleClick (const MouseEvent &) override
void mouseWheelMove (const MouseEvent &, const MouseWheelDetails &) override
void focusGained (FocusChangeType) override
void focusLost (FocusChangeType) override
bool isTextInputActive () const override
void setTemporaryUnderlining (const Array< Range< int > > &) override
ApplicationCommandTarget * getNextCommandTarget () override
void getAllCommands (Array< CommandID > &) override
void getCommandInfo (CommandID, ApplicationCommandInfo &) override
bool perform (const InvocationInfo &) override
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
virtual ~Component ()
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
virtual void visibilityChanged ()
Called when this component's visibility changes.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (int x, int y, int width, int height, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void parentHierarchyChanged ()
Called to indicate that the component's parents have changed.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
virtual void lookAndFeelChanged ()
Called to let the component react to a change in the look-and-feel setting.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparancy level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
virtual void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
virtual void mouseMagnify (const MouseEvent &event, float scaleFactor)
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown () const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourId, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourId, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourId)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourId) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
virtual MarkerList * getMarkers (bool xAxis)
Components can implement this method to provide a MarkerList.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
JUCE_DEPRECATED (Point< int > relativePositionToGlobal(Point< int >) const)
JUCE_DEPRECATED (Point< int > globalPositionToRelative(Point< int >) const)
JUCE_DEPRECATED (Point< int > relativePositionToOtherComponent(const Component *, Point< int >) const)
JUCE_DEPRECATED (void setBounds(const RelativeRectangle &))
JUCE_DEPRECATED (void setBounds(const String &))
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()
Destructor.
Public Member Functions inherited from ApplicationCommandTarget
ApplicationCommandTarget ()
Creates a command target.
virtual ~ApplicationCommandTarget ()
Destructor.
bool invoke (const InvocationInfo &invocationInfo, const bool asynchronously)
Makes this target invoke a command.
bool invokeDirectly (const CommandID commandID, const bool asynchronously)
Invokes a given command directly on this target.
ApplicationCommandTarget * getTargetForCommand (const CommandID commandID)
Searches this target and all subsequent ones for the first one that can handle the specified command.
bool isCommandActive (const CommandID commandID)
Checks whether this command can currently be performed by this target.
ApplicationCommandTarget * findFirstTargetParentComponent ()
If this object is a Component, this method will search upwards in its current UI hierarchy for the next parent component that implements the ApplicationCommandTarget class.
Public Member Functions inherited from TextInputTarget
TextInputTarget ()
virtual ~TextInputTarget ()
Destructor.
virtual VirtualKeyboardType getKeyboardType ()
Returns the target's preference for the type of keyboard that would be most appropriate.
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Member Enumeration Documentation
enum CodeEditorComponent::ColourIds
A set of colour IDs to use to change the colour of various aspects of the editor.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
See Also
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator
backgroundColourId
A colour to use to fill the editor's background.
highlightColourId
The colour to use for the highlighted background under selected text.
defaultTextColourId
The colour to use for text when no syntax colouring is enabled.
lineNumberBackgroundId
The colour to use for filling the background of the line-number gutter.
lineNumberTextId
The colour to use for drawing the line numbers.
Constructor & Destructor Documentation
CodeEditorComponent::CodeEditorComponent (CodeDocument & document, CodeTokeniser * codeTokeniser)
Creates an editor for a document.
The tokeniser object is optional - pass nullptr to disable syntax highlighting. The object that you pass in is not owned or deleted by the editor - you must make sure that it doesn't get deleted while this component is still using it.
See Also
CodeDocument
CodeEditorComponent::~CodeEditorComponent ()
Destructor.
Member Function Documentation
CodeDocument& CodeEditorComponent::getDocument () const noexcept
Returns the code document that this component is editing.
void CodeEditorComponent::loadContent (const String & newContent)
Loads the given content into the document.
This will completely reset the CodeDocument object, clear its undo history, and fill it with this text.
float CodeEditorComponent::getCharWidth () const noexcept
Returns the standard character width.
int CodeEditorComponent::getLineHeight () const noexcept
Returns the height of a line of text, in pixels.
int CodeEditorComponent::getNumLinesOnScreen () const noexcept
Returns the number of whole lines visible on the screen, This doesn't include a cut-off line that might be visible at the bottom if the component's height isn't an exact multiple of the line-height.
int CodeEditorComponent::getFirstLineOnScreen () const noexcept
Returns the index of the first line that's visible at the top of the editor.
int CodeEditorComponent::getNumColumnsOnScreen () const noexcept
Returns the number of whole columns visible on the screen.
This doesn't include any cut-off columns at the right-hand edge.
CodeDocument::Position CodeEditorComponent::getCaretPos () const
Returns the current caret position.
Rectangle<int> CodeEditorComponent::getCaretRectangle () override virtual
Returns the position of the caret, relative to the editor's origin.
Implements TextInputTarget.
void CodeEditorComponent::moveCaretTo (const CodeDocument::Position & newPos, bool selecting)
Moves the caret.
If selecting is true, the section of the document between the current caret position and the new one will become selected. If false, any currently selected region will be deselected.
Rectangle<int> CodeEditorComponent::getCharacterBounds (const CodeDocument::Position & pos) const
Returns the on-screen position of a character in the document.
The rectangle returned is relative to this component's top-left origin.
CodeDocument::Position CodeEditorComponent::getPositionAt (int x, int y)
Finds the character at a given on-screen position.
The coordinates are relative to this component's top-left origin.
CodeDocument::Position CodeEditorComponent::getSelectionStart () const
Returns the start of the selection as a position.
CodeDocument::Position CodeEditorComponent::getSelectionEnd () const
Returns the end of the selection as a position.
void CodeEditorComponent::setLineNumbersShown (bool shouldBeShown)
Enables or disables the line-number display in the gutter.
bool CodeEditorComponent::moveCaretLeft (bool moveInWholeWordSteps, bool selecting)
bool CodeEditorComponent::moveCaretRight (bool moveInWholeWordSteps, bool selecting)
bool CodeEditorComponent::moveCaretUp (bool selecting)
bool CodeEditorComponent::moveCaretDown (bool selecting)
bool CodeEditorComponent::scrollDown ()
bool CodeEditorComponent::scrollUp ()
bool CodeEditorComponent::pageUp (bool selecting)
bool CodeEditorComponent::pageDown (bool selecting)
bool CodeEditorComponent::moveCaretToTop (bool selecting)
bool CodeEditorComponent::moveCaretToStartOfLine (bool selecting)
bool CodeEditorComponent::moveCaretToEnd (bool selecting)
bool CodeEditorComponent::moveCaretToEndOfLine (bool selecting)
bool CodeEditorComponent::deleteBackwards (bool moveInWholeWordSteps)
bool CodeEditorComponent::deleteForwards (bool moveInWholeWordSteps)
bool CodeEditorComponent::deleteWhitespaceBackwardsToTabStop ()
virtual bool CodeEditorComponent::copyToClipboard () virtual
virtual bool CodeEditorComponent::cutToClipboard () virtual
virtual bool CodeEditorComponent::pasteFromClipboard () virtual
bool CodeEditorComponent::undo ()
bool CodeEditorComponent::redo ()
void CodeEditorComponent::selectRegion (const CodeDocument::Position & start, const CodeDocument::Position & end)
bool CodeEditorComponent::selectAll ()
void CodeEditorComponent::deselectAll ()
void CodeEditorComponent::scrollToLine (int newFirstLineOnScreen)
void CodeEditorComponent::scrollBy (int deltaLines)
void CodeEditorComponent::scrollToColumn (int newFirstColumnOnScreen)
void CodeEditorComponent::scrollToKeepCaretOnScreen ()
void CodeEditorComponent::scrollToKeepLinesOnScreen (Range< int > linesToShow)
void CodeEditorComponent::insertTextAtCaret (const String & textToInsert) override virtual
Inserts some text, overwriting the selected text region, if there is one.
Implements TextInputTarget.
void CodeEditorComponent::insertTabAtCaret ()
void CodeEditorComponent::indentSelection ()
void CodeEditorComponent::unindentSelection ()
Range<int> CodeEditorComponent::getHighlightedRegion () const override virtual
Returns the extents of the selected text region, or an empty range if nothing is selected,.
Implements TextInputTarget.
bool CodeEditorComponent::isHighlightActive () const noexcept
void CodeEditorComponent::setHighlightedRegion (const Range< int > & newRange) override virtual
Sets the currently-selected text region.
Implements TextInputTarget.
String CodeEditorComponent::getTextInRange (const Range< int > & range) const override virtual
Returns a specified sub-section of the text.
Implements TextInputTarget.
void CodeEditorComponent::setTabSize (int numSpacesPerTab, bool insertSpacesInsteadOfTabCharacters)
Changes the current tab settings.
This lets you change the tab size and whether pressing the tab key inserts a tab character, or its equivalent number of spaces.
int CodeEditorComponent::getTabSize () const noexcept
Returns the current number of spaces per tab.
See Also
setTabSize
bool CodeEditorComponent::areSpacesInsertedForTabs () const
Returns true if the tab key will insert spaces instead of actual tab characters.
See Also
setTabSize
String CodeEditorComponent::getTabString (int numSpaces) const
Returns a string containing spaces or tab characters to generate the given number of spaces.
void CodeEditorComponent::setFont (const Font & newFont)
Changes the font.
Make sure you only use a fixed-width font, or this component will look pretty nasty!
const Font& CodeEditorComponent::getFont () const noexcept
Returns the font that the editor is using.
void CodeEditorComponent::setReadOnly (bool shouldBeReadOnly) noexcept
Makes the editor read-only.
bool CodeEditorComponent::isReadOnly () const noexcept
Returns true if the editor is set to be read-only.
void CodeEditorComponent::setColourScheme (const ColourScheme & scheme)
Changes the syntax highlighting scheme.
The token type values are dependent on the tokeniser being used - use CodeTokeniser::getTokenTypes() to get a list of the token types.
See Also
getColourForTokenType
const ColourScheme& CodeEditorComponent::getColourScheme () const noexcept
Returns the current syntax highlighting colour scheme.
Colour CodeEditorComponent::getColourForTokenType (int tokenType) const
Returns one the syntax highlighting colour for the given token.
The token type values are dependent on the tokeniser being used.
See Also
setColourScheme
void CodeEditorComponent::setScrollbarThickness (int thickness)
Changes the size of the scrollbars.
int CodeEditorComponent::getScrollbarThickness () const noexcept
Returns the thickness of the scrollbars.
virtual void CodeEditorComponent::handleReturnKey () virtual
Called when the return key is pressed - this can be overridden for custom behaviour.
virtual void CodeEditorComponent::handleTabKey () virtual
Called when the tab key is pressed - this can be overridden for custom behaviour.
virtual void CodeEditorComponent::handleEscapeKey () virtual
Called when the escape key is pressed - this can be overridden for custom behaviour.
virtual void CodeEditorComponent::editorViewportPositionChanged () virtual
Called when the view position is scrolled horizontally or vertically.
virtual void CodeEditorComponent::addPopupMenuItems (PopupMenu & menuToAddTo, const MouseEvent * mouseClickEvent) virtual
This adds the items to the popup menu.
By default it adds the cut/copy/paste items, but you can override this if you need to replace these with your own items.
If you want to add your own items to the existing ones, you can override this, call the base class's addPopupMenuItems() method, then append your own items.
When the menu has been shown, performPopupMenuAction() will be called to perform the item that the user has chosen.
If this was triggered by a mouse-click, the mouseClickEvent parameter will be a pointer to the info about it, or may be null if the menu is being triggered by some other means.
See Also
performPopupMenuAction, setPopupMenuEnabled, isPopupMenuEnabled
virtual void CodeEditorComponent::performPopupMenuAction (int menuItemID) virtual
This is called to perform one of the items that was shown on the popup menu.
If you've overridden addPopupMenuItems(), you should also override this to perform the actions that you've added.
If you've overridden addPopupMenuItems() but have still left the default items on the menu, remember to call the superclass's performPopupMenuAction() so that it can perform the default actions if that's what the user clicked on.
See Also
addPopupMenuItems, setPopupMenuEnabled, isPopupMenuEnabled
void CodeEditorComponent::setCommandManager (ApplicationCommandManager * newManager) noexcept
Specifies a commmand-manager which the editor will notify whenever the state of any of its commands changes.
If you're making use of the editor's ApplicationCommandTarget interface, then you should also use this to tell it which command manager it should use. Make sure that the manager does not go out of scope while the editor is using it. You can pass a nullptr here to disable this.
void CodeEditorComponent::paint (Graphics &) override virtual
Reimplemented from Component.
void CodeEditorComponent::resized () override virtual
Reimplemented from Component.
bool CodeEditorComponent::keyPressed (const KeyPress &) override virtual
Reimplemented from Component.
void CodeEditorComponent::mouseDown (const MouseEvent &) override virtual
Reimplemented from Component.
void CodeEditorComponent::mouseDrag (const MouseEvent &) override virtual
Reimplemented from Component.
void CodeEditorComponent::mouseUp (const MouseEvent &) override virtual
Reimplemented from Component.
void CodeEditorComponent::mouseDoubleClick (const MouseEvent &) override virtual
Reimplemented from Component.
void CodeEditorComponent::mouseWheelMove (const MouseEvent & , const MouseWheelDetails &) override virtual
Reimplemented from Component.
void CodeEditorComponent::focusGained (FocusChangeType) override virtual
Reimplemented from Component.
void CodeEditorComponent::focusLost (FocusChangeType) override virtual
Reimplemented from Component.
bool CodeEditorComponent::isTextInputActive () const override virtual
Implements TextInputTarget.
void CodeEditorComponent::setTemporaryUnderlining (const Array< Range< int > > &) override virtual
Implements TextInputTarget.
ApplicationCommandTarget* CodeEditorComponent::getNextCommandTarget () override virtual
Implements ApplicationCommandTarget.
void CodeEditorComponent::getAllCommands (Array< CommandID > &) override virtual
Implements ApplicationCommandTarget.
void CodeEditorComponent::getCommandInfo (CommandID , ApplicationCommandInfo &) override virtual
Implements ApplicationCommandTarget.
bool CodeEditorComponent::perform (const InvocationInfo &) override virtual
Implements ApplicationCommandTarget.
class CodeTokeniser
A base class for tokenising code so that the syntax can be displayed in a code editor.
See Also
CodeDocument, CodeEditorComponent
Public Member Functions
CodeTokeniser ()
virtual ~CodeTokeniser ()
virtual int readNextToken (CodeDocument::Iterator &source)=0
Reads the next token from the source and returns its token type.
virtual
CodeEditorComponent::ColourScheme getDefaultColourScheme ()=0
Returns a suggested syntax highlighting colour scheme.
Constructor & Destructor Documentation
CodeTokeniser::CodeTokeniser ()
virtual CodeTokeniser::~CodeTokeniser () virtual
Member Function Documentation
virtual int CodeTokeniser::readNextToken (CodeDocument::Iterator & source) pure virtual
Reads the next token from the source and returns its token type.
This must leave the source pointing to the first character in the next token.
Implemented in CPlusPlusCodeTokeniser, LuaTokeniser, and XmlTokeniser.
virtual CodeEditorComponent::ColourScheme CodeTokeniser::getDefaultColourScheme () pure virtual
Returns a suggested syntax highlighting colour scheme.
Implemented in CPlusPlusCodeTokeniser, LuaTokeniser, and XmlTokeniser.
class CPlusPlusCodeTokeniser
A simple lexical analyser for syntax colouring of C++ code.
See Also
CodeEditorComponent, CodeDocument
Public Types
enum TokenType {
tokenType_error = 0, tokenType_comment, tokenType_keyword, tokenType_operator,
tokenType_identifier, tokenType_integer, tokenType_float, tokenType_string,
tokenType_bracket, tokenType_punctuation, tokenType_preprocessor
}
The token values returned by this tokeniser.
Public Member Functions
CPlusPlusCodeTokeniser ()
~CPlusPlusCodeTokeniser ()
int readNextToken (CodeDocument::Iterator &) override
Reads the next token from the source and returns its token type.
CodeEditorComponent::ColourScheme getDefaultColourScheme () override
Returns a suggested syntax highlighting colour scheme.
Public Member Functions inherited from CodeTokeniser
CodeTokeniser ()
virtual ~CodeTokeniser ()
Static Public Member Functions
static bool isReservedKeyword (const String &token) noexcept
This is a handy method for checking whether a string is a c++ reserved keyword.
Member Enumeration Documentation
enum CPlusPlusCodeTokeniser::TokenType
The token values returned by this tokeniser.
Enumerator
tokenType_error
tokenType_comment
tokenType_keyword
tokenType_operator
tokenType_identifier
tokenType_integer
tokenType_float
tokenType_string
tokenType_bracket
tokenType_punctuation
tokenType_preprocessor
Constructor & Destructor Documentation
CPlusPlusCodeTokeniser::CPlusPlusCodeTokeniser ()
CPlusPlusCodeTokeniser::~CPlusPlusCodeTokeniser ()
Member Function Documentation
int CPlusPlusCodeTokeniser::readNextToken (CodeDocument::Iterator & source) override virtual
Reads the next token from the source and returns its token type.
This must leave the source pointing to the first character in the next token.
Implements CodeTokeniser.
CodeEditorComponent::ColourScheme CPlusPlusCodeTokeniser::getDefaultColourScheme () override virtual
Returns a suggested syntax highlighting colour scheme.
Implements CodeTokeniser.
static bool CPlusPlusCodeTokeniser::isReservedKeyword (const String & token) static noexcept
This is a handy method for checking whether a string is a c++ reserved keyword.
struct CppTokeniserFunctions
Class containing some basic functions for simple tokenising of C++ code.
Static Public Member Functions
static bool isIdentifierStart (const juce_wchar c) noexcept
static bool isIdentifierBody (const juce_wchar c) noexcept
static bool isReservedKeyword (String::CharPointerType token, const int tokenLength) noexcept
template<typename Iterator >
static int parseIdentifier (Iterator &source) noexcept
template<typename Iterator >
static bool skipNumberSuffix (Iterator &source)
static bool isHexDigit (const juce_wchar c) noexcept
template<typename Iterator >
static bool parseHexLiteral (Iterator &source) noexcept
static bool isOctalDigit (const juce_wchar c) noexcept
template<typename Iterator >
static bool parseOctalLiteral (Iterator &source) noexcept
static bool isDecimalDigit (const juce_wchar c) noexcept
template<typename Iterator >
static bool parseDecimalLiteral (Iterator &source) noexcept
template<typename Iterator >
static bool parseFloatLiteral (Iterator &source) noexcept
template<typename Iterator >
static int parseNumber (Iterator &source)
template<typename Iterator >
static void skipQuotedString (Iterator &source) noexcept
template<typename Iterator >
static void skipComment (Iterator &source) noexcept
template<typename Iterator >
static void skipPreprocessorLine (Iterator &source) noexcept
template<typename Iterator >
static void skipIfNextCharMatches (Iterator &source, const juce_wchar c) noexcept
template<typename Iterator >
static void skipIfNextCharMatches (Iterator &source, const juce_wchar c1, const juce_wchar c2) noexcept
template<typename Iterator >
static int readNextToken (Iterator &source)
static void writeEscapeChars (OutputStream &out, const char *utf8, const int numBytesToRead, const int maxCharsOnLine, const bool breakAtNewLines, const bool replaceSingleQuotes, const bool allowStringBreaks)
Takes a UTF8 string and writes it to a stream using standard C++ escape sequences for any non-ascii bytes.
static String addEscapeChars (const String &s)
Takes a string and returns a version of it where standard C++ escape sequences have been used to replace any non-ascii bytes.
Member Function Documentation
static bool CppTokeniserFunctions::isIdentifierStart (const juce_wchar c) static noexcept
References CharacterFunctions::isLetter().
Referenced by readNextToken().
static bool CppTokeniserFunctions::isIdentifierBody (const juce_wchar c) static noexcept
References CharacterFunctions::isLetterOrDigit().
Referenced by parseIdentifier().
static bool CppTokeniserFunctions::isReservedKeyword (String::CharPointerType token, const int tokenLength) static noexcept
Referenced by parseIdentifier().
template<typename Iterator > static int CppTokeniserFunctions::parseIdentifier (Iterator & source) static noexcept
References isIdentifierBody(), isReservedKeyword(), CPlusPlusCodeTokeniser::tokenType_identifier, CPlusPlusCodeTokeniser::tokenType_keyword, CharPointer_UTF8::write(), and CharPointer_UTF8::writeNull().
Referenced by readNextToken().
template<typename Iterator > static bool CppTokeniserFunctions::skipNumberSuffix (Iterator & source) static
References CharacterFunctions::isLetterOrDigit().
Referenced by parseDecimalLiteral(), parseHexLiteral(), and parseOctalLiteral().
static bool CppTokeniserFunctions::isHexDigit (const juce_wchar c) static noexcept
Referenced by parseHexLiteral().
template<typename Iterator > static bool CppTokeniserFunctions::parseHexLiteral (Iterator & source) static noexcept
References isHexDigit(), and skipNumberSuffix().
Referenced by parseNumber().
static bool CppTokeniserFunctions::isOctalDigit (const juce_wchar c) static noexcept
Referenced by parseOctalLiteral().
template<typename Iterator > static bool CppTokeniserFunctions::parseOctalLiteral (Iterator & source) static noexcept
References isOctalDigit(), and skipNumberSuffix().
Referenced by parseNumber().
static bool CppTokeniserFunctions::isDecimalDigit (const juce_wchar c) static noexcept
Referenced by parseDecimalLiteral(), and parseFloatLiteral().
template<typename Iterator > static bool CppTokeniserFunctions::parseDecimalLiteral (Iterator & source) static noexcept
References isDecimalDigit(), and skipNumberSuffix().
Referenced by parseNumber().
template<typename Iterator > static bool CppTokeniserFunctions::parseFloatLiteral (Iterator & source) static noexcept
References isDecimalDigit().
Referenced by parseNumber().
template<typename Iterator > static int CppTokeniserFunctions::parseNumber (Iterator & source) static
References parseDecimalLiteral(), parseFloatLiteral(), parseHexLiteral(), parseOctalLiteral(), CPlusPlusCodeTokeniser::tokenType_error, CPlusPlusCodeTokeniser::tokenType_float, and CPlusPlusCodeTokeniser::tokenType_integer.
Referenced by readNextToken().
template<typename Iterator > static void CppTokeniserFunctions::skipQuotedString (Iterator & source) static noexcept
Referenced by readNextToken(), and skipPreprocessorLine().
template<typename Iterator > static void CppTokeniserFunctions::skipComment (Iterator & source) static noexcept
Referenced by readNextToken().
template<typename Iterator > static void CppTokeniserFunctions::skipPreprocessorLine (Iterator & source) static noexcept
References skipQuotedString().
Referenced by readNextToken().
template<typename Iterator > static void CppTokeniserFunctions::skipIfNextCharMatches (Iterator & source, const juce_wchar c) static noexcept
Referenced by readNextToken().
template<typename Iterator > static void CppTokeniserFunctions::skipIfNextCharMatches (Iterator & source, const juce_wchar c1, const juce_wchar c2) static noexcept
template<typename Iterator > static int CppTokeniserFunctions::readNextToken (Iterator & source) static
References isIdentifierStart(), parseIdentifier(), parseNumber(), skipComment(), skipIfNextCharMatches(), skipPreprocessorLine(), skipQuotedString(), CPlusPlusCodeTokeniser::tokenType_bracket, CPlusPlusCodeTokeniser::tokenType_comment, CPlusPlusCodeTokeniser::tokenType_error, CPlusPlusCodeTokeniser::tokenType_operator, CPlusPlusCodeTokeniser::tokenType_preprocessor, CPlusPlusCodeTokeniser::tokenType_punctuation, and CPlusPlusCodeTokeniser::tokenType_string.
static void CppTokeniserFunctions::writeEscapeChars (OutputStream & out, const char * utf8, const int numBytesToRead, const int maxCharsOnLine, const bool breakAtNewLines, const bool replaceSingleQuotes, const bool allowStringBreaks) static
Takes a UTF8 string and writes it to a stream using standard C++ escape sequences for any non-ascii bytes.
Although not strictly a tokenising function, this is still a function that often comes in handy when working with C++ code!
Note that addEscapeChars() is easier to use than this function if you're working with Strings.
See Also
addEscapeChars
References CharacterFunctions::getHexDigitValue(), newLine, and String::toHexString().
Referenced by addEscapeChars().
static String CppTokeniserFunctions::addEscapeChars (const String & s) static
Takes a string and returns a version of it where standard C++ escape sequences have been used to replace any non-ascii bytes.
Although not strictly a tokenising function, this is still a function that often comes in handy when working with C++ code!
See Also
writeEscapeChars
References String::toRawUTF8(), MemoryOutputStream::toString(), and writeEscapeChars().
class LuaTokeniser
Public Types
enum TokenType {
tokenType_error = 0, tokenType_comment, tokenType_keyword, tokenType_operator,
tokenType_identifier, tokenType_integer, tokenType_float, tokenType_string,
tokenType_bracket, tokenType_punctuation
}
The token values returned by this tokeniser.
Public Member Functions
LuaTokeniser ()
~LuaTokeniser ()
int readNextToken (CodeDocument::Iterator &) override
Reads the next token from the source and returns its token type.
CodeEditorComponent::ColourScheme getDefaultColourScheme () override
Returns a suggested syntax highlighting colour scheme.
Public Member Functions inherited from CodeTokeniser
CodeTokeniser ()
virtual ~CodeTokeniser ()
Member Enumeration Documentation
enum LuaTokeniser::TokenType
The token values returned by this tokeniser.
Enumerator
tokenType_error
tokenType_comment
tokenType_keyword
tokenType_operator
tokenType_identifier
tokenType_integer
tokenType_float
tokenType_string
tokenType_bracket
tokenType_punctuation
Constructor & Destructor Documentation
LuaTokeniser::LuaTokeniser ()
LuaTokeniser::~LuaTokeniser ()
Member Function Documentation
int LuaTokeniser::readNextToken (CodeDocument::Iterator & source) override virtual
Reads the next token from the source and returns its token type.
This must leave the source pointing to the first character in the next token.
Implements CodeTokeniser.
CodeEditorComponent::ColourScheme LuaTokeniser::getDefaultColourScheme () override virtual
Returns a suggested syntax highlighting colour scheme.
Implements CodeTokeniser.
class XmlTokeniser
Public Types
enum TokenType {
tokenType_error = 0, tokenType_comment, tokenType_keyword, tokenType_operator,
tokenType_identifier, tokenType_string, tokenType_bracket, tokenType_punctuation,
tokenType_preprocessor
}
The token values returned by this tokeniser.
Public Member Functions
XmlTokeniser ()
~XmlTokeniser ()
int readNextToken (CodeDocument::Iterator &) override
Reads the next token from the source and returns its token type.
CodeEditorComponent::ColourScheme getDefaultColourScheme () override
Returns a suggested syntax highlighting colour scheme.
Public Member Functions inherited from CodeTokeniser
CodeTokeniser ()
virtual ~CodeTokeniser ()
Member Enumeration Documentation
enum XmlTokeniser::TokenType
The token values returned by this tokeniser.
Enumerator
tokenType_error
tokenType_comment
tokenType_keyword
tokenType_operator
tokenType_identifier
tokenType_string
tokenType_bracket
tokenType_punctuation
tokenType_preprocessor
Constructor & Destructor Documentation
XmlTokeniser::XmlTokeniser ()
XmlTokeniser::~XmlTokeniser ()
Member Function Documentation
int XmlTokeniser::readNextToken (CodeDocument::Iterator & source) override virtual
Reads the next token from the source and returns its token type.
This must leave the source pointing to the first character in the next token.
Implements CodeTokeniser.
CodeEditorComponent::ColourScheme XmlTokeniser::getDefaultColourScheme () override virtual
Returns a suggested syntax highlighting colour scheme.
Implements CodeTokeniser.