JUCE: maths
maths
juce_dsp
Classes
struct FastMathApproximations
This class contains various fast mathematical function approximations.
class LookupTable< FloatType >
Class for efficiently approximating expensive arithmetic operations.
class LookupTableTransform< FloatType >
Class for approximating expensive arithmetic operations.
class Matrix< ElementType >
General matrix and vectors class, meant for classic math manipulation such as additions, multiplications, and linear systems of equations solving.
class Polynomial< FloatingType >
A class representing a polynomial.
struct SpecialFunctions
Contains miscellaneous filter design and windowing functions.
Detailed Description
Class Documentation
struct FastMathApproximations
This class contains various fast mathematical function approximations.
Static Public Member Functions
template<typename FloatType >
static FloatType cosh (FloatType x) noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void cosh (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType sinh (FloatType x) noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void sinh (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType tanh (FloatType x) noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void tanh (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType cos (FloatType x) noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void cos (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType sin (FloatType x) noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void sin (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType tan (FloatType x) noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void tan (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType exp (FloatType x) noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void exp (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType logNPlusOne (FloatType x) noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void logNPlusOne (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated on a whole buffer.
Member Function Documentation
template<typename FloatType > static FloatType FastMathApproximations::cosh (FloatType x) static noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
Referenced by cosh().
template<typename FloatType > static void FastMathApproximations::cosh (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
References cosh().
template<typename FloatType > static FloatType FastMathApproximations::sinh (FloatType x) static noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
Referenced by sinh().
template<typename FloatType > static void FastMathApproximations::sinh (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
References sinh().
template<typename FloatType > static FloatType FastMathApproximations::tanh (FloatType x) static noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
Referenced by tanh().
template<typename FloatType > static void FastMathApproximations::tanh (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
References tanh().
template<typename FloatType > static FloatType FastMathApproximations::cos (FloatType x) static noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
Referenced by cos().
template<typename FloatType > static void FastMathApproximations::cos (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
References cos().
template<typename FloatType > static FloatType FastMathApproximations::sin (FloatType x) static noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
Referenced by sin().
template<typename FloatType > static void FastMathApproximations::sin (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
References sin().
template<typename FloatType > static FloatType FastMathApproximations::tan (FloatType x) static noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi/2 and +pi/2 for limiting the error.
Referenced by tan().
template<typename FloatType > static void FastMathApproximations::tan (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi/2 and +pi/2 for limiting the error.
References tan().
template<typename FloatType > static FloatType FastMathApproximations::exp (FloatType x) static noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -6 and +4 for limiting the error.
Referenced by exp().
template<typename FloatType > static void FastMathApproximations::exp (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -6 and +4 for limiting the error.
References exp().
template<typename FloatType > static FloatType FastMathApproximations::logNPlusOne (FloatType x) static noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -0.8 and +5 for limiting the error.
Referenced by logNPlusOne().
template<typename FloatType > static void FastMathApproximations::logNPlusOne (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -0.8 and +5 for limiting the error.
References logNPlusOne().
class LookupTable
template<typename FloatType>
class LookupTable< FloatType >
Class for efficiently approximating expensive arithmetic operations.
The approximation is based on linear interpolation between pre-calculated values. The approximated function should be passed as a callable object to the constructor along with the number of data points to be pre-calculated. The accuracy of the approximation can be increased by using more points at the cost of a larger memory footprint.
Consider using LookupTableTransform as an easy-to-use alternative.
Example:
LookupTable<float> lut ([] (size_t i) { return std::sqrt ((float) i); }, 64);
auto outValue = lut[17];
See Also
LookupTableTransform
Public Member Functions
LookupTable ()
Creates an uninitialised LookupTable object.
LookupTable (const std::function< FloatType(size_t)> &functionToApproximate, size_t numPointsToUse)
Creates and initialises a LookupTable object.
void initialise (const std::function< FloatType(size_t)> &functionToApproximate, size_t numPointsToUse)
Initialises or changes the parameters of a LookupTable object.
FloatType getUnchecked (FloatType index) const noexcept
Calculates the approximated value for the given index without range checking.
FloatType get (FloatType index) const noexcept
Calculates the approximated value for the given index with range checking.
FloatType operator[] (FloatType index) const noexcept
size_t getNumPoints () const noexcept
Returns the size of the LookupTable, i.e., the number of pre-calculated data points.
bool isInitialised () const noexcept
Returns true if the LookupTable is initialised and ready to be used.
Constructor & Destructor Documentation
template<typename FloatType> LookupTable< FloatType >::LookupTable ()
Creates an uninitialised LookupTable object.
You need to call initialise() before using the object. Prefer using the non-default constructor instead.
See Also
initialise
template<typename FloatType> LookupTable< FloatType >::LookupTable (const std::function< FloatType(size_t)> & functionToApproximate, size_t numPointsToUse)
Creates and initialises a LookupTable object.
Parameters
functionToApproximate The function to be approximated. This should be a mapping from the integer range [0, numPointsToUse - 1].
numPointsToUse The number of pre-calculated values stored.
Member Function Documentation
template<typename FloatType> void LookupTable< FloatType >::initialise (const std::function< FloatType(size_t)> & functionToApproximate, size_t numPointsToUse)
Initialises or changes the parameters of a LookupTable object.
This function can be used to change what function is approximated by an already constructed LookupTable along with the number of data points used. If the function to be approximated won't ever change, prefer using the non-default constructor.
Parameters
functionToApproximate The function to be approximated. This should be a mapping from the integer range [0, numPointsToUse - 1].
numPointsToUse The number of pre-calculated values stored.
template<typename FloatType> FloatType LookupTable< FloatType >::getUnchecked (FloatType index) const noexcept
Calculates the approximated value for the given index without range checking.
Use this if you can guarantee that the index is non-negative and less than numPoints. Otherwise use get().
Parameters
index The approximation is calculated for this non-integer index.
Returns
The approximated value at the given index.
See Also
get, operator[]
Referenced by LookupTable< NumericType >::get(), and LookupTable< NumericType >::operator[]().
template<typename FloatType> FloatType LookupTable< FloatType >::get (FloatType index) const noexcept
Calculates the approximated value for the given index with range checking.
This can be called with any input indices. If the provided index is out-of-range either the bottom or the top element of the LookupTable is returned.
If the index is guaranteed to be in range use the faster getUnchecked() instead.
Parameters
index The approximation is calculated for this non-integer index.
Returns
The approximated value at the given index.
See Also
getUnchecked, operator[]
template<typename FloatType> FloatType LookupTable< FloatType >::operator[] (FloatType index) const noexcept
See Also
getUnchecked
template<typename FloatType> size_t LookupTable< FloatType >::getNumPoints () const noexcept
Returns the size of the LookupTable, i.e., the number of pre-calculated data points.
Referenced by LookupTable< NumericType >::get(), and LookupTable< NumericType >::getUnchecked().
template<typename FloatType> bool LookupTable< FloatType >::isInitialised () const noexcept
Returns true if the LookupTable is initialised and ready to be used.
Referenced by LookupTable< NumericType >::getUnchecked().
class LookupTableTransform
template<typename FloatType>
class LookupTableTransform< FloatType >
Class for approximating expensive arithmetic operations.
Once initialised, this class can be used just like the function it approximates via operator().
Example:
LookupTableTransform<float> tanhApprox ([] (float x) { return std::tanh (x); }, -5.0f, 5.0f, 64);
auto outValue = tanhApprox (4.2f);
Note : if you try to call the function with an input outside the provided range, it will return either the first or the last recorded LookupTable value.
See Also
LookupTable
Public Member Functions
LookupTableTransform ()
Creates an uninitialised LookupTableTransform object.
LookupTableTransform (const std::function< FloatType(FloatType)> &functionToApproximate, FloatType minInputValueToUse, FloatType maxInputValueToUse, size_t numPoints)
Creates and initialises a LookupTableTransform object.
void initialise (const std::function< FloatType(FloatType)> &functionToApproximate, FloatType minInputValueToUse, FloatType maxInputValueToUse, size_t numPoints)
Initialises or changes the parameters of a LookupTableTransform object.
FloatType processSampleUnchecked (FloatType value) const noexcept
Calculates the approximated value for the given input value without range checking.
FloatType processSample (FloatType value) const noexcept
Calculates the approximated value for the given input value with range checking.
FloatType operator[] (FloatType index) const noexcept
FloatType operator() (FloatType index) const noexcept
void processUnchecked (const FloatType *input, FloatType *output, size_t numSamples) const noexcept
Processes an array of input values without range checking.
void process (const FloatType *input, FloatType *output, size_t numSamples) const noexcept
Processes an array of input values with range checking.
Static Public Member Functions
static double calculateMaxRelativeError (const std::function< FloatType(FloatType)> &functionToApproximate, FloatType minInputValue, FloatType maxInputValue, size_t numPoints, size_t numTestPoints=0)
Calculates the maximum relative error of the approximation for the specified parameter set.
Constructor & Destructor Documentation
template<typename FloatType> LookupTableTransform< FloatType >::LookupTableTransform ()
Creates an uninitialised LookupTableTransform object.
You need to call initialise() before using the object. Prefer using the non-default constructor instead.
See Also
initialise
template<typename FloatType> LookupTableTransform< FloatType >::LookupTableTransform (const std::function< FloatType(FloatType)> & functionToApproximate, FloatType minInputValueToUse, FloatType maxInputValueToUse, size_t numPoints)
Creates and initialises a LookupTableTransform object.
Parameters
functionToApproximate The function to be approximated. This should be a mapping from a FloatType to FloatType.
minInputValueToUse The lowest input value used. The approximation will fail for values lower than this.
maxInputValueToUse The highest input value used. The approximation will fail for values higher than this.
numPoints The number of pre-calculated values stored.
Member Function Documentation
template<typename FloatType> void LookupTableTransform< FloatType >::initialise (const std::function< FloatType(FloatType)> & functionToApproximate, FloatType minInputValueToUse, FloatType maxInputValueToUse, size_t numPoints)
Initialises or changes the parameters of a LookupTableTransform object.
Parameters
functionToApproximate The function to be approximated. This should be a mapping from a FloatType to FloatType.
minInputValueToUse The lowest input value used. The approximation will fail for values lower than this.
maxInputValueToUse The highest input value used. The approximation will fail for values higher than this.
numPoints The number of pre-calculated values stored.
Referenced by LookupTableTransform< NumericType >::LookupTableTransform().
template<typename FloatType> FloatType LookupTableTransform< FloatType >::processSampleUnchecked (FloatType value) const noexcept
Calculates the approximated value for the given input value without range checking.
Use this if you can guarantee that the input value is within the range specified in the constructor or initialise(), otherwise use processSample().
Parameters
value The approximation is calculated for this input value.
Returns
The approximated value for the provided input value.
See Also
processSample, operator(), operator[]
Referenced by LookupTableTransform< NumericType >::operator[](), and LookupTableTransform< NumericType >::processUnchecked().
template<typename FloatType> FloatType LookupTableTransform< FloatType >::processSample (FloatType value) const noexcept
Calculates the approximated value for the given input value with range checking.
This can be called with any input values. Out-of-range input values will be clipped to the specified input range.
If the index is guaranteed to be in range use the faster processSampleUnchecked() instead.
Parameters
value The approximation is calculated for this input value.
Returns
The approximated value for the provided input value.
See Also
processSampleUnchecked, operator(), operator[]
Referenced by LookupTableTransform< NumericType >::operator()(), and LookupTableTransform< NumericType >::process().
template<typename FloatType> FloatType LookupTableTransform< FloatType >::operator[] (FloatType index) const noexcept
See Also
processSampleUnchecked
template<typename FloatType> FloatType LookupTableTransform< FloatType >::operator() (FloatType index) const noexcept
See Also
processSample
template<typename FloatType> void LookupTableTransform< FloatType >::processUnchecked (const FloatType * input, FloatType * output, size_t numSamples) const noexcept
Processes an array of input values without range checking.
See Also
process
template<typename FloatType> void LookupTableTransform< FloatType >::process (const FloatType * input, FloatType * output, size_t numSamples) const noexcept
Processes an array of input values with range checking.
See Also
processUnchecked
template<typename FloatType> static double LookupTableTransform< FloatType >::calculateMaxRelativeError (const std::function< FloatType(FloatType)> & functionToApproximate, FloatType minInputValue, FloatType maxInputValue, size_t numPoints, size_t numTestPoints = 0) static
Calculates the maximum relative error of the approximation for the specified parameter set.
The closer the returned value is to zero the more accurate the approximation is.
This function compares the approximated output of this class to the function it approximates at a range of points and returns the maximum relative error. This can be used to determine if the approximation is suitable for the given problem. The accuracy of the approximation can generally be improved by increasing numPoints.
Parameters
functionToApproximate The approximated function. This should be a mapping from a FloatType to FloatType.
minInputValue The lowest input value used.
maxInputValue The highest input value used.
numPoints The number of pre-calculated values stored.
numTestPoints The number of input values used for error calculation. Higher numbers can increase the accuracy of the error calculation. If it's zero then 100 * numPoints will be used.
class Matrix
template<typename ElementType>
class Matrix< ElementType >
General matrix and vectors class, meant for classic math manipulation such as additions, multiplications, and linear systems of equations solving.
See Also
LinearAlgebra
Public Member Functions
Matrix (size_t numRows, size_t numColumns)
Creates a new matrix with a given number of rows and columns.
Matrix (size_t numRows, size_t numColumns, const ElementType *dataPointer)
Creates a new matrix with a given number of rows and columns, with initial data coming from an array, stored in row-major order.
Matrix (const Matrix &)=default
Creates a copy of another matrix.
Matrix (Matrix &&) noexcept=default
Moves a copy of another matrix.
Matrix & operator= (const Matrix &)=default
Creates a copy of another matrix.
Matrix & operator= (Matrix &&) noexcept=default
Moves another matrix into this one.
size_t getNumRows () const noexcept
Returns the number of rows in the matrix.
size_t getNumColumns () const noexcept
Returns the number of columns in the matrix.
Array< size_t > getSize () const noexcept
Returns an Array of 2 integers with the number of rows and columns in the matrix.
void clear () noexcept
Fills the contents of the matrix with zeroes.
Matrix & swapRows (size_t rowOne, size_t rowTwo) noexcept
Swaps the contents of two rows in the matrix and returns a reference to itself.
Matrix & swapColumns (size_t columnOne, size_t columnTwo) noexcept
Swaps the contents of two columns in the matrix and returns a reference to itself.
ElementType operator() (size_t row, size_t column) const noexcept
Returns the value of the matrix at a given row and column (for reading).
ElementType & operator() (size_t row, size_t column) noexcept
Returns the value of the matrix at a given row and column (for modifying).
ElementType * getRawDataPointer () noexcept
Returns a pointer to the raw data of the matrix object, ordered in row-major order (for modifying).
const ElementType * getRawDataPointer () const noexcept
Returns a pointer to the raw data of the matrix object, ordered in row-major order (for reading).
Matrix & operator+= (const Matrix &other) noexcept
Addition of two matrices.
Matrix & operator-= (const Matrix &other) noexcept
Subtraction of two matrices.
Matrix & operator*= (ElementType scalar) noexcept
Scalar multiplication.
Matrix operator+ (const Matrix &other) const
Addition of two matrices.
Matrix operator- (const Matrix &other) const
Addition of two matrices.
Matrix operator* (ElementType scalar) const
Scalar multiplication.
Matrix operator* (const Matrix &other) const
Matrix multiplication.
Matrix & hadarmard (const Matrix &other) noexcept
Does a hadarmard product with the receiver and other and stores the result in the receiver.
bool operator== (const Matrix &other) const noexcept
bool isSquare () const noexcept
Tells if the matrix is a square matrix.
bool isVector () const noexcept
Tells if the matrix is a vector.
bool isOneColumnVector () const noexcept
Tells if the matrix is a one column vector.
bool isOneRowVector () const noexcept
Tells if the matrix is a one row vector.
bool isNullMatrix () const noexcept
Tells if the matrix is a null matrix.
bool solve (Matrix &b) const noexcept
Solves a linear system of equations represented by this object and the argument b, using various algorithms depending on the size of the arguments.
String toString () const
Returns a String displaying in a convenient way the matrix contents.
ElementType * begin () noexcept
ElementType * end () noexcept
const ElementType * begin () const noexcept
const ElementType * end () const noexcept
Static Public Member Functions
static Matrix identity (size_t size)
Creates the identity matrix.
static Matrix toeplitz (const Matrix &vector, size_t size)
Creates a Toeplitz Matrix from a vector with a given squared size.
static Matrix hankel (const Matrix &vector, size_t size, size_t offset=0)
Creates a squared size x size Hankel Matrix from a vector with an optional offset.
static Matrix hadarmard (const Matrix &a, const Matrix &b)
Does a hadarmard product with a and b returns the result.
static bool compare (const Matrix &a, const Matrix &b, ElementType tolerance=0) noexcept
Compare to matrices with a given tolerance.
Constructor & Destructor Documentation
template<typename ElementType > Matrix< ElementType >::Matrix (size_t numRows, size_t numColumns)
Creates a new matrix with a given number of rows and columns.
References Matrix< ElementType >::clear().
template<typename ElementType > Matrix< ElementType >::Matrix (size_t numRows, size_t numColumns, const ElementType * dataPointer)
Creates a new matrix with a given number of rows and columns, with initial data coming from an array, stored in row-major order.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer().
template<typename ElementType > Matrix< ElementType >::Matrix (const Matrix< ElementType > &) default
Creates a copy of another matrix.
template<typename ElementType > Matrix< ElementType >::Matrix (Matrix< ElementType > &&) default noexcept
Moves a copy of another matrix.
Member Function Documentation
template<typename ElementType > Matrix& Matrix< ElementType >::operator= (const Matrix< ElementType > &) default
Creates a copy of another matrix.
template<typename ElementType > Matrix& Matrix< ElementType >::operator= (Matrix< ElementType > &&) default noexcept
Moves another matrix into this one.
template<typename ElementType > static Matrix Matrix< ElementType >::identity (size_t size) static
Creates the identity matrix.
template<typename ElementType > static Matrix Matrix< ElementType >::toeplitz (const Matrix< ElementType > & vector, size_t size) static
Creates a Toeplitz Matrix from a vector with a given squared size.
template<typename ElementType > static Matrix Matrix< ElementType >::hankel (const Matrix< ElementType > & vector, size_t size, size_t offset = 0) static
Creates a squared size x size Hankel Matrix from a vector with an optional offset.
Parameters
vector The vector from which the Hankel matrix should be generated. Its number of rows should be at least 2 * (size - 1) + 1
size The size of resulting square matrix.
offset An optional offset into the given vector.
template<typename ElementType > size_t Matrix< ElementType >::getNumRows () const noexcept
Returns the number of rows in the matrix.
template<typename ElementType > size_t Matrix< ElementType >::getNumColumns () const noexcept
Returns the number of columns in the matrix.
template<typename ElementType > Array<size_t> Matrix< ElementType >::getSize () const noexcept
Returns an Array of 2 integers with the number of rows and columns in the matrix.
template<typename ElementType > void Matrix< ElementType >::clear () noexcept
Fills the contents of the matrix with zeroes.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size(), and zeromem().
Referenced by Matrix< ElementType >::Matrix().
template<typename ElementType > Matrix& Matrix< ElementType >::swapRows (size_t rowOne, size_t rowTwo) noexcept
Swaps the contents of two rows in the matrix and returns a reference to itself.
template<typename ElementType > Matrix& Matrix< ElementType >::swapColumns (size_t columnOne, size_t columnTwo) noexcept
Swaps the contents of two columns in the matrix and returns a reference to itself.
template<typename ElementType > ElementType Matrix< ElementType >::operator() (size_t row, size_t column) const noexcept
Returns the value of the matrix at a given row and column (for reading).
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), and jassert.
template<typename ElementType > ElementType& Matrix< ElementType >::operator() (size_t row, size_t column) noexcept
Returns the value of the matrix at a given row and column (for modifying).
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), and jassert.
template<typename ElementType > ElementType* Matrix< ElementType >::getRawDataPointer () noexcept
Returns a pointer to the raw data of the matrix object, ordered in row-major order (for modifying).
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer().
template<typename ElementType > const ElementType* Matrix< ElementType >::getRawDataPointer () const noexcept
Returns a pointer to the raw data of the matrix object, ordered in row-major order (for reading).
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin().
template<typename ElementType > Matrix& Matrix< ElementType >::operator+= (const Matrix< ElementType > & other) noexcept
Addition of two matrices.
template<typename ElementType > Matrix& Matrix< ElementType >::operator-= (const Matrix< ElementType > & other) noexcept
Subtraction of two matrices.
template<typename ElementType > Matrix& Matrix< ElementType >::operator*= (ElementType scalar) noexcept
Scalar multiplication.
References Matrix< ElementType >::begin(), and Matrix< ElementType >::end().
template<typename ElementType > Matrix Matrix< ElementType >::operator+ (const Matrix< ElementType > & other) const
Addition of two matrices.
template<typename ElementType > Matrix Matrix< ElementType >::operator- (const Matrix< ElementType > & other) const
Addition of two matrices.
template<typename ElementType > Matrix Matrix< ElementType >::operator* (ElementType scalar) const
Scalar multiplication.
template<typename ElementType > Matrix Matrix< ElementType >::operator* (const Matrix< ElementType > & other) const
Matrix multiplication.
template<typename ElementType > Matrix& Matrix< ElementType >::hadarmard (const Matrix< ElementType > & other) noexcept
Does a hadarmard product with the receiver and other and stores the result in the receiver.
Referenced by Matrix< ElementType >::hadarmard().
template<typename ElementType > static Matrix Matrix< ElementType >::hadarmard (const Matrix< ElementType > & a, const Matrix< ElementType > & b) static
Does a hadarmard product with a and b returns the result.
References Matrix< ElementType >::hadarmard().
template<typename ElementType > static bool Matrix< ElementType >::compare (const Matrix< ElementType > & a, const Matrix< ElementType > & b, ElementType tolerance = 0) static noexcept
Compare to matrices with a given tolerance.
Referenced by Matrix< ElementType >::operator==().
template<typename ElementType > bool Matrix< ElementType >::operator== (const Matrix< ElementType > & other) const noexcept
References Matrix< ElementType >::compare().
template<typename ElementType > bool Matrix< ElementType >::isSquare () const noexcept
Tells if the matrix is a square matrix.
template<typename ElementType > bool Matrix< ElementType >::isVector () const noexcept
Tells if the matrix is a vector.
References Matrix< ElementType >::isOneColumnVector(), and Matrix< ElementType >::isOneRowVector().
template<typename ElementType > bool Matrix< ElementType >::isOneColumnVector () const noexcept
Tells if the matrix is a one column vector.
Referenced by Matrix< ElementType >::isVector().
template<typename ElementType > bool Matrix< ElementType >::isOneRowVector () const noexcept
Tells if the matrix is a one row vector.
Referenced by Matrix< ElementType >::isVector().
template<typename ElementType > bool Matrix< ElementType >::isNullMatrix () const noexcept
Tells if the matrix is a null matrix.
template<typename ElementType > bool Matrix< ElementType >::solve (Matrix< ElementType > & b) const noexcept
Solves a linear system of equations represented by this object and the argument b, using various algorithms depending on the size of the arguments.
The matrix must be a square matrix N times N, and b must be a vector N times 1, with the coefficients of b. After the execution of the algorithm, the vector b will contain the solution.
Returns true if the linear system of euqations was successfully solved.
template<typename ElementType > String Matrix< ElementType >::toString () const
Returns a String displaying in a convenient way the matrix contents.
template<typename ElementType > ElementType* Matrix< ElementType >::begin () noexcept
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin().
Referenced by Matrix< ElementType >::end(), and Matrix< ElementType >::operator*=().
template<typename ElementType > ElementType* Matrix< ElementType >::end () noexcept
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end().
Referenced by Matrix< ElementType >::operator*=().
template<typename ElementType > const ElementType* Matrix< ElementType >::begin () const noexcept
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference().
template<typename ElementType > const ElementType* Matrix< ElementType >::end () const noexcept
References Matrix< ElementType >::begin(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
class Polynomial
template<typename FloatingType>
class Polynomial< FloatingType >
A class representing a polynomial.
Public Member Functions
Polynomial ()
Creates a new polynomial which will always evaluate to zero.
Polynomial (const FloatingType *coefficients, int numCoefficients)
Creates a new polynomial with given coefficients.
Polynomial (const Polynomial &)=default
Creates a copy of another polynomial.
Polynomial (Polynomial &&)=default
Creates a copy of another polynomial.
Polynomial & operator= (const Polynomial &)=default
Creates a copy of another polynomial.
Polynomial & operator= (Polynomial &&)=default
Creates a copy of another polynomial.
template<typename TypeToCreateFrom >
Polynomial (const std::initializer_list< TypeToCreateFrom > &items)
Creates a new polynomial with coefficients by a C++11 initializer list.
FloatingType operator[] (int index) const noexcept
Returns a single coefficient of the receiver for reading.
FloatingType & operator[] (int index) noexcept
Returns a single coefficient of the receiver for modifying.
FloatingType operator() (FloatingType x) const noexcept
Evaluates the value of the polynomial at a single point x.
int getOrder () noexcept
Returns the order of the polynomial.
Polynomial< FloatingType > withGain (double gain) const
Returns the polynomial with all its coefficients multiplied with a gain factor.
Polynomial< FloatingType > getSumWith (const Polynomial< FloatingType > &other) const
Returns the sum of this polynomial with another.
Polynomial< FloatingType > getProductWith (const Polynomial< FloatingType > &other) const
computes the product of two polynomials and return the result
Constructor & Destructor Documentation
template<typename FloatingType> Polynomial< FloatingType >::Polynomial ()
Creates a new polynomial which will always evaluate to zero.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
template<typename FloatingType> Polynomial< FloatingType >::Polynomial (const FloatingType * coefficients, int numCoefficients)
Creates a new polynomial with given coefficients.
Parameters
numCoefficients The number of coefficients stored in coefficients. This is also the order of the returned polynomial.
coefficients The coefficients which will be used by the newly created polynomial. The Polynomial class will keep a private copy of the coefficients.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::isEmpty(), and jassert.
template<typename FloatingType> Polynomial< FloatingType >::Polynomial (const Polynomial< FloatingType > &) default
Creates a copy of another polynomial.
template<typename FloatingType> Polynomial< FloatingType >::Polynomial (Polynomial< FloatingType > &&) default
Creates a copy of another polynomial.
template<typename FloatingType> template<typename TypeToCreateFrom > Polynomial< FloatingType >::Polynomial (const std::initializer_list< TypeToCreateFrom > & items)
Creates a new polynomial with coefficients by a C++11 initializer list.
This function can be used in the following way: Polynomial<float> p ({0.5f, -0.3f, 0.2f});
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::isEmpty(), and jassert.
Member Function Documentation
template<typename FloatingType> Polynomial& Polynomial< FloatingType >::operator= (const Polynomial< FloatingType > &) default
Creates a copy of another polynomial.
template<typename FloatingType> Polynomial& Polynomial< FloatingType >::operator= (Polynomial< FloatingType > &&) default
Creates a copy of another polynomial.
template<typename FloatingType> FloatingType Polynomial< FloatingType >::operator[] (int index) const noexcept
Returns a single coefficient of the receiver for reading.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked().
template<typename FloatingType> FloatingType& Polynomial< FloatingType >::operator[] (int index) noexcept
Returns a single coefficient of the receiver for modifying.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference().
template<typename FloatingType> FloatingType Polynomial< FloatingType >::operator() (FloatingType x) const noexcept
Evaluates the value of the polynomial at a single point x.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<typename FloatingType> int Polynomial< FloatingType >::getOrder () noexcept
Returns the order of the polynomial.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<typename FloatingType> Polynomial<FloatingType> Polynomial< FloatingType >::withGain (double gain) const
Returns the polynomial with all its coefficients multiplied with a gain factor.
template<typename FloatingType> Polynomial<FloatingType> Polynomial< FloatingType >::getSumWith (const Polynomial< FloatingType > & other) const
Returns the sum of this polynomial with another.
References Polynomial< FloatingType >::getSumWith(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by Polynomial< FloatingType >::getSumWith().
template<typename FloatingType> Polynomial<FloatingType> Polynomial< FloatingType >::getProductWith (const Polynomial< FloatingType > & other) const
computes the product of two polynomials and return the result
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick(), jmax(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
struct SpecialFunctions
Contains miscellaneous filter design and windowing functions.
Static Public Member Functions
static double besselI0 (double x) noexcept
Computes the modified Bessel function of the first kind I0 for a given double value x.
static void ellipticIntegralK (double k, double &K, double &Kp) noexcept
Computes the complete elliptic integral of the first kind K for a given double value k, and the associated complete elliptic integral of the first kind Kp for the complementary modulus of k.
static Complex< double > cde (Complex< double > u, double k) noexcept
Computes the Jacobian elliptic function cd for the elliptic modulus k and the quarter-period units u.
static Complex< double > sne (Complex< double > u, double k) noexcept
Computes the Jacobian elliptic function sn for the elliptic modulus k and the quarter-period units u.
static Complex< double > asne (Complex< double > w, double k) noexcept
Computes the inverse of the Jacobian elliptic function sn for the elliptic modulus k and the quarter-period units u.
Member Function Documentation
static double SpecialFunctions::besselI0 (double x) static noexcept
Computes the modified Bessel function of the first kind I0 for a given double value x.
Modified Bessel functions are useful to solve various mathematical problems involving differential equations.
static void SpecialFunctions::ellipticIntegralK (double k, double & K, double & Kp) static noexcept
Computes the complete elliptic integral of the first kind K for a given double value k, and the associated complete elliptic integral of the first kind Kp for the complementary modulus of k.
static Complex<double> SpecialFunctions::cde (Complex< double > u, double k) static noexcept
Computes the Jacobian elliptic function cd for the elliptic modulus k and the quarter-period units u.
static Complex<double> SpecialFunctions::sne (Complex< double > u, double k) static noexcept
Computes the Jacobian elliptic function sn for the elliptic modulus k and the quarter-period units u.
static Complex<double> SpecialFunctions::asne (Complex< double > w, double k) static noexcept
Computes the inverse of the Jacobian elliptic function sn for the elliptic modulus k and the quarter-period units u.