JUCE: mouse
mouse
juce_gui_basics
Classes
class ComponentDragger
An object to take care of the logic for dragging components around with the mouse.
class DragAndDropContainer
Enables drag-and-drop behaviour for a component and all its sub-components.
class DragAndDropTarget
Components derived from this class can have things dropped onto them by a DragAndDropContainer.
class FileDragAndDropTarget
Components derived from this class can have files dropped onto them by an external application.
class LassoSource< SelectableItemType >
A class used by the LassoComponent to manage the things that it selects.
class LassoComponent< SelectableItemType >
A component that acts as a rectangular selection region, which you drag with the mouse to select groups of objects (in conjunction with a SelectedItemSet).
class MouseCursor
Represents a mouse cursor image.
class MouseEvent
Contains position and status information about a mouse event.
struct MouseWheelDetails
Contains status information about a mouse wheel event.
struct PenDetails
Contains status information about a pen event.
class MouseInactivityDetector
This object watches for mouse-events happening within a component, and if the mouse remains still for long enough, triggers an event to indicate that it has become inactive.
class MouseInputSource
Represents a linear source of mouse events from a mouse device or individual finger in a multi-touch environment.
class MouseListener
A MouseListener can be registered with a component to receive callbacks about mouse events that happen to that component.
class SelectedItemSet< SelectableItemType >
Manages a list of selectable items.
class TextDragAndDropTarget
Components derived from this class can have text dropped onto them by an external application.
class TooltipClient
Components that want to use pop-up tooltips should implement this interface.
class SettableTooltipClient
An implementation of TooltipClient that stores the tooltip string and a method for changing it.
Detailed Description
Class Documentation
class ComponentDragger
An object to take care of the logic for dragging components around with the mouse.
Very easy to use - in your mouseDown() callback, call startDraggingComponent(), then in your mouseDrag() callback, call dragComponent().
When starting a drag, you can give it a ComponentBoundsConstrainer to use to limit the component's position and keep it on-screen.
e.g.
class MyDraggableComp
{
    ComponentDragger myDragger;
    void mouseDown (const MouseEvent& e)
    {
        myDragger.startDraggingComponent (this, e);
    }
    void mouseDrag (const MouseEvent& e)
    {
        myDragger.dragComponent (this, e, nullptr);
    }
};
Public Member Functions
ComponentDragger ()
Creates a ComponentDragger.
virtual ~ComponentDragger ()
Destructor.
void startDraggingComponent (Component *componentToDrag, const MouseEvent &e)
Call this from your component's mouseDown() method, to prepare for dragging.
void dragComponent (Component *componentToDrag, const MouseEvent &e, ComponentBoundsConstrainer *constrainer)
Call this from your mouseDrag() callback to move the component.
Constructor & Destructor Documentation
ComponentDragger::ComponentDragger ()
Creates a ComponentDragger.
virtual ComponentDragger::~ComponentDragger () virtual
Destructor.
Member Function Documentation
void ComponentDragger::startDraggingComponent (Component * componentToDrag, const MouseEvent & e)
Call this from your component's mouseDown() method, to prepare for dragging.
Parameters
componentToDrag the component that you want to drag
e the mouse event that is triggering the drag
See Also
dragComponent
void ComponentDragger::dragComponent (Component * componentToDrag, const MouseEvent & e, ComponentBoundsConstrainer * constrainer)
Call this from your mouseDrag() callback to move the component.
This will move the component, using the given constrainer object to check the new position.
Parameters
componentToDrag the component that you want to drag
e the current mouse-drag event
constrainer an optional constrainer object that should be used to apply limits to the component's position. Pass null if you don't want to contrain the movement.
See Also
startDraggingComponent
class DragAndDropContainer
Enables drag-and-drop behaviour for a component and all its sub-components.
For a component to be able to make or receive drag-and-drop events, one of its parent components must derive from this class. It's probably best for the top-level component to implement it.
Then to start a drag operation, any sub-component can just call the startDragging() method, and this object will take over, tracking the mouse and sending appropriate callbacks to any child components derived from DragAndDropTarget which the mouse moves over.
Note: If all that you need to do is to respond to files being drag-and-dropped from the operating system onto your component, you don't need any of these classes: you can do this simply by overriding FileDragAndDropTarget::filesDropped().
See Also
DragAndDropTarget
Public Member Functions
DragAndDropContainer ()
Creates a DragAndDropContainer.
virtual ~DragAndDropContainer ()
Destructor.
void startDragging (const var &sourceDescription, Component *sourceComponent, Image dragImage=Image(), bool allowDraggingToOtherJuceWindows=false, const Point< int > *imageOffsetFromMouse=nullptr)
Begins a drag-and-drop operation.
bool isDragAndDropActive () const
Returns true if something is currently being dragged.
var getCurrentDragDescription () const
Returns the description of the thing that's currently being dragged.
void setCurrentDragImage (const Image &newImage)
If a drag is in progress, this allows the image being shown to be dynamically updated.
Static Public Member Functions
static DragAndDropContainer * findParentDragContainerFor (Component *childComponent)
Utility to find the DragAndDropContainer for a given Component.
static bool performExternalDragDropOfFiles (const StringArray &files, bool canMoveFiles, Component *sourceComponent=nullptr)
This performs a synchronous drag-and-drop of a set of files to some external application.
static bool performExternalDragDropOfText (const String &text, Component *sourceComponent=nullptr)
This performs a synchronous drag-and-drop of a block of text to some external application.
Protected Member Functions
virtual bool shouldDropFilesWhenDraggedExternally (const DragAndDropTarget::SourceDetails &sourceDetails, StringArray &files, bool &canMoveFiles)
Override this if you want to be able to perform an external drag of a set of files when the user drags outside of this container component.
virtual bool shouldDropTextWhenDraggedExternally (const DragAndDropTarget::SourceDetails &sourceDetails, String &text)
Override this if you want to be able to perform an external drag of text when the user drags outside of this container component.
virtual void dragOperationStarted (const DragAndDropTarget::SourceDetails &)
Subclasses can override this to be told when a drag starts.
virtual void dragOperationEnded (const DragAndDropTarget::SourceDetails &)
Subclasses can override this to be told when a drag finishes.
Constructor & Destructor Documentation
DragAndDropContainer::DragAndDropContainer ()
Creates a DragAndDropContainer.
The object that derives from this class must also be a Component.
virtual DragAndDropContainer::~DragAndDropContainer () virtual
Destructor.
Member Function Documentation
void DragAndDropContainer::startDragging (const var & sourceDescription, Component * sourceComponent, Image dragImage = Image(), bool allowDraggingToOtherJuceWindows = false, const Point< int > * imageOffsetFromMouse = nullptr)
Begins a drag-and-drop operation.
This starts a drag-and-drop operation - call it when the user drags the mouse in your drag-source component, and this object will track mouse movements until the user lets go of the mouse button, and will send appropriate messages to DragAndDropTarget objects that the mouse moves over.
findParentDragContainerFor() is a handy method to call to find the drag container to use for a component.
Parameters
sourceDescription a string or value to use as the description of the thing being dragged - this will be passed to the objects that might be dropped-onto so they can decide whether they want to handle it
sourceComponent the component that is being dragged
dragImage the image to drag around underneath the mouse. If this is a null image, a snapshot of the sourceComponent will be used instead.
allowDraggingToOtherJuceWindows if true, the dragged component will appear as a desktop window, and can be dragged to DragAndDropTargets that are the children of components other than this one.
imageOffsetFromMouse if an image has been passed-in, this specifies the offset at which the image should be drawn from the mouse. If it isn't specified, then the image will be centred around the mouse. If an image hasn't been passed-in, this will be ignored.
bool DragAndDropContainer::isDragAndDropActive () const
Returns true if something is currently being dragged.
var DragAndDropContainer::getCurrentDragDescription () const
Returns the description of the thing that's currently being dragged.
If nothing's being dragged, this will return a null var, otherwise it'll return the var that was passed into startDragging().
See Also
startDragging
void DragAndDropContainer::setCurrentDragImage (const Image & newImage)
If a drag is in progress, this allows the image being shown to be dynamically updated.
static DragAndDropContainer* DragAndDropContainer::findParentDragContainerFor (Component * childComponent) static
Utility to find the DragAndDropContainer for a given Component.
This will search up this component's parent hierarchy looking for the first parent component which is a DragAndDropContainer.
It's useful when a component wants to call startDragging but doesn't know the DragAndDropContainer it should to use.
Obviously this may return nullptr if it doesn't find a suitable component.
static bool DragAndDropContainer::performExternalDragDropOfFiles (const StringArray & files, bool canMoveFiles, Component * sourceComponent = nullptr) static
This performs a synchronous drag-and-drop of a set of files to some external application.
You can call this function in response to a mouseDrag callback, and it will block, running its own internal message loop and tracking the mouse, while it uses a native operating system drag-and-drop operation to move or copy some files to another application.
Parameters
files a list of filenames to drag
canMoveFiles if true, the app that receives the files is allowed to move the files to a new location (if this is appropriate). If false, the receiver is expected to make a copy of them.
sourceComponent Normally, JUCE will assume that the component under the mouse is the source component of the drag, but you can use this parameter to override this.
Returns
true if the files were successfully dropped somewhere, or false if it was interrupted
See Also
performExternalDragDropOfText
static bool DragAndDropContainer::performExternalDragDropOfText (const String & text, Component * sourceComponent = nullptr) static
This performs a synchronous drag-and-drop of a block of text to some external application.
You can call this function in response to a mouseDrag callback, and it will block, running its own internal message loop and tracking the mouse, while it uses a native operating system drag-and-drop operation to move or copy some text to another application.
Parameters
text the text to copy
sourceComponent Normally, JUCE will assume that the component under the mouse is the source component of the drag, but you can use this parameter to override this.
Returns
true if the text was successfully dropped somewhere, or false if it was interrupted
See Also
performExternalDragDropOfFiles
virtual bool DragAndDropContainer::shouldDropFilesWhenDraggedExternally (const DragAndDropTarget::SourceDetails & sourceDetails, StringArray & files, bool & canMoveFiles) protected virtual
Override this if you want to be able to perform an external drag of a set of files when the user drags outside of this container component.
This method will be called when a drag operation moves outside the JUCE window, and if you want it to then perform a file drag-and-drop, add the filenames you want to the array passed in, and return true.
Parameters
sourceDetails information about the source of the drag operation
files on return, the filenames you want to drag
canMoveFiles on return, true if it's ok for the receiver to move the files; false if it must make a copy of them (see the performExternalDragDropOfFiles() method)
See Also
performExternalDragDropOfFiles, shouldDropTextWhenDraggedExternally
virtual bool DragAndDropContainer::shouldDropTextWhenDraggedExternally (const DragAndDropTarget::SourceDetails & sourceDetails, String & text) protected virtual
Override this if you want to be able to perform an external drag of text when the user drags outside of this container component.
This method will be called when a drag operation moves outside the JUCE window, and if you want it to then perform a text drag-and-drop, copy the text you want to be dragged into the argument provided and return true.
Parameters
sourceDetails information about the source of the drag operation
text on return, the text you want to drag
See Also
shouldDropFilesWhenDraggedExternally
virtual void DragAndDropContainer::dragOperationStarted (const DragAndDropTarget::SourceDetails &) protected virtual
Subclasses can override this to be told when a drag starts.
virtual void DragAndDropContainer::dragOperationEnded (const DragAndDropTarget::SourceDetails &) protected virtual
Subclasses can override this to be told when a drag finishes.
class DragAndDropTarget
Components derived from this class can have things dropped onto them by a DragAndDropContainer.
To create a component that can receive things drag-and-dropped by a DragAndDropContainer, derive your component from this class, and make sure that it is somewhere inside a DragAndDropContainer component.
Note: If all that you need to do is to respond to files being drag-and-dropped from the operating system onto your component, you don't need any of these classes: instead see the FileDragAndDropTarget class.
See Also
DragAndDropContainer, FileDragAndDropTarget
Public Member Functions
virtual ~DragAndDropTarget ()
Destructor.
virtual bool isInterestedInDragSource (const SourceDetails &dragSourceDetails)=0
Callback to check whether this target is interested in the type of object being dragged.
virtual void itemDragEnter (const SourceDetails &dragSourceDetails)
Callback to indicate that something is being dragged over this component.
virtual void itemDragMove (const SourceDetails &dragSourceDetails)
Callback to indicate that the user is dragging something over this component.
virtual void itemDragExit (const SourceDetails &dragSourceDetails)
Callback to indicate that something has been dragged off the edge of this component.
virtual void itemDropped (const SourceDetails &dragSourceDetails)=0
Callback to indicate that the user has dropped something onto this component.
virtual bool shouldDrawDragImageWhenOver ()
Overriding this allows the target to tell the drag container whether to draw the drag image while the cursor is over it.
Constructor & Destructor Documentation
virtual DragAndDropTarget::~DragAndDropTarget () virtual
Destructor.
Member Function Documentation
virtual bool DragAndDropTarget::isInterestedInDragSource (const SourceDetails & dragSourceDetails) pure virtual
Callback to check whether this target is interested in the type of object being dragged.
Parameters
dragSourceDetails contains information about the source of the drag operation.
Returns
true if this component wants to receive the other callbacks regarging this type of object; if it returns false, no other callbacks will be made.
Implemented in TreeView, and Toolbar.
virtual void DragAndDropTarget::itemDragEnter (const SourceDetails & dragSourceDetails) virtual
Callback to indicate that something is being dragged over this component.
This gets called when the user moves the mouse into this component while dragging something.
Use this callback as a trigger to make your component repaint itself to give the user feedback about whether the item can be dropped here or not.
Parameters
dragSourceDetails contains information about the source of the drag operation.
See Also
itemDragExit
Reimplemented in TreeView.
virtual void DragAndDropTarget::itemDragMove (const SourceDetails & dragSourceDetails) virtual
Callback to indicate that the user is dragging something over this component.
This gets called when the user moves the mouse over this component while dragging something. Normally overriding itemDragEnter() and itemDragExit() are enough, but this lets you know what happens in-between.
Parameters
dragSourceDetails contains information about the source of the drag operation.
Reimplemented in TreeView, and Toolbar.
virtual void DragAndDropTarget::itemDragExit (const SourceDetails & dragSourceDetails) virtual
Callback to indicate that something has been dragged off the edge of this component.
This gets called when the user moves the mouse out of this component while dragging something.
If you've used itemDragEnter() to repaint your component and give feedback, use this as a signal to repaint it in its normal state.
Parameters
dragSourceDetails contains information about the source of the drag operation.
See Also
itemDragEnter
Reimplemented in TreeView, and Toolbar.
virtual void DragAndDropTarget::itemDropped (const SourceDetails & dragSourceDetails) pure virtual
Callback to indicate that the user has dropped something onto this component.
When the user drops an item this get called, and you can use the description to work out whether your object wants to deal with it or not.
Note that after this is called, the itemDragExit method may not be called, so you should clean up in here if there's anything you need to do when the drag finishes.
Parameters
dragSourceDetails contains information about the source of the drag operation.
Implemented in TreeView, and Toolbar.
virtual bool DragAndDropTarget::shouldDrawDragImageWhenOver () virtual
Overriding this allows the target to tell the drag container whether to draw the drag image while the cursor is over it.
By default it returns true, but if you return false, then the normal drag image will not be shown when the cursor is over this target.
class FileDragAndDropTarget
Components derived from this class can have files dropped onto them by an external application.
See Also
DragAndDropContainer
Public Member Functions
virtual ~FileDragAndDropTarget ()
Destructor.
virtual bool isInterestedInFileDrag (const StringArray &files)=0
Callback to check whether this target is interested in the set of files being offered.
virtual void fileDragEnter (const StringArray &files, int x, int y)
Callback to indicate that some files are being dragged over this component.
virtual void fileDragMove (const StringArray &files, int x, int y)
Callback to indicate that the user is dragging some files over this component.
virtual void fileDragExit (const StringArray &files)
Callback to indicate that the mouse has moved away from this component.
virtual void filesDropped (const StringArray &files, int x, int y)=0
Callback to indicate that the user has dropped the files onto this component.
Constructor & Destructor Documentation
virtual FileDragAndDropTarget::~FileDragAndDropTarget () virtual
Destructor.
Member Function Documentation
virtual bool FileDragAndDropTarget::isInterestedInFileDrag (const StringArray & files) pure virtual
Callback to check whether this target is interested in the set of files being offered.
Note that this will be called repeatedly when the user is dragging the mouse around over your component, so don't do anything time-consuming in here, like opening the files to have a look inside them!
Parameters
files the set of (absolute) pathnames of the files that the user is dragging
Returns
true if this component wants to receive the other callbacks regarging this type of object; if it returns false, no other callbacks will be made.
Implemented in TreeView, FilenameComponent, and FileSearchPathListComponent.
virtual void FileDragAndDropTarget::fileDragEnter (const StringArray & files, int x, int y) virtual
Callback to indicate that some files are being dragged over this component.
This gets called when the user moves the mouse into this component while dragging.
Use this callback as a trigger to make your component repaint itself to give the user feedback about whether the files can be dropped here or not.
Parameters
files the set of (absolute) pathnames of the files that the user is dragging
x the mouse x position, relative to this component
y the mouse y position, relative to this component
Reimplemented in TreeView, and FilenameComponent.
virtual void FileDragAndDropTarget::fileDragMove (const StringArray & files, int x, int y) virtual
Callback to indicate that the user is dragging some files over this component.
This gets called when the user moves the mouse over this component while dragging. Normally overriding itemDragEnter() and itemDragExit() are enough, but this lets you know what happens in-between.
Parameters
files the set of (absolute) pathnames of the files that the user is dragging
x the mouse x position, relative to this component
y the mouse y position, relative to this component
Reimplemented in TreeView.
virtual void FileDragAndDropTarget::fileDragExit (const StringArray & files) virtual
Callback to indicate that the mouse has moved away from this component.
This gets called when the user moves the mouse out of this component while dragging the files.
If you've used fileDragEnter() to repaint your component and give feedback, use this as a signal to repaint it in its normal state.
Parameters
files the set of (absolute) pathnames of the files that the user is dragging
Reimplemented in TreeView, and FilenameComponent.
virtual void FileDragAndDropTarget::filesDropped (const StringArray & files, int x, int y) pure virtual
Callback to indicate that the user has dropped the files onto this component.
When the user drops the files, this get called, and you can use the files in whatever way is appropriate.
Note that after this is called, the fileDragExit method may not be called, so you should clean up in here if there's anything you need to do when the drag finishes.
Parameters
files the set of (absolute) pathnames of the files that the user is dragging
x the mouse x position, relative to this component
y the mouse y position, relative to this component
Implemented in TreeView, FilenameComponent, and FileSearchPathListComponent.
class LassoSource
template<class SelectableItemType>
class LassoSource< SelectableItemType >
A class used by the LassoComponent to manage the things that it selects.
This allows the LassoComponent to find out which items are within the lasso, and to change the list of selected items.
See Also
LassoComponent, SelectedItemSet
Public Member Functions
virtual ~LassoSource ()
Destructor.
virtual void findLassoItemsInArea (Array< SelectableItemType > &itemsFound, const Rectangle< int > &area)=0
Returns the set of items that lie within a given lassoable region.
virtual SelectedItemSet
< SelectableItemType > & getLassoSelection ()=0
Returns the SelectedItemSet that the lasso should update.
Constructor & Destructor Documentation
template<class SelectableItemType> virtual LassoSource< SelectableItemType >::~LassoSource () virtual
Destructor.
Member Function Documentation
template<class SelectableItemType> virtual void LassoSource< SelectableItemType >::findLassoItemsInArea (Array< SelectableItemType > & itemsFound, const Rectangle< int > & area) pure virtual
Returns the set of items that lie within a given lassoable region.
Your implementation of this method must find all the relevant items that lie within the given rectangle. and add them to the itemsFound array.
The coordinates are relative to the top-left of the lasso component's parent component. (i.e. they are the same as the size and position of the lasso component itself).
template<class SelectableItemType> virtual SelectedItemSet<SelectableItemType>& LassoSource< SelectableItemType >::getLassoSelection () pure virtual
Returns the SelectedItemSet that the lasso should update.
This set will be continuously updated by the LassoComponent as it gets dragged around, so make sure that you've got a ChangeListener attached to the set so that your UI objects will know when the selection changes and be able to update themselves appropriately.
Referenced by LassoComponent< SelectableItemType >::beginLasso().
class LassoComponent
template<class SelectableItemType>
class LassoComponent< SelectableItemType >
A component that acts as a rectangular selection region, which you drag with the mouse to select groups of objects (in conjunction with a SelectedItemSet).
To use one of these:
In your mouseDown or mouseDrag event, add the LassoComponent to your parent component, and call its beginLasso() method, giving it a suitable LassoSource object that it can use to find out which items are in the active area.
Each time your parent component gets a mouseDrag event, call dragLasso() to update the lasso's position - it will use its LassoSource to calculate and update the current selection.
After the drag has finished and you get a mouseUp callback, you should call endLasso() to clean up. This will make the lasso component invisible, and you can remove it from the parent component, or delete it.
The class takes into account the modifier keys that are being held down while the lasso is being dragged, so if shift is pressed, then any lassoed items will be added to the original selection; if ctrl or command is pressed, they will be xor'ed with any previously selected items.
See Also
LassoSource, SelectedItemSet
Public Types
enum ColourIds { lassoFillColourId = 0x1000440, lassoOutlineColourId = 0x1000441 }
A set of colour IDs to use to change the colour of various aspects of the label.
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusChanged() and focusLost() methods.
Public Member Functions
LassoComponent ()
Creates a Lasso component.
void beginLasso (const MouseEvent &e, LassoSource< SelectableItemType > *lassoSource)
Call this in your mouseDown event, to initialise a drag.
void dragLasso (const MouseEvent &e)
Call this in your mouseDrag event, to update the lasso's position.
void endLasso ()
Call this in your mouseUp event, after the lasso has been dragged.
void paint (Graphics &g) override
bool hitTest (int, int) override
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
virtual ~Component ()
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
virtual void visibilityChanged ()
Called when this component's visibility changes.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (int x, int y, int width, int height, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void parentHierarchyChanged ()
Called to indicate that the component's parents have changed.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
virtual void lookAndFeelChanged ()
Called to let the component react to a change in the look-and-feel setting.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparancy level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
virtual void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
virtual void mouseDown (const MouseEvent &event) override
Called when a mouse button is pressed.
virtual void mouseDrag (const MouseEvent &event) override
Called when the mouse is moved while a button is held down.
virtual void mouseUp (const MouseEvent &event) override
Called when a mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
virtual void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel) override
Called when the mouse-wheel is moved.
virtual void mouseMagnify (const MouseEvent &event, float scaleFactor)
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyPressed (const KeyPress &key)
Called when a key is pressed.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown () const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void resized ()
Called when this component's size has been changed.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourId, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourId, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourId)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourId) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
virtual MarkerList * getMarkers (bool xAxis)
Components can implement this method to provide a MarkerList.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
JUCE_DEPRECATED (Point< int > relativePositionToGlobal(Point< int >) const)
JUCE_DEPRECATED (Point< int > globalPositionToRelative(Point< int >) const)
JUCE_DEPRECATED (Point< int > relativePositionToOtherComponent(const Component *, Point< int >) const)
JUCE_DEPRECATED (void setBounds(const RelativeRectangle &))
JUCE_DEPRECATED (void setBounds(const String &))
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Member Enumeration Documentation
template<class SelectableItemType > enum LassoComponent::ColourIds
A set of colour IDs to use to change the colour of various aspects of the label.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
Note that you can also use the constants from TextEditor::ColourIds to change the colour of the text editor that is opened when a label is editable.
See Also
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator
lassoFillColourId
The colour to fill the lasso rectangle with.
lassoOutlineColourId
The colour to draw the outline with.
Constructor & Destructor Documentation
template<class SelectableItemType > LassoComponent< SelectableItemType >::LassoComponent ()
Creates a Lasso component.
Member Function Documentation
template<class SelectableItemType > void LassoComponent< SelectableItemType >::beginLasso (const MouseEvent & e, LassoSource< SelectableItemType > * lassoSource)
Call this in your mouseDown event, to initialise a drag.
Pass in a suitable LassoSource object which the lasso will use to find the items and change the selection.
After using this method to initialise the lasso, repeatedly call dragLasso() in your component's mouseDrag callback.
See Also
dragLasso, endLasso, LassoSource
References LassoSource< SelectableItemType >::getLassoSelection(), MouseEvent::getMouseDownPosition(), Component::getParentComponent(), jassert, and Component::setSize().
template<class SelectableItemType > void LassoComponent< SelectableItemType >::dragLasso (const MouseEvent & e)
Call this in your mouseDrag event, to update the lasso's position.
This must be repeatedly calling when the mouse is dragged, after you've first initialised the lasso with beginLasso().
This method takes into account the modifier keys that are being held down, so if shift is pressed, then the lassoed items will be added to any that were previously selected; if ctrl or command is pressed, then they will be xor'ed with previously selected items.
See Also
beginLasso, endLasso
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addArray(), Component::getBounds(), MouseEvent::getPosition(), ModifierKeys::isAltDown(), ModifierKeys::isCommandDown(), ModifierKeys::isShiftDown(), MouseEvent::mods, Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeValuesIn(), Component::setBounds(), and Component::setVisible().
template<class SelectableItemType > void LassoComponent< SelectableItemType >::endLasso ()
Call this in your mouseUp event, after the lasso has been dragged.
See Also
beginLasso, dragLasso
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clear(), and Component::setVisible().
template<class SelectableItemType > void LassoComponent< SelectableItemType >::paint (Graphics & g) override virtual
Reimplemented from Component.
References ExtraLookAndFeelBaseClasses::LassoComponentMethods::drawLasso(), Component::getLookAndFeel(), Component::isMouseButtonDownAnywhere(), and jassert.
template<class SelectableItemType > bool LassoComponent< SelectableItemType >::hitTest (int , int) override virtual
Reimplemented from Component.
class MouseCursor
Represents a mouse cursor image.
This object can either be used to represent one of the standard mouse cursor shapes, or a custom one generated from an image.
Public Types
enum StandardCursorType {
ParentCursor = 0, NoCursor, NormalCursor, WaitCursor,
IBeamCursor, CrosshairCursor, CopyingCursor, PointingHandCursor,
DraggingHandCursor, LeftRightResizeCursor, UpDownResizeCursor, UpDownLeftRightResizeCursor,
TopEdgeResizeCursor, BottomEdgeResizeCursor, LeftEdgeResizeCursor, RightEdgeResizeCursor,
TopLeftCornerResizeCursor, TopRightCornerResizeCursor, BottomLeftCornerResizeCursor, BottomRightCornerResizeCursor,
NumStandardCursorTypes
}
The set of available standard mouse cursors.
Public Member Functions
MouseCursor () noexcept
Creates the standard arrow cursor.
MouseCursor (StandardCursorType)
Creates one of the standard mouse cursor.
MouseCursor (const Image &image, int hotSpotX, int hotSpotY)
Creates a custom cursor from an image.
MouseCursor (const Image &image, int hotSpotX, int hotSpotY, float scaleFactor)
Creates a custom cursor from an image.
MouseCursor (const MouseCursor &)
Creates a copy of another cursor object.
MouseCursor & operator= (const MouseCursor &)
Copies this cursor from another object.
~MouseCursor ()
Destructor.
MouseCursor (MouseCursor &&) noexcept
Move constructor.
MouseCursor & operator= (MouseCursor &&) noexcept
Move assignment operator.
bool operator== (const MouseCursor &) const noexcept
Checks whether two mouse cursors are the same.
bool operator!= (const MouseCursor &) const noexcept
Checks whether two mouse cursors are the same.
bool operator== (StandardCursorType type) const noexcept
Checks whether this cursor is of the standard type mentioned.
bool operator!= (StandardCursorType type) const noexcept
Checks whether this cursor is of the standard type mentioned.
Static Public Member Functions
static void showWaitCursor ()
Makes the system show its default 'busy' cursor.
static void hideWaitCursor ()
If showWaitCursor has been called, this will return the mouse to its normal state.
Member Enumeration Documentation
enum MouseCursor::StandardCursorType
The set of available standard mouse cursors.
Enumerator
ParentCursor
Indicates that the component's parent's cursor should be used.
NoCursor
An invisible cursor.
NormalCursor
The stardard arrow cursor.
WaitCursor
The normal hourglass or spinning-beachball 'busy' cursor.
IBeamCursor
A vertical I-beam for positioning within text.
CrosshairCursor
A pair of crosshairs.
CopyingCursor
The normal arrow cursor, but with a "+" on it to indicate that you're dragging a copy of something.
PointingHandCursor
A hand with a pointing finger, for clicking on web-links.
DraggingHandCursor
An open flat hand for dragging heavy objects around.
LeftRightResizeCursor
An arrow pointing left and right.
UpDownResizeCursor
an arrow pointing up and down.
UpDownLeftRightResizeCursor
An arrow pointing up, down, left and right.
TopEdgeResizeCursor
A platform-specific cursor for resizing the top-edge of a window.
BottomEdgeResizeCursor
A platform-specific cursor for resizing the bottom-edge of a window.
LeftEdgeResizeCursor
A platform-specific cursor for resizing the left-edge of a window.
RightEdgeResizeCursor
A platform-specific cursor for resizing the right-edge of a window.
TopLeftCornerResizeCursor
A platform-specific cursor for resizing the top-left-corner of a window.
TopRightCornerResizeCursor
A platform-specific cursor for resizing the top-right-corner of a window.
BottomLeftCornerResizeCursor
A platform-specific cursor for resizing the bottom-left-corner of a window.
BottomRightCornerResizeCursor
A platform-specific cursor for resizing the bottom-right-corner of a window.
NumStandardCursorTypes
Constructor & Destructor Documentation
MouseCursor::MouseCursor () noexcept
Creates the standard arrow cursor.
MouseCursor::MouseCursor (StandardCursorType)
Creates one of the standard mouse cursor.
MouseCursor::MouseCursor (const Image & image, int hotSpotX, int hotSpotY)
Creates a custom cursor from an image.
Parameters
image the image to use for the cursor - if this is bigger than the system can manage, it might get scaled down first, and might also have to be turned to black-and-white if it can't do colour cursors.
hotSpotX the x position of the cursor's hotspot within the image
hotSpotY the y position of the cursor's hotspot within the image
MouseCursor::MouseCursor (const Image & image, int hotSpotX, int hotSpotY, float scaleFactor)
Creates a custom cursor from an image.
Parameters
image the image to use for the cursor - if this is bigger than the system can manage, it might get scaled down first, and might also have to be turned to black-and-white if it can't do colour cursors.
hotSpotX the x position of the cursor's hotspot within the image
hotSpotY the y position of the cursor's hotspot within the image
scaleFactor the factor by which this image is larger than the target screen size of the cursor.
MouseCursor::MouseCursor (const MouseCursor &)
Creates a copy of another cursor object.
MouseCursor::~MouseCursor ()
Destructor.
MouseCursor::MouseCursor (MouseCursor &&) noexcept
Move constructor.
Member Function Documentation
MouseCursor& MouseCursor::operator= (const MouseCursor &)
Copies this cursor from another object.
MouseCursor& MouseCursor::operator= (MouseCursor &&) noexcept
Move assignment operator.
bool MouseCursor::operator== (const MouseCursor &) const noexcept
Checks whether two mouse cursors are the same.
For custom cursors, two cursors created from the same image won't be recognised as the same, only MouseCursor objects that have been copied from the same object.
bool MouseCursor::operator!= (const MouseCursor &) const noexcept
Checks whether two mouse cursors are the same.
For custom cursors, two cursors created from the same image won't be recognised as the same, only MouseCursor objects that have been copied from the same object.
bool MouseCursor::operator== (StandardCursorType type) const noexcept
Checks whether this cursor is of the standard type mentioned.
bool MouseCursor::operator!= (StandardCursorType type) const noexcept
Checks whether this cursor is of the standard type mentioned.
static void MouseCursor::showWaitCursor () static
Makes the system show its default 'busy' cursor.
This will turn the system cursor to an hourglass or spinning beachball until the next time the mouse is moved, or hideWaitCursor() is called.
This is handy if the message loop is about to block for a couple of seconds while busy and you want to give the user feedback about this.
static void MouseCursor::hideWaitCursor () static
If showWaitCursor has been called, this will return the mouse to its normal state.
This will look at what component is under the mouse, and update the cursor to be the correct one for that component.
See Also
showWaitCursor
class MouseEvent
Contains position and status information about a mouse event.
See Also
MouseListener, Component::mouseMove, Component::mouseEnter, Component::mouseExit, Component::mouseDown, Component::mouseUp, Component::mouseDrag
Public Member Functions
MouseEvent (MouseInputSource source, Point< float > position, ModifierKeys modifiers, float pressure, float orientation, float rotation, float tiltX, float tiltY, Component *eventComponent, Component *originator, Time eventTime, Point< float > mouseDownPos, Time mouseDownTime, int numberOfClicks, bool mouseWasDragged) noexcept
Creates a MouseEvent.
~MouseEvent () noexcept
Destructor.
int getMouseDownX () const noexcept
Returns the x coordinate of the last place that a mouse was pressed.
int getMouseDownY () const noexcept
Returns the y coordinate of the last place that a mouse was pressed.
Point< int > getMouseDownPosition () const noexcept
Returns the coordinates of the last place that a mouse was pressed.
int getDistanceFromDragStart () const noexcept
Returns the straight-line distance between where the mouse is now and where it was the last time the button was pressed.
int getDistanceFromDragStartX () const noexcept
Returns the difference between the mouse's current x position and where it was when the button was last pressed.
int getDistanceFromDragStartY () const noexcept
Returns the difference between the mouse's current y position and where it was when the button was last pressed.
Point< int > getOffsetFromDragStart () const noexcept
Returns the difference between the mouse's current position and where it was when the button was last pressed.
bool mouseWasDraggedSinceMouseDown () const noexcept
Returns true if the user seems to be performing a drag gesture.
bool mouseWasClicked () const noexcept
Returns true if the mouse event is part of a click gesture rather than a drag.
int getNumberOfClicks () const noexcept
For a click event, the number of times the mouse was clicked in succession.
int getLengthOfMousePress () const noexcept
Returns the time that the mouse button has been held down for.
bool isPressureValid () const noexcept
Returns true if the pressure value for this event is meaningful.
bool isOrientationValid () const noexcept
Returns true if the orientation value for this event is meaningful.
bool isRotationValid () const noexcept
Returns true if the rotation value for this event is meaningful.
bool isTiltValid (bool tiltX) const noexcept
Returns true if the current tilt value (either x- or y-axis) is meaningful.
Point< int > getPosition () const noexcept
The position of the mouse when the event occurred.
int getScreenX () const
Returns the mouse x position of this event, in global screen coordinates.
int getScreenY () const
Returns the mouse y position of this event, in global screen coordinates.
Point< int > getScreenPosition () const
Returns the mouse position of this event, in global screen coordinates.
int getMouseDownScreenX () const
Returns the x coordinate at which the mouse button was last pressed.
int getMouseDownScreenY () const
Returns the y coordinate at which the mouse button was last pressed.
Point< int > getMouseDownScreenPosition () const
Returns the coordinates at which the mouse button was last pressed.
MouseEvent getEventRelativeTo (Component *newComponent) const noexcept
Creates a version of this event that is relative to a different component.
MouseEvent withNewPosition (Point< float > newPosition) const noexcept
Creates a copy of this event with a different position.
MouseEvent withNewPosition (Point< int > newPosition) const noexcept
Creates a copy of this event with a different position.
Static Public Member Functions
static void setDoubleClickTimeout (int timeOutMilliseconds) noexcept
Changes the application-wide setting for the double-click time limit.
static int getDoubleClickTimeout () noexcept
Returns the application-wide setting for the double-click time limit.
Public Attributes
const Point< float > position
The position of the mouse when the event occurred.
const int x
The x-position of the mouse when the event occurred.
const int y
The y-position of the mouse when the event occurred.
const ModifierKeys mods
The key modifiers associated with the event.
const float pressure
The pressure of the touch or stylus for this event.
const float orientation
The orientation of the touch input for this event in radians where 0 indicates a touch aligned with the x-axis and pointing from left to right; increasing values indicate rotation in the clockwise direction.
const float rotation
The rotation of the pen device for this event in radians.
const float tiltX
The tilt of the pen device along the x-axis between -1.0 and 1.0.
const float tiltY
The tilt of the pen device along the y-axis between -1.0 and 1.0.
Component *const eventComponent
The component that this event applies to.
Component *const originalComponent
The component that the event first occurred on.
const Time eventTime
The time that this mouse-event occurred.
const Time mouseDownTime
The time that the corresponding mouse-down event occurred.
MouseInputSource source
The source device that generated this event.
Constructor & Destructor Documentation
MouseEvent::MouseEvent (MouseInputSource source, Point< float > position, ModifierKeys modifiers, float pressure, float orientation, float rotation, float tiltX, float tiltY, Component * eventComponent, Component * originator, Time eventTime, Point< float > mouseDownPos, Time mouseDownTime, int numberOfClicks, bool mouseWasDragged) noexcept
Creates a MouseEvent.
Normally an application will never need to use this.
Parameters
source the source that's invoking the event
position the position of the mouse, relative to the component that is passed-in
modifiers the key modifiers at the time of the event
pressure the pressure of the touch or stylus, in the range 0 to 1. Devices that do not support force information may return 0.0, 1.0, or a negative value, depending on the platform
orientation the orientation of the touch input for this event in radians. The default is 0
rotation the rotation of the pen device for this event in radians. The default is 0
tiltX the tilt of the pen device along the x-axis between -1.0 and 1.0. The default is 0
tiltY the tilt of the pen device along the y-axis between -1.0 and 1.0. The default is 0
eventComponent the component that the mouse event applies to
originator the component that originally received the event
eventTime the time the event happened
mouseDownPos the position of the corresponding mouse-down event (relative to the component that is passed-in). If there isn't a corresponding mouse-down (e.g. for a mouse-move), this will just be the same as the current mouse-x position.
mouseDownTime the time at which the corresponding mouse-down event happened If there isn't a corresponding mouse-down (e.g. for a mouse-move), this will just be the same as the current mouse-event time.
numberOfClicks how many clicks, e.g. a double-click event will be 2, a triple-click will be 3, etc
mouseWasDragged whether the mouse has been dragged significantly since the previous mouse-down
MouseEvent::~MouseEvent () noexcept
Destructor.
Member Function Documentation
int MouseEvent::getMouseDownX () const noexcept
Returns the x coordinate of the last place that a mouse was pressed.
The coordinate is relative to the component specified in MouseEvent::component.
See Also
getDistanceFromDragStart, getDistanceFromDragStartX, mouseWasDraggedSinceMouseDown
int MouseEvent::getMouseDownY () const noexcept
Returns the y coordinate of the last place that a mouse was pressed.
The coordinate is relative to the component specified in MouseEvent::component.
See Also
getDistanceFromDragStart, getDistanceFromDragStartX, mouseWasDraggedSinceMouseDown
Point<int> MouseEvent::getMouseDownPosition () const noexcept
Returns the coordinates of the last place that a mouse was pressed.
The coordinates are relative to the component specified in MouseEvent::component.
See Also
getDistanceFromDragStart, getDistanceFromDragStartX, mouseWasDraggedSinceMouseDown
Referenced by LassoComponent< SelectableItemType >::beginLasso().
int MouseEvent::getDistanceFromDragStart () const noexcept
Returns the straight-line distance between where the mouse is now and where it was the last time the button was pressed.
This is quite handy for things like deciding whether the user has moved far enough for it to be considered a drag operation.
See Also
getDistanceFromDragStartX
int MouseEvent::getDistanceFromDragStartX () const noexcept
Returns the difference between the mouse's current x position and where it was when the button was last pressed.
See Also
getDistanceFromDragStart
int MouseEvent::getDistanceFromDragStartY () const noexcept
Returns the difference between the mouse's current y position and where it was when the button was last pressed.
See Also
getDistanceFromDragStart
Point<int> MouseEvent::getOffsetFromDragStart () const noexcept
Returns the difference between the mouse's current position and where it was when the button was last pressed.
See Also
getDistanceFromDragStart
bool MouseEvent::mouseWasDraggedSinceMouseDown () const noexcept
Returns true if the user seems to be performing a drag gesture.
This is only meaningful if called in either a mouseUp() or mouseDrag() method.
It will return true if the user has dragged the mouse more than a few pixels from the place where the mouse-down occurred.
Once they have dragged it far enough for this method to return true, it will continue to return true until the mouse-up, even if they move the mouse back to the same location at which the mouse-down happened. This means that it's very handy for objects that can either be clicked on or dragged, as you can use it in the mouseDrag() callback to ignore small movements they might make while trying to click.
bool MouseEvent::mouseWasClicked () const noexcept
Returns true if the mouse event is part of a click gesture rather than a drag.
This is effectively the opposite of mouseWasDraggedSinceMouseDown()
int MouseEvent::getNumberOfClicks () const noexcept
For a click event, the number of times the mouse was clicked in succession.
So for example a double-click event will return 2, a triple-click 3, etc.
int MouseEvent::getLengthOfMousePress () const noexcept
Returns the time that the mouse button has been held down for.
If called from a mouseDrag or mouseUp callback, this will return the number of milliseconds since the corresponding mouseDown event occurred. If called in other contexts, e.g. a mouseMove, then the returned value may be 0 or an undefined value.
bool MouseEvent::isPressureValid () const noexcept
Returns true if the pressure value for this event is meaningful.
bool MouseEvent::isOrientationValid () const noexcept
Returns true if the orientation value for this event is meaningful.
bool MouseEvent::isRotationValid () const noexcept
Returns true if the rotation value for this event is meaningful.
bool MouseEvent::isTiltValid (bool tiltX) const noexcept
Returns true if the current tilt value (either x- or y-axis) is meaningful.
Point<int> MouseEvent::getPosition () const noexcept
The position of the mouse when the event occurred.
This position is relative to the top-left of the component to which the event applies (as indicated by the MouseEvent::eventComponent field).
For a floating-point position, see MouseEvent::position
Referenced by LassoComponent< SelectableItemType >::dragLasso().
int MouseEvent::getScreenX () const
Returns the mouse x position of this event, in global screen coordinates.
The coordinates are relative to the top-left of the main monitor.
See Also
getScreenPosition
int MouseEvent::getScreenY () const
Returns the mouse y position of this event, in global screen coordinates.
The coordinates are relative to the top-left of the main monitor.
See Also
getScreenPosition
Point<int> MouseEvent::getScreenPosition () const
Returns the mouse position of this event, in global screen coordinates.
The coordinates are relative to the top-left of the main monitor.
See Also
getMouseDownScreenPosition
int MouseEvent::getMouseDownScreenX () const
Returns the x coordinate at which the mouse button was last pressed.
The coordinates are relative to the top-left of the main monitor.
See Also
getMouseDownScreenPosition
int MouseEvent::getMouseDownScreenY () const
Returns the y coordinate at which the mouse button was last pressed.
The coordinates are relative to the top-left of the main monitor.
See Also
getMouseDownScreenPosition
Point<int> MouseEvent::getMouseDownScreenPosition () const
Returns the coordinates at which the mouse button was last pressed.
The coordinates are relative to the top-left of the main monitor.
See Also
getScreenPosition
MouseEvent MouseEvent::getEventRelativeTo (Component * newComponent) const noexcept
Creates a version of this event that is relative to a different component.
The x and y positions of the event that is returned will have been adjusted to be relative to the new component. The component pointer that is passed-in must not be null.
MouseEvent MouseEvent::withNewPosition (Point< float > newPosition) const noexcept
Creates a copy of this event with a different position.
All other members of the event object are the same, but the x and y are replaced with these new values.
MouseEvent MouseEvent::withNewPosition (Point< int > newPosition) const noexcept
Creates a copy of this event with a different position.
All other members of the event object are the same, but the x and y are replaced with these new values.
static void MouseEvent::setDoubleClickTimeout (int timeOutMilliseconds) static noexcept
Changes the application-wide setting for the double-click time limit.
This is the maximum length of time between mouse-clicks for it to be considered a double-click. It's used by the Component class.
See Also
getDoubleClickTimeout, MouseListener::mouseDoubleClick
static int MouseEvent::getDoubleClickTimeout () static noexcept
Returns the application-wide setting for the double-click time limit.
This is the maximum length of time between mouse-clicks for it to be considered a double-click. It's used by the Component class.
See Also
setDoubleClickTimeout, MouseListener::mouseDoubleClick
Member Data Documentation
const Point<float> MouseEvent::position
The position of the mouse when the event occurred.
This value is relative to the top-left of the component to which the event applies (as indicated by the MouseEvent::eventComponent field).
This is a more accurate floating-point version of the position returned by getPosition() and the integer x and y member variables.
const int MouseEvent::x
The x-position of the mouse when the event occurred.
This value is relative to the top-left of the component to which the event applies (as indicated by the MouseEvent::eventComponent field).
For a floating-point coordinate, see MouseEvent::position
const int MouseEvent::y
The y-position of the mouse when the event occurred.
This value is relative to the top-left of the component to which the event applies (as indicated by the MouseEvent::eventComponent field).
For a floating-point coordinate, see MouseEvent::position
const ModifierKeys MouseEvent::mods
The key modifiers associated with the event.
This will let you find out which mouse buttons were down, as well as which modifier keys were held down.
When used for mouse-up events, this will indicate the state of the mouse buttons just before they were released, so that you can tell which button they let go of.
Referenced by LassoComponent< SelectableItemType >::dragLasso().
const float MouseEvent::pressure
The pressure of the touch or stylus for this event.
The range is 0 (soft) to 1 (hard). If the input device doesn't provide any pressure data, it may return a negative value here, or 0.0 or 1.0, depending on the platform.
const float MouseEvent::orientation
The orientation of the touch input for this event in radians where 0 indicates a touch aligned with the x-axis and pointing from left to right; increasing values indicate rotation in the clockwise direction.
The default is 0.
const float MouseEvent::rotation
The rotation of the pen device for this event in radians.
Indicates the clockwise rotation, or twist, of the pen. The default is 0.
const float MouseEvent::tiltX
The tilt of the pen device along the x-axis between -1.0 and 1.0.
A positive value indicates a tilt to the right. The default is 0.
const float MouseEvent::tiltY
The tilt of the pen device along the y-axis between -1.0 and 1.0.
A positive value indicates a tilt toward the user. The default is 0.
Component* const MouseEvent::eventComponent
The component that this event applies to.
This is usually the component that the mouse was over at the time, but for mouse-drag events the mouse could actually be over a different component and the events are still sent to the component that the button was originally pressed on.
The x and y member variables are relative to this component's position.
If you use getEventRelativeTo() to retarget this object to be relative to a different component, this pointer will be updated, but originalComponent remains unchanged.
See Also
originalComponent
Component* const MouseEvent::originalComponent
The component that the event first occurred on.
If you use getEventRelativeTo() to retarget this object to be relative to a different component, this value remains unchanged to indicate the first component that received it.
See Also
eventComponent
const Time MouseEvent::eventTime
The time that this mouse-event occurred.
const Time MouseEvent::mouseDownTime
The time that the corresponding mouse-down event occurred.
MouseInputSource MouseEvent::source
The source device that generated this event.
struct MouseWheelDetails
Contains status information about a mouse wheel event.
See Also
MouseListener, MouseEvent
Public Attributes
float deltaX
The amount that the wheel has been moved in the X axis.
float deltaY
The amount that the wheel has been moved in the Y axis.
bool isReversed
Indicates whether the user has reversed the direction of the wheel.
bool isSmooth
If true, then the wheel has continuous, un-stepped motion.
bool isInertial
If true, then this event is part of the intertial momentum phase that follows the wheel being released.
Member Data Documentation
float MouseWheelDetails::deltaX
The amount that the wheel has been moved in the X axis.
If isReversed is true, then a negative deltaX means that the wheel has been pushed physically to the left. If isReversed is false, then a negative deltaX means that the wheel has been pushed physically to the right.
float MouseWheelDetails::deltaY
The amount that the wheel has been moved in the Y axis.
If isReversed is true, then a negative deltaY means that the wheel has been pushed physically upwards. If isReversed is false, then a negative deltaY means that the wheel has been pushed physically downwards.
bool MouseWheelDetails::isReversed
Indicates whether the user has reversed the direction of the wheel.
See deltaX and deltaY for an explanation of the effects of this value.
bool MouseWheelDetails::isSmooth
If true, then the wheel has continuous, un-stepped motion.
bool MouseWheelDetails::isInertial
If true, then this event is part of the intertial momentum phase that follows the wheel being released.
struct PenDetails
Contains status information about a pen event.
See Also
MouseListener, MouseEvent
Public Attributes
float rotation
The rotation of the pen device in radians.
float tiltX
Indicates the angle of tilt of the pointer in a range of -1.0 to 1.0 along the x-axis where a positive value indicates a tilt to the right.
float tiltY
Indicates the angle of tilt of the pointer in a range of -1.0 to 1.0 along the y-axis where a positive value indicates a tilt toward the user.
Member Data Documentation
float PenDetails::rotation
The rotation of the pen device in radians.
Indicates the clockwise rotation, or twist, of the pen. The default is 0.
float PenDetails::tiltX
Indicates the angle of tilt of the pointer in a range of -1.0 to 1.0 along the x-axis where a positive value indicates a tilt to the right.
The default is 0.
float PenDetails::tiltY
Indicates the angle of tilt of the pointer in a range of -1.0 to 1.0 along the y-axis where a positive value indicates a tilt toward the user.
The default is 0.
class MouseInactivityDetector
This object watches for mouse-events happening within a component, and if the mouse remains still for long enough, triggers an event to indicate that it has become inactive.
You'd use this for situations where e.g. you want to hide the mouse-cursor when the user's not actively using the mouse.
After creating an instance of this, use addListener to get callbacks when the activity status changes.
Public Member Functions
MouseInactivityDetector (Component &target)
Creates an inactivity watcher, attached to the given component.
~MouseInactivityDetector ()
Destructor.
void setDelay (int newDelayMilliseconds) noexcept
Sets the time for which the mouse must be still before the callback is triggered.
void setMouseMoveTolerance (int pixelsNeededToTrigger) noexcept
Sets the number of pixels by which the cursor is allowed to drift before it is considered to be actively moved.
void addListener (Listener *listener)
Registers a listener.
void removeListener (Listener *listener)
Removes a previously-registered listener.
Constructor & Destructor Documentation
MouseInactivityDetector::MouseInactivityDetector (Component & target)
Creates an inactivity watcher, attached to the given component.
The target component must not be deleted while this - it will be monitored for any mouse events in it or its child components.
MouseInactivityDetector::~MouseInactivityDetector ()
Destructor.
Member Function Documentation
void MouseInactivityDetector::setDelay (int newDelayMilliseconds) noexcept
Sets the time for which the mouse must be still before the callback is triggered.
void MouseInactivityDetector::setMouseMoveTolerance (int pixelsNeededToTrigger) noexcept
Sets the number of pixels by which the cursor is allowed to drift before it is considered to be actively moved.
void MouseInactivityDetector::addListener (Listener * listener)
Registers a listener.
void MouseInactivityDetector::removeListener (Listener * listener)
Removes a previously-registered listener.
class MouseInputSource
Represents a linear source of mouse events from a mouse device or individual finger in a multi-touch environment.
Each MouseEvent object contains a reference to the MouseInputSource that generated it. In an environment with a single mouse for input, all events will come from the same source, but in a multi-touch system, there may be multiple MouseInputSource obects active, each representing a stream of events coming from a particular finger.
Events coming from a single MouseInputSource are always sent in a fixed and predictable order: a mouseMove will never be called without a mouseEnter having been sent beforehand, the only events that can happen between a mouseDown and its corresponding mouseUp are mouseDrags, etc. When there are multiple touches arriving from multiple MouseInputSources, their event streams may arrive in an interleaved order, so you should use the getIndex() method to find out which finger each event came from.
See Also
MouseEvent
Public Types
enum InputSourceType { mouse, touch, pen }
Possible mouse input sources.
Public Member Functions
MouseInputSource (const MouseInputSource &) noexcept
MouseInputSource & operator= (const MouseInputSource &) noexcept
~MouseInputSource () noexcept
bool operator== (const MouseInputSource &other) const noexcept
bool operator!= (const MouseInputSource &other) const noexcept
MouseInputSource::InputSourceType getType () const noexcept
Returns the type of input source that this object represents.
bool isMouse () const noexcept
Returns true if this object represents a normal desk-based mouse device.
bool isTouch () const noexcept
Returns true if this object represents a source of touch events.
bool isPen () const noexcept
Returns true if this object represents a pen device.
bool canHover () const noexcept
Returns true if this source has an on-screen pointer that can hover over items without clicking them.
bool hasMouseWheel () const noexcept
Returns true if this source may have a scroll wheel.
int getIndex () const noexcept
Returns this source's index in the global list of possible sources.
bool isDragging () const noexcept
Returns true if this device is currently being pressed.
Point< float > getScreenPosition () const noexcept
Returns the last-known screen position of this source.
Point< float > getRawScreenPosition () const noexcept
Returns the last-known screen position of this source without any scaling applied.
ModifierKeys getCurrentModifiers () const noexcept
Returns a set of modifiers that indicate which buttons are currently held down on this device.
float getCurrentPressure () const noexcept
Returns the device's current touch or pen pressure.
float getCurrentOrientation () const noexcept
Returns the device's current orientation in radians.
float getCurrentRotation () const noexcept
Returns the device's current rotation.
float getCurrentTilt (bool tiltX) const noexcept
Returns the angle of tilt of the pointer in a range of -1.0 to 1.0 either in the x- or y-axis.
bool isPressureValid () const noexcept
Returns true if the current pressure value is meaningful.
bool isOrientationValid () const noexcept
Returns true if the current orientation value is meaningful.
bool isRotationValid () const noexcept
Returns true if the current rotation value is meaningful.
bool isTiltValid (bool tiltX) const noexcept
Returns true if the current tilt value (either x- or y-axis) is meaningful.
Component * getComponentUnderMouse () const
Returns the component that was last known to be under this pointer.
void triggerFakeMove () const
Tells the device to dispatch a mouse-move or mouse-drag event.
int getNumberOfMultipleClicks () const noexcept
Returns the number of clicks that should be counted as belonging to the current mouse event.
Time getLastMouseDownTime () const noexcept
Returns the time at which the last mouse-down occurred.
Point< float > getLastMouseDownPosition () const noexcept
Returns the screen position at which the last mouse-down occurred.
bool hasMouseMovedSignificantlySincePressed () const noexcept
Returns true if this mouse is currently down, and if it has been dragged more than a couple of pixels from the place it was pressed.
bool hasMouseCursor () const noexcept
Returns true if this input source uses a visible mouse cursor.
void showMouseCursor (const MouseCursor &cursor)
Changes the mouse cursor, (if there is one).
void hideCursor ()
Hides the mouse cursor (if there is one).
void revealCursor ()
Un-hides the mouse cursor if it was hidden by hideCursor().
void forceMouseCursorUpdate ()
Forces an update of the mouse cursor for whatever component it's currently over.
bool canDoUnboundedMovement () const noexcept
Returns true if this mouse can be moved indefinitely in any direction without running out of space.
void enableUnboundedMouseMovement (bool isEnabled, bool keepCursorVisibleUntilOffscreen=false) const
Allows the mouse to move beyond the edges of the screen.
bool isUnboundedMouseMovementEnabled () const
Returns true if this source is currently in "unbounded" mode.
void setScreenPosition (Point< float > newPosition)
Attempts to set this mouse pointer's screen position.
Static Public Attributes
static const float invalidPressure
A default value for pressure, which is used when a device doesn't support it, or for mouse-moves, mouse-ups, etc.
static const float invalidOrientation
A default value for orientation, which is used when a device doesn't support it.
static const float invalidRotation
A default value for rotation, which is used when a device doesn't support it.
static const float invalidTiltX
Default values for tilt, which are used when a device doesn't support it.
static const float invalidTiltY
Member Enumeration Documentation
enum MouseInputSource::InputSourceType
Possible mouse input sources.
Enumerator
mouse
touch
pen
Constructor & Destructor Documentation
MouseInputSource::MouseInputSource (const MouseInputSource &) noexcept
MouseInputSource::~MouseInputSource () noexcept
Member Function Documentation
MouseInputSource& MouseInputSource::operator= (const MouseInputSource &) noexcept
bool MouseInputSource::operator== (const MouseInputSource & other) const noexcept
bool MouseInputSource::operator!= (const MouseInputSource & other) const noexcept
MouseInputSource::InputSourceType MouseInputSource::getType () const noexcept
Returns the type of input source that this object represents.
bool MouseInputSource::isMouse () const noexcept
Returns true if this object represents a normal desk-based mouse device.
bool MouseInputSource::isTouch () const noexcept
Returns true if this object represents a source of touch events.
bool MouseInputSource::isPen () const noexcept
Returns true if this object represents a pen device.
bool MouseInputSource::canHover () const noexcept
Returns true if this source has an on-screen pointer that can hover over items without clicking them.
bool MouseInputSource::hasMouseWheel () const noexcept
Returns true if this source may have a scroll wheel.
int MouseInputSource::getIndex () const noexcept
Returns this source's index in the global list of possible sources.
If the system only has a single mouse, there will only be a single MouseInputSource with an index of 0.
If the system supports multi-touch input, then the index will represent a finger number, starting from 0. When the first touch event begins, it will have finger number 0, and then if a second touch happens while the first is still down, it will have index 1, etc.
bool MouseInputSource::isDragging () const noexcept
Returns true if this device is currently being pressed.
Point<float> MouseInputSource::getScreenPosition () const noexcept
Returns the last-known screen position of this source.
Point<float> MouseInputSource::getRawScreenPosition () const noexcept
Returns the last-known screen position of this source without any scaling applied.
ModifierKeys MouseInputSource::getCurrentModifiers () const noexcept
Returns a set of modifiers that indicate which buttons are currently held down on this device.
float MouseInputSource::getCurrentPressure () const noexcept
Returns the device's current touch or pen pressure.
The range is 0 (soft) to 1 (hard). If the input device doesn't provide any pressure data, it may return a negative value here, or 0.0 or 1.0, depending on the platform.
float MouseInputSource::getCurrentOrientation () const noexcept
Returns the device's current orientation in radians.
0 indicates a touch pointer aligned with the x-axis and pointing from left to right; increasing values indicate rotation in the clockwise direction. Only reported by a touch pointer.
float MouseInputSource::getCurrentRotation () const noexcept
Returns the device's current rotation.
Indicates the clockwise rotation, or twist, of the pointer in radians. The default is 0. Only reported by a pen pointer.
float MouseInputSource::getCurrentTilt (bool tiltX) const noexcept
Returns the angle of tilt of the pointer in a range of -1.0 to 1.0 either in the x- or y-axis.
The default is 0. If x-axis, a positive value indicates a tilt to the right and if y-axis, a positive value indicates a tilt toward the user. Only reported by a pen pointer.
bool MouseInputSource::isPressureValid () const noexcept
Returns true if the current pressure value is meaningful.
bool MouseInputSource::isOrientationValid () const noexcept
Returns true if the current orientation value is meaningful.
bool MouseInputSource::isRotationValid () const noexcept
Returns true if the current rotation value is meaningful.
bool MouseInputSource::isTiltValid (bool tiltX) const noexcept
Returns true if the current tilt value (either x- or y-axis) is meaningful.
Component* MouseInputSource::getComponentUnderMouse () const
Returns the component that was last known to be under this pointer.
void MouseInputSource::triggerFakeMove () const
Tells the device to dispatch a mouse-move or mouse-drag event.
This is asynchronous - the event will occur on the message thread.
int MouseInputSource::getNumberOfMultipleClicks () const noexcept
Returns the number of clicks that should be counted as belonging to the current mouse event.
So the mouse is currently down and it's the second click of a double-click, this will return 2.
Time MouseInputSource::getLastMouseDownTime () const noexcept
Returns the time at which the last mouse-down occurred.
Point<float> MouseInputSource::getLastMouseDownPosition () const noexcept
Returns the screen position at which the last mouse-down occurred.
bool MouseInputSource::hasMouseMovedSignificantlySincePressed () const noexcept
Returns true if this mouse is currently down, and if it has been dragged more than a couple of pixels from the place it was pressed.
bool MouseInputSource::hasMouseCursor () const noexcept
Returns true if this input source uses a visible mouse cursor.
void MouseInputSource::showMouseCursor (const MouseCursor & cursor)
Changes the mouse cursor, (if there is one).
void MouseInputSource::hideCursor ()
Hides the mouse cursor (if there is one).
void MouseInputSource::revealCursor ()
Un-hides the mouse cursor if it was hidden by hideCursor().
void MouseInputSource::forceMouseCursorUpdate ()
Forces an update of the mouse cursor for whatever component it's currently over.
bool MouseInputSource::canDoUnboundedMovement () const noexcept
Returns true if this mouse can be moved indefinitely in any direction without running out of space.
void MouseInputSource::enableUnboundedMouseMovement (bool isEnabled, bool keepCursorVisibleUntilOffscreen = false) const
Allows the mouse to move beyond the edges of the screen.
Calling this method when the mouse button is currently pressed will remove the cursor from the screen and allow the mouse to (seem to) move beyond the edges of the screen.
This means that the coordinates returned to mouseDrag() will be unbounded, and this can be used for things like custom slider controls or dragging objects around, where movement would be otherwise be limited by the mouse hitting the edges of the screen.
The unbounded mode is automatically turned off when the mouse button is released, or it can be turned off explicitly by calling this method again.
Parameters
isEnabled whether to turn this mode on or off
keepCursorVisibleUntilOffscreen if set to false, the cursor will immediately be hidden; if true, it will only be hidden when it is moved beyond the edge of the screen
bool MouseInputSource::isUnboundedMouseMovementEnabled () const
Returns true if this source is currently in "unbounded" mode.
void MouseInputSource::setScreenPosition (Point< float > newPosition)
Attempts to set this mouse pointer's screen position.
Member Data Documentation
const float MouseInputSource::invalidPressure static
A default value for pressure, which is used when a device doesn't support it, or for mouse-moves, mouse-ups, etc.
Referenced by FakeMouseMoveGenerator::timerCallback().
const float MouseInputSource::invalidOrientation static
A default value for orientation, which is used when a device doesn't support it.
Referenced by FakeMouseMoveGenerator::timerCallback().
const float MouseInputSource::invalidRotation static
A default value for rotation, which is used when a device doesn't support it.
const float MouseInputSource::invalidTiltX static
Default values for tilt, which are used when a device doesn't support it.
const float MouseInputSource::invalidTiltY static
class MouseListener
A MouseListener can be registered with a component to receive callbacks about mouse events that happen to that component.
See Also
Component::addMouseListener, Component::removeMouseListener
Public Member Functions
virtual ~MouseListener ()
Destructor.
virtual void mouseMove (const MouseEvent &event)
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event)
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event)
Called when the mouse moves out of a component.
virtual void mouseDown (const MouseEvent &event)
Called when a mouse button is pressed.
virtual void mouseDrag (const MouseEvent &event)
Called when the mouse is moved while a button is held down.
virtual void mouseUp (const MouseEvent &event)
Called when a mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event)
Called when a mouse button has been double-clicked on a component.
virtual void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel)
Called when the mouse-wheel is moved.
Constructor & Destructor Documentation
virtual MouseListener::~MouseListener () virtual
Destructor.
Member Function Documentation
virtual void MouseListener::mouseMove (const MouseEvent & event) virtual
Called when the mouse moves inside a component.
If the mouse button isn't pressed and the mouse moves over a component, this will be called to let the component react to this.
A component will always get a mouseEnter callback before a mouseMove.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseEnter, mouseExit, mouseDrag, contains
Reimplemented in Component, Slider, TableHeaderComponent, MidiKeyboardComponent, ResizableBorderComponent, and MenuBarComponent.
virtual void MouseListener::mouseEnter (const MouseEvent & event) virtual
Called when the mouse first enters a component.
If the mouse button isn't pressed and the mouse moves into a component, this will be called to let the component react to this.
When the mouse button is pressed and held down while being moved in or out of a component, no mouseEnter or mouseExit callbacks are made - only mouseDrag messages are sent to the component that the mouse was originally clicked on, until the button is released.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseExit, mouseDrag, mouseMove, contains
Reimplemented in Component, Button, TableHeaderComponent, MidiKeyboardComponent, ResizableBorderComponent, and MenuBarComponent.
virtual void MouseListener::mouseExit (const MouseEvent & event) virtual
Called when the mouse moves out of a component.
This will be called when the mouse moves off the edge of this component.
If the mouse button was pressed, and it was then dragged off the edge of the component and released, then this callback will happen when the button is released, after the mouseUp callback.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseEnter, mouseDrag, mouseMove, contains
Reimplemented in Component, Slider, Button, TableHeaderComponent, MidiKeyboardComponent, and MenuBarComponent.
virtual void MouseListener::mouseDown (const MouseEvent & event) virtual
Called when a mouse button is pressed.
The MouseEvent object passed in contains lots of methods for finding out which button was pressed, as well as which modifier keys (e.g. shift, ctrl) were held down at the time.
Once a button is held down, the mouseDrag method will be called when the mouse moves, until the button is released.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseUp, mouseDrag, mouseDoubleClick, contains
Reimplemented in Component, Slider, TextEditor, AlertWindow, Button, TableHeaderComponent, ComboBox, ScrollBar, ResizableWindow, CodeEditorComponent, Toolbar, MidiKeyboardComponent, ResizableBorderComponent, StretchableLayoutResizerBar, ResizableEdgeComponent, MenuBarComponent, and ResizableCornerComponent.
virtual void MouseListener::mouseDrag (const MouseEvent & event) virtual
Called when the mouse is moved while a button is held down.
When a mouse button is pressed inside a component, that component receives mouseDrag callbacks each time the mouse moves, even if the mouse strays outside the component's bounds.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseDown, mouseUp, mouseMove, contains, setDragRepeatInterval
Reimplemented in Component, Slider, TextEditor, AlertWindow, Button, TableHeaderComponent, ComboBox, ScrollBar, ResizableWindow, CodeEditorComponent, MidiKeyboardComponent, ResizableBorderComponent, StretchableLayoutResizerBar, ResizableEdgeComponent, MenuBarComponent, and ResizableCornerComponent.
virtual void MouseListener::mouseUp (const MouseEvent & event) virtual
Called when a mouse button is released.
A mouseUp callback is sent to the component in which a button was pressed even if the mouse is actually over a different component when the button is released.
The MouseEvent object passed in contains lots of methods for finding out which buttons were down just before they were released.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseDown, mouseDrag, mouseDoubleClick, contains
Reimplemented in Component, Slider, TextEditor, ListBox, Button, TableHeaderComponent, ComboBox, ScrollBar, ResizableWindow, CodeEditorComponent, Label, MidiKeyboardComponent, ResizableBorderComponent, ResizableEdgeComponent, MenuBarComponent, and ResizableCornerComponent.
virtual void MouseListener::mouseDoubleClick (const MouseEvent & event) virtual
Called when a mouse button has been double-clicked on a component.
The MouseEvent object passed in contains lots of methods for finding out which button was pressed, as well as which modifier keys (e.g. shift, ctrl) were held down at the time.
Parameters
event details about the position and status of the mouse event, including the source component in which it occurred
See Also
mouseDown, mouseUp
Reimplemented in Component, Slider, TextEditor, CodeEditorComponent, and Label.
virtual void MouseListener::mouseWheelMove (const MouseEvent & event, const MouseWheelDetails & wheel) virtual
Called when the mouse-wheel is moved.
This callback is sent to the component that the mouse is over when the wheel is moved.
If not overridden, a component will forward this message to its parent, so that parent components can collect mouse-wheel messages that happen to child components which aren't interested in them.
Parameters
event details about the mouse event
wheel details about the wheel movement
Reimplemented in Component, Slider, TextEditor, ListBox, ComboBox, ScrollBar, CodeEditorComponent, MidiKeyboardComponent, and Viewport.
class SelectedItemSet
template<class SelectableItemType>
class SelectedItemSet< SelectableItemType >
Manages a list of selectable items.
Use one of these to keep a track of things that the user has highlighted, like icons or things in a list.
The class is templated so that you can use it to hold either a set of pointers to objects, or a set of ID numbers or handles, for cases where each item may not always have a corresponding object.
To be informed when items are selected/deselected, register a ChangeListener with this object.
Public Types
typedef SelectableItemType ItemType
typedef Array< SelectableItemType > ItemArray
typedef
TypeHelpers::ParameterType
< SelectableItemType >::type ParameterType
Public Member Functions
SelectedItemSet ()
Creates an empty set.
SelectedItemSet (const ItemArray &items)
Creates a set based on an array of items.
SelectedItemSet (const SelectedItemSet &other)
Creates a copy of another set.
SelectedItemSet & operator= (const SelectedItemSet &other)
Creates a copy of another set.
void selectOnly (ParameterType item)
Clears any other currently selected items, and selects this item.
void addToSelection (ParameterType item)
Selects an item.
void addToSelectionBasedOnModifiers (ParameterType item, ModifierKeys modifiers)
Selects or deselects an item.
bool addToSelectionOnMouseDown (ParameterType item, ModifierKeys modifiers)
Selects or deselects items that can also be dragged, based on a mouse-down event.
void addToSelectionOnMouseUp (ParameterType item, ModifierKeys modifiers, const bool wasItemDragged, const bool resultOfMouseDownSelectMethod)
Selects or deselects items that can also be dragged, based on a mouse-up event.
void deselect (ParameterType item)
Deselects an item.
void deselectAll ()
Deselects all items.
int getNumSelected () const noexcept
Returns the number of currently selected items.
SelectableItemType getSelectedItem (const int index) const
Returns one of the currently selected items.
bool isSelected (ParameterType item) const noexcept
True if this item is currently selected.
const ItemArray & getItemArray () const noexcept
Provides access to the array of items.
SelectableItemType * begin () const noexcept
Provides iterator access to the array of items.
SelectableItemType * end () const noexcept
Provides iterator access to the array of items.
virtual void itemSelected (SelectableItemType)
Can be overridden to do special handling when an item is selected.
virtual void itemDeselected (SelectableItemType)
Can be overridden to do special handling when an item is deselected.
void changed ()
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
void changed (const bool synchronous)
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
Public Member Functions inherited from ChangeBroadcaster
ChangeBroadcaster () noexcept
Creates an ChangeBroadcaster.
virtual ~ChangeBroadcaster ()
Destructor.
void addChangeListener (ChangeListener *listener)
Registers a listener to receive change callbacks from this broadcaster.
void removeChangeListener (ChangeListener *listener)
Unregisters a listener from the list.
void removeAllChangeListeners ()
Removes all listeners from the list.
void sendChangeMessage ()
Causes an asynchronous change message to be sent to all the registered listeners.
void sendSynchronousChangeMessage ()
Sends a synchronous change message to all the registered listeners.
void dispatchPendingMessages ()
If a change message has been sent but not yet dispatched, this will call sendSynchronousChangeMessage() to make the callback immediately.
Member Typedef Documentation
template<class SelectableItemType > typedef SelectableItemType SelectedItemSet< SelectableItemType >::ItemType
template<class SelectableItemType > typedef Array<SelectableItemType> SelectedItemSet< SelectableItemType >::ItemArray
template<class SelectableItemType > typedef TypeHelpers::ParameterType<SelectableItemType>::type SelectedItemSet< SelectableItemType >::ParameterType
Constructor & Destructor Documentation
template<class SelectableItemType > SelectedItemSet< SelectableItemType >::SelectedItemSet ()
Creates an empty set.
template<class SelectableItemType > SelectedItemSet< SelectableItemType >::SelectedItemSet (const ItemArray & items) explicit
Creates a set based on an array of items.
template<class SelectableItemType > SelectedItemSet< SelectableItemType >::SelectedItemSet (const SelectedItemSet< SelectableItemType > & other)
Creates a copy of another set.
Member Function Documentation
template<class SelectableItemType > SelectedItemSet& SelectedItemSet< SelectableItemType >::operator= (const SelectedItemSet< SelectableItemType > & other)
Creates a copy of another set.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin(), SelectedItemSet< SelectableItemType >::changed(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), SelectedItemSet< SelectableItemType >::isSelected(), SelectedItemSet< SelectableItemType >::itemDeselected(), SelectedItemSet< SelectableItemType >::itemSelected(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::selectOnly (ParameterType item)
Clears any other currently selected items, and selects this item.
If this item is already the only thing selected, no change notification will be sent out.
See Also
addToSelection, addToSelectionBasedOnModifiers
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), SelectedItemSet< SelectableItemType >::changed(), SelectedItemSet< SelectableItemType >::deselect(), SelectedItemSet< SelectableItemType >::deselectAll(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), SelectedItemSet< SelectableItemType >::isSelected(), SelectedItemSet< SelectableItemType >::itemSelected(), jmin(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::addToSelection (ParameterType item)
Selects an item.
If the item is already selected, no change notification will be sent out.
See Also
selectOnly, addToSelectionBasedOnModifiers
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), SelectedItemSet< SelectableItemType >::changed(), SelectedItemSet< SelectableItemType >::isSelected(), and SelectedItemSet< SelectableItemType >::itemSelected().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers (ParameterType item, ModifierKeys modifiers)
Selects or deselects an item.
This will use the modifier keys to decide whether to deselect other items first.
So if the shift key is held down, the item will be added without deselecting anything (same as calling addToSelection())
If no modifiers are down, the current selection will be cleared first (same as calling selectOnly())
If the ctrl (or command on the Mac) key is held down, the item will be toggled - so it'll be added to the set unless it's already there, in which case it'll be deselected.
If the items that you're selecting can also be dragged, you may need to use the addToSelectionOnMouseDown() and addToSelectionOnMouseUp() calls to handle the subtleties of this kind of usage.
See Also
selectOnly, addToSelection, addToSelectionOnMouseDown, addToSelectionOnMouseUp
References SelectedItemSet< SelectableItemType >::addToSelection(), SelectedItemSet< SelectableItemType >::deselect(), ModifierKeys::isCommandDown(), SelectedItemSet< SelectableItemType >::isSelected(), ModifierKeys::isShiftDown(), and SelectedItemSet< SelectableItemType >::selectOnly().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown(), and SelectedItemSet< SelectableItemType >::addToSelectionOnMouseUp().
template<class SelectableItemType > bool SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown (ParameterType item, ModifierKeys modifiers)
Selects or deselects items that can also be dragged, based on a mouse-down event.
If you call addToSelectionOnMouseDown() at the start of your mouseDown event, and then call addToSelectionOnMouseUp() at the end of your mouseUp event, this makes it easy to handle multiple-selection of sets of objects that can also be dragged.
For example, if you have several items already selected, and you click on one of them (without dragging), then you'd expect this to deselect the other, and just select the item you clicked on. But if you had clicked on this item and dragged it, you'd have expected them all to stay selected.
When you call this method, you'll need to store the boolean result, because the addToSelectionOnMouseUp() method will need to be know this value.
See Also
addToSelectionOnMouseUp, addToSelectionBasedOnModifiers
References SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), ModifierKeys::isPopupMenu(), and SelectedItemSet< SelectableItemType >::isSelected().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::addToSelectionOnMouseUp (ParameterType item, ModifierKeys modifiers, const bool wasItemDragged, const bool resultOfMouseDownSelectMethod)
Selects or deselects items that can also be dragged, based on a mouse-up event.
Call this during a mouseUp callback, when you have previously called the addToSelectionOnMouseDown() method during your mouseDown event.
See addToSelectionOnMouseDown() for more info
Parameters
item the item to select (or deselect)
modifiers the modifiers from the mouse-up event
wasItemDragged true if your item was dragged during the mouse click
resultOfMouseDownSelectMethod this is the boolean return value that came back from the addToSelectionOnMouseDown() call that you should have made during the matching mouseDown event
References SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::deselect (ParameterType item)
Deselects an item.
References SelectedItemSet< SelectableItemType >::changed(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOf(), SelectedItemSet< SelectableItemType >::itemDeselected(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn().
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), and SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::deselectAll ()
Deselects all items.
References SelectedItemSet< SelectableItemType >::changed(), SelectedItemSet< SelectableItemType >::itemDeselected(), jmin(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > int SelectedItemSet< SelectableItemType >::getNumSelected () const noexcept
Returns the number of currently selected items.
See Also
getSelectedItem
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<class SelectableItemType > SelectableItemType SelectedItemSet< SelectableItemType >::getSelectedItem (const int index) const
Returns one of the currently selected items.
If the index is out-of-range, this returns a default-constructed SelectableItemType.
See Also
getNumSelected
template<class SelectableItemType > bool SelectedItemSet< SelectableItemType >::isSelected (ParameterType item) const noexcept
True if this item is currently selected.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::contains().
Referenced by SelectedItemSet< SelectableItemType >::addToSelection(), SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown(), SelectedItemSet< SelectableItemType >::operator=(), and SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > const ItemArray& SelectedItemSet< SelectableItemType >::getItemArray () const noexcept
Provides access to the array of items.
template<class SelectableItemType > SelectableItemType* SelectedItemSet< SelectableItemType >::begin () const noexcept
Provides iterator access to the array of items.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin().
template<class SelectableItemType > SelectableItemType* SelectedItemSet< SelectableItemType >::end () const noexcept
Provides iterator access to the array of items.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end().
template<class SelectableItemType > virtual void SelectedItemSet< SelectableItemType >::itemSelected (SelectableItemType) virtual
Can be overridden to do special handling when an item is selected.
For example, if the item is an object, you might want to call it and tell it that it's being selected.
Referenced by SelectedItemSet< SelectableItemType >::addToSelection(), SelectedItemSet< SelectableItemType >::operator=(), and SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > virtual void SelectedItemSet< SelectableItemType >::itemDeselected (SelectableItemType) virtual
Can be overridden to do special handling when an item is deselected.
For example, if the item is an object, you might want to call it and tell it that it's being deselected.
Referenced by SelectedItemSet< SelectableItemType >::deselect(), SelectedItemSet< SelectableItemType >::deselectAll(), and SelectedItemSet< SelectableItemType >::operator=().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::changed ()
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
References ChangeBroadcaster::sendChangeMessage().
Referenced by SelectedItemSet< SelectableItemType >::addToSelection(), SelectedItemSet< SelectableItemType >::deselect(), SelectedItemSet< SelectableItemType >::deselectAll(), SelectedItemSet< SelectableItemType >::operator=(), and SelectedItemSet< SelectableItemType >::selectOnly().
template<class SelectableItemType > void SelectedItemSet< SelectableItemType >::changed (const bool synchronous)
Used internally, but can be called to force a change message to be sent to the ChangeListeners.
References ChangeBroadcaster::sendChangeMessage(), and ChangeBroadcaster::sendSynchronousChangeMessage().
class TextDragAndDropTarget
Components derived from this class can have text dropped onto them by an external application.
See Also
DragAndDropContainer
Public Member Functions
virtual ~TextDragAndDropTarget ()
Destructor.
virtual bool isInterestedInTextDrag (const String &text)=0
Callback to check whether this target is interested in the set of text being offered.
virtual void textDragEnter (const String &text, int x, int y)
Callback to indicate that some text is being dragged over this component.
virtual void textDragMove (const String &text, int x, int y)
Callback to indicate that the user is dragging some text over this component.
virtual void textDragExit (const String &text)
Callback to indicate that the mouse has moved away from this component.
virtual void textDropped (const String &text, int x, int y)=0
Callback to indicate that the user has dropped the text onto this component.
Constructor & Destructor Documentation
virtual TextDragAndDropTarget::~TextDragAndDropTarget () virtual
Destructor.
Member Function Documentation
virtual bool TextDragAndDropTarget::isInterestedInTextDrag (const String & text) pure virtual
Callback to check whether this target is interested in the set of text being offered.
Note that this will be called repeatedly when the user is dragging the mouse around over your component, so don't do anything time-consuming in here!
Parameters
text the text that the user is dragging
Returns
true if this component wants to receive the other callbacks regarging this type of object; if it returns false, no other callbacks will be made.
virtual void TextDragAndDropTarget::textDragEnter (const String & text, int x, int y) virtual
Callback to indicate that some text is being dragged over this component.
This gets called when the user moves the mouse into this component while dragging.
Use this callback as a trigger to make your component repaint itself to give the user feedback about whether the text can be dropped here or not.
Parameters
text the text that the user is dragging
x the mouse x position, relative to this component
y the mouse y position, relative to this component
virtual void TextDragAndDropTarget::textDragMove (const String & text, int x, int y) virtual
Callback to indicate that the user is dragging some text over this component.
This gets called when the user moves the mouse over this component while dragging. Normally overriding itemDragEnter() and itemDragExit() are enough, but this lets you know what happens in-between.
Parameters
text the text that the user is dragging
x the mouse x position, relative to this component
y the mouse y position, relative to this component
virtual void TextDragAndDropTarget::textDragExit (const String & text) virtual
Callback to indicate that the mouse has moved away from this component.
This gets called when the user moves the mouse out of this component while dragging the text.
If you've used textDragEnter() to repaint your component and give feedback, use this as a signal to repaint it in its normal state.
Parameters
text the text that the user is dragging
virtual void TextDragAndDropTarget::textDropped (const String & text, int x, int y) pure virtual
Callback to indicate that the user has dropped the text onto this component.
When the user drops the text, this get called, and you can use the text in whatever way is appropriate.
Note that after this is called, the textDragExit method may not be called, so you should clean up in here if there's anything you need to do when the drag finishes.
Parameters
text the text that the user is dragging
x the mouse x position, relative to this component
y the mouse y position, relative to this component
class TooltipClient
Components that want to use pop-up tooltips should implement this interface.
A TooltipWindow will wait for the mouse to hover over a component that implements the TooltipClient interface, and when it finds one, it will display the tooltip returned by its getTooltip() method.
See Also
TooltipWindow, SettableTooltipClient
Public Member Functions
virtual ~TooltipClient ()
Destructor.
virtual String getTooltip ()=0
Returns the string that this object wants to show as its tooltip.
Constructor & Destructor Documentation
virtual TooltipClient::~TooltipClient () virtual
Destructor.
Member Function Documentation
virtual String TooltipClient::getTooltip () pure virtual
Returns the string that this object wants to show as its tooltip.
Implemented in ComboBox, and SettableTooltipClient.
class SettableTooltipClient
An implementation of TooltipClient that stores the tooltip string and a method for changing it.
This makes it easy to add a tooltip to a custom component, by simply adding this as a base class and calling setTooltip().
Many of the Juce widgets already use this as a base class to implement their tooltips.
See Also
TooltipClient, TooltipWindow
Public Member Functions
~SettableTooltipClient ()
Destructor.
virtual void setTooltip (const String &newTooltip)
Assigns a new tooltip to this object.
String getTooltip () override
Returns the tooltip assigned to this object.
Public Member Functions inherited from TooltipClient
virtual ~TooltipClient ()
Destructor.
Protected Member Functions
SettableTooltipClient ()
Constructor & Destructor Documentation
SettableTooltipClient::~SettableTooltipClient ()
Destructor.
SettableTooltipClient::SettableTooltipClient () protected
Member Function Documentation
virtual void SettableTooltipClient::setTooltip (const String & newTooltip) virtual
Assigns a new tooltip to this object.
Reimplemented in ComboBox, Button, and FilenameComponent.
String SettableTooltipClient::getTooltip () override virtual
Returns the tooltip assigned to this object.
Implements TooltipClient.
Reimplemented in ComboBox.