JUCE: audio_io
audio_io
juce_audio_devices
Classes
class AudioDeviceManager
Manages the state of some audio and midi i/o devices.
class AudioIODeviceCallback
One of these is passed to an AudioIODevice object to stream the audio data in and out.
class AudioIODevice
Base class for an audio device with synchronised input and output channels.
class AudioIODeviceType
Represents a type of audio driver, such as DirectSound, ASIO, CoreAudio, etc.
class SystemAudioVolume
Contains functions to control the system's master volume.
Detailed Description
Class Documentation
class AudioDeviceManager
Manages the state of some audio and midi i/o devices.
This class keeps tracks of a currently-selected audio device, through with which it continuously streams data from an audio callback, as well as one or more midi inputs.
The idea is that your application will create one global instance of this object, and let it take care of creating and deleting specific types of audio devices internally. So when the device is changed, your callbacks will just keep running without having to worry about this.
The manager can save and reload all of its device settings as XML, which makes it very easy for you to save and reload the audio setup of your application.
And to make it easy to let the user change its settings, there's a component to do just that - the AudioDeviceSelectorComponent class, which contains a set of device selection/sample-rate/latency controls.
To use an AudioDeviceManager, create one, and use initialise() to set it up. Then call addAudioCallback() to register your audio callback with it, and use that to process your audio data.
The manager also acts as a handy hub for incoming midi messages, allowing a listener to register for messages from either a specific midi device, or from whatever the current default midi input device is. The listener then doesn't have to worry about re-registering with different midi devices if they are changed or deleted.
And yet another neat trick is that amount of CPU time being used is measured and available with the getCpuUsage() method.
The AudioDeviceManager is a ChangeBroadcaster, and will send a change message to listeners whenever one of its settings is changed.
See Also
AudioDeviceSelectorComponent, AudioIODevice, AudioIODeviceType
Public Member Functions
AudioDeviceManager ()
Creates a default AudioDeviceManager.
~AudioDeviceManager ()
Destructor.
String initialise (int numInputChannelsNeeded, int numOutputChannelsNeeded, const XmlElement *savedState, bool selectDefaultDeviceOnFailure, const String &preferredDefaultDeviceName=String(), const AudioDeviceSetup *preferredSetupOptions=nullptr)
Opens a set of audio devices ready for use.
String initialiseWithDefaultDevices (int numInputChannelsNeeded, int numOutputChannelsNeeded)
Resets everything to a default device setup, clearing any stored settings.
XmlElement * createStateXml () const
Returns some XML representing the current state of the manager.
void getAudioDeviceSetup (AudioDeviceSetup &result) const
Returns the current device properties that are in use.
String setAudioDeviceSetup (const AudioDeviceSetup &newSetup, bool treatAsChosenDevice)
Changes the current device or its settings.
AudioIODevice * getCurrentAudioDevice () const noexcept
Returns the currently-active audio device.
String getCurrentAudioDeviceType () const
Returns the type of audio device currently in use.
AudioIODeviceType * getCurrentDeviceTypeObject () const
Returns the currently active audio device type object.
void setCurrentAudioDeviceType (const String &type, bool treatAsChosenDevice)
Changes the class of audio device being used.
void closeAudioDevice ()
Closes the currently-open device.
void restartLastAudioDevice ()
Tries to reload the last audio device that was running.
void addAudioCallback (AudioIODeviceCallback *newCallback)
Registers an audio callback to be used.
void removeAudioCallback (AudioIODeviceCallback *callback)
Deregisters a previously added callback.
double getCpuUsage () const
Returns the average proportion of available CPU being spent inside the audio callbacks.
void setMidiInputEnabled (const String &midiInputDeviceName, bool enabled)
Enables or disables a midi input device.
bool isMidiInputEnabled (const String &midiInputDeviceName) const
Returns true if a given midi input device is being used.
void addMidiInputCallback (const String &midiInputDeviceName, MidiInputCallback *callback)
Registers a listener for callbacks when midi events arrive from a midi input.
void removeMidiInputCallback (const String &midiInputDeviceName, MidiInputCallback *callback)
Removes a listener that was previously registered with addMidiInputCallback().
void setDefaultMidiOutput (const String &deviceName)
Sets a midi output device to use as the default.
const String & getDefaultMidiOutputName () const noexcept
Returns the name of the default midi output.
MidiOutput * getDefaultMidiOutput () const noexcept
Returns the current default midi output device.
const OwnedArray
< AudioIODeviceType > & getAvailableDeviceTypes ()
Returns a list of the types of device supported.
virtual void createAudioDeviceTypes (OwnedArray< AudioIODeviceType > &types)
Creates a list of available types.
void addAudioDeviceType (AudioIODeviceType *newDeviceType)
Adds a new device type to the list of types.
void playTestSound ()
Plays a beep through the current audio device.
void enableInputLevelMeasurement (bool enableMeasurement) noexcept
Turns on level-measuring for input channels.
void enableOutputLevelMeasurement (bool enableMeasurement) noexcept
Turns on level-measuring for output channels.
double getCurrentInputLevel () const noexcept
Returns the current input level.
double getCurrentOutputLevel () const noexcept
Returns the current output level.
CriticalSection & getAudioCallbackLock () noexcept
Returns the a lock that can be used to synchronise access to the audio callback.
CriticalSection & getMidiCallbackLock () noexcept
Returns the a lock that can be used to synchronise access to the midi callback.
Public Member Functions inherited from ChangeBroadcaster
ChangeBroadcaster () noexcept
Creates an ChangeBroadcaster.
virtual ~ChangeBroadcaster ()
Destructor.
void addChangeListener (ChangeListener *listener)
Registers a listener to receive change callbacks from this broadcaster.
void removeChangeListener (ChangeListener *listener)
Unregisters a listener from the list.
void removeAllChangeListeners ()
Removes all listeners from the list.
void sendChangeMessage ()
Causes an asynchronous change message to be sent to all the registered listeners.
void sendSynchronousChangeMessage ()
Sends a synchronous change message to all the registered listeners.
void dispatchPendingMessages ()
If a change message has been sent but not yet dispatched, this will call sendSynchronousChangeMessage() to make the callback immediately.
Constructor & Destructor Documentation
AudioDeviceManager::AudioDeviceManager ()
Creates a default AudioDeviceManager.
Initially no audio device will be selected. You should call the initialise() method and register an audio callback with setAudioCallback() before it'll be able to actually make any noise.
AudioDeviceManager::~AudioDeviceManager ()
Destructor.
Member Function Documentation
String AudioDeviceManager::initialise (int numInputChannelsNeeded, int numOutputChannelsNeeded, const XmlElement * savedState, bool selectDefaultDeviceOnFailure, const String & preferredDefaultDeviceName = String(), const AudioDeviceSetup * preferredSetupOptions = nullptr)
Opens a set of audio devices ready for use.
This will attempt to open either a default audio device, or one that was previously saved as XML.
Parameters
numInputChannelsNeeded the maximum number of input channels your app would like to use (the actual number of channels opened may be less than the number requested)
numOutputChannelsNeeded the maximum number of output channels your app would like to use (the actual number of channels opened may be less than the number requested)
savedState either a previously-saved state that was produced by createStateXml(), or nullptr if you want the manager to choose the best device to open.
selectDefaultDeviceOnFailure if true, then if the device specified in the XML fails to open, then a default device will be used instead. If false, then on failure, no device is opened.
preferredDefaultDeviceName if this is not empty, and there's a device with this name, then that will be used as the default device (assuming that there wasn't one specified in the XML). The string can actually be a simple wildcard, containing "*" and "?" characters
preferredSetupOptions if this is non-null, the structure will be used as the set of preferred settings when opening the device. If you use this parameter, the preferredDefaultDeviceName field will be ignored
Returns
an error message if anything went wrong, or an empty string if it worked ok.
Referenced by StandalonePluginHolder::reloadAudioDeviceState().
String AudioDeviceManager::initialiseWithDefaultDevices (int numInputChannelsNeeded, int numOutputChannelsNeeded)
Resets everything to a default device setup, clearing any stored settings.
XmlElement* AudioDeviceManager::createStateXml () const
Returns some XML representing the current state of the manager.
This stores the current device, its samplerate, block size, etc, and can be restored later with initialise().
Note that this can return a null pointer if no settings have been explicitly changed (i.e. if the device manager has just been left in its default state).
Referenced by StandalonePluginHolder::saveAudioDeviceState().
void AudioDeviceManager::getAudioDeviceSetup (AudioDeviceSetup & result) const
Returns the current device properties that are in use.
See Also
setAudioDeviceSetup
String AudioDeviceManager::setAudioDeviceSetup (const AudioDeviceSetup & newSetup, bool treatAsChosenDevice)
Changes the current device or its settings.
If you want to change a device property, like the current sample rate or block size, you can call getAudioDeviceSetup() to retrieve the current settings, then tweak the appropriate fields in the AudioDeviceSetup structure, and pass it back into this method to apply the new settings.
Parameters
newSetup the settings that you'd like to use
treatAsChosenDevice if this is true and if the device opens correctly, these new settings will be taken as having been explicitly chosen by the user, and the next time createStateXml() is called, these settings will be returned. If it's false, then the device is treated as a temporary or default device, and a call to createStateXml() will return either the last settings that were made with treatAsChosenDevice as true, or the last XML settings that were passed into initialise().
Returns
an error message if anything went wrong, or an empty string if it worked ok.
See Also
getAudioDeviceSetup
AudioIODevice* AudioDeviceManager::getCurrentAudioDevice () const noexcept
Returns the currently-active audio device.
Referenced by StandalonePluginHolder::isInterAppAudioConnected(), StandalonePluginHolder::startPlaying(), and StandalonePluginHolder::switchToHostApplication().
String AudioDeviceManager::getCurrentAudioDeviceType () const
Returns the type of audio device currently in use.
See Also
setCurrentAudioDeviceType
AudioIODeviceType* AudioDeviceManager::getCurrentDeviceTypeObject () const
Returns the currently active audio device type object.
Don't keep a copy of this pointer - it's owned by the device manager and could change at any time.
void AudioDeviceManager::setCurrentAudioDeviceType (const String & type, bool treatAsChosenDevice)
Changes the class of audio device being used.
This switches between, e.g. ASIO and DirectSound. On the Mac you probably won't ever call this because there's only one type: CoreAudio.
For a list of types, see getAvailableDeviceTypes().
void AudioDeviceManager::closeAudioDevice ()
Closes the currently-open device.
You can call restartLastAudioDevice() later to reopen it in the same state that it was just in.
void AudioDeviceManager::restartLastAudioDevice ()
Tries to reload the last audio device that was running.
Note that this only reloads the last device that was running before closeAudioDevice() was called - it doesn't reload any kind of saved-state, and can only be called after a device has been opened with SetAudioDevice().
If a device is already open, this call will do nothing.
void AudioDeviceManager::addAudioCallback (AudioIODeviceCallback * newCallback)
Registers an audio callback to be used.
The manager will redirect callbacks from whatever audio device is currently in use to all registered callback objects. If more than one callback is active, they will all be given the same input data, and their outputs will be summed.
If necessary, this method will invoke audioDeviceAboutToStart() on the callback object before returning.
To remove a callback, use removeAudioCallback().
void AudioDeviceManager::removeAudioCallback (AudioIODeviceCallback * callback)
Deregisters a previously added callback.
If necessary, this method will invoke audioDeviceStopped() on the callback object before returning.
See Also
addAudioCallback
double AudioDeviceManager::getCpuUsage () const
Returns the average proportion of available CPU being spent inside the audio callbacks.
Returns
A value between 0 and 1.0 to indicate the approximate proportion of CPU time spent in the callbacks.
void AudioDeviceManager::setMidiInputEnabled (const String & midiInputDeviceName, bool enabled)
Enables or disables a midi input device.
The list of devices can be obtained with the MidiInput::getDevices() method.
Any incoming messages from enabled input devices will be forwarded on to all the listeners that have been registered with the addMidiInputCallback() method. They can either register for messages from a particular device, or from just the "default" midi input.
Routing the midi input via an AudioDeviceManager means that when a listener registers for the default midi input, this default device can be changed by the manager without the listeners having to know about it or re-register.
It also means that a listener can stay registered for a midi input that is disabled or not present, so that when the input is re-enabled, the listener will start receiving messages again.
See Also
addMidiInputCallback, isMidiInputEnabled
bool AudioDeviceManager::isMidiInputEnabled (const String & midiInputDeviceName) const
Returns true if a given midi input device is being used.
See Also
setMidiInputEnabled
void AudioDeviceManager::addMidiInputCallback (const String & midiInputDeviceName, MidiInputCallback * callback)
Registers a listener for callbacks when midi events arrive from a midi input.
The device name can be empty to indicate that it wants to receive all incoming events from all the enabled MIDI inputs. Or it can be the name of one of the MIDI input devices if it just wants the events from that device. (see MidiInput::getDevices() for the list of device names).
Only devices which are enabled (see the setMidiInputEnabled() method) will have their events forwarded on to listeners.
void AudioDeviceManager::removeMidiInputCallback (const String & midiInputDeviceName, MidiInputCallback * callback)
Removes a listener that was previously registered with addMidiInputCallback().
void AudioDeviceManager::setDefaultMidiOutput (const String & deviceName)
Sets a midi output device to use as the default.
The list of devices can be obtained with the MidiOutput::getDevices() method.
The specified device will be opened automatically and can be retrieved with the getDefaultMidiOutput() method.
Pass in an empty string to deselect all devices. For the default device, you can use MidiOutput::getDevices() [MidiOutput::getDefaultDeviceIndex()].
See Also
getDefaultMidiOutput, getDefaultMidiOutputName
const String& AudioDeviceManager::getDefaultMidiOutputName () const noexcept
Returns the name of the default midi output.
See Also
setDefaultMidiOutput, getDefaultMidiOutput
MidiOutput* AudioDeviceManager::getDefaultMidiOutput () const noexcept
Returns the current default midi output device.
If no device has been selected, or the device can't be opened, this will return nullptr.
See Also
getDefaultMidiOutputName
const OwnedArray<AudioIODeviceType>& AudioDeviceManager::getAvailableDeviceTypes ()
Returns a list of the types of device supported.
virtual void AudioDeviceManager::createAudioDeviceTypes (OwnedArray< AudioIODeviceType > & types) virtual
Creates a list of available types.
This will add a set of new AudioIODeviceType objects to the specified list, to represent each available types of device.
You can override this if your app needs to do something specific, like avoid using DirectSound devices, etc.
void AudioDeviceManager::addAudioDeviceType (AudioIODeviceType * newDeviceType)
Adds a new device type to the list of types.
The manager will take ownership of the object that is passed-in.
void AudioDeviceManager::playTestSound ()
Plays a beep through the current audio device.
This is here to allow the audio setup UI panels to easily include a "test" button so that the user can check where the audio is coming from.
void AudioDeviceManager::enableInputLevelMeasurement (bool enableMeasurement) noexcept
Turns on level-measuring for input channels.
See Also
getCurrentInputLevel()
void AudioDeviceManager::enableOutputLevelMeasurement (bool enableMeasurement) noexcept
Turns on level-measuring for output channels.
See Also
getCurrentOutputLevel()
double AudioDeviceManager::getCurrentInputLevel () const noexcept
Returns the current input level.
To use this, you must first enable it by calling enableInputLevelMeasurement().
See Also
enableInputLevelMeasurement()
double AudioDeviceManager::getCurrentOutputLevel () const noexcept
Returns the current output level.
To use this, you must first enable it by calling enableOutputLevelMeasurement().
See Also
enableOutputLevelMeasurement()
CriticalSection& AudioDeviceManager::getAudioCallbackLock () noexcept
Returns the a lock that can be used to synchronise access to the audio callback.
Obviously while this is locked, you're blocking the audio thread from running, so it must only be used for very brief periods when absolutely necessary.
CriticalSection& AudioDeviceManager::getMidiCallbackLock () noexcept
Returns the a lock that can be used to synchronise access to the midi callback.
Obviously while this is locked, you're blocking the midi system from running, so it must only be used for very brief periods when absolutely necessary.
class AudioIODeviceCallback
One of these is passed to an AudioIODevice object to stream the audio data in and out.
The AudioIODevice will repeatedly call this class's audioDeviceIOCallback() method on its own high-priority audio thread, when it needs to send or receive the next block of data.
See Also
AudioIODevice, AudioDeviceManager
Public Member Functions
virtual ~AudioIODeviceCallback ()
Destructor.
virtual void audioDeviceIOCallback (const float **inputChannelData, int numInputChannels, float **outputChannelData, int numOutputChannels, int numSamples)=0
Processes a block of incoming and outgoing audio data.
virtual void audioDeviceAboutToStart (AudioIODevice *device)=0
Called to indicate that the device is about to start calling back.
virtual void audioDeviceStopped ()=0
Called to indicate that the device has stopped.
virtual void audioDeviceError (const String &errorMessage)
This can be overridden to be told if the device generates an error while operating.
Constructor & Destructor Documentation
virtual AudioIODeviceCallback::~AudioIODeviceCallback () virtual
Destructor.
Member Function Documentation
virtual void AudioIODeviceCallback::audioDeviceIOCallback (const float ** inputChannelData, int numInputChannels, float ** outputChannelData, int numOutputChannels, int numSamples) pure virtual
Processes a block of incoming and outgoing audio data.
The subclass's implementation should use the incoming audio for whatever purposes it needs to, and must fill all the output channels with the next block of output data before returning.
The channel data is arranged with the same array indices as the channel name array returned by AudioIODevice::getOutputChannelNames(), but those channels that aren't specified in AudioIODevice::open() will have a null pointer for their associated channel, so remember to check for this.
Parameters
inputChannelData a set of arrays containing the audio data for each incoming channel - this data is valid until the function returns. There will be one channel of data for each input channel that was enabled when the audio device was opened (see AudioIODevice::open())
numInputChannels the number of pointers to channel data in the inputChannelData array.
outputChannelData a set of arrays which need to be filled with the data that should be sent to each outgoing channel of the device. There will be one channel of data for each output channel that was enabled when the audio device was opened (see AudioIODevice::open()) The initial contents of the array is undefined, so the callback function must fill all the channels with zeros if its output is silence. Failing to do this could cause quite an unpleasant noise!
numOutputChannels the number of pointers to channel data in the outputChannelData array.
numSamples the number of samples in each channel of the input and output arrays. The number of samples will depend on the audio device's buffer size and will usually remain constant, although this isn't guaranteed, so make sure your code can cope with reasonable changes in the buffer size from one callback to the next.
Implemented in SoundPlayer, AudioProcessorPlayer, and AudioSourcePlayer.
virtual void AudioIODeviceCallback::audioDeviceAboutToStart (AudioIODevice * device) pure virtual
Called to indicate that the device is about to start calling back.
This will be called just before the audio callbacks begin, either when this callback has just been added to an audio device, or after the device has been restarted because of a sample-rate or block-size change.
You can use this opportunity to find out the sample rate and block size that the device is going to use by calling the AudioIODevice::getCurrentSampleRate() and AudioIODevice::getCurrentBufferSizeSamples() on the supplied pointer.
Parameters
device the audio IO device that will be used to drive the callback. Note that if you're going to store this this pointer, it is only valid until the next time that audioDeviceStopped is called.
Implemented in SoundPlayer, AudioSourcePlayer, and AudioProcessorPlayer.
virtual void AudioIODeviceCallback::audioDeviceStopped () pure virtual
Called to indicate that the device has stopped.
Implemented in SoundPlayer, AudioSourcePlayer, and AudioProcessorPlayer.
virtual void AudioIODeviceCallback::audioDeviceError (const String & errorMessage) virtual
This can be overridden to be told if the device generates an error while operating.
Be aware that this could be called by any thread! And not all devices perform this callback.
Reimplemented in SoundPlayer.
class AudioIODevice
Base class for an audio device with synchronised input and output channels.
Subclasses of this are used to implement different protocols such as DirectSound, ASIO, CoreAudio, etc.
To create one of these, you'll need to use the AudioIODeviceType class - see the documentation for that class for more info.
For an easier way of managing audio devices and their settings, have a look at the AudioDeviceManager class.
See Also
AudioIODeviceType, AudioDeviceManager
Public Member Functions
virtual ~AudioIODevice ()
Destructor.
const String & getName () const noexcept
Returns the device's name, (as set in the constructor).
const String & getTypeName () const noexcept
Returns the type of the device.
virtual StringArray getOutputChannelNames ()=0
Returns the names of all the available output channels on this device.
virtual StringArray getInputChannelNames ()=0
Returns the names of all the available input channels on this device.
virtual Array< double > getAvailableSampleRates ()=0
Returns the set of sample-rates this device supports.
virtual Array< int > getAvailableBufferSizes ()=0
Returns the set of buffer sizes that are available.
virtual int getDefaultBufferSize ()=0
Returns the default buffer-size to use.
virtual String open (const BigInteger &inputChannels, const BigInteger &outputChannels, double sampleRate, int bufferSizeSamples)=0
Tries to open the device ready to play.
virtual void close ()=0
Closes and releases the device if it's open.
virtual bool isOpen ()=0
Returns true if the device is still open.
virtual void start (AudioIODeviceCallback *callback)=0
Starts the device actually playing.
virtual void stop ()=0
Stops the device playing.
virtual bool isPlaying ()=0
Returns true if the device is still calling back.
virtual String getLastError ()=0
Returns the last error that happened if anything went wrong.
virtual int getCurrentBufferSizeSamples ()=0
Returns the buffer size that the device is currently using.
virtual double getCurrentSampleRate ()=0
Returns the sample rate that the device is currently using.
virtual int getCurrentBitDepth ()=0
Returns the device's current physical bit-depth.
virtual BigInteger getActiveOutputChannels () const =0
Returns a mask showing which of the available output channels are currently enabled.
virtual BigInteger getActiveInputChannels () const =0
Returns a mask showing which of the available input channels are currently enabled.
virtual int getOutputLatencyInSamples ()=0
Returns the device's output latency.
virtual int getInputLatencyInSamples ()=0
Returns the device's input latency.
virtual bool hasControlPanel () const
True if this device can show a pop-up control panel for editing its settings.
virtual bool showControlPanel ()
Shows a device-specific control panel if there is one.
virtual bool setAudioPreprocessingEnabled (bool shouldBeEnabled)
On devices which support it, this allows automatic gain control or other mic processing to be disabled.
Protected Member Functions
AudioIODevice (const String &deviceName, const String &typeName)
Creates a device, setting its name and type member variables.
Protected Attributes
String name
String typeName
Constructor & Destructor Documentation
virtual AudioIODevice::~AudioIODevice () virtual
Destructor.
AudioIODevice::AudioIODevice (const String & deviceName, const String & typeName) protected
Creates a device, setting its name and type member variables.
Member Function Documentation
const String& AudioIODevice::getName () const noexcept
Returns the device's name, (as set in the constructor).
const String& AudioIODevice::getTypeName () const noexcept
Returns the type of the device.
E.g. "CoreAudio", "ASIO", etc. - this comes from the AudioIODeviceType that created it.
virtual StringArray AudioIODevice::getOutputChannelNames () pure virtual
Returns the names of all the available output channels on this device.
To find out which of these are currently in use, call getActiveOutputChannels().
virtual StringArray AudioIODevice::getInputChannelNames () pure virtual
Returns the names of all the available input channels on this device.
To find out which of these are currently in use, call getActiveInputChannels().
virtual Array<double> AudioIODevice::getAvailableSampleRates () pure virtual
Returns the set of sample-rates this device supports.
See Also
getCurrentSampleRate
virtual Array<int> AudioIODevice::getAvailableBufferSizes () pure virtual
Returns the set of buffer sizes that are available.
See Also
getCurrentBufferSizeSamples, getDefaultBufferSize
virtual int AudioIODevice::getDefaultBufferSize () pure virtual
Returns the default buffer-size to use.
Returns
a number of samples
See Also
getAvailableBufferSizes
virtual String AudioIODevice::open (const BigInteger & inputChannels, const BigInteger & outputChannels, double sampleRate, int bufferSizeSamples) pure virtual
Tries to open the device ready to play.
Parameters
inputChannels a BigInteger in which a set bit indicates that the corresponding input channel should be enabled
outputChannels a BigInteger in which a set bit indicates that the corresponding output channel should be enabled
sampleRate the sample rate to try to use - to find out which rates are available, see getAvailableSampleRates()
bufferSizeSamples the size of i/o buffer to use - to find out the available buffer sizes, see getAvailableBufferSizes()
Returns
an error description if there's a problem, or an empty string if it succeeds in opening the device
See Also
close
virtual void AudioIODevice::close () pure virtual
Closes and releases the device if it's open.
virtual bool AudioIODevice::isOpen () pure virtual
Returns true if the device is still open.
A device might spontaneously close itself if something goes wrong, so this checks if it's still open.
virtual void AudioIODevice::start (AudioIODeviceCallback * callback) pure virtual
Starts the device actually playing.
This must be called after the device has been opened.
Parameters
callback the callback to use for streaming the data.
See Also
AudioIODeviceCallback, open
virtual void AudioIODevice::stop () pure virtual
Stops the device playing.
Once a device has been started, this will stop it. Any pending calls to the callback class will be flushed before this method returns.
virtual bool AudioIODevice::isPlaying () pure virtual
Returns true if the device is still calling back.
The device might mysteriously stop, so this checks whether it's still playing.
virtual String AudioIODevice::getLastError () pure virtual
Returns the last error that happened if anything went wrong.
virtual int AudioIODevice::getCurrentBufferSizeSamples () pure virtual
Returns the buffer size that the device is currently using.
If the device isn't actually open, this value doesn't really mean much.
virtual double AudioIODevice::getCurrentSampleRate () pure virtual
Returns the sample rate that the device is currently using.
If the device isn't actually open, this value doesn't really mean much.
virtual int AudioIODevice::getCurrentBitDepth () pure virtual
Returns the device's current physical bit-depth.
If the device isn't actually open, this value doesn't really mean much.
virtual BigInteger AudioIODevice::getActiveOutputChannels () const pure virtual
Returns a mask showing which of the available output channels are currently enabled.
See Also
getOutputChannelNames
virtual BigInteger AudioIODevice::getActiveInputChannels () const pure virtual
Returns a mask showing which of the available input channels are currently enabled.
See Also
getInputChannelNames
virtual int AudioIODevice::getOutputLatencyInSamples () pure virtual
Returns the device's output latency.
This is the delay in samples between a callback getting a block of data, and that data actually getting played.
virtual int AudioIODevice::getInputLatencyInSamples () pure virtual
Returns the device's input latency.
This is the delay in samples between some audio actually arriving at the soundcard, and the callback getting passed this block of data.
virtual bool AudioIODevice::hasControlPanel () const virtual
True if this device can show a pop-up control panel for editing its settings.
This is generally just true of ASIO devices. If true, you can call showControlPanel() to display it.
virtual bool AudioIODevice::showControlPanel () virtual
Shows a device-specific control panel if there is one.
This should only be called for devices which return true from hasControlPanel().
virtual bool AudioIODevice::setAudioPreprocessingEnabled (bool shouldBeEnabled) virtual
On devices which support it, this allows automatic gain control or other mic processing to be disabled.
If the device doesn't support this operation, it'll return false.
Member Data Documentation
String AudioIODevice::name protected
String AudioIODevice::typeName protected
class AudioIODeviceType
Represents a type of audio driver, such as DirectSound, ASIO, CoreAudio, etc.
To get a list of available audio driver types, use the AudioDeviceManager::createAudioDeviceTypes() method. Each of the objects returned can then be used to list the available devices of that type. E.g.
OwnedArray<AudioIODeviceType> types;
myAudioDeviceManager.createAudioDeviceTypes (types);
for (int i = 0; i < types.size(); ++i)
{
    String typeName (types[i]->getTypeName());  // This will be things like "DirectSound", "CoreAudio", etc.
    types[i]->scanForDevices();                 // This must be called before getting the list of devices
    StringArray deviceNames (types[i]->getDeviceNames());  // This will now return a list of available devices of this type
    for (int j = 0; j < deviceNames.size(); ++j)
    {
        AudioIODevice* device = types[i]->createDevice (deviceNames [j]);
        ...
    }
}
For an easier way of managing audio devices and their settings, have a look at the AudioDeviceManager class.
See Also
AudioIODevice, AudioDeviceManager
Public Member Functions
const String & getTypeName () const noexcept
Returns the name of this type of driver that this object manages.
virtual void scanForDevices ()=0
Refreshes the object's cached list of known devices.
virtual StringArray getDeviceNames (bool wantInputNames=false) const =0
Returns the list of available devices of this type.
virtual int getDefaultDeviceIndex (bool forInput) const =0
Returns the name of the default device.
virtual int getIndexOfDevice (AudioIODevice *device, bool asInput) const =0
Returns the index of a given device in the list of device names.
virtual bool hasSeparateInputsAndOutputs () const =0
Returns true if two different devices can be used for the input and output.
virtual AudioIODevice * createDevice (const String &outputDeviceName, const String &inputDeviceName)=0
Creates one of the devices of this type.
void addListener (Listener *listener)
Adds a listener that will be called when this type of device is added or removed from the system.
void removeListener (Listener *listener)
Removes a listener that was previously added with addListener().
virtual ~AudioIODeviceType ()
Destructor.
Static Public Member Functions
static AudioIODeviceType * createAudioIODeviceType_CoreAudio ()
Creates a CoreAudio device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_iOSAudio ()
Creates an iOS device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_WASAPI (bool exclusiveMode)
Creates a WASAPI device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_DirectSound ()
Creates a DirectSound device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_ASIO ()
Creates an ASIO device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_ALSA ()
Creates an ALSA device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_JACK ()
Creates a JACK device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_Android ()
Creates an Android device type if it's available on this platform, or returns null.
static AudioIODeviceType * createAudioIODeviceType_OpenSLES ()
Creates an Android OpenSLES device type if it's available on this platform, or returns null.
Protected Member Functions
AudioIODeviceType (const String &typeName)
void callDeviceChangeListeners ()
Synchronously calls all the registered device list change listeners.
Constructor & Destructor Documentation
virtual AudioIODeviceType::~AudioIODeviceType () virtual
Destructor.
AudioIODeviceType::AudioIODeviceType (const String & typeName) explicit protected
Member Function Documentation
const String& AudioIODeviceType::getTypeName () const noexcept
Returns the name of this type of driver that this object manages.
This will be something like "DirectSound", "ASIO", "CoreAudio", "ALSA", etc.
virtual void AudioIODeviceType::scanForDevices () pure virtual
Refreshes the object's cached list of known devices.
This must be called at least once before calling getDeviceNames() or any of the other device creation methods.
virtual StringArray AudioIODeviceType::getDeviceNames (bool wantInputNames = false) const pure virtual
Returns the list of available devices of this type.
The scanForDevices() method must have been called to create this list.
Parameters
wantInputNames only really used by DirectSound where devices are split up into inputs and outputs, this indicates whether to use the input or output name to refer to a pair of devices.
virtual int AudioIODeviceType::getDefaultDeviceIndex (bool forInput) const pure virtual
Returns the name of the default device.
This will be one of the names from the getDeviceNames() list.
Parameters
forInput if true, this means that a default input device should be returned; if false, it should return the default output
virtual int AudioIODeviceType::getIndexOfDevice (AudioIODevice * device, bool asInput) const pure virtual
Returns the index of a given device in the list of device names.
If asInput is true, it shows the index in the inputs list, otherwise it looks for it in the outputs list.
virtual bool AudioIODeviceType::hasSeparateInputsAndOutputs () const pure virtual
Returns true if two different devices can be used for the input and output.
virtual AudioIODevice* AudioIODeviceType::createDevice (const String & outputDeviceName, const String & inputDeviceName) pure virtual
Creates one of the devices of this type.
The deviceName must be one of the strings returned by getDeviceNames(), and scanForDevices() must have been called before this method is used.
void AudioIODeviceType::addListener (Listener * listener)
Adds a listener that will be called when this type of device is added or removed from the system.
void AudioIODeviceType::removeListener (Listener * listener)
Removes a listener that was previously added with addListener().
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_CoreAudio () static
Creates a CoreAudio device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_iOSAudio () static
Creates an iOS device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_WASAPI (bool exclusiveMode) static
Creates a WASAPI device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_DirectSound () static
Creates a DirectSound device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_ASIO () static
Creates an ASIO device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_ALSA () static
Creates an ALSA device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_JACK () static
Creates a JACK device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_Android () static
Creates an Android device type if it's available on this platform, or returns null.
static AudioIODeviceType* AudioIODeviceType::createAudioIODeviceType_OpenSLES () static
Creates an Android OpenSLES device type if it's available on this platform, or returns null.
void AudioIODeviceType::callDeviceChangeListeners () protected
Synchronously calls all the registered device list change listeners.
class SystemAudioVolume
Contains functions to control the system's master volume.
Static Public Member Functions
static float JUCE_CALLTYPE getGain ()
Returns the operating system's current volume level in the range 0 to 1.0.
static bool JUCE_CALLTYPE setGain (float newGain)
Attempts to set the operating system's current volume level.
static bool JUCE_CALLTYPE isMuted ()
Returns true if the system's audio output is currently muted.
static bool JUCE_CALLTYPE setMuted (bool shouldBeMuted)
Attempts to mute the operating system's audio output.
Member Function Documentation
static float JUCE_CALLTYPE SystemAudioVolume::getGain () static
Returns the operating system's current volume level in the range 0 to 1.0.
static bool JUCE_CALLTYPE SystemAudioVolume::setGain (float newGain) static
Attempts to set the operating system's current volume level.
Parameters
newGain the level, between 0 and 1.0
Returns
true if the operation succeeds
static bool JUCE_CALLTYPE SystemAudioVolume::isMuted () static
Returns true if the system's audio output is currently muted.
static bool JUCE_CALLTYPE SystemAudioVolume::setMuted (bool shouldBeMuted) static
Attempts to mute the operating system's audio output.
Parameters
shouldBeMuted true if you want it to be muted
Returns
true if the operation succeeds