JUCE: geometry
geometry
juce_graphics
Classes
class AffineTransform
Represents a 2D affine-transformation matrix.
class BorderSize< ValueType >
Specifies a set of gaps to be left around the sides of a rectangle.
class EdgeTable
A table of horizontal scan-line segments - used for rasterising Paths.
class Line< ValueType >
Represents a line.
class Path
A path is a sequence of lines and curves that may either form a closed shape or be open-ended.
class PathFlatteningIterator
Flattens a Path object into a series of straight-line sections.
class PathStrokeType
Describes a type of stroke used to render a solid outline along a path.
class Point< ValueType >
A pair of (x, y) coordinates.
class Rectangle< ValueType >
Manages a rectangle and allows geometric operations to be performed on it.
class RectangleList< ValueType >
Maintains a set of rectangles as a complex region.
Functions
template<typename ValueType >
Point< ValueType > operator* (ValueType value, Point< ValueType > p) noexcept
Multiplies the point's coordinates by a scalar value.
Detailed Description
Class Documentation
class AffineTransform
Represents a 2D affine-transformation matrix.
An affine transformation is a transformation such as a rotation, scale, shear, resize or translation.
These are used for various 2D transformation tasks, e.g. with Path objects.
See Also
Path, Point, Line
Public Member Functions
AffineTransform () noexcept
Creates an identity transform.
AffineTransform (const AffineTransform &other) noexcept
Creates a copy of another transform.
AffineTransform (float mat00, float mat01, float mat02, float mat10, float mat11, float mat12) noexcept
Creates a transform from a set of raw matrix values.
AffineTransform & operator= (const AffineTransform &other) noexcept
Copies from another AffineTransform object.
bool operator== (const AffineTransform &other) const noexcept
Compares two transforms.
bool operator!= (const AffineTransform &other) const noexcept
Compares two transforms.
template<typename ValueType >
void transformPoint (ValueType &x, ValueType &y) const noexcept
Transforms a 2D coordinate using this matrix.
template<typename ValueType >
void transformPoints (ValueType &x1, ValueType &y1, ValueType &x2, ValueType &y2) const noexcept
Transforms two 2D coordinates using this matrix.
template<typename ValueType >
void transformPoints (ValueType &x1, ValueType &y1, ValueType &x2, ValueType &y2, ValueType &x3, ValueType &y3) const noexcept
Transforms three 2D coordinates using this matrix.
AffineTransform translated (float deltaX, float deltaY) const noexcept
Returns a new transform which is the same as this one followed by a translation.
template<typename PointType >
AffineTransform translated (PointType delta) const noexcept
Returns a new transform which is the same as this one followed by a translation.
AffineTransform withAbsoluteTranslation (float translationX, float translationY) const noexcept
Returns a copy of this transform with the specified translation matrix values.
AffineTransform rotated (float angleInRadians) const noexcept
Returns a transform which is the same as this one followed by a rotation.
AffineTransform rotated (float angleInRadians, float pivotX, float pivotY) const noexcept
Returns a transform which is the same as this one followed by a rotation about a given point.
AffineTransform scaled (float factorX, float factorY) const noexcept
Returns a transform which is the same as this one followed by a re-scaling.
AffineTransform scaled (float factor) const noexcept
Returns a transform which is the same as this one followed by a re-scaling.
AffineTransform scaled (float factorX, float factorY, float pivotX, float pivotY) const noexcept
Returns a transform which is the same as this one followed by a re-scaling.
AffineTransform sheared (float shearX, float shearY) const noexcept
Returns a transform which is the same as this one followed by a shear.
AffineTransform inverted () const noexcept
Returns a matrix which is the inverse operation of this one.
AffineTransform followedBy (const AffineTransform &other) const noexcept
Returns the result of concatenating another transformation after this one.
bool isIdentity () const noexcept
Returns true if this transform has no effect on points.
bool isSingularity () const noexcept
Returns true if this transform maps to a singularity - i.e.
bool isOnlyTranslation () const noexcept
Returns true if the transform only translates, and doesn't scale or rotate the points.
float getTranslationX () const noexcept
If this transform is only a translation, this returns the X offset.
float getTranslationY () const noexcept
If this transform is only a translation, this returns the X offset.
float getScaleFactor () const noexcept
Returns the approximate scale factor by which lengths will be transformed.
Static Public Member Functions
static AffineTransform translation (float deltaX, float deltaY) noexcept
Returns a new transform which is a translation.
template<typename PointType >
static AffineTransform translation (PointType delta) noexcept
Returns a new transform which is a translation.
static AffineTransform rotation (float angleInRadians) noexcept
Returns a new transform which is a rotation about (0, 0).
static AffineTransform rotation (float angleInRadians, float pivotX, float pivotY) noexcept
Returns a new transform which is a rotation about a given point.
static AffineTransform scale (float factorX, float factorY) noexcept
Returns a new transform which is a re-scale about the origin.
static AffineTransform scale (float factor) noexcept
Returns a new transform which is a re-scale about the origin.
static AffineTransform scale (float factorX, float factorY, float pivotX, float pivotY) noexcept
Returns a new transform which is a re-scale centred around the point provided.
static AffineTransform shear (float shearX, float shearY) noexcept
Returns a shear transform, centred around the origin (0, 0).
static AffineTransform verticalFlip (float height) noexcept
Returns a transform that will flip coordinates vertically within a window of the given height.
static AffineTransform fromTargetPoints (float x00, float y00, float x10, float y10, float x01, float y01) noexcept
Returns the transform that will map three known points onto three coordinates that are supplied.
static AffineTransform fromTargetPoints (float sourceX1, float sourceY1, float targetX1, float targetY1, float sourceX2, float sourceY2, float targetX2, float targetY2, float sourceX3, float sourceY3, float targetX3, float targetY3) noexcept
Returns the transform that will map three specified points onto three target points.
Public Attributes
float mat00
float mat01
float mat02
float mat10
float mat11
float mat12
Constructor & Destructor Documentation
AffineTransform::AffineTransform () noexcept
Creates an identity transform.
AffineTransform::AffineTransform (const AffineTransform & other) noexcept
Creates a copy of another transform.
AffineTransform::AffineTransform (float mat00, float mat01, float mat02, float mat10, float mat11, float mat12) noexcept
Creates a transform from a set of raw matrix values.
The resulting matrix is:
(mat00 mat01 mat02)
(mat10 mat11 mat12)
(0     0     1)
Member Function Documentation
AffineTransform& AffineTransform::operator= (const AffineTransform & other) noexcept
Copies from another AffineTransform object.
bool AffineTransform::operator== (const AffineTransform & other) const noexcept
Compares two transforms.
bool AffineTransform::operator!= (const AffineTransform & other) const noexcept
Compares two transforms.
template<typename ValueType > void AffineTransform::transformPoint (ValueType & x, ValueType & y) const noexcept
Transforms a 2D coordinate using this matrix.
template<typename ValueType > void AffineTransform::transformPoints (ValueType & x1, ValueType & y1, ValueType & x2, ValueType & y2) const noexcept
Transforms two 2D coordinates using this matrix.
This is just a shortcut for calling transformPoint() on each of these pairs of coordinates in turn. (And putting all the calculations into one function hopefully also gives the compiler a bit more scope for pipelining it).
template<typename ValueType > void AffineTransform::transformPoints (ValueType & x1, ValueType & y1, ValueType & x2, ValueType & y2, ValueType & x3, ValueType & y3) const noexcept
Transforms three 2D coordinates using this matrix.
This is just a shortcut for calling transformPoint() on each of these pairs of coordinates in turn. (And putting all the calculations into one function hopefully also gives the compiler a bit more scope for pipelining it).
AffineTransform AffineTransform::translated (float deltaX, float deltaY) const noexcept
Returns a new transform which is the same as this one followed by a translation.
template<typename PointType > AffineTransform AffineTransform::translated (PointType delta) const noexcept
Returns a new transform which is the same as this one followed by a translation.
static AffineTransform AffineTransform::translation (float deltaX, float deltaY) static noexcept
Returns a new transform which is a translation.
template<typename PointType > static AffineTransform AffineTransform::translation (PointType delta) static noexcept
Returns a new transform which is a translation.
AffineTransform AffineTransform::withAbsoluteTranslation (float translationX, float translationY) const noexcept
Returns a copy of this transform with the specified translation matrix values.
AffineTransform AffineTransform::rotated (float angleInRadians) const noexcept
Returns a transform which is the same as this one followed by a rotation.
The rotation is specified by a number of radians to rotate clockwise, centred around the origin (0, 0).
AffineTransform AffineTransform::rotated (float angleInRadians, float pivotX, float pivotY) const noexcept
Returns a transform which is the same as this one followed by a rotation about a given point.
The rotation is specified by a number of radians to rotate clockwise, centred around the coordinates passed in.
static AffineTransform AffineTransform::rotation (float angleInRadians) static noexcept
Returns a new transform which is a rotation about (0, 0).
static AffineTransform AffineTransform::rotation (float angleInRadians, float pivotX, float pivotY) static noexcept
Returns a new transform which is a rotation about a given point.
AffineTransform AffineTransform::scaled (float factorX, float factorY) const noexcept
Returns a transform which is the same as this one followed by a re-scaling.
The scaling is centred around the origin (0, 0).
AffineTransform AffineTransform::scaled (float factor) const noexcept
Returns a transform which is the same as this one followed by a re-scaling.
The scaling is centred around the origin (0, 0).
AffineTransform AffineTransform::scaled (float factorX, float factorY, float pivotX, float pivotY) const noexcept
Returns a transform which is the same as this one followed by a re-scaling.
The scaling is centred around the origin provided.
static AffineTransform AffineTransform::scale (float factorX, float factorY) static noexcept
Returns a new transform which is a re-scale about the origin.
static AffineTransform AffineTransform::scale (float factor) static noexcept
Returns a new transform which is a re-scale about the origin.
static AffineTransform AffineTransform::scale (float factorX, float factorY, float pivotX, float pivotY) static noexcept
Returns a new transform which is a re-scale centred around the point provided.
AffineTransform AffineTransform::sheared (float shearX, float shearY) const noexcept
Returns a transform which is the same as this one followed by a shear.
The shear is centred around the origin (0, 0).
static AffineTransform AffineTransform::shear (float shearX, float shearY) static noexcept
Returns a shear transform, centred around the origin (0, 0).
static AffineTransform AffineTransform::verticalFlip (float height) static noexcept
Returns a transform that will flip coordinates vertically within a window of the given height.
This is handy for converting between upside-down coordinate systems such as OpenGL or CoreGraphics.
AffineTransform AffineTransform::inverted () const noexcept
Returns a matrix which is the inverse operation of this one.
Some matrices don't have an inverse - in this case, the method will just return an identity transform.
static AffineTransform AffineTransform::fromTargetPoints (float x00, float y00, float x10, float y10, float x01, float y01) static noexcept
Returns the transform that will map three known points onto three coordinates that are supplied.
This returns the transform that will transform (0, 0) into (x00, y00), (1, 0) to (x10, y10), and (0, 1) to (x01, y01).
static AffineTransform AffineTransform::fromTargetPoints (float sourceX1, float sourceY1, float targetX1, float targetY1, float sourceX2, float sourceY2, float targetX2, float targetY2, float sourceX3, float sourceY3, float targetX3, float targetY3) static noexcept
Returns the transform that will map three specified points onto three target points.
AffineTransform AffineTransform::followedBy (const AffineTransform & other) const noexcept
Returns the result of concatenating another transformation after this one.
bool AffineTransform::isIdentity () const noexcept
Returns true if this transform has no effect on points.
bool AffineTransform::isSingularity () const noexcept
Returns true if this transform maps to a singularity - i.e.
if it has no inverse.
bool AffineTransform::isOnlyTranslation () const noexcept
Returns true if the transform only translates, and doesn't scale or rotate the points.
float AffineTransform::getTranslationX () const noexcept
If this transform is only a translation, this returns the X offset.
See Also
isOnlyTranslation
float AffineTransform::getTranslationY () const noexcept
If this transform is only a translation, this returns the X offset.
See Also
isOnlyTranslation
float AffineTransform::getScaleFactor () const noexcept
Returns the approximate scale factor by which lengths will be transformed.
Obviously a length may be scaled by entirely different amounts depending on its direction, so this is only appropriate as a rough guide.
Member Data Documentation
float AffineTransform::mat00
float AffineTransform::mat01
float AffineTransform::mat02
float AffineTransform::mat10
float AffineTransform::mat11
float AffineTransform::mat12
class BorderSize
template<typename ValueType>
class BorderSize< ValueType >
Specifies a set of gaps to be left around the sides of a rectangle.
This is basically the size of the spaces at the top, bottom, left and right of a rectangle. It's used by various component classes to specify borders.
See Also
Rectangle
Public Member Functions
BorderSize () noexcept
Creates a null border.
BorderSize (const BorderSize &other) noexcept
Creates a copy of another border.
BorderSize (ValueType topGap, ValueType leftGap, ValueType bottomGap, ValueType rightGap) noexcept
Creates a border with the given gaps.
BorderSize (ValueType allGaps) noexcept
Creates a border with the given gap on all sides.
ValueType getTop () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getLeft () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getBottom () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getRight () const noexcept
Returns the gap that should be left at the top of the region.
ValueType getTopAndBottom () const noexcept
Returns the sum of the top and bottom gaps.
ValueType getLeftAndRight () const noexcept
Returns the sum of the left and right gaps.
bool isEmpty () const noexcept
Returns true if this border has no thickness along any edge.
void setTop (ValueType newTopGap) noexcept
Changes the top gap.
void setLeft (ValueType newLeftGap) noexcept
Changes the left gap.
void setBottom (ValueType newBottomGap) noexcept
Changes the bottom gap.
void setRight (ValueType newRightGap) noexcept
Changes the right gap.
Rectangle< ValueType > subtractedFrom (const Rectangle< ValueType > &original) const noexcept
Returns a rectangle with these borders removed from it.
void subtractFrom (Rectangle< ValueType > &rectangle) const noexcept
Removes this border from a given rectangle.
Rectangle< ValueType > addedTo (const Rectangle< ValueType > &original) const noexcept
Returns a rectangle with these borders added around it.
void addTo (Rectangle< ValueType > &rectangle) const noexcept
Adds this border around a given rectangle.
bool operator== (const BorderSize &other) const noexcept
bool operator!= (const BorderSize &other) const noexcept
Constructor & Destructor Documentation
template<typename ValueType> BorderSize< ValueType >::BorderSize () noexcept
Creates a null border.
All sizes are left as 0.
template<typename ValueType> BorderSize< ValueType >::BorderSize (const BorderSize< ValueType > & other) noexcept
Creates a copy of another border.
template<typename ValueType> BorderSize< ValueType >::BorderSize (ValueType topGap, ValueType leftGap, ValueType bottomGap, ValueType rightGap) noexcept
Creates a border with the given gaps.
template<typename ValueType> BorderSize< ValueType >::BorderSize (ValueType allGaps) explicit noexcept
Creates a border with the given gap on all sides.
Member Function Documentation
template<typename ValueType> ValueType BorderSize< ValueType >::getTop () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType BorderSize< ValueType >::getLeft () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType BorderSize< ValueType >::getBottom () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType BorderSize< ValueType >::getRight () const noexcept
Returns the gap that should be left at the top of the region.
template<typename ValueType> ValueType BorderSize< ValueType >::getTopAndBottom () const noexcept
Returns the sum of the top and bottom gaps.
template<typename ValueType> ValueType BorderSize< ValueType >::getLeftAndRight () const noexcept
Returns the sum of the left and right gaps.
template<typename ValueType> bool BorderSize< ValueType >::isEmpty () const noexcept
Returns true if this border has no thickness along any edge.
template<typename ValueType> void BorderSize< ValueType >::setTop (ValueType newTopGap) noexcept
Changes the top gap.
template<typename ValueType> void BorderSize< ValueType >::setLeft (ValueType newLeftGap) noexcept
Changes the left gap.
template<typename ValueType> void BorderSize< ValueType >::setBottom (ValueType newBottomGap) noexcept
Changes the bottom gap.
template<typename ValueType> void BorderSize< ValueType >::setRight (ValueType newRightGap) noexcept
Changes the right gap.
template<typename ValueType> Rectangle<ValueType> BorderSize< ValueType >::subtractedFrom (const Rectangle< ValueType > & original) const noexcept
Returns a rectangle with these borders removed from it.
Referenced by BorderSize< int >::subtractFrom().
template<typename ValueType> void BorderSize< ValueType >::subtractFrom (Rectangle< ValueType > & rectangle) const noexcept
Removes this border from a given rectangle.
template<typename ValueType> Rectangle<ValueType> BorderSize< ValueType >::addedTo (const Rectangle< ValueType > & original) const noexcept
Returns a rectangle with these borders added around it.
Referenced by BorderSize< int >::addTo().
template<typename ValueType> void BorderSize< ValueType >::addTo (Rectangle< ValueType > & rectangle) const noexcept
Adds this border around a given rectangle.
template<typename ValueType> bool BorderSize< ValueType >::operator== (const BorderSize< ValueType > & other) const noexcept
Referenced by BorderSize< int >::operator!=().
template<typename ValueType> bool BorderSize< ValueType >::operator!= (const BorderSize< ValueType > & other) const noexcept
class EdgeTable
A table of horizontal scan-line segments - used for rasterising Paths.
See Also
Path, Graphics
Public Member Functions
EdgeTable (const Rectangle< int > &clipLimits, const Path &pathToAdd, const AffineTransform &transform)
Creates an edge table containing a path.
EdgeTable (const Rectangle< int > &rectangleToAdd)
Creates an edge table containing a rectangle.
EdgeTable (const RectangleList< int > &rectanglesToAdd)
Creates an edge table containing a rectangle list.
EdgeTable (const RectangleList< float > &rectanglesToAdd)
Creates an edge table containing a rectangle list.
EdgeTable (const Rectangle< float > &rectangleToAdd)
Creates an edge table containing a rectangle.
EdgeTable (const EdgeTable &)
Creates a copy of another edge table.
EdgeTable & operator= (const EdgeTable &)
Copies from another edge table.
~EdgeTable ()
Destructor.
void clipToRectangle (const Rectangle< int > &r)
void excludeRectangle (const Rectangle< int > &r)
void clipToEdgeTable (const EdgeTable &)
void clipLineToMask (int x, int y, const uint8 *mask, int maskStride, int numPixels)
bool isEmpty () noexcept
const Rectangle< int > & getMaximumBounds () const noexcept
void translate (float dx, int dy) noexcept
void multiplyLevels (float factor)
Scales all the alpha-levels in the table by the given multiplier.
void optimiseTable ()
Reduces the amount of space the table has allocated.
template<class EdgeTableIterationCallback >
void iterate (EdgeTableIterationCallback &iterationCallback) const noexcept
Iterates the lines in the table, for rendering.
Constructor & Destructor Documentation
EdgeTable::EdgeTable (const Rectangle< int > & clipLimits, const Path & pathToAdd, const AffineTransform & transform)
Creates an edge table containing a path.
A table is created with a fixed vertical range, and only sections of the path which lie within this range will be added to the table.
Parameters
clipLimits only the region of the path that lies within this area will be added
pathToAdd the path to add to the table
transform a transform to apply to the path being added
EdgeTable::EdgeTable (const Rectangle< int > & rectangleToAdd) explicit
Creates an edge table containing a rectangle.
EdgeTable::EdgeTable (const RectangleList< int > & rectanglesToAdd) explicit
Creates an edge table containing a rectangle list.
EdgeTable::EdgeTable (const RectangleList< float > & rectanglesToAdd) explicit
Creates an edge table containing a rectangle list.
EdgeTable::EdgeTable (const Rectangle< float > & rectangleToAdd) explicit
Creates an edge table containing a rectangle.
EdgeTable::EdgeTable (const EdgeTable &)
Creates a copy of another edge table.
EdgeTable::~EdgeTable ()
Destructor.
Member Function Documentation
EdgeTable& EdgeTable::operator= (const EdgeTable &)
Copies from another edge table.
void EdgeTable::clipToRectangle (const Rectangle< int > & r)
void EdgeTable::excludeRectangle (const Rectangle< int > & r)
void EdgeTable::clipToEdgeTable (const EdgeTable &)
void EdgeTable::clipLineToMask (int x, int y, const uint8 * mask, int maskStride, int numPixels)
bool EdgeTable::isEmpty () noexcept
const Rectangle<int>& EdgeTable::getMaximumBounds () const noexcept
void EdgeTable::translate (float dx, int dy) noexcept
void EdgeTable::multiplyLevels (float factor)
Scales all the alpha-levels in the table by the given multiplier.
void EdgeTable::optimiseTable ()
Reduces the amount of space the table has allocated.
This will shrink the table down to use as little memory as possible - useful for read-only tables that get stored and re-used for rendering.
template<class EdgeTableIterationCallback > void EdgeTable::iterate (EdgeTableIterationCallback & iterationCallback) const noexcept
Iterates the lines in the table, for rendering.
This function will iterate each line in the table, and call a user-defined class to render each pixel or continuous line of pixels that the table contains.
Parameters
iterationCallback this templated class must contain the following methods:
inline void setEdgeTableYPos (int y);
inline void handleEdgeTablePixel (int x, int alphaLevel) const;
inline void handleEdgeTablePixelFull (int x) const;
inline void handleEdgeTableLine (int x, int width, int alphaLevel) const;
inline void handleEdgeTableLineFull (int x, int width) const;
(these don't necessarily have to be 'const', but it might help it go faster)
References isPositiveAndBelow(), and jassert.
class Line
template<typename ValueType>
class Line< ValueType >
Represents a line.
This class contains a bunch of useful methods for various geometric tasks.
The ValueType template parameter should be a primitive type - float or double are what it's designed for. Integer types will work in a basic way, but some methods that perform mathematical operations may not compile, or they may not produce sensible results.
See Also
Point, Rectangle, Path, Graphics::drawLine
Public Member Functions
Line () noexcept
Creates a line, using (0, 0) as its start and end points.
Line (const Line &other) noexcept
Creates a copy of another line.
Line (ValueType startX, ValueType startY, ValueType endX, ValueType endY) noexcept
Creates a line based on the coordinates of its start and end points.
Line (Point< ValueType > startPoint, Point< ValueType > endPoint) noexcept
Creates a line from its start and end points.
Line & operator= (const Line &other) noexcept
Copies a line from another one.
~Line () noexcept
Destructor.
ValueType getStartX () const noexcept
Returns the x coordinate of the line's start point.
ValueType getStartY () const noexcept
Returns the y coordinate of the line's start point.
ValueType getEndX () const noexcept
Returns the x coordinate of the line's end point.
ValueType getEndY () const noexcept
Returns the y coordinate of the line's end point.
Point< ValueType > getStart () const noexcept
Returns the line's start point.
Point< ValueType > getEnd () const noexcept
Returns the line's end point.
void setStart (ValueType newStartX, ValueType newStartY) noexcept
Changes this line's start point.
void setEnd (ValueType newEndX, ValueType newEndY) noexcept
Changes this line's end point.
void setStart (const Point< ValueType > newStart) noexcept
Changes this line's start point.
void setEnd (const Point< ValueType > newEnd) noexcept
Changes this line's end point.
Line reversed () const noexcept
Returns a line that is the same as this one, but with the start and end reversed,.
void applyTransform (const AffineTransform &transform) noexcept
Applies an affine transform to the line's start and end points.
ValueType getLength () const noexcept
Returns the length of the line.
ValueType getLengthSquared () const noexcept
Returns the length of the line.
bool isVertical () const noexcept
Returns true if the line's start and end x coordinates are the same.
bool isHorizontal () const noexcept
Returns true if the line's start and end y coordinates are the same.
Point< ValueType >::FloatType getAngle () const noexcept
Returns the line's angle.
Line< float > toFloat () const noexcept
Casts this line to float coordinates.
Line< double > toDouble () const noexcept
Casts this line to double coordinates.
bool operator== (Line other) const noexcept
Compares two lines.
bool operator!= (Line other) const noexcept
Compares two lines.
Point< ValueType > getIntersection (Line line) const noexcept
Finds the intersection between two lines.
bool intersects (Line line, Point< ValueType > &intersection) const noexcept
Finds the intersection between two lines.
bool intersects (Line other) const noexcept
Returns true if this line intersects another.
Point< ValueType > getPointAlongLine (ValueType distanceFromStart) const noexcept
Returns the location of the point which is a given distance along this line.
Point< ValueType > getPointAlongLine (ValueType distanceFromStart, ValueType perpendicularDistance) const noexcept
Returns a point which is a certain distance along and to the side of this line.
Point< ValueType > getPointAlongLineProportionally (typename Point< ValueType >::FloatType proportionOfLength) const noexcept
Returns the location of the point which is a given distance along this line proportional to the line's length.
ValueType getDistanceFromPoint (Point< ValueType > targetPoint, Point< ValueType > &pointOnLine) const noexcept
Returns the smallest distance between this line segment and a given point.
ValueType findNearestProportionalPositionTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point, and returns its position as a proportional position along the line.
Point< ValueType > findNearestPointTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point.
bool isPointAbove (Point< ValueType > point) const noexcept
Returns true if the given point lies above this line.
Line withShortenedStart (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
Line withShortenedEnd (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
Static Public Member Functions
static Line fromStartAndAngle (Point< ValueType > startPoint, ValueType length, ValueType angle) noexcept
Creates a line from a start point, length and angle.
Constructor & Destructor Documentation
template<typename ValueType> Line< ValueType >::Line () noexcept
Creates a line, using (0, 0) as its start and end points.
template<typename ValueType> Line< ValueType >::Line (const Line< ValueType > & other) noexcept
Creates a copy of another line.
template<typename ValueType> Line< ValueType >::Line (ValueType startX, ValueType startY, ValueType endX, ValueType endY) noexcept
Creates a line based on the coordinates of its start and end points.
template<typename ValueType> Line< ValueType >::Line (Point< ValueType > startPoint, Point< ValueType > endPoint) noexcept
Creates a line from its start and end points.
template<typename ValueType> Line< ValueType >::~Line () noexcept
Destructor.
Member Function Documentation
template<typename ValueType> Line& Line< ValueType >::operator= (const Line< ValueType > & other) noexcept
Copies a line from another one.
template<typename ValueType> ValueType Line< ValueType >::getStartX () const noexcept
Returns the x coordinate of the line's start point.
template<typename ValueType> ValueType Line< ValueType >::getStartY () const noexcept
Returns the y coordinate of the line's start point.
template<typename ValueType> ValueType Line< ValueType >::getEndX () const noexcept
Returns the x coordinate of the line's end point.
template<typename ValueType> ValueType Line< ValueType >::getEndY () const noexcept
Returns the y coordinate of the line's end point.
template<typename ValueType> Point<ValueType> Line< ValueType >::getStart () const noexcept
Returns the line's start point.
template<typename ValueType> Point<ValueType> Line< ValueType >::getEnd () const noexcept
Returns the line's end point.
template<typename ValueType> void Line< ValueType >::setStart (ValueType newStartX, ValueType newStartY) noexcept
Changes this line's start point.
template<typename ValueType> void Line< ValueType >::setEnd (ValueType newEndX, ValueType newEndY) noexcept
Changes this line's end point.
template<typename ValueType> void Line< ValueType >::setStart (const Point< ValueType > newStart) noexcept
Changes this line's start point.
template<typename ValueType> void Line< ValueType >::setEnd (const Point< ValueType > newEnd) noexcept
Changes this line's end point.
template<typename ValueType> Line Line< ValueType >::reversed () const noexcept
Returns a line that is the same as this one, but with the start and end reversed,.
template<typename ValueType> void Line< ValueType >::applyTransform (const AffineTransform & transform) noexcept
Applies an affine transform to the line's start and end points.
template<typename ValueType> ValueType Line< ValueType >::getLength () const noexcept
Returns the length of the line.
Referenced by Line< ValueType >::getPointAlongLine(), Line< ValueType >::withShortenedEnd(), and Line< ValueType >::withShortenedStart().
template<typename ValueType> ValueType Line< ValueType >::getLengthSquared () const noexcept
Returns the length of the line.
template<typename ValueType> bool Line< ValueType >::isVertical () const noexcept
Returns true if the line's start and end x coordinates are the same.
template<typename ValueType> bool Line< ValueType >::isHorizontal () const noexcept
Returns true if the line's start and end y coordinates are the same.
template<typename ValueType> Point<ValueType>::FloatType Line< ValueType >::getAngle () const noexcept
Returns the line's angle.
This value is the number of radians clockwise from the 12 o'clock direction, where the line's start point is considered to be at the centre.
template<typename ValueType> static Line Line< ValueType >::fromStartAndAngle (Point< ValueType > startPoint, ValueType length, ValueType angle) static noexcept
Creates a line from a start point, length and angle.
This angle is the number of radians clockwise from the 12 o'clock direction, where the line's start point is considered to be at the centre.
template<typename ValueType> Line<float> Line< ValueType >::toFloat () const noexcept
Casts this line to float coordinates.
template<typename ValueType> Line<double> Line< ValueType >::toDouble () const noexcept
Casts this line to double coordinates.
template<typename ValueType> bool Line< ValueType >::operator== (Line< ValueType > other) const noexcept
Compares two lines.
template<typename ValueType> bool Line< ValueType >::operator!= (Line< ValueType > other) const noexcept
Compares two lines.
template<typename ValueType> Point<ValueType> Line< ValueType >::getIntersection (Line< ValueType > line) const noexcept
Finds the intersection between two lines.
Parameters
line the line to intersect with
Returns
the point at which the lines intersect, even if this lies beyond the end of the lines
template<typename ValueType> bool Line< ValueType >::intersects (Line< ValueType > line, Point< ValueType > & intersection) const noexcept
Finds the intersection between two lines.
Parameters
line the other line
intersection the position of the point where the lines meet (or where they would meet if they were infinitely long) the intersection (if the lines intersect). If the lines are parallel, this will just be set to the position of one of the line's endpoints.
Returns
true if the line segments intersect; false if they dont. Even if they don't intersect, the intersection coordinates returned will still be valid
template<typename ValueType> bool Line< ValueType >::intersects (Line< ValueType > other) const noexcept
Returns true if this line intersects another.
template<typename ValueType> Point<ValueType> Line< ValueType >::getPointAlongLine (ValueType distanceFromStart) const noexcept
Returns the location of the point which is a given distance along this line.
Parameters
distanceFromStart the distance to move along the line from its start point. This value can be negative or longer than the line itself
See Also
getPointAlongLineProportionally
References Line< ValueType >::getLength().
Referenced by Line< ValueType >::withShortenedEnd(), and Line< ValueType >::withShortenedStart().
template<typename ValueType> Point<ValueType> Line< ValueType >::getPointAlongLine (ValueType distanceFromStart, ValueType perpendicularDistance) const noexcept
Returns a point which is a certain distance along and to the side of this line.
This effectively moves a given distance along the line, then another distance perpendicularly to this, and returns the resulting position.
Parameters
distanceFromStart the distance to move along the line from its start point. This value can be negative or longer than the line itself
perpendicularDistance how far to move sideways from the line. If you're looking along the line from its start towards its end, then a positive value here will move to the right, negative value move to the left.
References juce_hypot().
template<typename ValueType> Point<ValueType> Line< ValueType >::getPointAlongLineProportionally (typename Point< ValueType >::FloatType proportionOfLength) const noexcept
Returns the location of the point which is a given distance along this line proportional to the line's length.
Parameters
proportionOfLength the distance to move along the line from its start point, in multiples of the line's length. So a value of 0.0 will return the line's start point and a value of 1.0 will return its end point. (This value can be negative or greater than 1.0).
See Also
getPointAlongLine
Referenced by Line< ValueType >::findNearestPointTo().
template<typename ValueType> ValueType Line< ValueType >::getDistanceFromPoint (Point< ValueType > targetPoint, Point< ValueType > & pointOnLine) const noexcept
Returns the smallest distance between this line segment and a given point.
So if the point is close to the line, this will return the perpendicular distance from the line; if the point is a long way beyond one of the line's end-point's, it'll return the straight-line distance to the nearest end-point.
pointOnLine receives the position of the point that is found.
Returns
the point's distance from the line
See Also
getPositionAlongLineOfNearestPoint
template<typename ValueType> ValueType Line< ValueType >::findNearestProportionalPositionTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point, and returns its position as a proportional position along the line.
Returns
a value 0 to 1.0 which is the distance along this line from the line's start to the point which is nearest to the point passed-in. To turn this number into a position, use getPointAlongLineProportionally().
See Also
getDistanceFromPoint, getPointAlongLineProportionally
References jlimit().
Referenced by Line< ValueType >::findNearestPointTo().
template<typename ValueType> Point<ValueType> Line< ValueType >::findNearestPointTo (Point< ValueType > point) const noexcept
Finds the point on this line which is nearest to a given point.
See Also
getDistanceFromPoint, findNearestProportionalPositionTo
References Line< ValueType >::findNearestProportionalPositionTo(), and Line< ValueType >::getPointAlongLineProportionally().
template<typename ValueType> bool Line< ValueType >::isPointAbove (Point< ValueType > point) const noexcept
Returns true if the given point lies above this line.
The return value is true if the point's y coordinate is less than the y coordinate of this line at the given x (assuming the line extends infinitely in both directions).
template<typename ValueType> Line Line< ValueType >::withShortenedStart (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
This will chop off part of the start of this line by a certain amount, (leaving the end-point the same), and return the new line.
References Line< ValueType >::getLength(), Line< ValueType >::getPointAlongLine(), and jmin().
template<typename ValueType> Line Line< ValueType >::withShortenedEnd (ValueType distanceToShortenBy) const noexcept
Returns a shortened copy of this line.
This will chop off part of the end of this line by a certain amount, (leaving the start-point the same), and return the new line.
References Line< ValueType >::getLength(), Line< ValueType >::getPointAlongLine(), and jmin().
class Path
A path is a sequence of lines and curves that may either form a closed shape or be open-ended.
To use a path, you can create an empty one, then add lines and curves to it to create shapes, then it can be rendered by a Graphics context or used for geometric operations.
e.g.
Path myPath;
myPath.startNewSubPath (10.0f, 10.0f);          // move the current position to (10, 10)
myPath.lineTo (100.0f, 200.0f);                 // draw a line from here to (100, 200)
myPath.quadraticTo (0.0f, 150.0f, 5.0f, 50.0f); // draw a curve that ends at (5, 50)
myPath.closeSubPath();                          // close the subpath with a line back to (10, 10)
// add an ellipse as well, which will form a second sub-path within the path..
myPath.addEllipse (50.0f, 50.0f, 40.0f, 30.0f);
// double the width of the whole thing..
myPath.applyTransform (AffineTransform::scale (2.0f, 1.0f));
// and draw it to a graphics context with a 5-pixel thick outline.
g.strokePath (myPath, PathStrokeType (5.0f));
A path object can actually contain multiple sub-paths, which may themselves be open or closed.
See Also
PathFlatteningIterator, PathStrokeType, Graphics
Public Member Functions
Path ()
Creates an empty path.
Path (const Path &)
Creates a copy of another path.
~Path ()
Destructor.
Path & operator= (const Path &)
Copies this path from another one.
Path (Path &&) noexcept
Move constructor.
Path & operator= (Path &&) noexcept
Move assignment operator.
bool operator== (const Path &) const noexcept
bool operator!= (const Path &) const noexcept
bool isEmpty () const noexcept
Returns true if the path doesn't contain any lines or curves.
Rectangle< float > getBounds () const noexcept
Returns the smallest rectangle that contains all points within the path.
Rectangle< float > getBoundsTransformed (const AffineTransform &transform) const noexcept
Returns the smallest rectangle that contains all points within the path after it's been transformed with the given tranasform matrix.
bool contains (float x, float y, float tolerance=defaultToleranceForTesting) const
Checks whether a point lies within the path.
bool contains (Point< float > point, float tolerance=defaultToleranceForTesting) const
Checks whether a point lies within the path.
bool intersectsLine (Line< float > line, float tolerance=defaultToleranceForTesting)
Checks whether a line crosses the path.
Line< float > getClippedLine (Line< float > line, bool keepSectionOutsidePath) const
Cuts off parts of a line to keep the parts that are either inside or outside this path.
float getLength (const AffineTransform &transform=AffineTransform(), float tolerance=defaultToleranceForMeasurement) const
Returns the length of the path.
Point< float > getPointAlongPath (float distanceFromStart, const AffineTransform &transform=AffineTransform(), float tolerance=defaultToleranceForMeasurement) const
Returns a point that is the specified distance along the path.
float getNearestPoint (Point< float > targetPoint, Point< float > &pointOnPath, const AffineTransform &transform=AffineTransform(), float tolerance=defaultToleranceForMeasurement) const
Finds the point along the path which is nearest to a given position.
void clear () noexcept
Removes all lines and curves, resetting the path completely.
void startNewSubPath (float startX, float startY)
Begins a new subpath with a given starting position.
void startNewSubPath (Point< float > start)
Begins a new subpath with a given starting position.
void closeSubPath ()
Closes a the current sub-path with a line back to its start-point.
void lineTo (float endX, float endY)
Adds a line from the shape's last position to a new end-point.
void lineTo (Point< float > end)
Adds a line from the shape's last position to a new end-point.
void quadraticTo (float controlPointX, float controlPointY, float endPointX, float endPointY)
Adds a quadratic bezier curve from the shape's last position to a new position.
void quadraticTo (Point< float > controlPoint, Point< float > endPoint)
Adds a quadratic bezier curve from the shape's last position to a new position.
void cubicTo (float controlPoint1X, float controlPoint1Y, float controlPoint2X, float controlPoint2Y, float endPointX, float endPointY)
Adds a cubic bezier curve from the shape's last position to a new position.
void cubicTo (Point< float > controlPoint1, Point< float > controlPoint2, Point< float > endPoint)
Adds a cubic bezier curve from the shape's last position to a new position.
Point< float > getCurrentPosition () const
Returns the last point that was added to the path by one of the drawing methods.
void addRectangle (float x, float y, float width, float height)
Adds a rectangle to the path.
template<typename ValueType >
void addRectangle (Rectangle< ValueType > rectangle)
Adds a rectangle to the path.
void addRoundedRectangle (float x, float y, float width, float height, float cornerSize)
Adds a rectangle with rounded corners to the path.
void addRoundedRectangle (float x, float y, float width, float height, float cornerSizeX, float cornerSizeY)
Adds a rectangle with rounded corners to the path.
void addRoundedRectangle (float x, float y, float width, float height, float cornerSizeX, float cornerSizeY, bool curveTopLeft, bool curveTopRight, bool curveBottomLeft, bool curveBottomRight)
Adds a rectangle with rounded corners to the path.
template<typename ValueType >
void addRoundedRectangle (Rectangle< ValueType > rectangle, float cornerSizeX, float cornerSizeY)
Adds a rectangle with rounded corners to the path.
template<typename ValueType >
void addRoundedRectangle (Rectangle< ValueType > rectangle, float cornerSize)
Adds a rectangle with rounded corners to the path.
void addTriangle (float x1, float y1, float x2, float y2, float x3, float y3)
Adds a triangle to the path.
void addTriangle (Point< float > point1, Point< float > point2, Point< float > point3)
Adds a triangle to the path.
void addQuadrilateral (float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4)
Adds a quadrilateral to the path.
void addEllipse (float x, float y, float width, float height)
Adds an ellipse to the path.
void addEllipse (Rectangle< float > area)
Adds an ellipse to the path.
void addArc (float x, float y, float width, float height, float fromRadians, float toRadians, bool startAsNewSubPath=false)
Adds an elliptical arc to the current path.
void addCentredArc (float centreX, float centreY, float radiusX, float radiusY, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath=false)
Adds an arc which is centred at a given point, and can have a rotation specified.
void addPieSegment (float x, float y, float width, float height, float fromRadians, float toRadians, float innerCircleProportionalSize)
Adds a "pie-chart" shape to the path.
void addPieSegment (Rectangle< float > segmentBounds, float fromRadians, float toRadians, float innerCircleProportionalSize)
Adds a "pie-chart" shape to the path.
void addLineSegment (Line< float > line, float lineThickness)
Adds a line with a specified thickness.
void addArrow (Line< float > line, float lineThickness, float arrowheadWidth, float arrowheadLength)
Adds a line with an arrowhead on the end.
void addPolygon (Point< float > centre, int numberOfSides, float radius, float startAngle=0.0f)
Adds a polygon shape to the path.
void addStar (Point< float > centre, int numberOfPoints, float innerRadius, float outerRadius, float startAngle=0.0f)
Adds a star shape to the path.
void addBubble (Rectangle< float > bodyArea, Rectangle< float > maximumArea, const Point< float > arrowTipPosition, const float cornerSize, const float arrowBaseWidth)
Adds a speech-bubble shape to the path.
void addPath (const Path &pathToAppend)
Adds another path to this one.
void addPath (const Path &pathToAppend, const AffineTransform &transformToApply)
Adds another path to this one, transforming it on the way in.
void swapWithPath (Path &) noexcept
Swaps the contents of this path with another one.
void preallocateSpace (int numExtraCoordsToMakeSpaceFor)
Preallocates enough space for adding the given number of coordinates to the path.
void applyTransform (const AffineTransform &transform) noexcept
Applies a 2D transform to all the vertices in the path.
void scaleToFit (float x, float y, float width, float height, bool preserveProportions) noexcept
Rescales this path to make it fit neatly into a given space.
AffineTransform getTransformToScaleToFit (float x, float y, float width, float height, bool preserveProportions, Justification justificationType=Justification::centred) const
Returns a transform that can be used to rescale the path to fit into a given space.
AffineTransform getTransformToScaleToFit (Rectangle< float > area, bool preserveProportions, Justification justificationType=Justification::centred) const
Returns a transform that can be used to rescale the path to fit into a given space.
Path createPathWithRoundedCorners (float cornerRadius) const
Creates a version of this path where all sharp corners have been replaced by curves.
void setUsingNonZeroWinding (bool isNonZeroWinding) noexcept
Changes the winding-rule to be used when filling the path.
bool isUsingNonZeroWinding () const
Returns the flag that indicates whether the path should use a non-zero winding rule.
void loadPathFromStream (InputStream &source)
Loads a stored path from a data stream.
void loadPathFromData (const void *data, size_t numberOfBytes)
Loads a stored path from a block of data.
void writePathToStream (OutputStream &destination) const
Stores the path by writing it out to a stream.
String toString () const
Creates a string containing a textual representation of this path.
void restoreFromString (StringRef stringVersion)
Restores this path from a string that was created with the toString() method.
Static Public Attributes
static const float defaultToleranceForTesting
static const float defaultToleranceForMeasurement
Constructor & Destructor Documentation
Path::Path ()
Creates an empty path.
Path::Path (const Path &)
Creates a copy of another path.
Path::~Path ()
Destructor.
Path::Path (Path &&) noexcept
Move constructor.
Member Function Documentation
Path& Path::operator= (const Path &)
Copies this path from another one.
Path& Path::operator= (Path &&) noexcept
Move assignment operator.
bool Path::operator== (const Path &) const noexcept
bool Path::operator!= (const Path &) const noexcept
bool Path::isEmpty () const noexcept
Returns true if the path doesn't contain any lines or curves.
Rectangle<float> Path::getBounds () const noexcept
Returns the smallest rectangle that contains all points within the path.
Rectangle<float> Path::getBoundsTransformed (const AffineTransform & transform) const noexcept
Returns the smallest rectangle that contains all points within the path after it's been transformed with the given tranasform matrix.
bool Path::contains (float x, float y, float tolerance = defaultToleranceForTesting) const
Checks whether a point lies within the path.
This is only relevant for closed paths (see closeSubPath()), and may produce false results if used on a path which has open sub-paths.
The path's winding rule is taken into account by this method.
The tolerance parameter is the maximum error allowed when flattening the path, so this method could return a false positive when your point is up to this distance outside the path's boundary.
See Also
closeSubPath, setUsingNonZeroWinding
bool Path::contains (Point< float > point, float tolerance = defaultToleranceForTesting) const
Checks whether a point lies within the path.
This is only relevant for closed paths (see closeSubPath()), and may produce false results if used on a path which has open sub-paths.
The path's winding rule is taken into account by this method.
The tolerance parameter is the maximum error allowed when flattening the path, so this method could return a false positive when your point is up to this distance outside the path's boundary.
See Also
closeSubPath, setUsingNonZeroWinding
bool Path::intersectsLine (Line< float > line, float tolerance = defaultToleranceForTesting)
Checks whether a line crosses the path.
This will return positive if the line crosses any of the paths constituent lines or curves. It doesn't take into account whether the line is inside or outside the path, or whether the path is open or closed.
The tolerance parameter is the maximum error allowed when flattening the path, so this method could return a false positive when your point is up to this distance outside the path's boundary.
Line<float> Path::getClippedLine (Line< float > line, bool keepSectionOutsidePath) const
Cuts off parts of a line to keep the parts that are either inside or outside this path.
Note that this isn't smart enough to cope with situations where the line would need to be cut into multiple pieces to correctly clip against a re-entrant shape.
Parameters
line the line to clip
keepSectionOutsidePath if true, it's the section outside the path that will be kept; if false its the section inside the path
float Path::getLength (const AffineTransform & transform = AffineTransform(), float tolerance = defaultToleranceForMeasurement) const
Returns the length of the path.
See Also
getPointAlongPath
Point<float> Path::getPointAlongPath (float distanceFromStart, const AffineTransform & transform = AffineTransform(), float tolerance = defaultToleranceForMeasurement) const
Returns a point that is the specified distance along the path.
If the distance is greater than the total length of the path, this will return the end point.
See Also
getLength
float Path::getNearestPoint (Point< float > targetPoint, Point< float > & pointOnPath, const AffineTransform & transform = AffineTransform(), float tolerance = defaultToleranceForMeasurement) const
Finds the point along the path which is nearest to a given position.
This sets pointOnPath to the nearest point, and returns the distance of this point from the start of the path.
void Path::clear () noexcept
Removes all lines and curves, resetting the path completely.
void Path::startNewSubPath (float startX, float startY)
Begins a new subpath with a given starting position.
This will move the path's current position to the coordinates passed in and make it ready to draw lines or curves starting from this position.
After adding whatever lines and curves are needed, you can either close the current sub-path using closeSubPath() or call startNewSubPath() to move to a new sub-path, leaving the old one open-ended.
See Also
lineTo, quadraticTo, cubicTo, closeSubPath
void Path::startNewSubPath (Point< float > start)
Begins a new subpath with a given starting position.
This will move the path's current position to the coordinates passed in and make it ready to draw lines or curves starting from this position.
After adding whatever lines and curves are needed, you can either close the current sub-path using closeSubPath() or call startNewSubPath() to move to a new sub-path, leaving the old one open-ended.
See Also
lineTo, quadraticTo, cubicTo, closeSubPath
void Path::closeSubPath ()
Closes a the current sub-path with a line back to its start-point.
When creating a closed shape such as a triangle, don't use 3 lineTo() calls - instead use two lineTo() calls, followed by a closeSubPath() to join the final point back to the start.
This ensures that closes shapes are recognised as such, and this is important for tasks like drawing strokes, which needs to know whether to draw end-caps or not.
See Also
startNewSubPath, lineTo, quadraticTo, cubicTo, closeSubPath
void Path::lineTo (float endX, float endY)
Adds a line from the shape's last position to a new end-point.
This will connect the end-point of the last line or curve that was added to a new point, using a straight line.
See the class description for an example of how to add lines and curves to a path.
See Also
startNewSubPath, quadraticTo, cubicTo, closeSubPath
void Path::lineTo (Point< float > end)
Adds a line from the shape's last position to a new end-point.
This will connect the end-point of the last line or curve that was added to a new point, using a straight line.
See the class description for an example of how to add lines and curves to a path.
See Also
startNewSubPath, quadraticTo, cubicTo, closeSubPath
void Path::quadraticTo (float controlPointX, float controlPointY, float endPointX, float endPointY)
Adds a quadratic bezier curve from the shape's last position to a new position.
This will connect the end-point of the last line or curve that was added to a new point, using a quadratic spline with one control-point.
See the class description for an example of how to add lines and curves to a path.
See Also
startNewSubPath, lineTo, cubicTo, closeSubPath
void Path::quadraticTo (Point< float > controlPoint, Point< float > endPoint)
Adds a quadratic bezier curve from the shape's last position to a new position.
This will connect the end-point of the last line or curve that was added to a new point, using a quadratic spline with one control-point.
See the class description for an example of how to add lines and curves to a path.
See Also
startNewSubPath, lineTo, cubicTo, closeSubPath
void Path::cubicTo (float controlPoint1X, float controlPoint1Y, float controlPoint2X, float controlPoint2Y, float endPointX, float endPointY)
Adds a cubic bezier curve from the shape's last position to a new position.
This will connect the end-point of the last line or curve that was added to a new point, using a cubic spline with two control-points.
See the class description for an example of how to add lines and curves to a path.
See Also
startNewSubPath, lineTo, quadraticTo, closeSubPath
void Path::cubicTo (Point< float > controlPoint1, Point< float > controlPoint2, Point< float > endPoint)
Adds a cubic bezier curve from the shape's last position to a new position.
This will connect the end-point of the last line or curve that was added to a new point, using a cubic spline with two control-points.
See the class description for an example of how to add lines and curves to a path.
See Also
startNewSubPath, lineTo, quadraticTo, closeSubPath
Point<float> Path::getCurrentPosition () const
Returns the last point that was added to the path by one of the drawing methods.
void Path::addRectangle (float x, float y, float width, float height)
Adds a rectangle to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRoundedRectangle, addTriangle
Referenced by RectangleList< int >::toPath().
template<typename ValueType > void Path::addRectangle (Rectangle< ValueType > rectangle)
Adds a rectangle to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRoundedRectangle, addTriangle
void Path::addRoundedRectangle (float x, float y, float width, float height, float cornerSize)
Adds a rectangle with rounded corners to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRectangle, addTriangle
void Path::addRoundedRectangle (float x, float y, float width, float height, float cornerSizeX, float cornerSizeY)
Adds a rectangle with rounded corners to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRectangle, addTriangle
void Path::addRoundedRectangle (float x, float y, float width, float height, float cornerSizeX, float cornerSizeY, bool curveTopLeft, bool curveTopRight, bool curveBottomLeft, bool curveBottomRight)
Adds a rectangle with rounded corners to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRectangle, addTriangle
template<typename ValueType > void Path::addRoundedRectangle (Rectangle< ValueType > rectangle, float cornerSizeX, float cornerSizeY)
Adds a rectangle with rounded corners to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRectangle, addTriangle
References Rectangle< ValueType >::getHeight(), Rectangle< ValueType >::getWidth(), Rectangle< ValueType >::getX(), and Rectangle< ValueType >::getY().
template<typename ValueType > void Path::addRoundedRectangle (Rectangle< ValueType > rectangle, float cornerSize)
Adds a rectangle with rounded corners to the path.
The rectangle is added as a new sub-path. (Any currently open paths will be left open).
See Also
addRectangle, addTriangle
void Path::addTriangle (float x1, float y1, float x2, float y2, float x3, float y3)
Adds a triangle to the path.
The triangle is added as a new closed sub-path. (Any currently open paths will be left open).
Note that whether the vertices are specified in clockwise or anticlockwise order will affect how the triangle is filled when it overlaps other shapes (the winding order setting will affect this of course).
void Path::addTriangle (Point< float > point1, Point< float > point2, Point< float > point3)
Adds a triangle to the path.
The triangle is added as a new closed sub-path. (Any currently open paths will be left open).
Note that whether the vertices are specified in clockwise or anticlockwise order will affect how the triangle is filled when it overlaps other shapes (the winding order setting will affect this of course).
void Path::addQuadrilateral (float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4)
Adds a quadrilateral to the path.
The quad is added as a new closed sub-path. (Any currently open paths will be left open).
Note that whether the vertices are specified in clockwise or anticlockwise order will affect how the quad is filled when it overlaps other shapes (the winding order setting will affect this of course).
void Path::addEllipse (float x, float y, float width, float height)
Adds an ellipse to the path.
The shape is added as a new sub-path. (Any currently open paths will be left open).
See Also
addArc
void Path::addEllipse (Rectangle< float > area)
Adds an ellipse to the path.
The shape is added as a new sub-path. (Any currently open paths will be left open).
See Also
addArc
void Path::addArc (float x, float y, float width, float height, float fromRadians, float toRadians, bool startAsNewSubPath = false)
Adds an elliptical arc to the current path.
Note that when specifying the start and end angles, the curve will be drawn either clockwise or anti-clockwise according to whether the end angle is greater than the start. This means that sometimes you may need to use values greater than 2*Pi for the end angle.
Parameters
x the left-hand edge of the rectangle in which the elliptical outline fits
y the top edge of the rectangle in which the elliptical outline fits
width the width of the rectangle in which the elliptical outline fits
height the height of the rectangle in which the elliptical outline fits
fromRadians the angle (clockwise) in radians at which to start the arc segment (where 0 is the top-centre of the ellipse)
toRadians the angle (clockwise) in radians at which to end the arc segment (where 0 is the top-centre of the ellipse). This angle can be greater than 2*Pi, so for example to draw a curve clockwise from the 9 o'clock position to the 3 o'clock position via 12 o'clock, you'd use 1.5*Pi and 2.5*Pi as the start and finish points.
startAsNewSubPath if true, the arc will begin a new subpath from its starting point; if false, it will be added to the current sub-path, continuing from the current postition
See Also
addCentredArc, arcTo, addPieSegment, addEllipse
void Path::addCentredArc (float centreX, float centreY, float radiusX, float radiusY, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath = false)
Adds an arc which is centred at a given point, and can have a rotation specified.
Note that when specifying the start and end angles, the curve will be drawn either clockwise or anti-clockwise according to whether the end angle is greater than the start. This means that sometimes you may need to use values greater than 2*Pi for the end angle.
Parameters
centreX the centre x of the ellipse
centreY the centre y of the ellipse
radiusX the horizontal radius of the ellipse
radiusY the vertical radius of the ellipse
rotationOfEllipse an angle by which the whole ellipse should be rotated about its centre, in radians (clockwise)
fromRadians the angle (clockwise) in radians at which to start the arc segment (where 0 is the top-centre of the ellipse)
toRadians the angle (clockwise) in radians at which to end the arc segment (where 0 is the top-centre of the ellipse). This angle can be greater than 2*Pi, so for example to draw a curve clockwise from the 9 o'clock position to the 3 o'clock position via 12 o'clock, you'd use 1.5*Pi and 2.5*Pi as the start and finish points.
startAsNewSubPath if true, the arc will begin a new subpath from its starting point; if false, it will be added to the current sub-path, continuing from the current postition
See Also
addArc, arcTo
void Path::addPieSegment (float x, float y, float width, float height, float fromRadians, float toRadians, float innerCircleProportionalSize)
Adds a "pie-chart" shape to the path.
The shape is added as a new sub-path. (Any currently open paths will be left open).
Note that when specifying the start and end angles, the curve will be drawn either clockwise or anti-clockwise according to whether the end angle is greater than the start. This means that sometimes you may need to use values greater than 2*Pi for the end angle.
Parameters
x the left-hand edge of the rectangle in which the elliptical outline fits
y the top edge of the rectangle in which the elliptical outline fits
width the width of the rectangle in which the elliptical outline fits
height the height of the rectangle in which the elliptical outline fits
fromRadians the angle (clockwise) in radians at which to start the arc segment (where 0 is the top-centre of the ellipse)
toRadians the angle (clockwise) in radians at which to end the arc segment (where 0 is the top-centre of the ellipse)
innerCircleProportionalSize if this is > 0, then the pie will be drawn as a curved band around a hollow ellipse at its centre, where this value indicates the inner ellipse's size with respect to the outer one.
See Also
addArc
void Path::addPieSegment (Rectangle< float > segmentBounds, float fromRadians, float toRadians, float innerCircleProportionalSize)
Adds a "pie-chart" shape to the path.
The shape is added as a new sub-path. (Any currently open paths will be left open).
Note that when specifying the start and end angles, the curve will be drawn either clockwise or anti-clockwise according to whether the end angle is greater than the start. This means that sometimes you may need to use values greater than 2*Pi for the end angle.
Parameters
segmentBounds the outer rectangle in which the elliptical outline fits
fromRadians the angle (clockwise) in radians at which to start the arc segment (where 0 is the top-centre of the ellipse)
toRadians the angle (clockwise) in radians at which to end the arc segment (where 0 is the top-centre of the ellipse)
innerCircleProportionalSize if this is > 0, then the pie will be drawn as a curved band around a hollow ellipse at its centre, where this value indicates the inner ellipse's size with respect to the outer one.
See Also
addArc
void Path::addLineSegment (Line< float > line, float lineThickness)
Adds a line with a specified thickness.
The line is added as a new closed sub-path. (Any currently open paths will be left open).
See Also
addArrow
void Path::addArrow (Line< float > line, float lineThickness, float arrowheadWidth, float arrowheadLength)
Adds a line with an arrowhead on the end.
The arrow is added as a new closed sub-path. (Any currently open paths will be left open).
See Also
PathStrokeType::createStrokeWithArrowheads
void Path::addPolygon (Point< float > centre, int numberOfSides, float radius, float startAngle = 0.0f)
Adds a polygon shape to the path.
See Also
addStar
void Path::addStar (Point< float > centre, int numberOfPoints, float innerRadius, float outerRadius, float startAngle = 0.0f)
Adds a star shape to the path.
See Also
addPolygon
void Path::addBubble (Rectangle< float > bodyArea, Rectangle< float > maximumArea, const Point< float > arrowTipPosition, const float cornerSize, const float arrowBaseWidth)
Adds a speech-bubble shape to the path.
Parameters
bodyArea the area of the body of the bubble shape
maximumArea an area which encloses the body area and defines the limits within which the arrow tip can be drawn - if the tip lies outside this area, the bubble will be drawn without an arrow
arrowTipPosition the location of the tip of the arrow
cornerSize the size of the rounded corners
arrowBaseWidth the width of the base of the arrow where it joins the main rectangle
void Path::addPath (const Path & pathToAppend)
Adds another path to this one.
The new path is added as a new sub-path. (Any currently open paths in this path will be left open).
Parameters
pathToAppend the path to add
void Path::addPath (const Path & pathToAppend, const AffineTransform & transformToApply)
Adds another path to this one, transforming it on the way in.
The new path is added as a new sub-path, its points being transformed by the given matrix before being added.
Parameters
pathToAppend the path to add
transformToApply an optional transform to apply to the incoming vertices
void Path::swapWithPath (Path &) noexcept
Swaps the contents of this path with another one.
The internal data of the two paths is swapped over, so this is much faster than copying it to a temp variable and back.
void Path::preallocateSpace (int numExtraCoordsToMakeSpaceFor)
Preallocates enough space for adding the given number of coordinates to the path.
If you're about to add a large number of lines or curves to the path, it can make the task much more efficient to call this first and avoid costly reallocations as the structure grows. The actual value to pass is a bit tricky to calculate because the space required depends on what you're adding - e.g. each lineTo() or startNewSubPath() will require 3 coords (x, y and a type marker). Each quadraticTo() will need 5, and a cubicTo() will require 7. Closing a sub-path will require 1.
void Path::applyTransform (const AffineTransform & transform) noexcept
Applies a 2D transform to all the vertices in the path.
See Also
AffineTransform, scaleToFit, getTransformToScaleToFit
void Path::scaleToFit (float x, float y, float width, float height, bool preserveProportions) noexcept
Rescales this path to make it fit neatly into a given space.
This is effectively a quick way of calling applyTransform (getTransformToScaleToFit (x, y, w, h, preserveProportions))
Parameters
x the x position of the rectangle to fit the path inside
y the y position of the rectangle to fit the path inside
width the width of the rectangle to fit the path inside
height the height of the rectangle to fit the path inside
preserveProportions if true, it will fit the path into the space without altering its horizontal/vertical scale ratio; if false, it will distort the path to fill the specified ratio both horizontally and vertically
See Also
applyTransform, getTransformToScaleToFit
AffineTransform Path::getTransformToScaleToFit (float x, float y, float width, float height, bool preserveProportions, Justification justificationType = Justification::centred) const
Returns a transform that can be used to rescale the path to fit into a given space.
Parameters
x the x position of the rectangle to fit the path inside
y the y position of the rectangle to fit the path inside
width the width of the rectangle to fit the path inside
height the height of the rectangle to fit the path inside
preserveProportions if true, it will fit the path into the space without altering its horizontal/vertical scale ratio; if false, it will distort the path to fill the specified ratio both horizontally and vertically
justificationType if the proportions are preseved, the resultant path may be smaller than the available rectangle, so this describes how it should be positioned within the space.
Returns
an appropriate transformation
See Also
applyTransform, scaleToFit
AffineTransform Path::getTransformToScaleToFit (Rectangle< float > area, bool preserveProportions, Justification justificationType = Justification::centred) const
Returns a transform that can be used to rescale the path to fit into a given space.
Parameters
area the rectangle to fit the path inside
preserveProportions if true, it will fit the path into the space without altering its horizontal/vertical scale ratio; if false, it will distort the path to fill the specified ratio both horizontally and vertically
justificationType if the proportions are preseved, the resultant path may be smaller than the available rectangle, so this describes how it should be positioned within the space.
Returns
an appropriate transformation
See Also
applyTransform, scaleToFit
Path Path::createPathWithRoundedCorners (float cornerRadius) const
Creates a version of this path where all sharp corners have been replaced by curves.
Wherever two lines meet at an angle, this will replace the corner with a curve of the given radius.
void Path::setUsingNonZeroWinding (bool isNonZeroWinding) noexcept
Changes the winding-rule to be used when filling the path.
If set to true (which is the default), then the path uses a non-zero-winding rule to determine which points are inside the path. If set to false, it uses an alternate-winding rule.
The winding-rule comes into play when areas of the shape overlap other areas, and determines whether the overlapping regions are considered to be inside or outside.
Changing this value just sets a flag - it doesn't affect the contents of the path.
See Also
isUsingNonZeroWinding
bool Path::isUsingNonZeroWinding () const
Returns the flag that indicates whether the path should use a non-zero winding rule.
The default for a new path is true.
See Also
setUsingNonZeroWinding
void Path::loadPathFromStream (InputStream & source)
Loads a stored path from a data stream.
The data in the stream must have been written using writePathToStream().
Note that this will append the stored path to whatever is currently in this path, so you might need to call clear() beforehand.
See Also
loadPathFromData, writePathToStream
void Path::loadPathFromData (const void * data, size_t numberOfBytes)
Loads a stored path from a block of data.
This is similar to loadPathFromStream(), but just reads from a block of data. Useful if you're including stored shapes in your code as a block of static data.
See Also
loadPathFromStream, writePathToStream
void Path::writePathToStream (OutputStream & destination) const
Stores the path by writing it out to a stream.
After writing out a path, you can reload it using loadPathFromStream().
See Also
loadPathFromStream, loadPathFromData
String Path::toString () const
Creates a string containing a textual representation of this path.
See Also
restoreFromString
void Path::restoreFromString (StringRef stringVersion)
Restores this path from a string that was created with the toString() method.
See Also
toString()
Member Data Documentation
const float Path::defaultToleranceForTesting static
const float Path::defaultToleranceForMeasurement static
class PathFlatteningIterator
Flattens a Path object into a series of straight-line sections.
Use one of these to iterate through a Path object, and it will convert all the curves into line sections so it's easy to render or perform geometric operations on.
See Also
Path
Public Member Functions
PathFlatteningIterator (const Path &path, const AffineTransform &transform=AffineTransform(), float tolerance=Path::defaultToleranceForMeasurement)
Creates a PathFlatteningIterator.
~PathFlatteningIterator ()
Destructor.
bool next ()
Fetches the next line segment from the path.
bool isLastInSubpath () const noexcept
Returns true if the current segment is the last in the current sub-path.
Public Attributes
float x1
The x position of the start of the current line segment.
float y1
The y position of the start of the current line segment.
float x2
The x position of the end of the current line segment.
float y2
The y position of the end of the current line segment.
bool closesSubPath
Indicates whether the current line segment is closing a sub-path.
int subPathIndex
The index of the current line within the current sub-path.
Constructor & Destructor Documentation
PathFlatteningIterator::PathFlatteningIterator (const Path & path, const AffineTransform & transform = AffineTransform(), float tolerance = Path::defaultToleranceForMeasurement)
Creates a PathFlatteningIterator.
After creation, use the next() method to initialise the fields in the object with the first line's position.
Parameters
path the path to iterate along
transform a transform to apply to each point in the path being iterated
tolerance the amount by which the curves are allowed to deviate from the lines into which they are being broken down - a higher tolerance contains less lines, so can be generated faster, but will be less smooth.
PathFlatteningIterator::~PathFlatteningIterator ()
Destructor.
Member Function Documentation
bool PathFlatteningIterator::next ()
Fetches the next line segment from the path.
This will update the member variables x1, y1, x2, y2, subPathIndex and closesSubPath so that they describe the new line segment.
Returns
false when there are no more lines to fetch.
bool PathFlatteningIterator::isLastInSubpath () const noexcept
Returns true if the current segment is the last in the current sub-path.
Member Data Documentation
float PathFlatteningIterator::x1
The x position of the start of the current line segment.
float PathFlatteningIterator::y1
The y position of the start of the current line segment.
float PathFlatteningIterator::x2
The x position of the end of the current line segment.
float PathFlatteningIterator::y2
The y position of the end of the current line segment.
bool PathFlatteningIterator::closesSubPath
Indicates whether the current line segment is closing a sub-path.
If the current line is the one that connects the end of a sub-path back to the start again, this will be true.
int PathFlatteningIterator::subPathIndex
The index of the current line within the current sub-path.
E.g. you can use this to see whether the line is the first one in the subpath by seeing if it's 0.
class PathStrokeType
Describes a type of stroke used to render a solid outline along a path.
A PathStrokeType object can be used directly to create the shape of an outline around a path, and is used by Graphics::strokePath to specify the type of stroke to draw.
See Also
Path, Graphics::strokePath
Public Types
enum JointStyle { mitered, curved, beveled }
The type of shape to use for the corners between two adjacent line segments.
enum EndCapStyle { butt, square, rounded }
The type shape to use for the ends of lines.
Public Member Functions
PathStrokeType (float strokeThickness) noexcept
Creates a stroke type with a given line-width, and default joint/end styles.
PathStrokeType (float strokeThickness, JointStyle jointStyle, EndCapStyle endStyle=butt) noexcept
Creates a stroke type.
PathStrokeType (const PathStrokeType &) noexcept
Creates a copy of another stroke type.
PathStrokeType & operator= (const PathStrokeType &) noexcept
Copies another stroke onto this one.
~PathStrokeType () noexcept
Destructor.
void createStrokedPath (Path &destPath, const Path &sourcePath, const AffineTransform &transform=AffineTransform(), float extraAccuracy=1.0f) const
Applies this stroke type to a path and returns the resultant stroke as another Path.
void createDashedStroke (Path &destPath, const Path &sourcePath, const float *dashLengths, int numDashLengths, const AffineTransform &transform=AffineTransform(), float extraAccuracy=1.0f) const
Applies this stroke type to a path, creating a dashed line.
void createStrokeWithArrowheads (Path &destPath, const Path &sourcePath, float arrowheadStartWidth, float arrowheadStartLength, float arrowheadEndWidth, float arrowheadEndLength, const AffineTransform &transform=AffineTransform(), float extraAccuracy=1.0f) const
Applies this stroke type to a path and returns the resultant stroke as another Path.
float getStrokeThickness () const noexcept
Returns the stroke thickness.
void setStrokeThickness (float newThickness) noexcept
Sets the stroke thickness.
JointStyle getJointStyle () const noexcept
Returns the joint style.
void setJointStyle (JointStyle newStyle) noexcept
Sets the joint style.
EndCapStyle getEndStyle () const noexcept
Returns the end-cap style.
void setEndStyle (EndCapStyle newStyle) noexcept
Sets the end-cap style.
bool operator== (const PathStrokeType &) const noexcept
Compares the stroke thickness, joint and end styles of two stroke types.
bool operator!= (const PathStrokeType &) const noexcept
Compares the stroke thickness, joint and end styles of two stroke types.
Member Enumeration Documentation
enum PathStrokeType::JointStyle
The type of shape to use for the corners between two adjacent line segments.
Enumerator
mitered
Indicates that corners should be drawn with sharp joints.
Note that for angles that curve back on themselves, drawing a mitre could require extending the point too far away from the path, so a mitre limit is imposed and any corners that exceed it are drawn as bevelled instead.
curved
Indicates that corners should be drawn as rounded-off.
beveled
Indicates that corners should be drawn with a line flattening their outside edge.
enum PathStrokeType::EndCapStyle
The type shape to use for the ends of lines.
Enumerator
butt
Ends of lines are flat and don't extend beyond the end point.
square
Ends of lines are flat, but stick out beyond the end point for half the thickness of the stroke.
rounded
Ends of lines are rounded-off with a circular shape.
Constructor & Destructor Documentation
PathStrokeType::PathStrokeType (float strokeThickness) explicit noexcept
Creates a stroke type with a given line-width, and default joint/end styles.
PathStrokeType::PathStrokeType (float strokeThickness, JointStyle jointStyle, EndCapStyle endStyle = butt) noexcept
Creates a stroke type.
Parameters
strokeThickness the width of the line to use
jointStyle the type of joints to use for corners
endStyle the type of end-caps to use for the ends of open paths.
PathStrokeType::PathStrokeType (const PathStrokeType &) noexcept
Creates a copy of another stroke type.
PathStrokeType::~PathStrokeType () noexcept
Destructor.
Member Function Documentation
PathStrokeType& PathStrokeType::operator= (const PathStrokeType &) noexcept
Copies another stroke onto this one.
void PathStrokeType::createStrokedPath (Path & destPath, const Path & sourcePath, const AffineTransform & transform = AffineTransform(), float extraAccuracy = 1.0f) const
Applies this stroke type to a path and returns the resultant stroke as another Path.
Parameters
destPath the resultant stroked outline shape will be copied into this path. Note that it's ok for the source and destination Paths to be the same object, so you can easily turn a path into a stroked version of itself.
sourcePath the path to use as the source
transform an optional transform to apply to the points from the source path as they are being used
extraAccuracy if this is greater than 1.0, it will subdivide the path to a higher resolution, which improves the quality if you'll later want to enlarge the stroked path. So for example, if you're planning on drawing the stroke at 3x the size that you're creating it, you should set this to 3.
See Also
createDashedStroke
void PathStrokeType::createDashedStroke (Path & destPath, const Path & sourcePath, const float * dashLengths, int numDashLengths, const AffineTransform & transform = AffineTransform(), float extraAccuracy = 1.0f) const
Applies this stroke type to a path, creating a dashed line.
This is similar to createStrokedPath, but uses the array passed in to break the stroke up into a series of dashes.
Parameters
destPath the resultant stroked outline shape will be copied into this path. Note that it's ok for the source and destination Paths to be the same object, so you can easily turn a path into a stroked version of itself.
sourcePath the path to use as the source
dashLengths An array of alternating on/off lengths. E.g. { 2, 3, 4, 5 } will create a line of length 2, then skip a length of 3, then add a line of length 4, skip 5, and keep repeating this pattern.
numDashLengths The number of lengths in the dashLengths array. This should really be an even number, otherwise the pattern will get out of step as it repeats.
transform an optional transform to apply to the points from the source path as they are being used
extraAccuracy if this is greater than 1.0, it will subdivide the path to a higher resolution, which improves the quality if you'll later want to enlarge the stroked path. So for example, if you're planning on drawing the stroke at 3x the size that you're creating it, you should set this to 3.
void PathStrokeType::createStrokeWithArrowheads (Path & destPath, const Path & sourcePath, float arrowheadStartWidth, float arrowheadStartLength, float arrowheadEndWidth, float arrowheadEndLength, const AffineTransform & transform = AffineTransform(), float extraAccuracy = 1.0f) const
Applies this stroke type to a path and returns the resultant stroke as another Path.
Parameters
destPath the resultant stroked outline shape will be copied into this path. Note that it's ok for the source and destination Paths to be the same object, so you can easily turn a path into a stroked version of itself.
sourcePath the path to use as the source
arrowheadStartWidth the width of the arrowhead at the start of the path
arrowheadStartLength the length of the arrowhead at the start of the path
arrowheadEndWidth the width of the arrowhead at the end of the path
arrowheadEndLength the length of the arrowhead at the end of the path
transform an optional transform to apply to the points from the source path as they are being used
extraAccuracy if this is greater than 1.0, it will subdivide the path to a higher resolution, which improves the quality if you'll later want to enlarge the stroked path. So for example, if you're planning on drawing the stroke at 3x the size that you're creating it, you should set this to 3.
See Also
createDashedStroke
float PathStrokeType::getStrokeThickness () const noexcept
Returns the stroke thickness.
void PathStrokeType::setStrokeThickness (float newThickness) noexcept
Sets the stroke thickness.
JointStyle PathStrokeType::getJointStyle () const noexcept
Returns the joint style.
void PathStrokeType::setJointStyle (JointStyle newStyle) noexcept
Sets the joint style.
EndCapStyle PathStrokeType::getEndStyle () const noexcept
Returns the end-cap style.
void PathStrokeType::setEndStyle (EndCapStyle newStyle) noexcept
Sets the end-cap style.
bool PathStrokeType::operator== (const PathStrokeType &) const noexcept
Compares the stroke thickness, joint and end styles of two stroke types.
bool PathStrokeType::operator!= (const PathStrokeType &) const noexcept
Compares the stroke thickness, joint and end styles of two stroke types.
class Point
template<typename ValueType>
class Point< ValueType >
A pair of (x, y) coordinates.
The ValueType template should be a primitive type such as int, float, double, rather than a class.
See Also
Line, Path, AffineTransform
Public Types
typedef
TypeHelpers::SmallestFloatType
< ValueType >::type FloatType
This type will be double if the Point's type is double, otherwise it will be float.
Public Member Functions
JUCE_CONSTEXPR Point () noexcept
Creates a point at the origin.
JUCE_CONSTEXPR Point (const Point &other) noexcept
Creates a copy of another point.
JUCE_CONSTEXPR Point (ValueType initialX, ValueType initialY) noexcept
Creates a point from an (x, y) position.
Point & operator= (const Point &other) noexcept
Copies this point from another one.
JUCE_CONSTEXPR bool operator== (Point other) const noexcept
JUCE_CONSTEXPR bool operator!= (Point other) const noexcept
JUCE_CONSTEXPR bool isOrigin () const noexcept
Returns true if the point is (0, 0).
JUCE_CONSTEXPR bool isFinite () const noexcept
Returns true if the coordinates are finite values.
JUCE_CONSTEXPR ValueType getX () const noexcept
Returns the point's x coordinate.
JUCE_CONSTEXPR ValueType getY () const noexcept
Returns the point's y coordinate.
void setX (ValueType newX) noexcept
Sets the point's x coordinate.
void setY (ValueType newY) noexcept
Sets the point's y coordinate.
JUCE_CONSTEXPR Point withX (ValueType newX) const noexcept
Returns a point which has the same Y position as this one, but a new X.
JUCE_CONSTEXPR Point withY (ValueType newY) const noexcept
Returns a point which has the same X position as this one, but a new Y.
void setXY (ValueType newX, ValueType newY) noexcept
Changes the point's x and y coordinates.
void addXY (ValueType xToAdd, ValueType yToAdd) noexcept
Adds a pair of coordinates to this value.
JUCE_CONSTEXPR Point translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a point with a given offset from this one.
JUCE_CONSTEXPR Point operator+ (Point other) const noexcept
Adds two points together.
Point & operator+= (Point other) noexcept
Adds another point's coordinates to this one.
JUCE_CONSTEXPR Point operator- (Point other) const noexcept
Subtracts one points from another.
Point & operator-= (Point other) noexcept
Subtracts another point's coordinates to this one.
template<typename OtherType >
JUCE_CONSTEXPR Point operator* (Point< OtherType > other) const noexcept
Multiplies two points together.
template<typename OtherType >
Point & operator*= (Point< OtherType > other) noexcept
Multiplies another point's coordinates to this one.
template<typename OtherType >
JUCE_CONSTEXPR Point operator/ (Point< OtherType > other) const noexcept
Divides one point by another.
template<typename OtherType >
Point & operator/= (Point< OtherType > other) noexcept
Divides this point's coordinates by another.
template<typename FloatType >
JUCE_CONSTEXPR Point operator* (FloatType multiplier) const noexcept
Returns a point whose coordinates are multiplied by a given scalar value.
template<typename FloatType >
JUCE_CONSTEXPR Point operator/ (FloatType divisor) const noexcept
Returns a point whose coordinates are divided by a given scalar value.
template<typename FloatType >
Point & operator*= (FloatType multiplier) noexcept
Multiplies the point's coordinates by a scalar value.
template<typename FloatType >
Point & operator/= (FloatType divisor) noexcept
Divides the point's coordinates by a scalar value.
JUCE_CONSTEXPR Point operator- () const noexcept
Returns the inverse of this point.
ValueType getDistanceFromOrigin () const noexcept
Returns the straight-line distance between this point and the origin.
ValueType getDistanceFrom (Point other) const noexcept
Returns the straight-line distance between this point and another one.
ValueType getDistanceSquaredFromOrigin () const noexcept
Returns the square of the straight-line distance between this point and the origin.
ValueType getDistanceSquaredFrom (Point other) const noexcept
Returns the square of the straight-line distance between this point and another one.
FloatType getAngleToPoint (Point other) const noexcept
Returns the angle from this point to another one.
Point rotatedAboutOrigin (ValueType angleRadians) const noexcept
Returns the point that would be reached by rotating this point clockwise about the origin by the specified angle.
Point< FloatType > getPointOnCircumference (float radius, float angle) const noexcept
Taking this point to be the centre of a circle, this returns a point on its circumference.
Point< FloatType > getPointOnCircumference (float radiusX, float radiusY, float angle) const noexcept
Taking this point to be the centre of an ellipse, this returns a point on its circumference.
FloatType getDotProduct (Point other) const noexcept
Returns the dot-product of two points (x1 * x2 + y1 * y2).
void applyTransform (const AffineTransform &transform) noexcept
Uses a transform to change the point's coordinates.
Point transformedBy (const AffineTransform &transform) const noexcept
Returns the position of this point, if it is transformed by a given AffineTransform.
Point< int > toInt () const noexcept
Casts this point to a Point<int> object.
Point< float > toFloat () const noexcept
Casts this point to a Point<float> object.
Point< double > toDouble () const noexcept
Casts this point to a Point<double> object.
Point< int > roundToInt () const noexcept
Casts this point to a Point<int> object using roundToInt() to convert the values.
String toString () const
Returns the point as a string in the form "x, y".
Public Attributes
ValueType x
The point's X coordinate.
ValueType y
The point's Y coordinate.
Member Typedef Documentation
template<typename ValueType> typedef TypeHelpers::SmallestFloatType<ValueType>::type Point< ValueType >::FloatType
This type will be double if the Point's type is double, otherwise it will be float.
Constructor & Destructor Documentation
template<typename ValueType> JUCE_CONSTEXPR Point< ValueType >::Point () noexcept
Creates a point at the origin.
Referenced by Point< int >::operator*(), Point< int >::operator+(), Point< int >::operator-(), Point< int >::operator/(), Point< int >::rotatedAboutOrigin(), Point< int >::transformedBy(), Point< int >::translated(), Point< int >::withX(), and Point< int >::withY().
template<typename ValueType> JUCE_CONSTEXPR Point< ValueType >::Point (const Point< ValueType > & other) noexcept
Creates a copy of another point.
template<typename ValueType> JUCE_CONSTEXPR Point< ValueType >::Point (ValueType initialX, ValueType initialY) noexcept
Creates a point from an (x, y) position.
Member Function Documentation
template<typename ValueType> Point& Point< ValueType >::operator= (const Point< ValueType > & other) noexcept
Copies this point from another one.
template<typename ValueType> JUCE_CONSTEXPR bool Point< ValueType >::operator== (Point< ValueType > other) const noexcept
template<typename ValueType> JUCE_CONSTEXPR bool Point< ValueType >::operator!= (Point< ValueType > other) const noexcept
template<typename ValueType> JUCE_CONSTEXPR bool Point< ValueType >::isOrigin () const noexcept
Returns true if the point is (0, 0).
template<typename ValueType> JUCE_CONSTEXPR bool Point< ValueType >::isFinite () const noexcept
Returns true if the coordinates are finite values.
template<typename ValueType> JUCE_CONSTEXPR ValueType Point< ValueType >::getX () const noexcept
Returns the point's x coordinate.
template<typename ValueType> JUCE_CONSTEXPR ValueType Point< ValueType >::getY () const noexcept
Returns the point's y coordinate.
template<typename ValueType> void Point< ValueType >::setX (ValueType newX) noexcept
Sets the point's x coordinate.
template<typename ValueType> void Point< ValueType >::setY (ValueType newY) noexcept
Sets the point's y coordinate.
template<typename ValueType> JUCE_CONSTEXPR Point Point< ValueType >::withX (ValueType newX) const noexcept
Returns a point which has the same Y position as this one, but a new X.
template<typename ValueType> JUCE_CONSTEXPR Point Point< ValueType >::withY (ValueType newY) const noexcept
Returns a point which has the same X position as this one, but a new Y.
template<typename ValueType> void Point< ValueType >::setXY (ValueType newX, ValueType newY) noexcept
Changes the point's x and y coordinates.
template<typename ValueType> void Point< ValueType >::addXY (ValueType xToAdd, ValueType yToAdd) noexcept
Adds a pair of coordinates to this value.
template<typename ValueType> JUCE_CONSTEXPR Point Point< ValueType >::translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a point with a given offset from this one.
template<typename ValueType> JUCE_CONSTEXPR Point Point< ValueType >::operator+ (Point< ValueType > other) const noexcept
Adds two points together.
template<typename ValueType> Point& Point< ValueType >::operator+= (Point< ValueType > other) noexcept
Adds another point's coordinates to this one.
template<typename ValueType> JUCE_CONSTEXPR Point Point< ValueType >::operator- (Point< ValueType > other) const noexcept
Subtracts one points from another.
template<typename ValueType> Point& Point< ValueType >::operator-= (Point< ValueType > other) noexcept
Subtracts another point's coordinates to this one.
template<typename ValueType> template<typename OtherType > JUCE_CONSTEXPR Point Point< ValueType >::operator* (Point< OtherType > other) const noexcept
Multiplies two points together.
template<typename ValueType> template<typename OtherType > Point& Point< ValueType >::operator*= (Point< OtherType > other) noexcept
Multiplies another point's coordinates to this one.
template<typename ValueType> template<typename OtherType > JUCE_CONSTEXPR Point Point< ValueType >::operator/ (Point< OtherType > other) const noexcept
Divides one point by another.
template<typename ValueType> template<typename OtherType > Point& Point< ValueType >::operator/= (Point< OtherType > other) noexcept
Divides this point's coordinates by another.
template<typename ValueType> template<typename FloatType > JUCE_CONSTEXPR Point Point< ValueType >::operator* (FloatType multiplier) const noexcept
Returns a point whose coordinates are multiplied by a given scalar value.
template<typename ValueType> template<typename FloatType > JUCE_CONSTEXPR Point Point< ValueType >::operator/ (FloatType divisor) const noexcept
Returns a point whose coordinates are divided by a given scalar value.
template<typename ValueType> template<typename FloatType > Point& Point< ValueType >::operator*= (FloatType multiplier) noexcept
Multiplies the point's coordinates by a scalar value.
template<typename ValueType> template<typename FloatType > Point& Point< ValueType >::operator/= (FloatType divisor) noexcept
Divides the point's coordinates by a scalar value.
template<typename ValueType> JUCE_CONSTEXPR Point Point< ValueType >::operator- () const noexcept
Returns the inverse of this point.
template<typename ValueType> ValueType Point< ValueType >::getDistanceFromOrigin () const noexcept
Returns the straight-line distance between this point and the origin.
template<typename ValueType> ValueType Point< ValueType >::getDistanceFrom (Point< ValueType > other) const noexcept
Returns the straight-line distance between this point and another one.
template<typename ValueType> ValueType Point< ValueType >::getDistanceSquaredFromOrigin () const noexcept
Returns the square of the straight-line distance between this point and the origin.
template<typename ValueType> ValueType Point< ValueType >::getDistanceSquaredFrom (Point< ValueType > other) const noexcept
Returns the square of the straight-line distance between this point and another one.
template<typename ValueType> FloatType Point< ValueType >::getAngleToPoint (Point< ValueType > other) const noexcept
Returns the angle from this point to another one.
Taking this point to be the centre of a circle, and the other point being a position on the circumference, the return value is the number of radians clockwise from the 12 o'clock direction. So 12 o'clock = 0, 3 o'clock = Pi/2, 6 o'clock = Pi, 9 o'clock = -Pi/2
template<typename ValueType> Point Point< ValueType >::rotatedAboutOrigin (ValueType angleRadians) const noexcept
Returns the point that would be reached by rotating this point clockwise about the origin by the specified angle.
template<typename ValueType> Point<FloatType> Point< ValueType >::getPointOnCircumference (float radius, float angle) const noexcept
Taking this point to be the centre of a circle, this returns a point on its circumference.
Parameters
radius the radius of the circle.
angle the angle of the point, in radians clockwise from the 12 o'clock position.
template<typename ValueType> Point<FloatType> Point< ValueType >::getPointOnCircumference (float radiusX, float radiusY, float angle) const noexcept
Taking this point to be the centre of an ellipse, this returns a point on its circumference.
Parameters
radiusX the horizontal radius of the circle.
radiusY the vertical radius of the circle.
angle the angle of the point, in radians clockwise from the 12 o'clock position.
template<typename ValueType> FloatType Point< ValueType >::getDotProduct (Point< ValueType > other) const noexcept
Returns the dot-product of two points (x1 * x2 + y1 * y2).
template<typename ValueType> void Point< ValueType >::applyTransform (const AffineTransform & transform) noexcept
Uses a transform to change the point's coordinates.
This will only compile if ValueType = float!
See Also
AffineTransform::transformPoint
template<typename ValueType> Point Point< ValueType >::transformedBy (const AffineTransform & transform) const noexcept
Returns the position of this point, if it is transformed by a given AffineTransform.
template<typename ValueType> Point<int> Point< ValueType >::toInt () const noexcept
Casts this point to a Point<int> object.
template<typename ValueType> Point<float> Point< ValueType >::toFloat () const noexcept
Casts this point to a Point<float> object.
template<typename ValueType> Point<double> Point< ValueType >::toDouble () const noexcept
Casts this point to a Point<double> object.
template<typename ValueType> Point<int> Point< ValueType >::roundToInt () const noexcept
Casts this point to a Point<int> object using roundToInt() to convert the values.
Referenced by FakeMouseMoveGenerator::timerCallback().
template<typename ValueType> String Point< ValueType >::toString () const
Returns the point as a string in the form "x, y".
Member Data Documentation
template<typename ValueType> ValueType Point< ValueType >::x
The point's X coordinate.
Referenced by Point< int >::addXY(), Point< int >::applyTransform(), Point< int >::getAngleToPoint(), Point< int >::getDistanceFrom(), Point< int >::getDistanceFromOrigin(), Point< int >::getDistanceSquaredFromOrigin(), Point< int >::getDotProduct(), Point< int >::getPointOnCircumference(), Point< int >::getX(), Point< int >::isFinite(), Point< int >::isOrigin(), Point< int >::operator!=(), Point< int >::operator*(), Point< int >::operator*=(), Point< int >::operator+(), Point< int >::operator+=(), Point< int >::operator-(), Point< int >::operator-=(), Point< int >::operator/(), Point< int >::operator/=(), Point< int >::operator=(), Point< int >::operator==(), Point< int >::rotatedAboutOrigin(), Point< int >::roundToInt(), Point< int >::setX(), Point< int >::setXY(), Point< int >::toDouble(), Point< int >::toFloat(), Point< int >::toInt(), Point< int >::toString(), Point< int >::transformedBy(), Point< int >::translated(), and Point< int >::withY().
template<typename ValueType> ValueType Point< ValueType >::y
The point's Y coordinate.
Referenced by Point< int >::addXY(), Point< int >::applyTransform(), Point< int >::getAngleToPoint(), Point< int >::getDistanceFrom(), Point< int >::getDistanceFromOrigin(), Point< int >::getDistanceSquaredFromOrigin(), Point< int >::getDotProduct(), Point< int >::getPointOnCircumference(), Point< int >::getY(), Point< int >::isFinite(), Point< int >::isOrigin(), Point< int >::operator!=(), Point< int >::operator*(), Point< int >::operator*=(), Point< int >::operator+(), Point< int >::operator+=(), Point< int >::operator-(), Point< int >::operator-=(), Point< int >::operator/(), Point< int >::operator/=(), Point< int >::operator=(), Point< int >::operator==(), Point< int >::rotatedAboutOrigin(), Point< int >::roundToInt(), Point< int >::setXY(), Point< int >::setY(), Point< int >::toDouble(), Point< int >::toFloat(), Point< int >::toInt(), Point< int >::toString(), Point< int >::transformedBy(), Point< int >::translated(), and Point< int >::withX().
class Rectangle
template<typename ValueType>
class Rectangle< ValueType >
Manages a rectangle and allows geometric operations to be performed on it.
See Also
RectangleList, Path, Line, Point
Public Member Functions
Rectangle () noexcept
Creates a rectangle of zero size.
Rectangle (const Rectangle &other) noexcept
Creates a copy of another rectangle.
Rectangle (ValueType initialX, ValueType initialY, ValueType width, ValueType height) noexcept
Creates a rectangle with a given position and size.
Rectangle (ValueType width, ValueType height) noexcept
Creates a rectangle with a given size, and a position of (0, 0).
Rectangle (Point< ValueType > corner1, Point< ValueType > corner2) noexcept
Creates a Rectangle from the positions of two opposite corners.
Rectangle & operator= (const Rectangle &other) noexcept
~Rectangle () noexcept
Destructor.
bool isEmpty () const noexcept
Returns true if the rectangle's width or height are zero or less.
bool isFinite () const noexcept
Returns true if the rectangle's values are all finite numbers, i.e.
ValueType getX () const noexcept
Returns the x coordinate of the rectangle's left-hand-side.
ValueType getY () const noexcept
Returns the y coordinate of the rectangle's top edge.
ValueType getWidth () const noexcept
Returns the width of the rectangle.
ValueType getHeight () const noexcept
Returns the height of the rectangle.
ValueType getRight () const noexcept
Returns the x coordinate of the rectangle's right-hand-side.
ValueType getBottom () const noexcept
Returns the y coordinate of the rectangle's bottom edge.
ValueType getCentreX () const noexcept
Returns the x coordinate of the rectangle's centre.
ValueType getCentreY () const noexcept
Returns the y coordinate of the rectangle's centre.
Point< ValueType > getCentre () const noexcept
Returns the centre point of the rectangle.
ValueType getAspectRatio (bool widthOverHeight=true) const noexcept
Returns the aspect ratio of the rectangle's width / height.
Point< ValueType > getPosition () const noexcept
Returns the rectangle's top-left position as a Point.
void setPosition (Point< ValueType > newPos) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
void setPosition (ValueType newX, ValueType newY) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
Point< ValueType > getTopLeft () const noexcept
Returns the rectangle's top-left position as a Point.
Point< ValueType > getTopRight () const noexcept
Returns the rectangle's top-right position as a Point.
Point< ValueType > getBottomLeft () const noexcept
Returns the rectangle's bottom-left position as a Point.
Point< ValueType > getBottomRight () const noexcept
Returns the rectangle's bottom-right position as a Point.
Range< ValueType > getHorizontalRange () const noexcept
Returns the rectangle's left and right positions as a Range.
Range< ValueType > getVerticalRange () const noexcept
Returns the rectangle's top and bottom positions as a Range.
void setSize (ValueType newWidth, ValueType newHeight) noexcept
Changes the rectangle's size, leaving the position of its top-left corner unchanged.
void setBounds (ValueType newX, ValueType newY, ValueType newWidth, ValueType newHeight) noexcept
Changes all the rectangle's coordinates.
void setX (ValueType newX) noexcept
Changes the rectangle's X coordinate.
void setY (ValueType newY) noexcept
Changes the rectangle's Y coordinate.
void setWidth (ValueType newWidth) noexcept
Changes the rectangle's width.
void setHeight (ValueType newHeight) noexcept
Changes the rectangle's height.
void setCentre (ValueType newCentreX, ValueType newCentreY) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
void setCentre (Point< ValueType > newCentre) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
void setHorizontalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's left and right edges.
void setVerticalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's top and bottom edges.
Rectangle withX (ValueType newX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but with a different x-position.
Rectangle withY (ValueType newY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but with a different y-position.
Rectangle withRightX (ValueType newRightX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but whose right-hand edge has the given position.
Rectangle withBottomY (ValueType newBottomY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but whose bottom edge has the given position.
Rectangle withPosition (ValueType newX, ValueType newY) const noexcept
Returns a rectangle with the same size as this one, but a new position.
Rectangle withPosition (Point< ValueType > newPos) const noexcept
Returns a rectangle with the same size as this one, but a new position.
Rectangle withZeroOrigin () const noexcept
Returns a rectangle whose size is the same as this one, but whose top-left position is (0, 0).
Rectangle withCentre (Point< ValueType > newCentre) const noexcept
Returns a rectangle with the same size as this one, but a new centre position.
Rectangle withWidth (ValueType newWidth) const noexcept
Returns a rectangle which has the same position and height as this one, but with a different width.
Rectangle withHeight (ValueType newHeight) const noexcept
Returns a rectangle which has the same position and width as this one, but with a different height.
Rectangle withSize (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same top-left position as this one, but a new size.
Rectangle withSizeKeepingCentre (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same centre position as this one, but a new size.
void setLeft (ValueType newLeft) noexcept
Moves the x position, adjusting the width so that the right-hand edge remains in the same place.
Rectangle withLeft (ValueType newLeft) const noexcept
Returns a new rectangle with a different x position, but the same right-hand edge as this one.
void setTop (ValueType newTop) noexcept
Moves the y position, adjusting the height so that the bottom edge remains in the same place.
Rectangle withTop (ValueType newTop) const noexcept
Returns a new rectangle with a different y position, but the same bottom edge as this one.
void setRight (ValueType newRight) noexcept
Adjusts the width so that the right-hand edge of the rectangle has this new value.
Rectangle withRight (ValueType newRight) const noexcept
Returns a new rectangle with a different right-hand edge position, but the same left-hand edge as this one.
void setBottom (ValueType newBottom) noexcept
Adjusts the height so that the bottom edge of the rectangle has this new value.
Rectangle withBottom (ValueType newBottom) const noexcept
Returns a new rectangle with a different bottom edge position, but the same top edge as this one.
Rectangle withTrimmedLeft (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its left-hand edge.
Rectangle withTrimmedRight (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its right-hand edge.
Rectangle withTrimmedTop (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its top edge.
Rectangle withTrimmedBottom (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its bottom edge.
void translate (ValueType deltaX, ValueType deltaY) noexcept
Moves the rectangle's position by adding amount to its x and y coordinates.
Rectangle translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
Rectangle operator+ (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
Rectangle & operator+= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
Rectangle operator- (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
Rectangle & operator-= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
template<typename FloatType >
Rectangle operator* (FloatType scaleFactor) const noexcept
Returns a rectangle that has been scaled by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator*= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator*= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
template<typename FloatType >
Rectangle operator/ (FloatType scaleFactor) const noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator/= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename FloatType >
Rectangle operator/= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
void expand (ValueType deltaX, ValueType deltaY) noexcept
Expands the rectangle by a given amount.
Rectangle expanded (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is larger than this one by a given amount.
Rectangle expanded (ValueType delta) const noexcept
Returns a rectangle that is larger than this one by a given amount.
void reduce (ValueType deltaX, ValueType deltaY) noexcept
Shrinks the rectangle by a given amount.
Rectangle reduced (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Rectangle reduced (ValueType delta) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Rectangle removeFromTop (ValueType amountToRemove) noexcept
Removes a strip from the top of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Rectangle removeFromLeft (ValueType amountToRemove) noexcept
Removes a strip from the left-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Rectangle removeFromRight (ValueType amountToRemove) noexcept
Removes a strip from the right-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Rectangle removeFromBottom (ValueType amountToRemove) noexcept
Removes a strip from the bottom of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
Point< ValueType > getConstrainedPoint (Point< ValueType > point) const noexcept
Returns the nearest point to the specified point that lies within this rectangle.
template<typename FloatType >
Point< ValueType > getRelativePoint (FloatType relativeX, FloatType relativeY) const noexcept
Returns a point within this rectangle, specified as proportional coordinates.
template<typename FloatType >
ValueType proportionOfWidth (FloatType proportion) const noexcept
Returns a proportion of the width of this rectangle.
template<typename FloatType >
ValueType proportionOfHeight (FloatType proportion) const noexcept
Returns a proportion of the height of this rectangle.
template<typename FloatType >
Rectangle getProportion (Rectangle< FloatType > proportionalRect) const noexcept
Returns a rectangle based on some proportional coordinates relative to this one.
bool operator== (const Rectangle &other) const noexcept
Returns true if the two rectangles are identical.
bool operator!= (const Rectangle &other) const noexcept
Returns true if the two rectangles are not identical.
bool contains (ValueType xCoord, ValueType yCoord) const noexcept
Returns true if this coordinate is inside the rectangle.
bool contains (Point< ValueType > point) const noexcept
Returns true if this coordinate is inside the rectangle.
bool contains (Rectangle other) const noexcept
Returns true if this other rectangle is completely inside this one.
bool intersects (Rectangle other) const noexcept
Returns true if any part of another rectangle overlaps this one.
bool intersects (const Line< ValueType > &line) const noexcept
Returns true if any part of the given line lies inside this rectangle.
Rectangle getIntersection (Rectangle other) const noexcept
Returns the region that is the overlap between this and another rectangle.
bool intersectRectangle (ValueType &otherX, ValueType &otherY, ValueType &otherW, ValueType &otherH) const noexcept
Clips a set of rectangle coordinates so that they lie only within this one.
bool intersectRectangle (Rectangle< ValueType > &rectangleToClip) const noexcept
Clips a rectangle so that it lies only within this one.
Rectangle getUnion (Rectangle other) const noexcept
Returns the smallest rectangle that contains both this one and the one passed-in.
bool enlargeIfAdjacent (Rectangle other) noexcept
If this rectangle merged with another one results in a simple rectangle, this will set this rectangle to the result, and return true.
bool reduceIfPartlyContainedIn (Rectangle other) noexcept
If after removing another rectangle from this one the result is a simple rectangle, this will set this object's bounds to be the result, and return true.
Rectangle constrainedWithin (Rectangle areaToFitWithin) const noexcept
Tries to fit this rectangle within a target area, returning the result.
Rectangle transformedBy (const AffineTransform &transform) const noexcept
Returns the smallest rectangle that can contain the shape created by applying a transform to this rectangle.
Rectangle< int > getSmallestIntegerContainer () const noexcept
Returns the smallest integer-aligned rectangle that completely contains this one.
Rectangle< int > toNearestInt () const noexcept
Casts this rectangle to a Rectangle<int>.
Rectangle< float > toFloat () const noexcept
Casts this rectangle to a Rectangle<float>.
Rectangle< double > toDouble () const noexcept
Casts this rectangle to a Rectangle<double>.
template<typename TargetType >
Rectangle< TargetType > toType () const noexcept
Casts this rectangle to a Rectangle with the given type.
String toString () const
Creates a string describing this rectangle.
Static Public Member Functions
static Rectangle leftTopRightBottom (ValueType left, ValueType top, ValueType right, ValueType bottom) noexcept
Creates a Rectangle from a set of left, right, top, bottom coordinates.
static Rectangle findAreaContainingPoints (const Point< ValueType > *points, int numPoints) noexcept
Returns the smallest Rectangle that can contain a set of points.
static bool intersectRectangles (ValueType &x1, ValueType &y1, ValueType &w1, ValueType &h1, ValueType x2, ValueType y2, ValueType w2, ValueType h2) noexcept
Static utility to intersect two sets of rectangular coordinates.
static Rectangle fromString (StringRef stringVersion)
Parses a string containing a rectangle's details.
Constructor & Destructor Documentation
template<typename ValueType> Rectangle< ValueType >::Rectangle () noexcept
Creates a rectangle of zero size.
The default coordinates will be (0, 0, 0, 0).
template<typename ValueType> Rectangle< ValueType >::Rectangle (const Rectangle< ValueType > & other) noexcept
Creates a copy of another rectangle.
template<typename ValueType> Rectangle< ValueType >::Rectangle (ValueType initialX, ValueType initialY, ValueType width, ValueType height) noexcept
Creates a rectangle with a given position and size.
template<typename ValueType> Rectangle< ValueType >::Rectangle (ValueType width, ValueType height) noexcept
Creates a rectangle with a given size, and a position of (0, 0).
template<typename ValueType> Rectangle< ValueType >::Rectangle (Point< ValueType > corner1, Point< ValueType > corner2) noexcept
Creates a Rectangle from the positions of two opposite corners.
template<typename ValueType> Rectangle< ValueType >::~Rectangle () noexcept
Destructor.
Member Function Documentation
template<typename ValueType> static Rectangle Rectangle< ValueType >::leftTopRightBottom (ValueType left, ValueType top, ValueType right, ValueType bottom) static noexcept
Creates a Rectangle from a set of left, right, top, bottom coordinates.
The right and bottom values must be larger than the left and top ones, or the resulting rectangle will have a negative size.
Referenced by Rectangle< int >::getSmallestIntegerContainer().
template<typename ValueType> Rectangle& Rectangle< ValueType >::operator= (const Rectangle< ValueType > & other) noexcept
template<typename ValueType> bool Rectangle< ValueType >::isEmpty () const noexcept
Returns true if the rectangle's width or height are zero or less.
Referenced by RectangleList< int >::add(), RectangleList< int >::addWithoutMerging(), RectangleList< int >::clipTo(), RectangleList< int >::getIntersectionWith(), and Rectangle< int >::getUnion().
template<typename ValueType> bool Rectangle< ValueType >::isFinite () const noexcept
Returns true if the rectangle's values are all finite numbers, i.e.
not NaN or infinity.
Referenced by RectangleList< int >::add(), RectangleList< int >::addWithoutMerging(), RectangleList< int >::clipTo(), and RectangleList< int >::getIntersectionWith().
template<typename ValueType> ValueType Rectangle< ValueType >::getX () const noexcept
Returns the x coordinate of the rectangle's left-hand-side.
Referenced by Path::addRoundedRectangle(), and RectangleList< int >::subtract().
template<typename ValueType> ValueType Rectangle< ValueType >::getY () const noexcept
Returns the y coordinate of the rectangle's top edge.
Referenced by Path::addRoundedRectangle(), and RectangleList< int >::subtract().
template<typename ValueType> ValueType Rectangle< ValueType >::getWidth () const noexcept
Returns the width of the rectangle.
Referenced by Path::addRoundedRectangle(), and RectangleList< int >::subtract().
template<typename ValueType> ValueType Rectangle< ValueType >::getHeight () const noexcept
Returns the height of the rectangle.
Referenced by Path::addRoundedRectangle(), and RectangleList< int >::subtract().
template<typename ValueType> ValueType Rectangle< ValueType >::getRight () const noexcept
Returns the x coordinate of the rectangle's right-hand-side.
Referenced by Rectangle< int >::enlargeIfAdjacent().
template<typename ValueType> ValueType Rectangle< ValueType >::getBottom () const noexcept
Returns the y coordinate of the rectangle's bottom edge.
Referenced by Rectangle< int >::enlargeIfAdjacent().
template<typename ValueType> ValueType Rectangle< ValueType >::getCentreX () const noexcept
Returns the x coordinate of the rectangle's centre.
template<typename ValueType> ValueType Rectangle< ValueType >::getCentreY () const noexcept
Returns the y coordinate of the rectangle's centre.
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getCentre () const noexcept
Returns the centre point of the rectangle.
template<typename ValueType> ValueType Rectangle< ValueType >::getAspectRatio (bool widthOverHeight = true) const noexcept
Returns the aspect ratio of the rectangle's width / height.
If widthOverHeight is true, it returns width / height; if widthOverHeight is false, it returns height / width.
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getPosition () const noexcept
Returns the rectangle's top-left position as a Point.
template<typename ValueType> void Rectangle< ValueType >::setPosition (Point< ValueType > newPos) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
template<typename ValueType> void Rectangle< ValueType >::setPosition (ValueType newX, ValueType newY) noexcept
Changes the position of the rectangle's top-left corner (leaving its size unchanged).
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getTopLeft () const noexcept
Returns the rectangle's top-left position as a Point.
Referenced by Rectangle< int >::intersects().
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getTopRight () const noexcept
Returns the rectangle's top-right position as a Point.
Referenced by Rectangle< int >::intersects().
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getBottomLeft () const noexcept
Returns the rectangle's bottom-left position as a Point.
Referenced by Rectangle< int >::intersects().
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getBottomRight () const noexcept
Returns the rectangle's bottom-right position as a Point.
Referenced by Rectangle< int >::intersects().
template<typename ValueType> Range<ValueType> Rectangle< ValueType >::getHorizontalRange () const noexcept
Returns the rectangle's left and right positions as a Range.
template<typename ValueType> Range<ValueType> Rectangle< ValueType >::getVerticalRange () const noexcept
Returns the rectangle's top and bottom positions as a Range.
template<typename ValueType> void Rectangle< ValueType >::setSize (ValueType newWidth, ValueType newHeight) noexcept
Changes the rectangle's size, leaving the position of its top-left corner unchanged.
template<typename ValueType> void Rectangle< ValueType >::setBounds (ValueType newX, ValueType newY, ValueType newWidth, ValueType newHeight) noexcept
Changes all the rectangle's coordinates.
Referenced by Rectangle< int >::expand().
template<typename ValueType> void Rectangle< ValueType >::setX (ValueType newX) noexcept
Changes the rectangle's X coordinate.
template<typename ValueType> void Rectangle< ValueType >::setY (ValueType newY) noexcept
Changes the rectangle's Y coordinate.
template<typename ValueType> void Rectangle< ValueType >::setWidth (ValueType newWidth) noexcept
Changes the rectangle's width.
template<typename ValueType> void Rectangle< ValueType >::setHeight (ValueType newHeight) noexcept
Changes the rectangle's height.
template<typename ValueType> void Rectangle< ValueType >::setCentre (ValueType newCentreX, ValueType newCentreY) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
template<typename ValueType> void Rectangle< ValueType >::setCentre (Point< ValueType > newCentre) noexcept
Changes the position of the rectangle's centre (leaving its size unchanged).
Referenced by Rectangle< int >::setCentre().
template<typename ValueType> void Rectangle< ValueType >::setHorizontalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's left and right edges.
template<typename ValueType> void Rectangle< ValueType >::setVerticalRange (Range< ValueType > range) noexcept
Changes the position of the rectangle's top and bottom edges.
template<typename ValueType> Rectangle Rectangle< ValueType >::withX (ValueType newX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but with a different x-position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withY (ValueType newY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but with a different y-position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withRightX (ValueType newRightX) const noexcept
Returns a rectangle which has the same size and y-position as this one, but whose right-hand edge has the given position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withBottomY (ValueType newBottomY) const noexcept
Returns a rectangle which has the same size and x-position as this one, but whose bottom edge has the given position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withPosition (ValueType newX, ValueType newY) const noexcept
Returns a rectangle with the same size as this one, but a new position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withPosition (Point< ValueType > newPos) const noexcept
Returns a rectangle with the same size as this one, but a new position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withZeroOrigin () const noexcept
Returns a rectangle whose size is the same as this one, but whose top-left position is (0, 0).
template<typename ValueType> Rectangle Rectangle< ValueType >::withCentre (Point< ValueType > newCentre) const noexcept
Returns a rectangle with the same size as this one, but a new centre position.
template<typename ValueType> Rectangle Rectangle< ValueType >::withWidth (ValueType newWidth) const noexcept
Returns a rectangle which has the same position and height as this one, but with a different width.
Referenced by Rectangle< int >::withTrimmedRight().
template<typename ValueType> Rectangle Rectangle< ValueType >::withHeight (ValueType newHeight) const noexcept
Returns a rectangle which has the same position and width as this one, but with a different height.
Referenced by Rectangle< int >::withTrimmedBottom().
template<typename ValueType> Rectangle Rectangle< ValueType >::withSize (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same top-left position as this one, but a new size.
template<typename ValueType> Rectangle Rectangle< ValueType >::withSizeKeepingCentre (ValueType newWidth, ValueType newHeight) const noexcept
Returns a rectangle with the same centre position as this one, but a new size.
template<typename ValueType> void Rectangle< ValueType >::setLeft (ValueType newLeft) noexcept
Moves the x position, adjusting the width so that the right-hand edge remains in the same place.
If the x is moved to be on the right of the current right-hand edge, the width will be set to zero.
See Also
withLeft
template<typename ValueType> Rectangle Rectangle< ValueType >::withLeft (ValueType newLeft) const noexcept
Returns a new rectangle with a different x position, but the same right-hand edge as this one.
If the new x is beyond the right of the current right-hand edge, the width will be set to zero.
See Also
setLeft
Referenced by Rectangle< int >::withTrimmedLeft().
template<typename ValueType> void Rectangle< ValueType >::setTop (ValueType newTop) noexcept
Moves the y position, adjusting the height so that the bottom edge remains in the same place.
If the y is moved to be below the current bottom edge, the height will be set to zero.
See Also
withTop
template<typename ValueType> Rectangle Rectangle< ValueType >::withTop (ValueType newTop) const noexcept
Returns a new rectangle with a different y position, but the same bottom edge as this one.
If the new y is beyond the bottom of the current rectangle, the height will be set to zero.
See Also
setTop
Referenced by Rectangle< int >::withTrimmedTop().
template<typename ValueType> void Rectangle< ValueType >::setRight (ValueType newRight) noexcept
Adjusts the width so that the right-hand edge of the rectangle has this new value.
If the new right is below the current X value, the X will be pushed down to match it.
See Also
getRight, withRight
template<typename ValueType> Rectangle Rectangle< ValueType >::withRight (ValueType newRight) const noexcept
Returns a new rectangle with a different right-hand edge position, but the same left-hand edge as this one.
If the new right edge is below the current left-hand edge, the width will be set to zero.
See Also
setRight
template<typename ValueType> void Rectangle< ValueType >::setBottom (ValueType newBottom) noexcept
Adjusts the height so that the bottom edge of the rectangle has this new value.
If the new bottom is lower than the current Y value, the Y will be pushed down to match it.
See Also
getBottom, withBottom
template<typename ValueType> Rectangle Rectangle< ValueType >::withBottom (ValueType newBottom) const noexcept
Returns a new rectangle with a different bottom edge position, but the same top edge as this one.
If the new y is beyond the bottom of the current rectangle, the height will be set to zero.
See Also
setBottom
template<typename ValueType> Rectangle Rectangle< ValueType >::withTrimmedLeft (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its left-hand edge.
template<typename ValueType> Rectangle Rectangle< ValueType >::withTrimmedRight (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its right-hand edge.
template<typename ValueType> Rectangle Rectangle< ValueType >::withTrimmedTop (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its top edge.
template<typename ValueType> Rectangle Rectangle< ValueType >::withTrimmedBottom (ValueType amountToRemove) const noexcept
Returns a version of this rectangle with the given amount removed from its bottom edge.
template<typename ValueType> void Rectangle< ValueType >::translate (ValueType deltaX, ValueType deltaY) noexcept
Moves the rectangle's position by adding amount to its x and y coordinates.
template<typename ValueType> Rectangle Rectangle< ValueType >::translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
template<typename ValueType> Rectangle Rectangle< ValueType >::operator+ (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
template<typename ValueType> Rectangle& Rectangle< ValueType >::operator+= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
template<typename ValueType> Rectangle Rectangle< ValueType >::operator- (Point< ValueType > deltaPosition) const noexcept
Returns a rectangle which is the same as this one moved by a given amount.
template<typename ValueType> Rectangle& Rectangle< ValueType >::operator-= (Point< ValueType > deltaPosition) noexcept
Moves this rectangle by a given amount.
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::operator* (FloatType scaleFactor) const noexcept
Returns a rectangle that has been scaled by the given amount, centred around the origin.
Note that if the rectangle has int coordinates and it's scaled by a floating-point amount, then the result will be converted back to integer coordinates using getSmallestIntegerContainer().
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::operator*= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
Note that if the rectangle has int coordinates and it's scaled by a floating-point amount, then the result will be converted back to integer coordinates using getSmallestIntegerContainer().
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::operator*= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
Note that if the rectangle has int coordinates and it's scaled by a floating-point amount, then the result will be converted back to integer coordinates using getSmallestIntegerContainer().
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::operator/ (FloatType scaleFactor) const noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::operator/= (FloatType scaleFactor) noexcept
Scales this rectangle by the given amount, centred around the origin.
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::operator/= (Point< FloatType > scaleFactor) noexcept
Scales this rectangle by the given X and Y factors, centred around the origin.
template<typename ValueType> void Rectangle< ValueType >::expand (ValueType deltaX, ValueType deltaY) noexcept
Expands the rectangle by a given amount.
Effectively, its new size is (x - deltaX, y - deltaY, w + deltaX * 2, h + deltaY * 2).
See Also
expanded, reduce, reduced
Referenced by Rectangle< int >::reduce().
template<typename ValueType> Rectangle Rectangle< ValueType >::expanded (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is larger than this one by a given amount.
Effectively, the rectangle returned is (x - deltaX, y - deltaY, w + deltaX * 2, h + deltaY * 2).
See Also
expand, reduce, reduced
Referenced by Rectangle< int >::expanded(), and Rectangle< int >::reduced().
template<typename ValueType> Rectangle Rectangle< ValueType >::expanded (ValueType delta) const noexcept
Returns a rectangle that is larger than this one by a given amount.
Effectively, the rectangle returned is (x - delta, y - delta, w + delta * 2, h + delta * 2).
See Also
expand, reduce, reduced
template<typename ValueType> void Rectangle< ValueType >::reduce (ValueType deltaX, ValueType deltaY) noexcept
Shrinks the rectangle by a given amount.
Effectively, its new size is (x + deltaX, y + deltaY, w - deltaX * 2, h - deltaY * 2).
See Also
reduced, expand, expanded
template<typename ValueType> Rectangle Rectangle< ValueType >::reduced (ValueType deltaX, ValueType deltaY) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Effectively, the rectangle returned is (x + deltaX, y + deltaY, w - deltaX * 2, h - deltaY * 2).
See Also
reduce, expand, expanded
Referenced by Rectangle< int >::reduced().
template<typename ValueType> Rectangle Rectangle< ValueType >::reduced (ValueType delta) const noexcept
Returns a rectangle that is smaller than this one by a given amount.
Effectively, the rectangle returned is (x + delta, y + delta, w - delta * 2, h - delta * 2).
See Also
reduce, expand, expanded
template<typename ValueType> Rectangle Rectangle< ValueType >::removeFromTop (ValueType amountToRemove) noexcept
Removes a strip from the top of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (100, 100, 300, 50) and leave this rectangle as (100, 150, 300, 250).
If amountToRemove is greater than the height of this rectangle, it'll be clipped to that value.
template<typename ValueType> Rectangle Rectangle< ValueType >::removeFromLeft (ValueType amountToRemove) noexcept
Removes a strip from the left-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (100, 100, 50, 300) and leave this rectangle as (150, 100, 250, 300).
If amountToRemove is greater than the width of this rectangle, it'll be clipped to that value.
template<typename ValueType> Rectangle Rectangle< ValueType >::removeFromRight (ValueType amountToRemove) noexcept
Removes a strip from the right-hand edge of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (250, 100, 50, 300) and leave this rectangle as (100, 100, 250, 300).
If amountToRemove is greater than the width of this rectangle, it'll be clipped to that value.
template<typename ValueType> Rectangle Rectangle< ValueType >::removeFromBottom (ValueType amountToRemove) noexcept
Removes a strip from the bottom of this rectangle, reducing this rectangle by the specified amount and returning the section that was removed.
E.g. if this rectangle is (100, 100, 300, 300) and amountToRemove is 50, this will return (100, 250, 300, 50) and leave this rectangle as (100, 100, 300, 250).
If amountToRemove is greater than the height of this rectangle, it'll be clipped to that value.
template<typename ValueType> Point<ValueType> Rectangle< ValueType >::getConstrainedPoint (Point< ValueType > point) const noexcept
Returns the nearest point to the specified point that lies within this rectangle.
template<typename ValueType> template<typename FloatType > Point<ValueType> Rectangle< ValueType >::getRelativePoint (FloatType relativeX, FloatType relativeY) const noexcept
Returns a point within this rectangle, specified as proportional coordinates.
The relative X and Y values should be between 0 and 1, where 0 is the left or top of this rectangle, and 1 is the right or bottom. (Out-of-bounds values will return a point outside the rectangle).
template<typename ValueType> template<typename FloatType > ValueType Rectangle< ValueType >::proportionOfWidth (FloatType proportion) const noexcept
Returns a proportion of the width of this rectangle.
Referenced by Rectangle< int >::getProportion().
template<typename ValueType> template<typename FloatType > ValueType Rectangle< ValueType >::proportionOfHeight (FloatType proportion) const noexcept
Returns a proportion of the height of this rectangle.
Referenced by Rectangle< int >::getProportion().
template<typename ValueType> template<typename FloatType > Rectangle Rectangle< ValueType >::getProportion (Rectangle< FloatType > proportionalRect) const noexcept
Returns a rectangle based on some proportional coordinates relative to this one.
So for example getProportion ({ 0.25f, 0.25f, 0.5f, 0.5f }) would return a rectangle of half the original size, with the same centre.
template<typename ValueType> bool Rectangle< ValueType >::operator== (const Rectangle< ValueType > & other) const noexcept
Returns true if the two rectangles are identical.
template<typename ValueType> bool Rectangle< ValueType >::operator!= (const Rectangle< ValueType > & other) const noexcept
Returns true if the two rectangles are not identical.
template<typename ValueType> bool Rectangle< ValueType >::contains (ValueType xCoord, ValueType yCoord) const noexcept
Returns true if this coordinate is inside the rectangle.
Referenced by RectangleList< int >::add(), and Rectangle< int >::intersects().
template<typename ValueType> bool Rectangle< ValueType >::contains (Point< ValueType > point) const noexcept
Returns true if this coordinate is inside the rectangle.
template<typename ValueType> bool Rectangle< ValueType >::contains (Rectangle< ValueType > other) const noexcept
Returns true if this other rectangle is completely inside this one.
template<typename ValueType> bool Rectangle< ValueType >::intersects (Rectangle< ValueType > other) const noexcept
Returns true if any part of another rectangle overlaps this one.
Referenced by RectangleList< int >::add().
template<typename ValueType> bool Rectangle< ValueType >::intersects (const Line< ValueType > & line) const noexcept
Returns true if any part of the given line lies inside this rectangle.
template<typename ValueType> Rectangle Rectangle< ValueType >::getIntersection (Rectangle< ValueType > other) const noexcept
Returns the region that is the overlap between this and another rectangle.
If the two rectangles don't overlap, the rectangle returned will be empty.
template<typename ValueType> bool Rectangle< ValueType >::intersectRectangle (ValueType & otherX, ValueType & otherY, ValueType & otherW, ValueType & otherH) const noexcept
Clips a set of rectangle coordinates so that they lie only within this one.
This is a non-static version of intersectRectangles(). Returns false if the two rectangles didn't overlap.
Referenced by RectangleList< int >::clipTo(), RectangleList< int >::getIntersectionWith(), and Rectangle< int >::intersectRectangle().
template<typename ValueType> bool Rectangle< ValueType >::intersectRectangle (Rectangle< ValueType > & rectangleToClip) const noexcept
Clips a rectangle so that it lies only within this one.
Returns false if the two rectangles didn't overlap.
template<typename ValueType> Rectangle Rectangle< ValueType >::getUnion (Rectangle< ValueType > other) const noexcept
Returns the smallest rectangle that contains both this one and the one passed-in.
If either this or the other rectangle are empty, they will not be counted as part of the resulting region.
template<typename ValueType> bool Rectangle< ValueType >::enlargeIfAdjacent (Rectangle< ValueType > other) noexcept
If this rectangle merged with another one results in a simple rectangle, this will set this rectangle to the result, and return true.
Returns false and does nothing to this rectangle if the two rectangles don't overlap, or if they form a complex region.
template<typename ValueType> bool Rectangle< ValueType >::reduceIfPartlyContainedIn (Rectangle< ValueType > other) noexcept
If after removing another rectangle from this one the result is a simple rectangle, this will set this object's bounds to be the result, and return true.
Returns false and does nothing to this rectangle if the two rectangles don't overlap, or if removing the other one would form a complex region.
template<typename ValueType> Rectangle Rectangle< ValueType >::constrainedWithin (Rectangle< ValueType > areaToFitWithin) const noexcept
Tries to fit this rectangle within a target area, returning the result.
If this rectangle is not completely inside the target area, then it'll be shifted (without changing its size) so that it lies within the target. If it is larger than the target rectangle in either dimension, then that dimension will be reduced to fit within the target.
template<typename ValueType> Rectangle Rectangle< ValueType >::transformedBy (const AffineTransform & transform) const noexcept
Returns the smallest rectangle that can contain the shape created by applying a transform to this rectangle.
This should only be used on floating point rectangles.
template<typename ValueType> Rectangle<int> Rectangle< ValueType >::getSmallestIntegerContainer () const noexcept
Returns the smallest integer-aligned rectangle that completely contains this one.
This is only relevant for floating-point rectangles, of course.
See Also
toFloat(), toNearestInt()
template<typename ValueType> Rectangle<int> Rectangle< ValueType >::toNearestInt () const noexcept
Casts this rectangle to a Rectangle<int>.
This uses roundToInt to snap x, y, width and height to the nearest integer (losing precision). If the rectangle already uses integers, this will simply return a copy.
See Also
getSmallestIntegerContainer()
template<typename ValueType> Rectangle<float> Rectangle< ValueType >::toFloat () const noexcept
Casts this rectangle to a Rectangle<float>.
See Also
getSmallestIntegerContainer
template<typename ValueType> Rectangle<double> Rectangle< ValueType >::toDouble () const noexcept
Casts this rectangle to a Rectangle<double>.
See Also
getSmallestIntegerContainer
template<typename ValueType> template<typename TargetType > Rectangle<TargetType> Rectangle< ValueType >::toType () const noexcept
Casts this rectangle to a Rectangle with the given type.
If the target type is a conversion from float to int, then the conversion will be done using getSmallestIntegerContainer().
template<typename ValueType> static Rectangle Rectangle< ValueType >::findAreaContainingPoints (const Point< ValueType > * points, int numPoints) static noexcept
Returns the smallest Rectangle that can contain a set of points.
template<typename ValueType> static bool Rectangle< ValueType >::intersectRectangles (ValueType & x1, ValueType & y1, ValueType & w1, ValueType & h1, ValueType x2, ValueType y2, ValueType w2, ValueType h2) static noexcept
Static utility to intersect two sets of rectangular coordinates.
Returns false if the two regions didn't overlap.
See Also
intersectRectangle
template<typename ValueType> String Rectangle< ValueType >::toString () const
Creates a string describing this rectangle.
The string will be of the form "x y width height", e.g. "100 100 400 200".
Coupled with the fromString() method, this is very handy for things like storing rectangles (particularly component positions) in XML attributes.
See Also
fromString
template<typename ValueType> static Rectangle Rectangle< ValueType >::fromString (StringRef stringVersion) static
Parses a string containing a rectangle's details.
The string should contain 4 integer tokens, in the form "x y width height". They can be comma or whitespace separated.
This method is intended to go with the toString() method, to form an easy way of saving/loading rectangles as strings.
See Also
toString
class RectangleList
template<typename ValueType>
class RectangleList< ValueType >
Maintains a set of rectangles as a complex region.
This class allows a set of rectangles to be treated as a solid shape, and can add and remove rectangular sections of it, and simplify overlapping or adjacent rectangles.
See Also
Rectangle
Public Types
typedef Rectangle< ValueType > RectangleType
Public Member Functions
RectangleList () noexcept
Creates an empty RectangleList.
RectangleList (const RectangleList &other)
Creates a copy of another list.
RectangleList (const RectangleType &rect)
Creates a list containing just one rectangle.
RectangleList & operator= (const RectangleList &other)
Copies this list from another one.
RectangleList (RectangleList &&other) noexcept
Move constructor.
RectangleList & operator= (RectangleList &&other) noexcept
Move assignment operator.
bool isEmpty () const noexcept
Returns true if the region is empty.
int getNumRectangles () const noexcept
Returns the number of rectangles in the list.
RectangleType getRectangle (int index) const noexcept
Returns one of the rectangles at a particular index.
void clear ()
Removes all rectangles to leave an empty region.
void add (const RectangleType &rect)
Merges a new rectangle into the list.
void add (ValueType x, ValueType y, ValueType width, ValueType height)
Merges a new rectangle into the list.
void addWithoutMerging (const RectangleType &rect)
Dumbly adds a rectangle to the list without checking for overlaps.
void add (const RectangleList &other)
Merges another rectangle list into this one.
void subtract (const RectangleType &rect)
Removes a rectangular region from the list.
bool subtract (const RectangleList &otherList)
Removes all areas in another RectangleList from this one.
bool clipTo (const RectangleType &rect)
Removes any areas of the region that lie outside a given rectangle.
template<typename OtherValueType >
bool clipTo (const RectangleList< OtherValueType > &other)
Removes any areas of the region that lie outside a given rectangle list.
bool getIntersectionWith (const RectangleType &rect, RectangleList &destRegion) const
Creates a region which is the result of clipping this one to a given rectangle.
void swapWith (RectangleList &otherList) noexcept
Swaps the contents of this and another list.
bool containsPoint (Point< ValueType > point) const noexcept
Checks whether the region contains a given point.
bool containsPoint (ValueType x, ValueType y) const noexcept
Checks whether the region contains a given point.
bool containsRectangle (const RectangleType &rectangleToCheck) const
Checks whether the region contains the whole of a given rectangle.
bool intersectsRectangle (const RectangleType &rectangleToCheck) const noexcept
Checks whether the region contains any part of a given rectangle.
bool intersects (const RectangleList &other) const noexcept
Checks whether this region intersects any part of another one.
RectangleType getBounds () const noexcept
Returns the smallest rectangle that can enclose the whole of this region.
void consolidate ()
Optimises the list into a minimum number of constituent rectangles.
void offsetAll (Point< ValueType > offset) noexcept
Adds an x and y value to all the coordinates.
void offsetAll (ValueType dx, ValueType dy) noexcept
Adds an x and y value to all the coordinates.
template<typename ScaleType >
void scaleAll (ScaleType scaleFactor) noexcept
Scales all the coordinates.
void transformAll (const AffineTransform &transform) noexcept
Applies a transform to all the rectangles.
Path toPath () const
Creates a Path object to represent this region.
const RectangleType * begin () const noexcept
Standard method for iterating the rectangles in the list.
const RectangleType * end () const noexcept
Standard method for iterating the rectangles in the list.
void ensureStorageAllocated (int minNumRectangles)
Increases the internal storage to hold a minimum number of rectangles.
Member Typedef Documentation
template<typename ValueType> typedef Rectangle<ValueType> RectangleList< ValueType >::RectangleType
Constructor & Destructor Documentation
template<typename ValueType> RectangleList< ValueType >::RectangleList () noexcept
Creates an empty RectangleList.
template<typename ValueType> RectangleList< ValueType >::RectangleList (const RectangleList< ValueType > & other)
Creates a copy of another list.
template<typename ValueType> RectangleList< ValueType >::RectangleList (const RectangleType & rect)
Creates a list containing just one rectangle.
template<typename ValueType> RectangleList< ValueType >::RectangleList (RectangleList< ValueType > && other) noexcept
Move constructor.
Member Function Documentation
template<typename ValueType> RectangleList& RectangleList< ValueType >::operator= (const RectangleList< ValueType > & other)
Copies this list from another one.
template<typename ValueType> RectangleList& RectangleList< ValueType >::operator= (RectangleList< ValueType > && other) noexcept
Move assignment operator.
template<typename ValueType> bool RectangleList< ValueType >::isEmpty () const noexcept
Returns true if the region is empty.
Referenced by RectangleList< int >::add(), RectangleList< int >::clipTo(), RectangleList< int >::containsRectangle(), RectangleList< int >::getBounds(), RectangleList< int >::getIntersectionWith(), and RectangleList< int >::subtract().
template<typename ValueType> int RectangleList< ValueType >::getNumRectangles () const noexcept
Returns the number of rectangles in the list.
template<typename ValueType> RectangleType RectangleList< ValueType >::getRectangle (int index) const noexcept
Returns one of the rectangles at a particular index.
Returns
the rectangle at the index, or an empty rectangle if the index is out-of-range.
template<typename ValueType> void RectangleList< ValueType >::clear ()
Removes all rectangles to leave an empty region.
Referenced by RectangleList< int >::clipTo(), and RectangleList< int >::getIntersectionWith().
template<typename ValueType> void RectangleList< ValueType >::add (const RectangleType & rect)
Merges a new rectangle into the list.
The rectangle being added will first be clipped to remove any parts of it that overlap existing rectangles in the list, and adjacent rectangles will be merged into it.
The rectangle can have any size and may be empty, but if it's floating point then it's expected to not contain any INF values.
Referenced by RectangleList< int >::add().
template<typename ValueType> void RectangleList< ValueType >::add (ValueType x, ValueType y, ValueType width, ValueType height)
Merges a new rectangle into the list.
The rectangle being added will first be clipped to remove any parts of it that overlap existing rectangles in the list.
template<typename ValueType> void RectangleList< ValueType >::addWithoutMerging (const RectangleType & rect)
Dumbly adds a rectangle to the list without checking for overlaps.
This simply adds the rectangle to the end, it doesn't merge it or remove any overlapping bits.
The rectangle can have any size and may be empty, but if it's floating point then it's expected to not contain any INF values.
Referenced by RectangleList< int >::RectangleList().
template<typename ValueType> void RectangleList< ValueType >::add (const RectangleList< ValueType > & other)
Merges another rectangle list into this one.
Any overlaps between the two lists will be clipped, so that the result is the union of both lists.
template<typename ValueType> void RectangleList< ValueType >::subtract (const RectangleType & rect)
Removes a rectangular region from the list.
Any rectangles in the list which overlap this will be clipped and subdivided if necessary.
Referenced by RectangleList< int >::add(), RectangleList< int >::containsRectangle(), and RectangleList< int >::subtract().
template<typename ValueType> bool RectangleList< ValueType >::subtract (const RectangleList< ValueType > & otherList)
Removes all areas in another RectangleList from this one.
Any rectangles in the list which overlap this will be clipped and subdivided if necessary.
Returns
true if the resulting list is non-empty.
template<typename ValueType> bool RectangleList< ValueType >::clipTo (const RectangleType & rect)
Removes any areas of the region that lie outside a given rectangle.
Any rectangles in the list which overlap this will be clipped and subdivided if necessary.
Returns true if the resulting region is not empty, false if it is empty.
See Also
getIntersectionWith
template<typename ValueType> template<typename OtherValueType > bool RectangleList< ValueType >::clipTo (const RectangleList< OtherValueType > & other)
Removes any areas of the region that lie outside a given rectangle list.
Any rectangles in this object which overlap the specified list will be clipped and subdivided if necessary.
Returns true if the resulting region is not empty, false if it is empty.
See Also
getIntersectionWith
template<typename ValueType> bool RectangleList< ValueType >::getIntersectionWith (const RectangleType & rect, RectangleList< ValueType > & destRegion) const
Creates a region which is the result of clipping this one to a given rectangle.
Unlike the other clipTo method, this one doesn't affect this object - it puts the resulting region into the list whose reference is passed-in.
Returns true if the resulting region is not empty, false if it is empty.
See Also
clipTo
template<typename ValueType> void RectangleList< ValueType >::swapWith (RectangleList< ValueType > & otherList) noexcept
Swaps the contents of this and another list.
This swaps their internal pointers, so is hugely faster than using copy-by-value to swap them.
Referenced by RectangleList< int >::clipTo().
template<typename ValueType> bool RectangleList< ValueType >::containsPoint (Point< ValueType > point) const noexcept
Checks whether the region contains a given point.
Returns
true if the point lies within one of the rectangles in the list
Referenced by RectangleList< int >::containsPoint().
template<typename ValueType> bool RectangleList< ValueType >::containsPoint (ValueType x, ValueType y) const noexcept
Checks whether the region contains a given point.
Returns
true if the point lies within one of the rectangles in the list
template<typename ValueType> bool RectangleList< ValueType >::containsRectangle (const RectangleType & rectangleToCheck) const
Checks whether the region contains the whole of a given rectangle.
Returns
true all parts of the rectangle passed in lie within the region defined by this object
See Also
intersectsRectangle, containsPoint
template<typename ValueType> bool RectangleList< ValueType >::intersectsRectangle (const RectangleType & rectangleToCheck) const noexcept
Checks whether the region contains any part of a given rectangle.
Returns
true if any part of the rectangle passed in lies within the region defined by this object
See Also
containsRectangle
template<typename ValueType> bool RectangleList< ValueType >::intersects (const RectangleList< ValueType > & other) const noexcept
Checks whether this region intersects any part of another one.
See Also
intersectsRectangle
template<typename ValueType> RectangleType RectangleList< ValueType >::getBounds () const noexcept
Returns the smallest rectangle that can enclose the whole of this region.
template<typename ValueType> void RectangleList< ValueType >::consolidate ()
Optimises the list into a minimum number of constituent rectangles.
This will try to combine any adjacent rectangles into larger ones where possible, to simplify lists that might have been fragmented by repeated add/subtract calls.
template<typename ValueType> void RectangleList< ValueType >::offsetAll (Point< ValueType > offset) noexcept
Adds an x and y value to all the coordinates.
Referenced by RectangleList< int >::offsetAll().
template<typename ValueType> void RectangleList< ValueType >::offsetAll (ValueType dx, ValueType dy) noexcept
Adds an x and y value to all the coordinates.
template<typename ValueType> template<typename ScaleType > void RectangleList< ValueType >::scaleAll (ScaleType scaleFactor) noexcept
Scales all the coordinates.
template<typename ValueType> void RectangleList< ValueType >::transformAll (const AffineTransform & transform) noexcept
Applies a transform to all the rectangles.
Obviously this will create a mess if the transform involves any rotation or skewing.
template<typename ValueType> Path RectangleList< ValueType >::toPath () const
Creates a Path object to represent this region.
template<typename ValueType> const RectangleType* RectangleList< ValueType >::begin () const noexcept
Standard method for iterating the rectangles in the list.
template<typename ValueType> const RectangleType* RectangleList< ValueType >::end () const noexcept
Standard method for iterating the rectangles in the list.
template<typename ValueType> void RectangleList< ValueType >::ensureStorageAllocated (int minNumRectangles)
Increases the internal storage to hold a minimum number of rectangles.
Calling this before adding a large number of rectangles means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
See Also
Array::ensureStorageAllocated
Function Documentation
template<typename ValueType > Point<ValueType> operator* (ValueType value, Point< ValueType > p) noexcept
Multiplies the point's coordinates by a scalar value.