JUCE: colour
colour
juce_graphics
Classes
class Colour
Represents a colour, also including a transparency value.
class ColourGradient
Describes the layout and colours that should be used to paint a colour gradient.
class Colours
Contains a set of predefined named colours (mostly standard HTML colours)
class FillType
Represents a colour or fill pattern to use for rendering paths.
class PixelARGB
Represents a 32-bit INTERNAL pixel with premultiplied alpha, and can perform compositing operations with it.
class PixelRGB
Represents a 24-bit RGB pixel, and can perform compositing operations on it.
class PixelAlpha
Represents an 8-bit single-channel pixel, and can perform compositing operations on it.
Functions
uint32 maskPixelComponents (uint32 x) noexcept
uint32 clampPixelComponents (uint32 x) noexcept
forcedinline void PixelARGB::blend (const PixelRGB src) noexcept
Blends another pixel onto this one.
Detailed Description
Class Documentation
class Colour
Represents a colour, also including a transparency value.
The colour is stored internally as unsigned 8-bit red, green, blue and alpha values.
Public Member Functions
Colour () noexcept
Creates a transparent black colour.
Colour (const Colour &other) noexcept
Creates a copy of another Colour object.
Colour (uint32 argb) noexcept
Creates a colour from a 32-bit ARGB value.
Colour (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
Colour (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
Colour (uint8 red, uint8 green, uint8 blue, float alpha) noexcept
Creates a colour from 8-bit red, green, and blue values, and a floating-point alpha.
Colour (float hue, float saturation, float brightness, uint8 alpha) noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
Colour (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using floating point hue, saturation, brightness and alpha values.
Colour (PixelARGB argb) noexcept
Creates a colour using a PixelARGB object.
Colour (PixelRGB rgb) noexcept
Creates a colour using a PixelRGB object.
Colour (PixelAlpha alpha) noexcept
Creates a colour using a PixelAlpha object.
~Colour () noexcept
Destructor.
Colour & operator= (const Colour &other) noexcept
Copies another Colour object.
bool operator== (const Colour &other) const noexcept
Compares two colours.
bool operator!= (const Colour &other) const noexcept
Compares two colours.
uint8 getRed () const noexcept
Returns the red component of this colour.
uint8 getGreen () const noexcept
Returns the green component of this colour.
uint8 getBlue () const noexcept
Returns the blue component of this colour.
float getFloatRed () const noexcept
Returns the red component of this colour as a floating point value.
float getFloatGreen () const noexcept
Returns the green component of this colour as a floating point value.
float getFloatBlue () const noexcept
Returns the blue component of this colour as a floating point value.
const PixelARGB getPixelARGB () const noexcept
Returns a premultiplied ARGB pixel object that represents this colour.
uint32 getARGB () const noexcept
Returns a 32-bit integer that represents this colour.
uint8 getAlpha () const noexcept
Returns the colour's alpha (opacity).
float getFloatAlpha () const noexcept
Returns the colour's alpha (opacity) as a floating point value.
bool isOpaque () const noexcept
Returns true if this colour is completely opaque.
bool isTransparent () const noexcept
Returns true if this colour is completely transparent.
Colour withAlpha (uint8 newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour withAlpha (float newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour withMultipliedAlpha (float alphaMultiplier) const noexcept
Returns a colour that's the same colour as this one, but with a modified alpha value.
Colour overlaidWith (Colour foregroundColour) const noexcept
Returns a colour that is the result of alpha-compositing a new colour over this one.
Colour interpolatedWith (Colour other, float proportionOfOther) const noexcept
Returns a colour that lies somewhere between this one and another.
float getHue () const noexcept
Returns the colour's hue component.
float getSaturation () const noexcept
Returns the colour's saturation component.
float getBrightness () const noexcept
Returns the colour's brightness component.
float getPerceivedBrightness () const noexcept
Returns a skewed brightness value, adjusted to better reflect the way the human eye responds to different colour channels.
void getHSB (float &hue, float &saturation, float &brightness) const noexcept
Returns the colour's hue, saturation and brightness components all at once.
Colour withHue (float newHue) const noexcept
Returns a copy of this colour with a different hue.
Colour withSaturation (float newSaturation) const noexcept
Returns a copy of this colour with a different saturation.
Colour withBrightness (float newBrightness) const noexcept
Returns a copy of this colour with a different brightness.
Colour withRotatedHue (float amountToRotate) const noexcept
Returns a copy of this colour with it hue rotated.
Colour withMultipliedSaturation (float multiplier) const noexcept
Returns a copy of this colour with its saturation multiplied by the given value.
Colour withMultipliedBrightness (float amount) const noexcept
Returns a copy of this colour with its brightness multiplied by the given value.
Colour brighter (float amountBrighter=0.4f) const noexcept
Returns a brighter version of this colour.
Colour darker (float amountDarker=0.4f) const noexcept
Returns a darker version of this colour.
Colour contrasting (float amount=1.0f) const noexcept
Returns a colour that will be clearly visible against this colour.
Colour contrasting (Colour targetColour, float minLuminosityDiff) const noexcept
Returns a colour that is as close as possible to a target colour whilst still being in contrast to this one.
String toString () const
Returns a stringified version of this colour.
String toDisplayString (bool includeAlphaValue) const
Returns the colour as a hex string in the form RRGGBB or AARRGGBB.
Static Public Member Functions
static Colour fromRGB (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
static Colour fromRGBA (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
static Colour fromFloatRGBA (float red, float green, float blue, float alpha) noexcept
Creates a colour using floating point red, green, blue and alpha values.
static Colour fromHSV (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
static Colour contrasting (Colour colour1, Colour colour2) noexcept
Returns a colour that contrasts against two colours.
static Colour greyLevel (float brightness) noexcept
Returns an opaque shade of grey.
static Colour fromString (StringRef encodedColourString)
Reads the colour from a string that was created with toString().
Constructor & Destructor Documentation
Colour::Colour () noexcept
Creates a transparent black colour.
Colour::Colour (const Colour & other) noexcept
Creates a copy of another Colour object.
Colour::Colour (uint32 argb) explicit noexcept
Creates a colour from a 32-bit ARGB value.
The format of this number is: ((alpha << 24) | (red << 16) | (green << 8) | blue).
All components in the range 0x00 to 0xff. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque.
See Also
getPixelARGB
Colour::Colour (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
Colour::Colour (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
Colour::Colour (uint8 red, uint8 green, uint8 blue, float alpha) noexcept
Creates a colour from 8-bit red, green, and blue values, and a floating-point alpha.
Alpha of 0.0 is transparent, alpha of 1.0f is opaque. Values outside the valid range will be clipped.
Colour::Colour (float hue, float saturation, float brightness, uint8 alpha) noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
The floating point values must be between 0.0 and 1.0. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque. Values outside the valid range will be clipped.
Colour::Colour (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using floating point hue, saturation, brightness and alpha values.
All values must be between 0.0 and 1.0. Numbers outside the valid range will be clipped.
Colour::Colour (PixelARGB argb) noexcept
Creates a colour using a PixelARGB object.
This function assumes that the argb pixel is not premultiplied.
Colour::Colour (PixelRGB rgb) noexcept
Creates a colour using a PixelRGB object.
Colour::Colour (PixelAlpha alpha) noexcept
Creates a colour using a PixelAlpha object.
Colour::~Colour () noexcept
Destructor.
Member Function Documentation
static Colour Colour::fromRGB (uint8 red, uint8 green, uint8 blue) static noexcept
Creates an opaque colour using 8-bit red, green and blue values.
static Colour Colour::fromRGBA (uint8 red, uint8 green, uint8 blue, uint8 alpha) static noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
static Colour Colour::fromFloatRGBA (float red, float green, float blue, float alpha) static noexcept
Creates a colour using floating point red, green, blue and alpha values.
Numbers outside the range 0..1 will be clipped.
static Colour Colour::fromHSV (float hue, float saturation, float brightness, float alpha) static noexcept
Creates a colour using floating point hue, saturation and brightness values, and an 8-bit alpha.
The floating point values must be between 0.0 and 1.0. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque. Values outside the valid range will be clipped.
Colour& Colour::operator= (const Colour & other) noexcept
Copies another Colour object.
bool Colour::operator== (const Colour & other) const noexcept
Compares two colours.
bool Colour::operator!= (const Colour & other) const noexcept
Compares two colours.
uint8 Colour::getRed () const noexcept
Returns the red component of this colour.
Returns
a value between 0x00 and 0xff.
References PixelARGB::getRed().
uint8 Colour::getGreen () const noexcept
Returns the green component of this colour.
Returns
a value between 0x00 and 0xff.
References PixelARGB::getGreen().
uint8 Colour::getBlue () const noexcept
Returns the blue component of this colour.
Returns
a value between 0x00 and 0xff.
References PixelARGB::getBlue().
float Colour::getFloatRed () const noexcept
Returns the red component of this colour as a floating point value.
Returns
a value between 0.0 and 1.0
float Colour::getFloatGreen () const noexcept
Returns the green component of this colour as a floating point value.
Returns
a value between 0.0 and 1.0
float Colour::getFloatBlue () const noexcept
Returns the blue component of this colour as a floating point value.
Returns
a value between 0.0 and 1.0
const PixelARGB Colour::getPixelARGB () const noexcept
Returns a premultiplied ARGB pixel object that represents this colour.
uint32 Colour::getARGB () const noexcept
Returns a 32-bit integer that represents this colour.
The format of this number is: ((alpha << 24) | (red << 16) | (green << 16) | blue).
uint8 Colour::getAlpha () const noexcept
Returns the colour's alpha (opacity).
Alpha of 0x00 is completely transparent, 0xff is completely opaque.
References PixelARGB::getAlpha().
float Colour::getFloatAlpha () const noexcept
Returns the colour's alpha (opacity) as a floating point value.
Alpha of 0.0 is completely transparent, 1.0 is completely opaque.
Referenced by FillType::getOpacity().
bool Colour::isOpaque () const noexcept
Returns true if this colour is completely opaque.
Equivalent to (getAlpha() == 0xff).
bool Colour::isTransparent () const noexcept
Returns true if this colour is completely transparent.
Equivalent to (getAlpha() == 0x00).
Colour Colour::withAlpha (uint8 newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour Colour::withAlpha (float newAlpha) const noexcept
Returns a colour that's the same colour as this one, but with a new alpha value.
Colour Colour::withMultipliedAlpha (float alphaMultiplier) const noexcept
Returns a colour that's the same colour as this one, but with a modified alpha value.
The new colour's alpha will be this object's alpha multiplied by the value passed-in.
Colour Colour::overlaidWith (Colour foregroundColour) const noexcept
Returns a colour that is the result of alpha-compositing a new colour over this one.
If the foreground colour is semi-transparent, it is blended onto this colour accordingly.
Colour Colour::interpolatedWith (Colour other, float proportionOfOther) const noexcept
Returns a colour that lies somewhere between this one and another.
If amountOfOther is zero, the result is 100% this colour, if amountOfOther is 1.0, the result is 100% of the other colour.
float Colour::getHue () const noexcept
Returns the colour's hue component.
The value returned is in the range 0.0 to 1.0
float Colour::getSaturation () const noexcept
Returns the colour's saturation component.
The value returned is in the range 0.0 to 1.0
float Colour::getBrightness () const noexcept
Returns the colour's brightness component.
The value returned is in the range 0.0 to 1.0
float Colour::getPerceivedBrightness () const noexcept
Returns a skewed brightness value, adjusted to better reflect the way the human eye responds to different colour channels.
This makes it better than getBrightness() for comparing differences in brightness.
void Colour::getHSB (float & hue, float & saturation, float & brightness) const noexcept
Returns the colour's hue, saturation and brightness components all at once.
The values returned are in the range 0.0 to 1.0
Colour Colour::withHue (float newHue) const noexcept
Returns a copy of this colour with a different hue.
Colour Colour::withSaturation (float newSaturation) const noexcept
Returns a copy of this colour with a different saturation.
Colour Colour::withBrightness (float newBrightness) const noexcept
Returns a copy of this colour with a different brightness.
See Also
brighter, darker, withMultipliedBrightness
Colour Colour::withRotatedHue (float amountToRotate) const noexcept
Returns a copy of this colour with it hue rotated.
The new colour's hue is ((this->getHue() + amountToRotate) % 1.0)
See Also
brighter, darker, withMultipliedBrightness
Colour Colour::withMultipliedSaturation (float multiplier) const noexcept
Returns a copy of this colour with its saturation multiplied by the given value.
The new colour's saturation is (this->getSaturation() * multiplier) (the result is clipped to legal limits).
Colour Colour::withMultipliedBrightness (float amount) const noexcept
Returns a copy of this colour with its brightness multiplied by the given value.
The new colour's brightness is (this->getBrightness() * multiplier) (the result is clipped to legal limits).
Colour Colour::brighter (float amountBrighter = 0.4f) const noexcept
Returns a brighter version of this colour.
Parameters
amountBrighter how much brighter to make it - a value from 0 to 1.0 where 0 is unchanged, and higher values make it brighter
See Also
withMultipliedBrightness
Colour Colour::darker (float amountDarker = 0.4f) const noexcept
Returns a darker version of this colour.
Parameters
amountDarker how much darker to make it - a value from 0 to 1.0 where 0 is unchanged, and higher values make it darker
See Also
withMultipliedBrightness
Colour Colour::contrasting (float amount = 1.0f) const noexcept
Returns a colour that will be clearly visible against this colour.
The amount parameter indicates how contrasting the new colour should be, so e.g. Colours::black.contrasting (0.1f) will return a colour that's just a little bit lighter; Colours::black.contrasting (1.0f) will return white; Colours::white.contrasting (1.0f) will return black, etc.
Colour Colour::contrasting (Colour targetColour, float minLuminosityDiff) const noexcept
Returns a colour that is as close as possible to a target colour whilst still being in contrast to this one.
The colour that is returned will be the targetColour, but with its luminosity nudged up or down so that it differs from the luminosity of this colour by at least the amount specified by minLuminosityDiff.
static Colour Colour::contrasting (Colour colour1, Colour colour2) static noexcept
Returns a colour that contrasts against two colours.
Looks for a colour that contrasts with both of the colours passed-in. Handy for things like choosing a highlight colour in text editors, etc.
static Colour Colour::greyLevel (float brightness) static noexcept
Returns an opaque shade of grey.
Parameters
brightness the level of grey to return - 0 is black, 1.0 is white
String Colour::toString () const
Returns a stringified version of this colour.
The string can be turned back into a colour using the fromString() method.
static Colour Colour::fromString (StringRef encodedColourString) static
Reads the colour from a string that was created with toString().
String Colour::toDisplayString (bool includeAlphaValue) const
Returns the colour as a hex string in the form RRGGBB or AARRGGBB.
class ColourGradient
Describes the layout and colours that should be used to paint a colour gradient.
See Also
Graphics::setGradientFill
Public Member Functions
ColourGradient (Colour colour1, float x1, float y1, Colour colour2, float x2, float y2, bool isRadial)
Creates a gradient object.
ColourGradient (Colour colour1, Point< float > point1, Colour colour2, Point< float > point2, bool isRadial)
Creates a gradient object.
ColourGradient () noexcept
Creates an uninitialised gradient.
~ColourGradient ()
Destructor.
void clearColours ()
Removes any colours that have been added.
int addColour (double proportionAlongGradient, Colour colour)
Adds a colour at a point along the length of the gradient.
void removeColour (int index)
Removes one of the colours from the gradient.
void multiplyOpacity (float multiplier) noexcept
Multiplies the alpha value of all the colours by the given scale factor.
int getNumColours () const noexcept
Returns the number of colour-stops that have been added.
double getColourPosition (int index) const noexcept
Returns the position along the length of the gradient of the colour with this index.
Colour getColour (int index) const noexcept
Returns the colour that was added with a given index.
void setColour (int index, Colour newColour) noexcept
Changes the colour at a given index.
Colour getColourAtPosition (double position) const noexcept
Returns the an interpolated colour at any position along the gradient.
int createLookupTable (const AffineTransform &transform, HeapBlock< PixelARGB > &resultLookupTable) const
Creates a set of interpolated premultiplied ARGB values.
void createLookupTable (PixelARGB *resultLookupTable, int numEntries) const noexcept
Creates a set of interpolated premultiplied ARGB values.
bool isOpaque () const noexcept
Returns true if all colours are opaque.
bool isInvisible () const noexcept
Returns true if all colours are completely transparent.
bool operator== (const ColourGradient &) const noexcept
bool operator!= (const ColourGradient &) const noexcept
Public Attributes
Point< float > point1
Point< float > point2
bool isRadial
If true, the gradient should be filled circularly, centred around point1, with point2 defining a point on the circumference.
Constructor & Destructor Documentation
ColourGradient::ColourGradient (Colour colour1, float x1, float y1, Colour colour2, float x2, float y2, bool isRadial)
Creates a gradient object.
(x1, y1) is the location to draw with colour1. Likewise (x2, y2) is where colour2 should be. In between them there's a gradient.
If isRadial is true, the colours form a circular gradient with (x1, y1) at its centre.
The alpha transparencies of the colours are used, so note that if you blend from transparent to a solid colour, the RGB of the transparent colour will become visible in parts of the gradient. e.g. blending from Colour::transparentBlack to Colours::white will produce a muddy grey colour midway, but Colour::transparentWhite to Colours::white will be white all the way across.
See Also
ColourGradient
ColourGradient::ColourGradient (Colour colour1, Point< float > point1, Colour colour2, Point< float > point2, bool isRadial)
Creates a gradient object.
point1 is the location to draw with colour1. Likewise point2 is where colour2 should be. In between them there's a gradient.
If isRadial is true, the colours form a circular gradient with point1 at its centre.
The alpha transparencies of the colours are used, so note that if you blend from transparent to a solid colour, the RGB of the transparent colour will become visible in parts of the gradient. e.g. blending from Colour::transparentBlack to Colours::white will produce a muddy grey colour midway, but Colour::transparentWhite to Colours::white will be white all the way across.
See Also
ColourGradient
ColourGradient::ColourGradient () noexcept
Creates an uninitialised gradient.
If you use this constructor instead of the other one, be sure to set all the object's public member variables before using it!
ColourGradient::~ColourGradient ()
Destructor.
Member Function Documentation
void ColourGradient::clearColours ()
Removes any colours that have been added.
This will also remove any start and end colours, so the gradient won't work. You'll need to add more colours with addColour().
int ColourGradient::addColour (double proportionAlongGradient, Colour colour)
Adds a colour at a point along the length of the gradient.
This allows the gradient to go through a spectrum of colours, instead of just a start and end colour.
Parameters
proportionAlongGradient a value between 0 and 1.0, which is the proportion of the distance along the line between the two points at which the colour should occur.
colour the colour that should be used at this point
Returns
the index at which the new point was added
void ColourGradient::removeColour (int index)
Removes one of the colours from the gradient.
void ColourGradient::multiplyOpacity (float multiplier) noexcept
Multiplies the alpha value of all the colours by the given scale factor.
int ColourGradient::getNumColours () const noexcept
Returns the number of colour-stops that have been added.
double ColourGradient::getColourPosition (int index) const noexcept
Returns the position along the length of the gradient of the colour with this index.
The index is from 0 to getNumColours() - 1. The return value will be between 0.0 and 1.0
Colour ColourGradient::getColour (int index) const noexcept
Returns the colour that was added with a given index.
The index is from 0 to getNumColours() - 1.
void ColourGradient::setColour (int index, Colour newColour) noexcept
Changes the colour at a given index.
The index is from 0 to getNumColours() - 1.
Colour ColourGradient::getColourAtPosition (double position) const noexcept
Returns the an interpolated colour at any position along the gradient.
Parameters
position the position along the gradient, between 0 and 1
int ColourGradient::createLookupTable (const AffineTransform & transform, HeapBlock< PixelARGB > & resultLookupTable) const
Creates a set of interpolated premultiplied ARGB values.
This will resize the HeapBlock, fill it with the colours, and will return the number of colours that it added. When calling this, the ColourGradient must have at least 2 colour stops specified.
void ColourGradient::createLookupTable (PixelARGB * resultLookupTable, int numEntries) const noexcept
Creates a set of interpolated premultiplied ARGB values.
This will fill an array of a user-specified size with the gradient, interpolating to fit. The numEntries argument specifies the size of the array, and this size must be greater than zero. When calling this, the ColourGradient must have at least 2 colour stops specified.
bool ColourGradient::isOpaque () const noexcept
Returns true if all colours are opaque.
bool ColourGradient::isInvisible () const noexcept
Returns true if all colours are completely transparent.
bool ColourGradient::operator== (const ColourGradient &) const noexcept
bool ColourGradient::operator!= (const ColourGradient &) const noexcept
Member Data Documentation
Point<float> ColourGradient::point1
Point<float> ColourGradient::point2
bool ColourGradient::isRadial
If true, the gradient should be filled circularly, centred around point1, with point2 defining a point on the circumference.
If false, the gradient is linear between the two points.
class Colours
Contains a set of predefined named colours (mostly standard HTML colours)
See Also
Colour, Colours::greyLevel
Static Public Member Functions
static JUCE_API Colour findColourForName (const String &colourName, Colour defaultColour)
Attempts to look up a string in the list of known colour names, and return the appropriate colour.
Static Public Attributes
static JUCE_API const Colour transparentBlack
ARGB = 0x00000000.
static JUCE_API const Colour transparentWhite
ARGB = 0x00ffffff.
static JUCE_API const Colour black
ARGB = 0xff000000.
static JUCE_API const Colour white
ARGB = 0xffffffff.
static JUCE_API const Colour blue
ARGB = 0xff0000ff.
static JUCE_API const Colour grey
ARGB = 0xff808080.
static JUCE_API const Colour green
ARGB = 0xff008000.
static JUCE_API const Colour red
ARGB = 0xffff0000.
static JUCE_API const Colour yellow
ARGB = 0xffffff00.
static JUCE_API const Colour aliceblue
static JUCE_API const Colour antiquewhite
static JUCE_API const Colour aqua
static JUCE_API const Colour aquamarine
static JUCE_API const Colour azure
static JUCE_API const Colour beige
static JUCE_API const Colour bisque
static JUCE_API const Colour blanchedalmond
static JUCE_API const Colour blueviolet
static JUCE_API const Colour brown
static JUCE_API const Colour burlywood
static JUCE_API const Colour cadetblue
static JUCE_API const Colour chartreuse
static JUCE_API const Colour chocolate
static JUCE_API const Colour coral
static JUCE_API const Colour cornflowerblue
static JUCE_API const Colour cornsilk
static JUCE_API const Colour crimson
static JUCE_API const Colour cyan
static JUCE_API const Colour darkblue
static JUCE_API const Colour darkcyan
static JUCE_API const Colour darkgoldenrod
static JUCE_API const Colour darkgrey
static JUCE_API const Colour darkgreen
static JUCE_API const Colour darkkhaki
static JUCE_API const Colour darkmagenta
static JUCE_API const Colour darkolivegreen
static JUCE_API const Colour darkorange
static JUCE_API const Colour darkorchid
static JUCE_API const Colour darkred
static JUCE_API const Colour darksalmon
static JUCE_API const Colour darkseagreen
static JUCE_API const Colour darkslateblue
static JUCE_API const Colour darkslategrey
static JUCE_API const Colour darkturquoise
static JUCE_API const Colour darkviolet
static JUCE_API const Colour deeppink
static JUCE_API const Colour deepskyblue
static JUCE_API const Colour dimgrey
static JUCE_API const Colour dodgerblue
static JUCE_API const Colour firebrick
static JUCE_API const Colour floralwhite
static JUCE_API const Colour forestgreen
static JUCE_API const Colour fuchsia
static JUCE_API const Colour gainsboro
static JUCE_API const Colour gold
static JUCE_API const Colour goldenrod
static JUCE_API const Colour greenyellow
static JUCE_API const Colour honeydew
static JUCE_API const Colour hotpink
static JUCE_API const Colour indianred
static JUCE_API const Colour indigo
static JUCE_API const Colour ivory
static JUCE_API const Colour khaki
static JUCE_API const Colour lavender
static JUCE_API const Colour lavenderblush
static JUCE_API const Colour lemonchiffon
static JUCE_API const Colour lightblue
static JUCE_API const Colour lightcoral
static JUCE_API const Colour lightcyan
static JUCE_API const Colour lightgoldenrodyellow
static JUCE_API const Colour lightgreen
static JUCE_API const Colour lightgrey
static JUCE_API const Colour lightpink
static JUCE_API const Colour lightsalmon
static JUCE_API const Colour lightseagreen
static JUCE_API const Colour lightskyblue
static JUCE_API const Colour lightslategrey
static JUCE_API const Colour lightsteelblue
static JUCE_API const Colour lightyellow
static JUCE_API const Colour lime
static JUCE_API const Colour limegreen
static JUCE_API const Colour linen
static JUCE_API const Colour magenta
static JUCE_API const Colour maroon
static JUCE_API const Colour mediumaquamarine
static JUCE_API const Colour mediumblue
static JUCE_API const Colour mediumorchid
static JUCE_API const Colour mediumpurple
static JUCE_API const Colour mediumseagreen
static JUCE_API const Colour mediumslateblue
static JUCE_API const Colour mediumspringgreen
static JUCE_API const Colour mediumturquoise
static JUCE_API const Colour mediumvioletred
static JUCE_API const Colour midnightblue
static JUCE_API const Colour mintcream
static JUCE_API const Colour mistyrose
static JUCE_API const Colour navajowhite
static JUCE_API const Colour navy
static JUCE_API const Colour oldlace
static JUCE_API const Colour olive
static JUCE_API const Colour olivedrab
static JUCE_API const Colour orange
static JUCE_API const Colour orangered
static JUCE_API const Colour orchid
static JUCE_API const Colour palegoldenrod
static JUCE_API const Colour palegreen
static JUCE_API const Colour paleturquoise
static JUCE_API const Colour palevioletred
static JUCE_API const Colour papayawhip
static JUCE_API const Colour peachpuff
static JUCE_API const Colour peru
static JUCE_API const Colour pink
static JUCE_API const Colour plum
static JUCE_API const Colour powderblue
static JUCE_API const Colour purple
static JUCE_API const Colour rosybrown
static JUCE_API const Colour royalblue
static JUCE_API const Colour saddlebrown
static JUCE_API const Colour salmon
static JUCE_API const Colour sandybrown
static JUCE_API const Colour seagreen
static JUCE_API const Colour seashell
static JUCE_API const Colour sienna
static JUCE_API const Colour silver
static JUCE_API const Colour skyblue
static JUCE_API const Colour slateblue
static JUCE_API const Colour slategrey
static JUCE_API const Colour snow
static JUCE_API const Colour springgreen
static JUCE_API const Colour steelblue
static JUCE_API const Colour tan
static JUCE_API const Colour teal
static JUCE_API const Colour thistle
static JUCE_API const Colour tomato
static JUCE_API const Colour turquoise
static JUCE_API const Colour violet
static JUCE_API const Colour wheat
static JUCE_API const Colour whitesmoke
static JUCE_API const Colour yellowgreen
Member Function Documentation
static JUCE_API Colour Colours::findColourForName (const String & colourName, Colour defaultColour) static
Attempts to look up a string in the list of known colour names, and return the appropriate colour.
A non-case-sensitive search is made of the list of predefined colours, and if a match is found, that colour is returned. If no match is found, the colour passed in as the defaultColour parameter is returned.
Member Data Documentation
JUCE_API const Colour Colours::transparentBlack static
ARGB = 0x00000000.
JUCE_API const Colour Colours::transparentWhite static
ARGB = 0x00ffffff.
JUCE_API const Colour Colours::black static
ARGB = 0xff000000.
JUCE_API const Colour Colours::white static
ARGB = 0xffffffff.
JUCE_API const Colour Colours::blue static
ARGB = 0xff0000ff.
JUCE_API const Colour Colours::grey static
ARGB = 0xff808080.
JUCE_API const Colour Colours::green static
ARGB = 0xff008000.
JUCE_API const Colour Colours::red static
ARGB = 0xffff0000.
JUCE_API const Colour Colours::yellow static
ARGB = 0xffffff00.
JUCE_API const Colour Colours::aliceblue static
JUCE_API const Colour Colours::antiquewhite static
JUCE_API const Colour Colours::aqua static
JUCE_API const Colour Colours::aquamarine static
JUCE_API const Colour Colours::azure static
JUCE_API const Colour Colours::beige static
JUCE_API const Colour Colours::bisque static
JUCE_API const Colour Colours::blanchedalmond static
JUCE_API const Colour Colours::blueviolet static
JUCE_API const Colour Colours::brown static
JUCE_API const Colour Colours::burlywood static
JUCE_API const Colour Colours::cadetblue static
JUCE_API const Colour Colours::chartreuse static
JUCE_API const Colour Colours::chocolate static
JUCE_API const Colour Colours::coral static
JUCE_API const Colour Colours::cornflowerblue static
JUCE_API const Colour Colours::cornsilk static
JUCE_API const Colour Colours::crimson static
JUCE_API const Colour Colours::cyan static
JUCE_API const Colour Colours::darkblue static
JUCE_API const Colour Colours::darkcyan static
JUCE_API const Colour Colours::darkgoldenrod static
JUCE_API const Colour Colours::darkgrey static
JUCE_API const Colour Colours::darkgreen static
JUCE_API const Colour Colours::darkkhaki static
JUCE_API const Colour Colours::darkmagenta static
JUCE_API const Colour Colours::darkolivegreen static
JUCE_API const Colour Colours::darkorange static
JUCE_API const Colour Colours::darkorchid static
JUCE_API const Colour Colours::darkred static
JUCE_API const Colour Colours::darksalmon static
JUCE_API const Colour Colours::darkseagreen static
JUCE_API const Colour Colours::darkslateblue static
JUCE_API const Colour Colours::darkslategrey static
JUCE_API const Colour Colours::darkturquoise static
JUCE_API const Colour Colours::darkviolet static
JUCE_API const Colour Colours::deeppink static
JUCE_API const Colour Colours::deepskyblue static
JUCE_API const Colour Colours::dimgrey static
JUCE_API const Colour Colours::dodgerblue static
JUCE_API const Colour Colours::firebrick static
JUCE_API const Colour Colours::floralwhite static
JUCE_API const Colour Colours::forestgreen static
JUCE_API const Colour Colours::fuchsia static
JUCE_API const Colour Colours::gainsboro static
JUCE_API const Colour Colours::gold static
JUCE_API const Colour Colours::goldenrod static
JUCE_API const Colour Colours::greenyellow static
JUCE_API const Colour Colours::honeydew static
JUCE_API const Colour Colours::hotpink static
JUCE_API const Colour Colours::indianred static
JUCE_API const Colour Colours::indigo static
JUCE_API const Colour Colours::ivory static
JUCE_API const Colour Colours::khaki static
JUCE_API const Colour Colours::lavender static
JUCE_API const Colour Colours::lavenderblush static
JUCE_API const Colour Colours::lemonchiffon static
JUCE_API const Colour Colours::lightblue static
JUCE_API const Colour Colours::lightcoral static
JUCE_API const Colour Colours::lightcyan static
JUCE_API const Colour Colours::lightgoldenrodyellow static
JUCE_API const Colour Colours::lightgreen static
JUCE_API const Colour Colours::lightgrey static
JUCE_API const Colour Colours::lightpink static
JUCE_API const Colour Colours::lightsalmon static
JUCE_API const Colour Colours::lightseagreen static
JUCE_API const Colour Colours::lightskyblue static
JUCE_API const Colour Colours::lightslategrey static
JUCE_API const Colour Colours::lightsteelblue static
JUCE_API const Colour Colours::lightyellow static
JUCE_API const Colour Colours::lime static
JUCE_API const Colour Colours::limegreen static
JUCE_API const Colour Colours::linen static
JUCE_API const Colour Colours::magenta static
JUCE_API const Colour Colours::maroon static
JUCE_API const Colour Colours::mediumaquamarine static
JUCE_API const Colour Colours::mediumblue static
JUCE_API const Colour Colours::mediumorchid static
JUCE_API const Colour Colours::mediumpurple static
JUCE_API const Colour Colours::mediumseagreen static
JUCE_API const Colour Colours::mediumslateblue static
JUCE_API const Colour Colours::mediumspringgreen static
JUCE_API const Colour Colours::mediumturquoise static
JUCE_API const Colour Colours::mediumvioletred static
JUCE_API const Colour Colours::midnightblue static
JUCE_API const Colour Colours::mintcream static
JUCE_API const Colour Colours::mistyrose static
JUCE_API const Colour Colours::navajowhite static
JUCE_API const Colour Colours::navy static
JUCE_API const Colour Colours::oldlace static
JUCE_API const Colour Colours::olive static
JUCE_API const Colour Colours::olivedrab static
JUCE_API const Colour Colours::orange static
JUCE_API const Colour Colours::orangered static
JUCE_API const Colour Colours::orchid static
JUCE_API const Colour Colours::palegoldenrod static
JUCE_API const Colour Colours::palegreen static
JUCE_API const Colour Colours::paleturquoise static
JUCE_API const Colour Colours::palevioletred static
JUCE_API const Colour Colours::papayawhip static
JUCE_API const Colour Colours::peachpuff static
JUCE_API const Colour Colours::peru static
JUCE_API const Colour Colours::pink static
JUCE_API const Colour Colours::plum static
JUCE_API const Colour Colours::powderblue static
JUCE_API const Colour Colours::purple static
JUCE_API const Colour Colours::rosybrown static
JUCE_API const Colour Colours::royalblue static
JUCE_API const Colour Colours::saddlebrown static
JUCE_API const Colour Colours::salmon static
JUCE_API const Colour Colours::sandybrown static
JUCE_API const Colour Colours::seagreen static
JUCE_API const Colour Colours::seashell static
JUCE_API const Colour Colours::sienna static
JUCE_API const Colour Colours::silver static
JUCE_API const Colour Colours::skyblue static
JUCE_API const Colour Colours::slateblue static
JUCE_API const Colour Colours::slategrey static
JUCE_API const Colour Colours::snow static
JUCE_API const Colour Colours::springgreen static
JUCE_API const Colour Colours::steelblue static
JUCE_API const Colour Colours::tan static
JUCE_API const Colour Colours::teal static
JUCE_API const Colour Colours::thistle static
JUCE_API const Colour Colours::tomato static
JUCE_API const Colour Colours::turquoise static
JUCE_API const Colour Colours::violet static
JUCE_API const Colour Colours::wheat static
JUCE_API const Colour Colours::whitesmoke static
JUCE_API const Colour Colours::yellowgreen static
class FillType
Represents a colour or fill pattern to use for rendering paths.
This is used by the Graphics and DrawablePath classes as a way to encapsulate a brush type. It can either be a solid colour, a gradient, or a tiled image.
See Also
Graphics::setFillType, DrawablePath::setFill
Public Member Functions
FillType () noexcept
Creates a default fill type, of solid black.
FillType (Colour colour) noexcept
Creates a fill type of a solid colour.
FillType (const ColourGradient &gradient)
Creates a gradient fill type.
FillType (const Image &image, const AffineTransform &transform) noexcept
Creates a tiled image fill type.
FillType (const FillType &)
Creates a copy of another FillType.
FillType & operator= (const FillType &)
Makes a copy of another FillType.
FillType (FillType &&) noexcept
Move constructor.
FillType & operator= (FillType &&) noexcept
Move assignment operator.
~FillType () noexcept
Destructor.
bool isColour () const noexcept
Returns true if this is a solid colour fill, and not a gradient or image.
bool isGradient () const noexcept
Returns true if this is a gradient fill.
bool isTiledImage () const noexcept
Returns true if this is a tiled image pattern fill.
void setColour (Colour newColour) noexcept
Turns this object into a solid colour fill.
void setGradient (const ColourGradient &newGradient)
Turns this object into a gradient fill.
void setTiledImage (const Image &image, const AffineTransform &transform) noexcept
Turns this object into a tiled image fill type.
void setOpacity (float newOpacity) noexcept
Changes the opacity that should be used.
float getOpacity () const noexcept
Returns the current opacity to be applied to the colour, gradient, or image.
bool isInvisible () const noexcept
Returns true if this fill type is completely transparent.
FillType transformed (const AffineTransform &transform) const
Returns a copy of this fill, adding the specified transform applied to the existing transform.
bool operator== (const FillType &) const
bool operator!= (const FillType &) const
Public Attributes
Colour colour
The solid colour being used.
ScopedPointer< ColourGradient > gradient
Returns the gradient that should be used for filling.
Image image
The image that should be used for tiling.
AffineTransform transform
The transform that should be applied to the image or gradient that's being drawn.
Constructor & Destructor Documentation
FillType::FillType () noexcept
Creates a default fill type, of solid black.
FillType::FillType (Colour colour) noexcept
Creates a fill type of a solid colour.
See Also
setColour
FillType::FillType (const ColourGradient & gradient)
Creates a gradient fill type.
See Also
setGradient
FillType::FillType (const Image & image, const AffineTransform & transform) noexcept
Creates a tiled image fill type.
The transform allows you to set the scaling, offset and rotation of the pattern.
See Also
setTiledImage
FillType::FillType (const FillType &)
Creates a copy of another FillType.
FillType::FillType (FillType &&) noexcept
Move constructor.
FillType::~FillType () noexcept
Destructor.
Member Function Documentation
FillType& FillType::operator= (const FillType &)
Makes a copy of another FillType.
FillType& FillType::operator= (FillType &&) noexcept
Move assignment operator.
bool FillType::isColour () const noexcept
Returns true if this is a solid colour fill, and not a gradient or image.
References Image::isNull().
bool FillType::isGradient () const noexcept
Returns true if this is a gradient fill.
bool FillType::isTiledImage () const noexcept
Returns true if this is a tiled image pattern fill.
References Image::isValid().
void FillType::setColour (Colour newColour) noexcept
Turns this object into a solid colour fill.
If the object was an image or gradient, those fields will no longer be valid.
void FillType::setGradient (const ColourGradient & newGradient)
Turns this object into a gradient fill.
void FillType::setTiledImage (const Image & image, const AffineTransform & transform) noexcept
Turns this object into a tiled image fill type.
The transform allows you to set the scaling, offset and rotation of the pattern.
void FillType::setOpacity (float newOpacity) noexcept
Changes the opacity that should be used.
If the fill is a solid colour, this just changes the opacity of that colour. For gradients and image tiles, it changes the opacity that will be used for them.
float FillType::getOpacity () const noexcept
Returns the current opacity to be applied to the colour, gradient, or image.
See Also
setOpacity
References Colour::getFloatAlpha().
bool FillType::isInvisible () const noexcept
Returns true if this fill type is completely transparent.
FillType FillType::transformed (const AffineTransform & transform) const
Returns a copy of this fill, adding the specified transform applied to the existing transform.
bool FillType::operator== (const FillType &) const
bool FillType::operator!= (const FillType &) const
Member Data Documentation
Colour FillType::colour
The solid colour being used.
If the fill type is not a solid colour, the alpha channel of this colour indicates the opacity that should be used for the fill, and the RGB channels are ignored.
ScopedPointer<ColourGradient> FillType::gradient
Returns the gradient that should be used for filling.
This will be zero if the object is some other type of fill. If a gradient is active, the overall opacity with which it should be applied is indicated by the alpha channel of the colour variable.
Image FillType::image
The image that should be used for tiling.
If an image fill is active, the overall opacity with which it should be applied is indicated by the alpha channel of the colour variable.
AffineTransform FillType::transform
The transform that should be applied to the image or gradient that's being drawn.
class PixelARGB
Represents a 32-bit INTERNAL pixel with premultiplied alpha, and can perform compositing operations with it.
This is used internally by the imaging classes.
See Also
PixelRGB
Public Types
enum { indexA = 3, indexR = 0, indexG = 1, indexB = 2 }
The indexes of the different components in the byte layout of this type of colour.
Public Member Functions
PixelARGB () noexcept
Creates a pixel without defining its colour.
~PixelARGB () noexcept
PixelARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
forcedinline uint32 getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format.
forcedinline uint32 getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
forcedinline uint32 getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
forcedinline uint32 getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
forcedinline uint8 getAlpha () const noexcept
forcedinline uint8 getRed () const noexcept
forcedinline uint8 getGreen () const noexcept
forcedinline uint8 getBlue () const noexcept
forcedinline uint8 & getAlpha () noexcept
forcedinline uint8 & getRed () noexcept
forcedinline uint8 & getGreen () noexcept
forcedinline uint8 & getBlue () noexcept
template<class Pixel >
forcedinline void set (const Pixel &src) noexcept
Copies another pixel colour over this one.
void setARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
Sets the pixel's colour from individual components.
template<class Pixel >
forcedinline void blend (const Pixel &src) noexcept
Blends another pixel onto this one.
forcedinline void blend (const PixelRGB src) noexcept
Blends another pixel onto this one.
template<class Pixel >
forcedinline void blend (const Pixel &src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
template<class Pixel >
forcedinline void tween (const Pixel &src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void setAlpha (const uint8 newAlpha) noexcept
Replaces the colour's alpha value with another one.
forcedinline void multiplyAlpha (int multiplier) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void multiplyAlpha (const float multiplier) noexcept
PixelARGB getUnpremultiplied () const noexcept
forcedinline void premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void desaturate () noexcept
Member Enumeration Documentation
anonymous enum
The indexes of the different components in the byte layout of this type of colour.
Enumerator
indexA
indexR
indexG
indexB
Constructor & Destructor Documentation
PixelARGB::PixelARGB () noexcept
Creates a pixel without defining its colour.
PixelARGB::~PixelARGB () noexcept
PixelARGB::PixelARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
Member Function Documentation
forcedinline uint32 PixelARGB::getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format.
forcedinline uint32 PixelARGB::getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 PixelARGB::getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
In other words, if the return-value is read as a uint8 array then the elements will be in the order of a, r, g, b
forcedinline uint32 PixelARGB::getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent.
forcedinline uint32 PixelARGB::getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent.
forcedinline uint8 PixelARGB::getAlpha () const noexcept
Referenced by Colour::getAlpha().
forcedinline uint8 PixelARGB::getRed () const noexcept
Referenced by Colour::getRed().
forcedinline uint8 PixelARGB::getGreen () const noexcept
Referenced by Colour::getGreen().
forcedinline uint8 PixelARGB::getBlue () const noexcept
Referenced by Colour::getBlue().
forcedinline uint8& PixelARGB::getAlpha () noexcept
forcedinline uint8& PixelARGB::getRed () noexcept
forcedinline uint8& PixelARGB::getGreen () noexcept
forcedinline uint8& PixelARGB::getBlue () noexcept
template<class Pixel > forcedinline void PixelARGB::set (const Pixel & src) noexcept
Copies another pixel colour over this one.
This doesn't blend it - this colour is simply replaced by the other one.
void PixelARGB::setARGB (const uint8 a, const uint8 r, const uint8 g, const uint8 b) noexcept
Sets the pixel's colour from individual components.
template<class Pixel > forcedinline void PixelARGB::blend (const Pixel & src) noexcept
Blends another pixel onto this one.
This takes into account the opacity of the pixel being overlaid, and blends it accordingly.
References clampPixelComponents(), and maskPixelComponents().
template<class Pixel > forcedinline void PixelARGB::blend (const Pixel & src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
The opacity of the pixel being overlaid is scaled by the extraAlpha factor before being used, so this can blend semi-transparently from a PixelRGB argument.
References clampPixelComponents(), and maskPixelComponents().
template<class Pixel > forcedinline void PixelARGB::tween (const Pixel & src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void PixelARGB::setAlpha (const uint8 newAlpha) noexcept
Replaces the colour's alpha value with another one.
forcedinline void PixelARGB::multiplyAlpha (int multiplier) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void PixelARGB::multiplyAlpha (const float multiplier) noexcept
PixelARGB PixelARGB::getUnpremultiplied () const noexcept
References unpremultiply().
forcedinline void PixelARGB::premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void PixelARGB::unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
References jmin().
Referenced by getUnpremultiplied().
forcedinline void PixelARGB::desaturate () noexcept
Member Data Documentation
uint32 PixelARGB::internal
Components PixelARGB::components
class PixelRGB
Represents a 24-bit RGB pixel, and can perform compositing operations on it.
This is used internally by the imaging classes.
See Also
PixelARGB
Public Types
enum { indexR = 0, indexG = 1, indexB = 2 }
The indexes of the different components in the byte layout of this type of colour.
Public Member Functions
PixelRGB () noexcept
Creates a pixel without defining its colour.
~PixelRGB () noexcept
forcedinline uint32 getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format which is compatible with the native format of a PixelARGB.
forcedinline uint32 getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
forcedinline uint32 getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
forcedinline uint32 getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
forcedinline uint8 getAlpha () const noexcept
forcedinline uint8 getRed () const noexcept
forcedinline uint8 getGreen () const noexcept
forcedinline uint8 getBlue () const noexcept
forcedinline uint8 & getRed () noexcept
forcedinline uint8 & getGreen () noexcept
forcedinline uint8 & getBlue () noexcept
template<class Pixel >
forcedinline void set (const Pixel &src) noexcept
Copies another pixel colour over this one.
void setARGB (const uint8, const uint8 red, const uint8 green, const uint8 blue) noexcept
Sets the pixel's colour from individual components.
template<class Pixel >
forcedinline void blend (const Pixel &src) noexcept
Blends another pixel onto this one.
forcedinline void blend (const PixelRGB src) noexcept
template<class Pixel >
forcedinline void blend (const Pixel &src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
template<class Pixel >
forcedinline void tween (const Pixel &src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void setAlpha (const uint8) noexcept
This method is included for compatibility with the PixelARGB class.
forcedinline void multiplyAlpha (int) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void multiplyAlpha (float) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void desaturate () noexcept
Member Enumeration Documentation
anonymous enum
The indexes of the different components in the byte layout of this type of colour.
Enumerator
indexR
indexG
indexB
Constructor & Destructor Documentation
PixelRGB::PixelRGB () noexcept
Creates a pixel without defining its colour.
PixelRGB::~PixelRGB () noexcept
Member Function Documentation
forcedinline uint32 PixelRGB::getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format which is compatible with the native format of a PixelARGB.
See Also
PixelARGB::getNativeARGB
forcedinline uint32 PixelRGB::getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 PixelRGB::getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
In other words, if the return-value is read as a uint8 array then the elements will be in the order of a, r, g, b
forcedinline uint32 PixelRGB::getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent but compatible with the return value of getEvenBytes of the PixelARGB class.
See Also
PixelARGB::getEvenBytes
forcedinline uint32 PixelRGB::getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent but compatible with the return value of getOddBytes of the PixelARGB class.
See Also
PixelARGB::getOddBytes
forcedinline uint8 PixelRGB::getAlpha () const noexcept
forcedinline uint8 PixelRGB::getRed () const noexcept
forcedinline uint8 PixelRGB::getGreen () const noexcept
forcedinline uint8 PixelRGB::getBlue () const noexcept
forcedinline uint8& PixelRGB::getRed () noexcept
forcedinline uint8& PixelRGB::getGreen () noexcept
forcedinline uint8& PixelRGB::getBlue () noexcept
template<class Pixel > forcedinline void PixelRGB::set (const Pixel & src) noexcept
Copies another pixel colour over this one.
This doesn't blend it - this colour is simply replaced by the other one. Because PixelRGB has no alpha channel, any alpha value in the source pixel is thrown away.
void PixelRGB::setARGB (const uint8 , const uint8 red, const uint8 green, const uint8 blue) noexcept
Sets the pixel's colour from individual components.
template<class Pixel > forcedinline void PixelRGB::blend (const Pixel & src) noexcept
Blends another pixel onto this one.
This takes into account the opacity of the pixel being overlaid, and blends it accordingly.
References clampPixelComponents(), and maskPixelComponents().
forcedinline void PixelRGB::blend (const PixelRGB src) noexcept
template<class Pixel > forcedinline void PixelRGB::blend (const Pixel & src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
The opacity of the pixel being overlaid is scaled by the extraAlpha factor before being used, so this can blend semi-transparently from a PixelRGB argument.
References clampPixelComponents(), and maskPixelComponents().
template<class Pixel > forcedinline void PixelRGB::tween (const Pixel & src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void PixelRGB::setAlpha (const uint8) noexcept
This method is included for compatibility with the PixelARGB class.
forcedinline void PixelRGB::multiplyAlpha (int) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void PixelRGB::multiplyAlpha (float) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void PixelRGB::premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void PixelRGB::unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void PixelRGB::desaturate () noexcept
class PixelAlpha
Represents an 8-bit single-channel pixel, and can perform compositing operations on it.
This is used internally by the imaging classes.
See Also
PixelARGB, PixelRGB
Public Types
enum { indexA = 0 }
The indexes of the different components in the byte layout of this type of colour.
Public Member Functions
PixelAlpha () noexcept
Creates a pixel without defining its colour.
~PixelAlpha () noexcept
forcedinline uint32 getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format which is compatible with the native format of a PixelARGB.
forcedinline uint32 getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
forcedinline uint32 getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
forcedinline uint32 getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
forcedinline uint8 getAlpha () const noexcept
forcedinline uint8 & getAlpha () noexcept
forcedinline uint8 getRed () const noexcept
forcedinline uint8 getGreen () const noexcept
forcedinline uint8 getBlue () const noexcept
template<class Pixel >
forcedinline void set (const Pixel &src) noexcept
Copies another pixel colour over this one.
forcedinline void setARGB (const uint8 a_, const uint8, const uint8, const uint8) noexcept
Sets the pixel's colour from individual components.
template<class Pixel >
forcedinline void blend (const Pixel &src) noexcept
Blends another pixel onto this one.
template<class Pixel >
forcedinline void blend (const Pixel &src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
template<class Pixel >
forcedinline void tween (const Pixel &src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void setAlpha (const uint8 newAlpha) noexcept
Replaces the colour's alpha value with another one.
forcedinline void multiplyAlpha (int multiplier) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void multiplyAlpha (const float multiplier) noexcept
forcedinline void premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void desaturate () noexcept
Member Enumeration Documentation
anonymous enum
The indexes of the different components in the byte layout of this type of colour.
Enumerator
indexA
Constructor & Destructor Documentation
PixelAlpha::PixelAlpha () noexcept
Creates a pixel without defining its colour.
PixelAlpha::~PixelAlpha () noexcept
Member Function Documentation
forcedinline uint32 PixelAlpha::getNativeARGB () const noexcept
Returns a uint32 which represents the pixel in a platform dependent format which is compatible with the native format of a PixelARGB.
See Also
PixelARGB::getNativeARGB
forcedinline uint32 PixelAlpha::getInARGBMaskOrder () const noexcept
Returns a uint32 which will be in argb order as if constructed with the following mask operation ((alpha << 24) | (red << 16) | (green << 8) | blue).
uint32 PixelAlpha::getInARGBMemoryOrder () const noexcept
Returns a uint32 which when written to memory, will be in the order a, r, g, b.
In other words, if the return-value is read as a uint8 array then the elements will be in the order of a, r, g, b
forcedinline uint32 PixelAlpha::getEvenBytes () const noexcept
Return channels with an even index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent but compatible with the return value of getEvenBytes of the PixelARGB class.
See Also
PixelARGB::getEvenBytes
forcedinline uint32 PixelAlpha::getOddBytes () const noexcept
Return channels with an odd index and insert zero bytes between them.
This is useful for blending operations. The exact channels which are returned is platform dependent but compatible with the return value of getOddBytes of the PixelARGB class.
See Also
PixelARGB::getOddBytes
forcedinline uint8 PixelAlpha::getAlpha () const noexcept
forcedinline uint8& PixelAlpha::getAlpha () noexcept
forcedinline uint8 PixelAlpha::getRed () const noexcept
forcedinline uint8 PixelAlpha::getGreen () const noexcept
forcedinline uint8 PixelAlpha::getBlue () const noexcept
template<class Pixel > forcedinline void PixelAlpha::set (const Pixel & src) noexcept
Copies another pixel colour over this one.
This doesn't blend it - this colour is simply replaced by the other one.
forcedinline void PixelAlpha::setARGB (const uint8 a_, const uint8 , const uint8 , const uint8) noexcept
Sets the pixel's colour from individual components.
template<class Pixel > forcedinline void PixelAlpha::blend (const Pixel & src) noexcept
Blends another pixel onto this one.
This takes into account the opacity of the pixel being overlaid, and blends it accordingly.
template<class Pixel > forcedinline void PixelAlpha::blend (const Pixel & src, uint32 extraAlpha) noexcept
Blends another pixel onto this one, applying an extra multiplier to its opacity.
The opacity of the pixel being overlaid is scaled by the extraAlpha factor before being used, so this can blend semi-transparently from a PixelRGB argument.
template<class Pixel > forcedinline void PixelAlpha::tween (const Pixel & src, const uint32 amount) noexcept
Blends another pixel with this one, creating a colour that is somewhere between the two, as specified by the amount.
forcedinline void PixelAlpha::setAlpha (const uint8 newAlpha) noexcept
Replaces the colour's alpha value with another one.
forcedinline void PixelAlpha::multiplyAlpha (int multiplier) noexcept
Multiplies the colour's alpha value with another one.
forcedinline void PixelAlpha::multiplyAlpha (const float multiplier) noexcept
forcedinline void PixelAlpha::premultiply () noexcept
Premultiplies the pixel's RGB values by its alpha.
forcedinline void PixelAlpha::unpremultiply () noexcept
Unpremultiplies the pixel's RGB values.
forcedinline void PixelAlpha::desaturate () noexcept
Function Documentation
uint32 maskPixelComponents (uint32 x) noexcept
Referenced by PixelARGB::blend(), PixelRGB::blend(), and clampPixelComponents().
uint32 clampPixelComponents (uint32 x) noexcept
References maskPixelComponents().
Referenced by PixelARGB::blend(), and PixelRGB::blend().
forcedinline void PixelARGB::blend (const PixelRGB src) noexcept
Blends another pixel onto this one.
This takes into account the opacity of the pixel being overlaid, and blends it accordingly.