JUCE: midi
midi
juce_audio_basics
Classes
class MidiBuffer
Holds a sequence of time-stamped midi events.
class MidiFile
Reads/writes standard midi format files.
class MidiKeyboardStateListener
Receives events from a MidiKeyboardState object.
class MidiKeyboardState
Represents a piano keyboard, keeping track of which keys are currently pressed.
class MidiMessage
Encapsulates a MIDI message.
class MidiMessageSequence
A sequence of timestamped midi messages.
struct MidiRPNMessage
Represents a MIDI RPN (registered parameter number) or NRPN (non-registered parameter number) message.
class MidiRPNDetector
Parses a stream of MIDI data to assemble RPN and NRPN messages from their constituent MIDI CC messages.
class MidiRPNGenerator
Generates an appropriate sequence of MIDI CC messages to represent an RPN or NRPN message.
Detailed Description
Class Documentation
class MidiBuffer
Holds a sequence of time-stamped midi events.
Analogous to the AudioSampleBuffer, this holds a set of midi events with integer time-stamps. The buffer is kept sorted in order of the time-stamps.
If you're working with a sequence of midi events that may need to be manipulated or read/written to a midi file, then MidiMessageSequence is probably a more appropriate container. MidiBuffer is designed for lower-level streams of raw midi data.
See Also
MidiMessage
Public Member Functions
MidiBuffer () noexcept
Creates an empty MidiBuffer.
MidiBuffer (const MidiMessage &message) noexcept
Creates a MidiBuffer containing a single midi message.
MidiBuffer (const MidiBuffer &) noexcept
Creates a copy of another MidiBuffer.
MidiBuffer & operator= (const MidiBuffer &) noexcept
Makes a copy of another MidiBuffer.
~MidiBuffer ()
Destructor.
void clear () noexcept
Removes all events from the buffer.
void clear (int start, int numSamples)
Removes all events between two times from the buffer.
bool isEmpty () const noexcept
Returns true if the buffer is empty.
int getNumEvents () const noexcept
Counts the number of events in the buffer.
void addEvent (const MidiMessage &midiMessage, int sampleNumber)
Adds an event to the buffer.
void addEvent (const void *rawMidiData, int maxBytesOfMidiData, int sampleNumber)
Adds an event to the buffer from raw midi data.
void addEvents (const MidiBuffer &otherBuffer, int startSample, int numSamples, int sampleDeltaToAdd)
Adds some events from another buffer to this one.
int getFirstEventTime () const noexcept
Returns the sample number of the first event in the buffer.
int getLastEventTime () const noexcept
Returns the sample number of the last event in the buffer.
void swapWith (MidiBuffer &) noexcept
Exchanges the contents of this buffer with another one.
void ensureSize (size_t minimumNumBytes)
Preallocates some memory for the buffer to use.
Public Attributes
Array< uint8 > data
The raw data holding this buffer.
Constructor & Destructor Documentation
MidiBuffer::MidiBuffer () noexcept
Creates an empty MidiBuffer.
MidiBuffer::MidiBuffer (const MidiMessage & message) explicit noexcept
Creates a MidiBuffer containing a single midi message.
MidiBuffer::MidiBuffer (const MidiBuffer &) noexcept
Creates a copy of another MidiBuffer.
MidiBuffer::~MidiBuffer ()
Destructor.
Member Function Documentation
MidiBuffer& MidiBuffer::operator= (const MidiBuffer &) noexcept
Makes a copy of another MidiBuffer.
void MidiBuffer::clear () noexcept
Removes all events from the buffer.
void MidiBuffer::clear (int start, int numSamples)
Removes all events between two times from the buffer.
All events for which (start <= event position < start + numSamples) will be removed.
bool MidiBuffer::isEmpty () const noexcept
Returns true if the buffer is empty.
To actually retrieve the events, use a MidiBuffer::Iterator object
int MidiBuffer::getNumEvents () const noexcept
Counts the number of events in the buffer.
This is actually quite a slow operation, as it has to iterate through all the events, so you might prefer to call isEmpty() if that's all you need to know.
void MidiBuffer::addEvent (const MidiMessage & midiMessage, int sampleNumber)
Adds an event to the buffer.
The sample number will be used to determine the position of the event in the buffer, which is always kept sorted. The MidiMessage's timestamp is ignored.
If an event is added whose sample position is the same as one or more events already in the buffer, the new event will be placed after the existing ones.
To retrieve events, use a MidiBuffer::Iterator object
Referenced by MidiEventList::toMidiBuffer().
void MidiBuffer::addEvent (const void * rawMidiData, int maxBytesOfMidiData, int sampleNumber)
Adds an event to the buffer from raw midi data.
The sample number will be used to determine the position of the event in the buffer, which is always kept sorted.
If an event is added whose sample position is the same as one or more events already in the buffer, the new event will be placed after the existing ones.
The event data will be inspected to calculate the number of bytes in length that the midi event really takes up, so maxBytesOfMidiData may be longer than the data that actually gets stored. E.g. if you pass in a note-on and a length of 4 bytes, it'll actually only store 3 bytes. If the midi data is invalid, it might not add an event at all.
To retrieve events, use a MidiBuffer::Iterator object
void MidiBuffer::addEvents (const MidiBuffer & otherBuffer, int startSample, int numSamples, int sampleDeltaToAdd)
Adds some events from another buffer to this one.
Parameters
otherBuffer the buffer containing the events you want to add
startSample the lowest sample number in the source buffer for which events should be added. Any source events whose timestamp is less than this will be ignored
numSamples the valid range of samples from the source buffer for which events should be added - i.e. events in the source buffer whose timestamp is greater than or equal to (startSample + numSamples) will be ignored. If this value is less than 0, all events after startSample will be taken.
sampleDeltaToAdd a value which will be added to the source timestamps of the events that are added to this buffer
int MidiBuffer::getFirstEventTime () const noexcept
Returns the sample number of the first event in the buffer.
If the buffer's empty, this will just return 0.
int MidiBuffer::getLastEventTime () const noexcept
Returns the sample number of the last event in the buffer.
If the buffer's empty, this will just return 0.
void MidiBuffer::swapWith (MidiBuffer &) noexcept
Exchanges the contents of this buffer with another one.
This is a quick operation, because no memory allocating or copying is done, it just swaps the internal state of the two buffers.
void MidiBuffer::ensureSize (size_t minimumNumBytes)
Preallocates some memory for the buffer to use.
This helps to avoid needing to reallocate space when the buffer has messages added to it.
Member Data Documentation
Array<uint8> MidiBuffer::data
The raw data holding this buffer.
Obviously access to this data is provided at your own risk. Its internal format could change in future, so don't write code that relies on it!
class MidiFile
Reads/writes standard midi format files.
To read a midi file, create a MidiFile object and call its readFrom() method. You can then get the individual midi tracks from it using the getTrack() method.
To write a file, create a MidiFile object, add some MidiMessageSequence objects to it using the addTrack() method, and then call its writeTo() method to stream it out.
See Also
MidiMessageSequence
Public Member Functions
MidiFile ()
Creates an empty MidiFile object.
~MidiFile ()
Destructor.
MidiFile (const MidiFile &other)
Creates a copy of another MidiFile.
MidiFile & operator= (const MidiFile &other)
Copies from another MidiFile object.
int getNumTracks () const noexcept
Returns the number of tracks in the file.
const MidiMessageSequence * getTrack (int index) const noexcept
Returns a pointer to one of the tracks in the file.
void addTrack (const MidiMessageSequence &trackSequence)
Adds a midi track to the file.
void clear ()
Removes all midi tracks from the file.
short getTimeFormat () const noexcept
Returns the raw time format code that will be written to a stream.
void setTicksPerQuarterNote (int ticksPerQuarterNote) noexcept
Sets the time format to use when this file is written to a stream.
void setSmpteTimeFormat (int framesPerSecond, int subframeResolution) noexcept
Sets the time format to use when this file is written to a stream.
void findAllTempoEvents (MidiMessageSequence &tempoChangeEvents) const
Makes a list of all the tempo-change meta-events from all tracks in the midi file.
void findAllTimeSigEvents (MidiMessageSequence &timeSigEvents) const
Makes a list of all the time-signature meta-events from all tracks in the midi file.
void findAllKeySigEvents (MidiMessageSequence &keySigEvents) const
Makes a list of all the time-signature meta-events from all tracks in the midi file.
double getLastTimestamp () const
Returns the latest timestamp in any of the tracks.
bool readFrom (InputStream &sourceStream)
Reads a midi file format stream.
bool writeTo (OutputStream &destStream, int midiFileType=1)
Writes the midi tracks as a standard midi file.
void convertTimestampTicksToSeconds ()
Converts the timestamp of all the midi events from midi ticks to seconds.
Constructor & Destructor Documentation
MidiFile::MidiFile ()
Creates an empty MidiFile object.
MidiFile::~MidiFile ()
Destructor.
MidiFile::MidiFile (const MidiFile & other)
Creates a copy of another MidiFile.
Member Function Documentation
MidiFile& MidiFile::operator= (const MidiFile & other)
Copies from another MidiFile object.
int MidiFile::getNumTracks () const noexcept
Returns the number of tracks in the file.
See Also
getTrack, addTrack
const MidiMessageSequence* MidiFile::getTrack (int index) const noexcept
Returns a pointer to one of the tracks in the file.
Returns
a pointer to the track, or nullptr if the index is out-of-range
See Also
getNumTracks, addTrack
void MidiFile::addTrack (const MidiMessageSequence & trackSequence)
Adds a midi track to the file.
This will make its own internal copy of the sequence that is passed-in.
See Also
getNumTracks, getTrack
void MidiFile::clear ()
Removes all midi tracks from the file.
See Also
getNumTracks
short MidiFile::getTimeFormat () const noexcept
Returns the raw time format code that will be written to a stream.
After reading a midi file, this method will return the time-format that was read from the file's header. It can be changed using the setTicksPerQuarterNote() or setSmpteTimeFormat() methods.
If the value returned is positive, it indicates the number of midi ticks per quarter-note - see setTicksPerQuarterNote().
It it's negative, the upper byte indicates the frames-per-second (but negative), and the lower byte is the number of ticks per frame - see setSmpteTimeFormat().
void MidiFile::setTicksPerQuarterNote (int ticksPerQuarterNote) noexcept
Sets the time format to use when this file is written to a stream.
If this is called, the file will be written as bars/beats using the specified resolution, rather than SMPTE absolute times, as would be used if setSmpteTimeFormat() had been called instead.
Parameters
ticksPerQuarterNote e.g. 96, 960
See Also
setSmpteTimeFormat
void MidiFile::setSmpteTimeFormat (int framesPerSecond, int subframeResolution) noexcept
Sets the time format to use when this file is written to a stream.
If this is called, the file will be written using absolute times, rather than bars/beats as would be the case if setTicksPerBeat() had been called instead.
Parameters
framesPerSecond must be 24, 25, 29 or 30
subframeResolution the sub-second resolution, e.g. 4 (midi time code), 8, 10, 80 (SMPTE bit resolution), or 100. For millisecond timing, setSmpteTimeFormat (25, 40)
See Also
setTicksPerBeat
void MidiFile::findAllTempoEvents (MidiMessageSequence & tempoChangeEvents) const
Makes a list of all the tempo-change meta-events from all tracks in the midi file.
Useful for finding the positions of all the tempo changes in a file.
Parameters
tempoChangeEvents a list to which all the events will be added
void MidiFile::findAllTimeSigEvents (MidiMessageSequence & timeSigEvents) const
Makes a list of all the time-signature meta-events from all tracks in the midi file.
Useful for finding the positions of all the tempo changes in a file.
Parameters
timeSigEvents a list to which all the events will be added
void MidiFile::findAllKeySigEvents (MidiMessageSequence & keySigEvents) const
Makes a list of all the time-signature meta-events from all tracks in the midi file.
Parameters
keySigEvents a list to which all the events will be added
double MidiFile::getLastTimestamp () const
Returns the latest timestamp in any of the tracks.
(Useful for finding the length of the file).
bool MidiFile::readFrom (InputStream & sourceStream)
Reads a midi file format stream.
After calling this, you can get the tracks that were read from the file by using the getNumTracks() and getTrack() methods.
The timestamps of the midi events in the tracks will represent their positions in terms of midi ticks. To convert them to seconds, use the convertTimestampTicksToSeconds() method.
Returns
true if the stream was read successfully
bool MidiFile::writeTo (OutputStream & destStream, int midiFileType = 1)
Writes the midi tracks as a standard midi file.
The midiFileType value is written as the file's format type, which can be 0, 1 or 2 - see the midi file spec for more info about that.
Returns
true if the operation succeeded.
void MidiFile::convertTimestampTicksToSeconds ()
Converts the timestamp of all the midi events from midi ticks to seconds.
This will use the midi time format and tempo/time signature info in the tracks to convert all the timestamps to absolute values in seconds.
class MidiKeyboardStateListener
Receives events from a MidiKeyboardState object.
See Also
MidiKeyboardState
Public Member Functions
MidiKeyboardStateListener () noexcept
virtual ~MidiKeyboardStateListener ()
virtual void handleNoteOn (MidiKeyboardState *source, int midiChannel, int midiNoteNumber, float velocity)=0
Called when one of the MidiKeyboardState's keys is pressed.
virtual void handleNoteOff (MidiKeyboardState *source, int midiChannel, int midiNoteNumber, float velocity)=0
Called when one of the MidiKeyboardState's keys is released.
Constructor & Destructor Documentation
MidiKeyboardStateListener::MidiKeyboardStateListener () noexcept
virtual MidiKeyboardStateListener::~MidiKeyboardStateListener () virtual
Member Function Documentation
virtual void MidiKeyboardStateListener::handleNoteOn (MidiKeyboardState * source, int midiChannel, int midiNoteNumber, float velocity) pure virtual
Called when one of the MidiKeyboardState's keys is pressed.
This will be called synchronously when the state is either processing a buffer in its MidiKeyboardState::processNextMidiBuffer() method, or when a note is being played with its MidiKeyboardState::noteOn() method.
Note that this callback could happen from an audio callback thread, so be careful not to block, and avoid any UI activity in the callback.
Implemented in MidiKeyboardComponent, and MidiMessageCollector.
virtual void MidiKeyboardStateListener::handleNoteOff (MidiKeyboardState * source, int midiChannel, int midiNoteNumber, float velocity) pure virtual
Called when one of the MidiKeyboardState's keys is released.
This will be called synchronously when the state is either processing a buffer in its MidiKeyboardState::processNextMidiBuffer() method, or when a note is being played with its MidiKeyboardState::noteOff() method.
Note that this callback could happen from an audio callback thread, so be careful not to block, and avoid any UI activity in the callback.
Implemented in MidiKeyboardComponent, and MidiMessageCollector.
class MidiKeyboardState
Represents a piano keyboard, keeping track of which keys are currently pressed.
This object can parse a stream of midi events, using them to update its idea of which keys are pressed for each individiual midi channel.
When keys go up or down, it can broadcast these events to listener objects.
It also allows key up/down events to be triggered with its noteOn() and noteOff() methods, and midi messages for these events will be merged into the midi stream that gets processed by processNextMidiBuffer().
Public Member Functions
MidiKeyboardState ()
~MidiKeyboardState ()
void reset ()
Resets the state of the object.
bool isNoteOn (int midiChannel, int midiNoteNumber) const noexcept
Returns true if the given midi key is currently held down for the given midi channel.
bool isNoteOnForChannels (int midiChannelMask, int midiNoteNumber) const noexcept
Returns true if the given midi key is currently held down on any of a set of midi channels.
void noteOn (int midiChannel, int midiNoteNumber, float velocity)
Turns a specified note on.
void noteOff (int midiChannel, int midiNoteNumber, float velocity)
Turns a specified note off.
void allNotesOff (int midiChannel)
This will turn off any currently-down notes for the given midi channel.
void processNextMidiEvent (const MidiMessage &message)
Looks at a key-up/down event and uses it to update the state of this object.
void processNextMidiBuffer (MidiBuffer &buffer, int startSample, int numSamples, bool injectIndirectEvents)
Scans a midi stream for up/down events and adds its own events to it.
void addListener (MidiKeyboardStateListener *listener)
Registers a listener for callbacks when keys go up or down.
void removeListener (MidiKeyboardStateListener *listener)
Deregisters a listener.
Constructor & Destructor Documentation
MidiKeyboardState::MidiKeyboardState ()
MidiKeyboardState::~MidiKeyboardState ()
Member Function Documentation
void MidiKeyboardState::reset ()
Resets the state of the object.
All internal data for all the channels is reset, but no events are sent as a result.
If you want to release any keys that are currently down, and to send out note-up midi messages for this, use the allNotesOff() method instead.
bool MidiKeyboardState::isNoteOn (int midiChannel, int midiNoteNumber) const noexcept
Returns true if the given midi key is currently held down for the given midi channel.
The channel number must be between 1 and 16. If you want to see if any notes are on for a range of channels, use the isNoteOnForChannels() method.
bool MidiKeyboardState::isNoteOnForChannels (int midiChannelMask, int midiNoteNumber) const noexcept
Returns true if the given midi key is currently held down on any of a set of midi channels.
The channel mask has a bit set for each midi channel you want to test for - bit 0 = midi channel 1, bit 1 = midi channel 2, etc.
If a note is on for at least one of the specified channels, this returns true.
void MidiKeyboardState::noteOn (int midiChannel, int midiNoteNumber, float velocity)
Turns a specified note on.
This will cause a suitable midi note-on event to be injected into the midi buffer during the next call to processNextMidiBuffer().
It will also trigger a synchronous callback to the listeners to tell them that the key has gone down.
void MidiKeyboardState::noteOff (int midiChannel, int midiNoteNumber, float velocity)
Turns a specified note off.
This will cause a suitable midi note-off event to be injected into the midi buffer during the next call to processNextMidiBuffer().
It will also trigger a synchronous callback to the listeners to tell them that the key has gone up.
But if the note isn't acutally down for the given channel, this method will in fact do nothing.
void MidiKeyboardState::allNotesOff (int midiChannel)
This will turn off any currently-down notes for the given midi channel.
If you pass 0 for the midi channel, it will in fact turn off all notes on all channels.
Calling this method will make calls to noteOff(), so can trigger synchronous callbacks and events being added to the midi stream.
void MidiKeyboardState::processNextMidiEvent (const MidiMessage & message)
Looks at a key-up/down event and uses it to update the state of this object.
To process a buffer full of midi messages, use the processNextMidiBuffer() method instead.
void MidiKeyboardState::processNextMidiBuffer (MidiBuffer & buffer, int startSample, int numSamples, bool injectIndirectEvents)
Scans a midi stream for up/down events and adds its own events to it.
This will look for any up/down events and use them to update the internal state, synchronously making suitable callbacks to the listeners.
If injectIndirectEvents is true, then midi events to produce the recent noteOn() and noteOff() calls will be added into the buffer.
Only the section of the buffer whose timestamps are between startSample and (startSample + numSamples) will be affected, and any events added will be placed between these times.
If you're going to use this method, you'll need to keep calling it regularly for it to work satisfactorily.
To process a single midi event at a time, use the processNextMidiEvent() method instead.
void MidiKeyboardState::addListener (MidiKeyboardStateListener * listener)
Registers a listener for callbacks when keys go up or down.
See Also
removeListener
void MidiKeyboardState::removeListener (MidiKeyboardStateListener * listener)
Deregisters a listener.
See Also
addListener
class MidiMessage
Encapsulates a MIDI message.
See Also
MidiMessageSequence, MidiOutput, MidiInput
Public Types
enum SmpteTimecodeType { fps24 = 0, fps25 = 1, fps30drop = 2, fps30 = 3 }
SMPTE timecode types.
enum MidiMachineControlCommand {
mmc_stop = 1, mmc_play = 2, mmc_deferredplay = 3, mmc_fastforward = 4,
mmc_rewind = 5, mmc_recordStart = 6, mmc_recordStop = 7, mmc_pause = 9
}
Types of MMC command.
Public Member Functions
MidiMessage (int byte1, int byte2, int byte3, double timeStamp=0) noexcept
Creates a 3-byte short midi message.
MidiMessage (int byte1, int byte2, double timeStamp=0) noexcept
Creates a 2-byte short midi message.
MidiMessage (int byte1, double timeStamp=0) noexcept
Creates a 1-byte short midi message.
template<typename... Data>
MidiMessage (int byte1, int byte2, int byte3, Data...otherBytes)
Creates a midi message from a list of bytes.
MidiMessage (const void *data, int numBytes, double timeStamp=0)
Creates a midi message from a block of data.
MidiMessage (const void *data, int maxBytesToUse, int &numBytesUsed, uint8 lastStatusByte, double timeStamp=0, bool sysexHasEmbeddedLength=true)
Reads the next midi message from some data.
MidiMessage () noexcept
Creates an active-sense message.
MidiMessage (const MidiMessage &)
Creates a copy of another midi message.
MidiMessage (const MidiMessage &, double newTimeStamp)
Creates a copy of another midi message, with a different timestamp.
~MidiMessage () noexcept
Destructor.
MidiMessage & operator= (const MidiMessage &other)
Copies this message from another one.
MidiMessage (MidiMessage &&) noexcept
Move constructor.
MidiMessage & operator= (MidiMessage &&) noexcept
Move assignment operator.
const uint8 * getRawData () const noexcept
Returns a pointer to the raw midi data.
int getRawDataSize () const noexcept
Returns the number of bytes of data in the message.
String getDescription () const
Returns a human-readable description of the midi message as a string, for example "Note On C#3 Velocity 120 Channel 1".
double getTimeStamp () const noexcept
Returns the timestamp associated with this message.
void setTimeStamp (double newTimestamp) noexcept
Changes the message's associated timestamp.
void addToTimeStamp (double delta) noexcept
Adds a value to the message's timestamp.
int getChannel () const noexcept
Returns the midi channel associated with the message.
bool isForChannel (int channelNumber) const noexcept
Returns true if the message applies to the given midi channel.
void setChannel (int newChannelNumber) noexcept
Changes the message's midi channel.
bool isSysEx () const noexcept
Returns true if this is a system-exclusive message.
const uint8 * getSysExData () const noexcept
Returns a pointer to the sysex data inside the message.
int getSysExDataSize () const noexcept
Returns the size of the sysex data.
bool isNoteOn (bool returnTrueForVelocity0=false) const noexcept
Returns true if this message is a 'key-down' event.
bool isNoteOff (bool returnTrueForNoteOnVelocity0=true) const noexcept
Returns true if this message is a 'key-up' event.
bool isNoteOnOrOff () const noexcept
Returns true if this message is a 'key-down' or 'key-up' event.
int getNoteNumber () const noexcept
Returns the midi note number for note-on and note-off messages.
void setNoteNumber (int newNoteNumber) noexcept
Changes the midi note number of a note-on or note-off message.
uint8 getVelocity () const noexcept
Returns the velocity of a note-on or note-off message.
float getFloatVelocity () const noexcept
Returns the velocity of a note-on or note-off message.
void setVelocity (float newVelocity) noexcept
Changes the velocity of a note-on or note-off message.
void multiplyVelocity (float scaleFactor) noexcept
Multiplies the velocity of a note-on or note-off message by a given amount.
bool isSustainPedalOn () const noexcept
Returns true if this message is a 'sustain pedal down' controller message.
bool isSustainPedalOff () const noexcept
Returns true if this message is a 'sustain pedal up' controller message.
bool isSostenutoPedalOn () const noexcept
Returns true if this message is a 'sostenuto pedal down' controller message.
bool isSostenutoPedalOff () const noexcept
Returns true if this message is a 'sostenuto pedal up' controller message.
bool isSoftPedalOn () const noexcept
Returns true if this message is a 'soft pedal down' controller message.
bool isSoftPedalOff () const noexcept
Returns true if this message is a 'soft pedal up' controller message.
bool isProgramChange () const noexcept
Returns true if the message is a program (patch) change message.
int getProgramChangeNumber () const noexcept
Returns the new program number of a program change message.
bool isPitchWheel () const noexcept
Returns true if the message is a pitch-wheel move.
int getPitchWheelValue () const noexcept
Returns the pitch wheel position from a pitch-wheel move message.
bool isAftertouch () const noexcept
Returns true if the message is an aftertouch event.
int getAfterTouchValue () const noexcept
Returns the amount of aftertouch from an aftertouch messages.
bool isChannelPressure () const noexcept
Returns true if the message is a channel-pressure change event.
int getChannelPressureValue () const noexcept
Returns the pressure from a channel pressure change message.
bool isController () const noexcept
Returns true if this is a midi controller message.
int getControllerNumber () const noexcept
Returns the controller number of a controller message.
int getControllerValue () const noexcept
Returns the controller value from a controller message.
bool isControllerOfType (int controllerType) const noexcept
Returns true if this message is a controller message and if it has the specified controller type.
bool isAllNotesOff () const noexcept
Checks whether this message is an all-notes-off message.
bool isAllSoundOff () const noexcept
Checks whether this message is an all-sound-off message.
bool isMetaEvent () const noexcept
Returns true if this event is a meta-event.
int getMetaEventType () const noexcept
Returns a meta-event's type number.
const uint8 * getMetaEventData () const noexcept
Returns a pointer to the data in a meta-event.
int getMetaEventLength () const noexcept
Returns the length of the data for a meta-event.
bool isTrackMetaEvent () const noexcept
Returns true if this is a 'track' meta-event.
bool isEndOfTrackMetaEvent () const noexcept
Returns true if this is an 'end-of-track' meta-event.
bool isTrackNameEvent () const noexcept
Returns true if this is an 'track name' meta-event.
bool isTextMetaEvent () const noexcept
Returns true if this is a 'text' meta-event.
String getTextFromTextMetaEvent () const
Returns the text from a text meta-event.
bool isTempoMetaEvent () const noexcept
Returns true if this is a 'tempo' meta-event.
double getTempoMetaEventTickLength (short timeFormat) const noexcept
Returns the tick length from a tempo meta-event.
double getTempoSecondsPerQuarterNote () const noexcept
Calculates the seconds-per-quarter-note from a tempo meta-event.
bool isTimeSignatureMetaEvent () const noexcept
Returns true if this is a 'time-signature' meta-event.
void getTimeSignatureInfo (int &numerator, int &denominator) const noexcept
Returns the time-signature values from a time-signature meta-event.
bool isKeySignatureMetaEvent () const noexcept
Returns true if this is a 'key-signature' meta-event.
int getKeySignatureNumberOfSharpsOrFlats () const noexcept
Returns the key from a key-signature meta-event.
bool isKeySignatureMajorKey () const noexcept
Returns true if this key-signature event is major, or false if it's minor.
bool isMidiChannelMetaEvent () const noexcept
Returns true if this is a 'channel' meta-event.
int getMidiChannelMetaEventChannel () const noexcept
Returns the channel number from a channel meta-event.
bool isActiveSense () const noexcept
Returns true if this is an active-sense message.
bool isMidiStart () const noexcept
Returns true if this is a midi start event.
bool isMidiContinue () const noexcept
Returns true if this is a midi continue event.
bool isMidiStop () const noexcept
Returns true if this is a midi stop event.
bool isMidiClock () const noexcept
Returns true if this is a midi clock event.
bool isSongPositionPointer () const noexcept
Returns true if this is a song-position-pointer message.
int getSongPositionPointerMidiBeat () const noexcept
Returns the midi beat-number of a song-position-pointer message.
bool isQuarterFrame () const noexcept
Returns true if this is a quarter-frame midi timecode message.
int getQuarterFrameSequenceNumber () const noexcept
Returns the sequence number of a quarter-frame midi timecode message.
int getQuarterFrameValue () const noexcept
Returns the value from a quarter-frame message.
bool isFullFrame () const noexcept
Returns true if this is a full-frame midi timecode message.
void getFullFrameParameters (int &hours, int &minutes, int &seconds, int &frames, SmpteTimecodeType &timecodeType) const noexcept
Extracts the timecode information from a full-frame midi timecode message.
bool isMidiMachineControlMessage () const noexcept
Checks whether this is an MMC message.
MidiMachineControlCommand getMidiMachineControlCommand () const noexcept
For an MMC message, this returns its type.
bool isMidiMachineControlGoto (int &hours, int &minutes, int &seconds, int &frames) const noexcept
Checks whether this is an MMC "goto" message.
Static Public Member Functions
static MidiMessage noteOn (int channel, int noteNumber, float velocity) noexcept
Creates a key-down message (using a floating-point velocity).
static MidiMessage noteOn (int channel, int noteNumber, uint8 velocity) noexcept
Creates a key-down message (using an integer velocity).
static MidiMessage noteOff (int channel, int noteNumber, float velocity) noexcept
Creates a key-up message.
static MidiMessage noteOff (int channel, int noteNumber, uint8 velocity) noexcept
Creates a key-up message.
static MidiMessage noteOff (int channel, int noteNumber) noexcept
Creates a key-up message.
static MidiMessage programChange (int channel, int programNumber) noexcept
Creates a program-change message.
static MidiMessage pitchWheel (int channel, int position) noexcept
Creates a pitch-wheel move message.
static MidiMessage aftertouchChange (int channel, int noteNumber, int aftertouchAmount) noexcept
Creates an aftertouch message.
static MidiMessage channelPressureChange (int channel, int pressure) noexcept
Creates a channel-pressure change event.
static MidiMessage controllerEvent (int channel, int controllerType, int value) noexcept
Creates a controller message.
static MidiMessage allNotesOff (int channel) noexcept
Creates an all-notes-off message.
static MidiMessage allSoundOff (int channel) noexcept
Creates an all-sound-off message.
static MidiMessage allControllersOff (int channel) noexcept
Creates an all-controllers-off message.
static MidiMessage endOfTrack () noexcept
Creates an end-of-track meta-event.
static MidiMessage textMetaEvent (int type, StringRef text)
Creates a text meta-event.
static MidiMessage tempoMetaEvent (int microsecondsPerQuarterNote) noexcept
Creates a tempo meta-event.
static MidiMessage timeSignatureMetaEvent (int numerator, int denominator)
Creates a time-signature meta-event.
static MidiMessage keySignatureMetaEvent (int numberOfSharpsOrFlats, bool isMinorKey)
Creates a key-signature meta-event.
static MidiMessage midiChannelMetaEvent (int channel) noexcept
Creates a midi channel meta-event.
static MidiMessage midiStart () noexcept
Creates a midi start event.
static MidiMessage midiContinue () noexcept
Creates a midi continue event.
static MidiMessage midiStop () noexcept
Creates a midi stop event.
static MidiMessage midiClock () noexcept
Creates a midi clock event.
static MidiMessage songPositionPointer (int positionInMidiBeats) noexcept
Creates a song-position-pointer message.
static MidiMessage quarterFrame (int sequenceNumber, int value) noexcept
Creates a quarter-frame MTC message.
static MidiMessage fullFrame (int hours, int minutes, int seconds, int frames, SmpteTimecodeType timecodeType)
Creates a full-frame MTC message.
static MidiMessage midiMachineControlCommand (MidiMachineControlCommand command)
Creates an MMC message.
static MidiMessage midiMachineControlGoto (int hours, int minutes, int seconds, int frames)
Creates an MMC "goto" message.
static MidiMessage masterVolume (float volume)
Creates a master-volume change message.
static MidiMessage createSysExMessage (const void *sysexData, int dataSize)
Creates a system-exclusive message.
static int readVariableLengthVal (const uint8 *data, int &numBytesUsed) noexcept
Reads a midi variable-length integer.
static int getMessageLengthFromFirstByte (uint8 firstByte) noexcept
Based on the first byte of a short midi message, this uses a lookup table to return the message length (either 1, 2, or 3 bytes).
static String getMidiNoteName (int noteNumber, bool useSharps, bool includeOctaveNumber, int octaveNumForMiddleC)
Returns the name of a midi note number.
static double getMidiNoteInHertz (int noteNumber, double frequencyOfA=440.0) noexcept
Returns the frequency of a midi note number.
static bool isMidiNoteBlack (int noteNumber) noexcept
Returns true if the given midi note number is a black key.
static const char * getGMInstrumentName (int midiInstrumentNumber)
Returns the standard name of a GM instrument, or nullptr if unknown for this index.
static const char * getGMInstrumentBankName (int midiBankNumber)
Returns the name of a bank of GM instruments, or nullptr if unknown for this bank number.
static const char * getRhythmInstrumentName (int midiNoteNumber)
Returns the standard name of a channel 10 percussion sound, or nullptr if unknown for this note number.
static const char * getControllerName (int controllerNumber)
Returns the name of a controller type number, or nullptr if unknown for this controller number.
static uint8 floatValueToMidiByte (float valueBetween0and1) noexcept
Converts a floating-point value between 0 and 1 to a MIDI 7-bit value between 0 and 127.
static uint16 pitchbendToPitchwheelPos (float pitchbendInSemitones, float pitchbendRangeInSemitones) noexcept
Converts a pitchbend value in semitones to a MIDI 14-bit pitchwheel position value.
Member Enumeration Documentation
enum MidiMessage::SmpteTimecodeType
SMPTE timecode types.
Used by the getFullFrameParameters() and fullFrame() methods.
Enumerator
fps24
fps25
fps30drop
fps30
enum MidiMessage::MidiMachineControlCommand
Types of MMC command.
See Also
isMidiMachineControlMessage, getMidiMachineControlCommand, midiMachineControlCommand
Enumerator
mmc_stop
mmc_play
mmc_deferredplay
mmc_fastforward
mmc_rewind
mmc_recordStart
mmc_recordStop
mmc_pause
Constructor & Destructor Documentation
MidiMessage::MidiMessage (int byte1, int byte2, int byte3, double timeStamp = 0) noexcept
Creates a 3-byte short midi message.
Parameters
byte1 message byte 1
byte2 message byte 2
byte3 message byte 3
timeStamp the time to give the midi message - this value doesn't use any particular units, so will be application-specific
MidiMessage::MidiMessage (int byte1, int byte2, double timeStamp = 0) noexcept
Creates a 2-byte short midi message.
Parameters
byte1 message byte 1
byte2 message byte 2
timeStamp the time to give the midi message - this value doesn't use any particular units, so will be application-specific
MidiMessage::MidiMessage (int byte1, double timeStamp = 0) noexcept
Creates a 1-byte short midi message.
Parameters
byte1 message byte 1
timeStamp the time to give the midi message - this value doesn't use any particular units, so will be application-specific
template<typename... Data> MidiMessage::MidiMessage (int byte1, int byte2, int byte3, Data... otherBytes)
Creates a midi message from a list of bytes.
References jassert.
MidiMessage::MidiMessage (const void * data, int numBytes, double timeStamp = 0)
Creates a midi message from a block of data.
MidiMessage::MidiMessage (const void * data, int maxBytesToUse, int & numBytesUsed, uint8 lastStatusByte, double timeStamp = 0, bool sysexHasEmbeddedLength = true)
Reads the next midi message from some data.
This will read as many bytes from a data stream as it needs to make a complete message, and will return the number of bytes it used. This lets you read a sequence of midi messages from a file or stream.
Parameters
data the data to read from
maxBytesToUse the maximum number of bytes it's allowed to read
numBytesUsed returns the number of bytes that were actually needed
lastStatusByte in a sequence of midi messages, the initial byte can be dropped from a message if it's the same as the first byte of the previous message, so this lets you supply the byte to use if the first byte of the message has in fact been dropped.
timeStamp the time to give the midi message - this value doesn't use any particular units, so will be application-specific
sysexHasEmbeddedLength when reading sysexes, this flag indicates whether to expect the data to begin with a variable-length field indicating its size
MidiMessage::MidiMessage () noexcept
Creates an active-sense message.
Since the MidiMessage has to contain a valid message, this default constructor just initialises it with an empty sysex message.
MidiMessage::MidiMessage (const MidiMessage &)
Creates a copy of another midi message.
MidiMessage::MidiMessage (const MidiMessage & , double newTimeStamp)
Creates a copy of another midi message, with a different timestamp.
MidiMessage::~MidiMessage () noexcept
Destructor.
MidiMessage::MidiMessage (MidiMessage &&) noexcept
Move constructor.
Member Function Documentation
MidiMessage& MidiMessage::operator= (const MidiMessage & other)
Copies this message from another one.
MidiMessage& MidiMessage::operator= (MidiMessage &&) noexcept
Move assignment operator.
const uint8* MidiMessage::getRawData () const noexcept
Returns a pointer to the raw midi data.
See Also
getRawDataSize
int MidiMessage::getRawDataSize () const noexcept
Returns the number of bytes of data in the message.
See Also
getRawData
String MidiMessage::getDescription () const
Returns a human-readable description of the midi message as a string, for example "Note On C#3 Velocity 120 Channel 1".
double MidiMessage::getTimeStamp () const noexcept
Returns the timestamp associated with this message.
The exact meaning of this time and its units will vary, as messages are used in a variety of different contexts.
If you're getting the message from a midi file, this could be a time in seconds, or a number of ticks - see MidiFile::convertTimestampTicksToSeconds().
If the message is being used in a MidiBuffer, it might indicate the number of audio samples from the start of the buffer.
If the message was created by a MidiInput, see MidiInputCallback::handleIncomingMidiMessage() for details of the way that it initialises this value.
See Also
setTimeStamp, addToTimeStamp
void MidiMessage::setTimeStamp (double newTimestamp) noexcept
Changes the message's associated timestamp.
The units for the timestamp will be application-specific - see the notes for getTimeStamp().
See Also
addToTimeStamp, getTimeStamp
void MidiMessage::addToTimeStamp (double delta) noexcept
Adds a value to the message's timestamp.
The units for the timestamp will be application-specific.
int MidiMessage::getChannel () const noexcept
Returns the midi channel associated with the message.
Returns
a value 1 to 16 if the message has a channel, or 0 if it hasn't (e.g. if it's a sysex)
See Also
isForChannel, setChannel
Referenced by MidiEventList::toEventList().
bool MidiMessage::isForChannel (int channelNumber) const noexcept
Returns true if the message applies to the given midi channel.
Parameters
channelNumber the channel number to look for, in the range 1 to 16
See Also
getChannel, setChannel
void MidiMessage::setChannel (int newChannelNumber) noexcept
Changes the message's midi channel.
This won't do anything for non-channel messages like sysexes.
Parameters
newChannelNumber the channel number to change it to, in the range 1 to 16
bool MidiMessage::isSysEx () const noexcept
Returns true if this is a system-exclusive message.
Referenced by MidiEventList::toEventList().
const uint8* MidiMessage::getSysExData () const noexcept
Returns a pointer to the sysex data inside the message.
If this event isn't a sysex event, it'll return 0.
See Also
getSysExDataSize
Referenced by MidiEventList::toEventList().
int MidiMessage::getSysExDataSize () const noexcept
Returns the size of the sysex data.
This value excludes the 0xf0 header byte and the 0xf7 at the end.
See Also
getSysExData
Referenced by MidiEventList::toEventList().
bool MidiMessage::isNoteOn (bool returnTrueForVelocity0 = false) const noexcept
Returns true if this message is a 'key-down' event.
Parameters
returnTrueForVelocity0 if true, then if this event is a note-on with velocity 0, it will still be considered to be a note-on and the method will return true. If returnTrueForVelocity0 is false, then if this is a note-on event with velocity 0, it'll be regarded as a note-off, and the method will return false
See Also
isNoteOff, getNoteNumber, getVelocity, noteOn
Referenced by MidiEventList::toEventList().
static MidiMessage MidiMessage::noteOn (int channel, int noteNumber, float velocity) static noexcept
Creates a key-down message (using a floating-point velocity).
Parameters
channel the midi channel, in the range 1 to 16
noteNumber the key number, 0 to 127
velocity in the range 0 to 1.0
See Also
isNoteOn
Referenced by MidiEventList::toEventList(), and MidiEventList::toMidiBuffer().
static MidiMessage MidiMessage::noteOn (int channel, int noteNumber, uint8 velocity) static noexcept
Creates a key-down message (using an integer velocity).
Parameters
channel the midi channel, in the range 1 to 16
noteNumber the key number, 0 to 127
velocity in the range 0 to 127
See Also
isNoteOn
bool MidiMessage::isNoteOff (bool returnTrueForNoteOnVelocity0 = true) const noexcept
Returns true if this message is a 'key-up' event.
If returnTrueForNoteOnVelocity0 is true, then his will also return true for a note-on event with a velocity of 0.
See Also
isNoteOn, getNoteNumber, getVelocity, noteOff
Referenced by MidiEventList::toEventList().
static MidiMessage MidiMessage::noteOff (int channel, int noteNumber, float velocity) static noexcept
Creates a key-up message.
Parameters
channel the midi channel, in the range 1 to 16
noteNumber the key number, 0 to 127
velocity in the range 0 to 1.0
See Also
isNoteOff
Referenced by MidiEventList::toMidiBuffer().
static MidiMessage MidiMessage::noteOff (int channel, int noteNumber, uint8 velocity) static noexcept
Creates a key-up message.
Parameters
channel the midi channel, in the range 1 to 16
noteNumber the key number, 0 to 127
velocity in the range 0 to 127
See Also
isNoteOff
static MidiMessage MidiMessage::noteOff (int channel, int noteNumber) static noexcept
Creates a key-up message.
Parameters
channel the midi channel, in the range 1 to 16
noteNumber the key number, 0 to 127
See Also
isNoteOff
bool MidiMessage::isNoteOnOrOff () const noexcept
Returns true if this message is a 'key-down' or 'key-up' event.
See Also
isNoteOn, isNoteOff
int MidiMessage::getNoteNumber () const noexcept
Returns the midi note number for note-on and note-off messages.
If the message isn't a note-on or off, the value returned is undefined.
See Also
isNoteOff, getMidiNoteName, getMidiNoteInHertz, setNoteNumber
Referenced by MidiEventList::toEventList().
void MidiMessage::setNoteNumber (int newNoteNumber) noexcept
Changes the midi note number of a note-on or note-off message.
If the message isn't a note on or off, this will do nothing.
uint8 MidiMessage::getVelocity () const noexcept
Returns the velocity of a note-on or note-off message.
The value returned will be in the range 0 to 127. If the message isn't a note-on or off event, it will return 0.
See Also
getFloatVelocity
Referenced by MidiEventList::toEventList().
float MidiMessage::getFloatVelocity () const noexcept
Returns the velocity of a note-on or note-off message.
The value returned will be in the range 0 to 1.0 If the message isn't a note-on or off event, it will return 0.
See Also
getVelocity, setVelocity
void MidiMessage::setVelocity (float newVelocity) noexcept
Changes the velocity of a note-on or note-off message.
If the message isn't a note on or off, this will do nothing.
Parameters
newVelocity the new velocity, in the range 0 to 1.0
See Also
getFloatVelocity, multiplyVelocity
void MidiMessage::multiplyVelocity (float scaleFactor) noexcept
Multiplies the velocity of a note-on or note-off message by a given amount.
If the message isn't a note on or off, this will do nothing.
Parameters
scaleFactor the value by which to multiply the velocity
See Also
setVelocity
bool MidiMessage::isSustainPedalOn () const noexcept
Returns true if this message is a 'sustain pedal down' controller message.
bool MidiMessage::isSustainPedalOff () const noexcept
Returns true if this message is a 'sustain pedal up' controller message.
bool MidiMessage::isSostenutoPedalOn () const noexcept
Returns true if this message is a 'sostenuto pedal down' controller message.
bool MidiMessage::isSostenutoPedalOff () const noexcept
Returns true if this message is a 'sostenuto pedal up' controller message.
bool MidiMessage::isSoftPedalOn () const noexcept
Returns true if this message is a 'soft pedal down' controller message.
bool MidiMessage::isSoftPedalOff () const noexcept
Returns true if this message is a 'soft pedal up' controller message.
bool MidiMessage::isProgramChange () const noexcept
Returns true if the message is a program (patch) change message.
See Also
getProgramChangeNumber, getGMInstrumentName
int MidiMessage::getProgramChangeNumber () const noexcept
Returns the new program number of a program change message.
If the message isn't a program change, the value returned is undefined.
See Also
isProgramChange, getGMInstrumentName
static MidiMessage MidiMessage::programChange (int channel, int programNumber) static noexcept
Creates a program-change message.
Parameters
channel the midi channel, in the range 1 to 16
programNumber the midi program number, 0 to 127
See Also
isProgramChange, getGMInstrumentName
bool MidiMessage::isPitchWheel () const noexcept
Returns true if the message is a pitch-wheel move.
See Also
getPitchWheelValue, pitchWheel
int MidiMessage::getPitchWheelValue () const noexcept
Returns the pitch wheel position from a pitch-wheel move message.
The value returned is a 14-bit number from 0 to 0x3fff, indicating the wheel position. If called for messages which aren't pitch wheel events, the number returned will be nonsense.
See Also
isPitchWheel
static MidiMessage MidiMessage::pitchWheel (int channel, int position) static noexcept
Creates a pitch-wheel move message.
Parameters
channel the midi channel, in the range 1 to 16
position the wheel position, in the range 0 to 16383
See Also
isPitchWheel
bool MidiMessage::isAftertouch () const noexcept
Returns true if the message is an aftertouch event.
For aftertouch events, use the getNoteNumber() method to find out the key that it applies to, and getAftertouchValue() to find out the amount. Use getChannel() to find out the channel.
See Also
getAftertouchValue, getNoteNumber
Referenced by MidiEventList::toEventList().
int MidiMessage::getAfterTouchValue () const noexcept
Returns the amount of aftertouch from an aftertouch messages.
The value returned is in the range 0 to 127, and will be nonsense for messages other than aftertouch messages.
See Also
isAftertouch
Referenced by MidiEventList::toEventList().
static MidiMessage MidiMessage::aftertouchChange (int channel, int noteNumber, int aftertouchAmount) static noexcept
Creates an aftertouch message.
Parameters
channel the midi channel, in the range 1 to 16
noteNumber the key number, 0 to 127
aftertouchAmount the amount of aftertouch, 0 to 127
See Also
isAftertouch
Referenced by MidiEventList::toMidiBuffer().
bool MidiMessage::isChannelPressure () const noexcept
Returns true if the message is a channel-pressure change event.
This is like aftertouch, but common to the whole channel rather than a specific note. Use getChannelPressureValue() to find out the pressure, and getChannel() to find out the channel.
See Also
channelPressureChange
int MidiMessage::getChannelPressureValue () const noexcept
Returns the pressure from a channel pressure change message.
Returns
the pressure, in the range 0 to 127
See Also
isChannelPressure, channelPressureChange
static MidiMessage MidiMessage::channelPressureChange (int channel, int pressure) static noexcept
Creates a channel-pressure change event.
Parameters
channel the midi channel: 1 to 16
pressure the pressure, 0 to 127
See Also
isChannelPressure
bool MidiMessage::isController () const noexcept
Returns true if this is a midi controller message.
See Also
getControllerNumber, getControllerValue, controllerEvent
int MidiMessage::getControllerNumber () const noexcept
Returns the controller number of a controller message.
The name of the controller can be looked up using the getControllerName() method. Note that the value returned is invalid for messages that aren't controller changes.
See Also
isController, getControllerName, getControllerValue
int MidiMessage::getControllerValue () const noexcept
Returns the controller value from a controller message.
A value 0 to 127 is returned to indicate the new controller position. Note that the value returned is invalid for messages that aren't controller changes.
See Also
isController, getControllerNumber
bool MidiMessage::isControllerOfType (int controllerType) const noexcept
Returns true if this message is a controller message and if it has the specified controller type.
static MidiMessage MidiMessage::controllerEvent (int channel, int controllerType, int value) static noexcept
Creates a controller message.
Parameters
channel the midi channel, in the range 1 to 16
controllerType the type of controller
value the controller value
See Also
isController
bool MidiMessage::isAllNotesOff () const noexcept
Checks whether this message is an all-notes-off message.
See Also
allNotesOff
bool MidiMessage::isAllSoundOff () const noexcept
Checks whether this message is an all-sound-off message.
See Also
allSoundOff
static MidiMessage MidiMessage::allNotesOff (int channel) static noexcept
Creates an all-notes-off message.
Parameters
channel the midi channel, in the range 1 to 16
See Also
isAllNotesOff
static MidiMessage MidiMessage::allSoundOff (int channel) static noexcept
Creates an all-sound-off message.
Parameters
channel the midi channel, in the range 1 to 16
See Also
isAllSoundOff
static MidiMessage MidiMessage::allControllersOff (int channel) static noexcept
Creates an all-controllers-off message.
Parameters
channel the midi channel, in the range 1 to 16
bool MidiMessage::isMetaEvent () const noexcept
Returns true if this event is a meta-event.
Meta-events are things like tempo changes, track names, etc.
See Also
getMetaEventType, isTrackMetaEvent, isEndOfTrackMetaEvent, isTextMetaEvent, isTrackNameEvent, isTempoMetaEvent, isTimeSignatureMetaEvent, isKeySignatureMetaEvent, isMidiChannelMetaEvent
int MidiMessage::getMetaEventType () const noexcept
Returns a meta-event's type number.
If the message isn't a meta-event, this will return -1.
See Also
isMetaEvent, isTrackMetaEvent, isEndOfTrackMetaEvent, isTextMetaEvent, isTrackNameEvent, isTempoMetaEvent, isTimeSignatureMetaEvent, isKeySignatureMetaEvent, isMidiChannelMetaEvent
const uint8* MidiMessage::getMetaEventData () const noexcept
Returns a pointer to the data in a meta-event.
See Also
isMetaEvent, getMetaEventLength
int MidiMessage::getMetaEventLength () const noexcept
Returns the length of the data for a meta-event.
See Also
isMetaEvent, getMetaEventData
bool MidiMessage::isTrackMetaEvent () const noexcept
Returns true if this is a 'track' meta-event.
bool MidiMessage::isEndOfTrackMetaEvent () const noexcept
Returns true if this is an 'end-of-track' meta-event.
static MidiMessage MidiMessage::endOfTrack () static noexcept
Creates an end-of-track meta-event.
See Also
isEndOfTrackMetaEvent
bool MidiMessage::isTrackNameEvent () const noexcept
Returns true if this is an 'track name' meta-event.
You can use the getTextFromTextMetaEvent() method to get the track's name.
bool MidiMessage::isTextMetaEvent () const noexcept
Returns true if this is a 'text' meta-event.
See Also
getTextFromTextMetaEvent
String MidiMessage::getTextFromTextMetaEvent () const
Returns the text from a text meta-event.
See Also
isTextMetaEvent
static MidiMessage MidiMessage::textMetaEvent (int type, StringRef text) static
Creates a text meta-event.
bool MidiMessage::isTempoMetaEvent () const noexcept
Returns true if this is a 'tempo' meta-event.
See Also
getTempoMetaEventTickLength, getTempoSecondsPerQuarterNote
double MidiMessage::getTempoMetaEventTickLength (short timeFormat) const noexcept
Returns the tick length from a tempo meta-event.
Parameters
timeFormat the 16-bit time format value from the midi file's header.
Returns
the tick length (in seconds).
See Also
isTempoMetaEvent
double MidiMessage::getTempoSecondsPerQuarterNote () const noexcept
Calculates the seconds-per-quarter-note from a tempo meta-event.
See Also
isTempoMetaEvent, getTempoMetaEventTickLength
static MidiMessage MidiMessage::tempoMetaEvent (int microsecondsPerQuarterNote) static noexcept
Creates a tempo meta-event.
See Also
isTempoMetaEvent
bool MidiMessage::isTimeSignatureMetaEvent () const noexcept
Returns true if this is a 'time-signature' meta-event.
See Also
getTimeSignatureInfo
void MidiMessage::getTimeSignatureInfo (int & numerator, int & denominator) const noexcept
Returns the time-signature values from a time-signature meta-event.
See Also
isTimeSignatureMetaEvent
static MidiMessage MidiMessage::timeSignatureMetaEvent (int numerator, int denominator) static
Creates a time-signature meta-event.
See Also
isTimeSignatureMetaEvent
bool MidiMessage::isKeySignatureMetaEvent () const noexcept
Returns true if this is a 'key-signature' meta-event.
See Also
getKeySignatureNumberOfSharpsOrFlats, isKeySignatureMajorKey
int MidiMessage::getKeySignatureNumberOfSharpsOrFlats () const noexcept
Returns the key from a key-signature meta-event.
This method must only be called if isKeySignatureMetaEvent() is true. A positive number here indicates the number of sharps in the key signature, and a negative number indicates a number of flats. So e.g. 3 = F# + C# + G#, -2 = Bb + Eb
See Also
isKeySignatureMetaEvent, isKeySignatureMajorKey
bool MidiMessage::isKeySignatureMajorKey () const noexcept
Returns true if this key-signature event is major, or false if it's minor.
This method must only be called if isKeySignatureMetaEvent() is true.
static MidiMessage MidiMessage::keySignatureMetaEvent (int numberOfSharpsOrFlats, bool isMinorKey) static
Creates a key-signature meta-event.
Parameters
numberOfSharpsOrFlats if positive, this indicates the number of sharps in the key; if negative, the number of flats
isMinorKey if true, the key is minor; if false, it is major
See Also
isKeySignatureMetaEvent
bool MidiMessage::isMidiChannelMetaEvent () const noexcept
Returns true if this is a 'channel' meta-event.
A channel meta-event specifies the midi channel that should be used for subsequent meta-events.
See Also
getMidiChannelMetaEventChannel
int MidiMessage::getMidiChannelMetaEventChannel () const noexcept
Returns the channel number from a channel meta-event.
Returns
the channel, in the range 1 to 16.
See Also
isMidiChannelMetaEvent
static MidiMessage MidiMessage::midiChannelMetaEvent (int channel) static noexcept
Creates a midi channel meta-event.
Parameters
channel the midi channel, in the range 1 to 16
See Also
isMidiChannelMetaEvent
bool MidiMessage::isActiveSense () const noexcept
Returns true if this is an active-sense message.
bool MidiMessage::isMidiStart () const noexcept
Returns true if this is a midi start event.
See Also
midiStart
static MidiMessage MidiMessage::midiStart () static noexcept
Creates a midi start event.
bool MidiMessage::isMidiContinue () const noexcept
Returns true if this is a midi continue event.
See Also
midiContinue
static MidiMessage MidiMessage::midiContinue () static noexcept
Creates a midi continue event.
bool MidiMessage::isMidiStop () const noexcept
Returns true if this is a midi stop event.
See Also
midiStop
static MidiMessage MidiMessage::midiStop () static noexcept
Creates a midi stop event.
bool MidiMessage::isMidiClock () const noexcept
Returns true if this is a midi clock event.
See Also
midiClock, songPositionPointer
static MidiMessage MidiMessage::midiClock () static noexcept
Creates a midi clock event.
bool MidiMessage::isSongPositionPointer () const noexcept
Returns true if this is a song-position-pointer message.
See Also
getSongPositionPointerMidiBeat, songPositionPointer
int MidiMessage::getSongPositionPointerMidiBeat () const noexcept
Returns the midi beat-number of a song-position-pointer message.
See Also
isSongPositionPointer, songPositionPointer
static MidiMessage MidiMessage::songPositionPointer (int positionInMidiBeats) static noexcept
Creates a song-position-pointer message.
The position is a number of midi beats from the start of the song, where 1 midi beat is 6 midi clocks, and there are 24 midi clocks in a quarter-note. So there are 4 midi beats in a quarter-note.
See Also
isSongPositionPointer, getSongPositionPointerMidiBeat
bool MidiMessage::isQuarterFrame () const noexcept
Returns true if this is a quarter-frame midi timecode message.
See Also
quarterFrame, getQuarterFrameSequenceNumber, getQuarterFrameValue
int MidiMessage::getQuarterFrameSequenceNumber () const noexcept
Returns the sequence number of a quarter-frame midi timecode message.
This will be a value between 0 and 7.
See Also
isQuarterFrame, getQuarterFrameValue, quarterFrame
int MidiMessage::getQuarterFrameValue () const noexcept
Returns the value from a quarter-frame message.
This will be the lower nybble of the message's data-byte, a value between 0 and 15
static MidiMessage MidiMessage::quarterFrame (int sequenceNumber, int value) static noexcept
Creates a quarter-frame MTC message.
Parameters
sequenceNumber a value 0 to 7 for the upper nybble of the message's data byte
value a value 0 to 15 for the lower nybble of the message's data byte
bool MidiMessage::isFullFrame () const noexcept
Returns true if this is a full-frame midi timecode message.
void MidiMessage::getFullFrameParameters (int & hours, int & minutes, int & seconds, int & frames, SmpteTimecodeType & timecodeType) const noexcept
Extracts the timecode information from a full-frame midi timecode message.
You should only call this on messages where you've used isFullFrame() to check that they're the right kind.
static MidiMessage MidiMessage::fullFrame (int hours, int minutes, int seconds, int frames, SmpteTimecodeType timecodeType) static
Creates a full-frame MTC message.
bool MidiMessage::isMidiMachineControlMessage () const noexcept
Checks whether this is an MMC message.
If it is, you can use the getMidiMachineControlCommand() to find out its type.
MidiMachineControlCommand MidiMessage::getMidiMachineControlCommand () const noexcept
For an MMC message, this returns its type.
Make sure it's actually an MMC message with isMidiMachineControlMessage() before calling this method.
static MidiMessage MidiMessage::midiMachineControlCommand (MidiMachineControlCommand command) static
Creates an MMC message.
bool MidiMessage::isMidiMachineControlGoto (int & hours, int & minutes, int & seconds, int & frames) const noexcept
Checks whether this is an MMC "goto" message.
If it is, the parameters passed-in are set to the time that the message contains.
See Also
midiMachineControlGoto
static MidiMessage MidiMessage::midiMachineControlGoto (int hours, int minutes, int seconds, int frames) static
Creates an MMC "goto" message.
This messages tells the device to go to a specific frame.
See Also
isMidiMachineControlGoto
static MidiMessage MidiMessage::masterVolume (float volume) static
Creates a master-volume change message.
Parameters
volume the volume, 0 to 1.0
static MidiMessage MidiMessage::createSysExMessage (const void * sysexData, int dataSize) static
Creates a system-exclusive message.
The data passed in is wrapped with header and tail bytes of 0xf0 and 0xf7.
Referenced by MidiEventList::toMidiBuffer().
static int MidiMessage::readVariableLengthVal (const uint8 * data, int & numBytesUsed) static noexcept
Reads a midi variable-length integer.
Parameters
data the data to read the number from
numBytesUsed on return, this will be set to the number of bytes that were read
static int MidiMessage::getMessageLengthFromFirstByte (uint8 firstByte) static noexcept
Based on the first byte of a short midi message, this uses a lookup table to return the message length (either 1, 2, or 3 bytes).
The value passed in must be 0x80 or higher.
static String MidiMessage::getMidiNoteName (int noteNumber, bool useSharps, bool includeOctaveNumber, int octaveNumForMiddleC) static
Returns the name of a midi note number.
E.g "C", "D#", etc.
Parameters
noteNumber the midi note number, 0 to 127
useSharps if true, sharpened notes are used, e.g. "C#", otherwise they'll be flattened, e.g. "Db"
includeOctaveNumber if true, the octave number will be appended to the string, e.g. "C#4"
octaveNumForMiddleC if an octave number is being appended, this indicates the number that will be used for middle C's octave
See Also
getMidiNoteInHertz
static double MidiMessage::getMidiNoteInHertz (int noteNumber, double frequencyOfA = 440.0) static noexcept
Returns the frequency of a midi note number.
The frequencyOfA parameter is an optional frequency for 'A', normally 440-444Hz for concert pitch.
See Also
getMidiNoteName
static bool MidiMessage::isMidiNoteBlack (int noteNumber) static noexcept
Returns true if the given midi note number is a black key.
static const char* MidiMessage::getGMInstrumentName (int midiInstrumentNumber) static
Returns the standard name of a GM instrument, or nullptr if unknown for this index.
Parameters
midiInstrumentNumber the program number 0 to 127
See Also
getProgramChangeNumber
static const char* MidiMessage::getGMInstrumentBankName (int midiBankNumber) static
Returns the name of a bank of GM instruments, or nullptr if unknown for this bank number.
Parameters
midiBankNumber the bank, 0 to 15
static const char* MidiMessage::getRhythmInstrumentName (int midiNoteNumber) static
Returns the standard name of a channel 10 percussion sound, or nullptr if unknown for this note number.
Parameters
midiNoteNumber the key number, 35 to 81
static const char* MidiMessage::getControllerName (int controllerNumber) static
Returns the name of a controller type number, or nullptr if unknown for this controller number.
See Also
getControllerNumber
static uint8 MidiMessage::floatValueToMidiByte (float valueBetween0and1) static noexcept
Converts a floating-point value between 0 and 1 to a MIDI 7-bit value between 0 and 127.
static uint16 MidiMessage::pitchbendToPitchwheelPos (float pitchbendInSemitones, float pitchbendRangeInSemitones) static noexcept
Converts a pitchbend value in semitones to a MIDI 14-bit pitchwheel position value.
class MidiMessageSequence
A sequence of timestamped midi messages.
This allows the sequence to be manipulated, and also to be read from and written to a standard midi file.
See Also
MidiMessage, MidiFile
Public Member Functions
MidiMessageSequence ()
Creates an empty midi sequence object.
MidiMessageSequence (const MidiMessageSequence &)
Creates a copy of another sequence.
MidiMessageSequence & operator= (const MidiMessageSequence &)
Replaces this sequence with another one.
MidiMessageSequence (MidiMessageSequence &&) noexcept
Move constructor.
MidiMessageSequence & operator= (MidiMessageSequence &&) noexcept
Move assignment operator.
~MidiMessageSequence ()
Destructor.
void clear ()
Clears the sequence.
int getNumEvents () const noexcept
Returns the number of events in the sequence.
MidiEventHolder * getEventPointer (int index) const noexcept
Returns a pointer to one of the events.
MidiEventHolder ** begin () const noexcept
Iterator for the list of MidiEventHolders.
MidiEventHolder ** end () const noexcept
Iterator for the list of MidiEventHolders.
double getTimeOfMatchingKeyUp (int index) const noexcept
Returns the time of the note-up that matches the note-on at this index.
int getIndexOfMatchingKeyUp (int index) const noexcept
Returns the index of the note-up that matches the note-on at this index.
int getIndexOf (const MidiEventHolder *event) const noexcept
Returns the index of an event.
int getNextIndexAtTime (double timeStamp) const noexcept
Returns the index of the first event on or after the given timestamp.
double getStartTime () const noexcept
Returns the timestamp of the first event in the sequence.
double getEndTime () const noexcept
Returns the timestamp of the last event in the sequence.
double getEventTime (int index) const noexcept
Returns the timestamp of the event at a given index.
MidiEventHolder * addEvent (const MidiMessage &newMessage, double timeAdjustment=0)
Inserts a midi message into the sequence.
MidiEventHolder * addEvent (MidiMessage &&newMessage, double timeAdjustment=0)
Inserts a midi message into the sequence.
void deleteEvent (int index, bool deleteMatchingNoteUp)
Deletes one of the events in the sequence.
void addSequence (const MidiMessageSequence &other, double timeAdjustmentDelta, double firstAllowableDestTime, double endOfAllowableDestTimes)
Merges another sequence into this one.
void addSequence (const MidiMessageSequence &other, double timeAdjustmentDelta)
Merges another sequence into this one.
void updateMatchedPairs () noexcept
Makes sure all the note-on and note-off pairs are up-to-date.
void sort () noexcept
Forces a sort of the sequence.
void extractMidiChannelMessages (int channelNumberToExtract, MidiMessageSequence &destSequence, bool alsoIncludeMetaEvents) const
Copies all the messages for a particular midi channel to another sequence.
void extractSysExMessages (MidiMessageSequence &destSequence) const
Copies all midi sys-ex messages to another sequence.
void deleteMidiChannelMessages (int channelNumberToRemove)
Removes any messages in this sequence that have a specific midi channel.
void deleteSysExMessages ()
Removes any sys-ex messages from this sequence.
void addTimeToMessages (double deltaTime) noexcept
Adds an offset to the timestamps of all events in the sequence.
void createControllerUpdatesForTime (int channelNumber, double time, Array< MidiMessage > &resultMessages)
Scans through the sequence to determine the state of any midi controllers at a given time.
void swapWith (MidiMessageSequence &) noexcept
Swaps this sequence with another one.
Constructor & Destructor Documentation
MidiMessageSequence::MidiMessageSequence ()
Creates an empty midi sequence object.
MidiMessageSequence::MidiMessageSequence (const MidiMessageSequence &)
Creates a copy of another sequence.
MidiMessageSequence::MidiMessageSequence (MidiMessageSequence &&) noexcept
Move constructor.
MidiMessageSequence::~MidiMessageSequence ()
Destructor.
Member Function Documentation
MidiMessageSequence& MidiMessageSequence::operator= (const MidiMessageSequence &)
Replaces this sequence with another one.
MidiMessageSequence& MidiMessageSequence::operator= (MidiMessageSequence &&) noexcept
Move assignment operator.
void MidiMessageSequence::clear ()
Clears the sequence.
int MidiMessageSequence::getNumEvents () const noexcept
Returns the number of events in the sequence.
MidiEventHolder* MidiMessageSequence::getEventPointer (int index) const noexcept
Returns a pointer to one of the events.
MidiEventHolder** MidiMessageSequence::begin () const noexcept
Iterator for the list of MidiEventHolders.
MidiEventHolder** MidiMessageSequence::end () const noexcept
Iterator for the list of MidiEventHolders.
double MidiMessageSequence::getTimeOfMatchingKeyUp (int index) const noexcept
Returns the time of the note-up that matches the note-on at this index.
If the event at this index isn't a note-on, it'll just return 0.
See Also
MidiMessageSequence::MidiEventHolder::noteOffObject
int MidiMessageSequence::getIndexOfMatchingKeyUp (int index) const noexcept
Returns the index of the note-up that matches the note-on at this index.
If the event at this index isn't a note-on, it'll just return -1.
See Also
MidiMessageSequence::MidiEventHolder::noteOffObject
int MidiMessageSequence::getIndexOf (const MidiEventHolder * event) const noexcept
Returns the index of an event.
int MidiMessageSequence::getNextIndexAtTime (double timeStamp) const noexcept
Returns the index of the first event on or after the given timestamp.
If the time is beyond the end of the sequence, this will return the number of events.
double MidiMessageSequence::getStartTime () const noexcept
Returns the timestamp of the first event in the sequence.
See Also
getEndTime
double MidiMessageSequence::getEndTime () const noexcept
Returns the timestamp of the last event in the sequence.
See Also
getStartTime
double MidiMessageSequence::getEventTime (int index) const noexcept
Returns the timestamp of the event at a given index.
If the index is out-of-range, this will return 0.0
MidiEventHolder* MidiMessageSequence::addEvent (const MidiMessage & newMessage, double timeAdjustment = 0)
Inserts a midi message into the sequence.
The index at which the new message gets inserted will depend on its timestamp, because the sequence is kept sorted.
Remember to call updateMatchedPairs() after adding note-on events.
Parameters
newMessage the new message to add (an internal copy will be made)
timeAdjustment an optional value to add to the timestamp of the message that will be inserted
See Also
updateMatchedPairs
MidiEventHolder* MidiMessageSequence::addEvent (MidiMessage && newMessage, double timeAdjustment = 0)
Inserts a midi message into the sequence.
The index at which the new message gets inserted will depend on its timestamp, because the sequence is kept sorted.
Remember to call updateMatchedPairs() after adding note-on events.
Parameters
newMessage the new message to add (an internal copy will be made)
timeAdjustment an optional value to add to the timestamp of the message that will be inserted
See Also
updateMatchedPairs
void MidiMessageSequence::deleteEvent (int index, bool deleteMatchingNoteUp)
Deletes one of the events in the sequence.
Remember to call updateMatchedPairs() after removing events.
Parameters
index the index of the event to delete
deleteMatchingNoteUp whether to also remove the matching note-off if the event you're removing is a note-on
void MidiMessageSequence::addSequence (const MidiMessageSequence & other, double timeAdjustmentDelta, double firstAllowableDestTime, double endOfAllowableDestTimes)
Merges another sequence into this one.
Remember to call updateMatchedPairs() after using this method.
Parameters
other the sequence to add from
timeAdjustmentDelta an amount to add to the timestamps of the midi events as they are read from the other sequence
firstAllowableDestTime events will not be added if their time is earlier than this time. (This is after their time has been adjusted by the timeAdjustmentDelta)
endOfAllowableDestTimes events will not be added if their time is equal to or greater than this time. (This is after their time has been adjusted by the timeAdjustmentDelta)
void MidiMessageSequence::addSequence (const MidiMessageSequence & other, double timeAdjustmentDelta)
Merges another sequence into this one.
Remember to call updateMatchedPairs() after using this method.
Parameters
other the sequence to add from
timeAdjustmentDelta an amount to add to the timestamps of the midi events as they are read from the other sequence
void MidiMessageSequence::updateMatchedPairs () noexcept
Makes sure all the note-on and note-off pairs are up-to-date.
Call this after re-ordering messages or deleting/adding messages, and it will scan the list and make sure all the note-offs in the MidiEventHolder structures are pointing at the correct ones.
void MidiMessageSequence::sort () noexcept
Forces a sort of the sequence.
You may need to call this if you've manually modified the timestamps of some events such that the overall order now needs updating.
void MidiMessageSequence::extractMidiChannelMessages (int channelNumberToExtract, MidiMessageSequence & destSequence, bool alsoIncludeMetaEvents) const
Copies all the messages for a particular midi channel to another sequence.
Parameters
channelNumberToExtract the midi channel to look for, in the range 1 to 16
destSequence the sequence that the chosen events should be copied to
alsoIncludeMetaEvents if true, any meta-events (which don't apply to a specific channel) will also be copied across.
See Also
extractSysExMessages
void MidiMessageSequence::extractSysExMessages (MidiMessageSequence & destSequence) const
Copies all midi sys-ex messages to another sequence.
Parameters
destSequence this is the sequence to which any sys-exes in this sequence will be added
See Also
extractMidiChannelMessages
void MidiMessageSequence::deleteMidiChannelMessages (int channelNumberToRemove)
Removes any messages in this sequence that have a specific midi channel.
Parameters
channelNumberToRemove the midi channel to look for, in the range 1 to 16
void MidiMessageSequence::deleteSysExMessages ()
Removes any sys-ex messages from this sequence.
void MidiMessageSequence::addTimeToMessages (double deltaTime) noexcept
Adds an offset to the timestamps of all events in the sequence.
Parameters
deltaTime the amount to add to each timestamp.
void MidiMessageSequence::createControllerUpdatesForTime (int channelNumber, double time, Array< MidiMessage > & resultMessages)
Scans through the sequence to determine the state of any midi controllers at a given time.
This will create a sequence of midi controller changes that can be used to set all midi controllers to the state they would be in at the specified time within this sequence.
As well as controllers, it will also recreate the midi program number and pitch bend position.
Parameters
channelNumber the midi channel to look for, in the range 1 to 16. Controllers for other channels will be ignored.
time the time at which you want to find out the state - there are no explicit units for this time measurement, it's the same units as used for the timestamps of the messages
resultMessages an array to which midi controller-change messages will be added. This will be the minimum number of controller changes to recreate the state at the required time.
void MidiMessageSequence::swapWith (MidiMessageSequence &) noexcept
Swaps this sequence with another one.
struct MidiRPNMessage
Represents a MIDI RPN (registered parameter number) or NRPN (non-registered parameter number) message.
Public Attributes
int channel
Midi channel of the message, in the range 1 to 16.
int parameterNumber
The 14-bit parameter index, in the range 0 to 16383 (0x3fff).
int value
The parameter value, in the range 0 to 16383 (0x3fff).
bool isNRPN
True if this message is an NRPN; false if it is an RPN.
bool is14BitValue
True if the value uses 14-bit resolution (LSB + MSB); false if the value is 7-bit (MSB only).
Member Data Documentation
int MidiRPNMessage::channel
Midi channel of the message, in the range 1 to 16.
int MidiRPNMessage::parameterNumber
The 14-bit parameter index, in the range 0 to 16383 (0x3fff).
int MidiRPNMessage::value
The parameter value, in the range 0 to 16383 (0x3fff).
If the message contains no value LSB, the value will be in the range 0 to 127 (0x7f).
bool MidiRPNMessage::isNRPN
True if this message is an NRPN; false if it is an RPN.
bool MidiRPNMessage::is14BitValue
True if the value uses 14-bit resolution (LSB + MSB); false if the value is 7-bit (MSB only).
class MidiRPNDetector
Parses a stream of MIDI data to assemble RPN and NRPN messages from their constituent MIDI CC messages.
The detector uses the following parsing rules: the parameter number LSB/MSB can be sent/received in either order and must both come before the parameter value; for the parameter value, LSB always has to be sent/received before the value MSB, otherwise it will be treated as 7-bit (MSB only).
Public Member Functions
MidiRPNDetector () noexcept
Constructor.
~MidiRPNDetector () noexcept
Destructor.
void reset () noexcept
Resets the RPN detector's internal state, so that it forgets about previously received MIDI CC messages.
bool parseControllerMessage (int midiChannel, int controllerNumber, int controllerValue, MidiRPNMessage &result) noexcept
Takes the next in a stream of incoming MIDI CC messages and returns true if it forms the last of a sequence that makes an RPN or NPRN.
Constructor & Destructor Documentation
MidiRPNDetector::MidiRPNDetector () noexcept
Constructor.
MidiRPNDetector::~MidiRPNDetector () noexcept
Destructor.
Member Function Documentation
void MidiRPNDetector::reset () noexcept
Resets the RPN detector's internal state, so that it forgets about previously received MIDI CC messages.
bool MidiRPNDetector::parseControllerMessage (int midiChannel, int controllerNumber, int controllerValue, MidiRPNMessage & result) noexcept
Takes the next in a stream of incoming MIDI CC messages and returns true if it forms the last of a sequence that makes an RPN or NPRN.
If this returns true, then the RPNMessage object supplied will be filled-out with the message's details. (If it returns false then the RPNMessage object will be unchanged).
class MidiRPNGenerator
Generates an appropriate sequence of MIDI CC messages to represent an RPN or NRPN message.
This sequence (as a MidiBuffer) can then be directly sent to a MidiOutput.
Static Public Member Functions
static MidiBuffer generate (MidiRPNMessage message)
Generates a MIDI sequence representing the given RPN or NRPN message.
static MidiBuffer generate (int channel, int parameterNumber, int value, bool isNRPN=false, bool use14BitValue=true)
Generates a MIDI sequence representing an RPN or NRPN message with the given parameters.
Member Function Documentation
static MidiBuffer MidiRPNGenerator::generate (MidiRPNMessage message) static
Generates a MIDI sequence representing the given RPN or NRPN message.
static MidiBuffer MidiRPNGenerator::generate (int channel, int parameterNumber, int value, bool isNRPN = false, bool use14BitValue = true) static
Generates a MIDI sequence representing an RPN or NRPN message with the given parameters.
Parameters
channel The MIDI channel of the RPN/NRPN message.
parameterNumber The parameter number, in the range 0 to 16383.
value The parameter value, in the range 0 to 16383, or in the range 0 to 127 if sendAs14BitValue is false.
isNRPN Whether you need a MIDI RPN or NRPN sequence (RPN is default).
use14BitValue If true (default), the value will have 14-bit precision (two MIDI bytes). If false, instead the value will have 7-bit presision (a single MIDI byte).