JUCE: Math functions
Math functions
LittleFoot Functions
Functions
int min (int a, int b)
Returns the smaller of two integer values.
float min (float a, float b)
Returns the smaller of two floating point values.
int max (int a, int b)
Returns the larger of two integer values.
float max (float a, float b)
Returns the larger of two floating point values.
int clamp (int lowerLimit, int upperLimit, int valueToConstrain)
Constrains an integer value to keep it within a given range.
float clamp (float lowerLimit, float upperLimit, float valueToConstrain)
Constrains a floating point value to keep it within a given range.
int abs (int arg)
Returns the absolute value of an integer value.
float abs (float arg)
Returns the absolute value of a floating point value.
float map (float value, float sourceMin, float sourceMax, float destMin, float destMax)
Remaps a value from a source range to a target range.
float map (float value, float sourceMin, float sourceMax)
Remaps a value from a source range to the range 0 - 1.0.
int mod (int dividend, int divisor)
Performs a modulo operation (can cope with the dividend being negative).
float getRandomFloat ()
Returns a random floating-point number.
int getRandomInt (int maxValue)
Returns a random integer, limited to a given range.
int getMillisecondCounter ()
Returns the number of milliseconds since a fixed event (usually system startup).
int getTimeInCurrentFunctionCall ()
Returns the length of time spent in the current function call in milliseconds.
Detailed Description
Function Documentation
int min (int a, int b)
Returns the smaller of two integer values.
Parameters
a The first parameter
b The second parameter
Return values
The minimum of a and b
Referenced by HostPacketDecoder< Handler >::handleConfigMessage(), BlockConfigManager::handleConfigUpdateMessage(), jmin(), SIMDRegister< Type >::min(), BlockConfigManager::setItemMin(), and BlockConfigManager::ConfigDescription::toConfigMetaData().
float min (float a, float b)
Returns the smaller of two floating point values.
Parameters
a The first parameter
b The second parameter
Return values
The minimum of a and b
int max (int a, int b)
Returns the larger of two integer values.
Parameters
a The first parameter
b The second parameter
Return values
The maximum of a and b
Referenced by String::appendCharPointer(), HostPacketDecoder< Handler >::handleConfigMessage(), BlockConfigManager::handleConfigUpdateMessage(), jmax(), SIMDRegister< Type >::max(), BlockConfigManager::setItemMax(), BlockConfigManager::ConfigDescription::toConfigMetaData(), and truncatePositiveToUnsignedInt().
float max (float a, float b)
Returns the larger of two floating point values.
Parameters
a The first parameter
b The second parameter
Return values
The maximum of a and b
int clamp (int lowerLimit, int upperLimit, int valueToConstrain)
Constrains an integer value to keep it within a given range.
Parameters
lowerLimit the minimum value to return
upperLimit the maximum value to return
valueToConstrain the value to try to return
Returns
the closest value to valueToConstrain which lies between lowerLimit and upperLimit (inclusive)
float clamp (float lowerLimit, float upperLimit, float valueToConstrain)
Constrains a floating point value to keep it within a given range.
Parameters
lowerLimit the minimum value to return
upperLimit the maximum value to return
valueToConstrain the value to try to return
Returns
the closest value to valueToConstrain which lies between lowerLimit and upperLimit (inclusive)
int abs (int arg)
Returns the absolute value of an integer value.
Parameters
arg The argument to compute the absolute value of
Return values
either -arg if arg is negative or arg if arg is positive
Referenced by NormalisableRange< float >::convertFrom0to1(), NormalisableRange< float >::convertTo0to1(), UnitTest::expectWithinAbsoluteError(), DefaultHashFunctions::generateHash(), AnimatedPositionBehaviours::ContinuousWithMomentum::getNextPosition(), and AnimatedPositionBehaviours::SnapToPageBoundaries::isStopped().
float abs (float arg)
Returns the absolute value of a floating point value.
Parameters
arg The argument to compute the absolute value of
Return values
either -arg if arg is negative or arg if arg is positive
float map (float value, float sourceMin, float sourceMax, float destMin, float destMax)
Remaps a value from a source range to a target range.
Parameters
value the value within the source range to map
sourceMin the minimum value of the source range
sourceMax the maximum value of the source range
destMin the minumum value of the destination range
destMax the maximum value of the destination range
Returns
the original value mapped to the destination range
Referenced by MemoryMappedAudioFormatReader::getNumBytesUsed(), and MemoryMappedAudioFormatReader::sampleToPointer().
float map (float value, float sourceMin, float sourceMax)
Remaps a value from a source range to the range 0 - 1.0.
Parameters
value the value within the source range to map
sourceMin the minimum value of the source range
sourceMax the maximum value of the source range
Returns
the original value mapped to the range 0 - 1.0
int mod (int dividend, int divisor)
Performs a modulo operation (can cope with the dividend being negative).
The divisor must be greater than zero.
Returns
the result of the modulo operation
float getRandomFloat ()
Returns a random floating-point number.
Returns
a random value in the range 0 (inclusive) to 1.0 (exclusive)
int getRandomInt (int maxValue)
Returns a random integer, limited to a given range.
Returns
a random integer between 0 (inclusive) and maxValue (exclusive).
int getMillisecondCounter ()
Returns the number of milliseconds since a fixed event (usually system startup).
Returns
a monotonically increasing value which is unaffected by changes to the system clock. It should be accurate to within a few millisecseconds.
int getTimeInCurrentFunctionCall ()
Returns the length of time spent in the current function call in milliseconds.
Returns
the length of time spent in the current function call in milliseconds.