JUCE: text
text
juce_core
Classes
struct Base64
Contains some static methods for converting between binary and the standard base-64 encoding format.
class CharacterFunctions
A collection of functions for manipulating characters and character strings.
class CharPointer_ASCII
Wraps a pointer to a null-terminated ASCII character string, and provides various methods to operate on the data.
class CharPointer_UTF16
Wraps a pointer to a null-terminated UTF-16 character string, and provides various methods to operate on the data.
class CharPointer_UTF32
Wraps a pointer to a null-terminated UTF-32 character string, and provides various methods to operate on the data.
class CharPointer_UTF8
Wraps a pointer to a null-terminated UTF-8 character string, and provides various methods to operate on the data.
class Identifier
Represents a string identifier, designed for accessing properties by name.
class LocalisedStrings
Used to convert strings to localised foreign-language versions.
class NewLine
This class is used for represent a new-line character sequence.
class String
The JUCE String class!
class StringArray
A special array for holding a list of strings.
class StringPairArray
A container for holding a set of strings which are keyed by another string.
class StringPool
A StringPool holds a set of shared strings, which reduces storage overheads and improves comparison speed when dealing with many duplicate strings.
class StringRef
A simple class for holding temporary references to a string literal or String.
class TextDiff
Calculates and applies a sequence of changes to convert one text string into another.
Macros
#define JUCE_NATIVE_WCHAR_IS_UTF8 0
This macro will be set to 1 if the compiler's native wchar_t is an 8-bit type.
#define JUCE_NATIVE_WCHAR_IS_UTF16 0
This macro will be set to 1 if the compiler's native wchar_t is a 16-bit type.
#define JUCE_NATIVE_WCHAR_IS_UTF32 1
This macro will be set to 1 if the compiler's native wchar_t is a 32-bit type.
#define TRANS(stringLiteral) juce::translate (stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
#define NEEDS_TRANS(stringLiteral) (stringLiteral)
A dummy version of the TRANS macro, used to indicate a string literal that should be added to the translation file by source-code scanner tools.
Typedefs
typedef wchar_t juce_wchar
A platform-independent 32-bit unicode character type.
Functions
JUCE_API String translate (const String &stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
JUCE_API String translate (const char *stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
JUCE_API String translate (CharPointer_UTF8 stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
JUCE_API String translate (const String &stringLiteral, const String &resultIfNotFound)
Uses the LocalisedStrings class to translate the given string literal.
String & operator<< (String &string1, const NewLine &)
Writes a new-line sequence to a string.
String & operator+= (String &s1, const NewLine &)
String operator+ (const NewLine &, const NewLine &)
String operator+ (String s1, const NewLine &)
String operator+ (const NewLine &, const char *s2)
JUCE_API String JUCE_CALLTYPE operator+ (const char *string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (const wchar_t *string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (char string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (wchar_t string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const String &string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const char *string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const wchar_t *string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, char characterToAppend)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, wchar_t characterToAppend)
Concatenates two strings.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, char characterToAppend)
Appends a character at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, wchar_t characterToAppend)
Appends a character at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, const char *string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, const wchar_t *string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, const String &string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, StringRef string2)
Appends a string to the end of the first one.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, short number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, int number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, long number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, unsigned long number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, int64 number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, uint64 number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, float number)
Appends a decimal number at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String &string1, double number)
Appends a decimal number at the end of a string.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const char *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const wchar_t *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, const CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const char *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const wchar_t *string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, const CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator> (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator< (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator>= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator<= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
template<class traits >
std::basic_ostream< char,
traits > &JUCE_CALLTYPE operator<< (std::basic_ostream< char, traits > &stream, const String &stringToWrite)
This operator allows you to write a juce String directly to std output streams.
template<class traits >
std::basic_ostream< wchar_t,
traits > &JUCE_CALLTYPE operator<< (std::basic_ostream< wchar_t, traits > &stream, const String &stringToWrite)
This operator allows you to write a juce String directly to std output streams.
JUCE_API OutputStream
&JUCE_CALLTYPE operator<< (OutputStream &stream, const String &stringToWrite)
Writes a string to an OutputStream as UTF8.
JUCE_API OutputStream
&JUCE_CALLTYPE operator<< (OutputStream &stream, StringRef stringToWrite)
Writes a string to an OutputStream as UTF8.
JUCE_API bool JUCE_CALLTYPE operator== (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
String operator+ (String s1, StringRef s2)
String operator+ (StringRef s1, const String &s2)
String operator+ (const char *s1, StringRef s2)
String operator+ (StringRef s1, const char *s2)
Variables
NewLine newLine
A predefined object representing a new-line, which can be written to a string or stream.
Detailed Description
Class Documentation
struct Base64
Contains some static methods for converting between binary and the standard base-64 encoding format.
Static Public Member Functions
static bool convertToBase64 (OutputStream &base64Result, const void *sourceData, size_t sourceDataSize)
Converts a binary block of data into a base-64 string.
static bool convertFromBase64 (OutputStream &binaryOutput, StringRef base64TextInput)
Converts a base-64 string back to its binary representation.
static String toBase64 (const void *sourceData, size_t sourceDataSize)
Converts a block of binary data to a base-64 string.
static String toBase64 (const String &textToEncode)
Converts a string's UTF-8 representation to a base-64 string.
Member Function Documentation
static bool Base64::convertToBase64 (OutputStream & base64Result, const void * sourceData, size_t sourceDataSize) static
Converts a binary block of data into a base-64 string.
This will write the resulting string data to the given stream. If a write error occurs with the stream, the method will terminate and return false.
static bool Base64::convertFromBase64 (OutputStream & binaryOutput, StringRef base64TextInput) static
Converts a base-64 string back to its binary representation.
This will write the decoded binary data to the given stream. If the string is not valid base-64, the method will terminate and return false.
static String Base64::toBase64 (const void * sourceData, size_t sourceDataSize) static
Converts a block of binary data to a base-64 string.
static String Base64::toBase64 (const String & textToEncode) static
Converts a string's UTF-8 representation to a base-64 string.
class CharacterFunctions
A collection of functions for manipulating characters and character strings.
Most of these methods are designed for internal use by the String and CharPointer classes, but some of them may be useful to call directly.
See Also
String, CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Static Public Member Functions
static juce_wchar toUpperCase (juce_wchar character) noexcept
Converts a character to upper-case.
static juce_wchar toLowerCase (juce_wchar character) noexcept
Converts a character to lower-case.
static bool isUpperCase (juce_wchar character) noexcept
Checks whether a unicode character is upper-case.
static bool isLowerCase (juce_wchar character) noexcept
Checks whether a unicode character is lower-case.
static bool isWhitespace (char character) noexcept
Checks whether a character is whitespace.
static bool isWhitespace (juce_wchar character) noexcept
Checks whether a character is whitespace.
static bool isDigit (char character) noexcept
Checks whether a character is a digit.
static bool isDigit (juce_wchar character) noexcept
Checks whether a character is a digit.
static bool isLetter (char character) noexcept
Checks whether a character is alphabetic.
static bool isLetter (juce_wchar character) noexcept
Checks whether a character is alphabetic.
static bool isLetterOrDigit (char character) noexcept
Checks whether a character is alphabetic or numeric.
static bool isLetterOrDigit (juce_wchar character) noexcept
Checks whether a character is alphabetic or numeric.
static bool isPrintable (char character) noexcept
Checks whether a character is a printable character, i.e.
static bool isPrintable (juce_wchar character) noexcept
Checks whether a character is a printable character, i.e.
static int getHexDigitValue (juce_wchar digit) noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
static juce_wchar getUnicodeCharFromWindows1252Codepage (uint8 windows1252Char) noexcept
Converts a byte of Windows 1252 codepage to unicode.
template<typename CharPointerType >
static double readDoubleValue (CharPointerType &text) noexcept
Parses a character string to read a floating-point number.
template<typename CharPointerType >
static double getDoubleValue (CharPointerType text) noexcept
Parses a character string, to read a floating-point value.
template<typename IntType , typename CharPointerType >
static IntType getIntValue (const CharPointerType text) noexcept
Parses a character string, to read an integer value.
template<typename CharPointerType >
static size_t lengthUpTo (CharPointerType text, const size_t maxCharsToCount) noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
template<typename CharPointerType >
static size_t lengthUpTo (CharPointerType start, const CharPointerType end) noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
template<typename DestCharPointerType , typename SrcCharPointerType >
static void copyAll (DestCharPointerType &dest, SrcCharPointerType src) noexcept
Copies null-terminated characters from one string to another.
template<typename DestCharPointerType , typename SrcCharPointerType >
static size_t copyWithDestByteLimit (DestCharPointerType &dest, SrcCharPointerType src, size_t maxBytesToWrite) noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
template<typename DestCharPointerType , typename SrcCharPointerType >
static void copyWithCharLimit (DestCharPointerType &dest, SrcCharPointerType src, int maxChars) noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
static int compare (juce_wchar char1, juce_wchar char2) noexcept
Compares two characters.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compare (CharPointerType1 s1, CharPointerType2 s2) noexcept
Compares two null-terminated character strings.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
Compares two null-terminated character strings, up to a given number of characters.
static int compareIgnoreCase (juce_wchar char1, juce_wchar char2) noexcept
Compares two characters, using a case-independant match.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) noexcept
Compares two null-terminated character strings, using a case-independant match.
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
Compares two null-terminated character strings, using a case-independent match.
template<typename CharPointerType1 , typename CharPointerType2 >
static int indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
Finds the character index of a given substring in another string.
template<typename CharPointerType1 , typename CharPointerType2 >
static CharPointerType1 find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
Returns a pointer to the first occurrence of a substring in a string.
template<typename CharPointerType >
static CharPointerType find (CharPointerType textToSearch, const juce_wchar charToLookFor) noexcept
Returns a pointer to the first occurrence of a substring in a string.
template<typename CharPointerType1 , typename CharPointerType2 >
static int indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) noexcept
Finds the character index of a given substring in another string, using a case-independent match.
template<typename Type >
static int indexOfChar (Type text, const juce_wchar charToFind) noexcept
Finds the character index of a given character in another string.
template<typename Type >
static int indexOfCharIgnoreCase (Type text, juce_wchar charToFind) noexcept
Finds the character index of a given character in another string, using a case-independent match.
template<typename Type >
static Type findEndOfWhitespace (Type text) noexcept
Returns a pointer to the first non-whitespace character in a string.
template<typename Type , typename BreakType >
static Type findEndOfToken (Type text, BreakType breakCharacters, Type quoteCharacters)
Returns a pointer to the first character in the string which is found in the breakCharacters string.
Member Function Documentation
static juce_wchar CharacterFunctions::toUpperCase (juce_wchar character) static noexcept
Converts a character to upper-case.
Referenced by CharPointer_ASCII::toUpperCase(), CharPointer_UTF32::toUpperCase(), CharPointer_UTF16::toUpperCase(), and CharPointer_UTF8::toUpperCase().
static juce_wchar CharacterFunctions::toLowerCase (juce_wchar character) static noexcept
Converts a character to lower-case.
Referenced by indexOfCharIgnoreCase(), CharPointer_ASCII::toLowerCase(), CharPointer_UTF32::toLowerCase(), CharPointer_UTF16::toLowerCase(), and CharPointer_UTF8::toLowerCase().
static bool CharacterFunctions::isUpperCase (juce_wchar character) static noexcept
Checks whether a unicode character is upper-case.
Referenced by CharPointer_ASCII::isUpperCase(), CharPointer_UTF32::isUpperCase(), CharPointer_UTF16::isUpperCase(), and CharPointer_UTF8::isUpperCase().
static bool CharacterFunctions::isLowerCase (juce_wchar character) static noexcept
Checks whether a unicode character is lower-case.
Referenced by CharPointer_ASCII::isLowerCase(), CharPointer_UTF32::isLowerCase(), CharPointer_UTF16::isLowerCase(), and CharPointer_UTF8::isLowerCase().
static bool CharacterFunctions::isWhitespace (char character) static noexcept
Checks whether a character is whitespace.
Referenced by CharPointer_ASCII::isWhitespace(), CharPointer_UTF32::isWhitespace(), and CharPointer_UTF16::isWhitespace().
static bool CharacterFunctions::isWhitespace (juce_wchar character) static noexcept
Checks whether a character is whitespace.
static bool CharacterFunctions::isDigit (char character) static noexcept
Checks whether a character is a digit.
Referenced by CharPointer_ASCII::isDigit(), CharPointer_UTF32::isDigit(), and CharPointer_UTF16::isDigit().
static bool CharacterFunctions::isDigit (juce_wchar character) static noexcept
Checks whether a character is a digit.
static bool CharacterFunctions::isLetter (char character) static noexcept
Checks whether a character is alphabetic.
Referenced by CppTokeniserFunctions::isIdentifierStart(), CharPointer_ASCII::isLetter(), CharPointer_UTF32::isLetter(), CharPointer_UTF16::isLetter(), and CharPointer_UTF8::isLetter().
static bool CharacterFunctions::isLetter (juce_wchar character) static noexcept
Checks whether a character is alphabetic.
static bool CharacterFunctions::isLetterOrDigit (char character) static noexcept
Checks whether a character is alphabetic or numeric.
Referenced by CppTokeniserFunctions::isIdentifierBody(), CharPointer_ASCII::isLetterOrDigit(), CharPointer_UTF32::isLetterOrDigit(), CharPointer_UTF16::isLetterOrDigit(), CharPointer_UTF8::isLetterOrDigit(), and CppTokeniserFunctions::skipNumberSuffix().
static bool CharacterFunctions::isLetterOrDigit (juce_wchar character) static noexcept
Checks whether a character is alphabetic or numeric.
static bool CharacterFunctions::isPrintable (char character) static noexcept
Checks whether a character is a printable character, i.e.
alphabetic, numeric, a punctuation character or a space.
static bool CharacterFunctions::isPrintable (juce_wchar character) static noexcept
Checks whether a character is a printable character, i.e.
alphabetic, numeric, a punctuation character or a space.
static int CharacterFunctions::getHexDigitValue (juce_wchar digit) static noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
Referenced by CharacterFunctions::HexParser< ResultType >::parse(), and CppTokeniserFunctions::writeEscapeChars().
static juce_wchar CharacterFunctions::getUnicodeCharFromWindows1252Codepage (uint8 windows1252Char) static noexcept
Converts a byte of Windows 1252 codepage to unicode.
template<typename CharPointerType > static double CharacterFunctions::readDoubleValue (CharPointerType & text) static noexcept
Parses a character string to read a floating-point number.
Note that this will advance the pointer that is passed in, leaving it at the end of the number.
template<typename CharPointerType > static double CharacterFunctions::getDoubleValue (CharPointerType text) static noexcept
Parses a character string, to read a floating-point value.
Referenced by CharPointer_UTF32::getDoubleValue(), CharPointer_ASCII::getDoubleValue(), CharPointer_UTF16::getDoubleValue(), and CharPointer_UTF8::getDoubleValue().
template<typename IntType , typename CharPointerType > static IntType CharacterFunctions::getIntValue (const CharPointerType text) static noexcept
Parses a character string, to read an integer value.
template<typename CharPointerType > static size_t CharacterFunctions::lengthUpTo (CharPointerType text, const size_t maxCharsToCount) static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
Referenced by CharPointer_ASCII::lengthUpTo(), CharPointer_UTF32::lengthUpTo(), CharPointer_UTF16::lengthUpTo(), and CharPointer_UTF8::lengthUpTo().
template<typename CharPointerType > static size_t CharacterFunctions::lengthUpTo (CharPointerType start, const CharPointerType end) static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
template<typename DestCharPointerType , typename SrcCharPointerType > static void CharacterFunctions::copyAll (DestCharPointerType & dest, SrcCharPointerType src) static noexcept
Copies null-terminated characters from one string to another.
Referenced by CharPointer_ASCII::writeAll(), CharPointer_UTF32::writeAll(), CharPointer_UTF16::writeAll(), and CharPointer_UTF8::writeAll().
template<typename DestCharPointerType , typename SrcCharPointerType > static size_t CharacterFunctions::copyWithDestByteLimit (DestCharPointerType & dest, SrcCharPointerType src, size_t maxBytesToWrite) static noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
References getAddressDifference().
Referenced by CharPointer_ASCII::writeWithDestByteLimit(), CharPointer_UTF32::writeWithDestByteLimit(), CharPointer_UTF16::writeWithDestByteLimit(), and CharPointer_UTF8::writeWithDestByteLimit().
template<typename DestCharPointerType , typename SrcCharPointerType > static void CharacterFunctions::copyWithCharLimit (DestCharPointerType & dest, SrcCharPointerType src, int maxChars) static noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
Referenced by CharPointer_ASCII::writeWithCharLimit(), CharPointer_UTF32::writeWithCharLimit(), CharPointer_UTF16::writeWithCharLimit(), and CharPointer_UTF8::writeWithCharLimit().
static int CharacterFunctions::compare (juce_wchar char1, juce_wchar char2) static noexcept
Compares two characters.
Referenced by CharPointer_ASCII::compare(), CharPointer_UTF32::compare(), CharPointer_UTF16::compare(), and CharPointer_UTF8::compare().
template<typename CharPointerType1 , typename CharPointerType2 > static int CharacterFunctions::compare (CharPointerType1 s1, CharPointerType2 s2) static noexcept
Compares two null-terminated character strings.
template<typename CharPointerType1 , typename CharPointerType2 > static int CharacterFunctions::compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) static noexcept
Compares two null-terminated character strings, up to a given number of characters.
Referenced by CharPointer_ASCII::compareUpTo(), CharPointer_UTF32::compareUpTo(), CharPointer_UTF16::compareUpTo(), and CharPointer_UTF8::compareUpTo().
static int CharacterFunctions::compareIgnoreCase (juce_wchar char1, juce_wchar char2) static noexcept
Compares two characters, using a case-independant match.
Referenced by CharPointer_ASCII::compareIgnoreCase(), CharPointer_UTF32::compareIgnoreCase(), CharPointer_UTF16::compareIgnoreCase(), and CharPointer_UTF8::compareIgnoreCase().
template<typename CharPointerType1 , typename CharPointerType2 > static int CharacterFunctions::compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) static noexcept
Compares two null-terminated character strings, using a case-independant match.
template<typename CharPointerType1 , typename CharPointerType2 > static int CharacterFunctions::compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) static noexcept
Compares two null-terminated character strings, using a case-independent match.
Referenced by CharPointer_ASCII::compareIgnoreCaseUpTo(), CharPointer_UTF32::compareIgnoreCaseUpTo(), CharPointer_UTF16::compareIgnoreCaseUpTo(), and CharPointer_UTF8::compareIgnoreCaseUpTo().
template<typename CharPointerType1 , typename CharPointerType2 > static int CharacterFunctions::indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) static noexcept
Finds the character index of a given substring in another string.
Returns -1 if the substring is not found.
Referenced by CharPointer_ASCII::indexOf(), CharPointer_UTF32::indexOf(), CharPointer_UTF16::indexOf(), and CharPointer_UTF8::indexOf().
template<typename CharPointerType1 , typename CharPointerType2 > static CharPointerType1 CharacterFunctions::find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) static noexcept
Returns a pointer to the first occurrence of a substring in a string.
If the substring is not found, this will return a pointer to the string's null terminator.
template<typename CharPointerType > static CharPointerType CharacterFunctions::find (CharPointerType textToSearch, const juce_wchar charToLookFor) static noexcept
Returns a pointer to the first occurrence of a substring in a string.
If the substring is not found, this will return a pointer to the string's null terminator.
template<typename CharPointerType1 , typename CharPointerType2 > static int CharacterFunctions::indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) static noexcept
Finds the character index of a given substring in another string, using a case-independent match.
Returns -1 if the substring is not found.
template<typename Type > static int CharacterFunctions::indexOfChar (Type text, const juce_wchar charToFind) static noexcept
Finds the character index of a given character in another string.
Returns -1 if the character is not found.
Referenced by CharPointer_ASCII::indexOf(), CharPointer_UTF32::indexOf(), CharPointer_UTF16::indexOf(), and CharPointer_UTF8::indexOf().
template<typename Type > static int CharacterFunctions::indexOfCharIgnoreCase (Type text, juce_wchar charToFind) static noexcept
Finds the character index of a given character in another string, using a case-independent match.
Returns -1 if the character is not found.
References toLowerCase().
Referenced by CharPointer_ASCII::indexOf(), CharPointer_UTF32::indexOf(), CharPointer_UTF16::indexOf(), and CharPointer_UTF8::indexOf().
template<typename Type > static Type CharacterFunctions::findEndOfWhitespace (Type text) static noexcept
Returns a pointer to the first non-whitespace character in a string.
If the string contains only whitespace, this will return a pointer to its null terminator.
Referenced by CharPointer_UTF32::findEndOfWhitespace(), CharPointer_ASCII::findEndOfWhitespace(), CharPointer_UTF16::findEndOfWhitespace(), and CharPointer_UTF8::findEndOfWhitespace().
template<typename Type , typename BreakType > static Type CharacterFunctions::findEndOfToken (Type text, BreakType breakCharacters, Type quoteCharacters) static
Returns a pointer to the first character in the string which is found in the breakCharacters string.
class CharPointer_ASCII
Wraps a pointer to a null-terminated ASCII character string, and provides various methods to operate on the data.
A valid ASCII string is assumed to not contain any characters above 127.
See Also
CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Public Types
typedef char CharType
Public Member Functions
CharPointer_ASCII (const CharType *rawPointer) noexcept
CharPointer_ASCII (const CharPointer_ASCII &other) noexcept
CharPointer_ASCII operator= (const CharPointer_ASCII other) noexcept
CharPointer_ASCII operator= (const CharType *text) noexcept
bool operator== (CharPointer_ASCII other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_ASCII other) const noexcept
bool operator<= (CharPointer_ASCII other) const noexcept
bool operator< (CharPointer_ASCII other) const noexcept
bool operator>= (CharPointer_ASCII other) const noexcept
bool operator> (CharPointer_ASCII other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_ASCII operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_ASCII operator-- () noexcept
Moves this pointer to the previous character in the string.
juce_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_ASCII operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (const int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (const int numToSkip) noexcept
juce_wchar operator[] (const int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_ASCII operator+ (const int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_ASCII operator- (const int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void write (const juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void replaceChar (const juce_wchar newChar) noexcept
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (const CharPointer_ASCII end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_ASCII findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
template<typename CharPointer >
void writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
int compare (const CharPointer other) const noexcept
Compares this string with another one.
int compare (const CharPointer_ASCII other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
int compareUpTo (const CharPointer_ASCII other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int compareIgnoreCase (const CharPointer other) const
Compares this string with another one.
int compareIgnoreCase (const CharPointer_ASCII other) const
template<typename CharPointer >
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (const juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (const juce_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const
Returns true if the first character of this string is whitespace.
bool isDigit () const
Returns true if the first character of this string is a digit.
bool isLetter () const
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const
Returns true if the first character of this string is upper-case.
bool isLowerCase () const
Returns true if the first character of this string is lower-case.
juce_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
juce_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_ASCII findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
Static Public Member Functions
static size_t getBytesRequiredFor (const juce_wchar) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer >
static size_t getBytesRequiredFor (const CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (juce_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
Member Typedef Documentation
typedef char CharPointer_ASCII::CharType
Constructor & Destructor Documentation
CharPointer_ASCII::CharPointer_ASCII (const CharType * rawPointer) explicit noexcept
Referenced by findTerminatingNull(), operator+(), and operator-().
CharPointer_ASCII::CharPointer_ASCII (const CharPointer_ASCII & other) noexcept
Member Function Documentation
CharPointer_ASCII CharPointer_ASCII::operator= (const CharPointer_ASCII other) noexcept
CharPointer_ASCII CharPointer_ASCII::operator= (const CharType * text) noexcept
bool CharPointer_ASCII::operator== (CharPointer_ASCII other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool CharPointer_ASCII::operator!= (CharPointer_ASCII other) const noexcept
bool CharPointer_ASCII::operator<= (CharPointer_ASCII other) const noexcept
bool CharPointer_ASCII::operator< (CharPointer_ASCII other) const noexcept
bool CharPointer_ASCII::operator>= (CharPointer_ASCII other) const noexcept
bool CharPointer_ASCII::operator> (CharPointer_ASCII other) const noexcept
CharType* CharPointer_ASCII::getAddress () const noexcept
Returns the address that this pointer is pointing to.
Referenced by String::appendCharPointer().
CharPointer_ASCII::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool CharPointer_ASCII::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
Referenced by String::isEmpty(), and String::isNotEmpty().
bool CharPointer_ASCII::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar CharPointer_ASCII::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_ASCII CharPointer_ASCII::operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_ASCII CharPointer_ASCII::operator-- () noexcept
Moves this pointer to the previous character in the string.
juce_wchar CharPointer_ASCII::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_ASCII CharPointer_ASCII::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void CharPointer_ASCII::operator+= (const int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void CharPointer_ASCII::operator-= (const int numToSkip) noexcept
juce_wchar CharPointer_ASCII::operator[] (const int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_ASCII CharPointer_ASCII::operator+ (const int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
References CharPointer_ASCII().
CharPointer_ASCII CharPointer_ASCII::operator- (const int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
References CharPointer_ASCII().
void CharPointer_ASCII::write (const juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void CharPointer_ASCII::replaceChar (const juce_wchar newChar) noexcept
void CharPointer_ASCII::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t CharPointer_ASCII::length () const noexcept
Returns the number of characters in this string.
Referenced by findTerminatingNull(), and sizeInBytes().
size_t CharPointer_ASCII::lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_ASCII::lengthUpTo (const CharPointer_ASCII end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_ASCII::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
References length().
static size_t CharPointer_ASCII::getBytesRequiredFor (const juce_wchar) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer > static size_t CharPointer_ASCII::getBytesRequiredFor (const CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
CharPointer_ASCII CharPointer_ASCII::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_ASCII(), and length().
template<typename CharPointer > void CharPointer_ASCII::writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References CharacterFunctions::copyAll().
template<typename CharPointer > size_t CharPointer_ASCII::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References CharacterFunctions::copyWithDestByteLimit().
template<typename CharPointer > void CharPointer_ASCII::writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References CharacterFunctions::copyWithCharLimit().
template<typename CharPointer > int CharPointer_ASCII::compare (const CharPointer other) const noexcept
Compares this string with another one.
References CharacterFunctions::compare().
int CharPointer_ASCII::compare (const CharPointer_ASCII other) const noexcept
Compares this string with another one.
template<typename CharPointer > int CharPointer_ASCII::compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareUpTo().
int CharPointer_ASCII::compareUpTo (const CharPointer_ASCII other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer > int CharPointer_ASCII::compareIgnoreCase (const CharPointer other) const
Compares this string with another one.
References CharacterFunctions::compareIgnoreCase().
int CharPointer_ASCII::compareIgnoreCase (const CharPointer_ASCII other) const
References CharacterFunctions::compareIgnoreCase().
template<typename CharPointer > int CharPointer_ASCII::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareIgnoreCaseUpTo().
template<typename CharPointer > int CharPointer_ASCII::indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References CharacterFunctions::indexOf().
int CharPointer_ASCII::indexOf (const juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int CharPointer_ASCII::indexOf (const juce_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References CharacterFunctions::indexOfChar(), and CharacterFunctions::indexOfCharIgnoreCase().
bool CharPointer_ASCII::isWhitespace () const
Returns true if the first character of this string is whitespace.
References CharacterFunctions::isWhitespace().
bool CharPointer_ASCII::isDigit () const
Returns true if the first character of this string is a digit.
References CharacterFunctions::isDigit().
bool CharPointer_ASCII::isLetter () const
Returns true if the first character of this string is a letter.
References CharacterFunctions::isLetter().
bool CharPointer_ASCII::isLetterOrDigit () const
Returns true if the first character of this string is a letter or digit.
References CharacterFunctions::isLetterOrDigit().
bool CharPointer_ASCII::isUpperCase () const
Returns true if the first character of this string is upper-case.
References CharacterFunctions::isUpperCase().
bool CharPointer_ASCII::isLowerCase () const
Returns true if the first character of this string is lower-case.
References CharacterFunctions::isLowerCase().
juce_wchar CharPointer_ASCII::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References CharacterFunctions::toUpperCase().
juce_wchar CharPointer_ASCII::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References CharacterFunctions::toLowerCase().
int CharPointer_ASCII::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 CharPointer_ASCII::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double CharPointer_ASCII::getDoubleValue () const noexcept
Parses this string as a floating point double.
References CharacterFunctions::getDoubleValue().
CharPointer_ASCII CharPointer_ASCII::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References CharacterFunctions::findEndOfWhitespace().
static bool CharPointer_ASCII::canRepresent (juce_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool CharPointer_ASCII::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
class CharPointer_UTF16
Wraps a pointer to a null-terminated UTF-16 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF8, CharPointer_UTF32
Public Types
enum { byteOrderMarkBE1 = 0xfe, byteOrderMarkBE2 = 0xff, byteOrderMarkLE1 = 0xff, byteOrderMarkLE2 = 0xfe }
These values are the byte-order-mark (BOM) values for a UTF-16 stream.
typedef int16 CharType
Public Member Functions
CharPointer_UTF16 (const CharType *rawPointer) noexcept
CharPointer_UTF16 (const CharPointer_UTF16 &other) noexcept
CharPointer_UTF16 operator= (CharPointer_UTF16 other) noexcept
CharPointer_UTF16 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF16 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_UTF16 other) const noexcept
bool operator<= (CharPointer_UTF16 other) const noexcept
bool operator< (CharPointer_UTF16 other) const noexcept
bool operator>= (CharPointer_UTF16 other) const noexcept
bool operator> (CharPointer_UTF16 other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF16 operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF16 operator-- () noexcept
Moves this pointer back to the previous character in the string.
juce_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF16 operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
juce_wchar operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF16 operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF16 operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void write (juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (CharPointer_UTF16 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_UTF16 findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
template<typename CharPointer >
void writeAll (CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
void writeAll (CharPointer_UTF16 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
size_t writeWithDestByteLimit (CharPointer src, size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
void writeWithCharLimit (CharPointer src, int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
int compare (CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int compareIgnoreCase (CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareIgnoreCaseUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int indexOf (CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (juce_wchar charToFind, bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
bool isDigit () const noexcept
Returns true if the first character of this string is a digit.
bool isLetter () const noexcept
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
bool isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
juce_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
juce_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_UTF16 findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
CharPointer_UTF16 atomicSwap (CharPointer_UTF16 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
Static Public Member Functions
static size_t getBytesRequiredFor (juce_wchar charToWrite) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer >
static size_t getBytesRequiredFor (CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (juce_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
static bool isByteOrderMarkBigEndian (const void *possibleByteOrder) noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (big endian).
static bool isByteOrderMarkLittleEndian (const void *possibleByteOrder) noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (little endian).
Member Typedef Documentation
typedef int16 CharPointer_UTF16::CharType
Member Enumeration Documentation
anonymous enum
These values are the byte-order-mark (BOM) values for a UTF-16 stream.
Enumerator
byteOrderMarkBE1
byteOrderMarkBE2
byteOrderMarkLE1
byteOrderMarkLE2
Constructor & Destructor Documentation
CharPointer_UTF16::CharPointer_UTF16 (const CharType * rawPointer) explicit noexcept
Referenced by atomicSwap(), and findTerminatingNull().
CharPointer_UTF16::CharPointer_UTF16 (const CharPointer_UTF16 & other) noexcept
Member Function Documentation
CharPointer_UTF16 CharPointer_UTF16::operator= (CharPointer_UTF16 other) noexcept
CharPointer_UTF16 CharPointer_UTF16::operator= (const CharType * text) noexcept
bool CharPointer_UTF16::operator== (CharPointer_UTF16 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool CharPointer_UTF16::operator!= (CharPointer_UTF16 other) const noexcept
bool CharPointer_UTF16::operator<= (CharPointer_UTF16 other) const noexcept
bool CharPointer_UTF16::operator< (CharPointer_UTF16 other) const noexcept
bool CharPointer_UTF16::operator>= (CharPointer_UTF16 other) const noexcept
bool CharPointer_UTF16::operator> (CharPointer_UTF16 other) const noexcept
CharType* CharPointer_UTF16::getAddress () const noexcept
Returns the address that this pointer is pointing to.
CharPointer_UTF16::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool CharPointer_UTF16::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool CharPointer_UTF16::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar CharPointer_UTF16::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF16 CharPointer_UTF16::operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF16 CharPointer_UTF16::operator-- () noexcept
Moves this pointer back to the previous character in the string.
juce_wchar CharPointer_UTF16::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF16 CharPointer_UTF16::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void CharPointer_UTF16::operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
Referenced by operator-=().
void CharPointer_UTF16::operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
References operator+=().
juce_wchar CharPointer_UTF16::operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF16 CharPointer_UTF16::operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF16 CharPointer_UTF16::operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void CharPointer_UTF16::write (juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void CharPointer_UTF16::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t CharPointer_UTF16::length () const noexcept
Returns the number of characters in this string.
size_t CharPointer_UTF16::lengthUpTo (size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_UTF16::lengthUpTo (CharPointer_UTF16 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_UTF16::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
static size_t CharPointer_UTF16::getBytesRequiredFor (juce_wchar charToWrite) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Referenced by getBytesRequiredFor().
template<class CharPointer > static size_t CharPointer_UTF16::getBytesRequiredFor (CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
References getBytesRequiredFor().
CharPointer_UTF16 CharPointer_UTF16::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_UTF16().
template<typename CharPointer > void CharPointer_UTF16::writeAll (CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References CharacterFunctions::copyAll().
void CharPointer_UTF16::writeAll (CharPointer_UTF16 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer > size_t CharPointer_UTF16::writeWithDestByteLimit (CharPointer src, size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References CharacterFunctions::copyWithDestByteLimit().
template<typename CharPointer > void CharPointer_UTF16::writeWithCharLimit (CharPointer src, int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References CharacterFunctions::copyWithCharLimit().
template<typename CharPointer > int CharPointer_UTF16::compare (CharPointer other) const noexcept
Compares this string with another one.
References CharacterFunctions::compare().
template<typename CharPointer > int CharPointer_UTF16::compareUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareUpTo().
template<typename CharPointer > int CharPointer_UTF16::compareIgnoreCase (CharPointer other) const noexcept
Compares this string with another one.
References CharacterFunctions::compareIgnoreCase().
template<typename CharPointer > int CharPointer_UTF16::compareIgnoreCaseUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareIgnoreCaseUpTo().
template<typename CharPointer > int CharPointer_UTF16::indexOf (CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References CharacterFunctions::indexOf().
int CharPointer_UTF16::indexOf (juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References CharacterFunctions::indexOfChar().
int CharPointer_UTF16::indexOf (juce_wchar charToFind, bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References CharacterFunctions::indexOfChar(), and CharacterFunctions::indexOfCharIgnoreCase().
bool CharPointer_UTF16::isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
References CharacterFunctions::isWhitespace().
bool CharPointer_UTF16::isDigit () const noexcept
Returns true if the first character of this string is a digit.
References CharacterFunctions::isDigit().
bool CharPointer_UTF16::isLetter () const noexcept
Returns true if the first character of this string is a letter.
References CharacterFunctions::isLetter().
bool CharPointer_UTF16::isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
References CharacterFunctions::isLetterOrDigit().
bool CharPointer_UTF16::isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
References CharacterFunctions::isUpperCase().
bool CharPointer_UTF16::isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
References CharacterFunctions::isLowerCase().
juce_wchar CharPointer_UTF16::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References CharacterFunctions::toUpperCase().
juce_wchar CharPointer_UTF16::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References CharacterFunctions::toLowerCase().
int CharPointer_UTF16::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 CharPointer_UTF16::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double CharPointer_UTF16::getDoubleValue () const noexcept
Parses this string as a floating point double.
References CharacterFunctions::getDoubleValue().
CharPointer_UTF16 CharPointer_UTF16::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References CharacterFunctions::findEndOfWhitespace().
static bool CharPointer_UTF16::canRepresent (juce_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool CharPointer_UTF16::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
CharPointer_UTF16 CharPointer_UTF16::atomicSwap (CharPointer_UTF16 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
References CharPointer_UTF16().
static bool CharPointer_UTF16::isByteOrderMarkBigEndian (const void * possibleByteOrder) static noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (big endian).
The pointer must not be null, and must contain at least two valid bytes.
References byteOrderMarkBE1, byteOrderMarkBE2, and jassert.
static bool CharPointer_UTF16::isByteOrderMarkLittleEndian (const void * possibleByteOrder) static noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (little endian).
The pointer must not be null, and must contain at least two valid bytes.
References byteOrderMarkLE1, byteOrderMarkLE2, and jassert.
class CharPointer_UTF32
Wraps a pointer to a null-terminated UTF-32 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF8, CharPointer_UTF16
Public Types
typedef juce_wchar CharType
Public Member Functions
CharPointer_UTF32 (const CharType *rawPointer) noexcept
CharPointer_UTF32 (const CharPointer_UTF32 &other) noexcept
CharPointer_UTF32 operator= (CharPointer_UTF32 other) noexcept
CharPointer_UTF32 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF32 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_UTF32 other) const noexcept
bool operator<= (CharPointer_UTF32 other) const noexcept
bool operator< (CharPointer_UTF32 other) const noexcept
bool operator>= (CharPointer_UTF32 other) const noexcept
bool operator> (CharPointer_UTF32 other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF32 operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF32 operator-- () noexcept
Moves this pointer to the previous character in the string.
juce_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF32 operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (int numToSkip) noexcept
juce_wchar & operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF32 operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF32 operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void write (juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void replaceChar (juce_wchar newChar) noexcept
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (CharPointer_UTF32 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_UTF32 findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
template<typename CharPointer >
void writeAll (CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
void writeAll (CharPointer_UTF32 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
size_t writeWithDestByteLimit (CharPointer src, size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
void writeWithCharLimit (CharPointer src, int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
int compare (CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int compareIgnoreCase (CharPointer other) const
Compares this string with another one.
template<typename CharPointer >
int compareIgnoreCaseUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int indexOf (CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (juce_wchar charToFind, bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const
Returns true if the first character of this string is whitespace.
bool isDigit () const
Returns true if the first character of this string is a digit.
bool isLetter () const
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const
Returns true if the first character of this string is upper-case.
bool isLowerCase () const
Returns true if the first character of this string is lower-case.
juce_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
juce_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_UTF32 findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
CharPointer_UTF32 atomicSwap (CharPointer_UTF32 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
Static Public Member Functions
static size_t getBytesRequiredFor (juce_wchar) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer >
static size_t getBytesRequiredFor (CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (juce_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
Member Typedef Documentation
typedef juce_wchar CharPointer_UTF32::CharType
Constructor & Destructor Documentation
CharPointer_UTF32::CharPointer_UTF32 (const CharType * rawPointer) explicit noexcept
Referenced by atomicSwap(), findTerminatingNull(), operator+(), and operator-().
CharPointer_UTF32::CharPointer_UTF32 (const CharPointer_UTF32 & other) noexcept
Member Function Documentation
CharPointer_UTF32 CharPointer_UTF32::operator= (CharPointer_UTF32 other) noexcept
CharPointer_UTF32 CharPointer_UTF32::operator= (const CharType * text) noexcept
bool CharPointer_UTF32::operator== (CharPointer_UTF32 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool CharPointer_UTF32::operator!= (CharPointer_UTF32 other) const noexcept
bool CharPointer_UTF32::operator<= (CharPointer_UTF32 other) const noexcept
bool CharPointer_UTF32::operator< (CharPointer_UTF32 other) const noexcept
bool CharPointer_UTF32::operator>= (CharPointer_UTF32 other) const noexcept
bool CharPointer_UTF32::operator> (CharPointer_UTF32 other) const noexcept
CharType* CharPointer_UTF32::getAddress () const noexcept
Returns the address that this pointer is pointing to.
CharPointer_UTF32::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool CharPointer_UTF32::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool CharPointer_UTF32::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar CharPointer_UTF32::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF32 CharPointer_UTF32::operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF32 CharPointer_UTF32::operator-- () noexcept
Moves this pointer to the previous character in the string.
juce_wchar CharPointer_UTF32::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF32 CharPointer_UTF32::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void CharPointer_UTF32::operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void CharPointer_UTF32::operator-= (int numToSkip) noexcept
juce_wchar& CharPointer_UTF32::operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF32 CharPointer_UTF32::operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
References CharPointer_UTF32().
CharPointer_UTF32 CharPointer_UTF32::operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
References CharPointer_UTF32().
void CharPointer_UTF32::write (juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void CharPointer_UTF32::replaceChar (juce_wchar newChar) noexcept
void CharPointer_UTF32::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t CharPointer_UTF32::length () const noexcept
Returns the number of characters in this string.
Referenced by findTerminatingNull(), and sizeInBytes().
size_t CharPointer_UTF32::lengthUpTo (size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_UTF32::lengthUpTo (CharPointer_UTF32 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_UTF32::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
References length().
static size_t CharPointer_UTF32::getBytesRequiredFor (juce_wchar) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer > static size_t CharPointer_UTF32::getBytesRequiredFor (CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
CharPointer_UTF32 CharPointer_UTF32::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_UTF32(), and length().
template<typename CharPointer > void CharPointer_UTF32::writeAll (CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References CharacterFunctions::copyAll().
void CharPointer_UTF32::writeAll (CharPointer_UTF32 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer > size_t CharPointer_UTF32::writeWithDestByteLimit (CharPointer src, size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References CharacterFunctions::copyWithDestByteLimit().
template<typename CharPointer > void CharPointer_UTF32::writeWithCharLimit (CharPointer src, int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References CharacterFunctions::copyWithCharLimit().
template<typename CharPointer > int CharPointer_UTF32::compare (CharPointer other) const noexcept
Compares this string with another one.
References CharacterFunctions::compare().
template<typename CharPointer > int CharPointer_UTF32::compareUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareUpTo().
template<typename CharPointer > int CharPointer_UTF32::compareIgnoreCase (CharPointer other) const
Compares this string with another one.
References CharacterFunctions::compareIgnoreCase().
template<typename CharPointer > int CharPointer_UTF32::compareIgnoreCaseUpTo (CharPointer other, int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareIgnoreCaseUpTo().
template<typename CharPointer > int CharPointer_UTF32::indexOf (CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References CharacterFunctions::indexOf().
int CharPointer_UTF32::indexOf (juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int CharPointer_UTF32::indexOf (juce_wchar charToFind, bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References CharacterFunctions::indexOfChar(), and CharacterFunctions::indexOfCharIgnoreCase().
bool CharPointer_UTF32::isWhitespace () const
Returns true if the first character of this string is whitespace.
References CharacterFunctions::isWhitespace().
bool CharPointer_UTF32::isDigit () const
Returns true if the first character of this string is a digit.
References CharacterFunctions::isDigit().
bool CharPointer_UTF32::isLetter () const
Returns true if the first character of this string is a letter.
References CharacterFunctions::isLetter().
bool CharPointer_UTF32::isLetterOrDigit () const
Returns true if the first character of this string is a letter or digit.
References CharacterFunctions::isLetterOrDigit().
bool CharPointer_UTF32::isUpperCase () const
Returns true if the first character of this string is upper-case.
References CharacterFunctions::isUpperCase().
bool CharPointer_UTF32::isLowerCase () const
Returns true if the first character of this string is lower-case.
References CharacterFunctions::isLowerCase().
juce_wchar CharPointer_UTF32::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References CharacterFunctions::toUpperCase().
juce_wchar CharPointer_UTF32::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References CharacterFunctions::toLowerCase().
int CharPointer_UTF32::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 CharPointer_UTF32::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double CharPointer_UTF32::getDoubleValue () const noexcept
Parses this string as a floating point double.
References CharacterFunctions::getDoubleValue().
CharPointer_UTF32 CharPointer_UTF32::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References CharacterFunctions::findEndOfWhitespace().
static bool CharPointer_UTF32::canRepresent (juce_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
Referenced by isValidString().
static bool CharPointer_UTF32::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
References canRepresent().
CharPointer_UTF32 CharPointer_UTF32::atomicSwap (CharPointer_UTF32 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
References CharPointer_UTF32().
class CharPointer_UTF8
Wraps a pointer to a null-terminated UTF-8 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF16, CharPointer_UTF32
Public Types
enum { byteOrderMark1 = 0xef, byteOrderMark2 = 0xbb, byteOrderMark3 = 0xbf }
These values are the byte-order mark (BOM) values for a UTF-8 stream.
typedef char CharType
Public Member Functions
CharPointer_UTF8 (const CharType *rawPointer) noexcept
CharPointer_UTF8 (const CharPointer_UTF8 &other) noexcept
CharPointer_UTF8 operator= (CharPointer_UTF8 other) noexcept
CharPointer_UTF8 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF8 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_UTF8 other) const noexcept
bool operator<= (CharPointer_UTF8 other) const noexcept
bool operator< (CharPointer_UTF8 other) const noexcept
bool operator>= (CharPointer_UTF8 other) const noexcept
bool operator> (CharPointer_UTF8 other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF8 & operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF8 operator-- () noexcept
Moves this pointer back to the previous character in the string.
juce_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF8 operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
juce_wchar operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF8 operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF8 operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (const CharPointer_UTF8 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_UTF8 findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
void write (const juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
template<typename CharPointer >
void writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
void writeAll (const CharPointer_UTF8 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer >
int compare (const CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int compareIgnoreCase (const CharPointer other) const noexcept
Compares this string with another one.
int compareIgnoreCase (const CharPointer_UTF8 other) const noexcept
Compares this string with another one.
template<typename CharPointer >
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer >
int indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (const juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (const juce_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
bool isDigit () const noexcept
Returns true if the first character of this string is a digit.
bool isLetter () const noexcept
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
bool isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
juce_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
juce_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_UTF8 findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
CharPointer_UTF8 atomicSwap (const CharPointer_UTF8 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
Static Public Member Functions
static size_t getBytesRequiredFor (const juce_wchar charToWrite) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer >
static size_t getBytesRequiredFor (CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (juce_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
static bool isByteOrderMark (const void *possibleByteOrder) noexcept
Returns true if the first three bytes in this pointer are the UTF8 byte-order mark (BOM).
Member Typedef Documentation
typedef char CharPointer_UTF8::CharType
Member Enumeration Documentation
anonymous enum
These values are the byte-order mark (BOM) values for a UTF-8 stream.
Enumerator
byteOrderMark1
byteOrderMark2
byteOrderMark3
Constructor & Destructor Documentation
CharPointer_UTF8::CharPointer_UTF8 (const CharType * rawPointer) explicit noexcept
Referenced by atomicSwap(), and findTerminatingNull().
CharPointer_UTF8::CharPointer_UTF8 (const CharPointer_UTF8 & other) noexcept
Member Function Documentation
CharPointer_UTF8 CharPointer_UTF8::operator= (CharPointer_UTF8 other) noexcept
CharPointer_UTF8 CharPointer_UTF8::operator= (const CharType * text) noexcept
bool CharPointer_UTF8::operator== (CharPointer_UTF8 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool CharPointer_UTF8::operator!= (CharPointer_UTF8 other) const noexcept
bool CharPointer_UTF8::operator<= (CharPointer_UTF8 other) const noexcept
bool CharPointer_UTF8::operator< (CharPointer_UTF8 other) const noexcept
bool CharPointer_UTF8::operator>= (CharPointer_UTF8 other) const noexcept
bool CharPointer_UTF8::operator> (CharPointer_UTF8 other) const noexcept
CharType* CharPointer_UTF8::getAddress () const noexcept
Returns the address that this pointer is pointing to.
CharPointer_UTF8::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool CharPointer_UTF8::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
Referenced by CppTokeniserFunctions::StringIterator::isEOF().
bool CharPointer_UTF8::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
juce_wchar CharPointer_UTF8::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF8& CharPointer_UTF8::operator++ () noexcept
Moves this pointer along to the next character in the string.
References jassert.
CharPointer_UTF8 CharPointer_UTF8::operator-- () noexcept
Moves this pointer back to the previous character in the string.
juce_wchar CharPointer_UTF8::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
Referenced by CppTokeniserFunctions::StringIterator::nextChar().
CharPointer_UTF8 CharPointer_UTF8::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void CharPointer_UTF8::operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
Referenced by operator-=().
void CharPointer_UTF8::operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
References operator+=().
juce_wchar CharPointer_UTF8::operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF8 CharPointer_UTF8::operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF8 CharPointer_UTF8::operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
size_t CharPointer_UTF8::length () const noexcept
Returns the number of characters in this string.
size_t CharPointer_UTF8::lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_UTF8::lengthUpTo (const CharPointer_UTF8 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References CharacterFunctions::lengthUpTo().
size_t CharPointer_UTF8::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
References jassert.
static size_t CharPointer_UTF8::getBytesRequiredFor (const juce_wchar charToWrite) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Referenced by getBytesRequiredFor().
template<class CharPointer > static size_t CharPointer_UTF8::getBytesRequiredFor (CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
References getBytesRequiredFor().
CharPointer_UTF8 CharPointer_UTF8::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_UTF8().
void CharPointer_UTF8::write (const juce_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
Referenced by CppTokeniserFunctions::parseIdentifier().
void CharPointer_UTF8::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
Referenced by CppTokeniserFunctions::parseIdentifier().
template<typename CharPointer > void CharPointer_UTF8::writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References CharacterFunctions::copyAll().
void CharPointer_UTF8::writeAll (const CharPointer_UTF8 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer > size_t CharPointer_UTF8::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References CharacterFunctions::copyWithDestByteLimit().
template<typename CharPointer > void CharPointer_UTF8::writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References CharacterFunctions::copyWithCharLimit().
template<typename CharPointer > int CharPointer_UTF8::compare (const CharPointer other) const noexcept
Compares this string with another one.
References CharacterFunctions::compare().
template<typename CharPointer > int CharPointer_UTF8::compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareUpTo().
template<typename CharPointer > int CharPointer_UTF8::compareIgnoreCase (const CharPointer other) const noexcept
Compares this string with another one.
References CharacterFunctions::compareIgnoreCase().
int CharPointer_UTF8::compareIgnoreCase (const CharPointer_UTF8 other) const noexcept
Compares this string with another one.
References CharacterFunctions::compareIgnoreCase().
template<typename CharPointer > int CharPointer_UTF8::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharacterFunctions::compareIgnoreCaseUpTo().
template<typename CharPointer > int CharPointer_UTF8::indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References CharacterFunctions::indexOf().
int CharPointer_UTF8::indexOf (const juce_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References CharacterFunctions::indexOfChar().
int CharPointer_UTF8::indexOf (const juce_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References CharacterFunctions::indexOfChar(), and CharacterFunctions::indexOfCharIgnoreCase().
bool CharPointer_UTF8::isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
Referenced by CppTokeniserFunctions::StringIterator::skipWhitespace().
bool CharPointer_UTF8::isDigit () const noexcept
Returns true if the first character of this string is a digit.
bool CharPointer_UTF8::isLetter () const noexcept
Returns true if the first character of this string is a letter.
References CharacterFunctions::isLetter().
bool CharPointer_UTF8::isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
References CharacterFunctions::isLetterOrDigit().
bool CharPointer_UTF8::isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
References CharacterFunctions::isUpperCase().
bool CharPointer_UTF8::isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
References CharacterFunctions::isLowerCase().
juce_wchar CharPointer_UTF8::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References CharacterFunctions::toUpperCase().
juce_wchar CharPointer_UTF8::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References CharacterFunctions::toLowerCase().
int CharPointer_UTF8::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 CharPointer_UTF8::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double CharPointer_UTF8::getDoubleValue () const noexcept
Parses this string as a floating point double.
References CharacterFunctions::getDoubleValue().
CharPointer_UTF8 CharPointer_UTF8::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References CharacterFunctions::findEndOfWhitespace().
Referenced by Rectangle< int >::fromString().
static bool CharPointer_UTF8::canRepresent (juce_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool CharPointer_UTF8::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
CharPointer_UTF8 CharPointer_UTF8::atomicSwap (const CharPointer_UTF8 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
References CharPointer_UTF8().
static bool CharPointer_UTF8::isByteOrderMark (const void * possibleByteOrder) static noexcept
Returns true if the first three bytes in this pointer are the UTF8 byte-order mark (BOM).
The pointer must not be null, and must point to at least 3 valid bytes.
References byteOrderMark1, byteOrderMark2, byteOrderMark3, and jassert.
class Identifier
Represents a string identifier, designed for accessing properties by name.
Comparing two Identifier objects is very fast (an O(1) operation), but creating them can be slower than just using a String directly, so the optimal way to use them is to keep some static Identifier objects for the things you use often.
See Also
NamedValueSet, ValueTree
Public Member Functions
Identifier () noexcept
Creates a null identifier.
Identifier (const char *name)
Creates an identifier with a specified name.
Identifier (const String &name)
Creates an identifier with a specified name.
Identifier (String::CharPointerType nameStart, String::CharPointerType nameEnd)
Creates an identifier with a specified name.
Identifier (const Identifier &other) noexcept
Creates a copy of another identifier.
Identifier & operator= (const Identifier &other) noexcept
Creates a copy of another identifier.
Identifier (Identifier &&other) noexcept
Creates a copy of another identifier.
Identifier & operator= (Identifier &&other) noexcept
Creates a copy of another identifier.
~Identifier () noexcept
Destructor.
bool operator== (const Identifier &other) const noexcept
Compares two identifiers.
bool operator!= (const Identifier &other) const noexcept
Compares two identifiers.
bool operator== (StringRef other) const noexcept
Compares the identifier with a string.
bool operator!= (StringRef other) const noexcept
Compares the identifier with a string.
bool operator< (StringRef other) const noexcept
Compares the identifier with a string.
bool operator<= (StringRef other) const noexcept
Compares the identifier with a string.
bool operator> (StringRef other) const noexcept
Compares the identifier with a string.
bool operator>= (StringRef other) const noexcept
Compares the identifier with a string.
const String & toString () const noexcept
Returns this identifier as a string.
operator String::CharPointerType () const noexcept
Returns this identifier's raw string pointer.
String::CharPointerType getCharPointer () const noexcept
Returns this identifier's raw string pointer.
operator StringRef () const noexcept
Returns this identifier as a StringRef.
bool isValid () const noexcept
Returns true if this Identifier is not null.
bool isNull () const noexcept
Returns true if this Identifier is null.
Static Public Member Functions
static bool isValidIdentifier (const String &possibleIdentifier) noexcept
Checks a given string for characters that might not be valid in an Identifier.
Static Public Attributes
static Identifier null
A null identifier.
Constructor & Destructor Documentation
Identifier::Identifier () noexcept
Creates a null identifier.
Identifier::Identifier (const char * name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
Identifier::Identifier (const String & name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
Identifier::Identifier (String::CharPointerType nameStart, String::CharPointerType nameEnd)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
Identifier::Identifier (const Identifier & other) noexcept
Creates a copy of another identifier.
Identifier::Identifier (Identifier && other) noexcept
Creates a copy of another identifier.
Identifier::~Identifier () noexcept
Destructor.
Member Function Documentation
Identifier& Identifier::operator= (const Identifier & other) noexcept
Creates a copy of another identifier.
Identifier& Identifier::operator= (Identifier && other) noexcept
Creates a copy of another identifier.
bool Identifier::operator== (const Identifier & other) const noexcept
Compares two identifiers.
This is a very fast operation.
References String::getCharPointer().
bool Identifier::operator!= (const Identifier & other) const noexcept
Compares two identifiers.
This is a very fast operation.
References String::getCharPointer().
bool Identifier::operator== (StringRef other) const noexcept
Compares the identifier with a string.
bool Identifier::operator!= (StringRef other) const noexcept
Compares the identifier with a string.
bool Identifier::operator< (StringRef other) const noexcept
Compares the identifier with a string.
bool Identifier::operator<= (StringRef other) const noexcept
Compares the identifier with a string.
bool Identifier::operator> (StringRef other) const noexcept
Compares the identifier with a string.
bool Identifier::operator>= (StringRef other) const noexcept
Compares the identifier with a string.
const String& Identifier::toString () const noexcept
Returns this identifier as a string.
Identifier::operator String::CharPointerType () const noexcept
Returns this identifier's raw string pointer.
References String::getCharPointer().
String::CharPointerType Identifier::getCharPointer () const noexcept
Returns this identifier's raw string pointer.
References String::getCharPointer().
Identifier::operator StringRef () const noexcept
Returns this identifier as a StringRef.
bool Identifier::isValid () const noexcept
Returns true if this Identifier is not null.
References String::isNotEmpty().
bool Identifier::isNull () const noexcept
Returns true if this Identifier is null.
References String::isEmpty().
static bool Identifier::isValidIdentifier (const String & possibleIdentifier) static noexcept
Checks a given string for characters that might not be valid in an Identifier.
Since Identifiers are used as a script variables and XML attributes, they should only contain alphanumeric characters, underscores, or the '-' and ':' characters.
Member Data Documentation
Identifier Identifier::null static
A null identifier.
class LocalisedStrings
Used to convert strings to localised foreign-language versions.
This is basically a look-up table of strings and their translated equivalents. It can be loaded from a text file, so that you can supply a set of localised versions of strings that you use in your app.
To use it in your code, simply call the translate() method on each string that might have foreign versions, and if none is found, the method will just return the original string.
The translation file should start with some lines specifying a description of the language it contains, and also a list of ISO country codes where it might be appropriate to use the file. After that, each line of the file should contain a pair of quoted strings with an '=' sign.
E.g. for a french translation, the file might be:
language: French
countries: fr be mc ch lu
"hello" = "bonjour"
"goodbye" = "au revoir"
If the strings need to contain a quote character, they can use '"' instead, and if the first non-whitespace character on a line isn't a quote, then it's ignored, (you can use this to add comments).
Note that this is a singleton class, so don't create or destroy the object directly. There's also a TRANS(text) macro defined to make it easy to use the this.
E.g.
printSomething (TRANS("hello"));
This macro is used in the Juce classes themselves, so your application has a chance to intercept and translate any internal Juce text strings that might be shown. (You can easily get a list of all the messages by searching for the TRANS() macro in the Juce source code).
Public Member Functions
LocalisedStrings (const String &fileContents, bool ignoreCaseOfKeys)
Creates a set of translations from the text of a translation file.
LocalisedStrings (const File &fileToLoad, bool ignoreCaseOfKeys)
Creates a set of translations from a file.
LocalisedStrings (const LocalisedStrings &)
LocalisedStrings & operator= (const LocalisedStrings &)
~LocalisedStrings ()
Destructor.
String translate (const String &text) const
Attempts to look up a string and return its localised version.
String translate (const String &text, const String &resultIfNotFound) const
Attempts to look up a string and return its localised version.
String getLanguageName () const
Returns the name of the language specified in the translation file.
const StringArray & getCountryCodes () const
Returns the list of suitable country codes listed in the translation file.
const StringPairArray & getMappings () const
Provides access to the actual list of mappings.
void addStrings (const LocalisedStrings &)
Adds and merges another set of translations into this set.
void setFallback (LocalisedStrings *fallbackStrings)
Gives this object a set of strings to use as a fallback if a string isn't found.
Static Public Member Functions
static void setCurrentMappings (LocalisedStrings *newTranslations)
Selects the current set of mappings to be used by the system.
static LocalisedStrings * getCurrentMappings ()
Returns the currently selected set of mappings.
static String translateWithCurrentMappings (const String &text)
Tries to translate a string using the currently selected set of mappings.
static String translateWithCurrentMappings (const char *text)
Tries to translate a string using the currently selected set of mappings.
Constructor & Destructor Documentation
LocalisedStrings::LocalisedStrings (const String & fileContents, bool ignoreCaseOfKeys)
Creates a set of translations from the text of a translation file.
When you create one of these, you can call setCurrentMappings() to make it the set of mappings that the system's using.
LocalisedStrings::LocalisedStrings (const File & fileToLoad, bool ignoreCaseOfKeys)
Creates a set of translations from a file.
When you create one of these, you can call setCurrentMappings() to make it the set of mappings that the system's using.
LocalisedStrings::LocalisedStrings (const LocalisedStrings &)
LocalisedStrings::~LocalisedStrings ()
Destructor.
Member Function Documentation
LocalisedStrings& LocalisedStrings::operator= (const LocalisedStrings &)
static void LocalisedStrings::setCurrentMappings (LocalisedStrings * newTranslations) static
Selects the current set of mappings to be used by the system.
The object you pass in will be automatically deleted when no longer needed, so don't keep a pointer to it. You can also pass in nullptr to remove the current mappings.
See also the TRANS() macro, which uses the current set to do its translation.
See Also
translateWithCurrentMappings
static LocalisedStrings* LocalisedStrings::getCurrentMappings () static
Returns the currently selected set of mappings.
This is the object that was last passed to setCurrentMappings(). It may be nullptr if none has been created.
static String LocalisedStrings::translateWithCurrentMappings (const String & text) static
Tries to translate a string using the currently selected set of mappings.
If no mapping has been set, or if the mapping doesn't contain a translation for the string, this will just return the original string.
See also the TRANS() macro, which uses this method to do its translation.
See Also
setCurrentMappings, getCurrentMappings
static String LocalisedStrings::translateWithCurrentMappings (const char * text) static
Tries to translate a string using the currently selected set of mappings.
If no mapping has been set, or if the mapping doesn't contain a translation for the string, this will just return the original string.
See also the TRANS() macro, which uses this method to do its translation.
See Also
setCurrentMappings, getCurrentMappings
String LocalisedStrings::translate (const String & text) const
Attempts to look up a string and return its localised version.
If the string isn't found in the list, the original string will be returned.
String LocalisedStrings::translate (const String & text, const String & resultIfNotFound) const
Attempts to look up a string and return its localised version.
If the string isn't found in the list, the resultIfNotFound string will be returned.
String LocalisedStrings::getLanguageName () const
Returns the name of the language specified in the translation file.
This is specified in the file using a line starting with "language:", e.g.
language: german
const StringArray& LocalisedStrings::getCountryCodes () const
Returns the list of suitable country codes listed in the translation file.
These is specified in the file using a line starting with "countries:", e.g.
countries: fr be mc ch lu
The country codes are supposed to be 2-character ISO complient codes.
const StringPairArray& LocalisedStrings::getMappings () const
Provides access to the actual list of mappings.
void LocalisedStrings::addStrings (const LocalisedStrings &)
Adds and merges another set of translations into this set.
Note that the language name and country codes of the new LocalisedStrings object must match that of this object - an assertion will be thrown if they don't match.
Any existing values will have their mappings overwritten by the new ones.
void LocalisedStrings::setFallback (LocalisedStrings * fallbackStrings)
Gives this object a set of strings to use as a fallback if a string isn't found.
The object that is passed-in will be owned and deleted by this object when no longer needed. It can be nullptr to clear the existing fallback object.
class NewLine
This class is used for represent a new-line character sequence.
To write a new-line to a stream, you can use the predefined 'newLine' variable, e.g.
myOutputStream << "Hello World" << newLine << newLine;
The exact character sequence that will be used for the new-line can be set and retrieved with OutputStream::setNewLineString() and OutputStream::getNewLineString().
Public Member Functions
operator String () const
Returns the default new-line sequence that the library uses.
operator StringRef () const noexcept
Returns the default new-line sequence that the library uses.
Static Public Member Functions
static const char * getDefault () noexcept
Returns the default new-line sequence that the library uses.
Member Function Documentation
static const char* NewLine::getDefault () static noexcept
Returns the default new-line sequence that the library uses.
See Also
OutputStream::setNewLineString()
Referenced by operator+(), operator+=(), and operator<<().
NewLine::operator String () const
Returns the default new-line sequence that the library uses.
See Also
getDefault()
NewLine::operator StringRef () const noexcept
Returns the default new-line sequence that the library uses.
See Also
OutputStream::setNewLineString()
class String
The JUCE String class!
Using a reference-counted internal representation, these strings are fast and efficient, and there are methods to do just about any operation you'll ever dream of.
See Also
StringArray, StringPairArray
Public Types
typedef CharPointer_UTF8 CharPointerType
This is the character encoding type used internally to store the string.
Public Member Functions
String () noexcept
Creates an empty string.
String (const String &other) noexcept
Creates a copy of another string.
String (String &&other) noexcept
Move constructor.
String (const char *text)
Creates a string from a zero-terminated ascii text string.
String (const char *text, size_t maxChars)
Creates a string from a string of 8-bit ascii characters.
String (const wchar_t *text)
Creates a string from a wchar_t character string.
String (const wchar_t *text, size_t maxChars)
Creates a string from a wchar_t character string.
String (const CharPointer_UTF8 text)
Creates a string from a UTF-8 character string.
String (const CharPointer_UTF8 text, size_t maxChars)
Creates a string from a UTF-8 character string.
String (const CharPointer_UTF8 start, const CharPointer_UTF8 end)
Creates a string from a UTF-8 character string.
String (const CharPointer_UTF16 text)
Creates a string from a UTF-16 character string.
String (const CharPointer_UTF16 text, size_t maxChars)
Creates a string from a UTF-16 character string.
String (const CharPointer_UTF16 start, const CharPointer_UTF16 end)
Creates a string from a UTF-16 character string.
String (const CharPointer_UTF32 text)
Creates a string from a UTF-32 character string.
String (const CharPointer_UTF32 text, size_t maxChars)
Creates a string from a UTF-32 character string.
String (const CharPointer_UTF32 start, const CharPointer_UTF32 end)
Creates a string from a UTF-32 character string.
String (const CharPointer_ASCII text)
Creates a string from an ASCII character string.
String (const std::string &)
Creates a string from a UTF-8 encoded std::string.
String (StringRef)
Creates a string from a StringRef.
~String () noexcept
Destructor.
int hashCode () const noexcept
Generates a probably-unique 32-bit hashcode from this string.
int64 hashCode64 () const noexcept
Generates a probably-unique 64-bit hashcode from this string.
size_t hash () const noexcept
Generates a probably-unique hashcode from this string.
int length () const noexcept
Returns the number of characters in the string.
String & operator= (const String &other) noexcept
Replaces this string's contents with another string.
String & operator= (String &&other) noexcept
Moves the contents of another string to the receiver.
String & operator+= (const String &stringToAppend)
Appends another string at the end of this one.
String & operator+= (const char *textToAppend)
Appends another string at the end of this one.
String & operator+= (const wchar_t *textToAppend)
Appends another string at the end of this one.
String & operator+= (StringRef textToAppend)
Appends another string at the end of this one.
String & operator+= (int numberToAppend)
Appends a decimal number at the end of this string.
String & operator+= (long numberToAppend)
Appends a decimal number at the end of this string.
String & operator+= (int64 numberToAppend)
Appends a decimal number at the end of this string.
String & operator+= (uint64 numberToAppend)
Appends a decimal number at the end of this string.
String & operator+= (char characterToAppend)
Appends a character at the end of this string.
String & operator+= (wchar_t characterToAppend)
Appends a character at the end of this string.
String & operator+= (juce_wchar characterToAppend)
Appends a character at the end of this string.
void append (const String &textToAppend, size_t maxCharsToTake)
Appends a string to the end of this one.
void appendCharPointer (const CharPointerType startOfTextToAppend, const CharPointerType endOfTextToAppend)
Appends a string to the end of this one.
template<class CharPointer >
void appendCharPointer (const CharPointer startOfTextToAppend, const CharPointer endOfTextToAppend)
Appends a string to the end of this one.
void appendCharPointer (const CharPointerType textToAppend)
Appends a string to the end of this one.
template<class CharPointer >
void appendCharPointer (const CharPointer textToAppend, size_t maxCharsToTake)
Appends a string to the end of this one.
template<class CharPointer >
void appendCharPointer (const CharPointer textToAppend)
Appends a string to the end of this one.
bool isEmpty () const noexcept
Returns true if the string contains no characters.
bool isNotEmpty () const noexcept
Returns true if the string contains at least one character.
void clear () noexcept
Resets this string to be empty.
bool equalsIgnoreCase (const String &other) const noexcept
Case-insensitive comparison with another string.
bool equalsIgnoreCase (StringRef other) const noexcept
Case-insensitive comparison with another string.
bool equalsIgnoreCase (const wchar_t *other) const noexcept
Case-insensitive comparison with another string.
bool equalsIgnoreCase (const char *other) const noexcept
Case-insensitive comparison with another string.
int compare (const String &other) const noexcept
Case-sensitive comparison with another string.
int compare (const char *other) const noexcept
Case-sensitive comparison with another string.
int compare (const wchar_t *other) const noexcept
Case-sensitive comparison with another string.
int compareIgnoreCase (const String &other) const noexcept
Case-insensitive comparison with another string.
int compareNatural (StringRef other, bool isCaseSensitive=false) const noexcept
Compares two strings, taking into account textual characteristics like numbers and spaces.
bool startsWith (StringRef text) const noexcept
Tests whether the string begins with another string.
bool startsWithChar (juce_wchar character) const noexcept
Tests whether the string begins with a particular character.
bool startsWithIgnoreCase (StringRef text) const noexcept
Tests whether the string begins with another string.
bool endsWith (StringRef text) const noexcept
Tests whether the string ends with another string.
bool endsWithChar (juce_wchar character) const noexcept
Tests whether the string ends with a particular character.
bool endsWithIgnoreCase (StringRef text) const noexcept
Tests whether the string ends with another string.
bool contains (StringRef text) const noexcept
Tests whether the string contains another substring.
bool containsChar (juce_wchar character) const noexcept
Tests whether the string contains a particular character.
bool containsIgnoreCase (StringRef text) const noexcept
Tests whether the string contains another substring.
bool containsWholeWord (StringRef wordToLookFor) const noexcept
Tests whether the string contains another substring as a distinct word.
bool containsWholeWordIgnoreCase (StringRef wordToLookFor) const noexcept
Tests whether the string contains another substring as a distinct word.
int indexOfWholeWord (StringRef wordToLookFor) const noexcept
Finds an instance of another substring if it exists as a distinct word.
int indexOfWholeWordIgnoreCase (StringRef wordToLookFor) const noexcept
Finds an instance of another substring if it exists as a distinct word.
bool containsAnyOf (StringRef charactersItMightContain) const noexcept
Looks for any of a set of characters in the string.
bool containsOnly (StringRef charactersItMightContain) const noexcept
Looks for a set of characters in the string.
bool containsNonWhitespaceChars () const noexcept
Returns true if this string contains any non-whitespace characters.
bool matchesWildcard (StringRef wildcard, bool ignoreCase) const noexcept
Returns true if the string matches this simple wildcard expression.
int indexOfChar (juce_wchar characterToLookFor) const noexcept
Searches for a character inside this string.
int indexOfChar (int startIndex, juce_wchar characterToLookFor) const noexcept
Searches for a character inside this string.
int indexOfAnyOf (StringRef charactersToLookFor, int startIndex=0, bool ignoreCase=false) const noexcept
Returns the index of the first character that matches one of the characters passed-in to this method.
int indexOf (StringRef textToLookFor) const noexcept
Searches for a substring within this string.
int indexOf (int startIndex, StringRef textToLookFor) const noexcept
Searches for a substring within this string.
int indexOfIgnoreCase (StringRef textToLookFor) const noexcept
Searches for a substring within this string.
int indexOfIgnoreCase (int startIndex, StringRef textToLookFor) const noexcept
Searches for a substring within this string.
int lastIndexOfChar (juce_wchar character) const noexcept
Searches for a character inside this string (working backwards from the end of the string).
int lastIndexOf (StringRef textToLookFor) const noexcept
Searches for a substring inside this string (working backwards from the end of the string).
int lastIndexOfIgnoreCase (StringRef textToLookFor) const noexcept
Searches for a substring inside this string (working backwards from the end of the string).
int lastIndexOfAnyOf (StringRef charactersToLookFor, bool ignoreCase=false) const noexcept
Returns the index of the last character in this string that matches one of the characters passed-in to this method.
juce_wchar operator[] (int index) const noexcept
Returns the character at this index in the string.
juce_wchar getLastCharacter () const noexcept
Returns the final character of the string.
String substring (int startIndex, int endIndex) const
Returns a subsection of the string.
String substring (int startIndex) const
Returns a section of the string, starting from a given position.
String dropLastCharacters (int numberToDrop) const
Returns a version of this string with a number of characters removed from the end.
String getLastCharacters (int numCharacters) const
Returns a number of characters from the end of the string.
String fromFirstOccurrenceOf (StringRef substringToStartFrom, bool includeSubStringInResult, bool ignoreCase) const
Returns a section of the string starting from a given substring.
String fromLastOccurrenceOf (StringRef substringToFind, bool includeSubStringInResult, bool ignoreCase) const
Returns a section of the string starting from the last occurrence of a given substring.
String upToFirstOccurrenceOf (StringRef substringToEndWith, bool includeSubStringInResult, bool ignoreCase) const
Returns the start of this string, up to the first occurrence of a substring.
String upToLastOccurrenceOf (StringRef substringToFind, bool includeSubStringInResult, bool ignoreCase) const
Returns the start of this string, up to the last occurrence of a substring.
String trim () const
Returns a copy of this string with any whitespace characters removed from the start and end.
String trimStart () const
Returns a copy of this string with any whitespace characters removed from the start.
String trimEnd () const
Returns a copy of this string with any whitespace characters removed from the end.
String trimCharactersAtStart (StringRef charactersToTrim) const
Returns a copy of this string, having removed a specified set of characters from its start.
String trimCharactersAtEnd (StringRef charactersToTrim) const
Returns a copy of this string, having removed a specified set of characters from its end.
String toUpperCase () const
Returns an upper-case version of this string.
String toLowerCase () const
Returns an lower-case version of this string.
String replaceSection (int startIndex, int numCharactersToReplace, StringRef stringToInsert) const
Replaces a sub-section of the string with another string.
String replace (StringRef stringToReplace, StringRef stringToInsertInstead, bool ignoreCase=false) const
Replaces all occurrences of a substring with another string.
String replaceFirstOccurrenceOf (StringRef stringToReplace, StringRef stringToInsertInstead, bool ignoreCase=false) const
Replaces the first occurrence of a substring with another string.
String replaceCharacter (juce_wchar characterToReplace, juce_wchar characterToInsertInstead) const
Returns a string with all occurrences of a character replaced with a different one.
String replaceCharacters (StringRef charactersToReplace, StringRef charactersToInsertInstead) const
Replaces a set of characters with another set.
String retainCharacters (StringRef charactersToRetain) const
Returns a version of this string that only retains a fixed set of characters.
String removeCharacters (StringRef charactersToRemove) const
Returns a version of this string with a set of characters removed.
String initialSectionContainingOnly (StringRef permittedCharacters) const
Returns a section from the start of the string that only contains a certain set of characters.
String initialSectionNotContaining (StringRef charactersToStopAt) const
Returns a section from the start of the string that only contains a certain set of characters.
bool isQuotedString () const
Checks whether the string might be in quotation marks.
String unquoted () const
Removes quotation marks from around the string, (if there are any).
String quoted (juce_wchar quoteCharacter= '"') const
Adds quotation marks around a string.
String paddedLeft (juce_wchar padCharacter, int minimumLength) const
Returns a copy of this string with the specified character repeatedly added to its beginning until the total length is at least the minimum length specified.
String paddedRight (juce_wchar padCharacter, int minimumLength) const
Returns a copy of this string with the specified character repeatedly added to its end until the total length is at least the minimum length specified.
String (int decimalInteger)
Creates a string containing this signed 32-bit integer as a decimal number.
String (unsigned int decimalInteger)
Creates a string containing this unsigned 32-bit integer as a decimal number.
String (short decimalInteger)
Creates a string containing this signed 16-bit integer as a decimal number.
String (unsigned short decimalInteger)
Creates a string containing this unsigned 16-bit integer as a decimal number.
String (int64 largeIntegerValue)
Creates a string containing this signed 64-bit integer as a decimal number.
String (uint64 largeIntegerValue)
Creates a string containing this unsigned 64-bit integer as a decimal number.
String (long decimalInteger)
Creates a string containing this signed long integer as a decimal number.
String (unsigned long decimalInteger)
Creates a string containing this unsigned long integer as a decimal number.
String (float floatValue)
Creates a string representing this floating-point number.
String (double doubleValue)
Creates a string representing this floating-point number.
String (float floatValue, int numberOfDecimalPlaces)
Creates a string representing this floating-point number.
String (double doubleValue, int numberOfDecimalPlaces)
Creates a string representing this floating-point number.
int getIntValue () const noexcept
Reads the value of the string as a decimal number (up to 32 bits in size).
int64 getLargeIntValue () const noexcept
Reads the value of the string as a decimal number (up to 64 bits in size).
int getTrailingIntValue () const noexcept
Parses a decimal number from the end of the string.
float getFloatValue () const noexcept
Parses this string as a floating point number.
double getDoubleValue () const noexcept
Parses this string as a floating point number.
int getHexValue32 () const noexcept
Parses the string as a hexadecimal number.
int64 getHexValue64 () const noexcept
Parses the string as a hexadecimal number.
CharPointerType getCharPointer () const noexcept
Returns the character pointer currently being used to store this string.
CharPointer_UTF8 toUTF8 () const
Returns a pointer to a UTF-8 version of this string.
const char * toRawUTF8 () const
Returns a pointer to a UTF-8 version of this string.
CharPointer_UTF16 toUTF16 () const
Returns a pointer to a UTF-16 version of this string.
CharPointer_UTF32 toUTF32 () const
Returns a pointer to a UTF-32 version of this string.
const wchar_t * toWideCharPointer () const
Returns a pointer to a wchar_t version of this string.
std::string toStdString () const
size_t getNumBytesAsUTF8 () const noexcept
Returns the number of bytes required to represent this string as UTF8.
size_t copyToUTF8 (CharPointer_UTF8::CharType *destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-8 characters.
size_t copyToUTF16 (CharPointer_UTF16::CharType *destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-16 characters.
size_t copyToUTF32 (CharPointer_UTF32::CharType *destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-32 characters.
void preallocateBytes (size_t numBytesNeeded)
Increases the string's internally allocated storage.
void swapWith (String &other) noexcept
Swaps the contents of this string with another one.
CFStringRef toCFString () const
OSX ONLY - Converts this string to a CFString.
String convertToPrecomposedUnicode () const
OSX ONLY - Returns a copy of this string in which any decomposed unicode characters have been converted to their precomposed equivalents.
int getReferenceCount () const noexcept
Returns the number of String objects which are currently sharing the same internal data as this one.
Static Public Member Functions
static String charToString (juce_wchar character)
Creates a string from a single character.
static String repeatedString (StringRef stringToRepeat, int numberOfTimesToRepeat)
Creates a string which is a version of a string repeated and joined together.
static String createStringFromData (const void *data, int size)
Creates a string from data in an unknown format.
template<typename... Args>
static String formatted (const String &formatStr, Args...args)
Creates a String from a printf-style parameter list.
template<typename IntegerType >
static String toHexString (IntegerType number)
Returns a string representing this numeric value in hexadecimal.
static String toHexString (const void *data, int size, int groupSize=1)
Returns a string containing a hex dump of a block of binary data.
static String fromUTF8 (const char *utf8buffer, int bufferSizeBytes=-1)
Creates a String from a UTF-8 encoded buffer.
static String fromCFString (CFStringRef cfString)
OSX ONLY - Creates a String from an OSX CFString.
Member Typedef Documentation
typedef CharPointer_UTF8 String::CharPointerType
This is the character encoding type used internally to store the string.
By setting the value of JUCE_STRING_UTF_TYPE to 8, 16, or 32, you can change the internal storage format of the String class. UTF-8 uses the least space (if your strings contain few extended characters), but call operator[] involves iterating the string to find the required index. UTF-32 provides instant random access to its characters, but uses 4 bytes per character to store them. UTF-16 uses more space than UTF-8 and is also slow to index, but is the native wchar_t format used in Windows.
It doesn't matter too much which format you pick, because the toUTF8(), toUTF16() and toUTF32() methods let you access the string's content in any of the other formats.
Constructor & Destructor Documentation
String::String () noexcept
Creates an empty string.
See Also
empty
String::String (const String & other) noexcept
Creates a copy of another string.
String::String (String && other) noexcept
Move constructor.
String::String (const char * text)
Creates a string from a zero-terminated ascii text string.
The string passed-in must not contain any characters with a value above 127, because these can't be converted to unicode without knowing the original encoding that was used to create the string. If you attempt to pass-in values above 127, you'll get an assertion.
To create strings with extended characters from UTF-8, you should explicitly call String (CharPointer_UTF8 ("my utf8 string..")). It's highly recommended that you use UTF-8 with escape characters in your source code to represent extended characters, because there's no other way to represent unicode strings in a way that isn't dependent on the compiler, source code editor and platform.
String::String (const char * text, size_t maxChars)
Creates a string from a string of 8-bit ascii characters.
The string passed-in must not contain any characters with a value above 127, because these can't be converted to unicode without knowing the original encoding that was used to create the string. If you attempt to pass-in values above 127, you'll get an assertion.
To create strings with extended characters from UTF-8, you should explicitly call String (CharPointer_UTF8 ("my utf8 string..")). It's highly recommended that you use UTF-8 with escape characters in your source code to represent extended characters, because there's no other way to represent unicode strings in a way that isn't dependent on the compiler, source code editor and platform.
This will use up to the first maxChars characters of the string (or less if the string is actually shorter).
String::String (const wchar_t * text)
Creates a string from a wchar_t character string.
Depending on the platform, this may be treated as either UTF-32 or UTF-16.
String::String (const wchar_t * text, size_t maxChars)
Creates a string from a wchar_t character string.
Depending on the platform, this may be treated as either UTF-32 or UTF-16.
String::String (const CharPointer_UTF8 text)
Creates a string from a UTF-8 character string.
String::String (const CharPointer_UTF8 text, size_t maxChars)
Creates a string from a UTF-8 character string.
String::String (const CharPointer_UTF8 start, const CharPointer_UTF8 end)
Creates a string from a UTF-8 character string.
String::String (const CharPointer_UTF16 text)
Creates a string from a UTF-16 character string.
String::String (const CharPointer_UTF16 text, size_t maxChars)
Creates a string from a UTF-16 character string.
String::String (const CharPointer_UTF16 start, const CharPointer_UTF16 end)
Creates a string from a UTF-16 character string.
String::String (const CharPointer_UTF32 text)
Creates a string from a UTF-32 character string.
String::String (const CharPointer_UTF32 text, size_t maxChars)
Creates a string from a UTF-32 character string.
String::String (const CharPointer_UTF32 start, const CharPointer_UTF32 end)
Creates a string from a UTF-32 character string.
String::String (const CharPointer_ASCII text)
Creates a string from an ASCII character string.
String::String (const std::string &)
Creates a string from a UTF-8 encoded std::string.
String::String (StringRef)
Creates a string from a StringRef.
String::~String () noexcept
Destructor.
String::String (int decimalInteger) explicit
Creates a string containing this signed 32-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
String::String (unsigned int decimalInteger) explicit
Creates a string containing this unsigned 32-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
String::String (short decimalInteger) explicit
Creates a string containing this signed 16-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
String::String (unsigned short decimalInteger) explicit
Creates a string containing this unsigned 16-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
String::String (int64 largeIntegerValue) explicit
Creates a string containing this signed 64-bit integer as a decimal number.
See Also
getLargeIntValue, getFloatValue, getDoubleValue, toHexString
String::String (uint64 largeIntegerValue) explicit
Creates a string containing this unsigned 64-bit integer as a decimal number.
See Also
getLargeIntValue, getFloatValue, getDoubleValue, toHexString
String::String (long decimalInteger) explicit
Creates a string containing this signed long integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
String::String (unsigned long decimalInteger) explicit
Creates a string containing this unsigned long integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
String::String (float floatValue) explicit
Creates a string representing this floating-point number.
Parameters
floatValue the value to convert to a string
See Also
getDoubleValue, getIntValue
String::String (double doubleValue) explicit
Creates a string representing this floating-point number.
Parameters
doubleValue the value to convert to a string
See Also
getFloatValue, getIntValue
String::String (float floatValue, int numberOfDecimalPlaces)
Creates a string representing this floating-point number.
Parameters
floatValue the value to convert to a string
numberOfDecimalPlaces if this is > 0, it will format the number using that many decimal places, and will not use exponent notation. If 0 or less, it will use exponent notation if necessary.
See Also
getDoubleValue, getIntValue
String::String (double doubleValue, int numberOfDecimalPlaces)
Creates a string representing this floating-point number.
Parameters
doubleValue the value to convert to a string
numberOfDecimalPlaces if this is > 0, it will format the number using that many decimal places, and will not use exponent notation. If 0 or less, it will use exponent notation if necessary.
See Also
getFloatValue, getIntValue
Member Function Documentation
static String String::charToString (juce_wchar character) static
Creates a string from a single character.
int String::hashCode () const noexcept
Generates a probably-unique 32-bit hashcode from this string.
int64 String::hashCode64 () const noexcept
Generates a probably-unique 64-bit hashcode from this string.
size_t String::hash () const noexcept
Generates a probably-unique hashcode from this string.
int String::length () const noexcept
Returns the number of characters in the string.
String& String::operator= (const String & other) noexcept
Replaces this string's contents with another string.
String& String::operator= (String && other) noexcept
Moves the contents of another string to the receiver.
String& String::operator+= (const String & stringToAppend)
Appends another string at the end of this one.
String& String::operator+= (const char * textToAppend)
Appends another string at the end of this one.
String& String::operator+= (const wchar_t * textToAppend)
Appends another string at the end of this one.
String& String::operator+= (StringRef textToAppend)
Appends another string at the end of this one.
String& String::operator+= (int numberToAppend)
Appends a decimal number at the end of this string.
String& String::operator+= (long numberToAppend)
Appends a decimal number at the end of this string.
String& String::operator+= (int64 numberToAppend)
Appends a decimal number at the end of this string.
String& String::operator+= (uint64 numberToAppend)
Appends a decimal number at the end of this string.
String& String::operator+= (char characterToAppend)
Appends a character at the end of this string.
String& String::operator+= (wchar_t characterToAppend)
Appends a character at the end of this string.
String& String::operator+= (juce_wchar characterToAppend)
Appends a character at the end of this string.
void String::append (const String & textToAppend, size_t maxCharsToTake)
Appends a string to the end of this one.
Parameters
textToAppend the string to add
maxCharsToTake the maximum number of characters to take from the string passed in
void String::appendCharPointer (const CharPointerType startOfTextToAppend, const CharPointerType endOfTextToAppend)
Appends a string to the end of this one.
Parameters
startOfTextToAppend the start of the string to add. This must not be a nullptr
endOfTextToAppend the end of the string to add. This must not be a nullptr
template<class CharPointer > void String::appendCharPointer (const CharPointer startOfTextToAppend, const CharPointer endOfTextToAppend)
Appends a string to the end of this one.
Parameters
startOfTextToAppend the start of the string to add. This must not be a nullptr
endOfTextToAppend the end of the string to add. This must not be a nullptr
References addBytesToPointer(), CharPointer_ASCII::getAddress(), and jassert.
void String::appendCharPointer (const CharPointerType textToAppend)
Appends a string to the end of this one.
template<class CharPointer > void String::appendCharPointer (const CharPointer textToAppend, size_t maxCharsToTake)
Appends a string to the end of this one.
Parameters
textToAppend the string to add
maxCharsToTake the maximum number of characters to take from the string passed in
References addBytesToPointer(), and CharPointer_ASCII::getAddress().
template<class CharPointer > void String::appendCharPointer (const CharPointer textToAppend)
Appends a string to the end of this one.
References max().
bool String::isEmpty () const noexcept
Returns true if the string contains no characters.
Note that there's also an isNotEmpty() method to help write readable code.
See Also
containsNonWhitespaceChars()
References CharPointer_ASCII::isEmpty().
Referenced by StandalonePluginHolder::getFilePatterns(), and Identifier::isNull().
bool String::isNotEmpty () const noexcept
Returns true if the string contains at least one character.
Note that there's also an isEmpty() method to help write readable code.
See Also
containsNonWhitespaceChars()
References CharPointer_ASCII::isEmpty().
Referenced by Identifier::isValid().
void String::clear () noexcept
Resets this string to be empty.
bool String::equalsIgnoreCase (const String & other) const noexcept
Case-insensitive comparison with another string.
bool String::equalsIgnoreCase (StringRef other) const noexcept
Case-insensitive comparison with another string.
bool String::equalsIgnoreCase (const wchar_t * other) const noexcept
Case-insensitive comparison with another string.
bool String::equalsIgnoreCase (const char * other) const noexcept
Case-insensitive comparison with another string.
int String::compare (const String & other) const noexcept
Case-sensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
int String::compare (const char * other) const noexcept
Case-sensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
int String::compare (const wchar_t * other) const noexcept
Case-sensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
int String::compareIgnoreCase (const String & other) const noexcept
Case-insensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
int String::compareNatural (StringRef other, bool isCaseSensitive = false) const noexcept
Compares two strings, taking into account textual characteristics like numbers and spaces.
This comparison is case-insensitive and can detect words and embedded numbers in the strings, making it good for sorting human-readable lists of things like filenames.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
Referenced by File::NaturalFileComparator::compareElements().
bool String::startsWith (StringRef text) const noexcept
Tests whether the string begins with another string.
If the parameter is an empty string, this will always return true. Uses a case-sensitive comparison.
bool String::startsWithChar (juce_wchar character) const noexcept
Tests whether the string begins with a particular character.
If the character is 0, this will always return false. Uses a case-sensitive comparison.
Referenced by StandalonePluginHolder::getFilePatterns().
bool String::startsWithIgnoreCase (StringRef text) const noexcept
Tests whether the string begins with another string.
If the parameter is an empty string, this will always return true. Uses a case-insensitive comparison.
bool String::endsWith (StringRef text) const noexcept
Tests whether the string ends with another string.
If the parameter is an empty string, this will always return true. Uses a case-sensitive comparison.
bool String::endsWithChar (juce_wchar character) const noexcept
Tests whether the string ends with a particular character.
If the character is 0, this will always return false. Uses a case-sensitive comparison.
bool String::endsWithIgnoreCase (StringRef text) const noexcept
Tests whether the string ends with another string.
If the parameter is an empty string, this will always return true. Uses a case-insensitive comparison.
bool String::contains (StringRef text) const noexcept
Tests whether the string contains another substring.
If the parameter is an empty string, this will always return true. Uses a case-sensitive comparison.
bool String::containsChar (juce_wchar character) const noexcept
Tests whether the string contains a particular character.
Uses a case-sensitive comparison.
bool String::containsIgnoreCase (StringRef text) const noexcept
Tests whether the string contains another substring.
Uses a case-insensitive comparison.
bool String::containsWholeWord (StringRef wordToLookFor) const noexcept
Tests whether the string contains another substring as a distinct word.
Returns
true if the string contains this word, surrounded by non-alphanumeric characters
See Also
indexOfWholeWord, containsWholeWordIgnoreCase
bool String::containsWholeWordIgnoreCase (StringRef wordToLookFor) const noexcept
Tests whether the string contains another substring as a distinct word.
Returns
true if the string contains this word, surrounded by non-alphanumeric characters
See Also
indexOfWholeWordIgnoreCase, containsWholeWord
int String::indexOfWholeWord (StringRef wordToLookFor) const noexcept
Finds an instance of another substring if it exists as a distinct word.
Returns
if the string contains this word, surrounded by non-alphanumeric characters, then this will return the index of the start of the substring. If it isn't found, then it will return -1
See Also
indexOfWholeWordIgnoreCase, containsWholeWord
int String::indexOfWholeWordIgnoreCase (StringRef wordToLookFor) const noexcept
Finds an instance of another substring if it exists as a distinct word.
Returns
if the string contains this word, surrounded by non-alphanumeric characters, then this will return the index of the start of the substring. If it isn't found, then it will return -1
See Also
indexOfWholeWord, containsWholeWordIgnoreCase
bool String::containsAnyOf (StringRef charactersItMightContain) const noexcept
Looks for any of a set of characters in the string.
Uses a case-sensitive comparison.
Returns
true if the string contains any of the characters from the string that is passed in.
bool String::containsOnly (StringRef charactersItMightContain) const noexcept
Looks for a set of characters in the string.
Uses a case-sensitive comparison.
Returns
Returns false if any of the characters in this string do not occur in the parameter string. If this string is empty, the return value will always be true.
bool String::containsNonWhitespaceChars () const noexcept
Returns true if this string contains any non-whitespace characters.
This will return false if the string contains only whitespace characters, or if it's empty.
It is equivalent to calling "myString.trim().isNotEmpty()".
bool String::matchesWildcard (StringRef wildcard, bool ignoreCase) const noexcept
Returns true if the string matches this simple wildcard expression.
So for example String ("abcdef").matchesWildcard ("*DEF", true) would return true.
This isn't a full-blown regex though! The only wildcard characters supported are "*" and "?". It's mainly intended for filename pattern matching.
int String::indexOfChar (juce_wchar characterToLookFor) const noexcept
Searches for a character inside this string.
Uses a case-sensitive comparison.
Returns
the index of the first occurrence of the character in this string, or -1 if it's not found.
int String::indexOfChar (int startIndex, juce_wchar characterToLookFor) const noexcept
Searches for a character inside this string.
Uses a case-sensitive comparison.
Parameters
startIndex the index from which the search should proceed
characterToLookFor the character to look for
Returns
the index of the first occurrence of the character in this string, or -1 if it's not found.
int String::indexOfAnyOf (StringRef charactersToLookFor, int startIndex = 0, bool ignoreCase = false) const noexcept
Returns the index of the first character that matches one of the characters passed-in to this method.
This scans the string, beginning from the startIndex supplied, and if it finds a character that appears in the string charactersToLookFor, it returns its index.
If none of these characters are found, it returns -1.
If ignoreCase is true, the comparison will be case-insensitive.
See Also
indexOfChar, lastIndexOfAnyOf
int String::indexOf (StringRef textToLookFor) const noexcept
Searches for a substring within this string.
Uses a case-sensitive comparison.
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return 0.
int String::indexOf (int startIndex, StringRef textToLookFor) const noexcept
Searches for a substring within this string.
Uses a case-sensitive comparison.
Parameters
startIndex the index from which the search should proceed
textToLookFor the string to search for
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
int String::indexOfIgnoreCase (StringRef textToLookFor) const noexcept
Searches for a substring within this string.
Uses a case-insensitive comparison.
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return 0.
int String::indexOfIgnoreCase (int startIndex, StringRef textToLookFor) const noexcept
Searches for a substring within this string.
Uses a case-insensitive comparison.
Parameters
startIndex the index from which the search should proceed
textToLookFor the string to search for
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
int String::lastIndexOfChar (juce_wchar character) const noexcept
Searches for a character inside this string (working backwards from the end of the string).
Uses a case-sensitive comparison.
Returns
the index of the last occurrence of the character in this string, or -1 if it's not found.
int String::lastIndexOf (StringRef textToLookFor) const noexcept
Searches for a substring inside this string (working backwards from the end of the string).
Uses a case-sensitive comparison.
Returns
the index of the start of the last occurrence of the substring within this string, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
int String::lastIndexOfIgnoreCase (StringRef textToLookFor) const noexcept
Searches for a substring inside this string (working backwards from the end of the string).
Uses a case-insensitive comparison.
Returns
the index of the start of the last occurrence of the substring within this string, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
int String::lastIndexOfAnyOf (StringRef charactersToLookFor, bool ignoreCase = false) const noexcept
Returns the index of the last character in this string that matches one of the characters passed-in to this method.
This scans the string backwards, starting from its end, and if it finds a character that appears in the string charactersToLookFor, it returns its index.
If none of these characters are found, it returns -1.
If ignoreCase is true, the comparison will be case-insensitive.
See Also
lastIndexOf, indexOfAnyOf
juce_wchar String::operator[] (int index) const noexcept
Returns the character at this index in the string.
In a release build, no checks are made to see if the index is within a valid range, so be careful! In a debug build, the index is checked and an assertion fires if it's out-of-range.
Also beware that depending on the encoding format that the string is using internally, this method may execute in either O(1) or O(n) time, so be careful when using it in your algorithms. If you're scanning through a string to inspect its characters, you should never use this operator for random access, it's far more efficient to call getCharPointer() to return a pointer, and then to use that to iterate the string.
See Also
getCharPointer
juce_wchar String::getLastCharacter () const noexcept
Returns the final character of the string.
If the string is empty this will return 0.
String String::substring (int startIndex, int endIndex) const
Returns a subsection of the string.
If the range specified is beyond the limits of the string, as much as possible is returned.
Parameters
startIndex the index of the start of the substring needed
endIndex all characters from startIndex up to (but not including) this index are returned
See Also
fromFirstOccurrenceOf, dropLastCharacters, getLastCharacters, upToFirstOccurrenceOf
String String::substring (int startIndex) const
Returns a section of the string, starting from a given position.
Parameters
startIndex the first character to include. If this is beyond the end of the string, an empty string is returned. If it is zero or less, the whole string is returned.
Returns
the substring from startIndex up to the end of the string
See Also
dropLastCharacters, getLastCharacters, fromFirstOccurrenceOf, upToFirstOccurrenceOf, fromLastOccurrenceOf
String String::dropLastCharacters (int numberToDrop) const
Returns a version of this string with a number of characters removed from the end.
Parameters
numberToDrop the number of characters to drop from the end of the string. If this is greater than the length of the string, an empty string will be returned. If zero or less, the original string will be returned.
See Also
substring, fromFirstOccurrenceOf, upToFirstOccurrenceOf, fromLastOccurrenceOf, getLastCharacter
String String::getLastCharacters (int numCharacters) const
Returns a number of characters from the end of the string.
This returns the last numCharacters characters from the end of the string. If the string is shorter than numCharacters, the whole string is returned.
See Also
substring, dropLastCharacters, getLastCharacter
String String::fromFirstOccurrenceOf (StringRef substringToStartFrom, bool includeSubStringInResult, bool ignoreCase) const
Returns a section of the string starting from a given substring.
This will search for the first occurrence of the given substring, and return the section of the string starting from the point where this is found (optionally not including the substring itself).
e.g. for the string "123456", fromFirstOccurrenceOf ("34", true) would return "3456", and fromFirstOccurrenceOf ("34", false) would return "56".
If the substring isn't found, the method will return an empty string.
If ignoreCase is true, the comparison will be case-insensitive.
See Also
upToFirstOccurrenceOf, fromLastOccurrenceOf
String String::fromLastOccurrenceOf (StringRef substringToFind, bool includeSubStringInResult, bool ignoreCase) const
Returns a section of the string starting from the last occurrence of a given substring.
Similar to fromFirstOccurrenceOf(), but using the last occurrence of the substring, and unlike fromFirstOccurrenceOf(), if the substring isn't found, this method will return the whole of the original string.
See Also
fromFirstOccurrenceOf, upToLastOccurrenceOf
String String::upToFirstOccurrenceOf (StringRef substringToEndWith, bool includeSubStringInResult, bool ignoreCase) const
Returns the start of this string, up to the first occurrence of a substring.
This will search for the first occurrence of a given substring, and then return a copy of the string, up to the position of this substring, optionally including or excluding the substring itself in the result.
e.g. for the string "123456", upTo ("34", false) would return "12", and upTo ("34", true) would return "1234".
If the substring isn't found, this will return the whole of the original string.
See Also
upToLastOccurrenceOf, fromFirstOccurrenceOf
String String::upToLastOccurrenceOf (StringRef substringToFind, bool includeSubStringInResult, bool ignoreCase) const
Returns the start of this string, up to the last occurrence of a substring.
Similar to upToFirstOccurrenceOf(), but this finds the last occurrence rather than the first. If the substring isn't found, this will return the whole of the original string.
See Also
upToFirstOccurrenceOf, fromFirstOccurrenceOf
String String::trim () const
Returns a copy of this string with any whitespace characters removed from the start and end.
String String::trimStart () const
Returns a copy of this string with any whitespace characters removed from the start.
String String::trimEnd () const
Returns a copy of this string with any whitespace characters removed from the end.
String String::trimCharactersAtStart (StringRef charactersToTrim) const
Returns a copy of this string, having removed a specified set of characters from its start.
Characters are removed from the start of the string until it finds one that is not in the specified set, and then it stops.
Parameters
charactersToTrim the set of characters to remove.
See Also
trim, trimStart, trimCharactersAtEnd
String String::trimCharactersAtEnd (StringRef charactersToTrim) const
Returns a copy of this string, having removed a specified set of characters from its end.
Characters are removed from the end of the string until it finds one that is not in the specified set, and then it stops.
Parameters
charactersToTrim the set of characters to remove.
See Also
trim, trimEnd, trimCharactersAtStart
String String::toUpperCase () const
Returns an upper-case version of this string.
String String::toLowerCase () const
Returns an lower-case version of this string.
String String::replaceSection (int startIndex, int numCharactersToReplace, StringRef stringToInsert) const
Replaces a sub-section of the string with another string.
This will return a copy of this string, with a set of characters from startIndex to startIndex + numCharsToReplace removed, and with a new string inserted in their place.
Note that this is a const method, and won't alter the string itself.
Parameters
startIndex the first character to remove. If this is beyond the bounds of the string, it will be constrained to a valid range.
numCharactersToReplace the number of characters to remove. If zero or less, no characters will be taken out.
stringToInsert the new string to insert at startIndex after the characters have been removed.
String String::replace (StringRef stringToReplace, StringRef stringToInsertInstead, bool ignoreCase = false) const
Replaces all occurrences of a substring with another string.
Returns a copy of this string, with any occurrences of stringToReplace swapped for stringToInsertInstead.
Note that this is a const method, and won't alter the string itself.
String String::replaceFirstOccurrenceOf (StringRef stringToReplace, StringRef stringToInsertInstead, bool ignoreCase = false) const
Replaces the first occurrence of a substring with another string.
Returns a copy of this string, with the first occurrence of stringToReplace swapped for stringToInsertInstead.
Note that this is a const method, and won't alter the string itself.
String String::replaceCharacter (juce_wchar characterToReplace, juce_wchar characterToInsertInstead) const
Returns a string with all occurrences of a character replaced with a different one.
String String::replaceCharacters (StringRef charactersToReplace, StringRef charactersToInsertInstead) const
Replaces a set of characters with another set.
Returns a string in which each character from charactersToReplace has been replaced by the character at the equivalent position in newCharacters (so the two strings passed in must be the same length).
e.g. replaceCharacters ("abc", "def") replaces 'a' with 'd', 'b' with 'e', etc.
Note that this is a const method, and won't affect the string itself.
String String::retainCharacters (StringRef charactersToRetain) const
Returns a version of this string that only retains a fixed set of characters.
This will return a copy of this string, omitting any characters which are not found in the string passed-in.
e.g. for "1122334455", retainCharacters ("432") would return "223344"
Note that this is a const method, and won't alter the string itself.
String String::removeCharacters (StringRef charactersToRemove) const
Returns a version of this string with a set of characters removed.
This will return a copy of this string, omitting any characters which are found in the string passed-in.
e.g. for "1122334455", removeCharacters ("432") would return "1155"
Note that this is a const method, and won't alter the string itself.
String String::initialSectionContainingOnly (StringRef permittedCharacters) const
Returns a section from the start of the string that only contains a certain set of characters.
This returns the leftmost section of the string, up to (and not including) the first character that doesn't appear in the string passed in.
String String::initialSectionNotContaining (StringRef charactersToStopAt) const
Returns a section from the start of the string that only contains a certain set of characters.
This returns the leftmost section of the string, up to (and not including) the first character that occurs in the string passed in. (If none of the specified characters are found in the string, the return value will just be the original string).
bool String::isQuotedString () const
Checks whether the string might be in quotation marks.
Returns
true if the string begins with a quote character (either a double or single quote). It is also true if there is whitespace before the quote, but it doesn't check the end of the string.
See Also
unquoted, quoted
String String::unquoted () const
Removes quotation marks from around the string, (if there are any).
Returns a copy of this string with any quotes removed from its ends. Quotes that aren't at the ends of the string are not affected. If there aren't any quotes, the original string is returned.
Note that this is a const method, and won't alter the string itself.
See Also
isQuotedString, quoted
String String::quoted (juce_wchar quoteCharacter = '"') const
Adds quotation marks around a string.
This will return a copy of the string with a quote at the start and end, (but won't add the quote if there's already one there, so it's safe to call this on strings that may already have quotes around them).
Note that this is a const method, and won't alter the string itself.
Parameters
quoteCharacter the character to add at the start and end
See Also
isQuotedString, unquoted
static String String::repeatedString (StringRef stringToRepeat, int numberOfTimesToRepeat) static
Creates a string which is a version of a string repeated and joined together.
Parameters
stringToRepeat the string to repeat
numberOfTimesToRepeat how many times to repeat it
String String::paddedLeft (juce_wchar padCharacter, int minimumLength) const
Returns a copy of this string with the specified character repeatedly added to its beginning until the total length is at least the minimum length specified.
String String::paddedRight (juce_wchar padCharacter, int minimumLength) const
Returns a copy of this string with the specified character repeatedly added to its end until the total length is at least the minimum length specified.
static String String::createStringFromData (const void * data, int size) static
Creates a string from data in an unknown format.
This looks at some binary data and tries to guess whether it's Unicode or 8-bit characters, then returns a string that represents it correctly.
Should be able to handle Unicode endianness correctly, by looking at the first two bytes.
template<typename... Args> static String String::formatted (const String & formatStr, Args... args) static
Creates a String from a printf-style parameter list.
I don't like this method. I don't use it myself, and I recommend avoiding it and using the operator<< methods or pretty much anything else instead. It's only provided here because of the popular unrest that was stirred-up when I tried to remove it...
If you're really determined to use it, at least make sure that you never, ever, pass any String objects to it as parameters. And bear in mind that internally, depending on the platform, it may be using wchar_t or char character types, so that even string literals can't be safely used as parameters if you're writing portable code.
int String::getIntValue () const noexcept
Reads the value of the string as a decimal number (up to 32 bits in size).
Returns
the value of the string as a 32 bit signed base-10 integer.
See Also
getTrailingIntValue, getHexValue32, getHexValue64
int64 String::getLargeIntValue () const noexcept
Reads the value of the string as a decimal number (up to 64 bits in size).
Returns
the value of the string as a 64 bit signed base-10 integer.
int String::getTrailingIntValue () const noexcept
Parses a decimal number from the end of the string.
This will look for a value at the end of the string. e.g. for "321 xyz654" it will return 654; for "2 3 4" it'll return 4.
Negative numbers are not handled, so "xyz-5" returns 5.
See Also
getIntValue
float String::getFloatValue () const noexcept
Parses this string as a floating point number.
Returns
the value of the string as a 32-bit floating point value.
See Also
getDoubleValue
double String::getDoubleValue () const noexcept
Parses this string as a floating point number.
Returns
the value of the string as a 64-bit floating point value.
See Also
getFloatValue
int String::getHexValue32 () const noexcept
Parses the string as a hexadecimal number.
Non-hexadecimal characters in the string are ignored.
If the string contains too many characters, then the lowest significant digits are returned, e.g. "ffff12345678" would produce 0x12345678.
Returns
a 32-bit number which is the value of the string in hex.
int64 String::getHexValue64 () const noexcept
Parses the string as a hexadecimal number.
Non-hexadecimal characters in the string are ignored.
If the string contains too many characters, then the lowest significant digits are returned, e.g. "ffff1234567812345678" would produce 0x1234567812345678.
Returns
a 64-bit number which is the value of the string in hex.
template<typename IntegerType > static String String::toHexString (IntegerType number) static
Returns a string representing this numeric value in hexadecimal.
Referenced by CppTokeniserFunctions::writeEscapeChars().
static String String::toHexString (const void * data, int size, int groupSize = 1) static
Returns a string containing a hex dump of a block of binary data.
Parameters
data the binary data to use as input
size how many bytes of data to use
groupSize how many bytes are grouped together before inserting a space into the output. e.g. group size 0 has no spaces, group size 1 looks like: "be a1 c2 ff", group size 2 looks like "bea1 c2ff".
CharPointerType String::getCharPointer () const noexcept
Returns the character pointer currently being used to store this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
Referenced by Identifier::getCharPointer(), Identifier::operator String::CharPointerType(), Identifier::operator!=(), and Identifier::operator==().
CharPointer_UTF8 String::toUTF8 () const
Returns a pointer to a UTF-8 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
To find out how many bytes you need to store this string as UTF-8, you can call CharPointer_UTF8::getBytesRequiredFor (myString.getCharPointer())
See Also
toRawUTF8, getCharPointer, toUTF16, toUTF32
const char* String::toRawUTF8 () const
Returns a pointer to a UTF-8 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
To find out how many bytes you need to store this string as UTF-8, you can call CharPointer_UTF8::getBytesRequiredFor (myString.getCharPointer())
See Also
getCharPointer, toUTF8, toUTF16, toUTF32
Referenced by CppTokeniserFunctions::addEscapeChars(), and operator<<().
CharPointer_UTF16 String::toUTF16 () const
Returns a pointer to a UTF-16 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
To find out how many bytes you need to store this string as UTF-16, you can call CharPointer_UTF16::getBytesRequiredFor (myString.getCharPointer())
See Also
getCharPointer, toUTF8, toUTF32
CharPointer_UTF32 String::toUTF32 () const
Returns a pointer to a UTF-32 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
See Also
getCharPointer, toUTF8, toUTF16
const wchar_t* String::toWideCharPointer () const
Returns a pointer to a wchar_t version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
Bear in mind that the wchar_t type is different on different platforms, so on Windows, this will be equivalent to calling toUTF16(), on unix it'll be the same as calling toUTF32(), etc.
See Also
getCharPointer, toUTF8, toUTF16, toUTF32
Referenced by operator<<().
std::string String::toStdString () const
static String String::fromUTF8 (const char * utf8buffer, int bufferSizeBytes = -1) static
Creates a String from a UTF-8 encoded buffer.
If the size is < 0, it'll keep reading until it hits a zero.
size_t String::getNumBytesAsUTF8 () const noexcept
Returns the number of bytes required to represent this string as UTF8.
The number returned does NOT include the trailing zero.
See Also
toUTF8, copyToUTF8
size_t String::copyToUTF8 (CharPointer_UTF8::CharType * destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-8 characters.
Returns the number of bytes copied to the buffer, including the terminating null character.
To find out how many bytes you need to store this string as UTF-8, you can call CharPointer_UTF8::getBytesRequiredFor (myString.getCharPointer())
Parameters
destBuffer the place to copy it to; if this is a null pointer, the method just returns the number of bytes required (including the terminating null character).
maxBufferSizeBytes the size of the destination buffer, in bytes. If the string won't fit, it'll put in as many as it can while still allowing for a terminating null char at the end, and will return the number of bytes that were actually used.
See Also
CharPointer_UTF8::writeWithDestByteLimit
size_t String::copyToUTF16 (CharPointer_UTF16::CharType * destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-16 characters.
Returns the number of bytes copied to the buffer, including the terminating null character.
To find out how many bytes you need to store this string as UTF-16, you can call CharPointer_UTF16::getBytesRequiredFor (myString.getCharPointer())
Parameters
destBuffer the place to copy it to; if this is a null pointer, the method just returns the number of bytes required (including the terminating null character).
maxBufferSizeBytes the size of the destination buffer, in bytes. If the string won't fit, it'll put in as many as it can while still allowing for a terminating null char at the end, and will return the number of bytes that were actually used.
See Also
CharPointer_UTF16::writeWithDestByteLimit
size_t String::copyToUTF32 (CharPointer_UTF32::CharType * destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-32 characters.
Returns the number of bytes copied to the buffer, including the terminating null character.
To find out how many bytes you need to store this string as UTF-32, you can call CharPointer_UTF32::getBytesRequiredFor (myString.getCharPointer())
Parameters
destBuffer the place to copy it to; if this is a null pointer, the method just returns the number of bytes required (including the terminating null character).
maxBufferSizeBytes the size of the destination buffer, in bytes. If the string won't fit, it'll put in as many as it can while still allowing for a terminating null char at the end, and will return the number of bytes that were actually used.
See Also
CharPointer_UTF32::writeWithDestByteLimit
void String::preallocateBytes (size_t numBytesNeeded)
Increases the string's internally allocated storage.
Although the string's contents won't be affected by this call, it will increase the amount of memory allocated internally for the string to grow into.
If you're about to make a large number of calls to methods such as += or <<, it's more efficient to preallocate enough extra space beforehand, so that these methods won't have to keep resizing the string to append the extra characters.
Parameters
numBytesNeeded the number of bytes to allocate storage for. If this value is less than the currently allocated size, it will have no effect.
Referenced by Rectangle< int >::toString().
void String::swapWith (String & other) noexcept
Swaps the contents of this string with another one.
This is a very fast operation, as no allocation or copying needs to be done.
static String String::fromCFString (CFStringRef cfString) static
OSX ONLY - Creates a String from an OSX CFString.
CFStringRef String::toCFString () const
OSX ONLY - Converts this string to a CFString.
Remember that you must use CFRelease() to free the returned string when you're finished with it.
String String::convertToPrecomposedUnicode () const
OSX ONLY - Returns a copy of this string in which any decomposed unicode characters have been converted to their precomposed equivalents.
int String::getReferenceCount () const noexcept
Returns the number of String objects which are currently sharing the same internal data as this one.
class StringArray
A special array for holding a list of strings.
See Also
String, StringPairArray
Public Member Functions
StringArray () noexcept
Creates an empty string array.
StringArray (const StringArray &)
Creates a copy of another string array.
StringArray (StringArray &&) noexcept
Move constructor.
StringArray (const String &firstValue)
Creates an array containing a single string.
StringArray (const String *strings, int numberOfStrings)
Creates an array from a raw array of strings.
StringArray (const char *const *strings, int numberOfStrings)
Creates a copy of an array of string literals.
StringArray (const char *const *strings)
Creates a copy of a null-terminated array of string literals.
StringArray (const wchar_t *const *strings)
Creates a copy of a null-terminated array of string literals.
StringArray (const wchar_t *const *strings, int numberOfStrings)
Creates a copy of an array of string literals.
StringArray (const std::initializer_list< const char * > &strings)
~StringArray ()
Destructor.
StringArray & operator= (const StringArray &)
Copies the contents of another string array into this one.
StringArray & operator= (StringArray &&) noexcept
Move assignment operator.
void swapWith (StringArray &) noexcept
Swaps the contents of this and another StringArray.
bool operator== (const StringArray &) const noexcept
Compares two arrays.
bool operator!= (const StringArray &) const noexcept
Compares two arrays.
int size () const noexcept
Returns the number of strings in the array.
bool isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
const String & operator[] (int index) const noexcept
Returns one of the strings from the array.
String & getReference (int index) noexcept
Returns a reference to one of the strings in the array.
String * begin () const noexcept
Returns a pointer to the first String in the array.
String * end () const noexcept
Returns a pointer to the String which follows the last element in the array.
bool contains (StringRef stringToLookFor, bool ignoreCase=false) const
Searches for a string in the array.
int indexOf (StringRef stringToLookFor, bool ignoreCase=false, int startIndex=0) const
Searches for a string in the array.
void add (const String &stringToAdd)
Appends a string at the end of the array.
void add (String &&stringToAdd)
Appends a string at the end of the array.
void insert (int index, const String &stringToAdd)
Inserts a string into the array.
bool addIfNotAlreadyThere (const String &stringToAdd, bool ignoreCase=false)
Adds a string to the array as long as it's not already in there.
void set (int index, const String &newString)
Replaces one of the strings in the array with another one.
void addArray (const StringArray &other, int startIndex=0, int numElementsToAdd=-1)
Appends some strings from another array to the end of this one.
void mergeArray (const StringArray &other, bool ignoreCase=false)
Merges the strings from another array into this one.
int addTokens (StringRef stringToTokenise, bool preserveQuotedStrings)
Breaks up a string into tokens and adds them to this array.
int addTokens (StringRef stringToTokenise, StringRef breakCharacters, StringRef quoteCharacters)
Breaks up a string into tokens and adds them to this array.
int addLines (StringRef stringToBreakUp)
Breaks up a string into lines and adds them to this array.
void clear ()
Removes all elements from the array.
void clearQuick ()
Removes all elements from the array without freeing the array's allocated storage.
void remove (int index)
Removes a string from the array.
void removeString (StringRef stringToRemove, bool ignoreCase=false)
Finds a string in the array and removes it.
void removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
void removeDuplicates (bool ignoreCase)
Removes any duplicated elements from the array.
void removeEmptyStrings (bool removeWhitespaceStrings=true)
Removes empty strings from the array.
void move (int currentIndex, int newIndex) noexcept
Moves one of the strings to a different position.
void trim ()
Deletes any whitespace characters from the starts and ends of all the strings.
void appendNumbersToDuplicates (bool ignoreCaseWhenComparing, bool appendNumberToFirstInstance, CharPointer_UTF8 preNumberString=CharPointer_UTF8(nullptr), CharPointer_UTF8 postNumberString=CharPointer_UTF8(nullptr))
Adds numbers to the strings in the array, to make each string unique.
String joinIntoString (StringRef separatorString, int startIndex=0, int numberOfElements=-1) const
Joins the strings in the array together into one string.
void sort (bool ignoreCase)
Sorts the array into alphabetical order.
void sortNatural ()
Sorts the array using extra language-aware rules to do a better job of comparing words containing spaces and numbers.
void ensureStorageAllocated (int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
void minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Static Public Member Functions
static StringArray fromTokens (StringRef stringToTokenise, bool preserveQuotedStrings)
Returns an array containing the tokens in a given string.
static StringArray fromTokens (StringRef stringToTokenise, StringRef breakCharacters, StringRef quoteCharacters)
Returns an array containing the tokens in a given string.
static StringArray fromLines (StringRef stringToBreakUp)
Returns an array containing the lines in a given string.
Public Attributes
Array< String > strings
This is the array holding the actual strings.
Constructor & Destructor Documentation
StringArray::StringArray () noexcept
Creates an empty string array.
StringArray::StringArray (const StringArray &)
Creates a copy of another string array.
StringArray::StringArray (StringArray &&) noexcept
Move constructor.
StringArray::StringArray (const String & firstValue) explicit
Creates an array containing a single string.
StringArray::StringArray (const String * strings, int numberOfStrings)
Creates an array from a raw array of strings.
Parameters
strings an array of strings to add
numberOfStrings how many items there are in the array
StringArray::StringArray (const char *const * strings, int numberOfStrings)
Creates a copy of an array of string literals.
Parameters
strings an array of strings to add. Null pointers in the array will be treated as empty strings
numberOfStrings how many items there are in the array
StringArray::StringArray (const char *const * strings) explicit
Creates a copy of a null-terminated array of string literals.
Each item from the array passed-in is added, until it encounters a null pointer, at which point it stops.
StringArray::StringArray (const wchar_t *const * strings) explicit
Creates a copy of a null-terminated array of string literals.
Each item from the array passed-in is added, until it encounters a null pointer, at which point it stops.
StringArray::StringArray (const wchar_t *const * strings, int numberOfStrings)
Creates a copy of an array of string literals.
Parameters
strings an array of strings to add. Null pointers in the array will be treated as empty strings
numberOfStrings how many items there are in the array
StringArray::StringArray (const std::initializer_list< const char * > & strings)
StringArray::~StringArray ()
Destructor.
Member Function Documentation
StringArray& StringArray::operator= (const StringArray &)
Copies the contents of another string array into this one.
StringArray& StringArray::operator= (StringArray &&) noexcept
Move assignment operator.
void StringArray::swapWith (StringArray &) noexcept
Swaps the contents of this and another StringArray.
bool StringArray::operator== (const StringArray &) const noexcept
Compares two arrays.
Comparisons are case-sensitive.
Returns
true only if the other array contains exactly the same strings in the same order
bool StringArray::operator!= (const StringArray &) const noexcept
Compares two arrays.
Comparisons are case-sensitive.
Returns
false if the other array contains exactly the same strings in the same order
int StringArray::size () const noexcept
Returns the number of strings in the array.
Referenced by KeyGeneration::keyGenerationAppMain().
bool StringArray::isEmpty () const noexcept
Returns true if the array is empty, false otherwise.
const String& StringArray::operator[] (int index) const noexcept
Returns one of the strings from the array.
If the index is out-of-range, an empty string is returned.
Obviously the reference returned shouldn't be stored for later use, as the string it refers to may disappear when the array changes.
String& StringArray::getReference (int index) noexcept
Returns a reference to one of the strings in the array.
This lets you modify a string in-place in the array, but you must be sure that the index is in-range.
String* StringArray::begin () const noexcept
Returns a pointer to the first String in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
String* StringArray::end () const noexcept
Returns a pointer to the String which follows the last element in the array.
This method is provided for compatibility with standard C++ iteration mechanisms.
bool StringArray::contains (StringRef stringToLookFor, bool ignoreCase = false) const
Searches for a string in the array.
The comparison will be case-insensitive if the ignoreCase parameter is true.
Returns
true if the string is found inside the array
int StringArray::indexOf (StringRef stringToLookFor, bool ignoreCase = false, int startIndex = 0) const
Searches for a string in the array.
The comparison will be case-insensitive if the ignoreCase parameter is true.
Parameters
stringToLookFor the string to try to find
ignoreCase whether the comparison should be case-insensitive
startIndex the first index to start searching from
Returns
the index of the first occurrence of the string in this array, or -1 if it isn't found.
void StringArray::add (const String & stringToAdd)
Appends a string at the end of the array.
Referenced by KeyGeneration::keyGenerationAppMain().
void StringArray::add (String && stringToAdd)
Appends a string at the end of the array.
void StringArray::insert (int index, const String & stringToAdd)
Inserts a string into the array.
This will insert a string into the array at the given index, moving up the other elements to make room for it. If the index is less than zero or greater than the size of the array, the new string will be added to the end of the array.
bool StringArray::addIfNotAlreadyThere (const String & stringToAdd, bool ignoreCase = false)
Adds a string to the array as long as it's not already in there.
The search can optionally be case-insensitive.
Returns
true if the string has been added, false otherwise.
void StringArray::set (int index, const String & newString)
Replaces one of the strings in the array with another one.
If the index is higher than the array's size, the new string will be added to the end of the array; if it's less than zero nothing happens.
void StringArray::addArray (const StringArray & other, int startIndex = 0, int numElementsToAdd = -1)
Appends some strings from another array to the end of this one.
Parameters
other the array to add
startIndex the first element of the other array to add
numElementsToAdd the maximum number of elements to add (if this is less than zero, they are all added)
void StringArray::mergeArray (const StringArray & other, bool ignoreCase = false)
Merges the strings from another array into this one.
This will not add a string that already exists.
Parameters
other the array to add
ignoreCase ignore case when merging
int StringArray::addTokens (StringRef stringToTokenise, bool preserveQuotedStrings)
Breaks up a string into tokens and adds them to this array.
This will tokenise the given string using whitespace characters as the token delimiters, and will add these tokens to the end of the array.
Returns
the number of tokens added
See Also
fromTokens
Referenced by Rectangle< int >::fromString().
int StringArray::addTokens (StringRef stringToTokenise, StringRef breakCharacters, StringRef quoteCharacters)
Breaks up a string into tokens and adds them to this array.
This will tokenise the given string (using the string passed in to define the token delimiters), and will add these tokens to the end of the array.
Parameters
stringToTokenise the string to tokenise
breakCharacters a string of characters, any of which will be considered to be a token delimiter.
quoteCharacters if this string isn't empty, it defines a set of characters which are treated as quotes. Any text occurring between quotes is not broken up into tokens.
Returns
the number of tokens added
See Also
fromTokens
int StringArray::addLines (StringRef stringToBreakUp)
Breaks up a string into lines and adds them to this array.
This breaks a string down into lines separated by \n or \r\n, and adds each line to the array. Line-break characters are omitted from the strings that are added to the array.
static StringArray StringArray::fromTokens (StringRef stringToTokenise, bool preserveQuotedStrings) static
Returns an array containing the tokens in a given string.
This will tokenise the given string using whitespace characters as the token delimiters, and return the parsed tokens as an array.
See Also
addTokens
static StringArray StringArray::fromTokens (StringRef stringToTokenise, StringRef breakCharacters, StringRef quoteCharacters) static
Returns an array containing the tokens in a given string.
This will tokenise the given string using the breakCharacters string to define the token delimiters, and will return the parsed tokens as an array.
Parameters
stringToTokenise the string to tokenise
breakCharacters a string of characters, any of which will be considered to be a token delimiter.
quoteCharacters if this string isn't empty, it defines a set of characters which are treated as quotes. Any text occurring between quotes is not broken up into tokens.
See Also
addTokens
static StringArray StringArray::fromLines (StringRef stringToBreakUp) static
Returns an array containing the lines in a given string.
This breaks a string down into lines separated by \n or \r\n, and returns an array containing these lines. Line-break characters are omitted from the strings that are added to the array.
void StringArray::clear ()
Removes all elements from the array.
void StringArray::clearQuick ()
Removes all elements from the array without freeing the array's allocated storage.
See Also
clear
void StringArray::remove (int index)
Removes a string from the array.
If the index is out-of-range, no action will be taken.
void StringArray::removeString (StringRef stringToRemove, bool ignoreCase = false)
Finds a string in the array and removes it.
This will remove all occurrences of the given string from the array. The comparison may be case-insensitive depending on the ignoreCase parameter.
void StringArray::removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
This will remove a set of elements, starting from the given index, and move subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters
startIndex the index of the first element to remove
numberToRemove how many elements should be removed
void StringArray::removeDuplicates (bool ignoreCase)
Removes any duplicated elements from the array.
If any string appears in the array more than once, only the first occurrence of it will be retained.
Parameters
ignoreCase whether to use a case-insensitive comparison
void StringArray::removeEmptyStrings (bool removeWhitespaceStrings = true)
Removes empty strings from the array.
Parameters
removeWhitespaceStrings if true, strings that only contain whitespace characters will also be removed
void StringArray::move (int currentIndex, int newIndex) noexcept
Moves one of the strings to a different position.
This will move the string to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the value to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this value to end up. If this is less than zero, the value will be moved to the end of the array
void StringArray::trim ()
Deletes any whitespace characters from the starts and ends of all the strings.
void StringArray::appendNumbersToDuplicates (bool ignoreCaseWhenComparing, bool appendNumberToFirstInstance, CharPointer_UTF8 preNumberString = CharPointer_UTF8(nullptr), CharPointer_UTF8 postNumberString = CharPointer_UTF8(nullptr))
Adds numbers to the strings in the array, to make each string unique.
This will add numbers to the ends of groups of similar strings. e.g. if there are two "moose" strings, they will become "moose (1)" and "moose (2)"
Parameters
ignoreCaseWhenComparing whether the comparison used is case-insensitive
appendNumberToFirstInstance whether the first of a group of similar strings also has a number appended to it.
preNumberString when adding a number, this string is added before the number. If you pass nullptr, a default string will be used, which adds brackets around the number.
postNumberString this string is appended after any numbers that are added. If you pass nullptr, a default string will be used, which adds brackets around the number.
String StringArray::joinIntoString (StringRef separatorString, int startIndex = 0, int numberOfElements = -1) const
Joins the strings in the array together into one string.
This will join a range of elements from the array into a string, separating them with a given string.
e.g. joinIntoString (",") will turn an array of "a" "b" and "c" into "a,b,c".
Parameters
separatorString the string to insert between all the strings
startIndex the first element to join
numberOfElements how many elements to join together. If this is less than zero, all available elements will be used.
void StringArray::sort (bool ignoreCase)
Sorts the array into alphabetical order.
Parameters
ignoreCase if true, the comparisons used will be case-sensitive.
void StringArray::sortNatural ()
Sorts the array using extra language-aware rules to do a better job of comparing words containing spaces and numbers.
See Also
String::compareNatural()
void StringArray::ensureStorageAllocated (int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
void StringArray::minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Member Data Documentation
Array<String> StringArray::strings
This is the array holding the actual strings.
This is public to allow direct access to array methods that may not already be provided by the StringArray class.
class StringPairArray
A container for holding a set of strings which are keyed by another string.
See Also
StringArray
Public Member Functions
StringPairArray (bool ignoreCaseWhenComparingKeys=true)
Creates an empty array.
StringPairArray (const StringPairArray &other)
Creates a copy of another array.
~StringPairArray ()
Destructor.
StringPairArray & operator= (const StringPairArray &other)
Copies the contents of another string array into this one.
bool operator== (const StringPairArray &other) const
Compares two arrays.
bool operator!= (const StringPairArray &other) const
Compares two arrays.
const String & operator[] (StringRef key) const
Finds the value corresponding to a key string.
String getValue (StringRef, const String &defaultReturnValue) const
Finds the value corresponding to a key string.
bool containsKey (StringRef key) const noexcept
Returns true if the given key exists.
const StringArray & getAllKeys () const noexcept
Returns a list of all keys in the array.
const StringArray & getAllValues () const noexcept
Returns a list of all values in the array.
int size () const noexcept
Returns the number of strings in the array.
void set (const String &key, const String &value)
Adds or amends a key/value pair.
void addArray (const StringPairArray &other)
Adds the items from another array to this one.
void clear ()
Removes all elements from the array.
void remove (StringRef key)
Removes a string from the array based on its key.
void remove (int index)
Removes a string from the array based on its index.
void setIgnoresCase (bool shouldIgnoreCase)
Indicates whether to use a case-insensitive search when looking up a key string.
String getDescription () const
Returns a descriptive string containing the items.
void minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Constructor & Destructor Documentation
StringPairArray::StringPairArray (bool ignoreCaseWhenComparingKeys = true)
Creates an empty array.
StringPairArray::StringPairArray (const StringPairArray & other)
Creates a copy of another array.
StringPairArray::~StringPairArray ()
Destructor.
Member Function Documentation
StringPairArray& StringPairArray::operator= (const StringPairArray & other)
Copies the contents of another string array into this one.
bool StringPairArray::operator== (const StringPairArray & other) const
Compares two arrays.
Comparisons are case-sensitive.
Returns
true only if the other array contains exactly the same strings with the same keys
bool StringPairArray::operator!= (const StringPairArray & other) const
Compares two arrays.
Comparisons are case-sensitive.
Returns
false if the other array contains exactly the same strings with the same keys
const String& StringPairArray::operator[] (StringRef key) const
Finds the value corresponding to a key string.
If no such key is found, this will just return an empty string. To check whether a given key actually exists (because it might actually be paired with an empty string), use the getAllKeys() method to obtain a list.
Obviously the reference returned shouldn't be stored for later use, as the string it refers to may disappear when the array changes.
See Also
getValue
String StringPairArray::getValue (StringRef , const String & defaultReturnValue) const
Finds the value corresponding to a key string.
If no such key is found, this will just return the value provided as a default.
See Also
operator[]
bool StringPairArray::containsKey (StringRef key) const noexcept
Returns true if the given key exists.
const StringArray& StringPairArray::getAllKeys () const noexcept
Returns a list of all keys in the array.
const StringArray& StringPairArray::getAllValues () const noexcept
Returns a list of all values in the array.
int StringPairArray::size () const noexcept
Returns the number of strings in the array.
void StringPairArray::set (const String & key, const String & value)
Adds or amends a key/value pair.
If a value already exists with this key, its value will be overwritten, otherwise the key/value pair will be added to the array.
void StringPairArray::addArray (const StringPairArray & other)
Adds the items from another array to this one.
This is equivalent to using set() to add each of the pairs from the other array.
void StringPairArray::clear ()
Removes all elements from the array.
void StringPairArray::remove (StringRef key)
Removes a string from the array based on its key.
If the key isn't found, nothing will happen.
void StringPairArray::remove (int index)
Removes a string from the array based on its index.
If the index is out-of-range, no action will be taken.
void StringPairArray::setIgnoresCase (bool shouldIgnoreCase)
Indicates whether to use a case-insensitive search when looking up a key string.
String StringPairArray::getDescription () const
Returns a descriptive string containing the items.
This is handy for dumping the contents of an array.
void StringPairArray::minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
class StringPool
A StringPool holds a set of shared strings, which reduces storage overheads and improves comparison speed when dealing with many duplicate strings.
When you add a string to a pool using getPooledString, it'll return a character array containing the same string. This array is owned by the pool, and the same array is returned every time a matching string is asked for. This means that it's trivial to compare two pooled strings for equality, as you can simply compare their pointers. It also cuts down on storage if you're using many copies of the same string.
Public Member Functions
StringPool () noexcept
Creates an empty pool.
~StringPool ()
Destructor.
String getPooledString (const String &original)
Returns a pointer to a shared copy of the string that is passed in.
String getPooledString (const char *original)
Returns a pointer to a copy of the string that is passed in.
String getPooledString (StringRef original)
Returns a pointer to a shared copy of the string that is passed in.
String getPooledString (String::CharPointerType start, String::CharPointerType end)
Returns a pointer to a copy of the string that is passed in.
void garbageCollect ()
Scans the pool, and removes any strings that are unreferenced.
Static Public Member Functions
static StringPool & getGlobalPool () noexcept
Returns a shared global pool which is used for things like Identifiers, XML parsing.
Constructor & Destructor Documentation
StringPool::StringPool () noexcept
Creates an empty pool.
StringPool::~StringPool ()
Destructor.
Member Function Documentation
String StringPool::getPooledString (const String & original)
Returns a pointer to a shared copy of the string that is passed in.
The pool will always return the same String object when asked for a string that matches it.
String StringPool::getPooledString (const char * original)
Returns a pointer to a copy of the string that is passed in.
The pool will always return the same String object when asked for a string that matches it.
String StringPool::getPooledString (StringRef original)
Returns a pointer to a shared copy of the string that is passed in.
The pool will always return the same String object when asked for a string that matches it.
String StringPool::getPooledString (String::CharPointerType start, String::CharPointerType end)
Returns a pointer to a copy of the string that is passed in.
The pool will always return the same String object when asked for a string that matches it.
void StringPool::garbageCollect ()
Scans the pool, and removes any strings that are unreferenced.
You don't generally need to call this - it'll be called automatically when the pool grows large enough to warrant it.
static StringPool& StringPool::getGlobalPool () static noexcept
Returns a shared global pool which is used for things like Identifiers, XML parsing.
class StringRef
A simple class for holding temporary references to a string literal or String.
Unlike a real String object, the StringRef does not allocate any memory or take ownership of the strings you give to it - it simply holds a reference to a string that has been allocated elsewhere. The main purpose of the class is to be used instead of a const String& as the type of function arguments where the caller may pass either a string literal or a String object. This means that when the called uses a string literal, there's no need for an temporary String object to be allocated, and this cuts down overheads substantially.
Because the class is simply a wrapper around a pointer, you should always pass it by value, not by reference.
void myStringFunction1 (const String&);
void myStringFunction2 (StringRef);
myStringFunction1 ("abc"); // Implicitly allocates a temporary String object.
myStringFunction2 ("abc"); // Much faster, as no local allocations are needed.
For examples of it in use, see the XmlElement or StringArray classes.
Bear in mind that there are still many cases where it's better to use an argument which is a const String&. For example if the function stores the string or needs to internally create a String from the argument, then it's better for the original argument to already be a String.
See Also
String
Public Member Functions
StringRef (const char *stringLiteral) noexcept
Creates a StringRef from a raw string literal.
StringRef (String::CharPointerType stringLiteral) noexcept
Creates a StringRef from a raw char pointer.
StringRef (const String &string) noexcept
Creates a StringRef from a String.
StringRef () noexcept
Creates a StringRef pointer to an empty string.
operator const String::CharPointerType::CharType * () const noexcept
Returns a raw pointer to the underlying string data.
operator String::CharPointerType () const noexcept
Returns a pointer to the underlying string data as a char pointer object.
bool isEmpty () const noexcept
Returns true if the string is empty.
bool isNotEmpty () const noexcept
Returns true if the string is not empty.
int length () const noexcept
Returns the number of characters in the string.
juce_wchar operator[] (int index) const noexcept
Retrieves a character by index.
bool operator== (const String &s) const noexcept
Compares this StringRef with a String.
bool operator!= (const String &s) const noexcept
Compares this StringRef with a String.
bool operator== (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
bool operator!= (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
Public Attributes
String::CharPointerType text
The text that is referenced.
Constructor & Destructor Documentation
StringRef::StringRef (const char * stringLiteral) noexcept
Creates a StringRef from a raw string literal.
The StringRef object does NOT take ownership or copy this data, so you must ensure that the data does not change during the lifetime of the StringRef. Note that this pointer not be null!
StringRef::StringRef (String::CharPointerType stringLiteral) noexcept
Creates a StringRef from a raw char pointer.
The StringRef object does NOT take ownership or copy this data, so you must ensure that the data does not change during the lifetime of the StringRef.
StringRef::StringRef (const String & string) noexcept
Creates a StringRef from a String.
The StringRef object does NOT take ownership or copy the data from the String, so you must ensure that the String is not modified or deleted during the lifetime of the StringRef.
StringRef::StringRef () noexcept
Creates a StringRef pointer to an empty string.
Member Function Documentation
StringRef::operator const String::CharPointerType::CharType * () const noexcept
Returns a raw pointer to the underlying string data.
StringRef::operator String::CharPointerType () const noexcept
Returns a pointer to the underlying string data as a char pointer object.
bool StringRef::isEmpty () const noexcept
Returns true if the string is empty.
bool StringRef::isNotEmpty () const noexcept
Returns true if the string is not empty.
int StringRef::length () const noexcept
Returns the number of characters in the string.
juce_wchar StringRef::operator[] (int index) const noexcept
Retrieves a character by index.
bool StringRef::operator== (const String & s) const noexcept
Compares this StringRef with a String.
bool StringRef::operator!= (const String & s) const noexcept
Compares this StringRef with a String.
bool StringRef::operator== (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
bool StringRef::operator!= (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
Member Data Documentation
String::CharPointerType StringRef::text
The text that is referenced.
Referenced by Rectangle< int >::fromString(), and operator+().
class TextDiff
Calculates and applies a sequence of changes to convert one text string into another.
Once created, the TextDiff object contains an array of change objects, where each change can be either an insertion or a deletion. When applied in order to the original string, these changes will convert it to the target string.
Public Member Functions
TextDiff (const String &original, const String &target)
Creates a set of diffs for converting the original string into the target.
String appliedTo (String text) const
Applies this sequence of changes to the original string, producing the target string that was specified when generating them.
Public Attributes
Array< Change > changes
The list of changes required to perform the transformation.
Constructor & Destructor Documentation
TextDiff::TextDiff (const String & original, const String & target)
Creates a set of diffs for converting the original string into the target.
Member Function Documentation
String TextDiff::appliedTo (String text) const
Applies this sequence of changes to the original string, producing the target string that was specified when generating them.
Obviously it only makes sense to call this function with the string that was originally passed to the constructor. Any other input will produce an undefined result.
Member Data Documentation
Array<Change> TextDiff::changes
The list of changes required to perform the transformation.
Applying each of these, in order, to the original string will produce the target.
Macro Definition Documentation
#define JUCE_NATIVE_WCHAR_IS_UTF8 0
This macro will be set to 1 if the compiler's native wchar_t is an 8-bit type.
#define JUCE_NATIVE_WCHAR_IS_UTF16 0
This macro will be set to 1 if the compiler's native wchar_t is a 16-bit type.
#define JUCE_NATIVE_WCHAR_IS_UTF32 1
This macro will be set to 1 if the compiler's native wchar_t is a 32-bit type.
#define TRANS (stringLiteral) juce::translate (stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
This macro is provided for backwards-compatibility, and just calls the translate() function. In new code, it's recommended that you just call translate() directly instead, and avoid using macros.
See Also
translate(), LocalisedStrings
Referenced by StandalonePluginHolder::askUserToLoadState(), StandalonePluginHolder::askUserToSaveState(), StandaloneFilterWindow::buttonClicked(), and StandalonePluginHolder::showAudioSettingsDialog().
#define NEEDS_TRANS (stringLiteral) (stringLiteral)
A dummy version of the TRANS macro, used to indicate a string literal that should be added to the translation file by source-code scanner tools.
Wrapping a string literal in this macro has no effect, but by using it around strings that your app needs to translate at a later stage, it lets automatic code-scanning tools find this string and add it to the list of strings that need translation.
Typedef Documentation
typedef wchar_t juce_wchar
A platform-independent 32-bit unicode character type.
Function Documentation
JUCE_API String translate (const String & stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
See Also
LocalisedStrings
JUCE_API String translate (const char * stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
See Also
LocalisedStrings
JUCE_API String translate (CharPointer_UTF8 stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
See Also
LocalisedStrings
JUCE_API String translate (const String & stringLiteral, const String & resultIfNotFound)
Uses the LocalisedStrings class to translate the given string literal.
See Also
LocalisedStrings
String& operator<< (String & string1, const NewLine &)
Writes a new-line sequence to a string.
You can use the predefined object 'newLine' to invoke this, e.g.
myString << "Hello World" << newLine << newLine;
References NewLine::getDefault().
String& operator+= (String & s1, const NewLine &)
References NewLine::getDefault().
String operator+ (const NewLine & , const NewLine &)
References NewLine::getDefault().
String operator+ (String s1, const NewLine &)
References NewLine::getDefault().
String operator+ (const NewLine & , const char * s2)
References NewLine::getDefault().
JUCE_API String JUCE_CALLTYPE operator+ (const char * string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (const wchar_t * string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (char string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (wchar_t string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const String & string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const char * string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, const wchar_t * string2)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, char characterToAppend)
Concatenates two strings.
JUCE_API String JUCE_CALLTYPE operator+ (String string1, wchar_t characterToAppend)
Concatenates two strings.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, char characterToAppend)
Appends a character at the end of a string.
JUCE_API String &JUCE_CALLTYPE operator<< (String & string1, wchar_t characterToAppend)
Appends a character at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, const char * string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, const wchar_t * string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, const String & string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, StringRef string2)
Appends a string to the end of the first one.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, short number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, int number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, long number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, unsigned long number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, int64 number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, uint64 number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, float number)
Appends a decimal number at the end of a string.
JUCE_API String& JUCE_CALLTYPE operator<< (String & string1, double number)
Appends a decimal number at the end of a string.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const char * string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const wchar_t * string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, const CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const char * string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const wchar_t * string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, const CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator> (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator< (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator>= (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator<= (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
template<class traits > std::basic_ostream<char, traits>& JUCE_CALLTYPE operator<< (std::basic_ostream< char, traits > & stream, const String & stringToWrite)
This operator allows you to write a juce String directly to std output streams.
This is handy for writing strings to std::cout, std::cerr, etc.
References String::toRawUTF8().
template<class traits > std::basic_ostream<wchar_t, traits>& JUCE_CALLTYPE operator<< (std::basic_ostream< wchar_t, traits > & stream, const String & stringToWrite)
This operator allows you to write a juce String directly to std output streams.
This is handy for writing strings to std::wcout, std::wcerr, etc.
References String::toWideCharPointer().
JUCE_API OutputStream& JUCE_CALLTYPE operator<< (OutputStream & stream, const String & stringToWrite)
Writes a string to an OutputStream as UTF8.
JUCE_API OutputStream& JUCE_CALLTYPE operator<< (OutputStream & stream, StringRef stringToWrite)
Writes a string to an OutputStream as UTF8.
JUCE_API bool JUCE_CALLTYPE operator== (const String & string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
JUCE_API bool JUCE_CALLTYPE operator!= (const String & string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
String operator+ (String s1, StringRef s2)
References StringRef::text.
String operator+ (StringRef s1, const String & s2)
References StringRef::text.
String operator+ (const char * s1, StringRef s2)
References StringRef::text.
String operator+ (StringRef s1, const char * s2)
References StringRef::text.
Variable Documentation
NewLine newLine
A predefined object representing a new-line, which can be written to a string or stream.
To write a new-line to a stream, you can use the predefined 'newLine' variable like this:
myOutputStream << "Hello World" << newLine << newLine;
Referenced by CppTokeniserFunctions::writeEscapeChars().