JUCE: keyboard
keyboard
juce_gui_basics
Classes
class CaretComponent
class KeyboardFocusTraverser
Controls the order in which focus moves between components.
class KeyListener
Receives callbacks when keys are pressed.
class KeyPress
Represents a key press, including any modifier keys that are needed.
class ModifierKeys
Represents the state of the mouse buttons and modifier keys.
class SystemClipboard
Handles reading/writing to the system's clipboard.
struct TextEditorKeyMapper< CallbackClass >
This class is used to invoke a range of text-editor navigation methods on an object, based upon a keypress event.
class TextInputTarget
An abstract base class which can be implemented by components that function as text editors.
Detailed Description
Class Documentation
class CaretComponent
Public Types
enum ColourIds { caretColourId = 0x1000204 }
A set of colour IDs to use to change the colour of various aspects of the caret.
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusChanged() and focusLost() methods.
Public Member Functions
CaretComponent (Component *keyFocusOwner)
Creates the caret component.
~CaretComponent ()
Destructor.
virtual void setCaretPosition (const Rectangle< int > &characterArea)
Sets the caret's position to place it next to the given character.
void paint (Graphics &) override
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
virtual ~Component ()
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
virtual void visibilityChanged ()
Called when this component's visibility changes.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (int x, int y, int width, int height, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void parentHierarchyChanged ()
Called to indicate that the component's parents have changed.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
virtual void lookAndFeelChanged ()
Called to let the component react to a change in the look-and-feel setting.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparancy level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
virtual void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
virtual void mouseDown (const MouseEvent &event) override
Called when a mouse button is pressed.
virtual void mouseDrag (const MouseEvent &event) override
Called when the mouse is moved while a button is held down.
virtual void mouseUp (const MouseEvent &event) override
Called when a mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
virtual void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel) override
Called when the mouse-wheel is moved.
virtual void mouseMagnify (const MouseEvent &event, float scaleFactor)
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyPressed (const KeyPress &key)
Called when a key is pressed.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown () const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void resized ()
Called when this component's size has been changed.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourId, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourId, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourId)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourId) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
virtual MarkerList * getMarkers (bool xAxis)
Components can implement this method to provide a MarkerList.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
JUCE_DEPRECATED (Point< int > relativePositionToGlobal(Point< int >) const)
JUCE_DEPRECATED (Point< int > globalPositionToRelative(Point< int >) const)
JUCE_DEPRECATED (Point< int > relativePositionToOtherComponent(const Component *, Point< int >) const)
JUCE_DEPRECATED (void setBounds(const RelativeRectangle &))
JUCE_DEPRECATED (void setBounds(const String &))
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Member Enumeration Documentation
enum CaretComponent::ColourIds
A set of colour IDs to use to change the colour of various aspects of the caret.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
See Also
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator
caretColourId
The colour with which to draw the caret.
Constructor & Destructor Documentation
CaretComponent::CaretComponent (Component * keyFocusOwner)
Creates the caret component.
The keyFocusOwner is an optional component which the caret will check, making itself visible only when the keyFocusOwner has keyboard focus.
CaretComponent::~CaretComponent ()
Destructor.
Member Function Documentation
virtual void CaretComponent::setCaretPosition (const Rectangle< int > & characterArea) virtual
Sets the caret's position to place it next to the given character.
The area is the rectangle containing the entire character that the caret is positioned on, so by default a vertical-line caret may choose to just show itself at the left of this area. You can override this method to customise its size. This method will also force the caret to reset its timer and become visible (if appropriate), so that as it moves, you can see where it is.
void CaretComponent::paint (Graphics &) override virtual
Reimplemented from Component.
class KeyboardFocusTraverser
Controls the order in which focus moves between components.
The default algorithm used by this class to work out the order of traversal is as follows:
if two components both have an explicit focus order specified, then the one with the lowest number comes first (see the Component::setExplicitFocusOrder() method).
any component with an explicit focus order greater than 0 comes before ones that don't have an order specified.
any unspecified components are traversed in a left-to-right, then top-to-bottom order.
If you need traversal in a more customised way, you can create a subclass of KeyboardFocusTraverser that uses your own algorithm, and use Component::createFocusTraverser() to create it.
See Also
Component::setExplicitFocusOrder, Component::createFocusTraverser
Public Member Functions
KeyboardFocusTraverser ()
virtual ~KeyboardFocusTraverser ()
Destructor.
virtual Component * getNextComponent (Component *current)
Returns the component that should be given focus after the specified one when moving "forwards".
virtual Component * getPreviousComponent (Component *current)
Returns the component that should be given focus after the specified one when moving "backwards".
virtual Component * getDefaultComponent (Component *parentComponent)
Returns the component that should receive focus be default within the given parent component.
Constructor & Destructor Documentation
KeyboardFocusTraverser::KeyboardFocusTraverser ()
virtual KeyboardFocusTraverser::~KeyboardFocusTraverser () virtual
Destructor.
Member Function Documentation
virtual Component* KeyboardFocusTraverser::getNextComponent (Component * current) virtual
Returns the component that should be given focus after the specified one when moving "forwards".
The default implementation will return the next component which is to the right of or below this one.
This may return nullptr if there's no suitable candidate.
virtual Component* KeyboardFocusTraverser::getPreviousComponent (Component * current) virtual
Returns the component that should be given focus after the specified one when moving "backwards".
The default implementation will return the next component which is to the left of or above this one.
This may return nullptr if there's no suitable candidate.
virtual Component* KeyboardFocusTraverser::getDefaultComponent (Component * parentComponent) virtual
Returns the component that should receive focus be default within the given parent component.
The default implementation will just return the foremost child component that wants focus.
This may return nullptr if there's no suitable candidate.
class KeyListener
Receives callbacks when keys are pressed.
You can add a key listener to a component to be informed when that component gets key events. See the Component::addListener method for more details.
See Also
KeyPress, Component::addKeyListener, KeyPressMappingSet
Public Member Functions
virtual ~KeyListener ()
Destructor.
virtual bool keyPressed (const KeyPress &key, Component *originatingComponent)=0
Called to indicate that a key has been pressed.
virtual bool keyStateChanged (bool isKeyDown, Component *originatingComponent)
Called when any key is pressed or released.
Constructor & Destructor Documentation
virtual KeyListener::~KeyListener () virtual
Destructor.
Member Function Documentation
virtual bool KeyListener::keyPressed (const KeyPress & key, Component * originatingComponent) pure virtual
Called to indicate that a key has been pressed.
If your implementation returns true, then the key event is considered to have been consumed, and will not be passed on to any other components. If it returns false, then the key will be passed to other components that might want to use it.
Parameters
key the keystroke, including modifier keys
originatingComponent the component that received the key event
See Also
keyStateChanged, Component::keyPressed
Implemented in KeyPressMappingSet.
virtual bool KeyListener::keyStateChanged (bool isKeyDown, Component * originatingComponent) virtual
Called when any key is pressed or released.
When this is called, classes that might be interested in the state of one or more keys can use KeyPress::isKeyCurrentlyDown() to check whether their key has changed.
If your implementation returns true, then the key event is considered to have been consumed, and will not be passed on to any other components. If it returns false, then the key will be passed to other components that might want to use it.
Parameters
originatingComponent the component that received the key event
isKeyDown true if a key is being pressed, false if one is being released
See Also
KeyPress, Component::keyStateChanged
Reimplemented in KeyPressMappingSet.
class KeyPress
Represents a key press, including any modifier keys that are needed.
E.g. a KeyPress might represent CTRL+C, SHIFT+ALT+H, Spacebar, Escape, etc.
See Also
Component, KeyListener, KeyPressMappingSet, Button::addShortcut
Public Member Functions
KeyPress () noexcept
Creates an (invalid) KeyPress.
KeyPress (int keyCode, ModifierKeys modifiers, juce_wchar textCharacter) noexcept
Creates a KeyPress for a key and some modifiers.
KeyPress (int keyCode) noexcept
Creates a keypress with a keyCode but no modifiers or text character.
KeyPress (const KeyPress &other) noexcept
Creates a copy of another KeyPress.
KeyPress & operator= (const KeyPress &other) noexcept
Copies this KeyPress from another one.
bool operator== (const KeyPress &other) const noexcept
Compares two KeyPress objects.
bool operator!= (const KeyPress &other) const noexcept
Compares two KeyPress objects.
bool operator== (int keyCode) const noexcept
Returns true if this keypress is for the given keycode without any modifiers.
bool operator!= (int keyCode) const noexcept
Returns true if this keypress is not for the given keycode without any modifiers.
bool isValid () const noexcept
Returns true if this is a valid KeyPress.
int getKeyCode () const noexcept
Returns the key code itself.
ModifierKeys getModifiers () const noexcept
Returns the key modifiers.
juce_wchar getTextCharacter () const noexcept
Returns the character that is associated with this keypress.
bool isKeyCode (int keyCodeToCompare) const noexcept
Checks whether the KeyPress's key is the same as the one provided, without checking the modifiers.
String getTextDescription () const
Creates a textual description of the key combination.
String getTextDescriptionWithIcons () const
Creates a textual description of the key combination, using unicode icon symbols if possible.
bool isCurrentlyDown () const
Checks whether the user is currently holding down the keys that make up this KeyPress.
Static Public Member Functions
static KeyPress createFromDescription (const String &textVersion)
Converts a textual key description to a KeyPress.
static bool isKeyCurrentlyDown (int keyCode)
Checks whether a particular key is held down, irrespective of modifiers.
Static Public Attributes
static const int spaceKey
key-code for the space bar
static const int escapeKey
key-code for the escape key
static const int returnKey
key-code for the return key
static const int tabKey
key-code for the tab key
static const int deleteKey
key-code for the delete key (not backspace)
static const int backspaceKey
key-code for the backspace key
static const int insertKey
key-code for the insert key
static const int upKey
key-code for the cursor-up key
static const int downKey
key-code for the cursor-down key
static const int leftKey
key-code for the cursor-left key
static const int rightKey
key-code for the cursor-right key
static const int pageUpKey
key-code for the page-up key
static const int pageDownKey
key-code for the page-down key
static const int homeKey
key-code for the home key
static const int endKey
key-code for the end key
static const int F1Key
key-code for the F1 key
static const int F2Key
key-code for the F2 key
static const int F3Key
key-code for the F3 key
static const int F4Key
key-code for the F4 key
static const int F5Key
key-code for the F5 key
static const int F6Key
key-code for the F6 key
static const int F7Key
key-code for the F7 key
static const int F8Key
key-code for the F8 key
static const int F9Key
key-code for the F9 key
static const int F10Key
key-code for the F10 key
static const int F11Key
key-code for the F11 key
static const int F12Key
key-code for the F12 key
static const int F13Key
key-code for the F13 key
static const int F14Key
key-code for the F14 key
static const int F15Key
key-code for the F15 key
static const int F16Key
key-code for the F16 key
static const int numberPad0
key-code for the 0 on the numeric keypad.
static const int numberPad1
key-code for the 1 on the numeric keypad.
static const int numberPad2
key-code for the 2 on the numeric keypad.
static const int numberPad3
key-code for the 3 on the numeric keypad.
static const int numberPad4
key-code for the 4 on the numeric keypad.
static const int numberPad5
key-code for the 5 on the numeric keypad.
static const int numberPad6
key-code for the 6 on the numeric keypad.
static const int numberPad7
key-code for the 7 on the numeric keypad.
static const int numberPad8
key-code for the 8 on the numeric keypad.
static const int numberPad9
key-code for the 9 on the numeric keypad.
static const int numberPadAdd
key-code for the add sign on the numeric keypad.
static const int numberPadSubtract
key-code for the subtract sign on the numeric keypad.
static const int numberPadMultiply
key-code for the multiply sign on the numeric keypad.
static const int numberPadDivide
key-code for the divide sign on the numeric keypad.
static const int numberPadSeparator
key-code for the comma on the numeric keypad.
static const int numberPadDecimalPoint
key-code for the decimal point sign on the numeric keypad.
static const int numberPadEquals
key-code for the equals key on the numeric keypad.
static const int numberPadDelete
key-code for the delete key on the numeric keypad.
static const int playKey
key-code for a multimedia 'play' key, (not all keyboards will have one)
static const int stopKey
key-code for a multimedia 'stop' key, (not all keyboards will have one)
static const int fastForwardKey
key-code for a multimedia 'fast-forward' key, (not all keyboards will have one)
static const int rewindKey
key-code for a multimedia 'rewind' key, (not all keyboards will have one)
Constructor & Destructor Documentation
KeyPress::KeyPress () noexcept
Creates an (invalid) KeyPress.
See Also
isValid
KeyPress::KeyPress (int keyCode, ModifierKeys modifiers, juce_wchar textCharacter) noexcept
Creates a KeyPress for a key and some modifiers.
e.g. CTRL+C would be: KeyPress ('c', ModifierKeys::ctrlModifier) SHIFT+Escape would be: KeyPress (KeyPress::escapeKey, ModifierKeys::shiftModifier)
Parameters
keyCode a code that represents the key - this value must be one of special constants listed in this class, or an 8-bit character code such as a letter (case is ignored), digit or a simple key like "," or ".". Note that this isn't the same as the textCharacter parameter, so for example a keyCode of 'a' and a shift-key modifier should have a textCharacter value of 'A'.
modifiers the modifiers to associate with the keystroke
textCharacter the character that would be printed if someone typed this keypress into a text editor. This value may be null if the keypress is a non-printing character
See Also
getKeyCode, isKeyCode, getModifiers
KeyPress::KeyPress (int keyCode) explicit noexcept
Creates a keypress with a keyCode but no modifiers or text character.
KeyPress::KeyPress (const KeyPress & other) noexcept
Creates a copy of another KeyPress.
Member Function Documentation
KeyPress& KeyPress::operator= (const KeyPress & other) noexcept
Copies this KeyPress from another one.
bool KeyPress::operator== (const KeyPress & other) const noexcept
Compares two KeyPress objects.
bool KeyPress::operator!= (const KeyPress & other) const noexcept
Compares two KeyPress objects.
bool KeyPress::operator== (int keyCode) const noexcept
Returns true if this keypress is for the given keycode without any modifiers.
bool KeyPress::operator!= (int keyCode) const noexcept
Returns true if this keypress is not for the given keycode without any modifiers.
bool KeyPress::isValid () const noexcept
Returns true if this is a valid KeyPress.
A null keypress can be created by the default constructor, in case it's needed.
int KeyPress::getKeyCode () const noexcept
Returns the key code itself.
This will either be one of the special constants defined in this class, or an 8-bit character code.
ModifierKeys KeyPress::getModifiers () const noexcept
Returns the key modifiers.
See Also
ModifierKeys
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
juce_wchar KeyPress::getTextCharacter () const noexcept
Returns the character that is associated with this keypress.
This is the character that you'd expect to see printed if you press this keypress in a text editor or similar component.
bool KeyPress::isKeyCode (int keyCodeToCompare) const noexcept
Checks whether the KeyPress's key is the same as the one provided, without checking the modifiers.
The values for key codes can either be one of the special constants defined in this class, or an 8-bit character code.
See Also
getKeyCode
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
static KeyPress KeyPress::createFromDescription (const String & textVersion) static
Converts a textual key description to a KeyPress.
This attempts to decode a textual version of a keypress, e.g. "CTRL + C" or "SPACE".
This isn't designed to cope with any kind of input, but should be given the strings that are created by the getTextDescription() method.
If the string can't be parsed, the object returned will be invalid.
See Also
getTextDescription
String KeyPress::getTextDescription () const
Creates a textual description of the key combination.
e.g. "CTRL + C" or "DELETE".
To store a keypress in a file, use this method, along with createFromDescription() to retrieve it later.
String KeyPress::getTextDescriptionWithIcons () const
Creates a textual description of the key combination, using unicode icon symbols if possible.
On OSX, this uses the Apple symbols for command, option, shift, etc, instead of the textual modifier key descriptions that are returned by getTextDescription()
bool KeyPress::isCurrentlyDown () const
Checks whether the user is currently holding down the keys that make up this KeyPress.
Note that this will return false if any extra modifier keys are down - e.g. if the keypress is CTRL+X and the user is actually holding CTRL+ALT+x then it will be false.
static bool KeyPress::isKeyCurrentlyDown (int keyCode) static
Checks whether a particular key is held down, irrespective of modifiers.
The values for key codes can either be one of the special constants defined in this class, or an 8-bit character code.
Member Data Documentation
const int KeyPress::spaceKey static
key-code for the space bar
const int KeyPress::escapeKey static
key-code for the escape key
const int KeyPress::returnKey static
key-code for the return key
const int KeyPress::tabKey static
key-code for the tab key
const int KeyPress::deleteKey static
key-code for the delete key (not backspace)
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::backspaceKey static
key-code for the backspace key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::insertKey static
key-code for the insert key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::upKey static
key-code for the cursor-up key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::downKey static
key-code for the cursor-down key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::leftKey static
key-code for the cursor-left key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::rightKey static
key-code for the cursor-right key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::pageUpKey static
key-code for the page-up key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::pageDownKey static
key-code for the page-down key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::homeKey static
key-code for the home key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::endKey static
key-code for the end key
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
const int KeyPress::F1Key static
key-code for the F1 key
const int KeyPress::F2Key static
key-code for the F2 key
const int KeyPress::F3Key static
key-code for the F3 key
const int KeyPress::F4Key static
key-code for the F4 key
const int KeyPress::F5Key static
key-code for the F5 key
const int KeyPress::F6Key static
key-code for the F6 key
const int KeyPress::F7Key static
key-code for the F7 key
const int KeyPress::F8Key static
key-code for the F8 key
const int KeyPress::F9Key static
key-code for the F9 key
const int KeyPress::F10Key static
key-code for the F10 key
const int KeyPress::F11Key static
key-code for the F11 key
const int KeyPress::F12Key static
key-code for the F12 key
const int KeyPress::F13Key static
key-code for the F13 key
const int KeyPress::F14Key static
key-code for the F14 key
const int KeyPress::F15Key static
key-code for the F15 key
const int KeyPress::F16Key static
key-code for the F16 key
const int KeyPress::numberPad0 static
key-code for the 0 on the numeric keypad.
const int KeyPress::numberPad1 static
key-code for the 1 on the numeric keypad.
const int KeyPress::numberPad2 static
key-code for the 2 on the numeric keypad.
const int KeyPress::numberPad3 static
key-code for the 3 on the numeric keypad.
const int KeyPress::numberPad4 static
key-code for the 4 on the numeric keypad.
const int KeyPress::numberPad5 static
key-code for the 5 on the numeric keypad.
const int KeyPress::numberPad6 static
key-code for the 6 on the numeric keypad.
const int KeyPress::numberPad7 static
key-code for the 7 on the numeric keypad.
const int KeyPress::numberPad8 static
key-code for the 8 on the numeric keypad.
const int KeyPress::numberPad9 static
key-code for the 9 on the numeric keypad.
const int KeyPress::numberPadAdd static
key-code for the add sign on the numeric keypad.
const int KeyPress::numberPadSubtract static
key-code for the subtract sign on the numeric keypad.
const int KeyPress::numberPadMultiply static
key-code for the multiply sign on the numeric keypad.
const int KeyPress::numberPadDivide static
key-code for the divide sign on the numeric keypad.
const int KeyPress::numberPadSeparator static
key-code for the comma on the numeric keypad.
const int KeyPress::numberPadDecimalPoint static
key-code for the decimal point sign on the numeric keypad.
const int KeyPress::numberPadEquals static
key-code for the equals key on the numeric keypad.
const int KeyPress::numberPadDelete static
key-code for the delete key on the numeric keypad.
const int KeyPress::playKey static
key-code for a multimedia 'play' key, (not all keyboards will have one)
const int KeyPress::stopKey static
key-code for a multimedia 'stop' key, (not all keyboards will have one)
const int KeyPress::fastForwardKey static
key-code for a multimedia 'fast-forward' key, (not all keyboards will have one)
const int KeyPress::rewindKey static
key-code for a multimedia 'rewind' key, (not all keyboards will have one)
class ModifierKeys
Represents the state of the mouse buttons and modifier keys.
This is used both by mouse events and by KeyPress objects to describe the state of keys such as shift, control, alt, etc.
See Also
KeyPress, MouseEvent::mods
Public Types
enum Flags {
noModifiers = 0, shiftModifier = 1, ctrlModifier = 2, altModifier = 4,
leftButtonModifier = 16, rightButtonModifier = 32, middleButtonModifier = 64, commandModifier = 8,
popupMenuClickModifier = rightButtonModifier | ctrlModifier, allKeyboardModifiers = shiftModifier | ctrlModifier | altModifier | commandModifier, allMouseButtonModifiers = leftButtonModifier | rightButtonModifier | middleButtonModifier, ctrlAltCommandModifiers = ctrlModifier | altModifier | commandModifier
}
Flags that represent the different keys.
Public Member Functions
ModifierKeys () noexcept
Creates a ModifierKeys object with no flags set.
ModifierKeys (int flags) noexcept
Creates a ModifierKeys object from a raw set of flags.
ModifierKeys (const ModifierKeys &other) noexcept
Creates a copy of another object.
ModifierKeys & operator= (const ModifierKeys other) noexcept
Copies this object from another one.
bool isCommandDown () const noexcept
Checks whether the 'command' key flag is set (or 'ctrl' on Windows/Linux).
bool isPopupMenu () const noexcept
Checks whether the user is trying to launch a pop-up menu.
bool isLeftButtonDown () const noexcept
Checks whether the flag is set for the left mouse-button.
bool isRightButtonDown () const noexcept
Checks whether the flag is set for the right mouse-button.
bool isMiddleButtonDown () const noexcept
bool isAnyMouseButtonDown () const noexcept
Tests for any of the mouse-button flags.
bool isAnyModifierKeyDown () const noexcept
Tests for any of the modifier key flags.
bool isShiftDown () const noexcept
Checks whether the shift key's flag is set.
bool isCtrlDown () const noexcept
Checks whether the CTRL key's flag is set.
bool isAltDown () const noexcept
Checks whether the ALT key's flag is set.
ModifierKeys withOnlyMouseButtons () const noexcept
Returns a copy of only the mouse-button flags.
ModifierKeys withoutMouseButtons () const noexcept
Returns a copy of only the non-mouse flags.
bool operator== (const ModifierKeys other) const noexcept
bool operator!= (const ModifierKeys other) const noexcept
int getRawFlags () const noexcept
Returns the raw flags for direct testing.
ModifierKeys withoutFlags (int rawFlagsToClear) const noexcept
ModifierKeys withFlags (int rawFlagsToSet) const noexcept
bool testFlags (int flagsToTest) const noexcept
Tests a combination of flags and returns true if any of them are set.
int getNumMouseButtonsDown () const noexcept
Returns the total number of mouse buttons that are down.
Static Public Member Functions
static ModifierKeys getCurrentModifiers () noexcept
Creates a ModifierKeys object to represent the last-known state of the keyboard and mouse buttons.
static ModifierKeys getCurrentModifiersRealtime () noexcept
Creates a ModifierKeys object to represent the current state of the keyboard and mouse buttons.
Member Enumeration Documentation
enum ModifierKeys::Flags
Flags that represent the different keys.
Enumerator
noModifiers
Indicates no modifier keys.
shiftModifier
Shift key flag.
ctrlModifier
CTRL key flag.
altModifier
ALT key flag.
leftButtonModifier
Left mouse button flag.
rightButtonModifier
Right mouse button flag.
middleButtonModifier
Middle mouse button flag.
commandModifier
Command key flag - on windows this is the same as the CTRL key flag.
popupMenuClickModifier
Popup menu flag - on windows this is the same as rightButtonModifier, on the Mac it's the same as (rightButtonModifier | ctrlModifier).
allKeyboardModifiers
Represents a combination of all the shift, alt, ctrl and command key modifiers.
allMouseButtonModifiers
Represents a combination of all the mouse buttons at once.
ctrlAltCommandModifiers
Represents a combination of all the alt, ctrl and command key modifiers.
Constructor & Destructor Documentation
ModifierKeys::ModifierKeys () noexcept
Creates a ModifierKeys object with no flags set.
ModifierKeys::ModifierKeys (int flags) noexcept
Creates a ModifierKeys object from a raw set of flags.
Parameters
flags to represent the keys that are down
See Also
shiftModifier, ctrlModifier, altModifier, leftButtonModifier, rightButtonModifier, commandModifier, popupMenuClickModifier
ModifierKeys::ModifierKeys (const ModifierKeys & other) noexcept
Creates a copy of another object.
Member Function Documentation
ModifierKeys& ModifierKeys::operator= (const ModifierKeys other) noexcept
Copies this object from another one.
bool ModifierKeys::isCommandDown () const noexcept
Checks whether the 'command' key flag is set (or 'ctrl' on Windows/Linux).
This is a platform-agnostic way of checking for the operating system's preferred command-key modifier - so on the Mac it tests for the Apple key, on Windows/Linux, it's actually checking for the CTRL key.
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), LassoComponent< SelectableItemType >::dragLasso(), and TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
bool ModifierKeys::isPopupMenu () const noexcept
Checks whether the user is trying to launch a pop-up menu.
This checks for platform-specific modifiers that might indicate that the user is following the operating system's normal method of showing a pop-up menu.
So on Windows/Linux, this method is really testing for a right-click. On the Mac, it tests for either the CTRL key being down, or a right-click.
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionOnMouseDown().
bool ModifierKeys::isLeftButtonDown () const noexcept
Checks whether the flag is set for the left mouse-button.
bool ModifierKeys::isRightButtonDown () const noexcept
Checks whether the flag is set for the right mouse-button.
Note that for detecting popup-menu clicks, you should be using isPopupMenu() instead, as this is platform-independent (and makes your code more explanatory too).
bool ModifierKeys::isMiddleButtonDown () const noexcept
bool ModifierKeys::isAnyMouseButtonDown () const noexcept
Tests for any of the mouse-button flags.
Referenced by FakeMouseMoveGenerator::timerCallback().
bool ModifierKeys::isAnyModifierKeyDown () const noexcept
Tests for any of the modifier key flags.
bool ModifierKeys::isShiftDown () const noexcept
Checks whether the shift key's flag is set.
Referenced by SelectedItemSet< SelectableItemType >::addToSelectionBasedOnModifiers(), LassoComponent< SelectableItemType >::dragLasso(), and TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
bool ModifierKeys::isCtrlDown () const noexcept
Checks whether the CTRL key's flag is set.
Remember that it's better to use the platform-agnostic routines to test for command-key and popup-menu modifiers.
See Also
isCommandDown, isPopupMenu
Referenced by TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
bool ModifierKeys::isAltDown () const noexcept
Checks whether the ALT key's flag is set.
Referenced by LassoComponent< SelectableItemType >::dragLasso(), and TextEditorKeyMapper< CallbackClass >::invokeKeyFunction().
ModifierKeys ModifierKeys::withOnlyMouseButtons () const noexcept
Returns a copy of only the mouse-button flags.
ModifierKeys ModifierKeys::withoutMouseButtons () const noexcept
Returns a copy of only the non-mouse flags.
bool ModifierKeys::operator== (const ModifierKeys other) const noexcept
bool ModifierKeys::operator!= (const ModifierKeys other) const noexcept
int ModifierKeys::getRawFlags () const noexcept
Returns the raw flags for direct testing.
ModifierKeys ModifierKeys::withoutFlags (int rawFlagsToClear) const noexcept
ModifierKeys ModifierKeys::withFlags (int rawFlagsToSet) const noexcept
bool ModifierKeys::testFlags (int flagsToTest) const noexcept
Tests a combination of flags and returns true if any of them are set.
int ModifierKeys::getNumMouseButtonsDown () const noexcept
Returns the total number of mouse buttons that are down.
static ModifierKeys ModifierKeys::getCurrentModifiers () static noexcept
Creates a ModifierKeys object to represent the last-known state of the keyboard and mouse buttons.
See Also
getCurrentModifiersRealtime
Referenced by FakeMouseMoveGenerator::timerCallback().
static ModifierKeys ModifierKeys::getCurrentModifiersRealtime () static noexcept
Creates a ModifierKeys object to represent the current state of the keyboard and mouse buttons.
This isn't often needed and isn't recommended, but will actively check all the mouse and key states rather than just returning their last-known state like getCurrentModifiers() does.
This is only needed in special circumstances for up-to-date modifier information at times when the app's event loop isn't running normally.
Another reason to avoid this method is that it's not stateless, and calling it may update the value returned by getCurrentModifiers(), which could cause subtle changes in the behaviour of some components.
class SystemClipboard
Handles reading/writing to the system's clipboard.
Static Public Member Functions
static void copyTextToClipboard (const String &text)
Copies a string of text onto the clipboard.
static String getTextFromClipboard ()
Gets the current clipboard's contents.
Member Function Documentation
static void SystemClipboard::copyTextToClipboard (const String & text) static
Copies a string of text onto the clipboard.
static String SystemClipboard::getTextFromClipboard () static
Gets the current clipboard's contents.
Obviously this might have come from another app, so could contain anything..
struct TextEditorKeyMapper
template<class CallbackClass>
struct TextEditorKeyMapper< CallbackClass >
This class is used to invoke a range of text-editor navigation methods on an object, based upon a keypress event.
It's currently used internally by the TextEditor and CodeEditorComponent.
Static Public Member Functions
static bool invokeKeyFunction (CallbackClass &target, const KeyPress &key)
Checks the keypress and invokes one of a range of navigation functions that the target class must implement, based on the key event.
Member Function Documentation
template<class CallbackClass > static bool TextEditorKeyMapper< CallbackClass >::invokeKeyFunction (CallbackClass & target, const KeyPress & key) static
Checks the keypress and invokes one of a range of navigation functions that the target class must implement, based on the key event.
References KeyPress::backspaceKey, ModifierKeys::commandModifier, ModifierKeys::ctrlModifier, KeyPress::deleteKey, KeyPress::downKey, KeyPress::endKey, KeyPress::getModifiers(), KeyPress::homeKey, KeyPress::insertKey, ModifierKeys::isAltDown(), ModifierKeys::isCommandDown(), ModifierKeys::isCtrlDown(), KeyPress::isKeyCode(), ModifierKeys::isShiftDown(), KeyPress::leftKey, KeyPress::pageDownKey, KeyPress::pageUpKey, KeyPress::rightKey, ModifierKeys::shiftModifier, and KeyPress::upKey.
class TextInputTarget
An abstract base class which can be implemented by components that function as text editors.
This class allows different types of text editor component to provide a uniform interface, which can be used by things like OS-specific input methods, on-screen keyboards, etc.
Public Types
enum VirtualKeyboardType {
textKeyboard = 0, numericKeyboard, decimalKeyboard, urlKeyboard,
emailAddressKeyboard, phoneNumberKeyboard
}
A set of possible on-screen keyboard types, for use in the getKeyboardType() method.
Public Member Functions
TextInputTarget ()
virtual ~TextInputTarget ()
Destructor.
virtual bool isTextInputActive () const =0
Returns true if this input target is currently accepting input.
virtual Range< int > getHighlightedRegion () const =0
Returns the extents of the selected text region, or an empty range if nothing is selected,.
virtual void setHighlightedRegion (const Range< int > &newRange)=0
Sets the currently-selected text region.
virtual void setTemporaryUnderlining (const Array< Range< int > > &underlinedRegions)=0
Sets a number of temporarily underlined sections.
virtual String getTextInRange (const Range< int > &range) const =0
Returns a specified sub-section of the text.
virtual void insertTextAtCaret (const String &textToInsert)=0
Inserts some text, overwriting the selected text region, if there is one.
virtual Rectangle< int > getCaretRectangle ()=0
Returns the position of the caret, relative to the component's origin.
virtual VirtualKeyboardType getKeyboardType ()
Returns the target's preference for the type of keyboard that would be most appropriate.
Member Enumeration Documentation
enum TextInputTarget::VirtualKeyboardType
A set of possible on-screen keyboard types, for use in the getKeyboardType() method.
Enumerator
textKeyboard
numericKeyboard
decimalKeyboard
urlKeyboard
emailAddressKeyboard
phoneNumberKeyboard
Constructor & Destructor Documentation
TextInputTarget::TextInputTarget ()
virtual TextInputTarget::~TextInputTarget () virtual
Destructor.
Member Function Documentation
virtual bool TextInputTarget::isTextInputActive () const pure virtual
Returns true if this input target is currently accepting input.
For example, a text editor might return false if it's in read-only mode.
Implemented in TextEditor, and CodeEditorComponent.
virtual Range<int> TextInputTarget::getHighlightedRegion () const pure virtual
Returns the extents of the selected text region, or an empty range if nothing is selected,.
Implemented in TextEditor, and CodeEditorComponent.
virtual void TextInputTarget::setHighlightedRegion (const Range< int > & newRange) pure virtual
Sets the currently-selected text region.
Implemented in TextEditor, and CodeEditorComponent.
virtual void TextInputTarget::setTemporaryUnderlining (const Array< Range< int > > & underlinedRegions) pure virtual
Sets a number of temporarily underlined sections.
This is needed by MS Windows input method UI.
Implemented in TextEditor, and CodeEditorComponent.
virtual String TextInputTarget::getTextInRange (const Range< int > & range) const pure virtual
Returns a specified sub-section of the text.
Implemented in TextEditor, and CodeEditorComponent.
virtual void TextInputTarget::insertTextAtCaret (const String & textToInsert) pure virtual
Inserts some text, overwriting the selected text region, if there is one.
Implemented in TextEditor, and CodeEditorComponent.
virtual Rectangle<int> TextInputTarget::getCaretRectangle () pure virtual
Returns the position of the caret, relative to the component's origin.
Implemented in TextEditor, and CodeEditorComponent.
virtual VirtualKeyboardType TextInputTarget::getKeyboardType () virtual
Returns the target's preference for the type of keyboard that would be most appropriate.
This may be ignored, depending on the capabilities of the OS.
Reimplemented in TextEditor.