JUCE: sources
sources
juce_audio_basics
Classes
struct AudioSourceChannelInfo
Used by AudioSource::getNextAudioBlock().
class AudioSource
Base class for objects that can produce a continuous stream of audio.
class BufferingAudioSource
An AudioSource which takes another source as input, and buffers it using a thread.
class ChannelRemappingAudioSource
An AudioSource that takes the audio from another source, and re-maps its input and output channels to a different arrangement.
class IIRFilterAudioSource
An AudioSource that performs an IIR filter on another source.
class MemoryAudioSource
An AudioSource which takes some float audio data as an input.
class MixerAudioSource
An AudioSource that mixes together the output of a set of other AudioSources.
class PositionableAudioSource
A type of AudioSource which can be repositioned.
class ResamplingAudioSource
A type of AudioSource that takes an input source and changes its sample rate.
class ReverbAudioSource
An AudioSource that uses the Reverb class to apply a reverb to another AudioSource.
class ToneGeneratorAudioSource
A simple AudioSource that generates a sine wave.
Detailed Description
Class Documentation
struct AudioSourceChannelInfo
Used by AudioSource::getNextAudioBlock().
Public Member Functions
AudioSourceChannelInfo () noexcept
Creates an uninitialised AudioSourceChannelInfo.
AudioSourceChannelInfo (AudioSampleBuffer *bufferToUse, int startSampleOffset, int numSamplesToUse) noexcept
Creates an AudioSourceChannelInfo.
AudioSourceChannelInfo (AudioSampleBuffer &bufferToUse) noexcept
Creates an AudioSourceChannelInfo that uses the whole of a buffer.
void clearActiveBufferRegion () const
Convenient method to clear the buffer if the source is not producing any data.
Public Attributes
AudioSampleBuffer * buffer
The destination buffer to fill with audio data.
int startSample
The first sample in the buffer from which the callback is expected to write data.
int numSamples
The number of samples in the buffer which the callback is expected to fill with data.
Constructor & Destructor Documentation
AudioSourceChannelInfo::AudioSourceChannelInfo () noexcept
Creates an uninitialised AudioSourceChannelInfo.
AudioSourceChannelInfo::AudioSourceChannelInfo (AudioSampleBuffer * bufferToUse, int startSampleOffset, int numSamplesToUse) noexcept
Creates an AudioSourceChannelInfo.
AudioSourceChannelInfo::AudioSourceChannelInfo (AudioSampleBuffer & bufferToUse) explicit noexcept
Creates an AudioSourceChannelInfo that uses the whole of a buffer.
Note that the buffer provided must not be deleted while the AudioSourceChannelInfo is still using it.
Member Function Documentation
void AudioSourceChannelInfo::clearActiveBufferRegion () const
Convenient method to clear the buffer if the source is not producing any data.
Member Data Documentation
AudioSampleBuffer* AudioSourceChannelInfo::buffer
The destination buffer to fill with audio data.
When the AudioSource::getNextAudioBlock() method is called, the active section of this buffer should be filled with whatever output the source produces.
Only the samples specified by the startSample and numSamples members of this structure should be affected by the call.
The contents of the buffer when it is passed to the AudioSource::getNextAudioBlock() method can be treated as the input if the source is performing some kind of filter operation, but should be cleared if this is not the case - the clearActiveBufferRegion() is a handy way of doing this.
The number of channels in the buffer could be anything, so the AudioSource must cope with this in whatever way is appropriate for its function.
int AudioSourceChannelInfo::startSample
The first sample in the buffer from which the callback is expected to write data.
int AudioSourceChannelInfo::numSamples
The number of samples in the buffer which the callback is expected to fill with data.
class AudioSource
Base class for objects that can produce a continuous stream of audio.
An AudioSource has two states: 'prepared' and 'unprepared'.
When a source needs to be played, it is first put into a 'prepared' state by a call to prepareToPlay(), and then repeated calls will be made to its getNextAudioBlock() method to process the audio data.
Once playback has finished, the releaseResources() method is called to put the stream back into an 'unprepared' state.
See Also
AudioFormatReaderSource, ResamplingAudioSource
Public Member Functions
virtual ~AudioSource ()
Destructor.
virtual void prepareToPlay (int samplesPerBlockExpected, double sampleRate)=0
Tells the source to prepare for playing.
virtual void releaseResources ()=0
Allows the source to release anything it no longer needs after playback has stopped.
virtual void getNextAudioBlock (const AudioSourceChannelInfo &bufferToFill)=0
Called repeatedly to fetch subsequent blocks of audio data.
Protected Member Functions
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
AudioSource::AudioSource () protected noexcept
Creates an AudioSource.
virtual AudioSource::~AudioSource () virtual
Destructor.
Member Function Documentation
virtual void AudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) pure virtual
Tells the source to prepare for playing.
An AudioSource has two states: prepared and unprepared.
The prepareToPlay() method is guaranteed to be called at least once on an 'unpreprared' source to put it into a 'prepared' state before any calls will be made to getNextAudioBlock(). This callback allows the source to initialise any resources it might need when playing.
Once playback has finished, the releaseResources() method is called to put the stream back into an 'unprepared' state.
Note that this method could be called more than once in succession without a matching call to releaseResources(), so make sure your code is robust and can handle that kind of situation.
Parameters
samplesPerBlockExpected the number of samples that the source will be expected to supply each time its getNextAudioBlock() method is called. This number may vary slightly, because it will be dependent on audio hardware callbacks, and these aren't guaranteed to always use a constant block size, so the source should be able to cope with small variations.
sampleRate the sample rate that the output will be used at - this is needed by sources such as tone generators.
See Also
releaseResources, getNextAudioBlock
Implemented in AudioTransportSource, ChannelRemappingAudioSource, MixerAudioSource, AudioAppComponent, AudioFormatReaderSource, BufferingAudioSource, ResamplingAudioSource, ReverbAudioSource, IIRFilterAudioSource, ToneGeneratorAudioSource, and MemoryAudioSource.
virtual void AudioSource::releaseResources () pure virtual
Allows the source to release anything it no longer needs after playback has stopped.
This will be called when the source is no longer going to have its getNextAudioBlock() method called, so it should release any spare memory, etc. that it might have allocated during the prepareToPlay() call.
Note that there's no guarantee that prepareToPlay() will actually have been called before releaseResources(), and it may be called more than once in succession, so make sure your code is robust and doesn't make any assumptions about when it will be called.
See Also
prepareToPlay, getNextAudioBlock
Implemented in AudioTransportSource, ChannelRemappingAudioSource, AudioAppComponent, MixerAudioSource, AudioFormatReaderSource, BufferingAudioSource, ResamplingAudioSource, ReverbAudioSource, IIRFilterAudioSource, ToneGeneratorAudioSource, and MemoryAudioSource.
virtual void AudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) pure virtual
Called repeatedly to fetch subsequent blocks of audio data.
After calling the prepareToPlay() method, this callback will be made each time the audio playback hardware (or whatever other destination the audio data is going to) needs another block of data.
It will generally be called on a high-priority system thread, or possibly even an interrupt, so be careful not to do too much work here, as that will cause audio glitches!
See Also
AudioSourceChannelInfo, prepareToPlay, releaseResources
Implemented in AudioTransportSource, ChannelRemappingAudioSource, AudioAppComponent, MixerAudioSource, AudioFormatReaderSource, BufferingAudioSource, ResamplingAudioSource, ReverbAudioSource, ToneGeneratorAudioSource, IIRFilterAudioSource, and MemoryAudioSource.
class BufferingAudioSource
An AudioSource which takes another source as input, and buffers it using a thread.
Create this as a wrapper around another thread, and it will read-ahead with a background thread to smooth out playback. You can either create one of these directly, or use it indirectly using an AudioTransportSource.
See Also
PositionableAudioSource, AudioTransportSource
Public Member Functions
BufferingAudioSource (PositionableAudioSource *source, TimeSliceThread &backgroundThread, bool deleteSourceWhenDeleted, int numberOfSamplesToBuffer, int numberOfChannels=2, bool prefillBufferOnPrepareToPlay=true)
Creates a BufferingAudioSource.
~BufferingAudioSource ()
Destructor.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Implementation of the AudioSource method.
void setNextReadPosition (int64 newPosition) override
Implements the PositionableAudioSource method.
int64 getNextReadPosition () const override
Implements the PositionableAudioSource method.
int64 getTotalLength () const override
Implements the PositionableAudioSource method.
bool isLooping () const override
Implements the PositionableAudioSource method.
bool waitForNextAudioBlockReady (const AudioSourceChannelInfo &info, const uint32 timeout)
A useful function to block until the next the buffer info can be filled.
Public Member Functions inherited from PositionableAudioSource
~PositionableAudioSource ()
Destructor.
virtual void setLooping (bool shouldLoop)
Tells the source whether you'd like it to play in a loop.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from PositionableAudioSource
PositionableAudioSource () noexcept
Creates the PositionableAudioSource.
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
BufferingAudioSource::BufferingAudioSource (PositionableAudioSource * source, TimeSliceThread & backgroundThread, bool deleteSourceWhenDeleted, int numberOfSamplesToBuffer, int numberOfChannels = 2, bool prefillBufferOnPrepareToPlay = true)
Creates a BufferingAudioSource.
Parameters
source the input source to read from
backgroundThread a background thread that will be used for the background read-ahead. This object must not be deleted until after any BufferingAudioSources that are using it have been deleted!
deleteSourceWhenDeleted if true, then the input source object will be deleted when this object is deleted
numberOfSamplesToBuffer the size of buffer to use for reading ahead
numberOfChannels the number of channels that will be played
prefillBufferOnPrepareToPlay if true, then calling prepareToPlay on this object will block until the buffer has been filled
BufferingAudioSource::~BufferingAudioSource ()
Destructor.
The input source may be deleted depending on whether the deleteSourceWhenDeleted flag was set in the constructor.
Member Function Documentation
void BufferingAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void BufferingAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void BufferingAudioSource::getNextAudioBlock (const AudioSourceChannelInfo &) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void BufferingAudioSource::setNextReadPosition (int64 newPosition) override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
int64 BufferingAudioSource::getNextReadPosition () const override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
int64 BufferingAudioSource::getTotalLength () const override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
References PositionableAudioSource::getTotalLength().
bool BufferingAudioSource::isLooping () const override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
References PositionableAudioSource::isLooping().
bool BufferingAudioSource::waitForNextAudioBlockReady (const AudioSourceChannelInfo & info, const uint32 timeout)
A useful function to block until the next the buffer info can be filled.
This is useful for offline rendering.
class ChannelRemappingAudioSource
An AudioSource that takes the audio from another source, and re-maps its input and output channels to a different arrangement.
You can use this to increase or decrease the number of channels that an audio source uses, or to re-order those channels.
Call the reset() method before using it to set up a default mapping, and then the setInputChannelMapping() and setOutputChannelMapping() methods to create an appropriate mapping, otherwise no channels will be connected and it'll produce silence.
See Also
AudioSource
Public Member Functions
ChannelRemappingAudioSource (AudioSource *source, bool deleteSourceWhenDeleted)
Creates a remapping source that will pass on audio from the given input.
~ChannelRemappingAudioSource ()
Destructor.
void setNumberOfChannelsToProduce (int requiredNumberOfChannels)
Specifies a number of channels that this audio source must produce from its getNextAudioBlock() callback.
void clearAllMappings ()
Clears any mapped channels.
void setInputChannelMapping (int destChannelIndex, int sourceChannelIndex)
Creates an input channel mapping.
void setOutputChannelMapping (int sourceChannelIndex, int destChannelIndex)
Creates an output channel mapping.
int getRemappedInputChannel (int inputChannelIndex) const
Returns the channel from our input that will be sent to channel inputChannelIndex of our input audio source.
int getRemappedOutputChannel (int outputChannelIndex) const
Returns the output channel to which channel outputChannelIndex of our input audio source will be sent to.
XmlElement * createXml () const
Returns an XML object to encapsulate the state of the mappings.
void restoreFromXml (const XmlElement &)
Restores the mappings from an XML object created by createXML().
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Tells the source to prepare for playing.
void releaseResources () override
Allows the source to release anything it no longer needs after playback has stopped.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Called repeatedly to fetch subsequent blocks of audio data.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
ChannelRemappingAudioSource::ChannelRemappingAudioSource (AudioSource * source, bool deleteSourceWhenDeleted)
Creates a remapping source that will pass on audio from the given input.
Parameters
source the input source to use. Make sure that this doesn't get deleted before the ChannelRemappingAudioSource object
deleteSourceWhenDeleted if true, the input source will be deleted when this object is deleted, if false, the caller is responsible for its deletion
ChannelRemappingAudioSource::~ChannelRemappingAudioSource ()
Destructor.
Member Function Documentation
void ChannelRemappingAudioSource::setNumberOfChannelsToProduce (int requiredNumberOfChannels)
Specifies a number of channels that this audio source must produce from its getNextAudioBlock() callback.
void ChannelRemappingAudioSource::clearAllMappings ()
Clears any mapped channels.
After this, no channels are mapped, so this object will produce silence. Create some mappings with setInputChannelMapping() and setOutputChannelMapping().
void ChannelRemappingAudioSource::setInputChannelMapping (int destChannelIndex, int sourceChannelIndex)
Creates an input channel mapping.
When the getNextAudioBlock() method is called, the data in channel sourceChannelIndex of the incoming data will be sent to destChannelIndex of our input source.
Parameters
destChannelIndex the index of an input channel in our input audio source (i.e. the source specified when this object was created).
sourceChannelIndex the index of the input channel in the incoming audio data buffer during our getNextAudioBlock() callback
void ChannelRemappingAudioSource::setOutputChannelMapping (int sourceChannelIndex, int destChannelIndex)
Creates an output channel mapping.
When the getNextAudioBlock() method is called, the data returned in channel sourceChannelIndex by our input audio source will be copied to channel destChannelIndex of the final buffer.
Parameters
sourceChannelIndex the index of an output channel coming from our input audio source (i.e. the source specified when this object was created).
destChannelIndex the index of the output channel in the incoming audio data buffer during our getNextAudioBlock() callback
int ChannelRemappingAudioSource::getRemappedInputChannel (int inputChannelIndex) const
Returns the channel from our input that will be sent to channel inputChannelIndex of our input audio source.
int ChannelRemappingAudioSource::getRemappedOutputChannel (int outputChannelIndex) const
Returns the output channel to which channel outputChannelIndex of our input audio source will be sent to.
XmlElement* ChannelRemappingAudioSource::createXml () const
Returns an XML object to encapsulate the state of the mappings.
See Also
restoreFromXml
void ChannelRemappingAudioSource::restoreFromXml (const XmlElement &)
Restores the mappings from an XML object created by createXML().
See Also
createXml
void ChannelRemappingAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Tells the source to prepare for playing.
An AudioSource has two states: prepared and unprepared.
The prepareToPlay() method is guaranteed to be called at least once on an 'unpreprared' source to put it into a 'prepared' state before any calls will be made to getNextAudioBlock(). This callback allows the source to initialise any resources it might need when playing.
Once playback has finished, the releaseResources() method is called to put the stream back into an 'unprepared' state.
Note that this method could be called more than once in succession without a matching call to releaseResources(), so make sure your code is robust and can handle that kind of situation.
Parameters
samplesPerBlockExpected the number of samples that the source will be expected to supply each time its getNextAudioBlock() method is called. This number may vary slightly, because it will be dependent on audio hardware callbacks, and these aren't guaranteed to always use a constant block size, so the source should be able to cope with small variations.
sampleRate the sample rate that the output will be used at - this is needed by sources such as tone generators.
See Also
releaseResources, getNextAudioBlock
Implements AudioSource.
void ChannelRemappingAudioSource::releaseResources () override virtual
Allows the source to release anything it no longer needs after playback has stopped.
This will be called when the source is no longer going to have its getNextAudioBlock() method called, so it should release any spare memory, etc. that it might have allocated during the prepareToPlay() call.
Note that there's no guarantee that prepareToPlay() will actually have been called before releaseResources(), and it may be called more than once in succession, so make sure your code is robust and doesn't make any assumptions about when it will be called.
See Also
prepareToPlay, getNextAudioBlock
Implements AudioSource.
void ChannelRemappingAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) override virtual
Called repeatedly to fetch subsequent blocks of audio data.
After calling the prepareToPlay() method, this callback will be made each time the audio playback hardware (or whatever other destination the audio data is going to) needs another block of data.
It will generally be called on a high-priority system thread, or possibly even an interrupt, so be careful not to do too much work here, as that will cause audio glitches!
See Also
AudioSourceChannelInfo, prepareToPlay, releaseResources
Implements AudioSource.
class IIRFilterAudioSource
An AudioSource that performs an IIR filter on another source.
Public Member Functions
IIRFilterAudioSource (AudioSource *inputSource, bool deleteInputWhenDeleted)
Creates a IIRFilterAudioSource for a given input source.
~IIRFilterAudioSource ()
Destructor.
void setCoefficients (const IIRCoefficients &newCoefficients)
Changes the filter to use the same parameters as the one being passed in.
void makeInactive ()
Calls IIRFilter::makeInactive() on all the filters being used internally.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Tells the source to prepare for playing.
void releaseResources () override
Allows the source to release anything it no longer needs after playback has stopped.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Called repeatedly to fetch subsequent blocks of audio data.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
IIRFilterAudioSource::IIRFilterAudioSource (AudioSource * inputSource, bool deleteInputWhenDeleted)
Creates a IIRFilterAudioSource for a given input source.
Parameters
inputSource the input source to read from - this must not be null
deleteInputWhenDeleted if true, the input source will be deleted when this object is deleted
IIRFilterAudioSource::~IIRFilterAudioSource ()
Destructor.
Member Function Documentation
void IIRFilterAudioSource::setCoefficients (const IIRCoefficients & newCoefficients)
Changes the filter to use the same parameters as the one being passed in.
void IIRFilterAudioSource::makeInactive ()
Calls IIRFilter::makeInactive() on all the filters being used internally.
void IIRFilterAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Tells the source to prepare for playing.
An AudioSource has two states: prepared and unprepared.
The prepareToPlay() method is guaranteed to be called at least once on an 'unpreprared' source to put it into a 'prepared' state before any calls will be made to getNextAudioBlock(). This callback allows the source to initialise any resources it might need when playing.
Once playback has finished, the releaseResources() method is called to put the stream back into an 'unprepared' state.
Note that this method could be called more than once in succession without a matching call to releaseResources(), so make sure your code is robust and can handle that kind of situation.
Parameters
samplesPerBlockExpected the number of samples that the source will be expected to supply each time its getNextAudioBlock() method is called. This number may vary slightly, because it will be dependent on audio hardware callbacks, and these aren't guaranteed to always use a constant block size, so the source should be able to cope with small variations.
sampleRate the sample rate that the output will be used at - this is needed by sources such as tone generators.
See Also
releaseResources, getNextAudioBlock
Implements AudioSource.
void IIRFilterAudioSource::releaseResources () override virtual
Allows the source to release anything it no longer needs after playback has stopped.
This will be called when the source is no longer going to have its getNextAudioBlock() method called, so it should release any spare memory, etc. that it might have allocated during the prepareToPlay() call.
Note that there's no guarantee that prepareToPlay() will actually have been called before releaseResources(), and it may be called more than once in succession, so make sure your code is robust and doesn't make any assumptions about when it will be called.
See Also
prepareToPlay, getNextAudioBlock
Implements AudioSource.
void IIRFilterAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) override virtual
Called repeatedly to fetch subsequent blocks of audio data.
After calling the prepareToPlay() method, this callback will be made each time the audio playback hardware (or whatever other destination the audio data is going to) needs another block of data.
It will generally be called on a high-priority system thread, or possibly even an interrupt, so be careful not to do too much work here, as that will cause audio glitches!
See Also
AudioSourceChannelInfo, prepareToPlay, releaseResources
Implements AudioSource.
class MemoryAudioSource
An AudioSource which takes some float audio data as an input.
Public Member Functions
MemoryAudioSource (AudioBuffer< float > &audioBuffer, bool copyMemory, bool shouldLoop=false)
Creates a MemoryAudioSource by providing an audio buffer.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &bufferToFill) override
Implementation of the AudioSource method.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
MemoryAudioSource::MemoryAudioSource (AudioBuffer< float > & audioBuffer, bool copyMemory, bool shouldLoop = false)
Creates a MemoryAudioSource by providing an audio buffer.
If copyMemory is true then the buffer will be copied into an internal buffer which will be owned by the MemoryAudioSource. If copyMemory is false, then you must ensure that the lifetime of the audio buffer is at least as long as the MemoryAudioSource.
Member Function Documentation
void MemoryAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void MemoryAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void MemoryAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
class MixerAudioSource
An AudioSource that mixes together the output of a set of other AudioSources.
Input sources can be added and removed while the mixer is running as long as their prepareToPlay() and releaseResources() methods are called before and after adding them to the mixer.
Public Member Functions
MixerAudioSource ()
Creates a MixerAudioSource.
~MixerAudioSource ()
Destructor.
void addInputSource (AudioSource *newInput, bool deleteWhenRemoved)
Adds an input source to the mixer.
void removeInputSource (AudioSource *input)
Removes an input source.
void removeAllInputs ()
Removes all the input sources.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Implementation of the AudioSource method.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
MixerAudioSource::MixerAudioSource ()
Creates a MixerAudioSource.
MixerAudioSource::~MixerAudioSource ()
Destructor.
Member Function Documentation
void MixerAudioSource::addInputSource (AudioSource * newInput, bool deleteWhenRemoved)
Adds an input source to the mixer.
If the mixer is running you'll need to make sure that the input source is ready to play by calling its prepareToPlay() method before adding it. If the mixer is stopped, then its input sources will be automatically prepared when the mixer's prepareToPlay() method is called.
Parameters
newInput the source to add to the mixer
deleteWhenRemoved if true, then this source will be deleted when no longer needed by the mixer.
void MixerAudioSource::removeInputSource (AudioSource * input)
Removes an input source.
If the source was added by calling addInputSource() with the deleteWhenRemoved flag set, it will be deleted by this method.
void MixerAudioSource::removeAllInputs ()
Removes all the input sources.
Any sources which were added by calling addInputSource() with the deleteWhenRemoved flag set will be deleted by this method.
void MixerAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
This will call prepareToPlay() on all its input sources.
Implements AudioSource.
void MixerAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
This will call releaseResources() on all its input sources.
Implements AudioSource.
void MixerAudioSource::getNextAudioBlock (const AudioSourceChannelInfo &) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
class PositionableAudioSource
A type of AudioSource which can be repositioned.
The basic AudioSource just streams continuously with no idea of a current time or length, so the PositionableAudioSource is used for a finite stream that has a current read position.
See Also
AudioSource, AudioTransportSource
Public Member Functions
~PositionableAudioSource ()
Destructor.
virtual void setNextReadPosition (int64 newPosition)=0
Tells the stream to move to a new position.
virtual int64 getNextReadPosition () const =0
Returns the position from which the next block will be returned.
virtual int64 getTotalLength () const =0
Returns the total length of the stream (in samples).
virtual bool isLooping () const =0
Returns true if this source is actually playing in a loop.
virtual void setLooping (bool shouldLoop)
Tells the source whether you'd like it to play in a loop.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
virtual void prepareToPlay (int samplesPerBlockExpected, double sampleRate)=0
Tells the source to prepare for playing.
virtual void releaseResources ()=0
Allows the source to release anything it no longer needs after playback has stopped.
virtual void getNextAudioBlock (const AudioSourceChannelInfo &bufferToFill)=0
Called repeatedly to fetch subsequent blocks of audio data.
Protected Member Functions
PositionableAudioSource () noexcept
Creates the PositionableAudioSource.
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
PositionableAudioSource::PositionableAudioSource () protected noexcept
Creates the PositionableAudioSource.
PositionableAudioSource::~PositionableAudioSource ()
Destructor.
Member Function Documentation
virtual void PositionableAudioSource::setNextReadPosition (int64 newPosition) pure virtual
Tells the stream to move to a new position.
Calling this indicates that the next call to AudioSource::getNextAudioBlock() should return samples from this position.
Note that this may be called on a different thread to getNextAudioBlock(), so the subclass should make sure it's synchronised.
Implemented in AudioTransportSource, AudioFormatReaderSource, and BufferingAudioSource.
virtual int64 PositionableAudioSource::getNextReadPosition () const pure virtual
Returns the position from which the next block will be returned.
See Also
setNextReadPosition
Implemented in AudioTransportSource, AudioFormatReaderSource, and BufferingAudioSource.
virtual int64 PositionableAudioSource::getTotalLength () const pure virtual
Returns the total length of the stream (in samples).
Implemented in AudioTransportSource, AudioFormatReaderSource, and BufferingAudioSource.
Referenced by BufferingAudioSource::getTotalLength().
virtual bool PositionableAudioSource::isLooping () const pure virtual
Returns true if this source is actually playing in a loop.
Implemented in AudioTransportSource, BufferingAudioSource, and AudioFormatReaderSource.
Referenced by BufferingAudioSource::isLooping().
virtual void PositionableAudioSource::setLooping (bool shouldLoop) virtual
Tells the source whether you'd like it to play in a loop.
Reimplemented in AudioFormatReaderSource.
References ignoreUnused().
class ResamplingAudioSource
A type of AudioSource that takes an input source and changes its sample rate.
See Also
AudioSource, LagrangeInterpolator, CatmullRomInterpolator
Public Member Functions
ResamplingAudioSource (AudioSource *inputSource, bool deleteInputWhenDeleted, int numChannels=2)
Creates a ResamplingAudioSource for a given input source.
~ResamplingAudioSource ()
Destructor.
void setResamplingRatio (double samplesInPerOutputSample)
Changes the resampling ratio.
double getResamplingRatio () const noexcept
Returns the current resampling ratio.
void flushBuffers ()
Clears any buffers and filters that the resampler is using.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Tells the source to prepare for playing.
void releaseResources () override
Allows the source to release anything it no longer needs after playback has stopped.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Called repeatedly to fetch subsequent blocks of audio data.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
ResamplingAudioSource::ResamplingAudioSource (AudioSource * inputSource, bool deleteInputWhenDeleted, int numChannels = 2)
Creates a ResamplingAudioSource for a given input source.
Parameters
inputSource the input source to read from
deleteInputWhenDeleted if true, the input source will be deleted when this object is deleted
numChannels the number of channels to process
ResamplingAudioSource::~ResamplingAudioSource ()
Destructor.
Member Function Documentation
void ResamplingAudioSource::setResamplingRatio (double samplesInPerOutputSample)
Changes the resampling ratio.
(This value can be changed at any time, even while the source is running).
Parameters
samplesInPerOutputSample if set to 1.0, the input is passed through; higher values will speed it up; lower values will slow it down. The ratio must be greater than 0
double ResamplingAudioSource::getResamplingRatio () const noexcept
Returns the current resampling ratio.
This is the value that was set by setResamplingRatio().
void ResamplingAudioSource::flushBuffers ()
Clears any buffers and filters that the resampler is using.
void ResamplingAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Tells the source to prepare for playing.
An AudioSource has two states: prepared and unprepared.
The prepareToPlay() method is guaranteed to be called at least once on an 'unpreprared' source to put it into a 'prepared' state before any calls will be made to getNextAudioBlock(). This callback allows the source to initialise any resources it might need when playing.
Once playback has finished, the releaseResources() method is called to put the stream back into an 'unprepared' state.
Note that this method could be called more than once in succession without a matching call to releaseResources(), so make sure your code is robust and can handle that kind of situation.
Parameters
samplesPerBlockExpected the number of samples that the source will be expected to supply each time its getNextAudioBlock() method is called. This number may vary slightly, because it will be dependent on audio hardware callbacks, and these aren't guaranteed to always use a constant block size, so the source should be able to cope with small variations.
sampleRate the sample rate that the output will be used at - this is needed by sources such as tone generators.
See Also
releaseResources, getNextAudioBlock
Implements AudioSource.
void ResamplingAudioSource::releaseResources () override virtual
Allows the source to release anything it no longer needs after playback has stopped.
This will be called when the source is no longer going to have its getNextAudioBlock() method called, so it should release any spare memory, etc. that it might have allocated during the prepareToPlay() call.
Note that there's no guarantee that prepareToPlay() will actually have been called before releaseResources(), and it may be called more than once in succession, so make sure your code is robust and doesn't make any assumptions about when it will be called.
See Also
prepareToPlay, getNextAudioBlock
Implements AudioSource.
void ResamplingAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) override virtual
Called repeatedly to fetch subsequent blocks of audio data.
After calling the prepareToPlay() method, this callback will be made each time the audio playback hardware (or whatever other destination the audio data is going to) needs another block of data.
It will generally be called on a high-priority system thread, or possibly even an interrupt, so be careful not to do too much work here, as that will cause audio glitches!
See Also
AudioSourceChannelInfo, prepareToPlay, releaseResources
Implements AudioSource.
class ReverbAudioSource
An AudioSource that uses the Reverb class to apply a reverb to another AudioSource.
See Also
Reverb
Public Member Functions
ReverbAudioSource (AudioSource *inputSource, bool deleteInputWhenDeleted)
Creates a ReverbAudioSource to process a given input source.
~ReverbAudioSource ()
Destructor.
const Reverb::Parameters & getParameters () const noexcept
Returns the parameters from the reverb.
void setParameters (const Reverb::Parameters &newParams)
Changes the reverb's parameters.
void setBypassed (bool isBypassed) noexcept
bool isBypassed () const noexcept
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Tells the source to prepare for playing.
void releaseResources () override
Allows the source to release anything it no longer needs after playback has stopped.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Called repeatedly to fetch subsequent blocks of audio data.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
ReverbAudioSource::ReverbAudioSource (AudioSource * inputSource, bool deleteInputWhenDeleted)
Creates a ReverbAudioSource to process a given input source.
Parameters
inputSource the input source to read from - this must not be null
deleteInputWhenDeleted if true, the input source will be deleted when this object is deleted
ReverbAudioSource::~ReverbAudioSource ()
Destructor.
Member Function Documentation
const Reverb::Parameters& ReverbAudioSource::getParameters () const noexcept
Returns the parameters from the reverb.
void ReverbAudioSource::setParameters (const Reverb::Parameters & newParams)
Changes the reverb's parameters.
void ReverbAudioSource::setBypassed (bool isBypassed) noexcept
bool ReverbAudioSource::isBypassed () const noexcept
void ReverbAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Tells the source to prepare for playing.
An AudioSource has two states: prepared and unprepared.
The prepareToPlay() method is guaranteed to be called at least once on an 'unpreprared' source to put it into a 'prepared' state before any calls will be made to getNextAudioBlock(). This callback allows the source to initialise any resources it might need when playing.
Once playback has finished, the releaseResources() method is called to put the stream back into an 'unprepared' state.
Note that this method could be called more than once in succession without a matching call to releaseResources(), so make sure your code is robust and can handle that kind of situation.
Parameters
samplesPerBlockExpected the number of samples that the source will be expected to supply each time its getNextAudioBlock() method is called. This number may vary slightly, because it will be dependent on audio hardware callbacks, and these aren't guaranteed to always use a constant block size, so the source should be able to cope with small variations.
sampleRate the sample rate that the output will be used at - this is needed by sources such as tone generators.
See Also
releaseResources, getNextAudioBlock
Implements AudioSource.
void ReverbAudioSource::releaseResources () override virtual
Allows the source to release anything it no longer needs after playback has stopped.
This will be called when the source is no longer going to have its getNextAudioBlock() method called, so it should release any spare memory, etc. that it might have allocated during the prepareToPlay() call.
Note that there's no guarantee that prepareToPlay() will actually have been called before releaseResources(), and it may be called more than once in succession, so make sure your code is robust and doesn't make any assumptions about when it will be called.
See Also
prepareToPlay, getNextAudioBlock
Implements AudioSource.
void ReverbAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) override virtual
Called repeatedly to fetch subsequent blocks of audio data.
After calling the prepareToPlay() method, this callback will be made each time the audio playback hardware (or whatever other destination the audio data is going to) needs another block of data.
It will generally be called on a high-priority system thread, or possibly even an interrupt, so be careful not to do too much work here, as that will cause audio glitches!
See Also
AudioSourceChannelInfo, prepareToPlay, releaseResources
Implements AudioSource.
class ToneGeneratorAudioSource
A simple AudioSource that generates a sine wave.
Public Member Functions
ToneGeneratorAudioSource ()
Creates a ToneGeneratorAudioSource.
~ToneGeneratorAudioSource ()
Destructor.
void setAmplitude (float newAmplitude)
Sets the signal's amplitude.
void setFrequency (double newFrequencyHz)
Sets the signal's frequency.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Implementation of the AudioSource method.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
ToneGeneratorAudioSource::ToneGeneratorAudioSource ()
Creates a ToneGeneratorAudioSource.
ToneGeneratorAudioSource::~ToneGeneratorAudioSource ()
Destructor.
Member Function Documentation
void ToneGeneratorAudioSource::setAmplitude (float newAmplitude)
Sets the signal's amplitude.
void ToneGeneratorAudioSource::setFrequency (double newFrequencyHz)
Sets the signal's frequency.
void ToneGeneratorAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void ToneGeneratorAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void ToneGeneratorAudioSource::getNextAudioBlock (const AudioSourceChannelInfo &) override virtual
Implementation of the AudioSource method.
Implements AudioSource.