JUCE: protocol
protocol
juce_blocks_basics
Classes
struct IntegerWithBitSize< numBits >
struct Packed7BitArrayBuilder< allocatedBytes >
This helper class allocates a block of 7-bit bytes and can push sequences of bits into it.
struct Packed7BitArrayReader
This helper class reads from a block of 7-bit bytes as sequences of bits.
struct BlockDataSheet
struct BlockSerialNumber
struct VersionNumber
struct BlockName
struct DeviceStatus
struct DeviceConnection
struct DeviceVersion
struct DeviceName
struct TouchPosition
The coordinates of a touch.
struct TouchVelocity
The velocities for each dimension of a touch.
struct HostPacketBuilder< maxPacketBytes >
Helper class for constructing a packet for sending to a BLOCKS device.
struct HostPacketDecoder< Handler >
Parses data packets from a BLOCKS device, and translates them into callbacks on a handler object.
Typedefs
using ProtocolVersion = IntegerWithBitSize< 8 >
using PacketTimestamp = IntegerWithBitSize< 32 >
A timestamp for a packet, in milliseconds since device boot-up.
using PacketTimestampOffset = IntegerWithBitSize< 5 >
This relative timestamp is for use inside a packet, and it represents a number of milliseconds that should be added to the packet's timestamp.
using MessageType = IntegerWithBitSize< 7 >
This is the first item in a BLOCKS message, identifying the message type.
using TopologyIndex = uint8
This is a type of index identifier used to refer to a block within a group.
using DeviceCount = IntegerWithBitSize< 7 >
using ConnectionCount = IntegerWithBitSize< 8 >
using BatteryLevel = IntegerWithBitSize< 5 >
Battery charge level.
using BatteryCharging = IntegerWithBitSize< 1 >
Battery charger connection flag.
using ConnectorPort = IntegerWithBitSize< 5 >
ConnectorPort is an index, starting at 0 for the leftmost port on the top edge, and going clockwise.
using TouchIndex = IntegerWithBitSize< 5 >
The index of a touch, i.e.
using PacketCounter = IntegerWithBitSize< 10 >
using DeviceCommand = IntegerWithBitSize< 9 >
using ConfigCommand = IntegerWithBitSize< 4 >
using ConfigItemIndex = IntegerWithBitSize< 8 >
using ConfigItemValue = IntegerWithBitSize< 32 >
using ControlButtonID = IntegerWithBitSize< 12 >
An ID for a control-block button type.
using RotaryDialIndex = IntegerWithBitSize< 7 >
using RotaryDialAngle = IntegerWithBitSize< 14 >
using RotaryDialDelta = IntegerWithBitSize< 14 >
using PacketIndex = IntegerWithBitSize< 16 >
using DataChangeCommand = IntegerWithBitSize< 3 >
using ByteCountFew = IntegerWithBitSize< 4 >
using ByteCountMany = IntegerWithBitSize< 8 >
using ByteValue = IntegerWithBitSize< 8 >
using ByteSequenceContinues = IntegerWithBitSize< 1 >
using FirmwareUpdateACKCode = IntegerWithBitSize< 7 >
using FirmwareUpdateACKDetail = IntegerWithBitSize< 32 >
using FirmwareUpdatePacketSize = IntegerWithBitSize< 7 >
Enumerations
enum MessageFromDevice {
MessageFromDevice::deviceTopology = 0x01, packetACK = 0x02, firmwareUpdateACK = 0x03, MessageFromDevice::deviceTopologyExtend = 0x04,
MessageFromDevice::deviceTopologyEnd = 0x05, MessageFromDevice::deviceVersionList = 0x06, MessageFromDevice::deviceNameList = 0x07, MessageFromDevice::touchStart = 0x10,
MessageFromDevice::touchMove = 0x11, MessageFromDevice::touchEnd = 0x12, MessageFromDevice::touchStartWithVelocity = 0x13, MessageFromDevice::touchMoveWithVelocity = 0x14,
MessageFromDevice::touchEndWithVelocity = 0x15, MessageFromDevice::configMessage = 0x18, MessageFromDevice::controlButtonDown = 0x20, MessageFromDevice::controlButtonUp = 0x21,
programEventMessage = 0x28, MessageFromDevice::logMessage = 0x30
}
Messages that a device may send to the host.
enum MessageFromHost {
MessageFromHost::deviceCommandMessage = 0x01, MessageFromHost::sharedDataChange = 0x02, programEventMessage = 0x03, MessageFromHost::firmwareUpdatePacket = 0x04,
MessageFromHost::configMessage = 0x10, MessageFromHost::factoryReset = 0x11, MessageFromHost::blockReset = 0x12, MessageFromHost::setName = 0x20
}
Messages that the host may send to a device.
enum ConfigItemId {
midiStartChannel = 0, midiEndChannel = 1, midiUseMPE = 2, pitchBendRange = 3,
octave = 4, transpose = 5, slideCC = 6, slideMode = 7,
octaveTopology = 8, velocitySensitivity = 10, glideSensitivity = 11, slideSensitivity = 12,
pressureSensitivity = 13, liftSensitivity = 14, fixedVelocity = 15, fixedVelocityValue = 16,
pianoMode = 17, glideLock = 18, mode = 20, volume = 21,
scale = 22, hideMode = 23, chord = 24, arpPattern = 25,
tempo = 26, xTrackingMode = 30, yTrackingMode = 31, zTrackingMode = 32,
user0 = 64, user1 = 65, user2 = 66, user3 = 67,
user4 = 68, user5 = 69, user6 = 70, user7 = 71,
user8 = 72, user9 = 73, user10 = 74, user11 = 75,
user12 = 76, user13 = 77, user14 = 78, user15 = 79,
user16 = 80, user17 = 81, user18 = 82, user19 = 83,
user20 = 84, user21 = 85, user22 = 86, user23 = 87,
user24 = 88, user25 = 89, user26 = 90, user27 = 91,
user28 = 92, user29 = 93, user30 = 94, user31 = 95
}
Configuration Item Identifiers.
enum DeviceCommands {
beginAPIMode = 0x00, requestTopologyMessage = 0x01, endAPIMode = 0x02, ping = 0x03,
debugMode = 0x04, saveProgramAsDefault = 0x05
}
enum ConfigCommands {
setConfig = 0x00, requestConfig = 0x01, requestFactorySync = 0x02, requestUserSync = 0x03,
updateConfig = 0x04, updateUserConfig = 0x05, setConfigState = 0x06, factorySyncEnd = 0x07,
clusterConfigSync = 0x08
}
enum DataChangeCommands {
endOfPacket = 0, endOfChanges = 1, skipBytesFew = 2, skipBytesMany = 3,
setSequenceOfBytes = 4, setFewBytesWithValue = 5, setFewBytesWithLastValue = 6, setManyBytesWithValue = 7
}
enum BitSizes {
topologyMessageHeader = MessageType::bits + ProtocolVersion::bits + DeviceCount::bits + ConnectionCount::bits, topologyDeviceInfo = sizeof (BlockSerialNumber) * 7 + BatteryLevel::bits + BatteryCharging::bits, topologyConnectionInfo = topologyIndexBits + ConnectorPort::bits + topologyIndexBits + ConnectorPort::bits, typeDeviceAndTime = MessageType::bits + PacketTimestampOffset::bits,
touchMessage = typeDeviceAndTime + TouchIndex::bits + TouchPosition::bits, touchMessageWithVelocity = touchMessage + TouchVelocity::bits, programEventMessage = MessageType::bits + 32 * numProgramMessageInts, programEventMessage = 0x28,
programEventMessage = 0x03, packetACK = MessageType::bits + PacketCounter::bits, packetACK = 0x02, firmwareUpdateACK = MessageType::bits + FirmwareUpdateACKCode::bits + FirmwareUpdateACKDetail::bits,
firmwareUpdateACK = 0x03, controlButtonMessage = typeDeviceAndTime + ControlButtonID::bits, configSetMessage = MessageType::bits + ConfigCommand::bits + ConfigItemIndex::bits + ConfigItemValue::bits, configRespMessage = MessageType::bits + ConfigCommand::bits + ConfigItemIndex::bits + (ConfigItemValue::bits * 3),
configSyncEndMessage = MessageType::bits + ConfigCommand::bits
}
Contains the number of bits required to encode various items in the packets.
Detailed Description
Class Documentation
struct IntegerWithBitSize
template<int numBits>
struct IntegerWithBitSize< numBits >
Public Types
enum { bits = numBits, maxValue = static_cast<uint32> ((1ULL << numBits) - 1ULL) }
Public Member Functions
IntegerWithBitSize () noexcept=default
IntegerWithBitSize (const IntegerWithBitSize &) noexcept=default
IntegerWithBitSize & operator= (const IntegerWithBitSize &) noexcept=default
IntegerWithBitSize (uint32 v) noexcept
operator uint32 () const noexcept
uint32 get () const noexcept
uint8 getScaledToByte () const noexcept
float toUnipolarFloat () const noexcept
float toBipolarFloat () const noexcept
Static Public Member Functions
static IntegerWithBitSize fromUnipolarFloat (float value) noexcept
static IntegerWithBitSize fromBipolarFloat (float value) noexcept
Public Attributes
uint32 value = 0
Member Enumeration Documentation
template<int numBits> anonymous enum
Enumerator
bits
maxValue
Constructor & Destructor Documentation
template<int numBits> IntegerWithBitSize< numBits >::IntegerWithBitSize () default noexcept
Referenced by IntegerWithBitSize< 8 >::fromBipolarFloat(), and IntegerWithBitSize< 8 >::fromUnipolarFloat().
template<int numBits> IntegerWithBitSize< numBits >::IntegerWithBitSize (const IntegerWithBitSize< numBits > &) default noexcept
template<int numBits> IntegerWithBitSize< numBits >::IntegerWithBitSize (uint32 v) noexcept
Member Function Documentation
template<int numBits> IntegerWithBitSize& IntegerWithBitSize< numBits >::operator= (const IntegerWithBitSize< numBits > &) default noexcept
template<int numBits> IntegerWithBitSize< numBits >::operator uint32 () const noexcept
template<int numBits> uint32 IntegerWithBitSize< numBits >::get () const noexcept
Referenced by HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleConfigMessage(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleTouch(), and HostPacketDecoder< Handler >::handleTouchWithVelocity().
template<int numBits> uint8 IntegerWithBitSize< numBits >::getScaledToByte () const noexcept
template<int numBits> float IntegerWithBitSize< numBits >::toUnipolarFloat () const noexcept
template<int numBits> float IntegerWithBitSize< numBits >::toBipolarFloat () const noexcept
template<int numBits> static IntegerWithBitSize IntegerWithBitSize< numBits >::fromUnipolarFloat (float value) static noexcept
template<int numBits> static IntegerWithBitSize IntegerWithBitSize< numBits >::fromBipolarFloat (float value) static noexcept
Member Data Documentation
template<int numBits> uint32 IntegerWithBitSize< numBits >::value = 0
Referenced by IntegerWithBitSize< 8 >::get(), and IntegerWithBitSize< 8 >::operator uint32().
struct Packed7BitArrayBuilder
template<int allocatedBytes>
struct Packed7BitArrayBuilder< allocatedBytes >
This helper class allocates a block of 7-bit bytes and can push sequences of bits into it.
See Also
Packed7BitArrayReader
Public Member Functions
const void * getData () const noexcept
int size () const noexcept
bool hasCapacity (int bitsNeeded) const noexcept
void writeHeaderSysexBytes (uint8 deviceIndex) noexcept
void writePacketSysexFooter () noexcept
template<int numBits>
Packed7BitArrayBuilder & operator<< (IntegerWithBitSize< numBits > value) noexcept
void writeBits (uint32 value, int numBits) noexcept
State getState () const noexcept
void restore (State state) noexcept
Member Function Documentation
template<int allocatedBytes> const void* Packed7BitArrayBuilder< allocatedBytes >::getData () const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::getData().
template<int allocatedBytes> int Packed7BitArrayBuilder< allocatedBytes >::size () const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::size().
template<int allocatedBytes> bool Packed7BitArrayBuilder< allocatedBytes >::hasCapacity (int bitsNeeded) const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::addBlockReset(), HostPacketBuilder< maxPacketBytes >::addConfigSetMessage(), HostPacketBuilder< maxPacketBytes >::addFactoryReset(), HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket(), HostPacketBuilder< maxPacketBytes >::addProgramEventMessage(), HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage(), HostPacketBuilder< maxPacketBytes >::addRequestMessage(), HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage(), HostPacketBuilder< maxPacketBytes >::addSetBlockName(), HostPacketBuilder< maxPacketBytes >::beginDataChanges(), HostPacketBuilder< maxPacketBytes >::deviceControlMessage(), HostPacketBuilder< maxPacketBytes >::endDataChanges(), HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), HostPacketBuilder< maxPacketBytes >::skipBytes(), Packed7BitArrayBuilder< maxPacketBytes >::writeBits(), and Packed7BitArrayBuilder< maxPacketBytes >::writePacketSysexFooter().
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::writeHeaderSysexBytes (uint8 deviceIndex) noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::writePacketSysexFooter () noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter().
template<int allocatedBytes> template<int numBits> Packed7BitArrayBuilder& Packed7BitArrayBuilder< allocatedBytes >::operator<< (IntegerWithBitSize< numBits > value) noexcept
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::writeBits (uint32 value, int numBits) noexcept
Referenced by Packed7BitArrayBuilder< maxPacketBytes >::operator<<().
template<int allocatedBytes> State Packed7BitArrayBuilder< allocatedBytes >::getState () const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), and HostPacketBuilder< maxPacketBytes >::skipBytes().
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::restore (State state) noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), and HostPacketBuilder< maxPacketBytes >::skipBytes().
struct Packed7BitArrayReader
This helper class reads from a block of 7-bit bytes as sequences of bits.
See Also
Packed7BitArrayBuilder
Public Member Functions
Packed7BitArrayReader (const void *sourceData, int numBytes) noexcept
int getRemainingBits () const noexcept
template<typename Target >
Target read () noexcept
uint32 readBits (int numBits) noexcept
Static Public Member Functions
static bool checksumIsOK (const uint8 *data, uint32 size) noexcept
Constructor & Destructor Documentation
Packed7BitArrayReader::Packed7BitArrayReader (const void * sourceData, int numBytes) noexcept
Member Function Documentation
int Packed7BitArrayReader::getRemainingBits () const noexcept
Referenced by HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), HostPacketDecoder< Handler >::handleLogMessage(), HostPacketDecoder< Handler >::handlePacketACK(), HostPacketDecoder< Handler >::handleTopology(), HostPacketDecoder< Handler >::handleTouch(), HostPacketDecoder< Handler >::handleTouchWithVelocity(), HostPacketDecoder< Handler >::processNextMessage(), HostPacketDecoder< Handler >::processNextPacket(), and readBits().
template<typename Target > Target Packed7BitArrayReader::read () noexcept
References readBits().
Referenced by HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleConfigMessage(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), HostPacketDecoder< Handler >::handleLogMessage(), HostPacketDecoder< Handler >::handlePacketACK(), HostPacketDecoder< Handler >::handleTopology(), HostPacketDecoder< Handler >::handleTopologyConnection(), HostPacketDecoder< Handler >::handleTopologyDevice(), HostPacketDecoder< Handler >::handleTopologyEnd(), HostPacketDecoder< Handler >::handleTouch(), HostPacketDecoder< Handler >::handleTouchWithVelocity(), HostPacketDecoder< Handler >::processNextMessage(), and HostPacketDecoder< Handler >::processNextPacket().
uint32 Packed7BitArrayReader::readBits (int numBits) noexcept
References getRemainingBits(), and jassert.
Referenced by HostPacketDecoder< Handler >::handleName(), HostPacketDecoder< Handler >::handleTopologyConnection(), HostPacketDecoder< Handler >::handleTopologyDevice(), HostPacketDecoder< Handler >::handleVersion(), and read().
static bool Packed7BitArrayReader::checksumIsOK (const uint8 * data, uint32 size) static noexcept
Referenced by HostPacketDecoder< Handler >::processNextPacket().
struct BlockDataSheet
Public Member Functions
BlockDataSheet (const BlocksProtocol::BlockSerialNumber &serial)
Block::ConnectionPort convertPortIndexToConnectorPort (BlocksProtocol::ConnectorPort port) const noexcept
Public Attributes
const
BlocksProtocol::BlockSerialNumber serialNumber
Block::Type apiType = Block::Type::unknown
const char * description = nullptr
int widthUnits = 0
int heightUnits = 0
int lightGridWidth = 0
int lightGridHeight = 0
int lightGridStartIndex = 0
bool hasTouchSurface = false
int numKeywaves = 0
int numLEDRowLEDs = 0
uint32 programAndHeapSize = 0
juce::Array< ButtonInfo > buttons
juce::Array< StatusLEDInfo > statusLEDs
juce::Array
< Block::ConnectionPort > ports
juce::Array< const char * > dials
Constructor & Destructor Documentation
BlockDataSheet::BlockDataSheet (const BlocksProtocol::BlockSerialNumber & serial)
References serialNumber.
Member Function Documentation
Block::ConnectionPort BlockDataSheet::convertPortIndexToConnectorPort (BlocksProtocol::ConnectorPort port) const noexcept
References ports.
Member Data Documentation
const BlocksProtocol::BlockSerialNumber BlockDataSheet::serialNumber
Referenced by BlockDataSheet().
Block::Type BlockDataSheet::apiType = Block::Type::unknown
const char* BlockDataSheet::description = nullptr
int BlockDataSheet::widthUnits = 0
int BlockDataSheet::heightUnits = 0
int BlockDataSheet::lightGridWidth = 0
int BlockDataSheet::lightGridHeight = 0
int BlockDataSheet::lightGridStartIndex = 0
bool BlockDataSheet::hasTouchSurface = false
int BlockDataSheet::numKeywaves = 0
int BlockDataSheet::numLEDRowLEDs = 0
uint32 BlockDataSheet::programAndHeapSize = 0
juce::Array<ButtonInfo> BlockDataSheet::buttons
juce::Array<StatusLEDInfo> BlockDataSheet::statusLEDs
juce::Array<Block::ConnectionPort> BlockDataSheet::ports
Referenced by convertPortIndexToConnectorPort().
juce::Array<const char*> BlockDataSheet::dials
struct BlockSerialNumber
Public Member Functions
bool isValid () const noexcept
bool isPadBlock () const noexcept
bool isLiveBlock () const noexcept
bool isLoopBlock () const noexcept
bool isDevCtrlBlock () const noexcept
bool isTouchBlock () const noexcept
bool isSeaboardBlock () const noexcept
bool isAnyControlBlock () const noexcept
bool hasPrefix (const char *prefix) const noexcept
Public Attributes
uint8 serial [16]
Member Function Documentation
bool BlockSerialNumber::isValid () const noexcept
References isAnyControlBlock(), isPadBlock(), isSeaboardBlock(), and serial.
bool BlockSerialNumber::isPadBlock () const noexcept
References hasPrefix().
Referenced by isValid().
bool BlockSerialNumber::isLiveBlock () const noexcept
References hasPrefix().
Referenced by isAnyControlBlock().
bool BlockSerialNumber::isLoopBlock () const noexcept
References hasPrefix().
Referenced by isAnyControlBlock().
bool BlockSerialNumber::isDevCtrlBlock () const noexcept
References hasPrefix().
Referenced by isAnyControlBlock().
bool BlockSerialNumber::isTouchBlock () const noexcept
References hasPrefix().
Referenced by isAnyControlBlock().
bool BlockSerialNumber::isSeaboardBlock () const noexcept
References hasPrefix().
Referenced by isValid().
bool BlockSerialNumber::isAnyControlBlock () const noexcept
References isDevCtrlBlock(), isLiveBlock(), isLoopBlock(), and isTouchBlock().
Referenced by isValid().
bool BlockSerialNumber::hasPrefix (const char * prefix) const noexcept
References serial.
Referenced by isDevCtrlBlock(), isLiveBlock(), isLoopBlock(), isPadBlock(), isSeaboardBlock(), and isTouchBlock().
Member Data Documentation
uint8 BlockSerialNumber::serial[16]
Referenced by HostPacketDecoder< Handler >::handleTopologyDevice(), hasPrefix(), and isValid().
struct VersionNumber
Public Attributes
uint8 version [21] = {}
uint8 length = 0
Member Data Documentation
uint8 VersionNumber::version[21] = {}
Referenced by HostPacketDecoder< Handler >::handleVersion().
uint8 VersionNumber::length = 0
Referenced by HostPacketDecoder< Handler >::handleVersion().
struct BlockName
Public Attributes
uint8 name [33] = {}
uint8 length = 0
Member Data Documentation
uint8 BlockName::name[33] = {}
Referenced by HostPacketDecoder< Handler >::handleName().
uint8 BlockName::length = 0
Referenced by HostPacketDecoder< Handler >::handleName().
struct DeviceStatus
Public Attributes
BlockSerialNumber serialNumber
TopologyIndex index
BatteryLevel batteryLevel
BatteryCharging batteryCharging
Member Data Documentation
BlockSerialNumber DeviceStatus::serialNumber
Referenced by HostPacketDecoder< Handler >::handleTopologyDevice().
TopologyIndex DeviceStatus::index
Referenced by HostPacketDecoder< Handler >::handleTopologyDevice().
BatteryLevel DeviceStatus::batteryLevel
Referenced by HostPacketDecoder< Handler >::handleTopologyDevice().
BatteryCharging DeviceStatus::batteryCharging
Referenced by HostPacketDecoder< Handler >::handleTopologyDevice().
struct DeviceConnection
Public Attributes
TopologyIndex device1
TopologyIndex device2
ConnectorPort port1
ConnectorPort port2
Member Data Documentation
TopologyIndex DeviceConnection::device1
Referenced by HostPacketDecoder< Handler >::handleTopologyConnection().
TopologyIndex DeviceConnection::device2
Referenced by HostPacketDecoder< Handler >::handleTopologyConnection().
ConnectorPort DeviceConnection::port1
Referenced by HostPacketDecoder< Handler >::handleTopologyConnection().
ConnectorPort DeviceConnection::port2
Referenced by HostPacketDecoder< Handler >::handleTopologyConnection().
struct DeviceVersion
Public Attributes
TopologyIndex index
VersionNumber version
Member Data Documentation
TopologyIndex DeviceVersion::index
Referenced by HostPacketDecoder< Handler >::handleVersion().
VersionNumber DeviceVersion::version
Referenced by HostPacketDecoder< Handler >::handleVersion().
struct DeviceName
Public Attributes
TopologyIndex index
BlockName name
Member Data Documentation
TopologyIndex DeviceName::index
Referenced by HostPacketDecoder< Handler >::handleName().
BlockName DeviceName::name
Referenced by HostPacketDecoder< Handler >::handleName().
struct TouchPosition
The coordinates of a touch.
Public Types
enum { bits = Xcoord::bits + Ycoord::bits + Zcoord::bits }
using Xcoord = IntegerWithBitSize< 12 >
using Ycoord = IntegerWithBitSize< 12 >
using Zcoord = IntegerWithBitSize< 8 >
Public Attributes
Xcoord x
Ycoord y
Zcoord z
Member Typedef Documentation
using TouchPosition::Xcoord = IntegerWithBitSize<12>
using TouchPosition::Ycoord = IntegerWithBitSize<12>
using TouchPosition::Zcoord = IntegerWithBitSize<8>
Member Enumeration Documentation
anonymous enum
Enumerator
bits
Member Data Documentation
Xcoord TouchPosition::x
Ycoord TouchPosition::y
Zcoord TouchPosition::z
struct TouchVelocity
The velocities for each dimension of a touch.
Public Types
enum { bits = VXcoord::bits + VYcoord::bits + VZcoord::bits }
using VXcoord = IntegerWithBitSize< 8 >
using VYcoord = IntegerWithBitSize< 8 >
using VZcoord = IntegerWithBitSize< 8 >
Public Attributes
VXcoord vx
VYcoord vy
VZcoord vz
Member Typedef Documentation
using TouchVelocity::VXcoord = IntegerWithBitSize<8>
using TouchVelocity::VYcoord = IntegerWithBitSize<8>
using TouchVelocity::VZcoord = IntegerWithBitSize<8>
Member Enumeration Documentation
anonymous enum
Enumerator
bits
Member Data Documentation
VXcoord TouchVelocity::vx
VYcoord TouchVelocity::vy
VZcoord TouchVelocity::vz
struct HostPacketBuilder
template<int maxPacketBytes>
struct HostPacketBuilder< maxPacketBytes >
Helper class for constructing a packet for sending to a BLOCKS device.
Public Member Functions
HostPacketBuilder () noexcept
HostPacketBuilder (const HostPacketBuilder &)=delete
HostPacketBuilder (HostPacketBuilder &&)=default
const void * getData () const noexcept
int size () const noexcept
void writePacketSysexHeaderBytes (TopologyIndex deviceIndex) noexcept
void writePacketSysexFooter () noexcept
bool deviceControlMessage (DeviceCommand command) noexcept
bool beginDataChanges (PacketIndex packetIndex) noexcept
bool endDataChanges (bool isLastChange) noexcept
bool skipBytes (int numToSkip) noexcept
bool setMultipleBytes (const uint8 *values, int num) noexcept
bool setMultipleBytes (uint8 value, uint8 lastValue, int num) noexcept
bool addProgramEventMessage (const int32 *messageData)
bool addFirmwareUpdatePacket (const uint8 *packetData, uint8 size)
bool addConfigSetMessage (int32 item, int32 value)
bool addRequestMessage (int32 item)
bool addRequestFactorySyncMessage ()
bool addRequestUserSyncMessage ()
bool addFactoryReset ()
bool addBlockReset ()
bool addSetBlockName (const juce::String &name)
Constructor & Destructor Documentation
template<int maxPacketBytes> HostPacketBuilder< maxPacketBytes >::HostPacketBuilder () noexcept
template<int maxPacketBytes> HostPacketBuilder< maxPacketBytes >::HostPacketBuilder (const HostPacketBuilder< maxPacketBytes > &) delete
template<int maxPacketBytes> HostPacketBuilder< maxPacketBytes >::HostPacketBuilder (HostPacketBuilder< maxPacketBytes > &&) default
Member Function Documentation
template<int maxPacketBytes> const void* HostPacketBuilder< maxPacketBytes >::getData () const noexcept
References Packed7BitArrayBuilder< allocatedBytes >::getData().
Referenced by BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> int HostPacketBuilder< maxPacketBytes >::size () const noexcept
References Packed7BitArrayBuilder< allocatedBytes >::size().
Referenced by HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket(), BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> void HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes (TopologyIndex deviceIndex) noexcept
References jassert, and Packed7BitArrayBuilder< allocatedBytes >::writeHeaderSysexBytes().
Referenced by BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> void HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter () noexcept
References Packed7BitArrayBuilder< allocatedBytes >::writePacketSysexFooter().
Referenced by BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::deviceControlMessage (DeviceCommand command) noexcept
References IntegerWithBitSize< numBits >::bits, deviceCommandMessage, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::beginDataChanges (PacketIndex packetIndex) noexcept
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and sharedDataChange.
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::endDataChanges (bool isLastChange) noexcept
References IntegerWithBitSize< numBits >::bits, endOfChanges, endOfPacket, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::skipBytes (int numToSkip) noexcept
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayBuilder< allocatedBytes >::getState(), Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), IntegerWithBitSize< numBits >::maxValue, IntegerWithBitSize< 8 >::maxValue, Packed7BitArrayBuilder< allocatedBytes >::restore(), skipBytesFew, and skipBytesMany.
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::setMultipleBytes (const uint8 * values, int num) noexcept
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and setSequenceOfBytes.
Referenced by HostPacketBuilder< maxPacketBytes >::setMultipleBytes().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::setMultipleBytes (uint8 value, uint8 lastValue, int num) noexcept
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayBuilder< allocatedBytes >::getState(), Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), IntegerWithBitSize< numBits >::maxValue, IntegerWithBitSize< 8 >::maxValue, Packed7BitArrayBuilder< allocatedBytes >::restore(), setFewBytesWithLastValue, setFewBytesWithValue, setManyBytesWithValue, and HostPacketBuilder< maxPacketBytes >::setMultipleBytes().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addProgramEventMessage (const int32 * messageData)
References Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and programEventMessage.
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket (const uint8 * packetData, uint8 size)
References IntegerWithBitSize< numBits >::bits, firmwareUpdatePacket, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and HostPacketBuilder< maxPacketBytes >::size().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addConfigSetMessage (int32 item, int32 value)
References configMessage, configSetMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and setConfig.
Referenced by BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addRequestMessage (int32 item)
References configMessage, configSetMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and requestConfig.
Referenced by BlockConfigManager::requestBlockConfig().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage ()
References IntegerWithBitSize< numBits >::bits, configMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and requestFactorySync.
Referenced by BlockConfigManager::requestFactoryConfigSync().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage ()
References IntegerWithBitSize< numBits >::bits, configMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and requestUserSync.
Referenced by BlockConfigManager::requestUserConfigSync().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addFactoryReset ()
References IntegerWithBitSize< numBits >::bits, factoryReset, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addBlockReset ()
References IntegerWithBitSize< numBits >::bits, blockReset, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addSetBlockName (const juce::String & name)
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and setName.
struct HostPacketDecoder
template<typename Handler>
struct HostPacketDecoder< Handler >
Parses data packets from a BLOCKS device, and translates them into callbacks on a handler object.
Static Public Member Functions
static void processNextPacket (Handler &handler, TopologyIndex deviceIndex, const void *data, int size)
static bool processNextMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp)
static bool handleTopology (Handler &handler, Packed7BitArrayReader &reader, bool newTopology)
static bool handleTopologyEnd (Handler &handler, Packed7BitArrayReader &reader)
static void handleTopologyDevice (Handler &handler, Packed7BitArrayReader &reader)
static void handleTopologyConnection (Handler &handler, Packed7BitArrayReader &reader)
static bool handleVersion (Handler &handler, Packed7BitArrayReader &reader)
static bool handleName (Handler &handler, Packed7BitArrayReader &reader)
static bool handleTouch (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd)
static bool handleTouchWithVelocity (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd)
static void handleTouch (Handler &handler, TopologyIndex deviceIndex, uint32 timestamp, TouchIndex touchIndex, TouchPosition position, TouchVelocity velocity, bool isStart, bool isEnd)
static bool handleButtonDownOrUp (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isDown)
static bool handleCustomMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp)
static bool handlePacketACK (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
static bool handleFirmwareUpdateACK (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
static bool handleConfigMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
static bool handleLogMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
Member Function Documentation
template<typename Handler > static void HostPacketDecoder< Handler >::processNextPacket (Handler & handler, TopologyIndex deviceIndex, const void * data, int size) static
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayReader::checksumIsOK(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, HostPacketDecoder< Handler >::processNextMessage(), and Packed7BitArrayReader::read().
template<typename Handler > static bool HostPacketDecoder< Handler >::processNextMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp) static
References IntegerWithBitSize< numBits >::bits, configMessage, controlButtonDown, controlButtonUp, deviceNameList, deviceTopology, deviceTopologyEnd, deviceTopologyExtend, deviceVersionList, firmwareUpdateACK, Packed7BitArrayReader::getRemainingBits(), HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleConfigMessage(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), HostPacketDecoder< Handler >::handleLogMessage(), HostPacketDecoder< Handler >::handleName(), HostPacketDecoder< Handler >::handlePacketACK(), HostPacketDecoder< Handler >::handleTopology(), HostPacketDecoder< Handler >::handleTopologyEnd(), HostPacketDecoder< Handler >::handleTouch(), HostPacketDecoder< Handler >::handleTouchWithVelocity(), HostPacketDecoder< Handler >::handleVersion(), jassertfalse, logMessage, packetACK, programEventMessage, Packed7BitArrayReader::read(), touchEnd, touchEndWithVelocity, touchMove, touchMoveWithVelocity, touchStart, and touchStartWithVelocity.
Referenced by HostPacketDecoder< Handler >::processNextPacket().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTopology (Handler & handler, Packed7BitArrayReader & reader, bool newTopology) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayReader::getRemainingBits(), HostPacketDecoder< Handler >::handleTopologyConnection(), HostPacketDecoder< Handler >::handleTopologyDevice(), jassertfalse, Packed7BitArrayReader::read(), topologyConnectionInfo, and topologyDeviceInfo.
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTopologyEnd (Handler & handler, Packed7BitArrayReader & reader) static
References jassertfalse, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static void HostPacketDecoder< Handler >::handleTopologyDevice (Handler & handler, Packed7BitArrayReader & reader) static
References DeviceStatus::batteryCharging, DeviceStatus::batteryLevel, DeviceStatus::index, Packed7BitArrayReader::read(), Packed7BitArrayReader::readBits(), BlockSerialNumber::serial, and DeviceStatus::serialNumber.
Referenced by HostPacketDecoder< Handler >::handleTopology().
template<typename Handler > static void HostPacketDecoder< Handler >::handleTopologyConnection (Handler & handler, Packed7BitArrayReader & reader) static
References DeviceConnection::device1, DeviceConnection::device2, DeviceConnection::port1, DeviceConnection::port2, Packed7BitArrayReader::read(), and Packed7BitArrayReader::readBits().
Referenced by HostPacketDecoder< Handler >::handleTopology().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleVersion (Handler & handler, Packed7BitArrayReader & reader) static
References DeviceVersion::index, VersionNumber::length, Packed7BitArrayReader::readBits(), VersionNumber::version, and DeviceVersion::version.
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleName (Handler & handler, Packed7BitArrayReader & reader) static
References DeviceName::index, BlockName::length, BlockName::name, DeviceName::name, and Packed7BitArrayReader::readBits().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTouch (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, Packed7BitArrayReader::read(), and touchMessage.
Referenced by HostPacketDecoder< Handler >::handleTouchWithVelocity(), and HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTouchWithVelocity (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), HostPacketDecoder< Handler >::handleTouch(), jassertfalse, Packed7BitArrayReader::read(), and touchMessageWithVelocity.
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static void HostPacketDecoder< Handler >::handleTouch (Handler & handler, TopologyIndex deviceIndex, uint32 timestamp, TouchIndex touchIndex, TouchPosition position, TouchVelocity velocity, bool isStart, bool isEnd) static
template<typename Handler > static bool HostPacketDecoder< Handler >::handleButtonDownOrUp (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isDown) static
References IntegerWithBitSize< numBits >::bits, controlButtonMessage, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleCustomMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, programEventMessage, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handlePacketACK (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayReader::getRemainingBits(), jassertfalse, packetACK, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleFirmwareUpdateACK (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayReader::getRemainingBits(), jassertfalse, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleConfigMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References factorySyncEnd, IntegerWithBitSize< numBits >::get(), max(), min(), Packed7BitArrayReader::read(), setConfig, and updateConfig.
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleLogMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References Packed7BitArrayReader::getRemainingBits(), and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
Typedef Documentation
using ProtocolVersion = IntegerWithBitSize<8>
using PacketTimestamp = IntegerWithBitSize<32>
A timestamp for a packet, in milliseconds since device boot-up.
using PacketTimestampOffset = IntegerWithBitSize<5>
This relative timestamp is for use inside a packet, and it represents a number of milliseconds that should be added to the packet's timestamp.
using MessageType = IntegerWithBitSize<7>
This is the first item in a BLOCKS message, identifying the message type.
using TopologyIndex = uint8
This is a type of index identifier used to refer to a block within a group.
It refers to the index of a device in the list of devices that was most recently sent via a topology change message (It's not a global UID for a block unit). NB: to send a message to all devices, pass the getDeviceIndexForBroadcast() value.
using DeviceCount = IntegerWithBitSize<7>
using ConnectionCount = IntegerWithBitSize<8>
using BatteryLevel = IntegerWithBitSize<5>
Battery charge level.
using BatteryCharging = IntegerWithBitSize<1>
Battery charger connection flag.
using ConnectorPort = IntegerWithBitSize<5>
ConnectorPort is an index, starting at 0 for the leftmost port on the top edge, and going clockwise.
using TouchIndex = IntegerWithBitSize<5>
The index of a touch, i.e.
finger number.
using PacketCounter = IntegerWithBitSize<10>
using DeviceCommand = IntegerWithBitSize<9>
using ConfigCommand = IntegerWithBitSize<4>
using ConfigItemIndex = IntegerWithBitSize<8>
using ConfigItemValue = IntegerWithBitSize<32>
using ControlButtonID = IntegerWithBitSize<12>
An ID for a control-block button type.
using RotaryDialIndex = IntegerWithBitSize<7>
using RotaryDialAngle = IntegerWithBitSize<14>
using RotaryDialDelta = IntegerWithBitSize<14>
using PacketIndex = IntegerWithBitSize<16>
using DataChangeCommand = IntegerWithBitSize<3>
using ByteCountFew = IntegerWithBitSize<4>
using ByteCountMany = IntegerWithBitSize<8>
using ByteValue = IntegerWithBitSize<8>
using ByteSequenceContinues = IntegerWithBitSize<1>
using FirmwareUpdateACKCode = IntegerWithBitSize<7>
using FirmwareUpdateACKDetail = IntegerWithBitSize<32>
using FirmwareUpdatePacketSize = IntegerWithBitSize<7>
Enumeration Type Documentation
enum MessageFromDevice strong
Messages that a device may send to the host.
Enumerator
deviceTopology
packetACK
firmwareUpdateACK
deviceTopologyExtend
deviceTopologyEnd
deviceVersionList
deviceNameList
touchStart
touchMove
touchEnd
touchStartWithVelocity
touchMoveWithVelocity
touchEndWithVelocity
configMessage
controlButtonDown
controlButtonUp
programEventMessage
logMessage
enum MessageFromHost strong
Messages that the host may send to a device.
Enumerator
deviceCommandMessage
sharedDataChange
programEventMessage
firmwareUpdatePacket
configMessage
factoryReset
blockReset
setName
enum ConfigItemId
Configuration Item Identifiers.
Enumerator
midiStartChannel
midiEndChannel
midiUseMPE
pitchBendRange
octave
transpose
slideCC
slideMode
octaveTopology
velocitySensitivity
glideSensitivity
slideSensitivity
pressureSensitivity
liftSensitivity
fixedVelocity
fixedVelocityValue
pianoMode
glideLock
mode
volume
scale
hideMode
chord
arpPattern
tempo
xTrackingMode
yTrackingMode
zTrackingMode
user0
user1
user2
user3
user4
user5
user6
user7
user8
user9
user10
user11
user12
user13
user14
user15
user16
user17
user18
user19
user20
user21
user22
user23
user24
user25
user26
user27
user28
user29
user30
user31
enum DeviceCommands
Enumerator
beginAPIMode
requestTopologyMessage
endAPIMode
ping
debugMode
saveProgramAsDefault
enum ConfigCommands
Enumerator
setConfig
requestConfig
requestFactorySync
requestUserSync
updateConfig
updateUserConfig
setConfigState
factorySyncEnd
clusterConfigSync
enum DataChangeCommands
Enumerator
endOfPacket
endOfChanges
skipBytesFew
skipBytesMany
setSequenceOfBytes
setFewBytesWithValue
setFewBytesWithLastValue
setManyBytesWithValue
enum BitSizes
Contains the number of bits required to encode various items in the packets.
Enumerator
topologyMessageHeader
topologyDeviceInfo
topologyConnectionInfo
typeDeviceAndTime
touchMessage
touchMessageWithVelocity
programEventMessage
programEventMessage
programEventMessage
packetACK
packetACK
firmwareUpdateACK
firmwareUpdateACK
controlButtonMessage
configSetMessage
configRespMessage
configSyncEndMessage