JUCE: files
files
juce_core
Classes
class DirectoryIterator
Searches through the files in a directory, returning each file that is found.
class File
Represents a local file or directory.
class FileFilter
Interface for deciding which files are suitable for something.
class FileInputStream
An input stream that reads from a local file.
class FileOutputStream
An output stream that writes into a local file.
class FileSearchPath
Represents a set of folders that make up a search path.
class MemoryMappedFile
Maps a file into virtual memory for easy reading and/or writing.
class TemporaryFile
Manages a temporary file, which will be deleted when this object is deleted.
class WildcardFileFilter
A type of FileFilter that works by wildcard pattern matching.
Detailed Description
Class Documentation
class DirectoryIterator
Searches through the files in a directory, returning each file that is found.
A DirectoryIterator will search through a directory and its subdirectories using a wildcard filepattern match.
If you may be scanning a large number of files, it's usually smarter to use this class than File::findChildFiles() because it allows you to stop at any time, rather than having to wait for the entire scan to finish before getting the results.
It also provides an estimate of its progress, using a (highly inaccurate!) algorithm.
Public Member Functions
DirectoryIterator (const File &directory, bool isRecursive, const String &wildCard="*", int whatToLookFor=File::findFiles)
Creates a DirectoryIterator for a given directory.
~DirectoryIterator ()
Destructor.
bool next ()
Moves the iterator along to the next file.
bool next (bool *isDirectory, bool *isHidden, int64 *fileSize, Time *modTime, Time *creationTime, bool *isReadOnly)
Moves the iterator along to the next file, and returns various properties of that file.
const File & getFile () const
Returns the file that the iterator is currently pointing at.
float getEstimatedProgress () const
Returns a guess of how far through the search the iterator has got.
Constructor & Destructor Documentation
DirectoryIterator::DirectoryIterator (const File & directory, bool isRecursive, const String & wildCard = "*", int whatToLookFor = File::findFiles)
Creates a DirectoryIterator for a given directory.
After creating one of these, call its next() method to get the first file - e.g.
DirectoryIterator iter (File ("/animals/mooses"), true, "*.moose");
while (iter.next())
{
    File theFileItFound (iter.getFile());
    ... etc
}
Parameters
directory the directory to search in
isRecursive whether all the subdirectories should also be searched
wildCard the file pattern to match. This may contain multiple patterns separated by a semi-colon or comma, e.g. "*.jpg;*.png"
whatToLookFor a value from the File::TypesOfFileToFind enum, specifying whether to look for files, directories, or both.
DirectoryIterator::~DirectoryIterator ()
Destructor.
Member Function Documentation
bool DirectoryIterator::next ()
Moves the iterator along to the next file.
Returns
true if a file was found (you can then use getFile() to see what it was) - or false if there are no more matching files.
bool DirectoryIterator::next (bool * isDirectory, bool * isHidden, int64 * fileSize, Time * modTime, Time * creationTime, bool * isReadOnly)
Moves the iterator along to the next file, and returns various properties of that file.
If you need to find out details about the file, it's more efficient to call this method than to call the normal next() method and then find out the details afterwards.
All the parameters are optional, so pass null pointers for any items that you're not interested in.
Returns
true if a file was found (you can then use getFile() to see what it was) - or false if there are no more matching files. If it returns false, then none of the parameters will be filled-in.
const File& DirectoryIterator::getFile () const
Returns the file that the iterator is currently pointing at.
The result of this call is only valid after a call to next() has returned true.
float DirectoryIterator::getEstimatedProgress () const
Returns a guess of how far through the search the iterator has got.
Returns
a value 0.0 to 1.0 to show the progress, although this won't be very accurate.
class File
Represents a local file or directory.
This class encapsulates the absolute pathname of a file or directory, and has methods for finding out about the file and changing its properties.
To read or write to the file, there are methods for returning an input or output stream.
See Also
FileInputStream, FileOutputStream
Public Types
enum TypesOfFileToFind { findDirectories = 1, findFiles = 2, findFilesAndDirectories = 3, ignoreHiddenFiles = 4 }
Used in file searching, to specify whether to return files, directories, or both.
enum SpecialLocationType {
userHomeDirectory, userDocumentsDirectory, userDesktopDirectory, userMusicDirectory,
userMoviesDirectory, userPicturesDirectory, userApplicationDataDirectory, commonApplicationDataDirectory,
commonDocumentsDirectory, tempDirectory, currentExecutableFile, currentApplicationFile,
invokedExecutableFile, hostApplicationPath, globalApplicationsDirectory
}
A set of types of location that can be passed to the getSpecialLocation() method.
Public Member Functions
File () noexcept
Creates an (invalid) file object.
File (const String &absolutePath)
Creates a file from an absolute path.
File (const File &)
Creates a copy of another file object.
~File () noexcept
Destructor.
File & operator= (const String &newAbsolutePath)
Sets the file based on an absolute pathname.
File & operator= (const File &otherFile)
Copies from another file object.
File (File &&) noexcept
Move constructor.
File & operator= (File &&) noexcept
Move assignment operator.
bool exists () const
Checks whether the file actually exists.
bool existsAsFile () const
Checks whether the file exists and is a file rather than a directory.
bool isDirectory () const
Checks whether the file is a directory that exists.
bool isRoot () const
Checks whether the path of this file represents the root of a file system, irrespective of its existance.
int64 getSize () const
Returns the size of the file in bytes.
const String & getFullPathName () const noexcept
Returns the complete, absolute path of this file.
String getFileName () const
Returns the last section of the pathname.
String getRelativePathFrom (const File &directoryToBeRelativeTo) const
Creates a relative path that refers to a file relatively to a given directory.
String getFileExtension () const
Returns the file's extension.
bool hasFileExtension (StringRef extensionToTest) const
Checks whether the file has a given extension.
File withFileExtension (StringRef newExtension) const
Returns a version of this file with a different file extension.
String getFileNameWithoutExtension () const
Returns the last part of the filename, without its file extension.
int hashCode () const
Returns a 32-bit hash-code that identifies this file.
int64 hashCode64 () const
Returns a 64-bit hash-code that identifies this file.
File getChildFile (StringRef relativeOrAbsolutePath) const
Returns a file that represents a relative (or absolute) sub-path of the current one.
File getSiblingFile (StringRef siblingFileName) const
Returns a file which is in the same directory as this one.
File getParentDirectory () const
Returns the directory that contains this file or directory.
bool isAChildOf (const File &potentialParentDirectory) const
Checks whether a file is somewhere inside a directory.
File getNonexistentChildFile (const String &prefix, const String &suffix, bool putNumbersInBrackets=true) const
Chooses a filename relative to this one that doesn't already exist.
File getNonexistentSibling (bool putNumbersInBrackets=true) const
Chooses a filename for a sibling file to this one that doesn't already exist.
bool operator== (const File &) const
Compares the pathnames for two files.
bool operator!= (const File &) const
Compares the pathnames for two files.
bool operator< (const File &) const
Compares the pathnames for two files.
bool operator> (const File &) const
Compares the pathnames for two files.
bool hasWriteAccess () const
Checks whether a file can be created or written to.
bool setReadOnly (bool shouldBeReadOnly, bool applyRecursively=false) const
Changes the write-permission of a file or directory.
bool setExecutePermission (bool shouldBeExecutable) const
Changes the execute-permissions of a file.
bool isHidden () const
Returns true if this file is a hidden or system file.
uint64 getFileIdentifier () const
Returns a unique identifier for the file, if one is available.
Time getLastModificationTime () const
Returns the last modification time of this file.
Time getLastAccessTime () const
Returns the last time this file was accessed.
Time getCreationTime () const
Returns the time that this file was created.
bool setLastModificationTime (Time newTime) const
Changes the modification time for this file.
bool setLastAccessTime (Time newTime) const
Changes the last-access time for this file.
bool setCreationTime (Time newTime) const
Changes the creation date for this file.
String getVersion () const
If possible, this will try to create a version string for the given file.
Result create () const
Creates an empty file if it doesn't already exist.
Result createDirectory () const
Creates a new directory for this filename.
bool deleteFile () const
Deletes a file.
bool deleteRecursively () const
Deletes a file or directory and all its subdirectories.
bool moveToTrash () const
Moves this file or folder to the trash.
bool moveFileTo (const File &targetLocation) const
Moves or renames a file.
bool copyFileTo (const File &targetLocation) const
Copies a file.
bool replaceFileIn (const File &targetLocation) const
Replaces a file.
bool copyDirectoryTo (const File &newDirectory) const
Copies a directory.
int findChildFiles (Array< File > &results, int whatToLookFor, bool searchRecursively, const String &wildCardPattern="*") const
Searches inside a directory for files matching a wildcard pattern.
int getNumberOfChildFiles (int whatToLookFor, const String &wildCardPattern="*") const
Searches inside a directory and counts how many files match a wildcard pattern.
bool containsSubDirectories () const
Returns true if this file is a directory that contains one or more subdirectories.
FileInputStream * createInputStream () const
Creates a stream to read from this file.
FileOutputStream * createOutputStream (size_t bufferSize=0x8000) const
Creates a stream to write to this file.
bool loadFileAsData (MemoryBlock &result) const
Loads a file's contents into memory as a block of binary data.
String loadFileAsString () const
Reads a file into memory as a string.
void readLines (StringArray &destLines) const
Reads the contents of this file as text and splits it into lines, which are appended to the given StringArray.
bool appendData (const void *dataToAppend, size_t numberOfBytes) const
Appends a block of binary data to the end of the file.
bool replaceWithData (const void *dataToWrite, size_t numberOfBytes) const
Replaces this file's contents with a given block of data.
bool appendText (const String &textToAppend, bool asUnicode=false, bool writeUnicodeHeaderBytes=false) const
Appends a string to the end of the file.
bool replaceWithText (const String &textToWrite, bool asUnicode=false, bool writeUnicodeHeaderBytes=false) const
Replaces this file's contents with a given text string.
bool hasIdenticalContentTo (const File &other) const
Attempts to scan the contents of this file and compare it to another file, returning true if this is possible and they match byte-for-byte.
String getVolumeLabel () const
Finds the name of the drive on which this file lives.
int getVolumeSerialNumber () const
Returns the serial number of the volume on which this file lives.
int64 getBytesFreeOnVolume () const
Returns the number of bytes free on the drive that this file lives on.
int64 getVolumeTotalSize () const
Returns the total size of the drive that contains this file.
bool isOnCDRomDrive () const
Returns true if this file is on a CD or DVD drive.
bool isOnHardDisk () const
Returns true if this file is on a hard disk.
bool isOnRemovableDrive () const
Returns true if this file is on a removable disk drive.
bool startAsProcess (const String &parameters=String()) const
Launches the file as a process.
void revealToUser () const
Opens Finder, Explorer, or whatever the OS uses, to show the user this file's location.
bool setAsCurrentWorkingDirectory () const
Sets the current working directory to be this file.
bool createSymbolicLink (const File &linkFileToCreate, bool overwriteExisting) const
Tries to create a symbolic link and returns a boolean to indicate success.
bool isSymbolicLink () const
Returns true if this file is a link or alias that can be followed using getLinkedTarget().
File getLinkedTarget () const
If this file is a link or alias, this returns the file that it points to.
OSType getMacOSType () const
OSX ONLY - Finds the OSType of a file from the its resources.
bool isBundle () const
OSX ONLY - Returns true if this file is actually a bundle.
void addToDock () const
OSX ONLY - Adds this file to the OSX dock.
Static Public Member Functions
static String descriptionOfSizeInBytes (int64 bytes)
Utility function to convert a file size in bytes to a neat string description.
static void findFileSystemRoots (Array< File > &results)
Creates a set of files to represent each file root.
static File JUCE_CALLTYPE getSpecialLocation (const SpecialLocationType type)
Finds the location of a special type of file or directory, such as a home folder or documents folder.
static File createTempFile (StringRef fileNameEnding)
Returns a temporary file in the system's temp directory.
static File getCurrentWorkingDirectory ()
Returns the current working directory.
static String createLegalFileName (const String &fileNameToFix)
Returns a version of a filename with any illegal characters removed.
static String createLegalPathName (const String &pathNameToFix)
Returns a version of a path with any illegal characters removed.
static bool areFileNamesCaseSensitive ()
Indicates whether filenames are case-sensitive on the current operating system.
static bool isAbsolutePath (StringRef path)
Returns true if the string seems to be a fully-specified absolute path.
static File createFileWithoutCheckingPath (const String &absolutePath) noexcept
Creates a file that simply contains this string, without doing the sanity-checking that the normal constructors do.
static String addTrailingSeparator (const String &path)
Adds a separator character to the end of a path if it doesn't already have one.
Static Public Attributes
static const juce_wchar separator
The system-specific file separator character.
static const String separatorString
The system-specific file separator character, as a string.
Member Enumeration Documentation
enum File::TypesOfFileToFind
Used in file searching, to specify whether to return files, directories, or both.
Enumerator
findDirectories
Use this flag to indicate that you want to find directories.
findFiles
Use this flag to indicate that you want to find files.
findFilesAndDirectories
Use this flag to indicate that you want to find both files and directories.
ignoreHiddenFiles
Add this flag to avoid returning any hidden files in the results.
enum File::SpecialLocationType
A set of types of location that can be passed to the getSpecialLocation() method.
Enumerator
userHomeDirectory
The user's home folder.
This is the same as using File ("~").
userDocumentsDirectory
The user's default documents folder.
On Windows, this might be the user's "My Documents" folder. On the Mac it'll be their "Documents" folder. Linux doesn't tend to have one of these, so it might just return their home folder.
userDesktopDirectory
The folder that contains the user's desktop objects.
userMusicDirectory
The most likely place where a user might store their music files.
userMoviesDirectory
The most likely place where a user might store their movie files.
userPicturesDirectory
The most likely place where a user might store their picture files.
userApplicationDataDirectory
The folder in which applications store their persistent user-specific settings.
On Windows, this might be "\Documents and Settings\username\Application Data". On the Mac, it might be "~/Library". If you're going to store your settings in here, always create your own sub-folder to put them in, to avoid making a mess. On GNU/Linux it is "~/.config".
commonApplicationDataDirectory
An equivalent of the userApplicationDataDirectory folder that is shared by all users of the computer, rather than just the current user.
On the Mac it'll be "/Library", on Windows, it could be something like "\Documents and Settings\All Users\Application Data".
On GNU/Linux it is "/opt".
Depending on the setup, this folder may be read-only.
commonDocumentsDirectory
A place to put documents which are shared by all users of the machine.
On Windows this may be somewhere like "C:\Users\Public\Documents", on OSX it will be something like "/Users/Shared". Other OSes may have no such concept though, so be careful.
tempDirectory
The folder that should be used for temporary files.
Always delete them when you're finished, to keep the user's computer tidy!
currentExecutableFile
Returns this application's executable file.
If running as a plug-in or DLL, this will (where possible) be the DLL rather than the host app.
On the mac this will return the unix binary, not the package folder - see currentApplicationFile for that.
See also invokedExecutableFile, which is similar, but if the exe was launched from a file link, invokedExecutableFile will return the name of the link.
currentApplicationFile
Returns this application's location.
If running as a plug-in or DLL, this will (where possible) be the DLL rather than the host app.
On the mac this will return the package folder (if it's in one), not the unix binary that's inside it - compare with currentExecutableFile.
invokedExecutableFile
Returns the file that was invoked to launch this executable.
This may differ from currentExecutableFile if the app was started from e.g. a link - this will return the name of the link that was used, whereas currentExecutableFile will return the actual location of the target executable.
hostApplicationPath
In a plugin, this will return the path of the host executable.
globalApplicationsDirectory
The directory in which applications normally get installed.
So on windows, this would be something like "C:\Program Files", on the Mac "/Applications", or "/usr" on linux.
Constructor & Destructor Documentation
File::File () noexcept
Creates an (invalid) file object.
The file is initially set to an empty path, so getFullPathName() will return an empty string.
You can use its operator= method to point it at a proper file.
File::File (const String & absolutePath)
Creates a file from an absolute path.
If the path supplied is a relative path, it is taken to be relative to the current working directory (see File::getCurrentWorkingDirectory()), but this isn't a recommended way of creating a file, because you never know what the CWD is going to be.
On the Mac/Linux, the path can include "~" notation for referring to user home directories.
File::File (const File &)
Creates a copy of another file object.
File::~File () noexcept
Destructor.
File::File (File &&) noexcept
Move constructor.
Member Function Documentation
File& File::operator= (const String & newAbsolutePath)
Sets the file based on an absolute pathname.
If the path supplied is a relative path, it is taken to be relative to the current working directory (see File::getCurrentWorkingDirectory()), but this isn't a recommended way of creating a file, because you never know what the CWD is going to be.
On the Mac/Linux, the path can include "~" notation for referring to user home directories.
File& File::operator= (const File & otherFile)
Copies from another file object.
File& File::operator= (File &&) noexcept
Move assignment operator.
bool File::exists () const
Checks whether the file actually exists.
Returns
true if the file exists, either as a file or a directory.
See Also
existsAsFile, isDirectory
bool File::existsAsFile () const
Checks whether the file exists and is a file rather than a directory.
Returns
true only if this is a real file, false if it's a directory or doesn't exist
See Also
exists, isDirectory
bool File::isDirectory () const
Checks whether the file is a directory that exists.
Returns
true only if the file is a directory which actually exists, so false if it's a file or doesn't exist at all
See Also
exists, existsAsFile
Referenced by File::NaturalFileComparator::compareElements().
bool File::isRoot () const
Checks whether the path of this file represents the root of a file system, irrespective of its existance.
This will return true for "C:", "D:", etc on Windows and "/" on other platforms.
int64 File::getSize () const
Returns the size of the file in bytes.
Returns
the number of bytes in the file, or 0 if it doesn't exist.
static String File::descriptionOfSizeInBytes (int64 bytes) static
Utility function to convert a file size in bytes to a neat string description.
So for example 100 would return "100 bytes", 2000 would return "2 KB", 2000000 would produce "2 MB", etc.
const String& File::getFullPathName () const noexcept
Returns the complete, absolute path of this file.
This includes the filename and all its parent folders. On Windows it'll also include the drive letter prefix; on Mac or Linux it'll be a complete path starting from the root folder.
If you just want the file's name, you should use getFileName() or getFileNameWithoutExtension().
See Also
getFileName, getRelativePathFrom
Referenced by File::NaturalFileComparator::compareElements(), PluginHostType::getHostPath(), and StandalonePluginHolder::setLastFile().
String File::getFileName () const
Returns the last section of the pathname.
Returns just the final part of the path - e.g. if the whole path is "/moose/fish/foo.txt" this will return "foo.txt".
For a directory, it returns the final part of the path - e.g. for the directory "/moose/fish" it'll return "fish".
If the filename begins with a dot, it'll return the whole filename, e.g. for "/moose/.fish", it'll return ".fish"
See Also
getFullPathName, getFileNameWithoutExtension
String File::getRelativePathFrom (const File & directoryToBeRelativeTo) const
Creates a relative path that refers to a file relatively to a given directory.
e.g. File ("/moose/foo.txt").getRelativePathFrom (File ("/moose/fish/haddock")) would return "../../foo.txt".
If it's not possible to navigate from one file to the other, an absolute path is returned. If the paths are invalid, an empty string may also be returned.
Parameters
directoryToBeRelativeTo the directory which the resultant string will be relative to. If this is actually a file rather than a directory, its parent directory will be used instead. If it doesn't exist, it's assumed to be a directory.
See Also
getChildFile, isAbsolutePath
String File::getFileExtension () const
Returns the file's extension.
Returns the file extension of this file, also including the dot.
e.g. "/moose/fish/foo.txt" would return ".txt"
See Also
hasFileExtension, withFileExtension, getFileNameWithoutExtension
bool File::hasFileExtension (StringRef extensionToTest) const
Checks whether the file has a given extension.
Parameters
extensionToTest the extension to look for - it doesn't matter whether or not this string has a dot at the start, so ".wav" and "wav" will have the same effect. To compare with multiple extensions, this parameter can contain multiple strings, separated by semi-colons - so, for example: hasFileExtension (".jpeg;png;gif") would return true if the file has any of those three extensions.
See Also
getFileExtension, withFileExtension, getFileNameWithoutExtension
File File::withFileExtension (StringRef newExtension) const
Returns a version of this file with a different file extension.
e.g. File ("/moose/fish/foo.txt").withFileExtension ("html") returns "/moose/fish/foo.html"
Parameters
newExtension the new extension, either with or without a dot at the start (this doesn't make any difference). To get remove a file's extension altogether, pass an empty string into this function.
See Also
getFileName, getFileExtension, hasFileExtension, getFileNameWithoutExtension
String File::getFileNameWithoutExtension () const
Returns the last part of the filename, without its file extension.
e.g. for "/moose/fish/foo.txt" this will return "foo".
See Also
getFileName, getFileExtension, hasFileExtension, withFileExtension
int File::hashCode () const
Returns a 32-bit hash-code that identifies this file.
This is based on the filename. Obviously it's possible, although unlikely, that two files will have the same hash-code.
int64 File::hashCode64 () const
Returns a 64-bit hash-code that identifies this file.
This is based on the filename. Obviously it's possible, although unlikely, that two files will have the same hash-code.
File File::getChildFile (StringRef relativeOrAbsolutePath) const
Returns a file that represents a relative (or absolute) sub-path of the current one.
This will find a child file or directory of the current object.
e.g. File ("/moose/fish").getChildFile ("foo.txt") will produce "/moose/fish/foo.txt". File ("/moose/fish").getChildFile ("haddock/foo.txt") will produce "/moose/fish/haddock/foo.txt". File ("/moose/fish").getChildFile ("../foo.txt") will produce "/moose/foo.txt".
If the string is actually an absolute path, it will be treated as such, e.g. File ("/moose/fish").getChildFile ("/foo.txt") will produce "/foo.txt"
See Also
getSiblingFile, getParentDirectory, getRelativePathFrom, isAChildOf
File File::getSiblingFile (StringRef siblingFileName) const
Returns a file which is in the same directory as this one.
This is equivalent to getParentDirectory().getChildFile (name).
See Also
getChildFile, getParentDirectory
File File::getParentDirectory () const
Returns the directory that contains this file or directory.
e.g. for "/moose/fish/foo.txt" this will return "/moose/fish".
bool File::isAChildOf (const File & potentialParentDirectory) const
Checks whether a file is somewhere inside a directory.
Returns true if this file is somewhere inside a subdirectory of the directory that is passed in. Neither file actually has to exist, because the function just checks the paths for similarities.
e.g. File ("/moose/fish/foo.txt").isAChildOf ("/moose") is true. File ("/moose/fish/foo.txt").isAChildOf ("/moose/fish") is also true.
File File::getNonexistentChildFile (const String & prefix, const String & suffix, bool putNumbersInBrackets = true) const
Chooses a filename relative to this one that doesn't already exist.
If this file is a directory, this will return a child file of this directory that doesn't exist, by adding numbers to a prefix and suffix until it finds one that isn't already there.
If the prefix + the suffix doesn't exist, it won't bother adding a number.
e.g. File ("/moose/fish").getNonexistentChildFile ("foo", ".txt", true) might return "/moose/fish/foo(2).txt" if there's already a file called "foo.txt".
Parameters
prefix the string to use for the filename before the number
suffix the string to add to the filename after the number
putNumbersInBrackets if true, this will create filenames in the format "prefix(number)suffix", if false, it will leave the brackets out.
File File::getNonexistentSibling (bool putNumbersInBrackets = true) const
Chooses a filename for a sibling file to this one that doesn't already exist.
If this file doesn't exist, this will just return itself, otherwise it will return an appropriate sibling that doesn't exist, e.g. if a file "/moose/fish/foo.txt" exists, this might return "/moose/fish/foo(2).txt".
Parameters
putNumbersInBrackets whether to add brackets around the numbers that get appended to the new filename.
bool File::operator== (const File &) const
Compares the pathnames for two files.
bool File::operator!= (const File &) const
Compares the pathnames for two files.
bool File::operator< (const File &) const
Compares the pathnames for two files.
bool File::operator> (const File &) const
Compares the pathnames for two files.
bool File::hasWriteAccess () const
Checks whether a file can be created or written to.
Returns
true if it's possible to create and write to this file. If the file doesn't already exist, this will check its parent directory to see if writing is allowed.
See Also
setReadOnly
bool File::setReadOnly (bool shouldBeReadOnly, bool applyRecursively = false) const
Changes the write-permission of a file or directory.
Parameters
shouldBeReadOnly whether to add or remove write-permission
applyRecursively if the file is a directory and this is true, it will recurse through all the subfolders changing the permissions of all files
Returns
true if it manages to change the file's permissions.
See Also
hasWriteAccess
bool File::setExecutePermission (bool shouldBeExecutable) const
Changes the execute-permissions of a file.
Parameters
shouldBeExecutable whether to add or remove execute-permission
Returns
true if it manages to change the file's permissions.
bool File::isHidden () const
Returns true if this file is a hidden or system file.
The criteria for deciding whether a file is hidden are platform-dependent.
uint64 File::getFileIdentifier () const
Returns a unique identifier for the file, if one is available.
Depending on the OS and file-system, this may be a unix inode number or a win32 file identifier, or 0 if it fails to find one. The number will be unique on the filesystem, but not globally.
Time File::getLastModificationTime () const
Returns the last modification time of this file.
Returns
the time, or an invalid time if the file doesn't exist.
See Also
setLastModificationTime, getLastAccessTime, getCreationTime
Time File::getLastAccessTime () const
Returns the last time this file was accessed.
Returns
the time, or an invalid time if the file doesn't exist.
See Also
setLastAccessTime, getLastModificationTime, getCreationTime
Time File::getCreationTime () const
Returns the time that this file was created.
Returns
the time, or an invalid time if the file doesn't exist.
See Also
getLastModificationTime, getLastAccessTime
bool File::setLastModificationTime (Time newTime) const
Changes the modification time for this file.
Parameters
newTime the time to apply to the file
Returns
true if it manages to change the file's time.
See Also
getLastModificationTime, setLastAccessTime, setCreationTime
bool File::setLastAccessTime (Time newTime) const
Changes the last-access time for this file.
Parameters
newTime the time to apply to the file
Returns
true if it manages to change the file's time.
See Also
getLastAccessTime, setLastModificationTime, setCreationTime
bool File::setCreationTime (Time newTime) const
Changes the creation date for this file.
Parameters
newTime the time to apply to the file
Returns
true if it manages to change the file's time.
See Also
getCreationTime, setLastModificationTime, setLastAccessTime
String File::getVersion () const
If possible, this will try to create a version string for the given file.
The OS may be able to look at the file and give a version for it - e.g. with executables, bundles, dlls, etc. If no version is available, this will return an empty string.
Result File::create () const
Creates an empty file if it doesn't already exist.
If the file that this object refers to doesn't exist, this will create a file of zero size.
If it already exists or is a directory, this method will do nothing.
If the parent directories of the File do not exist then this method will recursively create the parent directories.
Returns
a result to indicate whether the file was created successfully, or an error message if it failed.
See Also
createDirectory
Result File::createDirectory () const
Creates a new directory for this filename.
This will try to create the file as a directory, and will also create any parent directories it needs in order to complete the operation.
Returns
a result to indicate whether the directory was created successfully, or an error message if it failed.
See Also
create
bool File::deleteFile () const
Deletes a file.
If this file is actually a directory, it may not be deleted correctly if it contains files. See deleteRecursively() as a better way of deleting directories.
Returns
true if the file has been successfully deleted (or if it didn't exist to begin with).
See Also
deleteRecursively
bool File::deleteRecursively () const
Deletes a file or directory and all its subdirectories.
If this file is a directory, this will try to delete it and all its subfolders. If it's just a file, it will just try to delete the file.
Returns
true if the file and all its subfolders have been successfully deleted (or if it didn't exist to begin with).
See Also
deleteFile
bool File::moveToTrash () const
Moves this file or folder to the trash.
Returns
true if the operation succeeded. It could fail if the trash is full, or if the file is write-protected, so you should check the return value and act appropriately.
bool File::moveFileTo (const File & targetLocation) const
Moves or renames a file.
Tries to move a file to a different location. If the target file already exists, this will attempt to delete it first, and will fail if this can't be done.
Note that the destination file isn't the directory to put it in, it's the actual filename that you want the new file to have.
Also note that on some OSes (e.g. Windows), moving files between different volumes may not be possible.
Returns
true if the operation succeeds
bool File::copyFileTo (const File & targetLocation) const
Copies a file.
Tries to copy a file to a different location. If the target file already exists, this will attempt to delete it first, and will fail if this can't be done.
Returns
true if the operation succeeds
bool File::replaceFileIn (const File & targetLocation) const
Replaces a file.
Replace the file in the given location, assuming the replaced files identity. Depending on the file system this will preserve file attributes such as creation date, short file name, etc.
If replacement succeeds the original file is deleted.
Returns
true if the operation succeeds
bool File::copyDirectoryTo (const File & newDirectory) const
Copies a directory.
Tries to copy an entire directory, recursively.
If this file isn't a directory or if any target files can't be created, this will return false.
Parameters
newDirectory the directory that this one should be copied to. Note that this is the name of the actual directory to create, not the directory into which the new one should be placed, so there must be enough write privileges to create it if it doesn't exist. Any files inside it will be overwritten by similarly named ones that are copied.
int File::findChildFiles (Array< File > & results, int whatToLookFor, bool searchRecursively, const String & wildCardPattern = "*") const
Searches inside a directory for files matching a wildcard pattern.
Assuming that this file is a directory, this method will search it for either files or subdirectories whose names match a filename pattern.
Parameters
results an array to which File objects will be added for the files that the search comes up with
whatToLookFor a value from the TypesOfFileToFind enum, specifying whether to return files, directories, or both. If the ignoreHiddenFiles flag is also added to this value, hidden files won't be returned
searchRecursively if true, all subdirectories will be recursed into to do an exhaustive search
wildCardPattern the filename pattern to search for, e.g. "*.txt"
Returns
the number of results that have been found
See Also
getNumberOfChildFiles, DirectoryIterator
int File::getNumberOfChildFiles (int whatToLookFor, const String & wildCardPattern = "*") const
Searches inside a directory and counts how many files match a wildcard pattern.
Assuming that this file is a directory, this method will search it for either files or subdirectories whose names match a filename pattern, and will return the number of matches found.
This isn't a recursive call, and will only search this directory, not its children.
Parameters
whatToLookFor a value from the TypesOfFileToFind enum, specifying whether to count files, directories, or both. If the ignoreHiddenFiles flag is also added to this value, hidden files won't be counted
wildCardPattern the filename pattern to search for, e.g. "*.txt"
Returns
the number of matches found
See Also
findChildFiles, DirectoryIterator
bool File::containsSubDirectories () const
Returns true if this file is a directory that contains one or more subdirectories.
See Also
isDirectory, findChildFiles
FileInputStream* File::createInputStream () const
Creates a stream to read from this file.
Returns
a stream that will read from this file (initially positioned at the start of the file), or nullptr if the file can't be opened for some reason
See Also
createOutputStream, loadFileAsData
FileOutputStream* File::createOutputStream (size_t bufferSize = 0x8000) const
Creates a stream to write to this file.
If the file exists, the stream that is returned will be positioned ready for writing at the end of the file, so you might want to use deleteFile() first to write to an empty file.
Returns
a stream that will write to this file (initially positioned at the end of the file), or nullptr if the file can't be opened for some reason
See Also
createInputStream, appendData, appendText
bool File::loadFileAsData (MemoryBlock & result) const
Loads a file's contents into memory as a block of binary data.
Of course, trying to load a very large file into memory will blow up, so it's better to check first.
Parameters
result the data block to which the file's contents should be appended - note that if the memory block might already contain some data, you might want to clear it first
Returns
true if the file could all be read into memory
Referenced by StandalonePluginHolder::askUserToLoadState().
String File::loadFileAsString () const
Reads a file into memory as a string.
Attempts to load the entire file as a zero-terminated string.
This makes use of InputStream::readEntireStreamAsString, which can read either UTF-16 or UTF-8 file formats.
void File::readLines (StringArray & destLines) const
Reads the contents of this file as text and splits it into lines, which are appended to the given StringArray.
bool File::appendData (const void * dataToAppend, size_t numberOfBytes) const
Appends a block of binary data to the end of the file.
This will try to write the given buffer to the end of the file.
Returns
false if it can't write to the file for some reason
bool File::replaceWithData (const void * dataToWrite, size_t numberOfBytes) const
Replaces this file's contents with a given block of data.
This will delete the file and replace it with the given data.
A nice feature of this method is that it's safe - instead of deleting the file first and then re-writing it, it creates a new temporary file, writes the data to that, and then moves the new file to replace the existing file. This means that if the power gets pulled out or something crashes, you're a lot less likely to end up with a corrupted or unfinished file..
Returns true if the operation succeeds, or false if it fails.
See Also
appendText
Referenced by StandalonePluginHolder::askUserToSaveState().
bool File::appendText (const String & textToAppend, bool asUnicode = false, bool writeUnicodeHeaderBytes = false) const
Appends a string to the end of the file.
This will try to append a text string to the file, as either 16-bit unicode or 8-bit characters in the default system encoding.
It can also write the 'ff fe' unicode header bytes before the text to indicate the endianness of the file.
Any single \n characters in the string are replaced with \r\n before it is written.
See Also
replaceWithText
bool File::replaceWithText (const String & textToWrite, bool asUnicode = false, bool writeUnicodeHeaderBytes = false) const
Replaces this file's contents with a given text string.
This will delete the file and replace it with the given text.
A nice feature of this method is that it's safe - instead of deleting the file first and then re-writing it, it creates a new temporary file, writes the text to that, and then moves the new file to replace the existing file. This means that if the power gets pulled out or something crashes, you're a lot less likely to end up with an empty file..
For an explanation of the parameters here, see the appendText() method.
Returns true if the operation succeeds, or false if it fails.
See Also
appendText
bool File::hasIdenticalContentTo (const File & other) const
Attempts to scan the contents of this file and compare it to another file, returning true if this is possible and they match byte-for-byte.
static void File::findFileSystemRoots (Array< File > & results) static
Creates a set of files to represent each file root.
e.g. on Windows this will create files for "c:\", "d:\" etc according to which ones are available. On the Mac/Linux, this will probably just add a single entry for "/".
String File::getVolumeLabel () const
Finds the name of the drive on which this file lives.
Returns
the volume label of the drive, or an empty string if this isn't possible
int File::getVolumeSerialNumber () const
Returns the serial number of the volume on which this file lives.
Returns
the serial number, or zero if there's a problem doing this
int64 File::getBytesFreeOnVolume () const
Returns the number of bytes free on the drive that this file lives on.
Returns
the number of bytes free, or 0 if there's a problem finding this out
See Also
getVolumeTotalSize
int64 File::getVolumeTotalSize () const
Returns the total size of the drive that contains this file.
Returns
the total number of bytes that the volume can hold
See Also
getBytesFreeOnVolume
bool File::isOnCDRomDrive () const
Returns true if this file is on a CD or DVD drive.
bool File::isOnHardDisk () const
Returns true if this file is on a hard disk.
This will fail if it's a network drive, but will still be true for removable hard-disks.
bool File::isOnRemovableDrive () const
Returns true if this file is on a removable disk drive.
This might be a usb-drive, a CD-rom, or maybe a network drive.
bool File::startAsProcess (const String & parameters = String()) const
Launches the file as a process.
if the file is executable, this will run it.
if it's a document of some kind, it will launch the document with its default viewer application.
if it's a folder, it will be opened in Explorer, Finder, or equivalent.
See Also
revealToUser
void File::revealToUser () const
Opens Finder, Explorer, or whatever the OS uses, to show the user this file's location.
See Also
startAsProcess
static File JUCE_CALLTYPE File::getSpecialLocation (const SpecialLocationType type) static
Finds the location of a special type of file or directory, such as a home folder or documents folder.
See Also
SpecialLocationType
Referenced by PluginHostType::getHostPath(), and StandalonePluginHolder::getLastFile().
static File File::createTempFile (StringRef fileNameEnding) static
Returns a temporary file in the system's temp directory.
This will try to return the name of a non-existent temp file. To get the temp folder, you can use getSpecialLocation (File::tempDirectory).
static File File::getCurrentWorkingDirectory () static
Returns the current working directory.
See Also
setAsCurrentWorkingDirectory
bool File::setAsCurrentWorkingDirectory () const
Sets the current working directory to be this file.
For this to work the file must point to a valid directory.
Returns
true if the current directory has been changed.
See Also
getCurrentWorkingDirectory
static String File::createLegalFileName (const String & fileNameToFix) static
Returns a version of a filename with any illegal characters removed.
This will return a copy of the given string after removing characters that are not allowed in a legal filename, and possibly shortening the string if it's too long.
Because this will remove slashes, don't use it on an absolute pathname - use createLegalPathName() for that.
See Also
createLegalPathName
static String File::createLegalPathName (const String & pathNameToFix) static
Returns a version of a path with any illegal characters removed.
Similar to createLegalFileName(), but this won't remove slashes, so can be used on a complete pathname.
See Also
createLegalFileName
static bool File::areFileNamesCaseSensitive () static
Indicates whether filenames are case-sensitive on the current operating system.
static bool File::isAbsolutePath (StringRef path) static
Returns true if the string seems to be a fully-specified absolute path.
static File File::createFileWithoutCheckingPath (const String & absolutePath) static noexcept
Creates a file that simply contains this string, without doing the sanity-checking that the normal constructors do.
Best to avoid this unless you really know what you're doing.
static String File::addTrailingSeparator (const String & path) static
Adds a separator character to the end of a path if it doesn't already have one.
bool File::createSymbolicLink (const File & linkFileToCreate, bool overwriteExisting) const
Tries to create a symbolic link and returns a boolean to indicate success.
bool File::isSymbolicLink () const
Returns true if this file is a link or alias that can be followed using getLinkedTarget().
File File::getLinkedTarget () const
If this file is a link or alias, this returns the file that it points to.
If the file isn't actually link, it'll just return itself.
OSType File::getMacOSType () const
OSX ONLY - Finds the OSType of a file from the its resources.
bool File::isBundle () const
OSX ONLY - Returns true if this file is actually a bundle.
void File::addToDock () const
OSX ONLY - Adds this file to the OSX dock.
Member Data Documentation
const juce_wchar File::separator static
The system-specific file separator character.
On Windows, this will be '\', on Mac/Linux, it'll be '/'
const String File::separatorString static
The system-specific file separator character, as a string.
On Windows, this will be '\', on Mac/Linux, it'll be '/'
class FileFilter
Interface for deciding which files are suitable for something.
For example, this is used by DirectoryContentsList to select which files go into the list.
See Also
WildcardFileFilter, DirectoryContentsList, FileListComponent, FileBrowserComponent
Public Member Functions
FileFilter (const String &filterDescription)
Creates a filter with the given description.
virtual ~FileFilter ()
Destructor.
const String & getDescription () const noexcept
Returns the description that the filter was created with.
virtual bool isFileSuitable (const File &file) const =0
Should return true if this file is suitable for inclusion in whatever context the object is being used.
virtual bool isDirectorySuitable (const File &file) const =0
Should return true if this directory is suitable for inclusion in whatever context the object is being used.
Protected Attributes
String description
Constructor & Destructor Documentation
FileFilter::FileFilter (const String & filterDescription)
Creates a filter with the given description.
The description can be returned later with the getDescription() method.
virtual FileFilter::~FileFilter () virtual
Destructor.
Member Function Documentation
const String& FileFilter::getDescription () const noexcept
Returns the description that the filter was created with.
virtual bool FileFilter::isFileSuitable (const File & file) const pure virtual
Should return true if this file is suitable for inclusion in whatever context the object is being used.
Implemented in FileBrowserComponent, and WildcardFileFilter.
virtual bool FileFilter::isDirectorySuitable (const File & file) const pure virtual
Should return true if this directory is suitable for inclusion in whatever context the object is being used.
Implemented in FileBrowserComponent, and WildcardFileFilter.
Member Data Documentation
String FileFilter::description protected
class FileInputStream
An input stream that reads from a local file.
See Also
InputStream, FileOutputStream, File::createInputStream
Public Member Functions
FileInputStream (const File &fileToRead)
Creates a FileInputStream to read from the given file.
~FileInputStream ()
Destructor.
const File & getFile () const noexcept
Returns the file that this stream is reading from.
const Result & getStatus () const noexcept
Returns the status of the file stream.
bool failedToOpen () const noexcept
Returns true if the stream couldn't be opened for some reason.
bool openedOk () const noexcept
Returns true if the stream opened without problems.
int64 getTotalLength () override
Returns the total number of bytes available for reading in this stream.
int read (void *, int) override
Reads some data from the stream into a memory buffer.
bool isExhausted () override
Returns true if the stream has no more data to read.
int64 getPosition () override
Returns the offset of the next byte that will be read from the stream.
bool setPosition (int64) override
Tries to move the current read position of the stream.
Public Member Functions inherited from InputStream
virtual ~InputStream ()
Destructor.
int64 getNumBytesRemaining ()
Returns the number of bytes available for reading, or a negative value if the remaining length is not known.
virtual char readByte ()
Reads a byte from the stream.
virtual bool readBool ()
Reads a boolean from the stream.
virtual short readShort ()
Reads two bytes from the stream as a little-endian 16-bit value.
virtual short readShortBigEndian ()
Reads two bytes from the stream as a little-endian 16-bit value.
virtual int readInt ()
Reads four bytes from the stream as a little-endian 32-bit value.
virtual int readIntBigEndian ()
Reads four bytes from the stream as a big-endian 32-bit value.
virtual int64 readInt64 ()
Reads eight bytes from the stream as a little-endian 64-bit value.
virtual int64 readInt64BigEndian ()
Reads eight bytes from the stream as a big-endian 64-bit value.
virtual float readFloat ()
Reads four bytes as a 32-bit floating point value.
virtual float readFloatBigEndian ()
Reads four bytes as a 32-bit floating point value.
virtual double readDouble ()
Reads eight bytes as a 64-bit floating point value.
virtual double readDoubleBigEndian ()
Reads eight bytes as a 64-bit floating point value.
virtual int readCompressedInt ()
Reads an encoded 32-bit number from the stream using a space-saving compressed format.
virtual String readNextLine ()
Reads a UTF-8 string from the stream, up to the next linefeed or carriage return.
virtual String readString ()
Reads a zero-terminated UTF-8 string from the stream.
virtual String readEntireStreamAsString ()
Tries to read the whole stream and turn it into a string.
virtual size_t readIntoMemoryBlock (MemoryBlock &destBlock, ssize_t maxNumBytesToRead=-1)
Reads from the stream and appends the data to a MemoryBlock.
virtual void skipNextBytes (int64 numBytesToSkip)
Reads and discards a number of bytes from the stream.
Additional Inherited Members
Protected Member Functions inherited from InputStream
InputStream () noexcept
Constructor & Destructor Documentation
FileInputStream::FileInputStream (const File & fileToRead) explicit
Creates a FileInputStream to read from the given file.
After creating a FileInputStream, you should use openedOk() or failedToOpen() to make sure that it's OK before trying to read from it! If it failed, you can call getStatus() to get more error information.
FileInputStream::~FileInputStream ()
Destructor.
Member Function Documentation
const File& FileInputStream::getFile () const noexcept
Returns the file that this stream is reading from.
const Result& FileInputStream::getStatus () const noexcept
Returns the status of the file stream.
The result will be ok if the file opened successfully. If an error occurs while opening or reading from the file, this will contain an error message.
bool FileInputStream::failedToOpen () const noexcept
Returns true if the stream couldn't be opened for some reason.
See Also
getResult()
bool FileInputStream::openedOk () const noexcept
Returns true if the stream opened without problems.
See Also
getResult()
int64 FileInputStream::getTotalLength () override virtual
Returns the total number of bytes available for reading in this stream.
Note that this is the number of bytes available from the start of the stream, not from the current position.
If the size of the stream isn't actually known, this will return -1.
See Also
getNumBytesRemaining
Implements InputStream.
int FileInputStream::read (void * destBuffer, int maxBytesToRead) override virtual
Reads some data from the stream into a memory buffer.
This is the only read method that subclasses actually need to implement, as the InputStream base class implements the other read methods in terms of this one (although it's often more efficient for subclasses to implement them directly).
Parameters
destBuffer the destination buffer for the data. This must not be null.
maxBytesToRead the maximum number of bytes to read - make sure the memory block passed in is big enough to contain this many bytes. This value must not be negative.
Returns
the actual number of bytes that were read, which may be less than maxBytesToRead if the stream is exhausted before it gets that far
Implements InputStream.
bool FileInputStream::isExhausted () override virtual
Returns true if the stream has no more data to read.
Implements InputStream.
int64 FileInputStream::getPosition () override virtual
Returns the offset of the next byte that will be read from the stream.
See Also
setPosition
Implements InputStream.
bool FileInputStream::setPosition (int64 newPosition) override virtual
Tries to move the current read position of the stream.
The position is an absolute number of bytes from the stream's start.
Some streams might not be able to do this, in which case they should do nothing and return false. Others might be able to manage it by resetting themselves and skipping to the correct position, although this is obviously a bit slow.
Returns
true if the stream manages to reposition itself correctly
See Also
getPosition
Implements InputStream.
class FileOutputStream
An output stream that writes into a local file.
See Also
OutputStream, FileInputStream, File::createOutputStream
Public Member Functions
FileOutputStream (const File &fileToWriteTo, size_t bufferSizeToUse=16384)
Creates a FileOutputStream.
~FileOutputStream ()
Destructor.
const File & getFile () const
Returns the file that this stream is writing to.
const Result & getStatus () const noexcept
Returns the status of the file stream.
bool failedToOpen () const noexcept
Returns true if the stream couldn't be opened for some reason.
bool openedOk () const noexcept
Returns true if the stream opened without problems.
Result truncate ()
Attempts to truncate the file to the current write position.
void flush () override
If the stream is using a buffer, this will ensure it gets written out to the destination.
int64 getPosition () override
Returns the stream's current position.
bool setPosition (int64) override
Tries to move the stream's output position.
bool write (const void *, size_t) override
Writes a block of data to the stream.
bool writeRepeatedByte (uint8 byte, size_t numTimesToRepeat) override
Writes a byte to the output stream a given number of times.
Public Member Functions inherited from OutputStream
virtual ~OutputStream ()
Destructor.
virtual bool writeByte (char byte)
Writes a single byte to the stream.
virtual bool writeBool (bool boolValue)
Writes a boolean to the stream as a single byte.
virtual bool writeShort (short value)
Writes a 16-bit integer to the stream in a little-endian byte order.
virtual bool writeShortBigEndian (short value)
Writes a 16-bit integer to the stream in a big-endian byte order.
virtual bool writeInt (int value)
Writes a 32-bit integer to the stream in a little-endian byte order.
virtual bool writeIntBigEndian (int value)
Writes a 32-bit integer to the stream in a big-endian byte order.
virtual bool writeInt64 (int64 value)
Writes a 64-bit integer to the stream in a little-endian byte order.
virtual bool writeInt64BigEndian (int64 value)
Writes a 64-bit integer to the stream in a big-endian byte order.
virtual bool writeFloat (float value)
Writes a 32-bit floating point value to the stream in a binary format.
virtual bool writeFloatBigEndian (float value)
Writes a 32-bit floating point value to the stream in a binary format.
virtual bool writeDouble (double value)
Writes a 64-bit floating point value to the stream in a binary format.
virtual bool writeDoubleBigEndian (double value)
Writes a 64-bit floating point value to the stream in a binary format.
virtual bool writeCompressedInt (int value)
Writes a condensed binary encoding of a 32-bit integer.
virtual bool writeString (const String &text)
Stores a string in the stream in a binary format.
virtual bool writeText (const String &text, bool asUTF16, bool writeUTF16ByteOrderMark)
Writes a string of text to the stream.
virtual int64 writeFromInputStream (InputStream &source, int64 maxNumBytesToWrite)
Reads data from an input stream and writes it to this stream.
void setNewLineString (const String &newLineString)
Sets the string to write to the stream when a new line is written.
const String & getNewLineString () const noexcept
Returns the current new-line string that was set by setNewLineString().
Additional Inherited Members
Protected Member Functions inherited from OutputStream
OutputStream ()
Constructor & Destructor Documentation
FileOutputStream::FileOutputStream (const File & fileToWriteTo, size_t bufferSizeToUse = 16384)
Creates a FileOutputStream.
If the file doesn't exist, it will first be created. If the file can't be created or opened (for example, because the parent directory of the file does not exist), the failedToOpen() method will return true.
If the file already exists when opened, the stream's write-position will be set to the end of the file. To overwrite an existing file, use File::deleteFile() before opening the stream, or use setPosition(0) after it's opened (although this won't truncate the file).
Destroying a FileOutputStream object does not force the operating system to write the buffered data to disk immediately. If this is required you should call flush() before triggering the destructor.
See Also
TemporaryFile
FileOutputStream::~FileOutputStream ()
Destructor.
Member Function Documentation
const File& FileOutputStream::getFile () const
Returns the file that this stream is writing to.
const Result& FileOutputStream::getStatus () const noexcept
Returns the status of the file stream.
The result will be ok if the file opened successfully. If an error occurs while opening or writing to the file, this will contain an error message.
bool FileOutputStream::failedToOpen () const noexcept
Returns true if the stream couldn't be opened for some reason.
See Also
getResult()
bool FileOutputStream::openedOk () const noexcept
Returns true if the stream opened without problems.
See Also
getResult()
Result FileOutputStream::truncate ()
Attempts to truncate the file to the current write position.
To truncate a file to a specific size, first use setPosition() to seek to the appropriate location, and then call this method.
void FileOutputStream::flush () override virtual
If the stream is using a buffer, this will ensure it gets written out to the destination.
Implements OutputStream.
int64 FileOutputStream::getPosition () override virtual
Returns the stream's current position.
See Also
setPosition
Implements OutputStream.
bool FileOutputStream::setPosition (int64 newPosition) override virtual
Tries to move the stream's output position.
Not all streams will be able to seek to a new position - this will return false if it fails to work.
See Also
getPosition
Implements OutputStream.
bool FileOutputStream::write (const void * dataToWrite, size_t numberOfBytes) override virtual
Writes a block of data to the stream.
When creating a subclass of OutputStream, this is the only write method that needs to be overloaded - the base class has methods for writing other types of data which use this to do the work.
Parameters
dataToWrite the target buffer to receive the data. This must not be null.
numberOfBytes the number of bytes to write.
Returns
false if the write operation fails for some reason
Implements OutputStream.
bool FileOutputStream::writeRepeatedByte (uint8 byte, size_t numTimesToRepeat) override virtual
Writes a byte to the output stream a given number of times.
Returns
false if the write operation fails for some reason
Reimplemented from OutputStream.
class FileSearchPath
Represents a set of folders that make up a search path.
See Also
File
Public Member Functions
FileSearchPath ()
Creates an empty search path.
FileSearchPath (const String &path)
Creates a search path from a string of pathnames.
FileSearchPath (const FileSearchPath &)
Creates a copy of another search path.
FileSearchPath & operator= (const FileSearchPath &)
Copies another search path.
~FileSearchPath ()
Destructor.
FileSearchPath & operator= (const String &path)
Uses a string containing a list of pathnames to re-initialise this list.
int getNumPaths () const
Returns the number of folders in this search path.
File operator[] (int index) const
Returns one of the folders in this search path.
String toString () const
Returns the search path as a semicolon-separated list of directories.
void add (const File &directoryToAdd, int insertIndex=-1)
Adds a new directory to the search path.
bool addIfNotAlreadyThere (const File &directoryToAdd)
Adds a new directory to the search path if it's not already in there.
void remove (int indexToRemove)
Removes a directory from the search path.
void addPath (const FileSearchPath &)
Merges another search path into this one.
void removeRedundantPaths ()
Removes any directories that are actually subdirectories of one of the other directories in the search path.
void removeNonExistentPaths ()
Removes any directories that don't actually exist.
int findChildFiles (Array< File > &results, int whatToLookFor, bool searchRecursively, const String &wildCardPattern="*") const
Searches the path for a wildcard.
bool isFileInPath (const File &fileToCheck, bool checkRecursively) const
Finds out whether a file is inside one of the path's directories.
Constructor & Destructor Documentation
FileSearchPath::FileSearchPath ()
Creates an empty search path.
FileSearchPath::FileSearchPath (const String & path)
Creates a search path from a string of pathnames.
The path can be semicolon- or comma-separated, e.g. "/foo/bar;/foo/moose;/fish/moose"
The separate folders are tokenised and added to the search path.
FileSearchPath::FileSearchPath (const FileSearchPath &)
Creates a copy of another search path.
FileSearchPath::~FileSearchPath ()
Destructor.
Member Function Documentation
FileSearchPath& FileSearchPath::operator= (const FileSearchPath &)
Copies another search path.
FileSearchPath& FileSearchPath::operator= (const String & path)
Uses a string containing a list of pathnames to re-initialise this list.
This search path is cleared and the semicolon- or comma-separated folders in this string are added instead. e.g. "/foo/bar;/foo/moose;/fish/moose"
int FileSearchPath::getNumPaths () const
Returns the number of folders in this search path.
See Also
operator[]
File FileSearchPath::operator[] (int index) const
Returns one of the folders in this search path.
The file returned isn't guaranteed to actually be a valid directory.
See Also
getNumPaths
String FileSearchPath::toString () const
Returns the search path as a semicolon-separated list of directories.
void FileSearchPath::add (const File & directoryToAdd, int insertIndex = -1)
Adds a new directory to the search path.
The new directory is added to the end of the list if the insertIndex parameter is less than zero, otherwise it is inserted at the given index.
bool FileSearchPath::addIfNotAlreadyThere (const File & directoryToAdd)
Adds a new directory to the search path if it's not already in there.
Returns
true if the directory has been added, false otherwise.
void FileSearchPath::remove (int indexToRemove)
Removes a directory from the search path.
void FileSearchPath::addPath (const FileSearchPath &)
Merges another search path into this one.
This will remove any duplicate directories.
void FileSearchPath::removeRedundantPaths ()
Removes any directories that are actually subdirectories of one of the other directories in the search path.
If the search is intended to be recursive, there's no point having nested folders in the search path, because they'll just get searched twice and you'll get duplicate results.
e.g. if the path is "c:\abc\de;c:\abc", this method will simplify it to "c:\abc"
void FileSearchPath::removeNonExistentPaths ()
Removes any directories that don't actually exist.
int FileSearchPath::findChildFiles (Array< File > & results, int whatToLookFor, bool searchRecursively, const String & wildCardPattern = "*") const
Searches the path for a wildcard.
This will search all the directories in the search path in order, adding any matching files to the results array.
Parameters
results an array to append the results to
whatToLookFor a value from the File::TypesOfFileToFind enum, specifying whether to return files, directories, or both.
searchRecursively whether to recursively search the subdirectories too
wildCardPattern a pattern to match against the filenames
Returns
the number of files added to the array
See Also
File::findChildFiles
bool FileSearchPath::isFileInPath (const File & fileToCheck, bool checkRecursively) const
Finds out whether a file is inside one of the path's directories.
This will return true if the specified file is a child of one of the directories specified by this path. Note that this doesn't actually do any searching or check that the files exist - it just looks at the pathnames to work out whether the file would be inside a directory.
Parameters
fileToCheck the file to look for
checkRecursively if true, then this will return true if the file is inside a subfolder of one of the path's directories (at any depth). If false it will only return true if the file is actually a direct child of one of the directories.
See Also
File::isAChildOf
class MemoryMappedFile
Maps a file into virtual memory for easy reading and/or writing.
Public Types
enum AccessMode { readOnly, readWrite }
The read/write flags used when opening a memory mapped file.
Public Member Functions
MemoryMappedFile (const File &file, AccessMode mode, bool exclusive=false)
Opens a file and maps it to an area of virtual memory.
MemoryMappedFile (const File &file, const Range< int64 > &fileRange, AccessMode mode, bool exclusive=false)
Opens a section of a file and maps it to an area of virtual memory.
~MemoryMappedFile ()
Destructor.
void * getData () const noexcept
Returns the address at which this file has been mapped, or a null pointer if the file couldn't be successfully mapped.
size_t getSize () const noexcept
Returns the number of bytes of data that are available for reading or writing.
Range< int64 > getRange () const noexcept
Returns the section of the file at which the mapped memory represents.
Member Enumeration Documentation
enum MemoryMappedFile::AccessMode
The read/write flags used when opening a memory mapped file.
Enumerator
readOnly
Indicates that the memory can only be read.
readWrite
Indicates that the memory can be read and written to - changes that are made will be flushed back to disk at the whim of the OS.
Constructor & Destructor Documentation
MemoryMappedFile::MemoryMappedFile (const File & file, AccessMode mode, bool exclusive = false)
Opens a file and maps it to an area of virtual memory.
The file should already exist, and should already be the size that you want to work with when you call this. If the file is resized after being opened, the behaviour is undefined.
If the file exists and the operation succeeds, the getData() and getSize() methods will return the location and size of the data that can be read or written. Note that the entire file is not read into memory immediately - the OS simply creates a virtual mapping, which will lazily pull the data into memory when blocks are accessed.
If the file can't be opened for some reason, the getData() method will return a null pointer.
If exclusive is false then other apps can also open the same memory mapped file and use this mapping as an effective way of communicating. If exclusive is true then the mapped file will be opened exclusively - preventing other apps to access the file which may improve the performance of accessing the file.
MemoryMappedFile::MemoryMappedFile (const File & file, const Range< int64 > & fileRange, AccessMode mode, bool exclusive = false)
Opens a section of a file and maps it to an area of virtual memory.
The file should already exist, and should already be the size that you want to work with when you call this. If the file is resized after being opened, the behaviour is undefined.
If the file exists and the operation succeeds, the getData() and getSize() methods will return the location and size of the data that can be read or written. Note that the entire file is not read into memory immediately - the OS simply creates a virtual mapping, which will lazily pull the data into memory when blocks are accessed.
If the file can't be opened for some reason, the getData() method will return a null pointer.
NOTE: the start of the actual range used may be rounded-down to a multiple of the OS's page-size, so do not assume that the mapped memory will begin at exactly the position you requested - always use getRange() to check the actual range that is being used.
MemoryMappedFile::~MemoryMappedFile ()
Destructor.
Member Function Documentation
void* MemoryMappedFile::getData () const noexcept
Returns the address at which this file has been mapped, or a null pointer if the file couldn't be successfully mapped.
size_t MemoryMappedFile::getSize () const noexcept
Returns the number of bytes of data that are available for reading or writing.
This will normally be the size of the file.
Range<int64> MemoryMappedFile::getRange () const noexcept
Returns the section of the file at which the mapped memory represents.
class TemporaryFile
Manages a temporary file, which will be deleted when this object is deleted.
This object is intended to be used as a stack based object, using its scope to make sure the temporary file isn't left lying around.
For example:
{
    File myTargetFile ("~/myfile.txt");
    // this will choose a file called something like "~/myfile_temp239348.txt"
    // which definitely doesn't exist at the time the constructor is called.
    TemporaryFile temp (myTargetFile);
    // create a stream to the temporary file, and write some data to it...
    ScopedPointer<FileOutputStream> out (temp.getFile().createOutputStream());
    if (out != nullptr)
    {
        out->write ( ...etc )
        out = nullptr; // (deletes the stream)
        // ..now we've finished writing, this will rename the temp file to
        // make it replace the target file we specified above.
        bool succeeded = temp.overwriteTargetFileWithTemporary();
    }
    // ..and even if something went wrong and our overwrite failed,
    // as the TemporaryFile object goes out of scope here, it'll make sure
    // that the temp file gets deleted.
}
See Also
File, FileOutputStream
Public Types
enum OptionFlags { useHiddenFile = 1, putNumbersInBrackets = 2 }
Public Member Functions
TemporaryFile (const String &suffix=String(), int optionFlags=0)
Creates a randomly-named temporary file in the default temp directory.
TemporaryFile (const File &targetFile, int optionFlags=0)
Creates a temporary file in the same directory as a specified file.
TemporaryFile (const File &targetFile, const File &temporaryFile)
Creates a temporary file using an explicit filename.
~TemporaryFile ()
Destructor.
const File & getFile () const noexcept
Returns the temporary file.
const File & getTargetFile () const noexcept
Returns the target file that was specified in the constructor.
bool overwriteTargetFileWithTemporary () const
Tries to move the temporary file to overwrite the target file that was specified in the constructor.
bool deleteTemporaryFile () const
Attempts to delete the temporary file, if it exists.
Member Enumeration Documentation
enum TemporaryFile::OptionFlags
Enumerator
useHiddenFile
Indicates that the temporary file should be hidden - i.e.
its name should start with a dot.
putNumbersInBrackets
Indicates that when numbers are appended to make sure the file is unique, they should go in brackets rather than just being appended (see File::getNonexistentSibling())
Constructor & Destructor Documentation
TemporaryFile::TemporaryFile (const String & suffix = String(), int optionFlags = 0)
Creates a randomly-named temporary file in the default temp directory.
Parameters
suffix a file suffix to use for the file
optionFlags a combination of the values listed in the OptionFlags enum The file will not be created until you write to it. And remember that when this object is deleted, the file will also be deleted!
TemporaryFile::TemporaryFile (const File & targetFile, int optionFlags = 0)
Creates a temporary file in the same directory as a specified file.
This is useful if you have a file that you want to overwrite, but don't want to harm the original file if the write operation fails. You can use this to create a temporary file next to the target file, then write to the temporary file, and finally use overwriteTargetFileWithTemporary() to replace the target file with the one you've just written.
This class won't create any files until you actually write to them. And remember that when this object is deleted, the temporary file will also be deleted!
Parameters
targetFile the file that you intend to overwrite - the temporary file will be created in the same directory as this
optionFlags a combination of the values listed in the OptionFlags enum
TemporaryFile::TemporaryFile (const File & targetFile, const File & temporaryFile)
Creates a temporary file using an explicit filename.
The other constructors are a better choice than this one, unless for some reason you need to explicitly specify the temporary file you want to use.
Parameters
targetFile the file that you intend to overwrite
temporaryFile the temporary file to be used
TemporaryFile::~TemporaryFile ()
Destructor.
When this object is deleted it will make sure that its temporary file is also deleted! If the operation fails, it'll throw an assertion in debug mode.
Member Function Documentation
const File& TemporaryFile::getFile () const noexcept
Returns the temporary file.
const File& TemporaryFile::getTargetFile () const noexcept
Returns the target file that was specified in the constructor.
bool TemporaryFile::overwriteTargetFileWithTemporary () const
Tries to move the temporary file to overwrite the target file that was specified in the constructor.
If you used the constructor that specified a target file, this will attempt to replace that file with the temporary one.
Before calling this, make sure:
that you've actually written to the temporary file
that you've closed any open streams that you were using to write to it
and that you don't have any streams open to the target file, which would prevent it being overwritten
If the file move succeeds, this returns false, and the temporary file will have disappeared. If it fails, the temporary file will probably still exist, but will be deleted when this object is destroyed.
bool TemporaryFile::deleteTemporaryFile () const
Attempts to delete the temporary file, if it exists.
Returns
true if the file is successfully deleted (or if it didn't exist).
class WildcardFileFilter
A type of FileFilter that works by wildcard pattern matching.
This filter only allows files that match one of the specified patterns, but allows all directories through.
See Also
FileFilter, DirectoryContentsList, FileListComponent, FileBrowserComponent
Public Member Functions
WildcardFileFilter (const String &fileWildcardPatterns, const String &directoryWildcardPatterns, const String &description)
Creates a wildcard filter for one or more patterns.
~WildcardFileFilter ()
Destructor.
bool isFileSuitable (const File &file) const override
Returns true if the filename matches one of the patterns specified.
bool isDirectorySuitable (const File &file) const override
This always returns true.
Public Member Functions inherited from FileFilter
FileFilter (const String &filterDescription)
Creates a filter with the given description.
virtual ~FileFilter ()
Destructor.
const String & getDescription () const noexcept
Returns the description that the filter was created with.
Additional Inherited Members
Protected Attributes inherited from FileFilter
String description
Constructor & Destructor Documentation
WildcardFileFilter::WildcardFileFilter (const String & fileWildcardPatterns, const String & directoryWildcardPatterns, const String & description)
Creates a wildcard filter for one or more patterns.
The wildcardPatterns parameter is a comma or semicolon-delimited set of patterns, e.g. "*.wav;*.aiff" would look for files ending in either .wav or .aiff.
Passing an empty string as a pattern will fail to match anything, so by leaving either the file or directory pattern parameter empty means you can control whether files or directories are found.
The description is a name to show the user in a list of possible patterns, so for the wav/aiff example, your description might be "audio files".
WildcardFileFilter::~WildcardFileFilter ()
Destructor.
Member Function Documentation
bool WildcardFileFilter::isFileSuitable (const File & file) const override virtual
Returns true if the filename matches one of the patterns specified.
Implements FileFilter.
bool WildcardFileFilter::isDirectorySuitable (const File & file) const override virtual
This always returns true.
Implements FileFilter.