JUCE: memory
memory
juce_core
Classes
class Atomic< Type >
Simple class to hold a primitive value and perform atomic operations on it.
class ByteOrder
Contains static methods for converting the byte order between different endiannesses.
struct ContainerDeletePolicy< ObjectType >
Used by container classes as an indirect way to delete an object of a particular type.
class HeapBlock< ElementType, throwOnFailure >
Very simple container class to hold a pointer to some data on the heap.
class LeakedObjectDetector< OwnerClass >
Embedding an instance of this class inside another class can be used as a low-overhead way of detecting leaked instances.
class ScopedAutoReleasePool
A handy C++ wrapper that creates and deletes an NSAutoreleasePool object using RAII.
class MemoryBlock
A class to hold a resizable block of raw data.
class OptionalScopedPointer< ObjectType >
Holds a pointer to an object which can optionally be deleted when this pointer goes out of scope.
class ReferenceCountedObject
A base class which provides methods for reference-counting.
class SingleThreadedReferenceCountedObject
Adds reference-counting to an object.
class ReferenceCountedObjectPtr< ReferenceCountedObjectClass >
A smart-pointer class which points to a reference-counted object.
class ScopedPointer< ObjectType >
This class holds a pointer which is automatically deleted when this object goes out of scope.
class SharedResourcePointer< SharedObjectType >
A smart-pointer that automatically creates and manages the lifetime of a shared static instance of a class.
class WeakReference< ObjectType, ReferenceCountingType >
This class acts as a pointer which will automatically become null if the object to which it points is deleted.
Macros
#define JUCE_LEAK_DETECTOR(OwnerClass)
This macro lets you embed a leak-detecting object inside a class.
#define JUCE_AUTORELEASEPOOL @autoreleasepool
A macro that can be used to easily declare a local ScopedAutoReleasePool object for RAII-based obj-C autoreleasing.
#define juce_UseDebuggingNewOperator
(Deprecated) This was a Windows-specific way of checking for object leaks - now please use the JUCE_LEAK_DETECTOR instead.
#define juce_DeclareSingleton(classname, doNotRecreateAfterDeletion)
Macro to declare member variables and methods for a singleton class.
#define juce_ImplementSingleton(classname)
This is a counterpart to the juce_DeclareSingleton macro.
#define juce_DeclareSingleton_SingleThreaded(classname, doNotRecreateAfterDeletion)
Macro to declare member variables and methods for a singleton class.
#define juce_DeclareSingleton_SingleThreaded_Minimal(classname)
Macro to declare member variables and methods for a singleton class.
#define juce_ImplementSingleton_SingleThreaded(classname)
This is a counterpart to the juce_DeclareSingleton_SingleThreaded macro.
Functions
void zeromem (void *memory, size_t numBytes) noexcept
Fills a block of memory with zeros.
template<typename Type >
void zerostruct (Type &structure) noexcept
Overwrites a structure or object with zeros.
template<typename Type >
void deleteAndZero (Type &pointer)
Delete an object pointer, and sets the pointer to null.
template<typename Type , typename IntegerType >
Type * addBytesToPointer (Type *basePointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result.
template<typename Type , typename IntegerType >
Type * snapPointerToAlignment (Type *basePointer, IntegerType alignmentBytes) noexcept
A handy function to round up a pointer to the nearest multiple of a given number of bytes.
template<typename Type1 , typename Type2 >
int getAddressDifference (Type1 *pointer1, Type2 *pointer2) noexcept
A handy function which returns the difference between any two pointers, in bytes.
template<class Type >
Type * createCopyIfNotNull (const Type *objectToCopy)
If a pointer is non-null, this returns a new copy of the object that it points to, or safely returns nullptr if the pointer is null.
template<typename Type >
Type readUnaligned (const void *srcPtr) noexcept
A handy function to read un-aligned memory without a performance penalty or bus-error.
template<typename Type >
void writeUnaligned (void *dstPtr, Type value) noexcept
A handy function to write un-aligned memory without a performance penalty or bus-error.
template<typename ReferenceCountedObjectClass >
bool operator== (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object1, ReferenceCountedObjectClass *const object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass >
bool operator== (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass >
bool operator== (ReferenceCountedObjectClass *object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass >
bool operator!= (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object1, const ReferenceCountedObjectClass *object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass >
bool operator!= (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass >
bool operator!= (ReferenceCountedObjectClass *object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > &object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<class ObjectType >
bool operator== (const ScopedPointer< ObjectType > &pointer1, ObjectType *const pointer2) noexcept
Compares a ScopedPointer with another pointer.
template<class ObjectType >
bool operator!= (const ScopedPointer< ObjectType > &pointer1, ObjectType *const pointer2) noexcept
Compares a ScopedPointer with another pointer.
static uint16 ByteOrder::swap (uint16 value) noexcept
Swaps the upper and lower bytes of a 16-bit integer.
static uint32 ByteOrder::swap (uint32 value) noexcept
Reverses the order of the 4 bytes in a 32-bit integer.
static uint64 ByteOrder::swap (uint64 value) noexcept
Reverses the order of the 8 bytes in a 64-bit integer.
static uint16 ByteOrder::swapIfBigEndian (uint16 value) noexcept
Swaps the byte order of a 16-bit unsigned int if the CPU is big-endian.
static uint32 ByteOrder::swapIfBigEndian (uint32 value) noexcept
Swaps the byte order of a 32-bit unsigned int if the CPU is big-endian.
static uint64 ByteOrder::swapIfBigEndian (uint64 value) noexcept
Swaps the byte order of a 64-bit unsigned int if the CPU is big-endian.
static int16 ByteOrder::swapIfBigEndian (int16 value) noexcept
Swaps the byte order of a 16-bit signed int if the CPU is big-endian.
static int32 ByteOrder::swapIfBigEndian (int32 value) noexcept
Swaps the byte order of a 32-bit signed int if the CPU is big-endian.
static int64 ByteOrder::swapIfBigEndian (int64 value) noexcept
Swaps the byte order of a 64-bit signed int if the CPU is big-endian.
static float ByteOrder::swapIfBigEndian (float value) noexcept
Swaps the byte order of a 32-bit float if the CPU is big-endian.
static double ByteOrder::swapIfBigEndian (double value) noexcept
Swaps the byte order of a 64-bit float if the CPU is big-endian.
static uint16 ByteOrder::swapIfLittleEndian (uint16 value) noexcept
Swaps the byte order of a 16-bit unsigned int if the CPU is little-endian.
static uint32 ByteOrder::swapIfLittleEndian (uint32 value) noexcept
Swaps the byte order of a 32-bit unsigned int if the CPU is little-endian.
static uint64 ByteOrder::swapIfLittleEndian (uint64 value) noexcept
Swaps the byte order of a 64-bit unsigned int if the CPU is little-endian.
static int16 ByteOrder::swapIfLittleEndian (int16 value) noexcept
Swaps the byte order of a 16-bit signed int if the CPU is little-endian.
static int32 ByteOrder::swapIfLittleEndian (int32 value) noexcept
Swaps the byte order of a 32-bit signed int if the CPU is little-endian.
static int64 ByteOrder::swapIfLittleEndian (int64 value) noexcept
Swaps the byte order of a 64-bit signed int if the CPU is little-endian.
static float ByteOrder::swapIfLittleEndian (float value) noexcept
Swaps the byte order of a 32-bit float if the CPU is little-endian.
static double ByteOrder::swapIfLittleEndian (double value) noexcept
Swaps the byte order of a 64-bit float if the CPU is little-endian.
static uint32 ByteOrder::littleEndianInt (const void *bytes) noexcept
Turns 4 bytes into a little-endian integer.
static uint64 ByteOrder::littleEndianInt64 (const void *bytes) noexcept
Turns 8 bytes into a little-endian integer.
static uint16 ByteOrder::littleEndianShort (const void *bytes) noexcept
Turns 2 bytes into a little-endian integer.
static uint32 ByteOrder::bigEndianInt (const void *bytes) noexcept
Turns 4 bytes into a big-endian integer.
static uint64 ByteOrder::bigEndianInt64 (const void *bytes) noexcept
Turns 8 bytes into a big-endian integer.
static uint16 ByteOrder::bigEndianShort (const void *bytes) noexcept
Turns 2 bytes into a big-endian integer.
static bool ByteOrder::isBigEndian () noexcept
Returns true if the current CPU is big-endian.
static int ByteOrder::littleEndian24Bit (const void *bytes) noexcept
Converts 3 little-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
static int ByteOrder::bigEndian24Bit (const void *bytes) noexcept
Converts 3 big-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
static void ByteOrder::littleEndian24BitToChars (int value, void *destBytes) noexcept
Copies a 24-bit number to 3 little-endian bytes.
static void ByteOrder::bigEndian24BitToChars (int value, void *destBytes) noexcept
Copies a 24-bit number to 3 big-endian bytes.
Detailed Description
Class Documentation
class Atomic
template<typename Type>
class Atomic< Type >
Simple class to hold a primitive value and perform atomic operations on it.
The type used must be a 32 or 64 bit primitive, like an int, pointer, etc. There are methods to perform most of the basic atomic operations.
Inherits AtomicBase< Type >.
Public Types
typedef AtomicBase< Type >
::DiffType DiffType
Resulting type when subtracting the underlying Type.
Public Member Functions
Atomic () noexcept
Creates a new value, initialised to zero.
Atomic (const Type initialValue) noexcept
Creates a new value, with a given initial value.
Atomic (const Atomic &other) noexcept
Copies another value (atomically).
~Atomic () noexcept
Destructor.
Type get () const noexcept
Atomically reads and returns the current value.
Atomic & operator= (const Atomic &other) noexcept
Copies another value into this one (atomically).
Atomic & operator= (const Type newValue) noexcept
Copies another value into this one (atomically).
void set (Type newValue) noexcept
Atomically sets the current value.
Type exchange (Type v) noexcept
Atomically sets the current value, returning the value that was replaced.
Type operator+= (DiffType amountToAdd) noexcept
Atomically adds a number to this value, returning the new value.
Type operator-= (DiffType amountToSubtract) noexcept
Atomically subtracts a number from this value, returning the new value.
Type operator++ () noexcept
Atomically increments this value, returning the new value.
Type operator-- () noexcept
Atomically decrements this value, returning the new value.
bool compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
Type compareAndSetValue (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
Static Public Member Functions
static void memoryBarrier () noexcept
Implements a memory read/write barrier.
Member Typedef Documentation
template<typename Type> typedef AtomicBase<Type>::DiffType Atomic< Type >::DiffType
Resulting type when subtracting the underlying Type.
Constructor & Destructor Documentation
template<typename Type> Atomic< Type >::Atomic () noexcept
Creates a new value, initialised to zero.
template<typename Type> Atomic< Type >::Atomic (const Type initialValue) explicit noexcept
Creates a new value, with a given initial value.
template<typename Type> Atomic< Type >::Atomic (const Atomic< Type > & other) noexcept
Copies another value (atomically).
template<typename Type> Atomic< Type >::~Atomic () noexcept
Destructor.
Member Function Documentation
template<typename Type> Type Atomic< Type >::get () const noexcept
Atomically reads and returns the current value.
Referenced by ThreadLocalValue< Type >::get(), ThreadLocalValue< Type >::releaseCurrentThreadStorage(), and ThreadLocalValue< Type >::~ThreadLocalValue().
template<typename Type> Atomic& Atomic< Type >::operator= (const Atomic< Type > & other) noexcept
Copies another value into this one (atomically).
template<typename Type> Atomic& Atomic< Type >::operator= (const Type newValue) noexcept
Copies another value into this one (atomically).
template<typename Type> void Atomic< Type >::set (Type newValue) noexcept
Atomically sets the current value.
template<typename Type> Type Atomic< Type >::exchange (Type v) noexcept
Atomically sets the current value, returning the value that was replaced.
Referenced by Atomic< Thread::ThreadID >::set().
template<typename Type> Type Atomic< Type >::operator+= (DiffType amountToAdd) noexcept
Atomically adds a number to this value, returning the new value.
template<typename Type> Type Atomic< Type >::operator-= (DiffType amountToSubtract) noexcept
Atomically subtracts a number from this value, returning the new value.
template<typename Type> Type Atomic< Type >::operator++ () noexcept
Atomically increments this value, returning the new value.
template<typename Type> Type Atomic< Type >::operator-- () noexcept
Atomically decrements this value, returning the new value.
template<typename Type> bool Atomic< Type >::compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
bool compareAndSetBool (Type newValue, Type valueToCompare)
{
    if (get() == valueToCompare)
    {
        set (newValue);
        return true;
    }
    return false;
}
Returns
true if the comparison was true and the value was replaced; false if the comparison failed and the value was left unchanged.
See Also
compareAndSetValue
Referenced by ThreadLocalValue< Type >::get().
template<typename Type> Type Atomic< Type >::compareAndSetValue (Type newValue, Type valueToCompare) noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
Type compareAndSetValue (Type newValue, Type valueToCompare)
{
    Type oldValue = get();
    if (oldValue == valueToCompare)
        set (newValue);
    return oldValue;
}
Returns
the old value before it was changed.
See Also
compareAndSetBool
template<typename Type> static void Atomic< Type >::memoryBarrier () static noexcept
Implements a memory read/write barrier.
class ByteOrder
Contains static methods for converting the byte order between different endiannesses.
Static Public Member Functions
static uint16 swap (uint16 value) noexcept
Swaps the upper and lower bytes of a 16-bit integer.
static uint32 swap (uint32 value) noexcept
Reverses the order of the 4 bytes in a 32-bit integer.
static uint64 swap (uint64 value) noexcept
Reverses the order of the 8 bytes in a 64-bit integer.
static uint16 swapIfBigEndian (uint16 value) noexcept
Swaps the byte order of a 16-bit unsigned int if the CPU is big-endian.
static uint32 swapIfBigEndian (uint32 value) noexcept
Swaps the byte order of a 32-bit unsigned int if the CPU is big-endian.
static uint64 swapIfBigEndian (uint64 value) noexcept
Swaps the byte order of a 64-bit unsigned int if the CPU is big-endian.
static int16 swapIfBigEndian (int16 value) noexcept
Swaps the byte order of a 16-bit signed int if the CPU is big-endian.
static int32 swapIfBigEndian (int32 value) noexcept
Swaps the byte order of a 32-bit signed int if the CPU is big-endian.
static int64 swapIfBigEndian (int64 value) noexcept
Swaps the byte order of a 64-bit signed int if the CPU is big-endian.
static float swapIfBigEndian (float value) noexcept
Swaps the byte order of a 32-bit float if the CPU is big-endian.
static double swapIfBigEndian (double value) noexcept
Swaps the byte order of a 64-bit float if the CPU is big-endian.
static uint16 swapIfLittleEndian (uint16 value) noexcept
Swaps the byte order of a 16-bit unsigned int if the CPU is little-endian.
static uint32 swapIfLittleEndian (uint32 value) noexcept
Swaps the byte order of a 32-bit unsigned int if the CPU is little-endian.
static uint64 swapIfLittleEndian (uint64 value) noexcept
Swaps the byte order of a 64-bit unsigned int if the CPU is little-endian.
static int16 swapIfLittleEndian (int16 value) noexcept
Swaps the byte order of a 16-bit signed int if the CPU is little-endian.
static int32 swapIfLittleEndian (int32 value) noexcept
Swaps the byte order of a 32-bit signed int if the CPU is little-endian.
static int64 swapIfLittleEndian (int64 value) noexcept
Swaps the byte order of a 64-bit signed int if the CPU is little-endian.
static float swapIfLittleEndian (float value) noexcept
Swaps the byte order of a 32-bit float if the CPU is little-endian.
static double swapIfLittleEndian (double value) noexcept
Swaps the byte order of a 64-bit float if the CPU is little-endian.
static uint32 littleEndianInt (const void *bytes) noexcept
Turns 4 bytes into a little-endian integer.
static uint64 littleEndianInt64 (const void *bytes) noexcept
Turns 8 bytes into a little-endian integer.
static uint16 littleEndianShort (const void *bytes) noexcept
Turns 2 bytes into a little-endian integer.
static uint32 bigEndianInt (const void *bytes) noexcept
Turns 4 bytes into a big-endian integer.
static uint64 bigEndianInt64 (const void *bytes) noexcept
Turns 8 bytes into a big-endian integer.
static uint16 bigEndianShort (const void *bytes) noexcept
Turns 2 bytes into a big-endian integer.
static int littleEndian24Bit (const void *bytes) noexcept
Converts 3 little-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
static int bigEndian24Bit (const void *bytes) noexcept
Converts 3 big-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
static void littleEndian24BitToChars (int value, void *destBytes) noexcept
Copies a 24-bit number to 3 little-endian bytes.
static void bigEndian24BitToChars (int value, void *destBytes) noexcept
Copies a 24-bit number to 3 big-endian bytes.
static bool isBigEndian () noexcept
Returns true if the current CPU is big-endian.
struct ContainerDeletePolicy
template<typename ObjectType>
struct ContainerDeletePolicy< ObjectType >
Used by container classes as an indirect way to delete an object of a particular type.
The generic implementation of this class simply calls 'delete', but you can create a specialised version of it for a particular class if you need to delete that type of object in a more appropriate way.
See Also
ScopedPointer, OwnedArray
Static Public Member Functions
static void destroy (ObjectType *object)
Member Function Documentation
template<typename ObjectType > static void ContainerDeletePolicy< ObjectType >::destroy (ObjectType * object) static
References ignoreUnused().
Referenced by ScopedPointer< ListViewport >::operator=(), OwnedArray< MidiBuffer >::removeRange(), and ScopedPointer< ListViewport >::~ScopedPointer().
class HeapBlock
template<class ElementType, bool throwOnFailure = false>
class HeapBlock< ElementType, throwOnFailure >
Very simple container class to hold a pointer to some data on the heap.
When you need to allocate some heap storage for something, always try to use this class instead of allocating the memory directly using malloc/free.
A HeapBlock<char> object can be treated in pretty much exactly the same way as an char*, but as long as you allocate it on the stack or as a class member, it's almost impossible for it to leak memory.
It also makes your code much more concise and readable than doing the same thing using direct allocations,
E.g. instead of this:
int* temp = (int*) malloc (1024 * sizeof (int));
memcpy (temp, xyz, 1024 * sizeof (int));
free (temp);
temp = (int*) calloc (2048 * sizeof (int));
temp[0] = 1234;
memcpy (foobar, temp, 2048 * sizeof (int));
free (temp);
..you could just write this:
HeapBlock<int> temp (1024);
memcpy (temp, xyz, 1024 * sizeof (int));
temp.calloc (2048);
temp[0] = 1234;
memcpy (foobar, temp, 2048 * sizeof (int));
The class is extremely lightweight, containing only a pointer to the data, and exposes malloc/realloc/calloc/free methods that do the same jobs as their less object-oriented counterparts. Despite adding safety, you probably won't sacrifice any performance by using this in place of normal pointers.
The throwOnFailure template parameter can be set to true if you'd like the class to throw a std::bad_alloc exception when an allocation fails. If this is false, then a failed allocation will just leave the heapblock with a null pointer (assuming that the system's malloc() function doesn't throw).
See Also
Array, OwnedArray, MemoryBlock
Public Types
typedef ElementType Type
This typedef can be used to get the type of the heapblock's elements.
Public Member Functions
HeapBlock () noexcept
Creates a HeapBlock which is initially just a null pointer.
HeapBlock (const size_t numElements)
Creates a HeapBlock containing a number of elements.
HeapBlock (const size_t numElements, const bool initialiseToZero)
Creates a HeapBlock containing a number of elements.
~HeapBlock ()
Destructor.
HeapBlock (HeapBlock &&other) noexcept
Move constructor.
HeapBlock & operator= (HeapBlock &&other) noexcept
Move assignment operator.
operator ElementType * () const noexcept
Returns a raw pointer to the allocated data.
ElementType * getData () const noexcept
Returns a raw pointer to the allocated data.
operator void * () const noexcept
Returns a void pointer to the allocated data.
operator const void * () const noexcept
Returns a void pointer to the allocated data.
ElementType * operator-> () const noexcept
Lets you use indirect calls to the first element in the array.
template<typename IndexType >
ElementType & operator[] (IndexType index) const noexcept
Returns a reference to one of the data elements.
template<typename IndexType >
ElementType * operator+ (IndexType index) const noexcept
Returns a pointer to a data element at an offset from the start of the array.
bool operator== (const ElementType *const otherPointer) const noexcept
Compares the pointer with another pointer.
bool operator!= (const ElementType *const otherPointer) const noexcept
Compares the pointer with another pointer.
void malloc (const size_t newNumElements, const size_t elementSize=sizeof(ElementType))
Allocates a specified amount of memory.
void calloc (const size_t newNumElements, const size_t elementSize=sizeof(ElementType))
Allocates a specified amount of memory and clears it.
void allocate (const size_t newNumElements, bool initialiseToZero)
Allocates a specified amount of memory and optionally clears it.
void realloc (const size_t newNumElements, const size_t elementSize=sizeof(ElementType))
Re-allocates a specified amount of memory.
void free () noexcept
Frees any currently-allocated data.
template<bool otherBlockThrows>
void swapWith (HeapBlock< ElementType, otherBlockThrows > &other) noexcept
Swaps this object's data with the data of another HeapBlock.
void clear (size_t numElements) noexcept
This fills the block with zeros, up to the number of elements specified.
Member Typedef Documentation
template<class ElementType, bool throwOnFailure = false> typedef ElementType HeapBlock< ElementType, throwOnFailure >::Type
This typedef can be used to get the type of the heapblock's elements.
Constructor & Destructor Documentation
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::HeapBlock () noexcept
Creates a HeapBlock which is initially just a null pointer.
After creation, you can resize the array using the malloc(), calloc(), or realloc() methods.
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::HeapBlock (const size_t numElements) explicit
Creates a HeapBlock containing a number of elements.
The contents of the block are undefined, as it will have been created by a malloc call.
If you want an array of zero values, you can use the calloc() method or the other constructor that takes an InitialisationState parameter.
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::HeapBlock (const size_t numElements, const bool initialiseToZero)
Creates a HeapBlock containing a number of elements.
The initialiseToZero parameter determines whether the new memory should be cleared, or left uninitialised.
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::~HeapBlock ()
Destructor.
This will free the data, if any has been allocated.
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::HeapBlock (HeapBlock< ElementType, throwOnFailure > && other) noexcept
Move constructor.
Member Function Documentation
template<class ElementType, bool throwOnFailure = false> HeapBlock& HeapBlock< ElementType, throwOnFailure >::operator= (HeapBlock< ElementType, throwOnFailure > && other) noexcept
Move assignment operator.
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::operator ElementType * () const noexcept
Returns a raw pointer to the allocated data.
This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
template<class ElementType, bool throwOnFailure = false> ElementType* HeapBlock< ElementType, throwOnFailure >::getData () const noexcept
Returns a raw pointer to the allocated data.
This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
Referenced by ReferenceCountedArray< AudioProcessorGraph::Node >::addOrReplaceSorted(), ReferenceCountedArray< AudioProcessorGraph::Node >::addSorted(), OwnedArray< MidiBuffer >::addSorted(), OwnedArray< MidiBuffer >::contains(), ReferenceCountedArray< AudioProcessorGraph::Node >::contains(), SpeakerMappings::VstSpeakerConfigurationHolder::get(), OwnedArray< MidiBuffer >::indexOf(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOf(), OwnedArray< MidiBuffer >::removeObject(), FIR::Filter< SampleType >::reset(), AudioUnitHelpers::CoreAudioBufferList::reset(), AudioBuffer< float >::setSize(), ReferenceCountedArray< AudioProcessorGraph::Node >::sort(), and OwnedArray< MidiBuffer >::sort().
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::operator void * () const noexcept
Returns a void pointer to the allocated data.
This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
template<class ElementType, bool throwOnFailure = false> HeapBlock< ElementType, throwOnFailure >::operator const void * () const noexcept
Returns a void pointer to the allocated data.
This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
template<class ElementType, bool throwOnFailure = false> ElementType* HeapBlock< ElementType, throwOnFailure >::operator-> () const noexcept
Lets you use indirect calls to the first element in the array.
Obviously this will cause problems if the array hasn't been initialised, because it'll be referencing a null pointer.
template<class ElementType, bool throwOnFailure = false> template<typename IndexType > ElementType& HeapBlock< ElementType, throwOnFailure >::operator[] (IndexType index) const noexcept
Returns a reference to one of the data elements.
Obviously there's no bounds-checking here, as this object is just a dumb pointer and has no idea of the size it currently has allocated.
template<class ElementType, bool throwOnFailure = false> template<typename IndexType > ElementType* HeapBlock< ElementType, throwOnFailure >::operator+ (IndexType index) const noexcept
Returns a pointer to a data element at an offset from the start of the array.
This is the same as doing pointer arithmetic on the raw pointer itself.
template<class ElementType, bool throwOnFailure = false> bool HeapBlock< ElementType, throwOnFailure >::operator== (const ElementType *const otherPointer) const noexcept
Compares the pointer with another pointer.
This can be handy for checking whether this is a null pointer.
template<class ElementType, bool throwOnFailure = false> bool HeapBlock< ElementType, throwOnFailure >::operator!= (const ElementType *const otherPointer) const noexcept
Compares the pointer with another pointer.
This can be handy for checking whether this is a null pointer.
template<class ElementType, bool throwOnFailure = false> void HeapBlock< ElementType, throwOnFailure >::malloc (const size_t newNumElements, const size_t elementSize = sizeof (ElementType))
Allocates a specified amount of memory.
This uses the normal malloc to allocate an amount of memory for this object. Any previously allocated memory will be freed by this method.
The number of bytes allocated will be (newNumElements * elementSize). Normally you wouldn't need to specify the second parameter, but it can be handy if you need to allocate a size in bytes rather than in terms of the number of elements.
The data that is allocated will be freed when this object is deleted, or when you call free() or any of the allocation methods.
Referenced by FIR::Filter< SampleType >::reset().
template<class ElementType, bool throwOnFailure = false> void HeapBlock< ElementType, throwOnFailure >::calloc (const size_t newNumElements, const size_t elementSize = sizeof (ElementType))
Allocates a specified amount of memory and clears it.
This does the same job as the malloc() method, but clears the memory that it allocates.
Referenced by AudioUnitHelpers::CoreAudioBufferList::prepare().
template<class ElementType, bool throwOnFailure = false> void HeapBlock< ElementType, throwOnFailure >::allocate (const size_t newNumElements, bool initialiseToZero)
Allocates a specified amount of memory and optionally clears it.
This does the same job as either malloc() or calloc(), depending on the initialiseToZero parameter.
Referenced by AudioBuffer< float >::setSize().
template<class ElementType, bool throwOnFailure = false> void HeapBlock< ElementType, throwOnFailure >::realloc (const size_t newNumElements, const size_t elementSize = sizeof (ElementType))
Re-allocates a specified amount of memory.
The semantics of this method are the same as malloc() and calloc(), but it uses realloc() to keep as much of the existing data as possible.
Referenced by ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::setAllocatedSize().
template<class ElementType, bool throwOnFailure = false> void HeapBlock< ElementType, throwOnFailure >::free () noexcept
Frees any currently-allocated data.
This will free the data and reset this object to be a null pointer.
Referenced by AudioUnitHelpers::ChannelRemapper::release(), AudioUnitHelpers::CoreAudioBufferList::release(), ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::setAllocatedSize(), and AudioBuffer< float >::setDataToReferTo().
template<class ElementType, bool throwOnFailure = false> template<bool otherBlockThrows> void HeapBlock< ElementType, throwOnFailure >::swapWith (HeapBlock< ElementType, otherBlockThrows > & other) noexcept
Swaps this object's data with the data of another HeapBlock.
The two objects simply exchange their data pointers.
Referenced by AudioBuffer< float >::setSize(), and ArrayAllocationBase< ProgressBar *, DummyCriticalSection >::swapWith().
template<class ElementType, bool throwOnFailure = false> void HeapBlock< ElementType, throwOnFailure >::clear (size_t numElements) noexcept
This fills the block with zeros, up to the number of elements specified.
Since the block has no way of knowing its own size, you must make sure that the number of elements you specify doesn't exceed the allocated size.
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::operator=(), and AudioBuffer< float >::setSize().
class LeakedObjectDetector
template<class OwnerClass>
class LeakedObjectDetector< OwnerClass >
Embedding an instance of this class inside another class can be used as a low-overhead way of detecting leaked instances.
This class keeps an internal static count of the number of instances that are active, so that when the app is shutdown and the static destructors are called, it can check whether there are any left-over instances that may have been leaked.
To use it, use the JUCE_LEAK_DETECTOR macro as a simple way to put one in your class declaration. Have a look through the juce codebase for examples, it's used in most of the classes.
Public Member Functions
LeakedObjectDetector () noexcept
LeakedObjectDetector (const LeakedObjectDetector &) noexcept
~LeakedObjectDetector ()
Constructor & Destructor Documentation
template<class OwnerClass > LeakedObjectDetector< OwnerClass >::LeakedObjectDetector () noexcept
template<class OwnerClass > LeakedObjectDetector< OwnerClass >::LeakedObjectDetector (const LeakedObjectDetector< OwnerClass > &) noexcept
template<class OwnerClass > LeakedObjectDetector< OwnerClass >::~LeakedObjectDetector ()
References DBG, and jassertfalse.
class ScopedAutoReleasePool
A handy C++ wrapper that creates and deletes an NSAutoreleasePool object using RAII.
You should use the JUCE_AUTORELEASEPOOL macro to create a local auto-release pool on the stack.
Public Member Functions
ScopedAutoReleasePool ()
~ScopedAutoReleasePool ()
Constructor & Destructor Documentation
ScopedAutoReleasePool::ScopedAutoReleasePool ()
ScopedAutoReleasePool::~ScopedAutoReleasePool ()
class MemoryBlock
A class to hold a resizable block of raw data.
Public Member Functions
MemoryBlock () noexcept
Create an uninitialised block with 0 size.
MemoryBlock (const size_t initialSize, bool initialiseToZero=false)
Creates a memory block with a given initial size.
MemoryBlock (const MemoryBlock &)
Creates a copy of another memory block.
MemoryBlock (const void *dataToInitialiseFrom, size_t sizeInBytes)
Creates a memory block using a copy of a block of data.
~MemoryBlock () noexcept
Destructor.
MemoryBlock & operator= (const MemoryBlock &)
Copies another memory block onto this one.
MemoryBlock (MemoryBlock &&) noexcept
Move constructor.
MemoryBlock & operator= (MemoryBlock &&) noexcept
Move assignment operator.
bool operator== (const MemoryBlock &other) const noexcept
Compares two memory blocks.
bool operator!= (const MemoryBlock &other) const noexcept
Compares two memory blocks.
bool matches (const void *data, size_t dataSize) const noexcept
Returns true if the data in this MemoryBlock matches the raw bytes passed-in.
void * getData () const noexcept
Returns a void pointer to the data.
template<typename Type >
char & operator[] (const Type offset) const noexcept
Returns a byte from the memory block.
char * begin () const noexcept
Returns an iterator for the data.
char * end () const noexcept
Returns an end-iterator for the data.
size_t getSize () const noexcept
Returns the block's current allocated size, in bytes.
void setSize (const size_t newSize, bool initialiseNewSpaceToZero=false)
Resizes the memory block.
void ensureSize (const size_t minimumSize, bool initialiseNewSpaceToZero=false)
Increases the block's size only if it's smaller than a given size.
void reset ()
Frees all the blocks data, setting its size to 0.
void fillWith (uint8 valueToUse) noexcept
Fills the entire memory block with a repeated byte value.
void append (const void *data, size_t numBytes)
Adds another block of data to the end of this one.
void replaceWith (const void *data, size_t numBytes)
Resizes this block to the given size and fills its contents from the supplied buffer.
void insert (const void *dataToInsert, size_t numBytesToInsert, size_t insertPosition)
Inserts some data into the block.
void removeSection (size_t startByte, size_t numBytesToRemove)
Chops out a section of the block.
void copyFrom (const void *srcData, int destinationOffset, size_t numBytes) noexcept
Copies data into this MemoryBlock from a memory address.
void copyTo (void *destData, int sourceOffset, size_t numBytes) const noexcept
Copies data from this MemoryBlock to a memory address.
void swapWith (MemoryBlock &other) noexcept
Exchanges the contents of this and another memory block.
String toString () const
Attempts to parse the contents of the block as a zero-terminated UTF8 string.
void loadFromHexString (StringRef sourceHexString)
Parses a string of hexadecimal numbers and writes this data into the memory block.
void setBitRange (size_t bitRangeStart, size_t numBits, int binaryNumberToApply) noexcept
Sets a number of bits in the memory block, treating it as a long binary sequence.
int getBitRange (size_t bitRangeStart, size_t numBitsToRead) const noexcept
Reads a number of bits from the memory block, treating it as one long binary sequence.
String toBase64Encoding () const
Returns a string of characters in a JUCE-specific text encoding that represents the binary contents of this block.
bool fromBase64Encoding (StringRef encodedString)
Takes a string created by MemoryBlock::toBase64Encoding() and extracts the original data.
Constructor & Destructor Documentation
MemoryBlock::MemoryBlock () noexcept
Create an uninitialised block with 0 size.
MemoryBlock::MemoryBlock (const size_t initialSize, bool initialiseToZero = false)
Creates a memory block with a given initial size.
Parameters
initialSize the size of block to create
initialiseToZero whether to clear the memory or just leave it uninitialised
MemoryBlock::MemoryBlock (const MemoryBlock &)
Creates a copy of another memory block.
MemoryBlock::MemoryBlock (const void * dataToInitialiseFrom, size_t sizeInBytes)
Creates a memory block using a copy of a block of data.
Parameters
dataToInitialiseFrom some data to copy into this block
sizeInBytes how much space to use
MemoryBlock::~MemoryBlock () noexcept
Destructor.
MemoryBlock::MemoryBlock (MemoryBlock &&) noexcept
Move constructor.
Member Function Documentation
MemoryBlock& MemoryBlock::operator= (const MemoryBlock &)
Copies another memory block onto this one.
This block will be resized and copied to exactly match the other one.
MemoryBlock& MemoryBlock::operator= (MemoryBlock &&) noexcept
Move assignment operator.
bool MemoryBlock::operator== (const MemoryBlock & other) const noexcept
Compares two memory blocks.
Returns
true only if the two blocks are the same size and have identical contents.
bool MemoryBlock::operator!= (const MemoryBlock & other) const noexcept
Compares two memory blocks.
Returns
true if the two blocks are different sizes or have different contents.
bool MemoryBlock::matches (const void * data, size_t dataSize) const noexcept
Returns true if the data in this MemoryBlock matches the raw bytes passed-in.
void* MemoryBlock::getData () const noexcept
Returns a void pointer to the data.
Note that the pointer returned will probably become invalid when the block is resized.
Referenced by StandalonePluginHolder::askUserToLoadState(), StandalonePluginHolder::askUserToSaveState(), and StandalonePluginHolder::reloadPluginState().
template<typename Type > char& MemoryBlock::operator[] (const Type offset) const noexcept
Returns a byte from the memory block.
This returns a reference, so you can also use it to set a byte.
char* MemoryBlock::begin () const noexcept
Returns an iterator for the data.
char* MemoryBlock::end () const noexcept
Returns an end-iterator for the data.
size_t MemoryBlock::getSize () const noexcept
Returns the block's current allocated size, in bytes.
Referenced by StandalonePluginHolder::askUserToLoadState(), StandalonePluginHolder::askUserToSaveState(), and StandalonePluginHolder::reloadPluginState().
void MemoryBlock::setSize (const size_t newSize, bool initialiseNewSpaceToZero = false)
Resizes the memory block.
Any data that is present in both the old and new sizes will be retained. When enlarging the block, the new space that is allocated at the end can either be cleared, or left uninitialised.
Parameters
newSize the new desired size for the block
initialiseNewSpaceToZero if the block gets enlarged, this determines whether to clear the new section or just leave it uninitialised
See Also
ensureSize
void MemoryBlock::ensureSize (const size_t minimumSize, bool initialiseNewSpaceToZero = false)
Increases the block's size only if it's smaller than a given size.
Parameters
minimumSize if the block is already bigger than this size, no action will be taken; otherwise it will be increased to this size
initialiseNewSpaceToZero if the block gets enlarged, this determines whether to clear the new section or just leave it uninitialised
See Also
setSize
void MemoryBlock::reset ()
Frees all the blocks data, setting its size to 0.
void MemoryBlock::fillWith (uint8 valueToUse) noexcept
Fills the entire memory block with a repeated byte value.
This is handy for clearing a block of memory to zero.
void MemoryBlock::append (const void * data, size_t numBytes)
Adds another block of data to the end of this one.
The data pointer must not be null. This block's size will be increased accordingly.
void MemoryBlock::replaceWith (const void * data, size_t numBytes)
Resizes this block to the given size and fills its contents from the supplied buffer.
The data pointer must not be null.
void MemoryBlock::insert (const void * dataToInsert, size_t numBytesToInsert, size_t insertPosition)
Inserts some data into the block.
The dataToInsert pointer must not be null. This block's size will be increased accordingly. If the insert position lies outside the valid range of the block, it will be clipped to within the range before being used.
void MemoryBlock::removeSection (size_t startByte, size_t numBytesToRemove)
Chops out a section of the block.
This will remove a section of the memory block and close the gap around it, shifting any subsequent data downwards and reducing the size of the block.
If the range specified goes beyond the size of the block, it will be clipped.
void MemoryBlock::copyFrom (const void * srcData, int destinationOffset, size_t numBytes) noexcept
Copies data into this MemoryBlock from a memory address.
Parameters
srcData the memory location of the data to copy into this block
destinationOffset the offset in this block at which the data being copied should begin
numBytes how much to copy in (if this goes beyond the size of the memory block, it will be clipped so not to do anything nasty)
void MemoryBlock::copyTo (void * destData, int sourceOffset, size_t numBytes) const noexcept
Copies data from this MemoryBlock to a memory address.
Parameters
destData the memory location to write to
sourceOffset the offset within this block from which the copied data will be read
numBytes how much to copy (if this extends beyond the limits of the memory block, zeros will be used for that portion of the data)
void MemoryBlock::swapWith (MemoryBlock & other) noexcept
Exchanges the contents of this and another memory block.
No actual copying is required for this, so it's very fast.
String MemoryBlock::toString () const
Attempts to parse the contents of the block as a zero-terminated UTF8 string.
void MemoryBlock::loadFromHexString (StringRef sourceHexString)
Parses a string of hexadecimal numbers and writes this data into the memory block.
The block will be resized to the number of valid bytes read from the string. Non-hex characters in the string will be ignored.
See Also
String::toHexString()
void MemoryBlock::setBitRange (size_t bitRangeStart, size_t numBits, int binaryNumberToApply) noexcept
Sets a number of bits in the memory block, treating it as a long binary sequence.
int MemoryBlock::getBitRange (size_t bitRangeStart, size_t numBitsToRead) const noexcept
Reads a number of bits from the memory block, treating it as one long binary sequence.
String MemoryBlock::toBase64Encoding () const
Returns a string of characters in a JUCE-specific text encoding that represents the binary contents of this block.
This uses a JUCE-specific (i.e. not standard!) 64-bit encoding system to convert binary data into a string of ASCII characters for purposes like storage in XML. Note that this proprietary format is mainly kept here for backwards-compatibility, and you may prefer to use the Base64::toBase64() method if you want to use the standard base-64 encoding.
See Also
fromBase64Encoding, Base64::toBase64, Base64::convertToBase64
Referenced by StandalonePluginHolder::savePluginState().
bool MemoryBlock::fromBase64Encoding (StringRef encodedString)
Takes a string created by MemoryBlock::toBase64Encoding() and extracts the original data.
The string passed in must have been created by to64BitEncoding(), and this block will be resized to recreate the original data block.
Note that these methods use a JUCE-specific (i.e. not standard!) 64-bit encoding system. You may prefer to use the Base64::convertFromBase64() method if you want to use the standard base-64 encoding.
See Also
toBase64Encoding, Base64::convertFromBase64
Referenced by StandalonePluginHolder::reloadPluginState().
class OptionalScopedPointer
template<class ObjectType>
class OptionalScopedPointer< ObjectType >
Holds a pointer to an object which can optionally be deleted when this pointer goes out of scope.
This acts in many ways like a ScopedPointer, but allows you to specify whether or not the object is deleted.
See Also
ScopedPointer
Public Member Functions
OptionalScopedPointer ()
Creates an empty OptionalScopedPointer.
OptionalScopedPointer (ObjectType *objectToHold, bool takeOwnership)
Creates an OptionalScopedPointer to point to a given object, and specifying whether the OptionalScopedPointer will delete it.
OptionalScopedPointer (OptionalScopedPointer &objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
OptionalScopedPointer & operator= (OptionalScopedPointer &objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
~OptionalScopedPointer ()
The destructor may or may not delete the object that is being held, depending on the takeOwnership flag that was specified when the object was first passed into an OptionalScopedPointer constructor.
operator ObjectType * () const noexcept
Returns the object that this pointer is managing.
ObjectType * get () const noexcept
Returns the object that this pointer is managing.
ObjectType & operator* () const noexcept
Returns the object that this pointer is managing.
ObjectType * operator-> () const noexcept
Lets you access methods and properties of the object that this pointer is holding.
ObjectType * release () noexcept
Removes the current object from this OptionalScopedPointer without deleting it.
void clear ()
Resets this pointer to null, possibly deleting the object that it holds, if it has ownership of it.
void set (ObjectType *newObject, bool takeOwnership)
Makes this OptionalScopedPointer point at a new object, specifying whether the OptionalScopedPointer will take ownership of the object.
void setOwned (ObjectType *newObject)
Makes this OptionalScopedPointer point at a new object, and take ownership of that object.
void setNonOwned (ObjectType *newObject)
Makes this OptionalScopedPointer point at a new object, but will not take ownership of that object.
bool willDeleteObject () const noexcept
Returns true if the target object will be deleted when this pointer object is deleted.
void swapWith (OptionalScopedPointer< ObjectType > &other) noexcept
Swaps this object with another OptionalScopedPointer.
Constructor & Destructor Documentation
template<class ObjectType> OptionalScopedPointer< ObjectType >::OptionalScopedPointer ()
Creates an empty OptionalScopedPointer.
template<class ObjectType> OptionalScopedPointer< ObjectType >::OptionalScopedPointer (ObjectType * objectToHold, bool takeOwnership)
Creates an OptionalScopedPointer to point to a given object, and specifying whether the OptionalScopedPointer will delete it.
If takeOwnership is true, then the OptionalScopedPointer will act like a ScopedPointer, deleting the object when it is itself deleted. If this parameter is false, then the OptionalScopedPointer just holds a normal pointer to the object, and won't delete it.
template<class ObjectType> OptionalScopedPointer< ObjectType >::OptionalScopedPointer (OptionalScopedPointer< ObjectType > & objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
Like a normal ScopedPointer, the objectToTransferFrom object will become null, as ownership of the managed object is transferred to this object.
The flag to indicate whether or not to delete the managed object is also copied from the source object.
template<class ObjectType> OptionalScopedPointer< ObjectType >::~OptionalScopedPointer ()
The destructor may or may not delete the object that is being held, depending on the takeOwnership flag that was specified when the object was first passed into an OptionalScopedPointer constructor.
Member Function Documentation
template<class ObjectType> OptionalScopedPointer& OptionalScopedPointer< ObjectType >::operator= (OptionalScopedPointer< ObjectType > & objectToTransferFrom)
Takes ownership of the object that another OptionalScopedPointer holds.
Like a normal ScopedPointer, the objectToTransferFrom object will become null, as ownership of the managed object is transferred to this object.
The ownership flag that says whether or not to delete the managed object is also copied from the source object.
template<class ObjectType> OptionalScopedPointer< ObjectType >::operator ObjectType * () const noexcept
Returns the object that this pointer is managing.
template<class ObjectType> ObjectType* OptionalScopedPointer< ObjectType >::get () const noexcept
Returns the object that this pointer is managing.
Referenced by StandaloneFilterWindow::resetToDefaultState(), StandaloneFilterWindow::StandaloneFilterWindow(), and StandaloneFilterWindow::~StandaloneFilterWindow().
template<class ObjectType> ObjectType& OptionalScopedPointer< ObjectType >::operator* () const noexcept
Returns the object that this pointer is managing.
template<class ObjectType> ObjectType* OptionalScopedPointer< ObjectType >::operator-> () const noexcept
Lets you access methods and properties of the object that this pointer is holding.
template<class ObjectType> ObjectType* OptionalScopedPointer< ObjectType >::release () noexcept
Removes the current object from this OptionalScopedPointer without deleting it.
This will return the current object, and set this OptionalScopedPointer to a null pointer.
template<class ObjectType> void OptionalScopedPointer< ObjectType >::clear ()
Resets this pointer to null, possibly deleting the object that it holds, if it has ownership of it.
Referenced by OptionalScopedPointer< OutputStream >::operator=(), OptionalScopedPointer< OutputStream >::set(), and OptionalScopedPointer< OutputStream >::~OptionalScopedPointer().
template<class ObjectType> void OptionalScopedPointer< ObjectType >::set (ObjectType * newObject, bool takeOwnership)
Makes this OptionalScopedPointer point at a new object, specifying whether the OptionalScopedPointer will take ownership of the object.
If takeOwnership is true, then the OptionalScopedPointer will act like a ScopedPointer, deleting the object when it is itself deleted. If this parameter is false, then the OptionalScopedPointer just holds a normal pointer to the object, and won't delete it.
Referenced by OptionalScopedPointer< OutputStream >::setNonOwned(), and OptionalScopedPointer< OutputStream >::setOwned().
template<class ObjectType> void OptionalScopedPointer< ObjectType >::setOwned (ObjectType * newObject)
Makes this OptionalScopedPointer point at a new object, and take ownership of that object.
Referenced by StandalonePluginHolder::showAudioSettingsDialog().
template<class ObjectType> void OptionalScopedPointer< ObjectType >::setNonOwned (ObjectType * newObject)
Makes this OptionalScopedPointer point at a new object, but will not take ownership of that object.
template<class ObjectType> bool OptionalScopedPointer< ObjectType >::willDeleteObject () const noexcept
Returns true if the target object will be deleted when this pointer object is deleted.
template<class ObjectType> void OptionalScopedPointer< ObjectType >::swapWith (OptionalScopedPointer< ObjectType > & other) noexcept
Swaps this object with another OptionalScopedPointer.
The two objects simply exchange their states.
class ReferenceCountedObject
A base class which provides methods for reference-counting.
To add reference-counting to a class, derive it from this class, and use the ReferenceCountedObjectPtr class to point to it.
e.g.
class MyClass : public ReferenceCountedObject
{
    void foo();
    // This is a neat way of declaring a typedef for a pointer class,
    // rather than typing out the full templated name each time..
    typedef ReferenceCountedObjectPtr<MyClass> Ptr;
};
MyClass::Ptr p = new MyClass();
MyClass::Ptr p2 = p;
p = nullptr;
p2->foo();
Once a new ReferenceCountedObject has been assigned to a pointer, be careful not to delete the object manually.
This class uses an Atomic<int> value to hold the reference count, so that it the pointers can be passed between threads safely. For a faster but non-thread-safe version, use SingleThreadedReferenceCountedObject instead.
See Also
ReferenceCountedObjectPtr, ReferenceCountedArray, SingleThreadedReferenceCountedObject
Public Member Functions
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Protected Member Functions
ReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () noexcept
Resets the reference count to zero without deleting the object.
Constructor & Destructor Documentation
ReferenceCountedObject::ReferenceCountedObject () protected
Creates the reference-counted object (with an initial ref count of zero).
virtual ReferenceCountedObject::~ReferenceCountedObject () protected virtual
Destructor.
References jassert.
Member Function Documentation
void ReferenceCountedObject::incReferenceCount () noexcept
Increments the object's reference count.
This is done automatically by the smart pointer, but is public just in case it's needed for nefarious purposes.
void ReferenceCountedObject::decReferenceCount () noexcept
Decreases the object's reference count.
If the count gets to zero, the object will be deleted.
References jassert.
bool ReferenceCountedObject::decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
If the count gets to zero, the object will not be deleted, but this method will return true, allowing the caller to take care of deletion.
References jassert.
int ReferenceCountedObject::getReferenceCount () const noexcept
Returns the object's current reference count.
void ReferenceCountedObject::resetReferenceCount () protected noexcept
Resets the reference count to zero without deleting the object.
You should probably never need to use this!
class SingleThreadedReferenceCountedObject
Adds reference-counting to an object.
This is effectively a version of the ReferenceCountedObject class, but which uses a non-atomic counter, and so is not thread-safe (but which will be more efficient). For more details on how to use it, see the ReferenceCountedObject class notes.
See Also
ReferenceCountedObject, ReferenceCountedObjectPtr, ReferenceCountedArray
Public Member Functions
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Protected Member Functions
SingleThreadedReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
virtual ~SingleThreadedReferenceCountedObject ()
Destructor.
Constructor & Destructor Documentation
SingleThreadedReferenceCountedObject::SingleThreadedReferenceCountedObject () protected
Creates the reference-counted object (with an initial ref count of zero).
virtual SingleThreadedReferenceCountedObject::~SingleThreadedReferenceCountedObject () protected virtual
Destructor.
References jassert.
Member Function Documentation
void SingleThreadedReferenceCountedObject::incReferenceCount () noexcept
Increments the object's reference count.
This is done automatically by the smart pointer, but is public just in case it's needed for nefarious purposes.
void SingleThreadedReferenceCountedObject::decReferenceCount () noexcept
Decreases the object's reference count.
If the count gets to zero, the object will be deleted.
References jassert.
bool SingleThreadedReferenceCountedObject::decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
If the count gets to zero, the object will not be deleted, but this method will return true, allowing the caller to take care of deletion.
References jassert.
int SingleThreadedReferenceCountedObject::getReferenceCount () const noexcept
Returns the object's current reference count.
class ReferenceCountedObjectPtr
template<class ReferenceCountedObjectClass>
class ReferenceCountedObjectPtr< ReferenceCountedObjectClass >
A smart-pointer class which points to a reference-counted object.
The template parameter specifies the class of the object you want to point to - the easiest way to make a class reference-countable is to simply make it inherit from ReferenceCountedObject or SingleThreadedReferenceCountedObject, but if you need to, you can roll your own reference-countable class by implementing a set of methods called incReferenceCount(), decReferenceCount(), and decReferenceCountWithoutDeleting(). See ReferenceCountedObject for examples of how these methods should behave.
When using this class, you'll probably want to create a typedef to abbreviate the full templated name - e.g.
struct MyClass  : public ReferenceCountedObject
{
    typedef ReferenceCountedObjectPtr<MyClass> Ptr;
    ...
See Also
ReferenceCountedObject, ReferenceCountedObjectArray
Public Types
typedef ReferenceCountedObjectClass ReferencedType
The class being referenced by this pointer.
Public Member Functions
ReferenceCountedObjectPtr () noexcept
Creates a pointer to a null object.
ReferenceCountedObjectPtr (ReferencedType *refCountedObject) noexcept
Creates a pointer to an object.
ReferenceCountedObjectPtr (decltype(nullptr)) noexcept
Creates a pointer to a null object.
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr &other) noexcept
Copies another pointer.
template<typename Convertible >
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > &other) noexcept
Copies another pointer.
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr &other)
Changes this pointer to point at a different object.
template<typename Convertible >
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr< Convertible > &other)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr & operator= (ReferencedType *const newObject)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr (ReferenceCountedObjectPtr &&other) noexcept
Takes-over the object from another pointer.
ReferenceCountedObjectPtr & operator= (ReferenceCountedObjectPtr &&other)
Takes-over the object from another pointer.
~ReferenceCountedObjectPtr ()
Destructor.
operator ReferencedType * () const noexcept
Returns the object that this pointer references.
ReferencedType * get () const noexcept
Returns the object that this pointer references.
ReferencedType * getObject () const noexcept
Returns the object that this pointer references.
ReferencedType * operator-> () const noexcept
Member Typedef Documentation
template<class ReferenceCountedObjectClass> typedef ReferenceCountedObjectClass ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferencedType
The class being referenced by this pointer.
Constructor & Destructor Documentation
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr () noexcept
Creates a pointer to a null object.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (ReferencedType * refCountedObject) noexcept
Creates a pointer to an object.
This will increment the object's reference-count.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (decltype(nullptr)) noexcept
Creates a pointer to a null object.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & other) noexcept
Copies another pointer.
This will increment the object's reference-count.
template<class ReferenceCountedObjectClass> template<typename Convertible > ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > & other) noexcept
Copies another pointer.
This will increment the object's reference-count (if it is non-null).
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::ReferenceCountedObjectPtr (ReferenceCountedObjectPtr< ReferenceCountedObjectClass > && other) noexcept
Takes-over the object from another pointer.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::~ReferenceCountedObjectPtr ()
Destructor.
This will decrement the object's reference-count, which will cause the object to be deleted when the ref-count hits zero.
Member Function Documentation
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & other)
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Referenced by ReferenceCountedObjectPtr< ImagePixelData >::operator=().
template<class ReferenceCountedObjectClass> template<typename Convertible > ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (const ReferenceCountedObjectPtr< Convertible > & other)
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (ReferencedType *const newObject)
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator= (ReferenceCountedObjectPtr< ReferenceCountedObjectClass > && other)
Takes-over the object from another pointer.
template<class ReferenceCountedObjectClass> ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator ReferencedType * () const noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
template<class ReferenceCountedObjectClass> ReferencedType* ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::get () const noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
Referenced by WeakReference< InterprocessConnection >::get(), WeakReference< ObjectType, ReferenceCountingType >::Master::getSharedPointer(), ReferenceCountedObjectPtr< ImagePixelData >::operator=(), WeakReference< InterprocessConnection >::wasObjectDeleted(), and WeakReference< ObjectType, ReferenceCountingType >::Master::~Master().
template<class ReferenceCountedObjectClass> ReferencedType* ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::getObject () const noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
template<class ReferenceCountedObjectClass> ReferencedType* ReferenceCountedObjectPtr< ReferenceCountedObjectClass >::operator-> () const noexcept
class ScopedPointer
template<class ObjectType>
class ScopedPointer< ObjectType >
This class holds a pointer which is automatically deleted when this object goes out of scope.
Once a pointer has been passed to a ScopedPointer, it will make sure that the pointer gets deleted when the ScopedPointer is deleted. Using the ScopedPointer on the stack or as member variables is a good way to use RAII to avoid accidentally leaking dynamically created objects.
A ScopedPointer can be used in pretty much the same way that you'd use a normal pointer to an object. If you use the assignment operator to assign a different object to a ScopedPointer, the old one will be automatically deleted.
Important note: The class is designed to hold a pointer to an object, NOT to an array! It calls delete on its payload, not delete[], so do not give it an array to hold! For that kind of purpose, you should be using HeapBlock or Array instead.
A const ScopedPointer is guaranteed not to lose ownership of its object or change the object to which it points during its lifetime. This means that making a copy of a const ScopedPointer is impossible, as that would involve the new copy taking ownership from the old one.
If you need to get a pointer out of a ScopedPointer without it being deleted, you can use the release() method.
Something to note is the main difference between this class and the std::auto_ptr class, which is that ScopedPointer provides a cast-to-object operator, whereas std::auto_ptr requires that you always call get() to retrieve the pointer. The advantages of providing the cast is that you don't need to call get(), so can use the ScopedPointer in pretty much exactly the same way as a raw pointer. The disadvantage is that the compiler is free to use the cast in unexpected and sometimes dangerous ways - in particular, it becomes difficult to return a ScopedPointer as the result of a function. To avoid this causing errors, ScopedPointer contains an overloaded constructor that should cause a syntax error in these circumstances, but it does mean that instead of returning a ScopedPointer from a function, you'd need to return a raw pointer (or use a std::auto_ptr instead).
Public Member Functions
ScopedPointer () noexcept
Creates a ScopedPointer containing a null pointer.
ScopedPointer (decltype(nullptr)) noexcept
Creates a ScopedPointer containing a null pointer.
ScopedPointer (ObjectType *const objectToTakePossessionOf) noexcept
Creates a ScopedPointer that owns the specified object.
ScopedPointer (ScopedPointer &objectToTransferFrom) noexcept
Creates a ScopedPointer that takes its pointer from another ScopedPointer.
~ScopedPointer ()
Destructor.
ScopedPointer & operator= (ScopedPointer &objectToTransferFrom)
Changes this ScopedPointer to point to a new object.
ScopedPointer & operator= (ObjectType *const newObjectToTakePossessionOf)
Changes this ScopedPointer to point to a new object.
ScopedPointer (ScopedPointer &&other) noexcept
Take ownership of another ScopedPointer.
ScopedPointer & operator= (ScopedPointer &&other) noexcept
Take ownership of another ScopedPointer.
operator ObjectType * () const noexcept
Returns the object that this ScopedPointer refers to.
ObjectType * get () const noexcept
Returns the object that this ScopedPointer refers to.
ObjectType & operator* () const noexcept
Returns the object that this ScopedPointer refers to.
ObjectType * operator-> () const noexcept
Lets you access methods and properties of the object that this ScopedPointer refers to.
ObjectType * release () noexcept
Removes the current object from this ScopedPointer without deleting it.
void swapWith (ScopedPointer< ObjectType > &other) noexcept
Swaps this object with that of another ScopedPointer.
ObjectType * createCopy () const
If the pointer is non-null, this will attempt to return a new copy of the object that is pointed to.
Constructor & Destructor Documentation
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer () noexcept
Creates a ScopedPointer containing a null pointer.
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (decltype(nullptr)) noexcept
Creates a ScopedPointer containing a null pointer.
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (ObjectType *const objectToTakePossessionOf) noexcept
Creates a ScopedPointer that owns the specified object.
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (ScopedPointer< ObjectType > & objectToTransferFrom) noexcept
Creates a ScopedPointer that takes its pointer from another ScopedPointer.
Because a pointer can only belong to one ScopedPointer, this transfers the pointer from the other object to this one, and the other object is reset to be a null pointer.
template<class ObjectType> ScopedPointer< ObjectType >::~ScopedPointer ()
Destructor.
This will delete the object that this ScopedPointer currently refers to.
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (ScopedPointer< ObjectType > && other) noexcept
Take ownership of another ScopedPointer.
Member Function Documentation
template<class ObjectType> ScopedPointer& ScopedPointer< ObjectType >::operator= (ScopedPointer< ObjectType > & objectToTransferFrom)
Changes this ScopedPointer to point to a new object.
Because a pointer can only belong to one ScopedPointer, this transfers the pointer from the other object to this one, and the other object is reset to be a null pointer.
If this ScopedPointer already points to an object, that object will first be deleted.
template<class ObjectType> ScopedPointer& ScopedPointer< ObjectType >::operator= (ObjectType *const newObjectToTakePossessionOf)
Changes this ScopedPointer to point to a new object.
If this ScopedPointer already points to an object, that object will first be deleted.
The pointer that you pass in may be a nullptr.
template<class ObjectType> ScopedPointer& ScopedPointer< ObjectType >::operator= (ScopedPointer< ObjectType > && other) noexcept
Take ownership of another ScopedPointer.
template<class ObjectType> ScopedPointer< ObjectType >::operator ObjectType * () const noexcept
Returns the object that this ScopedPointer refers to.
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::get () const noexcept
Returns the object that this ScopedPointer refers to.
template<class ObjectType> ObjectType& ScopedPointer< ObjectType >::operator* () const noexcept
Returns the object that this ScopedPointer refers to.
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::operator-> () const noexcept
Lets you access methods and properties of the object that this ScopedPointer refers to.
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::release () noexcept
Removes the current object from this ScopedPointer without deleting it.
This will return the current object, and set the ScopedPointer to a null pointer.
Referenced by OwnedArray< MidiBuffer >::set().
template<class ObjectType> void ScopedPointer< ObjectType >::swapWith (ScopedPointer< ObjectType > & other) noexcept
Swaps this object with that of another ScopedPointer.
The two objects simply exchange their pointers.
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::createCopy () const
If the pointer is non-null, this will attempt to return a new copy of the object that is pointed to.
If the pointer is null, this will safely return a nullptr.
class SharedResourcePointer
template<typename SharedObjectType>
class SharedResourcePointer< SharedObjectType >
A smart-pointer that automatically creates and manages the lifetime of a shared static instance of a class.
The SharedObjectType template type indicates the class to use for the shared object - the only requirements on this class are that it must have a public default constructor and destructor.
The SharedResourcePointer offers a pattern that differs from using a singleton or static instance of an object, because it uses reference-counting to make sure that the underlying shared object is automatically created/destroyed according to the number of SharedResourcePointer objects that exist. When the last one is deleted, the underlying object is also immediately destroyed. This allows you to use scoping to manage the lifetime of a shared resource.
Note: the construction/deletion of the shared object must not involve any code that makes recursive calls to a SharedResourcePointer, or you'll cause a deadlock.
Example:
// An example of a class that contains the shared data you want to use.
struct MySharedData
{
    // There's no need to ever create an instance of this class directly yourself,
    // but it does need a public constructor that does the initialisation.
    MySharedData()
    {
        sharedStuff = generateHeavyweightStuff();
    }
    Array<SomeKindOfData> sharedStuff;
};
struct DataUserClass
{
    DataUserClass()
    {
        // Multiple instances of the DataUserClass will all have the same
        // shared common instance of MySharedData referenced by their sharedData
        // member variables.
        useSharedStuff (sharedData->sharedStuff);
    }
    // By keeping this pointer as a member variable, the shared resource
    // is guaranteed to be available for as long as the DataUserClass object.
    SharedResourcePointer<MySharedData> sharedData;
};
Public Member Functions
SharedResourcePointer ()
Creates an instance of the shared object.
SharedResourcePointer (const SharedResourcePointer &)
~SharedResourcePointer ()
Destructor.
operator SharedObjectType * () const noexcept
Returns the shared object.
SharedObjectType & get () const noexcept
Returns the shared object.
SharedObjectType & getObject () const noexcept
Returns the object that this pointer references.
SharedObjectType * operator-> () const noexcept
Returns the shared object.
int getReferenceCount () const noexcept
Returns the number of SharedResourcePointers that are currently holding the shared object.
Constructor & Destructor Documentation
template<typename SharedObjectType > SharedResourcePointer< SharedObjectType >::SharedResourcePointer ()
Creates an instance of the shared object.
If other SharedResourcePointer objects for this type already exist, then this one will simply point to the same shared object that they are already using. Otherwise, if this is the first SharedResourcePointer to be created, then a shared object will be created automatically.
template<typename SharedObjectType > SharedResourcePointer< SharedObjectType >::SharedResourcePointer (const SharedResourcePointer< SharedObjectType > &)
template<typename SharedObjectType > SharedResourcePointer< SharedObjectType >::~SharedResourcePointer ()
Destructor.
If no other SharedResourcePointer objects exist, this will also delete the shared object to which it refers.
Member Function Documentation
template<typename SharedObjectType > SharedResourcePointer< SharedObjectType >::operator SharedObjectType * () const noexcept
Returns the shared object.
template<typename SharedObjectType > SharedObjectType& SharedResourcePointer< SharedObjectType >::get () const noexcept
Returns the shared object.
template<typename SharedObjectType > SharedObjectType& SharedResourcePointer< SharedObjectType >::getObject () const noexcept
Returns the object that this pointer references.
The pointer returned may be a nullptr, of course.
template<typename SharedObjectType > SharedObjectType* SharedResourcePointer< SharedObjectType >::operator-> () const noexcept
Returns the shared object.
template<typename SharedObjectType > int SharedResourcePointer< SharedObjectType >::getReferenceCount () const noexcept
Returns the number of SharedResourcePointers that are currently holding the shared object.
class WeakReference
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject>
class WeakReference< ObjectType, ReferenceCountingType >
This class acts as a pointer which will automatically become null if the object to which it points is deleted.
To accomplish this, the source object needs to cooperate by performing a couple of simple tasks. It must embed a WeakReference::Master object, which stores a shared pointer object, and must clear this master pointer in its destructor.
E.g.
class MyObject
{
public:
    MyObject()
    {
        // If you're planning on using your WeakReferences in a multi-threaded situation, you may choose
        // to create a WeakReference to the object here in the constructor, which will pre-initialise the
        // embedded object, avoiding an (extremely unlikely) race condition that could occur if multiple
        // threads overlap while creating the first WeakReference to it.
    }
    ~MyObject()
    {
        // This will zero all the references - you need to call this in your destructor.
        masterReference.clear();
    }
private:
    // You need to embed a variable of this type, with the name "masterReference" inside your object. If the
    // variable is not public, you should make your class a friend of WeakReference<MyObject> so that the
    // WeakReference class can access it.
    WeakReference<MyObject>::Master masterReference;
    friend class WeakReference<MyObject>;
};
// Here's an example of using a pointer..
MyObject* n = new MyObject();
WeakReference<MyObject> myObjectRef = n;
MyObject* pointer1 = myObjectRef;  // returns a valid pointer to 'n'
delete n;
MyObject* pointer2 = myObjectRef;  // returns a null pointer
See Also
WeakReference::Master
Public Types
typedef
ReferenceCountedObjectPtr
< SharedPointer > SharedRef
Public Member Functions
WeakReference () noexcept
Creates a null SafePointer.
WeakReference (ObjectType *const object)
Creates a WeakReference that points at the given object.
WeakReference (const WeakReference &other) noexcept
Creates a copy of another WeakReference.
WeakReference (WeakReference &&other) noexcept
Move constructor.
WeakReference & operator= (const WeakReference &other)
Copies another pointer to this one.
WeakReference & operator= (ObjectType *const newObject)
Copies another pointer to this one.
WeakReference & operator= (WeakReference &&other) noexcept
Move assignment operator.
ObjectType * get () const noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
operator ObjectType * () const noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
ObjectType * operator-> () noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
const ObjectType * operator-> () const noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
bool wasObjectDeleted () const noexcept
This returns true if this reference has been pointing at an object, but that object has since been deleted.
bool operator== (ObjectType *const object) const noexcept
bool operator!= (ObjectType *const object) const noexcept
Member Typedef Documentation
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> typedef ReferenceCountedObjectPtr<SharedPointer> WeakReference< ObjectType, ReferenceCountingType >::SharedRef
Constructor & Destructor Documentation
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference< ObjectType, ReferenceCountingType >::WeakReference () noexcept
Creates a null SafePointer.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference< ObjectType, ReferenceCountingType >::WeakReference (ObjectType *const object)
Creates a WeakReference that points at the given object.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference< ObjectType, ReferenceCountingType >::WeakReference (const WeakReference< ObjectType, ReferenceCountingType > & other) noexcept
Creates a copy of another WeakReference.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference< ObjectType, ReferenceCountingType >::WeakReference (WeakReference< ObjectType, ReferenceCountingType > && other) noexcept
Move constructor.
Member Function Documentation
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference& WeakReference< ObjectType, ReferenceCountingType >::operator= (const WeakReference< ObjectType, ReferenceCountingType > & other)
Copies another pointer to this one.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference& WeakReference< ObjectType, ReferenceCountingType >::operator= (ObjectType *const newObject)
Copies another pointer to this one.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference& WeakReference< ObjectType, ReferenceCountingType >::operator= (WeakReference< ObjectType, ReferenceCountingType > && other) noexcept
Move assignment operator.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> ObjectType* WeakReference< ObjectType, ReferenceCountingType >::get () const noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> WeakReference< ObjectType, ReferenceCountingType >::operator ObjectType * () const noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> ObjectType* WeakReference< ObjectType, ReferenceCountingType >::operator-> () noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> const ObjectType* WeakReference< ObjectType, ReferenceCountingType >::operator-> () const noexcept
Returns the object that this pointer refers to, or null if the object no longer exists.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> bool WeakReference< ObjectType, ReferenceCountingType >::wasObjectDeleted () const noexcept
This returns true if this reference has been pointing at an object, but that object has since been deleted.
If this reference was only ever pointing at a null pointer, this will return false. Using operator=() to make this refer to a different object will reset this flag to match the status of the reference from which you're copying.
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> bool WeakReference< ObjectType, ReferenceCountingType >::operator== (ObjectType *const object) const noexcept
template<class ObjectType, class ReferenceCountingType = ReferenceCountedObject> bool WeakReference< ObjectType, ReferenceCountingType >::operator!= (ObjectType *const object) const noexcept
Macro Definition Documentation
#define JUCE_LEAK_DETECTOR (OwnerClass)
Value:
friend class juce::LeakedObjectDetector<OwnerClass>; \
        static const char* getLeakedObjectClassName() noexcept { return #OwnerClass; } \
        juce::LeakedObjectDetector<OwnerClass> JUCE_JOIN_MACRO (leakDetector, __LINE__);
This macro lets you embed a leak-detecting object inside a class.
To use it, simply declare a JUCE_LEAK_DETECTOR(YourClassName) inside a private section of the class declaration. E.g.
class MyClass
{
public:
    MyClass();
    void blahBlah();
private:
    JUCE_LEAK_DETECTOR (MyClass)
};
See Also
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, LeakedObjectDetector
#define JUCE_AUTORELEASEPOOL @autoreleasepool
A macro that can be used to easily declare a local ScopedAutoReleasePool object for RAII-based obj-C autoreleasing.
Because this may use the @autoreleasepool syntax, you must follow the macro with a set of braces to mark the scope of the pool.
#define juce_UseDebuggingNewOperator
(Deprecated) This was a Windows-specific way of checking for object leaks - now please use the JUCE_LEAK_DETECTOR instead.
#define juce_DeclareSingleton (classname, doNotRecreateAfterDeletion)
Macro to declare member variables and methods for a singleton class.
To use this, add the line juce_DeclareSingleton (MyClass, doNotRecreateAfterDeletion) to the class's definition.
Then put a macro juce_ImplementSingleton (MyClass) along with the class's implementation code.
It's also a very good idea to also add the call clearSingletonInstance() in your class's destructor, in case it is deleted by other means than deleteInstance()
Clients can then call the static method MyClass::getInstance() to get a pointer to the singleton, or MyClass::getInstanceWithoutCreating() which will return nullptr if no instance currently exists.
e.g.
class MySingleton
{
public:
    MySingleton()
    {
    }
    ~MySingleton()
    {
        // this ensures that no dangling pointers are left when the
        // singleton is deleted.
        clearSingletonInstance();
    }
    juce_DeclareSingleton (MySingleton, false)
};
juce_ImplementSingleton (MySingleton)
// example of usage:
MySingleton* m = MySingleton::getInstance(); // creates the singleton if there isn't already one.
...
MySingleton::deleteInstance(); // safely deletes the singleton (if it's been created).
If doNotRecreateAfterDeletion = true, it won't allow the object to be created more than once during the process's lifetime - i.e. after you've created and deleted the object, getInstance() will refuse to create another one. This can be useful to stop objects being accidentally re-created during your app's shutdown code.
If you know that your object will only be created and deleted by a single thread, you can use the slightly more efficient juce_DeclareSingleton_SingleThreaded() macro instead of this one.
See Also
juce_ImplementSingleton, juce_DeclareSingleton_SingleThreaded
#define juce_ImplementSingleton (classname)
Value:
\
    classname* classname::_singletonInstance = nullptr; \
    juce::CriticalSection classname::_singletonLock;
This is a counterpart to the juce_DeclareSingleton macro.
After adding the juce_DeclareSingleton to the class definition, this macro has to be used in the cpp file.
#define juce_DeclareSingleton_SingleThreaded (classname, doNotRecreateAfterDeletion)
Macro to declare member variables and methods for a singleton class.
This is exactly the same as juce_DeclareSingleton, but doesn't use a critical section to make access to it thread-safe. If you know that your object will only ever be created or deleted by a single thread, then this is a more efficient version to use.
If doNotRecreateAfterDeletion = true, it won't allow the object to be created more than once during the process's lifetime - i.e. after you've created and deleted the object, getInstance() will refuse to create another one. This can be useful to stop objects being accidentally re-created during your app's shutdown code.
See the documentation for juce_DeclareSingleton for more information about how to use it, the only difference being that you have to use juce_ImplementSingleton_SingleThreaded instead of juce_ImplementSingleton.
See Also
juce_ImplementSingleton_SingleThreaded, juce_DeclareSingleton, juce_DeclareSingleton_SingleThreaded_Minimal
#define juce_DeclareSingleton_SingleThreaded_Minimal (classname)
Value:
\
    static classname* _singletonInstance;  \
\
    static classname* getInstance() \
    { \
        if (_singletonInstance == nullptr) \
            _singletonInstance = new classname(); \
\
        return _singletonInstance; \
    } \
\
    static inline classname* getInstanceWithoutCreating() noexcept\
    { \
        return _singletonInstance; \
    } \
\
    static void deleteInstance() \
    { \
        if (_singletonInstance != nullptr) \
        { \
            classname* const old = _singletonInstance; \
            _singletonInstance = nullptr; \
            delete old; \
        } \
    } \
\
    void clearSingletonInstance() noexcept\
    { \
        if (_singletonInstance == this) \
            _singletonInstance = nullptr; \
    }
Macro to declare member variables and methods for a singleton class.
This is like juce_DeclareSingleton_SingleThreaded, but doesn't do any checking for recursion or repeated instantiation. It's intended for use as a lightweight version of a singleton, where you're using it in very straightforward circumstances and don't need the extra checking.
Juce use the normal juce_ImplementSingleton_SingleThreaded as the counterpart to this declaration, as you would with juce_DeclareSingleton_SingleThreaded.
See the documentation for juce_DeclareSingleton for more information about how to use it, the only difference being that you have to use juce_ImplementSingleton_SingleThreaded instead of juce_ImplementSingleton.
See Also
juce_ImplementSingleton_SingleThreaded, juce_DeclareSingleton
#define juce_ImplementSingleton_SingleThreaded (classname)
Value:
\
    classname* classname::_singletonInstance = nullptr;
This is a counterpart to the juce_DeclareSingleton_SingleThreaded macro.
After adding juce_DeclareSingleton_SingleThreaded or juce_DeclareSingleton_SingleThreaded_Minimal to the class definition, this macro has to be used somewhere in the cpp file.
Function Documentation
void zeromem (void * memory, size_t numBytes) noexcept
Fills a block of memory with zeros.
Referenced by littlefoot::LittleFootRemoteHeap< ImplementationClass >::clear(), Matrix< ElementType >::clear(), HeapBlock< ObjectClass * >::clear(), AudioUnitHelpers::clearAudioBuffer(), AudioFormatReader::clearSamplesBeyondAvailableLength(), AudioUnitHelpers::CoreAudioBufferList::reset(), and SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
template<typename Type > void zerostruct (Type & structure) noexcept
Overwrites a structure or object with zeros.
template<typename Type > void deleteAndZero (Type & pointer)
Delete an object pointer, and sets the pointer to null.
Remember that it's not good c++ practice to use delete directly - always try to use a ScopedPointer or other automatic lifetime-management system rather than resorting to deleting raw pointers!
template<typename Type , typename IntegerType > Type* addBytesToPointer (Type * basePointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result.
This can be useful to avoid casting pointers to a char* and back when you want to move them by a specific number of bytes,
Referenced by String::appendCharPointer(), AudioBlock< float >::AudioBlock(), AudioData::ConverterInstance< SourceSampleType, DestSampleType >::convertSamples(), AudioFormatReader::ReadHelper< DestSampleType, SourceSampleType, SourceEndianness >::read(), MemoryMappedAudioFormatReader::sampleToPointer(), MemoryMappedAudioFormatReader::scanMinAndMaxInterleaved(), and AudioFormatWriter::WriteHelper< DestSampleType, SourceSampleType, DestEndianness >::write().
template<typename Type , typename IntegerType > Type* snapPointerToAlignment (Type * basePointer, IntegerType alignmentBytes) noexcept
A handy function to round up a pointer to the nearest multiple of a given number of bytes.
alignmentBytes must be a power of two.
Referenced by AudioBlock< float >::AudioBlock(), SIMDRegister< Type >::getNextSIMDAlignedPtr(), and FIR::Filter< SampleType >::reset().
template<typename Type1 , typename Type2 > int getAddressDifference (Type1 * pointer1, Type2 * pointer2) noexcept
A handy function which returns the difference between any two pointers, in bytes.
The address of the second pointer is subtracted from the first, and the difference in bytes is returned.
Referenced by CharacterFunctions::copyWithDestByteLimit().
template<class Type > Type* createCopyIfNotNull (const Type * objectToCopy)
If a pointer is non-null, this returns a new copy of the object that it points to, or safely returns nullptr if the pointer is null.
Referenced by OwnedArray< MidiBuffer >::addCopiesOf(), and ScopedPointer< ListViewport >::createCopy().
template<typename Type > Type readUnaligned (const void * srcPtr) noexcept
A handy function to read un-aligned memory without a performance penalty or bus-error.
template<typename Type > void writeUnaligned (void * dstPtr, Type value) noexcept
A handy function to write un-aligned memory without a performance penalty or bus-error.
template<typename ReferenceCountedObjectClass > bool operator== (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object1, ReferenceCountedObjectClass *const object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass > bool operator== (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass > bool operator== (ReferenceCountedObjectClass * object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass > bool operator!= (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object1, const ReferenceCountedObjectClass * object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass > bool operator!= (const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename ReferenceCountedObjectClass > bool operator!= (ReferenceCountedObjectClass * object1, const ReferenceCountedObjectPtr< ReferenceCountedObjectClass > & object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<class ObjectType > bool operator== (const ScopedPointer< ObjectType > & pointer1, ObjectType *const pointer2) noexcept
Compares a ScopedPointer with another pointer.
This can be handy for checking whether this is a null pointer.
template<class ObjectType > bool operator!= (const ScopedPointer< ObjectType > & pointer1, ObjectType *const pointer2) noexcept
Compares a ScopedPointer with another pointer.
This can be handy for checking whether this is a null pointer.
uint16 ByteOrder::swap (uint16 value) static noexcept
Swaps the upper and lower bytes of a 16-bit integer.
Referenced by ByteOrder::swapIfBigEndian().
uint32 ByteOrder::swap (uint32 value) static noexcept
Reverses the order of the 4 bytes in a 32-bit integer.
uint64 ByteOrder::swap (uint64 value) static noexcept
Reverses the order of the 8 bytes in a 64-bit integer.
uint16 ByteOrder::swapIfBigEndian (uint16 value) static noexcept
Swaps the byte order of a 16-bit unsigned int if the CPU is big-endian.
uint32 ByteOrder::swapIfBigEndian (uint32 value) static noexcept
Swaps the byte order of a 32-bit unsigned int if the CPU is big-endian.
uint64 ByteOrder::swapIfBigEndian (uint64 value) static noexcept
Swaps the byte order of a 64-bit unsigned int if the CPU is big-endian.
int16 ByteOrder::swapIfBigEndian (int16 value) static noexcept
Swaps the byte order of a 16-bit signed int if the CPU is big-endian.
int32 ByteOrder::swapIfBigEndian (int32 value) static noexcept
Swaps the byte order of a 32-bit signed int if the CPU is big-endian.
int64 ByteOrder::swapIfBigEndian (int64 value) static noexcept
Swaps the byte order of a 64-bit signed int if the CPU is big-endian.
float ByteOrder::swapIfBigEndian (float value) static noexcept
Swaps the byte order of a 32-bit float if the CPU is big-endian.
References ByteOrder::swap().
double ByteOrder::swapIfBigEndian (double value) static noexcept
Swaps the byte order of a 64-bit float if the CPU is big-endian.
References ByteOrder::swap().
uint16 ByteOrder::swapIfLittleEndian (uint16 value) static noexcept
Swaps the byte order of a 16-bit unsigned int if the CPU is little-endian.
uint32 ByteOrder::swapIfLittleEndian (uint32 value) static noexcept
Swaps the byte order of a 32-bit unsigned int if the CPU is little-endian.
uint64 ByteOrder::swapIfLittleEndian (uint64 value) static noexcept
Swaps the byte order of a 64-bit unsigned int if the CPU is little-endian.
int16 ByteOrder::swapIfLittleEndian (int16 value) static noexcept
Swaps the byte order of a 16-bit signed int if the CPU is little-endian.
int32 ByteOrder::swapIfLittleEndian (int32 value) static noexcept
Swaps the byte order of a 32-bit signed int if the CPU is little-endian.
int64 ByteOrder::swapIfLittleEndian (int64 value) static noexcept
Swaps the byte order of a 64-bit signed int if the CPU is little-endian.
float ByteOrder::swapIfLittleEndian (float value) static noexcept
Swaps the byte order of a 32-bit float if the CPU is little-endian.
double ByteOrder::swapIfLittleEndian (double value) static noexcept
Swaps the byte order of a 64-bit float if the CPU is little-endian.
uint32 ByteOrder::littleEndianInt (const void * bytes) static noexcept
Turns 4 bytes into a little-endian integer.
uint64 ByteOrder::littleEndianInt64 (const void * bytes) static noexcept
Turns 8 bytes into a little-endian integer.
uint16 ByteOrder::littleEndianShort (const void * bytes) static noexcept
Turns 2 bytes into a little-endian integer.
uint32 ByteOrder::bigEndianInt (const void * bytes) static noexcept
Turns 4 bytes into a big-endian integer.
uint64 ByteOrder::bigEndianInt64 (const void * bytes) static noexcept
Turns 8 bytes into a big-endian integer.
uint16 ByteOrder::bigEndianShort (const void * bytes) static noexcept
Turns 2 bytes into a big-endian integer.
bool ByteOrder::isBigEndian () static noexcept
Returns true if the current CPU is big-endian.
int ByteOrder::littleEndian24Bit (const void * bytes) static noexcept
Converts 3 little-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
int ByteOrder::bigEndian24Bit (const void * bytes) static noexcept
Converts 3 big-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
void ByteOrder::littleEndian24BitToChars (int value, void * destBytes) static noexcept
Copies a 24-bit number to 3 little-endian bytes.
void ByteOrder::bigEndian24BitToChars (int value, void * destBytes) static noexcept
Copies a 24-bit number to 3 big-endian bytes.