JUCE: time
time
juce_core
Classes
class PerformanceCounter
A timer for measuring performance of code and dumping the results to a file.
class ScopedTimeMeasurement
Simple RAII class for measuring the time spent in a scope.
class RelativeTime
A relative measure of time.
class Time
Holds an absolute date and time.
Functions
JUCE_API bool JUCE_CALLTYPE operator== (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator!= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator> (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator< (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator>= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator<= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API RelativeTime JUCE_CALLTYPE operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
JUCE_API RelativeTime JUCE_CALLTYPE operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
JUCE_API Time operator+ (Time time, RelativeTime delta) noexcept
Adds a RelativeTime to a Time.
JUCE_API Time operator+ (RelativeTime delta, Time time) noexcept
Adds a RelativeTime to a Time.
JUCE_API Time operator- (Time time, RelativeTime delta) noexcept
Subtracts a RelativeTime from a Time.
JUCE_API const RelativeTime operator- (Time time1, Time time2) noexcept
Returns the relative time difference between two times.
JUCE_API bool operator== (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator!= (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator< (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator<= (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator> (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator>= (Time time1, Time time2) noexcept
Compares two Time objects.
Detailed Description
Class Documentation
class PerformanceCounter
A timer for measuring performance of code and dumping the results to a file.
e.g.
PerformanceCounter pc ("fish", 50, "/temp/myfishlog.txt");
for (;;)
{
    pc.start();
    doSomethingFishy();
    pc.stop();
}
In this example, the time of each period between calling start/stop will be measured and averaged over 50 runs, and the results printed to a file every 50 times round the loop.
Public Member Functions
PerformanceCounter (const String &counterName, int runsPerPrintout=100, const File &loggingFile=File())
Creates a PerformanceCounter object.
~PerformanceCounter ()
Destructor.
void start () noexcept
Starts timing.
bool stop ()
Stops timing and prints out the results.
void printStatistics ()
Dumps the current metrics to the debugger output and to a file.
Statistics getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
Constructor & Destructor Documentation
PerformanceCounter::PerformanceCounter (const String & counterName, int runsPerPrintout = 100, const File & loggingFile = File())
Creates a PerformanceCounter object.
Parameters
counterName the name used when printing out the statistics
runsPerPrintout the number of start/stop iterations before calling printStatistics()
loggingFile a file to dump the results to - if this is File(), the results are just written to the debugger output
PerformanceCounter::~PerformanceCounter ()
Destructor.
Member Function Documentation
void PerformanceCounter::start () noexcept
Starts timing.
See Also
stop
bool PerformanceCounter::stop ()
Stops timing and prints out the results.
The number of iterations before doing a printout of the results is set in the constructor.
See Also
start
void PerformanceCounter::printStatistics ()
Dumps the current metrics to the debugger output and to a file.
As well as using Logger::outputDebugString to print the results, this will write then to the file specified in the constructor (if this was valid).
Statistics PerformanceCounter::getStatisticsAndReset ()
Returns a copy of the current stats, and resets the internal counter.
class ScopedTimeMeasurement
Simple RAII class for measuring the time spent in a scope.
Example:
{ double timeSec;
{ ScopedTimeMeasurement m (timeSec); doSomething(); }
Logger::writeToLog (String ("doSomething() took ") + String (timeSec) + "seconds"); }
Parameters
resultInSeconds The result of the measurement will be stored in this variable.
Public Member Functions
ScopedTimeMeasurement (double &resultInSeconds) noexcept
~ScopedTimeMeasurement ()
Constructor & Destructor Documentation
ScopedTimeMeasurement::ScopedTimeMeasurement (double & resultInSeconds) noexcept
ScopedTimeMeasurement::~ScopedTimeMeasurement ()
References Time::getHighResolutionTicks(), and Time::getHighResolutionTicksPerSecond().
class RelativeTime
A relative measure of time.
The time is stored as a number of seconds, at double-precision floating point accuracy, and may be positive or negative.
If you need an absolute time, (i.e. a date + time), see the Time class.
Public Member Functions
RelativeTime (double seconds=0.0) noexcept
Creates a RelativeTime.
RelativeTime (const RelativeTime &other) noexcept
Copies another relative time.
RelativeTime & operator= (const RelativeTime &other) noexcept
Copies another relative time.
~RelativeTime () noexcept
Destructor.
int64 inMilliseconds () const noexcept
Returns the number of milliseconds this time represents.
double inSeconds () const noexcept
Returns the number of seconds this time represents.
double inMinutes () const noexcept
Returns the number of minutes this time represents.
double inHours () const noexcept
Returns the number of hours this time represents.
double inDays () const noexcept
Returns the number of days this time represents.
double inWeeks () const noexcept
Returns the number of weeks this time represents.
String getDescription (const String &returnValueForZeroTime="0") const
Returns a readable textual description of the time.
RelativeTime operator+= (RelativeTime timeToAdd) noexcept
Adds another RelativeTime to this one.
RelativeTime operator-= (RelativeTime timeToSubtract) noexcept
Subtracts another RelativeTime from this one.
RelativeTime operator+= (double secondsToAdd) noexcept
Adds a number of seconds to this time.
RelativeTime operator-= (double secondsToSubtract) noexcept
Subtracts a number of seconds from this time.
Static Public Member Functions
static RelativeTime milliseconds (int milliseconds) noexcept
Creates a new RelativeTime object representing a number of milliseconds.
static RelativeTime milliseconds (int64 milliseconds) noexcept
Creates a new RelativeTime object representing a number of milliseconds.
static RelativeTime seconds (double seconds) noexcept
Creates a new RelativeTime object representing a number of seconds.
static RelativeTime minutes (double numberOfMinutes) noexcept
Creates a new RelativeTime object representing a number of minutes.
static RelativeTime hours (double numberOfHours) noexcept
Creates a new RelativeTime object representing a number of hours.
static RelativeTime days (double numberOfDays) noexcept
Creates a new RelativeTime object representing a number of days.
static RelativeTime weeks (double numberOfWeeks) noexcept
Creates a new RelativeTime object representing a number of weeks.
Constructor & Destructor Documentation
RelativeTime::RelativeTime (double seconds = 0.0) explicit noexcept
Creates a RelativeTime.
Parameters
seconds the number of seconds, which may be +ve or -ve.
See Also
milliseconds, minutes, hours, days, weeks
RelativeTime::RelativeTime (const RelativeTime & other) noexcept
Copies another relative time.
RelativeTime::~RelativeTime () noexcept
Destructor.
Member Function Documentation
RelativeTime& RelativeTime::operator= (const RelativeTime & other) noexcept
Copies another relative time.
static RelativeTime RelativeTime::milliseconds (int milliseconds) static noexcept
Creates a new RelativeTime object representing a number of milliseconds.
See Also
seconds, minutes, hours, days, weeks
Referenced by littlefoot::LittleFootRemoteHeap< ImplementationClass >::sendChanges().
static RelativeTime RelativeTime::milliseconds (int64 milliseconds) static noexcept
Creates a new RelativeTime object representing a number of milliseconds.
See Also
seconds, minutes, hours, days, weeks
static RelativeTime RelativeTime::seconds (double seconds) static noexcept
Creates a new RelativeTime object representing a number of seconds.
See Also
milliseconds, minutes, hours, days, weeks
static RelativeTime RelativeTime::minutes (double numberOfMinutes) static noexcept
Creates a new RelativeTime object representing a number of minutes.
See Also
milliseconds, hours, days, weeks
static RelativeTime RelativeTime::hours (double numberOfHours) static noexcept
Creates a new RelativeTime object representing a number of hours.
See Also
milliseconds, minutes, days, weeks
static RelativeTime RelativeTime::days (double numberOfDays) static noexcept
Creates a new RelativeTime object representing a number of days.
See Also
milliseconds, minutes, hours, weeks
static RelativeTime RelativeTime::weeks (double numberOfWeeks) static noexcept
Creates a new RelativeTime object representing a number of weeks.
See Also
milliseconds, minutes, hours, days
int64 RelativeTime::inMilliseconds () const noexcept
Returns the number of milliseconds this time represents.
See Also
milliseconds, inSeconds, inMinutes, inHours, inDays, inWeeks
double RelativeTime::inSeconds () const noexcept
Returns the number of seconds this time represents.
See Also
inMilliseconds, inMinutes, inHours, inDays, inWeeks
double RelativeTime::inMinutes () const noexcept
Returns the number of minutes this time represents.
See Also
inMilliseconds, inSeconds, inHours, inDays, inWeeks
double RelativeTime::inHours () const noexcept
Returns the number of hours this time represents.
See Also
inMilliseconds, inSeconds, inMinutes, inDays, inWeeks
double RelativeTime::inDays () const noexcept
Returns the number of days this time represents.
See Also
inMilliseconds, inSeconds, inMinutes, inHours, inWeeks
double RelativeTime::inWeeks () const noexcept
Returns the number of weeks this time represents.
See Also
inMilliseconds, inSeconds, inMinutes, inHours, inDays
String RelativeTime::getDescription (const String & returnValueForZeroTime = "0") const
Returns a readable textual description of the time.
The exact format of the string returned will depend on the magnitude of the time - e.g.
"1 min 4 secs", "1 hr 45 mins", "2 weeks 5 days", "140 ms"
so that only the two most significant units are printed.
The returnValueForZeroTime value is the result that is returned if the length is zero. Depending on your application you might want to use this to return something more relevant like "empty" or "0 secs", etc.
See Also
inMilliseconds, inSeconds, inMinutes, inHours, inDays, inWeeks
RelativeTime RelativeTime::operator+= (RelativeTime timeToAdd) noexcept
Adds another RelativeTime to this one.
RelativeTime RelativeTime::operator-= (RelativeTime timeToSubtract) noexcept
Subtracts another RelativeTime from this one.
RelativeTime RelativeTime::operator+= (double secondsToAdd) noexcept
Adds a number of seconds to this time.
RelativeTime RelativeTime::operator-= (double secondsToSubtract) noexcept
Subtracts a number of seconds from this time.
class Time
Holds an absolute date and time.
Internally, the time is stored at millisecond precision.
See Also
RelativeTime
Public Member Functions
Time () noexcept
Creates a Time object.
Time (int64 millisecondsSinceEpoch) noexcept
Creates a time based on a number of milliseconds.
Time (int year, int month, int day, int hours, int minutes, int seconds=0, int milliseconds=0, bool useLocalTime=true) noexcept
Creates a time from a set of date components.
Time (const Time &other) noexcept
Creates a copy of another Time object.
~Time () noexcept
Destructor.
Time & operator= (const Time &other) noexcept
Copies this time from another one.
int64 toMilliseconds () const noexcept
Returns the time as a number of milliseconds.
int getYear () const noexcept
Returns the year (in this machine's local timezone).
int getMonth () const noexcept
Returns the number of the month (in this machine's local timezone).
String getMonthName (bool threeLetterVersion) const
Returns the name of the month (in this machine's local timezone).
int getDayOfMonth () const noexcept
Returns the day of the month (in this machine's local timezone).
int getDayOfWeek () const noexcept
Returns the number of the day of the week (in this machine's local timezone).
int getDayOfYear () const noexcept
Returns the number of the day of the year (in this machine's local timezone).
String getWeekdayName (bool threeLetterVersion) const
Returns the name of the weekday (in this machine's local timezone).
int getHours () const noexcept
Returns the number of hours since midnight (in this machine's local timezone).
bool isAfternoon () const noexcept
Returns true if the time is in the afternoon (in this machine's local timezone).
int getHoursInAmPmFormat () const noexcept
Returns the hours in 12-hour clock format (in this machine's local timezone).
int getMinutes () const noexcept
Returns the number of minutes, 0 to 59 (in this machine's local timezone).
int getSeconds () const noexcept
Returns the number of seconds, 0 to 59.
int getMilliseconds () const noexcept
Returns the number of milliseconds, 0 to 999.
bool isDaylightSavingTime () const noexcept
Returns true if the local timezone uses a daylight saving correction.
String getTimeZone () const noexcept
Returns a 3-character string to indicate the local timezone.
int getUTCOffsetSeconds () const noexcept
Returns the local timezone offset from UTC in seconds.
String getUTCOffsetString (bool includeDividerCharacters) const
Returns a string to indicate the offset of the local timezone from UTC.
String toString (bool includeDate, bool includeTime, bool includeSeconds=true, bool use24HourClock=false) const noexcept
Returns a string version of this date and time, using this machine's local timezone.
String formatted (const String &format) const
Converts this date/time to a string with a user-defined format.
String toISO8601 (bool includeDividerCharacters) const
Returns a fully described string of this date and time in ISO-8601 format (using the local timezone).
Time & operator+= (RelativeTime delta) noexcept
Adds a RelativeTime to this time.
Time & operator-= (RelativeTime delta) noexcept
Subtracts a RelativeTime from this time.
bool setSystemTimeToThisTime () const
Tries to set the computer's clock.
Static Public Member Functions
static Time JUCE_CALLTYPE getCurrentTime () noexcept
Returns a Time object that is set to the current system time.
static Time fromISO8601 (StringRef iso8601) noexcept
Parses an ISO-8601 string and returns it as a Time.
static String getWeekdayName (int dayNumber, bool threeLetterVersion)
Returns the name of a day of the week.
static String getMonthName (int monthNumber, bool threeLetterVersion)
Returns the name of one of the months.
static int64 currentTimeMillis () noexcept
Returns the current system time.
static uint32 getMillisecondCounter () noexcept
Returns the number of millisecs since a fixed event (usually system startup).
static double getMillisecondCounterHiRes () noexcept
Returns the number of millisecs since a fixed event (usually system startup).
static void waitForMillisecondCounter (uint32 targetTime) noexcept
Waits until the getMillisecondCounter() reaches a given value.
static uint32 getApproximateMillisecondCounter () noexcept
Less-accurate but faster version of getMillisecondCounter().
static int64 getHighResolutionTicks () noexcept
Returns the current high-resolution counter's tick-count.
static int64 getHighResolutionTicksPerSecond () noexcept
Returns the resolution of the high-resolution counter in ticks per second.
static double highResolutionTicksToSeconds (int64 ticks) noexcept
Converts a number of high-resolution ticks into seconds.
static int64 secondsToHighResolutionTicks (double seconds) noexcept
Converts a number seconds into high-resolution ticks.
static Time getCompilationDate ()
Returns a Time based on the value of the DATE macro when this module was compiled.
Constructor & Destructor Documentation
Time::Time () noexcept
Creates a Time object.
This default constructor creates a time of midnight Jan 1st 1970 UTC, (which is represented internally as 0ms).
To create a time object representing the current time, use getCurrentTime().
See Also
getCurrentTime
Time::Time (int64 millisecondsSinceEpoch) explicit noexcept
Creates a time based on a number of milliseconds.
To create a time object set to the current time, use getCurrentTime().
Parameters
millisecondsSinceEpoch the number of milliseconds since the unix 'epoch' (midnight Jan 1st 1970 UTC).
See Also
getCurrentTime, currentTimeMillis
Time::Time (int year, int month, int day, int hours, int minutes, int seconds = 0, int milliseconds = 0, bool useLocalTime = true) noexcept
Creates a time from a set of date components.
Parameters
year the year, in 4-digit format, e.g. 2004
month the month, in the range 0 to 11
day the day of the month, in the range 1 to 31
hours hours in 24-hour clock format, 0 to 23
minutes minutes 0 to 59
seconds seconds 0 to 59
milliseconds milliseconds 0 to 999
useLocalTime if true, assume input is in this machine's local timezone if false, assume input is in UTC.
Time::Time (const Time & other) noexcept
Creates a copy of another Time object.
Time::~Time () noexcept
Destructor.
Member Function Documentation
Time& Time::operator= (const Time & other) noexcept
Copies this time from another one.
static Time JUCE_CALLTYPE Time::getCurrentTime () static noexcept
Returns a Time object that is set to the current system time.
This may not be monotonic, as the system time can change at any moment. You should therefore not use this method for measuring time intervals.
See Also
currentTimeMillis
Referenced by littlefoot::LittleFootRemoteHeap< ImplementationClass >::sendChanges().
int64 Time::toMilliseconds () const noexcept
Returns the time as a number of milliseconds.
Returns
the number of milliseconds this Time object represents, since midnight Jan 1st 1970 UTC.
See Also
getMilliseconds
int Time::getYear () const noexcept
Returns the year (in this machine's local timezone).
A 4-digit format is used, e.g. 2004.
int Time::getMonth () const noexcept
Returns the number of the month (in this machine's local timezone).
The value returned is in the range 0 to 11.
See Also
getMonthName
String Time::getMonthName (bool threeLetterVersion) const
Returns the name of the month (in this machine's local timezone).
Parameters
threeLetterVersion if true, it'll be a 3-letter abbreviation, e.g. "Jan"; if false it'll return the long form, e.g. "January"
See Also
getMonth
int Time::getDayOfMonth () const noexcept
Returns the day of the month (in this machine's local timezone).
The value returned is in the range 1 to 31.
int Time::getDayOfWeek () const noexcept
Returns the number of the day of the week (in this machine's local timezone).
The value returned is in the range 0 to 6 (0 = sunday, 1 = monday, etc).
int Time::getDayOfYear () const noexcept
Returns the number of the day of the year (in this machine's local timezone).
The value returned is in the range 0 to 365.
String Time::getWeekdayName (bool threeLetterVersion) const
Returns the name of the weekday (in this machine's local timezone).
Parameters
threeLetterVersion if true, it'll return a 3-letter abbreviation, e.g. "Tue"; if false, it'll return the full version, e.g. "Tuesday".
int Time::getHours () const noexcept
Returns the number of hours since midnight (in this machine's local timezone).
This is in 24-hour clock format, in the range 0 to 23.
See Also
getHoursInAmPmFormat, isAfternoon
bool Time::isAfternoon () const noexcept
Returns true if the time is in the afternoon (in this machine's local timezone).
Returns
true for "PM", false for "AM".
See Also
getHoursInAmPmFormat, getHours
int Time::getHoursInAmPmFormat () const noexcept
Returns the hours in 12-hour clock format (in this machine's local timezone).
This will return a value 1 to 12 - use isAfternoon() to find out whether this is in the afternoon or morning.
See Also
getHours, isAfternoon
int Time::getMinutes () const noexcept
Returns the number of minutes, 0 to 59 (in this machine's local timezone).
int Time::getSeconds () const noexcept
Returns the number of seconds, 0 to 59.
int Time::getMilliseconds () const noexcept
Returns the number of milliseconds, 0 to 999.
Unlike toMilliseconds(), this just returns the position within the current second rather than the total number since the epoch.
See Also
toMilliseconds
bool Time::isDaylightSavingTime () const noexcept
Returns true if the local timezone uses a daylight saving correction.
String Time::getTimeZone () const noexcept
Returns a 3-character string to indicate the local timezone.
int Time::getUTCOffsetSeconds () const noexcept
Returns the local timezone offset from UTC in seconds.
String Time::getUTCOffsetString (bool includeDividerCharacters) const
Returns a string to indicate the offset of the local timezone from UTC.
Returns
"+XX:XX", "-XX:XX" or "Z"
Parameters
includeDividerCharacters whether to include or omit the ":" divider in the string
String Time::toString (bool includeDate, bool includeTime, bool includeSeconds = true, bool use24HourClock = false) const noexcept
Returns a string version of this date and time, using this machine's local timezone.
For a more powerful way of formatting the date and time, see the formatted() method.
Parameters
includeDate whether to include the date in the string
includeTime whether to include the time in the string
includeSeconds if the time is being included, this provides an option not to include the seconds in it
use24HourClock if the time is being included, sets whether to use am/pm or 24 hour notation.
See Also
formatted
String Time::formatted (const String & format) const
Converts this date/time to a string with a user-defined format.
This uses the C strftime() function to format this time as a string. To save you looking it up, these are the escape codes that strftime uses (other codes might work on some platforms and not others, but these are the common ones):
a is replaced by the locale's abbreviated weekday name.
A is replaced by the locale's full weekday name.
b is replaced by the locale's abbreviated month name.
B is replaced by the locale's full month name.
c is replaced by the locale's appropriate date and time representation.
d is replaced by the day of the month as a decimal number [01,31].
H is replaced by the hour (24-hour clock) as a decimal number [00,23].
I is replaced by the hour (12-hour clock) as a decimal number [01,12].
j is replaced by the day of the year as a decimal number [001,366].
m is replaced by the month as a decimal number [01,12].
M is replaced by the minute as a decimal number [00,59].
p is replaced by the locale's equivalent of either a.m. or p.m.
S is replaced by the second as a decimal number [00,61].
U is replaced by the week number of the year (Sunday as the first day of the week) as a decimal number [00,53].
w is replaced by the weekday as a decimal number [0,6], with 0 representing Sunday.
W is replaced by the week number of the year (Monday as the first day of the week) as a decimal number [00,53]. All days in a new year preceding the first Monday are considered to be in week 0.
x is replaced by the locale's appropriate date representation.
X is replaced by the locale's appropriate time representation.
y is replaced by the year without century as a decimal number [00,99].
Y is replaced by the year with century as a decimal number.
Z is replaced by the timezone name or abbreviation, or by no bytes if no timezone information exists.
%% is replaced by %.
See Also
toString
String Time::toISO8601 (bool includeDividerCharacters) const
Returns a fully described string of this date and time in ISO-8601 format (using the local timezone).
Parameters
includeDividerCharacters whether to include or omit the "-" and ":" dividers in the string
static Time Time::fromISO8601 (StringRef iso8601) static noexcept
Parses an ISO-8601 string and returns it as a Time.
Time& Time::operator+= (RelativeTime delta) noexcept
Adds a RelativeTime to this time.
Time& Time::operator-= (RelativeTime delta) noexcept
Subtracts a RelativeTime from this time.
bool Time::setSystemTimeToThisTime () const
Tries to set the computer's clock.
Returns
true if this succeeds, although depending on the system, the application might not have sufficient privileges to do this.
static String Time::getWeekdayName (int dayNumber, bool threeLetterVersion) static
Returns the name of a day of the week.
Parameters
dayNumber the day, 0 to 6 (0 = sunday, 1 = monday, etc)
threeLetterVersion if true, it'll return a 3-letter abbreviation, e.g. "Tue"; if false, it'll return the full version, e.g. "Tuesday".
static String Time::getMonthName (int monthNumber, bool threeLetterVersion) static
Returns the name of one of the months.
Parameters
monthNumber the month, 0 to 11
threeLetterVersion if true, it'll be a 3-letter abbreviation, e.g. "Jan"; if false it'll return the long form, e.g. "January"
static int64 Time::currentTimeMillis () static noexcept
Returns the current system time.
Returns the number of milliseconds since midnight Jan 1st 1970 UTC.
Should be accurate to within a few millisecs, depending on platform, hardware, etc.
Referenced by FakeMouseMoveGenerator::timerCallback().
static uint32 Time::getMillisecondCounter () static noexcept
Returns the number of millisecs since a fixed event (usually system startup).
This returns a monotonically increasing value which is unaffected by changes to the system clock. It should be accurate to within a few millisecs, depending on platform, hardware, etc.
Being a 32-bit return value, it will of course wrap back to 0 after 2^32 seconds of uptime, so be careful to take that into account. If you need a 64-bit time, you can use currentTimeMillis() instead.
See Also
getApproximateMillisecondCounter
static double Time::getMillisecondCounterHiRes () static noexcept
Returns the number of millisecs since a fixed event (usually system startup).
This has the same function as getMillisecondCounter(), but returns a more accurate value, using a higher-resolution timer if one is available.
See Also
getMillisecondCounter
static void Time::waitForMillisecondCounter (uint32 targetTime) static noexcept
Waits until the getMillisecondCounter() reaches a given value.
This will make the thread sleep as efficiently as it can while it's waiting.
static uint32 Time::getApproximateMillisecondCounter () static noexcept
Less-accurate but faster version of getMillisecondCounter().
This will return the last value that getMillisecondCounter() returned, so doesn't need to make a system call, but is less accurate - it shouldn't be more than 100ms away from the correct time, though, so is still accurate enough for a lot of purposes.
See Also
getMillisecondCounter
static int64 Time::getHighResolutionTicks () static noexcept
Returns the current high-resolution counter's tick-count.
This is a similar idea to getMillisecondCounter(), but with a higher resolution.
See Also
getHighResolutionTicksPerSecond, highResolutionTicksToSeconds, secondsToHighResolutionTicks
Referenced by ScopedTimeMeasurement::~ScopedTimeMeasurement().
static int64 Time::getHighResolutionTicksPerSecond () static noexcept
Returns the resolution of the high-resolution counter in ticks per second.
See Also
getHighResolutionTicks, highResolutionTicksToSeconds, secondsToHighResolutionTicks
Referenced by ScopedTimeMeasurement::~ScopedTimeMeasurement().
static double Time::highResolutionTicksToSeconds (int64 ticks) static noexcept
Converts a number of high-resolution ticks into seconds.
See Also
getHighResolutionTicks, getHighResolutionTicksPerSecond, secondsToHighResolutionTicks
static int64 Time::secondsToHighResolutionTicks (double seconds) static noexcept
Converts a number seconds into high-resolution ticks.
See Also
getHighResolutionTicks, getHighResolutionTicksPerSecond, highResolutionTicksToSeconds
static Time Time::getCompilationDate () static
Returns a Time based on the value of the DATE macro when this module was compiled.
Function Documentation
JUCE_API bool JUCE_CALLTYPE operator== (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator!= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator> (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator< (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator>= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator<= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API RelativeTime JUCE_CALLTYPE operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
JUCE_API RelativeTime JUCE_CALLTYPE operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
JUCE_API Time operator+ (Time time, RelativeTime delta) noexcept
Adds a RelativeTime to a Time.
JUCE_API Time operator+ (RelativeTime delta, Time time) noexcept
Adds a RelativeTime to a Time.
JUCE_API Time operator- (Time time, RelativeTime delta) noexcept
Subtracts a RelativeTime from a Time.
JUCE_API const RelativeTime operator- (Time time1, Time time2) noexcept
Returns the relative time difference between two times.
JUCE_API bool operator== (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator!= (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator< (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator<= (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator> (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator>= (Time time1, Time time2) noexcept
Compares two Time objects.