JUCE: effects
effects
juce_audio_basics
Classes
class CatmullRomInterpolator
Interpolator for resampling a stream of floats using Catmull-Rom interpolation.
class Decibels
This class contains some helpful static methods for dealing with decibel values.
class IIRCoefficients
A set of coefficients for use in an IIRFilter object.
class IIRFilter
An IIR filter that can perform low, high, or band-pass filtering on an audio signal.
class LagrangeInterpolator
Interpolator for resampling a stream of floats using 4-point lagrange interpolation.
class LinearSmoothedValue< FloatType >
Utility class for linearly smoothed values like volume etc.
class Reverb
Performs a simple reverb effect on a stream of audio data.
Detailed Description
Class Documentation
class CatmullRomInterpolator
Interpolator for resampling a stream of floats using Catmull-Rom interpolation.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own CatmullRomInterpolator object.
See Also
LagrangeInterpolator
Public Member Functions
CatmullRomInterpolator () noexcept
~CatmullRomInterpolator () noexcept
void reset () noexcept
Resets the state of the interpolator.
int process (double speedRatio, const float *inputSamples, float *outputSamples, int numOutputSamplesToProduce) noexcept
Resamples a stream of samples.
int processAdding (double speedRatio, const float *inputSamples, float *outputSamples, int numOutputSamplesToProduce, float gain) noexcept
Resamples a stream of samples, adding the results to the output data with a gain.
Constructor & Destructor Documentation
CatmullRomInterpolator::CatmullRomInterpolator () noexcept
CatmullRomInterpolator::~CatmullRomInterpolator () noexcept
Member Function Documentation
void CatmullRomInterpolator::reset () noexcept
Resets the state of the interpolator.
Call this when there's a break in the continuity of the input data stream.
int CatmullRomInterpolator::process (double speedRatio, const float * inputSamples, float * outputSamples, int numOutputSamplesToProduce) noexcept
Resamples a stream of samples.
Parameters
speedRatio the number of input samples to use for each output sample
inputSamples the source data to read from. This must contain at least (speedRatio * numOutputSamplesToProduce) samples.
outputSamples the buffer to write the results into
numOutputSamplesToProduce the number of output samples that should be created
Returns
the actual number of input samples that were used
int CatmullRomInterpolator::processAdding (double speedRatio, const float * inputSamples, float * outputSamples, int numOutputSamplesToProduce, float gain) noexcept
Resamples a stream of samples, adding the results to the output data with a gain.
Parameters
speedRatio the number of input samples to use for each output sample
inputSamples the source data to read from. This must contain at least (speedRatio * numOutputSamplesToProduce) samples.
outputSamples the buffer to write the results to - the result values will be added to any pre-existing data in this buffer after being multiplied by the gain factor
numOutputSamplesToProduce the number of output samples that should be created
gain a gain factor to multiply the resulting samples by before adding them to the destination buffer
Returns
the actual number of input samples that were used
class Decibels
This class contains some helpful static methods for dealing with decibel values.
Static Public Member Functions
template<typename Type >
static Type decibelsToGain (const Type decibels, const Type minusInfinityDb=(Type) defaultMinusInfinitydB)
Converts a dBFS value to its equivalent gain level.
template<typename Type >
static Type gainToDecibels (const Type gain, const Type minusInfinityDb=(Type) defaultMinusInfinitydB)
Converts a gain level into a dBFS value.
template<typename Type >
static String toString (const Type decibels, const int decimalPlaces=2, const Type minusInfinityDb=(Type) defaultMinusInfinitydB)
Converts a decibel reading to a string, with the 'dB' suffix.
Member Function Documentation
template<typename Type > static Type Decibels::decibelsToGain (const Type decibels, const Type minusInfinityDb = (Type) defaultMinusInfinitydB) static
Converts a dBFS value to its equivalent gain level.
A gain of 1.0 = 0 dB, and lower gains map onto negative decibel values. Any decibel value lower than minusInfinityDb will return a gain of 0.
template<typename Type > static Type Decibels::gainToDecibels (const Type gain, const Type minusInfinityDb = (Type) defaultMinusInfinitydB) static
Converts a gain level into a dBFS value.
A gain of 1.0 = 0 dB, and lower gains map onto negative decibel values. If the gain is 0 (or negative), then the method will return the value provided as minusInfinityDb.
References jmax().
template<typename Type > static String Decibels::toString (const Type decibels, const int decimalPlaces = 2, const Type minusInfinityDb = (Type) defaultMinusInfinitydB) static
Converts a decibel reading to a string, with the 'dB' suffix.
If the decibel value is lower than minusInfinityDb, the return value will be "-INF dB".
class IIRCoefficients
A set of coefficients for use in an IIRFilter object.
See Also
IIRFilter
Public Member Functions
IIRCoefficients () noexcept
Creates a null set of coefficients (which will produce silence).
IIRCoefficients (double c1, double c2, double c3, double c4, double c5, double c6) noexcept
Directly constructs an object from the raw coefficients.
IIRCoefficients (const IIRCoefficients &) noexcept
Creates a copy of another filter.
IIRCoefficients & operator= (const IIRCoefficients &) noexcept
Creates a copy of another filter.
~IIRCoefficients () noexcept
Destructor.
Static Public Member Functions
static IIRCoefficients makeLowPass (double sampleRate, double frequency) noexcept
Returns the coefficients for a low-pass filter.
static IIRCoefficients makeLowPass (double sampleRate, double frequency, double Q) noexcept
Returns the coefficients for a low-pass filter with variable Q.
static IIRCoefficients makeHighPass (double sampleRate, double frequency) noexcept
Returns the coefficients for a high-pass filter.
static IIRCoefficients makeHighPass (double sampleRate, double frequency, double Q) noexcept
Returns the coefficients for a high-pass filter with variable Q.
static IIRCoefficients makeBandPass (double sampleRate, double frequency) noexcept
Returns the coefficients for a band-pass filter.
static IIRCoefficients makeBandPass (double sampleRate, double frequency, double Q) noexcept
Returns the coefficients for a band-pass filter with variable Q.
static IIRCoefficients makeNotchFilter (double sampleRate, double frequency) noexcept
Returns the coefficients for a notch filter.
static IIRCoefficients makeNotchFilter (double sampleRate, double frequency, double Q) noexcept
Returns the coefficients for a notch filter with variable Q.
static IIRCoefficients makeAllPass (double sampleRate, double frequency) noexcept
Returns the coefficients for an all-pass filter.
static IIRCoefficients makeAllPass (double sampleRate, double frequency, double Q) noexcept
Returns the coefficients for an all-pass filter with variable Q.
static IIRCoefficients makeLowShelf (double sampleRate, double cutOffFrequency, double Q, float gainFactor) noexcept
Returns the coefficients for a low-pass shelf filter with variable Q and gain.
static IIRCoefficients makeHighShelf (double sampleRate, double cutOffFrequency, double Q, float gainFactor) noexcept
Returns the coefficients for a high-pass shelf filter with variable Q and gain.
static IIRCoefficients makePeakFilter (double sampleRate, double centreFrequency, double Q, float gainFactor) noexcept
Returns the coefficients for a peak filter centred around a given frequency, with a variable Q and gain.
Public Attributes
float coefficients [5]
The raw coefficients.
Constructor & Destructor Documentation
IIRCoefficients::IIRCoefficients () noexcept
Creates a null set of coefficients (which will produce silence).
IIRCoefficients::IIRCoefficients (double c1, double c2, double c3, double c4, double c5, double c6) noexcept
Directly constructs an object from the raw coefficients.
Most people will want to use the static methods instead of this, but the constructor is public to allow tinkerers to create their own custom filters!
IIRCoefficients::IIRCoefficients (const IIRCoefficients &) noexcept
Creates a copy of another filter.
IIRCoefficients::~IIRCoefficients () noexcept
Destructor.
Member Function Documentation
IIRCoefficients& IIRCoefficients::operator= (const IIRCoefficients &) noexcept
Creates a copy of another filter.
static IIRCoefficients IIRCoefficients::makeLowPass (double sampleRate, double frequency) static noexcept
Returns the coefficients for a low-pass filter.
static IIRCoefficients IIRCoefficients::makeLowPass (double sampleRate, double frequency, double Q) static noexcept
Returns the coefficients for a low-pass filter with variable Q.
static IIRCoefficients IIRCoefficients::makeHighPass (double sampleRate, double frequency) static noexcept
Returns the coefficients for a high-pass filter.
static IIRCoefficients IIRCoefficients::makeHighPass (double sampleRate, double frequency, double Q) static noexcept
Returns the coefficients for a high-pass filter with variable Q.
static IIRCoefficients IIRCoefficients::makeBandPass (double sampleRate, double frequency) static noexcept
Returns the coefficients for a band-pass filter.
static IIRCoefficients IIRCoefficients::makeBandPass (double sampleRate, double frequency, double Q) static noexcept
Returns the coefficients for a band-pass filter with variable Q.
static IIRCoefficients IIRCoefficients::makeNotchFilter (double sampleRate, double frequency) static noexcept
Returns the coefficients for a notch filter.
static IIRCoefficients IIRCoefficients::makeNotchFilter (double sampleRate, double frequency, double Q) static noexcept
Returns the coefficients for a notch filter with variable Q.
static IIRCoefficients IIRCoefficients::makeAllPass (double sampleRate, double frequency) static noexcept
Returns the coefficients for an all-pass filter.
static IIRCoefficients IIRCoefficients::makeAllPass (double sampleRate, double frequency, double Q) static noexcept
Returns the coefficients for an all-pass filter with variable Q.
static IIRCoefficients IIRCoefficients::makeLowShelf (double sampleRate, double cutOffFrequency, double Q, float gainFactor) static noexcept
Returns the coefficients for a low-pass shelf filter with variable Q and gain.
The gain is a scale factor that the low frequencies are multiplied by, so values greater than 1.0 will boost the low frequencies, values less than 1.0 will attenuate them.
static IIRCoefficients IIRCoefficients::makeHighShelf (double sampleRate, double cutOffFrequency, double Q, float gainFactor) static noexcept
Returns the coefficients for a high-pass shelf filter with variable Q and gain.
The gain is a scale factor that the high frequencies are multiplied by, so values greater than 1.0 will boost the high frequencies, values less than 1.0 will attenuate them.
static IIRCoefficients IIRCoefficients::makePeakFilter (double sampleRate, double centreFrequency, double Q, float gainFactor) static noexcept
Returns the coefficients for a peak filter centred around a given frequency, with a variable Q and gain.
The gain is a scale factor that the centre frequencies are multiplied by, so values greater than 1.0 will boost the centre frequencies, values less than 1.0 will attenuate them.
Member Data Documentation
float IIRCoefficients::coefficients[5]
The raw coefficients.
You should leave these numbers alone unless you really know what you're doing.
class IIRFilter
An IIR filter that can perform low, high, or band-pass filtering on an audio signal.
See Also
IIRCoefficient, IIRFilterAudioSource
Public Member Functions
IIRFilter () noexcept
Creates a filter.
IIRFilter (const IIRFilter &) noexcept
Creates a copy of another filter.
~IIRFilter () noexcept
Destructor.
void makeInactive () noexcept
Clears the filter so that any incoming data passes through unchanged.
void setCoefficients (const IIRCoefficients &newCoefficients) noexcept
Applies a set of coefficients to this filter.
IIRCoefficients getCoefficients () const noexcept
Returns the coefficients that this filter is using.
void reset () noexcept
Resets the filter's processing pipeline, ready to start a new stream of data.
void processSamples (float *samples, int numSamples) noexcept
Performs the filter operation on the given set of samples.
float processSingleSampleRaw (float sample) noexcept
Processes a single sample, without any locking or checking.
Protected Member Functions
IIRFilter & operator= (const IIRFilter &)
Protected Attributes
SpinLock processLock
IIRCoefficients coefficients
float v1
float v2
bool active
Constructor & Destructor Documentation
IIRFilter::IIRFilter () noexcept
Creates a filter.
Initially the filter is inactive, so will have no effect on samples that you process with it. Use the setCoefficients() method to turn it into the type of filter needed.
IIRFilter::IIRFilter (const IIRFilter &) noexcept
Creates a copy of another filter.
IIRFilter::~IIRFilter () noexcept
Destructor.
Member Function Documentation
void IIRFilter::makeInactive () noexcept
Clears the filter so that any incoming data passes through unchanged.
void IIRFilter::setCoefficients (const IIRCoefficients & newCoefficients) noexcept
Applies a set of coefficients to this filter.
IIRCoefficients IIRFilter::getCoefficients () const noexcept
Returns the coefficients that this filter is using.
void IIRFilter::reset () noexcept
Resets the filter's processing pipeline, ready to start a new stream of data.
Note that this clears the processing state, but the type of filter and its coefficients aren't changed. To put a filter into an inactive state, use the makeInactive() method.
void IIRFilter::processSamples (float * samples, int numSamples) noexcept
Performs the filter operation on the given set of samples.
float IIRFilter::processSingleSampleRaw (float sample) noexcept
Processes a single sample, without any locking or checking.
Use this if you need fast processing of a single value, but be aware that this isn't thread-safe in the way that processSamples() is.
IIRFilter& IIRFilter::operator= (const IIRFilter &) protected
Member Data Documentation
SpinLock IIRFilter::processLock protected
IIRCoefficients IIRFilter::coefficients protected
float IIRFilter::v1 protected
float IIRFilter::v2 protected
bool IIRFilter::active protected
class LagrangeInterpolator
Interpolator for resampling a stream of floats using 4-point lagrange interpolation.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own LagrangeInterpolator object.
See Also
CatmullRomInterpolator
Public Member Functions
LagrangeInterpolator () noexcept
~LagrangeInterpolator () noexcept
void reset () noexcept
Resets the state of the interpolator.
int process (double speedRatio, const float *inputSamples, float *outputSamples, int numOutputSamplesToProduce) noexcept
Resamples a stream of samples.
int processAdding (double speedRatio, const float *inputSamples, float *outputSamples, int numOutputSamplesToProduce, float gain) noexcept
Resamples a stream of samples, adding the results to the output data with a gain.
Constructor & Destructor Documentation
LagrangeInterpolator::LagrangeInterpolator () noexcept
LagrangeInterpolator::~LagrangeInterpolator () noexcept
Member Function Documentation
void LagrangeInterpolator::reset () noexcept
Resets the state of the interpolator.
Call this when there's a break in the continuity of the input data stream.
int LagrangeInterpolator::process (double speedRatio, const float * inputSamples, float * outputSamples, int numOutputSamplesToProduce) noexcept
Resamples a stream of samples.
Parameters
speedRatio the number of input samples to use for each output sample
inputSamples the source data to read from. This must contain at least (speedRatio * numOutputSamplesToProduce) samples.
outputSamples the buffer to write the results into
numOutputSamplesToProduce the number of output samples that should be created
Returns
the actual number of input samples that were used
int LagrangeInterpolator::processAdding (double speedRatio, const float * inputSamples, float * outputSamples, int numOutputSamplesToProduce, float gain) noexcept
Resamples a stream of samples, adding the results to the output data with a gain.
Parameters
speedRatio the number of input samples to use for each output sample
inputSamples the source data to read from. This must contain at least (speedRatio * numOutputSamplesToProduce) samples.
outputSamples the buffer to write the results to - the result values will be added to any pre-existing data in this buffer after being multiplied by the gain factor
numOutputSamplesToProduce the number of output samples that should be created
gain a gain factor to multiply the resulting samples by before adding them to the destination buffer
Returns
the actual number of input samples that were used
class LinearSmoothedValue
template<typename FloatType>
class LinearSmoothedValue< FloatType >
Utility class for linearly smoothed values like volume etc.
that should not change abruptly but as a linear ramp, to avoid audio glitches.
Public Member Functions
LinearSmoothedValue () noexcept
Constructor.
LinearSmoothedValue (FloatType initialValue) noexcept
Constructor.
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
void setValue (FloatType newValue) noexcept
Set a new target value.
FloatType getNextValue () noexcept
Compute the next value.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
FloatType getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
void applyGain (FloatType *samples, int numSamples) noexcept
Applies a linear smoothed gain to a stream of samples S[i] *= gain.
void applyGain (FloatType *samplesOut, const FloatType *samplesIn, int numSamples) noexcept
Computes output as linear smoothed gain applied to a stream of samples.
void applyGain (AudioBuffer< FloatType > &buffer, int numSamples) noexcept
Applies a linear smoothed gain to a buffer.
Constructor & Destructor Documentation
template<typename FloatType> LinearSmoothedValue< FloatType >::LinearSmoothedValue () noexcept
Constructor.
template<typename FloatType> LinearSmoothedValue< FloatType >::LinearSmoothedValue (FloatType initialValue) noexcept
Constructor.
Member Function Documentation
template<typename FloatType> void LinearSmoothedValue< FloatType >::reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
Parameters
sampleRate The sampling rate
rampLengthInSeconds The duration of the ramp in seconds
Referenced by Oscillator< SampleType >::reset(), and Reverb::setSampleRate().
template<typename FloatType> void LinearSmoothedValue< FloatType >::setValue (FloatType newValue) noexcept
Set a new target value.
Parameters
newValue New target value
Referenced by Oscillator< SampleType >::setFrequency(), and Reverb::setParameters().
template<typename FloatType> FloatType LinearSmoothedValue< FloatType >::getNextValue () noexcept
Compute the next value.
Returns
Smoothed value
Referenced by LinearSmoothedValue< NumericType >::applyGain(), Oscillator< SampleType >::process(), Reverb::processMono(), Oscillator< SampleType >::processSample(), and Reverb::processStereo().
template<typename FloatType> bool LinearSmoothedValue< FloatType >::isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
Referenced by LinearSmoothedValue< NumericType >::applyGain(), and Oscillator< SampleType >::process().
template<typename FloatType> FloatType LinearSmoothedValue< FloatType >::getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
Referenced by Oscillator< SampleType >::getFrequency().
template<typename FloatType> void LinearSmoothedValue< FloatType >::applyGain (FloatType * samples, int numSamples) noexcept
Applies a linear smoothed gain to a stream of samples S[i] *= gain.
Parameters
samples Pointer to a raw array of samples
numSamples Length of array of samples
template<typename FloatType> void LinearSmoothedValue< FloatType >::applyGain (FloatType * samplesOut, const FloatType * samplesIn, int numSamples) noexcept
Computes output as linear smoothed gain applied to a stream of samples.
Sout[i] = Sin[i] * gain
Parameters
samplesOut A pointer to a raw array of output samples
samplesIn A pointer to a raw array of input samples
numSamples The length of the array of samples
template<typename FloatType> void LinearSmoothedValue< FloatType >::applyGain (AudioBuffer< FloatType > & buffer, int numSamples) noexcept
Applies a linear smoothed gain to a buffer.
class Reverb
Performs a simple reverb effect on a stream of audio data.
This is a simple stereo reverb, based on the technique and tunings used in FreeVerb. Use setSampleRate() to prepare it, and then call processStereo() or processMono() to apply the reverb to your audio data.
See Also
ReverbAudioSource
Public Member Functions
Reverb ()
const Parameters & getParameters () const noexcept
Returns the reverb's current parameters.
void setParameters (const Parameters &newParams)
Applies a new set of parameters to the reverb.
void setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
void reset ()
Clears the reverb's buffers.
void processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
void processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
Constructor & Destructor Documentation
Reverb::Reverb ()
References setParameters(), and setSampleRate().
Member Function Documentation
const Parameters& Reverb::getParameters () const noexcept
Returns the reverb's current parameters.
void Reverb::setParameters (const Parameters & newParams)
Applies a new set of parameters to the reverb.
Note that this doesn't attempt to lock the reverb, so if you call this in parallel with the process method, you may get artifacts.
References Reverb::Parameters::dryLevel, Reverb::Parameters::freezeMode, LinearSmoothedValue< FloatType >::setValue(), Reverb::Parameters::wetLevel, and Reverb::Parameters::width.
Referenced by Reverb().
void Reverb::setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
You must call this before the process methods, in order to tell it the correct sample rate.
References jassert, and LinearSmoothedValue< FloatType >::reset().
Referenced by Reverb().
void Reverb::reset ()
Clears the reverb's buffers.
void Reverb::processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
References LinearSmoothedValue< FloatType >::getNextValue(), and jassert.
void Reverb::processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
References LinearSmoothedValue< FloatType >::getNextValue(), and jassert.