JUCE: blocks
blocks
juce_blocks_basics
Classes
class Block
Represents an individual BLOCKS device.
struct BlockConfigManager
class ControlButton
Represents a button on a block device.
struct LEDColour
A simple ARGB colour class for setting LEDs.
class LEDGrid
Represents a 2D grid of LEDs on a block device.
class LEDRow
Represents an LED strip on a device.
class StatusLight
Represents a status LED on a device.
class TouchList< Type >
Utility class to hold a list of TouchSurface::Touch objects with different indices and blockUIDs, where each touch has a mapping to some kind of user-supplied data value.
class TouchSurface
Represents the touch surface of a BLOCKS device.
Detailed Description
Class Documentation
class Block
Represents an individual BLOCKS device.
Inherits ReferenceCountedObject.
Public Types
enum Type {
unknown = 0, lightPadBlock, liveBlock, loopBlock,
developerControlBlock, touchBlock, seaboardBlock
}
The different block types.
using Ptr = juce::ReferenceCountedObjectPtr< Block >
The Block class is reference-counted, so always use a Block::Ptr when you are keeping references to them.
using Array = juce::ReferenceCountedArray< Block >
The Block class is reference-counted, so Block::Array is useful when you are storing lists of them.
using UID = uint64
using Timestamp = uint32
This type is used for timestamping events.
Public Member Functions
virtual ~Block ()
Destructor.
virtual Type getType () const =0
Returns the type of this device.
virtual juce::String getDeviceDescription () const =0
Returns a human-readable description of this device type.
virtual float getBatteryLevel () const =0
Returns the battery level in the range 0.0 to 1.0.
virtual bool isBatteryCharging () const =0
Returns true if the battery is charging.
virtual bool isConnected () const =0
Returns true if this block is connected and active.
virtual bool isMasterBlock () const =0
Returns true if this block is directly connected to the application, as opposed to only being connected to a different block via a connection port.
virtual int getWidth () const =0
Returns the width of the device in logical device units.
virtual int getHeight () const =0
Returns the height of the device in logical device units.
virtual bool isHardwareBlock () const =0
Returns true if the device is a physical hardware block (i.e.
virtual float getMillimetersPerUnit () const =0
Returns the length of one logical device unit as physical millimeters.
virtual LEDGrid * getLEDGrid () const =0
If this block has a grid of LEDs, this will return an object to control it.
virtual LEDRow * getLEDRow () const =0
If this block has a row of LEDs, this will return an object to control it.
virtual juce::Array
< StatusLight * > getStatusLights () const =0
If this block has any status LEDs, this will return an array of objects to control them.
virtual TouchSurface * getTouchSurface () const =0
If this block has a pressure-sensitive surface, this will return an object to access its data.
virtual juce::Array
< ControlButton * > getButtons () const =0
If this block has any control buttons, this will return an array of objects to control them.
virtual bool supportsGraphics () const =0
This returns true if the block supports generating graphics by drawing into a JUCE Graphics context.
virtual juce::Array
< ConnectionPort > getPorts () const =0
Returns a list of the connectors that this device has.
virtual juce::Result setProgram (Program *)=0
Sets the Program to run on this block.
virtual Program * getProgram () const =0
Returns a pointer to the currently loaded program.
virtual void sendProgramEvent (const ProgramEventMessage &)=0
Sends a message to the currently loaded program.
virtual void addProgramEventListener (ProgramEventListener *)
Adds a new listener for custom program events from the block.
virtual void removeProgramEventListener (ProgramEventListener *)
Removes a listener for custom program events from the block.
virtual uint32 getMemorySize ()=0
Returns the size of the data block that setDataByte and other functions can write to.
virtual void setDataByte (size_t offset, uint8 value)=0
Sets a single byte on the littlefoot heap.
virtual void setDataBytes (size_t offset, const void *data, size_t num)=0
Sets multiple bytes on the littlefoot heap.
virtual void setDataBits (uint32 startBit, uint32 numBits, uint32 value)=0
Sets multiple bits on the littlefoot heap.
virtual uint8 getDataByte (size_t offset)=0
Gets a byte from the littlefoot heap.
virtual void saveProgramAsDefault ()=0
Sets the current program as the block's default state.
virtual uint32 getMaxConfigIndex ()=0
Returns the maximum number of config items available.
virtual bool isValidUserConfigIndex (uint32 item)=0
Determine if this is a valid config item index.
virtual int32 getLocalConfigValue (uint32 item)=0
Get local config item value.
virtual void setLocalConfigValue (uint32 item, int32 value)=0
Set local config item value.
virtual void setLocalConfigRange (uint32 item, int32 min, int32 max)=0
Set local config item range.
virtual void setLocalConfigItemActive (uint32 item, bool isActive)=0
Set if config item is active or not.
virtual bool isLocalConfigItemActive (uint32 item)=0
Determine if config item is active or not.
virtual ConfigMetaData getLocalConfigMetaData (uint32 item)=0
Get config item metadata.
virtual void requestFactoryConfigSync ()=0
Request sync of factory config with block.
virtual void resetConfigListActiveStatus ()=0
Reset all items active status.
virtual void factoryReset ()=0
Perform factory reset on Block.
virtual void blockReset ()=0
Reset this Block.
virtual bool setName (const juce::String &name)=0
Set Block name.
virtual void setLogger (std::function< void(const String &)> loggingCallback)=0
Allows the user to provide a function that will receive log messages from the block.
virtual bool sendFirmwareUpdatePacket (const uint8 *data, uint8 size, std::function< void(uint8, uint32)> packetAckCallback)=0
Sends a firmware update packet to a block, and waits for a reply.
virtual void setConfigChangedCallback (std::function< void(Block &, const ConfigMetaData &, uint32)>)=0
Provides a callback that will be called when a config changes.
virtual void addDataInputPortListener (DataInputPortListener *)
Adds a new listener for the data input port.
virtual void removeDataInputPortListener (DataInputPortListener *)
Removes a listener for the data input port.
virtual void sendMessage (const void *messageData, size_t messageSize)=0
Sends a message to the block.
Public Attributes
const juce::String serialNumber
The Block's serial number.
juce::String versionNumber
The Block's version number.
juce::String name
The Block's name.
const UID uid
This Block's UID.
Protected Member Functions
Block (const juce::String &serialNumberToUse)
Block (const juce::String &serial, const juce::String &version, const juce::String &name)
Protected Attributes
juce::ListenerList
< DataInputPortListener > dataInputPortListeners
juce::ListenerList
< ProgramEventListener > programEventListeners
Member Typedef Documentation
using Block::Ptr = juce::ReferenceCountedObjectPtr<Block>
The Block class is reference-counted, so always use a Block::Ptr when you are keeping references to them.
using Block::Array = juce::ReferenceCountedArray<Block>
The Block class is reference-counted, so Block::Array is useful when you are storing lists of them.
using Block::UID = uint64
using Block::Timestamp = uint32
This type is used for timestamping events.
It represents a number of milliseconds since the block device was booted.
Member Enumeration Documentation
enum Block::Type
The different block types.
See Also
Block::getType()
Enumerator
unknown
lightPadBlock
liveBlock
loopBlock
developerControlBlock
touchBlock
seaboardBlock
Constructor & Destructor Documentation
virtual Block::~Block () virtual
Destructor.
Block::Block (const juce::String & serialNumberToUse) protected
Block::Block (const juce::String & serial, const juce::String & version, const juce::String & name) protected
Member Function Documentation
virtual Type Block::getType () const pure virtual
Returns the type of this device.
See Also
Block::Type
virtual juce::String Block::getDeviceDescription () const pure virtual
Returns a human-readable description of this device type.
virtual float Block::getBatteryLevel () const pure virtual
Returns the battery level in the range 0.0 to 1.0.
virtual bool Block::isBatteryCharging () const pure virtual
Returns true if the battery is charging.
virtual bool Block::isConnected () const pure virtual
Returns true if this block is connected and active.
virtual bool Block::isMasterBlock () const pure virtual
Returns true if this block is directly connected to the application, as opposed to only being connected to a different block via a connection port.
See Also
ConnectionPort
virtual int Block::getWidth () const pure virtual
Returns the width of the device in logical device units.
virtual int Block::getHeight () const pure virtual
Returns the height of the device in logical device units.
virtual bool Block::isHardwareBlock () const pure virtual
Returns true if the device is a physical hardware block (i.e.
not a virtual block).
virtual float Block::getMillimetersPerUnit () const pure virtual
Returns the length of one logical device unit as physical millimeters.
virtual LEDGrid* Block::getLEDGrid () const pure virtual
If this block has a grid of LEDs, this will return an object to control it.
Note that the pointer that is returned belongs to this object, and the caller must neither delete it or use it after the lifetime of this Block object has finished. If there are no LEDs, then this method will return nullptr.
virtual LEDRow* Block::getLEDRow () const pure virtual
If this block has a row of LEDs, this will return an object to control it.
Note that the pointer that is returned belongs to this object, and the caller must neither delete it or use it after the lifetime of this Block object has finished. If there are no LEDs, then this method will return nullptr.
virtual juce::Array<StatusLight*> Block::getStatusLights () const pure virtual
If this block has any status LEDs, this will return an array of objects to control them.
Note that the objects in the array belong to this Block object, and the caller must neither delete them or use them after the lifetime of this Block object has finished.
virtual TouchSurface* Block::getTouchSurface () const pure virtual
If this block has a pressure-sensitive surface, this will return an object to access its data.
Note that the pointer returned does is owned by this object, and the caller must neither delete it or use it after the lifetime of this Block object has finished. If the device is not touch-sensitive, then this method will return nullptr.
virtual juce::Array<ControlButton*> Block::getButtons () const pure virtual
If this block has any control buttons, this will return an array of objects to control them.
Note that the objects in the array belong to this Block object, and the caller must neither delete them or use them after the lifetime of this Block object has finished.
virtual bool Block::supportsGraphics () const pure virtual
This returns true if the block supports generating graphics by drawing into a JUCE Graphics context.
This should only be true for virtual on-screen blocks; hardware blocks will instead use the LED Grid for visuals.
virtual juce::Array<ConnectionPort> Block::getPorts () const pure virtual
Returns a list of the connectors that this device has.
virtual juce::Result Block::setProgram (Program *) pure virtual
Sets the Program to run on this block.
The supplied Program's lifetime will be managed by this class, so do not use the Program in other places in your code.
virtual Program* Block::getProgram () const pure virtual
Returns a pointer to the currently loaded program.
virtual void Block::sendProgramEvent (const ProgramEventMessage &) pure virtual
Sends a message to the currently loaded program.
To receive the message the program must provide a littlefoot function called handleMessage with the following form:
void handleMessage (int param1, int param2, int param3)
{
    // Do something with the two integer parameters that the app has sent...
}
virtual void Block::addProgramEventListener (ProgramEventListener *) virtual
Adds a new listener for custom program events from the block.
virtual void Block::removeProgramEventListener (ProgramEventListener *) virtual
Removes a listener for custom program events from the block.
virtual uint32 Block::getMemorySize () pure virtual
Returns the size of the data block that setDataByte and other functions can write to.
virtual void Block::setDataByte (size_t offset, uint8 value) pure virtual
Sets a single byte on the littlefoot heap.
virtual void Block::setDataBytes (size_t offset, const void * data, size_t num) pure virtual
Sets multiple bytes on the littlefoot heap.
virtual void Block::setDataBits (uint32 startBit, uint32 numBits, uint32 value) pure virtual
Sets multiple bits on the littlefoot heap.
virtual uint8 Block::getDataByte (size_t offset) pure virtual
Gets a byte from the littlefoot heap.
virtual void Block::saveProgramAsDefault () pure virtual
Sets the current program as the block's default state.
virtual uint32 Block::getMaxConfigIndex () pure virtual
Returns the maximum number of config items available.
virtual bool Block::isValidUserConfigIndex (uint32 item) pure virtual
Determine if this is a valid config item index.
virtual int32 Block::getLocalConfigValue (uint32 item) pure virtual
Get local config item value.
virtual void Block::setLocalConfigValue (uint32 item, int32 value) pure virtual
Set local config item value.
virtual void Block::setLocalConfigRange (uint32 item, int32 min, int32 max) pure virtual
Set local config item range.
virtual void Block::setLocalConfigItemActive (uint32 item, bool isActive) pure virtual
Set if config item is active or not.
virtual bool Block::isLocalConfigItemActive (uint32 item) pure virtual
Determine if config item is active or not.
virtual ConfigMetaData Block::getLocalConfigMetaData (uint32 item) pure virtual
Get config item metadata.
virtual void Block::requestFactoryConfigSync () pure virtual
Request sync of factory config with block.
virtual void Block::resetConfigListActiveStatus () pure virtual
Reset all items active status.
virtual void Block::factoryReset () pure virtual
Perform factory reset on Block.
virtual void Block::blockReset () pure virtual
Reset this Block.
virtual bool Block::setName (const juce::String & name) pure virtual
Set Block name.
virtual void Block::setLogger (std::function< void(const String &)> loggingCallback) pure virtual
Allows the user to provide a function that will receive log messages from the block.
virtual bool Block::sendFirmwareUpdatePacket (const uint8 * data, uint8 size, std::function< void(uint8, uint32)> packetAckCallback) pure virtual
Sends a firmware update packet to a block, and waits for a reply.
Returns an error code.
virtual void Block::setConfigChangedCallback (std::function< void(Block &, const ConfigMetaData &, uint32)>) pure virtual
Provides a callback that will be called when a config changes.
virtual void Block::addDataInputPortListener (DataInputPortListener *) virtual
Adds a new listener for the data input port.
virtual void Block::removeDataInputPortListener (DataInputPortListener *) virtual
Removes a listener for the data input port.
virtual void Block::sendMessage (const void * messageData, size_t messageSize) pure virtual
Sends a message to the block.
Member Data Documentation
const juce::String Block::serialNumber
The Block's serial number.
juce::String Block::versionNumber
The Block's version number.
juce::String Block::name
The Block's name.
Referenced by Block::ConfigMetaData::operator=(), and Block::ConfigMetaData::operator==().
const UID Block::uid
This Block's UID.
This will be globally unique, and remains constant for a particular device.
juce::ListenerList<DataInputPortListener> Block::dataInputPortListeners protected
juce::ListenerList<ProgramEventListener> Block::programEventListeners protected
struct BlockConfigManager
Public Types
enum ConfigType {
integer, floating, boolean, colour,
options
}
Public Member Functions
void setDeviceIndex (TopologyIndex newDeviceIndex)
void setDeviceComms (PhysicalTopologySource::DeviceConnection *newConn)
int32 getItemValue (ConfigItemId item)
void setItemValue (ConfigItemId item, int32 value)
int32 getItemMin (ConfigItemId item)
void setItemMin (ConfigItemId item, int32 min)
int32 getItemMax (ConfigItemId item)
void setItemMax (ConfigItemId item, int32 max)
bool getItemActive (ConfigItemId item)
void setItemActive (ConfigItemId item, bool isActive)
juce::String getOptionName (ConfigItemId item, uint8 optionIndex)
Block::ConfigMetaData getMetaData (ConfigItemId item)
void resetConfigListActiveStatus ()
void setBlockConfig (ConfigItemId item, int32 value)
void requestBlockConfig (ConfigItemId item)
void requestFactoryConfigSync ()
void requestUserConfigSync ()
void handleConfigUpdateMessage (int32 item, int32 value, int32 min, int32 max)
void handleConfigSetMessage (int32 item, int32 value)
Public Attributes
ConfigDescription configList [numConfigItems]
Static Public Attributes
static constexpr uint32 numConfigItems = 59
Member Enumeration Documentation
enum BlockConfigManager::ConfigType
Enumerator
integer
floating
boolean
colour
options
Member Function Documentation
void BlockConfigManager::setDeviceIndex (TopologyIndex newDeviceIndex)
void BlockConfigManager::setDeviceComms (PhysicalTopologySource::DeviceConnection * newConn)
int32 BlockConfigManager::getItemValue (ConfigItemId item)
void BlockConfigManager::setItemValue (ConfigItemId item, int32 value)
int32 BlockConfigManager::getItemMin (ConfigItemId item)
void BlockConfigManager::setItemMin (ConfigItemId item, int32 min)
References min().
int32 BlockConfigManager::getItemMax (ConfigItemId item)
void BlockConfigManager::setItemMax (ConfigItemId item, int32 max)
References max().
bool BlockConfigManager::getItemActive (ConfigItemId item)
void BlockConfigManager::setItemActive (ConfigItemId item, bool isActive)
juce::String BlockConfigManager::getOptionName (ConfigItemId item, uint8 optionIndex)
Block::ConfigMetaData BlockConfigManager::getMetaData (ConfigItemId item)
void BlockConfigManager::resetConfigListActiveStatus ()
void BlockConfigManager::setBlockConfig (ConfigItemId item, int32 value)
References HostPacketBuilder< maxPacketBytes >::addConfigSetMessage(), HostPacketBuilder< maxPacketBytes >::getData(), HostPacketBuilder< maxPacketBytes >::size(), HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void BlockConfigManager::requestBlockConfig (ConfigItemId item)
References HostPacketBuilder< maxPacketBytes >::addRequestMessage(), HostPacketBuilder< maxPacketBytes >::getData(), HostPacketBuilder< maxPacketBytes >::size(), HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void BlockConfigManager::requestFactoryConfigSync ()
References HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage(), HostPacketBuilder< maxPacketBytes >::getData(), HostPacketBuilder< maxPacketBytes >::size(), HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void BlockConfigManager::requestUserConfigSync ()
References HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage(), HostPacketBuilder< maxPacketBytes >::getData(), HostPacketBuilder< maxPacketBytes >::size(), HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void BlockConfigManager::handleConfigUpdateMessage (int32 item, int32 value, int32 min, int32 max)
References max(), and min().
void BlockConfigManager::handleConfigSetMessage (int32 item, int32 value)
Member Data Documentation
constexpr uint32 BlockConfigManager::numConfigItems = 59 static
ConfigDescription BlockConfigManager::configList[numConfigItems]
class ControlButton
Represents a button on a block device.
Public Types
enum ButtonFunction {
mode, volume, up, down,
scale, chord, arp, sustain,
octave, love, click, snap,
back, playOrPause, record, learn,
button0, button1, button2, button3,
button4, button5, button6, button7,
velocitySensitivity, glideSensitivity, slideSensitivity, pressSensitivity,
liftSensitivity, fixedVelocity, glideLock, pianoMode
}
These are all known types of control buttons.
Public Member Functions
ControlButton (Block &)
virtual ~ControlButton ()
Destructor.
virtual ButtonFunction getType () const =0
Returns the button's type.
virtual juce::String getName () const =0
Returns the button's description.
virtual float getPositionX () const =0
Returns the position of this button on the device, in device units.
virtual float getPositionY () const =0
Returns the position of this button on the device, in device units.
virtual bool hasLight () const =0
Returns true if this button has a controllable light.
virtual bool setLightColour (LEDColour newColour)=0
If the button can light-up, this sets its colour.
void addListener (Listener *)
void removeListener (Listener *)
Public Attributes
Block & block
Protected Attributes
juce::ListenerList< Listener > listeners
Member Enumeration Documentation
enum ControlButton::ButtonFunction
These are all known types of control buttons.
You can find out which buttons a device has by calling getButtons(), and can get the name of a button type with getButtonName().
Enumerator
mode
volume
up
down
scale
chord
arp
sustain
octave
love
click
snap
back
playOrPause
record
learn
button0
button1
button2
button3
button4
button5
button6
button7
velocitySensitivity
glideSensitivity
slideSensitivity
pressSensitivity
liftSensitivity
fixedVelocity
glideLock
pianoMode
Constructor & Destructor Documentation
ControlButton::ControlButton (Block &)
virtual ControlButton::~ControlButton () virtual
Destructor.
Member Function Documentation
virtual ButtonFunction ControlButton::getType () const pure virtual
Returns the button's type.
virtual juce::String ControlButton::getName () const pure virtual
Returns the button's description.
virtual float ControlButton::getPositionX () const pure virtual
Returns the position of this button on the device, in device units.
For buttons that are on the side of the device, this may want to return a value that is beyond the phyiscal block size.
virtual float ControlButton::getPositionY () const pure virtual
Returns the position of this button on the device, in device units.
For buttons that are on the side of the device, this may want to return a value that is beyond the phyiscal block size.
virtual bool ControlButton::hasLight () const pure virtual
Returns true if this button has a controllable light.
virtual bool ControlButton::setLightColour (LEDColour newColour) pure virtual
If the button can light-up, this sets its colour.
void ControlButton::addListener (Listener *)
void ControlButton::removeListener (Listener *)
Member Data Documentation
Block& ControlButton::block
juce::ListenerList<Listener> ControlButton::listeners protected
struct LEDColour
A simple ARGB colour class for setting LEDs.
Public Member Functions
LEDColour () noexcept=default
LEDColour (const LEDColour &) noexcept=default
LEDColour & operator= (const LEDColour &) noexcept=default
LEDColour (uint32 argbColour) noexcept
template<typename ColourType >
LEDColour (const ColourType &colour)
uint8 getAlpha () const noexcept
uint8 getRed () const noexcept
uint8 getGreen () const noexcept
uint8 getBlue () const noexcept
uint32 getARGB () const noexcept
Public Attributes
uint32 argb = 0
Constructor & Destructor Documentation
LEDColour::LEDColour () default noexcept
LEDColour::LEDColour (const LEDColour &) default noexcept
LEDColour::LEDColour (uint32 argbColour) noexcept
template<typename ColourType > LEDColour::LEDColour (const ColourType & colour)
Member Function Documentation
LEDColour& LEDColour::operator= (const LEDColour &) default noexcept
uint8 LEDColour::getAlpha () const noexcept
References argb.
uint8 LEDColour::getRed () const noexcept
References argb.
uint8 LEDColour::getGreen () const noexcept
References argb.
uint8 LEDColour::getBlue () const noexcept
References argb.
uint32 LEDColour::getARGB () const noexcept
References argb.
Member Data Documentation
uint32 LEDColour::argb = 0
Referenced by getAlpha(), getARGB(), getBlue(), getGreen(), and getRed().
class LEDGrid
Represents a 2D grid of LEDs on a block device.
Public Member Functions
LEDGrid (Block &)
virtual ~LEDGrid ()
Destructor.
virtual int getNumColumns () const =0
Returns the number of columns in the LED grid.
virtual int getNumRows () const =0
Returns the number of rows in the LED grid.
void setRenderer (Renderer::Ptr newRenderer) noexcept
Set the visualiser that will create visuals for this block (nullptr for none).
Renderer::Ptr getRenderer () const noexcept
Returns the visualiser currently attached to this block (nullptr for none).
Public Attributes
Block & block
The device that this LEDGrid belongs to.
Constructor & Destructor Documentation
LEDGrid::LEDGrid (Block &)
virtual LEDGrid::~LEDGrid () virtual
Destructor.
Member Function Documentation
virtual int LEDGrid::getNumColumns () const pure virtual
Returns the number of columns in the LED grid.
virtual int LEDGrid::getNumRows () const pure virtual
Returns the number of rows in the LED grid.
void LEDGrid::setRenderer (Renderer::Ptr newRenderer) noexcept
Set the visualiser that will create visuals for this block (nullptr for none).
Note that the LEDGrid will NOT take ownership of this object, so the caller must ensure that it doesn't get deleted while in use here.
Renderer::Ptr LEDGrid::getRenderer () const noexcept
Returns the visualiser currently attached to this block (nullptr for none).
Member Data Documentation
Block& LEDGrid::block
The device that this LEDGrid belongs to.
class LEDRow
Represents an LED strip on a device.
Public Member Functions
LEDRow (Block &)
virtual ~LEDRow ()
Destructor.
virtual int getNumLEDs () const =0
Return the number of LEDs in the row.
virtual void setLEDColour (int index, LEDColour newColour)=0
Sets the colour of the corresponding LED.
virtual void setOverlayColour (LEDColour newColour)=0
Overlays all LEDs with a single colour.
virtual void resetOverlayColour ()=0
Public Attributes
Block & block
The device that these lights belong to.
Constructor & Destructor Documentation
LEDRow::LEDRow (Block &)
virtual LEDRow::~LEDRow () virtual
Destructor.
Member Function Documentation
virtual int LEDRow::getNumLEDs () const pure virtual
Return the number of LEDs in the row.
virtual void LEDRow::setLEDColour (int index, LEDColour newColour) pure virtual
Sets the colour of the corresponding LED.
virtual void LEDRow::setOverlayColour (LEDColour newColour) pure virtual
Overlays all LEDs with a single colour.
Whilst the overlay is set subsequent calls to setLEDColour will happen behind* the overlay, and will be invisible to the user until the overlay is removed.
virtual void LEDRow::resetOverlayColour () pure virtual
Member Data Documentation
Block& LEDRow::block
The device that these lights belong to.
class StatusLight
Represents a status LED on a device.
Public Member Functions
StatusLight (Block &)
virtual ~StatusLight ()
Destructor.
virtual juce::String getName () const =0
Returns a name to describe this light.
virtual bool setColour (LEDColour newColour)=0
Changes the light's colour.
Public Attributes
Block & block
The device that this LED belongs to.
Constructor & Destructor Documentation
StatusLight::StatusLight (Block &)
virtual StatusLight::~StatusLight () virtual
Destructor.
Member Function Documentation
virtual juce::String StatusLight::getName () const pure virtual
Returns a name to describe this light.
virtual bool StatusLight::setColour (LEDColour newColour) pure virtual
Changes the light's colour.
Member Data Documentation
Block& StatusLight::block
The device that this LED belongs to.
class TouchList
template<typename Type>
class TouchList< Type >
Utility class to hold a list of TouchSurface::Touch objects with different indices and blockUIDs, where each touch has a mapping to some kind of user-supplied data value.
The Type template is a user-defined type of object that will be stored for each touch element. The type must be default-constructable and copyable.
Public Member Functions
TouchList ()
Creates an empty touch list.
~TouchList ()
Destructor.
int size () const noexcept
Returns the number of entries in the touch list.
Type & getValue (const TouchSurface::Touch &touch)
Returns the user data object that corresponds to the given touch.
bool contains (const TouchSurface::Touch &touch) const noexcept
Returns true if a touch is already in the list.
void updateTouch (const TouchSurface::Touch &touch)
Updates the entry for the given touch, copying in the new state.
TouchEntry * find (const TouchSurface::Touch &touch) const noexcept
If a touch is in the list, returns a pointer to the TouchEntry.
TouchEntry * begin () const noexcept
Allows iterator access to the list of touch entries.
TouchEntry * end () const noexcept
Allows iterator access to the list of touch entries.
TouchEntry & operator[] (const int index)
Retrieve a reference to particular item in the list of touch entires.
void clear () noexcept
Resets all contents, doest not generate any call-backs.
Constructor & Destructor Documentation
template<typename Type > TouchList< Type >::TouchList ()
Creates an empty touch list.
template<typename Type > TouchList< Type >::~TouchList ()
Destructor.
Member Function Documentation
template<typename Type > int TouchList< Type >::size () const noexcept
Returns the number of entries in the touch list.
template<typename Type > Type& TouchList< Type >::getValue (const TouchSurface::Touch & touch)
Returns the user data object that corresponds to the given touch.
This will also update the stored state of the TouchEntry::touch value for this touch index.
References TouchList< Type >::find().
template<typename Type > bool TouchList< Type >::contains (const TouchSurface::Touch & touch) const noexcept
Returns true if a touch is already in the list.
References TouchList< Type >::find().
Referenced by TouchList< Type >::updateTouch().
template<typename Type > void TouchList< Type >::updateTouch (const TouchSurface::Touch & touch)
Updates the entry for the given touch, copying in the new state.
If no entry with the same index and blockUID exists then a new entry is created. If given a touch which is a touch-end, this will remove any corresponding entries from the list.
References TouchList< Type >::contains(), TouchList< Type >::find(), TouchSurface::Touch::isTouchEnd, and jassert.
template<typename Type > TouchEntry* TouchList< Type >::find (const TouchSurface::Touch & touch) const noexcept
If a touch is in the list, returns a pointer to the TouchEntry.
Otherwise, returns nullptr.
Referenced by TouchList< Type >::contains(), TouchList< Type >::getValue(), and TouchList< Type >::updateTouch().
template<typename Type > TouchEntry* TouchList< Type >::begin () const noexcept
Allows iterator access to the list of touch entries.
template<typename Type > TouchEntry* TouchList< Type >::end () const noexcept
Allows iterator access to the list of touch entries.
template<typename Type > TouchEntry& TouchList< Type >::operator[] (const int index)
Retrieve a reference to particular item in the list of touch entires.
template<typename Type > void TouchList< Type >::clear () noexcept
Resets all contents, doest not generate any call-backs.
class TouchSurface
Represents the touch surface of a BLOCKS device.
Public Member Functions
TouchSurface (Block &)
virtual ~TouchSurface ()
Destructor.
virtual void cancelAllActiveTouches () noexcept=0
Forces a touch-off message for all active touches.
virtual int getNumberOfKeywaves () const =0
For the on-screen seaboard view, this will return the number of keys.
void callListenersTouchChanged (const TouchSurface::Touch &t)
Testing feature: this allows you to inject touches onto a touch surface.
void addListener (Listener *)
Adds a listener to be called when the surface is touched.
void removeListener (Listener *)
Removes a previously-registered listener.
Public Attributes
Block & block
The block that owns this touch surface.
Protected Attributes
juce::ListenerList< Listener > listeners
Constructor & Destructor Documentation
TouchSurface::TouchSurface (Block &)
virtual TouchSurface::~TouchSurface () virtual
Destructor.
Member Function Documentation
virtual void TouchSurface::cancelAllActiveTouches () pure virtual noexcept
Forces a touch-off message for all active touches.
virtual int TouchSurface::getNumberOfKeywaves () const pure virtual
For the on-screen seaboard view, this will return the number of keys.
For other types of touch-surface, it will return 0.
void TouchSurface::callListenersTouchChanged (const TouchSurface::Touch & t)
Testing feature: this allows you to inject touches onto a touch surface.
References listeners, and TouchSurface::Listener::touchChanged().
void TouchSurface::addListener (Listener *)
Adds a listener to be called when the surface is touched.
void TouchSurface::removeListener (Listener *)
Removes a previously-registered listener.
Member Data Documentation
Block& TouchSurface::block
The block that owns this touch surface.
juce::ListenerList<Listener> TouchSurface::listeners protected
Referenced by callListenersTouchChanged().