JUCE: processors
processors
juce_audio_processors
Classes
class AudioPluginInstance
Base class for an active instance of a plugin.
class AudioProcessor
Base class for audio processing filters or plugins.
class AudioProcessorEditor
Base class for the component that acts as the GUI for an AudioProcessor.
class AudioProcessorGraph
A type of AudioProcessor which plays back a graph of other AudioProcessors.
class AudioProcessorListener
Base class for listeners that want to know about changes to an AudioProcessor.
class AudioProcessorParameter
An abstract base class for parameter objects that can be added to an AudioProcessor.
class GenericAudioProcessorEditor
A type of UI component that displays the parameters of an AudioProcessor as a simple list of sliders.
class PluginDescription
A small class to represent some facts about a particular type of plug-in.
Detailed Description
Class Documentation
class AudioPluginInstance
Base class for an active instance of a plugin.
This derives from the AudioProcessor class, and adds some extra functionality that helps when wrapping dynamically loaded plugins.
This class is not needed when writing plugins, and you should never need to derive your own sub-classes from it. The plugin hosting classes use it internally and will return AudioPluginInstance objects which wrap external plugins.
See Also
AudioProcessor, AudioPluginFormat
Public Member Functions
virtual ~AudioPluginInstance ()
Destructor.
virtual void fillInPluginDescription (PluginDescription &description) const =0
Fills-in the appropriate parts of this plugin description object.
PluginDescription getPluginDescription () const
Returns a PluginDescription for this plugin.
virtual void * getPlatformSpecificData ()
Returns a pointer to some kind of platform-specific data about the plugin.
virtual void refreshParameterList ()
For some formats (currently AudioUnit), this forces a reload of the list of available parameters.
Public Member Functions inherited from AudioProcessor
virtual ~AudioProcessor ()
Destructor.
virtual const String getName () const =0
Returns the name of this processor.
virtual StringArray getAlternateDisplayNames () const
Returns a list of alternative names to use for this processor.
virtual void prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock)=0
Called before playback starts, to let the filter prepare itself.
virtual void releaseResources ()=0
Called after playback has stopped, to let the filter free up any resources it no longer needs.
virtual void processBlock (AudioBuffer< float > &buffer, MidiBuffer &midiMessages)=0
Renders the next block.
virtual void processBlock (AudioBuffer< double > &buffer, MidiBuffer &midiMessages)
Renders the next block.
virtual void processBlockBypassed (AudioBuffer< float > &buffer, MidiBuffer &midiMessages)
Renders the next block when the processor is being bypassed.
virtual void processBlockBypassed (AudioBuffer< double > &buffer, MidiBuffer &midiMessages)
Renders the next block when the processor is being bypassed.
int getBusCount (bool isInput) const noexcept
Returns the number of buses on the input or output side.
Bus * getBus (bool isInput, int busIdx) noexcept
Returns the audio bus with a given index and direction.
const Bus * getBus (bool isInput, int busIdx) const noexcept
Returns the audio bus with a given index and direction.
virtual bool canAddBus (bool isInput) const
Callback to query if a bus can currently be added.
virtual bool canRemoveBus (bool isInput) const
Callback to query if the last bus can currently be removed.
bool addBus (bool isInput)
Dynamically request an additional bus.
bool removeBus (bool isInput)
Dynamically remove the latest added bus.
bool setBusesLayout (const BusesLayout &)
Set the channel layouts of this audio processor.
bool setBusesLayoutWithoutEnabling (const BusesLayout &)
Set the channel layouts of this audio processor without changing the enablement state of the buses.
BusesLayout getBusesLayout () const
Provides the current channel layouts of this audio processor.
AudioChannelSet getChannelLayoutOfBus (bool isInput, int busIndex) const noexcept
Provides the channel layout of the bus with a given index and direction.
bool setChannelLayoutOfBus (bool isInput, int busIdx, const AudioChannelSet &layout)
Set the channel layout of the bus with a given index and direction.
int getChannelCountOfBus (bool isInput, int busIdx) const noexcept
Provides the number of channels of the bus with a given index and direction.
bool enableAllBuses ()
Enables all buses.
bool disableNonMainBuses ()
Disables all non-main buses (aux and sidechains).
int getChannelIndexInProcessBlockBuffer (bool isInput, int busIndex, int channelIndex) const noexcept
Returns the position of a bus's channels within the processBlock buffer.
int getOffsetInBusBufferForAbsoluteChannelIndex (bool isInput, int absoluteChannelIndex, int &busIdx) const noexcept
Returns the offset in a bus's buffer from an absolute channel indes.
template<typename FloatType >
AudioBuffer< FloatType > getBusBuffer (AudioBuffer< FloatType > &processBlockBuffer, bool isInput, int busIndex) const
Returns an AudioBuffer containing a set of channel pointers for a specific bus.
bool checkBusesLayoutSupported (const BusesLayout &) const
Returns true if the Audio processor is likely to support a given layout.
virtual bool supportsDoublePrecisionProcessing () const
Returns true if the Audio processor supports double precision floating point processing.
ProcessingPrecision getProcessingPrecision () const noexcept
Returns the precision-mode of the processor.
bool isUsingDoublePrecision () const noexcept
Returns true if the current precision is set to doublePrecision.
void setProcessingPrecision (ProcessingPrecision newPrecision) noexcept
Changes the processing precision of the receiver.
AudioPlayHead * getPlayHead () const noexcept
Returns the current AudioPlayHead object that should be used to find out the state and position of the playhead.
int getTotalNumInputChannels () const noexcept
Returns the total number of input channels.
int getTotalNumOutputChannels () const noexcept
Returns the total number of output channels.
int getMainBusNumInputChannels () const noexcept
Returns the number of input channels on the main bus.
int getMainBusNumOutputChannels () const noexcept
Returns the number of output channels on the main bus.
template<int numLayouts>
BusesLayout getNextBestLayoutInLayoutList (const BusesLayout &layouts, const short(&channelLayoutList)[numLayouts][2])
Returns the next best layout which is contained in a channel layout map.
double getSampleRate () const noexcept
Returns the current sample rate.
int getBlockSize () const noexcept
Returns the current typical block size that is being used.
int getLatencySamples () const noexcept
This returns the number of samples delay that the filter imposes on the audio passing through it.
void setLatencySamples (int newLatency)
The filter should call this to set the number of samples delay that it introduces.
virtual double getTailLengthSeconds () const =0
Returns the length of the filter's tail, in seconds.
virtual bool acceptsMidi () const =0
Returns true if the processor wants midi messages.
virtual bool producesMidi () const =0
Returns true if the processor produces midi messages.
virtual bool supportsMPE () const
Returns true if the processor supports MPE.
virtual bool isMidiEffect () const
Returns true if this is a midi effect plug-in and does no audio processing.
const CriticalSection & getCallbackLock () const noexcept
This returns a critical section that will automatically be locked while the host is calling the processBlock() method.
void suspendProcessing (bool shouldBeSuspended)
Enables and disables the processing callback.
bool isSuspended () const noexcept
Returns true if processing is currently suspended.
virtual void reset ()
A plugin can override this to be told when it should reset any playing voices.
bool isNonRealtime () const noexcept
Returns true if the processor is being run in an offline mode for rendering.
virtual void setNonRealtime (bool isNonRealtime) noexcept
Called by the host to tell this processor whether it's being used in a non-realtime capacity for offline rendering or bouncing.
virtual AudioProcessorEditor * createEditor ()=0
Creates the filter's UI.
virtual bool hasEditor () const =0
Your filter must override this and return true if it can create an editor component.
AudioProcessorEditor * getActiveEditor () const noexcept
Returns the active editor, if there is one.
AudioProcessorEditor * createEditorIfNeeded ()
Returns the active editor, or if there isn't one, it will create one.
virtual int getNumParameters ()
This must return the correct value immediately after the object has been created, and mustn't change the number of parameters later.
virtual const String getParameterName (int parameterIndex)
Returns the name of a particular parameter.
virtual String getParameterID (int index)
Returns the ID of a particular parameter.
virtual float getParameter (int parameterIndex)
Called by the host to find out the value of one of the filter's parameters.
virtual String getParameterName (int parameterIndex, int maximumStringLength)
Returns the name of a parameter as a text string with a preferred maximum length.
virtual const String getParameterText (int parameterIndex)
Returns the value of a parameter as a text string.
virtual String getParameterText (int parameterIndex, int maximumStringLength)
Returns the value of a parameter as a text string with a preferred maximum length.
virtual int getParameterNumSteps (int parameterIndex)
Returns the number of discrete steps that this parameter can represent.
virtual float getParameterDefaultValue (int parameterIndex)
Returns the default value for the parameter.
virtual String getParameterLabel (int index) const
Some plugin types may be able to return a label string for a parameter's units.
virtual bool isParameterOrientationInverted (int index) const
This can be overridden to tell the host that particular parameters operate in the reverse direction.
virtual void setParameter (int parameterIndex, float newValue)
The host will call this method to change the value of one of the filter's parameters.
void setParameterNotifyingHost (int parameterIndex, float newValue)
Your filter can call this when it needs to change one of its parameters.
virtual bool isParameterAutomatable (int parameterIndex) const
Returns true if the host can automate this parameter.
virtual bool isMetaParameter (int parameterIndex) const
Should return true if this parameter is a "meta" parameter.
virtual
AudioProcessorParameter::Category getParameterCategory (int parameterIndex) const
Should return the parameter's category.
void beginParameterChangeGesture (int parameterIndex)
Sends a signal to the host to tell it that the user is about to start changing this parameter.
void endParameterChangeGesture (int parameterIndex)
Tells the host that the user has finished changing this parameter.
void updateHostDisplay ()
The filter can call this when something (apart from a parameter value) has changed.
void addParameter (AudioProcessorParameter *)
Adds a parameter to the list.
const OwnedArray
< AudioProcessorParameter > & getParameters () const noexcept
Returns the current list of parameters.
virtual int getNumPrograms ()=0
Returns the number of preset programs the filter supports.
virtual int getCurrentProgram ()=0
Returns the number of the currently active program.
virtual void setCurrentProgram (int index)=0
Called by the host to change the current program.
virtual const String getProgramName (int index)=0
Must return the name of a given program.
virtual void changeProgramName (int index, const String &newName)=0
Called by the host to rename a program.
virtual void getStateInformation (juce::MemoryBlock &destData)=0
The host will call this method when it wants to save the filter's internal state.
virtual void getCurrentProgramStateInformation (juce::MemoryBlock &destData)
The host will call this method if it wants to save the state of just the filter's current program.
virtual void setStateInformation (const void *data, int sizeInBytes)=0
This must restore the filter's state from a block of data previously created using getStateInformation().
virtual void setCurrentProgramStateInformation (const void *data, int sizeInBytes)
The host will call this method if it wants to restore the state of just the filter's current program.
virtual void numChannelsChanged ()
This method is called when the total number of input or output channels is changed.
virtual void numBusesChanged ()
This method is called when the number of buses is changed.
virtual void processorLayoutsChanged ()
This method is called when the layout of the audio processor changes.
virtual void addListener (AudioProcessorListener *newListener)
Adds a listener that will be called when an aspect of this processor changes.
virtual void removeListener (AudioProcessorListener *listenerToRemove)
Removes a previously added listener.
virtual void setPlayHead (AudioPlayHead *newPlayHead)
Tells the processor to use this playhead object.
void setPlayConfigDetails (int numIns, int numOuts, double sampleRate, int blockSize)
This is called by the processor to specify its details before being played.
void setRateAndBufferSizeDetails (double sampleRate, int blockSize) noexcept
This is called by the processor to specify its details before being played.
virtual int32 getAAXPluginIDForMainBusConfig (const AudioChannelSet &mainInputLayout, const AudioChannelSet &mainOutputLayout, bool idForAudioSuite) const
AAX plug-ins need to report a unique "plug-in id" for every audio layout configuration that your AudioProcessor supports on the main bus.
void editorBeingDeleted (AudioProcessorEditor *) noexcept
Not for public use - this is called before deleting an editor component.
virtual void updateTrackProperties (const TrackProperties &properties)
Informs the AudioProcessor that track properties such as the track's name or colour has been changed.
Protected Member Functions
AudioPluginInstance ()
AudioPluginInstance (const BusesProperties &ioLayouts)
template<int numLayouts>
AudioPluginInstance (const short channelLayoutList[numLayouts][2])
Protected Member Functions inherited from AudioProcessor
AudioProcessor ()
Constructor.
AudioProcessor (const BusesProperties &ioLayouts)
Constructor for multibus AudioProcessors.
AudioProcessor (const std::initializer_list< const short[2]> &channelLayoutList)
Constructor for AudioProcessors which use layout maps.
virtual bool isBusesLayoutSupported (const BusesLayout &) const
Callback to query if the AudioProcessor supports a specific layout.
virtual bool canApplyBusesLayout (const BusesLayout &layouts) const
Callback to check if a certain bus layout can now be applied.
virtual bool canApplyBusCountChange (bool isInput, bool isAddingBuses, BusProperties &outNewBusProperties)
Callback to query if adding/removing buses currently possible.
void sendParamChangeMessageToListeners (int parameterIndex, float newValue)
Additional Inherited Members
Public Types inherited from AudioProcessor
enum ProcessingPrecision { singlePrecision, doublePrecision }
enum WrapperType {
wrapperType_Undefined = 0, wrapperType_VST, wrapperType_VST3, wrapperType_AudioUnit,
wrapperType_AudioUnitv3, wrapperType_RTAS, wrapperType_AAX, wrapperType_Standalone
}
Flags to indicate the type of plugin context in which a processor is being used.
Static Public Member Functions inherited from AudioProcessor
static bool containsLayout (const BusesLayout &layouts, const std::initializer_list< const short[2]> &channelLayoutList)
Returns true if the channel layout map contains a certain layout.
template<int numLayouts>
static bool containsLayout (const BusesLayout &layouts, const short(&channelLayoutList)[numLayouts][2])
static int getDefaultNumParameterSteps () noexcept
Returns the default number of steps for a parameter.
static void copyXmlToBinary (const XmlElement &xml, juce::MemoryBlock &destData)
Helper function that just converts an xml element into a binary blob.
static XmlElement * getXmlFromBinary (const void *data, int sizeInBytes)
Retrieves an XML element that was stored as binary with the copyXmlToBinary() method.
static void JUCE_CALLTYPE setTypeOfNextNewPlugin (WrapperType)
Public Attributes inherited from AudioProcessor
WrapperType wrapperType
When loaded by a plugin wrapper, this flag will be set to indicate the type of plugin within which the processor is running.
Protected Attributes inherited from AudioProcessor
AudioPlayHead * playHead
Constructor & Destructor Documentation
virtual AudioPluginInstance::~AudioPluginInstance () virtual
Destructor.
Make sure that you delete any UI components that belong to this plugin before deleting the plugin.
AudioPluginInstance::AudioPluginInstance () protected
AudioPluginInstance::AudioPluginInstance (const BusesProperties & ioLayouts) protected
template<int numLayouts> AudioPluginInstance::AudioPluginInstance (const short channelLayoutList[numLayouts][2]) protected
Member Function Documentation
virtual void AudioPluginInstance::fillInPluginDescription (PluginDescription & description) const pure virtual
Fills-in the appropriate parts of this plugin description object.
Implemented in AudioProcessorGraph::AudioGraphIOProcessor.
PluginDescription AudioPluginInstance::getPluginDescription () const
Returns a PluginDescription for this plugin.
This is just a convenience method to avoid calling fillInPluginDescription.
virtual void* AudioPluginInstance::getPlatformSpecificData () virtual
Returns a pointer to some kind of platform-specific data about the plugin.
E.g. For a VST, this value can be cast to an AEffect*. For an AudioUnit, it can be cast to an AudioUnit handle.
virtual void AudioPluginInstance::refreshParameterList () virtual
For some formats (currently AudioUnit), this forces a reload of the list of available parameters.
class AudioProcessor
Base class for audio processing filters or plugins.
This is intended to act as a base class of audio filter that is general enough to be wrapped as a VST, AU, RTAS, etc, or used internally.
It is also used by the plugin hosting code as the wrapper around an instance of a loaded plugin.
Derive your filter class from this base class, and if you're building a plugin, you should implement a global function called createPluginFilter() which creates and returns a new instance of your subclass.
Public Types
enum ProcessingPrecision { singlePrecision, doublePrecision }
enum WrapperType {
wrapperType_Undefined = 0, wrapperType_VST, wrapperType_VST3, wrapperType_AudioUnit,
wrapperType_AudioUnitv3, wrapperType_RTAS, wrapperType_AAX, wrapperType_Standalone
}
Flags to indicate the type of plugin context in which a processor is being used.
Public Member Functions
virtual ~AudioProcessor ()
Destructor.
virtual const String getName () const =0
Returns the name of this processor.
virtual StringArray getAlternateDisplayNames () const
Returns a list of alternative names to use for this processor.
virtual void prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock)=0
Called before playback starts, to let the filter prepare itself.
virtual void releaseResources ()=0
Called after playback has stopped, to let the filter free up any resources it no longer needs.
virtual void processBlock (AudioBuffer< float > &buffer, MidiBuffer &midiMessages)=0
Renders the next block.
virtual void processBlock (AudioBuffer< double > &buffer, MidiBuffer &midiMessages)
Renders the next block.
virtual void processBlockBypassed (AudioBuffer< float > &buffer, MidiBuffer &midiMessages)
Renders the next block when the processor is being bypassed.
virtual void processBlockBypassed (AudioBuffer< double > &buffer, MidiBuffer &midiMessages)
Renders the next block when the processor is being bypassed.
int getBusCount (bool isInput) const noexcept
Returns the number of buses on the input or output side.
Bus * getBus (bool isInput, int busIdx) noexcept
Returns the audio bus with a given index and direction.
const Bus * getBus (bool isInput, int busIdx) const noexcept
Returns the audio bus with a given index and direction.
virtual bool canAddBus (bool isInput) const
Callback to query if a bus can currently be added.
virtual bool canRemoveBus (bool isInput) const
Callback to query if the last bus can currently be removed.
bool addBus (bool isInput)
Dynamically request an additional bus.
bool removeBus (bool isInput)
Dynamically remove the latest added bus.
bool setBusesLayout (const BusesLayout &)
Set the channel layouts of this audio processor.
bool setBusesLayoutWithoutEnabling (const BusesLayout &)
Set the channel layouts of this audio processor without changing the enablement state of the buses.
BusesLayout getBusesLayout () const
Provides the current channel layouts of this audio processor.
AudioChannelSet getChannelLayoutOfBus (bool isInput, int busIndex) const noexcept
Provides the channel layout of the bus with a given index and direction.
bool setChannelLayoutOfBus (bool isInput, int busIdx, const AudioChannelSet &layout)
Set the channel layout of the bus with a given index and direction.
int getChannelCountOfBus (bool isInput, int busIdx) const noexcept
Provides the number of channels of the bus with a given index and direction.
bool enableAllBuses ()
Enables all buses.
bool disableNonMainBuses ()
Disables all non-main buses (aux and sidechains).
int getChannelIndexInProcessBlockBuffer (bool isInput, int busIndex, int channelIndex) const noexcept
Returns the position of a bus's channels within the processBlock buffer.
int getOffsetInBusBufferForAbsoluteChannelIndex (bool isInput, int absoluteChannelIndex, int &busIdx) const noexcept
Returns the offset in a bus's buffer from an absolute channel indes.
template<typename FloatType >
AudioBuffer< FloatType > getBusBuffer (AudioBuffer< FloatType > &processBlockBuffer, bool isInput, int busIndex) const
Returns an AudioBuffer containing a set of channel pointers for a specific bus.
bool checkBusesLayoutSupported (const BusesLayout &) const
Returns true if the Audio processor is likely to support a given layout.
virtual bool supportsDoublePrecisionProcessing () const
Returns true if the Audio processor supports double precision floating point processing.
ProcessingPrecision getProcessingPrecision () const noexcept
Returns the precision-mode of the processor.
bool isUsingDoublePrecision () const noexcept
Returns true if the current precision is set to doublePrecision.
void setProcessingPrecision (ProcessingPrecision newPrecision) noexcept
Changes the processing precision of the receiver.
AudioPlayHead * getPlayHead () const noexcept
Returns the current AudioPlayHead object that should be used to find out the state and position of the playhead.
int getTotalNumInputChannels () const noexcept
Returns the total number of input channels.
int getTotalNumOutputChannels () const noexcept
Returns the total number of output channels.
int getMainBusNumInputChannels () const noexcept
Returns the number of input channels on the main bus.
int getMainBusNumOutputChannels () const noexcept
Returns the number of output channels on the main bus.
template<int numLayouts>
BusesLayout getNextBestLayoutInLayoutList (const BusesLayout &layouts, const short(&channelLayoutList)[numLayouts][2])
Returns the next best layout which is contained in a channel layout map.
double getSampleRate () const noexcept
Returns the current sample rate.
int getBlockSize () const noexcept
Returns the current typical block size that is being used.
int getLatencySamples () const noexcept
This returns the number of samples delay that the filter imposes on the audio passing through it.
void setLatencySamples (int newLatency)
The filter should call this to set the number of samples delay that it introduces.
virtual double getTailLengthSeconds () const =0
Returns the length of the filter's tail, in seconds.
virtual bool acceptsMidi () const =0
Returns true if the processor wants midi messages.
virtual bool producesMidi () const =0
Returns true if the processor produces midi messages.
virtual bool supportsMPE () const
Returns true if the processor supports MPE.
virtual bool isMidiEffect () const
Returns true if this is a midi effect plug-in and does no audio processing.
const CriticalSection & getCallbackLock () const noexcept
This returns a critical section that will automatically be locked while the host is calling the processBlock() method.
void suspendProcessing (bool shouldBeSuspended)
Enables and disables the processing callback.
bool isSuspended () const noexcept
Returns true if processing is currently suspended.
virtual void reset ()
A plugin can override this to be told when it should reset any playing voices.
bool isNonRealtime () const noexcept
Returns true if the processor is being run in an offline mode for rendering.
virtual void setNonRealtime (bool isNonRealtime) noexcept
Called by the host to tell this processor whether it's being used in a non-realtime capacity for offline rendering or bouncing.
virtual AudioProcessorEditor * createEditor ()=0
Creates the filter's UI.
virtual bool hasEditor () const =0
Your filter must override this and return true if it can create an editor component.
AudioProcessorEditor * getActiveEditor () const noexcept
Returns the active editor, if there is one.
AudioProcessorEditor * createEditorIfNeeded ()
Returns the active editor, or if there isn't one, it will create one.
virtual int getNumParameters ()
This must return the correct value immediately after the object has been created, and mustn't change the number of parameters later.
virtual const String getParameterName (int parameterIndex)
Returns the name of a particular parameter.
virtual String getParameterID (int index)
Returns the ID of a particular parameter.
virtual float getParameter (int parameterIndex)
Called by the host to find out the value of one of the filter's parameters.
virtual String getParameterName (int parameterIndex, int maximumStringLength)
Returns the name of a parameter as a text string with a preferred maximum length.
virtual const String getParameterText (int parameterIndex)
Returns the value of a parameter as a text string.
virtual String getParameterText (int parameterIndex, int maximumStringLength)
Returns the value of a parameter as a text string with a preferred maximum length.
virtual int getParameterNumSteps (int parameterIndex)
Returns the number of discrete steps that this parameter can represent.
virtual float getParameterDefaultValue (int parameterIndex)
Returns the default value for the parameter.
virtual String getParameterLabel (int index) const
Some plugin types may be able to return a label string for a parameter's units.
virtual bool isParameterOrientationInverted (int index) const
This can be overridden to tell the host that particular parameters operate in the reverse direction.
virtual void setParameter (int parameterIndex, float newValue)
The host will call this method to change the value of one of the filter's parameters.
void setParameterNotifyingHost (int parameterIndex, float newValue)
Your filter can call this when it needs to change one of its parameters.
virtual bool isParameterAutomatable (int parameterIndex) const
Returns true if the host can automate this parameter.
virtual bool isMetaParameter (int parameterIndex) const
Should return true if this parameter is a "meta" parameter.
virtual
AudioProcessorParameter::Category getParameterCategory (int parameterIndex) const
Should return the parameter's category.
void beginParameterChangeGesture (int parameterIndex)
Sends a signal to the host to tell it that the user is about to start changing this parameter.
void endParameterChangeGesture (int parameterIndex)
Tells the host that the user has finished changing this parameter.
void updateHostDisplay ()
The filter can call this when something (apart from a parameter value) has changed.
void addParameter (AudioProcessorParameter *)
Adds a parameter to the list.
const OwnedArray
< AudioProcessorParameter > & getParameters () const noexcept
Returns the current list of parameters.
virtual int getNumPrograms ()=0
Returns the number of preset programs the filter supports.
virtual int getCurrentProgram ()=0
Returns the number of the currently active program.
virtual void setCurrentProgram (int index)=0
Called by the host to change the current program.
virtual const String getProgramName (int index)=0
Must return the name of a given program.
virtual void changeProgramName (int index, const String &newName)=0
Called by the host to rename a program.
virtual void getStateInformation (juce::MemoryBlock &destData)=0
The host will call this method when it wants to save the filter's internal state.
virtual void getCurrentProgramStateInformation (juce::MemoryBlock &destData)
The host will call this method if it wants to save the state of just the filter's current program.
virtual void setStateInformation (const void *data, int sizeInBytes)=0
This must restore the filter's state from a block of data previously created using getStateInformation().
virtual void setCurrentProgramStateInformation (const void *data, int sizeInBytes)
The host will call this method if it wants to restore the state of just the filter's current program.
virtual void numChannelsChanged ()
This method is called when the total number of input or output channels is changed.
virtual void numBusesChanged ()
This method is called when the number of buses is changed.
virtual void processorLayoutsChanged ()
This method is called when the layout of the audio processor changes.
virtual void addListener (AudioProcessorListener *newListener)
Adds a listener that will be called when an aspect of this processor changes.
virtual void removeListener (AudioProcessorListener *listenerToRemove)
Removes a previously added listener.
virtual void setPlayHead (AudioPlayHead *newPlayHead)
Tells the processor to use this playhead object.
void setPlayConfigDetails (int numIns, int numOuts, double sampleRate, int blockSize)
This is called by the processor to specify its details before being played.
void setRateAndBufferSizeDetails (double sampleRate, int blockSize) noexcept
This is called by the processor to specify its details before being played.
virtual int32 getAAXPluginIDForMainBusConfig (const AudioChannelSet &mainInputLayout, const AudioChannelSet &mainOutputLayout, bool idForAudioSuite) const
AAX plug-ins need to report a unique "plug-in id" for every audio layout configuration that your AudioProcessor supports on the main bus.
void editorBeingDeleted (AudioProcessorEditor *) noexcept
Not for public use - this is called before deleting an editor component.
virtual void updateTrackProperties (const TrackProperties &properties)
Informs the AudioProcessor that track properties such as the track's name or colour has been changed.
Static Public Member Functions
static bool containsLayout (const BusesLayout &layouts, const std::initializer_list< const short[2]> &channelLayoutList)
Returns true if the channel layout map contains a certain layout.
template<int numLayouts>
static bool containsLayout (const BusesLayout &layouts, const short(&channelLayoutList)[numLayouts][2])
static int getDefaultNumParameterSteps () noexcept
Returns the default number of steps for a parameter.
static void copyXmlToBinary (const XmlElement &xml, juce::MemoryBlock &destData)
Helper function that just converts an xml element into a binary blob.
static XmlElement * getXmlFromBinary (const void *data, int sizeInBytes)
Retrieves an XML element that was stored as binary with the copyXmlToBinary() method.
static void JUCE_CALLTYPE setTypeOfNextNewPlugin (WrapperType)
Public Attributes
WrapperType wrapperType
When loaded by a plugin wrapper, this flag will be set to indicate the type of plugin within which the processor is running.
Protected Member Functions
AudioProcessor ()
Constructor.
AudioProcessor (const BusesProperties &ioLayouts)
Constructor for multibus AudioProcessors.
AudioProcessor (const std::initializer_list< const short[2]> &channelLayoutList)
Constructor for AudioProcessors which use layout maps.
virtual bool isBusesLayoutSupported (const BusesLayout &) const
Callback to query if the AudioProcessor supports a specific layout.
virtual bool canApplyBusesLayout (const BusesLayout &layouts) const
Callback to check if a certain bus layout can now be applied.
virtual bool canApplyBusCountChange (bool isInput, bool isAddingBuses, BusProperties &outNewBusProperties)
Callback to query if adding/removing buses currently possible.
void sendParamChangeMessageToListeners (int parameterIndex, float newValue)
Protected Attributes
AudioPlayHead * playHead
Member Enumeration Documentation
enum AudioProcessor::ProcessingPrecision
Enumerator
singlePrecision
doublePrecision
enum AudioProcessor::WrapperType
Flags to indicate the type of plugin context in which a processor is being used.
Enumerator
wrapperType_Undefined
wrapperType_VST
wrapperType_VST3
wrapperType_AudioUnit
wrapperType_AudioUnitv3
wrapperType_RTAS
wrapperType_AAX
wrapperType_Standalone
Constructor & Destructor Documentation
AudioProcessor::AudioProcessor () protected
Constructor.
This constructor will create a main input and output bus which are diabled by default. If you need more fine grain control then use the other constructors.
AudioProcessor::AudioProcessor (const BusesProperties & ioLayouts) protected
Constructor for multibus AudioProcessors.
If your AudioProcessor supports multiple buses than use this constructor to initialise the bus layouts and bus names of your plug-in.
AudioProcessor::AudioProcessor (const std::initializer_list< const short[2]> & channelLayoutList) protected
Constructor for AudioProcessors which use layout maps.
If your AudioProcessor uses layout maps then use this constructor.
References initialise().
virtual AudioProcessor::~AudioProcessor () virtual
Destructor.
Member Function Documentation
virtual const String AudioProcessor::getName () const pure virtual
Returns the name of this processor.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual StringArray AudioProcessor::getAlternateDisplayNames () const virtual
Returns a list of alternative names to use for this processor.
Some hosts truncate the name of your AudioProcessor when there isn't enough space in the GUI to show the full name. Overriding this method, allows the host to choose an alternative name (such as an abbreviation) to better fit the available space.
virtual void AudioProcessor::prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) pure virtual
Called before playback starts, to let the filter prepare itself.
The sample rate is the target sample rate, and will remain constant until playback stops.
You can call getTotalNumInputChannels and getTotalNumOutputChannels or query the busLayout member variable to find out the number of channels your processBlock callback must process.
The maximumExpectedSamplesPerBlock value is a strong hint about the maximum number of samples that will be provided in each block. You may want to use this value to resize internal buffers. You should program defensively in case a buggy host exceeds this value. The actual block sizes that the host uses may be different each time the callback happens: completely variable block sizes can be expected from some hosts.
See Also
busLayout, getTotalNumInputChannels, getTotalNumOutputChannels
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::releaseResources () pure virtual
Called after playback has stopped, to let the filter free up any resources it no longer needs.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::processBlock (AudioBuffer< float > & buffer, MidiBuffer & midiMessages) pure virtual
Renders the next block.
When this method is called, the buffer contains a number of channels which is at least as great as the maximum number of input and output channels that this filter is using. It will be filled with the filter's input data and should be replaced with the filter's output.
So for example if your filter has a total of 2 input channels and 4 output channels, then the buffer will contain 4 channels, the first two being filled with the input data. Your filter should read these, do its processing, and replace the contents of all 4 channels with its output.
Or if your filter has a total of 5 inputs and 2 outputs, the buffer will have 5 channels, all filled with data, and your filter should overwrite the first 2 of these with its output. But be VERY careful not to write anything to the last 3 channels, as these might be mapped to memory that the host assumes is read-only!
If your plug-in has more than one input or output buses then the buffer passed to the processBlock methods will contain a bundle of all channels of each bus. Use AudiobusLayout::getBusBuffer to obtain an audio buffer for a particular bus.
Note that if you have more outputs than inputs, then only those channels that correspond to an input channel are guaranteed to contain sensible data - e.g. in the case of 2 inputs and 4 outputs, the first two channels contain the input, but the last two channels may contain garbage, so you should be careful not to let this pass through without being overwritten or cleared.
Also note that the buffer may have more channels than are strictly necessary, but you should only read/write from the ones that your filter is supposed to be using.
The number of samples in these buffers is NOT guaranteed to be the same for every callback, and may be more or less than the estimated value given to prepareToPlay(). Your code must be able to cope with variable-sized blocks, or you're going to get clicks and crashes!
Also note that some hosts will occasionally decide to pass a buffer containing zero samples, so make sure that your algorithm can deal with that!
If the filter is receiving a midi input, then the midiMessages array will be filled with the midi messages for this block. Each message's timestamp will indicate the message's time, as a number of samples from the start of the block.
Any messages left in the midi buffer when this method has finished are assumed to be the filter's midi output. This means that your filter should be careful to clear any incoming messages from the array if it doesn't want them to be passed-on.
Be very careful about what you do in this callback - it's going to be called by the audio thread, so any kind of interaction with the UI is absolutely out of the question. If you change a parameter in here and need to tell your UI to update itself, the best way is probably to inherit from a ChangeBroadcaster, let the UI components register as listeners, and then call sendChangeMessage() inside the processBlock() method to send out an asynchronous message. You could also use the AsyncUpdater class in a similar way.
See Also
AudiobusLayout::getBusBuffer
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::processBlock (AudioBuffer< double > & buffer, MidiBuffer & midiMessages) virtual
Renders the next block.
When this method is called, the buffer contains a number of channels which is at least as great as the maximum number of input and output channels that this filter is using. It will be filled with the filter's input data and should be replaced with the filter's output.
So for example if your filter has a combined total of 2 input channels and 4 output channels, then the buffer will contain 4 channels, the first two being filled with the input data. Your filter should read these, do its processing, and replace the contents of all 4 channels with its output.
Or if your filter has 5 inputs and 2 outputs, the buffer will have 5 channels, all filled with data, and your filter should overwrite the first 2 of these with its output. But be VERY careful not to write anything to the last 3 channels, as these might be mapped to memory that the host assumes is read-only!
If your plug-in has more than one input or output buses then the buffer passed to the processBlock methods will contain a bundle of all channels of each bus. Use AudiobusLayout::getBusBuffer to obtain a audio buffer for a particular bus.
Note that if you have more outputs than inputs, then only those channels that correspond to an input channel are guaranteed to contain sensible data - e.g. in the case of 2 inputs and 4 outputs, the first two channels contain the input, but the last two channels may contain garbage, so you should be careful not to let this pass through without being overwritten or cleared.
Also note that the buffer may have more channels than are strictly necessary, but you should only read/write from the ones that your filter is supposed to be using.
If your plugin uses buses, then you should use AudiobusLayout::getBusBuffer() or AudiobusLayout::getChannelIndexInProcessBlockBuffer() to find out which of the input and output channels correspond to which of the buses.
The number of samples in these buffers is NOT guaranteed to be the same for every callback, and may be more or less than the estimated value given to prepareToPlay(). Your code must be able to cope with variable-sized blocks, or you're going to get clicks and crashes!
Also note that some hosts will occasionally decide to pass a buffer containing zero samples, so make sure that your algorithm can deal with that!
If the filter is receiving a midi input, then the midiMessages array will be filled with the midi messages for this block. Each message's timestamp will indicate the message's time, as a number of samples from the start of the block.
Any messages left in the midi buffer when this method has finished are assumed to be the filter's midi output. This means that your filter should be careful to clear any incoming messages from the array if it doesn't want them to be passed-on.
Be very careful about what you do in this callback - it's going to be called by the audio thread, so any kind of interaction with the UI is absolutely out of the question. If you change a parameter in here and need to tell your UI to update itself, the best way is probably to inherit from a ChangeBroadcaster, let the UI components register as listeners, and then call sendChangeMessage() inside the processBlock() method to send out an asynchronous message. You could also use the AsyncUpdater class in a similar way.
See Also
AudiobusLayout::getBusBuffer
Reimplemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::processBlockBypassed (AudioBuffer< float > & buffer, MidiBuffer & midiMessages) virtual
Renders the next block when the processor is being bypassed.
The default implementation of this method will pass-through any incoming audio, but you may override this method e.g. to add latency compensation to the data to match the processor's latency characteristics. This will avoid situations where bypassing will shift the signal forward in time, possibly creating pre-echo effects and odd timings. Another use for this method would be to cross-fade or morph between the wet (not bypassed) and dry (bypassed) signals.
virtual void AudioProcessor::processBlockBypassed (AudioBuffer< double > & buffer, MidiBuffer & midiMessages) virtual
Renders the next block when the processor is being bypassed.
The default implementation of this method will pass-through any incoming audio, but you may override this method e.g. to add latency compensation to the data to match the processor's latency characteristics. This will avoid situations where bypassing will shift the signal forward in time, possibly creating pre-echo effects and odd timings. Another use for this method would be to cross-fade or morph between the wet (not bypassed) and dry (bypassed) signals.
int AudioProcessor::getBusCount (bool isInput) const noexcept
Returns the number of buses on the input or output side.
Referenced by AudioUnitHelpers::getBusCount(), AudioUnitHelpers::getBusesLayout(), and AudioUnitHelpers::setBusesLayout().
Bus* AudioProcessor::getBus (bool isInput, int busIdx) noexcept
Returns the audio bus with a given index and direction.
If busIdx is invalid then this method will return a nullptr.
Referenced by AudioUnitHelpers::getAUChannelInfo(), getBus(), getChannelCountOfBus(), and AudioUnitHelpers::isLayoutSupported().
const Bus* AudioProcessor::getBus (bool isInput, int busIdx) const noexcept
Returns the audio bus with a given index and direction.
If busIdx is invalid then this method will return a nullptr.
References getBus().
virtual bool AudioProcessor::canAddBus (bool isInput) const virtual
Callback to query if a bus can currently be added.
This callback probes if a bus can currently be added. You should override this callback if you want to support dynamically adding/removing buses by the host. This is useful for mixer audio processors.
The default implementation will always return false.
See Also
addBus
References ignoreUnused().
virtual bool AudioProcessor::canRemoveBus (bool isInput) const virtual
Callback to query if the last bus can currently be removed.
This callback probes if the last bus can currently be removed. You should override this callback if you want to support dynamically adding/removing buses by the host. This is useful for mixer audio processors.
If you return true in this callback then the AudioProcessor will go ahead and delete the bus.
The default implementation will always return false.
References ignoreUnused().
bool AudioProcessor::addBus (bool isInput)
Dynamically request an additional bus.
Request an additional bus from the audio processor. If the audio processor does not support adding additional buses then this method will return false.
Most audio processors will not allow you to dynamically add/remove audio buses and will return false.
This method will invoke the canApplyBusCountChange callback to probe if a bus can be added and, if yes, will use the supplied bus properties of the canApplyBusCountChange callback to create a new bus.
See Also
canApplyBusCountChange, removeBus
bool AudioProcessor::removeBus (bool isInput)
Dynamically remove the latest added bus.
Request the removal of the last bus from the audio processor. If the audio processor does not support removing buses then this method will return false.
Most audio processors will not allow you to dynamically add/remove audio buses and will return false.
The default implementation will return false.
This method will invoke the canApplyBusCountChange callback to probe if a bus can currently be removed and, if yes, will go ahead and remove it.
See Also
addBus, canRemoveBus
bool AudioProcessor::setBusesLayout (const BusesLayout &)
Set the channel layouts of this audio processor.
If the layout is not supported by this audio processor then this method will return false. You can use the checkBusesLayoutSupported and getNextBestLayout methods to probe which layouts this audio processor supports.
Referenced by AudioUnitHelpers::setBusesLayout().
bool AudioProcessor::setBusesLayoutWithoutEnabling (const BusesLayout &)
Set the channel layouts of this audio processor without changing the enablement state of the buses.
If the layout is not supported by this audio processor then this method will return false. You can use the checkBusesLayoutSupported methods to probe which layouts this audio processor supports.
BusesLayout AudioProcessor::getBusesLayout () const
Provides the current channel layouts of this audio processor.
Referenced by AudioUnitHelpers::getAUChannelInfo(), and AudioUnitHelpers::getBusesLayout().
AudioChannelSet AudioProcessor::getChannelLayoutOfBus (bool isInput, int busIndex) const noexcept
Provides the channel layout of the bus with a given index and direction.
If the index, direction combination is invalid then this will return an AudioChannelSet with no channels.
bool AudioProcessor::setChannelLayoutOfBus (bool isInput, int busIdx, const AudioChannelSet & layout)
Set the channel layout of the bus with a given index and direction.
If the index, direction combination is invalid or the layout is not supported by the audio processor then this method will return false.
int AudioProcessor::getChannelCountOfBus (bool isInput, int busIdx) const noexcept
Provides the number of channels of the bus with a given index and direction.
If the index, direction combination is invalid then this will return zero.
References getBus().
Referenced by AudioUnitHelpers::getAUChannelInfo(), getBusBuffer(), getMainBusNumInputChannels(), and getMainBusNumOutputChannels().
bool AudioProcessor::enableAllBuses ()
Enables all buses.
bool AudioProcessor::disableNonMainBuses ()
Disables all non-main buses (aux and sidechains).
Referenced by StandalonePluginHolder::createPlugin().
int AudioProcessor::getChannelIndexInProcessBlockBuffer (bool isInput, int busIndex, int channelIndex) const noexcept
Returns the position of a bus's channels within the processBlock buffer.
This can be called in processBlock to figure out which channel of the master AudioSampleBuffer maps onto a specific bus's channel.
Referenced by getBusBuffer().
int AudioProcessor::getOffsetInBusBufferForAbsoluteChannelIndex (bool isInput, int absoluteChannelIndex, int & busIdx) const noexcept
Returns the offset in a bus's buffer from an absolute channel indes.
This method returns the offset in a bus's buffer given an absolute channel index. It also provides the bus index. For example, this method would return one for a processor with two stereo buses when given the absolute channel index.
template<typename FloatType > AudioBuffer<FloatType> AudioProcessor::getBusBuffer (AudioBuffer< FloatType > & processBlockBuffer, bool isInput, int busIndex) const
Returns an AudioBuffer containing a set of channel pointers for a specific bus.
This can be called in processBlock to get a buffer containing a sub-group of the master AudioSampleBuffer which contains all the plugin channels.
References AudioBuffer< Type >::getArrayOfWritePointers(), getChannelCountOfBus(), getChannelIndexInProcessBlockBuffer(), and AudioBuffer< Type >::getNumSamples().
bool AudioProcessor::checkBusesLayoutSupported (const BusesLayout &) const
Returns true if the Audio processor is likely to support a given layout.
This can be called regardless if the processor is currently running.
virtual bool AudioProcessor::supportsDoublePrecisionProcessing () const virtual
Returns true if the Audio processor supports double precision floating point processing.
The default implementation will always return false. If you return true here then you must override the double precision versions of processBlock. Additionally, you must call getProcessingPrecision() in your prepareToPlay method to determine the precision with which you need to allocate your internal buffers.
See Also
getProcessingPrecision, setProcessingPrecision
Reimplemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
ProcessingPrecision AudioProcessor::getProcessingPrecision () const noexcept
Returns the precision-mode of the processor.
Depending on the result of this method you MUST call the corresponding version of processBlock. The default processing precision is single precision.
See Also
setProcessingPrecision, supportsDoublePrecisionProcessing
bool AudioProcessor::isUsingDoublePrecision () const noexcept
Returns true if the current precision is set to doublePrecision.
References doublePrecision.
void AudioProcessor::setProcessingPrecision (ProcessingPrecision newPrecision) noexcept
Changes the processing precision of the receiver.
A client of the AudioProcessor calls this function to indicate which version of processBlock (single or double precision) it intends to call. The client MUST call this function before calling the prepareToPlay method so that the receiver can do any necessary allocations in the prepareToPlay() method. An implementation of prepareToPlay() should call getProcessingPrecision() to determine with which precision it should allocate it's internal buffers.
Note that setting the processing precision to double floating point precision on a receiver which does not support double precision processing (i.e. supportsDoublePrecisionProcessing() returns false) will result in an assertion.
See Also
getProcessingPrecision, supportsDoublePrecisionProcessing
AudioPlayHead* AudioProcessor::getPlayHead () const noexcept
Returns the current AudioPlayHead object that should be used to find out the state and position of the playhead.
You can ONLY call this from your processBlock() method! Calling it at other times will produce undefined behaviour, as the host may not have any context in which a time would make sense, and some hosts will almost certainly have multithreading issues if it's not called on the audio thread.
The AudioPlayHead object that is returned can be used to get the details about the time of the start of the block currently being processed. But do not store this pointer or use it outside of the current audio callback, because the host may delete or re-use it.
If the host can't or won't provide any time info, this will return nullptr.
References playHead.
int AudioProcessor::getTotalNumInputChannels () const noexcept
Returns the total number of input channels.
This method will return the total number of input channels by accumulating the number of channels on each input bus. The number of channels of the buffer passed to your processBlock callback will be equivalent to either getTotalNumInputChannels or getTotalNumOutputChannels - which ever is greater.
Note that getTotalNumInputChannels is equivalent to getMainBusNumInputChannels if your processor does not have any sidechains or aux buses.
int AudioProcessor::getTotalNumOutputChannels () const noexcept
Returns the total number of output channels.
This method will return the total number of output channels by accumulating the number of channels on each output bus. The number of channels of the buffer passed to your processBlock callback will be equivalent to either getTotalNumInputChannels or getTotalNumOutputChannels - which ever is greater.
Note that getTotalNumOutputChannels is equivalent to getMainBusNumOutputChannels if your processor does not have any sidechains or aux buses.
int AudioProcessor::getMainBusNumInputChannels () const noexcept
Returns the number of input channels on the main bus.
References getChannelCountOfBus().
Referenced by StandalonePluginHolder::createPlugin(), StandalonePluginHolder::reloadAudioDeviceState(), StandalonePluginHolder::showAudioSettingsDialog(), and StandalonePluginHolder::StandalonePluginHolder().
int AudioProcessor::getMainBusNumOutputChannels () const noexcept
Returns the number of output channels on the main bus.
References getChannelCountOfBus().
Referenced by StandalonePluginHolder::createPlugin(), StandalonePluginHolder::reloadAudioDeviceState(), and StandalonePluginHolder::showAudioSettingsDialog().
static bool AudioProcessor::containsLayout (const BusesLayout & layouts, const std::initializer_list< const short[2]> & channelLayoutList) static
Returns true if the channel layout map contains a certain layout.
You can use this method to help you implement the checkBusesLayoutSupported method. For example
bool checkBusesLayoutSupported (const BusesLayout& layouts) override
{
    return containsLayout (layouts, {{1,1},{2,2}});
}
Referenced by containsLayout().
template<int numLayouts> static bool AudioProcessor::containsLayout (const BusesLayout & layouts, const short(&) channelLayoutList[numLayouts][2]) static
References containsLayout().
template<int numLayouts> BusesLayout AudioProcessor::getNextBestLayoutInLayoutList (const BusesLayout & layouts, const short(&) channelLayoutList[numLayouts][2])
Returns the next best layout which is contained in a channel layout map.
You can use this mehtod to help you implement getNextBestLayout. For example:
BusesLayout getNextBestLayout (const BusesLayout& layouts) override
{
    return getNextBestLayoutInLayoutList (layouts, {{1,1},{2,2}});
}
double AudioProcessor::getSampleRate () const noexcept
Returns the current sample rate.
This can be called from your processBlock() method - it's not guaranteed to be valid at any other time, and may return 0 if it's unknown.
int AudioProcessor::getBlockSize () const noexcept
Returns the current typical block size that is being used.
This can be called from your processBlock() method - it's not guaranteed to be valid at any other time.
Remember it's not the ONLY block size that may be used when calling processBlock, it's just the normal one. The actual block sizes used may be larger or smaller than this, and will vary between successive calls.
int AudioProcessor::getLatencySamples () const noexcept
This returns the number of samples delay that the filter imposes on the audio passing through it.
The host will call this to find the latency - the filter itself should set this value by calling setLatencySamples() as soon as it can during its initialisation.
void AudioProcessor::setLatencySamples (int newLatency)
The filter should call this to set the number of samples delay that it introduces.
The filter should call this as soon as it can during initialisation, and can call it later if the value changes.
virtual double AudioProcessor::getTailLengthSeconds () const pure virtual
Returns the length of the filter's tail, in seconds.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual bool AudioProcessor::acceptsMidi () const pure virtual
Returns true if the processor wants midi messages.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual bool AudioProcessor::producesMidi () const pure virtual
Returns true if the processor produces midi messages.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual bool AudioProcessor::supportsMPE () const virtual
Returns true if the processor supports MPE.
virtual bool AudioProcessor::isMidiEffect () const virtual
Returns true if this is a midi effect plug-in and does no audio processing.
const CriticalSection& AudioProcessor::getCallbackLock () const noexcept
This returns a critical section that will automatically be locked while the host is calling the processBlock() method.
Use it from your UI or other threads to lock access to variables that are used by the process callback, but obviously be careful not to keep it locked for too long, because that could cause stuttering playback. If you need to do something that'll take a long time and need the processing to stop while it happens, use the suspendProcessing() method instead.
See Also
suspendProcessing
void AudioProcessor::suspendProcessing (bool shouldBeSuspended)
Enables and disables the processing callback.
If you need to do something time-consuming on a thread and would like to make sure the audio processing callback doesn't happen until you've finished, use this to disable the callback and re-enable it again afterwards.
E.g.
void loadNewPatch()
{
    suspendProcessing (true);
    ..do something that takes ages..
    suspendProcessing (false);
}
If the host tries to make an audio callback while processing is suspended, the filter will return an empty buffer, but won't block the audio thread like it would do if you use the getCallbackLock() critical section to synchronise access.
Any code that calls processBlock() should call isSuspended() before doing so, and if the processor is suspended, it should avoid the call and emit silence or whatever is appropriate.
See Also
getCallbackLock
bool AudioProcessor::isSuspended () const noexcept
Returns true if processing is currently suspended.
See Also
suspendProcessing
virtual void AudioProcessor::reset () virtual
A plugin can override this to be told when it should reset any playing voices.
The default implementation does nothing, but a host may call this to tell the plugin that it should stop any tails or sounds that have been left running.
Reimplemented in AudioProcessorGraph.
bool AudioProcessor::isNonRealtime () const noexcept
Returns true if the processor is being run in an offline mode for rendering.
If the processor is being run live on realtime signals, this returns false. If the mode is unknown, this will assume it's realtime and return false.
This value may be unreliable until the prepareToPlay() method has been called, and could change each time prepareToPlay() is called.
See Also
setNonRealtime()
virtual void AudioProcessor::setNonRealtime (bool isNonRealtime) virtual noexcept
Called by the host to tell this processor whether it's being used in a non-realtime capacity for offline rendering or bouncing.
Reimplemented in AudioProcessorGraph.
virtual AudioProcessorEditor* AudioProcessor::createEditor () pure virtual
Creates the filter's UI.
This can return nullptr if you want a UI-less filter, in which case the host may create a generic UI that lets the user twiddle the parameters directly.
If you do want to pass back a component, the component should be created and set to the correct size before returning it. If you implement this method, you must also implement the hasEditor() method and make it return true.
Remember not to do anything silly like allowing your filter to keep a pointer to the component that gets created - it could be deleted later without any warning, which would make your pointer into a dangler. Use the getActiveEditor() method instead.
The correct way to handle the connection between an editor component and its filter is to use something like a ChangeBroadcaster so that the editor can register itself as a listener, and be told when a change occurs. This lets them safely unregister themselves when they are deleted.
Here are a few things to bear in mind when writing an editor:
Initially there won't be an editor, until the user opens one, or they might not open one at all. Your filter mustn't rely on it being there.
An editor object may be deleted and a replacement one created again at any time.
It's safe to assume that an editor will be deleted before its filter.
See Also
hasEditor
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual bool AudioProcessor::hasEditor () const pure virtual
Your filter must override this and return true if it can create an editor component.
See Also
createEditor
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
AudioProcessorEditor* AudioProcessor::getActiveEditor () const noexcept
Returns the active editor, if there is one.
Bear in mind this can return nullptr, even if an editor has previously been opened.
AudioProcessorEditor* AudioProcessor::createEditorIfNeeded ()
Returns the active editor, or if there isn't one, it will create one.
This may call createEditor() internally to create the component.
virtual int AudioProcessor::getNumParameters () virtual
This must return the correct value immediately after the object has been created, and mustn't change the number of parameters later.
NOTE! This method will eventually be deprecated! It's recommended that you use the AudioProcessorParameter class instead to manage your parameters.
virtual const String AudioProcessor::getParameterName (int parameterIndex) virtual
Returns the name of a particular parameter.
NOTE! This method will eventually be deprecated! It's recommended that you use the AudioProcessorParameter class instead to manage your parameters.
virtual String AudioProcessor::getParameterID (int index) virtual
Returns the ID of a particular parameter.
The ID is used to communicate the value or mapping of a particular parameter with the host. By default this method will simply return a string representation of index.
NOTE! This method will eventually be deprecated! It's recommended that you use the AudioProcessorParameterWithID class instead to manage your parameters.
virtual float AudioProcessor::getParameter (int parameterIndex) virtual
Called by the host to find out the value of one of the filter's parameters.
The host will expect the value returned to be between 0 and 1.0.
This could be called quite frequently, so try to make your code efficient. It's also likely to be called by non-UI threads, so the code in here should be thread-aware.
NOTE! This method will eventually be deprecated! It's recommended that you use the AudioProcessorParameter class instead to manage your parameters.
virtual String AudioProcessor::getParameterName (int parameterIndex, int maximumStringLength) virtual
Returns the name of a parameter as a text string with a preferred maximum length.
If you want to provide customised short versions of your parameter names that will look better in constrained spaces (e.g. the displays on hardware controller devices or mixing desks) then you should implement this method. If you don't override it, the default implementation will call getParameterName(int), and truncate the result.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getName() instead.
virtual const String AudioProcessor::getParameterText (int parameterIndex) virtual
Returns the value of a parameter as a text string.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getText() instead.
virtual String AudioProcessor::getParameterText (int parameterIndex, int maximumStringLength) virtual
Returns the value of a parameter as a text string with a preferred maximum length.
If you want to provide customised short versions of your parameter values that will look better in constrained spaces (e.g. the displays on hardware controller devices or mixing desks) then you should implement this method. If you don't override it, the default implementation will call getParameterText(int), and truncate the result.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getText() instead.
virtual int AudioProcessor::getParameterNumSteps (int parameterIndex) virtual
Returns the number of discrete steps that this parameter can represent.
The default return value if you don't implement this method is AudioProcessor::getDefaultNumParameterSteps(). If your parameter is boolean, then you may want to make this return 2. The value that is returned may or may not be used, depending on the host.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getNumSteps() instead.
static int AudioProcessor::getDefaultNumParameterSteps () static noexcept
Returns the default number of steps for a parameter.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getNumSteps() instead.
See Also
getParameterNumSteps
virtual float AudioProcessor::getParameterDefaultValue (int parameterIndex) virtual
Returns the default value for the parameter.
By default, this just returns 0. The value that is returned may or may not be used, depending on the host.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getDefaultValue() instead.
virtual String AudioProcessor::getParameterLabel (int index) const virtual
Some plugin types may be able to return a label string for a parameter's units.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::getLabel() instead.
virtual bool AudioProcessor::isParameterOrientationInverted (int index) const virtual
This can be overridden to tell the host that particular parameters operate in the reverse direction.
(Not all plugin formats or hosts will actually use this information).
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::isOrientationInverted() instead.
virtual void AudioProcessor::setParameter (int parameterIndex, float newValue) virtual
The host will call this method to change the value of one of the filter's parameters.
The host may call this at any time, including during the audio processing callback, so the filter has to process this very fast and avoid blocking.
If you want to set the value of a parameter internally, e.g. from your editor component, then don't call this directly - instead, use the setParameterNotifyingHost() method, which will also send a message to the host telling it about the change. If the message isn't sent, the host won't be able to automate your parameters properly.
The value passed will be between 0 and 1.0.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::setValue() instead.
void AudioProcessor::setParameterNotifyingHost (int parameterIndex, float newValue)
Your filter can call this when it needs to change one of its parameters.
This could happen when the editor or some other internal operation changes a parameter. This method will call the setParameter() method to change the value, and will then send a message to the host telling it about the change.
Note that to make sure the host correctly handles automation, you should call the beginParameterChangeGesture() and endParameterChangeGesture() methods to tell the host when the user has started and stopped changing the parameter.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::setValueNotifyingHost() instead.
virtual bool AudioProcessor::isParameterAutomatable (int parameterIndex) const virtual
Returns true if the host can automate this parameter.
By default, this returns true for all parameters.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::isAutomatable() instead.
virtual bool AudioProcessor::isMetaParameter (int parameterIndex) const virtual
Should return true if this parameter is a "meta" parameter.
A meta-parameter is a parameter that changes other params. It is used by some hosts (e.g. AudioUnit hosts). By default this returns false.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::isMetaParameter() instead.
virtual AudioProcessorParameter::Category AudioProcessor::getParameterCategory (int parameterIndex) const virtual
Should return the parameter's category.
By default, this returns the "generic" category.
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::isMetaParameter() instead.
void AudioProcessor::beginParameterChangeGesture (int parameterIndex)
Sends a signal to the host to tell it that the user is about to start changing this parameter.
This allows the host to know when a parameter is actively being held by the user, and it may use this information to help it record automation.
If you call this, it must be matched by a later call to endParameterChangeGesture().
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::beginChangeGesture() instead.
void AudioProcessor::endParameterChangeGesture (int parameterIndex)
Tells the host that the user has finished changing this parameter.
This allows the host to know when a parameter is actively being held by the user, and it may use this information to help it record automation.
A call to this method must follow a call to beginParameterChangeGesture().
NOTE! This method will eventually be deprecated! It's recommended that you use AudioProcessorParameter::endChangeGesture() instead.
void AudioProcessor::updateHostDisplay ()
The filter can call this when something (apart from a parameter value) has changed.
It sends a hint to the host that something like the program, number of parameters, etc, has changed, and that it should update itself.
void AudioProcessor::addParameter (AudioProcessorParameter *)
Adds a parameter to the list.
The parameter object will be managed and deleted automatically by the list when no longer needed.
const OwnedArray<AudioProcessorParameter>& AudioProcessor::getParameters () const noexcept
Returns the current list of parameters.
virtual int AudioProcessor::getNumPrograms () pure virtual
Returns the number of preset programs the filter supports.
The value returned must be valid as soon as this object is created, and must not change over its lifetime.
This value shouldn't be less than 1.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual int AudioProcessor::getCurrentProgram () pure virtual
Returns the number of the currently active program.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::setCurrentProgram (int index) pure virtual
Called by the host to change the current program.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual const String AudioProcessor::getProgramName (int index) pure virtual
Must return the name of a given program.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::changeProgramName (int index, const String & newName) pure virtual
Called by the host to rename a program.
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
virtual void AudioProcessor::getStateInformation (juce::MemoryBlock & destData) pure virtual
The host will call this method when it wants to save the filter's internal state.
This must copy any info about the filter's state into the block of memory provided, so that the host can store this and later restore it using setStateInformation().
Note that there's also a getCurrentProgramStateInformation() method, which only stores the current program, not the state of the entire filter.
See also the helper function copyXmlToBinary() for storing settings as XML.
See Also
getCurrentProgramStateInformation
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
Referenced by StandalonePluginHolder::askUserToSaveState(), and StandalonePluginHolder::savePluginState().
virtual void AudioProcessor::getCurrentProgramStateInformation (juce::MemoryBlock & destData) virtual
The host will call this method if it wants to save the state of just the filter's current program.
Unlike getStateInformation, this should only return the current program's state.
Not all hosts support this, and if you don't implement it, the base class method just calls getStateInformation() instead. If you do implement it, be sure to also implement getCurrentProgramStateInformation.
See Also
getStateInformation, setCurrentProgramStateInformation
virtual void AudioProcessor::setStateInformation (const void * data, int sizeInBytes) pure virtual
This must restore the filter's state from a block of data previously created using getStateInformation().
Note that there's also a setCurrentProgramStateInformation() method, which tries to restore just the current program, not the state of the entire filter.
See also the helper function getXmlFromBinary() for loading settings as XML.
See Also
setCurrentProgramStateInformation
Implemented in AudioProcessorGraph, and AudioProcessorGraph::AudioGraphIOProcessor.
Referenced by StandalonePluginHolder::askUserToLoadState(), and StandalonePluginHolder::reloadPluginState().
virtual void AudioProcessor::setCurrentProgramStateInformation (const void * data, int sizeInBytes) virtual
The host will call this method if it wants to restore the state of just the filter's current program.
Not all hosts support this, and if you don't implement it, the base class method just calls setStateInformation() instead. If you do implement it, be sure to also implement getCurrentProgramStateInformation.
See Also
setStateInformation, getCurrentProgramStateInformation
virtual void AudioProcessor::numChannelsChanged () virtual
This method is called when the total number of input or output channels is changed.
virtual void AudioProcessor::numBusesChanged () virtual
This method is called when the number of buses is changed.
virtual void AudioProcessor::processorLayoutsChanged () virtual
This method is called when the layout of the audio processor changes.
virtual void AudioProcessor::addListener (AudioProcessorListener * newListener) virtual
Adds a listener that will be called when an aspect of this processor changes.
virtual void AudioProcessor::removeListener (AudioProcessorListener * listenerToRemove) virtual
Removes a previously added listener.
virtual void AudioProcessor::setPlayHead (AudioPlayHead * newPlayHead) virtual
Tells the processor to use this playhead object.
The processor will not take ownership of the object, so the caller must delete it when it is no longer being used.
Reimplemented in AudioProcessorGraph.
Referenced by StandalonePluginHolder::startPlaying().
void AudioProcessor::setPlayConfigDetails (int numIns, int numOuts, double sampleRate, int blockSize)
This is called by the processor to specify its details before being played.
Use this version of the function if you are not interested in any sidechain and/or aux buses and do not care about the layout of channels. Otherwise use setRateAndBufferSizeDetails.
void AudioProcessor::setRateAndBufferSizeDetails (double sampleRate, int blockSize) noexcept
This is called by the processor to specify its details before being played.
You should call this function after having informed the processor about the channel and bus layouts via setBusesLayout.
See Also
setBusesLayout
Referenced by StandalonePluginHolder::createPlugin().
virtual int32 AudioProcessor::getAAXPluginIDForMainBusConfig (const AudioChannelSet & mainInputLayout, const AudioChannelSet & mainOutputLayout, bool idForAudioSuite) const virtual
AAX plug-ins need to report a unique "plug-in id" for every audio layout configuration that your AudioProcessor supports on the main bus.
Override this function if you want your AudioProcessor to use a custom "plug-in id" (for example to stay backward compatible with older versions of JUCE).
The default implementation will compute a unique integer from the input and output layout and add this value to the 4 character code 'jcaa' (for native AAX) or 'jyaa' (for AudioSuite plug-ins).
void AudioProcessor::editorBeingDeleted (AudioProcessorEditor *) noexcept
Not for public use - this is called before deleting an editor component.
virtual void AudioProcessor::updateTrackProperties (const TrackProperties & properties) virtual
Informs the AudioProcessor that track properties such as the track's name or colour has been changed.
If you are hosting this AudioProcessor then use this method to inform the AudioProcessor about which track the AudioProcessor is loaded on. This method may only be called on the message thread.
If you are implemeting an AudioProcessor then you can override this callback to do something useful with the track properties such as changing the colour of your AudioProcessor's editor. It's entirely up to the host when and how often this callback will be called.
The default implementation of this callback will do nothing.
static void AudioProcessor::copyXmlToBinary (const XmlElement & xml, juce::MemoryBlock & destData) static
Helper function that just converts an xml element into a binary blob.
Use this in your filter's getStateInformation() method if you want to store its state as xml.
Then use getXmlFromBinary() to reverse this operation and retrieve the XML from a binary blob.
static XmlElement* AudioProcessor::getXmlFromBinary (const void * data, int sizeInBytes) static
Retrieves an XML element that was stored as binary with the copyXmlToBinary() method.
This might return nullptr if the data's unsuitable or corrupted. Otherwise it will return an XmlElement object that the caller must delete when no longer needed.
static void JUCE_CALLTYPE AudioProcessor::setTypeOfNextNewPlugin (WrapperType) static
Referenced by StandalonePluginHolder::createPlugin().
virtual bool AudioProcessor::isBusesLayoutSupported (const BusesLayout &) const protected virtual
Callback to query if the AudioProcessor supports a specific layout.
This callback is called when the host probes the supported bus layouts via the checkBusesLayoutSupported method. You should override this callback if you would like to limit the layouts that your AudioProcessor supports. The default implementation will accept any layout. JUCE does basic sanity checks so that the provided layouts parameter will have the same number of buses as your AudioProcessor.
See Also
checkBusesLayoutSupported
virtual bool AudioProcessor::canApplyBusesLayout (const BusesLayout & layouts) const protected virtual
Callback to check if a certain bus layout can now be applied.
Most subclasses will not need to override this method and should instead override the isBusesLayoutSupported callback to reject certain layout changes.
This callback is called when the user requests a layout change. It will only be called if processing of the AudioProcessor has been stopped by a previous call to releaseResources or after the construction of the AudioProcessor. It will be called just before the actual layout change. By returning false you will abort the layout change and setBusesLayout will return false indicating that the layout change was not successful.
The default implementation will simply call isBusesLayoutSupported.
You only need to override this method if there is a chance that your AudioProcessor may not accept a layout although you have previously claimed to support it via the isBusesLayoutSupported callback. This can occur if your AudioProcessor's supported layouts depend on other plug-in parameters which may have changed since the last call to isBusesLayoutSupported, such as the format of an audio file which can be selected by the user in the AudioProcessor's editor. This callback gives the AudioProcessor a last chance to reject a layout if conditions have changed as it is always called just before the actual layout change.
As it is never called while the AudioProcessor is processing audio, it can also be used for AudioProcessors which wrap other plug-in formats to apply the current layout to the underlying plug-in. This callback gives such AudioProcessors a chance to reject the layout change should an error occur with the underlying plug-in during the layout change.
See Also
isBusesLayoutSupported, setBusesLayout
virtual bool AudioProcessor::canApplyBusCountChange (bool isInput, bool isAddingBuses, BusProperties & outNewBusProperties) protected virtual
Callback to query if adding/removing buses currently possible.
This callback is called when the host calls addBus or removeBus. Similar to canApplyBusesLayout, this callback is only called while the AudioProcessor is stopped and gives the processor a last chance to reject a requested bus change. It can also be used to apply the bus count change to an underlying wrapped plug-in.
When adding a bus, isAddingBuses will be true and the plug-in is expected to fill out outNewBusProperties with the properties of the bus which will be created just after the succesful return of this callback.
Implementations of AudioProcessor will rarely need to override this method. Only override this method if your processor supports adding and removing buses and if it needs more fine grain control over the naming of new buses or may reject bus number changes although canAddBus or canRemoveBus returned true.
The default implementation will return false if canAddBus/canRemoveBus returns false (the default behavior). Otherwise, this method returns "Input #busIdx" for input buses and "Output #busIdx" for output buses where busIdx is the index for newly created buses. The default layout in this case will be the layout of the previous bus of the same direction.
void AudioProcessor::sendParamChangeMessageToListeners (int parameterIndex, float newValue) protected
Member Data Documentation
WrapperType AudioProcessor::wrapperType
When loaded by a plugin wrapper, this flag will be set to indicate the type of plugin within which the processor is running.
AudioPlayHead* AudioProcessor::playHead protected
Referenced by getPlayHead().
class AudioProcessorEditor
Base class for the component that acts as the GUI for an AudioProcessor.
Derive your editor component from this class, and create an instance of it by overriding the AudioProcessor::createEditor() method.
See Also
AudioProcessor, GenericAudioProcessorEditor
Public Member Functions
~AudioProcessorEditor ()
Destructor.
AudioProcessor * getAudioProcessor () const noexcept
Returns a pointer to the processor that this editor represents.
virtual void setControlHighlight (ParameterControlHighlightInfo)
Some types of plugin can call this to suggest that the control for a particular parameter should be highlighted.
virtual int getControlParameterIndex (Component &)
Called by certain plug-in wrappers to find out whether a component is used to control a parameter.
virtual bool supportsHostMIDIControllerPresence (bool hostMIDIControllerIsAvailable)
Override this method to indicate if your editor supports the presence or absence of a host-provided MIDI controller.
virtual void hostMIDIControllerIsAvailable (bool controllerIsAvailable)
Called to indicate if a host is providing a MIDI controller when the host reconfigures its layout.
virtual void setScaleFactor (float newScale)
Can be called by a host to tell the editor that it should use a non-unity GUI scale.
void setResizable (bool allowHostToResize, bool useBottomRightCornerResizer)
Marks the host's editor window as resizable.
bool isResizable () const noexcept
Returns true if the host is allowed to resize editor's parent window.
void setResizeLimits (int newMinimumWidth, int newMinimumHeight, int newMaximumWidth, int newMaximumHeight) noexcept
This sets the maximum and minimum sizes for the window.
ComponentBoundsConstrainer * getConstrainer () noexcept
Returns the bounds constrainer object that this window is using.
void setConstrainer (ComponentBoundsConstrainer *newConstrainer)
Sets the bounds-constrainer object to use for resizing and dragging this window.
void setBoundsConstrained (Rectangle< int > newBounds)
Calls the window's setBounds method, after first checking these bounds with the current constrainer.
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
virtual ~Component ()
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
virtual void visibilityChanged ()
Called when this component's visibility changes.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (int x, int y, int width, int height, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void parentHierarchyChanged ()
Called to indicate that the component's parents have changed.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
virtual void lookAndFeelChanged ()
Called to let the component react to a change in the look-and-feel setting.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparancy level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paint (Graphics &g)
Components can override this method to draw their content.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
virtual void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
virtual void mouseDown (const MouseEvent &event) override
Called when a mouse button is pressed.
virtual void mouseDrag (const MouseEvent &event) override
Called when the mouse is moved while a button is held down.
virtual void mouseUp (const MouseEvent &event) override
Called when a mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
virtual void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel) override
Called when the mouse-wheel is moved.
virtual void mouseMagnify (const MouseEvent &event, float scaleFactor)
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyPressed (const KeyPress &key)
Called when a key is pressed.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown () const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void resized ()
Called when this component's size has been changed.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourId, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourId, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourId)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourId) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
virtual MarkerList * getMarkers (bool xAxis)
Components can implement this method to provide a MarkerList.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
JUCE_DEPRECATED (Point< int > relativePositionToGlobal(Point< int >) const)
JUCE_DEPRECATED (Point< int > globalPositionToRelative(Point< int >) const)
JUCE_DEPRECATED (Point< int > relativePositionToOtherComponent(const Component *, Point< int >) const)
JUCE_DEPRECATED (void setBounds(const RelativeRectangle &))
JUCE_DEPRECATED (void setBounds(const String &))
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()
Destructor.
Public Attributes
AudioProcessor & processor
The AudioProcessor that this editor represents.
ScopedPointer
< ResizableCornerComponent > resizableCorner
Protected Member Functions
AudioProcessorEditor (AudioProcessor &) noexcept
Creates an editor for the specified processor.
AudioProcessorEditor (AudioProcessor *) noexcept
Creates an editor for the specified processor.
Additional Inherited Members
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusChanged() and focusLost() methods.
Static Public Member Functions inherited from Component
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Constructor & Destructor Documentation
AudioProcessorEditor::AudioProcessorEditor (AudioProcessor &) protected noexcept
Creates an editor for the specified processor.
AudioProcessorEditor::AudioProcessorEditor (AudioProcessor *) protected noexcept
Creates an editor for the specified processor.
AudioProcessorEditor::~AudioProcessorEditor ()
Destructor.
Member Function Documentation
AudioProcessor* AudioProcessorEditor::getAudioProcessor () const noexcept
Returns a pointer to the processor that this editor represents.
This method is here to support legacy code, but it's easier to just use the AudioProcessorEditor::processor member variable directly to get this object.
virtual void AudioProcessorEditor::setControlHighlight (ParameterControlHighlightInfo) virtual
Some types of plugin can call this to suggest that the control for a particular parameter should be highlighted.
Currently only AAX plugins will call this, and implementing it is optional.
virtual int AudioProcessorEditor::getControlParameterIndex (Component &) virtual
Called by certain plug-in wrappers to find out whether a component is used to control a parameter.
If the given component represents a particular plugin parameter, then this method should return the index of that parameter. If not, it should return -1. Currently only AAX plugins will call this, and implementing it is optional.
virtual bool AudioProcessorEditor::supportsHostMIDIControllerPresence (bool hostMIDIControllerIsAvailable) virtual
Override this method to indicate if your editor supports the presence or absence of a host-provided MIDI controller.
Currently only AUv3 plug-ins compiled for MacOS 10.13 or iOS 11.0 (or later) support this functionality, and even then the host may choose to ignore this information.
The default behaviour is to report support for both cases.
virtual void AudioProcessorEditor::hostMIDIControllerIsAvailable (bool controllerIsAvailable) virtual
Called to indicate if a host is providing a MIDI controller when the host reconfigures its layout.
Use this as an opportunity to hide or display your own onscreen keyboard or other input component.
Currently only AUv3 plug-ins compiled for MacOS 10.13 or iOS 11.0 (or later) support this functionality.
virtual void AudioProcessorEditor::setScaleFactor (float newScale) virtual
Can be called by a host to tell the editor that it should use a non-unity GUI scale.
void AudioProcessorEditor::setResizable (bool allowHostToResize, bool useBottomRightCornerResizer)
Marks the host's editor window as resizable.
Parameters
allowHostToResize whether the editor's parent window can be resized by the user or the host. Even if this is false, you can still resize your window yourself by calling setBounds (for example, when a user clicks on a button in your editor to drop out a panel) which will bypass any resizable/constraints checks. If you are using your own corner resizer than this will also bypass any checks.
useBottomRightCornerResizer
See Also
setResizeLimits, isResizable
bool AudioProcessorEditor::isResizable () const noexcept
Returns true if the host is allowed to resize editor's parent window.
See Also
setResizable
void AudioProcessorEditor::setResizeLimits (int newMinimumWidth, int newMinimumHeight, int newMaximumWidth, int newMaximumHeight) noexcept
This sets the maximum and minimum sizes for the window.
If the window's current size is outside these limits, it will be resized to make sure it's within them.
A direct call to setBounds() will bypass any constraint checks, but when the window is dragged by the user or resized by other indirect means, the constrainer will limit the numbers involved.
See Also
setResizable
ComponentBoundsConstrainer* AudioProcessorEditor::getConstrainer () noexcept
Returns the bounds constrainer object that this window is using.
You can access this to change its properties.
void AudioProcessorEditor::setConstrainer (ComponentBoundsConstrainer * newConstrainer)
Sets the bounds-constrainer object to use for resizing and dragging this window.
A pointer to the object you pass in will be kept, but it won't be deleted by this object, so it's the caller's responsibility to manage it.
If you pass a nullptr, then no contraints will be placed on the positioning of the window.
void AudioProcessorEditor::setBoundsConstrained (Rectangle< int > newBounds)
Calls the window's setBounds method, after first checking these bounds with the current constrainer.
See Also
setConstrainer
Member Data Documentation
AudioProcessor& AudioProcessorEditor::processor
The AudioProcessor that this editor represents.
ScopedPointer<ResizableCornerComponent> AudioProcessorEditor::resizableCorner
class AudioProcessorGraph
A type of AudioProcessor which plays back a graph of other AudioProcessors.
Use one of these objects if you want to wire-up a set of AudioProcessors and play back the result.
Processors can be added to the graph as "nodes" using addNode(), and once added, you can connect any of their input or output channels to other nodes using addConnection().
To play back a graph through an audio device, you might want to use an AudioProcessorPlayer object.
Public Member Functions
AudioProcessorGraph ()
Creates an empty graph.
~AudioProcessorGraph ()
Destructor.
void clear ()
Deletes all nodes and connections from this graph.
int getNumNodes () const noexcept
Returns the number of nodes in the graph.
Node * getNode (const int index) const noexcept
Returns a pointer to one of the nodes in the graph.
Node * getNodeForId (const uint32 nodeId) const
Searches the graph for a node with the given ID number and returns it.
Node * addNode (AudioProcessor *newProcessor, uint32 nodeId=0)
Adds a node to the graph.
bool removeNode (uint32 nodeId)
Deletes a node within the graph which has the specified ID.
bool removeNode (Node *node)
Deletes a node within the graph.
int getNumConnections () const
Returns the number of connections in the graph.
const Connection * getConnection (int index) const
Returns a pointer to one of the connections in the graph.
const Connection * getConnectionBetween (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex) const
Searches for a connection between some specified channels.
bool isConnected (uint32 possibleSourceNodeId, uint32 possibleDestNodeId) const
Returns true if there is a connection between any of the channels of two specified nodes.
bool canConnect (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex) const
Returns true if it would be legal to connect the specified points.
bool addConnection (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex)
Attempts to connect two specified channels of two nodes.
void removeConnection (int index)
Deletes the connection with the specified index.
bool removeConnection (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex)
Deletes any connection between two specified points.
bool disconnectNode (uint32 nodeId)
Removes all connections from the specified node.
bool isConnectionLegal (const Connection *connection) const
Returns true if the given connection's channel numbers map on to valid channels at each end.
bool removeIllegalConnections ()
Performs a sanity checks of all the connections.
const String getName () const override
Returns the name of this processor.
void prepareToPlay (double, int) override
Called before playback starts, to let the filter prepare itself.
void releaseResources () override
Called after playback has stopped, to let the filter free up any resources it no longer needs.
void processBlock (AudioBuffer< float > &, MidiBuffer &) override
Renders the next block.
void processBlock (AudioBuffer< double > &, MidiBuffer &) override
Renders the next block.
bool supportsDoublePrecisionProcessing () const override
Returns true if the Audio processor supports double precision floating point processing.
void reset () override
A plugin can override this to be told when it should reset any playing voices.
void setNonRealtime (bool) noexceptoverride
Called by the host to tell this processor whether it's being used in a non-realtime capacity for offline rendering or bouncing.
void setPlayHead (AudioPlayHead *) override
Tells the processor to use this playhead object.
double getTailLengthSeconds () const override
Returns the length of the filter's tail, in seconds.
bool acceptsMidi () const override
Returns true if the processor wants midi messages.
bool producesMidi () const override
Returns true if the processor produces midi messages.
bool hasEditor () const override
Your filter must override this and return true if it can create an editor component.
AudioProcessorEditor * createEditor () override
Creates the filter's UI.
int getNumPrograms () override
Returns the number of preset programs the filter supports.
int getCurrentProgram () override
Returns the number of the currently active program.
void setCurrentProgram (int) override
Called by the host to change the current program.
const String getProgramName (int) override
Must return the name of a given program.
void changeProgramName (int, const String &) override
Called by the host to rename a program.
void getStateInformation (juce::MemoryBlock &) override
The host will call this method when it wants to save the filter's internal state.
void setStateInformation (const void *data, int sizeInBytes) override
This must restore the filter's state from a block of data previously created using getStateInformation().
Public Member Functions inherited from AudioProcessor
virtual ~AudioProcessor ()
Destructor.
virtual StringArray getAlternateDisplayNames () const
Returns a list of alternative names to use for this processor.
virtual void processBlockBypassed (AudioBuffer< float > &buffer, MidiBuffer &midiMessages)
Renders the next block when the processor is being bypassed.
virtual void processBlockBypassed (AudioBuffer< double > &buffer, MidiBuffer &midiMessages)
Renders the next block when the processor is being bypassed.
int getBusCount (bool isInput) const noexcept
Returns the number of buses on the input or output side.
Bus * getBus (bool isInput, int busIdx) noexcept
Returns the audio bus with a given index and direction.
const Bus * getBus (bool isInput, int busIdx) const noexcept
Returns the audio bus with a given index and direction.
virtual bool canAddBus (bool isInput) const
Callback to query if a bus can currently be added.
virtual bool canRemoveBus (bool isInput) const
Callback to query if the last bus can currently be removed.
bool addBus (bool isInput)
Dynamically request an additional bus.
bool removeBus (bool isInput)
Dynamically remove the latest added bus.
bool setBusesLayout (const BusesLayout &)
Set the channel layouts of this audio processor.
bool setBusesLayoutWithoutEnabling (const BusesLayout &)
Set the channel layouts of this audio processor without changing the enablement state of the buses.
BusesLayout getBusesLayout () const
Provides the current channel layouts of this audio processor.
AudioChannelSet getChannelLayoutOfBus (bool isInput, int busIndex) const noexcept
Provides the channel layout of the bus with a given index and direction.
bool setChannelLayoutOfBus (bool isInput, int busIdx, const AudioChannelSet &layout)
Set the channel layout of the bus with a given index and direction.
int getChannelCountOfBus (bool isInput, int busIdx) const noexcept
Provides the number of channels of the bus with a given index and direction.
bool enableAllBuses ()
Enables all buses.
bool disableNonMainBuses ()
Disables all non-main buses (aux and sidechains).
int getChannelIndexInProcessBlockBuffer (bool isInput, int busIndex, int channelIndex) const noexcept
Returns the position of a bus's channels within the processBlock buffer.
int getOffsetInBusBufferForAbsoluteChannelIndex (bool isInput, int absoluteChannelIndex, int &busIdx) const noexcept
Returns the offset in a bus's buffer from an absolute channel indes.
template<typename FloatType >
AudioBuffer< FloatType > getBusBuffer (AudioBuffer< FloatType > &processBlockBuffer, bool isInput, int busIndex) const
Returns an AudioBuffer containing a set of channel pointers for a specific bus.
bool checkBusesLayoutSupported (const BusesLayout &) const
Returns true if the Audio processor is likely to support a given layout.
ProcessingPrecision getProcessingPrecision () const noexcept
Returns the precision-mode of the processor.
bool isUsingDoublePrecision () const noexcept
Returns true if the current precision is set to doublePrecision.
void setProcessingPrecision (ProcessingPrecision newPrecision) noexcept
Changes the processing precision of the receiver.
AudioPlayHead * getPlayHead () const noexcept
Returns the current AudioPlayHead object that should be used to find out the state and position of the playhead.
int getTotalNumInputChannels () const noexcept
Returns the total number of input channels.
int getTotalNumOutputChannels () const noexcept
Returns the total number of output channels.
int getMainBusNumInputChannels () const noexcept
Returns the number of input channels on the main bus.
int getMainBusNumOutputChannels () const noexcept
Returns the number of output channels on the main bus.
template<int numLayouts>
BusesLayout getNextBestLayoutInLayoutList (const BusesLayout &layouts, const short(&channelLayoutList)[numLayouts][2])
Returns the next best layout which is contained in a channel layout map.
double getSampleRate () const noexcept
Returns the current sample rate.
int getBlockSize () const noexcept
Returns the current typical block size that is being used.
int getLatencySamples () const noexcept
This returns the number of samples delay that the filter imposes on the audio passing through it.
void setLatencySamples (int newLatency)
The filter should call this to set the number of samples delay that it introduces.
virtual bool supportsMPE () const
Returns true if the processor supports MPE.
virtual bool isMidiEffect () const
Returns true if this is a midi effect plug-in and does no audio processing.
const CriticalSection & getCallbackLock () const noexcept
This returns a critical section that will automatically be locked while the host is calling the processBlock() method.
void suspendProcessing (bool shouldBeSuspended)
Enables and disables the processing callback.
bool isSuspended () const noexcept
Returns true if processing is currently suspended.
bool isNonRealtime () const noexcept
Returns true if the processor is being run in an offline mode for rendering.
AudioProcessorEditor * getActiveEditor () const noexcept
Returns the active editor, if there is one.
AudioProcessorEditor * createEditorIfNeeded ()
Returns the active editor, or if there isn't one, it will create one.
virtual int getNumParameters ()
This must return the correct value immediately after the object has been created, and mustn't change the number of parameters later.
virtual const String getParameterName (int parameterIndex)
Returns the name of a particular parameter.
virtual String getParameterID (int index)
Returns the ID of a particular parameter.
virtual float getParameter (int parameterIndex)
Called by the host to find out the value of one of the filter's parameters.
virtual String getParameterName (int parameterIndex, int maximumStringLength)
Returns the name of a parameter as a text string with a preferred maximum length.
virtual const String getParameterText (int parameterIndex)
Returns the value of a parameter as a text string.
virtual String getParameterText (int parameterIndex, int maximumStringLength)
Returns the value of a parameter as a text string with a preferred maximum length.
virtual int getParameterNumSteps (int parameterIndex)
Returns the number of discrete steps that this parameter can represent.
virtual float getParameterDefaultValue (int parameterIndex)
Returns the default value for the parameter.
virtual String getParameterLabel (int index) const
Some plugin types may be able to return a label string for a parameter's units.
virtual bool isParameterOrientationInverted (int index) const
This can be overridden to tell the host that particular parameters operate in the reverse direction.
virtual void setParameter (int parameterIndex, float newValue)
The host will call this method to change the value of one of the filter's parameters.
void setParameterNotifyingHost (int parameterIndex, float newValue)
Your filter can call this when it needs to change one of its parameters.
virtual bool isParameterAutomatable (int parameterIndex) const
Returns true if the host can automate this parameter.
virtual bool isMetaParameter (int parameterIndex) const
Should return true if this parameter is a "meta" parameter.
virtual
AudioProcessorParameter::Category getParameterCategory (int parameterIndex) const
Should return the parameter's category.
void beginParameterChangeGesture (int parameterIndex)
Sends a signal to the host to tell it that the user is about to start changing this parameter.
void endParameterChangeGesture (int parameterIndex)
Tells the host that the user has finished changing this parameter.
void updateHostDisplay ()
The filter can call this when something (apart from a parameter value) has changed.
void addParameter (AudioProcessorParameter *)
Adds a parameter to the list.
const OwnedArray
< AudioProcessorParameter > & getParameters () const noexcept
Returns the current list of parameters.
virtual void getCurrentProgramStateInformation (juce::MemoryBlock &destData)
The host will call this method if it wants to save the state of just the filter's current program.
virtual void setCurrentProgramStateInformation (const void *data, int sizeInBytes)
The host will call this method if it wants to restore the state of just the filter's current program.
virtual void numChannelsChanged ()
This method is called when the total number of input or output channels is changed.
virtual void numBusesChanged ()
This method is called when the number of buses is changed.
virtual void processorLayoutsChanged ()
This method is called when the layout of the audio processor changes.
virtual void addListener (AudioProcessorListener *newListener)
Adds a listener that will be called when an aspect of this processor changes.
virtual void removeListener (AudioProcessorListener *listenerToRemove)
Removes a previously added listener.
void setPlayConfigDetails (int numIns, int numOuts, double sampleRate, int blockSize)
This is called by the processor to specify its details before being played.
void setRateAndBufferSizeDetails (double sampleRate, int blockSize) noexcept
This is called by the processor to specify its details before being played.
virtual int32 getAAXPluginIDForMainBusConfig (const AudioChannelSet &mainInputLayout, const AudioChannelSet &mainOutputLayout, bool idForAudioSuite) const
AAX plug-ins need to report a unique "plug-in id" for every audio layout configuration that your AudioProcessor supports on the main bus.
void editorBeingDeleted (AudioProcessorEditor *) noexcept
Not for public use - this is called before deleting an editor component.
virtual void updateTrackProperties (const TrackProperties &properties)
Informs the AudioProcessor that track properties such as the track's name or colour has been changed.
Static Public Attributes
static const int midiChannelIndex
A special number that represents the midi channel of a node.
Additional Inherited Members
Public Types inherited from AudioProcessor
enum ProcessingPrecision { singlePrecision, doublePrecision }
enum WrapperType {
wrapperType_Undefined = 0, wrapperType_VST, wrapperType_VST3, wrapperType_AudioUnit,
wrapperType_AudioUnitv3, wrapperType_RTAS, wrapperType_AAX, wrapperType_Standalone
}
Flags to indicate the type of plugin context in which a processor is being used.
Static Public Member Functions inherited from AudioProcessor
static bool containsLayout (const BusesLayout &layouts, const std::initializer_list< const short[2]> &channelLayoutList)
Returns true if the channel layout map contains a certain layout.
template<int numLayouts>
static bool containsLayout (const BusesLayout &layouts, const short(&channelLayoutList)[numLayouts][2])
static int getDefaultNumParameterSteps () noexcept
Returns the default number of steps for a parameter.
static void copyXmlToBinary (const XmlElement &xml, juce::MemoryBlock &destData)
Helper function that just converts an xml element into a binary blob.
static XmlElement * getXmlFromBinary (const void *data, int sizeInBytes)
Retrieves an XML element that was stored as binary with the copyXmlToBinary() method.
static void JUCE_CALLTYPE setTypeOfNextNewPlugin (WrapperType)
Public Attributes inherited from AudioProcessor
WrapperType wrapperType
When loaded by a plugin wrapper, this flag will be set to indicate the type of plugin within which the processor is running.
Protected Member Functions inherited from AudioProcessor
AudioProcessor ()
Constructor.
AudioProcessor (const BusesProperties &ioLayouts)
Constructor for multibus AudioProcessors.
AudioProcessor (const std::initializer_list< const short[2]> &channelLayoutList)
Constructor for AudioProcessors which use layout maps.
virtual bool isBusesLayoutSupported (const BusesLayout &) const
Callback to query if the AudioProcessor supports a specific layout.
virtual bool canApplyBusesLayout (const BusesLayout &layouts) const
Callback to check if a certain bus layout can now be applied.
virtual bool canApplyBusCountChange (bool isInput, bool isAddingBuses, BusProperties &outNewBusProperties)
Callback to query if adding/removing buses currently possible.
void sendParamChangeMessageToListeners (int parameterIndex, float newValue)
Protected Attributes inherited from AudioProcessor
AudioPlayHead * playHead
Constructor & Destructor Documentation
AudioProcessorGraph::AudioProcessorGraph ()
Creates an empty graph.
AudioProcessorGraph::~AudioProcessorGraph ()
Destructor.
Any processor objects that have been added to the graph will also be deleted.
Member Function Documentation
void AudioProcessorGraph::clear ()
Deletes all nodes and connections from this graph.
Any processor objects in the graph will be deleted.
int AudioProcessorGraph::getNumNodes () const noexcept
Returns the number of nodes in the graph.
Node* AudioProcessorGraph::getNode (const int index) const noexcept
Returns a pointer to one of the nodes in the graph.
This will return nullptr if the index is out of range.
See Also
getNodeForId
Node* AudioProcessorGraph::getNodeForId (const uint32 nodeId) const
Searches the graph for a node with the given ID number and returns it.
If no such node was found, this returns nullptr.
See Also
getNode
Node* AudioProcessorGraph::addNode (AudioProcessor * newProcessor, uint32 nodeId = 0)
Adds a node to the graph.
This creates a new node in the graph, for the specified processor. Once you have added a processor to the graph, the graph owns it and will delete it later when it is no longer needed.
The optional nodeId parameter lets you specify an ID to use for the node, but if the value is already in use, this new node will overwrite the old one.
If this succeeds, it returns a pointer to the newly-created node.
bool AudioProcessorGraph::removeNode (uint32 nodeId)
Deletes a node within the graph which has the specified ID.
This will also delete any connections that are attached to this node.
bool AudioProcessorGraph::removeNode (Node * node)
Deletes a node within the graph.
This will also delete any connections that are attached to this node.
int AudioProcessorGraph::getNumConnections () const
Returns the number of connections in the graph.
const Connection* AudioProcessorGraph::getConnection (int index) const
Returns a pointer to one of the connections in the graph.
const Connection* AudioProcessorGraph::getConnectionBetween (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex) const
Searches for a connection between some specified channels.
If no such connection is found, this returns nullptr.
bool AudioProcessorGraph::isConnected (uint32 possibleSourceNodeId, uint32 possibleDestNodeId) const
Returns true if there is a connection between any of the channels of two specified nodes.
bool AudioProcessorGraph::canConnect (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex) const
Returns true if it would be legal to connect the specified points.
bool AudioProcessorGraph::addConnection (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex)
Attempts to connect two specified channels of two nodes.
If this isn't allowed (e.g. because you're trying to connect a midi channel to an audio one or other such nonsense), then it'll return false.
void AudioProcessorGraph::removeConnection (int index)
Deletes the connection with the specified index.
bool AudioProcessorGraph::removeConnection (uint32 sourceNodeId, int sourceChannelIndex, uint32 destNodeId, int destChannelIndex)
Deletes any connection between two specified points.
Returns true if a connection was actually deleted.
bool AudioProcessorGraph::disconnectNode (uint32 nodeId)
Removes all connections from the specified node.
bool AudioProcessorGraph::isConnectionLegal (const Connection * connection) const
Returns true if the given connection's channel numbers map on to valid channels at each end.
Even if a connection is valid when created, its status could change if a node changes its channel config.
bool AudioProcessorGraph::removeIllegalConnections ()
Performs a sanity checks of all the connections.
This might be useful if some of the processors are doing things like changing their channel counts, which could render some connections obsolete.
const String AudioProcessorGraph::getName () const override virtual
Returns the name of this processor.
Implements AudioProcessor.
void AudioProcessorGraph::prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) override virtual
Called before playback starts, to let the filter prepare itself.
The sample rate is the target sample rate, and will remain constant until playback stops.
You can call getTotalNumInputChannels and getTotalNumOutputChannels or query the busLayout member variable to find out the number of channels your processBlock callback must process.
The maximumExpectedSamplesPerBlock value is a strong hint about the maximum number of samples that will be provided in each block. You may want to use this value to resize internal buffers. You should program defensively in case a buggy host exceeds this value. The actual block sizes that the host uses may be different each time the callback happens: completely variable block sizes can be expected from some hosts.
See Also
busLayout, getTotalNumInputChannels, getTotalNumOutputChannels
Implements AudioProcessor.
void AudioProcessorGraph::releaseResources () override virtual
Called after playback has stopped, to let the filter free up any resources it no longer needs.
Implements AudioProcessor.
void AudioProcessorGraph::processBlock (AudioBuffer< float > & buffer, MidiBuffer & midiMessages) override virtual
Renders the next block.
When this method is called, the buffer contains a number of channels which is at least as great as the maximum number of input and output channels that this filter is using. It will be filled with the filter's input data and should be replaced with the filter's output.
So for example if your filter has a total of 2 input channels and 4 output channels, then the buffer will contain 4 channels, the first two being filled with the input data. Your filter should read these, do its processing, and replace the contents of all 4 channels with its output.
Or if your filter has a total of 5 inputs and 2 outputs, the buffer will have 5 channels, all filled with data, and your filter should overwrite the first 2 of these with its output. But be VERY careful not to write anything to the last 3 channels, as these might be mapped to memory that the host assumes is read-only!
If your plug-in has more than one input or output buses then the buffer passed to the processBlock methods will contain a bundle of all channels of each bus. Use AudiobusLayout::getBusBuffer to obtain an audio buffer for a particular bus.
Note that if you have more outputs than inputs, then only those channels that correspond to an input channel are guaranteed to contain sensible data - e.g. in the case of 2 inputs and 4 outputs, the first two channels contain the input, but the last two channels may contain garbage, so you should be careful not to let this pass through without being overwritten or cleared.
Also note that the buffer may have more channels than are strictly necessary, but you should only read/write from the ones that your filter is supposed to be using.
The number of samples in these buffers is NOT guaranteed to be the same for every callback, and may be more or less than the estimated value given to prepareToPlay(). Your code must be able to cope with variable-sized blocks, or you're going to get clicks and crashes!
Also note that some hosts will occasionally decide to pass a buffer containing zero samples, so make sure that your algorithm can deal with that!
If the filter is receiving a midi input, then the midiMessages array will be filled with the midi messages for this block. Each message's timestamp will indicate the message's time, as a number of samples from the start of the block.
Any messages left in the midi buffer when this method has finished are assumed to be the filter's midi output. This means that your filter should be careful to clear any incoming messages from the array if it doesn't want them to be passed-on.
Be very careful about what you do in this callback - it's going to be called by the audio thread, so any kind of interaction with the UI is absolutely out of the question. If you change a parameter in here and need to tell your UI to update itself, the best way is probably to inherit from a ChangeBroadcaster, let the UI components register as listeners, and then call sendChangeMessage() inside the processBlock() method to send out an asynchronous message. You could also use the AsyncUpdater class in a similar way.
See Also
AudiobusLayout::getBusBuffer
Implements AudioProcessor.
void AudioProcessorGraph::processBlock (AudioBuffer< double > & buffer, MidiBuffer & midiMessages) override virtual
Renders the next block.
When this method is called, the buffer contains a number of channels which is at least as great as the maximum number of input and output channels that this filter is using. It will be filled with the filter's input data and should be replaced with the filter's output.
So for example if your filter has a combined total of 2 input channels and 4 output channels, then the buffer will contain 4 channels, the first two being filled with the input data. Your filter should read these, do its processing, and replace the contents of all 4 channels with its output.
Or if your filter has 5 inputs and 2 outputs, the buffer will have 5 channels, all filled with data, and your filter should overwrite the first 2 of these with its output. But be VERY careful not to write anything to the last 3 channels, as these might be mapped to memory that the host assumes is read-only!
If your plug-in has more than one input or output buses then the buffer passed to the processBlock methods will contain a bundle of all channels of each bus. Use AudiobusLayout::getBusBuffer to obtain a audio buffer for a particular bus.
Note that if you have more outputs than inputs, then only those channels that correspond to an input channel are guaranteed to contain sensible data - e.g. in the case of 2 inputs and 4 outputs, the first two channels contain the input, but the last two channels may contain garbage, so you should be careful not to let this pass through without being overwritten or cleared.
Also note that the buffer may have more channels than are strictly necessary, but you should only read/write from the ones that your filter is supposed to be using.
If your plugin uses buses, then you should use AudiobusLayout::getBusBuffer() or AudiobusLayout::getChannelIndexInProcessBlockBuffer() to find out which of the input and output channels correspond to which of the buses.
The number of samples in these buffers is NOT guaranteed to be the same for every callback, and may be more or less than the estimated value given to prepareToPlay(). Your code must be able to cope with variable-sized blocks, or you're going to get clicks and crashes!
Also note that some hosts will occasionally decide to pass a buffer containing zero samples, so make sure that your algorithm can deal with that!
If the filter is receiving a midi input, then the midiMessages array will be filled with the midi messages for this block. Each message's timestamp will indicate the message's time, as a number of samples from the start of the block.
Any messages left in the midi buffer when this method has finished are assumed to be the filter's midi output. This means that your filter should be careful to clear any incoming messages from the array if it doesn't want them to be passed-on.
Be very careful about what you do in this callback - it's going to be called by the audio thread, so any kind of interaction with the UI is absolutely out of the question. If you change a parameter in here and need to tell your UI to update itself, the best way is probably to inherit from a ChangeBroadcaster, let the UI components register as listeners, and then call sendChangeMessage() inside the processBlock() method to send out an asynchronous message. You could also use the AsyncUpdater class in a similar way.
See Also
AudiobusLayout::getBusBuffer
Reimplemented from AudioProcessor.
bool AudioProcessorGraph::supportsDoublePrecisionProcessing () const override virtual
Returns true if the Audio processor supports double precision floating point processing.
The default implementation will always return false. If you return true here then you must override the double precision versions of processBlock. Additionally, you must call getProcessingPrecision() in your prepareToPlay method to determine the precision with which you need to allocate your internal buffers.
See Also
getProcessingPrecision, setProcessingPrecision
Reimplemented from AudioProcessor.
void AudioProcessorGraph::reset () override virtual
A plugin can override this to be told when it should reset any playing voices.
The default implementation does nothing, but a host may call this to tell the plugin that it should stop any tails or sounds that have been left running.
Reimplemented from AudioProcessor.
void AudioProcessorGraph::setNonRealtime (bool isNonRealtime) override virtual noexcept
Called by the host to tell this processor whether it's being used in a non-realtime capacity for offline rendering or bouncing.
Reimplemented from AudioProcessor.
void AudioProcessorGraph::setPlayHead (AudioPlayHead * newPlayHead) override virtual
Tells the processor to use this playhead object.
The processor will not take ownership of the object, so the caller must delete it when it is no longer being used.
Reimplemented from AudioProcessor.
double AudioProcessorGraph::getTailLengthSeconds () const override virtual
Returns the length of the filter's tail, in seconds.
Implements AudioProcessor.
bool AudioProcessorGraph::acceptsMidi () const override virtual
Returns true if the processor wants midi messages.
Implements AudioProcessor.
bool AudioProcessorGraph::producesMidi () const override virtual
Returns true if the processor produces midi messages.
Implements AudioProcessor.
bool AudioProcessorGraph::hasEditor () const override virtual
Your filter must override this and return true if it can create an editor component.
See Also
createEditor
Implements AudioProcessor.
AudioProcessorEditor* AudioProcessorGraph::createEditor () override virtual
Creates the filter's UI.
This can return nullptr if you want a UI-less filter, in which case the host may create a generic UI that lets the user twiddle the parameters directly.
If you do want to pass back a component, the component should be created and set to the correct size before returning it. If you implement this method, you must also implement the hasEditor() method and make it return true.
Remember not to do anything silly like allowing your filter to keep a pointer to the component that gets created - it could be deleted later without any warning, which would make your pointer into a dangler. Use the getActiveEditor() method instead.
The correct way to handle the connection between an editor component and its filter is to use something like a ChangeBroadcaster so that the editor can register itself as a listener, and be told when a change occurs. This lets them safely unregister themselves when they are deleted.
Here are a few things to bear in mind when writing an editor:
Initially there won't be an editor, until the user opens one, or they might not open one at all. Your filter mustn't rely on it being there.
An editor object may be deleted and a replacement one created again at any time.
It's safe to assume that an editor will be deleted before its filter.
See Also
hasEditor
Implements AudioProcessor.
int AudioProcessorGraph::getNumPrograms () override virtual
Returns the number of preset programs the filter supports.
The value returned must be valid as soon as this object is created, and must not change over its lifetime.
This value shouldn't be less than 1.
Implements AudioProcessor.
int AudioProcessorGraph::getCurrentProgram () override virtual
Returns the number of the currently active program.
Implements AudioProcessor.
void AudioProcessorGraph::setCurrentProgram (int index) override virtual
Called by the host to change the current program.
Implements AudioProcessor.
const String AudioProcessorGraph::getProgramName (int index) override virtual
Must return the name of a given program.
Implements AudioProcessor.
void AudioProcessorGraph::changeProgramName (int index, const String & newName) override virtual
Called by the host to rename a program.
Implements AudioProcessor.
void AudioProcessorGraph::getStateInformation (juce::MemoryBlock & destData) override virtual
The host will call this method when it wants to save the filter's internal state.
This must copy any info about the filter's state into the block of memory provided, so that the host can store this and later restore it using setStateInformation().
Note that there's also a getCurrentProgramStateInformation() method, which only stores the current program, not the state of the entire filter.
See also the helper function copyXmlToBinary() for storing settings as XML.
See Also
getCurrentProgramStateInformation
Implements AudioProcessor.
void AudioProcessorGraph::setStateInformation (const void * data, int sizeInBytes) override virtual
This must restore the filter's state from a block of data previously created using getStateInformation().
Note that there's also a setCurrentProgramStateInformation() method, which tries to restore just the current program, not the state of the entire filter.
See also the helper function getXmlFromBinary() for loading settings as XML.
See Also
setCurrentProgramStateInformation
Implements AudioProcessor.
Member Data Documentation
const int AudioProcessorGraph::midiChannelIndex static
A special number that represents the midi channel of a node.
This is used as a channel index value if you want to refer to the midi input or output instead of an audio channel.
class AudioProcessorListener
Base class for listeners that want to know about changes to an AudioProcessor.
Use AudioProcessor::addListener() to register your listener with an AudioProcessor.
See Also
AudioProcessor
Public Member Functions
virtual ~AudioProcessorListener ()
Destructor.
virtual void audioProcessorParameterChanged (AudioProcessor *processor, int parameterIndex, float newValue)=0
Receives a callback when a parameter is changed.
virtual void audioProcessorChanged (AudioProcessor *processor)=0
Called to indicate that something else in the plugin has changed, like its program, number of parameters, etc.
virtual void audioProcessorParameterChangeGestureBegin (AudioProcessor *processor, int parameterIndex)
Indicates that a parameter change gesture has started.
virtual void audioProcessorParameterChangeGestureEnd (AudioProcessor *processor, int parameterIndex)
Indicates that a parameter change gesture has finished.
Constructor & Destructor Documentation
virtual AudioProcessorListener::~AudioProcessorListener () virtual
Destructor.
Member Function Documentation
virtual void AudioProcessorListener::audioProcessorParameterChanged (AudioProcessor * processor, int parameterIndex, float newValue) pure virtual
Receives a callback when a parameter is changed.
IMPORTANT NOTE: this will be called synchronously when a parameter changes, and many audio processors will change their parameter during their audio callback. This means that not only has your handler code got to be completely thread-safe, but it's also got to be VERY fast, and avoid blocking. If you need to handle this event on your message thread, use this callback to trigger an AsyncUpdater or ChangeBroadcaster which you can respond to on the message thread.
virtual void AudioProcessorListener::audioProcessorChanged (AudioProcessor * processor) pure virtual
Called to indicate that something else in the plugin has changed, like its program, number of parameters, etc.
IMPORTANT NOTE: this will be called synchronously, and many audio processors will call it during their audio callback. This means that not only has your handler code got to be completely thread-safe, but it's also got to be VERY fast, and avoid blocking. If you need to handle this event on your message thread, use this callback to trigger an AsyncUpdater or ChangeBroadcaster which you can respond to later on the message thread.
virtual void AudioProcessorListener::audioProcessorParameterChangeGestureBegin (AudioProcessor * processor, int parameterIndex) virtual
Indicates that a parameter change gesture has started.
E.g. if the user is dragging a slider, this would be called when they first press the mouse button, and audioProcessorParameterChangeGestureEnd would be called when they release it.
IMPORTANT NOTE: this will be called synchronously, and many audio processors will call it during their audio callback. This means that not only has your handler code got to be completely thread-safe, but it's also got to be VERY fast, and avoid blocking. If you need to handle this event on your message thread, use this callback to trigger an AsyncUpdater or ChangeBroadcaster which you can respond to later on the message thread.
See Also
audioProcessorParameterChangeGestureEnd
virtual void AudioProcessorListener::audioProcessorParameterChangeGestureEnd (AudioProcessor * processor, int parameterIndex) virtual
Indicates that a parameter change gesture has finished.
E.g. if the user is dragging a slider, this would be called when they release the mouse button.
IMPORTANT NOTE: this will be called synchronously, and many audio processors will call it during their audio callback. This means that not only has your handler code got to be completely thread-safe, but it's also got to be VERY fast, and avoid blocking. If you need to handle this event on your message thread, use this callback to trigger an AsyncUpdater or ChangeBroadcaster which you can respond to later on the message thread.
See Also
audioProcessorParameterChangeGestureBegin
class AudioProcessorParameter
An abstract base class for parameter objects that can be added to an AudioProcessor.
See Also
AudioProcessor::addParameter
Public Types
enum Category {
genericParameter = (0 << 16) | 0, inputGain = (1 << 16) | 0, outputGain = (1 << 16) | 1, inputMeter = (2 << 16) | 0,
outputMeter = (2 << 16) | 1, compressorLimiterGainReductionMeter = (2 << 16) | 2, expanderGateGainReductionMeter = (2 << 16) | 3, analysisMeter = (2 << 16) | 4,
otherMeter = (2 << 16) | 5
}
Public Member Functions
AudioProcessorParameter () noexcept
virtual ~AudioProcessorParameter ()
Destructor.
virtual float getValue () const =0
Called by the host to find out the value of this parameter.
virtual void setValue (float newValue)=0
The host will call this method to change the value of one of the filter's parameters.
void setValueNotifyingHost (float newValue)
Your filter can call this when it needs to change one of its parameters.
void beginChangeGesture ()
Sends a signal to the host to tell it that the user is about to start changing this parameter.
void endChangeGesture ()
Tells the host that the user has finished changing this parameter.
virtual float getDefaultValue () const =0
This should return the default value for this parameter.
virtual String getName (int maximumStringLength) const =0
Returns the name to display for this parameter, which should be made to fit within the given string length.
virtual String getLabel () const =0
Some parameters may be able to return a label string for their units.
virtual int getNumSteps () const
Returns the number of discrete interval steps that this parameter's range should be quantised into.
virtual String getText (float value, int) const
Returns a textual version of the supplied parameter value.
virtual float getValueForText (const String &text) const =0
Should parse a string and return the appropriate value for it.
virtual bool isOrientationInverted () const
This can be overridden to tell the host that this parameter operates in the reverse direction.
virtual bool isAutomatable () const
Returns true if the host can automate this parameter.
virtual bool isMetaParameter () const
Should return true if this parameter is a "meta" parameter.
virtual Category getCategory () const
Returns the parameter's category.
int getParameterIndex () const noexcept
Returns the index of this parameter in its parent processor's parameter list.
Member Enumeration Documentation
enum AudioProcessorParameter::Category
Enumerator
genericParameter
inputGain
If your parameter is not a meter then you should use this category.
outputGain
Currently not used.
inputMeter
The following categories tell the host that this parameter is a meter level value and therefore read-only.
Most hosts will display these type of parameters as a meter in the generic view of your plug-in. Pro-Tools will also show the meter in the mixer view.
outputMeter
compressorLimiterGainReductionMeter
expanderGateGainReductionMeter
analysisMeter
otherMeter
Constructor & Destructor Documentation
AudioProcessorParameter::AudioProcessorParameter () noexcept
virtual AudioProcessorParameter::~AudioProcessorParameter () virtual
Destructor.
Member Function Documentation
virtual float AudioProcessorParameter::getValue () const pure virtual
Called by the host to find out the value of this parameter.
Hosts will expect the value returned to be between 0 and 1.0.
This could be called quite frequently, so try to make your code efficient. It's also likely to be called by non-UI threads, so the code in here should be thread-aware.
virtual void AudioProcessorParameter::setValue (float newValue) pure virtual
The host will call this method to change the value of one of the filter's parameters.
The host may call this at any time, including during the audio processing callback, so the filter has to process this very fast and avoid blocking.
If you want to set the value of a parameter internally, e.g. from your editor component, then don't call this directly - instead, use the setValueNotifyingHost() method, which will also send a message to the host telling it about the change. If the message isn't sent, the host won't be able to automate your parameters properly.
The value passed will be between 0 and 1.0.
void AudioProcessorParameter::setValueNotifyingHost (float newValue)
Your filter can call this when it needs to change one of its parameters.
This could happen when the editor or some other internal operation changes a parameter. This method will call the setValue() method to change the value, and will then send a message to the host telling it about the change.
Note that to make sure the host correctly handles automation, you should call the beginChangeGesture() and endChangeGesture() methods to tell the host when the user has started and stopped changing the parameter.
void AudioProcessorParameter::beginChangeGesture ()
Sends a signal to the host to tell it that the user is about to start changing this parameter.
This allows the host to know when a parameter is actively being held by the user, and it may use this information to help it record automation. If you call this, it must be matched by a later call to endChangeGesture().
void AudioProcessorParameter::endChangeGesture ()
Tells the host that the user has finished changing this parameter.
This allows the host to know when a parameter is actively being held by the user, and it may use this information to help it record automation. A call to this method must follow a call to beginChangeGesture().
virtual float AudioProcessorParameter::getDefaultValue () const pure virtual
This should return the default value for this parameter.
virtual String AudioProcessorParameter::getName (int maximumStringLength) const pure virtual
Returns the name to display for this parameter, which should be made to fit within the given string length.
virtual String AudioProcessorParameter::getLabel () const pure virtual
Some parameters may be able to return a label string for their units.
For example "Hz" or "%".
virtual int AudioProcessorParameter::getNumSteps () const virtual
Returns the number of discrete interval steps that this parameter's range should be quantised into.
If you want a continuous range of values, don't override this method, and allow the default implementation to return AudioProcessor::getDefaultNumParameterSteps(). If your parameter is boolean, then you may want to make this return 2. The value that is returned may or may not be used, depending on the host.
virtual String AudioProcessorParameter::getText (float value, int) const virtual
Returns a textual version of the supplied parameter value.
The default implementation just returns the floating point value as a string, but this could do anything you need for a custom type of value.
virtual float AudioProcessorParameter::getValueForText (const String & text) const pure virtual
Should parse a string and return the appropriate value for it.
virtual bool AudioProcessorParameter::isOrientationInverted () const virtual
This can be overridden to tell the host that this parameter operates in the reverse direction.
(Not all plugin formats or hosts will actually use this information).
virtual bool AudioProcessorParameter::isAutomatable () const virtual
Returns true if the host can automate this parameter.
By default, this returns true.
virtual bool AudioProcessorParameter::isMetaParameter () const virtual
Should return true if this parameter is a "meta" parameter.
A meta-parameter is a parameter that changes other params. It is used by some hosts (e.g. AudioUnit hosts). By default this returns false.
virtual Category AudioProcessorParameter::getCategory () const virtual
Returns the parameter's category.
int AudioProcessorParameter::getParameterIndex () const noexcept
Returns the index of this parameter in its parent processor's parameter list.
class GenericAudioProcessorEditor
A type of UI component that displays the parameters of an AudioProcessor as a simple list of sliders.
This can be used for showing an editor for a processor that doesn't supply its own custom editor.
See Also
AudioProcessor
Public Member Functions
GenericAudioProcessorEditor (AudioProcessor *owner)
~GenericAudioProcessorEditor ()
void paint (Graphics &) override
Components can override this method to draw their content.
void resized () override
Called when this component's size has been changed.
Public Member Functions inherited from AudioProcessorEditor
~AudioProcessorEditor ()
Destructor.
AudioProcessor * getAudioProcessor () const noexcept
Returns a pointer to the processor that this editor represents.
virtual void setControlHighlight (ParameterControlHighlightInfo)
Some types of plugin can call this to suggest that the control for a particular parameter should be highlighted.
virtual int getControlParameterIndex (Component &)
Called by certain plug-in wrappers to find out whether a component is used to control a parameter.
virtual bool supportsHostMIDIControllerPresence (bool hostMIDIControllerIsAvailable)
Override this method to indicate if your editor supports the presence or absence of a host-provided MIDI controller.
virtual void hostMIDIControllerIsAvailable (bool controllerIsAvailable)
Called to indicate if a host is providing a MIDI controller when the host reconfigures its layout.
virtual void setScaleFactor (float newScale)
Can be called by a host to tell the editor that it should use a non-unity GUI scale.
void setResizable (bool allowHostToResize, bool useBottomRightCornerResizer)
Marks the host's editor window as resizable.
bool isResizable () const noexcept
Returns true if the host is allowed to resize editor's parent window.
void setResizeLimits (int newMinimumWidth, int newMinimumHeight, int newMaximumWidth, int newMaximumHeight) noexcept
This sets the maximum and minimum sizes for the window.
ComponentBoundsConstrainer * getConstrainer () noexcept
Returns the bounds constrainer object that this window is using.
void setConstrainer (ComponentBoundsConstrainer *newConstrainer)
Sets the bounds-constrainer object to use for resizing and dragging this window.
void setBoundsConstrained (Rectangle< int > newBounds)
Calls the window's setBounds method, after first checking these bounds with the current constrainer.
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
virtual ~Component ()
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
virtual void visibilityChanged ()
Called when this component's visibility changes.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (int x, int y, int width, int height, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void parentHierarchyChanged ()
Called to indicate that the component's parents have changed.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
virtual void lookAndFeelChanged ()
Called to let the component react to a change in the look-and-feel setting.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparancy level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
virtual void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
virtual void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
virtual void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
virtual void mouseDown (const MouseEvent &event) override
Called when a mouse button is pressed.
virtual void mouseDrag (const MouseEvent &event) override
Called when the mouse is moved while a button is held down.
virtual void mouseUp (const MouseEvent &event) override
Called when a mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
virtual void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel) override
Called when the mouse-wheel is moved.
virtual void mouseMagnify (const MouseEvent &event, float scaleFactor)
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyPressed (const KeyPress &key)
Called when a key is pressed.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown () const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourId, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourId, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourId)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourId) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
virtual MarkerList * getMarkers (bool xAxis)
Components can implement this method to provide a MarkerList.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
JUCE_DEPRECATED (Point< int > relativePositionToGlobal(Point< int >) const)
JUCE_DEPRECATED (Point< int > globalPositionToRelative(Point< int >) const)
JUCE_DEPRECATED (Point< int > relativePositionToOtherComponent(const Component *, Point< int >) const)
JUCE_DEPRECATED (void setBounds(const RelativeRectangle &))
JUCE_DEPRECATED (void setBounds(const String &))
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()
Destructor.
Additional Inherited Members
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusChanged() and focusLost() methods.
Static Public Member Functions inherited from Component
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Public Attributes inherited from AudioProcessorEditor
AudioProcessor & processor
The AudioProcessor that this editor represents.
ScopedPointer
< ResizableCornerComponent > resizableCorner
Protected Member Functions inherited from AudioProcessorEditor
AudioProcessorEditor (AudioProcessor &) noexcept
Creates an editor for the specified processor.
AudioProcessorEditor (AudioProcessor *) noexcept
Creates an editor for the specified processor.
Constructor & Destructor Documentation
GenericAudioProcessorEditor::GenericAudioProcessorEditor (AudioProcessor * owner)
GenericAudioProcessorEditor::~GenericAudioProcessorEditor ()
Member Function Documentation
void GenericAudioProcessorEditor::paint (Graphics & g) override virtual
Components can override this method to draw their content.
The paint() method gets called when a region of a component needs redrawing, either because the component's repaint() method has been called, or because something has happened on the screen that means a section of a window needs to be redrawn.
Any child components will draw themselves over whatever this method draws. If you need to paint over the top of your child components, you can also implement the paintOverChildren() method to do this.
If you want to cause a component to redraw itself, this is done asynchronously - calling the repaint() method marks a region of the component as "dirty", and the paint() method will automatically be called sometime later, by the message thread, to paint any bits that need refreshing. In Juce (and almost all modern UI frameworks), you never redraw something synchronously.
You should never need to call this method directly - to take a snapshot of the component you could use createComponentSnapshot() or paintEntireComponent().
Parameters
g the graphics context that must be used to do the drawing operations.
See Also
repaint, paintOverChildren, Graphics
Reimplemented from Component.
void GenericAudioProcessorEditor::resized () override virtual
Called when this component's size has been changed.
A component can implement this method to do things such as laying out its child components when its width or height changes.
The method is called synchronously as a result of the setBounds or setSize methods, so repeatedly changing a components size will repeatedly call its resized method (unlike things like repainting, where multiple calls to repaint are coalesced together).
If the component is a top-level window on the desktop, its size could also be changed by operating-system factors beyond the application's control.
See Also
moved, setSize
Reimplemented from Component.
class PluginDescription
A small class to represent some facts about a particular type of plug-in.
This class is for storing and managing the details about a plug-in without actually having to load an instance of it.
A KnownPluginList contains a list of PluginDescription objects.
See Also
KnownPluginList
Public Member Functions
PluginDescription ()
PluginDescription (const PluginDescription &other)
PluginDescription & operator= (const PluginDescription &other)
~PluginDescription ()
bool isDuplicateOf (const PluginDescription &other) const noexcept
Returns true if the two descriptions refer to the same plug-in.
bool matchesIdentifierString (const String &identifierString) const
Return true if this description is equivalent to another one which created the given identifier string.
String createIdentifierString () const
Returns a string that can be saved and used to uniquely identify the plugin again.
XmlElement * createXml () const
Creates an XML object containing these details.
bool loadFromXml (const XmlElement &xml)
Reloads the info in this structure from an XML record that was previously saved with createXML().
Public Attributes
String name
The name of the plug-in.
String descriptiveName
A more descriptive name for the plug-in.
String pluginFormatName
The plug-in format, e.g.
String category
A category, such as "Dynamics", "Reverbs", etc.
String manufacturerName
The manufacturer.
String version
The version.
String fileOrIdentifier
Either the file containing the plug-in module, or some other unique way of identifying it.
Time lastFileModTime
The last time the plug-in file was changed.
Time lastInfoUpdateTime
The last time that this information was updated.
int uid
A unique ID for the plug-in.
bool isInstrument
True if the plug-in identifies itself as a synthesiser.
int numInputChannels
The number of inputs.
int numOutputChannels
The number of outputs.
bool hasSharedContainer
True if the plug-in is part of a multi-type container, e.g.
Constructor & Destructor Documentation
PluginDescription::PluginDescription ()
PluginDescription::PluginDescription (const PluginDescription & other)
PluginDescription::~PluginDescription ()
Member Function Documentation
PluginDescription& PluginDescription::operator= (const PluginDescription & other)
bool PluginDescription::isDuplicateOf (const PluginDescription & other) const noexcept
Returns true if the two descriptions refer to the same plug-in.
This isn't quite as simple as them just having the same file (because of shell plug-ins).
bool PluginDescription::matchesIdentifierString (const String & identifierString) const
Return true if this description is equivalent to another one which created the given identifier string.
Note that this isn't quite as simple as them just calling createIdentifierString() and comparing the strings, because the identifiers can differ (thanks to shell plug-ins).
String PluginDescription::createIdentifierString () const
Returns a string that can be saved and used to uniquely identify the plugin again.
This contains less info than the XML encoding, and is independent of the plug-in's file location, so can be used to store a plug-in ID for use across different machines.
XmlElement* PluginDescription::createXml () const
Creates an XML object containing these details.
See Also
loadFromXml
bool PluginDescription::loadFromXml (const XmlElement & xml)
Reloads the info in this structure from an XML record that was previously saved with createXML().
Returns true if the XML was a valid plug-in description.
Member Data Documentation
String PluginDescription::name
The name of the plug-in.
String PluginDescription::descriptiveName
A more descriptive name for the plug-in.
This may be the same as the 'name' field, but some plug-ins may provide an alternative name.
String PluginDescription::pluginFormatName
The plug-in format, e.g.
"VST", "AudioUnit", etc.
String PluginDescription::category
A category, such as "Dynamics", "Reverbs", etc.
String PluginDescription::manufacturerName
The manufacturer.
String PluginDescription::version
The version.
This string doesn't have any particular format.
String PluginDescription::fileOrIdentifier
Either the file containing the plug-in module, or some other unique way of identifying it.
E.g. for an AU, this would be an ID string that the component manager could use to retrieve the plug-in. For a VST, it's the file path.
Time PluginDescription::lastFileModTime
The last time the plug-in file was changed.
This is handy when scanning for new or changed plug-ins.
Time PluginDescription::lastInfoUpdateTime
The last time that this information was updated.
This would typically have been during a scan when this plugin was first tested or found to have changed.
int PluginDescription::uid
A unique ID for the plug-in.
Note that this might not be unique between formats, e.g. a VST and some other format might actually have the same id.
See Also
createIdentifierString
bool PluginDescription::isInstrument
True if the plug-in identifies itself as a synthesiser.
int PluginDescription::numInputChannels
The number of inputs.
int PluginDescription::numOutputChannels
The number of outputs.
bool PluginDescription::hasSharedContainer
True if the plug-in is part of a multi-type container, e.g.
a VST Shell.