JUCE: processors
processors
juce_dsp
Namespaces
FIR
Classes for FIR filter processing.
IIR
Classes for IIR filter processing.
StateVariableFilter
An IIR filter that can perform low, band and high-pass filtering on an audio signal, with 12 dB of attenuation / octave, using a TPT structure, designed for fast modulation (see Vadim Zavalishin's documentation about TPT structures for more information).
Classes
class Bias< FloatType >
Adds a DC offset (voltage bias) to the audio samples.
struct FIR::Coefficients< NumericType >
A set of coefficients for use in an FIRFilter object.
class FIR::Filter< SampleType >
A processing class that can perform FIR filtering on an audio signal, in the time domain.
class Gain< FloatType >
Applies a gain to audio samples as single samples or AudioBlocks.
class Oscillator< SampleType >
Generates a signal based on a user-supplied function.
struct ProcessSpec
This structure is passed into a DSP algorithm's prepare() method, and contains information about various aspects of the context in which it can expect to be called.
struct ProcessorState
This is a handy base class for the state of a processor (such as parameter values) which is typically shared among several procoessors.
struct ProcessContextReplacing< ContextSampleType >
Contains context information that is passed into an algorithm's process method.
struct ProcessContextNonReplacing< ContextSampleType >
Contains context information that is passed into an algorithm's process method.
struct ProcessorDuplicator< MonoProcessorType, StateType >
Converts a mono processor class into a multi-channel version by duplicating it and applying multichannel buffers across an array of instances.
struct ProcessorBase
Acts as a polymorphic base class for processors.
struct ProcessorWrapper< ProcessorType >
Wraps an instance of a given processor class, and exposes it through the ProcessorBase interface.
struct StateVariableFilter::Parameters< NumericType >
struct WaveShaper< FloatType, Function >
Applies waveshaping to audio samples as single samples or AudioBlocks.
Typedefs
template<typename... Processors>
using ProcessorChain = ProcessorHelpers::Chain< Processors...>
This variadically-templated class lets you join together any number of processor classes into a single processor which will call process() on them all in sequence.
Detailed Description
Class Documentation
class Bias
template<typename FloatType>
class Bias< FloatType >
Adds a DC offset (voltage bias) to the audio samples.
This is a useful preprocessor for asymmetric waveshaping when a waveshaper is bookended by a bias on input and a DC-offset removing high pass filter on output.
This is an extremely simple bias implementation that simply adds a value to a signal. More complicated bias behaviours exist in real circuits - for your homework ;).
Public Member Functions
Bias () noexcept
void setBias (FloatType newBias) noexcept
Sets the DC bias.
FloatType getBias () const noexcept
Returns the DC bias.
void setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
double getRampDurationSeconds () const noexcept
void prepare (const ProcessSpec &spec) noexcept
Called before processing starts.
void reset () noexcept
template<typename SampleType >
SampleType processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes the input and output buffers supplied in the processing context.
Constructor & Destructor Documentation
template<typename FloatType > Bias< FloatType >::Bias () noexcept
Member Function Documentation
template<typename FloatType > void Bias< FloatType >::setBias (FloatType newBias) noexcept
Sets the DC bias.
Parameters
newBias DC offset in range [-1, 1]
References jassert.
template<typename FloatType > FloatType Bias< FloatType >::getBias () const noexcept
Returns the DC bias.
Returns
DC bias, which should be in the range [-1, 1]
template<typename FloatType > void Bias< FloatType >::setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
template<typename FloatType > double Bias< FloatType >::getRampDurationSeconds () const noexcept
template<typename FloatType > void Bias< FloatType >::prepare (const ProcessSpec & spec) noexcept
Called before processing starts.
template<typename FloatType > void Bias< FloatType >::reset () noexcept
template<typename FloatType > template<typename SampleType > SampleType Bias< FloatType >::processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
template<typename FloatType > template<typename ProcessContext > void Bias< FloatType >::process (const ProcessContext & context) noexcept
Processes the input and output buffers supplied in the processing context.
References FloatVectorOperations::add(), and jassert.
struct FIR::Coefficients
template<typename NumericType>
struct FIR::Coefficients< NumericType >
A set of coefficients for use in an FIRFilter object.
See Also
FIRFilter
Public Types
using Ptr = ReferenceCountedObjectPtr< Coefficients >
The Coefficients structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Public Types inherited from ProcessorState
using Ptr = ReferenceCountedObjectPtr< ProcessorState >
The ProcessorState structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Public Member Functions
Coefficients ()
Creates a null set of coefficients (which will produce silence).
Coefficients (Coefficients &&)=default
Move constructor.
Coefficients (const NumericType *samples, size_t numSamples)
Creates a set of coefficients from an array of samples.
Coefficients & operator= (const Coefficients &other)
Creates a copy of another filter.
Coefficients & operator= (Coefficients &&)=default
Creates a copy of another filter.
size_t getFilterOrder () const noexcept
Returns the filter order associated with the coefficients.
double getMagnitudeForFrequency (double frequency, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency and sample rate.
void getMagnitudeForFrequencyArray (double *frequencies, double *magnitudes, size_t numSamples, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency array and sample rate.
double getPhaseForFrequency (double frequency, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency and sample rate.
void getPhaseForFrequencyArray (double *frequencies, double *phases, size_t numSamples, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency array and sample rate.
NumericType * getRawCoefficients () noexcept
Returns a raw data pointer to the coefficients.
const NumericType * getRawCoefficients () const noexcept
Returns a raw data pointer to the coefficients.
void normalise () noexcept
Scales the values of the FIR filter with the sum of the squared coefficients.
Public Member Functions inherited from ReferenceCountedObject
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Public Attributes
Array< NumericType > coefficients
The raw coefficients.
Additional Inherited Members
Protected Member Functions inherited from ReferenceCountedObject
ReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () noexcept
Resets the reference count to zero without deleting the object.
Member Typedef Documentation
template<typename NumericType> using FIR::Coefficients< NumericType >::Ptr = ReferenceCountedObjectPtr<Coefficients>
The Coefficients structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Constructor & Destructor Documentation
template<typename NumericType> FIR::Coefficients< NumericType >::Coefficients ()
Creates a null set of coefficients (which will produce silence).
template<typename NumericType> FIR::Coefficients< NumericType >::Coefficients (Coefficients< NumericType > &&) default
Move constructor.
template<typename NumericType> FIR::Coefficients< NumericType >::Coefficients (const NumericType * samples, size_t numSamples)
Creates a set of coefficients from an array of samples.
Member Function Documentation
template<typename NumericType> Coefficients& FIR::Coefficients< NumericType >::operator= (const Coefficients< NumericType > & other)
Creates a copy of another filter.
References FIR::Coefficients< NumericType >::coefficients.
template<typename NumericType> Coefficients& FIR::Coefficients< NumericType >::operator= (Coefficients< NumericType > &&) default
Creates a copy of another filter.
template<typename NumericType> size_t FIR::Coefficients< NumericType >::getFilterOrder () const noexcept
Returns the filter order associated with the coefficients.
References FIR::Coefficients< NumericType >::coefficients, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<typename NumericType> double FIR::Coefficients< NumericType >::getMagnitudeForFrequency (double frequency, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency and sample rate.
template<typename NumericType> void FIR::Coefficients< NumericType >::getMagnitudeForFrequencyArray (double * frequencies, double * magnitudes, size_t numSamples, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency array and sample rate.
template<typename NumericType> double FIR::Coefficients< NumericType >::getPhaseForFrequency (double frequency, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency and sample rate.
template<typename NumericType> void FIR::Coefficients< NumericType >::getPhaseForFrequencyArray (double * frequencies, double * phases, size_t numSamples, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency array and sample rate.
template<typename NumericType> NumericType* FIR::Coefficients< NumericType >::getRawCoefficients () noexcept
Returns a raw data pointer to the coefficients.
References FIR::Coefficients< NumericType >::coefficients, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer().
template<typename NumericType> const NumericType* FIR::Coefficients< NumericType >::getRawCoefficients () const noexcept
Returns a raw data pointer to the coefficients.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin(), and FIR::Coefficients< NumericType >::coefficients.
template<typename NumericType> void FIR::Coefficients< NumericType >::normalise () noexcept
Scales the values of the FIR filter with the sum of the squared coefficients.
Member Data Documentation
template<typename NumericType> Array<NumericType> FIR::Coefficients< NumericType >::coefficients
The raw coefficients.
You should leave these numbers alone unless you really know what you're doing.
Referenced by FIR::Coefficients< NumericType >::getFilterOrder(), FIR::Coefficients< NumericType >::getRawCoefficients(), and FIR::Coefficients< NumericType >::operator=().
class FIR::Filter
template<typename SampleType>
class FIR::Filter< SampleType >
A processing class that can perform FIR filtering on an audio signal, in the time domain.
Using FIRFilter is fast enough for FIRCoefficients with a size lower than 128 samples. For longer filters, it might be more efficient to use the class Convolution instead, which does the same processing in the frequency domain thanks to FFT.
See Also
FIRFilter::Coefficients, Convolution, FFT
Public Types
using NumericType = typename SampleTypeHelpers::ElementType< SampleType >::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Public Member Functions
Filter ()
This will create a filter which will produce silence.
Filter (Coefficients< NumericType > *coefficientsToUse)
Creates a filter with a given set of coefficients.
Filter (const Filter &)=default
Creates a copy of another filter.
Filter (Filter &&)=default
Creates a copy of another filter.
Filter & operator= (const Filter &)=default
Assignment operator.
Filter & operator= (Filter &&)=default
Assignment operator.
void prepare (const ProcessSpec &spec) noexcept
Prepare this filter for processing.
void reset ()
Resets the filter's processing pipeline, ready to start a new stream of data.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes as a block of samples.
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType sample) noexcept
Processes a single sample, without any locking.
Public Attributes
Coefficients< NumericType >::Ptr coefficients
The coefficients of the FIR filter.
Member Typedef Documentation
template<typename SampleType > using FIR::Filter< SampleType >::NumericType = typename SampleTypeHelpers::ElementType<SampleType>::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Constructor & Destructor Documentation
template<typename SampleType > FIR::Filter< SampleType >::Filter ()
This will create a filter which will produce silence.
References FIR::Filter< SampleType >::reset().
template<typename SampleType > FIR::Filter< SampleType >::Filter (Coefficients< NumericType > * coefficientsToUse)
Creates a filter with a given set of coefficients.
References FIR::Filter< SampleType >::reset().
template<typename SampleType > FIR::Filter< SampleType >::Filter (const Filter< SampleType > &) default
Creates a copy of another filter.
template<typename SampleType > FIR::Filter< SampleType >::Filter (Filter< SampleType > &&) default
Creates a copy of another filter.
Member Function Documentation
template<typename SampleType > Filter& FIR::Filter< SampleType >::operator= (const Filter< SampleType > &) default
Assignment operator.
template<typename SampleType > Filter& FIR::Filter< SampleType >::operator= (Filter< SampleType > &&) default
Assignment operator.
template<typename SampleType > void FIR::Filter< SampleType >::prepare (const ProcessSpec & spec) noexcept
Prepare this filter for processing.
References ignoreUnused(), jassert, and FIR::Filter< SampleType >::reset().
template<typename SampleType > void FIR::Filter< SampleType >::reset ()
Resets the filter's processing pipeline, ready to start a new stream of data.
Note that this clears the processing state, but the type of filter and its coefficients aren't changed. To disable the filter, call setEnabled (false).
References FIR::Filter< SampleType >::coefficients, HeapBlock< ElementType, throwOnFailure >::getData(), jmax(), HeapBlock< ElementType, throwOnFailure >::malloc(), and snapPointerToAlignment().
Referenced by FIR::Filter< SampleType >::Filter(), and FIR::Filter< SampleType >::prepare().
template<typename SampleType > template<typename ProcessContext > void FIR::Filter< SampleType >::process (const ProcessContext & context) noexcept
Processes as a block of samples.
References FIR::Filter< SampleType >::coefficients, and jassert.
template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE FIR::Filter< SampleType >::processSample (SampleType sample) noexcept
Processes a single sample, without any locking.
Use this if you need processing of a single value.
References FIR::Filter< SampleType >::coefficients.
Member Data Documentation
template<typename SampleType > Coefficients<NumericType>::Ptr FIR::Filter< SampleType >::coefficients
The coefficients of the FIR filter.
It's up to the called to ensure that these coefficients are modified in a thread-safe way.
If you change the order of the coefficients then you must call reset after modifying them.
Referenced by FIR::Filter< SampleType >::process(), FIR::Filter< SampleType >::processSample(), and FIR::Filter< SampleType >::reset().
class Gain
template<typename FloatType>
class Gain< FloatType >
Applies a gain to audio samples as single samples or AudioBlocks.
Public Member Functions
Gain () noexcept
void setGainLinear (FloatType newGain) noexcept
Applies a new gain as a linear value.
void setGainDecibels (FloatType newGainDecibels) noexcept
Applies a new gain as a decibel value.
FloatType getGainLinear () const noexcept
Returns the current gain as a linear value.
FloatType getGainDecibels () const noexcept
Returns the current gain in decibels.
void setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
double getRampDurationSeconds () const noexcept
Returns the ramp duration in seconds.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
void prepare (const ProcessSpec &spec) noexcept
Called before processing starts.
void reset () noexcept
Resets the internal state of the gain.
template<typename SampleType >
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType s) noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes the input and output buffers supplied in the processing context.
Constructor & Destructor Documentation
template<typename FloatType > Gain< FloatType >::Gain () noexcept
Member Function Documentation
template<typename FloatType > void Gain< FloatType >::setGainLinear (FloatType newGain) noexcept
Applies a new gain as a linear value.
Referenced by Gain< FloatType >::setGainDecibels().
template<typename FloatType > void Gain< FloatType >::setGainDecibels (FloatType newGainDecibels) noexcept
Applies a new gain as a decibel value.
References Gain< FloatType >::setGainLinear().
template<typename FloatType > FloatType Gain< FloatType >::getGainLinear () const noexcept
Returns the current gain as a linear value.
Referenced by Gain< FloatType >::getGainDecibels().
template<typename FloatType > FloatType Gain< FloatType >::getGainDecibels () const noexcept
Returns the current gain in decibels.
References Gain< FloatType >::getGainLinear().
template<typename FloatType > void Gain< FloatType >::setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
References Gain< FloatType >::reset().
template<typename FloatType > double Gain< FloatType >::getRampDurationSeconds () const noexcept
Returns the ramp duration in seconds.
template<typename FloatType > bool Gain< FloatType >::isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
template<typename FloatType > void Gain< FloatType >::prepare (const ProcessSpec & spec) noexcept
Called before processing starts.
References Gain< FloatType >::reset().
template<typename FloatType > void Gain< FloatType >::reset () noexcept
Resets the internal state of the gain.
Referenced by Gain< FloatType >::prepare(), and Gain< FloatType >::setRampDurationSeconds().
template<typename FloatType > template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE Gain< FloatType >::processSample (SampleType s) noexcept
Returns the result of processing a single sample.
template<typename FloatType > template<typename ProcessContext > void Gain< FloatType >::process (const ProcessContext & context) noexcept
Processes the input and output buffers supplied in the processing context.
References jassert, and FloatVectorOperations::multiply().
class Oscillator
template<typename SampleType>
class Oscillator< SampleType >
Generates a signal based on a user-supplied function.
Public Types
using NumericType = typename SampleTypeHelpers::ElementType< SampleType >::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Public Member Functions
Oscillator (const std::function< NumericType(NumericType)> &function, size_t lookupTableNumPoints=0)
Creates an oscillator with a periodic input function (-pi..pi).
void setFrequency (NumericType newGain) noexcept
Sets the frequency of the oscillator.
NumericType getFrequency () const noexcept
Returns the current frequency of the oscillator.
void prepare (const ProcessSpec &spec) noexcept
Called before processing starts.
void reset () noexcept
Resets the internal state of the oscillator.
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType) noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes the input and output buffers supplied in the processing context.
Member Typedef Documentation
template<typename SampleType > using Oscillator< SampleType >::NumericType = typename SampleTypeHelpers::ElementType<SampleType>::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Constructor & Destructor Documentation
template<typename SampleType > Oscillator< SampleType >::Oscillator (const std::function< NumericType(NumericType)> & function, size_t lookupTableNumPoints = 0)
Creates an oscillator with a periodic input function (-pi..pi).
If lookup table is not zero, then the function will be approximated with a lookup table.
References double_Pi.
Member Function Documentation
template<typename SampleType > void Oscillator< SampleType >::setFrequency (NumericType newGain) noexcept
Sets the frequency of the oscillator.
References LinearSmoothedValue< FloatType >::setValue().
template<typename SampleType > NumericType Oscillator< SampleType >::getFrequency () const noexcept
Returns the current frequency of the oscillator.
References LinearSmoothedValue< FloatType >::getTargetValue().
template<typename SampleType > void Oscillator< SampleType >::prepare (const ProcessSpec & spec) noexcept
Called before processing starts.
References Oscillator< SampleType >::reset(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::resize().
template<typename SampleType > void Oscillator< SampleType >::reset () noexcept
Resets the internal state of the oscillator.
References LinearSmoothedValue< FloatType >::reset().
Referenced by Oscillator< SampleType >::prepare().
template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE Oscillator< SampleType >::processSample (SampleType) noexcept
Returns the result of processing a single sample.
References double_Pi, and LinearSmoothedValue< FloatType >::getNextValue().
template<typename SampleType > template<typename ProcessContext > void Oscillator< SampleType >::process (const ProcessContext & context) noexcept
Processes the input and output buffers supplied in the processing context.
References double_Pi, LinearSmoothedValue< FloatType >::getNextValue(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer(), LinearSmoothedValue< FloatType >::isSmoothing(), jassert, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
struct ProcessSpec
This structure is passed into a DSP algorithm's prepare() method, and contains information about various aspects of the context in which it can expect to be called.
Public Attributes
double sampleRate
The sample rate that will be used for the data that is sent to the processor.
uint32 maximumBlockSize
The maximum number of samples that will be in the blocks sent to process() method.
uint32 numChannels
The number of channels that the process() method will be expected to handle.
Member Data Documentation
double ProcessSpec::sampleRate
The sample rate that will be used for the data that is sent to the processor.
uint32 ProcessSpec::maximumBlockSize
The maximum number of samples that will be in the blocks sent to process() method.
uint32 ProcessSpec::numChannels
The number of channels that the process() method will be expected to handle.
Referenced by ProcessorDuplicator< MonoProcessorType, StateType >::prepare().
struct ProcessorState
This is a handy base class for the state of a processor (such as parameter values) which is typically shared among several procoessors.
This is useful to for multi-mono filters which share the same state among several mono processors.
Public Types
using Ptr = ReferenceCountedObjectPtr< ProcessorState >
The ProcessorState structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Additional Inherited Members
Public Member Functions inherited from ReferenceCountedObject
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Protected Member Functions inherited from ReferenceCountedObject
ReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () noexcept
Resets the reference count to zero without deleting the object.
Member Typedef Documentation
using ProcessorState::Ptr = ReferenceCountedObjectPtr<ProcessorState>
The ProcessorState structure is ref-counted, so this is a handy type that can be used as a pointer to one.
struct ProcessContextReplacing
template<typename ContextSampleType>
struct ProcessContextReplacing< ContextSampleType >
Contains context information that is passed into an algorithm's process method.
This context is intended for use in situations where a single block is being used for both the input and output, so it will return the same object for both its getInputBlock() and getOutputBlock() methods.
See Also
ProcessContextNonReplacing
Public Types
using SampleType = ContextSampleType
The type of a single sample (which may be a vector if multichannel).
using AudioBlockType = AudioBlock< SampleType >
The type of audio block that this context handles.
Public Member Functions
ProcessContextReplacing (AudioBlockType &block) noexcept
Creates a ProcessContextReplacing that uses the given audio block.
ProcessContextReplacing (const ProcessContextReplacing &)=default
ProcessContextReplacing (ProcessContextReplacing &&)=default
const AudioBlockType & getInputBlock () const noexcept
Returns the audio block to use as the input to a process function.
AudioBlockType & getOutputBlock () const noexcept
Returns the audio block to use as the output to a process function.
Static Public Member Functions
static constexpr bool usesSeparateInputAndOutputBlocks ()
All process context classes will define this constant method so that templated code can determine whether the input and output blocks refer to the same buffer, or to two different ones.
Public Attributes
bool isBypassed = false
If set to true, then a processor's process() method is expected to do whatever is appropriate for it to be in a bypassed state.
Member Typedef Documentation
template<typename ContextSampleType> using ProcessContextReplacing< ContextSampleType >::SampleType = ContextSampleType
The type of a single sample (which may be a vector if multichannel).
template<typename ContextSampleType> using ProcessContextReplacing< ContextSampleType >::AudioBlockType = AudioBlock<SampleType>
The type of audio block that this context handles.
Constructor & Destructor Documentation
template<typename ContextSampleType> ProcessContextReplacing< ContextSampleType >::ProcessContextReplacing (AudioBlockType & block) noexcept
Creates a ProcessContextReplacing that uses the given audio block.
Note that the caller must not delete the block while it is still in use by this object!
template<typename ContextSampleType> ProcessContextReplacing< ContextSampleType >::ProcessContextReplacing (const ProcessContextReplacing< ContextSampleType > &) default
template<typename ContextSampleType> ProcessContextReplacing< ContextSampleType >::ProcessContextReplacing (ProcessContextReplacing< ContextSampleType > &&) default
Member Function Documentation
template<typename ContextSampleType> const AudioBlockType& ProcessContextReplacing< ContextSampleType >::getInputBlock () const noexcept
Returns the audio block to use as the input to a process function.
template<typename ContextSampleType> AudioBlockType& ProcessContextReplacing< ContextSampleType >::getOutputBlock () const noexcept
Returns the audio block to use as the output to a process function.
template<typename ContextSampleType> static constexpr bool ProcessContextReplacing< ContextSampleType >::usesSeparateInputAndOutputBlocks () static
All process context classes will define this constant method so that templated code can determine whether the input and output blocks refer to the same buffer, or to two different ones.
Member Data Documentation
template<typename ContextSampleType> bool ProcessContextReplacing< ContextSampleType >::isBypassed = false
If set to true, then a processor's process() method is expected to do whatever is appropriate for it to be in a bypassed state.
struct ProcessContextNonReplacing
template<typename ContextSampleType>
struct ProcessContextNonReplacing< ContextSampleType >
Contains context information that is passed into an algorithm's process method.
This context is intended for use in situations where two different blocks are being used the input and output to the process algorithm, so the processor must read from the block returned by getInputBlock() and write its results to the block returned by getOutputBlock().
See Also
ProcessContextReplacing
Public Types
using SampleType = ContextSampleType
The type of a single sample (which may be a vector if multichannel).
using AudioBlockType = AudioBlock< SampleType >
The type of audio block that this context handles.
Public Member Functions
ProcessContextNonReplacing (const AudioBlockType &input, AudioBlockType &output) noexcept
Creates a ProcessContextReplacing that uses the given input and output blocks.
ProcessContextNonReplacing (const ProcessContextNonReplacing &)=default
ProcessContextNonReplacing (ProcessContextNonReplacing &&)=default
const AudioBlockType & getInputBlock () const noexcept
Returns the audio block to use as the input to a process function.
AudioBlockType & getOutputBlock () const noexcept
Returns the audio block to use as the output to a process function.
Static Public Member Functions
static constexpr bool usesSeparateInputAndOutputBlocks ()
All process context classes will define this constant method so that templated code can determine whether the input and output blocks refer to the same buffer, or to two different ones.
Public Attributes
bool isBypassed = false
If set to true, then a processor's process() method is expected to do whatever is appropriate for it to be in a bypassed state.
Member Typedef Documentation
template<typename ContextSampleType > using ProcessContextNonReplacing< ContextSampleType >::SampleType = ContextSampleType
The type of a single sample (which may be a vector if multichannel).
template<typename ContextSampleType > using ProcessContextNonReplacing< ContextSampleType >::AudioBlockType = AudioBlock<SampleType>
The type of audio block that this context handles.
Constructor & Destructor Documentation
template<typename ContextSampleType > ProcessContextNonReplacing< ContextSampleType >::ProcessContextNonReplacing (const AudioBlockType & input, AudioBlockType & output) noexcept
Creates a ProcessContextReplacing that uses the given input and output blocks.
Note that the caller must not delete these blocks while they are still in use by this object!
template<typename ContextSampleType > ProcessContextNonReplacing< ContextSampleType >::ProcessContextNonReplacing (const ProcessContextNonReplacing< ContextSampleType > &) default
template<typename ContextSampleType > ProcessContextNonReplacing< ContextSampleType >::ProcessContextNonReplacing (ProcessContextNonReplacing< ContextSampleType > &&) default
Member Function Documentation
template<typename ContextSampleType > const AudioBlockType& ProcessContextNonReplacing< ContextSampleType >::getInputBlock () const noexcept
Returns the audio block to use as the input to a process function.
template<typename ContextSampleType > AudioBlockType& ProcessContextNonReplacing< ContextSampleType >::getOutputBlock () const noexcept
Returns the audio block to use as the output to a process function.
template<typename ContextSampleType > static constexpr bool ProcessContextNonReplacing< ContextSampleType >::usesSeparateInputAndOutputBlocks () static
All process context classes will define this constant method so that templated code can determine whether the input and output blocks refer to the same buffer, or to two different ones.
Member Data Documentation
template<typename ContextSampleType > bool ProcessContextNonReplacing< ContextSampleType >::isBypassed = false
If set to true, then a processor's process() method is expected to do whatever is appropriate for it to be in a bypassed state.
struct ProcessorDuplicator
template<typename MonoProcessorType, typename StateType>
struct ProcessorDuplicator< MonoProcessorType, StateType >
Converts a mono processor class into a multi-channel version by duplicating it and applying multichannel buffers across an array of instances.
When the prepare method is called, it uses the specified number of channels to instantiate the appropriate number of instances, which it then uses in its process() method.
Public Member Functions
ProcessorDuplicator ()
ProcessorDuplicator (StateType *stateToUse)
ProcessorDuplicator (const ProcessorDuplicator &)=default
ProcessorDuplicator (ProcessorDuplicator &&)=default
void prepare (const ProcessSpec &spec)
void reset () noexcept
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Public Attributes
StateType::Ptr state
Constructor & Destructor Documentation
template<typename MonoProcessorType , typename StateType > ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator ()
template<typename MonoProcessorType , typename StateType > ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (StateType * stateToUse)
template<typename MonoProcessorType , typename StateType > ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (const ProcessorDuplicator< MonoProcessorType, StateType > &) default
template<typename MonoProcessorType , typename StateType > ProcessorDuplicator< MonoProcessorType, StateType >::ProcessorDuplicator (ProcessorDuplicator< MonoProcessorType, StateType > &&) default
Member Function Documentation
template<typename MonoProcessorType , typename StateType > void ProcessorDuplicator< MonoProcessorType, StateType >::prepare (const ProcessSpec & spec)
References ProcessSpec::numChannels, and ProcessorDuplicator< MonoProcessorType, StateType >::state.
template<typename MonoProcessorType , typename StateType > void ProcessorDuplicator< MonoProcessorType, StateType >::reset () noexcept
template<typename MonoProcessorType , typename StateType > template<typename ProcessContext > void ProcessorDuplicator< MonoProcessorType, StateType >::process (const ProcessContext & context) noexcept
References jassert, and jmin().
Member Data Documentation
template<typename MonoProcessorType , typename StateType > StateType::Ptr ProcessorDuplicator< MonoProcessorType, StateType >::state
Referenced by ProcessorDuplicator< MonoProcessorType, StateType >::prepare().
struct ProcessorBase
Acts as a polymorphic base class for processors.
This exposes the same set of methods that a processor must implement as virtual methods, so that you can use the ProcessorWrapper class to wrap an instance of a subclass, and then pass that around using ProcessorBase as a base class.
See Also
ProcessorWrapper
Public Member Functions
ProcessorBase ()=default
virtual ~ProcessorBase ()=default
virtual void prepare (const ProcessSpec &)=0
virtual void process (const ProcessContextReplacing< float > &)=0
virtual void reset ()=0
Constructor & Destructor Documentation
ProcessorBase::ProcessorBase () default
virtual ProcessorBase::~ProcessorBase () virtual default
Member Function Documentation
virtual void ProcessorBase::prepare (const ProcessSpec &) pure virtual
Implemented in ProcessorWrapper< ProcessorType >.
virtual void ProcessorBase::process (const ProcessContextReplacing< float > &) pure virtual
Implemented in ProcessorWrapper< ProcessorType >.
virtual void ProcessorBase::reset () pure virtual
Implemented in ProcessorWrapper< ProcessorType >.
struct ProcessorWrapper
template<typename ProcessorType>
struct ProcessorWrapper< ProcessorType >
Wraps an instance of a given processor class, and exposes it through the ProcessorBase interface.
See Also
ProcessorBase
Public Member Functions
void prepare (const ProcessSpec &spec) override
void process (const ProcessContextReplacing< float > &context) override
void reset () override
Public Member Functions inherited from ProcessorBase
ProcessorBase ()=default
virtual ~ProcessorBase ()=default
Public Attributes
ProcessorType processor
Member Function Documentation
template<typename ProcessorType > void ProcessorWrapper< ProcessorType >::prepare (const ProcessSpec & spec) override virtual
Implements ProcessorBase.
References ProcessorWrapper< ProcessorType >::processor.
template<typename ProcessorType > void ProcessorWrapper< ProcessorType >::process (const ProcessContextReplacing< float > & context) override virtual
Implements ProcessorBase.
References ProcessorWrapper< ProcessorType >::processor.
template<typename ProcessorType > void ProcessorWrapper< ProcessorType >::reset () override virtual
Implements ProcessorBase.
References ProcessorWrapper< ProcessorType >::processor.
Member Data Documentation
template<typename ProcessorType > ProcessorType ProcessorWrapper< ProcessorType >::processor
Referenced by ProcessorWrapper< ProcessorType >::prepare(), ProcessorWrapper< ProcessorType >::process(), and ProcessorWrapper< ProcessorType >::reset().
struct StateVariableFilter::Parameters
template<typename NumericType>
struct StateVariableFilter::Parameters< NumericType >
Public Types
enum Type { Type::lowPass, Type::bandPass, Type::highPass }
using Ptr = ReferenceCountedObjectPtr< Parameters >
The Coefficients structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Public Types inherited from ProcessorState
using Ptr = ReferenceCountedObjectPtr< ProcessorState >
The ProcessorState structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Public Member Functions
void setCutOffFrequency (double sampleRate, NumericType frequency, NumericType resonance=static_cast< NumericType >(1.0/std::sqrt(2.0))) noexcept
Sets the cutoff frequency and resonance of the IIR filter.
Parameters ()=default
Parameters (const Parameters &o)
Parameters & operator= (const Parameters &o) noexcept
Public Member Functions inherited from ReferenceCountedObject
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Public Attributes
Type type = Type::lowPass
The type of the IIR filter.
NumericType g = static_cast<NumericType> (std::tan (double_Pi * 200.0 / 44100.0))
NumericType R2 = static_cast<NumericType> (std::sqrt (2.0))
NumericType h = static_cast<NumericType> (1.0 / (1.0 + R2 * g + g * g))
Additional Inherited Members
Protected Member Functions inherited from ReferenceCountedObject
ReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () noexcept
Resets the reference count to zero without deleting the object.
Member Typedef Documentation
template<typename NumericType> using StateVariableFilter::Parameters< NumericType >::Ptr = ReferenceCountedObjectPtr<Parameters>
The Coefficients structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Member Enumeration Documentation
template<typename NumericType> enum StateVariableFilter::Parameters::Type strong
Enumerator
lowPass
bandPass
highPass
Constructor & Destructor Documentation
template<typename NumericType> StateVariableFilter::Parameters< NumericType >::Parameters () default
template<typename NumericType> StateVariableFilter::Parameters< NumericType >::Parameters (const Parameters< NumericType > & o)
Member Function Documentation
template<typename NumericType> void StateVariableFilter::Parameters< NumericType >::setCutOffFrequency (double sampleRate, NumericType frequency, NumericType resonance = static_cast<NumericType> (1.0 / std::sqrt (2.0))) noexcept
Sets the cutoff frequency and resonance of the IIR filter.
Note : the bandwidth of the resonance increases with the value of the parameter. To have a standard 12 dB/octave filter, the value must be set at 1 / sqrt(2).
References double_Pi, StateVariableFilter::Parameters< NumericType >::g, StateVariableFilter::Parameters< NumericType >::h, and StateVariableFilter::Parameters< NumericType >::R2.
template<typename NumericType> Parameters& StateVariableFilter::Parameters< NumericType >::operator= (const Parameters< NumericType > & o) noexcept
References StateVariableFilter::Parameters< NumericType >::g, StateVariableFilter::Parameters< NumericType >::h, and StateVariableFilter::Parameters< NumericType >::R2.
Member Data Documentation
template<typename NumericType> Type StateVariableFilter::Parameters< NumericType >::type = Type::lowPass
The type of the IIR filter.
template<typename NumericType> NumericType StateVariableFilter::Parameters< NumericType >::g = static_cast<NumericType> (std::tan (double_Pi * 200.0 / 44100.0))
Referenced by StateVariableFilter::Parameters< NumericType >::operator=(), and StateVariableFilter::Parameters< NumericType >::setCutOffFrequency().
template<typename NumericType> NumericType StateVariableFilter::Parameters< NumericType >::R2 = static_cast<NumericType> (std::sqrt (2.0))
Referenced by StateVariableFilter::Parameters< NumericType >::operator=(), and StateVariableFilter::Parameters< NumericType >::setCutOffFrequency().
template<typename NumericType> NumericType StateVariableFilter::Parameters< NumericType >::h = static_cast<NumericType> (1.0 / (1.0 + R2 * g + g * g))
Referenced by StateVariableFilter::Parameters< NumericType >::operator=(), and StateVariableFilter::Parameters< NumericType >::setCutOffFrequency().
struct WaveShaper
template<typename FloatType, typename Function = FloatType (*) (FloatType)>
struct WaveShaper< FloatType, Function >
Applies waveshaping to audio samples as single samples or AudioBlocks.
Public Member Functions
void prepare (const ProcessSpec &) noexcept
Called before processing starts.
template<typename SampleType >
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) const noexcept
Processes the input and output buffers supplied in the processing context.
void reset () noexcept
Public Attributes
Function functionToUse
Member Function Documentation
template<typename FloatType , typename Function = FloatType (*) (FloatType)> void WaveShaper< FloatType, Function >::prepare (const ProcessSpec &) noexcept
Called before processing starts.
template<typename FloatType , typename Function = FloatType (*) (FloatType)> template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE WaveShaper< FloatType, Function >::processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
References WaveShaper< FloatType, Function >::functionToUse.
template<typename FloatType , typename Function = FloatType (*) (FloatType)> template<typename ProcessContext > void WaveShaper< FloatType, Function >::process (const ProcessContext & context) const noexcept
Processes the input and output buffers supplied in the processing context.
References WaveShaper< FloatType, Function >::functionToUse, jassert, and AudioBlock< SampleType >::process().
template<typename FloatType , typename Function = FloatType (*) (FloatType)> void WaveShaper< FloatType, Function >::reset () noexcept
Member Data Documentation
template<typename FloatType , typename Function = FloatType (*) (FloatType)> Function WaveShaper< FloatType, Function >::functionToUse
Referenced by WaveShaper< FloatType, Function >::process(), and WaveShaper< FloatType, Function >::processSample().
Typedef Documentation
template<typename... Processors> using ProcessorChain = ProcessorHelpers::Chain<Processors...>
This variadically-templated class lets you join together any number of processor classes into a single processor which will call process() on them all in sequence.