JUCE: Unity
Unity
juce_audio_plugin_client
Classes
struct UnityAudioSpatializerData
struct UnityAudioAmbisonicData
struct UnityAudioEffectState
struct UnityAudioParameterDefinition
struct UnityAudioEffectDefinition
Macros
#define UNITY_AUDIO_PLUGIN_API_VERSION 0x010401
#define UNITY_INTERFACE_API
#define UNITY_INTERFACE_EXPORT __attribute__ ((visibility("default")))
Typedefs
typedef float * inBuffer
typedef float float * outBuffer
typedef float float unsigned int bufferSize
typedef float float unsigned
int int numInChannels
typedef float float unsigned
int int int numOutChannels
typedef unsigned int pos
typedef int index
typedef int float value
typedef int float char * valuestr
typedef const char * name
typedef const char float * buffer
typedef const char float int numsamples
typedef float distanceIn
typedef float float attenuationIn
typedef float float float * attenuationOut
Enumerations
enum UnityAudioEffectDefinitionFlags { isSideChainTarget = 1, isSpatializer = 2, isAmbisonicDecoder = 4, appliesDistanceAttenuation = 8 }
enum UnityAudioEffectStateFlags { stateIsPlaying = 1, stateIsPaused = 2, stateIsMuted = 8, statIsSideChainTarget = 16 }
enum UnityEventModifiers {
shift = 1, control = 2, alt = 4, command = 8,
numeric = 16, capsLock = 32, functionKey = 64
}
Functions
typedef int (UNITY_INTERFACE_API *createCallback)(UnityAudioEffectState *state)
typedef void (UNITY_INTERFACE_API *renderCallback)(int eventId)
UNITY_INTERFACE_EXPORT int
UNITY_INTERFACE_API UnityGetAudioEffectDefinitions (UnityAudioEffectDefinition ***definitionsPtr)
UNITY_INTERFACE_EXPORT
renderCallback
UNITY_INTERFACE_API getRenderCallback ()
UNITY_INTERFACE_EXPORT void
UNITY_INTERFACE_API unityInitialiseTexture (int id, void *textureHandle, int w, int h)
UNITY_INTERFACE_EXPORT void
UNITY_INTERFACE_API unityMouseDown (int id, float x, float y, UnityEventModifiers mods, int button)
UNITY_INTERFACE_EXPORT void
UNITY_INTERFACE_API unityMouseDrag (int id, float x, float y, UnityEventModifiers mods, int button)
UNITY_INTERFACE_EXPORT void
UNITY_INTERFACE_API unityMouseUp (int id, float x, float y, UnityEventModifiers mods)
UNITY_INTERFACE_EXPORT void
UNITY_INTERFACE_API unityKeyEvent (int id, int code, UnityEventModifiers mods, const char *name)
UNITY_INTERFACE_EXPORT void
UNITY_INTERFACE_API unitySetScreenBounds (int id, float x, float y, float w, float h)
Detailed Description
Macro Definition Documentation
#define UNITY_AUDIO_PLUGIN_API_VERSION 0x010401
#define UNITY_INTERFACE_API
#define UNITY_INTERFACE_EXPORT __attribute__ ((visibility("default")))
Typedef Documentation
typedef float* inBuffer
typedef float float* outBuffer
typedef float float unsigned int bufferSize
typedef float float unsigned int int numInChannels
typedef float float unsigned int int int numOutChannels
typedef unsigned int pos
typedef int index
typedef int float * value
typedef int float char* valuestr
typedef const char* name
typedef const char float* buffer
typedef const char float int numsamples
typedef float distanceIn
typedef float float attenuationIn
typedef float float float* attenuationOut
Enumeration Type Documentation
enum UnityAudioEffectDefinitionFlags
Enumerator
isSideChainTarget
isSpatializer
isAmbisonicDecoder
appliesDistanceAttenuation
enum UnityAudioEffectStateFlags
Enumerator
stateIsPlaying
stateIsPaused
stateIsMuted
statIsSideChainTarget
enum UnityEventModifiers
Enumerator
shift
control
alt
command
numeric
capsLock
functionKey
Function Documentation
typedef int (UNITY_INTERFACE_API * createCallback)
Referenced by String::appendCharPointer(), StandalonePluginHolder::askUserToLoadState(), PixelAlpha::blend(), CharPointer_ASCII::canRepresent(), AudioFormatReader::clearSamplesBeyondAvailableLength(), PixelARGB::desaturate(), CharacterFunctions::find(), AudioParameterInt::getRange(), BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp(), BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage(), BlocksProtocol::HostPacketDecoder< Handler >::handlePacketACK(), BlocksProtocol::HostPacketDecoder< Handler >::handleTopology(), BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity(), CharacterFunctions::indexOf(), CharacterFunctions::indexOfIgnoreCase(), CharPointer_UTF32::isValidString(), CharPointer_UTF16::isValidString(), dsp::Reverb::process(), BlocksProtocol::HostPacketDecoder< Handler >::processNextPacket(), CharacterFunctions::readDoubleValue(), StandalonePluginHolder::reloadPluginState(), Array< Button::Listener * >::remove(), Reverb::setSampleRate(), String::toDecimalStringWithSignificantFigures(), and BlocksProtocol::Packed7BitArrayBuilder< maxPacketBytes >::writeHeaderSysexBytes().
typedef void (UNITY_INTERFACE_API * renderCallback)
UNITY_INTERFACE_EXPORT int UNITY_INTERFACE_API UnityGetAudioEffectDefinitions (UnityAudioEffectDefinition *** definitionsPtr)
UNITY_INTERFACE_EXPORT renderCallback UNITY_INTERFACE_API getRenderCallback ()
UNITY_INTERFACE_EXPORT void UNITY_INTERFACE_API unityInitialiseTexture (int id, void * textureHandle, int w, int h)
UNITY_INTERFACE_EXPORT void UNITY_INTERFACE_API unityMouseDown (int id, float x, float y, UnityEventModifiers mods, int button)
UNITY_INTERFACE_EXPORT void UNITY_INTERFACE_API unityMouseDrag (int id, float x, float y, UnityEventModifiers mods, int button)
UNITY_INTERFACE_EXPORT void UNITY_INTERFACE_API unityMouseUp (int id, float x, float y, UnityEventModifiers mods)
UNITY_INTERFACE_EXPORT void UNITY_INTERFACE_API unityKeyEvent (int id, int code, UnityEventModifiers mods, const char * name)
UNITY_INTERFACE_EXPORT void UNITY_INTERFACE_API unitySetScreenBounds (int id, float x, float y, float w, float h)