JUCE: maths
maths
juce_core
Namespaces
TypeHelpers
This namespace contains a few template classes for helping work out class type variations.
Classes
class BigInteger
An arbitrarily large integer class.
class Expression
A class for dynamically evaluating simple numeric expressions.
struct MathConstants< FloatType >
Commonly used mathematical constants.
struct TypeHelpers::ParameterType< Type >
The ParameterType struct is used to find the best type to use when passing some kind of object as a parameter.
struct TypeHelpers::SmallestFloatType< Type >
These templates are designed to take a type, and if it's a double, they return a double type; for anything else, they return a float type.
struct TypeHelpers::SmallestFloatType< double >
struct TypeHelpers::UnsignedTypeWithSize< bytes >
These templates are designed to take an integer type, and return an unsigned int version with the same size.
struct TypeHelpers::UnsignedTypeWithSize< 1 >
struct TypeHelpers::UnsignedTypeWithSize< 2 >
struct TypeHelpers::UnsignedTypeWithSize< 4 >
struct TypeHelpers::UnsignedTypeWithSize< 8 >
class NormalisableRange< ValueType >
Represents a mapping between an arbitrary range of values and a normalised 0->1 range.
class Random
A random number generator.
class Range< ValueType >
A general-purpose range object, that simply represents any linear range with a start and end point.
class StatisticsAccumulator< FloatType >
A class that measures various statistics about a series of floating point values that it is given.
Macros
#define JUCE_UNDENORMALISE(x) { (x) += 0.1f; (x) -= 0.1f; }
This macro can be applied to a float variable to check whether it contains a denormalised value, and to normalise it if necessary.
Typedefs
typedef signed char int8
A platform-independent 8-bit signed integer type.
typedef unsigned char uint8
A platform-independent 8-bit unsigned integer type.
typedef signed short int16
A platform-independent 16-bit signed integer type.
typedef unsigned short uint16
A platform-independent 16-bit unsigned integer type.
typedef signed int int32
A platform-independent 32-bit signed integer type.
typedef unsigned int uint32
A platform-independent 32-bit unsigned integer type.
typedef long long int64
A platform-independent 64-bit integer type.
typedef unsigned long long uint64
A platform-independent 64-bit unsigned integer type.
typedef int pointer_sized_int
A signed integer type that's guaranteed to be large enough to hold a pointer without truncating it.
typedef unsigned int pointer_sized_uint
An unsigned integer type that's guaranteed to be large enough to hold a pointer without truncating it.
Functions
OutputStream &JUCE_CALLTYPE operator<< (OutputStream &stream, const BigInteger &value)
Writes a BigInteger to an OutputStream as a UTF8 decimal string.
template<typename Type >
Type jmax (const Type a, const Type b)
Returns the larger of two values.
template<typename Type >
Type jmax (const Type a, const Type b, const Type c)
Returns the larger of three values.
template<typename Type >
Type jmax (const Type a, const Type b, const Type c, const Type d)
Returns the larger of four values.
template<typename Type >
Type jmin (const Type a, const Type b)
Returns the smaller of two values.
template<typename Type >
Type jmin (const Type a, const Type b, const Type c)
Returns the smaller of three values.
template<typename Type >
Type jmin (const Type a, const Type b, const Type c, const Type d)
Returns the smaller of four values.
template<typename Type >
Type jmap (Type value0To1, Type targetRangeMin, Type targetRangeMax)
Remaps a normalised value (between 0 and 1) to a target range.
template<typename Type >
Type jmap (Type sourceValue, Type sourceRangeMin, Type sourceRangeMax, Type targetRangeMin, Type targetRangeMax)
Remaps a value from a source range to a target range.
template<typename Type >
Type findMinimum (const Type *data, int numValues)
Scans an array of values, returning the minimum value that it contains.
template<typename Type >
Type findMaximum (const Type *values, int numValues)
Scans an array of values, returning the maximum value that it contains.
template<typename Type >
void findMinAndMax (const Type *values, int numValues, Type &lowest, Type &highest)
Scans an array of values, returning the minimum and maximum values that it contains.
template<typename Type >
Type jlimit (const Type lowerLimit, const Type upperLimit, const Type valueToConstrain) noexcept
Constrains a value to keep it within a given range.
template<typename Type >
bool isPositiveAndBelow (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also below a specified upper limit.
template<>
bool isPositiveAndBelow (const int valueToTest, const int upperLimit) noexcept
template<typename Type >
bool isPositiveAndNotGreaterThan (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit.
template<>
bool isPositiveAndNotGreaterThan (const int valueToTest, const int upperLimit) noexcept
template<typename Type >
void swapVariables (Type &variable1, Type &variable2)
Handy function to swap two values.
template<typename Type1 >
void ignoreUnused (const Type1 &) noexcept
Handy function for avoiding unused variables warning.
template<typename Type1 , typename Type2 >
void ignoreUnused (const Type1 &, const Type2 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 >
void ignoreUnused (const Type1 &, const Type2 &, const Type3 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 , typename Type4 >
void ignoreUnused (const Type1 &, const Type2 &, const Type3 &, const Type4 &) noexcept
template<typename Type , int N>
int numElementsInArray (Type(&array)[N])
Handy function for getting the number of elements in a simple const C array.
template<typename Type >
Type juce_hypot (Type a, Type b) noexcept
Using juce_hypot is easier than dealing with the different types of hypot function that are provided by the various platforms and compilers.
int64 abs64 (const int64 n) noexcept
64-bit abs function.
float degreesToRadians (float degrees) noexcept
Converts an angle in degrees to radians.
double degreesToRadians (double degrees) noexcept
Converts an angle in degrees to radians.
float radiansToDegrees (float radians) noexcept
Converts an angle in radians to degrees.
double radiansToDegrees (double radians) noexcept
Converts an angle in radians to degrees.
template<typename NumericType >
bool juce_isfinite (NumericType) noexcept
The isfinite() method seems to vary between platforms, so this is a platform-independent function for it.
template<>
bool juce_isfinite (float value) noexcept
template<>
bool juce_isfinite (double value) noexcept
template<typename FloatType >
int roundToInt (const FloatType value) noexcept
Fast floating-point-to-integer conversion.
int roundToInt (int value) noexcept
int roundToIntAccurate (double value) noexcept
Fast floating-point-to-integer conversion.
int roundDoubleToInt (double value) noexcept
Fast floating-point-to-integer conversion.
int roundFloatToInt (float value) noexcept
Fast floating-point-to-integer conversion.
template<typename FloatType >
unsigned int truncatePositiveToUnsignedInt (FloatType value) noexcept
Truncates a positive floating-point number to an unsigned int.
template<typename IntegerType >
bool isPowerOfTwo (IntegerType value)
Returns true if the specified integer is a power-of-two.
int nextPowerOfTwo (int n) noexcept
Returns the smallest power-of-two which is equal to or greater than the given integer.
int findHighestSetBit (uint32 n) noexcept
Returns the index of the highest set bit in a (non-zero) number.
int countNumberOfBits (uint32 n) noexcept
Returns the number of bits in a 32-bit integer.
int countNumberOfBits (uint64 n) noexcept
Returns the number of bits in a 64-bit integer.
template<typename IntegerType >
IntegerType negativeAwareModulo (IntegerType dividend, const IntegerType divisor) noexcept
Performs a modulo operation, but can cope with the dividend being negative.
template<typename NumericType >
NumericType square (NumericType n) noexcept
Returns the square of its argument.
void writeLittleEndianBitsInBuffer (void *targetBuffer, uint32 startBit, uint32 numBits, uint32 value) noexcept
Writes a number of bits into a memory buffer at a given bit index.
uint32 readLittleEndianBitsInBuffer (const void *sourceBuffer, uint32 startBit, uint32 numBits) noexcept
Reads a number of bits from a buffer at a given bit index.
Variables
const double double_Pi = MathConstants<double>::pi
A predefined value for Pi, at double-precision.
const float float_Pi = MathConstants<float>::pi
A predefined value for Pi, at single-precision.
static const FloatType MathConstants< FloatType >::pi = static_cast<FloatType> (3.141592653589793238L)
A predefined value for Pi.
static const FloatType MathConstants< FloatType >::euler = static_cast<FloatType> (2.71828182845904523536L)
A predfined value for Euler's number.
Detailed Description
Class Documentation
class BigInteger
An arbitrarily large integer class.
A BigInteger can be used in a similar way to a normal integer, but has no size limit (except for memory and performance constraints).
Negative values are possible, but the value isn't stored as 2s-complement, so be careful if you use negative values and look at the values of individual bits.
Public Member Functions
BigInteger ()
Creates an empty BigInteger.
BigInteger (uint32 value)
Creates a BigInteger containing an integer value in its low bits.
BigInteger (int32 value)
Creates a BigInteger containing an integer value in its low bits.
BigInteger (int64 value)
Creates a BigInteger containing an integer value in its low bits.
BigInteger (const BigInteger &)
Creates a copy of another BigInteger.
BigInteger (BigInteger &&) noexcept
Move constructor.
BigInteger & operator= (BigInteger &&) noexcept
Move assignment operator.
~BigInteger ()
Destructor.
BigInteger & operator= (const BigInteger &)
Copies another BigInteger onto this one.
void swapWith (BigInteger &) noexcept
Swaps the internal contents of this with another object.
bool operator[] (int bit) const noexcept
Returns the value of a specified bit in the number.
bool isZero () const noexcept
Returns true if no bits are set.
bool isOne () const noexcept
Returns true if the value is 1.
int toInteger () const noexcept
Attempts to get the lowest 32 bits of the value as an integer.
int64 toInt64 () const noexcept
Attempts to get the lowest 64 bits of the value as an integer.
void clear () noexcept
Resets the value to 0.
void clearBit (int bitNumber) noexcept
Clears a particular bit in the number.
void setBit (int bitNumber)
Sets a specified bit to 1.
void setBit (int bitNumber, bool shouldBeSet)
Sets or clears a specified bit.
void setRange (int startBit, int numBits, bool shouldBeSet)
Sets a range of bits to be either on or off.
void insertBit (int bitNumber, bool shouldBeSet)
Inserts a bit an a given position, shifting up any bits above it.
BigInteger getBitRange (int startBit, int numBits) const
Returns a range of bits as a new BigInteger.
uint32 getBitRangeAsInt (int startBit, int numBits) const noexcept
Returns a range of bits as an integer value.
void setBitRangeAsInt (int startBit, int numBits, uint32 valueToSet)
Sets a range of bits to an integer value.
void shiftBits (int howManyBitsLeft, int startBit)
Shifts a section of bits left or right.
int countNumberOfSetBits () const noexcept
Returns the total number of set bits in the value.
int findNextSetBit (int startIndex) const noexcept
Looks for the index of the next set bit after a given starting point.
int findNextClearBit (int startIndex) const noexcept
Looks for the index of the next clear bit after a given starting point.
int getHighestBit () const noexcept
Returns the index of the highest set bit in the number.
bool isNegative () const noexcept
Returns true if the value is less than zero.
void setNegative (bool shouldBeNegative) noexcept
Changes the sign of the number to be positive or negative.
void negate () noexcept
Inverts the sign of the number.
BigInteger & operator+= (const BigInteger &)
BigInteger & operator-= (const BigInteger &)
BigInteger & operator*= (const BigInteger &)
BigInteger & operator/= (const BigInteger &)
BigInteger & operator|= (const BigInteger &)
BigInteger & operator&= (const BigInteger &)
BigInteger & operator^= (const BigInteger &)
BigInteger & operator%= (const BigInteger &)
BigInteger & operator<<= (int numBitsToShift)
BigInteger & operator>>= (int numBitsToShift)
BigInteger & operator++ ()
BigInteger & operator-- ()
BigInteger operator++ (int)
BigInteger operator-- (int)
BigInteger operator- () const
BigInteger operator+ (const BigInteger &) const
BigInteger operator- (const BigInteger &) const
BigInteger operator* (const BigInteger &) const
BigInteger operator/ (const BigInteger &) const
BigInteger operator| (const BigInteger &) const
BigInteger operator& (const BigInteger &) const
BigInteger operator^ (const BigInteger &) const
BigInteger operator% (const BigInteger &) const
BigInteger operator<< (int numBitsToShift) const
BigInteger operator>> (int numBitsToShift) const
bool operator== (const BigInteger &) const noexcept
bool operator!= (const BigInteger &) const noexcept
bool operator< (const BigInteger &) const noexcept
bool operator<= (const BigInteger &) const noexcept
bool operator> (const BigInteger &) const noexcept
bool operator>= (const BigInteger &) const noexcept
int compare (const BigInteger &other) const noexcept
Does a signed comparison of two BigIntegers.
int compareAbsolute (const BigInteger &other) const noexcept
Compares the magnitudes of two BigIntegers, ignoring their signs.
void divideBy (const BigInteger &divisor, BigInteger &remainder)
Divides this value by another one and returns the remainder.
BigInteger findGreatestCommonDivisor (BigInteger other) const
Returns the largest value that will divide both this value and the argument.
void exponentModulo (const BigInteger &exponent, const BigInteger &modulus)
Performs a combined exponent and modulo operation.
void inverseModulo (const BigInteger &modulus)
Performs an inverse modulo on the value.
void montgomeryMultiplication (const BigInteger &other, const BigInteger &modulus, const BigInteger &modulusp, int k)
Performs the Montgomery Multiplication with modulo.
void extendedEuclidean (const BigInteger &a, const BigInteger &b, BigInteger &xOut, BigInteger &yOut)
Performs the Extended Euclidean algorithm.
String toString (int base, int minimumNumCharacters=1) const
Converts the number to a string.
void parseString (StringRef text, int base)
Reads the numeric value from a string.
MemoryBlock toMemoryBlock () const
Turns the number into a block of binary data.
void loadFromMemoryBlock (const MemoryBlock &data)
Converts a block of raw data into a number.
Constructor & Destructor Documentation
BigInteger::BigInteger ()
Creates an empty BigInteger.
BigInteger::BigInteger (uint32 value)
Creates a BigInteger containing an integer value in its low bits.
The low 32 bits of the number are initialised with this value.
BigInteger::BigInteger (int32 value)
Creates a BigInteger containing an integer value in its low bits.
The low 32 bits of the number are initialised with the absolute value passed in, and its sign is set to reflect the sign of the number.
BigInteger::BigInteger (int64 value)
Creates a BigInteger containing an integer value in its low bits.
The low 64 bits of the number are initialised with the absolute value passed in, and its sign is set to reflect the sign of the number.
BigInteger::BigInteger (const BigInteger &)
Creates a copy of another BigInteger.
BigInteger::BigInteger (BigInteger &&) noexcept
Move constructor.
BigInteger::~BigInteger ()
Destructor.
Member Function Documentation
BigInteger& BigInteger::operator= (BigInteger &&) noexcept
Move assignment operator.
BigInteger& BigInteger::operator= (const BigInteger &)
Copies another BigInteger onto this one.
void BigInteger::swapWith (BigInteger &) noexcept
Swaps the internal contents of this with another object.
bool BigInteger::operator[] (int bit) const noexcept
Returns the value of a specified bit in the number.
If the index is out-of-range, the result will be false.
bool BigInteger::isZero () const noexcept
Returns true if no bits are set.
bool BigInteger::isOne () const noexcept
Returns true if the value is 1.
int BigInteger::toInteger () const noexcept
Attempts to get the lowest 32 bits of the value as an integer.
If the value is bigger than the integer limits, this will return only the lower bits.
int64 BigInteger::toInt64 () const noexcept
Attempts to get the lowest 64 bits of the value as an integer.
If the value is bigger than the integer limits, this will return only the lower bits.
void BigInteger::clear () noexcept
Resets the value to 0.
void BigInteger::clearBit (int bitNumber) noexcept
Clears a particular bit in the number.
void BigInteger::setBit (int bitNumber)
Sets a specified bit to 1.
void BigInteger::setBit (int bitNumber, bool shouldBeSet)
Sets or clears a specified bit.
void BigInteger::setRange (int startBit, int numBits, bool shouldBeSet)
Sets a range of bits to be either on or off.
Parameters
startBit the first bit to change
numBits the number of bits to change
shouldBeSet whether to turn these bits on or off
void BigInteger::insertBit (int bitNumber, bool shouldBeSet)
Inserts a bit an a given position, shifting up any bits above it.
BigInteger BigInteger::getBitRange (int startBit, int numBits) const
Returns a range of bits as a new BigInteger.
e.g. getBitRangeAsInt (0, 64) would return the lowest 64 bits.
See Also
getBitRangeAsInt
uint32 BigInteger::getBitRangeAsInt (int startBit, int numBits) const noexcept
Returns a range of bits as an integer value.
e.g. getBitRangeAsInt (0, 32) would return the lowest 32 bits.
Asking for more than 32 bits isn't allowed (obviously) - for that, use getBitRange().
void BigInteger::setBitRangeAsInt (int startBit, int numBits, uint32 valueToSet)
Sets a range of bits to an integer value.
Copies the given integer onto a range of bits, starting at startBit, and using up to numBits of the available bits.
void BigInteger::shiftBits (int howManyBitsLeft, int startBit)
Shifts a section of bits left or right.
Parameters
howManyBitsLeft how far to move the bits (+ve numbers shift it left, -ve numbers shift it right).
startBit the first bit to affect - if this is > 0, only bits above that index will be affected.
int BigInteger::countNumberOfSetBits () const noexcept
Returns the total number of set bits in the value.
int BigInteger::findNextSetBit (int startIndex) const noexcept
Looks for the index of the next set bit after a given starting point.
This searches from startIndex (inclusive) upwards for the first set bit, and returns its index. If no set bits are found, it returns -1.
int BigInteger::findNextClearBit (int startIndex) const noexcept
Looks for the index of the next clear bit after a given starting point.
This searches from startIndex (inclusive) upwards for the first clear bit, and returns its index.
int BigInteger::getHighestBit () const noexcept
Returns the index of the highest set bit in the number.
If the value is zero, this will return -1.
bool BigInteger::isNegative () const noexcept
Returns true if the value is less than zero.
See Also
setNegative, negate
void BigInteger::setNegative (bool shouldBeNegative) noexcept
Changes the sign of the number to be positive or negative.
See Also
isNegative, negate
void BigInteger::negate () noexcept
Inverts the sign of the number.
See Also
isNegative, setNegative
BigInteger& BigInteger::operator+= (const BigInteger &)
BigInteger& BigInteger::operator-= (const BigInteger &)
BigInteger& BigInteger::operator*= (const BigInteger &)
BigInteger& BigInteger::operator/= (const BigInteger &)
BigInteger& BigInteger::operator|= (const BigInteger &)
BigInteger& BigInteger::operator&= (const BigInteger &)
BigInteger& BigInteger::operator^= (const BigInteger &)
BigInteger& BigInteger::operator%= (const BigInteger &)
BigInteger& BigInteger::operator<<= (int numBitsToShift)
BigInteger& BigInteger::operator>>= (int numBitsToShift)
BigInteger& BigInteger::operator++ ()
BigInteger& BigInteger::operator-- ()
BigInteger BigInteger::operator++ (int)
BigInteger BigInteger::operator-- (int)
BigInteger BigInteger::operator- () const
BigInteger BigInteger::operator+ (const BigInteger &) const
BigInteger BigInteger::operator- (const BigInteger &) const
BigInteger BigInteger::operator* (const BigInteger &) const
BigInteger BigInteger::operator/ (const BigInteger &) const
BigInteger BigInteger::operator| (const BigInteger &) const
BigInteger BigInteger::operator& (const BigInteger &) const
BigInteger BigInteger::operator^ (const BigInteger &) const
BigInteger BigInteger::operator% (const BigInteger &) const
BigInteger BigInteger::operator<< (int numBitsToShift) const
BigInteger BigInteger::operator>> (int numBitsToShift) const
bool BigInteger::operator== (const BigInteger &) const noexcept
bool BigInteger::operator!= (const BigInteger &) const noexcept
bool BigInteger::operator< (const BigInteger &) const noexcept
bool BigInteger::operator<= (const BigInteger &) const noexcept
bool BigInteger::operator> (const BigInteger &) const noexcept
bool BigInteger::operator>= (const BigInteger &) const noexcept
int BigInteger::compare (const BigInteger & other) const noexcept
Does a signed comparison of two BigIntegers.
Return values are:
0 if the numbers are the same
< 0 if this number is smaller than the other
> 0 if this number is bigger than the other
int BigInteger::compareAbsolute (const BigInteger & other) const noexcept
Compares the magnitudes of two BigIntegers, ignoring their signs.
Return values are:
0 if the numbers are the same
< 0 if this number is smaller than the other
> 0 if this number is bigger than the other
void BigInteger::divideBy (const BigInteger & divisor, BigInteger & remainder)
Divides this value by another one and returns the remainder.
This number is divided by other, leaving the quotient in this number, with the remainder being copied to the other BigInteger passed in.
BigInteger BigInteger::findGreatestCommonDivisor (BigInteger other) const
Returns the largest value that will divide both this value and the argument.
void BigInteger::exponentModulo (const BigInteger & exponent, const BigInteger & modulus)
Performs a combined exponent and modulo operation.
This BigInteger's value becomes (this ^ exponent) % modulus.
void BigInteger::inverseModulo (const BigInteger & modulus)
Performs an inverse modulo on the value.
i.e. the result is (this ^ -1) mod (modulus).
void BigInteger::montgomeryMultiplication (const BigInteger & other, const BigInteger & modulus, const BigInteger & modulusp, int k)
Performs the Montgomery Multiplication with modulo.
This object is left containing the result value: ((this * other) * R1) % modulus. To get this result, we need modulus, modulusp and k such as R = 2^k, with modulus * modulusp - R * R1 = GCD(modulus, R) = 1
void BigInteger::extendedEuclidean (const BigInteger & a, const BigInteger & b, BigInteger & xOut, BigInteger & yOut)
Performs the Extended Euclidean algorithm.
This method will set the xOut and yOut arguments such that (a * xOut) - (b * yOut) = GCD (a, b). On return, this object is left containing the value of the GCD.
String BigInteger::toString (int base, int minimumNumCharacters = 1) const
Converts the number to a string.
Specify a base such as 2 (binary), 8 (octal), 10 (decimal), 16 (hex). If minimumNumCharacters is greater than 0, the returned string will be padded with leading zeros to reach at least that length.
void BigInteger::parseString (StringRef text, int base)
Reads the numeric value from a string.
Specify a base such as 2 (binary), 8 (octal), 10 (decimal), 16 (hex). Any invalid characters will be ignored.
MemoryBlock BigInteger::toMemoryBlock () const
Turns the number into a block of binary data.
The data is arranged as little-endian, so the first byte of data is the low 8 bits of the number, and so on.
See Also
loadFromMemoryBlock
void BigInteger::loadFromMemoryBlock (const MemoryBlock & data)
Converts a block of raw data into a number.
The data is arranged as little-endian, so the first byte of data is the low 8 bits of the number, and so on.
See Also
toMemoryBlock
class Expression
A class for dynamically evaluating simple numeric expressions.
This class can parse a simple C-style string expression involving floating point numbers, named symbols and functions. The basic arithmetic operations of +, -, *, / are supported, as well as parentheses, and any alphanumeric identifiers are assumed to be named symbols which will be resolved when the expression is evaluated.
Expressions which use identifiers and functions require a subclass of Expression::Scope to be supplied when evaluating them, and this object is expected to be able to resolve the symbol names and perform the functions that are used.
Public Types
enum Type { constantType, functionType, operatorType, symbolType }
Expression type.
Public Member Functions
Expression ()
Creates a simple expression with a value of 0.
~Expression ()
Destructor.
Expression (const Expression &)
Creates a copy of an expression.
Expression & operator= (const Expression &)
Copies another expression.
Expression (Expression &&) noexcept
Move constructor.
Expression & operator= (Expression &&) noexcept
Move assignment operator.
Expression (double constant)
Creates a simple expression with a specified constant value.
Expression (const String &stringToParse, String &parseError)
Attempts to create an expression by parsing a string.
String toString () const
Returns a string version of the expression.
Expression operator+ (const Expression &) const
Returns an expression which is an addition operation of two existing expressions.
Expression operator- (const Expression &) const
Returns an expression which is a subtraction operation of two existing expressions.
Expression operator* (const Expression &) const
Returns an expression which is a multiplication operation of two existing expressions.
Expression operator/ (const Expression &) const
Returns an expression which is a division operation of two existing expressions.
Expression operator- () const
Returns an expression which performs a negation operation on an existing expression.
double evaluate () const
Evaluates this expression, without using a Scope.
double evaluate (const Scope &scope) const
Evaluates this expression, providing a scope that should be able to evaluate any symbols or functions that it uses.
double evaluate (const Scope &scope, String &evaluationError) const
Evaluates this expression, providing a scope that should be able to evaluate any symbols or functions that it uses.
Expression adjustedToGiveNewResult (double targetValue, const Scope &scope) const
Attempts to return an expression which is a copy of this one, but with a constant adjusted to make the expression resolve to a target value.
Expression withRenamedSymbol (const Symbol &oldSymbol, const String &newName, const Scope &scope) const
Returns a copy of this expression in which all instances of a given symbol have been renamed.
bool referencesSymbol (const Symbol &symbol, const Scope &scope) const
Returns true if this expression makes use of the specified symbol.
bool usesAnySymbols () const
Returns true if this expression contains any symbols.
void findReferencedSymbols (Array< Symbol > &results, const Scope &scope) const
Returns a list of all symbols that may be needed to resolve this expression in the given scope.
Type getType () const noexcept
Returns the type of this expression.
String getSymbolOrFunction () const
If this expression is a symbol, function or operator, this returns its identifier.
int getNumInputs () const
Returns the number of inputs to this expression.
Expression getInput (int index) const
Retrieves one of the inputs to this expression.
Static Public Member Functions
static Expression symbol (const String &symbol)
Returns an Expression which is an identifier reference.
static Expression function (const String &functionName, const Array< Expression > &parameters)
Returns an Expression which is a function call.
static Expression parse (String::CharPointerType &stringToParse, String &parseError)
Returns an Expression which parses a string from a character pointer, and updates the pointer to indicate where it finished.
Member Enumeration Documentation
enum Expression::Type
Expression type.
See Also
Expression::getType()
Enumerator
constantType
functionType
operatorType
symbolType
Constructor & Destructor Documentation
Expression::Expression ()
Creates a simple expression with a value of 0.
Expression::~Expression ()
Destructor.
Expression::Expression (const Expression &)
Creates a copy of an expression.
Expression::Expression (Expression &&) noexcept
Move constructor.
Expression::Expression (double constant) explicit
Creates a simple expression with a specified constant value.
Expression::Expression (const String & stringToParse, String & parseError)
Attempts to create an expression by parsing a string.
Any errors are returned in the parseError argument provided.
Member Function Documentation
Expression& Expression::operator= (const Expression &)
Copies another expression.
Expression& Expression::operator= (Expression &&) noexcept
Move assignment operator.
String Expression::toString () const
Returns a string version of the expression.
Expression Expression::operator+ (const Expression &) const
Returns an expression which is an addition operation of two existing expressions.
Expression Expression::operator- (const Expression &) const
Returns an expression which is a subtraction operation of two existing expressions.
Expression Expression::operator* (const Expression &) const
Returns an expression which is a multiplication operation of two existing expressions.
Expression Expression::operator/ (const Expression &) const
Returns an expression which is a division operation of two existing expressions.
Expression Expression::operator- () const
Returns an expression which performs a negation operation on an existing expression.
static Expression Expression::symbol (const String & symbol) static
Returns an Expression which is an identifier reference.
static Expression Expression::function (const String & functionName, const Array< Expression > & parameters) static
Returns an Expression which is a function call.
static Expression Expression::parse (String::CharPointerType & stringToParse, String & parseError) static
Returns an Expression which parses a string from a character pointer, and updates the pointer to indicate where it finished.
The pointer is incremented so that on return, it indicates the character that follows the end of the expression that was parsed.
If there's a syntax error in parsing, the parseError argument will be set to a description of the problem.
double Expression::evaluate () const
Evaluates this expression, without using a Scope.
Without a Scope, no symbols can be used, and only basic functions such as sin, cos, tan, min, max are available. To find out about any errors during evaluation, use the other version of this method which takes a String parameter.
double Expression::evaluate (const Scope & scope) const
Evaluates this expression, providing a scope that should be able to evaluate any symbols or functions that it uses.
To find out about any errors during evaluation, use the other version of this method which takes a String parameter.
double Expression::evaluate (const Scope & scope, String & evaluationError) const
Evaluates this expression, providing a scope that should be able to evaluate any symbols or functions that it uses.
Expression Expression::adjustedToGiveNewResult (double targetValue, const Scope & scope) const
Attempts to return an expression which is a copy of this one, but with a constant adjusted to make the expression resolve to a target value.
E.g. if the expression is "x + 10" and x is 5, then asking for a target value of 8 will return the expression "x + 3". Obviously some expressions can't be reversed in this way, in which case they might just be adjusted by adding a constant to the original expression.
Exceptions
Expression::EvaluationError
Expression Expression::withRenamedSymbol (const Symbol & oldSymbol, const String & newName, const Scope & scope) const
Returns a copy of this expression in which all instances of a given symbol have been renamed.
bool Expression::referencesSymbol (const Symbol & symbol, const Scope & scope) const
Returns true if this expression makes use of the specified symbol.
If a suitable scope is supplied, the search will dereference and recursively check all symbols, so that it can be determined whether this expression relies on the given symbol at any level in its evaluation. If the scope parameter is null, this just checks whether the expression contains any direct references to the symbol.
Exceptions
Expression::EvaluationError
bool Expression::usesAnySymbols () const
Returns true if this expression contains any symbols.
void Expression::findReferencedSymbols (Array< Symbol > & results, const Scope & scope) const
Returns a list of all symbols that may be needed to resolve this expression in the given scope.
Type Expression::getType () const noexcept
Returns the type of this expression.
String Expression::getSymbolOrFunction () const
If this expression is a symbol, function or operator, this returns its identifier.
int Expression::getNumInputs () const
Returns the number of inputs to this expression.
See Also
getInput
Expression Expression::getInput (int index) const
Retrieves one of the inputs to this expression.
See Also
getNumInputs
struct MathConstants
template<typename FloatType>
struct MathConstants< FloatType >
Commonly used mathematical constants.
Static Public Attributes
static const FloatType pi = static_cast<FloatType> (3.141592653589793238L)
A predefined value for Pi.
static const FloatType euler = static_cast<FloatType> (2.71828182845904523536L)
A predfined value for Euler's number.
struct TypeHelpers::ParameterType
template<typename Type>
struct TypeHelpers::ParameterType< Type >
The ParameterType struct is used to find the best type to use when passing some kind of object as a parameter.
Of course, this is only likely to be useful in certain esoteric template situations.
E.g. "myFunction (typename TypeHelpers::ParameterType<int>::type, typename TypeHelpers::ParameterType<MyObject>::type)" would evaluate to "myfunction (int, const MyObject&)", keeping any primitive types as pass-by-value, but passing objects as a const reference, to avoid copying.
Public Types
typedef const Type & type
Member Typedef Documentation
template<typename Type> typedef const Type& TypeHelpers::ParameterType< Type >::type
struct TypeHelpers::SmallestFloatType
template<typename Type>
struct TypeHelpers::SmallestFloatType< Type >
These templates are designed to take a type, and if it's a double, they return a double type; for anything else, they return a float type.
Public Types
typedef float type
Member Typedef Documentation
template<typename Type> typedef float TypeHelpers::SmallestFloatType< Type >::type
struct TypeHelpers::SmallestFloatType< double >
template<>
struct TypeHelpers::SmallestFloatType< double >
Public Types
typedef double type
Member Typedef Documentation
typedef double TypeHelpers::SmallestFloatType< double >::type
struct TypeHelpers::UnsignedTypeWithSize
template<int bytes>
struct TypeHelpers::UnsignedTypeWithSize< bytes >
These templates are designed to take an integer type, and return an unsigned int version with the same size.
struct TypeHelpers::UnsignedTypeWithSize< 1 >
template<>
struct TypeHelpers::UnsignedTypeWithSize< 1 >
Public Types
typedef uint8 type
Member Typedef Documentation
typedef uint8 TypeHelpers::UnsignedTypeWithSize< 1 >::type
struct TypeHelpers::UnsignedTypeWithSize< 2 >
template<>
struct TypeHelpers::UnsignedTypeWithSize< 2 >
Public Types
typedef uint16 type
Member Typedef Documentation
typedef uint16 TypeHelpers::UnsignedTypeWithSize< 2 >::type
struct TypeHelpers::UnsignedTypeWithSize< 4 >
template<>
struct TypeHelpers::UnsignedTypeWithSize< 4 >
Public Types
typedef uint32 type
Member Typedef Documentation
typedef uint32 TypeHelpers::UnsignedTypeWithSize< 4 >::type
struct TypeHelpers::UnsignedTypeWithSize< 8 >
template<>
struct TypeHelpers::UnsignedTypeWithSize< 8 >
Public Types
typedef uint64 type
Member Typedef Documentation
typedef uint64 TypeHelpers::UnsignedTypeWithSize< 8 >::type
class NormalisableRange
template<typename ValueType>
class NormalisableRange< ValueType >
Represents a mapping between an arbitrary range of values and a normalised 0->1 range.
The properties of the mapping also include an optional snapping interval and skew-factor.
See Also
Range
Public Member Functions
NormalisableRange () noexcept
Creates a continuous range that performs a dummy mapping.
NormalisableRange (const NormalisableRange &other) noexcept
Creates a copy of another range.
NormalisableRange & operator= (const NormalisableRange &other) noexcept
Creates a copy of another range.
NormalisableRange (ValueType rangeStart, ValueType rangeEnd, ValueType intervalValue, ValueType skewFactor, bool useSymmetricSkew=false) noexcept
Creates a NormalisableRange with a given range, interval and skew factor.
NormalisableRange (ValueType rangeStart, ValueType rangeEnd, ValueType intervalValue) noexcept
Creates a NormalisableRange with a given range and interval, but a dummy skew-factor.
NormalisableRange (ValueType rangeStart, ValueType rangeEnd) noexcept
Creates a NormalisableRange with a given range, continuous interval, but a dummy skew-factor.
NormalisableRange (ValueType rangeStart, ValueType rangeEnd, std::function< ValueType(ValueType currentRangeStart, ValueType currentRangeEnd, ValueType normalisedValue)> convertFrom0To1Func, std::function< ValueType(ValueType currentRangeStart, ValueType currentRangeEnd, ValueType mappedValue)> convertTo0To1Func, std::function< ValueType(ValueType currentRangeStart, ValueType currentRangeEnd, ValueType valueToSnap)> snapToLegalValueFunc=nullptr) noexcept
Creates a NormalisableRange with a given range and an injective mapping function.
ValueType convertTo0to1 (ValueType v) const noexcept
Uses the properties of this mapping to convert a non-normalised value to its 0->1 representation.
ValueType convertFrom0to1 (ValueType proportion) const noexcept
Uses the properties of this mapping to convert a normalised 0->1 value to its full-range representation.
ValueType snapToLegalValue (ValueType v) const noexcept
Takes a non-normalised value and snaps it based on either the interval property of this NormalisedRange or the lambda function supplied to the constructor.
Range< ValueType > getRange () const noexcept
Returns the extent of the normalisable range.
void setSkewForCentre (ValueType centrePointValue) noexcept
Given a value which is between the start and end points, this sets the skew such that convertFrom0to1 (0.5) will return this value.
Public Attributes
ValueType start
The minimum value of the non-normalised range.
ValueType end
The maximum value of the non-normalised range.
ValueType interval
The snapping interval that should be used (for a non-normalised value).
ValueType skew
An optional skew factor that alters the way values are distribute across the range.
bool symmetricSkew
If true, the skew factor applies from the middle of the slider to each of its ends.
Constructor & Destructor Documentation
template<typename ValueType> NormalisableRange< ValueType >::NormalisableRange () noexcept
Creates a continuous range that performs a dummy mapping.
template<typename ValueType> NormalisableRange< ValueType >::NormalisableRange (const NormalisableRange< ValueType > & other) noexcept
Creates a copy of another range.
template<typename ValueType> NormalisableRange< ValueType >::NormalisableRange (ValueType rangeStart, ValueType rangeEnd, ValueType intervalValue, ValueType skewFactor, bool useSymmetricSkew = false) noexcept
Creates a NormalisableRange with a given range, interval and skew factor.
template<typename ValueType> NormalisableRange< ValueType >::NormalisableRange (ValueType rangeStart, ValueType rangeEnd, ValueType intervalValue) noexcept
Creates a NormalisableRange with a given range and interval, but a dummy skew-factor.
template<typename ValueType> NormalisableRange< ValueType >::NormalisableRange (ValueType rangeStart, ValueType rangeEnd) noexcept
Creates a NormalisableRange with a given range, continuous interval, but a dummy skew-factor.
template<typename ValueType> NormalisableRange< ValueType >::NormalisableRange (ValueType rangeStart, ValueType rangeEnd, std::function< ValueType(ValueType currentRangeStart, ValueType currentRangeEnd, ValueType normalisedValue)> convertFrom0To1Func, std::function< ValueType(ValueType currentRangeStart, ValueType currentRangeEnd, ValueType mappedValue)> convertTo0To1Func, std::function< ValueType(ValueType currentRangeStart, ValueType currentRangeEnd, ValueType valueToSnap)> snapToLegalValueFunc = nullptr) noexcept
Creates a NormalisableRange with a given range and an injective mapping function.
Parameters
rangeStart The minimum value in the range.
rangeEnd The maximum value in the range.
convertFrom0To1Func A function which uses the current start and end of this NormalisableRange and produces a mapped value from a normalised value.
convertTo0To1Func A function which uses the current start and end of this NormalisableRange and produces a normalised value from a mapped value.
snapToLegalValueFunc A function which uses the current start and end of this NormalisableRange to take a mapped value and snap it to the nearest legal value.
Member Function Documentation
template<typename ValueType> NormalisableRange& NormalisableRange< ValueType >::operator= (const NormalisableRange< ValueType > & other) noexcept
Creates a copy of another range.
template<typename ValueType> ValueType NormalisableRange< ValueType >::convertTo0to1 (ValueType v) const noexcept
Uses the properties of this mapping to convert a non-normalised value to its 0->1 representation.
template<typename ValueType> ValueType NormalisableRange< ValueType >::convertFrom0to1 (ValueType proportion) const noexcept
Uses the properties of this mapping to convert a normalised 0->1 value to its full-range representation.
template<typename ValueType> ValueType NormalisableRange< ValueType >::snapToLegalValue (ValueType v) const noexcept
Takes a non-normalised value and snaps it based on either the interval property of this NormalisedRange or the lambda function supplied to the constructor.
template<typename ValueType> Range<ValueType> NormalisableRange< ValueType >::getRange () const noexcept
Returns the extent of the normalisable range.
template<typename ValueType> void NormalisableRange< ValueType >::setSkewForCentre (ValueType centrePointValue) noexcept
Given a value which is between the start and end points, this sets the skew such that convertFrom0to1 (0.5) will return this value.
If you have used lambda functions for convertFrom0to1Func and convertFrom0to1Func in the constructor of this class then the skew value is ignored.
Parameters
centrePointValue this must be greater than the start of the range and less than the end.
Member Data Documentation
template<typename ValueType> ValueType NormalisableRange< ValueType >::start
The minimum value of the non-normalised range.
Referenced by NormalisableRange< float >::convertFrom0to1(), NormalisableRange< float >::convertTo0to1(), NormalisableRange< float >::getRange(), NormalisableRange< float >::operator=(), NormalisableRange< float >::setSkewForCentre(), and NormalisableRange< float >::snapToLegalValue().
template<typename ValueType> ValueType NormalisableRange< ValueType >::end
The maximum value of the non-normalised range.
Referenced by NormalisableRange< float >::convertFrom0to1(), NormalisableRange< float >::convertTo0to1(), NormalisableRange< float >::getRange(), NormalisableRange< float >::operator=(), NormalisableRange< float >::setSkewForCentre(), and NormalisableRange< float >::snapToLegalValue().
template<typename ValueType> ValueType NormalisableRange< ValueType >::interval
The snapping interval that should be used (for a non-normalised value).
Use 0 for a continuous range.
If you have used a lambda function for snapToLegalValueFunction in the constructor of this class then the interval is ignored.
Referenced by NormalisableRange< float >::operator=(), and NormalisableRange< float >::snapToLegalValue().
template<typename ValueType> ValueType NormalisableRange< ValueType >::skew
An optional skew factor that alters the way values are distribute across the range.
The skew factor lets you skew the mapping logarithmically so that larger or smaller values are given a larger proportion of the available space.
A factor of 1.0 has no skewing effect at all. If the factor is < 1.0, the lower end of the range will fill more of the slider's length; if the factor is > 1.0, the upper end of the range will be expanded.
If you have used lambda functions for convertFrom0to1Func and convertFrom0to1Func in the constructor of this class then the skew value is ignored.
Referenced by NormalisableRange< float >::convertFrom0to1(), NormalisableRange< float >::convertTo0to1(), NormalisableRange< float >::operator=(), and NormalisableRange< float >::setSkewForCentre().
template<typename ValueType> bool NormalisableRange< ValueType >::symmetricSkew
If true, the skew factor applies from the middle of the slider to each of its ends.
Referenced by NormalisableRange< float >::convertFrom0to1(), NormalisableRange< float >::convertTo0to1(), NormalisableRange< float >::operator=(), and NormalisableRange< float >::setSkewForCentre().
class Random
A random number generator.
You can create a Random object and use it to generate a sequence of random numbers.
Public Member Functions
Random (int64 seedValue) noexcept
Creates a Random object based on a seed value.
Random ()
Creates a Random object using a random seed value.
~Random () noexcept
Destructor.
int nextInt () noexcept
Returns the next random 32 bit integer.
int nextInt (int maxValue) noexcept
Returns the next random number, limited to a given range.
int nextInt (Range< int > range) noexcept
Returns the next random number, limited to a given range.
int64 nextInt64 () noexcept
Returns the next 64-bit random number.
float nextFloat () noexcept
Returns the next random floating-point number.
double nextDouble () noexcept
Returns the next random floating-point number.
bool nextBool () noexcept
Returns the next random boolean value.
BigInteger nextLargeNumber (const BigInteger &maximumValue)
Returns a BigInteger containing a random number.
void fillBitsRandomly (void *bufferToFill, size_t sizeInBytes)
Fills a block of memory with random values.
void fillBitsRandomly (BigInteger &arrayToChange, int startBit, int numBits)
Sets a range of bits in a BigInteger to random values.
void setSeed (int64 newSeed) noexcept
Resets this Random object to a given seed value.
int64 getSeed () const noexcept
Returns the RNG's current seed.
void combineSeed (int64 seedValue) noexcept
Merges this object's seed with another value.
void setSeedRandomly ()
Reseeds this generator using a value generated from various semi-random system properties like the current time, etc.
Static Public Member Functions
static Random & getSystemRandom () noexcept
The overhead of creating a new Random object is fairly small, but if you want to avoid it, you can call this method to get a global shared Random object.
Constructor & Destructor Documentation
Random::Random (int64 seedValue) explicit noexcept
Creates a Random object based on a seed value.
For a given seed value, the subsequent numbers generated by this object will be predictable, so a good idea is to set this value based on the time, e.g.
new Random (Time::currentTimeMillis())
Random::Random ()
Creates a Random object using a random seed value.
Internally, this calls setSeedRandomly() to randomise the seed.
Random::~Random () noexcept
Destructor.
Member Function Documentation
int Random::nextInt () noexcept
Returns the next random 32 bit integer.
Returns
a random integer from the full range 0x80000000 to 0x7fffffff
int Random::nextInt (int maxValue) noexcept
Returns the next random number, limited to a given range.
The maxValue parameter may not be negative, or zero.
Returns
a random integer between 0 (inclusive) and maxValue (exclusive).
int Random::nextInt (Range< int > range) noexcept
Returns the next random number, limited to a given range.
Returns
a random integer between the range start (inclusive) and its end (exclusive).
int64 Random::nextInt64 () noexcept
Returns the next 64-bit random number.
Returns
a random integer from the full range 0x8000000000000000 to 0x7fffffffffffffff
float Random::nextFloat () noexcept
Returns the next random floating-point number.
Returns
a random value in the range 0 (inclusive) to 1.0 (exclusive)
double Random::nextDouble () noexcept
Returns the next random floating-point number.
Returns
a random value in the range 0 (inclusive) to 1.0 (exclusive)
bool Random::nextBool () noexcept
Returns the next random boolean value.
BigInteger Random::nextLargeNumber (const BigInteger & maximumValue)
Returns a BigInteger containing a random number.
Returns
a random value in the range 0 to (maximumValue - 1).
void Random::fillBitsRandomly (void * bufferToFill, size_t sizeInBytes)
Fills a block of memory with random values.
void Random::fillBitsRandomly (BigInteger & arrayToChange, int startBit, int numBits)
Sets a range of bits in a BigInteger to random values.
void Random::setSeed (int64 newSeed) noexcept
Resets this Random object to a given seed value.
int64 Random::getSeed () const noexcept
Returns the RNG's current seed.
void Random::combineSeed (int64 seedValue) noexcept
Merges this object's seed with another value.
This sets the seed to be a value created by combining the current seed and this new value.
void Random::setSeedRandomly ()
Reseeds this generator using a value generated from various semi-random system properties like the current time, etc.
Because this function convolves the time with the last seed value, calling it repeatedly will increase the randomness of the final result.
static Random& Random::getSystemRandom () static noexcept
The overhead of creating a new Random object is fairly small, but if you want to avoid it, you can call this method to get a global shared Random object.
It's not thread-safe though, so threads should use their own Random object, otherwise you run the risk of your random numbers becoming.. erm.. randomly corrupted..
class Range
template<typename ValueType>
class Range< ValueType >
A general-purpose range object, that simply represents any linear range with a start and end point.
Note that when checking whether values fall within the range, the start value is considered to be inclusive, and the end of the range exclusive.
The templated parameter is expected to be a primitive integer or floating point type, though class types could also be used if they behave in a number-like way.
Public Member Functions
Range () noexcept
Constructs an empty range.
Range (const ValueType startValue, const ValueType endValue) noexcept
Constructs a range with given start and end values.
Range (const Range &other) noexcept
Constructs a copy of another range.
Range & operator= (Range other) noexcept
Copies another range object.
ValueType getStart () const noexcept
Returns the start of the range.
ValueType getLength () const noexcept
Returns the length of the range.
ValueType getEnd () const noexcept
Returns the end of the range.
bool isEmpty () const noexcept
Returns true if the range has a length of zero.
void setStart (const ValueType newStart) noexcept
Changes the start position of the range, leaving the end position unchanged.
Range withStart (const ValueType newStart) const noexcept
Returns a range with the same end as this one, but a different start.
Range movedToStartAt (const ValueType newStart) const noexcept
Returns a range with the same length as this one, but moved to have the given start position.
void setEnd (const ValueType newEnd) noexcept
Changes the end position of the range, leaving the start unchanged.
Range withEnd (const ValueType newEnd) const noexcept
Returns a range with the same start position as this one, but a different end.
Range movedToEndAt (const ValueType newEnd) const noexcept
Returns a range with the same length as this one, but moved to have the given end position.
void setLength (const ValueType newLength) noexcept
Changes the length of the range.
Range withLength (const ValueType newLength) const noexcept
Returns a range with the same start as this one, but a different length.
Range expanded (ValueType amount) const noexcept
Returns a range which has its start moved down and its end moved up by the given amount.
Range operator+= (const ValueType amountToAdd) noexcept
Adds an amount to the start and end of the range.
Range operator-= (const ValueType amountToSubtract) noexcept
Subtracts an amount from the start and end of the range.
Range operator+ (const ValueType amountToAdd) const noexcept
Returns a range that is equal to this one with an amount added to its start and end.
Range operator- (const ValueType amountToSubtract) const noexcept
Returns a range that is equal to this one with the specified amount subtracted from its start and end.
bool operator== (Range other) const noexcept
bool operator!= (Range other) const noexcept
bool contains (const ValueType position) const noexcept
Returns true if the given position lies inside this range.
ValueType clipValue (const ValueType value) const noexcept
Returns the nearest value to the one supplied, which lies within the range.
bool contains (Range other) const noexcept
Returns true if the given range lies entirely inside this range.
bool intersects (Range other) const noexcept
Returns true if the given range intersects this one.
Range getIntersectionWith (Range other) const noexcept
Returns the range that is the intersection of the two ranges, or an empty range with an undefined start position if they don't overlap.
Range getUnionWith (Range other) const noexcept
Returns the smallest range that contains both this one and the other one.
Range getUnionWith (const ValueType valueToInclude) const noexcept
Returns the smallest range that contains both this one and the given value.
Range constrainRange (Range rangeToConstrain) const noexcept
Returns a given range, after moving it forwards or backwards to fit it within this range.
Static Public Member Functions
static Range between (const ValueType position1, const ValueType position2) noexcept
Returns the range that lies between two positions (in either order).
static Range withStartAndLength (const ValueType startValue, const ValueType length) noexcept
Returns a range with a given start and length.
static Range emptyRange (const ValueType start) noexcept
Returns a range with the specified start position and a length of zero.
static Range findMinAndMax (const ValueType *values, int numValues) noexcept
Scans an array of values for its min and max, and returns these as a Range.
Constructor & Destructor Documentation
template<typename ValueType> Range< ValueType >::Range () noexcept
Constructs an empty range.
Referenced by Range< int64 >::between(), Range< int64 >::emptyRange(), Range< int64 >::expanded(), Range< int64 >::findMinAndMax(), Range< int64 >::getIntersectionWith(), Range< int64 >::getUnionWith(), Range< int64 >::movedToEndAt(), Range< int64 >::movedToStartAt(), Range< int64 >::operator+(), Range< int64 >::operator-(), Range< int64 >::withEnd(), Range< int64 >::withLength(), Range< int64 >::withStart(), and Range< int64 >::withStartAndLength().
template<typename ValueType> Range< ValueType >::Range (const ValueType startValue, const ValueType endValue) noexcept
Constructs a range with given start and end values.
template<typename ValueType> Range< ValueType >::Range (const Range< ValueType > & other) noexcept
Constructs a copy of another range.
Member Function Documentation
template<typename ValueType> Range& Range< ValueType >::operator= (Range< ValueType > other) noexcept
Copies another range object.
template<typename ValueType> static Range Range< ValueType >::between (const ValueType position1, const ValueType position2) static noexcept
Returns the range that lies between two positions (in either order).
template<typename ValueType> static Range Range< ValueType >::withStartAndLength (const ValueType startValue, const ValueType length) static noexcept
Returns a range with a given start and length.
Referenced by Rectangle< int >::getHorizontalRange(), and Rectangle< int >::getVerticalRange().
template<typename ValueType> static Range Range< ValueType >::emptyRange (const ValueType start) static noexcept
Returns a range with the specified start position and a length of zero.
template<typename ValueType> ValueType Range< ValueType >::getStart () const noexcept
Returns the start of the range.
Referenced by SparseSet< int >::addRange(), SparseSet< int >::containsRange(), AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::findMinAndMax(), SparseSet< int >::overlapsRange(), and SparseSet< int >::removeRange().
template<typename ValueType> ValueType Range< ValueType >::getLength () const noexcept
Returns the length of the range.
Referenced by SparseSet< int >::addRange(), Range< int64 >::constrainRange(), SparseSet< int >::containsRange(), SparseSet< int >::overlapsRange(), and SparseSet< int >::removeRange().
template<typename ValueType> ValueType Range< ValueType >::getEnd () const noexcept
Returns the end of the range.
Referenced by SparseSet< int >::addRange(), SparseSet< int >::containsRange(), AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::findMinAndMax(), SparseSet< int >::overlapsRange(), and SparseSet< int >::removeRange().
template<typename ValueType> bool Range< ValueType >::isEmpty () const noexcept
Returns true if the range has a length of zero.
template<typename ValueType> void Range< ValueType >::setStart (const ValueType newStart) noexcept
Changes the start position of the range, leaving the end position unchanged.
If the new start position is higher than the current end of the range, the end point will be pushed along to equal it, leaving an empty range at the new position.
template<typename ValueType> Range Range< ValueType >::withStart (const ValueType newStart) const noexcept
Returns a range with the same end as this one, but a different start.
If the new start position is higher than the current end of the range, the end point will be pushed along to equal it, returning an empty range at the new position.
template<typename ValueType> Range Range< ValueType >::movedToStartAt (const ValueType newStart) const noexcept
Returns a range with the same length as this one, but moved to have the given start position.
template<typename ValueType> void Range< ValueType >::setEnd (const ValueType newEnd) noexcept
Changes the end position of the range, leaving the start unchanged.
If the new end position is below the current start of the range, the start point will be pushed back to equal the new end point.
template<typename ValueType> Range Range< ValueType >::withEnd (const ValueType newEnd) const noexcept
Returns a range with the same start position as this one, but a different end.
If the new end position is below the current start of the range, the start point will be pushed back to equal the new end point.
template<typename ValueType> Range Range< ValueType >::movedToEndAt (const ValueType newEnd) const noexcept
Returns a range with the same length as this one, but moved to have the given end position.
template<typename ValueType> void Range< ValueType >::setLength (const ValueType newLength) noexcept
Changes the length of the range.
Lengths less than zero are treated as zero.
template<typename ValueType> Range Range< ValueType >::withLength (const ValueType newLength) const noexcept
Returns a range with the same start as this one, but a different length.
Lengths less than zero are treated as zero.
template<typename ValueType> Range Range< ValueType >::expanded (ValueType amount) const noexcept
Returns a range which has its start moved down and its end moved up by the given amount.
Returns
The returned range will be (start - amount, end + amount)
template<typename ValueType> Range Range< ValueType >::operator+= (const ValueType amountToAdd) noexcept
Adds an amount to the start and end of the range.
template<typename ValueType> Range Range< ValueType >::operator-= (const ValueType amountToSubtract) noexcept
Subtracts an amount from the start and end of the range.
template<typename ValueType> Range Range< ValueType >::operator+ (const ValueType amountToAdd) const noexcept
Returns a range that is equal to this one with an amount added to its start and end.
template<typename ValueType> Range Range< ValueType >::operator- (const ValueType amountToSubtract) const noexcept
Returns a range that is equal to this one with the specified amount subtracted from its start and end.
template<typename ValueType> bool Range< ValueType >::operator== (Range< ValueType > other) const noexcept
template<typename ValueType> bool Range< ValueType >::operator!= (Range< ValueType > other) const noexcept
template<typename ValueType> bool Range< ValueType >::contains (const ValueType position) const noexcept
Returns true if the given position lies inside this range.
When making this comparison, the start value is considered to be inclusive, and the end of the range exclusive.
template<typename ValueType> ValueType Range< ValueType >::clipValue (const ValueType value) const noexcept
Returns the nearest value to the one supplied, which lies within the range.
template<typename ValueType> bool Range< ValueType >::contains (Range< ValueType > other) const noexcept
Returns true if the given range lies entirely inside this range.
template<typename ValueType> bool Range< ValueType >::intersects (Range< ValueType > other) const noexcept
Returns true if the given range intersects this one.
template<typename ValueType> Range Range< ValueType >::getIntersectionWith (Range< ValueType > other) const noexcept
Returns the range that is the intersection of the two ranges, or an empty range with an undefined start position if they don't overlap.
template<typename ValueType> Range Range< ValueType >::getUnionWith (Range< ValueType > other) const noexcept
Returns the smallest range that contains both this one and the other one.
Referenced by AudioBlock< float >::findMinAndMax().
template<typename ValueType> Range Range< ValueType >::getUnionWith (const ValueType valueToInclude) const noexcept
Returns the smallest range that contains both this one and the given value.
template<typename ValueType> Range Range< ValueType >::constrainRange (Range< ValueType > rangeToConstrain) const noexcept
Returns a given range, after moving it forwards or backwards to fit it within this range.
If the supplied range has a greater length than this one, the return value will be this range.
Otherwise, if the supplied range is smaller than this one, the return value will be the new range, shifted forwards or backwards so that it doesn't extend beyond this one, but keeping its original length.
template<typename ValueType> static Range Range< ValueType >::findMinAndMax (const ValueType * values, int numValues) static noexcept
Scans an array of values for its min and max, and returns these as a Range.
class StatisticsAccumulator
template<typename FloatType>
class StatisticsAccumulator< FloatType >
A class that measures various statistics about a series of floating point values that it is given.
Public Member Functions
StatisticsAccumulator () noexcept
Constructs a new StatisticsAccumulator.
void addValue (FloatType v) noexcept
Add a new value to the accumulator.
void reset () noexcept
Reset the accumulator.
FloatType getAverage () const noexcept
Returns the average (arithmetic mean) of all previously added values.
FloatType getVariance () const noexcept
Returns the variance of all previously added values.
FloatType getStandardDeviation () const noexcept
Returns the standard deviation of all previously added values.
FloatType getMinValue () const noexcept
Returns the smallest of all previously added values.
FloatType getMaxValue () const noexcept
Returns the largest of all previously added values.
size_t getCount () const noexcept
Returns how many values have been added to this accumulator.
Constructor & Destructor Documentation
template<typename FloatType > StatisticsAccumulator< FloatType >::StatisticsAccumulator () noexcept
Constructs a new StatisticsAccumulator.
Member Function Documentation
template<typename FloatType > void StatisticsAccumulator< FloatType >::addValue (FloatType v) noexcept
Add a new value to the accumulator.
This will update all running statistics accordingly.
References jassert, and juce_isfinite().
template<typename FloatType > void StatisticsAccumulator< FloatType >::reset () noexcept
Reset the accumulator.
This will reset all currently saved statistcs.
template<typename FloatType > FloatType StatisticsAccumulator< FloatType >::getAverage () const noexcept
Returns the average (arithmetic mean) of all previously added values.
If no values have been added yet, this will return zero.
template<typename FloatType > FloatType StatisticsAccumulator< FloatType >::getVariance () const noexcept
Returns the variance of all previously added values.
If no values have been added yet, this will return zero.
Referenced by StatisticsAccumulator< FloatType >::getStandardDeviation().
template<typename FloatType > FloatType StatisticsAccumulator< FloatType >::getStandardDeviation () const noexcept
Returns the standard deviation of all previously added values.
If no values have been added yet, this will return zero.
References StatisticsAccumulator< FloatType >::getVariance().
template<typename FloatType > FloatType StatisticsAccumulator< FloatType >::getMinValue () const noexcept
Returns the smallest of all previously added values.
If no values have been added yet, this will return positive infinity.
template<typename FloatType > FloatType StatisticsAccumulator< FloatType >::getMaxValue () const noexcept
Returns the largest of all previously added values.
If no values have been added yet, this will return negative infinity.
template<typename FloatType > size_t StatisticsAccumulator< FloatType >::getCount () const noexcept
Returns how many values have been added to this accumulator.
Macro Definition Documentation
#define JUCE_UNDENORMALISE (x) { (x) += 0.1f; (x) -= 0.1f; }
This macro can be applied to a float variable to check whether it contains a denormalised value, and to normalise it if necessary.
On CPUs that aren't vulnerable to denormalisation problems, this will have no effect.
Typedef Documentation
typedef signed char int8
A platform-independent 8-bit signed integer type.
typedef unsigned char uint8
A platform-independent 8-bit unsigned integer type.
typedef signed short int16
A platform-independent 16-bit signed integer type.
typedef unsigned short uint16
A platform-independent 16-bit unsigned integer type.
typedef signed int int32
A platform-independent 32-bit signed integer type.
typedef unsigned int uint32
A platform-independent 32-bit unsigned integer type.
typedef long long int64
A platform-independent 64-bit integer type.
typedef unsigned long long uint64
A platform-independent 64-bit unsigned integer type.
typedef int pointer_sized_int
A signed integer type that's guaranteed to be large enough to hold a pointer without truncating it.
typedef unsigned int pointer_sized_uint
An unsigned integer type that's guaranteed to be large enough to hold a pointer without truncating it.
Function Documentation
OutputStream& JUCE_CALLTYPE operator<< (OutputStream & stream, const BigInteger & value)
Writes a BigInteger to an OutputStream as a UTF8 decimal string.
template<typename Type > Type jmax (const Type a, const Type b)
Returns the larger of two values.
Referenced by Rectangle< int >::enlargeIfAdjacent(), Rectangle< int >::expand(), Rectangle< int >::expanded(), Rectangle< int >::findAreaContainingPoints(), Decibels::gainToDecibels(), RectangleList< int >::getBounds(), Rectangle< int >::getIntersection(), Range< int64 >::getIntersectionWith(), AudioBuffer< float >::getMagnitude(), Polynomial< FloatingType >::getProductWith(), Rectangle< int >::getUnion(), Range< int64 >::getUnionWith(), Rectangle< int >::intersectRectangle(), Rectangle< int >::intersectRectangles(), jmax(), AudioUnitHelpers::CoreAudioBufferList::prepare(), FIR::Filter< SampleType >::reset(), ResizableBorderComponent::Zone::resizeRectangleBy(), Rectangle< int >::setLeft(), Range< int64 >::setLength(), TextEditor::setLineSpacing(), Draggable3DOrientation::setRadius(), Rectangle< int >::setTop(), Rectangle< int >::transformedBy(), Rectangle< int >::withBottom(), Rectangle< int >::withLeft(), Rectangle< int >::withRight(), Range< int64 >::withStart(), and Rectangle< int >::withTop().
template<typename Type > Type jmax (const Type a, const Type b, const Type c)
Returns the larger of three values.
template<typename Type > Type jmax (const Type a, const Type b, const Type c, const Type d)
Returns the larger of four values.
References jmax().
template<typename Type > Type jmin (const Type a, const Type b)
Returns the smaller of two values.
Referenced by AudioBlock< float >::add(), AudioBlock< float >::addWithMultiply(), Rectangle< int >::constrainedWithin(), AudioBlock< float >::copy(), SelectedItemSet< SelectableItemType >::deselectAll(), Rectangle< int >::enlargeIfAdjacent(), Rectangle< int >::findAreaContainingPoints(), RectangleList< int >::getBounds(), AudioUnitHelpers::getBusCount(), Rectangle< int >::getIntersection(), Range< int64 >::getIntersectionWith(), Rectangle< int >::getUnion(), Range< int64 >::getUnionWith(), Rectangle< int >::intersectRectangle(), Rectangle< int >::intersectRectangles(), jmin(), AudioBlock< float >::max(), AudioBlock< float >::min(), AudioBlock< float >::move(), AudioBlock< float >::multiply(), ProcessorDuplicator< MonoProcessorType, StateType >::process(), Rectangle< int >::removeFromBottom(), Rectangle< int >::removeFromLeft(), Rectangle< int >::removeFromRight(), Rectangle< int >::removeFromTop(), SparseSet< int >::removeRange(), AudioBlock< float >::replaceWithAbsoluteValueOf(), AudioBlock< float >::replaceWithNegativeOf(), ResizableBorderComponent::Zone::resizeRectangleBy(), SelectedItemSet< SelectableItemType >::selectOnly(), Rectangle< int >::setBottom(), Rectangle< int >::setRight(), AudioBuffer< float >::setSize(), AudioBlock< float >::subtract(), Rectangle< int >::transformedBy(), PixelARGB::unpremultiply(), Rectangle< int >::withBottom(), Range< int64 >::withEnd(), Rectangle< int >::withRight(), Line< ValueType >::withShortenedEnd(), Line< ValueType >::withShortenedStart(), and Packed7BitArrayBuilder< maxPacketBytes >::writeBits().
template<typename Type > Type jmin (const Type a, const Type b, const Type c)
Returns the smaller of three values.
template<typename Type > Type jmin (const Type a, const Type b, const Type c, const Type d)
Returns the smaller of four values.
References jmin().
template<typename Type > Type jmap (Type value0To1, Type targetRangeMin, Type targetRangeMax)
Remaps a normalised value (between 0 and 1) to a target range.
This effectively returns (targetRangeMin + value0To1 * (targetRangeMax - targetRangeMin)).
Referenced by LookupTable< NumericType >::getUnchecked().
template<typename Type > Type jmap (Type sourceValue, Type sourceRangeMin, Type sourceRangeMax, Type targetRangeMin, Type targetRangeMax)
Remaps a value from a source range to a target range.
References jassert.
template<typename Type > Type findMinimum (const Type * data, int numValues)
Scans an array of values, returning the minimum value that it contains.
template<typename Type > Type findMaximum (const Type * values, int numValues)
Scans an array of values, returning the maximum value that it contains.
template<typename Type > void findMinAndMax (const Type * values, int numValues, Type & lowest, Type & highest)
Scans an array of values, returning the minimum and maximum values that it contains.
Referenced by AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::findMinAndMax().
template<typename Type > Type jlimit (const Type lowerLimit, const Type upperLimit, const Type valueToConstrain) noexcept
Constrains a value to keep it within a given range.
This will check that the specified value lies between the lower and upper bounds specified, and if not, will return the nearest value that would be in-range. Effectively, it's like calling jmax (lowerLimit, jmin (upperLimit, value)).
Note that it expects that lowerLimit <= upperLimit. If this isn't true, the results will be unpredictable.
Parameters
lowerLimit the minimum value to return
upperLimit the maximum value to return
valueToConstrain the value to try to return
Returns
the closest value to valueToConstrain which lies between lowerLimit and upperLimit (inclusive)
See Also
jmin, jmax, jmap
References jassert.
Referenced by Range< int64 >::clipValue(), Rectangle< int >::constrainedWithin(), Range< int64 >::constrainRange(), Line< ValueType >::findNearestProportionalPositionTo(), IntegerWithBitSize< 8 >::fromBipolarFloat(), IntegerWithBitSize< 8 >::fromUnipolarFloat(), Rectangle< int >::getConstrainedPoint(), LookupTableTransform< NumericType >::processSample(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeRange(), OwnedArray< MidiBuffer >::removeRange(), and Array< Button::Listener * >::removeRange().
template<typename Type > bool isPositiveAndBelow (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also below a specified upper limit.
This is basically a quicker way to write:
valueToTest >= 0 && valueToTest < upperLimit
References jassert.
Referenced by AudioBuffer< float >::addFrom(), AudioBuffer< float >::addFromWithRamp(), AudioBuffer< float >::addSample(), AudioBuffer< float >::applyGain(), AudioBuffer< float >::applyGainRamp(), AudioBuffer< float >::clear(), AudioBuffer< float >::copyFrom(), AudioBuffer< float >::copyFromWithRamp(), AudioBuffer< float >::findMinMax(), MidiEventList::getEvent(), AudioBuffer< float >::getMagnitude(), AudioProcessor::BusesLayout::getNumChannels(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointer(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointerUnchecked(), SparseSet< int >::getRange(), AudioBuffer< float >::getReadPointer(), Array< Button::Listener * >::getReference(), AudioBuffer< float >::getRMSLevel(), AudioBuffer< float >::getSample(), LookupTable< NumericType >::getUnchecked(), OwnedArray< MidiBuffer >::getUnchecked(), Array< Button::Listener * >::getUnchecked(), AudioBuffer< float >::getWritePointer(), Array< Button::Listener * >::insert(), OwnedArray< MidiBuffer >::insertArray(), Array< Button::Listener * >::insertArray(), Array< Button::Listener * >::insertMultiple(), EdgeTable::iterate(), ReferenceCountedArray< AudioProcessorGraph::Node >::move(), OwnedArray< MidiBuffer >::move(), Array< Button::Listener * >::move(), OwnedArray< MidiBuffer >::operator[](), Array< Button::Listener * >::operator[](), LookupTableTransform< NumericType >::processSample(), ReferenceCountedArray< AudioProcessorGraph::Node >::remove(), OwnedArray< MidiBuffer >::remove(), Array< Button::Listener * >::remove(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeAndReturn(), OwnedArray< MidiBuffer >::removeAndReturn(), Array< Button::Listener * >::removeAndReturn(), AudioBuffer< float >::reverse(), Array< Button::Listener * >::set(), AudioBuffer< float >::setSample(), Array< Button::Listener * >::setUnchecked(), ReferenceCountedArray< AudioProcessorGraph::Node >::swap(), OwnedArray< MidiBuffer >::swap(), and Array< Button::Listener * >::swap().
template<> bool isPositiveAndBelow (const int valueToTest, const int upperLimit) noexcept
References jassert.
template<typename Type > bool isPositiveAndNotGreaterThan (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit.
This is basically a quicker way to write:
valueToTest >= 0 && valueToTest <= upperLimit
References jassert.
template<> bool isPositiveAndNotGreaterThan (const int valueToTest, const int upperLimit) noexcept
References jassert.
template<typename Type > void swapVariables (Type & variable1, Type & variable2)
Handy function to swap two values.
template<typename Type1 > void ignoreUnused (const Type1 &) noexcept
Handy function for avoiding unused variables warning.
Referenced by OwnedArray< MidiBuffer >::addSorted(), StandalonePluginHolder::askUserToLoadState(), StandalonePluginHolder::askUserToSaveState(), AudioProcessor::canAddBus(), AudioProcessor::canRemoveBus(), UndoableAction::createCoalescedAction(), ContainerDeletePolicy< ObjectType >::destroy(), MidiInputCallback::handlePartialSysexMessage(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOfSorted(), OwnedArray< MidiBuffer >::indexOfSorted(), Array< Button::Listener * >::indexOfSorted(), numElementsInArray(), FIR::Filter< SampleType >::prepare(), PositionableAudioSource::setLooping(), ReferenceCountedArray< AudioProcessorGraph::Node >::sort(), OwnedArray< MidiBuffer >::sort(), Array< Button::Listener * >::sort(), AudioPlayHead::transportPlay(), and AudioPlayHead::transportRecord().
template<typename Type1 , typename Type2 > void ignoreUnused (const Type1 & , const Type2 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 > void ignoreUnused (const Type1 & , const Type2 & , const Type3 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 , typename Type4 > void ignoreUnused (const Type1 & , const Type2 & , const Type3 & , const Type4 &) noexcept
template<typename Type , int N> int numElementsInArray (Type(&) array[N])
Handy function for getting the number of elements in a simple const C array.
E.g.
static int myArray[] = { 1, 2, 3 };
int numElements = numElementsInArray (myArray) // returns 3
References ignoreUnused().
Referenced by CoreAudioLayouts::getSpeakerLayoutForCoreAudioTag(), and CoreAudioLayouts::toCoreAudio().
template<typename Type > Type juce_hypot (Type a, Type b) noexcept
Using juce_hypot is easier than dealing with the different types of hypot function that are provided by the various platforms and compilers.
Referenced by Point< int >::getDistanceFrom(), Point< int >::getDistanceFromOrigin(), and Line< ValueType >::getPointAlongLine().
int64 abs64 (const int64 n) noexcept
64-bit abs function.
float degreesToRadians (float degrees) noexcept
Converts an angle in degrees to radians.
double degreesToRadians (double degrees) noexcept
Converts an angle in degrees to radians.
float radiansToDegrees (float radians) noexcept
Converts an angle in radians to degrees.
References float_Pi.
double radiansToDegrees (double radians) noexcept
Converts an angle in radians to degrees.
References double_Pi.
template<typename NumericType > bool juce_isfinite (NumericType) noexcept
The isfinite() method seems to vary between platforms, so this is a platform-independent function for it.
Referenced by StatisticsAccumulator< FloatType >::addValue(), Point< int >::isFinite(), and Rectangle< int >::isFinite().
template<> bool juce_isfinite (float value) noexcept
template<> bool juce_isfinite (double value) noexcept
template<typename FloatType > int roundToInt (const FloatType value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a float to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently.
Referenced by AudioParameterInt::get(), AudioParameterChoice::getIndex(), roundDoubleToInt(), roundFloatToInt(), Point< int >::roundToInt(), roundToIntAccurate(), and Rectangle< int >::toNearestInt().
int roundToInt (int value) noexcept
int roundToIntAccurate (double value) noexcept
Fast floating-point-to-integer conversion.
This is a slightly slower and slightly more accurate version of roundDoubleToInt(). It works fine for values above zero, but negative numbers are rounded the wrong way.
References roundToInt().
int roundDoubleToInt (double value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a double to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently. For a more accurate conversion, see roundDoubleToIntAccurate().
References roundToInt().
int roundFloatToInt (float value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a float to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently.
References roundToInt().
template<typename FloatType > unsigned int truncatePositiveToUnsignedInt (FloatType value) noexcept
Truncates a positive floating-point number to an unsigned int.
This is generally faster than static_cast<unsigned int> (std::floor (x)) but it only works for positive numbers small enough to be represented as an unsigned int.
References jassert, and max().
Referenced by LookupTable< NumericType >::getUnchecked().
template<typename IntegerType > bool isPowerOfTwo (IntegerType value)
Returns true if the specified integer is a power-of-two.
int nextPowerOfTwo (int n) noexcept
Returns the smallest power-of-two which is equal to or greater than the given integer.
int findHighestSetBit (uint32 n) noexcept
Returns the index of the highest set bit in a (non-zero) number.
So for n=3 this would return 1, for n=7 it returns 2, etc. An input value of 0 is illegal!
int countNumberOfBits (uint32 n) noexcept
Returns the number of bits in a 32-bit integer.
Referenced by countNumberOfBits().
int countNumberOfBits (uint64 n) noexcept
Returns the number of bits in a 64-bit integer.
References countNumberOfBits().
template<typename IntegerType > IntegerType negativeAwareModulo (IntegerType dividend, const IntegerType divisor) noexcept
Performs a modulo operation, but can cope with the dividend being negative.
The divisor must be greater than zero.
References jassert.
template<typename NumericType > NumericType square (NumericType n) noexcept
Returns the square of its argument.
void writeLittleEndianBitsInBuffer (void * targetBuffer, uint32 startBit, uint32 numBits, uint32 value) noexcept
Writes a number of bits into a memory buffer at a given bit index.
The buffer is treated as a sequence of 8-bit bytes, and the value is encoded in little-endian order, so for example if startBit = 10, and numBits = 11 then the lower 6 bits of the value would be written into bits 2-8 of targetBuffer[1], and the upper 5 bits of value into bits 0-5 of targetBuffer[2].
See Also
readLittleEndianBitsInBuffer
Referenced by littlefoot::LittleFootRemoteHeap< ImplementationClass >::setBits().
uint32 readLittleEndianBitsInBuffer (const void * sourceBuffer, uint32 startBit, uint32 numBits) noexcept
Reads a number of bits from a buffer at a given bit index.
The buffer is treated as a sequence of 8-bit bytes, and the value is encoded in little-endian order, so for example if startBit = 10, and numBits = 11 then the lower 6 bits of the result would be read from bits 2-8 of sourceBuffer[1], and the upper 5 bits of the result from bits 0-5 of sourceBuffer[2].
See Also
writeLittleEndianBitsInBuffer
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapBits(), and littlefoot::LittleFootRemoteHeap< ImplementationClass >::setBits().
Variable Documentation
const double double_Pi = MathConstants<double>::pi
A predefined value for Pi, at double-precision.
See Also
float_Pi
Referenced by Oscillator< SampleType >::Oscillator(), Oscillator< SampleType >::process(), Oscillator< SampleType >::processSample(), radiansToDegrees(), and StateVariableFilter::Parameters< NumericType >::setCutOffFrequency().
const float float_Pi = MathConstants<float>::pi
A predefined value for Pi, at single-precision.
See Also
double_Pi
Referenced by radiansToDegrees().
template<typename FloatType > const FloatType MathConstants< FloatType >::pi = static_cast<FloatType> (3.141592653589793238L) static
A predefined value for Pi.
template<typename FloatType > const FloatType MathConstants< FloatType >::euler = static_cast<FloatType> (2.71828182845904523536L) static
A predfined value for Euler's number.