JUCE: format_types
format_types
juce_audio_processors
Namespaces
Steinberg
Classes
struct AudioUnitHelpers
class AudioUnitPluginFormat
Implements a plugin format manager for AudioUnits.
class LADSPAPluginFormat
Implements a plugin format manager for LADSPA plugins.
class ComSmartPtr< ObjectType >
class MidiEventList
struct VST3BufferExchange< FloatType >
struct VST3FloatAndDoubleBusMapCompositeHelper< FloatType >
struct VST3FloatAndDoubleBusMapComposite
struct VST3FloatAndDoubleBusMapCompositeHelper< float >
struct VST3FloatAndDoubleBusMapCompositeHelper< double >
class VST3PluginFormat
Implements a plugin format for VST3s.
struct SpeakerMappings
struct VstEffectInterface
struct VstEditorBounds
struct VstPinInfo
struct VstEvent
struct VstEventBlock
struct VstMidiEvent
struct VstSysExEvent
struct VstTimingInformation
struct VstIndividualSpeakerInfo
struct VstSpeakerConfiguration
struct vst2FxBank
class VSTPluginFormat
Implements a plugin format manager for VSTs.
Macros
#define JUCE_STATE_DICTIONARY_KEY "jucePluginState"
#define JUCE_DECLARE_VST3_COM_REF_METHODS
#define JUCE_DECLARE_VST3_COM_QUERY_METHODS
#define TEST_FOR_AND_RETURN_IF_VALID(iidToTest, ClassType)
#define TEST_FOR_COMMON_BASE_AND_RETURN_IF_VALID(iidToTest, CommonClassType, SourceClassType)
#define DEVELOPMENT 0
#define JUCE_VSTINTERFACE_H_INCLUDED
#define VSTINTERFACECALL
#define JUCE_MULTICHAR_CONSTANT(a, b, c, d) (d | (((uint32) c) << 8) | (((uint32) b) << 16) | (((uint32) a) << 24))
Typedefs
typedef int32 op
typedef int32 int32 index
typedef int32 int32
pointer_sized_int value
typedef int32 int32
pointer_sized_int void * ptr
typedef int32 int32
pointer_sized_int void float opt
Enumerations
enum { kAudioUnitProperty_SupportsMPE = 58 }
enum VstEffectInterfaceFlags {
vstEffectFlagHasEditor = 1, vstEffectFlagInplaceAudio = 16, vstEffectFlagDataInChunks = 32, vstEffectFlagIsSynth = 256,
vstEffectFlagInplaceDoubleAudio = 4096
}
enum VstHostToPlugInOpcodes {
plugInOpcodeOpen, plugInOpcodeClose, plugInOpcodeSetCurrentProgram, plugInOpcodeGetCurrentProgram,
plugInOpcodeSetCurrentProgramName, plugInOpcodeGetCurrentProgramName, plugInOpcodeGetParameterLabel, plugInOpcodeGetParameterText,
plugInOpcodeGetParameterName, plugInOpcodeSetSampleRate = plugInOpcodeGetParameterName + 2, plugInOpcodeSetBlockSize, plugInOpcodeResumeSuspend,
plugInOpcodeGetEditorBounds, plugInOpcodeOpenEditor, plugInOpcodeCloseEditor, plugInOpcodeDrawEditor,
plugInOpcodeGetMouse, plugInOpcodeEditorIdle = plugInOpcodeGetMouse + 2, plugInOpcodeeffEditorTop, plugInOpcodeSleepEditor,
plugInOpcodeIdentify, plugInOpcodeGetData, plugInOpcodeSetData, plugInOpcodePreAudioProcessingEvents,
plugInOpcodeIsParameterAutomatable, plugInOpcodeParameterValueForText, plugInOpcodeGetProgramName = plugInOpcodeParameterValueForText + 2, plugInOpcodeConnectInput = plugInOpcodeGetProgramName + 2,
plugInOpcodeConnectOutput, plugInOpcodeGetInputPinProperties, plugInOpcodeGetOutputPinProperties, plugInOpcodeGetPlugInCategory,
plugInOpcodeSetSpeakerConfiguration = plugInOpcodeGetPlugInCategory + 7, plugInOpcodeSetBypass = plugInOpcodeSetSpeakerConfiguration + 2, plugInOpcodeGetPlugInName, plugInOpcodeGetManufacturerName = plugInOpcodeGetPlugInName + 2,
plugInOpcodeGetManufacturerProductName, plugInOpcodeGetManufacturerVersion, plugInOpcodeManufacturerSpecific, plugInOpcodeCanPlugInDo,
plugInOpcodeGetTailSize, plugInOpcodeIdle, plugInOpcodeKeyboardFocusRequired = plugInOpcodeIdle + 4, plugInOpcodeGetVstInterfaceVersion,
plugInOpcodeGetCurrentMidiProgram = plugInOpcodeGetVstInterfaceVersion + 5, plugInOpcodeGetSpeakerArrangement = plugInOpcodeGetCurrentMidiProgram + 6, plugInOpcodeNextPlugInUniqueID, plugInOpcodeStartProcess,
plugInOpcodeStopProcess, plugInOpcodeSetNumberOfSamplesToProcess, plugInOpcodeSetSampleFloatType = plugInOpcodeSetNumberOfSamplesToProcess + 4, pluginOpcodeGetNumMidiInputChannels,
pluginOpcodeGetNumMidiOutputChannels, plugInOpcodeMaximum = pluginOpcodeGetNumMidiOutputChannels
}
enum VstPlugInToHostOpcodes {
hostOpcodeParameterChanged, hostOpcodeVstVersion, hostOpcodeCurrentId, hostOpcodeIdle,
hostOpcodePinConnected, hostOpcodePlugInWantsMidi = hostOpcodePinConnected + 2, hostOpcodeGetTimingInfo, hostOpcodePreAudioProcessingEvents,
hostOpcodeSetTime, hostOpcodeTempoAt, hostOpcodeGetNumberOfAutomatableParameters, hostOpcodeGetParameterInterval,
hostOpcodeIOModified, hostOpcodeNeedsIdle, hostOpcodeWindowSize, hostOpcodeGetSampleRate,
hostOpcodeGetBlockSize, hostOpcodeGetInputLatency, hostOpcodeGetOutputLatency, hostOpcodeGetPreviousPlugIn,
hostOpcodeGetNextPlugIn, hostOpcodeWillReplace, hostOpcodeGetCurrentAudioProcessingLevel, hostOpcodeGetAutomationState,
hostOpcodeOfflineStart, hostOpcodeOfflineReadSource, hostOpcodeOfflineWrite, hostOpcodeOfflineGetCurrentPass,
hostOpcodeOfflineGetCurrentMetaPass, hostOpcodeSetOutputSampleRate, hostOpcodeGetOutputSpeakerConfiguration, hostOpcodeGetManufacturerName,
hostOpcodeGetProductName, hostOpcodeGetManufacturerVersion, hostOpcodeManufacturerSpecific, hostOpcodeSetIcon,
hostOpcodeCanHostDo, hostOpcodeGetLanguage, hostOpcodeOpenEditorWindow, hostOpcodeCloseEditorWindow,
hostOpcodeGetDirectory, hostOpcodeUpdateView, hostOpcodeParameterChangeGestureBegin, hostOpcodeParameterChangeGestureEnd
}
enum VstProcessingSampleType { vstProcessingSampleTypeFloat, vstProcessingSampleTypeDouble }
enum VstPlugInCategory {
kPlugCategUnknown, kPlugCategEffect, kPlugCategSynth, kPlugCategAnalysis,
kPlugCategMastering, kPlugCategSpacializer, kPlugCategRoomFx, kPlugSurroundFx,
kPlugCategRestoration, kPlugCategOfflineProcess, kPlugCategShell, kPlugCategGenerator
}
enum VstMaxStringLengths {
vstMaxNameLength = 64, vstMaxParameterOrPinLabelLength = 64, vstMaxParameterOrPinShortLabelLength = 8, vstMaxCategoryLength = 24,
vstMaxManufacturerStringLength = 64, vstMaxPlugInNameStringLength = 64
}
enum VstPinInfoFlags { vstPinInfoFlagIsActive = 1, vstPinInfoFlagIsStereo = 2, vstPinInfoFlagValid = 4 }
enum VstEventTypes { vstMidiEventType = 1, vstSysExEventType = 6 }
enum VstMidiEventFlags { vstMidiEventIsRealtime = 1 }
enum VstTimingInformationFlags {
vstTimingInfoFlagTransportChanged = 1, vstTimingInfoFlagCurrentlyPlaying = 2, vstTimingInfoFlagLoopActive = 4, vstTimingInfoFlagCurrentlyRecording = 8,
vstTimingInfoFlagAutomationWriteModeActive = 64, vstTimingInfoFlagAutomationReadModeActive = 128, vstTimingInfoFlagNanosecondsValid = 256, vstTimingInfoFlagMusicalPositionValid = 512,
vstTimingInfoFlagTempoValid = 1024, vstTimingInfoFlagLastBarPositionValid = 2048, vstTimingInfoFlagLoopPositionValid = 4096, vstTimingInfoFlagTimeSignatureValid = 8192,
vstTimingInfoFlagSmpteValid = 16384, vstTimingInfoFlagNearestClockValid = 32768
}
enum VstSmpteRates {
vstSmpteRateFps24, vstSmpteRateFps25, vstSmpteRateFps2997, vstSmpteRateFps30,
vstSmpteRateFps2997drop, vstSmpteRateFps30drop, vstSmpteRate16mmFilm, vstSmpteRate35mmFilm,
vstSmpteRateFps239 = vstSmpteRate35mmFilm + 3, vstSmpteRateFps249, vstSmpteRateFps599, vstSmpteRateFps60
}
enum VstIndividualSpeakerType {
vstIndividualSpeakerTypeUndefined = 0x7fffffff, vstIndividualSpeakerTypeMono = 0, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeRight,
vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeRightSurround,
vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeCentreSurround = vstIndividualSpeakerTypeSurround,
vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopFrontLeft,
vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopRearLeft, vstIndividualSpeakerTypeTopRearCentre,
vstIndividualSpeakerTypeTopRearRight, vstIndividualSpeakerTypeLFE2
}
enum VstSpeakerConfigurationType {
vstSpeakerConfigTypeUser = -2, vstSpeakerConfigTypeEmpty = -1, vstSpeakerConfigTypeMono = 0, vstSpeakerConfigTypeLR,
vstSpeakerConfigTypeLsRs, vstSpeakerConfigTypeLcRc, vstSpeakerConfigTypeSlSr, vstSpeakerConfigTypeCLfe,
vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeLRCLfe, vstSpeakerConfigTypeLRLfeS,
vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRCLfeS, vstSpeakerConfigTypeLRLfeLsRs,
vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRLsRsSlSr,
vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr,
vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRsLcRcCs, vstSpeakerConfigTypeLRCLsRsCsSlSr,
vstSpeakerConfigTypeLRCLfeLsRsLcRcCs, vstSpeakerConfigTypeLRCLfeLsRsCsSlSr, vstSpeakerConfigTypeLRCLfeLsRsTflTfcTfrTrlTrrLfe2
}
enum PresonusExtensionConstants { presonusVendorID = JUCE_MULTICHAR_CONSTANT ('P', 'r', 'e', 'S'), presonusSetContentScaleFactor = JUCE_MULTICHAR_CONSTANT ('A', 'e', 'C', 's') }
Functions
juce::String toString (const Steinberg::char8 *string) noexcept
juce::String toString (const Steinberg::char16 *string) noexcept
juce::String toString (const Steinberg::UString128 &string) noexcept
juce::String toString (const Steinberg::UString256 &string) noexcept
void toString128 (Steinberg::Vst::String128 result, const char *source)
void toString128 (Steinberg::Vst::String128 result, const juce::String &source)
Steinberg::Vst::TChar * toString (const juce::String &source) noexcept
typedef pointer_sized_int (VSTINTERFACECALL *VstHostCallback)(VstEffectInterface *
Variables
const int32 juceVstInterfaceVersion = 2400
const int32 juceVstInterfaceIdentifier = 0x56737450
Detailed Description
Class Documentation
struct AudioUnitHelpers
Static Public Member Functions
static bool isAudioBufferInterleaved (const AudioBufferList &audioBuffer) noexcept
static void clearAudioBuffer (const AudioBufferList &audioBuffer) noexcept
static void copyAudioBuffer (const AudioBufferList &audioBuffer, const int channel, const UInt32 size, float *dst) noexcept
static void copyAudioBuffer (const float *src, const int channel, const UInt32 size, AudioBufferList &audioBuffer) noexcept
template<int numLayouts>
static bool isLayoutSupported (const AudioProcessor &processor, bool isInput, int busIdx, int numChannels, const short(&channelLayoutList)[numLayouts][2], bool hasLayoutMap=true)
static Array< AUChannelInfo > getAUChannelInfo (const AudioProcessor &processor)
static bool isNumberOfChannelsSupported (const AudioProcessor::Bus *b, int numChannels, AudioProcessor::BusesLayout &inOutCurrentLayout)
static int getBusCount (const AudioProcessor *juceFilter, bool isInput)
static bool setBusesLayout (AudioProcessor *juceFilter, const AudioProcessor::BusesLayout &requestedLayouts)
static AudioProcessor::BusesLayout getBusesLayout (const AudioProcessor *juceFilter)
Member Function Documentation
static bool AudioUnitHelpers::isAudioBufferInterleaved (const AudioBufferList & audioBuffer) static noexcept
Referenced by copyAudioBuffer(), AudioUnitHelpers::CoreAudioBufferList::pop(), and AudioUnitHelpers::CoreAudioBufferList::push().
static void AudioUnitHelpers::clearAudioBuffer (const AudioBufferList & audioBuffer) static noexcept
References zeromem().
static void AudioUnitHelpers::copyAudioBuffer (const AudioBufferList & audioBuffer, const int channel, const UInt32 size, float * dst) static noexcept
References isAudioBufferInterleaved(), and jassert.
Referenced by AudioUnitHelpers::CoreAudioBufferList::pop(), and AudioUnitHelpers::CoreAudioBufferList::push().
static void AudioUnitHelpers::copyAudioBuffer (const float * src, const int channel, const UInt32 size, AudioBufferList & audioBuffer) static noexcept
References isAudioBufferInterleaved(), and jassert.
template<int numLayouts> static bool AudioUnitHelpers::isLayoutSupported (const AudioProcessor & processor, bool isInput, int busIdx, int numChannels, const short(&) channelLayoutList[numLayouts][2], bool hasLayoutMap = true) static
References AudioProcessor::getBus().
static Array<AUChannelInfo> AudioUnitHelpers::getAUChannelInfo (const AudioProcessor & processor) static
References SortedSet< ElementType, TypeOfCriticalSectionToUse >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), AudioProcessor::getBus(), getBusCount(), AudioProcessor::getBusesLayout(), AudioProcessor::getChannelCountOfBus(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isNumberOfChannelsSupported(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
static bool AudioUnitHelpers::isNumberOfChannelsSupported (const AudioProcessor::Bus * b, int numChannels, AudioProcessor::BusesLayout & inOutCurrentLayout) static
References AudioChannelSet::channelSetsWithNumberOfChannels(), StandardApplicationCommandIDs::copy, and AudioProcessor::Bus::isLayoutSupported().
Referenced by getAUChannelInfo().
static int AudioUnitHelpers::getBusCount (const AudioProcessor * juceFilter, bool isInput) static
References AudioProcessor::getBusCount(), and jmin().
Referenced by AudioUnitHelpers::ChannelRemapper::alloc(), getAUChannelInfo(), getBusesLayout(), and setBusesLayout().
static bool AudioUnitHelpers::setBusesLayout (AudioProcessor * juceFilter, const AudioProcessor::BusesLayout & requestedLayouts) static
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), StandardApplicationCommandIDs::copy, AudioChannelSet::disabled(), getBusCount(), AudioProcessor::getBusCount(), AudioProcessor::BusesLayout::inputBuses, AudioProcessor::BusesLayout::outputBuses, and AudioProcessor::setBusesLayout().
static AudioProcessor::BusesLayout AudioUnitHelpers::getBusesLayout (const AudioProcessor * juceFilter) static
References getBusCount(), AudioProcessor::getBusCount(), AudioProcessor::getBusesLayout(), AudioProcessor::BusesLayout::inputBuses, AudioProcessor::BusesLayout::outputBuses, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeLast().
class AudioUnitPluginFormat
Implements a plugin format manager for AudioUnits.
Public Member Functions
AudioUnitPluginFormat ()
~AudioUnitPluginFormat ()
String getName () const override
Returns the format name.
void findAllTypesForFile (OwnedArray< PluginDescription > &, const String &fileOrIdentifier) override
This tries to create descriptions for all the plugin types available in a binary module file.
bool fileMightContainThisPluginType (const String &fileOrIdentifier) override
Should do a quick check to see if this file or directory might be a plugin of this format.
String getNameOfPluginFromIdentifier (const String &fileOrIdentifier) override
Returns a readable version of the name of the plugin that this identifier refers to.
bool pluginNeedsRescanning (const PluginDescription &) override
Returns true if this plugin's version or date has changed and it should be re-checked.
StringArray searchPathsForPlugins (const FileSearchPath &, bool recursive, bool) override
Searches a suggested set of directories for any plugins in this format.
bool doesPluginStillExist (const PluginDescription &) override
Checks whether this plugin could possibly be loaded.
FileSearchPath getDefaultLocationsToSearch () override
Returns the typical places to look for this kind of plugin.
bool canScanForPlugins () const override
Returns true if this format needs to run a scan to find its list of plugins.
Public Member Functions inherited from AudioPluginFormat
virtual ~AudioPluginFormat ()
Destructor.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize)
Tries to recreate a type from a previously generated PluginDescription.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize, String &errorMessage)
Same as above but with the possibility of returning an error message.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, InstantiationCompletionCallback *completionCallback)
Tries to recreate a type from a previously generated PluginDescription.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, std::function< void(AudioPluginInstance *, const String &)> completionCallback)
Additional Inherited Members
Protected Member Functions inherited from AudioPluginFormat
AudioPluginFormat () noexcept
Constructor & Destructor Documentation
AudioUnitPluginFormat::AudioUnitPluginFormat ()
AudioUnitPluginFormat::~AudioUnitPluginFormat ()
Member Function Documentation
String AudioUnitPluginFormat::getName () const override virtual
Returns the format name.
E.g. "VST", "AudioUnit", etc.
Implements AudioPluginFormat.
void AudioUnitPluginFormat::findAllTypesForFile (OwnedArray< PluginDescription > & results, const String & fileOrIdentifier) override virtual
This tries to create descriptions for all the plugin types available in a binary module file.
The file will be some kind of DLL or bundle.
Normally there will only be one type returned, but some plugins (e.g. VST shells) can use a single DLL to create a set of different plugin subtypes, so in that case, each subtype is returned as a separate object.
Implements AudioPluginFormat.
bool AudioUnitPluginFormat::fileMightContainThisPluginType (const String & fileOrIdentifier) override virtual
Should do a quick check to see if this file or directory might be a plugin of this format.
This is for searching for potential files, so it shouldn't actually try to load the plugin or do anything time-consuming.
Implements AudioPluginFormat.
String AudioUnitPluginFormat::getNameOfPluginFromIdentifier (const String & fileOrIdentifier) override virtual
Returns a readable version of the name of the plugin that this identifier refers to.
Implements AudioPluginFormat.
bool AudioUnitPluginFormat::pluginNeedsRescanning (const PluginDescription &) override virtual
Returns true if this plugin's version or date has changed and it should be re-checked.
Implements AudioPluginFormat.
StringArray AudioUnitPluginFormat::searchPathsForPlugins (const FileSearchPath & directoriesToSearch, bool recursive, bool allowPluginsWhichRequireAsynchronousInstantiation) override virtual
Searches a suggested set of directories for any plugins in this format.
The path might be ignored, e.g. by AUs, which are found by the OS rather than manually.
Parameters
directoriesToSearch This specifies which directories shall be searched for plug-ins.
recursive Should the search recursively traverse folders.
allowPluginsWhichRequireAsynchronousInstantiation If this is false then plug-ins which require asynchronous creation will be excluded.
Implements AudioPluginFormat.
bool AudioUnitPluginFormat::doesPluginStillExist (const PluginDescription &) override virtual
Checks whether this plugin could possibly be loaded.
It doesn't actually need to load it, just to check whether the file or component still exists.
Implements AudioPluginFormat.
FileSearchPath AudioUnitPluginFormat::getDefaultLocationsToSearch () override virtual
Returns the typical places to look for this kind of plugin.
Note that if this returns no paths, it means that the format doesn't search in files or folders, e.g. AudioUnits.
Implements AudioPluginFormat.
bool AudioUnitPluginFormat::canScanForPlugins () const override virtual
Returns true if this format needs to run a scan to find its list of plugins.
Implements AudioPluginFormat.
class LADSPAPluginFormat
Implements a plugin format manager for LADSPA plugins.
Public Member Functions
LADSPAPluginFormat ()
~LADSPAPluginFormat ()
String getName () const override
Returns the format name.
void findAllTypesForFile (OwnedArray< PluginDescription > &, const String &fileOrIdentifier) override
This tries to create descriptions for all the plugin types available in a binary module file.
bool fileMightContainThisPluginType (const String &fileOrIdentifier) override
Should do a quick check to see if this file or directory might be a plugin of this format.
String getNameOfPluginFromIdentifier (const String &fileOrIdentifier) override
Returns a readable version of the name of the plugin that this identifier refers to.
bool pluginNeedsRescanning (const PluginDescription &) override
Returns true if this plugin's version or date has changed and it should be re-checked.
StringArray searchPathsForPlugins (const FileSearchPath &, bool recursive, bool) override
Searches a suggested set of directories for any plugins in this format.
bool doesPluginStillExist (const PluginDescription &) override
Checks whether this plugin could possibly be loaded.
FileSearchPath getDefaultLocationsToSearch () override
Returns the typical places to look for this kind of plugin.
bool canScanForPlugins () const override
Returns true if this format needs to run a scan to find its list of plugins.
Public Member Functions inherited from AudioPluginFormat
virtual ~AudioPluginFormat ()
Destructor.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize)
Tries to recreate a type from a previously generated PluginDescription.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize, String &errorMessage)
Same as above but with the possibility of returning an error message.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, InstantiationCompletionCallback *completionCallback)
Tries to recreate a type from a previously generated PluginDescription.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, std::function< void(AudioPluginInstance *, const String &)> completionCallback)
Additional Inherited Members
Protected Member Functions inherited from AudioPluginFormat
AudioPluginFormat () noexcept
Constructor & Destructor Documentation
LADSPAPluginFormat::LADSPAPluginFormat ()
LADSPAPluginFormat::~LADSPAPluginFormat ()
Member Function Documentation
String LADSPAPluginFormat::getName () const override virtual
Returns the format name.
E.g. "VST", "AudioUnit", etc.
Implements AudioPluginFormat.
void LADSPAPluginFormat::findAllTypesForFile (OwnedArray< PluginDescription > & results, const String & fileOrIdentifier) override virtual
This tries to create descriptions for all the plugin types available in a binary module file.
The file will be some kind of DLL or bundle.
Normally there will only be one type returned, but some plugins (e.g. VST shells) can use a single DLL to create a set of different plugin subtypes, so in that case, each subtype is returned as a separate object.
Implements AudioPluginFormat.
bool LADSPAPluginFormat::fileMightContainThisPluginType (const String & fileOrIdentifier) override virtual
Should do a quick check to see if this file or directory might be a plugin of this format.
This is for searching for potential files, so it shouldn't actually try to load the plugin or do anything time-consuming.
Implements AudioPluginFormat.
String LADSPAPluginFormat::getNameOfPluginFromIdentifier (const String & fileOrIdentifier) override virtual
Returns a readable version of the name of the plugin that this identifier refers to.
Implements AudioPluginFormat.
bool LADSPAPluginFormat::pluginNeedsRescanning (const PluginDescription &) override virtual
Returns true if this plugin's version or date has changed and it should be re-checked.
Implements AudioPluginFormat.
StringArray LADSPAPluginFormat::searchPathsForPlugins (const FileSearchPath & directoriesToSearch, bool recursive, bool allowPluginsWhichRequireAsynchronousInstantiation) override virtual
Searches a suggested set of directories for any plugins in this format.
The path might be ignored, e.g. by AUs, which are found by the OS rather than manually.
Parameters
directoriesToSearch This specifies which directories shall be searched for plug-ins.
recursive Should the search recursively traverse folders.
allowPluginsWhichRequireAsynchronousInstantiation If this is false then plug-ins which require asynchronous creation will be excluded.
Implements AudioPluginFormat.
bool LADSPAPluginFormat::doesPluginStillExist (const PluginDescription &) override virtual
Checks whether this plugin could possibly be loaded.
It doesn't actually need to load it, just to check whether the file or component still exists.
Implements AudioPluginFormat.
FileSearchPath LADSPAPluginFormat::getDefaultLocationsToSearch () override virtual
Returns the typical places to look for this kind of plugin.
Note that if this returns no paths, it means that the format doesn't search in files or folders, e.g. AudioUnits.
Implements AudioPluginFormat.
bool LADSPAPluginFormat::canScanForPlugins () const override virtual
Returns true if this format needs to run a scan to find its list of plugins.
Implements AudioPluginFormat.
class ComSmartPtr
template<class ObjectType>
class ComSmartPtr< ObjectType >
Public Member Functions
ComSmartPtr () noexcept
ComSmartPtr (ObjectType *object, bool autoAddRef=true) noexcept
ComSmartPtr (const ComSmartPtr &other) noexcept
~ComSmartPtr ()
operator ObjectType * () const noexcept
ObjectType * get () const noexcept
ObjectType & operator* () const noexcept
ObjectType * operator-> () const noexcept
ComSmartPtr & operator= (const ComSmartPtr &other)
ComSmartPtr & operator= (ObjectType *const newObjectToTakePossessionOf)
bool operator== (ObjectType *const other) noexcept
bool operator!= (ObjectType *const other) noexcept
bool loadFrom (Steinberg::FUnknown *o)
bool loadFrom (Steinberg::IPluginFactory *factory, const Steinberg::TUID &uuid)
Constructor & Destructor Documentation
template<class ObjectType > ComSmartPtr< ObjectType >::ComSmartPtr () noexcept
template<class ObjectType > ComSmartPtr< ObjectType >::ComSmartPtr (ObjectType * object, bool autoAddRef = true) noexcept
template<class ObjectType > ComSmartPtr< ObjectType >::ComSmartPtr (const ComSmartPtr< ObjectType > & other) noexcept
template<class ObjectType > ComSmartPtr< ObjectType >::~ComSmartPtr ()
Member Function Documentation
template<class ObjectType > ComSmartPtr< ObjectType >::operator ObjectType * () const noexcept
template<class ObjectType > ObjectType* ComSmartPtr< ObjectType >::get () const noexcept
template<class ObjectType > ObjectType& ComSmartPtr< ObjectType >::operator* () const noexcept
template<class ObjectType > ObjectType* ComSmartPtr< ObjectType >::operator-> () const noexcept
template<class ObjectType > ComSmartPtr& ComSmartPtr< ObjectType >::operator= (const ComSmartPtr< ObjectType > & other)
template<class ObjectType > ComSmartPtr& ComSmartPtr< ObjectType >::operator= (ObjectType *const newObjectToTakePossessionOf)
template<class ObjectType > bool ComSmartPtr< ObjectType >::operator== (ObjectType *const other) noexcept
template<class ObjectType > bool ComSmartPtr< ObjectType >::operator!= (ObjectType *const other) noexcept
template<class ObjectType > bool ComSmartPtr< ObjectType >::loadFrom (Steinberg::FUnknown * o)
template<class ObjectType > bool ComSmartPtr< ObjectType >::loadFrom (Steinberg::IPluginFactory * factory, const Steinberg::TUID & uuid)
References jassert.
class MidiEventList
Inherits IEventList.
Public Member Functions
MidiEventList ()
virtual ~MidiEventList ()
JUCE_DECLARE_VST3_COM_REF_METHODS
JUCE_DECLARE_VST3_COM_QUERY_METHODS
void clear ()
Steinberg::int32 PLUGIN_API getEventCount () override
Steinberg::tresult PLUGIN_API getEvent (Steinberg::int32 index, Steinberg::Vst::Event &e) override
Steinberg::tresult PLUGIN_API addEvent (Steinberg::Vst::Event &e) override
Static Public Member Functions
static void toMidiBuffer (MidiBuffer &result, Steinberg::Vst::IEventList &eventList)
static void toEventList (Steinberg::Vst::IEventList &result, MidiBuffer &midiBuffer)
Constructor & Destructor Documentation
MidiEventList::MidiEventList ()
virtual MidiEventList::~MidiEventList () virtual
Member Function Documentation
JUCE_DECLARE_VST3_COM_REF_METHODS JUCE_DECLARE_VST3_COM_QUERY_METHODS void MidiEventList::clear ()
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick().
Steinberg::int32 PLUGIN_API MidiEventList::getEventCount () override
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Steinberg::tresult PLUGIN_API MidiEventList::getEvent (Steinberg::int32 index, Steinberg::Vst::Event & e) override
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isPositiveAndBelow(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Steinberg::tresult PLUGIN_API MidiEventList::addEvent (Steinberg::Vst::Event & e) override
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
static void MidiEventList::toMidiBuffer (MidiBuffer & result, Steinberg::Vst::IEventList & eventList) static
References MidiBuffer::addEvent(), MidiMessage::aftertouchChange(), MidiMessage::createSysExMessage(), MidiMessage::noteOff(), and MidiMessage::noteOn().
static void MidiEventList::toEventList (Steinberg::Vst::IEventList & result, MidiBuffer & midiBuffer) static
References MidiMessage::getAfterTouchValue(), MidiMessage::getChannel(), MidiBuffer::Iterator::getNextEvent(), MidiMessage::getNoteNumber(), MidiMessage::getSysExData(), MidiMessage::getSysExDataSize(), MidiMessage::getVelocity(), MidiMessage::isAftertouch(), MidiMessage::isNoteOff(), MidiMessage::isNoteOn(), MidiMessage::isSysEx(), and MidiMessage::noteOn().
struct VST3BufferExchange
template<typename FloatType>
struct VST3BufferExchange< FloatType >
Public Types
typedef Array< FloatType * > Bus
typedef Array< Bus > BusMap
Static Public Member Functions
static void assignRawPointer (Steinberg::Vst::AudioBusBuffers &vstBuffers, float **raw)
static void assignRawPointer (Steinberg::Vst::AudioBusBuffers &vstBuffers, double **raw)
static void associateBufferTo (Steinberg::Vst::AudioBusBuffers &vstBuffers, Bus &bus, AudioBuffer< FloatType > &buffer, int numChannels, int channelStartOffset, int sampleOffset=0)
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
static void mapArrangementToBuses (int &channelIndexOffset, int index, Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, const AudioChannelSet &arrangement, AudioBuffer< FloatType > &source)
static void mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, const Array< AudioChannelSet > &arrangements, AudioBuffer< FloatType > &source)
static void mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > &result, Steinberg::Vst::IAudioProcessor &processor, BusMap &busMapToUse, bool isInput, int numBuses, AudioBuffer< FloatType > &source)
Member Typedef Documentation
template<typename FloatType> typedef Array<FloatType*> VST3BufferExchange< FloatType >::Bus
template<typename FloatType> typedef Array<Bus> VST3BufferExchange< FloatType >::BusMap
Member Function Documentation
template<typename FloatType> static void VST3BufferExchange< FloatType >::assignRawPointer (Steinberg::Vst::AudioBusBuffers & vstBuffers, float ** raw) static
Referenced by VST3BufferExchange< float >::associateBufferTo().
template<typename FloatType> static void VST3BufferExchange< FloatType >::assignRawPointer (Steinberg::Vst::AudioBusBuffers & vstBuffers, double ** raw) static
template<typename FloatType> static void VST3BufferExchange< FloatType >::associateBufferTo (Steinberg::Vst::AudioBusBuffers & vstBuffers, Bus & bus, AudioBuffer< FloatType > & buffer, int numChannels, int channelStartOffset, int sampleOffset = 0) static
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
Warning
For speed, does not check the channel count and offsets according to the AudioSampleBuffer
Referenced by VST3BufferExchange< float >::mapArrangementToBuses().
template<typename FloatType> static void VST3BufferExchange< FloatType >::mapArrangementToBuses (int & channelIndexOffset, int index, Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, const AudioChannelSet & arrangement, AudioBuffer< FloatType > & source) static
Referenced by VST3BufferExchange< float >::mapBufferToBuses().
template<typename FloatType> static void VST3BufferExchange< FloatType >::mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, const Array< AudioChannelSet > & arrangements, AudioBuffer< FloatType > & source) static
template<typename FloatType> static void VST3BufferExchange< FloatType >::mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > & result, Steinberg::Vst::IAudioProcessor & processor, BusMap & busMapToUse, bool isInput, int numBuses, AudioBuffer< FloatType > & source) static
struct VST3FloatAndDoubleBusMapCompositeHelper
template<typename FloatType>
struct VST3FloatAndDoubleBusMapCompositeHelper< FloatType >
struct VST3FloatAndDoubleBusMapComposite
Public Member Functions
template<typename FloatType >
VST3BufferExchange< FloatType >
::BusMap & get ()
Public Attributes
VST3BufferExchange< float >::BusMap floatVersion
VST3BufferExchange< double >
::BusMap doubleVersion
Member Function Documentation
template<typename FloatType > VST3BufferExchange<FloatType>::BusMap& VST3FloatAndDoubleBusMapComposite::get ()
Member Data Documentation
VST3BufferExchange<float>::BusMap VST3FloatAndDoubleBusMapComposite::floatVersion
VST3BufferExchange<double>::BusMap VST3FloatAndDoubleBusMapComposite::doubleVersion
struct VST3FloatAndDoubleBusMapCompositeHelper< float >
template<>
struct VST3FloatAndDoubleBusMapCompositeHelper< float >
Static Public Member Functions
static VST3BufferExchange
< float >::BusMap & get (VST3FloatAndDoubleBusMapComposite &impl)
Member Function Documentation
static VST3BufferExchange<float>::BusMap& VST3FloatAndDoubleBusMapCompositeHelper< float >::get (VST3FloatAndDoubleBusMapComposite & impl) static
struct VST3FloatAndDoubleBusMapCompositeHelper< double >
template<>
struct VST3FloatAndDoubleBusMapCompositeHelper< double >
Static Public Member Functions
static VST3BufferExchange
< double >::BusMap & get (VST3FloatAndDoubleBusMapComposite &impl)
Member Function Documentation
static VST3BufferExchange<double>::BusMap& VST3FloatAndDoubleBusMapCompositeHelper< double >::get (VST3FloatAndDoubleBusMapComposite & impl) static
class VST3PluginFormat
Implements a plugin format for VST3s.
Public Member Functions
VST3PluginFormat ()
Constructor.
~VST3PluginFormat ()
Destructor.
String getName () const override
Returns the format name.
void findAllTypesForFile (OwnedArray< PluginDescription > &, const String &fileOrIdentifier) override
This tries to create descriptions for all the plugin types available in a binary module file.
bool fileMightContainThisPluginType (const String &fileOrIdentifier) override
Should do a quick check to see if this file or directory might be a plugin of this format.
String getNameOfPluginFromIdentifier (const String &fileOrIdentifier) override
Returns a readable version of the name of the plugin that this identifier refers to.
bool pluginNeedsRescanning (const PluginDescription &) override
Returns true if this plugin's version or date has changed and it should be re-checked.
StringArray searchPathsForPlugins (const FileSearchPath &, bool recursive, bool) override
Searches a suggested set of directories for any plugins in this format.
bool doesPluginStillExist (const PluginDescription &) override
Checks whether this plugin could possibly be loaded.
FileSearchPath getDefaultLocationsToSearch () override
Returns the typical places to look for this kind of plugin.
bool canScanForPlugins () const override
Returns true if this format needs to run a scan to find its list of plugins.
Public Member Functions inherited from AudioPluginFormat
virtual ~AudioPluginFormat ()
Destructor.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize)
Tries to recreate a type from a previously generated PluginDescription.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize, String &errorMessage)
Same as above but with the possibility of returning an error message.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, InstantiationCompletionCallback *completionCallback)
Tries to recreate a type from a previously generated PluginDescription.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, std::function< void(AudioPluginInstance *, const String &)> completionCallback)
Additional Inherited Members
Protected Member Functions inherited from AudioPluginFormat
AudioPluginFormat () noexcept
Constructor & Destructor Documentation
VST3PluginFormat::VST3PluginFormat ()
Constructor.
VST3PluginFormat::~VST3PluginFormat ()
Destructor.
Member Function Documentation
String VST3PluginFormat::getName () const override virtual
Returns the format name.
E.g. "VST", "AudioUnit", etc.
Implements AudioPluginFormat.
void VST3PluginFormat::findAllTypesForFile (OwnedArray< PluginDescription > & results, const String & fileOrIdentifier) override virtual
This tries to create descriptions for all the plugin types available in a binary module file.
The file will be some kind of DLL or bundle.
Normally there will only be one type returned, but some plugins (e.g. VST shells) can use a single DLL to create a set of different plugin subtypes, so in that case, each subtype is returned as a separate object.
Implements AudioPluginFormat.
bool VST3PluginFormat::fileMightContainThisPluginType (const String & fileOrIdentifier) override virtual
Should do a quick check to see if this file or directory might be a plugin of this format.
This is for searching for potential files, so it shouldn't actually try to load the plugin or do anything time-consuming.
Implements AudioPluginFormat.
String VST3PluginFormat::getNameOfPluginFromIdentifier (const String & fileOrIdentifier) override virtual
Returns a readable version of the name of the plugin that this identifier refers to.
Implements AudioPluginFormat.
bool VST3PluginFormat::pluginNeedsRescanning (const PluginDescription &) override virtual
Returns true if this plugin's version or date has changed and it should be re-checked.
Implements AudioPluginFormat.
StringArray VST3PluginFormat::searchPathsForPlugins (const FileSearchPath & directoriesToSearch, bool recursive, bool allowPluginsWhichRequireAsynchronousInstantiation) override virtual
Searches a suggested set of directories for any plugins in this format.
The path might be ignored, e.g. by AUs, which are found by the OS rather than manually.
Parameters
directoriesToSearch This specifies which directories shall be searched for plug-ins.
recursive Should the search recursively traverse folders.
allowPluginsWhichRequireAsynchronousInstantiation If this is false then plug-ins which require asynchronous creation will be excluded.
Implements AudioPluginFormat.
bool VST3PluginFormat::doesPluginStillExist (const PluginDescription &) override virtual
Checks whether this plugin could possibly be loaded.
It doesn't actually need to load it, just to check whether the file or component still exists.
Implements AudioPluginFormat.
FileSearchPath VST3PluginFormat::getDefaultLocationsToSearch () override virtual
Returns the typical places to look for this kind of plugin.
Note that if this returns no paths, it means that the format doesn't search in files or folders, e.g. AudioUnits.
Implements AudioPluginFormat.
bool VST3PluginFormat::canScanForPlugins () const override virtual
Returns true if this format needs to run a scan to find its list of plugins.
Implements AudioPluginFormat.
struct SpeakerMappings
Static Public Member Functions
static AudioChannelSet vstArrangementTypeToChannelSet (int32 arr, int fallbackNumChannels)
static AudioChannelSet vstArrangementTypeToChannelSet (const VstSpeakerConfiguration &arr)
static int32 channelSetToVstArrangementType (AudioChannelSet channels)
static const Mapping * getMappings () noexcept
static int32 getSpeakerType (AudioChannelSet::ChannelType type) noexcept
static AudioChannelSet::ChannelType getChannelType (int32 type) noexcept
Member Function Documentation
static AudioChannelSet SpeakerMappings::vstArrangementTypeToChannelSet (int32 arr, int fallbackNumChannels) static
References AudioChannelSet::addChannel(), AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create6point1Music(), AudioChannelSet::create7point0(), AudioChannelSet::create7point0SDDS(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1SDDS(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::discreteChannels(), getMappings(), AudioChannelSet::mono(), AudioChannelSet::quadraphonic(), AudioChannelSet::stereo(), SpeakerMappings::Mapping::vst2, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, and vstSpeakerConfigTypeMono.
Referenced by vstArrangementTypeToChannelSet().
static AudioChannelSet SpeakerMappings::vstArrangementTypeToChannelSet (const VstSpeakerConfiguration & arr) static
References VstSpeakerConfiguration::numberOfChannels, VstSpeakerConfiguration::type, and vstArrangementTypeToChannelSet().
static int32 SpeakerMappings::channelSetToVstArrangementType (AudioChannelSet channels) static
References AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create6point1Music(), AudioChannelSet::create7point0(), AudioChannelSet::create7point0SDDS(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1SDDS(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::getChannelTypes(), getMappings(), AudioChannelSet::mono(), AudioChannelSet::quadraphonic(), AudioChannelSet::stereo(), SpeakerMappings::Mapping::vst2, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeMono, and vstSpeakerConfigTypeUser.
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
static const Mapping* SpeakerMappings::getMappings () static noexcept
References AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, vstSpeakerConfigTypeCLfe, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLcRc, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfe, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsCsSlSr, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsLcRcCs, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLfeLsRsTflTfcTfrTrlTrrLfe2, vstSpeakerConfigTypeLRCLfeS, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsCsSlSr, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsLcRcCs, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRs, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLfeS, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeLsRs, vstSpeakerConfigTypeMono, and vstSpeakerConfigTypeSlSr.
Referenced by channelSetToVstArrangementType(), and vstArrangementTypeToChannelSet().
static int32 SpeakerMappings::getSpeakerType (AudioChannelSet::ChannelType type) static noexcept
References AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLFE2, vstIndividualSpeakerTypeRight, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeRightSurround, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontLeft, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopRearCentre, vstIndividualSpeakerTypeTopRearLeft, and vstIndividualSpeakerTypeTopRearRight.
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
static AudioChannelSet::ChannelType SpeakerMappings::getChannelType (int32 type) static noexcept
References AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLFE2, vstIndividualSpeakerTypeRight, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeRightSurround, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontLeft, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopRearCentre, vstIndividualSpeakerTypeTopRearLeft, and vstIndividualSpeakerTypeTopRearRight.
struct VstEffectInterface
Public Member Functions
pointer_sized_int (VSTINTERFACECALL *dispatchFunction)(VstEffectInterface *
void (VSTINTERFACECALL *processAudioFunction)(VstEffectInterface *
void (VSTINTERFACECALL *setParameterValueFunction)(VstEffectInterface *
float (VSTINTERFACECALL *getParameterValueFunction)(VstEffectInterface *
void (VSTINTERFACECALL *processAudioInplaceFunction)(VstEffectInterface *
void (VSTINTERFACECALL *processDoubleAudioInplaceFunction)(VstEffectInterface *
Public Attributes
int32 interfaceIdentifier
int32 op
int32 int32 index
int32 int32 pointer_sized_int value
int32 int32 pointer_sized_int
void * ptr
int32 int32 pointer_sized_int
void float opt
float ** inputs
float float ** outputs
float float int32 numSamples
int32 parameterIndex
int32 float value
int32 numPrograms
int32 numParameters
int32 numInputChannels
int32 numOutputChannels
int32 flags
pointer_sized_int hostSpace1
pointer_sized_int hostSpace2
int32 latency
int32 deprecated1
int32 deprecated2
float deprecated3
void * effectPointer
void * userPointer
int32 plugInIdentifier
int32 plugInVersion
double ** inputs
double double ** outputs
double double int32 numSamples
char emptySpace [56]
Member Function Documentation
VstEffectInterface::pointer_sized_int (VSTINTERFACECALL * dispatchFunction)
VstEffectInterface::void (VSTINTERFACECALL * processAudioFunction)
VstEffectInterface::void (VSTINTERFACECALL * setParameterValueFunction)
VstEffectInterface::float (VSTINTERFACECALL * getParameterValueFunction)
VstEffectInterface::void (VSTINTERFACECALL * processAudioInplaceFunction)
VstEffectInterface::void (VSTINTERFACECALL * processDoubleAudioInplaceFunction)
Member Data Documentation
int32 VstEffectInterface::interfaceIdentifier
int32 VstEffectInterface::op
int32 int32 VstEffectInterface::index
int32 int32 pointer_sized_int VstEffectInterface::value
int32 int32 pointer_sized_int void* VstEffectInterface::ptr
int32 int32 pointer_sized_int void float VstEffectInterface::opt
float ** VstEffectInterface::inputs
float float ** VstEffectInterface::outputs
float float int32 VstEffectInterface::numSamples
int32 VstEffectInterface::parameterIndex
int32 float VstEffectInterface::value
int32 VstEffectInterface::numPrograms
int32 VstEffectInterface::numParameters
int32 VstEffectInterface::numInputChannels
int32 VstEffectInterface::numOutputChannels
int32 VstEffectInterface::flags
pointer_sized_int VstEffectInterface::hostSpace1
pointer_sized_int VstEffectInterface::hostSpace2
int32 VstEffectInterface::latency
int32 VstEffectInterface::deprecated1
int32 VstEffectInterface::deprecated2
float VstEffectInterface::deprecated3
void* VstEffectInterface::effectPointer
void* VstEffectInterface::userPointer
int32 VstEffectInterface::plugInIdentifier
int32 VstEffectInterface::plugInVersion
double** VstEffectInterface::inputs
double double** VstEffectInterface::outputs
double double int32 VstEffectInterface::numSamples
char VstEffectInterface::emptySpace[56]
struct VstEditorBounds
Public Attributes
int16 upper
int16 leftmost
int16 lower
int16 rightmost
Member Data Documentation
int16 VstEditorBounds::upper
int16 VstEditorBounds::leftmost
int16 VstEditorBounds::lower
int16 VstEditorBounds::rightmost
struct VstPinInfo
Public Attributes
char text [vstMaxParameterOrPinLabelLength]
int32 flags
int32 configurationType
char shortText [vstMaxParameterOrPinShortLabelLength]
char unused [48]
Member Data Documentation
char VstPinInfo::text[vstMaxParameterOrPinLabelLength]
int32 VstPinInfo::flags
int32 VstPinInfo::configurationType
char VstPinInfo::shortText[vstMaxParameterOrPinShortLabelLength]
char VstPinInfo::unused[48]
struct VstEvent
Public Attributes
int32 type
int32 size
int32 sampleOffset
int32 flags
char content [16]
Member Data Documentation
int32 VstEvent::type
int32 VstEvent::size
int32 VstEvent::sampleOffset
int32 VstEvent::flags
char VstEvent::content[16]
struct VstEventBlock
Public Attributes
int32 numberOfEvents
pointer_sized_int future
VstEvent * events [2]
Member Data Documentation
int32 VstEventBlock::numberOfEvents
pointer_sized_int VstEventBlock::future
VstEvent* VstEventBlock::events[2]
struct VstMidiEvent
Public Attributes
int32 type
int32 size
int32 sampleOffset
int32 flags
int32 noteSampleLength
int32 noteSampleOffset
char midiData [4]
char tuning
char noteVelocityOff
char future1
char future2
Member Data Documentation
int32 VstMidiEvent::type
int32 VstMidiEvent::size
int32 VstMidiEvent::sampleOffset
int32 VstMidiEvent::flags
int32 VstMidiEvent::noteSampleLength
int32 VstMidiEvent::noteSampleOffset
char VstMidiEvent::midiData[4]
char VstMidiEvent::tuning
char VstMidiEvent::noteVelocityOff
char VstMidiEvent::future1
char VstMidiEvent::future2
struct VstSysExEvent
Public Attributes
int32 type
int32 size
int32 offsetSamples
int32 flags
int32 sysExDumpSize
pointer_sized_int future1
char * sysExDump
pointer_sized_int future2
Member Data Documentation
int32 VstSysExEvent::type
int32 VstSysExEvent::size
int32 VstSysExEvent::offsetSamples
int32 VstSysExEvent::flags
int32 VstSysExEvent::sysExDumpSize
pointer_sized_int VstSysExEvent::future1
char* VstSysExEvent::sysExDump
pointer_sized_int VstSysExEvent::future2
struct VstTimingInformation
Public Attributes
double samplePosition
double sampleRate
double systemTimeNanoseconds
double musicalPosition
double tempoBPM
double lastBarPosition
double loopStartPosition
double loopEndPosition
int32 timeSignatureNumerator
int32 timeSignatureDenominator
int32 smpteOffset
int32 smpteRate
int32 samplesToNearestClock
int32 flags
Member Data Documentation
double VstTimingInformation::samplePosition
double VstTimingInformation::sampleRate
double VstTimingInformation::systemTimeNanoseconds
double VstTimingInformation::musicalPosition
double VstTimingInformation::tempoBPM
double VstTimingInformation::lastBarPosition
double VstTimingInformation::loopStartPosition
double VstTimingInformation::loopEndPosition
int32 VstTimingInformation::timeSignatureNumerator
int32 VstTimingInformation::timeSignatureDenominator
int32 VstTimingInformation::smpteOffset
int32 VstTimingInformation::smpteRate
int32 VstTimingInformation::samplesToNearestClock
int32 VstTimingInformation::flags
struct VstIndividualSpeakerInfo
Public Attributes
float azimuthalAngle
float elevationAngle
float radius
float reserved
char label [vstMaxNameLength]
int32 type
char unused [28]
Member Data Documentation
float VstIndividualSpeakerInfo::azimuthalAngle
float VstIndividualSpeakerInfo::elevationAngle
float VstIndividualSpeakerInfo::radius
float VstIndividualSpeakerInfo::reserved
char VstIndividualSpeakerInfo::label[vstMaxNameLength]
int32 VstIndividualSpeakerInfo::type
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
char VstIndividualSpeakerInfo::unused[28]
struct VstSpeakerConfiguration
Public Attributes
int32 type
int32 numberOfChannels
VstIndividualSpeakerInfo speakers [8]
Member Data Documentation
int32 VstSpeakerConfiguration::type
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::operator=(), SpeakerMappings::vstArrangementTypeToChannelSet(), and SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
int32 VstSpeakerConfiguration::numberOfChannels
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::operator=(), SpeakerMappings::vstArrangementTypeToChannelSet(), and SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
VstIndividualSpeakerInfo VstSpeakerConfiguration::speakers[8]
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::operator=(), and SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
struct vst2FxBank
Public Attributes
int32 magic1
int32 size
int32 magic2
int32 version1
int32 fxID
int32 version2
int32 elements
int32 current
char shouldBeZero [124]
int32 chunkSize
char chunk [1]
Member Data Documentation
int32 vst2FxBank::magic1
int32 vst2FxBank::size
int32 vst2FxBank::magic2
int32 vst2FxBank::version1
int32 vst2FxBank::fxID
int32 vst2FxBank::version2
int32 vst2FxBank::elements
int32 vst2FxBank::current
char vst2FxBank::shouldBeZero[124]
int32 vst2FxBank::chunkSize
char vst2FxBank::chunk[1]
class VSTPluginFormat
Implements a plugin format manager for VSTs.
Public Member Functions
VSTPluginFormat ()
~VSTPluginFormat ()
String getName () const override
Returns the format name.
void findAllTypesForFile (OwnedArray< PluginDescription > &, const String &fileOrIdentifier) override
This tries to create descriptions for all the plugin types available in a binary module file.
bool fileMightContainThisPluginType (const String &fileOrIdentifier) override
Should do a quick check to see if this file or directory might be a plugin of this format.
String getNameOfPluginFromIdentifier (const String &fileOrIdentifier) override
Returns a readable version of the name of the plugin that this identifier refers to.
bool pluginNeedsRescanning (const PluginDescription &) override
Returns true if this plugin's version or date has changed and it should be re-checked.
StringArray searchPathsForPlugins (const FileSearchPath &, bool recursive, bool) override
Searches a suggested set of directories for any plugins in this format.
bool doesPluginStillExist (const PluginDescription &) override
Checks whether this plugin could possibly be loaded.
FileSearchPath getDefaultLocationsToSearch () override
Returns the typical places to look for this kind of plugin.
bool canScanForPlugins () const override
Returns true if this format needs to run a scan to find its list of plugins.
virtual void aboutToScanVSTShellPlugin (const PluginDescription &)
Can be overridden to receive a callback when each member of a shell plugin is about to be tested during a call to findAllTypesForFile().
Public Member Functions inherited from AudioPluginFormat
virtual ~AudioPluginFormat ()
Destructor.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize)
Tries to recreate a type from a previously generated PluginDescription.
AudioPluginInstance * createInstanceFromDescription (const PluginDescription &, double initialSampleRate, int initialBufferSize, String &errorMessage)
Same as above but with the possibility of returning an error message.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, InstantiationCompletionCallback *completionCallback)
Tries to recreate a type from a previously generated PluginDescription.
void createPluginInstanceAsync (const PluginDescription &description, double initialSampleRate, int initialBufferSize, std::function< void(AudioPluginInstance *, const String &)> completionCallback)
Static Public Member Functions
static const XmlElement * getVSTXML (AudioPluginInstance *plugin)
Attempts to retrieve the VSTXML data from a plugin.
static bool loadFromFXBFile (AudioPluginInstance *plugin, const void *data, size_t dataSize)
Attempts to reload a VST plugin's state from some FXB or FXP data.
static bool saveToFXBFile (AudioPluginInstance *plugin, MemoryBlock &result, bool asFXB)
Attempts to save a VST's state to some FXP or FXB data.
static bool getChunkData (AudioPluginInstance *plugin, MemoryBlock &result, bool isPreset)
Attempts to get a VST's state as a chunk of memory.
static bool setChunkData (AudioPluginInstance *plugin, const void *data, int size, bool isPreset)
Attempts to set a VST's state from a chunk of memory.
static AudioPluginInstance * createCustomVSTFromMainCall (void *entryPointFunction, double initialSampleRate, int initialBufferSize)
Given a suitable function pointer to a VSTPluginMain function, this will attempt to instantiate and return a plugin for it.
static void setExtraFunctions (AudioPluginInstance *plugin, ExtraFunctions *functions)
Provides an ExtraFunctions callback object for a plugin to use.
static pointer_sized_int
JUCE_CALLTYPE dispatcher (AudioPluginInstance *, int32, int32, pointer_sized_int, void *, float)
This simply calls directly to the VST's AEffect::dispatcher() function.
static AudioPluginInstance * getPluginInstanceFromVstEffectInterface (void *aEffect)
Given a VstEffectInterface* (aka vst::AEffect*), this will return the juce AudioPluginInstance that is being used to wrap it.
Additional Inherited Members
Protected Member Functions inherited from AudioPluginFormat
AudioPluginFormat () noexcept
Constructor & Destructor Documentation
VSTPluginFormat::VSTPluginFormat ()
VSTPluginFormat::~VSTPluginFormat ()
Member Function Documentation
static const XmlElement* VSTPluginFormat::getVSTXML (AudioPluginInstance * plugin) static
Attempts to retrieve the VSTXML data from a plugin.
Will return nullptr if the plugin isn't a VST, or if it doesn't have any VSTXML.
static bool VSTPluginFormat::loadFromFXBFile (AudioPluginInstance * plugin, const void * data, size_t dataSize) static
Attempts to reload a VST plugin's state from some FXB or FXP data.
static bool VSTPluginFormat::saveToFXBFile (AudioPluginInstance * plugin, MemoryBlock & result, bool asFXB) static
Attempts to save a VST's state to some FXP or FXB data.
static bool VSTPluginFormat::getChunkData (AudioPluginInstance * plugin, MemoryBlock & result, bool isPreset) static
Attempts to get a VST's state as a chunk of memory.
static bool VSTPluginFormat::setChunkData (AudioPluginInstance * plugin, const void * data, int size, bool isPreset) static
Attempts to set a VST's state from a chunk of memory.
static AudioPluginInstance* VSTPluginFormat::createCustomVSTFromMainCall (void * entryPointFunction, double initialSampleRate, int initialBufferSize) static
Given a suitable function pointer to a VSTPluginMain function, this will attempt to instantiate and return a plugin for it.
static void VSTPluginFormat::setExtraFunctions (AudioPluginInstance * plugin, ExtraFunctions * functions) static
Provides an ExtraFunctions callback object for a plugin to use.
The plugin will take ownership of the object and will delete it automatically.
static pointer_sized_int JUCE_CALLTYPE VSTPluginFormat::dispatcher (AudioPluginInstance * , int32 , int32 , pointer_sized_int , void * , float) static
This simply calls directly to the VST's AEffect::dispatcher() function.
static AudioPluginInstance* VSTPluginFormat::getPluginInstanceFromVstEffectInterface (void * aEffect) static
Given a VstEffectInterface* (aka vst::AEffect*), this will return the juce AudioPluginInstance that is being used to wrap it.
String VSTPluginFormat::getName () const override virtual
Returns the format name.
E.g. "VST", "AudioUnit", etc.
Implements AudioPluginFormat.
void VSTPluginFormat::findAllTypesForFile (OwnedArray< PluginDescription > & results, const String & fileOrIdentifier) override virtual
This tries to create descriptions for all the plugin types available in a binary module file.
The file will be some kind of DLL or bundle.
Normally there will only be one type returned, but some plugins (e.g. VST shells) can use a single DLL to create a set of different plugin subtypes, so in that case, each subtype is returned as a separate object.
Implements AudioPluginFormat.
bool VSTPluginFormat::fileMightContainThisPluginType (const String & fileOrIdentifier) override virtual
Should do a quick check to see if this file or directory might be a plugin of this format.
This is for searching for potential files, so it shouldn't actually try to load the plugin or do anything time-consuming.
Implements AudioPluginFormat.
String VSTPluginFormat::getNameOfPluginFromIdentifier (const String & fileOrIdentifier) override virtual
Returns a readable version of the name of the plugin that this identifier refers to.
Implements AudioPluginFormat.
bool VSTPluginFormat::pluginNeedsRescanning (const PluginDescription &) override virtual
Returns true if this plugin's version or date has changed and it should be re-checked.
Implements AudioPluginFormat.
StringArray VSTPluginFormat::searchPathsForPlugins (const FileSearchPath & directoriesToSearch, bool recursive, bool allowPluginsWhichRequireAsynchronousInstantiation) override virtual
Searches a suggested set of directories for any plugins in this format.
The path might be ignored, e.g. by AUs, which are found by the OS rather than manually.
Parameters
directoriesToSearch This specifies which directories shall be searched for plug-ins.
recursive Should the search recursively traverse folders.
allowPluginsWhichRequireAsynchronousInstantiation If this is false then plug-ins which require asynchronous creation will be excluded.
Implements AudioPluginFormat.
bool VSTPluginFormat::doesPluginStillExist (const PluginDescription &) override virtual
Checks whether this plugin could possibly be loaded.
It doesn't actually need to load it, just to check whether the file or component still exists.
Implements AudioPluginFormat.
FileSearchPath VSTPluginFormat::getDefaultLocationsToSearch () override virtual
Returns the typical places to look for this kind of plugin.
Note that if this returns no paths, it means that the format doesn't search in files or folders, e.g. AudioUnits.
Implements AudioPluginFormat.
bool VSTPluginFormat::canScanForPlugins () const override virtual
Returns true if this format needs to run a scan to find its list of plugins.
Implements AudioPluginFormat.
virtual void VSTPluginFormat::aboutToScanVSTShellPlugin (const PluginDescription &) virtual
Can be overridden to receive a callback when each member of a shell plugin is about to be tested during a call to findAllTypesForFile().
Only the name and uid members of the PluginDescription are guaranteed to be valid when this is called.
Macro Definition Documentation
#define JUCE_STATE_DICTIONARY_KEY "jucePluginState"
#define JUCE_DECLARE_VST3_COM_REF_METHODS
Value:
Steinberg::uint32 PLUGIN_API addRef() override   { return (Steinberg::uint32) ++refCount; } \
    Steinberg::uint32 PLUGIN_API release() override  { const int r = --refCount; if (r == 0) delete this; return (Steinberg::uint32) r; }
#define JUCE_DECLARE_VST3_COM_QUERY_METHODS
Value:
Steinberg::tresult PLUGIN_API queryInterface (const Steinberg::TUID, void** obj) override \
    { \
        jassertfalse; \
        *obj = nullptr; \
        return Steinberg::kNotImplemented; \
    }
#define TEST_FOR_AND_RETURN_IF_VALID (iidToTest, ClassType)
Value:
if (doUIDsMatch (iidToTest, ClassType::iid)) \
    { \
        addRef(); \
        *obj = dynamic_cast<ClassType*> (this); \
        return Steinberg::kResultOk; \
    }
#define TEST_FOR_COMMON_BASE_AND_RETURN_IF_VALID (iidToTest, CommonClassType, SourceClassType)
Value:
if (doUIDsMatch (iidToTest, CommonClassType::iid)) \
    { \
        addRef(); \
        *obj = (CommonClassType*) static_cast<SourceClassType*> (this); \
        return Steinberg::kResultOk; \
    }
#define DEVELOPMENT 0
#define JUCE_VSTINTERFACE_H_INCLUDED
#define VSTINTERFACECALL
#define JUCE_MULTICHAR_CONSTANT (a, b, c, d) (d | (((uint32) c) << 8) | (((uint32) b) << 16) | (((uint32) a) << 24))
Typedef Documentation
typedef int32 op
typedef int32 int32 index
typedef int32 int32 pointer_sized_int value
typedef int32 int32 pointer_sized_int void* ptr
typedef int32 int32 pointer_sized_int void float opt
Enumeration Type Documentation
anonymous enum
Enumerator
kAudioUnitProperty_SupportsMPE
Custom AudioUnit property used to indicate MPE support.
enum VstEffectInterfaceFlags
Enumerator
vstEffectFlagHasEditor
vstEffectFlagInplaceAudio
vstEffectFlagDataInChunks
vstEffectFlagIsSynth
vstEffectFlagInplaceDoubleAudio
enum VstHostToPlugInOpcodes
Enumerator
plugInOpcodeOpen
plugInOpcodeClose
plugInOpcodeSetCurrentProgram
plugInOpcodeGetCurrentProgram
plugInOpcodeSetCurrentProgramName
plugInOpcodeGetCurrentProgramName
plugInOpcodeGetParameterLabel
plugInOpcodeGetParameterText
plugInOpcodeGetParameterName
plugInOpcodeSetSampleRate
plugInOpcodeSetBlockSize
plugInOpcodeResumeSuspend
plugInOpcodeGetEditorBounds
plugInOpcodeOpenEditor
plugInOpcodeCloseEditor
plugInOpcodeDrawEditor
plugInOpcodeGetMouse
plugInOpcodeEditorIdle
plugInOpcodeeffEditorTop
plugInOpcodeSleepEditor
plugInOpcodeIdentify
plugInOpcodeGetData
plugInOpcodeSetData
plugInOpcodePreAudioProcessingEvents
plugInOpcodeIsParameterAutomatable
plugInOpcodeParameterValueForText
plugInOpcodeGetProgramName
plugInOpcodeConnectInput
plugInOpcodeConnectOutput
plugInOpcodeGetInputPinProperties
plugInOpcodeGetOutputPinProperties
plugInOpcodeGetPlugInCategory
plugInOpcodeSetSpeakerConfiguration
plugInOpcodeSetBypass
plugInOpcodeGetPlugInName
plugInOpcodeGetManufacturerName
plugInOpcodeGetManufacturerProductName
plugInOpcodeGetManufacturerVersion
plugInOpcodeManufacturerSpecific
plugInOpcodeCanPlugInDo
plugInOpcodeGetTailSize
plugInOpcodeIdle
plugInOpcodeKeyboardFocusRequired
plugInOpcodeGetVstInterfaceVersion
plugInOpcodeGetCurrentMidiProgram
plugInOpcodeGetSpeakerArrangement
plugInOpcodeNextPlugInUniqueID
plugInOpcodeStartProcess
plugInOpcodeStopProcess
plugInOpcodeSetNumberOfSamplesToProcess
plugInOpcodeSetSampleFloatType
pluginOpcodeGetNumMidiInputChannels
pluginOpcodeGetNumMidiOutputChannels
plugInOpcodeMaximum
enum VstPlugInToHostOpcodes
Enumerator
hostOpcodeParameterChanged
hostOpcodeVstVersion
hostOpcodeCurrentId
hostOpcodeIdle
hostOpcodePinConnected
hostOpcodePlugInWantsMidi
hostOpcodeGetTimingInfo
hostOpcodePreAudioProcessingEvents
hostOpcodeSetTime
hostOpcodeTempoAt
hostOpcodeGetNumberOfAutomatableParameters
hostOpcodeGetParameterInterval
hostOpcodeIOModified
hostOpcodeNeedsIdle
hostOpcodeWindowSize
hostOpcodeGetSampleRate
hostOpcodeGetBlockSize
hostOpcodeGetInputLatency
hostOpcodeGetOutputLatency
hostOpcodeGetPreviousPlugIn
hostOpcodeGetNextPlugIn
hostOpcodeWillReplace
hostOpcodeGetCurrentAudioProcessingLevel
hostOpcodeGetAutomationState
hostOpcodeOfflineStart
hostOpcodeOfflineReadSource
hostOpcodeOfflineWrite
hostOpcodeOfflineGetCurrentPass
hostOpcodeOfflineGetCurrentMetaPass
hostOpcodeSetOutputSampleRate
hostOpcodeGetOutputSpeakerConfiguration
hostOpcodeGetManufacturerName
hostOpcodeGetProductName
hostOpcodeGetManufacturerVersion
hostOpcodeManufacturerSpecific
hostOpcodeSetIcon
hostOpcodeCanHostDo
hostOpcodeGetLanguage
hostOpcodeOpenEditorWindow
hostOpcodeCloseEditorWindow
hostOpcodeGetDirectory
hostOpcodeUpdateView
hostOpcodeParameterChangeGestureBegin
hostOpcodeParameterChangeGestureEnd
enum VstProcessingSampleType
Enumerator
vstProcessingSampleTypeFloat
vstProcessingSampleTypeDouble
enum VstPlugInCategory
Enumerator
kPlugCategUnknown
kPlugCategEffect
kPlugCategSynth
kPlugCategAnalysis
kPlugCategMastering
kPlugCategSpacializer
kPlugCategRoomFx
kPlugSurroundFx
kPlugCategRestoration
kPlugCategOfflineProcess
kPlugCategShell
kPlugCategGenerator
enum VstMaxStringLengths
Enumerator
vstMaxNameLength
vstMaxParameterOrPinLabelLength
vstMaxParameterOrPinShortLabelLength
vstMaxCategoryLength
vstMaxManufacturerStringLength
vstMaxPlugInNameStringLength
enum VstPinInfoFlags
Enumerator
vstPinInfoFlagIsActive
vstPinInfoFlagIsStereo
vstPinInfoFlagValid
enum VstEventTypes
Enumerator
vstMidiEventType
vstSysExEventType
enum VstMidiEventFlags
Enumerator
vstMidiEventIsRealtime
enum VstTimingInformationFlags
Enumerator
vstTimingInfoFlagTransportChanged
vstTimingInfoFlagCurrentlyPlaying
vstTimingInfoFlagLoopActive
vstTimingInfoFlagCurrentlyRecording
vstTimingInfoFlagAutomationWriteModeActive
vstTimingInfoFlagAutomationReadModeActive
vstTimingInfoFlagNanosecondsValid
vstTimingInfoFlagMusicalPositionValid
vstTimingInfoFlagTempoValid
vstTimingInfoFlagLastBarPositionValid
vstTimingInfoFlagLoopPositionValid
vstTimingInfoFlagTimeSignatureValid
vstTimingInfoFlagSmpteValid
vstTimingInfoFlagNearestClockValid
enum VstSmpteRates
Enumerator
vstSmpteRateFps24
vstSmpteRateFps25
vstSmpteRateFps2997
vstSmpteRateFps30
vstSmpteRateFps2997drop
vstSmpteRateFps30drop
vstSmpteRate16mmFilm
vstSmpteRate35mmFilm
vstSmpteRateFps239
vstSmpteRateFps249
vstSmpteRateFps599
vstSmpteRateFps60
enum VstIndividualSpeakerType
Enumerator
vstIndividualSpeakerTypeUndefined
vstIndividualSpeakerTypeMono
vstIndividualSpeakerTypeLeft
vstIndividualSpeakerTypeRight
vstIndividualSpeakerTypeCentre
vstIndividualSpeakerTypeLFE
vstIndividualSpeakerTypeLeftSurround
vstIndividualSpeakerTypeRightSurround
vstIndividualSpeakerTypeLeftCentre
vstIndividualSpeakerTypeRightCentre
vstIndividualSpeakerTypeSurround
vstIndividualSpeakerTypeCentreSurround
vstIndividualSpeakerTypeLeftRearSurround
vstIndividualSpeakerTypeRightRearSurround
vstIndividualSpeakerTypeTopMiddle
vstIndividualSpeakerTypeTopFrontLeft
vstIndividualSpeakerTypeTopFrontCentre
vstIndividualSpeakerTypeTopFrontRight
vstIndividualSpeakerTypeTopRearLeft
vstIndividualSpeakerTypeTopRearCentre
vstIndividualSpeakerTypeTopRearRight
vstIndividualSpeakerTypeLFE2
enum VstSpeakerConfigurationType
Enumerator
vstSpeakerConfigTypeUser
vstSpeakerConfigTypeEmpty
vstSpeakerConfigTypeMono
vstSpeakerConfigTypeLR
vstSpeakerConfigTypeLsRs
vstSpeakerConfigTypeLcRc
vstSpeakerConfigTypeSlSr
vstSpeakerConfigTypeCLfe
vstSpeakerConfigTypeLRC
vstSpeakerConfigTypeLRS
vstSpeakerConfigTypeLRCLfe
vstSpeakerConfigTypeLRLfeS
vstSpeakerConfigTypeLRCS
vstSpeakerConfigTypeLRLsRs
vstSpeakerConfigTypeLRCLfeS
vstSpeakerConfigTypeLRLfeLsRs
vstSpeakerConfigTypeLRCLsRs
vstSpeakerConfigTypeLRCLfeLsRs
vstSpeakerConfigTypeLRCLsRsCs
vstSpeakerConfigTypeLRLsRsSlSr
vstSpeakerConfigTypeLRCLfeLsRsCs
vstSpeakerConfigTypeLRLfeLsRsSlSr
vstSpeakerConfigTypeLRCLsRsLcRc
vstSpeakerConfigTypeLRCLsRsSlSr
vstSpeakerConfigTypeLRCLfeLsRsLcRc
vstSpeakerConfigTypeLRCLfeLsRsSlSr
vstSpeakerConfigTypeLRCLsRsLcRcCs
vstSpeakerConfigTypeLRCLsRsCsSlSr
vstSpeakerConfigTypeLRCLfeLsRsLcRcCs
vstSpeakerConfigTypeLRCLfeLsRsCsSlSr
vstSpeakerConfigTypeLRCLfeLsRsTflTfcTfrTrlTrrLfe2
enum PresonusExtensionConstants
Enumerator
presonusVendorID
presonusSetContentScaleFactor
Function Documentation
juce::String toString (const Steinberg::char8 * string) noexcept
Referenced by toString().
juce::String toString (const Steinberg::char16 * string) noexcept
juce::String toString (const Steinberg::UString128 & string) noexcept
References toString().
juce::String toString (const Steinberg::UString256 & string) noexcept
References toString().
void toString128 (Steinberg::Vst::String128 result, const char * source)
void toString128 (Steinberg::Vst::String128 result, const juce::String & source)
Steinberg::Vst::TChar* toString (const juce::String & source) noexcept
typedef pointer_sized_int (VSTINTERFACECALL * VstHostCallback)
Variable Documentation
const int32 juceVstInterfaceVersion = 2400
const int32 juceVstInterfaceIdentifier = 0x56737450