JUCE: buffers
buffers
juce_audio_basics
Classes
class AudioChannelSet
Represents a set of audio channel types.
class AudioData
This class a container which holds all the classes pertaining to the AudioData::Pointer audio sample format class.
class AudioDataConverters
A set of routines to convert buffers of 32-bit floating point data to and from various integer formats.
class AudioBuffer< Type >
A multi-channel buffer of floating point audio samples.
class FloatVectorOperations
A collection of simple vector operations on arrays of floats, accelerated with SIMD instructions where possible.
Macros
#define JUCE_SNAP_TO_ZERO(n)
Typedefs
typedef AudioBuffer< float > AudioSampleBuffer
A multi-channel buffer of 32-bit floating point audio samples.
Detailed Description
Class Documentation
class AudioChannelSet
Represents a set of audio channel types.
For example, you might have a set of left + right channels, which is a stereo channel set. It is a collection of values from the AudioChannelSet::ChannelType enum, where each type may only occur once within the set.
The documentation below lists which AudioChannelSet corresponds to which native layouts used by AAX, VST2/VST3 and CoreAudio/AU. The layout tags in CoreAudio are particularly confusing. For example, the layout which is labeled as "7.1 SDDS" in Logic Pro, corresponds to CoreAudio/AU's kAudioChannelLayoutTag_DTS_7_0 tag, whereas AAX's DTS 7.1 Layout corresponds to CoreAudio/AU's kAudioChannelLayoutTag_MPEG_7_1_A format, etc. Please do not use the CoreAudio tag as an indication to the actual layout of the speakers.
See Also
Bus
Public Types
enum ChannelType {
unknown = 0, left = 1, right = 2, centre = 3,
LFE = 4, leftSurround = 5, rightSurround = 6, leftCentre = 7,
rightCentre = 8, centreSurround = 9, surround = centreSurround, leftSurroundSide = 10,
rightSurroundSide = 11, topMiddle = 12, topFrontLeft = 13, topFrontCentre = 14,
topFrontRight = 15, topRearLeft = 16, topRearCentre = 17, topRearRight = 18,
LFE2 = 19, leftSurroundRear = 20, rightSurroundRear = 21, wideLeft = 22,
wideRight = 23, ambisonicW = 24, ambisonicX = 25, ambisonicY = 26,
ambisonicZ = 27, discreteChannel0 = 64
}
Represents different audio channel types.
enum { maxChannelsOfNamedLayout = 8 }
Public Member Functions
AudioChannelSet () noexcept
Creates an empty channel set.
void addChannel (ChannelType newChannelType)
Adds a channel to the set.
void removeChannel (ChannelType newChannelType)
Removes a channel from the set.
int size () const noexcept
Returns the number of channels in the set.
bool isDisabled () const noexcept
Returns true if there are no channels in the set.
Array< ChannelType > getChannelTypes () const
Returns an array of all the types in this channel set.
ChannelType getTypeOfChannel (int channelIndex) const noexcept
Returns the type of one of the channels in the set, by index.
int getChannelIndexForType (ChannelType type) const noexcept
Returns the index for a particular channel-type.
String getSpeakerArrangementAsString () const
Returns a string containing a whitespace-separated list of speaker types corresponding to each channel.
String getDescription () const
Returns the description of the current layout.
bool isDiscreteLayout () const noexcept
Returns if this is a channel layout made-up of discrete channels.
void intersect (const AudioChannelSet &other)
Intersect two channel layouts.
int32 getWaveChannelMask () const noexcept
Returns a WAVEFORMATEXTENSIBLE channelMask representation (typically used in .wav files) of the receiver.
bool operator== (const AudioChannelSet &) const noexcept
bool operator!= (const AudioChannelSet &) const noexcept
bool operator< (const AudioChannelSet &) const noexcept
Static Public Member Functions
static AudioChannelSet
JUCE_CALLTYPE disabled ()
Creates a zero-channel set which can be used to indicate that a bus is disabled.
static AudioChannelSet
JUCE_CALLTYPE mono ()
Creates a one-channel mono set (centre).
static AudioChannelSet
JUCE_CALLTYPE stereo ()
Creates a set containing a stereo set (left, right).
static AudioChannelSet
JUCE_CALLTYPE createLCR ()
Creates a set containing an LCR set (left, right, centre).
static AudioChannelSet
JUCE_CALLTYPE createLRS ()
Creates a set containing an LRS set (left, right, surround).
static AudioChannelSet
JUCE_CALLTYPE createLCRS ()
Creates a set containing an LCRS set (left, right, centre, surround).
static AudioChannelSet
JUCE_CALLTYPE create5point0 ()
Creates a set for a 5.0 surround setup (left, right, centre, leftSurround, rightSurround).
static AudioChannelSet
JUCE_CALLTYPE create5point1 ()
Creates a set for a 5.1 surround setup (left, right, centre, leftSurround, rightSurround, LFE).
static AudioChannelSet
JUCE_CALLTYPE create6point0 ()
Creates a set for a 6.0 Cine surround setup (left, right, centre, leftSurround, rightSurround, centreSurround).
static AudioChannelSet
JUCE_CALLTYPE create6point1 ()
Creates a set for a 6.1 Cine surround setup (left, right, centre, leftSurround, rightSurround, centreSurround, LFE).
static AudioChannelSet
JUCE_CALLTYPE create6point0Music ()
Creates a set for a 6.0 Music surround setup (left, right, leftSurround, rightSurround, leftSurroundSide, rightSurroundSide).
static AudioChannelSet
JUCE_CALLTYPE create6point1Music ()
Creates a set for a 6.0 Music surround setup (left, right, leftSurround, rightSurround, leftSurroundSide, rightSurroundSide, LFE).
static AudioChannelSet
JUCE_CALLTYPE create7point0 ()
Creates a set for a DTS 7.0 surround setup (left, right, centre, leftSurroundSide, rightSurroundSide, leftSurroundRear, rightSurroundRear).
static AudioChannelSet
JUCE_CALLTYPE create7point0SDDS ()
Creates a set for a SDDS 7.0 surround setup (left, right, centre, leftSurround, rightSurround, leftCentre, rightCentre).
static AudioChannelSet
JUCE_CALLTYPE create7point1 ()
Creates a set for a DTS 7.1 surround setup (left, right, centre, leftSurroundSide, rightSurroundSide, leftSurroundRear, rightSurroundRear, LFE).
static AudioChannelSet
JUCE_CALLTYPE create7point1SDDS ()
Creates a set for a 7.1 surround setup (left, right, centre, leftSurround, rightSurround, leftCentre, rightCentre, LFE).
static AudioChannelSet
JUCE_CALLTYPE ambisonic ()
Creates a set for ambisonic surround setups (ambisonicW, ambisonicX, ambisonicY, ambisonicZ).
static AudioChannelSet
JUCE_CALLTYPE quadraphonic ()
Creates a set for quadraphonic surround setup (left, right, leftSurround, rightSurround)
static AudioChannelSet
JUCE_CALLTYPE pentagonal ()
Creates a set for pentagonal surround setup (left, right, centre, leftSurroundRear, rightSurroundRear).
static AudioChannelSet
JUCE_CALLTYPE hexagonal ()
Creates a set for hexagonal surround setup (left, right, leftSurroundRear, rightSurroundRear, centre, surroundCentre).
static AudioChannelSet
JUCE_CALLTYPE octagonal ()
Creates a set for octagonal surround setup (left, right, leftSurround, rightSurround, centre, centreSurround, wideLeft, wideRight).
static AudioChannelSet
JUCE_CALLTYPE discreteChannels (int numChannels)
Creates a set of untyped discrete channels.
static AudioChannelSet
JUCE_CALLTYPE canonicalChannelSet (int numChannels)
Create a canonical channel set for a given number of channels.
static AudioChannelSet
JUCE_CALLTYPE namedChannelSet (int numChannels)
Create a channel set for a given number of channels which is non-discrete.
static Array< AudioChannelSet >
JUCE_CALLTYPE channelSetsWithNumberOfChannels (int numChannels)
Return an array of channel sets which have a given number of channels.
static String JUCE_CALLTYPE getChannelTypeName (ChannelType)
Returns the name of a given channel type.
static String JUCE_CALLTYPE getAbbreviatedChannelTypeName (ChannelType)
Returns the abbreviated name of a channel type.
static ChannelType JUCE_CALLTYPE getChannelTypeFromAbbreviation (const String &abbreviation)
Returns the channel type from an abbreviated name.
static AudioChannelSet fromAbbreviatedString (const String &set)
Returns an AudioChannelSet from a string returned by getSpeakerArrangementAsString.
static AudioChannelSet
JUCE_CALLTYPE channelSetWithChannels (const Array< ChannelType > &)
Creates a channel set for a list of channel types.
static AudioChannelSet
JUCE_CALLTYPE fromWaveChannelMask (int32 dwChannelMask)
Create an AudioChannelSet from a WAVEFORMATEXTENSIBLE channelMask (typically used in .wav files).
Member Enumeration Documentation
enum AudioChannelSet::ChannelType
Represents different audio channel types.
Enumerator
unknown
left
right
centre
LFE
leftSurround
rightSurround
leftCentre
rightCentre
centreSurround
surround
leftSurroundSide
rightSurroundSide
topMiddle
topFrontLeft
topFrontCentre
topFrontRight
topRearLeft
topRearCentre
topRearRight
LFE2
leftSurroundRear
rightSurroundRear
wideLeft
wideRight
ambisonicW
ambisonicX
ambisonicY
ambisonicZ
discreteChannel0
Non-typed individual channels are indexed upwards from this value.
anonymous enum
Enumerator
maxChannelsOfNamedLayout
Constructor & Destructor Documentation
AudioChannelSet::AudioChannelSet () noexcept
Creates an empty channel set.
You can call addChannel to add channels to the set.
Member Function Documentation
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::disabled () static
Creates a zero-channel set which can be used to indicate that a bus is disabled.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), AudioUnitHelpers::setBusesLayout(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::mono () static
Creates a one-channel mono set (centre).
Is equivalent to: kMonoAAX (VST), AAX_eStemFormat_Mono (AAX), kAudioChannelLayoutTag_Mono (CoreAudio)
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::stereo () static
Creates a set containing a stereo set (left, right).
Is equivalent to: kStereo (VST), AAX_eStemFormat_Stereo (AAX), kAudioChannelLayoutTag_Stereo (CoreAudio)
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::createLCR () static
Creates a set containing an LCR set (left, right, centre).
Is equivalent to: k30Cine (VST), AAX_eStemFormat_LCR (AAX), kAudioChannelLayoutTag_MPEG_3_0_A (CoreAudio)
This format is referred to as "LRC" in Cubase. This format is referred to as "LCR" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::createLRS () static
Creates a set containing an LRS set (left, right, surround).
Is equivalent to: k30Music (VST), n/a (AAX), kAudioChannelLayoutTag_ITU_2_1 (CoreAudio)
This format is referred to as "LRS" in Cubase.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::createLCRS () static
Creates a set containing an LCRS set (left, right, centre, surround).
Is equivalent to: k40Cine (VST), AAX_eStemFormat_LCRS (AAX), kAudioChannelLayoutTag_MPEG_4_0_A (CoreAudio)
This format is referred to as "LCRS (Pro Logic)" in Logic Pro. This format is referred to as "LRCS" in Cubase. This format is referred to as "LCRS" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create5point0 () static
Creates a set for a 5.0 surround setup (left, right, centre, leftSurround, rightSurround).
Is equivalent to: k50 (VST), AAX_eStemFormat_5_0 (AAX), kAudioChannelLayoutTag_MPEG_5_0_A (CoreAudio)
This format is referred to as "5.0" in Cubase. This format is referred to as "5.0" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create5point1 () static
Creates a set for a 5.1 surround setup (left, right, centre, leftSurround, rightSurround, LFE).
Is equivalent to: k51 (VST), AAX_eStemFormat_5_1 (AAX), kAudioChannelLayoutTag_MPEG_5_1_A (CoreAudio)
This format is referred to as "5.1 (ITU 775)" in Logic Pro. This format is referred to as "5.1" in Cubase. This format is referred to as "5.1" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create6point0 () static
Creates a set for a 6.0 Cine surround setup (left, right, centre, leftSurround, rightSurround, centreSurround).
Is equivalent to: k60Cine (VST), AAX_eStemFormat_6_0 (AAX), kAudioChannelLayoutTag_AudioUnit_6_0 (CoreAudio)
Logic Pro incorrectly uses this for the surround format labeled "6.1 (ES/EX)". This format is referred to as "6.0 Cine" in Cubase. This format is referred to as "6.0" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create6point1 () static
Creates a set for a 6.1 Cine surround setup (left, right, centre, leftSurround, rightSurround, centreSurround, LFE).
Is equivalent to: k61Cine (VST), AAX_eStemFormat_6_1 (AAX), kAudioChannelLayoutTag_MPEG_6_1_A (CoreAudio)
This format is referred to as "6.1" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create6point0Music () static
Creates a set for a 6.0 Music surround setup (left, right, leftSurround, rightSurround, leftSurroundSide, rightSurroundSide).
Is equivalent to: k60Music (VST), n/a (AAX), kAudioChannelLayoutTag_DTS_6_0_A (CoreAudio)
This format is referred to as "6.0 Music" in Cubase.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create6point1Music () static
Creates a set for a 6.0 Music surround setup (left, right, leftSurround, rightSurround, leftSurroundSide, rightSurroundSide, LFE).
Is equivalent to: k61Music (VST), n/a (AAX), kAudioChannelLayoutTag_DTS_6_1_A (CoreAudio)
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create7point0 () static
Creates a set for a DTS 7.0 surround setup (left, right, centre, leftSurroundSide, rightSurroundSide, leftSurroundRear, rightSurroundRear).
Is equivalent to: k70Music (VST), AAX_eStemFormat_7_0_DTS (AAX), kAudioChannelLayoutTag_AudioUnit_7_0 (CoreAudio)
This format is referred to as "7.0" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create7point0SDDS () static
Creates a set for a SDDS 7.0 surround setup (left, right, centre, leftSurround, rightSurround, leftCentre, rightCentre).
Is equivalent to: k70Cine (VST), AAX_eStemFormat_7_0_SDDS (AAX), kAudioChannelLayoutTag_AudioUnit_7_0_Front (CoreAudio)
This format is referred to as "7.0 SDDS" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create7point1 () static
Creates a set for a DTS 7.1 surround setup (left, right, centre, leftSurroundSide, rightSurroundSide, leftSurroundRear, rightSurroundRear, LFE).
Is equivalent to: k71CineSideFill (VST), AAX_eStemFormat_7_1_DTS (AAX), kAudioChannelLayoutTag_MPEG_7_1_C/kAudioChannelLayoutTag_ITU_3_4_1 (CoreAudio)
This format is referred to as "7.1 (3/4.1)" in Logic Pro. This format is referred to as "7.1" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::create7point1SDDS () static
Creates a set for a 7.1 surround setup (left, right, centre, leftSurround, rightSurround, leftCentre, rightCentre, LFE).
Is equivalent to: k71Cine (VST), AAX_eStemFormat_7_1_SDDS (AAX), kAudioChannelLayoutTag_MPEG_7_1_A (CoreAudio)
This format is referred to as "7.1 (SDDS)" in Logic Pro. This format is referred to as "7.1 SDDS" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::ambisonic () static
Creates a set for ambisonic surround setups (ambisonicW, ambisonicX, ambisonicY, ambisonicZ).
Is equivalent to: kBFormat (VST), n/a (AAX), kAudioChannelLayoutTag_Ambisonic_B_Format (CoreAudio)
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::quadraphonic () static
Creates a set for quadraphonic surround setup (left, right, leftSurround, rightSurround)
Is equivalent to: k40Music (VST), AAX_eStemFormat_Quad (AAX), kAudioChannelLayoutTag_Quadraphonic (CoreAudio)
This format is referred to as "Quadraphonic" in Logic Pro. This format is referred to as "Quadro" in Cubase. This format is referred to as "Quad" in Pro Tools.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::pentagonal () static
Creates a set for pentagonal surround setup (left, right, centre, leftSurroundRear, rightSurroundRear).
Is equivalent to: n/a (VST), n/a (AAX), kAudioChannelLayoutTag_Pentagonal (CoreAudio)
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::hexagonal () static
Creates a set for hexagonal surround setup (left, right, leftSurroundRear, rightSurroundRear, centre, surroundCentre).
Is equivalent to: n/a (VST), n/a (AAX), kAudioChannelLayoutTag_Hexagonal (CoreAudio)
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::octagonal () static
Creates a set for octagonal surround setup (left, right, leftSurround, rightSurround, centre, centreSurround, wideLeft, wideRight).
Is equivalent to: n/a (VST), n/a (AAX), kAudioChannelLayoutTag_Octagonal (CoreAudio)
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::discreteChannels (int numChannels) static
Creates a set of untyped discrete channels.
Referenced by CoreAudioLayouts::getCoreAudioLayoutChannels(), and SpeakerMappings::vstArrangementTypeToChannelSet().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::canonicalChannelSet (int numChannels) static
Create a canonical channel set for a given number of channels.
For example, numChannels = 1 will return mono, numChannels = 2 will return stereo, etc.
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::namedChannelSet (int numChannels) static
Create a channel set for a given number of channels which is non-discrete.
If numChannels is larger than the number of channels of the surround format with the maximum amount of channels (currently 7.1 Surround), then this function returns an empty set.
static Array<AudioChannelSet> JUCE_CALLTYPE AudioChannelSet::channelSetsWithNumberOfChannels (int numChannels) static
Return an array of channel sets which have a given number of channels.
Referenced by AudioUnitHelpers::isNumberOfChannelsSupported().
static String JUCE_CALLTYPE AudioChannelSet::getChannelTypeName (ChannelType) static
Returns the name of a given channel type.
For example, this method may return "Surround Left".
static String JUCE_CALLTYPE AudioChannelSet::getAbbreviatedChannelTypeName (ChannelType) static
Returns the abbreviated name of a channel type.
For example, this method may return "Ls".
static ChannelType JUCE_CALLTYPE AudioChannelSet::getChannelTypeFromAbbreviation (const String & abbreviation) static
Returns the channel type from an abbreviated name.
void AudioChannelSet::addChannel (ChannelType newChannelType)
Adds a channel to the set.
Referenced by CoreAudioLayouts::toCoreAudio(), and SpeakerMappings::vstArrangementTypeToChannelSet().
void AudioChannelSet::removeChannel (ChannelType newChannelType)
Removes a channel from the set.
int AudioChannelSet::size () const noexcept
Returns the number of channels in the set.
Referenced by AudioProcessor::BusesLayout::getNumChannels(), VST3BufferExchange< float >::mapArrangementToBuses(), CoreAudioLayouts::toCoreAudio(), and SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
bool AudioChannelSet::isDisabled () const noexcept
Returns true if there are no channels in the set.
Array<ChannelType> AudioChannelSet::getChannelTypes () const
Returns an array of all the types in this channel set.
Referenced by SpeakerMappings::channelSetToVstArrangementType(), and CoreAudioLayouts::getCoreAudioLayoutChannels().
ChannelType AudioChannelSet::getTypeOfChannel (int channelIndex) const noexcept
Returns the type of one of the channels in the set, by index.
Referenced by SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
int AudioChannelSet::getChannelIndexForType (ChannelType type) const noexcept
Returns the index for a particular channel-type.
Will return -1 if the this set does not contain a channel of this type.
String AudioChannelSet::getSpeakerArrangementAsString () const
Returns a string containing a whitespace-separated list of speaker types corresponding to each channel.
For example in a 5.1 arrangement, the string may be "L R C Lfe Ls Rs". If the speaker arrangement is unknown, the returned string will be empty.
static AudioChannelSet AudioChannelSet::fromAbbreviatedString (const String & set) static
Returns an AudioChannelSet from a string returned by getSpeakerArrangementAsString.
See Also
getSpeakerArrangementAsString
String AudioChannelSet::getDescription () const
Returns the description of the current layout.
For example, this method may return "Quadraphonic". Note that the returned string may not be unique.
bool AudioChannelSet::isDiscreteLayout () const noexcept
Returns if this is a channel layout made-up of discrete channels.
void AudioChannelSet::intersect (const AudioChannelSet & other)
Intersect two channel layouts.
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::channelSetWithChannels (const Array< ChannelType > &) static
Creates a channel set for a list of channel types.
This function will assert if you supply a duplicate channel.
Note that this method ignores the order in which the channels are given, i.e. two arrays with the same elements but in a different order will still result in the same channel set.
Referenced by CoreAudioLayouts::fromCoreAudio().
static AudioChannelSet JUCE_CALLTYPE AudioChannelSet::fromWaveChannelMask (int32 dwChannelMask) static
Create an AudioChannelSet from a WAVEFORMATEXTENSIBLE channelMask (typically used in .wav files).
Referenced by CoreAudioLayouts::getCoreAudioLayoutChannels().
int32 AudioChannelSet::getWaveChannelMask () const noexcept
Returns a WAVEFORMATEXTENSIBLE channelMask representation (typically used in .wav files) of the receiver.
Returns -1 if the receiver cannot be represented in a WAVEFORMATEXTENSIBLE channelMask representation.
bool AudioChannelSet::operator== (const AudioChannelSet &) const noexcept
bool AudioChannelSet::operator!= (const AudioChannelSet &) const noexcept
bool AudioChannelSet::operator< (const AudioChannelSet &) const noexcept
class AudioData
This class a container which holds all the classes pertaining to the AudioData::Pointer audio sample format class.
See Also
AudioData::Pointer.
class AudioDataConverters
A set of routines to convert buffers of 32-bit floating point data to and from various integer formats.
Note that these functions are deprecated - the AudioData class provides a much more flexible set of conversion classes now.
Public Types
enum DataFormat {
int16LE, int16BE, int24LE, int24BE,
int32LE, int32BE, float32LE, float32BE
}
Static Public Member Functions
static void convertFloatToInt16LE (const float *source, void *dest, int numSamples, int destBytesPerSample=2)
static void convertFloatToInt16BE (const float *source, void *dest, int numSamples, int destBytesPerSample=2)
static void convertFloatToInt24LE (const float *source, void *dest, int numSamples, int destBytesPerSample=3)
static void convertFloatToInt24BE (const float *source, void *dest, int numSamples, int destBytesPerSample=3)
static void convertFloatToInt32LE (const float *source, void *dest, int numSamples, int destBytesPerSample=4)
static void convertFloatToInt32BE (const float *source, void *dest, int numSamples, int destBytesPerSample=4)
static void convertFloatToFloat32LE (const float *source, void *dest, int numSamples, int destBytesPerSample=4)
static void convertFloatToFloat32BE (const float *source, void *dest, int numSamples, int destBytesPerSample=4)
static void convertInt16LEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=2)
static void convertInt16BEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=2)
static void convertInt24LEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=3)
static void convertInt24BEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=3)
static void convertInt32LEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=4)
static void convertInt32BEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=4)
static void convertFloat32LEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=4)
static void convertFloat32BEToFloat (const void *source, float *dest, int numSamples, int srcBytesPerSample=4)
static void convertFloatToFormat (DataFormat destFormat, const float *source, void *dest, int numSamples)
static void convertFormatToFloat (DataFormat sourceFormat, const void *source, float *dest, int numSamples)
static void interleaveSamples (const float **source, float *dest, int numSamples, int numChannels)
static void deinterleaveSamples (const float *source, float **dest, int numSamples, int numChannels)
Member Enumeration Documentation
enum AudioDataConverters::DataFormat
Enumerator
int16LE
int16BE
int24LE
int24BE
int32LE
int32BE
float32LE
float32BE
Member Function Documentation
static void AudioDataConverters::convertFloatToInt16LE (const float * source, void * dest, int numSamples, int destBytesPerSample = 2) static
static void AudioDataConverters::convertFloatToInt16BE (const float * source, void * dest, int numSamples, int destBytesPerSample = 2) static
static void AudioDataConverters::convertFloatToInt24LE (const float * source, void * dest, int numSamples, int destBytesPerSample = 3) static
static void AudioDataConverters::convertFloatToInt24BE (const float * source, void * dest, int numSamples, int destBytesPerSample = 3) static
static void AudioDataConverters::convertFloatToInt32LE (const float * source, void * dest, int numSamples, int destBytesPerSample = 4) static
static void AudioDataConverters::convertFloatToInt32BE (const float * source, void * dest, int numSamples, int destBytesPerSample = 4) static
static void AudioDataConverters::convertFloatToFloat32LE (const float * source, void * dest, int numSamples, int destBytesPerSample = 4) static
static void AudioDataConverters::convertFloatToFloat32BE (const float * source, void * dest, int numSamples, int destBytesPerSample = 4) static
static void AudioDataConverters::convertInt16LEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 2) static
static void AudioDataConverters::convertInt16BEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 2) static
static void AudioDataConverters::convertInt24LEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 3) static
static void AudioDataConverters::convertInt24BEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 3) static
static void AudioDataConverters::convertInt32LEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 4) static
static void AudioDataConverters::convertInt32BEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 4) static
static void AudioDataConverters::convertFloat32LEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 4) static
static void AudioDataConverters::convertFloat32BEToFloat (const void * source, float * dest, int numSamples, int srcBytesPerSample = 4) static
static void AudioDataConverters::convertFloatToFormat (DataFormat destFormat, const float * source, void * dest, int numSamples) static
static void AudioDataConverters::convertFormatToFloat (DataFormat sourceFormat, const void * source, float * dest, int numSamples) static
static void AudioDataConverters::interleaveSamples (const float ** source, float * dest, int numSamples, int numChannels) static
static void AudioDataConverters::deinterleaveSamples (const float * source, float ** dest, int numSamples, int numChannels) static
class AudioBuffer
template<typename Type>
class AudioBuffer< Type >
A multi-channel buffer of floating point audio samples.
See Also
AudioSampleBuffer
Public Member Functions
AudioBuffer () noexcept
Creates an empty buffer with 0 channels and 0 length.
AudioBuffer (int numChannelsToAllocate, int numSamplesToAllocate)
Creates a buffer with a specified number of channels and samples.
AudioBuffer (Type *const *dataToReferTo, int numChannelsToUse, int numSamples)
Creates a buffer using a pre-allocated block of memory.
AudioBuffer (Type *const *dataToReferTo, int numChannelsToUse, int startSample, int numSamples)
Creates a buffer using a pre-allocated block of memory.
AudioBuffer (const AudioBuffer &other)
Copies another buffer.
AudioBuffer & operator= (const AudioBuffer &other)
Copies another buffer onto this one.
~AudioBuffer () noexcept
Destructor.
AudioBuffer (AudioBuffer &&other) noexcept
Move constructor.
AudioBuffer & operator= (AudioBuffer &&other) noexcept
Move assignment.
int getNumChannels () const noexcept
Returns the number of channels of audio data that this buffer contains.
int getNumSamples () const noexcept
Returns the number of samples allocated in each of the buffer's channels.
const Type * getReadPointer (int channelNumber) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
const Type * getReadPointer (int channelNumber, int sampleIndex) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
Type * getWritePointer (int channelNumber) noexcept
Returns a writeable pointer to one of the buffer's channels.
Type * getWritePointer (int channelNumber, int sampleIndex) noexcept
Returns a writeable pointer to one of the buffer's channels.
const Type ** getArrayOfReadPointers () const noexcept
Returns an array of pointers to the channels in the buffer.
Type ** getArrayOfWritePointers () noexcept
Returns an array of pointers to the channels in the buffer.
void setSize (int newNumChannels, int newNumSamples, bool keepExistingContent=false, bool clearExtraSpace=false, bool avoidReallocating=false)
Changes the buffer's size or number of channels.
void setDataToReferTo (Type **dataToReferTo, int newNumChannels, int newStartSample, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
void setDataToReferTo (Type **dataToReferTo, int newNumChannels, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
template<typename OtherType >
void makeCopyOf (const AudioBuffer< OtherType > &other, bool avoidReallocating=false)
Resizes this buffer to match the given one, and copies all of its content across.
void clear () noexcept
Clears all the samples in all channels.
void clear (int startSample, int numSamples) noexcept
Clears a specified region of all the channels.
void clear (int channel, int startSample, int numSamples) noexcept
Clears a specified region of just one channel.
bool hasBeenCleared () const noexcept
Returns true if the buffer has been entirely cleared.
Type getSample (int channel, int sampleIndex) const noexcept
Returns a sample from the buffer.
void setSample (int destChannel, int destSample, Type newValue) noexcept
Sets a sample in the buffer.
void addSample (int destChannel, int destSample, Type valueToAdd) noexcept
Adds a value to a sample in the buffer.
void applyGain (int channel, int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of one channel.
void applyGain (int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of all the channels.
void applyGain (Type gain) noexcept
Applies a gain multiple to all the audio data.
void applyGainRamp (int channel, int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of a channel.
void applyGainRamp (int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of all channels.
void addFrom (int destChannel, int destStartSample, const AudioBuffer &source, int sourceChannel, int sourceStartSample, int numSamples, Type gainToApplyToSource=(Type) 1) noexcept
Adds samples from another buffer to this one.
void addFrom (int destChannel, int destStartSample, const Type *source, int numSamples, Type gainToApplyToSource=(Type) 1) noexcept
Adds samples from an array of floats to one of the channels.
void addFromWithRamp (int destChannel, int destStartSample, const Type *source, int numSamples, Type startGain, Type endGain) noexcept
Adds samples from an array of floats, applying a gain ramp to them.
void copyFrom (int destChannel, int destStartSample, const AudioBuffer &source, int sourceChannel, int sourceStartSample, int numSamples) noexcept
Copies samples from another buffer to this one.
void copyFrom (int destChannel, int destStartSample, const Type *source, int numSamples) noexcept
Copies samples from an array of floats into one of the channels.
void copyFrom (int destChannel, int destStartSample, const Type *source, int numSamples, Type gain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain to it.
void copyFromWithRamp (int destChannel, int destStartSample, const Type *source, int numSamples, Type startGain, Type endGain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain ramp.
Range< Type > findMinMax (int channel, int startSample, int numSamples) const noexcept
Returns a Range indicating the lowest and highest sample values in a given section.
Type getMagnitude (int channel, int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region of a channel.
Type getMagnitude (int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region on all channels.
Type getRMSLevel (int channel, int startSample, int numSamples) const noexcept
Returns the root mean squared level for a region of a channel.
void reverse (int channel, int startSample, int numSamples) const noexcept
Reverses a part of a channel.
void reverse (int startSample, int numSamples) const noexcept
Reverses a part of the buffer.
Constructor & Destructor Documentation
template<typename Type> AudioBuffer< Type >::AudioBuffer () noexcept
Creates an empty buffer with 0 channels and 0 length.
template<typename Type> AudioBuffer< Type >::AudioBuffer (int numChannelsToAllocate, int numSamplesToAllocate)
Creates a buffer with a specified number of channels and samples.
The contents of the buffer will initially be undefined, so use clear() to set all the samples to zero.
The buffer will allocate its memory internally, and this will be released when the buffer is deleted. If the memory can't be allocated, this will throw a std::bad_alloc exception.
template<typename Type> AudioBuffer< Type >::AudioBuffer (Type *const * dataToReferTo, int numChannelsToUse, int numSamples)
Creates a buffer using a pre-allocated block of memory.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
numChannelsToUse the number of channels to use - this must correspond to the number of elements in the array passed in
numSamples the number of samples to use - this must correspond to the size of the arrays passed in
template<typename Type> AudioBuffer< Type >::AudioBuffer (Type *const * dataToReferTo, int numChannelsToUse, int startSample, int numSamples)
Creates a buffer using a pre-allocated block of memory.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
numChannelsToUse the number of channels to use - this must correspond to the number of elements in the array passed in
startSample the offset within the arrays at which the data begins
numSamples the number of samples to use - this must correspond to the size of the arrays passed in
template<typename Type> AudioBuffer< Type >::AudioBuffer (const AudioBuffer< Type > & other)
Copies another buffer.
This buffer will make its own copy of the other's data, unless the buffer was created using an external data buffer, in which case boths buffers will just point to the same shared block of data.
template<typename Type> AudioBuffer< Type >::~AudioBuffer () noexcept
Destructor.
This will free any memory allocated by the buffer.
template<typename Type> AudioBuffer< Type >::AudioBuffer (AudioBuffer< Type > && other) noexcept
Move constructor.
Member Function Documentation
template<typename Type> AudioBuffer& AudioBuffer< Type >::operator= (const AudioBuffer< Type > & other)
Copies another buffer onto this one.
This buffer's size will be changed to that of the other buffer.
template<typename Type> AudioBuffer& AudioBuffer< Type >::operator= (AudioBuffer< Type > && other) noexcept
Move assignment.
template<typename Type> int AudioBuffer< Type >::getNumChannels () const noexcept
Returns the number of channels of audio data that this buffer contains.
See Also
getNumSamples, getReadPointer, getWritePointer
Referenced by VST3BufferExchange< float >::associateBufferTo(), AudioUnitHelpers::CoreAudioBufferList::getBuffer(), AudioBuffer< float >::makeCopyOf(), AudioBuffer< float >::operator=(), AudioUnitHelpers::CoreAudioBufferList::pop(), AudioUnitHelpers::CoreAudioBufferList::push(), AudioUnitHelpers::CoreAudioBufferList::reset(), and AudioUnitHelpers::CoreAudioBufferList::setBuffer().
template<typename Type> int AudioBuffer< Type >::getNumSamples () const noexcept
Returns the number of samples allocated in each of the buffer's channels.
See Also
getNumChannels, getReadPointer, getWritePointer
Referenced by AudioProcessor::getBusBuffer(), AudioBuffer< float >::makeCopyOf(), and AudioBuffer< float >::operator=().
template<typename Type> const Type* AudioBuffer< Type >::getReadPointer (int channelNumber) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
For speed, this doesn't check whether the channel number is out of range, so be careful when using it! If you need to write to the data, do NOT call this method and const_cast the result! Instead, you must call getWritePointer so that the buffer knows you're planning on modifying the data.
Referenced by AudioBuffer< float >::makeCopyOf().
template<typename Type> const Type* AudioBuffer< Type >::getReadPointer (int channelNumber, int sampleIndex) const noexcept
Returns a pointer to an array of read-only samples in one of the buffer's channels.
For speed, this doesn't check whether the channel number or index are out of range, so be careful when using it! If you need to write to the data, do NOT call this method and const_cast the result! Instead, you must call getWritePointer so that the buffer knows you're planning on modifying the data.
template<typename Type> Type* AudioBuffer< Type >::getWritePointer (int channelNumber) noexcept
Returns a writeable pointer to one of the buffer's channels.
For speed, this doesn't check whether the channel number is out of range, so be careful when using it! Note that if you're not planning on writing to the data, you should always use getReadPointer instead.
Referenced by VST3BufferExchange< float >::associateBufferTo().
template<typename Type> Type* AudioBuffer< Type >::getWritePointer (int channelNumber, int sampleIndex) noexcept
Returns a writeable pointer to one of the buffer's channels.
For speed, this doesn't check whether the channel number or index are out of range, so be careful when using it! Note that if you're not planning on writing to the data, you should use getReadPointer instead.
template<typename Type> const Type** AudioBuffer< Type >::getArrayOfReadPointers () const noexcept
Returns an array of pointers to the channels in the buffer.
Don't modify any of the pointers that are returned, and bear in mind that these will become invalid if the buffer is resized.
template<typename Type> Type** AudioBuffer< Type >::getArrayOfWritePointers () noexcept
Returns an array of pointers to the channels in the buffer.
Don't modify any of the pointers that are returned, and bear in mind that these will become invalid if the buffer is resized.
Referenced by AudioProcessor::getBusBuffer().
template<typename Type> void AudioBuffer< Type >::setSize (int newNumChannels, int newNumSamples, bool keepExistingContent = false, bool clearExtraSpace = false, bool avoidReallocating = false)
Changes the buffer's size or number of channels.
This can expand or contract the buffer's length, and add or remove channels.
If keepExistingContent is true, it will try to preserve as much of the old data as it can in the new buffer.
If clearExtraSpace is true, then any extra channels or space that is allocated will be also be cleared. If false, then this space is left uninitialised.
If avoidReallocating is true, then changing the buffer's size won't reduce the amount of memory that is currently allocated (but it will still increase it if the new size is bigger than the amount it currently has). If this is false, then a new allocation will be done so that the buffer uses takes up the minimum amount of memory that it needs.
If the required memory can't be allocated, this will throw a std::bad_alloc exception.
Referenced by AudioBuffer< float >::makeCopyOf(), AudioBuffer< float >::operator=(), AudioUnitHelpers::CoreAudioBufferList::prepare(), and AudioUnitHelpers::CoreAudioBufferList::release().
template<typename Type> void AudioBuffer< Type >::setDataToReferTo (Type ** dataToReferTo, int newNumChannels, int newStartSample, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
There's also a constructor that lets you specify arrays like this, but this lets you change the channels dynamically.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
newNumChannels the number of channels to use - this must correspond to the number of elements in the array passed in
newStartSample the offset within the arrays at which the data begins
newNumSamples the number of samples to use - this must correspond to the size of the arrays passed in
Referenced by AudioUnitHelpers::CoreAudioBufferList::getBuffer(), and AudioBuffer< float >::setDataToReferTo().
template<typename Type> void AudioBuffer< Type >::setDataToReferTo (Type ** dataToReferTo, int newNumChannels, int newNumSamples)
Makes this buffer point to a pre-allocated set of channel data arrays.
There's also a constructor that lets you specify arrays like this, but this lets you change the channels dynamically.
Note that if the buffer is resized or its number of channels is changed, it will re-allocate memory internally and copy the existing data to this new area, so it will then stop directly addressing this memory.
Parameters
dataToReferTo a pre-allocated array containing pointers to the data for each channel that should be used by this buffer. The buffer will only refer to this memory, it won't try to delete it when the buffer is deleted or resized.
newNumChannels the number of channels to use - this must correspond to the number of elements in the array passed in
newNumSamples the number of samples to use - this must correspond to the size of the arrays passed in
template<typename Type> template<typename OtherType > void AudioBuffer< Type >::makeCopyOf (const AudioBuffer< OtherType > & other, bool avoidReallocating = false)
Resizes this buffer to match the given one, and copies all of its content across.
The source buffer can contain a different floating point type, so this can be used to convert between 32 and 64 bit float buffer types.
template<typename Type> void AudioBuffer< Type >::clear () noexcept
Clears all the samples in all channels.
Referenced by AudioBuffer< float >::AudioBuffer(), AudioBuffer< float >::makeCopyOf(), and AudioBuffer< float >::operator=().
template<typename Type> void AudioBuffer< Type >::clear (int startSample, int numSamples) noexcept
Clears a specified region of all the channels.
For speed, this doesn't check whether the channel and sample number are in-range, so be careful!
template<typename Type> void AudioBuffer< Type >::clear (int channel, int startSample, int numSamples) noexcept
Clears a specified region of just one channel.
For speed, this doesn't check whether the channel and sample number are in-range, so be careful!
template<typename Type> bool AudioBuffer< Type >::hasBeenCleared () const noexcept
Returns true if the buffer has been entirely cleared.
Note that this does not actually measure the contents of the buffer - it simply returns a flag that is set when the buffer is cleared, and which is reset whenever functions like getWritePointer() are invoked. That means the method does not take any time, but it may return false negatives when in fact the buffer is still empty.
Referenced by AudioBuffer< float >::makeCopyOf().
template<typename Type> Type AudioBuffer< Type >::getSample (int channel, int sampleIndex) const noexcept
Returns a sample from the buffer.
The channel and index are not checked - they are expected to be in-range. If not, an assertion will be thrown, but in a release build, you're into 'undefined behaviour' territory.
template<typename Type> void AudioBuffer< Type >::setSample (int destChannel, int destSample, Type newValue) noexcept
Sets a sample in the buffer.
The channel and index are not checked - they are expected to be in-range. If not, an assertion will be thrown, but in a release build, you're into 'undefined behaviour' territory.
template<typename Type> void AudioBuffer< Type >::addSample (int destChannel, int destSample, Type valueToAdd) noexcept
Adds a value to a sample in the buffer.
The channel and index are not checked - they are expected to be in-range. If not, an assertion will be thrown, but in a release build, you're into 'undefined behaviour' territory.
template<typename Type> void AudioBuffer< Type >::applyGain (int channel, int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of one channel.
For speed, this doesn't check whether the channel and sample number are in-range, so be careful!
Referenced by AudioBuffer< float >::applyGain(), and AudioBuffer< float >::applyGainRamp().
template<typename Type> void AudioBuffer< Type >::applyGain (int startSample, int numSamples, Type gain) noexcept
Applies a gain multiple to a region of all the channels.
For speed, this doesn't check whether the sample numbers are in-range, so be careful!
template<typename Type> void AudioBuffer< Type >::applyGain (Type gain) noexcept
Applies a gain multiple to all the audio data.
template<typename Type> void AudioBuffer< Type >::applyGainRamp (int channel, int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of a channel.
The gain that is applied to each sample will vary from startGain on the first sample to endGain on the last Sample, so it can be used to do basic fades.
For speed, this doesn't check whether the sample numbers are in-range, so be careful!
Referenced by AudioBuffer< float >::applyGainRamp().
template<typename Type> void AudioBuffer< Type >::applyGainRamp (int startSample, int numSamples, Type startGain, Type endGain) noexcept
Applies a range of gains to a region of all channels.
The gain that is applied to each sample will vary from startGain on the first sample to endGain on the last Sample, so it can be used to do basic fades.
For speed, this doesn't check whether the sample numbers are in-range, so be careful!
template<typename Type> void AudioBuffer< Type >::addFrom (int destChannel, int destStartSample, const AudioBuffer< Type > & source, int sourceChannel, int sourceStartSample, int numSamples, Type gainToApplyToSource = (Type) 1) noexcept
Adds samples from another buffer to this one.
Parameters
destChannel the channel within this buffer to add the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to add from
sourceChannel the channel within the source buffer to read from
sourceStartSample the offset within the source buffer's channel to start reading samples from
numSamples the number of samples to process
gainToApplyToSource an optional gain to apply to the source samples before they are added to this buffer's samples
See Also
copyFrom
Referenced by AudioBuffer< float >::addFromWithRamp().
template<typename Type> void AudioBuffer< Type >::addFrom (int destChannel, int destStartSample, const Type * source, int numSamples, Type gainToApplyToSource = (Type) 1) noexcept
Adds samples from an array of floats to one of the channels.
Parameters
destChannel the channel within this buffer to add the samples to
destStartSample the start sample within this buffer's channel
source the source data to use
numSamples the number of samples to process
gainToApplyToSource an optional gain to apply to the source samples before they are added to this buffer's samples
See Also
copyFrom
template<typename Type> void AudioBuffer< Type >::addFromWithRamp (int destChannel, int destStartSample, const Type * source, int numSamples, Type startGain, Type endGain) noexcept
Adds samples from an array of floats, applying a gain ramp to them.
Parameters
destChannel the channel within this buffer to add the samples to
destStartSample the start sample within this buffer's channel
source the source data to use
numSamples the number of samples to process
startGain the gain to apply to the first sample (this is multiplied with the source samples before they are added to this buffer)
endGain the gain to apply to the final sample. The gain is linearly interpolated between the first and last samples.
template<typename Type> void AudioBuffer< Type >::copyFrom (int destChannel, int destStartSample, const AudioBuffer< Type > & source, int sourceChannel, int sourceStartSample, int numSamples) noexcept
Copies samples from another buffer to this one.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
sourceChannel the channel within the source buffer to read from
sourceStartSample the offset within the source buffer's channel to start reading samples from
numSamples the number of samples to process
See Also
addFrom
Referenced by AudioBuffer< float >::copyFromWithRamp().
template<typename Type> void AudioBuffer< Type >::copyFrom (int destChannel, int destStartSample, const Type * source, int numSamples) noexcept
Copies samples from an array of floats into one of the channels.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
numSamples the number of samples to process
See Also
addFrom
template<typename Type> void AudioBuffer< Type >::copyFrom (int destChannel, int destStartSample, const Type * source, int numSamples, Type gain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain to it.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
numSamples the number of samples to process
gain the gain to apply
See Also
addFrom
template<typename Type> void AudioBuffer< Type >::copyFromWithRamp (int destChannel, int destStartSample, const Type * source, int numSamples, Type startGain, Type endGain) noexcept
Copies samples from an array of floats into one of the channels, applying a gain ramp.
Parameters
destChannel the channel within this buffer to copy the samples to
destStartSample the start sample within this buffer's channel
source the source buffer to read from
numSamples the number of samples to process
startGain the gain to apply to the first sample (this is multiplied with the source samples before they are copied to this buffer)
endGain the gain to apply to the final sample. The gain is linearly interpolated between the first and last samples.
See Also
addFrom
template<typename Type> Range<Type> AudioBuffer< Type >::findMinMax (int channel, int startSample, int numSamples) const noexcept
Returns a Range indicating the lowest and highest sample values in a given section.
Parameters
channel the channel to read from
startSample the start sample within the channel
numSamples the number of samples to check
Referenced by AudioBuffer< float >::getMagnitude().
template<typename Type> Type AudioBuffer< Type >::getMagnitude (int channel, int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region of a channel.
Referenced by AudioBuffer< float >::getMagnitude().
template<typename Type> Type AudioBuffer< Type >::getMagnitude (int startSample, int numSamples) const noexcept
Finds the highest absolute sample value within a region on all channels.
template<typename Type> Type AudioBuffer< Type >::getRMSLevel (int channel, int startSample, int numSamples) const noexcept
Returns the root mean squared level for a region of a channel.
template<typename Type> void AudioBuffer< Type >::reverse (int channel, int startSample, int numSamples) const noexcept
Reverses a part of a channel.
Referenced by AudioBuffer< float >::reverse().
template<typename Type> void AudioBuffer< Type >::reverse (int startSample, int numSamples) const noexcept
Reverses a part of the buffer.
class FloatVectorOperations
A collection of simple vector operations on arrays of floats, accelerated with SIMD instructions where possible.
Static Public Member Functions
static void JUCE_CALLTYPE clear (float *dest, int numValues) noexcept
Clears a vector of floats.
static void JUCE_CALLTYPE clear (double *dest, int numValues) noexcept
Clears a vector of doubles.
static void JUCE_CALLTYPE fill (float *dest, float valueToFill, int numValues) noexcept
Copies a repeated value into a vector of floats.
static void JUCE_CALLTYPE fill (double *dest, double valueToFill, int numValues) noexcept
Copies a repeated value into a vector of doubles.
static void JUCE_CALLTYPE copy (float *dest, const float *src, int numValues) noexcept
Copies a vector of floats.
static void JUCE_CALLTYPE copy (double *dest, const double *src, int numValues) noexcept
Copies a vector of doubles.
static void JUCE_CALLTYPE copyWithMultiply (float *dest, const float *src, float multiplier, int numValues) noexcept
Copies a vector of floats, multiplying each value by a given multiplier.
static void JUCE_CALLTYPE copyWithMultiply (double *dest, const double *src, double multiplier, int numValues) noexcept
Copies a vector of doubles, multiplying each value by a given multiplier.
static void JUCE_CALLTYPE add (float *dest, float amountToAdd, int numValues) noexcept
Adds a fixed value to the destination values.
static void JUCE_CALLTYPE add (double *dest, double amountToAdd, int numValues) noexcept
Adds a fixed value to the destination values.
static void JUCE_CALLTYPE add (float *dest, const float *src, float amount, int numValues) noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE add (double *dest, const double *src, double amount, int numValues) noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE add (float *dest, const float *src, int numValues) noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE add (double *dest, const double *src, int numValues) noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE add (float *dest, const float *src1, const float *src2, int num) noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE add (double *dest, const double *src1, const double *src2, int num) noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE subtract (float *dest, const float *src, int numValues) noexcept
Subtracts the source values from the destination values.
static void JUCE_CALLTYPE subtract (double *dest, const double *src, int numValues) noexcept
Subtracts the source values from the destination values.
static void JUCE_CALLTYPE subtract (float *dest, const float *src1, const float *src2, int num) noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE subtract (double *dest, const double *src1, const double *src2, int num) noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE addWithMultiply (float *dest, const float *src, float multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
static void JUCE_CALLTYPE addWithMultiply (double *dest, const double *src, double multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
static void JUCE_CALLTYPE addWithMultiply (float *dest, const float *src1, const float *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE addWithMultiply (double *dest, const double *src1, const double *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (float *dest, const float *src, float multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (double *dest, const double *src, double multiplier, int numValues) noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (float *dest, const float *src1, const float *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE subtractWithMultiply (double *dest, const double *src1, const double *src2, int num) noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE multiply (float *dest, const float *src, int numValues) noexcept
Multiplies the destination values by the source values.
static void JUCE_CALLTYPE multiply (double *dest, const double *src, int numValues) noexcept
Multiplies the destination values by the source values.
static void JUCE_CALLTYPE multiply (float *dest, const float *src1, const float *src2, int numValues) noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE multiply (double *dest, const double *src1, const double *src2, int numValues) noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE multiply (float *dest, float multiplier, int numValues) noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE multiply (double *dest, double multiplier, int numValues) noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE multiply (float *dest, const float *src, float multiplier, int num) noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE multiply (double *dest, const double *src, double multiplier, int num) noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE negate (float *dest, const float *src, int numValues) noexcept
Copies a source vector to a destination, negating each value.
static void JUCE_CALLTYPE negate (double *dest, const double *src, int numValues) noexcept
Copies a source vector to a destination, negating each value.
static void JUCE_CALLTYPE abs (float *dest, const float *src, int numValues) noexcept
Copies a source vector to a destination, taking the absolute of each value.
static void JUCE_CALLTYPE abs (double *dest, const double *src, int numValues) noexcept
Copies a source vector to a destination, taking the absolute of each value.
static void JUCE_CALLTYPE convertFixedToFloat (float *dest, const int *src, float multiplier, int numValues) noexcept
Converts a stream of integers to floats, multiplying each one by the given multiplier.
static void JUCE_CALLTYPE min (float *dest, const float *src, float comp, int num) noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE min (double *dest, const double *src, double comp, int num) noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE min (float *dest, const float *src1, const float *src2, int num) noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE min (double *dest, const double *src1, const double *src2, int num) noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE max (float *dest, const float *src, float comp, int num) noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE max (double *dest, const double *src, double comp, int num) noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE max (float *dest, const float *src1, const float *src2, int num) noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE max (double *dest, const double *src1, const double *src2, int num) noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE clip (float *dest, const float *src, float low, float high, int num) noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static void JUCE_CALLTYPE clip (double *dest, const double *src, double low, double high, int num) noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static Range< float > JUCE_CALLTYPE findMinAndMax (const float *src, int numValues) noexcept
Finds the miniumum and maximum values in the given array.
static Range< double >
JUCE_CALLTYPE findMinAndMax (const double *src, int numValues) noexcept
Finds the miniumum and maximum values in the given array.
static float JUCE_CALLTYPE findMinimum (const float *src, int numValues) noexcept
Finds the miniumum value in the given array.
static double JUCE_CALLTYPE findMinimum (const double *src, int numValues) noexcept
Finds the miniumum value in the given array.
static float JUCE_CALLTYPE findMaximum (const float *src, int numValues) noexcept
Finds the maximum value in the given array.
static double JUCE_CALLTYPE findMaximum (const double *src, int numValues) noexcept
Finds the maximum value in the given array.
static void JUCE_CALLTYPE enableFlushToZeroMode (bool shouldEnable) noexcept
On Intel CPUs, this method enables or disables the SSE flush-to-zero mode.
static void JUCE_CALLTYPE disableDenormalisedNumberSupport () noexcept
On Intel CPUs, this method enables the SSE flush-to-zero and denormalised-are-zero modes.
Member Function Documentation
static void JUCE_CALLTYPE FloatVectorOperations::clear (float * dest, int numValues) static noexcept
Clears a vector of floats.
Referenced by AudioBuffer< float >::applyGain(), AudioBlock< float >::clear(), AudioBuffer< float >::clear(), and AudioBuffer< float >::copyFrom().
static void JUCE_CALLTYPE FloatVectorOperations::clear (double * dest, int numValues) static noexcept
Clears a vector of doubles.
static void JUCE_CALLTYPE FloatVectorOperations::fill (float * dest, float valueToFill, int numValues) static noexcept
Copies a repeated value into a vector of floats.
Referenced by AudioBlock< float >::fill().
static void JUCE_CALLTYPE FloatVectorOperations::fill (double * dest, double valueToFill, int numValues) static noexcept
Copies a repeated value into a vector of doubles.
static void JUCE_CALLTYPE FloatVectorOperations::copy (float * dest, const float * src, int numValues) static noexcept
Copies a vector of floats.
Referenced by AudioBuffer< float >::addFrom(), AudioBuffer< float >::AudioBuffer(), AudioBlock< float >::copy(), AudioBuffer< float >::copyFrom(), AudioBuffer< float >::operator=(), and AudioBuffer< float >::setSize().
static void JUCE_CALLTYPE FloatVectorOperations::copy (double * dest, const double * src, int numValues) static noexcept
Copies a vector of doubles.
static void JUCE_CALLTYPE FloatVectorOperations::copyWithMultiply (float * dest, const float * src, float multiplier, int numValues) static noexcept
Copies a vector of floats, multiplying each value by a given multiplier.
Referenced by AudioBuffer< float >::addFrom(), and AudioBuffer< float >::copyFrom().
static void JUCE_CALLTYPE FloatVectorOperations::copyWithMultiply (double * dest, const double * src, double multiplier, int numValues) static noexcept
Copies a vector of doubles, multiplying each value by a given multiplier.
static void JUCE_CALLTYPE FloatVectorOperations::add (float * dest, float amountToAdd, int numValues) static noexcept
Adds a fixed value to the destination values.
Referenced by AudioBlock< float >::add(), AudioBuffer< float >::addFrom(), and Bias< FloatType >::process().
static void JUCE_CALLTYPE FloatVectorOperations::add (double * dest, double amountToAdd, int numValues) static noexcept
Adds a fixed value to the destination values.
static void JUCE_CALLTYPE FloatVectorOperations::add (float * dest, const float * src, float amount, int numValues) static noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::add (double * dest, const double * src, double amount, int numValues) static noexcept
Adds a fixed value to each source value and stores it in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::add (float * dest, const float * src, int numValues) static noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE FloatVectorOperations::add (double * dest, const double * src, int numValues) static noexcept
Adds the source values to the destination values.
static void JUCE_CALLTYPE FloatVectorOperations::add (float * dest, const float * src1, const float * src2, int num) static noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::add (double * dest, const double * src1, const double * src2, int num) static noexcept
Adds each source1 value to the corresponding source2 value and stores the result in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::subtract (float * dest, const float * src, int numValues) static noexcept
Subtracts the source values from the destination values.
Referenced by AudioBlock< float >::subtract().
static void JUCE_CALLTYPE FloatVectorOperations::subtract (double * dest, const double * src, int numValues) static noexcept
Subtracts the source values from the destination values.
static void JUCE_CALLTYPE FloatVectorOperations::subtract (float * dest, const float * src1, const float * src2, int num) static noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::subtract (double * dest, const double * src1, const double * src2, int num) static noexcept
Subtracts each source2 value from the corresponding source1 value and stores the result in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::addWithMultiply (float * dest, const float * src, float multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
Referenced by AudioBuffer< float >::addFrom(), and AudioBlock< float >::addWithMultiply().
static void JUCE_CALLTYPE FloatVectorOperations::addWithMultiply (double * dest, const double * src, double multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then adds it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::addWithMultiply (float * dest, const float * src1, const float * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::addWithMultiply (double * dest, const double * src1, const double * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then adds it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::subtractWithMultiply (float * dest, const float * src, float multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::subtractWithMultiply (double * dest, const double * src, double multiplier, int numValues) static noexcept
Multiplies each source value by the given multiplier, then subtracts it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::subtractWithMultiply (float * dest, const float * src1, const float * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::subtractWithMultiply (double * dest, const double * src1, const double * src2, int num) static noexcept
Multiplies each source1 value by the corresponding source2 value, then subtracts it to the destination value.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (float * dest, const float * src, int numValues) static noexcept
Multiplies the destination values by the source values.
Referenced by LinearSmoothedValue< NumericType >::applyGain(), AudioBuffer< float >::applyGain(), AudioBlock< float >::multiply(), and Gain< FloatType >::process().
static void JUCE_CALLTYPE FloatVectorOperations::multiply (double * dest, const double * src, int numValues) static noexcept
Multiplies the destination values by the source values.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (float * dest, const float * src1, const float * src2, int numValues) static noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (double * dest, const double * src1, const double * src2, int numValues) static noexcept
Multiplies each source1 value by the correspinding source2 value, then stores it in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (float * dest, float multiplier, int numValues) static noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (double * dest, double multiplier, int numValues) static noexcept
Multiplies each of the destination values by a fixed multiplier.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (float * dest, const float * src, float multiplier, int num) static noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::multiply (double * dest, const double * src, double multiplier, int num) static noexcept
Multiplies each of the source values by a fixed multiplier and stores the result in the destination array.
static void JUCE_CALLTYPE FloatVectorOperations::negate (float * dest, const float * src, int numValues) static noexcept
Copies a source vector to a destination, negating each value.
Referenced by AudioBlock< float >::replaceWithNegativeOf().
static void JUCE_CALLTYPE FloatVectorOperations::negate (double * dest, const double * src, int numValues) static noexcept
Copies a source vector to a destination, negating each value.
static void JUCE_CALLTYPE FloatVectorOperations::abs (float * dest, const float * src, int numValues) static noexcept
Copies a source vector to a destination, taking the absolute of each value.
Referenced by AudioBlock< float >::replaceWithAbsoluteValueOf().
static void JUCE_CALLTYPE FloatVectorOperations::abs (double * dest, const double * src, int numValues) static noexcept
Copies a source vector to a destination, taking the absolute of each value.
static void JUCE_CALLTYPE FloatVectorOperations::convertFixedToFloat (float * dest, const int * src, float multiplier, int numValues) static noexcept
Converts a stream of integers to floats, multiplying each one by the given multiplier.
static void JUCE_CALLTYPE FloatVectorOperations::min (float * dest, const float * src, float comp, int num) static noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
Referenced by AudioBlock< float >::min().
static void JUCE_CALLTYPE FloatVectorOperations::min (double * dest, const double * src, double comp, int num) static noexcept
Each element of dest will be the minimum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE FloatVectorOperations::min (float * dest, const float * src1, const float * src2, int num) static noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE FloatVectorOperations::min (double * dest, const double * src1, const double * src2, int num) static noexcept
Each element of dest will be the minimum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE FloatVectorOperations::max (float * dest, const float * src, float comp, int num) static noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
Referenced by AudioBlock< float >::max().
static void JUCE_CALLTYPE FloatVectorOperations::max (double * dest, const double * src, double comp, int num) static noexcept
Each element of dest will be the maximum of the corresponding element of the source array and the given comp value.
static void JUCE_CALLTYPE FloatVectorOperations::max (float * dest, const float * src1, const float * src2, int num) static noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE FloatVectorOperations::max (double * dest, const double * src1, const double * src2, int num) static noexcept
Each element of dest will be the maximum of the corresponding source1 and source2 values.
static void JUCE_CALLTYPE FloatVectorOperations::clip (float * dest, const float * src, float low, float high, int num) static noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static void JUCE_CALLTYPE FloatVectorOperations::clip (double * dest, const double * src, double low, double high, int num) static noexcept
Each element of dest is calculated by hard clipping the corresponding src element so that it is in the range specified by the arguments low and high.
static Range<float> JUCE_CALLTYPE FloatVectorOperations::findMinAndMax (const float * src, int numValues) static noexcept
Finds the miniumum and maximum values in the given array.
Referenced by AudioBlock< float >::findMinAndMax(), and AudioBuffer< float >::findMinMax().
static Range<double> JUCE_CALLTYPE FloatVectorOperations::findMinAndMax (const double * src, int numValues) static noexcept
Finds the miniumum and maximum values in the given array.
static float JUCE_CALLTYPE FloatVectorOperations::findMinimum (const float * src, int numValues) static noexcept
Finds the miniumum value in the given array.
static double JUCE_CALLTYPE FloatVectorOperations::findMinimum (const double * src, int numValues) static noexcept
Finds the miniumum value in the given array.
static float JUCE_CALLTYPE FloatVectorOperations::findMaximum (const float * src, int numValues) static noexcept
Finds the maximum value in the given array.
static double JUCE_CALLTYPE FloatVectorOperations::findMaximum (const double * src, int numValues) static noexcept
Finds the maximum value in the given array.
static void JUCE_CALLTYPE FloatVectorOperations::enableFlushToZeroMode (bool shouldEnable) static noexcept
On Intel CPUs, this method enables or disables the SSE flush-to-zero mode.
Effectively, this is a wrapper around a call to _MM_SET_FLUSH_ZERO_MODE
static void JUCE_CALLTYPE FloatVectorOperations::disableDenormalisedNumberSupport () static noexcept
On Intel CPUs, this method enables the SSE flush-to-zero and denormalised-are-zero modes.
This effectively sets the DAZ and FZ bits of the MXCSR register. It's a convenient thing to call before audio processing code where you really want to avoid denormalisation performance hits.
Macro Definition Documentation
#define JUCE_SNAP_TO_ZERO (n)
Typedef Documentation
typedef AudioBuffer<float> AudioSampleBuffer
A multi-channel buffer of 32-bit floating point audio samples.
This typedef is here for backwards compatibility with the older AudioSampleBuffer class, which was fixed for 32-bit data, but is otherwise the same as the new templated AudioBuffer class.
See Also
AudioBuffer