JUCE: players
players
juce_audio_utils
Classes
class AudioProcessorPlayer
An AudioIODeviceCallback object which streams audio through an AudioProcessor.
class SoundPlayer
A simple sound player that you can add to the AudioDeviceManager to play simple sounds.
Detailed Description
Class Documentation
class AudioProcessorPlayer
An AudioIODeviceCallback object which streams audio through an AudioProcessor.
To use one of these, just make it the callback used by your AudioIODevice, and give it a processor to use by calling setProcessor().
It's also a MidiInputCallback, so you can connect it to both an audio and midi input to send both streams through the processor.
See Also
AudioProcessor, AudioProcessorGraph
Public Member Functions
AudioProcessorPlayer (bool doDoublePrecisionProcessing=false)
virtual ~AudioProcessorPlayer ()
Destructor.
void setProcessor (AudioProcessor *processorToPlay)
Sets the processor that should be played.
AudioProcessor * getCurrentProcessor () const noexcept
Returns the current audio processor that is being played.
MidiMessageCollector & getMidiMessageCollector () noexcept
Returns a midi message collector that you can pass midi messages to if you want them to be injected into the midi stream that is being sent to the processor.
void setDoublePrecisionProcessing (bool doublePrecision)
Switch between double and single floating point precisions processing.
bool getDoublePrecisionProcessing ()
Returns true if this player processes internally processes the samples with double floating point precision.
void audioDeviceIOCallback (const float **, int, float **, int, int) override
void audioDeviceAboutToStart (AudioIODevice *) override
void audioDeviceStopped () override
void handleIncomingMidiMessage (MidiInput *, const MidiMessage &) override
Public Member Functions inherited from AudioIODeviceCallback
virtual ~AudioIODeviceCallback ()
Destructor.
virtual void audioDeviceError (const String &errorMessage)
This can be overridden to be told if the device generates an error while operating.
Public Member Functions inherited from MidiInputCallback
virtual ~MidiInputCallback ()
Destructor.
virtual void handlePartialSysexMessage (MidiInput *source, const uint8 *messageData, int numBytesSoFar, double timestamp)
Notification sent each time a packet of a multi-packet sysex message arrives.
Constructor & Destructor Documentation
AudioProcessorPlayer::AudioProcessorPlayer (bool doDoublePrecisionProcessing = false)
virtual AudioProcessorPlayer::~AudioProcessorPlayer () virtual
Destructor.
Member Function Documentation
void AudioProcessorPlayer::setProcessor (AudioProcessor * processorToPlay)
Sets the processor that should be played.
The processor that is passed in will not be deleted or owned by this object. To stop anything playing, pass a nullptr to this method.
Referenced by StandalonePluginHolder::startPlaying(), and StandalonePluginHolder::stopPlaying().
AudioProcessor* AudioProcessorPlayer::getCurrentProcessor () const noexcept
Returns the current audio processor that is being played.
MidiMessageCollector& AudioProcessorPlayer::getMidiMessageCollector () noexcept
Returns a midi message collector that you can pass midi messages to if you want them to be injected into the midi stream that is being sent to the processor.
Referenced by StandalonePluginHolder::startPlaying().
void AudioProcessorPlayer::setDoublePrecisionProcessing (bool doublePrecision)
Switch between double and single floating point precisions processing.
The audio IO callbacks will still operate in single floating point precision, however, all internal processing including the AudioProcessor will be processed in double floating point precision if the AudioProcessor supports it (see AudioProcessor::supportsDoublePrecisionProcessing()). Otherwise, the processing will remain single precision irrespective of the parameter doublePrecision.
bool AudioProcessorPlayer::getDoublePrecisionProcessing ()
Returns true if this player processes internally processes the samples with double floating point precision.
void AudioProcessorPlayer::audioDeviceIOCallback (const float ** , int , float ** , int , int) override virtual
Implements AudioIODeviceCallback.
void AudioProcessorPlayer::audioDeviceAboutToStart (AudioIODevice *) override virtual
Implements AudioIODeviceCallback.
void AudioProcessorPlayer::audioDeviceStopped () override virtual
Implements AudioIODeviceCallback.
void AudioProcessorPlayer::handleIncomingMidiMessage (MidiInput * , const MidiMessage &) override virtual
Implements MidiInputCallback.
class SoundPlayer
A simple sound player that you can add to the AudioDeviceManager to play simple sounds.
See Also
AudioProcessor, AudioProcessorGraph
Public Member Functions
SoundPlayer ()
virtual ~SoundPlayer ()
Destructor.
void play (const File &file)
Plays a sound from a file.
void play (const void *resourceData, size_t resourceSize)
Convenient method to play sound from a JUCE resource.
void play (AudioFormatReader *buffer, bool deleteWhenFinished=false)
Plays the sound from an audio format reader.
void play (PositionableAudioSource *audioSource, bool deleteWhenFinished=false, double sampleRateOfSource=0.0)
Plays the sound from a positionable audio source.
void play (AudioSampleBuffer *buffer, bool deleteWhenFinished=false, bool playOnAllOutputChannels=false)
Plays the sound from an audio sample buffer.
void playTestSound ()
Plays a beep through the current audio device.
void audioDeviceIOCallback (const float **, int, float **, int, int) override
void audioDeviceAboutToStart (AudioIODevice *) override
void audioDeviceStopped () override
void audioDeviceError (const String &errorMessage) override
Public Member Functions inherited from AudioIODeviceCallback
virtual ~AudioIODeviceCallback ()
Destructor.
Constructor & Destructor Documentation
SoundPlayer::SoundPlayer ()
virtual SoundPlayer::~SoundPlayer () virtual
Destructor.
Member Function Documentation
void SoundPlayer::play (const File & file)
Plays a sound from a file.
void SoundPlayer::play (const void * resourceData, size_t resourceSize)
Convenient method to play sound from a JUCE resource.
void SoundPlayer::play (AudioFormatReader * buffer, bool deleteWhenFinished = false)
Plays the sound from an audio format reader.
If deleteWhenFinished is true then the format reader will be automatically deleted once the sound has finished playing.
void SoundPlayer::play (PositionableAudioSource * audioSource, bool deleteWhenFinished = false, double sampleRateOfSource = 0.0)
Plays the sound from a positionable audio source.
This will output the sound coming from a positionable audio source. This gives you slightly more control over the sound playback compared to the other playSound methods. For example, if you would like to stop the sound prematurely you can call this method with a TransportAudioSource and then call audioSource->stop. Note that, you must call audioSource->start to start the playback, if your audioSource is a TransportAudioSource.
The audio device manager will not hold any references to this audio source once the audio source has stopped playing for any reason, for example when the sound has finished playing or when you have called audioSource->stop. Therefore, calling audioSource->start() on a finished audioSource will not restart the sound again. If this is desired simply call playSound with the same audioSource again.
Parameters
audioSource the audio source to play
deleteWhenFinished If this is true then the audio source will be deleted once the device manager has finished playing.
sampleRateOfSource The sample rate of the source. If this is zero, JUCE will assume that the sample rate is the same as the audio output device.
void SoundPlayer::play (AudioSampleBuffer * buffer, bool deleteWhenFinished = false, bool playOnAllOutputChannels = false)
Plays the sound from an audio sample buffer.
This will output the sound contained in an audio sample buffer. If deleteWhenFinished is true then the audio sample buffer will be automatically deleted once the sound has finished playing.
If playOnAllOutputChannels is true, then if there are more output channels than buffer channels, then the ones that are available will be re-used on multiple outputs so that something is sent to all output channels. If it is false, then the buffer will just be played on the first output channels.
void SoundPlayer::playTestSound ()
Plays a beep through the current audio device.
This is here to allow the audio setup UI panels to easily include a "test" button so that the user can check where the audio is coming from.
void SoundPlayer::audioDeviceIOCallback (const float ** , int , float ** , int , int) override virtual
Implements AudioIODeviceCallback.
void SoundPlayer::audioDeviceAboutToStart (AudioIODevice *) override virtual
Implements AudioIODeviceCallback.
void SoundPlayer::audioDeviceStopped () override virtual
Implements AudioIODeviceCallback.
void SoundPlayer::audioDeviceError (const String & errorMessage) override virtual
Reimplemented from AudioIODeviceCallback.