JUCE: format
format
juce_audio_formats
Classes
class AudioFormat
Subclasses of AudioFormat are used to read and write different audio file formats.
class AudioFormatManager
A class for keeping a list of available audio formats, and for deciding which one to use to open a given file.
class AudioFormatReader
Reads samples from an audio file stream.
class AudioFormatReaderSource
A type of AudioSource that will read from an AudioFormatReader.
class AudioFormatWriter
Writes samples to an audio file stream.
class AudioSubsectionReader
This class is used to wrap an AudioFormatReader and only read from a subsection of the file.
class BufferingAudioReader
An AudioFormatReader that uses a background thread to pre-read data from another reader.
class MemoryMappedAudioFormatReader
A specialised type of AudioFormatReader that uses a MemoryMappedFile to read directly from an audio file.
Detailed Description
Class Documentation
class AudioFormat
Subclasses of AudioFormat are used to read and write different audio file formats.
See Also
AudioFormatReader, AudioFormatWriter, WavAudioFormat, AiffAudioFormat
Public Member Functions
virtual ~AudioFormat ()
Destructor.
const String & getFormatName () const
Returns the name of this format.
const StringArray & getFileExtensions () const
Returns all the file extensions that might apply to a file of this format.
virtual bool canHandleFile (const File &fileToTest)
Returns true if this the given file can be read by this format.
virtual Array< int > getPossibleSampleRates ()=0
Returns a set of sample rates that the format can read and write.
virtual Array< int > getPossibleBitDepths ()=0
Returns a set of bit depths that the format can read and write.
virtual bool canDoStereo ()=0
Returns true if the format can do 2-channel audio.
virtual bool canDoMono ()=0
Returns true if the format can do 1-channel audio.
virtual bool isCompressed ()
Returns true if the format uses compressed data.
virtual bool isChannelLayoutSupported (const AudioChannelSet &channelSet)
Returns true if the channel layout is supported by this format.
virtual StringArray getQualityOptions ()
Returns a list of different qualities that can be used when writing.
virtual AudioFormatReader * createReaderFor (InputStream *sourceStream, bool deleteStreamIfOpeningFails)=0
Tries to create an object that can read from a stream containing audio data in this format.
virtual
MemoryMappedAudioFormatReader * createMemoryMappedReader (const File &file)
Attempts to create a MemoryMappedAudioFormatReader, if possible for this format.
virtual
MemoryMappedAudioFormatReader * createMemoryMappedReader (FileInputStream *fin)
virtual AudioFormatWriter * createWriterFor (OutputStream *streamToWriteTo, double sampleRateToUse, unsigned int numberOfChannels, int bitsPerSample, const StringPairArray &metadataValues, int qualityOptionIndex)=0
Tries to create an object that can write to a stream with this audio format.
virtual AudioFormatWriter * createWriterFor (OutputStream *streamToWriteTo, double sampleRateToUse, const AudioChannelSet &channelLayout, int bitsPerSample, const StringPairArray &metadataValues, int qualityOptionIndex)
Tries to create an object that can write to a stream with this audio format.
Protected Member Functions
AudioFormat (String formatName, StringArray fileExtensions)
Creates an AudioFormat object.
AudioFormat (StringRef formatName, StringRef fileExtensions)
Creates an AudioFormat object.
Constructor & Destructor Documentation
virtual AudioFormat::~AudioFormat () virtual
Destructor.
AudioFormat::AudioFormat (String formatName, StringArray fileExtensions) protected
Creates an AudioFormat object.
Parameters
formatName this sets the value that will be returned by getFormatName()
fileExtensions an array of file extensions - these will be returned by getFileExtensions()
AudioFormat::AudioFormat (StringRef formatName, StringRef fileExtensions) protected
Creates an AudioFormat object.
Parameters
formatName this sets the value that will be returned by getFormatName()
fileExtensions a whitespace-separated list of file extensions - these will be returned by getFileExtensions()
Member Function Documentation
const String& AudioFormat::getFormatName () const
Returns the name of this format.
e.g. "WAV file" or "AIFF file"
const StringArray& AudioFormat::getFileExtensions () const
Returns all the file extensions that might apply to a file of this format.
The first item will be the one that's preferred when creating a new file.
So for a wav file this might just return ".wav"; for an AIFF file it might return two items, ".aif" and ".aiff"
virtual bool AudioFormat::canHandleFile (const File & fileToTest) virtual
Returns true if this the given file can be read by this format.
Subclasses shouldn't do too much work here, just check the extension or file type. The base class implementation just checks the file's extension against one of the ones that was registered in the constructor.
Reimplemented in AiffAudioFormat, and LAMEEncoderAudioFormat.
virtual Array<int> AudioFormat::getPossibleSampleRates () pure virtual
Returns a set of sample rates that the format can read and write.
Implemented in WavAudioFormat, AiffAudioFormat, CoreAudioFormat, LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, OggVorbisAudioFormat, and WindowsMediaAudioFormat.
virtual Array<int> AudioFormat::getPossibleBitDepths () pure virtual
Returns a set of bit depths that the format can read and write.
Implemented in WavAudioFormat, AiffAudioFormat, CoreAudioFormat, LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, OggVorbisAudioFormat, and WindowsMediaAudioFormat.
virtual bool AudioFormat::canDoStereo () pure virtual
Returns true if the format can do 2-channel audio.
Implemented in WavAudioFormat, AiffAudioFormat, CoreAudioFormat, LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, OggVorbisAudioFormat, and WindowsMediaAudioFormat.
virtual bool AudioFormat::canDoMono () pure virtual
Returns true if the format can do 1-channel audio.
Implemented in WavAudioFormat, AiffAudioFormat, CoreAudioFormat, LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, OggVorbisAudioFormat, and WindowsMediaAudioFormat.
virtual bool AudioFormat::isCompressed () virtual
Returns true if the format uses compressed data.
Reimplemented in LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, OggVorbisAudioFormat, and WindowsMediaAudioFormat.
virtual bool AudioFormat::isChannelLayoutSupported (const AudioChannelSet & channelSet) virtual
Returns true if the channel layout is supported by this format.
Reimplemented in WavAudioFormat.
virtual StringArray AudioFormat::getQualityOptions () virtual
Returns a list of different qualities that can be used when writing.
Non-compressed formats will just return an empty array, but for something like Ogg-Vorbis or MP3, it might return a list of bit-rates, etc.
When calling createWriterFor(), an index from this array is passed in to tell the format which option is required.
Reimplemented in LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, and OggVorbisAudioFormat.
virtual AudioFormatReader* AudioFormat::createReaderFor (InputStream * sourceStream, bool deleteStreamIfOpeningFails) pure virtual
Tries to create an object that can read from a stream containing audio data in this format.
The reader object that is returned can be used to read from the stream, and should then be deleted by the caller.
Parameters
sourceStream the stream to read from - the AudioFormatReader object that is returned will delete this stream when it no longer needs it.
deleteStreamIfOpeningFails if no reader can be created, this determines whether this method should delete the stream object that was passed-in. (If a valid reader is returned, it will always be in charge of deleting the stream, so this parameter is ignored)
See Also
AudioFormatReader
Implemented in WavAudioFormat, OggVorbisAudioFormat, AiffAudioFormat, CoreAudioFormat, LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, and WindowsMediaAudioFormat.
virtual MemoryMappedAudioFormatReader* AudioFormat::createMemoryMappedReader (const File & file) virtual
Attempts to create a MemoryMappedAudioFormatReader, if possible for this format.
If the format does not support this, the method will return nullptr;
Reimplemented in WavAudioFormat, and AiffAudioFormat.
virtual MemoryMappedAudioFormatReader* AudioFormat::createMemoryMappedReader (FileInputStream * fin) virtual
Reimplemented in WavAudioFormat, and AiffAudioFormat.
virtual AudioFormatWriter* AudioFormat::createWriterFor (OutputStream * streamToWriteTo, double sampleRateToUse, unsigned int numberOfChannels, int bitsPerSample, const StringPairArray & metadataValues, int qualityOptionIndex) pure virtual
Tries to create an object that can write to a stream with this audio format.
The writer object that is returned can be used to write to the stream, and should then be deleted by the caller.
If the stream can't be created for some reason (e.g. the parameters passed in here aren't suitable), this will return nullptr.
Parameters
streamToWriteTo the stream that the data will go to - this will be deleted by the AudioFormatWriter object when it's no longer needed. If no AudioFormatWriter can be created by this method, the stream will NOT be deleted, so that the caller can re-use it to try to open a different format, etc
sampleRateToUse the sample rate for the file, which must be one of the ones returned by getPossibleSampleRates()
numberOfChannels the number of channels - this must be either 1 or 2, and the choice will depend on the results of canDoMono() and canDoStereo()
bitsPerSample the bits per sample to use - this must be one of the values returned by getPossibleBitDepths()
metadataValues a set of metadata values that the writer should try to write to the stream. Exactly what these are depends on the format, and the subclass doesn't actually have to do anything with them if it doesn't want to. Have a look at the specific format implementation classes to see possible values that can be used
qualityOptionIndex the index of one of compression qualities returned by the getQualityOptions() method. If there aren't any quality options for this format, just pass 0 in this parameter, as it'll be ignored
See Also
AudioFormatWriter
Implemented in WavAudioFormat, OggVorbisAudioFormat, AiffAudioFormat, CoreAudioFormat, LAMEEncoderAudioFormat, MP3AudioFormat, FlacAudioFormat, and WindowsMediaAudioFormat.
virtual AudioFormatWriter* AudioFormat::createWriterFor (OutputStream * streamToWriteTo, double sampleRateToUse, const AudioChannelSet & channelLayout, int bitsPerSample, const StringPairArray & metadataValues, int qualityOptionIndex) virtual
Tries to create an object that can write to a stream with this audio format.
The writer object that is returned can be used to write to the stream, and should then be deleted by the caller.
If the stream can't be created for some reason (e.g. the parameters passed in here aren't suitable), this will return nullptr.
Parameters
streamToWriteTo the stream that the data will go to - this will be deleted by the AudioFormatWriter object when it's no longer needed. If no AudioFormatWriter can be created by this method, the stream will NOT be deleted, so that the caller can re-use it to try to open a different format, etc
sampleRateToUse the sample rate for the file, which must be one of the ones returned by getPossibleSampleRates()
channelLayout the channel layout for the file. Use isChannelLayoutSupported to check if the writer supports this layout.
bitsPerSample the bits per sample to use - this must be one of the values returned by getPossibleBitDepths()
metadataValues a set of metadata values that the writer should try to write to the stream. Exactly what these are depends on the format, and the subclass doesn't actually have to do anything with them if it doesn't want to. Have a look at the specific format implementation classes to see possible values that can be used
qualityOptionIndex the index of one of compression qualities returned by the getQualityOptions() method. If there aren't any quality options for this format, just pass 0 in this parameter, as it'll be ignored
See Also
AudioFormatWriter
Reimplemented in WavAudioFormat.
class AudioFormatManager
A class for keeping a list of available audio formats, and for deciding which one to use to open a given file.
After creating an AudioFormatManager object, you should call registerFormat() or registerBasicFormats() to give it a list of format types that it can use.
See Also
AudioFormat
Public Member Functions
AudioFormatManager ()
Creates an empty format manager.
~AudioFormatManager ()
Destructor.
void registerFormat (AudioFormat *newFormat, bool makeThisTheDefaultFormat)
Adds a format to the manager's list of available file types.
void registerBasicFormats ()
Handy method to make it easy to register the formats that come with Juce.
void clearFormats ()
Clears the list of known formats.
int getNumKnownFormats () const
Returns the number of currently registered file formats.
AudioFormat * getKnownFormat (int index) const
Returns one of the registered file formats.
AudioFormat ** begin () const noexcept
Iterator access to the list of known formats.
AudioFormat ** end () const noexcept
Iterator access to the list of known formats.
AudioFormat * findFormatForFileExtension (const String &fileExtension) const
Looks for which of the known formats is listed as being for a given file extension.
AudioFormat * getDefaultFormat () const
Returns the format which has been set as the default one.
String getWildcardForAllFormats () const
Returns a set of wildcards for file-matching that contains the extensions for all known formats.
AudioFormatReader * createReaderFor (const File &audioFile)
Searches through the known formats to try to create a suitable reader for this file.
AudioFormatReader * createReaderFor (InputStream *audioFileStream)
Searches through the known formats to try to create a suitable reader for this stream.
Constructor & Destructor Documentation
AudioFormatManager::AudioFormatManager ()
Creates an empty format manager.
Before it'll be any use, you'll need to call registerFormat() with all the formats you want it to be able to recognise.
AudioFormatManager::~AudioFormatManager ()
Destructor.
Member Function Documentation
void AudioFormatManager::registerFormat (AudioFormat * newFormat, bool makeThisTheDefaultFormat)
Adds a format to the manager's list of available file types.
The object passed-in will be deleted by this object, so don't keep a pointer to it!
If makeThisTheDefaultFormat is true, then the getDefaultFormat() method will return this one when called.
void AudioFormatManager::registerBasicFormats ()
Handy method to make it easy to register the formats that come with Juce.
Currently, this will add WAV and AIFF to the list.
void AudioFormatManager::clearFormats ()
Clears the list of known formats.
int AudioFormatManager::getNumKnownFormats () const
Returns the number of currently registered file formats.
AudioFormat* AudioFormatManager::getKnownFormat (int index) const
Returns one of the registered file formats.
AudioFormat** AudioFormatManager::begin () const noexcept
Iterator access to the list of known formats.
AudioFormat** AudioFormatManager::end () const noexcept
Iterator access to the list of known formats.
AudioFormat* AudioFormatManager::findFormatForFileExtension (const String & fileExtension) const
Looks for which of the known formats is listed as being for a given file extension.
The extension may have a dot before it, so e.g. ".wav" or "wav" are both ok.
AudioFormat* AudioFormatManager::getDefaultFormat () const
Returns the format which has been set as the default one.
You can set a format as being the default when it is registered. It's useful when you want to write to a file, because the best format may change between platforms, e.g. AIFF is preferred on the Mac, WAV on Windows.
If none has been set as the default, this method will just return the first one in the list.
String AudioFormatManager::getWildcardForAllFormats () const
Returns a set of wildcards for file-matching that contains the extensions for all known formats.
E.g. if might return "*.wav;*.aiff" if it just knows about wavs and aiffs.
AudioFormatReader* AudioFormatManager::createReaderFor (const File & audioFile)
Searches through the known formats to try to create a suitable reader for this file.
If none of the registered formats can open the file, it'll return nullptr. It's the caller's responsibility to delete the reader that is returned.
AudioFormatReader* AudioFormatManager::createReaderFor (InputStream * audioFileStream)
Searches through the known formats to try to create a suitable reader for this stream.
The stream object that is passed-in will be deleted by this method or by the reader that is returned, so the caller should not keep any references to it.
The stream that is passed-in must be capable of being repositioned so that all the formats can have a go at opening it.
If none of the registered formats can open the stream, it'll return nullptr. If it returns a reader, it's the caller's responsibility to delete the reader.
class AudioFormatReader
Reads samples from an audio file stream.
A subclass that reads a specific type of audio format will be created by an AudioFormat object.
See Also
AudioFormat, AudioFormatWriter
Public Member Functions
virtual ~AudioFormatReader ()
Destructor.
const String & getFormatName () const noexcept
Returns a description of what type of format this is.
bool read (int *const *destSamples, int numDestChannels, int64 startSampleInSource, int numSamplesToRead, bool fillLeftoverChannelsWithCopies)
Reads samples from the stream.
void read (AudioSampleBuffer *buffer, int startSampleInDestBuffer, int numSamples, int64 readerStartSample, bool useReaderLeftChan, bool useReaderRightChan)
Fills a section of an AudioSampleBuffer from this reader.
virtual void readMaxLevels (int64 startSample, int64 numSamples, Range< float > *results, int numChannelsToRead)
Finds the highest and lowest sample levels from a section of the audio stream.
virtual void readMaxLevels (int64 startSample, int64 numSamples, float &lowestLeft, float &highestLeft, float &lowestRight, float &highestRight)
Finds the highest and lowest sample levels from a section of the audio stream.
int64 searchForLevel (int64 startSample, int64 numSamplesToSearch, double magnitudeRangeMinimum, double magnitudeRangeMaximum, int minimumConsecutiveSamples)
Scans the source looking for a sample whose magnitude is in a specified range.
virtual AudioChannelSet getChannelLayout ()
Get the channel layout of the audio stream.
virtual bool readSamples (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples)=0
Subclasses must implement this method to perform the low-level read operation.
Public Attributes
double sampleRate
The sample-rate of the stream.
unsigned int bitsPerSample
The number of bits per sample, e.g.
int64 lengthInSamples
The total number of samples in the audio stream.
unsigned int numChannels
The total number of channels in the audio stream.
bool usesFloatingPointData
Indicates whether the data is floating-point or fixed.
StringPairArray metadataValues
A set of metadata values that the reader has pulled out of the stream.
InputStream * input
The input stream, for use by subclasses.
Protected Member Functions
AudioFormatReader (InputStream *sourceStream, const String &formatName)
Creates an AudioFormatReader object.
Static Protected Member Functions
static void clearSamplesBeyondAvailableLength (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int &numSamples, int64 fileLengthInSamples)
Used by AudioFormatReader subclasses to clear any parts of the data blocks that lie beyond the end of their available length.
Constructor & Destructor Documentation
AudioFormatReader::AudioFormatReader (InputStream * sourceStream, const String & formatName) protected
Creates an AudioFormatReader object.
Parameters
sourceStream the stream to read from - this will be deleted by this object when it is no longer needed. (Some specialised readers might not use this parameter and can leave it as nullptr).
formatName the description that will be returned by the getFormatName() method
virtual AudioFormatReader::~AudioFormatReader () virtual
Destructor.
Member Function Documentation
const String& AudioFormatReader::getFormatName () const noexcept
Returns a description of what type of format this is.
E.g. "AIFF"
bool AudioFormatReader::read (int *const * destSamples, int numDestChannels, int64 startSampleInSource, int numSamplesToRead, bool fillLeftoverChannelsWithCopies)
Reads samples from the stream.
Parameters
destSamples an array of buffers into which the sample data for each channel will be written. If the format is fixed-point, each channel will be written as an array of 32-bit signed integers using the full range -0x80000000 to 0x7fffffff, regardless of the source's bit-depth. If it is a floating-point format, you should cast the resulting array to a (float**) to get the values (in the range -1.0 to 1.0 or beyond) If the format is stereo, then destSamples[0] is the left channel data, and destSamples[1] is the right channel. The numDestChannels parameter indicates how many pointers this array contains, but some of these pointers can be null if you don't want to read data for some of the channels
numDestChannels the number of array elements in the destChannels array
startSampleInSource the position in the audio file or stream at which the samples should be read, as a number of samples from the start of the stream. It's ok for this to be beyond the start or end of the available data - any samples that are out-of-range will be returned as zeros.
numSamplesToRead the number of samples to read. If this is greater than the number of samples that the file or stream contains. the result will be padded with zeros
fillLeftoverChannelsWithCopies if true, this indicates that if there's no source data available for some of the channels that you pass in, then they should be filled with copies of valid source channels. E.g. if you're reading a mono file and you pass 2 channels to this method, then if fillLeftoverChannelsWithCopies is true, both destination channels will be filled with the same data from the file's single channel. If fillLeftoverChannelsWithCopies was false, then only the first channel would be filled with the file's contents, and the second would be cleared. If there are many channels, e.g. you try to read 4 channels from a stereo file, then the last 3 would all end up with copies of the same data.
Returns
true if the operation succeeded, false if there was an error. Note that reading sections of data beyond the extent of the stream isn't an error - the reader should just return zeros for these regions
See Also
readMaxLevels
void AudioFormatReader::read (AudioSampleBuffer * buffer, int startSampleInDestBuffer, int numSamples, int64 readerStartSample, bool useReaderLeftChan, bool useReaderRightChan)
Fills a section of an AudioSampleBuffer from this reader.
This will convert the reader's fixed- or floating-point data to the buffer's floating-point format, and will try to intelligently cope with mismatches between the number of channels in the reader and the buffer.
virtual void AudioFormatReader::readMaxLevels (int64 startSample, int64 numSamples, Range< float > * results, int numChannelsToRead) virtual
Finds the highest and lowest sample levels from a section of the audio stream.
This will read a block of samples from the stream, and measure the highest and lowest sample levels from the channels in that section, returning these as normalised floating-point levels.
Parameters
startSample the offset into the audio stream to start reading from. It's ok for this to be beyond the start or end of the stream.
numSamples how many samples to read
results this array will be filled with Range values for each channel. The array must contain numChannels elements.
numChannelsToRead the number of channels of data to scan. This must be more than zero, but not more than the total number of channels that the reader contains
See Also
read
Reimplemented in AudioSubsectionReader.
virtual void AudioFormatReader::readMaxLevels (int64 startSample, int64 numSamples, float & lowestLeft, float & highestLeft, float & lowestRight, float & highestRight) virtual
Finds the highest and lowest sample levels from a section of the audio stream.
This will read a block of samples from the stream, and measure the highest and lowest sample levels from the channels in that section, returning these as normalised floating-point levels.
Parameters
startSample the offset into the audio stream to start reading from. It's ok for this to be beyond the start or end of the stream.
numSamples how many samples to read
lowestLeft on return, this is the lowest absolute sample from the left channel
highestLeft on return, this is the highest absolute sample from the left channel
lowestRight on return, this is the lowest absolute sample from the right channel (if there is one)
highestRight on return, this is the highest absolute sample from the right channel (if there is one)
See Also
read
int64 AudioFormatReader::searchForLevel (int64 startSample, int64 numSamplesToSearch, double magnitudeRangeMinimum, double magnitudeRangeMaximum, int minimumConsecutiveSamples)
Scans the source looking for a sample whose magnitude is in a specified range.
This will read from the source, either forwards or backwards between two sample positions, until it finds a sample whose magnitude lies between two specified levels.
If it finds a suitable sample, it returns its position; if not, it will return -1.
There's also a minimumConsecutiveSamples setting to help avoid spikes or zero-crossing points when you're searching for a continuous range of samples
Parameters
startSample the first sample to look at
numSamplesToSearch the number of samples to scan. If this value is negative, the search will go backwards
magnitudeRangeMinimum the lowest magnitude (inclusive) that is considered a hit, from 0 to 1.0
magnitudeRangeMaximum the highest magnitude (inclusive) that is considered a hit, from 0 to 1.0
minimumConsecutiveSamples if this is > 0, the method will only look for a sequence of this many consecutive samples, all of which lie within the target range. When it finds such a sequence, it returns the position of the first in-range sample it found (i.e. the earliest one if scanning forwards, the latest one if scanning backwards)
virtual AudioChannelSet AudioFormatReader::getChannelLayout () virtual
Get the channel layout of the audio stream.
virtual bool AudioFormatReader::readSamples (int ** destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples) pure virtual
Subclasses must implement this method to perform the low-level read operation.
Callers should use read() instead of calling this directly.
Parameters
destSamples the array of destination buffers to fill. Some of these pointers may be null
numDestChannels the number of items in the destSamples array. This value is guaranteed not to be greater than the number of channels that this reader object contains
startOffsetInDestBuffer the number of samples from the start of the dest data at which to begin writing
startSampleInFile the number of samples into the source data at which to begin reading. This value is guaranteed to be >= 0.
numSamples the number of samples to read
Implemented in AudioCDReader, AudioSubsectionReader, and BufferingAudioReader.
static void AudioFormatReader::clearSamplesBeyondAvailableLength (int ** destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int & numSamples, int64 fileLengthInSamples) static protected
Used by AudioFormatReader subclasses to clear any parts of the data blocks that lie beyond the end of their available length.
References jassert, and zeromem().
Member Data Documentation
double AudioFormatReader::sampleRate
The sample-rate of the stream.
unsigned int AudioFormatReader::bitsPerSample
The number of bits per sample, e.g.
16, 24, 32.
int64 AudioFormatReader::lengthInSamples
The total number of samples in the audio stream.
unsigned int AudioFormatReader::numChannels
The total number of channels in the audio stream.
bool AudioFormatReader::usesFloatingPointData
Indicates whether the data is floating-point or fixed.
StringPairArray AudioFormatReader::metadataValues
A set of metadata values that the reader has pulled out of the stream.
Exactly what these values are depends on the format, so you can check out the format implementation code to see what kind of stuff they understand.
InputStream* AudioFormatReader::input
The input stream, for use by subclasses.
class AudioFormatReaderSource
A type of AudioSource that will read from an AudioFormatReader.
See Also
PositionableAudioSource, AudioTransportSource, BufferingAudioSource
Public Member Functions
AudioFormatReaderSource (AudioFormatReader *sourceReader, bool deleteReaderWhenThisIsDeleted)
Creates an AudioFormatReaderSource for a given reader.
~AudioFormatReaderSource ()
Destructor.
void setLooping (bool shouldLoop) override
Toggles loop-mode.
bool isLooping () const override
Returns whether loop-mode is turned on or not.
AudioFormatReader * getAudioFormatReader () const noexcept
Returns the reader that's being used.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Implementation of the AudioSource method.
void setNextReadPosition (int64 newPosition) override
Implements the PositionableAudioSource method.
int64 getNextReadPosition () const override
Implements the PositionableAudioSource method.
int64 getTotalLength () const override
Implements the PositionableAudioSource method.
Public Member Functions inherited from PositionableAudioSource
~PositionableAudioSource ()
Destructor.
Public Member Functions inherited from AudioSource
virtual ~AudioSource ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from PositionableAudioSource
PositionableAudioSource () noexcept
Creates the PositionableAudioSource.
Protected Member Functions inherited from AudioSource
AudioSource () noexcept
Creates an AudioSource.
Constructor & Destructor Documentation
AudioFormatReaderSource::AudioFormatReaderSource (AudioFormatReader * sourceReader, bool deleteReaderWhenThisIsDeleted)
Creates an AudioFormatReaderSource for a given reader.
Parameters
sourceReader the reader to use as the data source - this must not be null
deleteReaderWhenThisIsDeleted if true, the reader passed-in will be deleted when this object is deleted; if false it will be left up to the caller to manage its lifetime
AudioFormatReaderSource::~AudioFormatReaderSource ()
Destructor.
Member Function Documentation
void AudioFormatReaderSource::setLooping (bool shouldLoop) override virtual
Toggles loop-mode.
If set to true, it will continuously loop the input source. If false, it will just emit silence after the source has finished.
See Also
isLooping
Reimplemented from PositionableAudioSource.
bool AudioFormatReaderSource::isLooping () const override virtual
Returns whether loop-mode is turned on or not.
Implements PositionableAudioSource.
AudioFormatReader* AudioFormatReaderSource::getAudioFormatReader () const noexcept
Returns the reader that's being used.
void AudioFormatReaderSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void AudioFormatReaderSource::releaseResources () override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void AudioFormatReaderSource::getNextAudioBlock (const AudioSourceChannelInfo &) override virtual
Implementation of the AudioSource method.
Implements AudioSource.
void AudioFormatReaderSource::setNextReadPosition (int64 newPosition) override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
int64 AudioFormatReaderSource::getNextReadPosition () const override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
int64 AudioFormatReaderSource::getTotalLength () const override virtual
Implements the PositionableAudioSource method.
Implements PositionableAudioSource.
class AudioFormatWriter
Writes samples to an audio file stream.
A subclass that writes a specific type of audio format will be created by an AudioFormat object.
After creating one of these with the AudioFormat::createWriterFor() method you can call its write() method to store the samples, and then delete it.
See Also
AudioFormat, AudioFormatReader
Public Member Functions
virtual ~AudioFormatWriter ()
Destructor.
const String & getFormatName () const noexcept
Returns a description of what type of format this is.
virtual bool write (const int **samplesToWrite, int numSamples)=0
Writes a set of samples to the audio stream.
virtual bool flush ()
Some formats may support a flush operation that makes sure the file is in a valid state before carrying on.
bool writeFromAudioReader (AudioFormatReader &reader, int64 startSample, int64 numSamplesToRead)
Reads a section of samples from an AudioFormatReader, and writes these to the output.
bool writeFromAudioSource (AudioSource &source, int numSamplesToRead, int samplesPerBlock=2048)
Reads some samples from an AudioSource, and writes these to the output.
bool writeFromAudioSampleBuffer (const AudioSampleBuffer &source, int startSample, int numSamples)
Writes some samples from an AudioSampleBuffer.
bool writeFromFloatArrays (const float *const *channels, int numChannels, int numSamples)
Writes some samples from a set of float data channels.
double getSampleRate () const noexcept
Returns the sample rate being used.
int getNumChannels () const noexcept
Returns the number of channels being written.
int getBitsPerSample () const noexcept
Returns the bit-depth of the data being written.
bool isFloatingPoint () const noexcept
Returns true if it's a floating-point format, false if it's fixed-point.
Protected Member Functions
AudioFormatWriter (OutputStream *destStream, const String &formatName, double sampleRate, unsigned int numberOfChannels, unsigned int bitsPerSample)
Creates an AudioFormatWriter object.
AudioFormatWriter (OutputStream *destStream, const String &formatName, double sampleRate, const AudioChannelSet &audioChannelLayout, unsigned int bitsPerSample)
Creates an AudioFormatWriter object.
Protected Attributes
double sampleRate
The sample rate of the stream.
unsigned int numChannels
The number of channels being written to the stream.
unsigned int bitsPerSample
The bit depth of the file.
bool usesFloatingPointData
True if it's a floating-point format, false if it's fixed-point.
AudioChannelSet channelLayout
The audio channel layout that the writer should use.
OutputStream * output
The output stream for use by subclasses.
Constructor & Destructor Documentation
AudioFormatWriter::AudioFormatWriter (OutputStream * destStream, const String & formatName, double sampleRate, unsigned int numberOfChannels, unsigned int bitsPerSample) protected
Creates an AudioFormatWriter object.
Parameters
destStream the stream to write to - this will be deleted by this object when it is no longer needed
formatName the description that will be returned by the getFormatName() method
sampleRate the sample rate to use - the base class just stores this value, it doesn't do anything with it
numberOfChannels the number of channels to write - the base class just stores this value, it doesn't do anything with it
bitsPerSample the bit depth of the stream - the base class just stores this value, it doesn't do anything with it
AudioFormatWriter::AudioFormatWriter (OutputStream * destStream, const String & formatName, double sampleRate, const AudioChannelSet & audioChannelLayout, unsigned int bitsPerSample) protected
Creates an AudioFormatWriter object.
Parameters
destStream the stream to write to - this will be deleted by this object when it is no longer needed
formatName the description that will be returned by the getFormatName() method
sampleRate the sample rate to use - the base class just stores this value, it doesn't do anything with it
audioChannelLayout the channel layout to use for the writer - the base class just stores this value, it doesn't do anything with it
bitsPerSample the bit depth of the stream - the base class just stores this value, it doesn't do anything with it
virtual AudioFormatWriter::~AudioFormatWriter () virtual
Destructor.
Member Function Documentation
const String& AudioFormatWriter::getFormatName () const noexcept
Returns a description of what type of format this is.
E.g. "AIFF file"
virtual bool AudioFormatWriter::write (const int ** samplesToWrite, int numSamples) pure virtual
Writes a set of samples to the audio stream.
Note that if you're trying to write the contents of an AudioSampleBuffer, you can use writeFromAudioSampleBuffer().
Parameters
samplesToWrite an array of arrays containing the sample data for each channel to write. This is a zero-terminated array of arrays, and can contain a different number of channels than the actual stream uses, and the writer should do its best to cope with this. If the format is fixed-point, each channel will be formatted as an array of signed integers using the full 32-bit range -0x80000000 to 0x7fffffff, regardless of the source's bit-depth. If it is a floating-point format, you should treat the arrays as arrays of floats, and just cast it to an (int**) to pass it into the method.
numSamples the number of samples to write
virtual bool AudioFormatWriter::flush () virtual
Some formats may support a flush operation that makes sure the file is in a valid state before carrying on.
If supported, this means that by calling flush periodically when writing data to a large file, then it should still be left in a readable state if your program crashes. It goes without saying that this method must be called from the same thread that's calling write()! If the format supports flushing and the operation succeeds, this returns true.
bool AudioFormatWriter::writeFromAudioReader (AudioFormatReader & reader, int64 startSample, int64 numSamplesToRead)
Reads a section of samples from an AudioFormatReader, and writes these to the output.
This will take care of any floating-point conversion that's required to convert between the two formats. It won't deal with sample-rate conversion, though.
If numSamplesToRead < 0, it will write the entire length of the reader.
Returns
false if it can't read or write properly during the operation
bool AudioFormatWriter::writeFromAudioSource (AudioSource & source, int numSamplesToRead, int samplesPerBlock = 2048)
Reads some samples from an AudioSource, and writes these to the output.
The source must already have been initialised with the AudioSource::prepareToPlay() method
Parameters
source the source to read from
numSamplesToRead total number of samples to read and write
samplesPerBlock the maximum number of samples to fetch from the source
Returns
false if it can't read or write properly during the operation
bool AudioFormatWriter::writeFromAudioSampleBuffer (const AudioSampleBuffer & source, int startSample, int numSamples)
Writes some samples from an AudioSampleBuffer.
bool AudioFormatWriter::writeFromFloatArrays (const float *const * channels, int numChannels, int numSamples)
Writes some samples from a set of float data channels.
double AudioFormatWriter::getSampleRate () const noexcept
Returns the sample rate being used.
int AudioFormatWriter::getNumChannels () const noexcept
Returns the number of channels being written.
int AudioFormatWriter::getBitsPerSample () const noexcept
Returns the bit-depth of the data being written.
bool AudioFormatWriter::isFloatingPoint () const noexcept
Returns true if it's a floating-point format, false if it's fixed-point.
Member Data Documentation
double AudioFormatWriter::sampleRate protected
The sample rate of the stream.
unsigned int AudioFormatWriter::numChannels protected
The number of channels being written to the stream.
unsigned int AudioFormatWriter::bitsPerSample protected
The bit depth of the file.
bool AudioFormatWriter::usesFloatingPointData protected
True if it's a floating-point format, false if it's fixed-point.
AudioChannelSet AudioFormatWriter::channelLayout protected
The audio channel layout that the writer should use.
OutputStream* AudioFormatWriter::output protected
The output stream for use by subclasses.
class AudioSubsectionReader
This class is used to wrap an AudioFormatReader and only read from a subsection of the file.
So if you have a reader which can read a 1000 sample file, you could wrap it in one of these to only access, e.g. samples 100 to 200, and any samples outside that will come back as 0. Accessing sample 0 from this reader will actually read the first sample from the other's subsection, which might be at a non-zero position.
See Also
AudioFormatReader
Public Member Functions
AudioSubsectionReader (AudioFormatReader *sourceReader, int64 subsectionStartSample, int64 subsectionLength, bool deleteSourceWhenDeleted)
Creates an AudioSubsectionReader for a given data source.
~AudioSubsectionReader ()
Destructor.
bool readSamples (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples) override
Subclasses must implement this method to perform the low-level read operation.
void readMaxLevels (int64 startSample, int64 numSamples, Range< float > *results, int numChannelsToRead) override
Finds the highest and lowest sample levels from a section of the audio stream.
Public Member Functions inherited from AudioFormatReader
virtual ~AudioFormatReader ()
Destructor.
const String & getFormatName () const noexcept
Returns a description of what type of format this is.
bool read (int *const *destSamples, int numDestChannels, int64 startSampleInSource, int numSamplesToRead, bool fillLeftoverChannelsWithCopies)
Reads samples from the stream.
void read (AudioSampleBuffer *buffer, int startSampleInDestBuffer, int numSamples, int64 readerStartSample, bool useReaderLeftChan, bool useReaderRightChan)
Fills a section of an AudioSampleBuffer from this reader.
virtual void readMaxLevels (int64 startSample, int64 numSamples, float &lowestLeft, float &highestLeft, float &lowestRight, float &highestRight)
Finds the highest and lowest sample levels from a section of the audio stream.
int64 searchForLevel (int64 startSample, int64 numSamplesToSearch, double magnitudeRangeMinimum, double magnitudeRangeMaximum, int minimumConsecutiveSamples)
Scans the source looking for a sample whose magnitude is in a specified range.
virtual AudioChannelSet getChannelLayout ()
Get the channel layout of the audio stream.
Additional Inherited Members
Public Attributes inherited from AudioFormatReader
double sampleRate
The sample-rate of the stream.
unsigned int bitsPerSample
The number of bits per sample, e.g.
int64 lengthInSamples
The total number of samples in the audio stream.
unsigned int numChannels
The total number of channels in the audio stream.
bool usesFloatingPointData
Indicates whether the data is floating-point or fixed.
StringPairArray metadataValues
A set of metadata values that the reader has pulled out of the stream.
InputStream * input
The input stream, for use by subclasses.
Protected Member Functions inherited from AudioFormatReader
AudioFormatReader (InputStream *sourceStream, const String &formatName)
Creates an AudioFormatReader object.
Static Protected Member Functions inherited from AudioFormatReader
static void clearSamplesBeyondAvailableLength (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int &numSamples, int64 fileLengthInSamples)
Used by AudioFormatReader subclasses to clear any parts of the data blocks that lie beyond the end of their available length.
Constructor & Destructor Documentation
AudioSubsectionReader::AudioSubsectionReader (AudioFormatReader * sourceReader, int64 subsectionStartSample, int64 subsectionLength, bool deleteSourceWhenDeleted)
Creates an AudioSubsectionReader for a given data source.
Parameters
sourceReader the source reader from which we'll be taking data
subsectionStartSample the sample within the source reader which will be mapped onto sample 0 for this reader.
subsectionLength the number of samples from the source that will make up the subsection. If this reader is asked for any samples beyond this region, it will return zero.
deleteSourceWhenDeleted if true, the sourceReader object will be deleted when this object is deleted.
AudioSubsectionReader::~AudioSubsectionReader ()
Destructor.
Member Function Documentation
bool AudioSubsectionReader::readSamples (int ** destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples) override virtual
Subclasses must implement this method to perform the low-level read operation.
Callers should use read() instead of calling this directly.
Parameters
destSamples the array of destination buffers to fill. Some of these pointers may be null
numDestChannels the number of items in the destSamples array. This value is guaranteed not to be greater than the number of channels that this reader object contains
startOffsetInDestBuffer the number of samples from the start of the dest data at which to begin writing
startSampleInFile the number of samples into the source data at which to begin reading. This value is guaranteed to be >= 0.
numSamples the number of samples to read
Implements AudioFormatReader.
void AudioSubsectionReader::readMaxLevels (int64 startSample, int64 numSamples, Range< float > * results, int numChannelsToRead) override virtual
Finds the highest and lowest sample levels from a section of the audio stream.
This will read a block of samples from the stream, and measure the highest and lowest sample levels from the channels in that section, returning these as normalised floating-point levels.
Parameters
startSample the offset into the audio stream to start reading from. It's ok for this to be beyond the start or end of the stream.
numSamples how many samples to read
results this array will be filled with Range values for each channel. The array must contain numChannels elements.
numChannelsToRead the number of channels of data to scan. This must be more than zero, but not more than the total number of channels that the reader contains
See Also
read
Reimplemented from AudioFormatReader.
class BufferingAudioReader
An AudioFormatReader that uses a background thread to pre-read data from another reader.
See Also
AudioFormatReader
Public Member Functions
BufferingAudioReader (AudioFormatReader *sourceReader, TimeSliceThread &timeSliceThread, int samplesToBuffer)
Creates a reader.
~BufferingAudioReader ()
void setReadTimeout (int timeoutMilliseconds) noexcept
Sets a number of milliseconds that the reader can block for in its readSamples() method before giving up and returning silence.
bool readSamples (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples) override
Subclasses must implement this method to perform the low-level read operation.
Public Member Functions inherited from AudioFormatReader
virtual ~AudioFormatReader ()
Destructor.
const String & getFormatName () const noexcept
Returns a description of what type of format this is.
bool read (int *const *destSamples, int numDestChannels, int64 startSampleInSource, int numSamplesToRead, bool fillLeftoverChannelsWithCopies)
Reads samples from the stream.
void read (AudioSampleBuffer *buffer, int startSampleInDestBuffer, int numSamples, int64 readerStartSample, bool useReaderLeftChan, bool useReaderRightChan)
Fills a section of an AudioSampleBuffer from this reader.
virtual void readMaxLevels (int64 startSample, int64 numSamples, Range< float > *results, int numChannelsToRead)
Finds the highest and lowest sample levels from a section of the audio stream.
virtual void readMaxLevels (int64 startSample, int64 numSamples, float &lowestLeft, float &highestLeft, float &lowestRight, float &highestRight)
Finds the highest and lowest sample levels from a section of the audio stream.
int64 searchForLevel (int64 startSample, int64 numSamplesToSearch, double magnitudeRangeMinimum, double magnitudeRangeMaximum, int minimumConsecutiveSamples)
Scans the source looking for a sample whose magnitude is in a specified range.
virtual AudioChannelSet getChannelLayout ()
Get the channel layout of the audio stream.
Additional Inherited Members
Public Attributes inherited from AudioFormatReader
double sampleRate
The sample-rate of the stream.
unsigned int bitsPerSample
The number of bits per sample, e.g.
int64 lengthInSamples
The total number of samples in the audio stream.
unsigned int numChannels
The total number of channels in the audio stream.
bool usesFloatingPointData
Indicates whether the data is floating-point or fixed.
StringPairArray metadataValues
A set of metadata values that the reader has pulled out of the stream.
InputStream * input
The input stream, for use by subclasses.
Protected Member Functions inherited from AudioFormatReader
AudioFormatReader (InputStream *sourceStream, const String &formatName)
Creates an AudioFormatReader object.
Static Protected Member Functions inherited from AudioFormatReader
static void clearSamplesBeyondAvailableLength (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int &numSamples, int64 fileLengthInSamples)
Used by AudioFormatReader subclasses to clear any parts of the data blocks that lie beyond the end of their available length.
Constructor & Destructor Documentation
BufferingAudioReader::BufferingAudioReader (AudioFormatReader * sourceReader, TimeSliceThread & timeSliceThread, int samplesToBuffer)
Creates a reader.
Parameters
sourceReader the source reader to wrap. This BufferingAudioReader takes ownership of this object and will delete it later when no longer needed
timeSliceThread the thread that should be used to do the background reading. Make sure that the thread you supply is running, and won't be deleted while the reader object still exists.
samplesToBuffer the total number of samples to buffer ahead.
BufferingAudioReader::~BufferingAudioReader ()
Member Function Documentation
void BufferingAudioReader::setReadTimeout (int timeoutMilliseconds) noexcept
Sets a number of milliseconds that the reader can block for in its readSamples() method before giving up and returning silence.
A value of less that 0 means "wait forever". The default timeout is 0.
bool BufferingAudioReader::readSamples (int ** destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples) override virtual
Subclasses must implement this method to perform the low-level read operation.
Callers should use read() instead of calling this directly.
Parameters
destSamples the array of destination buffers to fill. Some of these pointers may be null
numDestChannels the number of items in the destSamples array. This value is guaranteed not to be greater than the number of channels that this reader object contains
startOffsetInDestBuffer the number of samples from the start of the dest data at which to begin writing
startSampleInFile the number of samples into the source data at which to begin reading. This value is guaranteed to be >= 0.
numSamples the number of samples to read
Implements AudioFormatReader.
class MemoryMappedAudioFormatReader
A specialised type of AudioFormatReader that uses a MemoryMappedFile to read directly from an audio file.
This allows for incredibly fast random-access to sample data in the mapped region of the file, but not all audio formats support it - see AudioFormat::createMemoryMappedReader().
Note that before reading samples from a MemoryMappedAudioFormatReader, you must first call mapEntireFile() or mapSectionOfFile() to ensure that the region you want to read has been mapped.
See Also
AudioFormat::createMemoryMappedReader, AudioFormatReader
Public Member Functions
const File & getFile () const noexcept
Returns the file that is being mapped.
bool mapEntireFile ()
Attempts to map the entire file into memory.
virtual bool mapSectionOfFile (Range< int64 > samplesToMap)
Attempts to map a section of the file into memory.
Range< int64 > getMappedSection () const noexcept
Returns the sample range that's currently memory-mapped and available for reading.
void touchSample (int64 sample) const noexcept
Touches the memory for the given sample, to force it to be loaded into active memory.
virtual void getSample (int64 sampleIndex, float *result) const noexcept=0
Returns the samples for all channels at a given sample position.
size_t getNumBytesUsed () const
Returns the number of bytes currently being mapped.
Public Member Functions inherited from AudioFormatReader
virtual ~AudioFormatReader ()
Destructor.
const String & getFormatName () const noexcept
Returns a description of what type of format this is.
bool read (int *const *destSamples, int numDestChannels, int64 startSampleInSource, int numSamplesToRead, bool fillLeftoverChannelsWithCopies)
Reads samples from the stream.
void read (AudioSampleBuffer *buffer, int startSampleInDestBuffer, int numSamples, int64 readerStartSample, bool useReaderLeftChan, bool useReaderRightChan)
Fills a section of an AudioSampleBuffer from this reader.
virtual void readMaxLevels (int64 startSample, int64 numSamples, Range< float > *results, int numChannelsToRead)
Finds the highest and lowest sample levels from a section of the audio stream.
virtual void readMaxLevels (int64 startSample, int64 numSamples, float &lowestLeft, float &highestLeft, float &lowestRight, float &highestRight)
Finds the highest and lowest sample levels from a section of the audio stream.
int64 searchForLevel (int64 startSample, int64 numSamplesToSearch, double magnitudeRangeMinimum, double magnitudeRangeMaximum, int minimumConsecutiveSamples)
Scans the source looking for a sample whose magnitude is in a specified range.
virtual AudioChannelSet getChannelLayout ()
Get the channel layout of the audio stream.
virtual bool readSamples (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int numSamples)=0
Subclasses must implement this method to perform the low-level read operation.
Protected Member Functions
MemoryMappedAudioFormatReader (const File &file, const AudioFormatReader &details, int64 dataChunkStart, int64 dataChunkLength, int bytesPerFrame)
Creates an MemoryMappedAudioFormatReader object.
int64 sampleToFilePos (int64 sample) const noexcept
Converts a sample index to a byte position in the file.
int64 filePosToSample (int64 filePos) const noexcept
Converts a byte position in the file to a sample index.
const void * sampleToPointer (int64 sample) const noexcept
Converts a sample index to a pointer to the mapped file memory.
template<typename SampleType , typename Endianness >
Range< float > scanMinAndMaxInterleaved (int channel, int64 startSampleInFile, int64 numSamples) const noexcept
Used by AudioFormatReader subclasses to scan for min/max ranges in interleaved data.
Protected Member Functions inherited from AudioFormatReader
AudioFormatReader (InputStream *sourceStream, const String &formatName)
Creates an AudioFormatReader object.
Protected Attributes
File file
Range< int64 > mappedSection
ScopedPointer< MemoryMappedFile > map
int64 dataChunkStart
int64 dataLength
int bytesPerFrame
Additional Inherited Members
Public Attributes inherited from AudioFormatReader
double sampleRate
The sample-rate of the stream.
unsigned int bitsPerSample
The number of bits per sample, e.g.
int64 lengthInSamples
The total number of samples in the audio stream.
unsigned int numChannels
The total number of channels in the audio stream.
bool usesFloatingPointData
Indicates whether the data is floating-point or fixed.
StringPairArray metadataValues
A set of metadata values that the reader has pulled out of the stream.
InputStream * input
The input stream, for use by subclasses.
Static Protected Member Functions inherited from AudioFormatReader
static void clearSamplesBeyondAvailableLength (int **destSamples, int numDestChannels, int startOffsetInDestBuffer, int64 startSampleInFile, int &numSamples, int64 fileLengthInSamples)
Used by AudioFormatReader subclasses to clear any parts of the data blocks that lie beyond the end of their available length.
Constructor & Destructor Documentation
MemoryMappedAudioFormatReader::MemoryMappedAudioFormatReader (const File & file, const AudioFormatReader & details, int64 dataChunkStart, int64 dataChunkLength, int bytesPerFrame) protected
Creates an MemoryMappedAudioFormatReader object.
Note that before attempting to read any data, you must call mapEntireFile() or mapSectionOfFile() to ensure that the region you want to read has been mapped.
Member Function Documentation
const File& MemoryMappedAudioFormatReader::getFile () const noexcept
Returns the file that is being mapped.
bool MemoryMappedAudioFormatReader::mapEntireFile ()
Attempts to map the entire file into memory.
virtual bool MemoryMappedAudioFormatReader::mapSectionOfFile (Range< int64 > samplesToMap) virtual
Attempts to map a section of the file into memory.
Range<int64> MemoryMappedAudioFormatReader::getMappedSection () const noexcept
Returns the sample range that's currently memory-mapped and available for reading.
void MemoryMappedAudioFormatReader::touchSample (int64 sample) const noexcept
Touches the memory for the given sample, to force it to be loaded into active memory.
virtual void MemoryMappedAudioFormatReader::getSample (int64 sampleIndex, float * result) const pure virtual noexcept
Returns the samples for all channels at a given sample position.
The result array must be large enough to hold a value for each channel that this reader contains.
size_t MemoryMappedAudioFormatReader::getNumBytesUsed () const
Returns the number of bytes currently being mapped.
References map().
int64 MemoryMappedAudioFormatReader::sampleToFilePos (int64 sample) const protected noexcept
Converts a sample index to a byte position in the file.
int64 MemoryMappedAudioFormatReader::filePosToSample (int64 filePos) const protected noexcept
Converts a byte position in the file to a sample index.
const void* MemoryMappedAudioFormatReader::sampleToPointer (int64 sample) const protected noexcept
Converts a sample index to a pointer to the mapped file memory.
References addBytesToPointer(), and map().
template<typename SampleType , typename Endianness > Range<float> MemoryMappedAudioFormatReader::scanMinAndMaxInterleaved (int channel, int64 startSampleInFile, int64 numSamples) const protected noexcept
Used by AudioFormatReader subclasses to scan for min/max ranges in interleaved data.
References addBytesToPointer(), and AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::findMinAndMax().
Member Data Documentation
File MemoryMappedAudioFormatReader::file protected
Range<int64> MemoryMappedAudioFormatReader::mappedSection protected
ScopedPointer<MemoryMappedFile> MemoryMappedAudioFormatReader::map protected
int64 MemoryMappedAudioFormatReader::dataChunkStart protected
int64 MemoryMappedAudioFormatReader::dataLength protected
int MemoryMappedAudioFormatReader::bytesPerFrame protected