JUCE: values
values
juce_data_structures
Classes
class CachedValue< Type >
This class acts as a typed wrapper around a property inside a ValueTree.
class Value
Represents a shared variant value.
class ValueTree
A powerful tree structure that can be used to hold free-form data, and which can handle its own undo and redo behaviour.
class ValueTreeSynchroniser
This class can be used to watch for all changes to the state of a ValueTree, and to convert them to a transmittable binary encoding.
Typedefs
typedef Value::Listener ValueListener
This typedef is just for compatibility with old code - newer code should use the Value::Listener class directly.
Functions
OutputStream &JUCE_CALLTYPE operator<< (OutputStream &, const Value &)
Writes a Value to an OutputStream as a UTF8 string.
CachedValue< Type >::CachedValue ()
Default constructor.
CachedValue< Type >::CachedValue (ValueTree &tree, const Identifier &propertyID, UndoManager *undoManager)
Constructor.
CachedValue< Type >::CachedValue (ValueTree &tree, const Identifier &propertyID, UndoManager *undoManager, const Type &defaultToUse)
Constructor.
Value CachedValue< Type >::getPropertyAsValue ()
Returns the current property as a Value object.
bool CachedValue< Type >::isUsingDefault () const
Returns true if the current property does not exist and the CachedValue is using the fallback default value instead.
CachedValue & CachedValue< Type >::operator= (const Type &newValue)
Sets the property.
void CachedValue< Type >::setValue (const Type &newValue, UndoManager *undoManagerToUse)
Sets the property.
void CachedValue< Type >::resetToDefault ()
Removes the property from the referenced ValueTree and makes the CachedValue return the fallback default value instead.
void CachedValue< Type >::resetToDefault (UndoManager *undoManagerToUse)
Removes the property from the referenced ValueTree and makes the CachedValue return the fallback default value instead.
void CachedValue< Type >::referTo (ValueTree &tree, const Identifier &property, UndoManager *um)
Makes the CachedValue refer to the specified property inside the given ValueTree.
void CachedValue< Type >::referTo (ValueTree &tree, const Identifier &property, UndoManager *um, const Type &defaultVal)
Makes the CachedValue refer to the specified property inside the given ValueTree, and specifies a fallback value to use if the property does not exist.
void CachedValue< Type >::forceUpdateOfCachedValue ()
Force an update in case the referenced property has been changed from elsewhere.
Detailed Description
Class Documentation
class CachedValue
template<typename Type>
class CachedValue< Type >
This class acts as a typed wrapper around a property inside a ValueTree.
A CachedValue provides an easy way to read and write a ValueTree property with a chosen type. So for example a CachedValue<int> allows you to read or write the property as an int, and a CachedValue<String> lets you work with it as a String.
It also allows efficient access to the value, by caching a copy of it in the type that is being used.
You can give the CachedValue an optional UndoManager which it will use when writing to the underlying ValueTree.
If the property inside the ValueTree is missing, the CachedValue will automatically return an optional default value, which can be specified when initialising the CachedValue.
To create one, you can either use the constructor to attach the CachedValue to a ValueTree, or can create an uninitialised CachedValue with its default constructor and then attach it later with the referTo() methods.
Common types like String, int, double which can be easily converted to a var should work out-of-the-box, but if you want to use more complex custom types, you may need to implement some template specialisations of VariantConverter which this class uses to convert between the type and the ValueTree's internal var.
Public Member Functions
CachedValue ()
Default constructor.
CachedValue (ValueTree &tree, const Identifier &propertyID, UndoManager *undoManager)
Constructor.
CachedValue (ValueTree &tree, const Identifier &propertyID, UndoManager *undoManager, const Type &defaultToUse)
Constructor.
operator Type () const noexcept
Returns the current value of the property.
Type get () const noexcept
Returns the current value of the property.
Type & operator* () noexcept
Dereference operator.
Type * operator-> () noexcept
Dereference operator.
template<typename OtherType >
bool operator== (const OtherType &other) const
Returns true if the current value of the property (or the fallback value) is equal to other.
template<typename OtherType >
bool operator!= (const OtherType &other) const
Returns true if the current value of the property (or the fallback value) is not equal to other.
Value getPropertyAsValue ()
Returns the current property as a Value object.
bool isUsingDefault () const
Returns true if the current property does not exist and the CachedValue is using the fallback default value instead.
Type getDefault () const
Returns the current fallback default value.
CachedValue & operator= (const Type &newValue)
Sets the property.
void setValue (const Type &newValue, UndoManager *undoManagerToUse)
Sets the property.
void resetToDefault ()
Removes the property from the referenced ValueTree and makes the CachedValue return the fallback default value instead.
void resetToDefault (UndoManager *undoManagerToUse)
Removes the property from the referenced ValueTree and makes the CachedValue return the fallback default value instead.
void setDefault (const Type &value)
Resets the fallback default value.
void referTo (ValueTree &tree, const Identifier &property, UndoManager *um)
Makes the CachedValue refer to the specified property inside the given ValueTree.
void referTo (ValueTree &tree, const Identifier &property, UndoManager *um, const Type &defaultVal)
Makes the CachedValue refer to the specified property inside the given ValueTree, and specifies a fallback value to use if the property does not exist.
void forceUpdateOfCachedValue ()
Force an update in case the referenced property has been changed from elsewhere.
ValueTree & getValueTree () noexcept
Returns a reference to the ValueTree containing the referenced property.
const Identifier & getPropertyID () const noexcept
Returns the property ID of the referenced property.
Member Function Documentation
template<typename Type > CachedValue< Type >::operator Type () const noexcept
Returns the current value of the property.
If the property does not exist, returns the fallback default value.
This is the same as calling get().
template<typename Type > Type CachedValue< Type >::get () const noexcept
Returns the current value of the property.
If the property does not exist, returns the fallback default value.
template<typename Type > Type& CachedValue< Type >::operator* () noexcept
Dereference operator.
Provides direct access to the property.
template<typename Type > Type* CachedValue< Type >::operator-> () noexcept
Dereference operator.
Provides direct access to members of the property if it is of object type.
template<typename Type > template<typename OtherType > bool CachedValue< Type >::operator== (const OtherType & other) const
Returns true if the current value of the property (or the fallback value) is equal to other.
template<typename Type > template<typename OtherType > bool CachedValue< Type >::operator!= (const OtherType & other) const
Returns true if the current value of the property (or the fallback value) is not equal to other.
template<typename Type > Type CachedValue< Type >::getDefault () const
Returns the current fallback default value.
template<typename Type > void CachedValue< Type >::setDefault (const Type & value)
Resets the fallback default value.
template<typename Type > ValueTree& CachedValue< Type >::getValueTree () noexcept
Returns a reference to the ValueTree containing the referenced property.
template<typename Type > const Identifier& CachedValue< Type >::getPropertyID () const noexcept
Returns the property ID of the referenced property.
class Value
Represents a shared variant value.
A Value object contains a reference to a var object, and can get and set its value. Listeners can be attached to be told when the value is changed.
The Value class is a wrapper around a shared, reference-counted underlying data object - this means that multiple Value objects can all refer to the same piece of data, allowing all of them to be notified when any of them changes it.
When you create a Value with its default constructor, it acts as a wrapper around a simple var object, but by creating a Value that refers to a custom subclass of ValueSource, you can map the Value onto any kind of underlying data.
Important note! The Value class is not thread-safe! If you're accessing one from multiple threads, then you'll need to use your own synchronisation around any code that accesses it.
Public Member Functions
Value ()
Creates an empty Value, containing a void var.
Value (const Value &other)
Creates a Value that refers to the same value as another one.
Value (const var &initialValue)
Creates a Value that is set to the specified value.
Value (Value &&) noexcept
Move constructor.
~Value ()
Destructor.
var getValue () const
Returns the current value.
operator var () const
Returns the current value.
String toString () const
Returns the value as a string.
void setValue (const var &newValue)
Sets the current value.
Value & operator= (const var &newValue)
Sets the current value.
Value & operator= (Value &&) noexcept
Move assignment operator.
void referTo (const Value &valueToReferTo)
Makes this object refer to the same underlying ValueSource as another one.
bool refersToSameSourceAs (const Value &other) const
Returns true if this value and the other one are references to the same value.
bool operator== (const Value &other) const
Compares two values.
bool operator!= (const Value &other) const
Compares two values.
void addListener (Listener *listener)
Adds a listener to receive callbacks when the value changes.
void removeListener (Listener *listener)
Removes a listener that was previously added with addListener().
Value (ValueSource *valueSource)
Creates a Value object that uses this valueSource object as its underlying data.
ValueSource & getValueSource () noexcept
Returns the ValueSource that this value is referring to.
Constructor & Destructor Documentation
Value::Value ()
Creates an empty Value, containing a void var.
Value::Value (const Value & other)
Creates a Value that refers to the same value as another one.
Note that this doesn't make a copy of the other value - both this and the other Value will share the same underlying value, so that when either one alters it, both will see it change.
Value::Value (const var & initialValue) explicit
Creates a Value that is set to the specified value.
Value::Value (Value &&) noexcept
Move constructor.
Value::~Value ()
Destructor.
Value::Value (ValueSource * valueSource) explicit
Creates a Value object that uses this valueSource object as its underlying data.
Member Function Documentation
var Value::getValue () const
Returns the current value.
Referenced by StandalonePluginHolder::saveAudioDeviceState().
Value::operator var () const
Returns the current value.
String Value::toString () const
Returns the value as a string.
This is a shortcut for "myValue.getValue().toString()".
void Value::setValue (const var & newValue)
Sets the current value.
You can also use operator= to set the value.
If there are any listeners registered, they will be notified of the change asynchronously.
Referenced by StandalonePluginHolder::reloadAudioDeviceState().
Value& Value::operator= (const var & newValue)
Sets the current value.
This is the same as calling setValue().
If there are any listeners registered, they will be notified of the change asynchronously.
Value& Value::operator= (Value &&) noexcept
Move assignment operator.
void Value::referTo (const Value & valueToReferTo)
Makes this object refer to the same underlying ValueSource as another one.
Once this object has been connected to another one, changing either one will update the other.
Existing listeners will still be registered after you call this method, and they'll continue to receive messages when the new value changes.
bool Value::refersToSameSourceAs (const Value & other) const
Returns true if this value and the other one are references to the same value.
bool Value::operator== (const Value & other) const
Compares two values.
This is a compare-by-value comparison, so is effectively the same as saying (this->getValue() == other.getValue()).
bool Value::operator!= (const Value & other) const
Compares two values.
This is a compare-by-value comparison, so is effectively the same as saying (this->getValue() != other.getValue()).
void Value::addListener (Listener * listener)
Adds a listener to receive callbacks when the value changes.
The listener is added to this specific Value object, and not to the shared object that it refers to. When this object is deleted, all the listeners will be lost, even if other references to the same Value still exist. So when you're adding a listener, make sure that you add it to a Value instance that will last for as long as you need the listener. In general, you'd never want to add a listener to a local stack-based Value, but more likely to one that's a member variable.
See Also
removeListener
void Value::removeListener (Listener * listener)
Removes a listener that was previously added with addListener().
ValueSource& Value::getValueSource () noexcept
Returns the ValueSource that this value is referring to.
class ValueTree
A powerful tree structure that can be used to hold free-form data, and which can handle its own undo and redo behaviour.
A ValueTree contains a list of named properties as var objects, and also holds any number of sub-trees.
Create ValueTree objects on the stack, and don't be afraid to copy them around, as they're simply a lightweight reference to a shared data container. Creating a copy of another ValueTree simply creates a new reference to the same underlying object - to make a separate, deep copy of a tree you should explicitly call createCopy().
Each ValueTree has a type name, in much the same way as an XmlElement has a tag name, and much of the structure of a ValueTree is similar to an XmlElement tree. You can convert a ValueTree to and from an XmlElement, and as long as the XML doesn't contain text elements, the conversion works well and makes a good serialisation format. They can also be serialised to a binary format, which is very fast and compact.
All the methods that change data take an optional UndoManager, which will be used to track any changes to the object. For this to work, you have to be careful to consistently always use the same UndoManager for all operations to any node inside the tree.
A ValueTree can only be a child of one parent at a time, so if you're moving one from one tree to another, be careful to always remove it first, before adding it. This could also mess up your undo/redo chain, so be wary! In a debug build you should hit assertions if you try to do anything dangerous, but there are still plenty of ways it could go wrong.
Note that although the children in a tree have a fixed order, the properties are not guaranteed to be stored in any particular order, so don't expect that a property's index will correspond to the order in which the property was added, or that it will remain constant when other properties are added or removed.
Listeners can be added to a ValueTree to be told when properies change and when nodes are added or removed.
See Also
var, XmlElement
Public Member Functions
ValueTree () noexcept
Creates an empty, invalid ValueTree.
ValueTree (const Identifier &type)
Creates an empty ValueTree with the given type name.
ValueTree (const ValueTree &) noexcept
Creates a reference to another ValueTree.
ValueTree & operator= (const ValueTree &)
Makes this object reference another node.
ValueTree (ValueTree &&) noexcept
Move constructor.
~ValueTree ()
Destructor.
bool operator== (const ValueTree &) const noexcept
Returns true if both this and the other tree node refer to the same underlying structure.
bool operator!= (const ValueTree &) const noexcept
Returns true if this and the other node refer to different underlying structures.
bool isEquivalentTo (const ValueTree &) const
Performs a deep comparison between the properties and children of two trees.
bool isValid () const noexcept
Returns true if this node refers to some valid data.
ValueTree createCopy () const
Returns a deep copy of this tree and all its sub-nodes.
Identifier getType () const noexcept
Returns the type of this node.
bool hasType (const Identifier &typeName) const noexcept
Returns true if the node has this type.
const var & getProperty (const Identifier &name) const noexcept
Returns the value of a named property.
var getProperty (const Identifier &name, const var &defaultReturnValue) const
Returns the value of a named property, or the value of defaultReturnValue if the property doesn't exist.
const var * getPropertyPointer (const Identifier &name) const noexcept
Returns a pointer to the value of a named property, or nullptr if the property doesn't exist.
const var & operator[] (const Identifier &name) const noexcept
Returns the value of a named property.
ValueTree & setProperty (const Identifier &name, const var &newValue, UndoManager *undoManager)
Changes a named property of the node.
bool hasProperty (const Identifier &name) const noexcept
Returns true if the node contains a named property.
void removeProperty (const Identifier &name, UndoManager *undoManager)
Removes a property from the node.
void removeAllProperties (UndoManager *undoManager)
Removes all properties from the node.
int getNumProperties () const noexcept
Returns the total number of properties that the node contains.
Identifier getPropertyName (int index) const noexcept
Returns the identifier of the property with a given index.
Value getPropertyAsValue (const Identifier &name, UndoManager *undoManager)
Returns a Value object that can be used to control and respond to one of the tree's properties.
void copyPropertiesFrom (const ValueTree &source, UndoManager *undoManager)
Overwrites all the properties in this tree with the properties of the source tree.
int getNumChildren () const noexcept
Returns the number of child nodes belonging to this one.
ValueTree getChild (int index) const
Returns one of this node's child nodes.
ValueTree getChildWithName (const Identifier &type) const
Returns the first child node with the specified type name.
ValueTree getOrCreateChildWithName (const Identifier &type, UndoManager *undoManager)
Returns the first child node with the specified type name, creating and adding a child with this name if there wasn't already one there.
ValueTree getChildWithProperty (const Identifier &propertyName, const var &propertyValue) const
Looks for the first child node that has the specified property value.
void addChild (const ValueTree &child, int index, UndoManager *undoManager)
Adds a child to this node.
void removeChild (const ValueTree &child, UndoManager *undoManager)
Removes the specified child from this node's child-list.
void removeChild (int childIndex, UndoManager *undoManager)
Removes a child from this node's child-list.
void removeAllChildren (UndoManager *undoManager)
Removes all child-nodes from this node.
void moveChild (int currentIndex, int newIndex, UndoManager *undoManager)
Moves one of the children to a different index.
bool isAChildOf (const ValueTree &possibleParent) const noexcept
Returns true if this node is anywhere below the specified parent node.
int indexOf (const ValueTree &child) const noexcept
Returns the index of a child item in this parent.
ValueTree getParent () const noexcept
Returns the parent node that contains this one.
ValueTree getRoot () const noexcept
Recusrively finds the highest-level parent node that contains this one.
ValueTree getSibling (int delta) const noexcept
Returns one of this node's siblings in its parent's child list.
Iterator begin () const noexcept
Returns a start iterator for the children in this tree.
Iterator end () const noexcept
Returns an end iterator for the children in this tree.
XmlElement * createXml () const
Creates an XmlElement that holds a complete image of this node and all its children.
String toXmlString () const
This returns a string containing an XML representation of the tree.
void writeToStream (OutputStream &output) const
Stores this tree (and all its children) in a binary format.
void addListener (Listener *listener)
Adds a listener to receive callbacks when this node is changed.
void removeListener (Listener *listener)
Removes a listener that was previously added with addListener().
ValueTree & setPropertyExcludingListener (Listener *listenerToExclude, const Identifier &name, const var &newValue, UndoManager *undoManager)
Changes a named property of the node, but will not notify a specified listener of the change.
void sendPropertyChangeMessage (const Identifier &property)
Causes a property-change callback to be triggered for the specified property, calling any listeners that are registered.
template<typename ElementComparator >
void sort (ElementComparator &comparator, UndoManager *undoManager, bool retainOrderOfEquivalentItems)
This method uses a comparator object to sort the tree's children into order.
int getReferenceCount () const noexcept
Returns the total number of references to the shared underlying data structure that this ValueTree is using.
Static Public Member Functions
static ValueTree fromXml (const XmlElement &xml)
Tries to recreate a node from its XML representation.
static ValueTree readFromStream (InputStream &input)
Reloads a tree from a stream that was written with writeToStream().
static ValueTree readFromData (const void *data, size_t numBytes)
Reloads a tree from a data block that was written with writeToStream().
static ValueTree readFromGZIPData (const void *data, size_t numBytes)
Reloads a tree from a data block that was written with writeToStream() and then zipped using GZIPCompressorOutputStream.
Constructor & Destructor Documentation
ValueTree::ValueTree () noexcept
Creates an empty, invalid ValueTree.
A ValueTree that is created with this constructor can't actually be used for anything, it's just a default 'null' ValueTree that can be returned to indicate some sort of failure. To create a real one, use the constructor that takes a string.
ValueTree::ValueTree (const Identifier & type) explicit
Creates an empty ValueTree with the given type name.
Like an XmlElement, each ValueTree node has a type, which you can access with getType() and hasType().
ValueTree::ValueTree (const ValueTree &) noexcept
Creates a reference to another ValueTree.
ValueTree::ValueTree (ValueTree &&) noexcept
Move constructor.
ValueTree::~ValueTree ()
Destructor.
Member Function Documentation
ValueTree& ValueTree::operator= (const ValueTree &)
Makes this object reference another node.
bool ValueTree::operator== (const ValueTree &) const noexcept
Returns true if both this and the other tree node refer to the same underlying structure.
Note that this isn't a value comparison - two independently-created trees which contain identical data are not considered equal.
bool ValueTree::operator!= (const ValueTree &) const noexcept
Returns true if this and the other node refer to different underlying structures.
Note that this isn't a value comparison - two independently-created trees which contain identical data are not considered equal.
bool ValueTree::isEquivalentTo (const ValueTree &) const
Performs a deep comparison between the properties and children of two trees.
If all the properties and children of the two trees are the same (recursively), this returns true. The normal operator==() only checks whether two trees refer to the same shared data structure, so use this method if you need to do a proper value comparison.
bool ValueTree::isValid () const noexcept
Returns true if this node refers to some valid data.
It's hard to create an invalid node, but you might get one returned, e.g. by an out-of-range call to getChild().
ValueTree ValueTree::createCopy () const
Returns a deep copy of this tree and all its sub-nodes.
Identifier ValueTree::getType () const noexcept
Returns the type of this node.
The type is specified when the ValueTree is created.
See Also
hasType
Referenced by DrawablePath::ValueTreeWrapper::Element::getType().
bool ValueTree::hasType (const Identifier & typeName) const noexcept
Returns true if the node has this type.
The comparison is case-sensitive.
const var& ValueTree::getProperty (const Identifier & name) const noexcept
Returns the value of a named property.
If no such property has been set, this will return a void variant. You can also use operator[] to get a property.
See Also
var, setProperty, getPropertyPointer, hasProperty
var ValueTree::getProperty (const Identifier & name, const var & defaultReturnValue) const
Returns the value of a named property, or the value of defaultReturnValue if the property doesn't exist.
You can also use operator[] and getProperty to get a property.
See Also
var, getProperty, getPropertyPointer, setProperty, hasProperty
const var* ValueTree::getPropertyPointer (const Identifier & name) const noexcept
Returns a pointer to the value of a named property, or nullptr if the property doesn't exist.
See Also
var, getProperty, setProperty, hasProperty
const var& ValueTree::operator[] (const Identifier & name) const noexcept
Returns the value of a named property.
If no such property has been set, this will return a void variant. This is the same as calling getProperty().
See Also
getProperty
ValueTree& ValueTree::setProperty (const Identifier & name, const var & newValue, UndoManager * undoManager)
Changes a named property of the node.
The name identifier must not be an empty string. If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
See Also
var, getProperty, removeProperty
Returns
a reference to the value tree, so that you can daisy-chain calls to this method.
bool ValueTree::hasProperty (const Identifier & name) const noexcept
Returns true if the node contains a named property.
void ValueTree::removeProperty (const Identifier & name, UndoManager * undoManager)
Removes a property from the node.
If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
void ValueTree::removeAllProperties (UndoManager * undoManager)
Removes all properties from the node.
If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
int ValueTree::getNumProperties () const noexcept
Returns the total number of properties that the node contains.
See Also
getProperty.
Identifier ValueTree::getPropertyName (int index) const noexcept
Returns the identifier of the property with a given index.
Note that properties are not guaranteed to be stored in any particular order, so don't expect that the index will correspond to the order in which the property was added, or that it will remain constant when other properties are added or removed.
See Also
getNumProperties
Value ValueTree::getPropertyAsValue (const Identifier & name, UndoManager * undoManager)
Returns a Value object that can be used to control and respond to one of the tree's properties.
The Value object will maintain a reference to this tree, and will use the undo manager when it needs to change the value. Attaching a Value::Listener to the value object will provide callbacks whenever the property changes.
void ValueTree::copyPropertiesFrom (const ValueTree & source, UndoManager * undoManager)
Overwrites all the properties in this tree with the properties of the source tree.
Any properties that already exist will be updated; and new ones will be added, and any that are not present in the source tree will be removed.
int ValueTree::getNumChildren () const noexcept
Returns the number of child nodes belonging to this one.
See Also
getChild
ValueTree ValueTree::getChild (int index) const
Returns one of this node's child nodes.
If the index is out of range, it'll return an invalid node. (See isValid() to find out whether a node is valid).
ValueTree ValueTree::getChildWithName (const Identifier & type) const
Returns the first child node with the specified type name.
If no such node is found, it'll return an invalid node. (See isValid() to find out whether a node is valid).
See Also
getOrCreateChildWithName
ValueTree ValueTree::getOrCreateChildWithName (const Identifier & type, UndoManager * undoManager)
Returns the first child node with the specified type name, creating and adding a child with this name if there wasn't already one there.
The only time this will return an invalid object is when the object that you're calling the method on is itself invalid.
See Also
getChildWithName
ValueTree ValueTree::getChildWithProperty (const Identifier & propertyName, const var & propertyValue) const
Looks for the first child node that has the specified property value.
This will scan the child nodes in order, until it finds one that has property that matches the specified value.
If no such node is found, it'll return an invalid node. (See isValid() to find out whether a node is valid).
void ValueTree::addChild (const ValueTree & child, int index, UndoManager * undoManager)
Adds a child to this node.
Make sure that the child is removed from any former parent node before calling this, or you'll hit an assertion.
If the index is < 0 or greater than the current number of child nodes, the new node will be added at the end of the list.
If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
void ValueTree::removeChild (const ValueTree & child, UndoManager * undoManager)
Removes the specified child from this node's child-list.
If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
void ValueTree::removeChild (int childIndex, UndoManager * undoManager)
Removes a child from this node's child-list.
If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
void ValueTree::removeAllChildren (UndoManager * undoManager)
Removes all child-nodes from this node.
If the undoManager parameter is non-null, its UndoManager::perform() method will be used, so that this change can be undone.
void ValueTree::moveChild (int currentIndex, int newIndex, UndoManager * undoManager)
Moves one of the children to a different index.
This will move the child to a specified index, shuffling along any intervening items as required. So for example, if you have a list of { 0, 1, 2, 3, 4, 5 }, then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the item to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this item to end up. If this is less than zero, the value will be moved to the end of the list
undoManager the optional UndoManager to use to store this transaction
bool ValueTree::isAChildOf (const ValueTree & possibleParent) const noexcept
Returns true if this node is anywhere below the specified parent node.
This returns true if the node is a child-of-a-child, as well as a direct child.
int ValueTree::indexOf (const ValueTree & child) const noexcept
Returns the index of a child item in this parent.
If the child isn't found, this returns -1.
ValueTree ValueTree::getParent () const noexcept
Returns the parent node that contains this one.
If the node has no parent, this will return an invalid node. (See isValid() to find out whether a node is valid).
ValueTree ValueTree::getRoot () const noexcept
Recusrively finds the highest-level parent node that contains this one.
If the node has no parent, this will return itself.
ValueTree ValueTree::getSibling (int delta) const noexcept
Returns one of this node's siblings in its parent's child list.
The delta specifies how far to move through the list, so a value of 1 would return the node that follows this one, -1 would return the node before it, 0 will return this node itself, etc. If the requested position is beyond the range of available nodes, this will return an empty ValueTree().
Iterator ValueTree::begin () const noexcept
Returns a start iterator for the children in this tree.
Iterator ValueTree::end () const noexcept
Returns an end iterator for the children in this tree.
XmlElement* ValueTree::createXml () const
Creates an XmlElement that holds a complete image of this node and all its children.
If this node is invalid, this may return nullptr. Otherwise, the XML that is produced can be used to recreate a similar node by calling fromXml().
The caller must delete the object that is returned.
See Also
fromXml
static ValueTree ValueTree::fromXml (const XmlElement & xml) static
Tries to recreate a node from its XML representation.
This isn't designed to cope with random XML data - for a sensible result, it should only be fed XML that was created by the createXml() method.
String ValueTree::toXmlString () const
This returns a string containing an XML representation of the tree.
This is quite handy for debugging purposes, as it provides a quick way to view a tree.
void ValueTree::writeToStream (OutputStream & output) const
Stores this tree (and all its children) in a binary format.
Once written, the data can be read back with readFromStream().
It's much faster to load/save your tree in binary form than as XML, but obviously isn't human-readable.
static ValueTree ValueTree::readFromStream (InputStream & input) static
Reloads a tree from a stream that was written with writeToStream().
static ValueTree ValueTree::readFromData (const void * data, size_t numBytes) static
Reloads a tree from a data block that was written with writeToStream().
static ValueTree ValueTree::readFromGZIPData (const void * data, size_t numBytes) static
Reloads a tree from a data block that was written with writeToStream() and then zipped using GZIPCompressorOutputStream.
void ValueTree::addListener (Listener * listener)
Adds a listener to receive callbacks when this node is changed.
The listener is added to this specific ValueTree object, and not to the shared object that it refers to. When this object is deleted, all the listeners will be lost, even if other references to the same ValueTree still exist. And if you use the operator= to make this refer to a different ValueTree, any listeners will begin listening to changes to the new tree instead of the old one.
When you're adding a listener, make sure that you add it to a ValueTree instance that will last for as long as you need the listener. In general, you'd never want to add a listener to a local stack-based ValueTree, and would usually add one to a member variable.
See Also
removeListener
Referenced by CachedValue< Type >::CachedValue().
void ValueTree::removeListener (Listener * listener)
Removes a listener that was previously added with addListener().
ValueTree& ValueTree::setPropertyExcludingListener (Listener * listenerToExclude, const Identifier & name, const var & newValue, UndoManager * undoManager)
Changes a named property of the node, but will not notify a specified listener of the change.
See Also
setProperty
void ValueTree::sendPropertyChangeMessage (const Identifier & property)
Causes a property-change callback to be triggered for the specified property, calling any listeners that are registered.
template<typename ElementComparator > void ValueTree::sort (ElementComparator & comparator, UndoManager * undoManager, bool retainOrderOfEquivalentItems)
This method uses a comparator object to sort the tree's children into order.
The object provided must have a method of the form:
int compareElements (const ValueTree& first, const ValueTree& second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
undoManager optional UndoManager for storing the changes
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
References OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::sort().
int ValueTree::getReferenceCount () const noexcept
Returns the total number of references to the shared underlying data structure that this ValueTree is using.
class ValueTreeSynchroniser
This class can be used to watch for all changes to the state of a ValueTree, and to convert them to a transmittable binary encoding.
The purpose of this class is to allow two or more ValueTrees to be remotely synchronised by transmitting encoded changes over some kind of transport mechanism.
To use it, you'll need to implement a subclass of ValueTreeSynchroniser and implement the stateChanged() method to transmit the encoded change (maybe via a network or other means) to a remote destination, where it can be applied to a target tree.
Public Member Functions
ValueTreeSynchroniser (const ValueTree &tree)
Creates a ValueTreeSynchroniser that watches the given tree.
virtual ~ValueTreeSynchroniser ()
Destructor.
virtual void stateChanged (const void *encodedChange, size_t encodedChangeSize)=0
This callback happens when the ValueTree changes and the given state-change message needs to be applied to any other trees that need to stay in sync with it.
void sendFullSyncCallback ()
Forces the sending of a full state message, which may be large, as it encodes the entire ValueTree.
const ValueTree & getRoot () noexcept
Returns the root ValueTree that is being observed.
Static Public Member Functions
static bool applyChange (ValueTree &target, const void *encodedChangeData, size_t encodedChangeDataSize, UndoManager *undoManager)
Applies an encoded change to the given destination tree.
Constructor & Destructor Documentation
ValueTreeSynchroniser::ValueTreeSynchroniser (const ValueTree & tree)
Creates a ValueTreeSynchroniser that watches the given tree.
After creating an instance of this class and somehow attaching it to a target tree, you probably want to call sendFullSyncCallback() to get them into a common starting state.
virtual ValueTreeSynchroniser::~ValueTreeSynchroniser () virtual
Destructor.
Member Function Documentation
virtual void ValueTreeSynchroniser::stateChanged (const void * encodedChange, size_t encodedChangeSize) pure virtual
This callback happens when the ValueTree changes and the given state-change message needs to be applied to any other trees that need to stay in sync with it.
The data is an opaque blob of binary that you should transmit to wherever your target tree lives, and use applyChange() to apply this to the target tree.
void ValueTreeSynchroniser::sendFullSyncCallback ()
Forces the sending of a full state message, which may be large, as it encodes the entire ValueTree.
This will internally invoke stateChanged() with the encoded version of the state.
static bool ValueTreeSynchroniser::applyChange (ValueTree & target, const void * encodedChangeData, size_t encodedChangeDataSize, UndoManager * undoManager) static
Applies an encoded change to the given destination tree.
When you implement a receiver for changes that were sent by the stateChanged() message, this is the function that you'll need to call to apply them to the target tree that you want to be synced.
const ValueTree& ValueTreeSynchroniser::getRoot () noexcept
Returns the root ValueTree that is being observed.
Typedef Documentation
typedef Value::Listener ValueListener
This typedef is just for compatibility with old code - newer code should use the Value::Listener class directly.
Function Documentation
OutputStream& JUCE_CALLTYPE operator<< (OutputStream & , const Value &)
Writes a Value to an OutputStream as a UTF8 string.
template<typename Type > CachedValue< Type >::CachedValue ()
Default constructor.
Creates a default CachedValue not referring to any property. To initialise the object, call one of the referTo() methods.
template<typename Type > CachedValue< Type >::CachedValue (ValueTree & tree, const Identifier & propertyID, UndoManager * undoManager)
Constructor.
Creates a CachedValue referring to a Value property inside a ValueTree. If you use this constructor, the fallback value will be a default-constructed instance of Type.
Parameters
tree The ValueTree containing the property
propertyID The identifier of the property
undoManager The UndoManager to use when writing to the property
References ValueTree::addListener().
template<typename Type > CachedValue< Type >::CachedValue (ValueTree & tree, const Identifier & propertyID, UndoManager * undoManager, const Type & defaultToUse)
Constructor.
Creates a default Cached Value referring to a Value property inside a ValueTree, and specifies a fallback value to use if the property does not exist.
Parameters
tree The ValueTree containing the property
propertyID The identifier of the property
undoManager The UndoManager to use when writing to the property
defaultToUse The fallback default value to use.
References ValueTree::addListener().
template<typename Type > Value CachedValue< Type >::getPropertyAsValue ()
Returns the current property as a Value object.
template<typename Type > bool CachedValue< Type >::isUsingDefault () const
Returns true if the current property does not exist and the CachedValue is using the fallback default value instead.
template<typename Type > CachedValue< Type > & CachedValue< Type >::operator= (const Type & newValue)
Sets the property.
This will actually modify the property in the referenced ValueTree.
template<typename Type > void CachedValue< Type >::setValue (const Type & newValue, UndoManager * undoManagerToUse)
Sets the property.
This will actually modify the property in the referenced ValueTree.
template<typename Type > void CachedValue< Type >::resetToDefault ()
Removes the property from the referenced ValueTree and makes the CachedValue return the fallback default value instead.
template<typename Type > void CachedValue< Type >::resetToDefault (UndoManager * undoManagerToUse)
Removes the property from the referenced ValueTree and makes the CachedValue return the fallback default value instead.
template<typename Type > void CachedValue< Type >::referTo (ValueTree & tree, const Identifier & property, UndoManager * um)
Makes the CachedValue refer to the specified property inside the given ValueTree.
template<typename Type > void CachedValue< Type >::referTo (ValueTree & tree, const Identifier & property, UndoManager * um, const Type & defaultVal)
Makes the CachedValue refer to the specified property inside the given ValueTree, and specifies a fallback value to use if the property does not exist.
template<typename Type > void CachedValue< Type >::forceUpdateOfCachedValue ()
Force an update in case the referenced property has been changed from elsewhere.
Note: The CachedValue is a ValueTree::Listener and therefore will be informed of changes of the referenced property anyway (and update itself). But this may happen asynchronously. forceUpdateOfCachedValue() forces an update immediately.