JUCE: threads
threads
juce_core
Classes
class ChildProcess
Launches and monitors a child process.
class CriticalSection
A re-entrant mutex.
class DummyCriticalSection
A class that can be used in place of a real CriticalSection object, but which doesn't perform any locking.
class DynamicLibrary
Handles the opening and closing of DLLs.
class HighResolutionTimer
A high-resolution periodic timer.
class InterProcessLock
Acts as a critical section which processes can use to block each other.
class Process
Represents the current executable's process.
class ReadWriteLock
A critical section that allows multiple simultaneous readers.
class GenericScopedLock< LockType >
Automatically locks and unlocks a mutex object.
class GenericScopedUnlock< LockType >
Automatically unlocks and re-locks a mutex object.
class GenericScopedTryLock< LockType >
Automatically locks and unlocks a mutex object.
class ScopedReadLock
Automatically locks and unlocks a ReadWriteLock object.
class ScopedWriteLock
Automatically locks and unlocks a ReadWriteLock object.
class SpinLock
A simple spin-lock class that can be used as a simple, low-overhead mutex for uncontended situations.
class Thread
Encapsulates a thread.
class ThreadLocalValue< Type >
Provides cross-platform support for thread-local objects.
class ThreadPoolJob
A task that is executed by a ThreadPool object.
class ThreadPool
A set of threads that will run a list of jobs.
class TimeSliceClient
Used by the TimeSliceThread class.
class TimeSliceThread
A thread that keeps a list of clients, and calls each one in turn, giving them all a chance to run some sort of short task.
class WaitableEvent
Allows threads to wait for events triggered by other threads.
Typedefs
typedef
CriticalSection::ScopedLockType ScopedLock
Automatically locks and unlocks a CriticalSection object.
typedef
CriticalSection::ScopedUnlockType ScopedUnlock
Automatically unlocks and re-locks a CriticalSection object.
typedef
CriticalSection::ScopedTryLockType ScopedTryLock
Automatically tries to lock and unlock a CriticalSection object.
Detailed Description
Class Documentation
class ChildProcess
Launches and monitors a child process.
This class lets you launch an executable, and read its output. You can also use it to check whether the child process has finished.
Public Types
enum StreamFlags { wantStdOut = 1, wantStdErr = 2 }
These flags are used by the start() methods.
Public Member Functions
ChildProcess ()
Creates a process object.
~ChildProcess ()
Destructor.
bool start (const String &command, int streamFlags=wantStdOut|wantStdErr)
Attempts to launch a child process command.
bool start (const StringArray &arguments, int streamFlags=wantStdOut|wantStdErr)
Attempts to launch a child process command.
bool isRunning () const
Returns true if the child process is alive.
int readProcessOutput (void *destBuffer, int numBytesToRead)
Attempts to read some output from the child process.
String readAllProcessOutput ()
Blocks until the process has finished, and then returns its complete output as a string.
bool waitForProcessToFinish (int timeoutMs) const
Blocks until the process is no longer running.
uint32 getExitCode () const
If the process has finished, this returns its exit code.
bool kill ()
Attempts to kill the child process.
Member Enumeration Documentation
enum ChildProcess::StreamFlags
These flags are used by the start() methods.
Enumerator
wantStdOut
wantStdErr
Constructor & Destructor Documentation
ChildProcess::ChildProcess ()
Creates a process object.
To actually launch the process, use start().
ChildProcess::~ChildProcess ()
Destructor.
Note that deleting this object won't terminate the child process.
Member Function Documentation
bool ChildProcess::start (const String & command, int streamFlags = wantStdOut|wantStdErr)
Attempts to launch a child process command.
The command should be the name of the executable file, followed by any arguments that are required. If the process has already been launched, this will launch it again. If a problem occurs, the method will return false. The streamFlags is a combinations of values to indicate which of the child's output streams should be read and returned by readProcessOutput().
bool ChildProcess::start (const StringArray & arguments, int streamFlags = wantStdOut|wantStdErr)
Attempts to launch a child process command.
The first argument should be the name of the executable file, followed by any other arguments that are needed. If the process has already been launched, this will launch it again. If a problem occurs, the method will return false. The streamFlags is a combinations of values to indicate which of the child's output streams should be read and returned by readProcessOutput().
bool ChildProcess::isRunning () const
Returns true if the child process is alive.
int ChildProcess::readProcessOutput (void * destBuffer, int numBytesToRead)
Attempts to read some output from the child process.
This will attempt to read up to the given number of bytes of data from the process. It returns the number of bytes that were actually read.
String ChildProcess::readAllProcessOutput ()
Blocks until the process has finished, and then returns its complete output as a string.
bool ChildProcess::waitForProcessToFinish (int timeoutMs) const
Blocks until the process is no longer running.
uint32 ChildProcess::getExitCode () const
If the process has finished, this returns its exit code.
bool ChildProcess::kill ()
Attempts to kill the child process.
Returns true if it succeeded. Trying to read from the process after calling this may result in undefined behaviour.
class CriticalSection
A re-entrant mutex.
A CriticalSection acts as a re-entrant mutex object. The best way to lock and unlock one of these is by using RAII in the form of a local ScopedLock object - have a look through the codebase for many examples of how to do this.
In almost all cases you'll want to declare your CriticalSection as a member variable. Occasionally you may want to declare one as a static variable, but in that case the usual C++ static object order-of-construction warnings should be heeded.
See Also
ScopedLock, ScopedTryLock, ScopedUnlock, SpinLock, ReadWriteLock, Thread, InterProcessLock
Public Types
typedef GenericScopedLock
< CriticalSection > ScopedLockType
Provides the type of scoped lock to use with a CriticalSection.
typedef GenericScopedUnlock
< CriticalSection > ScopedUnlockType
Provides the type of scoped unlocker to use with a CriticalSection.
typedef GenericScopedTryLock
< CriticalSection > ScopedTryLockType
Provides the type of scoped try-locker to use with a CriticalSection.
Public Member Functions
CriticalSection () noexcept
Creates a CriticalSection object.
~CriticalSection () noexcept
Destructor.
void enter () const noexcept
Acquires the lock.
bool tryEnter () const noexcept
Attempts to lock this critical section without blocking.
void exit () const noexcept
Releases the lock.
Member Typedef Documentation
typedef GenericScopedLock<CriticalSection> CriticalSection::ScopedLockType
Provides the type of scoped lock to use with a CriticalSection.
typedef GenericScopedUnlock<CriticalSection> CriticalSection::ScopedUnlockType
Provides the type of scoped unlocker to use with a CriticalSection.
typedef GenericScopedTryLock<CriticalSection> CriticalSection::ScopedTryLockType
Provides the type of scoped try-locker to use with a CriticalSection.
Constructor & Destructor Documentation
CriticalSection::CriticalSection () noexcept
Creates a CriticalSection object.
CriticalSection::~CriticalSection () noexcept
Destructor.
If the critical section is deleted whilst locked, any subsequent behaviour is unpredictable.
Member Function Documentation
void CriticalSection::enter () const noexcept
Acquires the lock.
If the lock is already held by the caller thread, the method returns immediately. If the lock is currently held by another thread, this will wait until it becomes free.
It's strongly recommended that you never call this method directly - instead use the ScopedLock class to manage the locking using an RAII pattern instead.
See Also
exit, tryEnter, ScopedLock
bool CriticalSection::tryEnter () const noexcept
Attempts to lock this critical section without blocking.
This method behaves identically to CriticalSection::enter, except that the caller thread does not wait if the lock is currently held by another thread but returns false immediately.
Returns
false if the lock is currently held by another thread, true otherwise.
See Also
enter
void CriticalSection::exit () const noexcept
Releases the lock.
If the caller thread hasn't got the lock, this can have unpredictable results.
If the enter() method has been called multiple times by the thread, each call must be matched by a call to exit() before other threads will be allowed to take over the lock.
See Also
enter, ScopedLock
class DummyCriticalSection
A class that can be used in place of a real CriticalSection object, but which doesn't perform any locking.
This is currently used by some templated classes, and most compilers should manage to optimise it out of existence.
See Also
CriticalSection, Array, OwnedArray, ReferenceCountedArray
Inherited by ArrayAllocationBase< ActionListener *, DummyCriticalSection >, ArrayAllocationBase< ActionSet *, DummyCriticalSection >, ArrayAllocationBase< AllocatedObject *, DummyCriticalSection >, ArrayAllocationBase< AnimatedPosition::Listener *, DummyCriticalSection >, ArrayAllocationBase< AnimationTask *, DummyCriticalSection >, ArrayAllocationBase< ApplicationCommandInfo *, DummyCriticalSection >, ArrayAllocationBase< ApplicationCommandManagerListener *, DummyCriticalSection >, ArrayAllocationBase< AttributedString::Attribute, DummyCriticalSection >, ArrayAllocationBase< AudioChannelSet, DummyCriticalSection >, ArrayAllocationBase< AudioDeviceManager::AudioDeviceSetup *, DummyCriticalSection >, ArrayAllocationBase< AudioFormat *, DummyCriticalSection >, ArrayAllocationBase< AudioIODeviceCallback *, DummyCriticalSection >, ArrayAllocationBase< AudioIODeviceType *, DummyCriticalSection >, ArrayAllocationBase< AudioIODeviceType::Listener *, DummyCriticalSection >, ArrayAllocationBase< AudioPluginFormat *, DummyCriticalSection >, ArrayAllocationBase< AudioProcessor::Bus *, DummyCriticalSection >, ArrayAllocationBase< AudioProcessor::BusProperties, DummyCriticalSection >, ArrayAllocationBase< AudioProcessorGraph::Connection *, DummyCriticalSection >, ArrayAllocationBase< AudioProcessorGraph::Node *, DummyCriticalSection >, ArrayAllocationBase< AudioProcessorListener *, DummyCriticalSection >, ArrayAllocationBase< AudioProcessorParameter *, DummyCriticalSection >, ArrayAllocationBase< AudioSource *, DummyCriticalSection >, ArrayAllocationBase< BufferedBlock *, DummyCriticalSection >, ArrayAllocationBase< Button::Listener *, DummyCriticalSection >, ArrayAllocationBase< ByteSequence, DummyCriticalSection >, ArrayAllocationBase< ChangeListener *, DummyCriticalSection >, ArrayAllocationBase< ChangeMessage *, DummyCriticalSection >, ArrayAllocationBase< ChannelInfo *, DummyCriticalSection >, ArrayAllocationBase< CodeDocument::Iterator *, DummyCriticalSection >, ArrayAllocationBase< CodeDocument::Listener *, DummyCriticalSection >, ArrayAllocationBase< CodeDocument::Position *, DummyCriticalSection >, ArrayAllocationBase< CodeDocumentLine *, DummyCriticalSection >, ArrayAllocationBase< CodeEditorComponent::ColourScheme::TokenType, DummyCriticalSection >, ArrayAllocationBase< CodeEditorLine *, DummyCriticalSection >, ArrayAllocationBase< ColourPoint, DummyCriticalSection >, ArrayAllocationBase< ColourSetting, DummyCriticalSection >, ArrayAllocationBase< ColumnInfo *, DummyCriticalSection >, ArrayAllocationBase< ComboBox *, DummyCriticalSection >, ArrayAllocationBase< ComboBox::Listener *, DummyCriticalSection >, ArrayAllocationBase< CommandMapping *, DummyCriticalSection >, ArrayAllocationBase< Component *, DummyCriticalSection >, ArrayAllocationBase< ComponentBuilder::TypeHandler *, DummyCriticalSection >, ArrayAllocationBase< ComponentPeer *, DummyCriticalSection >, ArrayAllocationBase< const PluginDescription *, DummyCriticalSection >, ArrayAllocationBase< const PopupMenu *, DummyCriticalSection >, ArrayAllocationBase< Desktop::Displays::Display, DummyCriticalSection >, ArrayAllocationBase< DirectoryContentsList::FileInfo *, DummyCriticalSection >, ArrayAllocationBase< DrawableButton *, DummyCriticalSection >, ArrayAllocationBase< ElementType, DummyCriticalSection >, ArrayAllocationBase< ExpPtr, DummyCriticalSection >, ArrayAllocationBase< File, DummyCriticalSection >, ArrayAllocationBase< FileBrowserListener *, DummyCriticalSection >, ArrayAllocationBase< FilenameComponentListener *, DummyCriticalSection >, ArrayAllocationBase< FlexItem, DummyCriticalSection >, ArrayAllocationBase< float, DummyCriticalSection >, ArrayAllocationBase< FloatingType, DummyCriticalSection >, ArrayAllocationBase< FloatType, DummyCriticalSection >, ArrayAllocationBase< FocusChangeListener *, DummyCriticalSection >, ArrayAllocationBase< Function *, DummyCriticalSection >, ArrayAllocationBase< GlyphInfo *, DummyCriticalSection >, ArrayAllocationBase< HashEntry *, DummyCriticalSection >, ArrayAllocationBase< IIRCoefficients, DummyCriticalSection >, ArrayAllocationBase< IIRFilter *, DummyCriticalSection >, ArrayAllocationBase< ImagePixelData::Listener *, DummyCriticalSection >, ArrayAllocationBase< InAppPurchases::Download *, DummyCriticalSection >, ArrayAllocationBase< InAppPurchases::Listener *, DummyCriticalSection >, ArrayAllocationBase< int, DummyCriticalSection >, ArrayAllocationBase< Item *, DummyCriticalSection >, ArrayAllocationBase< Item, DummyCriticalSection >, ArrayAllocationBase< ItemLayoutProperties *, DummyCriticalSection >, ArrayAllocationBase< KeyPress, DummyCriticalSection >, ArrayAllocationBase< KeyPressTime *, DummyCriticalSection >, ArrayAllocationBase< KnownPluginList::PluginTree *, DummyCriticalSection >, ArrayAllocationBase< Label::Listener *, DummyCriticalSection >, ArrayAllocationBase< littlefoot::Compiler::CodeGenerator::MarkerAndAddress, DummyCriticalSection >, ArrayAllocationBase< littlefoot::NativeFunction, DummyCriticalSection >, ArrayAllocationBase< LowLevelGraphicsPostScriptRenderer::SavedState *, DummyCriticalSection >, ArrayAllocationBase< MarkerList *, DummyCriticalSection >, ArrayAllocationBase< MarkerList::Listener *, DummyCriticalSection >, ArrayAllocationBase< MarkerList::Marker *, DummyCriticalSection >, ArrayAllocationBase< MenuBarModel::Listener *, DummyCriticalSection >, ArrayAllocationBase< MidiBuffer *, DummyCriticalSection >, ArrayAllocationBase< MidiCallbackInfo, DummyCriticalSection >, ArrayAllocationBase< MidiInput *, DummyCriticalSection >, ArrayAllocationBase< MidiKeyboardStateListener *, DummyCriticalSection >, ArrayAllocationBase< MidiMessageSequence *, DummyCriticalSection >, ArrayAllocationBase< MidiMessageSequence::MidiEventHolder *, DummyCriticalSection >, ArrayAllocationBase< ModalItem *, DummyCriticalSection >, ArrayAllocationBase< MouseInactivityDetector::Listener *, DummyCriticalSection >, ArrayAllocationBase< MouseListener *, DummyCriticalSection >, ArrayAllocationBase< MPEInstrument::Listener *, DummyCriticalSection >, ArrayAllocationBase< MPENote, DummyCriticalSection >, ArrayAllocationBase< MPESynthesiserVoice *, DummyCriticalSection >, ArrayAllocationBase< MPEZone, DummyCriticalSection >, ArrayAllocationBase< MPEZoneLayout::Listener *, DummyCriticalSection >, ArrayAllocationBase< NamedValueSet::NamedValue, DummyCriticalSection >, ArrayAllocationBase< NumericType, DummyCriticalSection >, ArrayAllocationBase< OSCArgument, DummyCriticalSection >, ArrayAllocationBase< OSCBundle::OSCBundle::Element, DummyCriticalSection >, ArrayAllocationBase< PanelHolder *, DummyCriticalSection >, ArrayAllocationBase< PluginDescription *, DummyCriticalSection >, ArrayAllocationBase< PopupMenu::Item *, DummyCriticalSection >, ArrayAllocationBase< PositionedGlyph, DummyCriticalSection >, ArrayAllocationBase< ProgressBar *, DummyCriticalSection >, ArrayAllocationBase< Range< int >, DummyCriticalSection >, ArrayAllocationBase< Rectangle, DummyCriticalSection >, ArrayAllocationBase< RelativePointPath::ElementBase *, DummyCriticalSection >, ArrayAllocationBase< ScrollBar::Listener *, DummyCriticalSection >, ArrayAllocationBase< SelectableItemType, DummyCriticalSection >, ArrayAllocationBase< size_t, DummyCriticalSection >, ArrayAllocationBase< StandalonePluginHolder::PluginInOuts, DummyCriticalSection >, ArrayAllocationBase< StatementPtr, DummyCriticalSection >, ArrayAllocationBase< String, DummyCriticalSection >, ArrayAllocationBase< SwatchComponent *, DummyCriticalSection >, ArrayAllocationBase< SynthesiserSound *, DummyCriticalSection >, ArrayAllocationBase< SynthesiserVoice *, DummyCriticalSection >, ArrayAllocationBase< TabInfo *, DummyCriticalSection >, ArrayAllocationBase< TableHeaderComponent::Listener *, DummyCriticalSection >, ArrayAllocationBase< TextButton *, DummyCriticalSection >, ArrayAllocationBase< TextDiff::Change, DummyCriticalSection >, ArrayAllocationBase< TextEditor *, DummyCriticalSection >, ArrayAllocationBase< TextEditor::Listener *, DummyCriticalSection >, ArrayAllocationBase< TextLayout::Glyph, DummyCriticalSection >, ArrayAllocationBase< TextLayout::Line *, DummyCriticalSection >, ArrayAllocationBase< TextLayout::Run *, DummyCriticalSection >, ArrayAllocationBase< TextPropertyComponent::Listener *, DummyCriticalSection >, ArrayAllocationBase< ThreadPoolJob *, DummyCriticalSection >, ArrayAllocationBase< ThreadPoolThread *, DummyCriticalSection >, ArrayAllocationBase< ThreadRecursionCount, DummyCriticalSection >, ArrayAllocationBase< ThumbData *, DummyCriticalSection >, ArrayAllocationBase< ThumbnailCacheEntry *, DummyCriticalSection >, ArrayAllocationBase< Timer *, DummyCriticalSection >, ArrayAllocationBase< TimeSliceClient *, DummyCriticalSection >, ArrayAllocationBase< ToolbarItemComponent *, DummyCriticalSection >, ArrayAllocationBase< TreeViewItem *, DummyCriticalSection >, ArrayAllocationBase< Type, DummyCriticalSection >, ArrayAllocationBase< uint8, DummyCriticalSection >, ArrayAllocationBase< UniformTextSection *, DummyCriticalSection >, ArrayAllocationBase< Upload *, DummyCriticalSection >, ArrayAllocationBase< Value *, DummyCriticalSection >, ArrayAllocationBase< Value::Listener *, DummyCriticalSection >, ArrayAllocationBase< ValueTree::Listener *, DummyCriticalSection >, ArrayAllocationBase< Variable, DummyCriticalSection >, ArrayAllocationBase< void *, DummyCriticalSection >, ArrayAllocationBase< WeakReference< Component >, DummyCriticalSection >, and ArrayAllocationBase< ZipEntryHolder *, DummyCriticalSection >.
Public Types
typedef ScopedLockType ScopedUnlockType
A dummy scoped-unlocker type to use with a dummy critical section.
Public Member Functions
DummyCriticalSection () noexcept
~DummyCriticalSection () noexcept
void enter () const noexcept
bool tryEnter () const noexcept
void exit () const noexcept
Member Typedef Documentation
typedef ScopedLockType DummyCriticalSection::ScopedUnlockType
A dummy scoped-unlocker type to use with a dummy critical section.
Constructor & Destructor Documentation
DummyCriticalSection::DummyCriticalSection () noexcept
DummyCriticalSection::~DummyCriticalSection () noexcept
Member Function Documentation
void DummyCriticalSection::enter () const noexcept
bool DummyCriticalSection::tryEnter () const noexcept
void DummyCriticalSection::exit () const noexcept
class DynamicLibrary
Handles the opening and closing of DLLs.
This class can be used to open a DLL and get some function pointers from it. Since the DLL is freed when this object is deleted, it's handy for managing library lifetimes using RAII.
Public Member Functions
DynamicLibrary () noexcept
Creates an unopened DynamicLibrary object.
DynamicLibrary (const String &name)
DynamicLibrary (DynamicLibrary &&other) noexcept
Move constructor.
~DynamicLibrary ()
Destructor.
bool open (const String &name)
Opens a DLL.
void close ()
Releases the currently-open DLL, or has no effect if none was open.
void * getFunction (const String &functionName) noexcept
Tries to find a named function in the currently-open DLL, and returns a pointer to it.
void * getNativeHandle () const noexcept
Returns the platform-specific native library handle.
Constructor & Destructor Documentation
DynamicLibrary::DynamicLibrary () noexcept
Creates an unopened DynamicLibrary object.
Call open() to actually open one.
DynamicLibrary::DynamicLibrary (const String & name)
DynamicLibrary::DynamicLibrary (DynamicLibrary && other) noexcept
Move constructor.
DynamicLibrary::~DynamicLibrary ()
Destructor.
If a library is currently open, it will be closed when this object is destroyed.
Member Function Documentation
bool DynamicLibrary::open (const String & name)
Opens a DLL.
The name and the method by which it gets found is of course platform-specific, and may or may not include a path, depending on the OS. If a library is already open when this method is called, it will first close the library before attempting to load the new one.
Returns
true if the library was successfully found and opened.
void DynamicLibrary::close ()
Releases the currently-open DLL, or has no effect if none was open.
void* DynamicLibrary::getFunction (const String & functionName) noexcept
Tries to find a named function in the currently-open DLL, and returns a pointer to it.
If no library is open, or if the function isn't found, this will return a null pointer.
void* DynamicLibrary::getNativeHandle () const noexcept
Returns the platform-specific native library handle.
You'll need to cast this to whatever is appropriate for the OS that's in use.
class HighResolutionTimer
A high-resolution periodic timer.
This provides accurately-timed regular callbacks. Unlike the normal Timer class, this one uses a dedicated thread, not the message thread, so is far more stable and precise.
You should only use this class in situations where you really need accuracy, because unlike the normal Timer class, which is very lightweight and cheap to start/stop, the HighResolutionTimer will use far more resources, and starting/stopping it may involve launching and killing threads.
See Also
Timer
Public Member Functions
virtual ~HighResolutionTimer ()
Destructor.
virtual void hiResTimerCallback ()=0
The user-defined callback routine that actually gets called periodically.
void startTimer (int intervalInMilliseconds)
Starts the timer and sets the length of interval required.
void stopTimer ()
Stops the timer.
bool isTimerRunning () const noexcept
Checks if the timer has been started.
int getTimerInterval () const noexcept
Returns the timer's interval.
Protected Member Functions
HighResolutionTimer ()
Creates a HighResolutionTimer.
Constructor & Destructor Documentation
HighResolutionTimer::HighResolutionTimer () protected
Creates a HighResolutionTimer.
When created, the timer is stopped, so use startTimer() to get it going.
virtual HighResolutionTimer::~HighResolutionTimer () virtual
Destructor.
Member Function Documentation
virtual void HighResolutionTimer::hiResTimerCallback () pure virtual
The user-defined callback routine that actually gets called periodically.
This will be called on a dedicated timer thread, so make sure your implementation is thread-safe!
It's perfectly ok to call startTimer() or stopTimer() from within this callback to change the subsequent intervals.
void HighResolutionTimer::startTimer (int intervalInMilliseconds)
Starts the timer and sets the length of interval required.
If the timer is already started, this will reset its counter, so the time between calling this method and the next timer callback will not be less than the interval length passed in.
Parameters
intervalInMilliseconds the interval to use (any values less than 1 will be rounded up to 1)
void HighResolutionTimer::stopTimer ()
Stops the timer.
This method may block while it waits for pending callbacks to complete. Once it returns, no more callbacks will be made. If it is called from the timer's own thread, it will cancel the timer after the current callback returns.
bool HighResolutionTimer::isTimerRunning () const noexcept
Checks if the timer has been started.
Returns
true if the timer is running.
int HighResolutionTimer::getTimerInterval () const noexcept
Returns the timer's interval.
Returns
the timer's interval in milliseconds if it's running, or 0 if it's not.
class InterProcessLock
Acts as a critical section which processes can use to block each other.
See Also
CriticalSection
Public Member Functions
InterProcessLock (const String &name)
Creates a lock object.
~InterProcessLock ()
Destructor.
bool enter (int timeOutMillisecs=-1)
Attempts to lock the critical section.
void exit ()
Releases the lock if it's currently held by this process.
Constructor & Destructor Documentation
InterProcessLock::InterProcessLock (const String & name) explicit
Creates a lock object.
Parameters
name a name that processes will use to identify this lock object
InterProcessLock::~InterProcessLock ()
Destructor.
This will also release the lock if it's currently held by this process.
Member Function Documentation
bool InterProcessLock::enter (int timeOutMillisecs = -1)
Attempts to lock the critical section.
Parameters
timeOutMillisecs how many milliseconds to wait if the lock is already held by another process - a value of 0 will return immediately, negative values will wait forever
Returns
true if the lock could be gained within the timeout period, or false if the timeout expired.
Referenced by InterProcessLock::ScopedLockType::ScopedLockType().
void InterProcessLock::exit ()
Releases the lock if it's currently held by this process.
class Process
Represents the current executable's process.
This contains methods for controlling the current application at the process-level.
See Also
Thread, JUCEApplicationBase
Public Types
enum ProcessPriority { LowPriority = 0, NormalPriority = 1, HighPriority = 2, RealtimePriority = 3 }
Static Public Member Functions
static void JUCE_CALLTYPE setPriority (const ProcessPriority priority)
Changes the current process's priority.
static void JUCE_CALLTYPE terminate ()
Kills the current process immediately.
static bool JUCE_CALLTYPE isForegroundProcess ()
Returns true if this application process is the one that the user is currently using.
static void JUCE_CALLTYPE makeForegroundProcess ()
Attempts to make the current process the active one.
static void JUCE_CALLTYPE hide ()
Hides the application (on an OS that supports this, e.g.
static void JUCE_CALLTYPE raisePrivilege ()
Raises the current process's privilege level.
static void JUCE_CALLTYPE lowerPrivilege ()
Lowers the current process's privilege level.
static bool JUCE_CALLTYPE isRunningUnderDebugger () noexcept
Returns true if this process is being hosted by a debugger.
static bool JUCE_CALLTYPE openDocument (const String &documentURL, const String &parameters)
Tries to launch the OS's default reader application for a given file or URL.
static bool JUCE_CALLTYPE openEmailWithAttachments (const String &targetEmailAddress, const String &emailSubject, const String &bodyText, const StringArray &filesToAttach)
Tries to launch the OS's default email application to let the user create a message.
static void *JUCE_CALLTYPE getCurrentModuleInstanceHandle () noexcept
WINDOWS ONLY - This returns the HINSTANCE of the current module.
static void JUCE_CALLTYPE setCurrentModuleInstanceHandle (void *newHandle) noexcept
WINDOWS ONLY - Sets a new module handle to be used by the library.
static void setDockIconVisible (bool isVisible)
OSX ONLY - Shows or hides the OSX dock icon for this app.
static bool setMaxNumberOfFileHandles (int maxNumberOfFiles) noexcept
UNIX ONLY - Attempts to use setrlimit to change the maximum number of file handles that the app can open.
Member Enumeration Documentation
enum Process::ProcessPriority
Enumerator
LowPriority
NormalPriority
HighPriority
RealtimePriority
Member Function Documentation
static void JUCE_CALLTYPE Process::setPriority (const ProcessPriority priority) static
Changes the current process's priority.
Parameters
priority the process priority, where 0=low, 1=normal, 2=high, 3=realtime
static void JUCE_CALLTYPE Process::terminate () static
Kills the current process immediately.
This is an emergency process terminator that kills the application immediately - it's intended only for use only when something goes horribly wrong.
See Also
JUCEApplicationBase::quit
static bool JUCE_CALLTYPE Process::isForegroundProcess () static
Returns true if this application process is the one that the user is currently using.
static void JUCE_CALLTYPE Process::makeForegroundProcess () static
Attempts to make the current process the active one.
(This is not possible on some platforms).
static void JUCE_CALLTYPE Process::hide () static
Hides the application (on an OS that supports this, e.g.
OSX)
static void JUCE_CALLTYPE Process::raisePrivilege () static
Raises the current process's privilege level.
Does nothing if this isn't supported by the current OS, or if process privilege level is fixed.
static void JUCE_CALLTYPE Process::lowerPrivilege () static
Lowers the current process's privilege level.
Does nothing if this isn't supported by the current OS, or if process privilege level is fixed.
static bool JUCE_CALLTYPE Process::isRunningUnderDebugger () static noexcept
Returns true if this process is being hosted by a debugger.
static bool JUCE_CALLTYPE Process::openDocument (const String & documentURL, const String & parameters) static
Tries to launch the OS's default reader application for a given file or URL.
static bool JUCE_CALLTYPE Process::openEmailWithAttachments (const String & targetEmailAddress, const String & emailSubject, const String & bodyText, const StringArray & filesToAttach) static
Tries to launch the OS's default email application to let the user create a message.
static void* JUCE_CALLTYPE Process::getCurrentModuleInstanceHandle () static noexcept
WINDOWS ONLY - This returns the HINSTANCE of the current module.
The return type is a void* to avoid being dependent on windows.h - just cast it to a HINSTANCE to use it.
In a normal JUCE application, this will be automatically set to the module handle of the executable.
If you've built a DLL and plan to use any JUCE messaging or windowing classes, you'll need to make sure you call the setCurrentModuleInstanceHandle() to provide the correct module handle in your DllMain() function, because the system relies on the correct instance handle when opening windows.
static void JUCE_CALLTYPE Process::setCurrentModuleInstanceHandle (void * newHandle) static noexcept
WINDOWS ONLY - Sets a new module handle to be used by the library.
The parameter type is a void* to avoid being dependent on windows.h, but it actually expects a HINSTANCE value.
See Also
getCurrentModuleInstanceHandle()
static void Process::setDockIconVisible (bool isVisible) static
OSX ONLY - Shows or hides the OSX dock icon for this app.
static bool Process::setMaxNumberOfFileHandles (int maxNumberOfFiles) static noexcept
UNIX ONLY - Attempts to use setrlimit to change the maximum number of file handles that the app can open.
Pass 0 or less as the parameter to mean 'infinite'. Returns true if it succeeds.
class ReadWriteLock
A critical section that allows multiple simultaneous readers.
Features of this type of lock are:
Multiple readers can hold the lock at the same time, but only one writer can hold it at once.
Writers trying to gain the lock will be blocked until all readers and writers have released it
Readers trying to gain the lock while a writer is waiting to acquire it will be blocked until the writer has obtained and released it
If a thread already has a read lock and tries to obtain a write lock, it will succeed if there are no other readers
If a thread already has the write lock and tries to obtain a read lock, this will succeed.
Recursive locking is supported.
See Also
ScopedReadLock, ScopedWriteLock, CriticalSection
Public Member Functions
ReadWriteLock () noexcept
Creates a ReadWriteLock object.
~ReadWriteLock () noexcept
Destructor.
void enterRead () const noexcept
Locks this object for reading.
bool tryEnterRead () const noexcept
Tries to lock this object for reading.
void exitRead () const noexcept
Releases the read-lock.
void enterWrite () const noexcept
Locks this object for writing.
bool tryEnterWrite () const noexcept
Tries to lock this object for writing.
void exitWrite () const noexcept
Releases the write-lock.
Constructor & Destructor Documentation
ReadWriteLock::ReadWriteLock () noexcept
Creates a ReadWriteLock object.
ReadWriteLock::~ReadWriteLock () noexcept
Destructor.
If the object is deleted whilst locked, any subsequent behaviour is undefined.
Member Function Documentation
void ReadWriteLock::enterRead () const noexcept
Locks this object for reading.
Multiple threads can simultaneously lock the object for reading, but if another thread has it locked for writing, then this will block until it releases the lock.
See Also
exitRead, ScopedReadLock
bool ReadWriteLock::tryEnterRead () const noexcept
Tries to lock this object for reading.
Multiple threads can simultaneously lock the object for reading, but if another thread has it locked for writing, then this will fail and return false.
Returns
true if the lock is successfully gained.
See Also
exitRead, ScopedReadLock
void ReadWriteLock::exitRead () const noexcept
Releases the read-lock.
If the caller thread hasn't got the lock, this can have unpredictable results.
If the enterRead() method has been called multiple times by the thread, each call must be matched by a call to exitRead() before other threads will be allowed to take over the lock.
See Also
enterRead, ScopedReadLock
void ReadWriteLock::enterWrite () const noexcept
Locks this object for writing.
This will block until any other threads that have it locked for reading or writing have released their lock.
See Also
exitWrite, ScopedWriteLock
bool ReadWriteLock::tryEnterWrite () const noexcept
Tries to lock this object for writing.
This is like enterWrite(), but doesn't block - it returns true if it manages to obtain the lock.
Returns
true if the lock is successfully gained.
See Also
enterWrite
void ReadWriteLock::exitWrite () const noexcept
Releases the write-lock.
If the caller thread hasn't got the lock, this can have unpredictable results.
If the enterWrite() method has been called multiple times by the thread, each call must be matched by a call to exit() before other threads will be allowed to take over the lock.
See Also
enterWrite, ScopedWriteLock
class GenericScopedLock
template<class LockType>
class GenericScopedLock< LockType >
Automatically locks and unlocks a mutex object.
Use one of these as a local variable to provide RAII-based locking of a mutex.
The templated class could be a CriticalSection, SpinLock, or anything else that provides enter() and exit() methods.
e.g.
CriticalSection myCriticalSection;
for (;;)
{
    const GenericScopedLock<CriticalSection> myScopedLock (myCriticalSection);
    // myCriticalSection is now locked
    ...do some stuff...
    // myCriticalSection gets unlocked here.
}
See Also
GenericScopedUnlock, CriticalSection, SpinLock, ScopedLock, ScopedUnlock
Public Member Functions
GenericScopedLock (const LockType &lock) noexcept
Creates a GenericScopedLock.
~GenericScopedLock () noexcept
Destructor.
Constructor & Destructor Documentation
template<class LockType> GenericScopedLock< LockType >::GenericScopedLock (const LockType & lock) explicit noexcept
Creates a GenericScopedLock.
As soon as it is created, this will acquire the lock, and when the GenericScopedLock object is deleted, the lock will be released.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen! Best just to use it as a local stack object, rather than creating one with the new() operator.
template<class LockType> GenericScopedLock< LockType >::~GenericScopedLock () noexcept
Destructor.
The lock will be released when the destructor is called. Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen!
class GenericScopedUnlock
template<class LockType>
class GenericScopedUnlock< LockType >
Automatically unlocks and re-locks a mutex object.
This is the reverse of a GenericScopedLock object - instead of locking the mutex for the lifetime of this object, it unlocks it.
Make sure you don't try to unlock mutexes that aren't actually locked!
e.g.
CriticalSection myCriticalSection;
for (;;)
{
    const GenericScopedLock<CriticalSection> myScopedLock (myCriticalSection);
    // myCriticalSection is now locked
    ... do some stuff with it locked ..
    while (xyz)
    {
        ... do some stuff with it locked ..
        const GenericScopedUnlock<CriticalSection> unlocker (myCriticalSection);
        // myCriticalSection is now unlocked for the remainder of this block,
        // and re-locked at the end.
        ...do some stuff with it unlocked ...
    }
    // myCriticalSection gets unlocked here.
}
See Also
GenericScopedLock, CriticalSection, ScopedLock, ScopedUnlock
Public Member Functions
GenericScopedUnlock (const LockType &lock) noexcept
Creates a GenericScopedUnlock.
~GenericScopedUnlock () noexcept
Destructor.
Constructor & Destructor Documentation
template<class LockType> GenericScopedUnlock< LockType >::GenericScopedUnlock (const LockType & lock) explicit noexcept
Creates a GenericScopedUnlock.
As soon as it is created, this will unlock the CriticalSection, and when the ScopedLock object is deleted, the CriticalSection will be re-locked.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen! Best just to use it as a local stack object, rather than creating one with the new() operator.
template<class LockType> GenericScopedUnlock< LockType >::~GenericScopedUnlock () noexcept
Destructor.
The CriticalSection will be unlocked when the destructor is called.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen!
class GenericScopedTryLock
template<class LockType>
class GenericScopedTryLock< LockType >
Automatically locks and unlocks a mutex object.
Use one of these as a local variable to provide RAII-based locking of a mutex.
The templated class could be a CriticalSection, SpinLock, or anything else that provides enter() and exit() methods.
e.g.
CriticalSection myCriticalSection;
for (;;)
{
    const GenericScopedTryLock<CriticalSection> myScopedTryLock (myCriticalSection);
    // Unlike using a ScopedLock, this may fail to actually get the lock, so you
    // should test this with the isLocked() method before doing your thread-unsafe
    // action..
    if (myScopedTryLock.isLocked())
    {
       ...do some stuff...
    }
    else
    {
        ..our attempt at locking failed because another thread had already locked it..
    }
    // myCriticalSection gets unlocked here (if it was locked)
}
See Also
CriticalSection::tryEnter, GenericScopedLock, GenericScopedUnlock
Public Member Functions
GenericScopedTryLock (const LockType &lock) noexcept
Creates a GenericScopedTryLock.
~GenericScopedTryLock () noexcept
Destructor.
bool isLocked () const noexcept
Returns true if the mutex was successfully locked.
Constructor & Destructor Documentation
template<class LockType> GenericScopedTryLock< LockType >::GenericScopedTryLock (const LockType & lock) explicit noexcept
Creates a GenericScopedTryLock.
As soon as it is created, this will attempt to acquire the lock, and when the GenericScopedTryLock is deleted, the lock will be released (if the lock was successfully acquired).
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen! Best just to use it as a local stack object, rather than creating one with the new() operator.
template<class LockType> GenericScopedTryLock< LockType >::~GenericScopedTryLock () noexcept
Destructor.
The mutex will be unlocked (if it had been successfully locked) when the destructor is called.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen!
Member Function Documentation
template<class LockType> bool GenericScopedTryLock< LockType >::isLocked () const noexcept
Returns true if the mutex was successfully locked.
class ScopedReadLock
Automatically locks and unlocks a ReadWriteLock object.
Use one of these as a local variable to control access to a ReadWriteLock.
e.g.
ReadWriteLock myLock;
for (;;)
{
    const ScopedReadLock myScopedLock (myLock);
    // myLock is now locked
    ...do some stuff...
    // myLock gets unlocked here.
}
See Also
ReadWriteLock, ScopedWriteLock
Public Member Functions
ScopedReadLock (const ReadWriteLock &lock) noexcept
Creates a ScopedReadLock.
~ScopedReadLock () noexcept
Destructor.
Constructor & Destructor Documentation
ScopedReadLock::ScopedReadLock (const ReadWriteLock & lock) explicit noexcept
Creates a ScopedReadLock.
As soon as it is created, this will call ReadWriteLock::enterRead(), and when the ScopedReadLock object is deleted, the ReadWriteLock will be unlocked.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen! Best just to use it as a local stack object, rather than creating one with the new() operator.
ScopedReadLock::~ScopedReadLock () noexcept
Destructor.
The ReadWriteLock's exitRead() method will be called when the destructor is called.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen!
class ScopedWriteLock
Automatically locks and unlocks a ReadWriteLock object.
Use one of these as a local variable to control access to a ReadWriteLock.
e.g.
ReadWriteLock myLock;
for (;;)
{
    const ScopedWriteLock myScopedLock (myLock);
    // myLock is now locked
    ...do some stuff...
    // myLock gets unlocked here.
}
See Also
ReadWriteLock, ScopedReadLock
Public Member Functions
ScopedWriteLock (const ReadWriteLock &lock) noexcept
Creates a ScopedWriteLock.
~ScopedWriteLock () noexcept
Destructor.
Constructor & Destructor Documentation
ScopedWriteLock::ScopedWriteLock (const ReadWriteLock & lock) explicit noexcept
Creates a ScopedWriteLock.
As soon as it is created, this will call ReadWriteLock::enterWrite(), and when the ScopedWriteLock object is deleted, the ReadWriteLock will be unlocked.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen! Best just to use it as a local stack object, rather than creating one with the new() operator.
ScopedWriteLock::~ScopedWriteLock () noexcept
Destructor.
The ReadWriteLock's exitWrite() method will be called when the destructor is called.
Make sure this object is created and deleted by the same thread, otherwise there are no guarantees what will happen!
class SpinLock
A simple spin-lock class that can be used as a simple, low-overhead mutex for uncontended situations.
Note that unlike a CriticalSection, this type of lock is not re-entrant, and may be less efficient when used it a highly contended situation, but it's very small and requires almost no initialisation. It's most appropriate for simple situations where you're only going to hold the lock for a very brief time.
See Also
CriticalSection
Public Types
typedef GenericScopedLock
< SpinLock > ScopedLockType
Provides the type of scoped lock to use for locking a SpinLock.
typedef GenericScopedUnlock
< SpinLock > ScopedUnlockType
Provides the type of scoped unlocker to use with a SpinLock.
Public Member Functions
SpinLock () noexcept
~SpinLock () noexcept
void enter () const noexcept
Acquires the lock.
bool tryEnter () const noexcept
Attempts to acquire the lock, returning true if this was successful.
void exit () const noexcept
Releases the lock.
Member Typedef Documentation
typedef GenericScopedLock<SpinLock> SpinLock::ScopedLockType
Provides the type of scoped lock to use for locking a SpinLock.
typedef GenericScopedUnlock<SpinLock> SpinLock::ScopedUnlockType
Provides the type of scoped unlocker to use with a SpinLock.
Constructor & Destructor Documentation
SpinLock::SpinLock () noexcept
SpinLock::~SpinLock () noexcept
Member Function Documentation
void SpinLock::enter () const noexcept
Acquires the lock.
This will block until the lock has been successfully acquired by this thread. Note that a SpinLock is NOT re-entrant, and is not smart enough to know whether the caller thread already has the lock - so if a thread tries to acquire a lock that it already holds, this method will never return!
It's strongly recommended that you never call this method directly - instead use the ScopedLockType class to manage the locking using an RAII pattern instead.
bool SpinLock::tryEnter () const noexcept
Attempts to acquire the lock, returning true if this was successful.
void SpinLock::exit () const noexcept
Releases the lock.
References jassert.
class Thread
Encapsulates a thread.
Subclasses derive from Thread and implement the run() method, in which they do their business. The thread can then be started with the startThread() method and controlled with various other methods.
This class also contains some thread-related static methods, such as sleep(), yield(), getCurrentThreadId() etc.
See Also
CriticalSection, WaitableEvent, Process, ThreadWithProgressWindow, MessageManagerLock
Public Types
enum { realtimeAudioPriority = -1 }
Special realtime audio thread priority.
typedef void * ThreadID
A value type used for thread IDs.
Public Member Functions
Thread (const String &threadName, size_t threadStackSize=0)
Creates a thread.
virtual ~Thread ()
Destructor.
virtual void run ()=0
Must be implemented to perform the thread's actual code.
void startThread ()
Starts the thread running.
void startThread (int priority)
Starts the thread with a given priority.
bool stopThread (int timeOutMilliseconds)
Attempts to stop the thread running.
bool isThreadRunning () const
Returns true if the thread is currently active.
void signalThreadShouldExit ()
Sets a flag to tell the thread it should stop.
bool threadShouldExit () const
Checks whether the thread has been told to stop running.
bool waitForThreadToExit (int timeOutMilliseconds) const
Waits for the thread to stop.
bool setPriority (int priority)
Changes the thread's priority.
void setAffinityMask (uint32 affinityMask)
Sets the affinity mask for the thread.
bool wait (int timeOutMilliseconds) const
Makes the thread wait for a notification.
void notify () const
Wakes up the thread.
ThreadID getThreadId () const noexcept
Returns the ID of this thread.
const String & getThreadName () const noexcept
Returns the name of the thread.
Static Public Member Functions
static void launch (std::function< void()> functionToRun)
Invokes a lambda or function on its own thread.
static bool currentThreadShouldExit ()
Checks whether the current thread has been told to stop running.
static bool setCurrentThreadPriority (int priority)
Changes the priority of the caller thread.
static void JUCE_CALLTYPE setCurrentThreadAffinityMask (uint32 affinityMask)
Changes the affinity mask for the caller thread.
static void JUCE_CALLTYPE sleep (int milliseconds)
static void JUCE_CALLTYPE yield ()
Yields the calling thread's current time-slot.
static ThreadID JUCE_CALLTYPE getCurrentThreadId ()
Returns an id that identifies the caller thread.
static Thread *JUCE_CALLTYPE getCurrentThread ()
Finds the thread object that is currently running.
static void JUCE_CALLTYPE setCurrentThreadName (const String &newThreadName)
Changes the name of the caller thread.
Member Typedef Documentation
typedef void* Thread::ThreadID
A value type used for thread IDs.
See Also
getCurrentThreadId(), getThreadId()
Member Enumeration Documentation
anonymous enum
Special realtime audio thread priority.
This priority will create a high-priority thread which is best suited for realtime audio processing.
Currently, this priority is identical to priority 9, except when building for Android with OpenSL support.
In this case, JUCE will ask OpenSL to consturct a super high priority thread specifically for realtime audio processing.
Note that this priority can only be set before the thread has started. Switching to this priority, or from this priority to a different priority, is not supported under Android and will assert.
For best performance this thread should yield at regular intervals and not call any blocking APIS.
See Also
startThread, setPriority, sleep, WaitableEvent
Enumerator
realtimeAudioPriority
Constructor & Destructor Documentation
Thread::Thread (const String & threadName, size_t threadStackSize = 0) explicit
Creates a thread.
When first created, the thread is not running. Use the startThread() method to start it.
Parameters
threadName The name of the thread which typically appears in debug logs and profiles.
threadStackSize The size of the stack of the thread. If this value is zero then the default stack size of the OS will be used.
virtual Thread::~Thread () virtual
Destructor.
You must never attempt to delete a Thread object while it's still running - always call stopThread() and make sure your thread has stopped before deleting the object. Failing to do so will throw an assertion, and put you firmly into undefined behaviour territory.
Member Function Documentation
virtual void Thread::run () pure virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
void Thread::startThread ()
Starts the thread running.
This will cause the thread's run() method to be called by a new thread. If this thread is already running, startThread() won't do anything.
See Also
stopThread
void Thread::startThread (int priority)
Starts the thread with a given priority.
Launches the thread with a given priority, where 0 = lowest, 10 = highest. If the thread is already running, its priority will be changed.
See Also
startThread, setPriority, realtimeAudioPriority
bool Thread::stopThread (int timeOutMilliseconds)
Attempts to stop the thread running.
This method will cause the threadShouldExit() method to return true and call notify() in case the thread is currently waiting.
Hopefully the thread will then respond to this by exiting cleanly, and the stopThread method will wait for a given time-period for this to happen.
If the thread is stuck and fails to respond after the time-out, it gets forcibly killed, which is a very bad thing to happen, as it could still be holding locks, etc. which are needed by other parts of your program.
Parameters
timeOutMilliseconds The number of milliseconds to wait for the thread to finish before killing it by force. A negative value in here will wait forever.
Returns
true if the thread was cleanly stopped before the timeout, or false if it had to be killed by force.
See Also
signalThreadShouldExit, threadShouldExit, waitForThreadToExit, isThreadRunning
static void Thread::launch (std::function< void()> functionToRun) static
Invokes a lambda or function on its own thread.
This will spin up a Thread object which calls the function and then exits. Bear in mind that starting and stopping a thread can be a fairly heavyweight operation, so you might prefer to use a ThreadPool if you're kicking off a lot of short background tasks. Also note that using an anonymous thread makes it very difficult to interrupt the function when you need to stop it, e.g. when your app quits. So it's up to you to deal with situations where the function may fail to stop in time.
bool Thread::isThreadRunning () const
Returns true if the thread is currently active.
void Thread::signalThreadShouldExit ()
Sets a flag to tell the thread it should stop.
Calling this means that the threadShouldExit() method will then return true. The thread should be regularly checking this to see whether it should exit.
If your thread makes use of wait(), you might want to call notify() after calling this method, to interrupt any waits that might be in progress, and allow it to reach a point where it can exit.
See Also
threadShouldExit
waitForThreadToExit
bool Thread::threadShouldExit () const
Checks whether the thread has been told to stop running.
Threads need to check this regularly, and if it returns true, they should return from their run() method at the first possible opportunity.
See Also
signalThreadShouldExit, currentThreadShouldExit
static bool Thread::currentThreadShouldExit () static
Checks whether the current thread has been told to stop running.
On the message thread, this will always return false, otherwise it will return threadShouldExit() called on the current thread.
See Also
threadShouldExit
bool Thread::waitForThreadToExit (int timeOutMilliseconds) const
Waits for the thread to stop.
This will wait until isThreadRunning() is false or until a timeout expires.
Parameters
timeOutMilliseconds the time to wait, in milliseconds. If this value is less than zero, it will wait forever.
Returns
true if the thread exits, or false if the timeout expires first.
bool Thread::setPriority (int priority)
Changes the thread's priority.
May return false if for some reason the priority can't be changed.
Parameters
priority the new priority, in the range 0 (lowest) to 10 (highest). A priority of 5 is normal.
See Also
realtimeAudioPriority
static bool Thread::setCurrentThreadPriority (int priority) static
Changes the priority of the caller thread.
Similar to setPriority(), but this static method acts on the caller thread. May return false if for some reason the priority can't be changed.
See Also
setPriority
void Thread::setAffinityMask (uint32 affinityMask)
Sets the affinity mask for the thread.
This will only have an effect next time the thread is started - i.e. if the thread is already running when called, it'll have no effect.
See Also
setCurrentThreadAffinityMask
static void JUCE_CALLTYPE Thread::setCurrentThreadAffinityMask (uint32 affinityMask) static
Changes the affinity mask for the caller thread.
This will change the affinity mask for the thread that calls this static method.
See Also
setAffinityMask
static void JUCE_CALLTYPE Thread::sleep (int milliseconds) static
static void JUCE_CALLTYPE Thread::yield () static
Yields the calling thread's current time-slot.
bool Thread::wait (int timeOutMilliseconds) const
Makes the thread wait for a notification.
This puts the thread to sleep until either the timeout period expires, or another thread calls the notify() method to wake it up.
A negative time-out value means that the method will wait indefinitely.
Returns
true if the event has been signalled, false if the timeout expires.
void Thread::notify () const
Wakes up the thread.
If the thread has called the wait() method, this will wake it up.
See Also
wait
static ThreadID JUCE_CALLTYPE Thread::getCurrentThreadId () static
Returns an id that identifies the caller thread.
To find the ID of a particular thread object, use getThreadId().
Returns
a unique identifier that identifies the calling thread.
See Also
getThreadId
Referenced by ThreadLocalValue< Type >::get(), and ThreadLocalValue< Type >::releaseCurrentThreadStorage().
static Thread* JUCE_CALLTYPE Thread::getCurrentThread () static
Finds the thread object that is currently running.
Note that the main UI thread (or other non-Juce threads) don't have a Thread object associated with them, so this will return nullptr.
ThreadID Thread::getThreadId () const noexcept
Returns the ID of this thread.
That means the ID of this thread object - not of the thread that's calling the method. This can change when the thread is started and stopped, and will be invalid if the thread's not actually running.
See Also
getCurrentThreadId
const String& Thread::getThreadName () const noexcept
Returns the name of the thread.
This is the name that gets set in the constructor.
static void JUCE_CALLTYPE Thread::setCurrentThreadName (const String & newThreadName) static
Changes the name of the caller thread.
Different OSes may place different length or content limits on this name.
class ThreadLocalValue
template<typename Type>
class ThreadLocalValue< Type >
Provides cross-platform support for thread-local objects.
This class holds an internal list of objects of the templated type, keeping an instance for each thread that requests one. The first time a thread attempts to access its value, an object is created and added to the list for that thread.
Typically, you'll probably want to create a static instance of a ThreadLocalValue object, or hold one within a singleton.
The templated class for your value must be a primitive type, or a simple POD struct.
When a thread no longer needs to use its value, it can call releaseCurrentThreadStorage() to allow the storage to be re-used by another thread. If a thread exits without calling this method, the object storage will be left allocated until the ThreadLocalValue object is deleted.
Public Member Functions
ThreadLocalValue () noexcept
~ThreadLocalValue ()
Destructor.
Type & operator* () const noexcept
Returns a reference to this thread's instance of the value.
operator Type * () const noexcept
Returns a pointer to this thread's instance of the value.
Type * operator-> () const noexcept
Accesses a method or field of the value object.
ThreadLocalValue & operator= (const Type &newValue)
Assigns a new value to the thread-local object.
Type & get () const noexcept
Returns a reference to this thread's instance of the value.
void releaseCurrentThreadStorage ()
Called by a thread before it terminates, to allow this class to release any storage associated with the thread.
Constructor & Destructor Documentation
template<typename Type > ThreadLocalValue< Type >::ThreadLocalValue () noexcept
template<typename Type > ThreadLocalValue< Type >::~ThreadLocalValue ()
Destructor.
When this object is deleted, all the value objects for all threads will be deleted.
References Atomic< Type >::get().
Member Function Documentation
template<typename Type > Type& ThreadLocalValue< Type >::operator* () const noexcept
Returns a reference to this thread's instance of the value.
Note that the first time a thread tries to access the value, an instance of the value object will be created - so if your value's class has a non-trivial constructor, be aware that this method could invoke it.
template<typename Type > ThreadLocalValue< Type >::operator Type * () const noexcept
Returns a pointer to this thread's instance of the value.
Note that the first time a thread tries to access the value, an instance of the value object will be created - so if your value's class has a non-trivial constructor, be aware that this method could invoke it.
template<typename Type > Type* ThreadLocalValue< Type >::operator-> () const noexcept
Accesses a method or field of the value object.
Note that the first time a thread tries to access the value, an instance of the value object will be created - so if your value's class has a non-trivial constructor, be aware that this method could invoke it.
template<typename Type > ThreadLocalValue& ThreadLocalValue< Type >::operator= (const Type & newValue)
Assigns a new value to the thread-local object.
template<typename Type > Type& ThreadLocalValue< Type >::get () const noexcept
Returns a reference to this thread's instance of the value.
Note that the first time a thread tries to access the value, an instance of the value object will be created - so if your value's class has a non-trivial constructor, be aware that this method could invoke it.
References Atomic< Type >::compareAndSetBool(), Atomic< Type >::get(), and Thread::getCurrentThreadId().
template<typename Type > void ThreadLocalValue< Type >::releaseCurrentThreadStorage ()
Called by a thread before it terminates, to allow this class to release any storage associated with the thread.
References Atomic< Type >::get(), and Thread::getCurrentThreadId().
class ThreadPoolJob
A task that is executed by a ThreadPool object.
A ThreadPool keeps a list of ThreadPoolJob objects which are executed by its threads.
The runJob() method needs to be implemented to do the task, and if the code that does the work takes a significant time to run, it must keep checking the shouldExit() method to see if something is trying to interrupt the job. If shouldExit() returns true, the runJob() method must return immediately.
See Also
ThreadPool, Thread
Public Types
enum JobStatus { jobHasFinished = 0, jobNeedsRunningAgain }
These are the values that can be returned by the runJob() method.
Public Member Functions
ThreadPoolJob (const String &name)
Creates a thread pool job object.
virtual ~ThreadPoolJob ()
Destructor.
String getJobName () const
Returns the name of this job.
void setJobName (const String &newName)
Changes the job's name.
virtual JobStatus runJob ()=0
Peforms the actual work that this job needs to do.
bool isRunning () const noexcept
Returns true if this job is currently running its runJob() method.
bool shouldExit () const noexcept
Returns true if something is trying to interrupt this job and make it stop.
void signalJobShouldExit ()
Calling this will cause the shouldExit() method to return true, and the job should (if it's been implemented correctly) stop as soon as possible.
Static Public Member Functions
static ThreadPoolJob * getCurrentThreadPoolJob ()
If the calling thread is being invoked inside a runJob() method, this will return the ThreadPoolJob that it belongs to.
Member Enumeration Documentation
enum ThreadPoolJob::JobStatus
These are the values that can be returned by the runJob() method.
Enumerator
jobHasFinished
indicates that the job has finished and can be removed from the pool.
jobNeedsRunningAgain
indicates that the job would like to be called again when a thread is free.
Constructor & Destructor Documentation
ThreadPoolJob::ThreadPoolJob (const String & name) explicit
Creates a thread pool job object.
After creating your job, add it to a thread pool with ThreadPool::addJob().
virtual ThreadPoolJob::~ThreadPoolJob () virtual
Destructor.
Member Function Documentation
String ThreadPoolJob::getJobName () const
Returns the name of this job.
See Also
setJobName
void ThreadPoolJob::setJobName (const String & newName)
Changes the job's name.
See Also
getJobName
virtual JobStatus ThreadPoolJob::runJob () pure virtual
Peforms the actual work that this job needs to do.
Your subclass must implement this method, in which is does its work.
If the code in this method takes a significant time to run, it must repeatedly check the shouldExit() method to see if something is trying to interrupt the job. If shouldExit() ever returns true, the runJob() method must return immediately.
If this method returns jobHasFinished, then the job will be removed from the pool immediately. If it returns jobNeedsRunningAgain, then the job will be left in the pool and will get a chance to run again as soon as a thread is free.
See Also
shouldExit()
bool ThreadPoolJob::isRunning () const noexcept
Returns true if this job is currently running its runJob() method.
bool ThreadPoolJob::shouldExit () const noexcept
Returns true if something is trying to interrupt this job and make it stop.
Your runJob() method must call this whenever it gets a chance, and if it ever returns true, the runJob() method must return immediately.
See Also
signalJobShouldExit()
void ThreadPoolJob::signalJobShouldExit ()
Calling this will cause the shouldExit() method to return true, and the job should (if it's been implemented correctly) stop as soon as possible.
See Also
shouldExit()
static ThreadPoolJob* ThreadPoolJob::getCurrentThreadPoolJob () static
If the calling thread is being invoked inside a runJob() method, this will return the ThreadPoolJob that it belongs to.
class ThreadPool
A set of threads that will run a list of jobs.
When a ThreadPoolJob object is added to the ThreadPool's list, its runJob() method will be called by the next pooled thread that becomes free.
See Also
ThreadPoolJob, Thread
Public Member Functions
ThreadPool (int numberOfThreads, size_t threadStackSize=0)
Creates a thread pool.
ThreadPool ()
Creates a thread pool with one thread per CPU core.
~ThreadPool ()
Destructor.
void addJob (ThreadPoolJob *job, bool deleteJobWhenFinished)
Adds a job to the queue.
void addJob (std::function< ThreadPoolJob::JobStatus()> job)
Adds a lambda function to be called as a job.
void addJob (std::function< void()> job)
Adds a lambda function to be called as a job.
bool removeJob (ThreadPoolJob *job, bool interruptIfRunning, int timeOutMilliseconds)
Tries to remove a job from the pool.
bool removeAllJobs (bool interruptRunningJobs, int timeOutMilliseconds, JobSelector *selectedJobsToRemove=nullptr)
Tries to remove all jobs from the pool.
int getNumJobs () const
Returns the number of jobs currently running or queued.
int getNumThreads () const
Returns the number of threads assigned to this thread pool.
ThreadPoolJob * getJob (int index) const
Returns one of the jobs in the queue.
bool contains (const ThreadPoolJob *job) const
Returns true if the given job is currently queued or running.
bool isJobRunning (const ThreadPoolJob *job) const
Returns true if the given job is currently being run by a thread.
bool waitForJobToFinish (const ThreadPoolJob *job, int timeOutMilliseconds) const
Waits until a job has finished running and has been removed from the pool.
StringArray getNamesOfAllJobs (bool onlyReturnActiveJobs) const
Returns a list of the names of all the jobs currently running or queued.
bool setThreadPriorities (int newPriority)
Changes the priority of all the threads.
Constructor & Destructor Documentation
ThreadPool::ThreadPool (int numberOfThreads, size_t threadStackSize = 0)
Creates a thread pool.
Once you've created a pool, you can give it some jobs by calling addJob().
Parameters
numberOfThreads the number of threads to run. These will be started immediately, and will run until the pool is deleted.
threadStackSize the size of the stack of each thread. If this value is zero then the default stack size of the OS will be used.
ThreadPool::ThreadPool ()
Creates a thread pool with one thread per CPU core.
Once you've created a pool, you can give it some jobs by calling addJob(). If you want to specify the number of threads, use the other constructor; this one creates a pool which has one thread for each CPU core.
See Also
SystemStats::getNumCpus()
ThreadPool::~ThreadPool ()
Destructor.
This will attempt to remove all the jobs before deleting, but if you want to specify a timeout, you should call removeAllJobs() explicitly before deleting the pool.
Member Function Documentation
void ThreadPool::addJob (ThreadPoolJob * job, bool deleteJobWhenFinished)
Adds a job to the queue.
Once a job has been added, then the next time a thread is free, it will run the job's ThreadPoolJob::runJob() method. Depending on the return value of the runJob() method, the pool will either remove the job from the pool or add it to the back of the queue to be run again.
If deleteJobWhenFinished is true, then the job object will be owned and deleted by the pool when not needed - if you do this, make sure that your object's destructor is thread-safe.
If deleteJobWhenFinished is false, the pointer will be used but not deleted, and the caller is responsible for making sure the object is not deleted before it has been removed from the pool.
void ThreadPool::addJob (std::function< ThreadPoolJob::JobStatus()> job)
Adds a lambda function to be called as a job.
This will create an internal ThreadPoolJob object to encapsulate and call the lambda.
void ThreadPool::addJob (std::function< void()> job)
Adds a lambda function to be called as a job.
This will create an internal ThreadPoolJob object to encapsulate and call the lambda.
bool ThreadPool::removeJob (ThreadPoolJob * job, bool interruptIfRunning, int timeOutMilliseconds)
Tries to remove a job from the pool.
If the job isn't yet running, this will simply remove it. If it is running, it will wait for it to finish.
If the timeout period expires before the job finishes running, then the job will be left in the pool and this will return false. It returns true if the job is successfully stopped and removed.
Parameters
job the job to remove
interruptIfRunning if true, then if the job is currently busy, its ThreadPoolJob::signalJobShouldExit() method will be called to try to interrupt it. If false, then if the job will be allowed to run until it stops normally (or the timeout expires)
timeOutMilliseconds the length of time this method should wait for the job to finish before giving up and returning false
bool ThreadPool::removeAllJobs (bool interruptRunningJobs, int timeOutMilliseconds, JobSelector * selectedJobsToRemove = nullptr)
Tries to remove all jobs from the pool.
Parameters
interruptRunningJobs if true, then all running jobs will have their ThreadPoolJob::signalJobShouldExit() methods called to try to interrupt them
timeOutMilliseconds the length of time this method should wait for all the jobs to finish before giving up and returning false
selectedJobsToRemove if this is not a nullptr, the JobSelector object is asked to decide which jobs should be removed. If it is a nullptr, all jobs are removed
Returns
true if all jobs are successfully stopped and removed; false if the timeout period expires while waiting for one or more jobs to stop
int ThreadPool::getNumJobs () const
Returns the number of jobs currently running or queued.
int ThreadPool::getNumThreads () const
Returns the number of threads assigned to this thread pool.
ThreadPoolJob* ThreadPool::getJob (int index) const
Returns one of the jobs in the queue.
Note that this can be a very volatile list as jobs might be continuously getting shifted around in the list, and this method may return nullptr if the index is currently out-of-range.
bool ThreadPool::contains (const ThreadPoolJob * job) const
Returns true if the given job is currently queued or running.
See Also
isJobRunning()
bool ThreadPool::isJobRunning (const ThreadPoolJob * job) const
Returns true if the given job is currently being run by a thread.
bool ThreadPool::waitForJobToFinish (const ThreadPoolJob * job, int timeOutMilliseconds) const
Waits until a job has finished running and has been removed from the pool.
This will wait until the job is no longer in the pool - i.e. until its runJob() method returns ThreadPoolJob::jobHasFinished.
If the timeout period expires before the job finishes, this will return false; it returns true if the job has finished successfully.
StringArray ThreadPool::getNamesOfAllJobs (bool onlyReturnActiveJobs) const
Returns a list of the names of all the jobs currently running or queued.
If onlyReturnActiveJobs is true, only the ones currently running are returned.
bool ThreadPool::setThreadPriorities (int newPriority)
Changes the priority of all the threads.
This will call Thread::setPriority() for each thread in the pool. May return false if for some reason the priority can't be changed.
class TimeSliceClient
Used by the TimeSliceThread class.
To register your class with a TimeSliceThread, derive from this class and use the TimeSliceThread::addTimeSliceClient() method to add it to the list.
Make sure you always call TimeSliceThread::removeTimeSliceClient() before deleting your client!
See Also
TimeSliceThread
Public Member Functions
virtual ~TimeSliceClient ()
Destructor.
virtual int useTimeSlice ()=0
Called back by a TimeSliceThread.
Constructor & Destructor Documentation
virtual TimeSliceClient::~TimeSliceClient () virtual
Destructor.
Member Function Documentation
virtual int TimeSliceClient::useTimeSlice () pure virtual
Called back by a TimeSliceThread.
When you register this class with it, a TimeSliceThread will repeatedly call this method.
The implementation of this method should use its time-slice to do something that's quick - never block for longer than absolutely necessary.
Returns
Your method should return the number of milliseconds which it would like to wait before being called again. Returning 0 will make the thread call again as soon as possible (after possibly servicing other busy clients). If you return a value below zero, your client will be removed from the list of clients, and won't be called again. The value you specify isn't a guaranteee, and is only used as a hint by the thread - the actual time before the next callback may be more or less than specified. You can force the TimeSliceThread to wake up and poll again immediately by calling its notify() method.
class TimeSliceThread
A thread that keeps a list of clients, and calls each one in turn, giving them all a chance to run some sort of short task.
See Also
TimeSliceClient, Thread
Public Member Functions
TimeSliceThread (const String &threadName)
Creates a TimeSliceThread.
~TimeSliceThread ()
Destructor.
void addTimeSliceClient (TimeSliceClient *clientToAdd, int millisecondsBeforeStarting=0)
Adds a client to the list.
void moveToFrontOfQueue (TimeSliceClient *clientToMove)
If the given client is waiting in the queue, it will be moved to the front and given a time-slice as soon as possible.
void removeTimeSliceClient (TimeSliceClient *clientToRemove)
Removes a client from the list.
void removeAllClients ()
Removes all the active and pending clients from the list.
int getNumClients () const
Returns the number of registered clients.
TimeSliceClient * getClient (int index) const
Returns one of the registered clients.
Public Member Functions inherited from Thread
Thread (const String &threadName, size_t threadStackSize=0)
Creates a thread.
virtual ~Thread ()
Destructor.
virtual void run ()=0
Must be implemented to perform the thread's actual code.
void startThread ()
Starts the thread running.
void startThread (int priority)
Starts the thread with a given priority.
bool stopThread (int timeOutMilliseconds)
Attempts to stop the thread running.
bool isThreadRunning () const
Returns true if the thread is currently active.
void signalThreadShouldExit ()
Sets a flag to tell the thread it should stop.
bool threadShouldExit () const
Checks whether the thread has been told to stop running.
bool waitForThreadToExit (int timeOutMilliseconds) const
Waits for the thread to stop.
bool setPriority (int priority)
Changes the thread's priority.
void setAffinityMask (uint32 affinityMask)
Sets the affinity mask for the thread.
bool wait (int timeOutMilliseconds) const
Makes the thread wait for a notification.
void notify () const
Wakes up the thread.
ThreadID getThreadId () const noexcept
Returns the ID of this thread.
const String & getThreadName () const noexcept
Returns the name of the thread.
Additional Inherited Members
Public Types inherited from Thread
enum { realtimeAudioPriority = -1 }
Special realtime audio thread priority.
typedef void * ThreadID
A value type used for thread IDs.
Static Public Member Functions inherited from Thread
static void launch (std::function< void()> functionToRun)
Invokes a lambda or function on its own thread.
static bool currentThreadShouldExit ()
Checks whether the current thread has been told to stop running.
static bool setCurrentThreadPriority (int priority)
Changes the priority of the caller thread.
static void JUCE_CALLTYPE setCurrentThreadAffinityMask (uint32 affinityMask)
Changes the affinity mask for the caller thread.
static void JUCE_CALLTYPE sleep (int milliseconds)
static void JUCE_CALLTYPE yield ()
Yields the calling thread's current time-slot.
static ThreadID JUCE_CALLTYPE getCurrentThreadId ()
Returns an id that identifies the caller thread.
static Thread *JUCE_CALLTYPE getCurrentThread ()
Finds the thread object that is currently running.
static void JUCE_CALLTYPE setCurrentThreadName (const String &newThreadName)
Changes the name of the caller thread.
Constructor & Destructor Documentation
TimeSliceThread::TimeSliceThread (const String & threadName) explicit
Creates a TimeSliceThread.
When first created, the thread is not running. Use the startThread() method to start it.
TimeSliceThread::~TimeSliceThread ()
Destructor.
Deleting a Thread object that is running will only give the thread a brief opportunity to stop itself cleanly, so it's recommended that you should always call stopThread() with a decent timeout before deleting, to avoid the thread being forcibly killed (which is a Bad Thing).
Member Function Documentation
void TimeSliceThread::addTimeSliceClient (TimeSliceClient * clientToAdd, int millisecondsBeforeStarting = 0)
Adds a client to the list.
The client's callbacks will start after the number of milliseconds specified by millisecondsBeforeStarting (and this may happen before this method has returned).
void TimeSliceThread::moveToFrontOfQueue (TimeSliceClient * clientToMove)
If the given client is waiting in the queue, it will be moved to the front and given a time-slice as soon as possible.
If the specified client has not been added, nothing will happen.
void TimeSliceThread::removeTimeSliceClient (TimeSliceClient * clientToRemove)
Removes a client from the list.
This method will make sure that all callbacks to the client have completely finished before the method returns.
void TimeSliceThread::removeAllClients ()
Removes all the active and pending clients from the list.
This method will make sure that all callbacks to clients have finished before the method returns.
int TimeSliceThread::getNumClients () const
Returns the number of registered clients.
TimeSliceClient* TimeSliceThread::getClient (int index) const
Returns one of the registered clients.
class WaitableEvent
Allows threads to wait for events triggered by other threads.
A thread can call wait() on a WaitableObject, and this will suspend the calling thread until another thread wakes it up by calling the signal() method.
Public Member Functions
WaitableEvent (bool manualReset=false) noexcept
Creates a WaitableEvent object.
~WaitableEvent () noexcept
Destructor.
bool wait (int timeOutMilliseconds=-1) const noexcept
Suspends the calling thread until the event has been signalled.
void signal () const noexcept
Wakes up any threads that are currently waiting on this object.
void reset () const noexcept
Resets the event to an unsignalled state.
Constructor & Destructor Documentation
WaitableEvent::WaitableEvent (bool manualReset = false) explicit noexcept
Creates a WaitableEvent object.
The object is initially in an unsignalled state.
Parameters
manualReset If this is false, the event will be reset automatically when the wait() method is called. If manualReset is true, then once the event is signalled, the only way to reset it will be by calling the reset() method.
WaitableEvent::~WaitableEvent () noexcept
Destructor.
If other threads are waiting on this object when it gets deleted, this can cause nasty errors, so be careful!
Member Function Documentation
bool WaitableEvent::wait (int timeOutMilliseconds = -1) const noexcept
Suspends the calling thread until the event has been signalled.
This will wait until the object's signal() method is called by another thread, or until the timeout expires.
After the event has been signalled, this method will return true and if manualReset was set to false in the WaitableEvent's constructor, then the event will be reset.
Parameters
timeOutMilliseconds the maximum time to wait, in milliseconds. A negative value will cause it to wait forever.
Returns
true if the object has been signalled, false if the timeout expires first.
See Also
signal, reset
void WaitableEvent::signal () const noexcept
Wakes up any threads that are currently waiting on this object.
If signal() is called when nothing is waiting, the next thread to call wait() will return immediately and reset the signal.
If the WaitableEvent is manual reset, all current and future threads that wait upon this object will be woken, until reset() is explicitly called.
If the WaitableEvent is automatic reset, and one or more threads is waiting upon the object, then one of them will be woken up. If no threads are currently waiting, then the next thread to call wait() will be woken up. As soon as a thread is woken, the signal is automatically reset.
See Also
wait, reset
void WaitableEvent::reset () const noexcept
Resets the event to an unsignalled state.
If it's not already signalled, this does nothing.
Typedef Documentation
typedef CriticalSection::ScopedLockType ScopedLock
Automatically locks and unlocks a CriticalSection object.
You can use a ScopedLock as a local variable to provide RAII-based locking of a CriticalSection.
e.g.
struct MyObject
{
    CriticalSection objectLock;
    // assuming that this example function will be called by multiple threads
    void foo()
    {
        const ScopedLock myScopedLock (objectLock);
        // objectLock is now locked..
        ...do some thread-safe work here...
        // ..and objectLock gets unlocked here, as myScopedLock goes out of
        // scope at the end of the block
    }
};
See Also
CriticalSection, ScopedUnlock
typedef CriticalSection::ScopedUnlockType ScopedUnlock
Automatically unlocks and re-locks a CriticalSection object.
This is the reverse of a ScopedLock object - instead of locking the critical section for the lifetime of this object, it unlocks it.
Make sure you don't try to unlock critical sections that aren't actually locked!
e.g.
struct MyObject
{
    CriticalSection objectLock;
    void foo()
    {
        {
            const ScopedLock myScopedLock (objectLock);
            // objectLock is now locked..
            {
                ScopedUnlock myUnlocker (objectLock);
                // ..and now unlocked..
            }
            // ..and now locked again..
        }
        // ..and finally unlocked.
    }
};
See Also
CriticalSection, ScopedLock
typedef CriticalSection::ScopedTryLockType ScopedTryLock
Automatically tries to lock and unlock a CriticalSection object.
Use one of these as a local variable to control access to a CriticalSection.
e.g.
struct MyObject
{
    CriticalSection objectLock;
    void foo()
    {
        const ScopedTryLock myScopedTryLock (objectLock);
        // Unlike using a ScopedLock, this may fail to actually get the lock, so you
        // must call the isLocked() method before making any assumptions..
        if (myScopedTryLock.isLocked())
        {
           ...safely do some work...
        }
        else
        {
            // If we get here, then our attempt at locking failed because another thread had already locked it..
        }
    }
};
See Also
CriticalSection::tryEnter, ScopedLock, ScopedUnlock, ScopedReadLock