JUCE: juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes > Struct Template Reference
juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes > Struct Template Reference
This helper class allocates a block of 7-bit bytes and can push sequences of bits into it.
Classes
struct State
Public Member Functions
const void * getData () const noexcept
int size () const noexcept
bool hasCapacity (int bitsNeeded) const noexcept
void writeHeaderSysexBytes (uint8 deviceIndex) noexcept
void writePacketSysexFooter () noexcept
template<int numBits>
Packed7BitArrayBuilder & operator<< (IntegerWithBitSize< numBits > value) noexcept
void writeBits (uint32 value, int numBits) noexcept
State getState () const noexcept
void restore (State state) noexcept
Detailed Description
template<int allocatedBytes>
struct juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >
This helper class allocates a block of 7-bit bytes and can push sequences of bits into it.
See Also
Packed7BitArrayReader
Member Function Documentation
template<int allocatedBytes> const void* juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::getData () const noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::getData().
template<int allocatedBytes> int juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::size () const noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size().
template<int allocatedBytes> bool juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity (int bitsNeeded) const noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addBlockReset(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addConfigSetMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addFactoryReset(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addProgramEventMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addSetBlockName(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::beginDataChanges(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::deviceControlMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::endDataChanges(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::skipBytes(), juce::BlocksProtocol::Packed7BitArrayBuilder< maxPacketBytes >::writeBits(), and juce::BlocksProtocol::Packed7BitArrayBuilder< maxPacketBytes >::writePacketSysexFooter().
template<int allocatedBytes> void juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::writeHeaderSysexBytes (uint8 deviceIndex) noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
template<int allocatedBytes> void juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::writePacketSysexFooter () noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter().
template<int allocatedBytes> template<int numBits> Packed7BitArrayBuilder& juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::operator<< (IntegerWithBitSize< numBits > value) noexcept
template<int allocatedBytes> void juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::writeBits (uint32 value, int numBits) noexcept
Referenced by juce::BlocksProtocol::Packed7BitArrayBuilder< maxPacketBytes >::operator<<().
template<int allocatedBytes> State juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::getState () const noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::skipBytes().
template<int allocatedBytes> void juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::restore (State state) noexcept
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::skipBytes().
The documentation for this struct was generated from the following file:
juce_BitPackingUtilities.h