JUCE: juce::DefaultHashFunctions Struct Reference
juce::DefaultHashFunctions Struct Reference
containers
A simple class to generate hash functions for some primitive types, intended for use with the HashMap class.
Static Public Member Functions
static int generateHash (uint32 key, int upperLimit) noexcept
Generates a simple hash from an unsigned int.
static int generateHash (int32 key, int upperLimit) noexcept
Generates a simple hash from an integer.
static int generateHash (uint64 key, int upperLimit) noexcept
Generates a simple hash from a uint64.
static int generateHash (int64 key, int upperLimit) noexcept
Generates a simple hash from an int64.
static int generateHash (const String &key, int upperLimit) noexcept
Generates a simple hash from a string.
static int generateHash (const var &key, int upperLimit) noexcept
Generates a simple hash from a variant.
static int generateHash (const void *key, int upperLimit) noexcept
Generates a simple hash from a void ptr.
Detailed Description
A simple class to generate hash functions for some primitive types, intended for use with the HashMap class.
See Also
HashMap
Member Function Documentation
static int juce::DefaultHashFunctions::generateHash (uint32 key, int upperLimit) static noexcept
Generates a simple hash from an unsigned int.
static int juce::DefaultHashFunctions::generateHash (int32 key, int upperLimit) static noexcept
Generates a simple hash from an integer.
References generateHash().
Referenced by generateHash().
static int juce::DefaultHashFunctions::generateHash (uint64 key, int upperLimit) static noexcept
Generates a simple hash from a uint64.
static int juce::DefaultHashFunctions::generateHash (int64 key, int upperLimit) static noexcept
Generates a simple hash from an int64.
References generateHash().
Referenced by generateHash().
static int juce::DefaultHashFunctions::generateHash (const String & key, int upperLimit) static noexcept
Generates a simple hash from a string.
References generateHash().
Referenced by generateHash().
static int juce::DefaultHashFunctions::generateHash (const var & key, int upperLimit) static noexcept
Generates a simple hash from a variant.
References generateHash().
Referenced by generateHash().
static int juce::DefaultHashFunctions::generateHash (const void * key, int upperLimit) static noexcept
Generates a simple hash from a void ptr.
References generateHash().
Referenced by generateHash().
The documentation for this struct was generated from the following file:
juce_HashMap.h