JUCE: juce::VST3BufferExchange< FloatType > Struct Template Reference
juce::VST3BufferExchange< FloatType > Struct Template Reference
format_types
Public Types
typedef Array< FloatType * > Bus
typedef Array< Bus > BusMap
Static Public Member Functions
static void assignRawPointer (Steinberg::Vst::AudioBusBuffers &vstBuffers, float **raw)
static void assignRawPointer (Steinberg::Vst::AudioBusBuffers &vstBuffers, double **raw)
static void associateBufferTo (Steinberg::Vst::AudioBusBuffers &vstBuffers, Bus &bus, AudioBuffer< FloatType > &buffer, int numChannels, int channelStartOffset, int sampleOffset=0)
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
static void mapArrangementToBuses (int &channelIndexOffset, int index, Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, const AudioChannelSet &arrangement, AudioBuffer< FloatType > &source)
static void mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, const Array< AudioChannelSet > &arrangements, AudioBuffer< FloatType > &source)
static void mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > &result, Steinberg::Vst::IAudioProcessor &processor, BusMap &busMapToUse, bool isInput, int numBuses, AudioBuffer< FloatType > &source)
Member Typedef Documentation
template<typename FloatType> typedef Array<FloatType*> juce::VST3BufferExchange< FloatType >::Bus
template<typename FloatType> typedef Array<Bus> juce::VST3BufferExchange< FloatType >::BusMap
Member Function Documentation
template<typename FloatType> static void juce::VST3BufferExchange< FloatType >::assignRawPointer (Steinberg::Vst::AudioBusBuffers & vstBuffers, float ** raw) static
Referenced by juce::VST3BufferExchange< float >::associateBufferTo().
template<typename FloatType> static void juce::VST3BufferExchange< FloatType >::assignRawPointer (Steinberg::Vst::AudioBusBuffers & vstBuffers, double ** raw) static
template<typename FloatType> static void juce::VST3BufferExchange< FloatType >::associateBufferTo (Steinberg::Vst::AudioBusBuffers & vstBuffers, Bus & bus, AudioBuffer< FloatType > & buffer, int numChannels, int channelStartOffset, int sampleOffset = 0) static
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
Warning
For speed, does not check the channel count and offsets according to the AudioSampleBuffer
Referenced by juce::VST3BufferExchange< float >::mapArrangementToBuses().
template<typename FloatType> static void juce::VST3BufferExchange< FloatType >::mapArrangementToBuses (int & channelIndexOffset, int index, Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, const AudioChannelSet & arrangement, AudioBuffer< FloatType > & source) static
Referenced by juce::VST3BufferExchange< float >::mapBufferToBuses().
template<typename FloatType> static void juce::VST3BufferExchange< FloatType >::mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, const Array< AudioChannelSet > & arrangements, AudioBuffer< FloatType > & source) static
template<typename FloatType> static void juce::VST3BufferExchange< FloatType >::mapBufferToBuses (Array< Steinberg::Vst::AudioBusBuffers > & result, Steinberg::Vst::IAudioProcessor & processor, BusMap & busMapToUse, bool isInput, int numBuses, AudioBuffer< FloatType > & source) static
The documentation for this struct was generated from the following file:
juce_VST3Common.h