JUCE: dsp::CmplxSIMDOps< Scalar > Struct Template Reference
dsp::CmplxSIMDOps< Scalar > Struct Template Reference
Public Types
typedef SIMDNativeOps< Scalar >
::vSIMDType vSIMDType
Static Public Member Functions
static vSIMDType
JUCE_VECTOR_CALLTYPE load (const Scalar *a) noexcept
static void JUCE_VECTOR_CALLTYPE store (vSIMDType value, Scalar *dest) noexcept
static vSIMDType
JUCE_VECTOR_CALLTYPE expand (Scalar s) noexcept
static Scalar JUCE_VECTOR_CALLTYPE sum (vSIMDType a) noexcept
static vSIMDType
JUCE_VECTOR_CALLTYPE mul (vSIMDType a, vSIMDType b) noexcept
static vSIMDType
JUCE_VECTOR_CALLTYPE muladd (vSIMDType a, vSIMDType b, vSIMDType c) noexcept
Member Typedef Documentation
template<typename Scalar > typedef SIMDNativeOps<Scalar>::vSIMDType dsp::CmplxSIMDOps< Scalar >::vSIMDType
Member Function Documentation
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE dsp::CmplxSIMDOps< Scalar >::load (const Scalar * a) static noexcept
Referenced by dsp::SIMDRegister< Type >::fromRawArray().
template<typename Scalar > static void JUCE_VECTOR_CALLTYPE dsp::CmplxSIMDOps< Scalar >::store (vSIMDType value, Scalar * dest) static noexcept
Referenced by dsp::SIMDRegister< Type >::copyToRawArray().
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE dsp::CmplxSIMDOps< Scalar >::expand (Scalar s) static noexcept
Referenced by dsp::SIMDRegister< Type >::expand(), dsp::SIMDRegister< Type >::operator*(), dsp::SIMDRegister< Type >::operator*=(), dsp::SIMDRegister< Type >::operator+(), dsp::SIMDRegister< Type >::operator+=(), dsp::SIMDRegister< Type >::operator-(), dsp::SIMDRegister< Type >::operator-=(), and dsp::SIMDRegister< Type >::operator=().
template<typename Scalar > static Scalar JUCE_VECTOR_CALLTYPE dsp::CmplxSIMDOps< Scalar >::sum (vSIMDType a) static noexcept
Referenced by dsp::SIMDRegister< Type >::sum().
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE dsp::CmplxSIMDOps< Scalar >::mul (vSIMDType a, vSIMDType b) static noexcept
Referenced by dsp::SIMDRegister< Type >::operator*(), and dsp::SIMDRegister< Type >::operator*=().
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE dsp::CmplxSIMDOps< Scalar >::muladd (vSIMDType a, vSIMDType b, vSIMDType c) static noexcept
Referenced by dsp::SIMDRegister< Type >::multiplyAdd().
The documentation for this struct was generated from the following file:
juce_SIMDRegister.h