JUCE: juce::BlocksProtocol::HostPacketDecoder< Handler > Struct Template Reference
juce::BlocksProtocol::HostPacketDecoder< Handler > Struct Template Reference
Parses data packets from a BLOCKS device, and translates them into callbacks on a handler object.
Static Public Member Functions
static void processNextPacket (Handler &handler, TopologyIndex deviceIndex, const void *data, int size)
static bool processNextMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp)
static bool handleTopology (Handler &handler, Packed7BitArrayReader &reader, bool newTopology)
static bool handleTopologyEnd (Handler &handler, Packed7BitArrayReader &reader)
static void handleTopologyDevice (Handler &handler, Packed7BitArrayReader &reader)
static void handleTopologyConnection (Handler &handler, Packed7BitArrayReader &reader)
static bool handleVersion (Handler &handler, Packed7BitArrayReader &reader)
static bool handleName (Handler &handler, Packed7BitArrayReader &reader)
static bool handleTouch (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd)
static bool handleTouchWithVelocity (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd)
static void handleTouch (Handler &handler, TopologyIndex deviceIndex, uint32 timestamp, TouchIndex touchIndex, TouchPosition position, TouchVelocity velocity, bool isStart, bool isEnd)
static bool handleButtonDownOrUp (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isDown)
static bool handleCustomMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp)
static bool handlePacketACK (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
static bool handleFirmwareUpdateACK (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
static bool handleConfigMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
static bool handleLogMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
Detailed Description
template<typename Handler>
struct juce::BlocksProtocol::HostPacketDecoder< Handler >
Parses data packets from a BLOCKS device, and translates them into callbacks on a handler object.
Member Function Documentation
template<typename Handler > static void juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextPacket (Handler & handler, TopologyIndex deviceIndex, const void * data, int size) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::Packed7BitArrayReader::checksumIsOK(), juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), jassertfalse, juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage(), and juce::BlocksProtocol::Packed7BitArrayReader::read().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::configMessage, juce::BlocksProtocol::controlButtonDown, juce::BlocksProtocol::controlButtonUp, juce::BlocksProtocol::deviceNameList, juce::BlocksProtocol::deviceTopology, juce::BlocksProtocol::deviceTopologyEnd, juce::BlocksProtocol::deviceTopologyExtend, juce::BlocksProtocol::deviceVersionList, juce::BlocksProtocol::firmwareUpdateACK, juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleConfigMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleLogMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleName(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handlePacketACK(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopology(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyEnd(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleVersion(), jassertfalse, juce::BlocksProtocol::logMessage, juce::BlocksProtocol::packetACK, juce::BlocksProtocol::programEventMessage, juce::BlocksProtocol::Packed7BitArrayReader::read(), juce::BlocksProtocol::touchEnd, juce::BlocksProtocol::touchEndWithVelocity, juce::BlocksProtocol::touchMove, juce::BlocksProtocol::touchMoveWithVelocity, juce::BlocksProtocol::touchStart, and juce::BlocksProtocol::touchStartWithVelocity.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextPacket().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopology (Handler & handler, Packed7BitArrayReader & reader, bool newTopology) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< 8 >::bits, juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyConnection(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyDevice(), jassertfalse, juce::BlocksProtocol::Packed7BitArrayReader::read(), juce::BlocksProtocol::topologyConnectionInfo, and juce::BlocksProtocol::topologyDeviceInfo.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyEnd (Handler & handler, Packed7BitArrayReader & reader) static
References jassertfalse, and juce::BlocksProtocol::Packed7BitArrayReader::read().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static void juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyDevice (Handler & handler, Packed7BitArrayReader & reader) static
References juce::BlocksProtocol::DeviceStatus::batteryCharging, juce::BlocksProtocol::DeviceStatus::batteryLevel, juce::BlocksProtocol::DeviceStatus::index, juce::BlocksProtocol::Packed7BitArrayReader::read(), juce::BlocksProtocol::Packed7BitArrayReader::readBits(), juce::BlocksProtocol::BlockSerialNumber::serial, and juce::BlocksProtocol::DeviceStatus::serialNumber.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopology().
template<typename Handler > static void juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyConnection (Handler & handler, Packed7BitArrayReader & reader) static
References juce::BlocksProtocol::DeviceConnection::device1, juce::BlocksProtocol::DeviceConnection::device2, juce::BlocksProtocol::DeviceConnection::port1, juce::BlocksProtocol::DeviceConnection::port2, juce::BlocksProtocol::Packed7BitArrayReader::read(), and juce::BlocksProtocol::Packed7BitArrayReader::readBits().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopology().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleVersion (Handler & handler, Packed7BitArrayReader & reader) static
References juce::BlocksProtocol::DeviceVersion::index, juce::BlocksProtocol::VersionNumber::length, juce::BlocksProtocol::Packed7BitArrayReader::readBits(), juce::BlocksProtocol::VersionNumber::version, and juce::BlocksProtocol::DeviceVersion::version.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleName (Handler & handler, Packed7BitArrayReader & reader) static
References juce::BlocksProtocol::DeviceName::index, juce::BlocksProtocol::BlockName::length, juce::BlocksProtocol::BlockName::name, juce::BlocksProtocol::DeviceName::name, and juce::BlocksProtocol::Packed7BitArrayReader::readBits().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< numBits >::get(), juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), jassertfalse, juce::BlocksProtocol::Packed7BitArrayReader::read(), and juce::BlocksProtocol::touchMessage.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity(), and juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< numBits >::get(), juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), jassertfalse, juce::BlocksProtocol::Packed7BitArrayReader::read(), and juce::BlocksProtocol::touchMessageWithVelocity.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static void juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch (Handler & handler, TopologyIndex deviceIndex, uint32 timestamp, TouchIndex touchIndex, TouchPosition position, TouchVelocity velocity, bool isStart, bool isEnd) static
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isDown) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::controlButtonMessage, juce::BlocksProtocol::IntegerWithBitSize< numBits >::get(), juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), jassertfalse, and juce::BlocksProtocol::Packed7BitArrayReader::read().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< numBits >::get(), juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), jassertfalse, juce::BlocksProtocol::programEventMessage, and juce::BlocksProtocol::Packed7BitArrayReader::read().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handlePacketACK (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), jassertfalse, juce::BlocksProtocol::packetACK, and juce::BlocksProtocol::Packed7BitArrayReader::read().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleFirmwareUpdateACK (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), jassertfalse, and juce::BlocksProtocol::Packed7BitArrayReader::read().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleConfigMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References juce::BlocksProtocol::factorySyncEnd, juce::BlocksProtocol::IntegerWithBitSize< numBits >::get(), max(), min(), juce::BlocksProtocol::Packed7BitArrayReader::read(), juce::BlocksProtocol::setConfig, and juce::BlocksProtocol::updateConfig.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool juce::BlocksProtocol::HostPacketDecoder< Handler >::handleLogMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits(), and juce::BlocksProtocol::Packed7BitArrayReader::read().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage().
The documentation for this struct was generated from the following file:
juce_HostPacketDecoder.h