JUCE: juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes > Struct Template Reference
juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes > Struct Template Reference
Helper class for constructing a packet for sending to a BLOCKS device.
Public Member Functions
HostPacketBuilder () noexcept
HostPacketBuilder (const HostPacketBuilder &)=delete
HostPacketBuilder (HostPacketBuilder &&)=default
const void * getData () const noexcept
int size () const noexcept
void writePacketSysexHeaderBytes (TopologyIndex deviceIndex) noexcept
void writePacketSysexFooter () noexcept
bool deviceControlMessage (DeviceCommand command) noexcept
bool beginDataChanges (PacketIndex packetIndex) noexcept
bool endDataChanges (bool isLastChange) noexcept
bool skipBytes (int numToSkip) noexcept
bool setMultipleBytes (const uint8 *values, int num) noexcept
bool setMultipleBytes (uint8 value, uint8 lastValue, int num) noexcept
bool addProgramEventMessage (const int32 *messageData)
bool addFirmwareUpdatePacket (const uint8 *packetData, uint8 size)
bool addConfigSetMessage (int32 item, int32 value)
bool addRequestMessage (int32 item)
bool addRequestFactorySyncMessage ()
bool addRequestUserSyncMessage ()
bool addFactoryReset ()
bool addBlockReset ()
bool addSetBlockName (const juce::String &name)
Detailed Description
template<int maxPacketBytes>
struct juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >
Helper class for constructing a packet for sending to a BLOCKS device.
Constructor & Destructor Documentation
template<int maxPacketBytes> juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::HostPacketBuilder () noexcept
template<int maxPacketBytes> juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::HostPacketBuilder (const HostPacketBuilder< maxPacketBytes > &) delete
template<int maxPacketBytes> juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::HostPacketBuilder (HostPacketBuilder< maxPacketBytes > &&) default
Member Function Documentation
template<int maxPacketBytes> const void* juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::getData () const noexcept
References juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::getData().
Referenced by juce::BlockConfigManager::requestBlockConfig(), juce::BlockConfigManager::requestFactoryConfigSync(), juce::BlockConfigManager::requestUserConfigSync(), and juce::BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> int juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size () const noexcept
References juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::size().
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket(), juce::BlockConfigManager::requestBlockConfig(), juce::BlockConfigManager::requestFactoryConfigSync(), juce::BlockConfigManager::requestUserConfigSync(), and juce::BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> void juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes (TopologyIndex deviceIndex) noexcept
References jassert, and juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::writeHeaderSysexBytes().
Referenced by juce::BlockConfigManager::requestBlockConfig(), juce::BlockConfigManager::requestFactoryConfigSync(), juce::BlockConfigManager::requestUserConfigSync(), and juce::BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> void juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter () noexcept
References juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::writePacketSysexFooter().
Referenced by juce::BlockConfigManager::requestBlockConfig(), juce::BlockConfigManager::requestFactoryConfigSync(), juce::BlockConfigManager::requestUserConfigSync(), and juce::BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::deviceControlMessage (DeviceCommand command) noexcept
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::deviceCommandMessage, and juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::beginDataChanges (PacketIndex packetIndex) noexcept
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::sharedDataChange.
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::endDataChanges (bool isLastChange) noexcept
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::endOfChanges, juce::BlocksProtocol::endOfPacket, and juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::skipBytes (int numToSkip) noexcept
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< 8 >::bits, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::getState(), juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), juce::BlocksProtocol::IntegerWithBitSize< numBits >::maxValue, juce::BlocksProtocol::IntegerWithBitSize< 8 >::maxValue, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::restore(), juce::BlocksProtocol::skipBytesFew, and juce::BlocksProtocol::skipBytesMany.
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes (const uint8 * values, int num) noexcept
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< 8 >::bits, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::setSequenceOfBytes.
Referenced by juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes (uint8 value, uint8 lastValue, int num) noexcept
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::IntegerWithBitSize< 8 >::bits, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::getState(), juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), juce::BlocksProtocol::IntegerWithBitSize< numBits >::maxValue, juce::BlocksProtocol::IntegerWithBitSize< 8 >::maxValue, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::restore(), juce::BlocksProtocol::setFewBytesWithLastValue, juce::BlocksProtocol::setFewBytesWithValue, juce::BlocksProtocol::setManyBytesWithValue, and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::setMultipleBytes().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addProgramEventMessage (const int32 * messageData)
References juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::programEventMessage.
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket (const uint8 * packetData, uint8 size)
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::firmwareUpdatePacket, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addConfigSetMessage (int32 item, int32 value)
References juce::BlocksProtocol::configMessage, juce::BlocksProtocol::configSetMessage, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::setConfig.
Referenced by juce::BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestMessage (int32 item)
References juce::BlocksProtocol::configMessage, juce::BlocksProtocol::configSetMessage, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::requestConfig.
Referenced by juce::BlockConfigManager::requestBlockConfig().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage ()
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::configMessage, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::requestFactorySync.
Referenced by juce::BlockConfigManager::requestFactoryConfigSync().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage ()
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::configMessage, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and juce::BlocksProtocol::requestUserSync.
Referenced by juce::BlockConfigManager::requestUserConfigSync().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addFactoryReset ()
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::factoryReset, and juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addBlockReset ()
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::blockReset, and juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addSetBlockName (const juce::String & name)
References juce::BlocksProtocol::IntegerWithBitSize< numBits >::bits, juce::BlocksProtocol::Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), juce::String::length(), juce::BlocksProtocol::setName, and juce::String::toRawUTF8().
The documentation for this struct was generated from the following file:
juce_HostPacketBuilder.h