JUCE: juce::CppTokeniserFunctions Struct Reference
juce::CppTokeniserFunctions Struct Reference
code_editor
Class containing some basic functions for simple tokenising of C++ code.
Classes
struct StringIterator
A class that can be passed to the CppTokeniserFunctions functions in order to parse a String.
Static Public Member Functions
static bool isIdentifierStart (const juce_wchar c) noexcept
static bool isIdentifierBody (const juce_wchar c) noexcept
static bool isReservedKeyword (String::CharPointerType token, const int tokenLength) noexcept
template<typename Iterator >
static int parseIdentifier (Iterator &source) noexcept
template<typename Iterator >
static bool skipNumberSuffix (Iterator &source)
static bool isHexDigit (const juce_wchar c) noexcept
template<typename Iterator >
static bool parseHexLiteral (Iterator &source) noexcept
static bool isOctalDigit (const juce_wchar c) noexcept
template<typename Iterator >
static bool parseOctalLiteral (Iterator &source) noexcept
static bool isDecimalDigit (const juce_wchar c) noexcept
template<typename Iterator >
static bool parseDecimalLiteral (Iterator &source) noexcept
template<typename Iterator >
static bool parseFloatLiteral (Iterator &source) noexcept
template<typename Iterator >
static int parseNumber (Iterator &source)
template<typename Iterator >
static void skipQuotedString (Iterator &source) noexcept
template<typename Iterator >
static void skipComment (Iterator &source) noexcept
template<typename Iterator >
static void skipPreprocessorLine (Iterator &source) noexcept
template<typename Iterator >
static void skipIfNextCharMatches (Iterator &source, const juce_wchar c) noexcept
template<typename Iterator >
static void skipIfNextCharMatches (Iterator &source, const juce_wchar c1, const juce_wchar c2) noexcept
template<typename Iterator >
static int readNextToken (Iterator &source)
static void writeEscapeChars (OutputStream &out, const char *utf8, const int numBytesToRead, const int maxCharsOnLine, const bool breakAtNewLines, const bool replaceSingleQuotes, const bool allowStringBreaks)
Takes a UTF8 string and writes it to a stream using standard C++ escape sequences for any non-ascii bytes.
static String addEscapeChars (const String &s)
Takes a string and returns a version of it where standard C++ escape sequences have been used to replace any non-ascii bytes.
Detailed Description
Class containing some basic functions for simple tokenising of C++ code.
Member Function Documentation
static bool juce::CppTokeniserFunctions::isIdentifierStart (const juce_wchar c) static noexcept
References juce::CharacterFunctions::isLetter().
Referenced by readNextToken().
static bool juce::CppTokeniserFunctions::isIdentifierBody (const juce_wchar c) static noexcept
References juce::CharacterFunctions::isLetterOrDigit().
Referenced by parseIdentifier().
static bool juce::CppTokeniserFunctions::isReservedKeyword (String::CharPointerType token, const int tokenLength) static noexcept
Referenced by parseIdentifier().
template<typename Iterator > static int juce::CppTokeniserFunctions::parseIdentifier (Iterator & source) static noexcept
References isIdentifierBody(), isReservedKeyword(), juce::CPlusPlusCodeTokeniser::tokenType_identifier, juce::CPlusPlusCodeTokeniser::tokenType_keyword, juce::CharPointer_UTF8::write(), and juce::CharPointer_UTF8::writeNull().
Referenced by readNextToken().
template<typename Iterator > static bool juce::CppTokeniserFunctions::skipNumberSuffix (Iterator & source) static
References juce::CharacterFunctions::isLetterOrDigit().
Referenced by parseDecimalLiteral(), parseHexLiteral(), and parseOctalLiteral().
static bool juce::CppTokeniserFunctions::isHexDigit (const juce_wchar c) static noexcept
Referenced by parseHexLiteral().
template<typename Iterator > static bool juce::CppTokeniserFunctions::parseHexLiteral (Iterator & source) static noexcept
References isHexDigit(), and skipNumberSuffix().
Referenced by parseNumber().
static bool juce::CppTokeniserFunctions::isOctalDigit (const juce_wchar c) static noexcept
Referenced by parseOctalLiteral().
template<typename Iterator > static bool juce::CppTokeniserFunctions::parseOctalLiteral (Iterator & source) static noexcept
References isOctalDigit(), and skipNumberSuffix().
Referenced by parseNumber().
static bool juce::CppTokeniserFunctions::isDecimalDigit (const juce_wchar c) static noexcept
Referenced by parseDecimalLiteral(), and parseFloatLiteral().
template<typename Iterator > static bool juce::CppTokeniserFunctions::parseDecimalLiteral (Iterator & source) static noexcept
References isDecimalDigit(), and skipNumberSuffix().
Referenced by parseNumber().
template<typename Iterator > static bool juce::CppTokeniserFunctions::parseFloatLiteral (Iterator & source) static noexcept
References isDecimalDigit().
Referenced by parseNumber().
template<typename Iterator > static int juce::CppTokeniserFunctions::parseNumber (Iterator & source) static
References parseDecimalLiteral(), parseFloatLiteral(), parseHexLiteral(), parseOctalLiteral(), juce::CPlusPlusCodeTokeniser::tokenType_error, juce::CPlusPlusCodeTokeniser::tokenType_float, and juce::CPlusPlusCodeTokeniser::tokenType_integer.
Referenced by readNextToken().
template<typename Iterator > static void juce::CppTokeniserFunctions::skipQuotedString (Iterator & source) static noexcept
Referenced by readNextToken(), and skipPreprocessorLine().
template<typename Iterator > static void juce::CppTokeniserFunctions::skipComment (Iterator & source) static noexcept
Referenced by readNextToken().
template<typename Iterator > static void juce::CppTokeniserFunctions::skipPreprocessorLine (Iterator & source) static noexcept
References skipQuotedString().
Referenced by readNextToken().
template<typename Iterator > static void juce::CppTokeniserFunctions::skipIfNextCharMatches (Iterator & source, const juce_wchar c) static noexcept
Referenced by readNextToken().
template<typename Iterator > static void juce::CppTokeniserFunctions::skipIfNextCharMatches (Iterator & source, const juce_wchar c1, const juce_wchar c2) static noexcept
template<typename Iterator > static int juce::CppTokeniserFunctions::readNextToken (Iterator & source) static
References isIdentifierStart(), parseIdentifier(), parseNumber(), skipComment(), skipIfNextCharMatches(), skipPreprocessorLine(), skipQuotedString(), juce::CPlusPlusCodeTokeniser::tokenType_bracket, juce::CPlusPlusCodeTokeniser::tokenType_comment, juce::CPlusPlusCodeTokeniser::tokenType_error, juce::CPlusPlusCodeTokeniser::tokenType_operator, juce::CPlusPlusCodeTokeniser::tokenType_preprocessor, juce::CPlusPlusCodeTokeniser::tokenType_punctuation, and juce::CPlusPlusCodeTokeniser::tokenType_string.
static void juce::CppTokeniserFunctions::writeEscapeChars (OutputStream & out, const char * utf8, const int numBytesToRead, const int maxCharsOnLine, const bool breakAtNewLines, const bool replaceSingleQuotes, const bool allowStringBreaks) static
Takes a UTF8 string and writes it to a stream using standard C++ escape sequences for any non-ascii bytes.
Although not strictly a tokenising function, this is still a function that often comes in handy when working with C++ code!
Note that addEscapeChars() is easier to use than this function if you're working with Strings.
See Also
addEscapeChars
References juce::CharacterFunctions::getHexDigitValue(), juce::newLine, and juce::String::toHexString().
Referenced by addEscapeChars().
static String juce::CppTokeniserFunctions::addEscapeChars (const String & s) static
Takes a string and returns a version of it where standard C++ escape sequences have been used to replace any non-ascii bytes.
Although not strictly a tokenising function, this is still a function that often comes in handy when working with C++ code!
See Also
writeEscapeChars
References juce::String::toRawUTF8(), juce::MemoryOutputStream::toString(), and writeEscapeChars().
The documentation for this struct was generated from the following file:
juce_CPlusPlusCodeTokeniserFunctions.h