JUCE: BlocksProtocol::BlockDataSheet Struct Reference
BlocksProtocol::BlockDataSheet Struct Reference
Classes
struct ButtonInfo
struct StatusLEDInfo
Public Member Functions
BlockDataSheet (const BlocksProtocol::BlockSerialNumber &serial)
Block::ConnectionPort convertPortIndexToConnectorPort (BlocksProtocol::ConnectorPort port) const noexcept
Public Attributes
const
BlocksProtocol::BlockSerialNumber serialNumber
Block::Type apiType = Block::Type::unknown
const char * description = nullptr
int widthUnits = 0
int heightUnits = 0
int lightGridWidth = 0
int lightGridHeight = 0
int lightGridStartIndex = 0
bool hasTouchSurface = false
int numKeywaves = 0
int numLEDRowLEDs = 0
uint32 programAndHeapSize = 0
juce::Array< ButtonInfo > buttons
juce::Array< StatusLEDInfo > statusLEDs
juce::Array
< Block::ConnectionPort > ports
juce::Array< const char * > dials
Constructor & Destructor Documentation
BlocksProtocol::BlockDataSheet::BlockDataSheet (const BlocksProtocol::BlockSerialNumber & serial)
References BlocksProtocol::BlockSerialNumber::isDevCtrlBlock(), BlocksProtocol::BlockSerialNumber::isLiveBlock(), BlocksProtocol::BlockSerialNumber::isLoopBlock(), BlocksProtocol::BlockSerialNumber::isPadBlock(), BlocksProtocol::BlockSerialNumber::isSeaboardBlock(), BlocksProtocol::BlockSerialNumber::isTouchBlock(), and serialNumber.
Member Function Documentation
Block::ConnectionPort BlocksProtocol::BlockDataSheet::convertPortIndexToConnectorPort (BlocksProtocol::ConnectorPort port) const noexcept
References ports.
Member Data Documentation
const BlocksProtocol::BlockSerialNumber BlocksProtocol::BlockDataSheet::serialNumber
Referenced by BlockDataSheet().
Block::Type BlocksProtocol::BlockDataSheet::apiType = Block::Type::unknown
const char* BlocksProtocol::BlockDataSheet::description = nullptr
int BlocksProtocol::BlockDataSheet::widthUnits = 0
int BlocksProtocol::BlockDataSheet::heightUnits = 0
int BlocksProtocol::BlockDataSheet::lightGridWidth = 0
int BlocksProtocol::BlockDataSheet::lightGridHeight = 0
int BlocksProtocol::BlockDataSheet::lightGridStartIndex = 0
bool BlocksProtocol::BlockDataSheet::hasTouchSurface = false
int BlocksProtocol::BlockDataSheet::numKeywaves = 0
int BlocksProtocol::BlockDataSheet::numLEDRowLEDs = 0
uint32 BlocksProtocol::BlockDataSheet::programAndHeapSize = 0
juce::Array<ButtonInfo> BlocksProtocol::BlockDataSheet::buttons
juce::Array<StatusLEDInfo> BlocksProtocol::BlockDataSheet::statusLEDs
juce::Array<Block::ConnectionPort> BlocksProtocol::BlockDataSheet::ports
Referenced by convertPortIndexToConnectorPort().
juce::Array<const char*> BlocksProtocol::BlockDataSheet::dials
The documentation for this struct was generated from the following file:
juce_BlockModels.h