JUCE: juce::BlockConfigManager Struct Reference
juce::BlockConfigManager Struct Reference
blocks
Classes
struct ConfigDescription
Public Types
enum ConfigType {
integer, floating, boolean, colour,
options
}
Public Member Functions
void setDeviceIndex (TopologyIndex newDeviceIndex)
void setDeviceComms (PhysicalTopologySource::DeviceConnection *newConn)
int32 getItemValue (ConfigItemId item)
void setItemValue (ConfigItemId item, int32 value)
int32 getItemMin (ConfigItemId item)
void setItemMin (ConfigItemId item, int32 min)
int32 getItemMax (ConfigItemId item)
void setItemMax (ConfigItemId item, int32 max)
bool getItemActive (ConfigItemId item)
void setItemActive (ConfigItemId item, bool isActive)
juce::String getOptionName (ConfigItemId item, uint8 optionIndex)
Block::ConfigMetaData getMetaData (ConfigItemId item)
void resetConfigListActiveStatus ()
void setBlockConfig (ConfigItemId item, int32 value)
void requestBlockConfig (ConfigItemId item)
void requestFactoryConfigSync ()
void requestUserConfigSync ()
void handleConfigUpdateMessage (int32 item, int32 value, int32 min, int32 max)
void handleConfigSetMessage (int32 item, int32 value)
Public Attributes
ConfigDescription configList [numConfigItems]
Static Public Attributes
static constexpr uint32 numConfigItems = 61
Member Enumeration Documentation
enum juce::BlockConfigManager::ConfigType
Enumerator
integer
floating
boolean
colour
options
Member Function Documentation
void juce::BlockConfigManager::setDeviceIndex (TopologyIndex newDeviceIndex)
void juce::BlockConfigManager::setDeviceComms (PhysicalTopologySource::DeviceConnection * newConn)
int32 juce::BlockConfigManager::getItemValue (ConfigItemId item)
void juce::BlockConfigManager::setItemValue (ConfigItemId item, int32 value)
int32 juce::BlockConfigManager::getItemMin (ConfigItemId item)
void juce::BlockConfigManager::setItemMin (ConfigItemId item, int32 min)
References min().
int32 juce::BlockConfigManager::getItemMax (ConfigItemId item)
void juce::BlockConfigManager::setItemMax (ConfigItemId item, int32 max)
References max().
bool juce::BlockConfigManager::getItemActive (ConfigItemId item)
void juce::BlockConfigManager::setItemActive (ConfigItemId item, bool isActive)
juce::String juce::BlockConfigManager::getOptionName (ConfigItemId item, uint8 optionIndex)
Block::ConfigMetaData juce::BlockConfigManager::getMetaData (ConfigItemId item)
void juce::BlockConfigManager::resetConfigListActiveStatus ()
void juce::BlockConfigManager::setBlockConfig (ConfigItemId item, int32 value)
References juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addConfigSetMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::getData(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void juce::BlockConfigManager::requestBlockConfig (ConfigItemId item)
References juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::getData(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void juce::BlockConfigManager::requestFactoryConfigSync ()
References juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::getData(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void juce::BlockConfigManager::requestUserConfigSync ()
References juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::getData(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::size(), juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter(), and juce::BlocksProtocol::HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
void juce::BlockConfigManager::handleConfigUpdateMessage (int32 item, int32 value, int32 min, int32 max)
References max(), and min().
void juce::BlockConfigManager::handleConfigSetMessage (int32 item, int32 value)
Member Data Documentation
constexpr uint32 juce::BlockConfigManager::numConfigItems = 61 static
ConfigDescription juce::BlockConfigManager::configList[numConfigItems]
The documentation for this struct was generated from the following file:
juce_BlockConfigManager.h