JUCE: juce::BlocksProtocol::Packed7BitArrayReader Struct Reference
juce::BlocksProtocol::Packed7BitArrayReader Struct Reference
This helper class reads from a block of 7-bit bytes as sequences of bits.
Public Member Functions
Packed7BitArrayReader (const void *sourceData, int numBytes) noexcept
int getRemainingBits () const noexcept
template<typename Target >
Target read () noexcept
uint32 readBits (int numBits) noexcept
Static Public Member Functions
static bool checksumIsOK (const uint8 *data, uint32 size) noexcept
Detailed Description
This helper class reads from a block of 7-bit bytes as sequences of bits.
See Also
Packed7BitArrayBuilder
Constructor & Destructor Documentation
juce::BlocksProtocol::Packed7BitArrayReader::Packed7BitArrayReader (const void * sourceData, int numBytes) noexcept
Member Function Documentation
int juce::BlocksProtocol::Packed7BitArrayReader::getRemainingBits () const noexcept
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleLogMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handlePacketACK(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopology(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity(), juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextPacket(), and readBits().
template<typename Target > Target juce::BlocksProtocol::Packed7BitArrayReader::read () noexcept
References readBits().
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleConfigMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleLogMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handlePacketACK(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopology(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyConnection(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyDevice(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyEnd(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity(), juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextMessage(), and juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextPacket().
uint32 juce::BlocksProtocol::Packed7BitArrayReader::readBits (int numBits) noexcept
References getRemainingBits(), and jassert.
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleName(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyConnection(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyDevice(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleVersion(), and read().
static bool juce::BlocksProtocol::Packed7BitArrayReader::checksumIsOK (const uint8 * data, uint32 size) static noexcept
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::processNextPacket().
The documentation for this struct was generated from the following file:
juce_BitPackingUtilities.h