JUCE: juce::AudioUnitHelpers Struct Reference
juce::AudioUnitHelpers Struct Reference
format_types
Classes
class ChannelRemapper
class CoreAudioBufferList
Static Public Member Functions
static bool isAudioBufferInterleaved (const AudioBufferList &audioBuffer) noexcept
static void clearAudioBuffer (const AudioBufferList &audioBuffer) noexcept
static void copyAudioBuffer (const AudioBufferList &audioBuffer, const int channel, const UInt32 size, float *dst) noexcept
static void copyAudioBuffer (const float *src, const int channel, const UInt32 size, AudioBufferList &audioBuffer) noexcept
template<int numLayouts>
static bool isLayoutSupported (const AudioProcessor &processor, bool isInput, int busIdx, int numChannels, const short(&channelLayoutList)[numLayouts][2], bool hasLayoutMap=true)
static Array< AUChannelInfo > getAUChannelInfo (const AudioProcessor &processor)
static bool isNumberOfChannelsSupported (const AudioProcessor::Bus *b, int numChannels, AudioProcessor::BusesLayout &inOutCurrentLayout)
static int getBusCount (const AudioProcessor *juceFilter, bool isInput)
static bool setBusesLayout (AudioProcessor *juceFilter, const AudioProcessor::BusesLayout &requestedLayouts)
static AudioProcessor::BusesLayout getBusesLayout (const AudioProcessor *juceFilter)
Member Function Documentation
static bool juce::AudioUnitHelpers::isAudioBufferInterleaved (const AudioBufferList & audioBuffer) static noexcept
Referenced by copyAudioBuffer(), juce::AudioUnitHelpers::CoreAudioBufferList::pop(), and juce::AudioUnitHelpers::CoreAudioBufferList::push().
static void juce::AudioUnitHelpers::clearAudioBuffer (const AudioBufferList & audioBuffer) static noexcept
References juce::zeromem().
static void juce::AudioUnitHelpers::copyAudioBuffer (const AudioBufferList & audioBuffer, const int channel, const UInt32 size, float * dst) static noexcept
References isAudioBufferInterleaved(), and jassert.
Referenced by juce::AudioUnitHelpers::CoreAudioBufferList::pop(), and juce::AudioUnitHelpers::CoreAudioBufferList::push().
static void juce::AudioUnitHelpers::copyAudioBuffer (const float * src, const int channel, const UInt32 size, AudioBufferList & audioBuffer) static noexcept
References isAudioBufferInterleaved(), and jassert.
template<int numLayouts> static bool juce::AudioUnitHelpers::isLayoutSupported (const AudioProcessor & processor, bool isInput, int busIdx, int numChannels, const short(&) channelLayoutList[numLayouts][2], bool hasLayoutMap = true) static
References juce::AudioProcessor::getBus().
static Array<AUChannelInfo> juce::AudioUnitHelpers::getAUChannelInfo (const AudioProcessor & processor) static
References juce::SortedSet< ElementType, TypeOfCriticalSectionToUse >::add(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), juce::AudioProcessor::getBus(), getBusCount(), juce::AudioProcessor::getBusesLayout(), juce::AudioProcessor::getChannelCountOfBus(), juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isNumberOfChannelsSupported(), and juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
static bool juce::AudioUnitHelpers::isNumberOfChannelsSupported (const AudioProcessor::Bus * b, int numChannels, AudioProcessor::BusesLayout & inOutCurrentLayout) static
References juce::AudioChannelSet::channelSetsWithNumberOfChannels(), juce::StandardApplicationCommandIDs::copy, and juce::AudioProcessor::Bus::isLayoutSupported().
Referenced by getAUChannelInfo().
static int juce::AudioUnitHelpers::getBusCount (const AudioProcessor * juceFilter, bool isInput) static
References juce::AudioProcessor::getBusCount(), and juce::jmin().
Referenced by juce::AudioUnitHelpers::ChannelRemapper::alloc(), getAUChannelInfo(), getBusesLayout(), and setBusesLayout().
static bool juce::AudioUnitHelpers::setBusesLayout (AudioProcessor * juceFilter, const AudioProcessor::BusesLayout & requestedLayouts) static
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), juce::StandardApplicationCommandIDs::copy, juce::AudioChannelSet::disabled(), getBusCount(), juce::AudioProcessor::getBusCount(), juce::AudioProcessor::BusesLayout::inputBuses, juce::AudioProcessor::BusesLayout::outputBuses, and juce::AudioProcessor::setBusesLayout().
static AudioProcessor::BusesLayout juce::AudioUnitHelpers::getBusesLayout (const AudioProcessor * juceFilter) static
References getBusCount(), juce::AudioProcessor::getBusCount(), juce::AudioProcessor::getBusesLayout(), juce::AudioProcessor::BusesLayout::inputBuses, and juce::AudioProcessor::BusesLayout::outputBuses.
The documentation for this struct was generated from the following file:
juce_AU_Shared.h