JUCE: juce::dsp::CmplxSIMDOps< Scalar > Struct Template Reference
juce::dsp::CmplxSIMDOps< Scalar > Struct Template Reference
Public Types
typedef SIMDNativeOps< Scalar >
::vSIMDType vSIMDType
Static Public Member Functions
static vSIMDType
JUCE_VECTOR_CALLTYPE expand (Scalar s) noexcept
static Scalar JUCE_VECTOR_CALLTYPE sum (vSIMDType a) noexcept
static vSIMDType
JUCE_VECTOR_CALLTYPE mul (vSIMDType a, vSIMDType b) noexcept
static vSIMDType
JUCE_VECTOR_CALLTYPE muladd (vSIMDType a, vSIMDType b, vSIMDType c) noexcept
Member Typedef Documentation
template<typename Scalar > typedef SIMDNativeOps<Scalar>::vSIMDType juce::dsp::CmplxSIMDOps< Scalar >::vSIMDType
Member Function Documentation
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE juce::dsp::CmplxSIMDOps< Scalar >::expand (Scalar s) static noexcept
Referenced by juce::dsp::SIMDRegister< Type >::expand(), juce::dsp::SIMDRegister< Type >::operator*(), juce::dsp::SIMDRegister< Type >::operator*=(), juce::dsp::SIMDRegister< Type >::operator+(), juce::dsp::SIMDRegister< Type >::operator+=(), juce::dsp::SIMDRegister< Type >::operator-(), juce::dsp::SIMDRegister< Type >::operator-=(), and juce::dsp::SIMDRegister< Type >::operator=().
template<typename Scalar > static Scalar JUCE_VECTOR_CALLTYPE juce::dsp::CmplxSIMDOps< Scalar >::sum (vSIMDType a) static noexcept
Referenced by juce::dsp::SIMDRegister< Type >::sum().
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE juce::dsp::CmplxSIMDOps< Scalar >::mul (vSIMDType a, vSIMDType b) static noexcept
Referenced by juce::dsp::SIMDRegister< Type >::operator*(), and juce::dsp::SIMDRegister< Type >::operator*=().
template<typename Scalar > static vSIMDType JUCE_VECTOR_CALLTYPE juce::dsp::CmplxSIMDOps< Scalar >::muladd (vSIMDType a, vSIMDType b, vSIMDType c) static noexcept
Referenced by juce::dsp::SIMDRegister< Type >::multiplyAdd().
The documentation for this struct was generated from the following file:
juce_SIMDRegister.h