JUCE: dsp::FIR::Coefficients< NumericType > Struct Template Reference
dsp::FIR::Coefficients< NumericType > Struct Template Reference
A set of coefficients for use in an FIRFilter object.
Public Types
using Ptr = ReferenceCountedObjectPtr< Coefficients >
The Coefficients structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Public Types inherited from dsp::ProcessorState
using Ptr = ReferenceCountedObjectPtr< ProcessorState >
The ProcessorState structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Public Member Functions
Coefficients ()
Creates a null set of coefficients (which will produce silence).
Coefficients (Coefficients &&)=default
Coefficients & operator= (const Coefficients &)=default
Coefficients & operator= (Coefficients &&)=default
size_t getFilterOrder () const noexcept
Returns the filter order associated with the coefficients.
double getMagnitudeForFrequency (double frequency, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency and sample rate.
void getMagnitudeForFrequencyArray (double *frequencies, double *magnitudes, size_t numSamples, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency array and sample rate.
double getPhaseForFrequency (double frequency, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency and sample rate.
void getPhaseForFrequencyArray (double *frequencies, double *phases, size_t numSamples, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency array and sample rate.
NumericType * getRawCoefficients () noexcept
Returns a raw data pointer to the coefficients.
const NumericType * getRawCoefficients () const noexcept
Returns a raw data pointer to the coefficients.
void normalise () noexcept
Scales the values of the FIR filter with the sum of the squared coefficients.
Public Member Functions inherited from ReferenceCountedObject
void incReferenceCount () noexcept
Increments the object's reference count.
void decReferenceCount () noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Public Attributes
Array< NumericType > coefficients
The raw coefficients.
Additional Inherited Members
Protected Member Functions inherited from ReferenceCountedObject
ReferenceCountedObject ()
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
template<typename NumericType>
struct dsp::FIR::Coefficients< NumericType >
A set of coefficients for use in an FIRFilter object.
See Also
FIRFilter
Member Typedef Documentation
template<typename NumericType> using dsp::FIR::Coefficients< NumericType >::Ptr = ReferenceCountedObjectPtr<Coefficients>
The Coefficients structure is ref-counted, so this is a handy type that can be used as a pointer to one.
Constructor & Destructor Documentation
template<typename NumericType> dsp::FIR::Coefficients< NumericType >::Coefficients ()
Creates a null set of coefficients (which will produce silence).
template<typename NumericType> dsp::FIR::Coefficients< NumericType >::Coefficients (Coefficients< NumericType > &&) default
Member Function Documentation
template<typename NumericType> Coefficients& dsp::FIR::Coefficients< NumericType >::operator= (const Coefficients< NumericType > &) default
template<typename NumericType> Coefficients& dsp::FIR::Coefficients< NumericType >::operator= (Coefficients< NumericType > &&) default
template<typename NumericType> size_t dsp::FIR::Coefficients< NumericType >::getFilterOrder () const noexcept
Returns the filter order associated with the coefficients.
References dsp::FIR::Coefficients< NumericType >::coefficients, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<typename NumericType> double dsp::FIR::Coefficients< NumericType >::getMagnitudeForFrequency (double frequency, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency and sample rate.
template<typename NumericType> void dsp::FIR::Coefficients< NumericType >::getMagnitudeForFrequencyArray (double * frequencies, double * magnitudes, size_t numSamples, double sampleRate) const noexcept
Returns the magnitude frequency response of the filter for a given frequency array and sample rate.
template<typename NumericType> double dsp::FIR::Coefficients< NumericType >::getPhaseForFrequency (double frequency, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency and sample rate.
template<typename NumericType> void dsp::FIR::Coefficients< NumericType >::getPhaseForFrequencyArray (double * frequencies, double * phases, size_t numSamples, double sampleRate) const noexcept
Returns the phase frequency response of the filter for a given frequency array and sample rate.
template<typename NumericType> NumericType* dsp::FIR::Coefficients< NumericType >::getRawCoefficients () noexcept
Returns a raw data pointer to the coefficients.
References dsp::FIR::Coefficients< NumericType >::coefficients, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer().
template<typename NumericType> const NumericType* dsp::FIR::Coefficients< NumericType >::getRawCoefficients () const noexcept
Returns a raw data pointer to the coefficients.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin(), and dsp::FIR::Coefficients< NumericType >::coefficients.
template<typename NumericType> void dsp::FIR::Coefficients< NumericType >::normalise () noexcept
Scales the values of the FIR filter with the sum of the squared coefficients.
Member Data Documentation
template<typename NumericType> Array<NumericType> dsp::FIR::Coefficients< NumericType >::coefficients
The raw coefficients.
You should leave these numbers alone unless you really know what you're doing.
Referenced by dsp::FIR::Coefficients< NumericType >::getFilterOrder(), and dsp::FIR::Coefficients< NumericType >::getRawCoefficients().
The documentation for this struct was generated from the following file:
juce_FIRFilter.h