JUCE: juce::BlocksProtocol::BlockSerialNumber Struct Reference
juce::BlocksProtocol::BlockSerialNumber Struct Reference
Public Member Functions
bool isValid () const noexcept
bool isPadBlock () const noexcept
bool isLiveBlock () const noexcept
bool isLoopBlock () const noexcept
bool isDevCtrlBlock () const noexcept
bool isTouchBlock () const noexcept
bool isSeaboardBlock () const noexcept
bool isAnyControlBlock () const noexcept
bool hasPrefix (const char *prefix) const noexcept
Public Attributes
uint8 serial [16]
Member Function Documentation
bool juce::BlocksProtocol::BlockSerialNumber::isValid () const noexcept
References isAnyControlBlock(), isPadBlock(), isSeaboardBlock(), and serial.
bool juce::BlocksProtocol::BlockSerialNumber::isPadBlock () const noexcept
References hasPrefix().
Referenced by juce::BlocksProtocol::BlockDataSheet::BlockDataSheet(), and isValid().
bool juce::BlocksProtocol::BlockSerialNumber::isLiveBlock () const noexcept
References hasPrefix().
Referenced by juce::BlocksProtocol::BlockDataSheet::BlockDataSheet(), and isAnyControlBlock().
bool juce::BlocksProtocol::BlockSerialNumber::isLoopBlock () const noexcept
References hasPrefix().
Referenced by juce::BlocksProtocol::BlockDataSheet::BlockDataSheet(), and isAnyControlBlock().
bool juce::BlocksProtocol::BlockSerialNumber::isDevCtrlBlock () const noexcept
References hasPrefix().
Referenced by juce::BlocksProtocol::BlockDataSheet::BlockDataSheet(), and isAnyControlBlock().
bool juce::BlocksProtocol::BlockSerialNumber::isTouchBlock () const noexcept
References hasPrefix().
Referenced by juce::BlocksProtocol::BlockDataSheet::BlockDataSheet(), and isAnyControlBlock().
bool juce::BlocksProtocol::BlockSerialNumber::isSeaboardBlock () const noexcept
References hasPrefix().
Referenced by juce::BlocksProtocol::BlockDataSheet::BlockDataSheet(), and isValid().
bool juce::BlocksProtocol::BlockSerialNumber::isAnyControlBlock () const noexcept
References isDevCtrlBlock(), isLiveBlock(), isLoopBlock(), and isTouchBlock().
Referenced by isValid().
bool juce::BlocksProtocol::BlockSerialNumber::hasPrefix (const char * prefix) const noexcept
References serial.
Referenced by isDevCtrlBlock(), isLiveBlock(), isLoopBlock(), isPadBlock(), isSeaboardBlock(), and isTouchBlock().
Member Data Documentation
uint8 juce::BlocksProtocol::BlockSerialNumber::serial[16]
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTopologyDevice(), hasPrefix(), and isValid().
The documentation for this struct was generated from the following file:
juce_BlocksProtocolDefinitions.h