JUCE: juce::SpeakerMappings Struct Reference
juce::SpeakerMappings Struct Reference
format_types
Classes
struct Mapping
class VstSpeakerConfigurationHolder
Static Public Member Functions
static AudioChannelSet vstArrangementTypeToChannelSet (int32 arr, int fallbackNumChannels)
static AudioChannelSet vstArrangementTypeToChannelSet (const VstSpeakerConfiguration &arr)
static int32 channelSetToVstArrangementType (AudioChannelSet channels)
static const Mapping * getMappings () noexcept
static int32 getSpeakerType (AudioChannelSet::ChannelType type) noexcept
static AudioChannelSet::ChannelType getChannelType (int32 type) noexcept
Member Function Documentation
static AudioChannelSet juce::SpeakerMappings::vstArrangementTypeToChannelSet (int32 arr, int fallbackNumChannels) static
References juce::AudioChannelSet::addChannel(), juce::AudioChannelSet::create5point0(), juce::AudioChannelSet::create5point1(), juce::AudioChannelSet::create6point0(), juce::AudioChannelSet::create6point0Music(), juce::AudioChannelSet::create6point1(), juce::AudioChannelSet::create6point1Music(), juce::AudioChannelSet::create7point0(), juce::AudioChannelSet::create7point0SDDS(), juce::AudioChannelSet::create7point1(), juce::AudioChannelSet::create7point1SDDS(), juce::AudioChannelSet::createLCR(), juce::AudioChannelSet::createLCRS(), juce::AudioChannelSet::createLRS(), juce::AudioChannelSet::disabled(), juce::AudioChannelSet::discreteChannels(), getMappings(), juce::AudioChannelSet::mono(), juce::AudioChannelSet::quadraphonic(), juce::AudioChannelSet::stereo(), juce::SpeakerMappings::Mapping::vst2, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, and vstSpeakerConfigTypeMono.
Referenced by vstArrangementTypeToChannelSet().
static AudioChannelSet juce::SpeakerMappings::vstArrangementTypeToChannelSet (const VstSpeakerConfiguration & arr) static
References VstSpeakerConfiguration::numberOfChannels, VstSpeakerConfiguration::type, and vstArrangementTypeToChannelSet().
static int32 juce::SpeakerMappings::channelSetToVstArrangementType (AudioChannelSet channels) static
References juce::AudioChannelSet::create5point0(), juce::AudioChannelSet::create5point1(), juce::AudioChannelSet::create6point0(), juce::AudioChannelSet::create6point0Music(), juce::AudioChannelSet::create6point1(), juce::AudioChannelSet::create6point1Music(), juce::AudioChannelSet::create7point0(), juce::AudioChannelSet::create7point0SDDS(), juce::AudioChannelSet::create7point1(), juce::AudioChannelSet::create7point1SDDS(), juce::AudioChannelSet::createLCR(), juce::AudioChannelSet::createLCRS(), juce::AudioChannelSet::createLRS(), juce::AudioChannelSet::disabled(), juce::AudioChannelSet::getChannelTypes(), getMappings(), juce::AudioChannelSet::mono(), juce::AudioChannelSet::quadraphonic(), juce::AudioChannelSet::stereo(), juce::SpeakerMappings::Mapping::vst2, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeMono, and vstSpeakerConfigTypeUser.
Referenced by juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
static const Mapping* juce::SpeakerMappings::getMappings () static noexcept
References juce::AudioChannelSet::centre, juce::AudioChannelSet::left, juce::AudioChannelSet::leftCentre, juce::AudioChannelSet::leftSurround, juce::AudioChannelSet::leftSurroundRear, juce::AudioChannelSet::LFE, juce::AudioChannelSet::LFE2, juce::AudioChannelSet::right, juce::AudioChannelSet::rightCentre, juce::AudioChannelSet::rightSurround, juce::AudioChannelSet::rightSurroundRear, juce::AudioChannelSet::surround, juce::AudioChannelSet::topFrontCentre, juce::AudioChannelSet::topFrontLeft, juce::AudioChannelSet::topFrontRight, juce::AudioChannelSet::topRearLeft, juce::AudioChannelSet::topRearRight, juce::AudioChannelSet::unknown, vstSpeakerConfigTypeCLfe, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLcRc, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfe, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsCsSlSr, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsLcRcCs, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLfeLsRsTflTfcTfrTrlTrrLfe2, vstSpeakerConfigTypeLRCLfeS, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsCsSlSr, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsLcRcCs, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRs, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLfeS, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeLsRs, vstSpeakerConfigTypeMono, and vstSpeakerConfigTypeSlSr.
Referenced by channelSetToVstArrangementType(), and vstArrangementTypeToChannelSet().
static int32 juce::SpeakerMappings::getSpeakerType (AudioChannelSet::ChannelType type) static noexcept
References juce::AudioChannelSet::centre, juce::AudioChannelSet::left, juce::AudioChannelSet::leftCentre, juce::AudioChannelSet::leftSurround, juce::AudioChannelSet::leftSurroundRear, juce::AudioChannelSet::LFE, juce::AudioChannelSet::LFE2, juce::AudioChannelSet::right, juce::AudioChannelSet::rightCentre, juce::AudioChannelSet::rightSurround, juce::AudioChannelSet::rightSurroundRear, juce::AudioChannelSet::surround, juce::AudioChannelSet::topFrontCentre, juce::AudioChannelSet::topFrontLeft, juce::AudioChannelSet::topFrontRight, juce::AudioChannelSet::topMiddle, juce::AudioChannelSet::topRearCentre, juce::AudioChannelSet::topRearLeft, juce::AudioChannelSet::topRearRight, vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLFE2, vstIndividualSpeakerTypeRight, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeRightSurround, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontLeft, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopRearCentre, vstIndividualSpeakerTypeTopRearLeft, and vstIndividualSpeakerTypeTopRearRight.
Referenced by juce::SpeakerMappings::VstSpeakerConfigurationHolder::VstSpeakerConfigurationHolder().
static AudioChannelSet::ChannelType juce::SpeakerMappings::getChannelType (int32 type) static noexcept
References juce::AudioChannelSet::centre, juce::AudioChannelSet::left, juce::AudioChannelSet::leftCentre, juce::AudioChannelSet::leftSurround, juce::AudioChannelSet::leftSurroundRear, juce::AudioChannelSet::LFE, juce::AudioChannelSet::LFE2, juce::AudioChannelSet::right, juce::AudioChannelSet::rightCentre, juce::AudioChannelSet::rightSurround, juce::AudioChannelSet::rightSurroundRear, juce::AudioChannelSet::surround, juce::AudioChannelSet::topFrontCentre, juce::AudioChannelSet::topFrontLeft, juce::AudioChannelSet::topFrontRight, juce::AudioChannelSet::topMiddle, juce::AudioChannelSet::topRearCentre, juce::AudioChannelSet::topRearLeft, juce::AudioChannelSet::topRearRight, juce::AudioChannelSet::unknown, vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLFE2, vstIndividualSpeakerTypeRight, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeRightSurround, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontLeft, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopRearCentre, vstIndividualSpeakerTypeTopRearLeft, and vstIndividualSpeakerTypeTopRearRight.
The documentation for this struct was generated from the following file:
juce_VSTCommon.h