JUCE: juce::CoreAudioLayouts Struct Reference
juce::CoreAudioLayouts Struct Reference
Static Public Member Functions
static AudioChannelSet fromCoreAudio (const AudioChannelLayout &layout)
Convert CoreAudio's native AudioChannelLayout to JUCE's AudioChannelSet.
static AudioChannelSet fromCoreAudio (AudioChannelLayoutTag layoutTag)
Convert CoreAudio's native AudioChannelLayoutTag to JUCE's AudioChannelSet.
static AudioChannelLayoutTag toCoreAudio (const AudioChannelSet &set)
Convert JUCE's AudioChannelSet to CoreAudio's AudioChannelLayoutTag.
static const Array
< AudioChannelLayoutTag > & getKnownCoreAudioTags ()
static Array
< AudioChannelSet::ChannelType > getCoreAudioLayoutChannels (const AudioChannelLayout &layout)
Convert CoreAudio's native AudioChannelLayout to an array of JUCE ChannelTypes.
static Array
< AudioChannelSet::ChannelType > getSpeakerLayoutForCoreAudioTag (AudioChannelLayoutTag tag)
Member Function Documentation
static AudioChannelSet juce::CoreAudioLayouts::fromCoreAudio (const AudioChannelLayout & layout) static
Convert CoreAudio's native AudioChannelLayout to JUCE's AudioChannelSet.
Note that this method cannot preserve the order of channels.
References juce::AudioChannelSet::channelSetWithChannels(), and getCoreAudioLayoutChannels().
static AudioChannelSet juce::CoreAudioLayouts::fromCoreAudio (AudioChannelLayoutTag layoutTag) static
Convert CoreAudio's native AudioChannelLayoutTag to JUCE's AudioChannelSet.
Note that this method cannot preserve the order of channels.
References juce::AudioChannelSet::channelSetWithChannels(), and getSpeakerLayoutForCoreAudioTag().
static AudioChannelLayoutTag juce::CoreAudioLayouts::toCoreAudio (const AudioChannelSet & set) static
Convert JUCE's AudioChannelSet to CoreAudio's AudioChannelLayoutTag.
Note that this method cannot preserve the order of channels.
References juce::AudioChannelSet::addChannel(), juce::numElementsInArray(), juce::AudioChannelSet::size(), and juce::AudioChannelSet::unknown.
static const Array<AudioChannelLayoutTag>& juce::CoreAudioLayouts::getKnownCoreAudioTags () static
static Array<AudioChannelSet::ChannelType> juce::CoreAudioLayouts::getCoreAudioLayoutChannels (const AudioChannelLayout & layout) static
Convert CoreAudio's native AudioChannelLayout to an array of JUCE ChannelTypes.
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addIfNotAlreadyThere(), juce::AudioChannelSet::discreteChannel0, juce::AudioChannelSet::discreteChannels(), juce::AudioChannelSet::fromWaveChannelMask(), juce::AudioChannelSet::getChannelTypes(), getSpeakerLayoutForCoreAudioTag(), and juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by fromCoreAudio().
static Array<AudioChannelSet::ChannelType> juce::CoreAudioLayouts::getSpeakerLayoutForCoreAudioTag (AudioChannelLayoutTag tag) static
References juce::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), juce::AudioChannelSet::discreteChannel0, jassert, juce::numElementsInArray(), and juce::AudioChannelSet::unknown.
Referenced by fromCoreAudio(), and getCoreAudioLayoutChannels().
The documentation for this struct was generated from the following file:
juce_mac_CoreAudioLayouts.h