JUCE: juce::BlocksProtocol::IntegerWithBitSize< numBits > Struct Template Reference
juce::BlocksProtocol::IntegerWithBitSize< numBits > Struct Template Reference
Public Types
enum { bits = numBits, maxValue = static_cast<uint32> ((1ULL << numBits) - 1ULL) }
Public Member Functions
IntegerWithBitSize () noexcept=default
IntegerWithBitSize (const IntegerWithBitSize &) noexcept=default
IntegerWithBitSize & operator= (const IntegerWithBitSize &) noexcept=default
IntegerWithBitSize (uint32 v) noexcept
operator uint32 () const noexcept
uint32 get () const noexcept
uint8 getScaledToByte () const noexcept
float toUnipolarFloat () const noexcept
float toBipolarFloat () const noexcept
Static Public Member Functions
static IntegerWithBitSize fromUnipolarFloat (float value) noexcept
static IntegerWithBitSize fromBipolarFloat (float value) noexcept
Public Attributes
uint32 value = 0
Member Enumeration Documentation
template<int numBits> anonymous enum
Enumerator
bits
maxValue
Constructor & Destructor Documentation
template<int numBits> juce::BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize () default noexcept
Referenced by juce::BlocksProtocol::IntegerWithBitSize< 8 >::fromBipolarFloat(), and juce::BlocksProtocol::IntegerWithBitSize< 8 >::fromUnipolarFloat().
template<int numBits> juce::BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize (const IntegerWithBitSize< numBits > &) default noexcept
template<int numBits> juce::BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize (uint32 v) noexcept
Member Function Documentation
template<int numBits> IntegerWithBitSize& juce::BlocksProtocol::IntegerWithBitSize< numBits >::operator= (const IntegerWithBitSize< numBits > &) default noexcept
template<int numBits> juce::BlocksProtocol::IntegerWithBitSize< numBits >::operator uint32 () const noexcept
template<int numBits> uint32 juce::BlocksProtocol::IntegerWithBitSize< numBits >::get () const noexcept
Referenced by juce::BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleConfigMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage(), juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), and juce::BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity().
template<int numBits> uint8 juce::BlocksProtocol::IntegerWithBitSize< numBits >::getScaledToByte () const noexcept
template<int numBits> float juce::BlocksProtocol::IntegerWithBitSize< numBits >::toUnipolarFloat () const noexcept
template<int numBits> float juce::BlocksProtocol::IntegerWithBitSize< numBits >::toBipolarFloat () const noexcept
template<int numBits> static IntegerWithBitSize juce::BlocksProtocol::IntegerWithBitSize< numBits >::fromUnipolarFloat (float value) static noexcept
template<int numBits> static IntegerWithBitSize juce::BlocksProtocol::IntegerWithBitSize< numBits >::fromBipolarFloat (float value) static noexcept
Member Data Documentation
template<int numBits> uint32 juce::BlocksProtocol::IntegerWithBitSize< numBits >::value = 0
Referenced by juce::BlocksProtocol::IntegerWithBitSize< 8 >::get(), and juce::BlocksProtocol::IntegerWithBitSize< 8 >::operator uint32().
The documentation for this struct was generated from the following file:
juce_BitPackingUtilities.h